/**
 * 고1 듣기 11회 — 사람이 직접 쓴 회차 (2026-09-21)
 *
 * 기존 1~10회는 변형으로 만들어 소재가 많이 겹쳤다(7번은 여섯 회차가 "요리 모임",
 * 5번은 거의 전 회차가 "Could you also email…? / Got it."). 여기서는 상황·소재·문장 틀을
 * 모두 다르게 잡았다.
 */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "고1 듣기 11회",
  gradeLevel: "high1",
  speechSpeed: 0.8,
  folder: "고1 듣기",
  questions: [
    {
      order: 1,
      type: "목적 파악",
      instruction: "다음을 듣고, 여자가 하는 말의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good afternoon, students. This is the school nurse, Ms. Han."],
        ["W", "As the weather turns cold, more of you are coming to the health room with headaches."],
        ["W", "In almost every case, the cause is the same: you are not drinking enough water."],
        ["W", "The heaters run all day now, and the air in the classrooms dries out very quickly."],
        ["W", "So please bring a water bottle and fill it at the fountain between classes."],
        ["W", "Small sips through the day work far better than one large drink at lunch."],
        ["W", "Try this for a week, and I think you will notice the difference yourselves."],
      ],
      choices: [
        "수업 중 물을 자주 마시도록 권하려고",
        "난방기 사용 시간을 줄이자고 요청하려고",
        "보건실 이용 절차의 변경을 알리려고",
        "겨울철 독감 예방 접종을 안내하려고",
        "교실 환기 당번을 새로 정하려고",
      ],
      answer: 1,
      clue: "So please bring a water bottle and fill it at the fountain between classes.",
      explanation:
        "여자는 난방 때문에 공기가 건조해져 두통이 늘었다며, 물병을 가지고 다니며 수업 사이사이에 물을 채워 조금씩 자주 마시라고 권하고 있다. 따라서 말의 목적은 ①이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 보건 선생님 한○○입니다.",
        "W: 날씨가 추워지면서 두통으로 보건실에 오는 학생이 늘고 있습니다.",
        "W: 거의 모든 경우 원인은 같습니다. 물을 충분히 마시지 않는 것입니다.",
        "W: 요즘은 난방기가 하루 종일 돌아가서 교실 공기가 아주 빨리 건조해집니다.",
        "W: 그러니 물병을 가지고 다니면서 쉬는 시간에 정수기에서 물을 채워 두세요.",
        "W: 점심때 한 번에 많이 마시는 것보다 하루 종일 조금씩 마시는 편이 훨씬 낫습니다.",
        "W: 일주일만 해 보면 여러분 스스로 차이를 느낄 수 있을 거예요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "의견 파악",
      instruction: "대화를 듣고, 남자의 의견으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjae, you write down every book you read. Isn't that a lot of work?"],
        ["M", "It takes about five minutes, but it changes how I read."],
        ["W", "Really? I thought a reading log was just a record."],
        ["M", "Mine isn't a list. I write one sentence about what I disagreed with."],
        ["W", "Why the part you disagreed with, not the part you liked?"],
        ["M", "Because that's the only part I have to think about on my own."],
        ["W", "Hmm. So the writing is where the reading actually happens."],
        ["M", "Exactly. Without it, I finish a book and forget it in a week."],
      ],
      choices: [
        "책은 끝까지 읽는 것이 중요하다.",
        "독서 기록은 읽은 책 목록으로 충분하다.",
        "동의하지 않는 부분을 써 보면 독서가 깊어진다.",
        "독서 습관은 친구와 함께 기를 때 오래간다.",
        "책을 고르는 데 시간을 충분히 들여야 한다.",
      ],
      answer: 3,
      clue: "I write one sentence about what I disagreed with.",
      explanation:
        "남자는 읽은 책의 목록을 적는 것이 아니라 '동의하지 않은 부분'을 한 문장으로 쓴다고 하며, 그 부분만이 스스로 생각해야 하는 지점이라고 말한다. 따라서 남자의 의견은 ③이다.",
      translation: [
        "W: 민재야, 너 읽은 책을 전부 적어 두더라. 그거 일 많지 않아?",
        "M: 5분쯤 걸리는데, 읽는 방식이 달라져.",
        "W: 정말? 독서 기록은 그냥 기록인 줄 알았는데.",
        "M: 내 건 목록이 아니야. 동의하지 않은 부분을 한 문장으로 써.",
        "W: 왜 좋았던 부분이 아니라 동의하지 않은 부분이야?",
        "M: 그 부분만이 내가 스스로 생각해야 하는 데니까.",
        "W: 음, 그럼 쓰는 순간에 진짜 읽기가 일어나는 거네.",
        "M: 맞아. 그거 없으면 책 다 읽고 일주일이면 잊어버려.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "요지 파악",
      instruction: "다음을 듣고, 남자가 하는 말의 요지로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "When you practice an instrument, the hard part is never the whole piece."],
        ["M", "It is usually two or three measures that keep falling apart."],
        ["M", "Most students play from the beginning again whenever they make a mistake."],
        ["M", "That feels like practice, but it mostly repeats what you already do well."],
        ["M", "Instead, cut out the difficult measures and play only those, very slowly."],
        ["M", "Speed up only after you can play them five times without an error."],
        ["M", "Ten minutes spent this way beats an hour of playing the piece from the top."],
      ],
      choices: [
        "악기 연습은 매일 같은 시간에 해야 한다.",
        "연습 시간을 늘릴수록 실력이 고르게 는다.",
        "곡 전체를 자주 들어 보아야 이해가 깊어진다.",
        "실수했을 때는 처음부터 다시 치는 것이 좋다.",
        "어려운 부분만 떼어 느리게 반복하는 것이 효과적이다.",
      ],
      answer: 5,
      clue: "Instead, cut out the difficult measures and play only those, very slowly.",
      explanation:
        "남자는 실수할 때마다 처음부터 다시 치는 습관은 이미 잘하는 부분만 반복하는 것이라며, 어려운 두세 마디만 떼어 아주 느리게 연습하라고 말한다. 따라서 요지는 ⑤이다.",
      translation: [
        "M: 악기를 연습할 때 어려운 건 곡 전체가 아닙니다.",
        "M: 보통은 자꾸 무너지는 두세 마디입니다.",
        "M: 많은 학생이 실수할 때마다 처음부터 다시 칩니다.",
        "M: 연습처럼 느껴지지만, 사실은 이미 잘하는 부분을 반복하는 것입니다.",
        "M: 대신 어려운 마디만 떼어 내서 아주 느리게 쳐 보세요.",
        "M: 실수 없이 다섯 번 칠 수 있게 된 다음에야 속도를 올리세요.",
        "M: 이렇게 쓴 10분이 처음부터 한 시간 치는 것보다 낫습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "그림 불일치",
      instruction: "대화를 듣고, 그림에서 대화의 내용과 일치하지 않는 것을 고르시오.",
      lines: [
        ["M", "Yuna, the school garden corner is ready. It looks tidy."],
        ["W", "Thanks. I want visitors to understand it at a glance."],
        ["M", "On the wall at the back there's a wide sign with a leaf shape in the middle."],
        ["W", "Right, that shows the club's theme. It's the first thing people see."],
        ["M", "On the left shelf, three clay pots are lined up."],
        ["W", "Those hold the seedlings we started in March."],
        ["M", "In the middle of the table there's a watering can with a long spout."],
        ["W", "Yes, the long spout reaches the back row without spilling."],
        ["M", "And by the stool, is that a rake leaning on the wall?"],
        ["W", "No, it's a shovel. We keep the rake in the shed."],
        ["M", "I see. On the right, two garden gloves are hanging from a hook."],
        ["W", "Good. Then we're ready for the visitors tomorrow."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, it's a shovel. We keep the rake in the shed.",
      explanation:
        "여자가 의자 옆에 기대어 놓은 것은 갈퀴가 아니라 삽이라고 바로잡는다. 그림에는 갈퀴가 그려져 있으므로 ④가 대화 내용과 일치하지 않는다.",
      figure: {
        kind: "labeled",
        scene:
          "A school gardening corner seen from the front, five things clearly separated. " +
          "Upper centre on the back wall: a wide blank sign with a single leaf shape drawn in its middle. " +
          "Left shelf: three clay pots lined up, each with a small seedling. " +
          "Centre of the table: a watering can with a long slender spout. " +
          "Leaning against the wall beside a round stool: a garden RAKE with a fan of teeth. " +
          "Right wall: two gardening gloves hanging from a hook.",
      },
      translation: [
        "M: 유나야, 학교 정원 코너 다 됐네. 깔끔하다.",
        "W: 고마워. 오는 사람들이 한눈에 알아봤으면 해서.",
        "M: 뒤쪽 벽에 가운데 잎 모양이 있는 넓은 안내판이 있네.",
        "W: 응, 동아리 주제를 보여 주는 거야. 사람들이 제일 먼저 보게 되지.",
        "M: 왼쪽 선반에는 토분 세 개가 나란히 있고.",
        "W: 3월에 심은 모종들이 들어 있어.",
        "M: 탁자 가운데에는 주둥이가 긴 물뿌리개가 있네.",
        "W: 응, 주둥이가 길어서 흘리지 않고 뒷줄까지 닿아.",
        "M: 그리고 의자 옆에 벽에 기대 둔 건 갈퀴야?",
        "W: 아니야, 삽이야. 갈퀴는 창고에 둬.",
        "M: 그렇구나. 오른쪽에는 원예용 장갑 두 짝이 고리에 걸려 있네.",
        "W: 좋아. 그럼 내일 손님 맞을 준비는 끝났다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "할 일",
      instruction: "대화를 듣고, 여자가 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, the science fair is Saturday and we still don't have a poster board."],
        ["W", "I thought the club had two left over from last year."],
        ["M", "They're warped. I checked the storage room this morning."],
        ["W", "Then someone has to buy one before the stationery shop closes."],
        ["M", "I can't. I have to finish the data table and print the graphs tonight."],
        ["W", "Fine. The shop is on my way home, so I'll stop by and get one."],
        ["M", "Thanks. Get the thick kind — the thin ones bend when we tape things on."],
        ["W", "Got it. I'll bring it to the lab tomorrow morning."],
      ],
      choices: ["자료 표 정리하기", "그래프 인쇄하기", "게시판 구입하기", "창고 정리하기", "실험실 예약하기"],
      answer: 3,
      clue: "The shop is on my way home, so I'll stop by and get one.",
      explanation:
        "남자는 자료 표와 그래프를 맡고, 여자는 집에 가는 길에 문구점에 들러 두꺼운 게시판을 사 오겠다고 말한다. 따라서 여자가 할 일은 ③이다.",
      translation: [
        "M: 서연아, 과학전이 토요일인데 게시판이 아직 없어.",
        "W: 작년에 쓰고 남은 게 두 장 있는 줄 알았는데.",
        "M: 휘었더라. 오늘 아침에 창고 확인했어.",
        "W: 그럼 문구점 닫기 전에 누가 사 와야겠네.",
        "M: 난 못 가. 오늘 밤에 자료 표 마무리하고 그래프도 뽑아야 해.",
        "W: 알겠어. 문구점이 우리 집 가는 길이니까 내가 들러서 사 올게.",
        "M: 고마워. 두꺼운 걸로 사. 얇은 건 뭘 붙이면 휘어.",
        "W: 알겠어. 내일 아침에 실험실로 가져갈게.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "금액 계산",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the Riverside Pottery Studio. Are you joining a class today?"],
        ["M", "Yes, the two-hour beginner class. It's for me and my younger brother."],
        ["W", "The beginner class is twenty dollars per person."],
        ["M", "Okay. And do we pay extra for the clay?"],
        ["W", "One bag of clay is five dollars, and each person needs one bag."],
        ["M", "Then two classes and two bags of clay, please."],
        ["W", "Certainly. And students get ten percent off the total."],
        ["M", "Great, my brother and I both have student cards."],
        ["W", "Then I'll take ten percent off everything. Here's your receipt."],
      ],
      choices: ["$40", "$45", "$50", "$54", "$60"],
      answer: 2,
      clue: "Then I'll take ten percent off everything.",
      explanation:
        "수업은 한 사람 20달러씩 두 명이라 40달러, 점토는 한 봉지 5달러씩 두 봉지라 10달러로 합계 50달러이다. 두 사람 모두 학생증이 있어 전체에서 10%를 빼므로 50 × 0.9 = 45달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 리버사이드 도예 공방에 오신 것을 환영합니다. 오늘 수업 들으시나요?",
        "M: 네, 두 시간짜리 초보 수업이요. 저랑 제 동생이요.",
        "W: 초보 수업은 한 사람에 20달러입니다.",
        "M: 알겠습니다. 점토는 따로 내야 하나요?",
        "W: 점토 한 봉지에 5달러이고, 한 사람당 한 봉지가 필요합니다.",
        "M: 그럼 수업 둘, 점토 두 봉지 주세요.",
        "W: 네. 그리고 학생은 전체 금액에서 10% 할인됩니다.",
        "M: 잘됐네요. 저랑 동생 둘 다 학생증 있어요.",
        "W: 그럼 전체에서 10% 빼 드릴게요. 영수증 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "이유 파악",
      instruction: "대화를 듣고, 여자가 사진 동아리 전시를 미루려는 이유를 고르시오.",
      lines: [
        ["M", "Dahye, I heard you want to move the photo club exhibition to December."],
        ["W", "Yes. I talked with the club members yesterday."],
        ["M", "Is it because the prints haven't arrived yet?"],
        ["W", "No, they came last Friday. They look better than I expected."],
        ["M", "Then is the hallway being used for something else?"],
        ["W", "The hallway is free. The problem is the lighting."],
        ["M", "The lighting? I thought the new lamps were installed last month."],
        ["W", "They were, but half of them face the wrong way, and the photos look flat."],
        ["M", "So you need time to have them adjusted."],
        ["W", "Right. The maintenance team can only come in early December."],
      ],
      choices: [
        "인화한 사진이 아직 도착하지 않아서",
        "복도를 다른 행사에서 쓰고 있어서",
        "조명 방향을 고쳐야 해서",
        "동아리 회원이 부족해서",
        "전시 예산이 확정되지 않아서",
      ],
      answer: 3,
      clue: "half of them face the wrong way, and the photos look flat",
      explanation:
        "여자는 사진도 도착했고 복도도 비어 있지만, 새 조명의 절반이 엉뚱한 방향을 향해 사진이 밋밋해 보인다고 말한다. 조명을 고칠 사람이 12월 초에나 올 수 있어 전시를 미루려는 것이므로 답은 ③이다.",
      translation: [
        "M: 다혜야, 사진 동아리 전시를 12월로 옮기고 싶다고 들었어.",
        "W: 응. 어제 회원들이랑 이야기했어.",
        "M: 인화한 사진이 아직 안 와서 그래?",
        "W: 아니야, 지난 금요일에 왔어. 생각보다 잘 나왔더라.",
        "M: 그럼 복도를 다른 데서 쓰는 거야?",
        "W: 복도는 비어 있어. 문제는 조명이야.",
        "M: 조명? 지난달에 새 등을 달지 않았어?",
        "W: 달긴 했는데 절반이 엉뚱한 쪽을 보고 있어서 사진이 밋밋해 보여.",
        "M: 그래서 방향을 고칠 시간이 필요한 거구나.",
        "W: 맞아. 시설 담당이 12월 초에나 올 수 있대.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "미언급",
      instruction: "대화를 듣고, Winter Coding Camp에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Jiwon, have you seen the poster for the Winter Coding Camp?"],
        ["W", "I saw it this morning, but I didn't have time to read it properly."],
        ["M", "It runs for five days, from January eighth to the twelfth."],
        ["W", "That works for me. My family trip ends on the fifth."],
        ["M", "Good. It's in the third-floor computer lab, right next to the library."],
        ["W", "That's close to the bus stop, so getting there won't be a problem."],
        ["M", "And you don't have to carry anything. The school lends a laptop to each person."],
        ["W", "That's a relief. Mine is too heavy to bring every morning."],
        ["M", "One thing, though. Only twenty students can join the whole camp."],
        ["W", "Twenty? Then it will fill up in a day or two."],
        ["M", "Probably. I already put my name down during lunch."],
        ["W", "Then I'll fill out the form tonight before I forget."],
      ],
      choices: ["기간", "장소", "준비물", "참가 인원", "참가비"],
      answer: 5,
      clue: "Only twenty students can join the whole camp.",
      explanation:
        "기간(1월 8일~12일), 장소(3층 컴퓨터실), 준비물(노트북은 학교에서 빌려 줌), 참가 인원(20명)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 지원아, 겨울 코딩 캠프 신청할 거야?",
        "W: 하고 싶어. 언제 해?",
        "M: 1월 8일부터 12일까지 닷새 동안.",
        "W: 나는 괜찮네. 어디서 해?",
        "M: 3층 컴퓨터실에서. 도서관 바로 옆이야.",
        "W: 좋다. 노트북은 각자 가져가야 해?",
        "M: 아니, 학교에서 참가자마다 한 대씩 빌려 줘.",
        "W: 다행이다. 몇 명까지 들을 수 있어?",
        "M: 스무 명뿐이라 일찍 신청하는 게 좋아.",
        "W: 그럼 오늘 밤에 신청서 쓸게.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "내용 불일치",
      instruction:
        "Green Roof Volunteer Day에 관한 다음 내용을 듣고, 일치하지 않는 것을 고르시오.",
      lines: [
        ["W", "Let me tell you about this year's Green Roof Volunteer Day."],
        ["W", "It will be held on the last Saturday of November, from nine to one."],
        ["W", "Volunteers will plant herbs in the boxes on the school's rooftop garden."],
        ["W", "Gloves and tools are provided, so you only need to bring a water bottle."],
        ["W", "Because the roof gets windy, we will stop the work if it rains."],
        ["W", "Every volunteer receives four hours of service credit."],
        ["W", "Sign up at the front office by Wednesday of that week."],
      ],
      choices: [
        "11월 마지막 주 토요일에 열린다.",
        "옥상 정원의 화단에 허브를 심는다.",
        "장갑과 도구는 각자 준비해야 한다.",
        "비가 오면 작업을 중단한다.",
        "봉사 시간 4시간이 인정된다.",
      ],
      answer: 3,
      clue: "Gloves and tools are provided, so you only need to bring a water bottle.",
      explanation:
        "장갑과 도구는 제공되며 참가자는 물병만 가져오면 된다고 했으므로, 각자 준비해야 한다는 ③이 내용과 일치하지 않는다.",
      translation: [
        "W: 올해 그린 루프 봉사의 날에 대해 알려 드리겠습니다.",
        "W: 11월 마지막 주 토요일 아홉 시부터 한 시까지 진행됩니다.",
        "W: 봉사자들은 학교 옥상 정원의 화단에 허브를 심게 됩니다.",
        "W: 장갑과 도구는 제공되니 물병만 가져오시면 됩니다.",
        "W: 옥상은 바람이 많이 불기 때문에 비가 오면 작업을 중단합니다.",
        "W: 봉사자에게는 4시간의 봉사 시간이 인정됩니다.",
        "W: 신청은 그 주 수요일까지 교무실에서 받습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "표 선택",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 신청할 방과 후 강좌를 고르시오.",
      lines: [
        ["W", "Minho, the after-school list came out. Let's pick one and take it together."],
        ["M", "Sure. There are five courses open this term, right?"],
        ["W", "Right, all five are on this sheet. Is any day impossible for you?"],
        ["M", "Monday is out. I tutor a neighbour's son every Monday evening."],
        ["W", "Then we cross that one off. I also have a limit on what I can pay."],
        ["M", "How much were you thinking?"],
        ["W", "I'd rather not pay more than thirty dollars for the whole course."],
        ["M", "That still leaves a few. What about how long each course runs?"],
        ["W", "Anything over eight weeks runs into the exam period, so let's stay under that."],
        ["M", "Then only two are left, and one of them charges a separate materials fee."],
        ["W", "Let's take the one where the materials are included, then."],
        ["M", "Agreed. I'll sign us both up tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Let's take the one where the materials are included, then.",
      explanation:
        "월요일 강좌(①)를 빼고, 30달러를 넘는 강좌(②)를 빼고, 8주가 넘는 강좌(③)를 뺀다. 남은 ④와 ⑤ 중 재료비가 포함된 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "월요일 / 25달러 / 6주 / 재료비 포함" },
          { no: 2, label: "②", value: "화요일 / 35달러 / 6주 / 재료비 포함" },
          { no: 3, label: "③", value: "수요일 / 28달러 / 10주 / 재료비 포함" },
          { no: 4, label: "④", value: "목요일 / 28달러 / 6주 / 재료비 포함" },
          { no: 5, label: "⑤", value: "금요일 / 26달러 / 7주 / 재료비 별도" },
        ],
      },
      translation: [
        "W: 민호야, 방과 후 강좌 같이 고르자. 열린 건 이 다섯 개야.",
        "M: 월요일 건 빼자. 그때 과외 아르바이트가 있어.",
        "W: 알겠어. 그리고 30달러 넘는 건 안 했으면 좋겠어.",
        "M: 그래도 몇 개 남네. 기간은 어때?",
        "W: 8주 넘어가면 시험 기간이랑 겹치니까 그 아래로 하자.",
        "M: 그럼 둘 남았다. 하나는 재료비가 따로 없네.",
        "W: 좋아, 재료비 포함된 걸로 하자.",
        "M: 그러자. 내일 내가 둘 다 신청할게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "짧은 응답",
      instruction:
        "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Did you hand in the bus pass application on time?"],
        ["M", "I did, but I left the photo section completely empty."],
        ["W", "Didn't you bring a picture with you that morning?"],
        ["M", "No, and I wasn't sure whether they would still take it later."],
        ["W", "They will. You can add the photo at the office any time until Friday."],
      ],
      choices: [
        "Then I'll drop by tomorrow with a photo.",
        "I already returned my old bus pass.",
        "The office moved to the second floor last year.",
        "I didn't know the bus route had changed.",
        "You should apply before the deadline passes.",
      ],
      answer: 1,
      clue: "You can add the photo at the office any time until Friday.",
      questionText: "▶ Man : ________________",
      explanation:
        "사진 칸을 비워 냈다는 남자에게 여자가 금요일까지 사무실에서 사진을 추가할 수 있다고 알려 주었으므로, 사진을 가지고 들르겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 버스 정기권 신청서 제때 냈어?",
        "M: 내긴 했는데 사진 칸을 비워 뒀어.",
        "W: 금요일까지는 사무실에서 사진을 넣을 수 있어.",
        "M: 그럼 내일 사진 가지고 들를게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "짧은 응답",
      instruction:
        "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Are you still looking for someone to swap shifts with on Sunday?"],
        ["W", "Yes, but nobody in our group is free that day."],
        ["M", "Did you write it on the board in the break room?"],
        ["W", "I did, and it's been up there for three days with no answer."],
        ["M", "Then have you asked the Saturday team? They usually have room."],
      ],
      choices: [
        "I finished my shift an hour early.",
        "Sunday is the busiest day of the week.",
        "The schedule is posted every Monday morning.",
        "No, I hadn't thought of them. I'll ask today.",
        "I'd rather not work two days in a row.",
      ],
      answer: 4,
      clue: "Have you asked the Saturday team? They usually have room.",
      questionText: "▶ Woman : ________________",
      explanation:
        "토요일 팀에게 물어봤느냐는 제안에 대해, 생각 못 했다며 오늘 물어보겠다는 ④가 가장 자연스러운 응답이다.",
      translation: [
        "M: 일요일에 근무 바꿔 줄 사람 아직 찾고 있어?",
        "W: 응, 그런데 우리 조에는 그날 시간 되는 사람이 없어.",
        "M: 토요일 조에는 물어봤어? 거긴 보통 여유가 있던데.",
        "W: 아니, 거긴 생각 못 했네. 오늘 물어볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "긴 응답",
      instruction:
        "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sora, I timed your part of the group presentation last night."],
        ["W", "How long did it come out? I felt like it was getting long."],
        ["M", "Almost nine minutes, and that was without the questions at the end."],
        ["W", "That's more than I expected. Every slide feels necessary when I look at it."],
        ["M", "I understand, but we only have twelve minutes for all four of us."],
        ["W", "Twelve for four people? Then I'm taking most of the time by myself."],
        ["M", "You are. The rest of us would have one minute each."],
        ["W", "So you're saying I should cut about half of what I prepared."],
        ["M", "Not exactly. I don't want you to lose the good parts."],
        ["W", "Then which parts would you keep?"],
        ["M", "Keep the examples and drop the background history at the beginning."],
      ],
      choices: [
        "Then I'll rewrite the whole presentation tonight.",
        "I'd rather present first so I don't run out of time.",
        "That makes sense — the examples are what people remember.",
        "We should ask the teacher for four more minutes.",
        "I'll add two more slides about the background.",
      ],
      answer: 3,
      clue: "Keep the examples and drop the background history.",
      questionText: "▶ Woman : ________________",
      explanation:
        "남자가 예시는 남기고 배경 설명을 덜어 내라고 조언했으므로, 사람들이 기억하는 건 예시라며 수긍하는 ③이 가장 적절하다.",
      translation: [
        "M: 소라야, 네 발표 분량이 9분 가까이 돼.",
        "W: 알아. 볼 때마다 슬라이드가 다 필요해 보여서.",
        "M: 우리 네 명이 다 합쳐서 12분밖에 없어.",
        "W: 그러니까 내 걸 절반쯤 줄이라는 거지.",
        "M: 꼭 그런 건 아니야. 예시는 두고 배경 설명을 빼.",
        "W: 그 말이 맞네. 사람들이 기억하는 건 예시니까.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "긴 응답",
      instruction:
        "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaeho, you've been running every morning for three months now, haven't you?"],
        ["M", "Almost every morning, yes. But lately my knees hurt on the way home."],
        ["W", "Both knees, or just one?"],
        ["M", "Both, and it starts about twenty minutes in."],
        ["W", "Did you change anything recently? Your shoes, your pace, your route?"],
        ["M", "My shoes are the same pair, and I run at the same speed as before."],
        ["W", "Then what about the route?"],
        ["M", "I did change that. I started running down the hill behind the school."],
        ["W", "That's probably it. Downhill puts much more strain on the knees than flat ground does."],
      ],
      choices: [
        "Then I'll buy a new pair of running shoes this weekend.",
        "Maybe I should run twice as far each morning.",
        "I didn't know running in the morning was better.",
        "My knees have never bothered me before this year.",
        "I'll go back to the flat course by the river, then.",
      ],
      answer: 5,
      clue: "Downhill puts much more strain on the knees than flat ground does.",
      questionText: "▶ Man : ________________",
      explanation:
        "내리막이 평지보다 무릎에 훨씬 부담이 된다는 말을 들었으므로, 강가의 평평한 길로 돌아가겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 재호야, 너 석 달째 매일 아침 달리고 있네.",
        "M: 응, 그런데 요즘 집에 오는 길에 무릎이 아파.",
        "W: 뭔가 바꾼 거 있어? 코스나 속도, 신발 같은 거.",
        "M: 코스만. 학교 뒤 언덕을 내려오는 길로 바꿨어.",
        "W: 내리막은 평지보다 무릎에 훨씬 무리가 가.",
        "M: 그럼 강가 평평한 코스로 돌아가야겠다.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "상황 발화",
      instruction:
        "다음 상황 설명을 듣고, Nara가 Taeho에게 할 말로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Nara and Taeho have been on the same school debate team since March."],
        ["W", "Taeho reads widely and builds arguments that are hard to answer."],
        ["W", "When he is nervous, though, his speaking speed doubles without him noticing."],
        ["W", "At last month's match, two of the three judges wrote the same comment."],
        ["W", "They said they simply could not follow his final point, even though it was strong."],
        ["W", "Tomorrow the team faces a school that beat them badly last year."],
        ["W", "Nara has read Taeho's script twice and thinks the content is already good enough to win."],
        ["W", "She does not want him to add anything or change his argument the night before."],
        ["W", "She believes the one thing that will help is slowing down so the judges can follow him."],
        ["W", "In this situation, what would Nara most likely say to Taeho?"],
      ],
      choices: [
        "You should add one more example to your argument.",
        "Try speaking a little slower so the judges can follow you.",
        "Let's switch the order of our speakers tomorrow.",
        "We need to practice the opening statement again.",
        "Don't worry about what the judges wrote last time.",
      ],
      answer: 2,
      questionText: "▶ Nara : ________________",
      clue: "She believes the one thing that will help is slowing down so the judges can follow him.",
      explanation:
        "나라는 태호의 내용은 이미 충분하다고 보고, 심사위원이 따라올 수 있도록 말을 조금 천천히 하라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 나라와 태호는 같은 학교 토론 팀입니다.",
        "W: 태호는 논거가 탄탄하지만 긴장하면 말이 아주 빨라집니다.",
        "W: 지난 경기에서 심사위원 두 명이 그의 마지막 논점을 따라가지 못했다고 했습니다.",
        "W: 내일 팀은 다른 학교와 중요한 경기를 치릅니다.",
        "W: 나라는 태호의 원고를 두 번 읽어 보고 내용은 이미 이길 만하다고 생각합니다.",
        "W: 경기 전날에 무언가를 더하거나 논지를 바꾸게 하고 싶지는 않습니다.",
        "W: 심사위원이 따라올 수 있도록 말을 천천히 하는 것 하나면 된다고 봅니다.",
        "W: 이런 상황에서 나라가 태호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
    {
      order: 16,
      type: "주제",
      instruction: "남자가 하는 말의 주제로 가장 적절한 것은?",
      lines: [
        ["M", "Good morning. Today I want to talk about foods people eat before a long walk."],
        ["M", "Many hikers reach for a chocolate bar, and it does give quick energy."],
        ["M", "But that energy runs out after about forty minutes, and then you feel worse."],
        ["M", "Bananas are better because they release their sugar more slowly."],
        ["M", "Boiled eggs carry protein that keeps you full on a long climb."],
        ["M", "Dried dates are light and easy to eat while you are still walking."],
        ["M", "Whole-grain bread digests slowly and works well an hour before you start."],
        ["M", "None of these are special hiking foods — they are just ordinary things chosen well."],
      ],
      choices: [
        "the right way to drink water while hiking",
        "everyday foods to eat before a long hike",
        "harmful effects of eating too much chocolate",
        "how to choose hiking gear for beginners",
        "ways to reduce trash left on mountain trails",
      ],
      answer: 2,
      clue: "Today I want to talk about foods people eat before a long walk.",
      explanation:
        "남자는 긴 산행 전에 먹는 음식으로 바나나, 삶은 달걀, 말린 대추야자, 통밀빵을 소개하며 초콜릿과 비교한다. 따라서 주제는 ②이다.",
      translation: [
        "M: 안녕하세요. 오늘은 긴 산행 전에 먹는 음식에 대해 이야기하겠습니다.",
        "M: 많은 등산객이 초콜릿 바를 집는데, 빠르게 힘이 나는 건 맞습니다.",
        "M: 하지만 그 힘은 40분쯤 지나면 떨어지고, 그 뒤엔 더 힘들어집니다.",
        "M: 바나나는 당이 더 천천히 나오기 때문에 낫습니다.",
        "M: 삶은 달걀은 단백질이 있어 긴 오르막에서 든든합니다.",
        "M: 말린 대추야자는 가볍고 걸으면서도 먹기 좋습니다.",
        "M: 통밀빵은 천천히 소화되어 출발 한 시간 전에 먹기 좋습니다.",
        "M: 이 중에 특별한 등산 식품은 없습니다. 평범한 것을 잘 고른 것뿐입니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "언급 여부",
      instruction: "언급된 음식이 아닌 것은?",
      lines: [
        ["M", "Good morning. Today I want to talk about foods people eat before a long walk."],
        ["M", "Many hikers reach for a chocolate bar, and it does give quick energy."],
        ["M", "But that energy runs out after about forty minutes, and then you feel worse."],
        ["M", "Bananas are better because they release their sugar more slowly."],
        ["M", "Boiled eggs carry protein that keeps you full on a long climb."],
        ["M", "Dried dates are light and easy to eat while you are still walking."],
        ["M", "Whole-grain bread digests slowly and works well an hour before you start."],
        ["M", "None of these are special hiking foods — they are just ordinary things chosen well."],
      ],
      choices: ["bananas", "boiled eggs", "dried dates", "whole-grain bread", "roasted nuts"],
      answer: 5,
      clue: "Bananas ... Boiled eggs ... Dried dates ... Whole-grain bread",
      explanation:
        "바나나, 삶은 달걀, 말린 대추야자, 통밀빵은 언급되지만 구운 견과류는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: "16번과 같은 담화입니다.",
    },
  ],
};
