/** 고1 듣기 12회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "고1 듣기 12회",
  gradeLevel: "high1",
  speechSpeed: 0.8,
  folder: "고1 듣기",
  questions: [
    {
      order: 1,
      type: "목적 파악",
      instruction: "다음을 듣고, 남자가 하는 말의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Attention, everyone. This is the student council president speaking."],
        ["M", "I want to say something about the lost and found box near the main entrance."],
        ["M", "Right now, we keep every item there until the end of the semester."],
        ["M", "As a result, the box is full of gloves and water bottles from last spring."],
        ["M", "Starting next Monday, we will keep items for four weeks only."],
        ["M", "After that, anything left will be donated to a local charity."],
        ["M", "So if you have lost something this month, please come and check the box this week."],
        ["M", "The council will be there every lunchtime to help you look."],
      ],
      choices: [
        "분실물 보관 기간의 변경을 알리려고",
        "분실물 보관함의 위치를 안내하려고",
        "학생회 임원 선거 일정을 공지하려고",
        "교내 기부 행사 참여를 부탁하려고",
        "점심시간 봉사 활동을 모집하려고",
      ],
      answer: 1,
      clue: "Starting next Monday, we will keep items for four weeks only.",
      explanation:
        "남자는 지금까지 학기 말까지 보관하던 분실물을 다음 주부터 4주만 보관하고 이후에는 기부한다고 알리고 있다. 따라서 말의 목적은 ①이다.",
      translation: [
        "M: 학생 여러분, 주목해 주세요. 학생회장입니다.",
        "M: 정문 옆 분실물 보관함에 대해 말씀드릴 것이 있습니다.",
        "M: 지금은 모든 물건을 학기가 끝날 때까지 보관하고 있습니다.",
        "M: 그러다 보니 지난봄에 들어온 장갑과 물병으로 상자가 가득 찼습니다.",
        "M: 다음 주 월요일부터는 물건을 4주 동안만 보관합니다.",
        "M: 그 뒤에 남은 물건은 지역 단체에 기부할 예정입니다.",
        "M: 이번 달에 무언가를 잃어버리셨다면 이번 주에 와서 확인해 주세요.",
        "M: 학생회가 점심시간마다 나와서 찾는 것을 도와드리겠습니다.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "의견 파악",
      instruction: "대화를 듣고, 남자의 의견으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, you skipped the stretching again before practice."],
        ["M", "I didn't skip warming up. I walked two laps around the track instead."],
        ["W", "Walking? Our coach always tells us to stretch first."],
        ["M", "I read that stretching a cold muscle doesn't protect it much."],
        ["W", "Then what does walking do that stretching doesn't?"],
        ["M", "It raises your body temperature, so the muscles are ready to move."],
        ["W", "Hmm. So you stretch after you're warm, not before?"],
        ["M", "Exactly. Light movement first, stretching later. That order matters."],
        ["W", "I've never thought about the order at all."],
        ["M", "Most people don't. But doing it backwards is why people still get hurt."],
      ],
      choices: [
        "운동 전에는 스트레칭을 오래 해야 한다.",
        "준비운동은 가벼운 움직임으로 시작해야 한다.",
        "운동은 코치의 지시대로 하는 것이 안전하다.",
        "부상을 막으려면 운동 시간을 줄여야 한다.",
        "운동 후에는 반드시 휴식을 취해야 한다.",
      ],
      answer: 2,
      clue: "Light movement first, stretching later. That order matters.",
      explanation:
        "남자는 차가운 근육을 늘이는 것보다 가볍게 걸어 체온을 올린 뒤 스트레칭하는 순서가 중요하다고 말한다. 따라서 남자의 의견은 ②이다.",
      translation: [
        "W: 준서야, 연습 전에 또 스트레칭 안 했네.",
        "M: 준비운동을 안 한 건 아니야. 대신 트랙을 두 바퀴 걸었어.",
        "W: 걷기? 코치님은 늘 스트레칭 먼저 하라고 하시잖아.",
        "M: 차가운 근육을 늘이는 건 보호 효과가 크지 않다고 읽었어.",
        "W: 그럼 걷기가 스트레칭이 못 하는 뭘 해 주는데?",
        "M: 체온을 올려서 근육이 움직일 준비를 하게 해 줘.",
        "W: 음, 그럼 몸이 따뜻해진 다음에 스트레칭하는 거야?",
        "M: 맞아. 가벼운 움직임 먼저, 스트레칭은 나중에. 그 순서가 중요해.",
        "W: 순서는 생각해 본 적이 없었어.",
        "M: 대부분 그래. 그런데 순서를 거꾸로 하니까 계속 다치는 거야.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "요지 파악",
      instruction: "다음을 듣고, 여자가 하는 말의 요지로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Many of you take notes carefully during club meetings."],
        ["W", "Then you close the notebook and open it again a week later."],
        ["W", "By then, half of what you wrote no longer makes sense to you."],
        ["W", "The words are there, but the reason you wrote them is gone."],
        ["W", "So spend five minutes right after the meeting, while it is still fresh."],
        ["W", "Add what was decided and who agreed to do what."],
        ["W", "Those five minutes save you an hour of asking people later."],
      ],
      choices: [
        "회의는 짧게 끝내는 것이 좋다.",
        "회의록은 여러 사람이 나누어 써야 한다.",
        "회의가 끝난 직후에 기록을 정리해야 한다.",
        "회의 전에 안건을 미리 공유해야 한다.",
        "기록보다 말로 전달하는 편이 빠르다.",
      ],
      answer: 3,
      clue: "So spend five minutes right after the meeting, while it is still fresh.",
      explanation:
        "여자는 회의 중에 적은 기록이 일주일 뒤에는 이해되지 않는다며, 회의 직후 5분 동안 결정 사항과 담당자를 정리하라고 말한다. 따라서 요지는 ③이다.",
      translation: [
        "W: 여러분 중 많은 사람이 동아리 회의 중에 꼼꼼히 기록을 합니다.",
        "W: 그러고는 공책을 덮고 일주일 뒤에 다시 펴 봅니다.",
        "W: 그때쯤이면 적어 둔 것의 절반은 무슨 말인지 알 수 없게 됩니다.",
        "W: 낱말은 남아 있지만 그것을 적은 이유는 사라졌습니다.",
        "W: 그러니 기억이 생생할 때, 회의가 끝나자마자 5분을 쓰세요.",
        "W: 무엇이 결정되었는지, 누가 무엇을 하기로 했는지 덧붙이세요.",
        "W: 그 5분이 나중에 사람들에게 물어보는 한 시간을 아껴 줍니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "그림 불일치",
      instruction: "대화를 듣고, 그림에서 대화의 내용과 일치하지 않는 것을 고르시오.",
      lines: [
        ["W", "Dongha, the recycling booth for the school festival is almost ready."],
        ["W", "I want people to know what to do without asking us."],
        ["M", "At the back there's a long banner with a round arrow symbol in the middle."],
        ["W", "Right, that symbol tells people what the booth is about."],
        ["M", "On the left I see three bins standing side by side."],
        ["W", "Those are for paper, cans, and plastic. Each one has a different lid."],
        ["M", "In the centre of the table there's a scale for weighing what people bring."],
        ["W", "Yes, we give out stickers based on the weight."],
        ["M", "And next to the scale, is that a square basket for the stickers?"],
        ["W", "No, it's a round jar. The basket kept tipping over yesterday."],
        ["M", "I see. On the right, a folding chair is set up for whoever is on duty."],
        ["W", "Perfect. Then we can open at nine tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, it's a round jar. The basket kept tipping over yesterday.",
      explanation:
        "여자가 스티커를 담는 것은 네모난 바구니가 아니라 둥근 병이라고 바로잡는다. 그림에는 네모난 바구니가 그려져 있으므로 ④가 대화와 일치하지 않는다.",
      figure: {
        kind: "labeled",
        scene:
          "A school festival recycling booth seen from the front, five things clearly separated. " +
          "Upper centre on the back wall: a long blank banner with a single round arrow symbol in its middle. " +
          "Left: three tall bins standing side by side, each with a differently shaped lid. " +
          "Centre of the table: a flat weighing scale with a round dial. " +
          "Right of the scale on the table: a SQUARE basket holding small sticker sheets. " +
          "Far right: a folding chair set up beside the table.",
      },
      translation: [
        "W: 동하야, 학교 축제 재활용 부스 거의 다 됐어.",
        "W: 사람들이 우리한테 묻지 않고도 뭘 해야 할지 알았으면 좋겠어.",
        "M: 뒤쪽에 가운데 둥근 화살표 표시가 있는 긴 현수막이 있네.",
        "W: 응, 그 표시가 이 부스가 뭘 하는 곳인지 알려 줘.",
        "M: 왼쪽에는 통 세 개가 나란히 서 있고.",
        "W: 종이, 캔, 플라스틱용이야. 뚜껑 모양이 다 달라.",
        "M: 탁자 가운데에는 사람들이 가져온 걸 다는 저울이 있네.",
        "W: 응, 무게에 따라 스티커를 줘.",
        "M: 저울 옆에 있는 건 스티커 담는 네모난 바구니야?",
        "W: 아니야, 둥근 병이야. 바구니는 어제 자꾸 넘어졌어.",
        "M: 그렇구나. 오른쪽에는 당번이 앉을 접이식 의자가 놓여 있네.",
        "W: 좋아. 그럼 내일 아침 아홉 시에 열 수 있겠다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "할 일",
      instruction: "대화를 듣고, 여자가 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, the club showcase is on Friday and I'm worried about the sound."],
        ["W", "Didn't the school tech team check the speakers last week?"],
        ["M", "They checked the big hall, but we moved to the small auditorium."],
        ["W", "Oh, that room has only two speakers, and one of them buzzes."],
        ["M", "Exactly. If it buzzes during the guitar piece, we're finished."],
        ["W", "Have you told the tech team about the room change?"],
        ["M", "I sent a message, but they said their schedule is full until Friday."],
        ["W", "Then someone has to test it ourselves before Thursday."],
        ["M", "I can't. I'm running the rehearsal every afternoon this week."],
        ["W", "All right. I'll go to the auditorium tomorrow and test both speakers."],
        ["M", "Thank you. Bring the spare cable from the club room just in case."],
      ],
      choices: ["예행연습 진행하기", "기술팀에 문자 보내기", "강당 사용 신청하기", "스피커 점검하기", "기타 줄 교체하기"],
      answer: 4,
      clue: "I'll go to the auditorium tomorrow and test both speakers.",
      explanation:
        "남자는 예행연습을 맡고 있어 갈 수 없고, 여자가 내일 강당에 가서 스피커 두 대를 점검하겠다고 말한다. 따라서 여자가 할 일은 ④이다.",
      translation: [
        "M: 예린아, 동아리 발표회가 금요일인데 음향이 걱정이야.",
        "W: 지난주에 기술팀이 스피커 점검하지 않았어?",
        "M: 큰 강당을 봤는데, 우리는 작은 강당으로 옮겼잖아.",
        "W: 아, 거긴 스피커가 두 대뿐이고 하나는 잡음이 나지.",
        "M: 맞아. 기타 연주 중에 잡음이 나면 끝이야.",
        "W: 기술팀에 장소 바뀐 거 말했어?",
        "M: 문자는 보냈는데 금요일까지 일정이 꽉 찼대.",
        "W: 그럼 목요일 전에 우리가 직접 확인해야겠네.",
        "M: 난 못 해. 이번 주 내내 오후마다 예행연습을 이끌어야 해.",
        "W: 알겠어. 내가 내일 강당 가서 스피커 두 대 다 확인할게.",
        "M: 고마워. 혹시 모르니 동아리방에서 여분 케이블도 가져가.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "금액 계산",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Good morning. Welcome to Hanul Bike Rental. How can I help you?"],
        ["M", "I'd like to rent two bicycles for three hours, please."],
        ["W", "Certainly. A bicycle is ten dollars for three hours."],
        ["M", "Ten dollars each, so that's twenty for the two."],
        ["W", "That's right. Would you like helmets as well?"],
        ["M", "Yes, two helmets. How much are they?"],
        ["W", "Helmets are four dollars each for the same period."],
        ["M", "All right, two of those too."],
        ["W", "Then that comes to twenty-eight dollars in total."],
        ["M", "I have a membership card. Does that help?"],
        ["W", "It does. Members get twenty-five percent off the total."],
        ["M", "Great. Here's my card and my payment."],
      ],
      choices: ["$18", "$20", "$21", "$24", "$28"],
      answer: 3,
      clue: "Members get twenty-five percent off the total.",
      explanation:
        "자전거 10달러씩 두 대면 20달러, 헬멧 4달러씩 두 개면 8달러로 합계 28달러이다. 회원 할인 25%를 빼면 28 × 0.75 = 21달러이므로 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 하늘 자전거 대여점입니다. 무엇을 도와드릴까요?",
        "M: 자전거 두 대를 세 시간 빌리고 싶습니다.",
        "W: 네. 자전거는 세 시간에 10달러입니다.",
        "M: 한 대에 10달러니까 두 대면 20달러네요.",
        "W: 맞습니다. 헬멧도 필요하신가요?",
        "M: 네, 두 개요. 얼마인가요?",
        "W: 헬멧은 같은 시간 기준으로 하나에 4달러입니다.",
        "M: 그럼 두 개 주세요.",
        "W: 그러면 모두 28달러입니다.",
        "M: 회원 카드가 있는데 할인이 되나요?",
        "W: 됩니다. 회원은 전체 금액에서 25% 할인됩니다.",
        "M: 좋네요. 카드랑 결제할 것 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "이유 파악",
      instruction: "대화를 듣고, 남자가 주말 농장 봉사에 갈 수 없는 이유를 고르시오.",
      lines: [
        ["W", "Sangwoo, are you coming to the weekend farm volunteering?"],
        ["M", "I signed up, but I have to cancel this time."],
        ["W", "Is your part-time job schedule changed again?"],
        ["M", "No, I don't work on Saturdays anymore."],
        ["W", "Then is it because of the bus? I heard the route is closed."],
        ["M", "The bus runs fine. It's my sister's piano recital."],
        ["W", "Oh, is it the same morning?"],
        ["M", "It starts at ten, and she asked me to record it for our grandmother."],
        ["W", "Then you definitely can't miss that."],
      ],
      choices: [
        "아르바이트 일정이 바뀌어서",
        "버스 노선이 막혀서",
        "동생의 연주회에 가야 해서",
        "할머니를 병원에 모셔다드려야 해서",
        "농장 신청이 마감되어서",
      ],
      answer: 3,
      clue: "It's my sister's piano recital.",
      explanation:
        "남자는 아르바이트도 없고 버스도 정상 운행하지만, 같은 날 아침 열 시에 있는 동생의 피아노 연주회를 녹화해 달라는 부탁을 받았다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "W: 상우야, 주말 농장 봉사 오는 거지?",
        "M: 신청은 했는데 이번엔 취소해야 해.",
        "W: 아르바이트 일정이 또 바뀌었어?",
        "M: 아니, 이제 토요일엔 일 안 해.",
        "W: 그럼 버스 때문이야? 노선이 막혔다고 들었는데.",
        "M: 버스는 잘 다녀. 동생 피아노 연주회 때문이야.",
        "W: 아, 같은 날 아침이야?",
        "M: 열 시에 시작하는데, 할머니께 보여 드리게 녹화해 달래.",
        "W: 그럼 그건 빠질 수 없지.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "미언급",
      instruction: "대화를 듣고, 교내 사진 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Suyeon, did you see the notice about the school photo contest?"],
        ["W", "I saw the poster, but I only read the title."],
        ["M", "The theme this year is 'a quiet corner of our school'."],
        ["W", "That's a good theme. When do we have to hand it in?"],
        ["M", "By the twentieth of next month, at the art room."],
        ["W", "Can I send a photo I took last year?"],
        ["M", "No, it has to be taken after the announcement date."],
        ["W", "Understood. How many can one person enter?"],
        ["M", "Two at most, and they must be printed, not sent by email."],
        ["W", "Printed? Then I should check the size before I go."],
        ["M", "Good idea. Anyway, the winner gets a camera bag as a prize."],
        ["W", "Then I'd better start looking for my quiet corner."],
      ],
      choices: ["주제", "제출 기한", "제출 편수", "상품", "심사 위원"],
      answer: 5,
      clue: "the winner gets a camera bag as a prize",
      explanation:
        "주제(학교의 조용한 구석), 제출 기한(다음 달 20일), 제출 편수(최대 두 장), 상품(카메라 가방)은 언급되지만 심사 위원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 수연아, 교내 사진 대회 공지 봤어?",
        "W: 포스터는 봤는데 제목만 읽었어.",
        "M: 올해 주제는 '우리 학교의 조용한 구석'이야.",
        "W: 주제 좋다. 언제까지 내야 해?",
        "M: 다음 달 20일까지, 미술실로 내면 돼.",
        "W: 작년에 찍은 사진을 내도 돼?",
        "M: 아니, 공지 날짜 이후에 찍은 것이어야 해.",
        "W: 알겠어. 한 사람이 몇 장까지 낼 수 있어?",
        "M: 최대 두 장이고, 이메일이 아니라 인화해서 내야 해.",
        "W: 인화? 그럼 가기 전에 크기를 확인해야겠네.",
        "M: 그게 좋겠다. 아무튼 1등은 상품으로 카메라 가방을 받아.",
        "W: 그럼 내 조용한 구석을 찾아봐야겠다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "내용 불일치",
      instruction: "Night Reading Room에 관한 다음 내용을 듣고, 일치하지 않는 것을 고르시오.",
      lines: [
        ["W", "Let me tell you about the Night Reading Room that opens next month."],
        ["W", "The school library will stay open until ten on weekday evenings."],
        ["W", "Only the second-floor reading room will be used, not the whole library."],
        ["W", "You may borrow books during these hours, but you cannot return them."],
        ["W", "A teacher will be on duty each evening, so ask if you need help."],
        ["W", "Drinks in closed bottles are allowed, but food is not."],
        ["W", "No sign-up is needed. Just show your student card at the door."],
      ],
      choices: [
        "평일 저녁 열 시까지 운영한다.",
        "2층 열람실만 사용한다.",
        "이 시간에는 책을 반납할 수 있다.",
        "저녁마다 담당 교사가 있다.",
        "미리 신청하지 않아도 된다.",
      ],
      answer: 3,
      clue: "You may borrow books during these hours, but you cannot return them.",
      explanation:
        "이 시간에는 책을 빌릴 수는 있지만 반납은 할 수 없다고 했으므로, 반납할 수 있다는 ③이 내용과 일치하지 않는다.",
      translation: [
        "W: 다음 달에 문을 여는 야간 열람실에 대해 알려 드리겠습니다.",
        "W: 평일 저녁에는 학교 도서관이 열 시까지 문을 엽니다.",
        "W: 도서관 전체가 아니라 2층 열람실만 사용합니다.",
        "W: 이 시간에는 책을 빌릴 수는 있지만 반납은 할 수 없습니다.",
        "W: 저녁마다 담당 교사가 있으니 도움이 필요하면 말씀하세요.",
        "W: 뚜껑이 있는 음료는 괜찮지만 음식은 안 됩니다.",
        "W: 미리 신청할 필요는 없습니다. 입구에서 학생증만 보여 주세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "표 선택",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 빌릴 캠핑 장비를 고르시오.",
      lines: [
        ["M", "Jieun, here are the five camping sets the rental shop has left."],
        ["W", "Good. First, it has to hold four people. There will be four of us."],
        ["M", "That rules out the smallest one. What about the price?"],
        ["W", "My share can't be more than fifteen dollars, so let's stay under sixty."],
        ["M", "Then two more are gone. Do we need a set with a lantern?"],
        ["W", "We already have two lanterns from the club room."],
        ["M", "So a lantern doesn't matter either way. What about the weight?"],
        ["W", "It does matter. We're carrying everything from the bus stop."],
        ["M", "Then let's take the lighter of the two that are left."],
        ["W", "Agreed. Under eight kilograms sounds manageable."],
        ["M", "I'll reserve it tonight and pick it up on Friday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Then let's take the lighter of the two that are left.",
      explanation:
        "4인용이 아닌 ①을 빼고, 60달러가 넘는 ④·⑤를 뺀다. 남은 ②와 ③ 중 더 가벼운 것은 7.5kg인 ②이므로 답은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "2인용 / 45달러 / 6.0kg / 랜턴 있음" },
          { no: 2, label: "②", value: "4인용 / 52달러 / 7.5kg / 랜턴 없음" },
          { no: 3, label: "③", value: "4인용 / 58달러 / 9.0kg / 랜턴 있음" },
          { no: 4, label: "④", value: "4인용 / 64달러 / 7.0kg / 랜턴 있음" },
          { no: 5, label: "⑤", value: "6인용 / 70달러 / 8.0kg / 랜턴 없음" },
        ],
      },
      translation: [
        "M: 지은아, 대여점에 남아 있는 캠핑 세트가 이 다섯 개야.",
        "W: 좋아. 우선 네 명이 쓸 수 있어야 해. 우리 넷이니까.",
        "M: 그럼 제일 작은 건 빠지네. 가격은 어때?",
        "W: 내 몫이 15달러를 넘으면 안 되니까 60달러 아래로 하자.",
        "M: 그럼 두 개 더 빠진다. 랜턴 있는 세트가 필요해?",
        "W: 동아리방에 랜턴 두 개 있잖아.",
        "M: 그럼 랜턴은 있든 없든 상관없네. 무게는?",
        "W: 그건 중요해. 버스 정류장에서 다 들고 가야 하니까.",
        "M: 그럼 남은 둘 중에 더 가벼운 걸로 하자.",
        "W: 좋아. 8킬로그램 아래면 들 만하겠다.",
        "M: 오늘 밤에 예약하고 금요일에 찾아올게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "짧은 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Did you find the book you were looking for?"],
        ["M", "Not yet. It wasn't on the shelf where the computer said it would be."],
        ["W", "Did you check the returns cart near the desk?"],
        ["M", "The returns cart? I didn't know there was one."],
        ["W", "Books wait there for a day before they go back on the shelf."],
      ],
      choices: [
        "Then I'll go and look through that cart.",
        "I returned it yesterday afternoon.",
        "The computer is next to the window.",
        "I already read that book last summer.",
        "You can borrow five books at a time.",
      ],
      answer: 1,
      clue: "Books wait there for a day before they go back on the shelf.",
      explanation:
        "반납 수레에 하루 정도 머문다는 설명을 들었으므로, 그 수레를 살펴보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 찾던 책 찾았어?",
        "M: 아직. 컴퓨터가 알려 준 자리에 없더라.",
        "W: 데스크 옆 반납 수레는 확인했어?",
        "M: 반납 수레? 그런 게 있는 줄 몰랐어.",
        "W: 책이 서가로 돌아가기 전에 하루 정도 거기 있어.",
        "M: 그럼 그 수레를 살펴봐야겠다.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "짧은 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Are you taking the school shuttle to the museum tomorrow?"],
        ["W", "I want to, but the sign-up sheet was already full this morning."],
        ["M", "Did you put your name on the waiting list at the bottom?"],
        ["W", "There was a waiting list? I didn't look past the numbered lines."],
        ["M", "It's on the back of the sheet. Two people cancelled yesterday."],
      ],
      choices: [
        "The museum closes at six on weekdays.",
        "I'll go back and check the back of the sheet.",
        "I took the shuttle last semester too.",
        "The bus leaves from the east gate.",
        "You should have signed up earlier.",
      ],
      answer: 2,
      clue: "It's on the back of the sheet. Two people cancelled yesterday.",
      explanation:
        "대기자 명단이 신청서 뒷면에 있고 두 명이 취소했다는 말을 들었으므로, 다시 가서 뒷면을 확인하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 내일 박물관 갈 때 학교 셔틀 타?",
        "W: 타고 싶은데 오늘 아침에 신청서가 이미 다 찼더라.",
        "M: 맨 아래 대기자 명단에 이름 적었어?",
        "W: 대기자 명단이 있었어? 번호 적힌 줄까지만 봤는데.",
        "M: 신청서 뒷면에 있어. 어제 두 명이 취소했대.",
        "W: 다시 가서 뒷면 확인해 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "긴 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunwoo, how is the school newspaper coming along?"],
        ["M", "The articles are done, but the layout is taking forever."],
        ["W", "How many pages are you working with?"],
        ["M", "Eight, and I'm placing every photo and caption by hand."],
        ["W", "By hand? Don't you have a template from last year's issue?"],
        ["M", "There is one, but the font sizes look old-fashioned to me."],
        ["W", "So you decided to design all eight pages from nothing."],
        ["M", "That was the idea. Now I'm three days behind."],
        ["W", "You could keep the old template and change only the fonts."],
        ["M", "Then the layout would still be last year's layout."],
        ["W", "Maybe, but readers notice the articles, not the column widths."],
      ],
      choices: [
        "I'll print a test copy before the deadline.",
        "The photos were taken by the club members.",
        "You're right. I'll reuse the template and just fix the fonts.",
        "We should publish the paper twice a month.",
        "I'd rather write another article instead.",
      ],
      answer: 3,
      clue: "Maybe, but readers notice the articles, not the column widths.",
      explanation:
        "독자는 단의 너비가 아니라 기사를 본다는 말을 들었으므로, 예전 틀을 그대로 쓰고 글꼴만 고치겠다는 ③이 가장 적절하다.",
      translation: [
        "W: 현우야, 학교 신문은 잘 되고 있어?",
        "M: 기사는 다 됐는데 편집이 끝이 없어.",
        "W: 몇 면이야?",
        "M: 여덟 면인데, 사진이랑 설명을 전부 손으로 배치하고 있어.",
        "W: 손으로? 작년 호에 쓰던 틀 없어?",
        "M: 있긴 한데 글꼴 크기가 좀 촌스러워 보여서.",
        "W: 그래서 여덟 면을 처음부터 다시 디자인하기로 한 거구나.",
        "M: 그럴 생각이었지. 지금은 사흘이나 밀렸어.",
        "W: 예전 틀을 두고 글꼴만 바꿔도 되잖아.",
        "M: 그러면 편집은 여전히 작년 것이잖아.",
        "W: 그럴 수도 있지만, 독자는 단 너비가 아니라 기사를 봐.",
        "M: 네 말이 맞아. 틀은 그대로 쓰고 글꼴만 고칠게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "긴 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Minkyung, you've been eating lunch at your desk all week."],
        ["W", "I have too much to finish before the science fair."],
        ["M", "Is the experiment not working?"],
        ["W", "It works, but writing the report takes longer than I thought."],
        ["M", "Do you take any break at all during the day?"],
        ["W", "I get up when my legs hurt. That's about it."],
        ["M", "That's not a break. That's your body complaining."],
        ["W", "I know, but stopping feels like wasting time."],
        ["M", "Try eating in the cafeteria just once and see how the afternoon goes."],
      ],
      choices: [
        "I'll finish the report by Thursday instead.",
        "The cafeteria food is better this year.",
        "Fine. I'll try it tomorrow and compare.",
        "My legs hurt because of the new chair.",
        "You should join the science fair too.",
      ],
      answer: 3,
      clue: "Try eating in the cafeteria just once and see how the afternoon goes.",
      explanation:
        "한 번만 식당에서 먹고 오후가 어떤지 보라는 제안을 들었으므로, 내일 해 보고 비교하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 민경아, 너 이번 주 내내 자리에서 점심 먹더라.",
        "W: 과학전 전에 끝낼 게 너무 많아서.",
        "M: 실험이 잘 안 돼?",
        "W: 실험은 되는데 보고서 쓰는 게 생각보다 오래 걸려.",
        "M: 낮에 쉬기는 해?",
        "W: 다리 아프면 일어나. 그 정도야.",
        "M: 그건 쉬는 게 아니라 몸이 항의하는 거지.",
        "W: 알아. 그런데 멈추면 시간 버리는 것 같아서.",
        "M: 딱 한 번만 식당에서 먹고 오후가 어떤지 봐.",
        "W: 알겠어. 내일 해 보고 비교해 볼게.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "상황 발화",
      instruction: "다음 상황 설명을 듣고, Jaemin이 Sua에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jaemin : ________________",
      lines: [
        ["M", "Jaemin and Sua are in the same after-school cooking class."],
        ["M", "Each week the class works in pairs, and they have been partners since April."],
        ["M", "Sua is quick with a knife and always finishes the chopping first."],
        ["M", "Because of that, she often starts the next step before reading the recipe."],
        ["M", "Last week she added the salt twice, and their soup was hard to eat."],
        ["M", "Today the class is making a sauce where the order of the steps decides the taste."],
        ["M", "Jaemin does not want to say that she made a mistake last week."],
        ["M", "He only wants her to look at the card before she picks up the next bowl."],
        ["M", "In this situation, what would Jaemin most likely say to Sua?"],
      ],
      choices: [
        "Let's ask the teacher to taste our sauce first.",
        "Could you read the next step before we add anything?",
        "I'll do the chopping today so you can rest.",
        "We should choose a different recipe this week.",
        "Don't worry about what happened last week.",
      ],
      answer: 2,
      clue: "He only wants her to look at the card before she picks up the next bowl.",
      explanation:
        "재민은 지난주의 실수를 들추지 않고, 다음 재료를 집기 전에 조리법을 먼저 읽자고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 재민이와 수아는 같은 방과 후 요리 수업을 듣습니다.",
        "M: 수업은 매주 둘씩 짝을 지어 하는데, 두 사람은 4월부터 짝입니다.",
        "M: 수아는 칼질이 빨라서 재료 썰기를 늘 먼저 끝냅니다.",
        "M: 그러다 보니 조리법을 읽기 전에 다음 단계를 시작할 때가 많습니다.",
        "M: 지난주에는 소금을 두 번 넣어서 국이 먹기 힘들었습니다.",
        "M: 오늘 수업에서는 단계의 순서가 맛을 좌우하는 소스를 만듭니다.",
        "M: 재민이는 지난주에 실수했다는 말을 하고 싶지는 않습니다.",
        "M: 다만 다음 그릇을 집기 전에 조리법 카드를 보기만 했으면 합니다.",
        "M: 이런 상황에서 재민이가 수아에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
    {
      order: 16,
      type: "주제",
      instruction: "여자가 하는 말의 주제로 가장 적절한 것은?",
      lines: [
        ["W", "Good afternoon. Today I'd like to talk about plants that survive in a student's room."],
        ["W", "Most of you water a plant carefully for two weeks and then forget it for a month."],
        ["W", "The plants I'm listing today forgive that kind of care."],
        ["W", "A spider plant grows new shoots even in a dim corner near a bookshelf."],
        ["W", "A snake plant needs water only once every three weeks, even in summer."],
        ["W", "Pothos grows along a string on the wall and tells you it's thirsty by drooping."],
        ["W", "An aloe stores water in its leaves, so a forgotten weekend does no harm."],
        ["W", "None of these need special soil or a sunny window to stay alive."],
      ],
      choices: [
        "how to choose soil for indoor plants",
        "houseplants that survive with little care",
        "why students give up on gardening",
        "the best season to start growing plants",
        "ways to water plants while travelling",
      ],
      answer: 2,
      clue: "Today I'd like to talk about plants that survive in a student's room.",
      explanation:
        "여자는 물을 자주 주지 않아도 잘 견디는 실내 식물로 접란, 산세비에리아, 스킨답서스, 알로에를 소개한다. 따라서 주제는 ②이다.",
      translation: [
        "W: 안녕하세요. 오늘은 학생 방에서도 살아남는 식물에 대해 이야기하려고 합니다.",
        "W: 여러분 대부분은 2주 동안 정성껏 물을 주다가 한 달쯤 잊어버립니다.",
        "W: 오늘 소개할 식물들은 그런 돌봄도 견뎌 냅니다.",
        "W: 접란은 책장 옆 어두운 구석에서도 새순을 냅니다.",
        "W: 산세비에리아는 여름에도 3주에 한 번만 물을 주면 됩니다.",
        "W: 스킨답서스는 벽에 매단 줄을 타고 자라고, 목마르면 잎을 늘어뜨려 알려 줍니다.",
        "W: 알로에는 잎에 물을 저장해서 주말 한 번쯤 잊어도 괜찮습니다.",
        "W: 이 중 어느 것도 특별한 흙이나 햇빛 좋은 창가가 있어야 사는 것은 아닙니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "언급 여부",
      instruction: "언급된 식물이 아닌 것은?",
      lines: [
        ["W", "Good afternoon. Today I'd like to talk about plants that survive in a student's room."],
        ["W", "Most of you water a plant carefully for two weeks and then forget it for a month."],
        ["W", "The plants I'm listing today forgive that kind of care."],
        ["W", "A spider plant grows new shoots even in a dim corner near a bookshelf."],
        ["W", "A snake plant needs water only once every three weeks, even in summer."],
        ["W", "Pothos grows along a string on the wall and tells you it's thirsty by drooping."],
        ["W", "An aloe stores water in its leaves, so a forgotten weekend does no harm."],
        ["W", "None of these need special soil or a sunny window to stay alive."],
      ],
      choices: ["spider plant", "snake plant", "pothos", "cactus", "aloe"],
      answer: 4,
      clue: "A spider plant ... A snake plant ... Pothos ... An aloe",
      explanation:
        "접란, 산세비에리아, 스킨답서스, 알로에는 언급되지만 선인장은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: "16번과 같은 담화입니다.",
    },
  ],
};
