/** 고2 듣기 11회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "고2 듣기 11회",
  gradeLevel: "high2",
  speechSpeed: 0.8,
  folder: "고2 듣기",
  questions: [
    {
      order: 1,
      type: "목적 파악",
      instruction: "다음을 듣고, 여자가 하는 말의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, residents of Maple Apartments. This is the management office."],
        ["W", "We have received many calls about the elevator in Building B this week."],
        ["W", "The engineers found that the door sensor needs to be replaced completely."],
        ["W", "The part will arrive on Wednesday, and the work will take two full days."],
        ["W", "During that time, the elevator in Building B will not run at all."],
        ["W", "Residents on the upper floors may use the elevator in Building A instead."],
        ["W", "The connecting door on the second floor will stay unlocked until Friday evening."],
        ["W", "We are sorry for the trouble and thank you for your patience."],
      ],
      choices: [
        "승강기 사용 요금 인상을 알리려고",
        "건물 사이 연결 통로의 폐쇄를 알리려고",
        "관리 사무소 운영 시간 변경을 알리려고",
        "승강기 수리로 인한 이용 중단을 알리려고",
        "승강기 안전 교육 참여를 요청하려고",
      ],
      answer: 4,
      clue: "During that time, the elevator in Building B will not run at all.",
      explanation:
        "여자는 B동 승강기의 문 감지기를 교체하는 이틀 동안 승강기를 쓸 수 없으니 A동 것을 이용하라고 알리고 있다. 따라서 말의 목적은 ④이다.",
      translation: [
        "W: 메이플 아파트 주민 여러분, 안녕하십니까. 관리 사무소입니다.",
        "W: 이번 주에 B동 승강기에 대한 문의 전화를 많이 받았습니다.",
        "W: 점검 결과 문 감지기를 완전히 교체해야 한다고 합니다.",
        "W: 부품은 수요일에 도착하고, 작업에는 꼬박 이틀이 걸립니다.",
        "W: 그동안 B동 승강기는 전혀 운행하지 않습니다.",
        "W: 위층 주민께서는 대신 A동 승강기를 이용해 주시기 바랍니다.",
        "W: 2층 연결 통로 문은 금요일 저녁까지 열어 두겠습니다.",
        "W: 불편을 드려 죄송하며 양해해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "의견 파악",
      instruction: "대화를 듣고, 여자의 의견으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, you turned down the lead role in the school play?"],
        ["W", "I did. I asked to work on the lighting instead."],
        ["M", "But you've wanted that role since last year."],
        ["W", "I know. And I'd have spent every evening memorizing lines."],
        ["M", "That's what acting is. Isn't it worth it?"],
        ["W", "It would be, if this term were like last term."],
        ["M", "What's different now?"],
        ["W", "I'm taking two extra science courses and I tutor on Tuesdays."],
        ["M", "So you decided before you were forced to decide."],
        ["W", "Right. Choosing early is better than dropping out halfway."],
        ["M", "I hadn't thought of it that way."],
      ],
      choices: [
        "연극은 여러 사람이 함께 만들어야 한다.",
        "하고 싶은 일은 미루지 말아야 한다.",
        "감당할 수 있는 만큼만 미리 정해 맡아야 한다.",
        "무대 뒤 역할도 배우만큼 중요하다.",
        "성적보다 경험을 우선해야 한다.",
      ],
      answer: 3,
      clue: "Choosing early is better than dropping out halfway.",
      explanation:
        "여자는 수업과 과외로 시간이 부족한 상황을 미리 헤아려, 중간에 그만두느니 처음부터 감당할 수 있는 역할을 고르는 편이 낫다고 말한다. 따라서 의견은 ③이다.",
      translation: [
        "M: 서연아, 학교 연극 주인공 역할을 거절했다면서?",
        "W: 응. 대신 조명을 맡겠다고 했어.",
        "M: 작년부터 그 역할 하고 싶어 했잖아.",
        "W: 알아. 그리고 매일 저녁 대사를 외웠겠지.",
        "M: 연기가 원래 그런 거잖아. 그만한 가치가 있지 않아?",
        "W: 이번 학기가 지난 학기 같았다면 그랬을 거야.",
        "M: 뭐가 달라졌는데?",
        "W: 과학 과목을 두 개 더 듣고, 화요일마다 과외도 해.",
        "M: 그러니까 떠밀려 결정하기 전에 네가 먼저 정한 거구나.",
        "W: 맞아. 중간에 그만두느니 처음에 고르는 게 나아.",
        "M: 그렇게는 생각해 본 적 없었어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "요지 파악",
      instruction: "다음을 듣고, 남자가 하는 말의 요지로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "When you write a report, you probably read it over before you hand it in."],
        ["M", "You read it on the same screen, in the same font, at the same desk."],
        ["M", "Your eyes slide over the sentences because they already know what comes next."],
        ["M", "That is why the mistake you missed at midnight is obvious the next morning."],
        ["M", "So change something before you check: print it out, or read it aloud."],
        ["M", "Even changing the font size makes your eyes move differently."],
        ["M", "The text has not changed, but you are reading it as a stranger would."],
      ],
      choices: [
        "글을 고칠 때는 보는 조건을 바꿔야 한다.",
        "보고서는 마감 전날 미리 끝내야 한다.",
        "글은 다른 사람에게 보여 주고 고쳐야 한다.",
        "긴 글은 여러 번 나누어 써야 한다.",
        "손으로 쓴 글이 기억에 오래 남는다.",
      ],
      answer: 1,
      clue: "So change something before you check: print it out, or read it aloud.",
      explanation:
        "남자는 같은 화면·같은 글꼴로 읽으면 눈이 미끄러져 실수를 못 본다며, 인쇄하거나 소리 내어 읽는 식으로 조건을 바꾸라고 말한다. 따라서 요지는 ①이다.",
      translation: [
        "M: 보고서를 쓰면 제출하기 전에 다시 읽어 볼 겁니다.",
        "M: 같은 화면에서, 같은 글꼴로, 같은 책상에서 읽지요.",
        "M: 다음에 무슨 말이 오는지 이미 알기 때문에 눈이 문장 위를 미끄러집니다.",
        "M: 자정에 못 본 실수가 다음 날 아침에는 대번 보이는 이유가 그것입니다.",
        "M: 그러니 확인하기 전에 무언가를 바꾸세요. 인쇄하거나 소리 내어 읽으세요.",
        "M: 글꼴 크기만 바꿔도 눈이 다르게 움직입니다.",
        "M: 글은 그대로지만, 남이 읽듯이 읽게 되는 것입니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "그림 불일치",
      instruction: "대화를 듣고, 그림에서 대화의 내용과 일치하지 않는 것을 고르시오.",
      lines: [
        ["M", "Nayeon, the reading corner in the community centre looks finished."],
        ["W", "Almost. I want children to find everything without help."],
        ["M", "On the wall at the back there's a wide board with a tree shape in the middle."],
        ["W", "Right, the children hang their reading cards on the branches."],
        ["M", "On the left I see three cushions lined up on the floor."],
        ["W", "Those are for the youngest ones. They don't like chairs."],
        ["M", "In the middle there's a low round table with a lamp on it."],
        ["W", "The lamp helps in the afternoon when that corner gets dark."],
        ["M", "And beside the shelf, is that a wooden step stool?"],
        ["W", "No, it's a plastic crate. The stool broke last week."],
        ["M", "I see. On the right there's a basket holding rolled-up mats."],
        ["W", "Good. Then we can open the corner on Monday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, it's a plastic crate. The stool broke last week.",
      explanation:
        "여자는 선반 옆에 있는 것이 나무 발판이 아니라 플라스틱 상자라고 바로잡는다. 그림에는 나무 발판이 그려져 있으므로 ④가 대화와 일치하지 않는다.",
      figure: {
        kind: "labeled",
        scene:
          "A reading corner in a community centre seen from the front, five things clearly separated. " +
          "Upper centre on the back wall: a wide blank board with a single bare tree shape drawn in its middle, small cards hanging from its branches. " +
          "Left on the floor: three square cushions lined up side by side. " +
          "Centre: a low round table with a small table lamp standing on it. " +
          "Beside the bookshelf at the right of the table: a WOODEN step stool with two steps. " +
          "Far right: a round basket holding several rolled-up mats standing upright.",
      },
      translation: [
        "M: 나연아, 주민센터 독서 코너 다 된 것 같네.",
        "W: 거의. 아이들이 도움 없이도 다 찾을 수 있으면 좋겠어.",
        "M: 뒤쪽 벽에 가운데 나무 모양이 있는 넓은 게시판이 있네.",
        "W: 응, 아이들이 독서 카드를 가지에 걸어 둬.",
        "M: 왼쪽 바닥에는 방석 세 개가 나란히 있고.",
        "W: 제일 어린아이들용이야. 의자를 안 좋아하거든.",
        "M: 가운데에는 낮은 둥근 탁자가 있고 그 위에 스탠드가 있네.",
        "W: 오후에 그 구석이 어두워져서 스탠드가 도움이 돼.",
        "M: 그리고 선반 옆에 있는 건 나무 발판이야?",
        "W: 아니야, 플라스틱 상자야. 발판은 지난주에 부서졌어.",
        "M: 그렇구나. 오른쪽에는 돌돌 만 매트를 담은 바구니가 있네.",
        "W: 좋아. 그럼 월요일에 코너를 열 수 있겠다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "할 일",
      instruction: "대화를 듣고, 남자가 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taehyun, the volunteer trip to the shelter is this Saturday."],
        ["M", "I know. I've been waiting for it all month."],
        ["W", "There's a problem. The shelter called about the van."],
        ["M", "Did something happen to it?"],
        ["W", "Their van can only take eight people, but eleven signed up."],
        ["M", "Then three of us need another way to get there."],
        ["W", "Exactly. The bus goes there, but only twice in the morning."],
        ["M", "I'll look up the times and post them in our group chat."],
        ["W", "That would help. Some people don't know the route at all."],
        ["M", "I'll also write down where to get off and how long the walk is."],
        ["W", "Perfect. I'll handle the supplies list, then."],
      ],
      choices: ["승합차 예약하기", "버스 시간 알아보기", "준비물 목록 만들기", "참가자 명단 정리하기", "보호소에 전화하기"],
      answer: 2,
      clue: "I'll look up the times and post them in our group chat.",
      explanation:
        "승합차에 자리가 모자라자 남자는 버스 시간을 알아보고 단체 대화방에 올리겠다고 말한다. 준비물 목록은 여자가 맡는다. 따라서 답은 ②이다.",
      translation: [
        "W: 태현아, 보호소 봉사 가는 날이 이번 주 토요일이야.",
        "M: 알아. 한 달 내내 기다렸어.",
        "W: 문제가 하나 있어. 보호소에서 승합차 때문에 전화 왔어.",
        "M: 차에 무슨 일 있어?",
        "W: 거기 승합차는 여덟 명까지만 타는데 열한 명이 신청했어.",
        "M: 그럼 세 명은 다른 방법으로 가야겠네.",
        "W: 맞아. 버스가 가긴 하는데 오전에 두 번뿐이야.",
        "M: 내가 시간 알아보고 단체 대화방에 올릴게.",
        "W: 그러면 좋겠다. 노선을 아예 모르는 사람도 있어.",
        "M: 어디서 내리는지, 걸어서 얼마나 걸리는지도 적어 둘게.",
        "W: 좋아. 그럼 준비물 목록은 내가 맡을게.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "금액 계산",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the Riverside Pottery Studio. How can I help you?"],
        ["W", "I'd like to sign up for the weekend beginner class."],
        ["M", "Certainly. The class is thirty dollars per person."],
        ["W", "It's for me and my two cousins, so three people."],
        ["M", "Three at thirty each. Will you need clay as well?"],
        ["W", "Yes. How much is that?"],
        ["M", "One bag is ten dollars, and one bag is enough for two people."],
        ["W", "Then two bags should be plenty for the three of us."],
        ["M", "That's right. So the total comes to one hundred and ten dollars."],
        ["W", "I have a resident card for this district. Does it give a discount?"],
        ["M", "It does — ten percent off the whole amount."],
        ["W", "Wonderful. I'll pay by card."],
      ],
      choices: ["$90", "$99", "$100", "$110", "$120"],
      answer: 2,
      clue: "It does — ten percent off the whole amount.",
      explanation:
        "수업 30달러씩 세 명이면 90달러, 점토 10달러씩 두 봉지면 20달러로 합계 110달러이다. 주민 할인 10%를 빼면 110 × 0.9 = 99달러이므로 답은 ②이다.",
      translation: [
        "M: 리버사이드 도예 공방입니다. 무엇을 도와드릴까요?",
        "W: 주말 초보 수업을 신청하고 싶어요.",
        "M: 네. 수업은 한 사람에 30달러입니다.",
        "W: 저랑 사촌 둘이라서 세 명이에요.",
        "M: 세 명에 한 사람당 30달러네요. 점토도 필요하신가요?",
        "W: 네. 얼마인가요?",
        "M: 한 봉지에 10달러이고, 한 봉지면 두 사람이 쓰기에 충분합니다.",
        "W: 그럼 세 명이니까 두 봉지면 넉넉하겠네요.",
        "M: 맞습니다. 그러면 모두 110달러입니다.",
        "W: 이 지역 주민 카드가 있는데 할인이 되나요?",
        "M: 됩니다. 전체 금액에서 10% 할인해 드립니다.",
        "W: 좋네요. 카드로 결제할게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "이유 파악",
      instruction: "대화를 듣고, 여자가 사진 동아리를 그만두려는 이유를 고르시오.",
      lines: [
        ["M", "Hyewon, I heard you're leaving the photography club."],
        ["W", "It's true. I told the club president yesterday."],
        ["M", "Is it because the meetings moved to Thursday?"],
        ["W", "No, Thursday actually works better for me."],
        ["M", "Then did something happen with the members?"],
        ["W", "Not at all. Everyone there has been kind to me."],
        ["M", "So what is it?"],
        ["W", "My father is opening a small shop, and I help him every afternoon now."],
        ["M", "Every afternoon? That's a lot."],
        ["W", "It is, but it's only until he hires someone in the spring."],
      ],
      choices: [
        "모임 요일이 바뀌어서",
        "회원들과 사이가 나빠져서",
        "아버지 가게 일을 도와야 해서",
        "장비를 살 돈이 부족해서",
        "다른 동아리로 옮기고 싶어서",
      ],
      answer: 3,
      clue: "My father is opening a small shop, and I help him every afternoon now.",
      explanation:
        "여자는 요일이나 사람 문제는 아니라고 하고, 아버지가 가게를 열어 매일 오후에 돕는다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "M: 혜원아, 사진 동아리 그만둔다고 들었어.",
        "W: 맞아. 어제 동아리 회장한테 말했어.",
        "M: 모임이 목요일로 옮겨서 그래?",
        "W: 아니, 목요일이 오히려 나한테는 더 나아.",
        "M: 그럼 회원들이랑 무슨 일 있었어?",
        "W: 전혀. 다들 나한테 잘해 줬어.",
        "M: 그럼 뭐 때문이야?",
        "W: 아버지가 작은 가게를 여셔서 요즘 매일 오후에 도와 드려.",
        "M: 매일 오후에? 힘들겠다.",
        "W: 그렇긴 한데, 봄에 사람 구하실 때까지만이야.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "미언급",
      instruction: "대화를 듣고, 도시 텃밭 프로그램에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, did you read about the city garden program?"],
        ["M", "I saw the leaflet, but I haven't looked at the details."],
        ["W", "It runs from April to October, every Saturday morning."],
        ["M", "That's a long season. Where are the gardens?"],
        ["W", "Behind the community centre, on the land that used to be a parking lot."],
        ["M", "Oh, that's close to my house. Do they give us seeds?"],
        ["W", "Yes, seeds and tools are provided. You only bring gloves."],
        ["M", "That's convenient. Is there a fee?"],
        ["W", "Twenty thousand won for the whole season, and it includes the water."],
        ["M", "That's reasonable. How do I sign up?"],
        ["W", "I'm not sure. The leaflet didn't say anything about that."],
        ["M", "Then I'll ask at the office tomorrow."],
      ],
      choices: ["운영 기간", "장소", "제공되는 것", "참가비", "신청 방법"],
      answer: 5,
      clue: "I'm not sure. The leaflet didn't say anything about that.",
      explanation:
        "운영 기간(4월~10월 토요일 오전), 장소(주민센터 뒤), 제공되는 것(씨앗과 도구), 참가비(2만 원)는 언급되지만 신청 방법은 전단에 없어 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 도시 텃밭 프로그램 봤어?",
        "M: 전단은 봤는데 자세히는 안 읽었어.",
        "W: 4월부터 10월까지 매주 토요일 오전에 해.",
        "M: 기간이 기네. 텃밭은 어디야?",
        "W: 주민센터 뒤편, 예전에 주차장이던 땅이야.",
        "M: 아, 우리 집에서 가깝네. 씨앗은 주나?",
        "W: 응, 씨앗이랑 도구는 제공돼. 장갑만 가져가면 돼.",
        "M: 편하네. 참가비는 있어?",
        "W: 한 철에 2만 원이고 물값도 포함이야.",
        "M: 괜찮네. 신청은 어떻게 해?",
        "W: 그건 잘 모르겠어. 전단에 아무 말도 없더라.",
        "M: 그럼 내일 사무실에 물어봐야겠다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "내용 불일치",
      instruction: "Star Night Observation에 관한 다음 내용을 듣고, 일치하지 않는 것을 고르시오.",
      lines: [
        ["M", "Here is some information about this year's Star Night Observation."],
        ["M", "It will be held on the rooftop of the science building on October eighteenth."],
        ["M", "The program starts at seven in the evening and ends at ten."],
        ["M", "Three telescopes will be set up, and a science teacher will guide each one."],
        ["M", "Students may come alone or bring one family member."],
        ["M", "If the sky is cloudy, the program moves indoors and becomes a lecture."],
        ["M", "Sign up on the science department website by October fifteenth."],
      ],
      choices: [
        "과학관 옥상에서 열린다.",
        "저녁 일곱 시에 시작한다.",
        "망원경마다 교사가 안내한다.",
        "학생은 혼자만 참여할 수 있다.",
        "흐리면 실내 강연으로 바뀐다.",
      ],
      answer: 4,
      clue: "Students may come alone or bring one family member.",
      explanation:
        "학생은 혼자 와도 되고 가족 한 명을 데려와도 된다고 했으므로, 혼자만 참여할 수 있다는 ④가 내용과 일치하지 않는다.",
      translation: [
        "M: 올해 별 관측의 밤에 대해 알려 드리겠습니다.",
        "M: 10월 18일 과학관 옥상에서 열립니다.",
        "M: 프로그램은 저녁 일곱 시에 시작해 열 시에 끝납니다.",
        "M: 망원경 세 대가 설치되고, 과학 교사가 한 대씩 안내합니다.",
        "M: 학생은 혼자 와도 되고 가족 한 명을 데려와도 됩니다.",
        "M: 하늘이 흐리면 실내로 옮겨 강연으로 진행합니다.",
        "M: 신청은 10월 15일까지 과학부 누리집에서 받습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "표 선택",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 봉사 프로그램을 고르시오.",
      lines: [
        ["M", "Dain, here are the five volunteer programs open this month."],
        ["W", "Let's pick one we can both do. Weekdays are impossible for me."],
        ["M", "Then the Tuesday one is out. What else matters?"],
        ["W", "The hours. I can't do anything longer than four hours a day."],
        ["M", "That removes one more. Three are left."],
        ["W", "Do any of them require training before you start?"],
        ["M", "One does — it needs a two-day course first."],
        ["W", "We don't have time for that this month, so let's skip it."],
        ["M", "Then it's between these two. One is indoors, one is outdoors."],
        ["W", "It's already cold in the evenings. Let's take the indoor one."],
        ["M", "Agreed. I'll register both of us tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "It's already cold in the evenings. Let's take the indoor one.",
      explanation:
        "평일인 ①을 빼고, 4시간을 넘는 ②를 빼고, 사전 교육이 필요한 ⑤를 뺀다. 남은 ③과 ④ 중 실내인 것은 ③이므로 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "화요일 / 3시간 / 사전 교육 없음 / 실내" },
          { no: 2, label: "②", value: "토요일 / 6시간 / 사전 교육 없음 / 실내" },
          { no: 3, label: "③", value: "토요일 / 3시간 / 사전 교육 없음 / 실내" },
          { no: 4, label: "④", value: "일요일 / 4시간 / 사전 교육 없음 / 실외" },
          { no: 5, label: "⑤", value: "일요일 / 3시간 / 사전 교육 필요 / 실내" },
        ],
      },
      translation: [
        "M: 다인아, 이번 달에 열리는 봉사 프로그램이 이 다섯 개야.",
        "W: 둘 다 할 수 있는 걸로 고르자. 나는 평일은 안 돼.",
        "M: 그럼 화요일 건 빠지네. 또 뭐가 중요해?",
        "W: 시간. 하루에 네 시간 넘는 건 못 해.",
        "M: 그럼 하나 더 빠진다. 세 개 남았어.",
        "W: 시작 전에 교육을 받아야 하는 게 있어?",
        "M: 하나 있어. 이틀짜리 과정을 먼저 들어야 해.",
        "W: 이번 달엔 그럴 시간이 없으니까 빼자.",
        "M: 그럼 둘 중 하나네. 하나는 실내, 하나는 실외야.",
        "W: 저녁엔 벌써 춥잖아. 실내로 하자.",
        "M: 좋아. 오늘 밤에 둘 다 신청할게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "짧은 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Did you get your student ID photo taken today?"],
        ["W", "I went at lunchtime, but the booth was closed."],
        ["M", "Was there a notice on the door?"],
        ["W", "Just a small one. It said 'back soon', with no time."],
        ["M", "They usually take a break from twelve to one on Wednesdays."],
      ],
      choices: [
        "I already have my student ID card.",
        "The booth is on the fourth floor.",
        "Then I'll go after one o'clock tomorrow.",
        "You should smile in the photo.",
        "I took the photo at a shop downtown.",
      ],
      answer: 3,
      clue: "They usually take a break from twelve to one on Wednesdays.",
      explanation:
        "수요일 열두 시부터 한 시까지 쉰다는 말을 들었으므로, 내일 한 시 이후에 가겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 오늘 학생증 사진 찍었어?",
        "W: 점심때 갔는데 부스가 닫혀 있었어.",
        "M: 문에 안내가 붙어 있었어?",
        "W: 작은 거 하나. '곧 돌아옵니다'라고만 적혀 있고 시간은 없었어.",
        "M: 수요일에는 보통 열두 시부터 한 시까지 쉬어.",
        "W: 그럼 내일 한 시 넘어서 갈게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "짧은 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Are you still using the old locker on the second floor?"],
        ["M", "Yes, but the door doesn't close properly anymore."],
        ["W", "Did you report it to the office?"],
        ["M", "I wasn't sure whether they fix lockers or just replace them."],
        ["W", "They keep a few empty ones for cases like yours."],
      ],
      choices: [
        "My locker is next to the water fountain.",
        "I'll ask them for one of those tomorrow.",
        "The office closes at four thirty.",
        "I've used that locker since March.",
        "You can share my locker if you want.",
      ],
      answer: 2,
      clue: "They keep a few empty ones for cases like yours.",
      explanation:
        "사무실에 여분 사물함이 있다는 말을 들었으므로, 내일 그중 하나를 달라고 하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 2층에 있는 예전 사물함 아직 써?",
        "M: 응, 그런데 문이 이제 제대로 안 닫혀.",
        "W: 사무실에 얘기했어?",
        "M: 고쳐 주는지 그냥 바꿔 주는지 몰라서 말 안 했어.",
        "W: 너 같은 경우를 위해 빈 사물함을 몇 개 남겨 둬.",
        "M: 그럼 내일 하나 달라고 해 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "긴 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, how is the school garden club doing this term?"],
        ["W", "Not well. Only four people came to the last two meetings."],
        ["M", "It was twelve last year, wasn't it?"],
        ["W", "Thirteen. I keep asking myself what changed."],
        ["M", "When do you meet now?"],
        ["W", "Fridays at four, right after the last class."],
        ["M", "Isn't that when the buses for the outer neighbourhoods leave?"],
        ["W", "They leave at four fifteen. I hadn't connected the two."],
        ["M", "Half of our members live out that way."],
        ["W", "So they have to choose between the club and a two-hour trip home."],
        ["M", "Try a lunchtime meeting for a month and see who shows up."],
      ],
      choices: [
        "I'll ask the school to add another bus.",
        "We'll grow vegetables instead of flowers.",
        "That's worth trying. I'll announce it tomorrow.",
        "Only four members is enough for a small garden.",
        "Friday is the only day the garden is open.",
      ],
      answer: 3,
      clue: "Try a lunchtime meeting for a month and see who shows up.",
      explanation:
        "점심시간 모임을 한 달 해 보라는 제안을 들었으므로, 해 볼 만하다며 내일 알리겠다는 ③이 가장 적절하다.",
      translation: [
        "M: 예린아, 이번 학기 학교 텃밭 동아리는 어때?",
        "W: 잘 안 돼. 최근 두 번 모임에 네 명밖에 안 왔어.",
        "M: 작년엔 열두 명이었지?",
        "W: 열세 명. 뭐가 달라졌는지 계속 생각하고 있어.",
        "M: 지금은 언제 모여?",
        "W: 금요일 네 시, 마지막 수업 끝나고 바로.",
        "M: 그때 외곽 동네 가는 버스가 떠나지 않아?",
        "W: 네 시 십오 분에 떠나. 그 둘을 연결해서 생각을 못 했네.",
        "M: 우리 회원 절반이 그쪽에 살잖아.",
        "W: 그럼 동아리랑 두 시간짜리 귀갓길 중에 골라야 하는 거네.",
        "M: 한 달만 점심시간 모임으로 해 보고 누가 오는지 봐.",
        "W: 해 볼 만하네. 내일 알릴게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "긴 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sungmin, you've entered the same essay contest three years in a row."],
        ["M", "And I haven't won once. This year I almost didn't apply."],
        ["W", "What made you change your mind?"],
        ["M", "I reread what I wrote in my first year. It was terrible."],
        ["W", "That sounds discouraging, not encouraging."],
        ["M", "It would be, except that I could see exactly why it was bad."],
        ["W", "And two years ago you couldn't?"],
        ["M", "Back then I thought it was fine. That's the difference."],
        ["W", "So the contest taught you something even though you never won."],
      ],
      choices: [
        "I'll stop entering contests from now on.",
        "The judges should explain their decisions.",
        "Exactly. That's why I'm entering again.",
        "My first essay was about my grandmother.",
        "You should enter the contest this year too.",
      ],
      answer: 3,
      clue: "So the contest taught you something even though you never won.",
      explanation:
        "상을 못 받았어도 대회가 가르쳐 준 것이 있다는 말에, 그래서 다시 나간다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 성민아, 같은 글쓰기 대회에 3년 연속 나갔네.",
        "M: 그리고 한 번도 못 받았지. 올해는 안 낼 뻔했어.",
        "W: 왜 마음을 바꿨어?",
        "M: 1학년 때 쓴 글을 다시 읽어 봤는데 형편없더라.",
        "W: 그건 힘 빠지는 얘기지, 힘나는 얘기가 아니잖아.",
        "M: 그런데 왜 형편없는지가 정확히 보이더라고.",
        "W: 2년 전엔 안 보였어?",
        "M: 그때는 괜찮은 줄 알았지. 그게 차이야.",
        "W: 그럼 상은 못 받았어도 대회가 뭔가를 가르쳐 준 거네.",
        "M: 바로 그거야. 그래서 또 나가는 거고.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "상황 발화",
      instruction: "다음 상황 설명을 듣고, Mr. Kang이 Sujin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Mr. Kang : ________________",
      lines: [
        ["W", "Mr. Kang teaches the school orchestra, and Sujin plays the violin."],
        ["W", "Sujin practises more than anyone else in the group."],
        ["W", "At the last rehearsal, however, she played louder than the rest of the strings."],
        ["W", "She was not making mistakes; her notes were all correct."],
        ["W", "The problem was that the other violins could no longer hear themselves."],
        ["W", "Mr. Kang knows she is nervous about the concert next week."],
        ["W", "He does not want her to practise less or to doubt her skill."],
        ["W", "He wants her to listen to the players beside her and match their volume."],
        ["W", "In this situation, what would Mr. Kang most likely say to Sujin?"],
      ],
      choices: [
        "You need to practise your part more at home.",
        "Try listening to the players next to you and match them.",
        "Let's move your chair to the back row.",
        "Don't worry about the concert next week.",
        "You should play a solo piece instead.",
      ],
      answer: 2,
      clue: "He wants her to listen to the players beside her and match their volume.",
      explanation:
        "강 선생님은 수진의 실력이나 연습량을 문제 삼지 않고, 옆 연주자의 소리를 들으며 세기를 맞추라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 강 선생님은 학교 관현악부를 지도하고, 수진이는 바이올린을 켭니다.",
        "W: 수진이는 부원 중 누구보다 연습을 많이 합니다.",
        "W: 그런데 지난 연습에서 다른 현악기보다 소리를 크게 냈습니다.",
        "W: 틀린 것은 아니었습니다. 음은 모두 정확했습니다.",
        "W: 문제는 다른 바이올린들이 자기 소리를 들을 수 없게 된 것이었습니다.",
        "W: 강 선생님은 수진이가 다음 주 연주회를 앞두고 긴장한 것을 압니다.",
        "W: 연습을 줄이라거나 실력을 의심하게 하고 싶지는 않습니다.",
        "W: 다만 옆 사람의 소리를 들으며 세기를 맞추기를 바랍니다.",
        "W: 이런 상황에서 강 선생님이 수진이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
    {
      order: 16,
      type: "주제",
      instruction: "여자가 하는 말의 주제로 가장 적절한 것은?",
      lines: [
        ["W", "Good afternoon, everyone. Today I want to talk about sounds that help people concentrate."],
        ["W", "Many students believe that complete silence is the best condition for studying."],
        ["W", "For some people it is, but for many others silence works against them."],
        ["W", "In a perfectly quiet room, every small noise becomes an interruption."],
        ["W", "A door closing two floors down pulls your eyes off the page for several seconds."],
        ["W", "Rain recorded on a window covers those noises without carrying any meaning of its own."],
        ["W", "A distant fan makes a steady low sound, and your ears stop noticing it after a minute."],
        ["W", "Ocean waves rise and fall slowly, so your attention is never pulled to one single moment."],
        ["W", "A crackling fire works the same way, and many people say they find it calming."],
        ["W", "Notice that none of these are songs, and none of them contain words."],
        ["W", "A song with lyrics asks part of your mind to follow the story in it."],
        ["W", "What the sounds on my list share is that none of them ask you to listen."],
      ],
      choices: [
        "why silence is the best place to study",
        "how noise damages hearing over time",
        "the history of recorded nature sounds",
        "ways to make your room quieter",
        "background sounds that help concentration",
      ],
      answer: 5,
      clue: "Today I want to talk about sounds that help people concentrate.",
      explanation:
        "여자는 완전한 정적보다 빗소리, 선풍기 소리, 파도 소리, 장작 타는 소리처럼 귀를 끌지 않는 소리가 집중에 도움이 된다고 말한다. 따라서 주제는 ⑤이다.",
      translation: [
        "W: 안녕하세요. 오늘은 집중에 도움이 되는 소리에 대해 이야기하려고 합니다.",
        "W: 완전한 정적이 공부에 늘 가장 좋은 조건은 아닙니다.",
        "W: 조용한 방에서는 작은 소리 하나하나가 방해가 됩니다.",
        "W: 창문에 부딪히는 빗소리는 뜻을 담지 않은 채 그 소리들을 덮어 줍니다.",
        "W: 멀리서 도는 선풍기는 낮고 고른 소리를 내서 1분이면 귀가 알아채지 않게 됩니다.",
        "W: 파도 소리는 천천히 오르내려서 어느 한순간으로 주의가 끌리지 않습니다.",
        "W: 장작 타는 소리도 같은 식으로 작용해서 많은 사람이 편안하다고 느낍니다.",
        "W: 이들의 공통점은 어느 것도 귀 기울이라고 요구하지 않는다는 점입니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "언급 여부",
      instruction: "언급된 소리가 아닌 것은?",
      lines: [
        ["W", "Good afternoon, everyone. Today I want to talk about sounds that help people concentrate."],
        ["W", "Many students believe that complete silence is the best condition for studying."],
        ["W", "For some people it is, but for many others silence works against them."],
        ["W", "In a perfectly quiet room, every small noise becomes an interruption."],
        ["W", "A door closing two floors down pulls your eyes off the page for several seconds."],
        ["W", "Rain recorded on a window covers those noises without carrying any meaning of its own."],
        ["W", "A distant fan makes a steady low sound, and your ears stop noticing it after a minute."],
        ["W", "Ocean waves rise and fall slowly, so your attention is never pulled to one single moment."],
        ["W", "A crackling fire works the same way, and many people say they find it calming."],
        ["W", "Notice that none of these are songs, and none of them contain words."],
        ["W", "A song with lyrics asks part of your mind to follow the story in it."],
        ["W", "What the sounds on my list share is that none of them ask you to listen."],
      ],
      choices: ["rain", "a fan", "ocean waves", "birdsong", "a crackling fire"],
      answer: 4,
      clue: "Rain ... A distant fan ... Ocean waves ... A crackling fire",
      explanation:
        "빗소리, 선풍기 소리, 파도 소리, 장작 타는 소리는 언급되지만 새소리는 언급되지 않았다. 따라서 답은 ④이다.",
      translation: "16번과 같은 담화입니다.",
    },
  ],
};
