/** 고3 듣기 12회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "고3 듣기 12회",
  gradeLevel: "high3",
  speechSpeed: 0.8,
  folder: "고3 듣기",
  questions: [
    {
      order: 1,
      type: "목적 파악",
      instruction: "다음을 듣고, 여자가 하는 말의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, staff and students. This is the head of the science department."],
        ["W", "As you know, the third-floor laboratory has two doors, front and back."],
        ["W", "Until now, both doors have been used freely during class hours."],
        ["W", "Last week a student entered through the back door while an experiment was running."],
        ["W", "Nobody was hurt, but the back door opens right beside the burner bench."],
        ["W", "From Monday, the back door will be used only as an emergency exit."],
        ["W", "Please enter and leave through the front door, even if it takes longer."],
        ["W", "A sign will be posted, and teachers will remind you for the first week."],
      ],
      choices: [
        "실험실 사용 신청 방법을 안내하려고",
        "실험 기구 구입 계획을 알리려고",
        "안전 교육 참여를 요청하려고",
        "실험실 공사 일정을 공지하려고",
        "실험실 출입문 사용 방식의 변경을 알리려고",
      ],
      answer: 5,
      clue: "From Monday, the back door will be used only as an emergency exit.",
      explanation:
        "여자는 뒷문이 버너 작업대 바로 옆에서 열린다는 이유로, 월요일부터 뒷문을 비상구로만 쓰고 앞문으로 드나들라고 알린다. 따라서 말의 목적은 ⑤이다.",
      translation: [
        "W: 교직원과 학생 여러분, 안녕하십니까. 과학부장입니다.",
        "W: 아시다시피 3층 실험실에는 앞문과 뒷문, 두 개의 문이 있습니다.",
        "W: 지금까지는 수업 중에도 두 문을 자유롭게 썼습니다.",
        "W: 지난주에 실험이 진행 중일 때 한 학생이 뒷문으로 들어왔습니다.",
        "W: 다친 사람은 없었지만, 뒷문은 버너 작업대 바로 옆에서 열립니다.",
        "W: 월요일부터 뒷문은 비상구로만 씁니다.",
        "W: 조금 돌아가더라도 앞문으로 드나들어 주십시오.",
        "W: 안내문을 붙일 것이고, 첫 주에는 선생님들이 다시 알려 드리겠습니다.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "의견 파악",
      instruction: "대화를 듣고, 여자의 의견으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiwon, you've stopped using the study planner app, haven't you?"],
        ["W", "I have. I went back to a paper notebook last month."],
        ["M", "But the app showed you charts of how much you studied."],
        ["W", "It did, and that was the problem."],
        ["M", "How can seeing your progress be a problem?"],
        ["W", "I started studying to make the chart look good, not to understand things."],
        ["M", "So the number became the goal."],
        ["W", "Right. I'd choose easy chapters because they finished faster."],
        ["M", "And the notebook doesn't count anything."],
        ["W", "Exactly. It only asks what I understood today, and that's the right question."],
      ],
      choices: [
        "학습 기록은 자세할수록 도움이 된다.",
        "공부는 기록보다 이해를 기준으로 삼아야 한다.",
        "계획표는 종이로 쓰는 것이 편하다.",
        "쉬운 부분부터 공부해야 효율적이다.",
        "학습량은 매일 확인해야 한다.",
      ],
      answer: 2,
      clue: "It only asks what I understood today, and that's the right question.",
      explanation:
        "여자는 기록의 숫자를 좋게 만들려고 쉬운 부분만 골랐다며, 오늘 무엇을 이해했는지를 묻는 편이 옳다고 말한다. 따라서 의견은 ②이다.",
      translation: [
        "M: 지원아, 공부 계획 앱 안 쓰게 됐지?",
        "W: 응. 지난달에 종이 공책으로 돌아갔어.",
        "M: 그 앱은 네가 얼마나 공부했는지 그래프로 보여 줬잖아.",
        "W: 보여 줬지. 그게 문제였어.",
        "M: 진행 상황을 보는 게 왜 문제야?",
        "W: 이해하려고가 아니라 그래프를 좋게 만들려고 공부하게 됐어.",
        "M: 숫자가 목표가 된 거구나.",
        "W: 맞아. 빨리 끝나니까 쉬운 단원을 고르게 되더라.",
        "M: 공책은 아무것도 세지 않고.",
        "W: 그렇지. 오늘 뭘 이해했는지만 묻는데, 그게 맞는 질문이야.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "요지 파악",
      instruction: "다음을 듣고, 남자가 하는 말의 요지로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Before an interview, most people prepare answers to likely questions."],
        ["M", "They write them out and repeat them until the wording is smooth."],
        ["M", "Then the interviewer asks something slightly different, and the answer does not fit."],
        ["M", "Memorised sentences break the moment the question changes shape."],
        ["M", "Instead, prepare three stories from your own experience."],
        ["M", "A story can be told from many angles, and it bends to fit the question."],
        ["M", "Prepare material, not sentences. Material survives a question you did not expect."],
      ],
      choices: [
        "면접 답변은 외우기보다 경험을 준비해야 한다.",
        "면접은 예상 질문을 많이 준비해야 한다.",
        "면접에서는 말투가 가장 중요하다.",
        "면접 전에는 충분히 쉬어야 한다.",
        "면접 답변은 짧을수록 좋다.",
      ],
      answer: 1,
      clue: "Prepare material, not sentences.",
      explanation:
        "남자는 외운 문장은 질문이 조금만 달라져도 무너진다며, 여러 각도로 말할 수 있는 자기 경험 세 가지를 준비하라고 말한다. 따라서 요지는 ①이다.",
      translation: [
        "M: 면접 전에 대부분은 나올 법한 질문의 답을 준비합니다.",
        "M: 그것을 적어 두고 말이 매끄러워질 때까지 반복합니다.",
        "M: 그런데 면접관이 조금 다른 것을 물으면 답이 맞지 않습니다.",
        "M: 외운 문장은 질문의 모양이 바뀌는 순간 무너집니다.",
        "M: 대신 자기 경험에서 나온 이야기 세 가지를 준비하세요.",
        "M: 이야기는 여러 각도에서 말할 수 있고, 질문에 맞게 휘어집니다.",
        "M: 문장이 아니라 재료를 준비하세요. 재료는 예상 못 한 질문에서도 살아남습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "그림 불일치",
      instruction: "대화를 듣고, 그림에서 대화의 내용과 일치하지 않는 것을 고르시오.",
      lines: [
        ["M", "Chaerin, the study lounge is finally set up for the exam period."],
        ["W", "Good. I want students to find a seat without wandering around."],
        ["M", "On the wall at the back there's a wide panel with a clock face in the middle."],
        ["W", "Right. That one shows the remaining time in each study block."],
        ["M", "On the left I see three tall lamps standing in a row."],
        ["W", "Those replaced the ceiling lights, which were too bright at night."],
        ["M", "In the centre there's a long table with a divider down the middle."],
        ["W", "The divider lets two students sit facing each other without seeing each other."],
        ["M", "And by the door, is that a water cooler?"],
        ["W", "No, it's a coffee machine. The cooler is out in the hallway now."],
        ["M", "I see. On the right there's a shelf with two stacks of blankets."],
        ["W", "Perfect. Then we can open the lounge tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, it's a coffee machine. The cooler is out in the hallway now.",
      explanation:
        "여자는 문 옆에 있는 것이 정수기가 아니라 커피 기계라고 바로잡는다. 그림에는 정수기가 그려져 있으므로 ④가 대화와 일치하지 않는다.",
      figure: {
        kind: "labeled",
        scene:
          "A school study lounge seen from the front, five things clearly separated and none overlapping. " +
          "Upper centre on the back wall: a wide blank panel with a single round clock face drawn in its middle, hands only and no numbers. " +
          "Left side: three tall floor lamps standing in a row. " +
          "Centre: a long table with a flat divider board running down its middle. " +
          "Standing by the door at the right of the table: a tall WATER COOLER with a large bottle on top. " +
          "Far right: a shelf holding two neat stacks of folded blankets.",
      },
      translation: [
        "M: 채린아, 시험 기간용 자습 공간이 드디어 다 됐네.",
        "W: 좋아. 학생들이 돌아다니지 않고 자리를 찾을 수 있으면 해.",
        "M: 뒤쪽 벽에 가운데 시계판이 있는 넓은 판이 있네.",
        "W: 응. 자습 시간마다 남은 시간을 보여 주는 거야.",
        "M: 왼쪽에는 키 큰 스탠드 세 개가 한 줄로 서 있고.",
        "W: 밤에 너무 밝던 천장 조명 대신 놓은 거야.",
        "M: 가운데에는 한가운데에 칸막이가 있는 긴 탁자가 있네.",
        "W: 칸막이 덕분에 마주 앉아도 서로 안 보여.",
        "M: 그리고 문 옆에 있는 건 정수기야?",
        "W: 아니야, 커피 기계야. 정수기는 이제 복도에 있어.",
        "M: 그렇구나. 오른쪽에는 담요 두 무더기가 놓인 선반이 있네.",
        "W: 좋아. 그럼 오늘 밤부터 열 수 있겠다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "할 일",
      instruction: "대화를 듣고, 남자가 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunwoo, the university fair is on Friday and we have a scheduling problem."],
        ["M", "I thought all the booths were assigned last week."],
        ["W", "They were, but two universities asked for the same time slot for their talks."],
        ["M", "Can't they just use different rooms?"],
        ["W", "There's only one room with a microphone, and both talks need one."],
        ["M", "Then one of them has to move to a different hour."],
        ["W", "Exactly, and someone has to call them and explain."],
        ["M", "I can do that. I have a free period this afternoon."],
        ["W", "Thank you. Offer them ten o'clock or two o'clock as alternatives."],
        ["M", "I'll call both universities and confirm the new times."],
        ["W", "Then I'll update the programme sheet once you tell me."],
      ],
      choices: ["부스 배치하기", "마이크 빌려 오기", "안내지 인쇄하기", "대학에 전화해 시간 조정하기", "강의실 예약하기"],
      answer: 4,
      clue: "I'll call both universities and confirm the new times.",
      explanation:
        "남자는 오후에 빈 시간이 있어 두 대학에 전화해 시간을 조정하겠다고 한다. 안내지 수정은 여자가 맡는다. 따라서 답은 ④이다.",
      translation: [
        "W: 현우야, 대학 박람회가 금요일인데 일정에 문제가 생겼어.",
        "M: 부스는 지난주에 다 배정된 줄 알았는데.",
        "W: 배정은 됐는데, 두 대학이 설명회 시간을 같은 때로 신청했어.",
        "M: 다른 강의실을 쓰면 안 돼?",
        "W: 마이크가 있는 방이 하나뿐인데, 두 설명회 다 마이크가 필요해.",
        "M: 그럼 한쪽이 다른 시간으로 옮겨야겠네.",
        "W: 맞아. 그리고 누가 전화해서 설명해야 해.",
        "M: 내가 할게. 오늘 오후에 빈 시간이 있어.",
        "W: 고마워. 열 시나 두 시를 대안으로 제안해 줘.",
        "M: 두 대학에 다 전화해서 새 시간을 확정할게.",
        "W: 그럼 네가 알려 주면 내가 안내지를 고칠게.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "금액 계산",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the Namsan Bookbinding Shop. How can I help you?"],
        ["W", "I'd like to have my thesis printed and bound."],
        ["M", "Certainly. How many copies do you need?"],
        ["W", "Five copies, please."],
        ["M", "Printing is fourteen dollars per copy."],
        ["W", "All right. And what about the binding?"],
        ["M", "Hard binding is six dollars a copy, soft binding is two."],
        ["W", "Hard binding for all five, please. It's for the department."],
        ["M", "So that's seventy for printing and thirty for binding."],
        ["W", "One hundred dollars in total, then."],
        ["M", "Correct. And graduate students get fifteen percent off."],
        ["W", "Wonderful. Here's my student card."],
      ],
      choices: ["$80", "$85", "$90", "$95", "$100"],
      answer: 2,
      clue: "And graduate students get fifteen percent off.",
      explanation:
        "인쇄 14달러씩 다섯 부면 70달러, 하드 제본 6달러씩 다섯 부면 30달러로 합계 100달러이다. 학생 할인 15%를 빼면 100 × 0.85 = 85달러이므로 답은 ②이다.",
      translation: [
        "M: 남산 제본소입니다. 무엇을 도와드릴까요?",
        "W: 논문을 인쇄하고 제본하고 싶습니다.",
        "M: 네. 몇 부 필요하신가요?",
        "W: 다섯 부요.",
        "M: 인쇄는 한 부에 14달러입니다.",
        "W: 알겠습니다. 제본은요?",
        "M: 하드 제본은 한 부에 6달러, 소프트 제본은 2달러입니다.",
        "W: 다섯 부 다 하드 제본으로 해 주세요. 학과에 낼 거라서요.",
        "M: 그러면 인쇄가 70달러, 제본이 30달러입니다.",
        "W: 모두 100달러네요.",
        "M: 맞습니다. 그리고 대학원생은 15% 할인됩니다.",
        "W: 좋네요. 학생증 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "이유 파악",
      instruction: "대화를 듣고, 남자가 봉사 동아리 회장을 그만두려는 이유를 고르시오.",
      lines: [
        ["W", "Dohyun, I heard you're stepping down as head of the volunteer club."],
        ["M", "Yes. I told the members at yesterday's meeting."],
        ["W", "Is it because of your university applications?"],
        ["M", "Those are done. I submitted the last one on Friday."],
        ["W", "Then did something happen with the members?"],
        ["M", "Not at all. They've been wonderful this year."],
        ["W", "So what made you decide?"],
        ["M", "My family is moving to Gwangju in November, and I'll transfer schools."],
        ["W", "Gwangju? That's far."],
        ["M", "It is. I'd rather hand over now than leave in the middle of a project."],
      ],
      choices: [
        "대학 지원 준비 때문에",
        "회원들과 갈등이 있어서",
        "전학을 가게 되어서",
        "건강이 좋지 않아서",
        "다른 동아리를 맡게 되어서",
      ],
      answer: 3,
      clue: "My family is moving to Gwangju in November, and I'll transfer schools.",
      explanation:
        "대학 지원은 끝났고 회원 문제도 없지만, 11월에 광주로 이사해 전학을 가게 되어 그만둔다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "W: 도현아, 봉사 동아리 회장을 그만둔다고 들었어.",
        "M: 응. 어제 모임에서 회원들한테 말했어.",
        "W: 대학 지원 준비 때문이야?",
        "M: 그건 끝났어. 마지막 걸 금요일에 냈어.",
        "W: 그럼 회원들이랑 무슨 일 있었어?",
        "M: 전혀. 올해 다들 정말 좋았어.",
        "W: 그럼 왜 그런 결정을 했어?",
        "M: 우리 가족이 11월에 광주로 이사해서 전학을 가게 됐어.",
        "W: 광주? 멀다.",
        "M: 멀지. 일 중간에 떠나느니 지금 넘기는 게 나아.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "미언급",
      instruction: "대화를 듣고, 진로 상담 주간에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minseok, did you sign up for the career counselling week?"],
        ["M", "Not yet. When exactly is it?"],
        ["W", "The second week of November, from Monday to Thursday."],
        ["M", "Where do the sessions take place?"],
        ["W", "In the counselling room and two small rooms next to it."],
        ["M", "How long is one session?"],
        ["W", "Thirty minutes each, and you can book only one."],
        ["M", "Only one? Then I should think about what to ask."],
        ["W", "That's right. They also ask you to bring your record sheet."],
        ["M", "Anything else to prepare?"],
        ["W", "No, just the record sheet and your questions."],
        ["M", "All right. I'll sign up tonight."],
      ],
      choices: ["운영 기간", "장소", "상담 시간", "준비물", "상담 교사"],
      answer: 5,
      clue: "No, just the record sheet and your questions.",
      explanation:
        "운영 기간(11월 둘째 주 월~목), 장소(상담실과 옆 작은 방), 상담 시간(30분), 준비물(기록지)은 언급되지만 상담 교사는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민석아, 진로 상담 주간 신청했어?",
        "M: 아직. 정확히 언제야?",
        "W: 11월 둘째 주, 월요일부터 목요일까지.",
        "M: 어디서 해?",
        "W: 상담실이랑 그 옆 작은 방 두 개에서.",
        "M: 한 번에 얼마나 해?",
        "W: 30분씩이고, 한 번만 신청할 수 있어.",
        "M: 한 번만? 그럼 뭘 물을지 생각해야겠네.",
        "W: 맞아. 기록지도 가져오라고 해.",
        "M: 또 준비할 거 있어?",
        "W: 아니, 기록지랑 질문만.",
        "M: 알겠어. 오늘 밤에 신청할게.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "내용 불일치",
      instruction: "Winter Volunteer Tutoring에 관한 다음 내용을 듣고, 일치하지 않는 것을 고르시오.",
      lines: [
        ["M", "Let me explain this year's Winter Volunteer Tutoring programme in detail."],
        ["M", "The programme runs for six weeks, beginning in the second week of January."],
        ["M", "Volunteers teach elementary school students at the community centre near the park."],
        ["M", "Most of the children are in the fourth and fifth grades."],
        ["M", "Each volunteer works two afternoons a week, two hours each time."],
        ["M", "You may choose which two afternoons suit your own schedule."],
        ["M", "Teaching materials are provided, so you do not need to prepare your own."],
        ["M", "Volunteers must attend a two-hour training session before they start."],
        ["M", "The training covers how to explain things simply to younger students."],
        ["M", "Apply through the school website by the end of December."],
      ],
      choices: [
        "1월 둘째 주부터 6주 동안 진행된다.",
        "주민센터에서 초등학생을 가르친다.",
        "일주일에 두 번, 두 시간씩 한다.",
        "교재는 각자 준비해야 한다.",
        "시작 전에 사전 교육을 받아야 한다.",
      ],
      answer: 4,
      clue: "Teaching materials are provided, so you do not need to prepare your own.",
      explanation:
        "교재가 제공되어 따로 준비할 필요가 없다고 했으므로, 각자 준비해야 한다는 ④가 내용과 일치하지 않는다.",
      translation: [
        "M: 올해 겨울 봉사 학습 지도 프로그램을 설명드리겠습니다.",
        "M: 1월 둘째 주부터 6주 동안 진행됩니다.",
        "M: 봉사자는 주민센터에서 초등학생을 가르칩니다.",
        "M: 봉사자마다 일주일에 오후 두 번, 한 번에 두 시간씩 합니다.",
        "M: 교재는 제공되므로 따로 준비하지 않아도 됩니다.",
        "M: 봉사자는 시작 전에 두 시간짜리 사전 교육을 받아야 합니다.",
        "M: 신청은 12월 말까지 학교 누리집에서 받습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "표 선택",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 스터디 강좌를 고르시오.",
      lines: [
        ["W", "Junho, the institute sent us five study courses for the winter."],
        ["M", "Let's take one together. I can't do anything that starts before nine."],
        ["W", "All right, that removes one. How many weeks can you manage?"],
        ["M", "Four at most. After that I have the mock exam schedule."],
        ["W", "Then another is gone. Three left."],
        ["M", "Is any of them online only? I'd rather sit in a classroom."],
        ["W", "One is online only, so let's skip that."],
        ["M", "Two left. What about the class size?"],
        ["W", "One has thirty students, the other has twelve."],
        ["M", "Twelve sounds much better for asking questions."],
        ["W", "Agreed. I'll register us for the smaller one tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Twelve sounds much better for asking questions.",
      explanation:
        "8시 시작인 ①을 빼고, 6주인 ②를 빼고, 온라인 전용인 ③을 뺀다. 남은 ④와 ⑤ 중 정원이 12명인 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "오전 8시 / 4주 / 교실 수업 / 12명" },
          { no: 2, label: "②", value: "오전 10시 / 6주 / 교실 수업 / 12명" },
          { no: 3, label: "③", value: "오전 10시 / 4주 / 온라인 전용 / 12명" },
          { no: 4, label: "④", value: "오전 10시 / 4주 / 교실 수업 / 12명" },
          { no: 5, label: "⑤", value: "오전 11시 / 3주 / 교실 수업 / 30명" },
        ],
      },
      translation: [
        "W: 준호야, 학원에서 겨울 강좌 다섯 개를 보내 줬어.",
        "M: 같이 하나 듣자. 아홉 시 전에 시작하는 건 못 해.",
        "W: 알겠어, 그럼 하나 빠지네. 몇 주까지 가능해?",
        "M: 최대 4주. 그 뒤엔 모의고사 일정이 있어.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 온라인 전용인 건 있어? 나는 교실에 앉는 게 나아.",
        "W: 하나가 온라인 전용이야. 그건 빼자.",
        "M: 둘 남았네. 정원은?",
        "W: 하나는 서른 명, 다른 하나는 열두 명이야.",
        "M: 질문하기엔 열두 명이 훨씬 낫지.",
        "W: 좋아. 오늘 밤에 작은 쪽으로 신청할게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "짧은 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Did you submit the scholarship application?"],
        ["M", "I uploaded everything, but I never saw a confirmation."],
        ["W", "Did you check the message under the upload box?"],
        ["M", "There was a message? I closed the page right after uploading."],
        ["W", "It shows a receipt number that you're supposed to save."],
      ],
      choices: [
        "Then I'll log in again and look for it.",
        "The deadline was last Wednesday.",
        "I applied for two scholarships this year.",
        "My file was about three megabytes.",
        "You should apply before the deadline.",
      ],
      answer: 1,
      clue: "It shows a receipt number that you're supposed to save.",
      explanation:
        "접수 번호가 뜬다는 말을 들었으므로, 다시 로그인해서 찾아보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 장학금 신청서 냈어?",
        "M: 다 올리긴 했는데 확인 메시지를 못 봤어.",
        "W: 업로드 칸 아래 안내 확인했어?",
        "M: 안내가 있었어? 올리고 바로 창을 닫았는데.",
        "W: 저장해 둬야 하는 접수 번호가 떠.",
        "M: 그럼 다시 로그인해서 찾아볼게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "짧은 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Are you still looking for a quiet place to study on Sundays?"],
        ["W", "Yes. The public library is closed and the cafes are noisy."],
        ["M", "Have you tried the reading room at the community centre?"],
        ["W", "I thought that was only for residents over sixty."],
        ["M", "It used to be, but they opened it to students last spring."],
      ],
      choices: [
        "The library opens at nine on Saturdays.",
        "I usually study at home in the evening.",
        "Cafes are too expensive for me.",
        "You should apply for a member card.",
        "Then I'll go there this Sunday.",
      ],
      answer: 5,
      clue: "It used to be, but they opened it to students last spring.",
      explanation:
        "지난봄부터 학생에게도 열었다는 말을 들었으므로, 이번 일요일에 가 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "M: 일요일에 조용히 공부할 데 아직 찾고 있어?",
        "W: 응. 공공도서관은 문을 닫고 카페는 시끄러워.",
        "M: 주민센터 열람실은 가 봤어?",
        "W: 거긴 예순 넘은 주민만 쓰는 줄 알았는데.",
        "M: 예전엔 그랬는데 지난봄부터 학생에게도 열었어.",
        "W: 그럼 이번 일요일에 가 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "긴 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Soyeon, how did the mock interview go yesterday?"],
        ["W", "Badly. I forgot half of what I planned to say."],
        ["M", "What did you plan to say?"],
        ["W", "I had written out full answers to twelve questions."],
        ["M", "Twelve full answers? That's a lot to hold in your head."],
        ["W", "It is, and the first unexpected question knocked all of it loose."],
        ["M", "Did the interviewer say anything about your content?"],
        ["W", "She said my examples were good when I finally talked freely."],
        ["M", "So the free part went better than the memorised part."],
        ["W", "Much better, now that you put it that way."],
        ["M", "Then prepare three examples next time, not twelve answers."],
      ],
      choices: [
        "I'll write out twenty answers instead.",
        "The interviewer was too strict with me.",
        "That sounds right. I'll try it that way.",
        "I don't think interviews suit me at all.",
        "The interview lasted forty minutes.",
      ],
      answer: 3,
      clue: "Then prepare three examples next time, not twelve answers.",
      explanation:
        "열두 개의 답 대신 예시 세 개를 준비하라는 조언을 들었으므로, 그렇게 해 보겠다는 ③이 가장 적절하다.",
      translation: [
        "M: 소연아, 어제 모의 면접 어땠어?",
        "W: 망했어. 준비한 말의 절반을 잊어버렸어.",
        "M: 뭘 준비했는데?",
        "W: 질문 열두 개에 대한 답을 다 써 뒀었어.",
        "M: 열두 개를 통째로? 머리에 담기엔 많다.",
        "W: 많지. 예상 못 한 첫 질문에 전부 흐트러졌어.",
        "M: 면접관이 내용에 대해서는 뭐라고 했어?",
        "W: 내가 나중에 편하게 말할 때 예시가 좋다고 하셨어.",
        "M: 그럼 외운 부분보다 자유롭게 말한 부분이 나았네.",
        "W: 그렇게 말하니 훨씬 나았네.",
        "M: 그럼 다음엔 답 열두 개 말고 예시 세 개를 준비해.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "긴 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taemin, you've been solving the same problem set for two hours."],
        ["M", "I know. I'm stuck on question seven and I refuse to skip it."],
        ["W", "How many times have you started it over?"],
        ["M", "Four. Each time I get to the same line and stop."],
        ["W", "Have you looked at question eight or nine?"],
        ["M", "No. I don't want to move on until I solve this one."],
        ["W", "Sometimes a later question uses the same idea in an easier form."],
        ["M", "I never thought of using the next question as a hint."],
        ["W", "Try eight, then come back to seven with what you learn."],
      ],
      choices: [
        "I'll look at the answer key instead.",
        "Question seven is the hardest one.",
        "I've been studying for three hours.",
        "All right. I'll move on and come back.",
        "You should solve them in order.",
      ],
      answer: 4,
      clue: "Try eight, then come back to seven with what you learn.",
      explanation:
        "8번을 먼저 풀고 거기서 알게 된 것으로 7번에 돌아오라는 조언을 들었으므로, 넘어갔다가 돌아오겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 태민아, 두 시간째 같은 문제집을 붙잡고 있네.",
        "M: 알아. 7번에서 막혔는데 건너뛰기 싫어.",
        "W: 몇 번이나 다시 시작했어?",
        "M: 네 번. 매번 같은 줄에서 멈춰.",
        "W: 8번이나 9번은 봤어?",
        "M: 아니. 이걸 풀기 전엔 넘어가기 싫어.",
        "W: 가끔은 뒷 문제가 같은 개념을 더 쉬운 형태로 쓰기도 해.",
        "M: 다음 문제를 힌트로 쓴다는 생각은 못 했네.",
        "W: 8번을 풀어 보고, 거기서 알게 된 걸로 7번에 돌아와.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "상황 발화",
      instruction: "다음 상황 설명을 듣고, Ms. Jeong이 Hyunbin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Ms. Jeong : ________________",
      lines: [
        ["W", "Ms. Jeong is the homeroom teacher of a third-year class."],
        ["W", "Hyunbin is one of her students and has applied to five universities."],
        ["W", "He is a careful writer and his essays are honest and well organised."],
        ["W", "The first result comes out tomorrow, and he has not slept properly for a week."],
        ["W", "He keeps refreshing the admissions page even during breaks."],
        ["W", "Ms. Jeong knows he cannot change anything by checking the page."],
        ["W", "She does not want to tell him that the result does not matter, because it does."],
        ["W", "She wants him to put the phone away and sleep tonight."],
        ["W", "In this situation, what would Ms. Jeong most likely say to Hyunbin?"],
      ],
      choices: [
        "You should apply to more universities next time.",
        "Put the phone away tonight and get some sleep.",
        "Let's rewrite your essay before tomorrow.",
        "The result will not matter in the end.",
        "Try checking the page again after dinner.",
      ],
      answer: 2,
      clue: "She wants him to put the phone away and sleep tonight.",
      explanation:
        "정 선생님은 결과가 중요하지 않다고 말하지는 않으면서, 오늘 밤은 휴대폰을 내려놓고 자라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 정 선생님은 3학년 담임입니다.",
        "W: 현빈이는 그 반 학생이고 대학 다섯 곳에 지원했습니다.",
        "W: 글을 꼼꼼히 쓰는 학생이고, 자기소개서도 솔직하고 잘 짜여 있습니다.",
        "W: 첫 결과가 내일 나오는데, 일주일째 제대로 자지 못했습니다.",
        "W: 쉬는 시간마다 입학 누리집을 계속 새로고침합니다.",
        "W: 정 선생님은 누리집을 본다고 달라질 것이 없다는 걸 압니다.",
        "W: 결과가 중요하지 않다고 말하고 싶지는 않습니다. 실제로 중요하니까요.",
        "W: 다만 오늘 밤은 휴대폰을 내려놓고 자기를 바랍니다.",
        "W: 이런 상황에서 정 선생님이 현빈이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
    {
      order: 16,
      type: "주제",
      instruction: "남자가 하는 말의 주제로 가장 적절한 것은?",
      lines: [
        ["M", "Good afternoon. Today I want to talk about plants that catch insects."],
        ["M", "We usually think of plants as quiet things that only take in sunlight and water."],
        ["M", "But in soil without enough nitrogen, some plants had to find another source."],
        ["M", "The Venus flytrap closes its two leaves in less than a second when hairs are touched."],
        ["M", "The pitcher plant grows a deep tube filled with liquid that insects slide into."],
        ["M", "The sundew covers its leaves with sticky drops that look like morning dew."],
        ["M", "The bladderwort lives underwater and sucks tiny creatures into a hollow sac."],
        ["M", "None of these plants hunt because they are cruel; they hunt because the soil is poor."],
        ["M", "That is the part I find most interesting about them."],
      ],
      choices: [
        "how plants use sunlight to make food",
        "plants that trap and eat insects",
        "the importance of nitrogen in farming",
        "insects that damage garden plants",
        "how to grow plants in poor soil",
      ],
      answer: 2,
      clue: "Today I want to talk about plants that catch insects.",
      explanation:
        "남자는 파리지옥, 벌레잡이통풀, 끈끈이주걱, 통발이 질소가 부족한 흙 때문에 곤충을 잡는다고 소개한다. 따라서 주제는 ②이다.",
      translation: [
        "M: 안녕하세요. 오늘은 곤충을 잡는 식물에 대해 이야기하려고 합니다.",
        "M: 우리는 보통 식물을 햇빛과 물만 받아들이는 조용한 존재로 생각합니다.",
        "M: 그런데 질소가 부족한 흙에서는 어떤 식물은 다른 공급원을 찾아야 했습니다.",
        "M: 파리지옥은 털이 건드려지면 1초도 안 되어 두 잎을 닫습니다.",
        "M: 벌레잡이통풀은 액체가 담긴 깊은 통을 길러 곤충이 미끄러져 들어가게 합니다.",
        "M: 끈끈이주걱은 아침 이슬처럼 보이는 끈끈한 방울로 잎을 덮습니다.",
        "M: 통발은 물속에 살면서 작은 생물을 빈 주머니로 빨아들입니다.",
        "M: 이 식물들이 사냥하는 것은 잔인해서가 아니라 흙이 척박하기 때문입니다.",
        "M: 제가 가장 흥미롭게 여기는 부분이 바로 그 점입니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "언급 여부",
      instruction: "언급된 식물이 아닌 것은?",
      lines: [
        ["M", "Good afternoon. Today I want to talk about plants that catch insects."],
        ["M", "We usually think of plants as quiet things that only take in sunlight and water."],
        ["M", "But in soil without enough nitrogen, some plants had to find another source."],
        ["M", "The Venus flytrap closes its two leaves in less than a second when hairs are touched."],
        ["M", "The pitcher plant grows a deep tube filled with liquid that insects slide into."],
        ["M", "The sundew covers its leaves with sticky drops that look like morning dew."],
        ["M", "The bladderwort lives underwater and sucks tiny creatures into a hollow sac."],
        ["M", "None of these plants hunt because they are cruel; they hunt because the soil is poor."],
        ["M", "That is the part I find most interesting about them."],
      ],
      choices: ["Venus flytrap", "pitcher plant", "cobra lily", "sundew", "bladderwort"],
      answer: 3,
      clue: "The Venus flytrap closes its two leaves in less than a second when hairs are touched.",
      explanation:
        "파리지옥, 벌레잡이통풀, 끈끈이주걱, 통발은 언급되지만 코브라릴리는 언급되지 않았다. 따라서 답은 ③이다.",
      translation: "16번과 같은 담화입니다.",
    },
  ],
};
