/** 고3 듣기 11회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "고3 듣기 11회",
  gradeLevel: "high3",
  speechSpeed: 0.8,
  folder: "고3 듣기",
  questions: [
    {
      order: 1,
      type: "목적 파악",
      instruction: "다음을 듣고, 남자가 하는 말의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, members of the Hanbit Community Library. This is the head librarian."],
        ["M", "Many of you use our study rooms on the third floor every evening."],
        ["M", "Until now, anyone could take a room simply by writing a name on the door."],
        ["M", "Because of that, rooms are often held by people who never arrive."],
        ["M", "From the first of next month, rooms must be booked through our website."],
        ["M", "A booking will be cancelled if no one checks in within fifteen minutes."],
        ["M", "Members without internet access may still book at the front desk."],
        ["M", "We hope this makes the rooms easier to use for everyone."],
      ],
      choices: [
        "도서관 이용 시간 연장을 알리려고",
        "스터디룸 예약 방식의 변경을 알리려고",
        "도서관 회원 가입 절차를 안내하려고",
        "3층 공사로 인한 이용 제한을 알리려고",
        "누리집 점검 일정을 공지하려고",
      ],
      answer: 2,
      clue: "From the first of next month, rooms must be booked through our website.",
      explanation:
        "남자는 문에 이름만 적으면 되던 방식 때문에 빈 방이 잡혀 있는 일이 많다며, 다음 달부터 누리집으로 예약하고 15분 안에 오지 않으면 취소된다고 알린다. 따라서 말의 목적은 ②이다.",
      translation: [
        "M: 한빛 구립도서관 회원 여러분, 안녕하십니까. 도서관장입니다.",
        "M: 여러 분들이 저녁마다 3층 스터디룸을 이용하고 계십니다.",
        "M: 지금까지는 문에 이름만 적으면 누구나 방을 쓸 수 있었습니다.",
        "M: 그러다 보니 오지도 않는 사람이 방을 잡아 두는 일이 잦았습니다.",
        "M: 다음 달 1일부터는 누리집을 통해 예약하셔야 합니다.",
        "M: 예약 후 15분 안에 오지 않으면 예약은 취소됩니다.",
        "M: 인터넷을 쓰기 어려운 회원께서는 안내 데스크에서도 예약하실 수 있습니다.",
        "M: 이 변화로 모두가 방을 더 편하게 쓰게 되기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "의견 파악",
      instruction: "대화를 듣고, 남자의 의견으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Woojin, you've been rewriting your university application essay for weeks."],
        ["M", "Eleven drafts now. But the eleventh is shorter than the first."],
        ["W", "Shorter? I thought you were adding more about your activities."],
        ["M", "I was, and that was the problem. It read like a list."],
        ["W", "But the reader wants to know what you did, doesn't it?"],
        ["M", "They can see what I did on the record sheet already."],
        ["W", "So what should the essay do instead?"],
        ["M", "Show one moment closely enough that they understand why I kept going."],
        ["W", "One moment out of three years?"],
        ["M", "Yes. Ten sentences about one afternoon beat ten activities in one page."],
        ["W", "That's a braver choice than listing everything."],
      ],
      choices: [
        "자기소개서는 활동을 빠짐없이 적어야 한다.",
        "자기소개서는 한 장면을 깊이 보여 주는 편이 낫다.",
        "자기소개서는 여러 사람에게 검토받아야 한다.",
        "자기소개서보다 성적 관리가 더 중요하다.",
        "자기소개서는 짧을수록 좋은 평가를 받는다.",
      ],
      answer: 2,
      clue: "Ten sentences about one afternoon beat ten activities in one page.",
      explanation:
        "남자는 활동을 나열하면 목록처럼 읽힌다며, 한 장면을 충분히 보여 주어 왜 계속했는지 이해시키는 편이 낫다고 말한다. 따라서 의견은 ②이다.",
      translation: [
        "W: 우진아, 대학 자기소개서를 몇 주째 다시 쓰고 있네.",
        "M: 지금 열한 번째야. 그런데 열한 번째가 첫 번째보다 짧아.",
        "W: 짧다고? 활동을 더 넣는 줄 알았는데.",
        "M: 그랬지. 그게 문제였어. 목록처럼 읽히더라.",
        "W: 그래도 읽는 사람은 네가 뭘 했는지 알고 싶어 하지 않아?",
        "M: 내가 뭘 했는지는 기록지에서 이미 볼 수 있어.",
        "W: 그럼 자기소개서는 뭘 해야 하는데?",
        "M: 내가 왜 계속했는지 이해할 만큼 한 장면을 가까이 보여 주는 거지.",
        "W: 3년 중에 한 장면만?",
        "M: 응. 어느 오후에 대한 열 문장이 한 쪽에 담은 열 개 활동보다 나아.",
        "W: 전부 나열하는 것보다 용기 있는 선택이네.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "요지 파악",
      instruction: "다음을 듣고, 여자가 하는 말의 요지로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Most of you review a failed test by reading the answer key."],
        ["W", "You see the correct answer, nod, and feel that you understand."],
        ["W", "But that feeling comes from recognition, not from knowing."],
        ["W", "Recognition disappears the moment the paper is closed."],
        ["W", "So cover the key and solve the same question again from the beginning."],
        ["W", "If you can't, you have found exactly where your understanding stops."],
        ["W", "That point, not the answer, is what you should study tonight."],
      ],
      choices: [
        "시험은 자주 볼수록 실력이 는다.",
        "오답은 정답을 가리고 다시 풀어 보아야 한다.",
        "시험 직후에 복습하는 것이 가장 효과적이다.",
        "어려운 문제는 친구와 함께 풀어야 한다.",
        "해설지는 자세할수록 도움이 된다.",
      ],
      answer: 2,
      clue: "So cover the key and solve the same question again from the beginning.",
      explanation:
        "여자는 해설을 읽고 이해했다고 느끼는 것은 '알아본 것'일 뿐이라며, 정답을 가리고 처음부터 다시 풀어 어디서 막히는지 찾으라고 말한다. 따라서 요지는 ②이다.",
      translation: [
        "W: 여러분 대부분은 틀린 시험을 해설을 읽으며 복습합니다.",
        "W: 정답을 보고 고개를 끄덕이며 이해했다고 느끼지요.",
        "W: 그러나 그 느낌은 아는 것이 아니라 알아본 것에서 옵니다.",
        "W: 알아본 것은 종이를 덮는 순간 사라집니다.",
        "W: 그러니 해설을 가리고 같은 문제를 처음부터 다시 푸세요.",
        "W: 풀지 못한다면 여러분의 이해가 멈추는 지점을 정확히 찾은 것입니다.",
        "W: 오늘 밤 공부해야 할 것은 정답이 아니라 바로 그 지점입니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "그림 불일치",
      instruction: "대화를 듣고, 그림에서 대화의 내용과 일치하지 않는 것을 고르시오.",
      lines: [
        ["W", "Junyoung, the photo exhibition room is almost ready for tomorrow."],
        ["W", "I want visitors to move through it without asking where to start."],
        ["M", "On the wall at the back there's a wide panel with a camera outline in the middle."],
        ["W", "Right. That tells people the exhibition begins on that side."],
        ["M", "On the left I see three framed photographs hung in a row."],
        ["W", "Those are from the first-year students. I hung them at eye level."],
        ["M", "In the centre of the floor there's a bench facing the long wall."],
        ["W", "Visitors can sit there and look at the large print across from them."],
        ["M", "And by the entrance, is that a standing sign with a tall arrow on it?"],
        ["W", "No, it's a flat map of the room. We took the arrow sign away."],
        ["M", "I see. On the right there's a small table with a visitors' book on it."],
        ["W", "Perfect. Then we can open at ten tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, it's a flat map of the room. We took the arrow sign away.",
      explanation:
        "여자는 입구에 있는 것이 화살표가 그려진 안내판이 아니라 방의 평면도라고 바로잡는다. 그림에는 화살표 안내판이 그려져 있으므로 ④가 대화와 일치하지 않는다.",
      figure: {
        kind: "labeled",
        scene:
          "A school photo exhibition room seen from the front, five things clearly separated. " +
          "Upper centre on the back wall: a wide blank panel with a single camera outline drawn in its middle. " +
          "Left wall: three framed photographs hung in a row at the same height, each frame blank inside. " +
          "Centre of the floor: a long backless bench facing the long wall. " +
          "By the entrance at the right of the bench: a standing sign board with one large ARROW shape drawn on it. " +
          "Far right: a small table with an open blank visitors' book lying on it.",
      },
      translation: [
        "W: 준영아, 사진 전시실이 내일 준비가 거의 다 됐어.",
        "W: 관람객이 어디서 시작할지 묻지 않고 돌아볼 수 있으면 좋겠어.",
        "M: 뒤쪽 벽에 가운데 카메라 윤곽이 있는 넓은 판이 있네.",
        "W: 응. 전시가 그쪽에서 시작한다는 걸 알려 주는 거야.",
        "M: 왼쪽에는 액자에 넣은 사진 세 장이 한 줄로 걸려 있고.",
        "W: 1학년 학생들 작품이야. 눈높이에 맞춰 걸었어.",
        "M: 바닥 가운데에는 긴 벽을 바라보는 벤치가 있네.",
        "W: 거기 앉아서 맞은편의 큰 사진을 볼 수 있어.",
        "M: 그리고 입구 쪽에 있는 건 큰 화살표가 그려진 세움 간판이야?",
        "W: 아니야, 전시실 평면도야. 화살표 간판은 치웠어.",
        "M: 그렇구나. 오른쪽에는 방명록이 놓인 작은 탁자가 있네.",
        "W: 좋아. 그럼 내일 아침 열 시에 열 수 있겠다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "할 일",
      instruction: "대화를 듣고, 여자가 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyoung, the career talk is on Thursday and we still have a problem."],
        ["W", "Is the speaker not coming after all?"],
        ["M", "She's coming, but she asked for a projector that shows video with sound."],
        ["W", "The one in the seminar room only handles slides, doesn't it?"],
        ["M", "Exactly. No speakers at all."],
        ["W", "Can we borrow the portable one from the media centre?"],
        ["M", "We can, but someone has to fill in the form two days in advance."],
        ["W", "Two days? Then it has to be done today."],
        ["M", "I have physics lab until six, so I can't get to the media centre."],
        ["W", "All right. I'll go there after class and fill in the form."],
        ["M", "Thanks. Then I'll email the speaker and confirm the room number."],
      ],
      choices: ["강연자에게 메일 보내기", "물리 실험 준비하기", "대여 신청서 작성하기", "세미나실 예약하기", "발표 자료 인쇄하기"],
      answer: 3,
      clue: "I'll go there after class and fill in the form.",
      explanation:
        "남자는 물리 실험 때문에 갈 수 없어서, 여자가 수업 후 미디어센터에 가서 대여 신청서를 쓰기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 채영아, 진로 강연이 목요일인데 아직 문제가 있어.",
        "W: 강연자분이 결국 못 오시는 거야?",
        "M: 오시긴 하는데, 소리가 나오는 영상을 틀 수 있는 projector를 요청하셨어.",
        "W: 세미나실에 있는 건 슬라이드만 되지 않아?",
        "M: 맞아. 스피커가 아예 없어.",
        "W: 미디어센터에서 이동식으로 빌릴 수 있지 않아?",
        "M: 빌릴 수는 있는데 이틀 전에 신청서를 내야 해.",
        "W: 이틀? 그럼 오늘 해야겠네.",
        "M: 난 여섯 시까지 물리 실험이라 미디어센터에 못 가.",
        "W: 알겠어. 내가 수업 끝나고 가서 신청서 쓸게.",
        "M: 고마워. 그럼 나는 강연자분께 메일 보내서 강의실 번호를 알려 드릴게.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "금액 계산",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Good afternoon. Welcome to the Hanaro Print Shop."],
        ["M", "Hello. I'd like to print and bind four copies of my report."],
        ["W", "Certainly. Printing one copy costs twelve dollars."],
        ["M", "Four copies, then. And how much is the binding?"],
        ["W", "Simple binding is three dollars per copy."],
        ["M", "Let's do simple binding for all four."],
        ["W", "So that's forty-eight for printing and twelve for binding."],
        ["M", "Sixty dollars in total, then."],
        ["W", "Yes. And since you're a student, you get ten percent off."],
        ["M", "Great. Here's my student card."],
        ["W", "Thank you. They'll be ready in about thirty minutes."],
      ],
      choices: ["$48", "$52", "$54", "$58", "$60"],
      answer: 3,
      clue: "And since you're a student, you get ten percent off.",
      explanation:
        "인쇄 12달러씩 네 부면 48달러, 제본 3달러씩 네 부면 12달러로 합계 60달러이다. 학생 할인 10%를 빼면 60 × 0.9 = 54달러이므로 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 하나로 인쇄소입니다.",
        "M: 안녕하세요. 보고서를 네 부 인쇄하고 제본하고 싶습니다.",
        "W: 네. 한 부 인쇄에 12달러입니다.",
        "M: 그럼 네 부요. 제본은 얼마인가요?",
        "W: 간단 제본은 한 부에 3달러입니다.",
        "M: 네 부 모두 간단 제본으로 해 주세요.",
        "W: 그러면 인쇄가 48달러, 제본이 12달러입니다.",
        "M: 전부 60달러네요.",
        "W: 네. 학생이시니까 10% 할인해 드립니다.",
        "M: 좋네요. 학생증 여기 있습니다.",
        "W: 감사합니다. 30분쯤 뒤에 준비됩니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "이유 파악",
      instruction: "대화를 듣고, 남자가 모의 면접에 참여하지 못한 이유를 고르시오.",
      lines: [
        ["W", "Seokjin, you weren't at the mock interview session yesterday."],
        ["M", "I know. I was looking forward to it all week."],
        ["W", "Did the time change without notice?"],
        ["M", "No, I had the right time written down."],
        ["W", "Then were you sick? You looked tired on Tuesday."],
        ["M", "I'm fine now. My grandfather was moved to a hospital that morning."],
        ["W", "Oh, is he all right?"],
        ["M", "He's recovering. My parents were at work, so I went with him."],
        ["W", "Of course you did. Nobody would blame you for that."],
      ],
      choices: [
        "시간이 갑자기 바뀌어서",
        "몸이 아파서",
        "할아버지와 병원에 가야 해서",
        "면접 자료를 준비하지 못해서",
        "다른 학교 행사에 참여해서",
      ],
      answer: 3,
      clue: "My grandfather was moved to a hospital that morning.",
      explanation:
        "시간을 잘못 안 것도 아니고 본인이 아픈 것도 아니며, 그날 아침 할아버지가 병원으로 옮겨져 부모님 대신 따라갔다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "W: 석진아, 어제 모의 면접에 안 왔더라.",
        "M: 알아. 일주일 내내 기다렸는데.",
        "W: 시간이 말도 없이 바뀐 거야?",
        "M: 아니, 시간은 제대로 적어 뒀어.",
        "W: 그럼 아팠어? 화요일에 피곤해 보이던데.",
        "M: 지금은 괜찮아. 그날 아침에 할아버지가 병원으로 옮겨지셨어.",
        "W: 아, 괜찮으셔?",
        "M: 회복 중이셔. 부모님이 일하셔서 내가 따라갔어.",
        "W: 당연히 그랬겠지. 누구도 그걸 뭐라고 하지 않아.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "미언급",
      instruction: "대화를 듣고, 진로 특강에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dayeon, are you going to the career lecture next week?"],
        ["W", "I want to, but I don't know the details yet."],
        ["M", "It's on Thursday, from four to five thirty."],
        ["W", "That's right after school. Where is it held?"],
        ["M", "In the seminar room on the fourth floor, next to the library."],
        ["W", "Who is the speaker this time?"],
        ["M", "A civil engineer who graduated from our school twelve years ago."],
        ["W", "That sounds interesting. Do we need to bring anything?"],
        ["M", "Just a notebook. Everything else is provided."],
        ["W", "Good. How many students can attend?"],
        ["M", "Thirty, and about twenty have signed up already."],
        ["W", "Then I'd better register tonight."],
      ],
      choices: ["시간", "장소", "강연자", "준비물", "신청 마감일"],
      answer: 5,
      clue: "Thirty, and about twenty have signed up already.",
      explanation:
        "시간(목요일 4시~5시 30분), 장소(4층 세미나실), 강연자(졸업생 토목 기사), 준비물(공책)은 언급되지만 신청 마감일은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다연아, 다음 주 진로 특강 갈 거야?",
        "W: 가고 싶은데 아직 자세한 걸 몰라.",
        "M: 목요일 네 시부터 다섯 시 반까지야.",
        "W: 수업 끝나고 바로네. 어디서 해?",
        "M: 4층 세미나실, 도서관 옆이야.",
        "W: 이번 강연자는 누구야?",
        "M: 12년 전에 우리 학교를 졸업한 토목 기사야.",
        "W: 재미있겠다. 뭘 가져가야 해?",
        "M: 공책만. 나머지는 다 준비돼 있어.",
        "W: 좋네. 몇 명까지 들을 수 있어?",
        "M: 서른 명인데 벌써 스무 명쯤 신청했어.",
        "W: 그럼 오늘 밤에 신청해야겠다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "내용 불일치",
      instruction: "Winter Coding Marathon에 관한 다음 내용을 듣고, 일치하지 않는 것을 고르시오.",
      lines: [
        ["W", "Here is what you need to know about the Winter Coding Marathon."],
        ["W", "It will be held on December twentieth in the university gymnasium."],
        ["W", "Teams of three to five people may enter, but not individuals."],
        ["W", "The event runs for twelve hours, from nine in the morning until nine at night."],
        ["W", "Meals and drinks are provided at no extra cost."],
        ["W", "Teams must bring their own laptops and power cables."],
        ["W", "Registration closes on December tenth, and there is no entry fee."],
      ],
      choices: [
        "대학 체육관에서 열린다.",
        "개인으로도 참가할 수 있다.",
        "열두 시간 동안 진행된다.",
        "식사와 음료가 제공된다.",
        "노트북은 각자 가져와야 한다.",
      ],
      answer: 2,
      clue: "Teams of three to five people may enter, but not individuals.",
      explanation:
        "3~5명으로 이루어진 팀만 참가할 수 있고 개인 참가는 안 된다고 했으므로, 개인으로도 참가할 수 있다는 ②가 내용과 일치하지 않는다.",
      translation: [
        "W: 겨울 코딩 마라톤에 대해 알아 두실 것을 알려 드립니다.",
        "W: 12월 20일 대학 체육관에서 열립니다.",
        "W: 3명에서 5명으로 이루어진 팀만 참가할 수 있고 개인 참가는 안 됩니다.",
        "W: 행사는 오전 아홉 시부터 밤 아홉 시까지 열두 시간 동안 진행됩니다.",
        "W: 식사와 음료는 추가 비용 없이 제공됩니다.",
        "W: 노트북과 전원 케이블은 팀에서 직접 가져와야 합니다.",
        "W: 신청은 12월 10일에 마감되며 참가비는 없습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "표 선택",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 신청할 온라인 강좌를 고르시오.",
      lines: [
        ["W", "Minwoo, these are the five online courses the institute is offering."],
        ["M", "Let's take one together. Anything that starts in December is too late for me."],
        ["W", "All right, that removes one. What about the length?"],
        ["M", "Six weeks is the most I can manage before the exam period."],
        ["W", "Then another one is gone. Three are left."],
        ["M", "Do any of them have live classes at a fixed time?"],
        ["W", "One does, on Wednesday evenings."],
        ["M", "I have my part-time job then, so let's skip that one."],
        ["W", "Two left, and one of them gives a certificate at the end."],
        ["M", "That's worth having. Let's take the one with the certificate."],
        ["W", "Agreed. I'll register for both of us tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Let's take the one with the certificate.",
      explanation:
        "12월 시작인 ⑤를 빼고, 6주를 넘는 ①을 빼고, 수요일 저녁 실시간 수업이 있는 ②를 뺀다. 남은 ③과 ④ 중 수료증이 나오는 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "11월 시작 / 8주 / 실시간 수업 없음 / 수료증 있음" },
          { no: 2, label: "②", value: "11월 시작 / 6주 / 수요일 저녁 실시간 / 수료증 있음" },
          { no: 3, label: "③", value: "11월 시작 / 5주 / 실시간 수업 없음 / 수료증 없음" },
          { no: 4, label: "④", value: "11월 시작 / 6주 / 실시간 수업 없음 / 수료증 있음" },
          { no: 5, label: "⑤", value: "12월 시작 / 4주 / 실시간 수업 없음 / 수료증 있음" },
        ],
      },
      translation: [
        "W: 민우야, 학원에서 여는 온라인 강좌가 이 다섯 개야.",
        "M: 같이 하나 듣자. 12월에 시작하는 건 나한테는 너무 늦어.",
        "W: 알겠어, 그럼 하나 빠지네. 기간은 어때?",
        "M: 시험 기간 전까지는 6주가 최대야.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 정해진 시간에 실시간 수업이 있는 건 있어?",
        "W: 하나 있어. 수요일 저녁이야.",
        "M: 그때 아르바이트가 있어서 그건 빼자.",
        "W: 둘 남았는데, 그중 하나는 끝나면 수료증을 줘.",
        "M: 그건 있으면 좋지. 수료증 나오는 걸로 하자.",
        "W: 좋아. 오늘 밤에 둘 다 신청할게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "짧은 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Did you get the recommendation letter from Ms. Park?"],
        ["M", "Not yet. She said she needs my activity record first."],
        ["W", "Didn't you give it to her last Friday?"],
        ["M", "I sent the file, but I'm not sure it opened properly."],
        ["W", "She usually replies within a day when a file arrives."],
      ],
      choices: [
        "I'll check with her tomorrow morning, then.",
        "The letter should be two pages long.",
        "I met Ms. Park in the hallway yesterday.",
        "My activity record has six entries.",
        "You should ask another teacher instead.",
      ],
      answer: 1,
      clue: "She usually replies within a day when a file arrives.",
      explanation:
        "파일이 도착하면 하루 안에 답이 온다는 말을 들었으므로, 내일 아침에 확인해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 박 선생님께 추천서 받았어?",
        "M: 아직. 활동 기록부터 달라고 하셨어.",
        "W: 지난 금요일에 드리지 않았어?",
        "M: 파일은 보냈는데 제대로 열렸는지 모르겠어.",
        "W: 파일이 오면 보통 하루 안에 답을 주시는데.",
        "M: 그럼 내일 아침에 여쭤봐야겠다.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "짧은 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Are you still planning to visit the campus open day?"],
        ["W", "I registered, but the train tickets are all sold out."],
        ["M", "Did you check the express bus from the terminal?"],
        ["W", "I forgot there was one. I only looked at trains."],
        ["M", "It leaves every hour and takes about the same time."],
      ],
      choices: [
        "The open day is next Saturday.",
        "I'll look at the bus schedule right away.",
        "Trains are usually more comfortable.",
        "I've been to that campus before.",
        "You can register until Friday.",
      ],
      answer: 2,
      clue: "It leaves every hour and takes about the same time.",
      explanation:
        "고속버스가 한 시간마다 있고 시간도 비슷하다는 말을 들었으므로, 바로 버스 시간표를 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 대학 개방 행사에 가는 거 아직 계획대로야?",
        "W: 신청은 했는데 기차표가 다 매진이야.",
        "M: 터미널에서 출발하는 고속버스는 알아봤어?",
        "W: 그게 있다는 걸 잊었네. 기차만 봤어.",
        "M: 한 시간마다 있고 걸리는 시간도 비슷해.",
        "W: 바로 버스 시간표 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "긴 응답",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jihun, you've been studying in the library until closing every night."],
        ["M", "It's the only place where nobody talks to me."],
        ["W", "How many hours a night is that?"],
        ["M", "Five, sometimes six after dinner."],
        ["W", "And how much of that time are you actually solving problems?"],
        ["M", "Maybe three hours. The rest I spend rereading my notes."],
        ["W", "Rereading notes feels productive, but it's the easy part."],
        ["M", "I know. It's also the part I'm least afraid of."],
        ["W", "That's honest. But the exam won't ask you to recognize your notes."],
        ["M", "So you're saying I should cut the rereading."],
        ["W", "Cut it in half and put that hour into problems you got wrong."],
      ],
      choices: [
        "I'll stay at the library an hour longer.",
        "My notes are too long to reread anyway.",
        "All right. I'll try that starting tonight.",
        "The library closes at ten on weekdays.",
        "I'd rather study at home from now on.",
      ],
      answer: 3,
      clue: "Cut it in half and put that hour into problems you got wrong.",
      explanation:
        "노트 다시 읽는 시간을 절반으로 줄이고 그 시간을 틀린 문제에 쓰라는 조언을 들었으므로, 오늘 밤부터 해 보겠다는 ③이 가장 적절하다.",
      translation: [
        "W: 지훈아, 너 매일 밤 도서관 문 닫을 때까지 공부하더라.",
        "M: 아무도 말 안 거는 데가 거기뿐이라서.",
        "W: 하루에 몇 시간이나 되는데?",
        "M: 저녁 먹고 다섯 시간, 어떤 날은 여섯 시간.",
        "W: 그중에 실제로 문제 푸는 시간은 얼마나 돼?",
        "M: 세 시간쯤. 나머지는 노트 다시 읽어.",
        "W: 노트 다시 읽는 건 뭔가 한 것 같지만 쉬운 쪽이야.",
        "M: 알아. 제일 안 무서운 부분이기도 하고.",
        "W: 솔직하네. 그런데 시험은 네 노트를 알아보라고 묻지 않아.",
        "M: 그러니까 다시 읽는 걸 줄이라는 거지.",
        "W: 절반으로 줄이고 그 한 시간을 틀린 문제에 써.",
        "M: 알겠어. 오늘 밤부터 해 볼게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "긴 응답",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerim, are you presenting at the science symposium next month?"],
        ["W", "I submitted an abstract, but I'm thinking of withdrawing it."],
        ["M", "Why? Your experiment worked in the end."],
        ["W", "It worked, but only after I changed the method twice."],
        ["M", "Isn't that what research looks like?"],
        ["W", "Maybe, but the other presenters will have clean results."],
        ["M", "Have you read their abstracts?"],
        ["W", "No. I'm only imagining what they'll look like."],
        ["M", "Then you're comparing your process to their finished product."],
      ],
      choices: [
        "I'll withdraw the abstract this week.",
        "Their results are probably better than mine.",
        "You're right. I hadn't seen it that way.",
        "The symposium is held every two years.",
        "I changed the method three times, actually.",
      ],
      answer: 3,
      clue: "Then you're comparing your process to their finished product.",
      explanation:
        "자기 과정과 남의 완성된 결과를 비교하고 있다는 지적을 들었으므로, 그렇게 보지 못했다고 수긍하는 ③이 가장 자연스럽다.",
      translation: [
        "M: 예림아, 다음 달 과학 심포지엄에서 발표해?",
        "W: 초록은 냈는데 철회할까 생각 중이야.",
        "M: 왜? 실험은 결국 됐잖아.",
        "W: 되긴 했는데 방법을 두 번이나 바꾸고 나서야 됐어.",
        "M: 연구가 원래 그런 거 아니야?",
        "W: 그럴지도. 그런데 다른 발표자들은 깔끔한 결과를 가져올 거잖아.",
        "M: 그 사람들 초록은 읽어 봤어?",
        "W: 아니. 그냥 어떨지 상상만 하고 있어.",
        "M: 그럼 네 과정을 남의 완성된 결과랑 비교하는 거네.",
        "W: 네 말이 맞다. 그렇게는 생각 못 했어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "상황 발화",
      instruction: "다음 상황 설명을 듣고, Ms. Yoon이 Doyun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Ms. Yoon : ________________",
      lines: [
        ["M", "Ms. Yoon is the teacher in charge of the school debate team."],
        ["M", "Doyun has been on the team for two years and is one of its strongest speakers."],
        ["M", "This year, three first-year students joined the team for the first time."],
        ["M", "During practice, Doyun answers every question before they can try."],
        ["M", "He is not being unkind; he simply knows the answers and wants practice to move quickly."],
        ["M", "But the new members have stopped raising their hands at all."],
        ["M", "Ms. Yoon does not want to tell Doyun to stay silent, because his answers are good."],
        ["M", "She wants him to wait a few seconds so the younger students can speak first."],
        ["M", "In this situation, what would Ms. Yoon most likely say to Doyun?"],
      ],
      choices: [
        "Could you give the new members a few seconds before you answer?",
        "You should prepare your arguments more carefully.",
        "Let's move the practice to a bigger room.",
        "I think you need to join a different team.",
        "Try to answer the questions more quickly.",
      ],
      answer: 1,
      clue: "She wants him to wait a few seconds so the younger students can speak first.",
      explanation:
        "윤 선생님은 도윤이의 답이 좋다는 점을 인정하면서도, 새 부원들이 먼저 말할 수 있도록 몇 초만 기다려 달라고 말하려 한다. 따라서 ①이 가장 적절하다.",
      translation: [
        "M: 윤 선생님은 학교 토론부를 맡고 있습니다.",
        "M: 도윤이는 2년째 부원이고 가장 뛰어난 발표자 중 하나입니다.",
        "M: 올해는 1학년 세 명이 처음으로 토론부에 들어왔습니다.",
        "M: 연습 중에 도윤이는 후배들이 해 보기도 전에 모든 질문에 답합니다.",
        "M: 짓궂어서가 아니라, 답을 알고 있고 연습이 빨리 진행되기를 바라서입니다.",
        "M: 그런데 새 부원들은 이제 아예 손을 들지 않게 되었습니다.",
        "M: 윤 선생님은 도윤이의 답이 좋기 때문에 말하지 말라고 하고 싶지는 않습니다.",
        "M: 다만 후배들이 먼저 말할 수 있도록 몇 초만 기다려 주기를 바랍니다.",
        "M: 이런 상황에서 윤 선생님이 도윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
    {
      order: 16,
      type: "주제",
      instruction: "남자가 하는 말의 주제로 가장 적절한 것은?",
      lines: [
        ["M", "Good morning. Today I want to talk about materials that were invented by accident."],
        ["M", "We often imagine an inventor who plans every step and reaches a goal."],
        ["M", "In reality, several materials in this room began as failures."],
        ["M", "A weak glue that would not hold anything became the sticky note."],
        ["M", "A slippery coating spilled in a laboratory became the non-stick pan surface."],
        ["M", "A stiff fibre meant for tyres turned out to stop bullets, and it protects officers today."],
        ["M", "A soft plastic made while searching for rubber became a children's toy sold worldwide."],
        ["M", "In each case, someone noticed that the wrong result was useful for something else."],
        ["M", "That noticing, not the accident itself, is what made the invention possible."],
      ],
      choices: [
        "materials discovered by accident",
        "how modern laboratories are organized",
        "the dangers of chemical experiments",
        "famous inventors of the last century",
        "why most experiments end in failure",
      ],
      answer: 1,
      clue: "Today I want to talk about materials that were invented by accident.",
      explanation:
        "남자는 접착력이 약한 풀, 미끄러운 코팅, 질긴 섬유, 무른 플라스틱이 뜻하지 않게 쓸모를 찾은 사례를 소개한다. 따라서 주제는 ①이다.",
      translation: [
        "M: 안녕하세요. 오늘은 우연히 발명된 재료에 대해 이야기하려고 합니다.",
        "M: 우리는 흔히 모든 단계를 계획해 목표에 이르는 발명가를 떠올립니다.",
        "M: 그런데 이 방 안에 있는 몇몇 재료는 실패에서 시작했습니다.",
        "M: 아무것도 붙이지 못하던 약한 풀은 붙였다 떼는 쪽지가 되었습니다.",
        "M: 실험실에 쏟아진 미끄러운 코팅은 눌어붙지 않는 프라이팬 표면이 되었습니다.",
        "M: 타이어용으로 만든 뻣뻣한 섬유는 총알을 막는 것으로 밝혀져 오늘날 경찰을 지킵니다.",
        "M: 고무를 찾다가 만들어진 무른 플라스틱은 전 세계에 팔리는 어린이 장난감이 되었습니다.",
        "M: 어느 경우든 누군가가 잘못된 결과가 다른 데 쓸모 있다는 것을 알아챘습니다.",
        "M: 발명을 가능하게 한 것은 우연 자체가 아니라 그 알아챔이었습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "언급 여부",
      instruction: "언급된 물건이 아닌 것은?",
      lines: [
        ["M", "Good morning. Today I want to talk about materials that were invented by accident."],
        ["M", "We often imagine an inventor who plans every step and reaches a goal."],
        ["M", "In reality, several materials in this room began as failures."],
        ["M", "A weak glue that would not hold anything became the sticky note."],
        ["M", "A slippery coating spilled in a laboratory became the non-stick pan surface."],
        ["M", "A stiff fibre meant for tyres turned out to stop bullets, and it protects officers today."],
        ["M", "A soft plastic made while searching for rubber became a children's toy sold worldwide."],
        ["M", "In each case, someone noticed that the wrong result was useful for something else."],
        ["M", "That noticing, not the accident itself, is what made the invention possible."],
      ],
      choices: ["sticky notes", "non-stick pans", "safety glass", "protective vests", "a children's toy"],
      answer: 3,
      clue: "A weak glue that would not hold anything became the sticky note.",
      explanation:
        "붙였다 떼는 쪽지, 눌어붙지 않는 프라이팬, 방탄조끼, 어린이 장난감은 언급되지만 안전유리는 언급되지 않았다. 따라서 답은 ③이다.",
      translation: "16번과 같은 담화입니다.",
    },
  ],
};
