/** 중1 듣기 11회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 11회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 필통을 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a pencil case?"],
        ["W", "Yes. I'd like one with a zipper, not a button."],
        ["M", "All right. Do you want a round one or a flat one?"],
        ["W", "A flat one, please. Round ones don't fit in my bag."],
        ["M", "We have flat ones with stars, with stripes, and with no pattern."],
        ["W", "I already have a striped bag, so not stripes."],
        ["M", "Then stars or plain?"],
        ["W", "I'll take the one with stars on it."],
        ["M", "Good choice. I'll wrap it for you."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I'll take the one with stars on it.",
      explanation:
        "여자는 지퍼가 달린 납작한 필통을 원하고, 줄무늬는 빼고 별무늬를 고른다. 따라서 답은 ③이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five pencil cases shown side by side on a plain white background, each drawn separately. " +
          "First: a ROUND pencil case with a zipper and no pattern. " +
          "Second: a FLAT pencil case with a zipper and wide stripes. " +
          "Third: a FLAT pencil case with a zipper and small stars printed on it. " +
          "Fourth: a FLAT pencil case with a zipper and no pattern at all. " +
          "Fifth: a FLAT pencil case closed with a BUTTON and small stars on it.",
      },
      translation: [
        "M: 어서 오세요. 필통 찾으시나요?",
        "W: 네. 단추 말고 지퍼가 달린 걸로요.",
        "M: 알겠습니다. 둥근 것과 납작한 것 중 어떤 걸 원하세요?",
        "W: 납작한 거요. 둥근 건 가방에 안 들어가요.",
        "M: 납작한 건 별무늬, 줄무늬, 무늬 없는 것이 있습니다.",
        "W: 줄무늬 가방이 이미 있어서 줄무늬는 말고요.",
        "M: 그럼 별무늬나 무늬 없는 것 중에서요?",
        "W: 별무늬가 있는 걸로 할게요.",
        "M: 좋은 선택이세요. 포장해 드리겠습니다.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 마라톤 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minjun, are you running in the school marathon?"],
        ["M", "I want to. When is it?"],
        ["W", "It's on the second Saturday of October."],
        ["M", "Where does it start?"],
        ["W", "At the school gate, and it ends at the river park."],
        ["M", "How long is the course?"],
        ["W", "Five kilometers. It's not too hard."],
        ["M", "Do I have to pay anything?"],
        ["W", "No, it's free for all students."],
        ["M", "Then I'll sign up tomorrow."],
      ],
      choices: ["날짜", "출발 장소", "거리", "참가비", "준비물"],
      answer: 5,
      clue: "No, it's free for all students.",
      explanation:
        "날짜(10월 둘째 토요일), 출발 장소(학교 정문), 거리(5km), 참가비(무료)는 언급되지만 준비물은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민준아, 학교 마라톤 대회 나가?",
        "M: 나가고 싶어. 언제야?",
        "W: 10월 둘째 주 토요일이야.",
        "M: 어디서 출발해?",
        "W: 학교 정문에서 출발해서 강변 공원에서 끝나.",
        "M: 거리는 얼마나 돼?",
        "W: 5킬로미터야. 그렇게 힘들지 않아.",
        "M: 돈을 내야 해?",
        "W: 아니, 학생은 모두 무료야.",
        "M: 그럼 내일 신청할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sora. This is Taeyang. Are you at home?"],
        ["W", "Yes, I'm doing my homework. What's up?"],
        ["M", "I think I left my math notebook on your desk yesterday."],
        ["W", "Let me check. Oh, it's here under my science book."],
        ["M", "Great. Could you bring it to school tomorrow?"],
        ["W", "Sure. I'll put it in my bag right now."],
        ["M", "Thanks a lot. See you tomorrow."],
      ],
      choices: [
        "숙제를 물어보려고",
        "함께 공부하자고 제안하려고",
        "약속 시간을 바꾸려고",
        "두고 온 공책을 부탁하려고",
        "책을 빌려달라고 부탁하려고",
      ],
      answer: 4,
      clue: "Could you bring it to school tomorrow?",
      explanation:
        "남자는 여자의 책상에 두고 온 수학 공책을 내일 학교에 가져다 달라고 부탁하려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 소라야. 나 태양이야. 집이야?",
        "W: 응, 숙제하고 있어. 무슨 일이야?",
        "M: 어제 네 책상에 수학 공책을 두고 온 것 같아.",
        "W: 확인해 볼게. 아, 과학책 밑에 있네.",
        "M: 잘됐다. 내일 학교에 가져다줄 수 있어?",
        "W: 그럼. 지금 바로 가방에 넣을게.",
        "M: 정말 고마워. 내일 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yujin, did you book the tickets for tomorrow?"],
        ["W", "Yes, I got two seats in the middle row."],
        ["M", "Great. What time does the movie start?"],
        ["W", "It starts at 4:00 p.m., but there are ten minutes of ads first."],
        ["M", "Then let's meet thirty minutes before it starts."],
        ["W", "That's 3:30. But I want to buy popcorn before we go in."],
        ["M", "Good idea. The line at the snack bar is always long on Saturdays."],
        ["W", "Then let's meet twenty minutes earlier than that."],
        ["M", "Twenty minutes earlier? All right, that gives us plenty of time."],
        ["W", "See you in front of the theater, then."],
      ],
      choices: ["3:00 p.m.", "3:10 p.m.", "3:20 p.m.", "3:30 p.m.", "3:40 p.m."],
      answer: 2,
      clue: "Then let's meet twenty minutes earlier than that.",
      explanation:
        "영화가 4시에 시작하고 30분 전인 3시 30분에 만나기로 했다가, 팝콘을 사기 위해 20분 더 일찍 만나기로 했으므로 3시 10분이다. 따라서 답은 ②이다.",
      translation: [
        "M: 유진아, 영화 몇 시에 시작해?",
        "W: 오후 4시에 시작해.",
        "M: 그럼 시작 30분 전에 만나자.",
        "W: 3시 30분이네. 그런데 팝콘을 먼저 사고 싶어.",
        "M: 좋은 생각이야. 줄이 늘 길잖아.",
        "W: 그럼 그보다 20분 더 일찍 만나자.",
        "M: 20분 더 일찍? 알겠어.",
        "W: 극장 앞에서 보자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Haeun, you look so happy today. What happened?"],
        ["W", "My drawing was chosen for the school hallway!"],
        ["M", "Really? That's wonderful."],
        ["W", "I worked on it for three weeks after school."],
        ["M", "Which drawing is it?"],
        ["W", "The one with the old tree in front of the library."],
        ["M", "I remember that one. It was really good."],
        ["W", "They will hang it up on Monday morning."],
      ],
      choices: ["proud", "bored", "nervous", "sorry", "angry"],
      answer: 1,
      clue: "My drawing was chosen for the school hallway!",
      explanation:
        "여자는 3주 동안 그린 그림이 학교 복도에 걸리게 되었다고 기뻐하고 있다. 따라서 심정은 ①(자랑스러운)이다.",
      translation: [
        "M: 하은아, 오늘 정말 기분 좋아 보인다. 무슨 일이야?",
        "W: 내 그림이 학교 복도에 걸리기로 뽑혔어!",
        "M: 정말? 대단하다.",
        "W: 방과 후에 3주 동안 그렸어.",
        "M: 어떤 그림이야?",
        "W: 도서관 앞 오래된 나무를 그린 거야.",
        "M: 그거 기억나. 정말 잘 그렸더라.",
        "W: 월요일 아침에 걸어 준대.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, how much is this notebook?"],
        ["M", "It's two dollars."],
        ["W", "Do you know where the post office is?"],
        ["M", "Go straight and turn left."],
        ["W", "I dropped my umbrella. Can you help me?"],
        ["M", "Sure. Here it is."],
        ["W", "Can I take a picture here?"],
        ["M", "Sorry, photos are not allowed."],
        ["W", "This soup is too salty for me."],
        ["M", "I'll bring you another bowl."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I dropped my umbrella. Can you help me?",
      explanation:
        "그림은 한 사람이 바닥에 떨어진 우산을 주워 주는 장면이므로, 우산을 떨어뜨려 도움을 청하는 ③이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "A street scene: a woman has dropped her umbrella on the pavement and a man is bending down to pick it up and hand it back to her. Both are smiling politely. Simple background with a low wall and a street lamp.",
      },
      translation: [
        "① W: 실례합니다, 이 공책 얼마예요? / M: 2달러입니다.",
        "② W: 우체국이 어디 있는지 아세요? / M: 곧장 가서 왼쪽으로 도세요.",
        "③ W: 우산을 떨어뜨렸어요. 도와주시겠어요? / M: 그럼요. 여기 있습니다.",
        "④ W: 여기서 사진 찍어도 되나요? / M: 죄송하지만 사진은 안 됩니다.",
        "⑤ W: 이 국이 저한테는 너무 짜요. / M: 다른 것으로 가져다드릴게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, are you going to the school store after class?"],
        ["M", "Yes, I need to buy a new eraser."],
        ["W", "Could you buy a glue stick for me?"],
        ["M", "Sure. What kind do you need?"],
        ["W", "Just a small one. We need it for the poster tomorrow."],
        ["M", "All right. Do you want me to bring it to the club room?"],
        ["W", "Yes, please. I'll be there until five."],
        ["M", "No problem. I'll see you then."],
      ],
      choices: ["지우개 사기", "포스터 그리기", "풀 사기", "동아리방 청소하기", "숙제 도와주기"],
      answer: 3,
      clue: "Could you buy a glue stick for me?",
      explanation:
        "여자는 내일 포스터에 쓸 작은 풀을 사다 달라고 부탁한다. 따라서 답은 ③이다.",
      translation: [
        "W: 지호야, 수업 끝나고 학교 매점 가?",
        "M: 응, 지우개를 새로 사야 해.",
        "W: 나 풀 하나만 사다 줄 수 있어?",
        "M: 그럼. 어떤 거 필요해?",
        "W: 작은 거면 돼. 내일 포스터 만드는 데 필요해.",
        "M: 알겠어. 동아리방으로 가져다줄까?",
        "W: 응, 부탁해. 다섯 시까지 거기 있을 거야.",
        "M: 문제없어. 그때 보자.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Green Market에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about the Green Market."],
        ["M", "It will be held next Friday in the school playground."],
        ["M", "You can bring books, clothes, or toys you no longer use."],
        ["M", "Everything will be sold for one or two dollars."],
        ["M", "All the money will be sent to an animal shelter."],
        ["M", "Come and join us after lunch."],
      ],
      choices: ["열리는 날", "장소", "파는 물건", "가격", "참가 신청 방법"],
      answer: 5,
      clue: "All the money will be sent to an animal shelter.",
      explanation:
        "날짜(다음 주 금요일), 장소(학교 운동장), 파는 물건(책·옷·장난감), 가격(1~2달러)은 언급되지만 참가 신청 방법은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 그린 마켓에 대해 알려 드리겠습니다.",
        "M: 다음 주 금요일에 학교 운동장에서 열립니다.",
        "M: 더 이상 쓰지 않는 책, 옷, 장난감을 가져오시면 됩니다.",
        "M: 모든 물건은 1달러나 2달러에 팝니다.",
        "M: 모인 돈은 모두 동물 보호소에 보낼 예정입니다.",
        "M: 점심시간 후에 와서 함께해 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "This is something you use almost every morning."],
        ["W", "It has a handle and many short, soft lines at one end."],
        ["W", "You put a little paste on it before you use it."],
        ["W", "You move it up and down for about two minutes."],
        ["W", "Dentists say you should change it every three months."],
      ],
      choices: ["빗", "수건", "비누", "거울", "칫솔"],
      answer: 5,
      clue: "You put a little paste on it before you use it.",
      explanation:
        "손잡이가 있고 끝에 짧고 부드러운 털이 있으며, 치약을 묻혀 2분간 위아래로 움직이고 3개월마다 바꾸라고 했으므로 칫솔이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 이것은 거의 매일 아침에 쓰는 물건입니다.",
        "W: 손잡이가 있고 한쪽 끝에 짧고 부드러운 털이 많이 있습니다.",
        "W: 쓰기 전에 그 위에 무언가를 조금 바릅니다.",
        "W: 약 2분 동안 위아래로 움직입니다.",
        "W: 치과 의사들은 3개월마다 바꾸라고 말합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How was your weekend?"],
        ["W", "It was great. I went hiking."],
        ["M", "Can I borrow your pen?"],
        ["W", "Of course. Here you are."],
        ["M", "What time is the next bus?"],
        ["W", "I like riding the bus to school."],
        ["M", "Why are you late today?"],
        ["W", "I missed the first subway."],
        ["M", "Could you close the window?"],
        ["W", "Sure, no problem."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "What time is the next bus?",
      explanation:
        "다음 버스가 몇 시인지 묻는 말에 버스 타는 것을 좋아한다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① M: 주말 어땠어? / W: 좋았어. 등산 갔어.",
        "② M: 펜 좀 빌려줄래? / W: 물론이지. 여기 있어.",
        "③ M: 다음 버스가 몇 시야? / W: 나는 버스 타고 학교 가는 거 좋아해.",
        "④ M: 오늘 왜 늦었어? / W: 첫 지하철을 놓쳤어.",
        "⑤ M: 창문 좀 닫아 줄래? / W: 응, 그럴게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongjun, the class picnic is tomorrow. Is everything ready?"],
        ["M", "Almost. I packed the paper cups and the plates."],
        ["W", "What about the name tags for the games?"],
        ["M", "Oh no, I completely forgot about them."],
        ["W", "We need twenty-five of them."],
        ["M", "I'll make them right now before I go home."],
        ["W", "Thanks. I'll bring the markers tomorrow morning."],
        ["M", "Good. See you at the school gate at eight."],
      ],
      choices: ["종이컵 챙기기", "마커 사기", "집에 가기", "운동장 청소하기", "이름표 만들기"],
      answer: 5,
      clue: "I'll make them right now before I go home.",
      explanation:
        "남자는 잊고 있던 이름표를 집에 가기 전에 지금 바로 만들겠다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 동준아, 학급 소풍이 내일이야. 준비는 다 됐어?",
        "M: 거의. 종이컵이랑 접시는 챙겼어.",
        "W: 게임에 쓸 이름표는?",
        "M: 이런, 그건 완전히 잊고 있었어.",
        "W: 스물다섯 개 필요해.",
        "M: 집에 가기 전에 지금 바로 만들게.",
        "W: 고마워. 마커는 내가 내일 아침에 가져올게.",
        "M: 좋아. 여덟 시에 학교 정문에서 보자.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 가방을 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a school bag?"],
        ["W", "Yes. I don't want to spend more than forty dollars."],
        ["M", "All right. These are under forty."],
        ["W", "I also want one with a laptop pocket."],
        ["M", "Then this one is out. What about the color?"],
        ["W", "Any color is fine, but it has to be light."],
        ["M", "Light means under one kilogram, right?"],
        ["W", "Yes, exactly."],
        ["M", "Then there is only one left."],
        ["W", "Great. I'll take that one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Light means under one kilogram, right?",
      explanation:
        "40달러가 넘는 ⑤를 빼고, 노트북 주머니가 없는 ①·③을 뺀다. 남은 ②와 ④ 중 1kg 미만인 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "32달러 / 노트북 주머니 없음 / 0.8kg" },
          { no: 2, label: "②", value: "35달러 / 노트북 주머니 있음 / 1.2kg" },
          { no: 3, label: "③", value: "36달러 / 노트북 주머니 없음 / 0.9kg" },
          { no: 4, label: "④", value: "38달러 / 노트북 주머니 있음 / 0.9kg" },
          { no: 5, label: "⑤", value: "45달러 / 노트북 주머니 있음 / 0.7kg" },
        ],
      },
      translation: [
        "M: 어서 오세요. 책가방 찾으시나요?",
        "W: 네. 40달러 넘게는 쓰고 싶지 않아요.",
        "M: 알겠습니다. 이것들이 40달러 아래예요.",
        "W: 그리고 노트북 주머니가 있는 걸 원해요.",
        "M: 그럼 이건 빠지겠네요. 색깔은요?",
        "W: 색은 아무거나 괜찮은데 가벼워야 해요.",
        "M: 가볍다는 건 1킬로그램 미만을 말씀하시는 거죠?",
        "W: 네, 맞아요.",
        "M: 그럼 하나만 남네요.",
        "W: 좋아요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 박물관에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Minho, let's visit the science museum this month."],
        ["M", "Good idea. There's a robot exhibition until the end of the month."],
        ["W", "I heard about that. When can you go?"],
        ["M", "How about Saturday the tenth? I'm free all day."],
        ["W", "I have a piano lesson that morning, and it usually runs long."],
        ["M", "Then what about Sunday the eleventh?"],
        ["W", "The museum is closed on Sundays. I checked the website."],
        ["M", "Oh, right. What about the next Saturday, the seventeenth?"],
        ["W", "That works for me. My lesson is cancelled that week."],
        ["M", "Then let's go on that day. I'll buy the tickets online."],
      ],
      choices: ["10일", "11일", "16일", "17일", "18일"],
      answer: 4,
      clue: "What about the next Saturday, the seventeenth?",
      explanation:
        "10일은 피아노 수업, 11일은 휴관이어서 다음 주 토요일인 17일에 가기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 민호야, 이번 달에 과학 박물관에 가자.",
        "M: 좋아. 10일 토요일 어때?",
        "W: 그날은 피아노 수업이 있어.",
        "M: 그럼 11일 일요일은?",
        "W: 박물관은 일요일에 문을 닫아.",
        "M: 아, 맞다. 그다음 토요일인 17일은?",
        "W: 나는 괜찮아.",
        "M: 그럼 그날 가자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, did you go to the beach last weekend?"],
        ["W", "No, the weather wasn't good. It rained all Saturday."],
        ["M", "That's too bad. You planned that trip for weeks."],
        ["W", "I know. We'll go again when it gets warmer."],
        ["M", "Then what did you do instead?"],
        ["W", "I stayed home and baked cookies with my brother."],
        ["M", "Cookies? That sounds fun. Was it your first time?"],
        ["W", "His first time, not mine. We made three kinds together."],
        ["M", "Which one turned out best?"],
        ["W", "The lemon ones. I'll bring some to school tomorrow."],
      ],
      choices: ["바다에 가기", "쿠키 굽기", "영화 보기", "자전거 타기", "책 읽기"],
      answer: 2,
      clue: "I stayed home and baked cookies with my brother.",
      explanation:
        "여자는 날씨가 좋지 않아 바다에 가지 않고 집에서 남동생과 쿠키를 구웠다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "M: 수민아, 지난 주말에 바다 갔어?",
        "W: 아니, 날씨가 안 좋았어.",
        "M: 그럼 뭐 했어?",
        "W: 집에 있으면서 남동생이랑 쿠키를 구웠어.",
        "M: 쿠키? 재미있었겠다.",
        "W: 세 가지를 만들었는데 레몬 쿠키가 제일 맛있었어.",
        "M: 나도 먹어 보고 싶다.",
        "W: 내일 좀 가져올게.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, students. This is an announcement from the health room."],
        ["W", "Starting this week, the health room will move to the first floor."],
        ["W", "It will be next to the teachers' office, in room 105."],
        ["W", "The second-floor room will be used for club meetings instead."],
        ["W", "If you feel sick, please come to the new room."],
        ["W", "Thank you for listening."],
      ],
      choices: [
        "보건실 이용 규칙을 알리려고",
        "보건실 위치 변경을 알리려고",
        "동아리 모임을 안내하려고",
        "건강 검진 일정을 공지하려고",
        "교무실 방문을 당부하려고",
      ],
      answer: 2,
      clue: "Starting this week, the health room will move to the first floor.",
      explanation:
        "이번 주부터 보건실이 1층 105호로 옮긴다고 알리고 있으므로 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 보건실에서 알려 드립니다.",
        "W: 이번 주부터 보건실이 1층으로 옮깁니다.",
        "W: 교무실 옆 105호입니다.",
        "W: 2층에 있던 방은 대신 동아리 모임에 쓰입니다.",
        "W: 몸이 아프면 새 보건실로 와 주세요.",
        "W: 들어 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Welcome to the corner deli. What would you like?"],
        ["W", "Two sandwiches, please. How much are they?"],
        ["M", "They're six dollars each today."],
        ["W", "All right, two of those. And something to drink as well."],
        ["M", "We have orange juice and bottled water."],
        ["W", "One orange juice, please. How much is that?"],
        ["M", "The juice is three dollars."],
        ["W", "So that's fifteen dollars in total?"],
        ["M", "Yes, but students get two dollars off the whole order."],
        ["W", "Great. Here's my student card and my money."],
      ],
      choices: ["$12", "$13", "$14", "$15", "$16"],
      answer: 2,
      clue: "Yes, but students get two dollars off.",
      explanation:
        "샌드위치 6달러씩 두 개면 12달러, 주스 3달러를 더하면 15달러이다. 학생 할인 2달러를 빼면 13달러이므로 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 무엇을 드릴까요?",
        "W: 샌드위치 두 개 주세요. 얼마예요?",
        "M: 하나에 6달러입니다.",
        "W: 그리고 오렌지 주스 하나요.",
        "M: 주스는 3달러입니다.",
        "W: 그럼 전부 15달러인가요?",
        "M: 네, 그런데 학생은 2달러 할인됩니다.",
        "W: 좋네요. 학생증 여기 있어요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Jieun, you're carrying a lot of books today."],
        ["W", "I borrowed them from the city library for my history project."],
        ["M", "How many did you take out at once?"],
        ["W", "Six, and two of them are really thick."],
        ["M", "That looks heavy. Are you taking them all the way home?"],
        ["W", "Yes, but my bag is already full of my school things."],
        ["M", "I'm going the same way until the bus stop. Shall I carry some for you?"],
      ],
      choices: [
        "No, the library closes at six.",
        "I finished the project last week.",
        "You should return them on time.",
        "Thank you. That would really help.",
        "History is my favorite subject.",
      ],
      answer: 4,
      clue: "Shall I carry some for you?",
      explanation:
        "같은 방향으로 가니 책을 들어 주겠다는 제안에는 고맙다며 받아들이는 ④가 가장 자연스럽다.",
      translation: [
        "M: 지은아, 오늘 책을 많이 들고 다니네.",
        "W: 역사 과제 때문에 빌렸어.",
        "M: 무거워 보인다. 집에 가져가는 거야?",
        "W: 응, 그런데 가방은 이미 꽉 찼어.",
        "M: 나도 같은 방향으로 가는데, 몇 권 들어 줄까?",
        "W: 고마워. 정말 도움이 되겠다.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junho, did you water the classroom plants today?"],
        ["M", "Not yet. I was going to do it right after lunch."],
        ["W", "Come and look at the one by the window for a second."],
        ["M", "Oh, the leaves look a little dry already."],
        ["W", "That's what I meant. The soil is dry too."],
        ["M", "Really? I watered them the day before yesterday."],
        ["W", "The heater has been on all morning, so they dry faster than before."],
      ],
      choices: [
        "I'll go and water them right now.",
        "The plants are in the science room.",
        "We bought them last spring.",
        "I don't like taking care of plants.",
        "The heater is next to the window.",
      ],
      answer: 1,
      clue: "The heater has been on all morning, so they dry faster.",
      explanation:
        "난방 때문에 화분이 빨리 마른다는 말을 들었으므로, 지금 바로 물을 주겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 오늘 교실 화분에 물 줬어?",
        "M: 아직. 점심 먹고 주려고 했어.",
        "W: 잎이 벌써 조금 말라 보여.",
        "M: 정말? 그저께 줬는데.",
        "W: 아침 내내 난방이 켜져 있어서 더 빨리 마르나 봐.",
        "M: 지금 바로 가서 물 줄게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sohee, are you joining the singing contest next week?"],
        ["W", "I signed up last Friday, but I'm not sure about my song."],
        ["M", "Which one did you choose in the end?"],
        ["W", "A slow song my grandmother likes. I've practiced it all month."],
        ["M", "That sounds nice. Why are you worried, then?"],
        ["W", "Everyone else in my class picked fast ones."],
        ["M", "That's not a problem. A slow song can stand out more on a long program."],
        ["W", "Do you really think so?"],
        ["M", "Yes. Judges remember the one that sounds different from the rest."],
      ],
      choices: [
        "Then I'll keep my song as it is.",
        "I'll practice the fast song instead.",
        "The contest was last Friday.",
        "I don't know how to sing at all.",
        "You should sign up before Monday.",
      ],
      answer: 1,
      clue: "Judges remember the one that sounds different.",
      explanation:
        "느린 노래가 오히려 돋보인다는 말을 들었으므로, 고른 노래를 그대로 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 소희야, 노래 대회 나가?",
        "W: 신청은 했는데 노래가 마음에 걸려.",
        "M: 어떤 걸 골랐는데?",
        "W: 느린 노래야. 그런데 다들 빠른 노래를 골랐어.",
        "M: 그건 문제가 아니야. 느린 노래가 더 돋보일 수 있어.",
        "W: 정말 그럴까?",
        "M: 응. 심사위원은 다르게 들리는 걸 기억하거든.",
        "W: 그럼 고른 노래 그대로 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yuna가 Minsu에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Yuna : ________________",
      lines: [
        ["M", "Yuna and Minsu are classmates who sit next to each other."],
        ["M", "Today the class is doing a group presentation in the afternoon."],
        ["M", "Minsu has practiced his part many times at home."],
        ["M", "But he left his printed script on his desk at home this morning."],
        ["M", "Yuna has an extra copy of the same script in her folder."],
        ["M", "She wants to lend it to him before the class starts."],
        ["M", "In this situation, what would Yuna most likely say to Minsu?"],
      ],
      choices: [
        "Can you print it again after school?",
        "You can use my copy of the script.",
        "I'll do your part instead of you.",
        "Let's change the presentation date.",
        "Please bring your folder tomorrow.",
      ],
      answer: 2,
      clue: "She wants to lend it to him before the class starts.",
      explanation:
        "유나는 민수가 원고를 집에 두고 왔다는 것을 알고, 자신의 여분 원고를 빌려주려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 유나와 민수는 옆자리에 앉는 같은 반 친구입니다.",
        "M: 오늘 오후에 반에서 모둠 발표를 합니다.",
        "M: 민수는 집에서 자기 부분을 여러 번 연습했습니다.",
        "M: 그런데 오늘 아침에 인쇄한 원고를 집 책상에 두고 왔습니다.",
        "M: 유나는 같은 원고를 한 부 더 가지고 있습니다.",
        "M: 수업이 시작되기 전에 그것을 빌려주고 싶어 합니다.",
        "M: 이런 상황에서 유나가 민수에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
