/** 중1 듣기 43회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 43회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 우산을 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for an umbrella?"],
        ["M", "Yes, mine broke in the wind yesterday."],
        ["W", "Do you want a long one or a folding one?"],
        ["M", "A folding one. It goes in my school bag."],
        ["W", "This folding one has stripes on it."],
        ["M", "No stripes, please. A plain one is better."],
        ["W", "Would you like a strap on the handle?"],
        ["M", "Yes, a strap. Then I can hang it up."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A folding one. It goes in my school bag. / Yes, a strap. Then I can hang it up.",
      explanation:
        "남자는 접히고 무늬가 없으며 손잡이에 끈이 달린 우산을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five closed umbrellas laid side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a LONG umbrella with a curved handle and bold STRIPES. " +
          "② a LONG plain umbrella with a STRAP loop on the handle. " +
          "③ a short FOLDING umbrella covered in bold STRIPES. " +
          "④ a short PLAIN FOLDING umbrella with a STRAP loop on the handle. " +
          "⑤ a short PLAIN FOLDING umbrella with no strap at all.",
      },
      translation: [
        "W: 안녕하세요. 우산 찾으세요?",
        "M: 네, 어제 바람에 제 것이 부러졌어요.",
        "W: 긴 우산이 좋으세요, 접는 우산이 좋으세요?",
        "M: 접는 걸로요. 책가방에 들어가야 해요.",
        "W: 이 접는 우산은 줄무늬가 있어요.",
        "M: 줄무늬는 빼 주세요. 무늬 없는 게 나아요.",
        "W: 손잡이에 끈이 달린 건 어떠세요?",
        "M: 네, 끈이요. 그래야 걸어 둘 수 있어요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학급 장기 자랑에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dain, are you joining the class talent show?"],
        ["W", "I want to. When is it held?"],
        ["M", "Next Friday, in the fifth period."],
        ["W", "Where do we perform it?"],
        ["M", "In our classroom, in front of the board."],
        ["W", "How long can each person perform?"],
        ["M", "Three minutes, and then the next one starts."],
        ["W", "Can two people go together?"],
        ["M", "Yes, pairs are allowed this year."],
      ],
      choices: [
        "행사를 하는 날",
        "공연하는 곳",
        "한 사람의 공연 시간",
        "둘이 함께 할 수 있는지",
        "신청하는 방법",
      ],
      answer: 5,
      clue: "Next Friday, in the fifth period.",
      explanation:
        "날짜, 장소, 공연 시간, 짝 참가는 말했지만 신청 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 학급 장기 자랑 나갈 거야?",
        "W: 나가고 싶어. 언제 해?",
        "M: 다음 주 금요일 5교시에.",
        "W: 어디서 해?",
        "M: 우리 교실에서, 칠판 앞에서.",
        "W: 한 사람이 몇 분 해?",
        "M: 3분. 그다음 사람이 바로 이어서 해.",
        "W: 둘이 같이 나가도 돼?",
        "M: 응, 올해는 짝으로도 돼.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Minjun. It's Sohee. Is now a good time?"],
        ["M", "Sure. I just finished my homework."],
        ["W", "We were going to meet at two tomorrow."],
        ["M", "At the bus stop, right?"],
        ["W", "Yes, but my aunt is coming at one."],
        ["M", "So two would be too early for you."],
        ["W", "Could we meet at four instead?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속 시각을 바꾸려고",
        "물건을 빌리려고",
        "생일을 축하하려고",
        "길을 물어보려고",
      ],
      answer: 2,
      clue: "Could we meet at four instead?",
      explanation:
        "여자는 약속을 두 시에서 네 시로 바꾸려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 민준아. 소희야. 지금 통화 괜찮아?",
        "M: 응. 방금 숙제 끝냈어.",
        "W: 내일 두 시에 만나기로 했잖아.",
        "M: 버스 정류장에서, 맞지?",
        "W: 응, 그런데 한 시에 이모가 오셔.",
        "M: 그럼 두 시는 너한테 이르겠다.",
        "W: 대신 네 시에 만나도 될까?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Junho, when does the movie start?"],
        ["M", "There are showings at four and at five."],
        ["W", "My English class ends at four fifteen."],
        ["M", "Then the four o'clock one is out."],
        ["W", "How long does it take to the theater?"],
        ["M", "About fifteen minutes by bus."],
        ["W", "We also need time to buy the tickets."],
        ["M", "Let's meet at four thirty at the stop."],
        ["W", "Four thirty. I'll be there."],
      ],
      choices: ["4:00 p.m.", "4:15 p.m.", "4:30 p.m.", "5:00 p.m.", "4:45 p.m."],
      answer: 3,
      clue: "Let's meet at four thirty at the stop.",
      explanation:
        "수업이 4시 15분에 끝나 4시 30분에 정류장에서 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 준호야, 영화 몇 시에 시작해?",
        "M: 네 시랑 다섯 시 상영이 있어.",
        "W: 내 영어 수업이 4시 15분에 끝나.",
        "M: 그럼 네 시 상영은 안 되겠다.",
        "W: 극장까지 얼마나 걸려?",
        "M: 버스로 15분쯤.",
        "W: 표 사는 시간도 있어야 해.",
        "M: 4시 30분에 정류장에서 만나자.",
        "W: 4시 30분. 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, you keep smiling at your phone."],
        ["M", "My cousin is coming from Busan tomorrow."],
        ["W", "How long has it been since you saw him?"],
        ["M", "Two years. We were in the same class once."],
        ["W", "How long is he staying?"],
        ["M", "A whole week, right here in my room."],
        ["W", "Do you have a plan for the week?"],
        ["M", "I've been making one since last night."],
      ],
      choices: ["excited", "worried", "bored", "sorry", "angry"],
      answer: 1,
      clue: "I've been making one since last night.",
      explanation:
        "2년 만에 사촌이 와서 계획까지 세우며 들떠 있다. 따라서 답은 ①이다.",
      translation: [
        "W: 도현아, 휴대폰 보면서 계속 웃네.",
        "M: 내일 부산에서 사촌이 와.",
        "W: 못 본 지 얼마나 됐어?",
        "M: 2년. 한때 같은 반이었어.",
        "W: 얼마나 머물러?",
        "M: 일주일 내내. 바로 내 방에서.",
        "W: 그 주에 뭐 할지 계획 있어?",
        "M: 어젯밤부터 짜고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Is this seat free?"],
        ["W", "Yes, please sit here."],
        ["ANN", "Number two."],
        ["M", "What time does the train leave?"],
        ["W", "In about ten minutes."],
        ["ANN", "Number three."],
        ["M", "You dropped your glove."],
        ["W", "Oh, thank you so much."],
        ["ANN", "Number four."],
        ["M", "Which way is the exit?"],
        ["W", "Down the stairs on the left."],
        ["ANN", "Number five."],
        ["M", "Is this bus going to the park?"],
        ["W", "No, take the next one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "You dropped your glove.",
      explanation:
        "그림은 길에서 남학생이 떨어진 장갑을 주워 건네는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "On a winter street, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy student bends down and picks up a single glove from the pavement, holding it out with one hand. " +
          "A woman walking just ahead turns back with a surprised, grateful expression and reaches for it. " +
          "A bare tree and a low wall are drawn simply behind them.",
      },
      translation: [
        "① M: 이 자리 비었나요? / W: 네, 여기 앉으세요.",
        "② M: 기차 몇 시에 떠나요? / W: 10분쯤 뒤에요.",
        "③ M: 장갑 떨어뜨리셨어요. / W: 아, 정말 고맙습니다.",
        "④ M: 출구가 어느 쪽이에요? / W: 왼쪽 계단 아래로요.",
        "⑤ M: 이 버스 공원 가나요? / W: 아니요, 다음 걸 타세요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, do you sit next to the window in music class?"],
        ["W", "Yes, in the second row by the piano."],
        ["M", "I have to go to the dentist tomorrow."],
        ["W", "Will you miss the whole class?"],
        ["M", "Only the first half of it."],
        ["W", "We're learning a new song tomorrow."],
        ["M", "That's the part I'll miss completely."],
        ["W", "I could write down what we do."],
        ["M", "Could you record the song for me?"],
        ["W", "Sure, I'll send it after class."],
      ],
      choices: [
        "노래를 녹음해 주기",
        "자리를 바꿔 주기",
        "병원에 같이 가 주기",
        "악보를 빌려주기",
        "선생님께 말씀드리기",
      ],
      answer: 1,
      clue: "Could you record the song for me?",
      explanation:
        "남자는 새로 배우는 노래를 녹음해 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 예린아, 음악 시간에 창가에 앉지?",
        "W: 응, 피아노 옆 둘째 줄에.",
        "M: 내일 치과에 가야 해.",
        "W: 수업 전체를 빠져?",
        "M: 앞 절반만.",
        "W: 내일 새 노래 배우는데.",
        "M: 그게 딱 내가 못 듣는 부분이야.",
        "W: 뭘 했는지 적어 줄 수도 있어.",
        "M: 노래 좀 녹음해 줄래?",
        "W: 그래, 수업 끝나고 보내 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 활동에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. We start the school garden this month. " +
            "The garden is behind the gym, next to the fence. " +
            "Each class works there for one hour on Wednesday. " +
            "We will plant lettuce, beans and small tomatoes. " +
            "Bring gloves on the day your class goes. " +
            "The teacher will hand out the small shovels.",
        ],
      ],
      choices: [
        "텃밭이 있는 곳",
        "활동하는 요일",
        "심는 작물",
        "가져와야 할 것",
        "수확하는 시기",
      ],
      answer: 5,
      clue: "The garden is behind the gym, next to the fence.",
      explanation:
        "위치, 요일, 작물, 준비물은 말했지만 수확 시기는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 이번 달에 학교 텃밭을 시작합니다. 텃밭은 체육관 뒤 울타리 옆에 있습니다. 각 반은 수요일에 한 시간씩 그곳에서 일합니다. 상추, 콩, 작은 토마토를 심습니다. 우리 반이 가는 날에는 장갑을 가져오세요. 작은 삽은 선생님이 나눠 주십니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a small machine you keep in the kitchen. " +
            "You put bread in the top and push the handle down. " +
            "It gets hot inside and the bread turns brown. " +
            "After a minute or two the bread pops up. " +
            "If you leave it too long, the bread burns.",
        ],
      ],
      choices: ["냉장고", "전자레인지", "토스터", "세탁기", "선풍기"],
      answer: 3,
      clue: "You put bread in the top and push the handle down.",
      explanation:
        "빵을 넣고 손잡이를 내리면 구워져 튀어 오르는 기계는 토스터이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 부엌에 두는 작은 기계입니다. 위쪽에 빵을 넣고 손잡이를 아래로 누릅니다. 안이 뜨거워지면서 빵이 갈색으로 변합니다. 1~2분 뒤에 빵이 톡 튀어 오릅니다. 너무 오래 두면 빵이 탑니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How was your weekend?"],
        ["M", "Quiet, but I liked it."],
        ["ANN", "Number two."],
        ["W", "Where do you live?"],
        ["M", "Near the middle school."],
        ["ANN", "Number three."],
        ["W", "May I open the window?"],
        ["M", "Sure, it's warm in here."],
        ["ANN", "Number four."],
        ["W", "Whose bag is this?"],
        ["M", "I ate lunch at twelve."],
        ["ANN", "Number five."],
        ["W", "Are you ready to go?"],
        ["M", "Give me one minute."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Whose bag is this?",
      explanation:
        "누구의 가방인지 묻는 말에 점심 먹은 시각을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 주말 어땠어? / M: 조용했는데 좋았어.",
        "② W: 어디 살아? / M: 중학교 근처에.",
        "③ W: 창문 열어도 돼? / M: 그럼, 여기 덥다.",
        "④ W: 이거 누구 가방이야? / M: 나는 열두 시에 점심 먹었어.",
        "⑤ W: 갈 준비 됐어? / M: 1분만 줘.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangmin, did you water the class plant today?"],
        ["M", "I forgot about it completely."],
        ["W", "Whose turn was it this week?"],
        ["M", "Mine, from Monday to Friday."],
        ["W", "The leaves looked a little dry this morning."],
        ["M", "Is there water in the bottle by the window?"],
        ["W", "It's half full, and we leave in ten minutes."],
        ["M", "I'll water the plant right now."],
      ],
      choices: [
        "물병을 채우기",
        "화분에 물을 주기",
        "창문을 닫기",
        "선생님께 말씀드리기",
        "교실을 청소하기",
      ],
      answer: 2,
      clue: "I'll water the plant right now.",
      explanation:
        "남자는 지금 바로 화분에 물을 주겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 상민아, 오늘 학급 화분에 물 줬어?",
        "M: 완전히 잊고 있었어.",
        "W: 이번 주 누구 차례였어?",
        "M: 내 차례. 월요일부터 금요일까지.",
        "W: 아침에 잎이 좀 말라 보였어.",
        "M: 창가 물병에 물 있어?",
        "W: 절반쯤. 10분 뒤에 나가.",
        "M: 지금 바로 물 줄게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 물병을 고르시오.",
      lines: [
        ["M", "Nayeon, which water bottle are you buying?"],
        ["W", "There are five on this shelf."],
        ["M", "How big do you need it?"],
        ["W", "At least five hundred milliliters."],
        ["M", "Two of them are smaller than that."],
        ["W", "And I want one with a strap."],
        ["M", "One of the bigger ones has no strap."],
        ["W", "The price should be under ten thousand won."],
        ["M", "Then only one is left for you."],
        ["W", "I'll take that one, thanks."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "At least five hundred milliliters.",
      explanation:
        "500밀리리터 이상, 끈이 있고, 1만 원 미만인 것을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Size: 350 ml / Strap: Yes / Price: 8,000 won" },
          { no: 2, label: "②", value: "Size: 400 ml / Strap: Yes / Price: 9,000 won" },
          { no: 3, label: "③", value: "Size: 600 ml / Strap: No / Price: 7,000 won" },
          { no: 4, label: "④", value: "Size: 700 ml / Strap: Yes / Price: 12,000 won" },
          { no: 5, label: "⑤", value: "Size: 500 ml / Strap: Yes / Price: 9,500 won" },
        ],
      },
      translation: [
        "M: 나연아, 어떤 물병 살 거야?",
        "W: 이 선반에 다섯 개 있어.",
        "M: 얼마나 큰 게 필요해?",
        "W: 적어도 500밀리리터.",
        "M: 두 개는 그보다 작아.",
        "W: 그리고 끈이 달린 게 좋아.",
        "M: 큰 것 중 하나는 끈이 없어.",
        "W: 값은 1만 원 아래여야 해.",
        "M: 그럼 하나만 남네.",
        "W: 그걸로 할게, 고마워.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taemin, when should we go to the animal shelter?"],
        ["M", "They take students on weekends only."],
        ["W", "This month's weekends are the fifth and the twelfth."],
        ["M", "The fifth is my brother's birthday."],
        ["W", "Then the twelfth is better for you."],
        ["M", "Is there another weekend after that?"],
        ["W", "The nineteenth, but the shelter is closed then."],
        ["M", "Closed on a weekend? That's unusual."],
        ["W", "They clean the whole building that day."],
        ["M", "So the twelfth is the only real choice."],
      ],
      choices: ["the 5th", "the 12th", "the 19th", "the 26th", "the 2nd"],
      answer: 2,
      clue: "So the twelfth is the only real choice.",
      explanation:
        "5일은 동생 생일, 19일은 보호소 휴관이어서 12일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 태민아, 동물 보호소 언제 갈까?",
        "M: 거기는 주말에만 학생을 받아.",
        "W: 이번 달 주말은 5일이랑 12일이야.",
        "M: 5일은 동생 생일이야.",
        "W: 그럼 12일이 낫겠다.",
        "M: 그 뒤에 다른 주말은 없어?",
        "W: 19일이 있는데 그날은 보호소가 닫아.",
        "M: 주말에 닫아? 드문 일이네.",
        "W: 그날 건물 전체를 청소해.",
        "M: 그럼 12일밖에 없네.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, did you go anywhere on Sunday?"],
        ["W", "I helped at my mother's flower shop."],
        ["M", "What did you do there all day?"],
        ["W", "I wrapped flowers and carried water buckets."],
        ["M", "Was it busy that day?"],
        ["W", "It was Parents' Day weekend, so very busy."],
        ["M", "How many bunches did you wrap?"],
        ["W", "More than sixty, and my hands were sore."],
        ["M", "Will you help again next weekend?"],
        ["W", "Only if she gives me a proper lunch break."],
      ],
      choices: [
        "친구와 영화를 보기",
        "어머니의 꽃집 일을 돕기",
        "집에서 쉬기",
        "도서관에서 공부하기",
        "병원에 가기",
      ],
      answer: 2,
      clue: "I helped at my mother's flower shop.",
      explanation:
        "여자는 일요일에 어머니의 꽃집에서 일을 도왔다. 따라서 답은 ②이다.",
      translation: [
        "M: 채원아, 일요일에 어디 갔어?",
        "W: 엄마 꽃집에서 일을 도왔어.",
        "M: 하루 종일 거기서 뭐 했어?",
        "W: 꽃을 포장하고 물통을 날랐어.",
        "M: 그날 바빴어?",
        "W: 어버이날 주말이라 아주 바빴어.",
        "M: 몇 다발이나 포장했어?",
        "W: 예순 다발 넘게. 손이 아팠어.",
        "M: 다음 주말에도 도울 거야?",
        "W: 점심시간을 제대로 주시면.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the lost and found desk. " +
            "A blue water bottle was found in the gym this morning. " +
            "It has a white strap and a name sticker on the bottom. " +
            "The sticker is too worn to read clearly. " +
            "Come to the office before five today if it is yours. " +
            "Please tell us the name on the sticker before you take it.",
        ],
      ],
      choices: [
        "분실물을 찾아가라고 하려고",
        "체육관 공사를 알리려고",
        "행사를 소개하려고",
        "청소를 부탁하려고",
        "시험을 안내하려고",
      ],
      answer: 1,
      clue: "A blue water bottle was found in the gym this morning.",
      explanation:
        "체육관에서 주운 물병의 주인을 찾는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 분실물 보관소입니다. 오늘 아침 체육관에서 파란 물병을 주웠습니다. 흰 끈이 달려 있고 바닥에 이름표가 붙어 있습니다. 이름표가 닳아서 잘 읽히지 않습니다. 자기 것이라면 오늘 다섯 시 전에 행정실로 오세요. 가져가기 전에 이름표에 적힌 이름을 말해 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What can I get for you today?"],
        ["M", "Two sandwiches and one milk, please."],
        ["W", "Would you like the egg one or the cheese one?"],
        ["M", "One of each, if you have both."],
        ["W", "We do. A sandwich is four dollars each."],
        ["M", "And how much is the milk?"],
        ["W", "Two dollars a bottle."],
        ["M", "Is there anything to pay for the bag?"],
        ["W", "No, the bag is free here."],
        ["M", "All right. Here you are."],
      ],
      choices: ["$8", "$9", "$10", "$11", "$12"],
      answer: 3,
      clue: "We do. A sandwich is four dollars each.",
      explanation:
        "샌드위치 두 개 8달러에 우유 2달러를 더하면 10달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 오늘은 뭘 드릴까요?",
        "M: 샌드위치 두 개랑 우유 하나요.",
        "W: 달걀 샌드위치로 드릴까요, 치즈로 드릴까요?",
        "M: 둘 다 있으면 하나씩요.",
        "W: 있습니다. 샌드위치는 하나에 4달러입니다.",
        "M: 우유는 얼마예요?",
        "W: 한 병에 2달러입니다.",
        "M: 봉투는 돈을 내야 하나요?",
        "W: 아니요, 여기는 봉투가 무료입니다.",
        "M: 알겠습니다. 여기요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Seoyeon, you always finish your homework early."],
        ["W", "I start it right when I get home."],
        ["M", "Before you eat or rest?"],
        ["W", "Before anything else, for thirty minutes."],
        ["M", "I always rest first and then it gets late."],
        ["W", "Resting first turns into resting all evening."],
        ["M", "That's exactly what happened yesterday."],
        ["W", "The first thirty minutes are the easiest ones."],
        ["M", "Could you tell me how you start?"],
      ],
      choices: [
        "I never do homework.",
        "Open the easiest subject first.",
        "You should rest longer.",
        "Homework is not important.",
        "I finished yours already.",
      ],
      answer: 2,
      clue: "Could you tell me how you start?",
      explanation:
        "어떻게 시작하는지 물었으므로, 제일 쉬운 과목부터 펴라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 서연아, 너는 늘 숙제를 일찍 끝내더라.",
        "W: 집에 오자마자 시작해.",
        "M: 먹거나 쉬기도 전에?",
        "W: 다른 무엇보다 먼저, 30분 동안.",
        "M: 나는 늘 먼저 쉬다가 늦어져.",
        "W: 먼저 쉬면 저녁 내내 쉬게 돼.",
        "M: 어제 딱 그랬어.",
        "W: 첫 30분이 제일 쉬운 30분이야.",
        "M: 어떻게 시작하는지 알려 줄래?",
        "W: 제일 쉬운 과목부터 펴.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunjin, you ride your bike to school, don't you?"],
        ["M", "Since April, about fifteen minutes each way."],
        ["W", "What do you do when it rains?"],
        ["M", "I take the bus on those days."],
        ["W", "Where do you leave the bike at school?"],
        ["M", "In the rack behind the gym building."],
        ["W", "Is it safe there all day?"],
        ["M", "I lock it, and nothing has happened yet."],
        ["W", "Could I ride with you tomorrow?"],
      ],
      choices: [
        "Sure, meet me at eight at the corner.",
        "I don't have a bike.",
        "The rack is always full.",
        "You should take the bus.",
        "I walk to school now.",
      ],
      answer: 1,
      clue: "Could I ride with you tomorrow?",
      explanation:
        "여자가 내일 함께 자전거를 타도 되는지 물었으므로, 여덟 시에 모퉁이에서 만나자는 ①이 가장 자연스럽다.",
      translation: [
        "W: 현진아, 자전거로 학교 오지?",
        "M: 4월부터. 편도 15분쯤.",
        "W: 비 오면 어떻게 해?",
        "M: 그런 날은 버스 타.",
        "W: 학교에서 자전거는 어디에 둬?",
        "M: 체육관 건물 뒤 거치대에.",
        "W: 하루 종일 거기 둬도 안전해?",
        "M: 자물쇠 채워. 아직 아무 일 없었어.",
        "W: 내일 같이 타고 가도 돼?",
        "M: 그럼, 여덟 시에 모퉁이에서 보자.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Suyeon, you look tired again this morning."],
        ["W", "I went to bed after midnight for the third night."],
        ["M", "Were you studying that late every time?"],
        ["W", "No, I was watching short videos on my phone."],
        ["M", "One video turns into twenty, doesn't it?"],
        ["W", "And I never notice until it is already late."],
        ["M", "My sister had the same problem last year."],
        ["W", "How did she get out of it?"],
        ["M", "I started leaving my phone in the kitchen."],
        ["W", "Does that really make a difference?"],
        ["M", "I fall asleep almost an hour earlier now."],
      ],
      choices: [
        "I watch videos all night.",
        "Then I'll try that tonight.",
        "My phone is broken.",
        "I sleep at nine every day.",
        "You should watch more videos.",
      ],
      answer: 2,
      clue: "I fall asleep almost an hour earlier now.",
      explanation:
        "휴대폰을 부엌에 두니 더 일찍 잔다고 했으므로, 오늘 밤 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 수연아, 오늘 아침에도 피곤해 보여.",
        "W: 사흘째 자정 넘어서 잤어.",
        "M: 매번 그렇게 늦게까지 공부했어?",
        "W: 아니, 휴대폰으로 짧은 영상을 보고 있었어.",
        "M: 하나 보다 보면 스무 개가 되지.",
        "W: 이미 늦을 때까지 모르겠더라.",
        "M: 우리 누나도 작년에 똑같았어.",
        "W: 어떻게 벗어났는데?",
        "M: 나는 휴대폰을 부엌에 두고 자기 시작했어.",
        "W: 그게 정말 달라져?",
        "M: 지금은 거의 한 시간 일찍 잠들어.",
        "W: 그럼 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiwoo가 Minseo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jiwoo : ________________",
      lines: [
        [
          "M",
          "Jiwoo and Minseo are cleaning the classroom after school. " +
            "Minseo lifts a chair onto the desk with one hand. " +
            "Jiwoo sees that one leg of the chair is loose and shaking. " +
            "If she lifts it that way, the chair could fall on her foot. " +
            "He wants to stop her before she lifts the next one. " +
            "In this situation, what would Jiwoo most likely say to Minseo?",
        ],
      ],
      choices: [
        "The classroom is already clean.",
        "Let's go home together today.",
        "Wait, that chair leg is loose.",
        "Can you open the window?",
        "We need more desks here.",
      ],
      answer: 3,
      clue: "He wants to stop her before she lifts the next one.",
      explanation:
        "의자 다리가 흔들려 위험하므로, 다리가 헐겁다고 말리는 ③이 가장 적절하다.",
      translation: [
        "M: 지우와 민서는 방과 후에 교실을 청소하고 있습니다. 민서는 한 손으로 의자를 책상 위에 올립니다. 지우는 그 의자의 다리 하나가 헐거워 흔들리는 것을 봅니다. 그렇게 들면 의자가 발 위로 떨어질 수 있습니다. 지우는 민서가 다음 의자를 들기 전에 말리고 싶습니다. 이런 상황에서 지우가 민서에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
