/** 중1 듣기 28회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 28회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 화분을 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a flower pot?"],
        ["M", "Yes, one for the small plant on my desk."],
        ["W", "We have tall pots and short round pots."],
        ["M", "A short round one, please. My desk shelf is low."],
        ["W", "All right. This round pot has a leaf pattern."],
        ["M", "Leaves on a pot look a little strange to me."],
        ["W", "Then here is a round one with wavy lines."],
        ["M", "That's nice. I'll take the pot with wavy lines."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "A short round one, please. / I'll take the pot with wavy lines.",
      explanation:
        "남자는 낮고 둥근 화분을 원하고, 잎 무늬 대신 물결무늬를 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five empty flower pots drawn side by side as five choices, clean black line art on white. " +
          "① a SHORT ROUND pot with a LEAF pattern. " +
          "② a SHORT ROUND pot with WAVY LINES around it. " +
          "③ a SHORT ROUND pot with no pattern at all. " +
          "④ a TALL pot with a LEAF pattern. " +
          "⑤ a TALL pot with WAVY LINES around it.",
      },
      translation: [
        "W: 안녕하세요. 화분 찾으세요?",
        "M: 네, 책상 위 작은 식물에 쓸 거예요.",
        "W: 키 큰 화분도 있고 낮고 둥근 것도 있어요.",
        "M: 낮고 둥근 걸로 주세요. 제 책상 선반이 낮아서요.",
        "W: 알겠습니다. 이 둥근 화분은 잎 무늬가 있어요.",
        "M: 화분에 잎 무늬는 좀 이상해 보여요.",
        "W: 그럼 물결무늬가 있는 둥근 화분이 여기 있어요.",
        "M: 그게 좋네요. 물결무늬 화분으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 요리 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yerin, are you entering the school cooking contest?"],
        ["W", "I want to. When is it held?"],
        ["M", "Next Friday, in the home economics room."],
        ["W", "How many people are in one team?"],
        ["M", "Three students make one team."],
        ["W", "Do we have to bring our own food?"],
        ["M", "Yes, you bring everything except the pans."],
        ["W", "Okay. How long do we get to cook?"],
        ["M", "Forty minutes from the starting bell."],
      ],
      choices: ["열리는 날", "열리는 장소", "한 팀의 인원", "요리 시간", "심사 기준"],
      answer: 5,
      clue: "심사 기준은 대화에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 금요일), 장소(가정실), 한 팀 인원(3명), 요리 시간(40분)은 언급되지만 심사 기준은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예린아, 학교 요리 대회 나갈 거야?",
        "W: 나가고 싶어. 언제 해?",
        "M: 다음 주 금요일, 가정실에서 해.",
        "W: 한 팀에 몇 명이야?",
        "M: 세 명이 한 팀이야.",
        "W: 재료는 우리가 가져가야 해?",
        "M: 응, 팬만 빼고 다 가져와야 해.",
        "W: 알겠어. 요리 시간은 얼마나 줘?",
        "M: 시작 종이 울리고 40분.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Hanbit Library front desk?"],
        ["W", "Yes, it is. What can I do for you?"],
        ["M", "I borrowed two books that are due tomorrow."],
        ["W", "Would you like to return them today?"],
        ["M", "Actually, I haven't finished reading them yet."],
        ["W", "I see. You can keep them one more week."],
        ["M", "Can you do that for me over the phone?"],
        ["W", "Of course. I've extended both books to next Tuesday."],
      ],
      choices: [
        "책을 새로 빌리려고",
        "책의 반납 기한을 미루려고",
        "도서관 여는 시간을 물어보려고",
        "잃어버린 책을 찾으려고",
        "읽을 책을 추천받으려고",
      ],
      answer: 2,
      clue: "Actually, I haven't finished reading them yet.",
      explanation:
        "남자는 아직 다 읽지 못한 책 두 권의 반납 기한을 미루려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요, 한빛 도서관 안내 데스크죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 내일이 반납일인 책 두 권을 빌렸어요.",
        "W: 오늘 반납하시겠어요?",
        "M: 사실 아직 다 못 읽었어요.",
        "W: 그렇군요. 일주일 더 가지고 계셔도 됩니다.",
        "M: 전화로 해 주실 수 있나요?",
        "W: 물론이죠. 두 권 다 다음 주 화요일까지로 연장했습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Junwoo, what time does the school shuttle leave?"],
        ["M", "The last one leaves the gate at five thirty."],
        ["W", "Then we should finish our poster before that."],
        ["M", "Right. How long will the last part take?"],
        ["W", "About an hour if we work together."],
        ["M", "Then let's start an hour and a half before the shuttle."],
        ["W", "Good idea. That gives us extra time to clean up."],
        ["M", "I'll be in the art room waiting for you."],
        ["W", "Okay, I'll come straight from my math class."],
      ],
      choices: ["3:30 p.m.", "4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "5:30 p.m."],
      answer: 2,
      clue: "Then let's start an hour and a half before the shuttle.",
      explanation:
        "마지막 셔틀이 5시 30분에 떠나고 그보다 한 시간 반 전에 시작하기로 했으므로 만나는 시각은 4시이다. 따라서 답은 ②이다.",
      translation: [
        "W: 준우야, 학교 셔틀 몇 시에 떠나?",
        "M: 마지막 차가 정문에서 5시 30분에 떠나.",
        "W: 그럼 그전에 포스터를 끝내야겠다.",
        "M: 맞아. 남은 부분 얼마나 걸릴까?",
        "W: 같이 하면 한 시간쯤.",
        "M: 그럼 셔틀 한 시간 반 전에 시작하자.",
        "W: 좋은 생각이야. 정리할 시간도 남네.",
        "M: 나는 미술실에서 기다릴게.",
        "W: 알겠어, 나는 수학 수업 끝나고 바로 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, did you open the envelope from the city library?"],
        ["W", "I just did. My story won the first prize."],
        ["M", "No way! Out of how many stories?"],
        ["W", "More than four hundred from all over the city."],
        ["M", "That's amazing. You wrote it in one week, right?"],
        ["W", "Yes, and I almost didn't send it in."],
        ["M", "Aren't you glad you did?"],
        ["W", "I keep reading the letter again and again."],
      ],
      choices: ["bored", "sorry", "angry", "proud", "sleepy"],
      answer: 4,
      clue: "More than four hundred from all over the city.",
      explanation:
        "400편이 넘는 작품 중에서 자기 글이 1등을 했고 편지를 계속 다시 읽는다고 했으므로 여자의 심정은 '자랑스러운(proud)'이다. 따라서 답은 ④이다.",
      translation: [
        "M: 예린아, 시립 도서관에서 온 봉투 열어 봤어?",
        "W: 방금 열었어. 내 이야기가 1등을 했어.",
        "M: 말도 안 돼! 몇 편 중에서?",
        "W: 시 전체에서 400편이 넘었대.",
        "M: 대단하다. 일주일 만에 쓴 거잖아?",
        "W: 응, 그리고 안 낼 뻔했어.",
        "M: 내길 잘했지?",
        "W: 편지를 계속 다시 읽고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much are these apples?"],
        ["M", "Three dollars for five."],
        ["ANN", "Number two."],
        ["W", "Do you sell strawberries here?"],
        ["M", "Not in winter, sorry."],
        ["ANN", "Number three."],
        ["W", "Excuse me, your oranges are rolling away."],
        ["M", "Oh dear, let me pick them up."],
        ["ANN", "Number four."],
        ["W", "Can I pay by card?"],
        ["M", "Yes, of course you can."],
        ["ANN", "Number five."],
        ["W", "What time do you close today?"],
        ["M", "We close at eight in the evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, your oranges are rolling away.",
      explanation:
        "그림은 시장에서 남자가 든 상자가 기울어 오렌지가 바닥으로 굴러가고, 여자가 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "At an outdoor fruit market stall, clean black line art on a plain white background, no writing anywhere. " +
          "A man carries a tilted cardboard box and several round oranges are rolling out of it onto the ground. " +
          "A woman beside him points at the rolling oranges and speaks to him. " +
          "Fruit crates and a striped awning are drawn simply in the background.",
      },
      translation: [
        "① W: 이 사과 얼마예요? / M: 다섯 개에 3달러입니다.",
        "② W: 여기 딸기 팔아요? / M: 겨울에는 안 팝니다, 죄송해요.",
        "③ W: 저기요, 오렌지가 굴러가고 있어요. / M: 이런, 제가 주울게요.",
        "④ W: 카드로 계산해도 돼요? / M: 네, 물론입니다.",
        "⑤ W: 오늘 몇 시에 닫아요? / M: 저녁 8시에 닫습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, you sit in the front row in music class, right?"],
        ["W", "Yes, right next to the piano. Why?"],
        ["M", "I have to leave early for a hospital visit."],
        ["W", "Oh, is the singing test today?"],
        ["M", "No, the teacher only picks the songs today."],
        ["W", "So you won't know which song is yours."],
        ["M", "Exactly. Could you write down my song for me?"],
        ["W", "Sure. I'll send you a message right after class."],
      ],
      choices: ["대신 노래 부르기", "피아노 쳐 주기", "받을 노래를 적어 주기", "병원에 같이 가기", "자리 바꿔 주기"],
      answer: 3,
      clue: "Exactly. Could you write down my song for me?",
      explanation:
        "남자는 병원에 가느라 수업에 빠지게 되어, 자기가 받을 노래를 적어 달라고 부탁했다. 따라서 답은 ③이다.",
      translation: [
        "M: 예린아, 너 음악 시간에 앞줄에 앉지?",
        "W: 응, 피아노 바로 옆에. 왜?",
        "M: 병원에 가야 해서 일찍 나가야 해.",
        "W: 아, 오늘 노래 시험이야?",
        "M: 아니, 오늘은 선생님이 곡만 정해 주셔.",
        "W: 그럼 네 곡이 뭔지 모르겠네.",
        "M: 그래서 그런데, 내 곡 좀 적어 줄 수 있어?",
        "W: 그럼. 수업 끝나고 바로 문자 보낼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 영화 상영회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The English movie night is back this month. " +
            "We will show the movie in the audiovisual room on Thursday. " +
            "It starts right after the seventh class and runs for two hours. " +
            "The movie has Korean subtitles, so don't worry about the language. " +
            "Popcorn will be handed out at the door to everyone who comes. " +
            "See you there on Thursday.",
        ],
      ],
      choices: ["상영 요일", "상영 장소", "상영 시간", "자막 여부", "관람 인원"],
      answer: 5,
      clue: "관람 인원은 방송에서 언급되지 않았다.",
      explanation:
        "상영 요일(목요일), 장소(시청각실), 시간(두 시간), 자막 여부(한국어 자막)는 언급되지만 관람 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 이번 달에도 영어 영화의 밤이 돌아왔습니다. 목요일에 시청각실에서 영화를 상영합니다. 7교시가 끝난 직후에 시작해서 두 시간 동안 진행됩니다. 한국어 자막이 있으니 언어 걱정은 하지 마세요. 오시는 모든 분께 문 앞에서 팝콘을 나눠 드립니다. 목요일에 만나요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is something you wear on your face when you need to see well. " +
            "It has two round or square pieces of glass and two arms. " +
            "The arms rest on your ears, and the middle part sits on your nose. " +
            "When you come inside from the cold, it turns white for a moment. " +
            "People who cannot see far away usually need one.",
        ],
      ],
      choices: ["모자", "마스크", "목도리", "안경", "귀마개"],
      answer: 4,
      clue: "It has two round or square pieces of glass and two arms.",
      explanation:
        "유리 두 개와 다리 두 개가 있고 귀에 걸쳐 코에 얹으며, 추운 데서 들어오면 잠깐 하얘지는 것은 안경이다. 따라서 답은 ④이다.",
      translation: [
        "M: 이것은 잘 보고 싶을 때 얼굴에 쓰는 것입니다. 둥글거나 네모난 유리 두 개와 다리 두 개가 있습니다. 다리는 귀에 걸치고 가운데 부분은 코에 얹힙니다. 추운 곳에서 안으로 들어오면 잠시 하얘집니다. 멀리 있는 것이 잘 안 보이는 사람들이 보통 하나씩 씁니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "What time do you usually get up?"],
        ["M", "I wake up at six thirty."],
        ["ANN", "Number two."],
        ["W", "How many classes do you have today?"],
        ["M", "My sister is a nurse."],
        ["ANN", "Number three."],
        ["W", "Do you want to join our team?"],
        ["M", "Yes, I'd love to."],
        ["ANN", "Number four."],
        ["W", "Where did you put my pencil?"],
        ["M", "I left it on your desk."],
        ["ANN", "Number five."],
        ["W", "What kind of music do you like?"],
        ["M", "I really like jazz."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "How many classes do you have today?",
      explanation:
        "오늘 수업이 몇 개인지 묻는 말에 누나가 간호사라고 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① W: 보통 몇 시에 일어나? / M: 6시 30분에 일어나.",
        "② W: 오늘 수업 몇 개 있어? / M: 우리 누나는 간호사야.",
        "③ W: 우리 팀에 들어올래? / M: 응, 좋아.",
        "④ W: 내 연필 어디에 뒀어? / M: 네 책상 위에 뒀어.",
        "⑤ W: 어떤 음악 좋아해? / M: 나는 재즈를 정말 좋아해.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junwoo, the book club meeting starts in ten minutes."],
        ["M", "I know. Did everyone get a copy of the story?"],
        ["W", "Yes, I printed twelve copies this morning."],
        ["M", "Great. Are the chairs in a circle already?"],
        ["W", "They are, but the room is really dark today."],
        ["M", "The curtains are closed. Someone should open them."],
        ["W", "I have to greet the new members at the door."],
        ["M", "Then I'll open all the curtains right now."],
      ],
      choices: ["복사하기", "의자 옮기기", "커튼 열기", "새 회원 맞이하기", "책 읽기"],
      answer: 3,
      clue: "Then I'll open all the curtains right now.",
      explanation:
        "방이 어두운데 여자는 새 회원을 맞아야 해서, 남자가 지금 바로 커튼을 다 열겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 준우야, 독서 모임이 10분 뒤에 시작해.",
        "M: 알아. 다들 이야기 인쇄물 받았어?",
        "W: 응, 오늘 아침에 열두 부 뽑았어.",
        "M: 잘했다. 의자는 둥글게 놨어?",
        "W: 놨는데, 오늘 방이 너무 어두워.",
        "M: 커튼이 닫혀 있네. 누가 열어야겠다.",
        "W: 나는 문에서 새 회원들을 맞아야 해.",
        "M: 그럼 내가 지금 커튼을 다 열게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 봉사 활동을 고르시오.",
      lines: [
        ["M", "Yerin, which volunteer activity are you choosing?"],
        ["W", "I'm still looking at the list."],
        ["M", "Do you have time on weekdays?"],
        ["W", "No, I have academy classes every weekday evening."],
        ["M", "Then it has to be on the weekend."],
        ["W", "Right. And it should be close to my house."],
        ["M", "How far can you go from home?"],
        ["W", "Less than twenty minutes by bus."],
        ["M", "Then only one activity on the list fits you."],
        ["W", "Good. I'll write my name on the sheet today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Less than twenty minutes by bus.",
      explanation:
        "주말에 하고, 버스로 20분 미만 거리인 것을 고른다. 두 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Weekday / Distance: 10 minutes / Place: Park" },
          { no: 2, label: "②", value: "Day: Weekend / Distance: 40 minutes / Place: Beach" },
          { no: 3, label: "③", value: "Day: Weekday / Distance: 15 minutes / Place: Library" },
          { no: 4, label: "④", value: "Day: Weekend / Distance: 30 minutes / Place: Farm" },
          { no: 5, label: "⑤", value: "Day: Weekend / Distance: 15 minutes / Place: Shelter" },
        ],
      },
      translation: [
        "M: 예린아, 어떤 봉사 활동 고를 거야?",
        "W: 아직 목록 보는 중이야.",
        "M: 평일에 시간 돼?",
        "W: 아니, 평일 저녁엔 매일 학원이 있어.",
        "M: 그럼 주말이어야겠네.",
        "W: 맞아. 그리고 집에서 가까워야 해.",
        "M: 집에서 얼마나 멀리까지 갈 수 있어?",
        "W: 버스로 20분 미만.",
        "M: 그럼 목록에서 너한테 맞는 건 하나뿐이네.",
        "W: 좋아. 오늘 신청서에 이름 쓸게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진을 찍으러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Yerin, when can we take photos at the old palace?"],
        ["W", "How about March 3rd? The trees will be pretty."],
        ["M", "I'm visiting my cousin in Daegu that weekend."],
        ["W", "Then what about March 7th, after school?"],
        ["M", "The palace closes early every Wednesday."],
        ["W", "Hmm. I'm free on March 12th."],
        ["M", "But our club presentation is on the 12th."],
        ["W", "Oh, right. Then let's go on March 9th."],
        ["M", "March 9th works. The weather should be warm."],
        ["W", "Perfect. I'll bring my father's old camera."],
      ],
      choices: ["3월 3일", "3월 7일", "3월 9일", "3월 12일", "3월 15일"],
      answer: 3,
      clue: "Oh, right. Then let's go on March 9th.",
      explanation:
        "3일에는 대구에 가고, 7일은 수요일 조기 폐장이며, 12일에는 동아리 발표가 있다. 두 사람은 3월 9일에 가기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 예린아, 고궁에 사진 찍으러 언제 갈까?",
        "W: 3월 3일 어때? 나무가 예쁠 거야.",
        "M: 그 주말엔 대구 사촌 집에 가.",
        "W: 그럼 3월 7일 방과 후는?",
        "M: 고궁은 수요일마다 일찍 닫아.",
        "W: 음. 나는 3월 12일이 비어.",
        "M: 그런데 12일에 우리 동아리 발표가 있어.",
        "W: 아, 맞다. 그럼 3월 9일에 가자.",
        "M: 3월 9일 괜찮아. 날씨도 따뜻할 거야.",
        "W: 좋아. 아버지 오래된 사진기 가져갈게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junwoo, why do you have a bandage on your thumb?"],
        ["M", "I was in my grandfather's workshop all Saturday."],
        ["W", "Does he make furniture there?"],
        ["M", "Yes, and we built a small bookshelf together."],
        ["W", "Wow, did you use a hammer and nails?"],
        ["M", "I did, and I hit my thumb once by mistake."],
        ["W", "Ouch. Did you finish the shelf anyway?"],
        ["M", "We did, and it's already in my room."],
      ],
      choices: ["책장 만들기", "책 읽기", "가구 사러 가기", "낚시하기", "집 청소하기"],
      answer: 1,
      clue: "Yes, and we built a small bookshelf together.",
      explanation:
        "남자는 토요일에 할아버지 작업실에서 작은 책장을 만들었다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 준우야, 엄지에 왜 밴드를 붙였어?",
        "M: 토요일 내내 할아버지 작업실에 있었어.",
        "W: 거기서 가구 만드셔?",
        "M: 응, 우리 둘이 작은 책장을 만들었어.",
        "W: 우와, 망치랑 못도 썼어?",
        "M: 응, 실수로 엄지를 한 번 쳤어.",
        "W: 아팠겠다. 그래도 책장은 끝냈어?",
        "M: 끝냈지. 벌써 내 방에 있어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement about the school bus. " +
            "Starting next week, the morning bus will leave ten minutes earlier. " +
            "The new departure time is seven forty, not seven fifty. " +
            "This is because of the road work near the city hall. " +
            "Please tell your family so that nobody misses the bus. " +
            "Thank you for your understanding.",
        ],
      ],
      choices: [
        "버스 요금 인상을 알리려고",
        "버스 노선 변경을 알리려고",
        "도로 공사 기간을 알리려고",
        "버스 출발 시각 변경을 알리려고",
        "버스 이용 규칙을 알리려고",
      ],
      answer: 4,
      clue: "The new departure time is seven forty, not seven fifty.",
      explanation:
        "도로 공사 때문에 다음 주부터 아침 버스가 10분 일찍 떠난다는 것을 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 학교 버스에 관한 안내입니다. 다음 주부터 아침 버스가 10분 일찍 출발합니다. 새 출발 시각은 7시 50분이 아니라 7시 40분입니다. 시청 근처 도로 공사 때문입니다. 아무도 버스를 놓치지 않도록 가족에게도 알려 주세요. 양해해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you renting bikes for today?"],
        ["M", "Yes, two bikes for three hours, please."],
        ["W", "One bike is four dollars an hour."],
        ["M", "So that's twenty-four dollars for both?"],
        ["W", "That's right. Do you need helmets as well?"],
        ["M", "Yes, two helmets, please."],
        ["W", "Helmets are free, and students get four dollars off."],
        ["M", "Great, here are our student cards."],
      ],
      choices: ["$16", "$18", "$19", "$20", "$24"],
      answer: 4,
      clue: "Helmets are free, and students get four dollars off.",
      explanation:
        "자전거 두 대를 세 시간 빌리면 24달러이고, 헬멧은 무료이며 학생 할인 4달러를 빼면 20달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요. 오늘 자전거 빌리시나요?",
        "M: 네, 세 시간 동안 두 대 주세요.",
        "W: 자전거 한 대에 한 시간 4달러입니다.",
        "M: 그럼 두 대면 24달러인가요?",
        "W: 맞습니다. 헬멧도 필요하세요?",
        "M: 네, 두 개 주세요.",
        "W: 헬멧은 무료이고, 학생은 4달러 할인됩니다.",
        "M: 잘됐네요, 여기 학생증이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junwoo, you've been yawning all through class."],
        ["M", "I only slept about four hours last night."],
        ["W", "Were you studying for the science test?"],
        ["M", "No, I was watching videos until two in the morning."],
        ["W", "That's why you can't keep your eyes open."],
        ["M", "I know, but I can't stop once I start."],
        ["W", "Try leaving your phone outside your room."],
        ["M", "Outside? What if I need the alarm?"],
        ["W", "Use a real clock. That's what I do every night."],
      ],
      choices: [
        "I'll try that from tonight.",
        "I don't have a phone at all.",
        "The science test was easy.",
        "I slept ten hours last night.",
        "Let's watch videos together.",
      ],
      answer: 1,
      clue: "Use a real clock. That's what I do every night.",
      explanation:
        "여자가 휴대폰 대신 시계를 쓰라고 했으므로, 오늘 밤부터 그렇게 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준우야, 수업 내내 하품하네.",
        "M: 어젯밤에 네 시간밖에 못 잤어.",
        "W: 과학 시험 공부했어?",
        "M: 아니, 새벽 2시까지 영상 봤어.",
        "W: 그러니 눈을 못 뜨지.",
        "M: 알아, 그런데 한번 보기 시작하면 못 멈춰.",
        "W: 휴대폰을 방 밖에 두고 자 봐.",
        "M: 밖에? 알람은 어떡하고?",
        "W: 진짜 시계를 써. 나는 매일 밤 그렇게 해.",
        "M: 오늘 밤부터 그렇게 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, did you see the sign about the lost puppy?"],
        ["W", "The brown one with a red collar? Yes, this morning."],
        ["M", "I think I saw that puppy near the playground."],
        ["W", "Really? Did you try to catch it?"],
        ["M", "It ran under the fence before I got close."],
        ["W", "The owner must be very worried right now."],
        ["M", "There was a phone number on the sign."],
        ["W", "Do you remember any of the numbers?"],
        ["M", "No, but the sign is still on the school gate."],
      ],
      choices: [
        "I'll go and check the sign now.",
        "The puppy was black and white.",
        "I don't like dogs very much.",
        "The owner already found it.",
        "Let's put up a new sign.",
      ],
      answer: 1,
      clue: "No, but the sign is still on the school gate.",
      explanation:
        "남자가 전단이 아직 정문에 붙어 있다고 했으므로, 지금 가서 확인하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 예린아, 강아지 찾는 전단 봤어?",
        "W: 빨간 목줄 한 갈색 강아지? 응, 오늘 아침에.",
        "M: 그 강아지를 운동장 근처에서 본 것 같아.",
        "W: 정말? 잡아 보려고 했어?",
        "M: 다가가기 전에 울타리 밑으로 도망갔어.",
        "W: 주인이 지금 아주 걱정하고 있겠다.",
        "M: 전단에 전화번호가 있었어.",
        "W: 번호 기억나?",
        "M: 아니, 그런데 전단이 아직 정문에 붙어 있어.",
        "W: 지금 가서 확인할게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Junwoo, our class is doing a play for the festival."],
        ["M", "I heard. Have you picked the story yet?"],
        ["W", "Yes, but we still have no one for the main part."],
        ["M", "Why not? That's usually the popular role."],
        ["W", "It has thirty lines, and everyone is scared of that."],
        ["M", "Thirty lines is a lot for two weeks."],
        ["W", "Right, so nobody raised their hand yesterday."],
        ["M", "What if two people share the part?"],
        ["W", "Can you do that in a play?"],
        ["M", "Sure, one plays the first half and one the second."],
      ],
      choices: [
        "That's a good idea. I'll suggest it tomorrow.",
        "We already finished the play.",
        "Nobody wants to watch our play.",
        "The main part has only two lines.",
        "Let's cancel the festival.",
      ],
      answer: 1,
      clue: "Sure, one plays the first half and one the second.",
      explanation:
        "남자가 주인공 역을 둘이 나눠 맡는 방법을 알려 주었으므로, 좋은 생각이라며 내일 제안하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준우야, 우리 반이 축제에서 연극을 해.",
        "M: 들었어. 이야기는 골랐어?",
        "W: 응, 그런데 아직 주인공 할 사람이 없어.",
        "M: 왜? 보통 제일 인기 있는 역할인데.",
        "W: 대사가 서른 줄이라 다들 무서워해.",
        "M: 두 주 만에 서른 줄이면 많긴 하다.",
        "W: 맞아, 그래서 어제 아무도 손을 안 들었어.",
        "M: 두 사람이 그 역할을 나눠 맡으면 어때?",
        "W: 연극에서 그렇게 해도 돼?",
        "M: 그럼, 한 명이 앞부분, 한 명이 뒷부분을 하면 되지.",
        "W: 좋은 생각이야. 내일 제안해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Doyeon이 Minho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Doyeon : ________________",
      lines: [
        [
          "W",
          "Doyeon and Minho are doing a science experiment together. " +
            "They have to heat water in a glass beaker over a small flame. " +
            "Minho is about to pick up the hot beaker with his bare hand. " +
            "Doyeon knows the glass has been over the flame for five minutes. " +
            "She wants to stop him before he burns his fingers. " +
            "In this situation, what would Doyeon most likely say to Minho?",
        ],
      ],
      choices: [
        "Let's add more water to it.",
        "The flame is not on yet.",
        "I'll wash the beaker later.",
        "We need a bigger beaker.",
        "Don't touch it. It's very hot.",
      ],
      answer: 5,
      clue: "She wants to stop him before he burns his fingers.",
      explanation:
        "민호가 5분 동안 불 위에 있던 뜨거운 비커를 맨손으로 잡으려 하므로, 뜨거우니 만지지 말라고 말리는 ⑤가 가장 적절하다.",
      translation: [
        "W: 도연이와 민호는 함께 과학 실험을 하고 있습니다. 두 사람은 작은 불 위에서 유리 비커에 든 물을 데워야 합니다. 민호는 뜨거운 비커를 맨손으로 잡으려 합니다. 도연이는 그 유리가 5분 동안 불 위에 있었다는 것을 압니다. 도연이는 민호가 손가락을 데기 전에 말리고 싶습니다. 이런 상황에서 도연이가 민호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
