/** 중1 듣기 39회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 39회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 의자를 고르시오.",
      lines: [
        ["W", "Hello. Do you need a chair for your room?"],
        ["M", "Yes, one for my desk at home."],
        ["W", "These chairs have wheels under the legs."],
        ["M", "Wheels would scratch my wooden floor."],
        ["W", "All right, then here are the ones without wheels."],
        ["M", "I sit for a long time, so I need a soft seat."],
        ["W", "This one has a thick cushion and two armrests."],
        ["M", "Armrests hit my desk. Just the cushion, please."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Wheels would scratch my wooden floor. / Armrests hit my desk. Just the cushion, please.",
      explanation:
        "남자는 바퀴가 없고 쿠션이 있으며 팔걸이는 없는 의자를 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five desk chairs standing side by side as five choices, clean black line art on white. " +
          "① a chair with a FLAT hard seat, NO wheels and NO armrests. " +
          "② a chair with a THICK CUSHION seat, NO wheels and NO armrests. " +
          "③ a chair with a THICK CUSHION seat and WHEELS under the legs, no armrests. " +
          "④ a chair with a FLAT hard seat and WHEELS under the legs, no armrests. " +
          "⑤ a chair with a THICK CUSHION seat, WHEELS under the legs and two ARMRESTS.",
      },
      translation: [
        "W: 안녕하세요. 방에 둘 의자 필요하세요?",
        "M: 네, 집 책상에 쓸 거예요.",
        "W: 이 의자들은 다리 아래에 바퀴가 있어요.",
        "M: 바퀴는 나무 바닥을 긁을 것 같아요.",
        "W: 알겠습니다. 그럼 바퀴 없는 것들이 여기 있어요.",
        "M: 오래 앉아 있어서 푹신한 자리가 필요해요.",
        "W: 이건 두꺼운 쿠션에 팔걸이가 두 개 있어요.",
        "M: 팔걸이는 책상에 부딪혀요. 쿠션만 있는 걸로요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 동아리 전시회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dahyun, when does your club exhibition open?"],
        ["W", "It opens next Monday and runs for five days."],
        ["M", "Where are you putting the works?"],
        ["W", "Along the wall of the hallway on the second floor."],
        ["M", "How many pieces will be on the wall?"],
        ["W", "Thirty-two, and each student made two of them."],
        ["M", "How long did it take to get ready?"],
        ["W", "We worked on it for about three months."],
        ["M", "I'll come and look at them next week."],
      ],
      choices: [
        "전시가 시작되는 날",
        "전시하는 장소",
        "관람할 수 있는 시간",
        "전시하는 작품 수",
        "준비하는 데 걸린 기간",
      ],
      answer: 3,
      clue: "It opens next Monday and runs for five days. / Thirty-two, and each student made two of them.",
      explanation:
        "날짜, 장소, 작품 수, 준비 기간은 말했지만 관람 시간은 말하지 않았다. 따라서 답은 ③이다.",
      translation: [
        "M: 다현아, 너희 동아리 전시 언제 시작해?",
        "W: 다음 주 월요일에 시작해서 닷새 동안 해.",
        "M: 작품은 어디에 걸어?",
        "W: 2층 복도 벽을 따라서.",
        "M: 벽에 몇 점이나 걸어?",
        "W: 서른두 점. 학생마다 두 점씩 만들었어.",
        "M: 준비하는 데 얼마나 걸렸어?",
        "W: 석 달쯤 준비했어.",
        "M: 다음 주에 보러 갈게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Seungwoo. It's Nayun. Did you get home yet?"],
        ["M", "Yes, about ten minutes ago. Why?"],
        ["W", "I can't find my English workbook anywhere."],
        ["M", "Did you leave it in the classroom?"],
        ["W", "I think it's still on the desk we shared."],
        ["M", "I'll check the classroom first thing tomorrow."],
        ["W", "Thank you. I really need it for the test."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "함께 공부하자고",
        "잃어버린 물건을 알리려고",
        "생일을 축하하려고",
      ],
      answer: 4,
      clue: "I can't find my English workbook anywhere.",
      explanation:
        "여자는 영어 문제집을 잃어버려서 찾아봐 달라고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 승우야. 나윤이야. 집에 도착했어?",
        "M: 응, 10분쯤 전에. 왜?",
        "W: 내 영어 문제집이 어디에도 없어.",
        "M: 교실에 두고 온 거 아니야?",
        "W: 우리가 같이 쓰던 책상 위에 있을 것 같아.",
        "M: 내일 아침에 제일 먼저 교실 확인할게.",
        "W: 고마워. 시험 때문에 꼭 필요해.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minchan, what time does the bowling alley open?"],
        ["M", "It opens at one o'clock on Sundays."],
        ["W", "Do we need to book a lane first?"],
        ["M", "Not on Sunday, but the lanes fill up fast."],
        ["W", "Then let's get there right when it opens."],
        ["M", "My piano lesson ends at one fifteen."],
        ["W", "Then we'll meet at one thirty in front of it."],
        ["M", "One thirty works for me. I can walk there quickly."],
        ["W", "See you at the entrance then."],
      ],
      choices: ["12:30 p.m.", "1:00 p.m.", "1:15 p.m.", "1:30 p.m.", "2:00 p.m."],
      answer: 4,
      clue: "Then we'll meet at one thirty in front of it.",
      explanation:
        "남자의 피아노 수업이 1시 15분에 끝나서 1시 30분에 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 민찬아, 볼링장 몇 시에 열어?",
        "M: 일요일에는 1시에 열어.",
        "W: 먼저 레인을 예약해야 해?",
        "M: 일요일에는 안 되는데 자리가 빨리 차.",
        "W: 그럼 문 열자마자 가자.",
        "M: 내 피아노 수업이 1시 15분에 끝나.",
        "W: 그럼 1시 30분에 그 앞에서 만나자.",
        "M: 1시 30분이면 돼. 빨리 걸어갈 수 있어.",
        "W: 그럼 입구에서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Bora, what happened to your science project?"],
        ["W", "Someone moved my box and the plants fell over."],
        ["M", "Did the soil spill out of the pots?"],
        ["W", "All six pots, and two stems broke in half."],
        ["M", "You watered those plants for three weeks."],
        ["W", "I measured them every single morning."],
        ["M", "Can you still hand in the report?"],
        ["W", "I have to start all over again from the seeds."],
      ],
      choices: ["happy", "upset", "excited", "calm", "shy"],
      answer: 2,
      clue: "I have to start all over again from the seeds.",
      explanation:
        "3주 동안 기른 식물이 망가져 처음부터 다시 해야 하므로 속상한 심정이다. 따라서 답은 ②이다.",
      translation: [
        "M: 보라야, 네 과학 과제 어떻게 된 거야?",
        "W: 누가 내 상자를 옮겨서 화분이 넘어졌어.",
        "M: 흙이 다 쏟아졌어?",
        "W: 화분 여섯 개 다. 줄기도 두 개가 부러졌어.",
        "M: 3주나 물 준 식물이잖아.",
        "W: 아침마다 자라는 걸 재기까지 했어.",
        "M: 그래도 보고서는 낼 수 있어?",
        "W: 씨앗부터 처음부터 다시 해야 해.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Which floor are you going to?"],
        ["M", "The fourth floor, please."],
        ["ANN", "Number two."],
        ["W", "Is the elevator working?"],
        ["M", "No, use the stairs today."],
        ["ANN", "Number three."],
        ["W", "Are you all right?"],
        ["M", "Yes, thank you for helping me up."],
        ["ANN", "Number four."],
        ["W", "Where is the teachers' room?"],
        ["M", "Next to the library."],
        ["ANN", "Number five."],
        ["W", "Can I take the front seat?"],
        ["M", "Of course you can."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Yes, thank you for helping me up.",
      explanation:
        "그림은 계단에서 넘어진 학생을 다른 학생이 손을 잡아 일으켜 주는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "A school staircase, clean black line art on a plain white background, no writing anywhere. " +
          "A schoolboy has fallen on the steps and is sitting on the floor with his books scattered around him. " +
          "A schoolgirl bends down and holds out her hand to pull him up, looking worried. " +
          "A handrail runs along the wall and a plain window is drawn above the stairs.",
      },
      translation: [
        "① W: 몇 층 가세요? / M: 4층이요.",
        "② W: 승강기 되나요? / M: 아니요, 오늘은 계단을 쓰세요.",
        "③ W: 괜찮아? / M: 응, 일으켜 줘서 고마워.",
        "④ W: 교무실이 어디예요? / M: 도서관 옆이요.",
        "⑤ W: 앞자리에 앉아도 돼? / M: 그럼, 앉아.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunchae, were you in history class yesterday?"],
        ["W", "Yes, we started a new chapter about castles."],
        ["M", "I was at the dentist all afternoon."],
        ["W", "The teacher wrote a lot on the board."],
        ["M", "Did she say the test would cover it?"],
        ["W", "She did, and it's only two weeks away."],
        ["M", "Could you copy your notes for me?"],
        ["W", "Sure, I'll make a copy at lunch time."],
      ],
      choices: [
        "창문을 열어 주기",
        "책을 빌려주기",
        "자리를 바꿔 주기",
        "사진을 찍어 주기",
        "필기한 것을 복사해 주기",
      ],
      answer: 5,
      clue: "Could you copy your notes for me?",
      explanation:
        "남자는 여자의 필기를 복사해 달라고 부탁했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 은채야, 어제 역사 수업 들었어?",
        "W: 응, 성에 대한 새 단원을 시작했어.",
        "M: 나는 오후 내내 치과에 있었어.",
        "W: 선생님이 칠판에 많이 쓰셨어.",
        "M: 시험에 나온다고 하셨어?",
        "W: 응, 시험이 2주밖에 안 남았어.",
        "M: 네 필기 좀 복사해 줄 수 있어?",
        "W: 그럼, 점심시간에 복사해 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 체육관 이용에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Here is how to use the school gym after class. " +
            "The gym is open on Monday, Wednesday and Friday evenings. " +
            "You must change into indoor shoes before you step onto the floor. " +
            "Balls and rackets can be borrowed at the small window by the door. " +
            "Never hang on the basketball net or climb the wall bars.",
        ],
      ],
      choices: [
        "문을 여는 요일",
        "신발에 관한 규칙",
        "내야 하는 이용료",
        "빌릴 수 있는 물건",
        "하면 안 되는 행동",
      ],
      answer: 3,
      clue: "The gym is open on Monday, Wednesday and Friday evenings.",
      explanation:
        "요일, 신발 규칙, 빌릴 수 있는 물건, 금지 행동은 말했지만 이용료는 말하지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 방과 후 체육관 이용 방법을 알려 드립니다. 체육관은 월요일, 수요일, 금요일 저녁에 엽니다. 바닥에 들어서기 전에 반드시 실내화로 갈아 신어야 합니다. 공과 라켓은 문 옆 작은 창구에서 빌릴 수 있습니다. 농구 골대에 매달리거나 늑목에 올라가지 마세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This stands on the floor or sits on a table in summer. " +
            "It has three or four blades behind a round metal cover. " +
            "When you press the button, the blades turn very fast. " +
            "The moving air makes your face and neck feel cooler. " +
            "Never put your finger through the cover while it is on.",
        ],
      ],
      choices: ["우산", "모자", "부채", "선풍기", "난로"],
      answer: 4,
      clue: "When you press the button, the blades turn very fast.",
      explanation:
        "둥근 덮개 안의 날개가 빠르게 돌며 바람을 만드는 것은 선풍기이다. 따라서 답은 ④이다.",
      translation: [
        "M: 이것은 여름에 바닥에 세우거나 탁자 위에 놓습니다. 둥근 쇠 덮개 뒤에 날개가 서너 개 있습니다. 단추를 누르면 날개가 아주 빠르게 돕니다. 움직이는 공기가 얼굴과 목을 시원하게 해 줍니다. 켜져 있을 때 덮개 안으로 손가락을 넣지 마세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Whose turn is it to speak?"],
        ["W", "It rained a lot last night."],
        ["ANN", "Number two."],
        ["M", "Would you like some water?"],
        ["W", "Yes, please. I'm thirsty."],
        ["ANN", "Number three."],
        ["M", "How do you spell your name?"],
        ["W", "J-I-N-A, Jina."],
        ["ANN", "Number four."],
        ["M", "Did you enjoy the trip?"],
        ["W", "Yes, it was wonderful."],
        ["ANN", "Number five."],
        ["M", "What should I bring tomorrow?"],
        ["W", "Just your textbook."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Whose turn is it to speak?",
      explanation:
        "누구 차례인지 묻는 말에 어젯밤 비가 많이 왔다고 답했으므로 ①의 대화가 어색하다. 따라서 답은 ①이다.",
      translation: [
        "① M: 누구 차례야? / W: 어젯밤에 비가 많이 왔어.",
        "② M: 물 좀 마실래? / W: 응, 목말라.",
        "③ M: 이름 철자가 어떻게 돼? / W: J-I-N-A, 지나.",
        "④ M: 여행 재밌었어? / W: 응, 정말 좋았어.",
        "⑤ M: 내일 뭐 가져가야 해? / W: 교과서만.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiwoo, isn't your P.E. class right after lunch?"],
        ["W", "Yes, and we are running the relay today."],
        ["M", "Are you wearing your gym clothes already?"],
        ["W", "No, they are still in my locker downstairs."],
        ["M", "Lunch time ends in about eight minutes."],
        ["W", "The locker room is on the first floor."],
        ["M", "You should go now or you'll be late."],
        ["W", "I'll go and get them right away."],
      ],
      choices: [
        "체육복을 가지러 가기",
        "급식실에 가기",
        "교실을 청소하기",
        "숙제를 하기",
        "집으로 돌아가기",
      ],
      answer: 1,
      clue: "I'll go and get them right away.",
      explanation:
        "여자는 지금 바로 사물함에 체육복을 가지러 가겠다고 했다. 따라서 답은 ①이다.",
      translation: [
        "M: 지우야, 점심 끝나고 바로 체육 아니야?",
        "W: 응, 오늘 계주 뛰어.",
        "M: 체육복 벌써 입었어?",
        "W: 아니, 아래층 사물함에 있어.",
        "M: 점심시간이 8분쯤 남았어.",
        "W: 탈의실이 1층이야.",
        "M: 지금 가야 안 늦어.",
        "W: 바로 가서 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 예약할 사진관을 고르시오.",
      lines: [
        ["M", "Seoyeon, let's pick a photo studio for our family picture."],
        ["W", "Here are five studios I found near our home."],
        ["M", "How far can we go with Grandmother?"],
        ["W", "Within ten minutes by car would be best."],
        ["M", "All right. What about the price?"],
        ["W", "Under one hundred thousand won for the whole set."],
        ["M", "Does the studio have to open on Sunday?"],
        ["W", "Yes, Dad only has Sundays off this month."],
        ["M", "Then only one studio here works for us."],
        ["W", "I'll call them tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Within ten minutes by car would be best.",
      explanation:
        "차로 10분 이내이고, 10만 원 이하이며, 일요일에 여는 곳을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Car: 5 min / Price: 120,000 won / Sunday: Open" },
          { no: 2, label: "②", value: "Car: 15 min / Price: 90,000 won / Sunday: Open" },
          { no: 3, label: "③", value: "Car: 8 min / Price: 85,000 won / Sunday: Closed" },
          { no: 4, label: "④", value: "Car: 20 min / Price: 70,000 won / Sunday: Closed" },
          { no: 5, label: "⑤", value: "Car: 7 min / Price: 95,000 won / Sunday: Open" },
        ],
      },
      translation: [
        "M: 서연아, 가족사진 찍을 사진관 고르자.",
        "W: 집 근처에서 찾은 다섯 곳이 여기 있어.",
        "M: 할머니 모시고 얼마나 멀리 갈 수 있어?",
        "W: 차로 10분 안쪽이 제일 좋아.",
        "M: 알겠어. 가격은?",
        "W: 전체 한 벌에 10만 원 이하로.",
        "M: 일요일에 여는 곳이어야 해?",
        "W: 응, 이번 달에 아빠는 일요일만 쉬셔.",
        "M: 그럼 여기서 되는 곳은 하나뿐이네.",
        "W: 내일 아침에 전화할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 자원봉사를 가기로 한 날짜를 고르시오.",
      lines: [
        ["W", "Hyunjun, the animal shelter needs helpers this month."],
        ["M", "I'd like to go. Which days can we choose?"],
        ["W", "They take students on the sixth, the thirteenth and the twentieth."],
        ["M", "The sixth is the day of our English speaking test."],
        ["W", "Right, and I have a family dinner on the thirteenth."],
        ["M", "Then the twentieth is the only day left for us."],
        ["W", "It's a Saturday, so we can stay all morning."],
        ["M", "Let's sign up for the twentieth today."],
        ["W", "I'll write both our names on the list."],
      ],
      choices: [
        "the 6th",
        "the 10th",
        "the 13th",
        "the 16th",
        "the 20th",
      ],
      answer: 5,
      clue: "Then the twentieth is the only day left for us.",
      explanation:
        "6일은 시험, 13일은 가족 모임이어서 20일로 정했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 현준아, 이번 달에 동물 보호소에서 도우미를 구해.",
        "M: 가고 싶어. 어떤 날 중에 고를 수 있어?",
        "W: 6일, 13일, 20일에 학생을 받아 줘.",
        "M: 6일은 영어 말하기 시험 날이야.",
        "W: 맞아, 그리고 13일에는 가족 모임이 있어.",
        "M: 그럼 남는 건 20일뿐이네.",
        "W: 토요일이라 오전 내내 있을 수 있어.",
        "M: 오늘 20일로 신청하자.",
        "W: 내가 우리 둘 이름을 명단에 적을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeyang, did you stay home all weekend again?"],
        ["M", "No, I went to the traditional market with my grandmother."],
        ["W", "What did the two of you buy there?"],
        ["M", "Green onions, tofu and a big bag of sweet potatoes."],
        ["W", "Was the market crowded on Saturday morning?"],
        ["M", "Very. I carried both bags all the way home."],
        ["W", "Your grandmother must have been happy."],
        ["M", "She bought me a hotteok on the way back."],
      ],
      choices: [
        "서점에 다녀오기",
        "할머니와 시장에 다녀오기",
        "축구 경기를 하기",
        "가족과 캠핑을 가기",
        "도서관에서 공부하기",
      ],
      answer: 2,
      clue: "No, I went to the traditional market with my grandmother.",
      explanation:
        "남자는 토요일 아침에 할머니와 전통 시장에 다녀왔다. 따라서 답은 ②이다.",
      translation: [
        "W: 태양아, 이번 주말에도 집에만 있었어?",
        "M: 아니, 할머니랑 전통 시장에 갔어.",
        "W: 둘이서 뭘 샀어?",
        "M: 파, 두부, 고구마 한 자루.",
        "W: 토요일 아침에 시장 붐볐어?",
        "M: 아주. 집까지 봉지 두 개를 다 들고 왔어.",
        "W: 할머니가 좋아하셨겠다.",
        "M: 오는 길에 호떡 사 주셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, everyone in the building. " +
            "The elevator will be checked by engineers this Thursday. " +
            "It will not work between ten and three on that day. " +
            "Please use the stairs at either end of the hallway. " +
            "If you need help carrying something heavy, call the front desk. " +
            "Thank you for your understanding.",
        ],
      ],
      choices: [
        "승강기 점검을 알리려고",
        "안전 규칙을 안내하려고",
        "할인 행사를 알리려고",
        "분실물을 찾아가라고",
        "공연 시작을 알리려고",
      ],
      answer: 1,
      clue: "The elevator will be checked by engineers this Thursday.",
      explanation:
        "목요일에 승강기 점검이 있어 쓸 수 없다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 건물에 계신 여러분께 알려 드립니다. 이번 주 목요일에 기술자들이 승강기를 점검합니다. 그날 열 시부터 세 시까지는 승강기를 쓸 수 없습니다. 복도 양쪽 끝에 있는 계단을 이용해 주십시오. 무거운 물건을 옮기실 때 도움이 필요하면 안내 데스크로 전화해 주십시오. 양해해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you renting skates today?"],
        ["W", "Yes, two pairs of skates for three hours."],
        ["M", "One pair is three dollars per hour."],
        ["W", "Do we also need to rent helmets?"],
        ["M", "Helmets are two dollars each for the whole day."],
        ["W", "We'll take two helmets as well."],
        ["M", "All right, that's everything for you."],
        ["W", "Here is my card. Thank you."],
      ],
      choices: ["$18", "$22", "$24", "$26", "$28"],
      answer: 2,
      clue: "One pair is three dollars per hour. / Helmets are two dollars each for the whole day.",
      explanation:
        "스케이트 두 켤레를 세 시간 빌리면 18달러이고 헬멧 두 개 4달러를 더하면 22달러이다. 따라서 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 오늘 스케이트 빌리시나요?",
        "W: 네, 스케이트 두 켤레를 세 시간 빌릴게요.",
        "M: 한 켤레에 시간당 3달러입니다.",
        "W: 헬멧도 빌려야 하나요?",
        "M: 헬멧은 하루 종일 개당 2달러입니다.",
        "W: 헬멧도 두 개 빌릴게요.",
        "M: 알겠습니다. 이걸로 다 되셨습니다.",
        "W: 여기 카드요. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerim, you always finish your homework at school."],
        ["W", "I use the twenty minutes before the bus comes."],
        ["M", "Isn't it noisy in the classroom at that time?"],
        ["W", "I go to the back corner of the library instead."],
        ["M", "I always carry my homework home in my bag."],
        ["W", "And do you finish it at home?"],
        ["M", "Usually not. I get sleepy after dinner."],
        ["W", "Then try the library for just one week."],
        ["M", "Could I sit with you tomorrow afternoon?"],
      ],
      choices: [
        "I never go to the library.",
        "You should stay in the classroom.",
        "Sure, meet me at four.",
        "I finish my homework at home.",
        "The library is closed all week.",
      ],
      answer: 3,
      clue: "Could I sit with you tomorrow afternoon?",
      explanation:
        "남자가 내일 오후에 같이 앉아도 되는지 물었으므로, 4시에 만나자는 ③이 가장 자연스럽다.",
      translation: [
        "M: 예림아, 너는 늘 학교에서 숙제를 끝내더라.",
        "W: 버스 오기 전 20분을 써.",
        "M: 그 시간에 교실 시끄럽지 않아?",
        "W: 대신 도서관 뒤쪽 구석에 가.",
        "M: 나는 늘 숙제를 가방에 넣어 집에 가져가.",
        "W: 그럼 집에서는 다 해?",
        "M: 대개 못 해. 저녁 먹고 나면 졸려.",
        "W: 그럼 일주일만 도서관에서 해 봐.",
        "M: 내일 오후에 너랑 같이 앉아도 될까?",
        "W: 그럼, 4시에 만나.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Dongha, did you finish the model ship for the fair?"],
        ["M", "Almost. The sails keep falling off the mast."],
        ["W", "What kind of glue are you using?"],
        ["M", "Just the white glue from the art room."],
        ["W", "White glue is too weak for cloth and wood."],
        ["M", "Then what should I use instead?"],
        ["W", "A glue gun holds cloth much better."],
        ["M", "I have never used a glue gun before."],
        ["W", "The art teacher will show you how after class."],
      ],
      choices: [
        "My ship has no sails.",
        "White glue works well.",
        "The fair was last week.",
        "I already used a glue gun.",
        "Then I'll ask her today.",
      ],
      answer: 5,
      clue: "The art teacher will show you how after class.",
      explanation:
        "미술 선생님이 알려 주실 거라고 했으므로, 오늘 여쭤보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 동하야, 박람회에 낼 모형 배 다 만들었어?",
        "M: 거의. 돛이 자꾸 돛대에서 떨어져.",
        "W: 무슨 풀 쓰고 있어?",
        "M: 미술실에 있는 흰 풀.",
        "W: 흰 풀은 천이랑 나무에는 너무 약해.",
        "M: 그럼 뭘 써야 해?",
        "W: 글루건이 천을 훨씬 잘 붙여.",
        "M: 글루건은 한 번도 안 써 봤어.",
        "W: 수업 끝나고 미술 선생님이 알려 주실 거야.",
        "M: 그럼 오늘 여쭤볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sujeong, your class won the clean classroom award again."],
        ["W", "We were surprised too. Nobody expected it."],
        ["M", "What do you do differently from us?"],
        ["W", "Each student cleans only one small area."],
        ["M", "Just one area for the whole week?"],
        ["W", "Yes, so everyone knows exactly what to do."],
        ["M", "In my class two people clean everything."],
        ["W", "That's why they get tired and give up."],
        ["M", "Could you help me make a plan like yours?"],
      ],
      choices: [
        "Your class is already clean.",
        "I don't clean my classroom.",
        "We have no cleaning plan.",
        "Sure, let's make one at lunch.",
        "You should clean it alone.",
      ],
      answer: 4,
      clue: "Could you help me make a plan like yours?",
      explanation:
        "남자가 청소 계획 짜는 걸 도와 달라고 했으므로, 점심시간에 같이 만들자는 ④가 가장 자연스럽다.",
      translation: [
        "M: 수정아, 너희 반이 또 깨끗한 교실 상을 받았네.",
        "W: 우리도 놀랐어. 아무도 기대 안 했거든.",
        "M: 우리랑 뭐가 다르게 해?",
        "W: 학생마다 작은 구역 하나씩만 맡아.",
        "M: 일주일 내내 한 구역만?",
        "W: 응, 그래서 다들 뭘 할지 정확히 알아.",
        "M: 우리 반은 두 명이 다 해.",
        "W: 그러니까 지쳐서 포기하는 거야.",
        "M: 우리도 그런 계획 짜는 것 좀 도와줄래?",
        "W: 그럼, 점심시간에 같이 만들자.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Hana가 Jiseok에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Hana : ________________",
      lines: [
        [
          "W",
          "Hana and Jiseok are working together at the school computer room. " +
            "Jiseok has been typing their group report for almost an hour. " +
            "Hana notices that he has not saved the file even once. " +
            "The lights in the room flickered twice a few minutes ago. " +
            "She wants to tell him before all their work disappears. " +
            "In this situation, what would Hana most likely say to Jiseok?",
        ],
      ],
      choices: [
        "You should save the file now.",
        "Let's print the report tomorrow.",
        "The computer room closes at six.",
        "Can I use your keyboard?",
        "Our report is too long.",
      ],
      answer: 1,
      clue: "She wants to tell him before all their work disappears.",
      explanation:
        "한 시간 동안 저장을 한 번도 안 했고 정전 위험이 있으므로, 지금 저장하라고 말하는 ①이 가장 적절하다.",
      translation: [
        "W: 하나와 지석이는 학교 컴퓨터실에서 함께 작업하고 있습니다. 지석이는 거의 한 시간째 모둠 보고서를 치고 있습니다. 하나는 지석이가 파일을 한 번도 저장하지 않은 것을 봅니다. 몇 분 전에 방 안의 불이 두 번 깜빡였습니다. 하나는 작업한 것이 모두 사라지기 전에 알려 주고 싶습니다. 이런 상황에서 하나가 지석이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
