/** 중1 듣기 26회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 26회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 우산을 고르시오.",
      lines: [
        ["W", "Hello. Do you need an umbrella for the rainy season?"],
        ["M", "Yes. Mine broke on the way here."],
        ["W", "We have long ones and folding ones."],
        ["M", "A folding one, please. It fits in my school bag."],
        ["W", "All right. This folding one has a flower pattern."],
        ["M", "Flowers are not really my style."],
        ["W", "Then here is a folding one with wide stripes."],
        ["M", "That's the one. I'll take the striped umbrella."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A folding one, please. / I'll take the striped umbrella.",
      explanation:
        "남자는 접이식 우산을 원하고, 꽃무늬 대신 줄무늬를 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five closed umbrellas standing side by side as five choices, clean black line art on white. " +
          "① a LONG umbrella with a FLOWER pattern. " +
          "② a LONG umbrella with wide STRIPES. " +
          "③ a SHORT FOLDING umbrella with a FLOWER pattern. " +
          "④ a SHORT FOLDING umbrella with no pattern at all. " +
          "⑤ a SHORT FOLDING umbrella with wide STRIPES.",
      },
      translation: [
        "W: 안녕하세요. 장마철 우산 찾으세요?",
        "M: 네. 오는 길에 제 것이 부러졌어요.",
        "W: 긴 우산도 있고 접이식도 있어요.",
        "M: 접이식으로 주세요. 책가방에 들어가야 해서요.",
        "W: 알겠습니다. 이 접이식은 꽃무늬가 있어요.",
        "M: 꽃무늬는 제 취향이 아니에요.",
        "W: 그럼 굵은 줄무늬 접이식이 여기 있어요.",
        "M: 그거예요. 줄무늬 우산으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 마라톤 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, are you running in the school marathon?"],
        ["W", "I think so. What day is it again?"],
        ["M", "It's next Tuesday, right after the morning class."],
        ["W", "How far do we have to run?"],
        ["M", "Three kilometers around the school park."],
        ["W", "That's not too bad. Do winners get anything?"],
        ["M", "The top three runners get a book coupon."],
        ["W", "Nice. Should I wear my gym clothes?"],
        ["M", "Yes, and running shoes, not your school shoes."],
      ],
      choices: ["열리는 요일", "달리는 거리", "참가비", "상품", "복장"],
      answer: 3,
      clue: "참가비는 대화에서 언급되지 않았다.",
      explanation:
        "요일(다음 주 화요일), 거리(3킬로미터), 상품(도서 상품권), 복장(체육복과 운동화)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ③이다.",
      translation: [
        "M: 서연아, 교내 마라톤 뛸 거야?",
        "W: 그럴 것 같아. 그게 언제였지?",
        "M: 다음 주 화요일, 오전 수업 끝나고 바로야.",
        "W: 얼마나 달려야 해?",
        "M: 학교 공원을 도는 3킬로미터야.",
        "W: 그 정도면 괜찮네. 1등 하면 뭐 줘?",
        "M: 상위 세 명은 도서 상품권을 받아.",
        "W: 좋다. 체육복 입으면 돼?",
        "M: 응, 그리고 실내화 말고 운동화 신어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Green Park Bike Shop?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "I left my bike there last Thursday for repair."],
        ["W", "Let me check. What is your name, please?"],
        ["M", "It's Taemin Kwon. The back tire was flat."],
        ["W", "Ah, yes. The new tire arrived this morning."],
        ["M", "So can I pick it up after school today?"],
        ["W", "Sure. We close at seven, so come before that."],
      ],
      choices: [
        "자전거를 새로 사려고",
        "수리 비용을 물어보려고",
        "가게 위치를 물어보려고",
        "맡긴 자전거를 찾을 수 있는지 물으려고",
        "자전거를 빌리려고",
      ],
      answer: 4,
      clue: "So can I pick it up after school today?",
      explanation:
        "남자는 지난 목요일에 수리를 맡긴 자전거를 오늘 찾아갈 수 있는지 물으려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요, 그린파크 자전거 가게죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 지난 목요일에 자전거를 수리 맡겼어요.",
        "W: 확인해 볼게요. 성함이 어떻게 되시죠?",
        "M: 권태민이요. 뒷바퀴에 바람이 빠졌었어요.",
        "W: 아, 네. 새 타이어가 오늘 아침에 도착했어요.",
        "M: 그럼 오늘 방과 후에 찾아가도 될까요?",
        "W: 네. 7시에 문을 닫으니 그전에 오세요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taemin, what time does the free concert start?"],
        ["M", "At seven in the evening, in the park."],
        ["W", "Do we need to get there early for seats?"],
        ["M", "Yes, the front rows fill up very fast."],
        ["W", "How early should we be there, then?"],
        ["M", "An hour before the concert, I'd say."],
        ["W", "Okay, let's meet at the park gate at that time."],
        ["M", "Good. I'll bring a mat for us to sit on."],
        ["W", "And I'll bring some sandwiches for both of us."],
      ],
      choices: ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
      answer: 3,
      clue: "An hour before the concert, I'd say.",
      explanation:
        "공연이 저녁 7시에 시작하고 한 시간 전에 가기로 했으므로 만나는 시각은 6시이다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 무료 공연 몇 시에 시작해?",
        "M: 저녁 7시에, 공원에서 해.",
        "W: 자리 잡으려면 일찍 가야 해?",
        "M: 응, 앞줄은 아주 빨리 차.",
        "W: 그럼 얼마나 일찍 가야 해?",
        "M: 공연 한 시간 전쯤이 좋을 것 같아.",
        "W: 알겠어, 그 시간에 공원 정문에서 만나자.",
        "M: 좋아. 내가 앉을 돗자리 가져갈게.",
        "W: 나는 우리 둘 먹을 샌드위치 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, why are you looking under the desk again?"],
        ["W", "My grandmother's ring is gone. I had it this morning."],
        ["M", "Are you sure you wore it to school?"],
        ["W", "Yes, I touched it during the math class."],
        ["M", "Did you check the gym and the cafeteria?"],
        ["W", "Twice each. She gave it to me before she passed away."],
        ["M", "Let's ask at the office. Someone may have found it."],
        ["W", "I can't stop thinking about losing it forever."],
      ],
      choices: ["proud", "bored", "thankful", "surprised", "worried"],
      answer: 5,
      clue: "I can't stop thinking about losing it forever.",
      explanation:
        "할머니가 주신 반지를 잃어버려 영영 못 찾을까 봐 계속 생각난다고 했으므로 여자의 심정은 '걱정스러운(worried)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 서연아, 왜 또 책상 밑을 보고 있어?",
        "W: 할머니 반지가 없어졌어. 아침엔 있었는데.",
        "M: 학교에 끼고 온 거 확실해?",
        "W: 응, 수학 시간에 만졌어.",
        "M: 체육관이랑 급식실은 확인했어?",
        "W: 각각 두 번씩. 할머니가 돌아가시기 전에 주신 거야.",
        "M: 행정실에 물어보자. 누가 주웠을지도 몰라.",
        "W: 영영 못 찾을 것 같아서 계속 생각나.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Excuse me, is this seat taken?"],
        ["M", "No, please sit here."],
        ["ANN", "Number two."],
        ["W", "How much is a cup of tea?"],
        ["M", "It's three dollars."],
        ["ANN", "Number three."],
        ["W", "Do you want some of my sandwich?"],
        ["M", "No, thanks. I already ate."],
        ["ANN", "Number four."],
        ["W", "Excuse me, your milk is spilling."],
        ["M", "Oh no, thank you for telling me."],
        ["ANN", "Number five."],
        ["W", "What time does the cafe close?"],
        ["M", "It closes at nine."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Excuse me, your milk is spilling.",
      explanation:
        "그림은 카페 탁자에서 남자의 우유갑이 넘어져 우유가 흐르는 것을 여자가 가리키며 알려 주는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small cafe, clean black line art on a plain white background, no writing anywhere. " +
          "A boy sits at a table reading, not noticing that a tipped-over milk carton beside his hand is pouring milk across the table. " +
          "A girl at the next table points at the spilling milk and speaks to him. " +
          "A counter and two empty chairs are drawn simply in the background.",
      },
      translation: [
        "① W: 저기요, 이 자리 임자 있나요? / M: 아니요, 앉으세요.",
        "② W: 차 한 잔에 얼마예요? / M: 3달러입니다.",
        "③ W: 내 샌드위치 좀 먹을래? / M: 괜찮아, 벌써 먹었어.",
        "④ W: 저기요, 우유가 흐르고 있어요. / M: 어머, 알려 줘서 고마워요.",
        "⑤ W: 이 카페는 몇 시에 닫아요? / M: 9시에 닫아요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, do you have a class right after lunch?"],
        ["W", "No, I have a free period today. Why?"],
        ["M", "I have to go to the dentist at one o'clock."],
        ["W", "Oh, will you miss the history class then?"],
        ["M", "Yes, and the teacher gives important notes."],
        ["W", "I see. Do you want my textbook?"],
        ["M", "Actually, could you take notes for me?"],
        ["W", "Of course. I'll write down everything he says."],
      ],
      choices: ["교과서 빌려주기", "수업 필기해 주기", "치과 같이 가기", "숙제 대신 내 주기", "선생님께 말씀드리기"],
      answer: 2,
      clue: "Actually, could you take notes for me?",
      explanation:
        "남자는 치과에 가느라 역사 수업을 빠지게 되어, 대신 필기를 해 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 서연아, 점심 먹고 바로 수업 있어?",
        "W: 아니, 오늘은 공강이야. 왜?",
        "M: 1시에 치과에 가야 해.",
        "W: 아, 그럼 역사 수업을 못 듣겠네?",
        "M: 응, 선생님이 중요한 내용을 알려 주시는데.",
        "W: 그렇구나. 내 교과서 빌려줄까?",
        "M: 그것보다, 나 대신 필기해 줄 수 있어?",
        "W: 그럼. 선생님 말씀 다 적어 둘게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 사진 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The school photo contest is back this year. " +
            "The subject is the four seasons of our school. " +
            "Send one photo to the art office by October 20th. " +
            "Every photo must be taken inside our school grounds. " +
            "The three best photos will be printed and hung in the main hallway. " +
            "We look forward to seeing your work.",
        ],
      ],
      choices: ["대회 주제", "제출 마감일", "사진 찍을 장소", "심사하는 사람", "입상작의 쓰임"],
      answer: 4,
      clue: "심사하는 사람은 방송에서 언급되지 않았다.",
      explanation:
        "주제(학교의 사계절), 마감일(10월 20일), 찍을 장소(학교 안), 입상작의 쓰임(복도에 걸림)은 언급되지만 심사하는 사람은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 올해도 학교 사진 대회가 열립니다. 주제는 우리 학교의 사계절입니다. 10월 20일까지 미술실로 사진 한 장을 보내 주세요. 모든 사진은 학교 안에서 찍은 것이어야 합니다. 가장 좋은 사진 세 장은 인화하여 중앙 복도에 걸 예정입니다. 여러분의 작품을 기대합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "You see this in almost every classroom in Korea. " +
            "It is wide and flat, and it hangs on the front wall. " +
            "Teachers write on it with markers of different colors. " +
            "At the end of the class, someone wipes it clean with an eraser. " +
            "Long ago it was black, but now it is usually white or green.",
        ],
      ],
      choices: ["사물함", "칠판", "지도", "창문", "시계"],
      answer: 2,
      clue: "Teachers write on it with markers of different colors.",
      explanation:
        "교실 앞 벽에 걸려 있고, 선생님이 색색의 펜으로 쓰며, 수업이 끝나면 지우개로 지우는 것은 칠판이다. 따라서 답은 ②이다.",
      translation: [
        "M: 여러분은 한국의 거의 모든 교실에서 이것을 봅니다. 넓고 평평하며 앞쪽 벽에 걸려 있습니다. 선생님들은 여러 색의 펜으로 여기에 씁니다. 수업이 끝나면 누군가 지우개로 깨끗이 지웁니다. 예전에는 검은색이었지만 지금은 보통 흰색이나 초록색입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How tall are you?"],
        ["W", "I'm one hundred sixty centimeters."],
        ["ANN", "Number two."],
        ["M", "What are you doing this evening?"],
        ["W", "I'm going to visit my aunt."],
        ["ANN", "Number three."],
        ["M", "Why are you so late?"],
        ["W", "My favorite color is green."],
        ["ANN", "Number four."],
        ["M", "Can you play the guitar?"],
        ["W", "Yes, I learned it last year."],
        ["ANN", "Number five."],
        ["M", "Would you like some water?"],
        ["W", "Yes, please. I'm thirsty."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Why are you so late?",
      explanation:
        "왜 늦었는지 묻는 말에 좋아하는 색이 초록색이라고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 키가 몇이야? / W: 160센티미터야.",
        "② M: 오늘 저녁에 뭐 해? / W: 이모 댁에 갈 거야.",
        "③ M: 왜 이렇게 늦었어? / W: 내가 좋아하는 색은 초록색이야.",
        "④ M: 기타 칠 줄 알아? / W: 응, 작년에 배웠어.",
        "⑤ M: 물 좀 마실래? / W: 응, 줘. 목말라.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, the school play starts in fifteen minutes."],
        ["M", "I know. Is everyone in costume already?"],
        ["W", "Yes, and I put all the props on the side table."],
        ["M", "Good. Did anyone turn on the stage lights?"],
        ["W", "I tried, but the switch in the hall doesn't work."],
        ["M", "Then someone has to tell the teacher right away."],
        ["W", "I can't. I have to help the actors with their hair."],
        ["M", "Okay, I'll run to the teachers' room and tell him."],
      ],
      choices: ["선생님께 알리기", "소품 옮기기", "배우 머리 손질하기", "무대 청소하기", "의상 갈아입기"],
      answer: 1,
      clue: "Okay, I'll run to the teachers' room and tell him.",
      explanation:
        "무대 조명 스위치가 고장 났는데 여자는 배우들을 도와야 해서, 남자가 교무실로 달려가 선생님께 알리겠다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 태민아, 학교 연극이 15분 뒤에 시작해.",
        "M: 알아. 다들 옷은 갈아입었어?",
        "W: 응, 소품도 내가 다 옆 탁자에 올려놨어.",
        "M: 잘했다. 무대 조명은 누가 켰어?",
        "W: 켜 보려고 했는데 강당 스위치가 안 돼.",
        "M: 그럼 누가 선생님께 바로 알려야 해.",
        "W: 나는 못 가. 배우들 머리 손질을 도와야 해.",
        "M: 알겠어, 내가 교무실로 달려가서 말씀드릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 자전거를 고르시오.",
      lines: [
        ["M", "Seoyeon, which bike are you going to buy?"],
        ["W", "I'm not sure yet. Let's look at the list together."],
        ["M", "Do you want a basket on the front?"],
        ["W", "Yes, I carry my books and lunch box every day."],
        ["M", "Okay. And what about the price?"],
        ["W", "I saved a hundred fifty thousand won, so nothing above that."],
        ["M", "Got it. Any color you don't like?"],
        ["W", "I don't want a black one. It looks too heavy."],
        ["M", "Then there's only one bike left for you."],
        ["W", "Great. Let's go to the shop this afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "I don't want a black one. It looks too heavy.",
      explanation:
        "바구니가 있고, 15만 원 이하이며, 검은색이 아닌 것을 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Basket: Yes / Price: 170,000 won / Color: White" },
          { no: 2, label: "②", value: "Basket: Yes / Price: 140,000 won / Color: White" },
          { no: 3, label: "③", value: "Basket: Yes / Price: 130,000 won / Color: Black" },
          { no: 4, label: "④", value: "Basket: No / Price: 120,000 won / Color: Green" },
          { no: 5, label: "⑤", value: "Basket: No / Price: 150,000 won / Color: White" },
        ],
      },
      translation: [
        "M: 서연아, 어떤 자전거 살 거야?",
        "W: 아직 모르겠어. 목록 같이 보자.",
        "M: 앞에 바구니 있는 게 좋아?",
        "W: 응, 매일 책이랑 도시락을 들고 다녀.",
        "M: 알겠어. 가격은?",
        "W: 15만 원 모았으니까 그보다 비싼 건 안 돼.",
        "M: 그렇구나. 싫은 색 있어?",
        "W: 검은색은 싫어. 너무 무거워 보여.",
        "M: 그럼 너한테 남는 건 하나뿐이네.",
        "W: 좋아. 오늘 오후에 가게 가자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진 전시회에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Seoyeon, when can we go to the photo exhibition?"],
        ["W", "How about June 2nd? It's a Saturday."],
        ["M", "I have to help my dad move furniture that day."],
        ["W", "Then what about June 5th, after school?"],
        ["M", "The gallery is closed every Tuesday."],
        ["W", "Oh, I forgot. I'm free on June 9th."],
        ["M", "But the exhibition ends on the 7th."],
        ["W", "You're right. Then let's go on June 6th."],
        ["M", "June 6th works. I finish my club at three."],
        ["W", "Perfect. Let's meet at the subway exit at four."],
      ],
      choices: ["6월 2일", "6월 5일", "6월 6일", "6월 7일", "6월 9일"],
      answer: 3,
      clue: "You're right. Then let's go on June 6th.",
      explanation:
        "2일에는 아버지를 도와야 하고, 5일은 화요일 휴관이며, 9일은 전시가 끝난 뒤다. 두 사람은 6월 6일에 가기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 서연아, 사진 전시회 언제 갈까?",
        "W: 6월 2일 어때? 토요일이야.",
        "M: 그날은 아버지 가구 옮기는 걸 도와드려야 해.",
        "W: 그럼 6월 5일 방과 후는?",
        "M: 그 갤러리는 화요일마다 문을 닫아.",
        "W: 아, 잊었네. 나는 6월 9일이 비어.",
        "M: 그런데 전시가 7일에 끝나.",
        "W: 맞네. 그럼 6월 6일에 가자.",
        "M: 6월 6일 괜찮아. 동아리가 3시에 끝나.",
        "W: 좋아. 4시에 지하철 출구에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, your hands are covered with white paint."],
        ["M", "I spent all Sunday at my uncle's bookstore."],
        ["W", "Did you sell books for him?"],
        ["M", "No, the shop was closed. We painted the walls."],
        ["W", "Wow, the whole shop in one day?"],
        ["M", "Only the front room. The back room is for next week."],
        ["W", "Was it hard work?"],
        ["M", "My arms still hurt, but the room looks much brighter."],
      ],
      choices: ["책 팔기", "책장 정리하기", "간판 만들기", "청소하기", "가게 벽 칠하기"],
      answer: 5,
      clue: "No, the shop was closed. We painted the walls.",
      explanation:
        "남자는 일요일에 삼촌의 서점에서 벽을 칠했다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 태민아, 손에 흰 페인트가 잔뜩 묻었네.",
        "M: 일요일 내내 삼촌 서점에 있었어.",
        "W: 책 파는 거 도와드렸어?",
        "M: 아니, 가게는 문을 닫았어. 우리는 벽을 칠했어.",
        "W: 우와, 가게 전체를 하루에?",
        "M: 앞쪽 방만. 뒷방은 다음 주에 해.",
        "W: 힘들었어?",
        "M: 아직 팔이 아픈데, 방이 훨씬 밝아졌어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement from the health office. " +
            "A bad cold is going around our school this week. " +
            "Please wash your hands with soap before and after every meal. " +
            "If you feel hot or your throat hurts, come to the health office right away. " +
            "Do not share cups or towels with your classmates. " +
            "Stay healthy, everyone.",
        ],
      ],
      choices: [
        "건강 검진 일정을 알리려고",
        "예방 접종을 권하려고",
        "보건실 위치를 알리려고",
        "감기 예방을 당부하려고",
        "급식 메뉴를 알리려고",
      ],
      answer: 4,
      clue: "Please wash your hands with soap before and after every meal.",
      explanation:
        "학교에 감기가 도니 손을 씻고 컵과 수건을 함께 쓰지 말라고 당부하는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 보건실에서 알려 드립니다. 이번 주 우리 학교에 독한 감기가 돌고 있습니다. 식사 전후에는 비누로 손을 씻어 주세요. 열이 나거나 목이 아프면 바로 보건실로 오세요. 컵이나 수건을 친구와 함께 쓰지 마세요. 모두 건강하세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the flower shop. What would you like?"],
        ["M", "I need five roses and three tulips, please."],
        ["W", "A rose is three dollars and a tulip is two."],
        ["M", "All right. Could you wrap them together?"],
        ["W", "Of course. Wrapping paper costs two dollars."],
        ["M", "That's fine. Please wrap them nicely."],
        ["W", "Sure. And students get two dollars off today."],
        ["M", "Here is my student card, then."],
      ],
      choices: ["$21", "$22", "$23", "$24", "$25"],
      answer: 1,
      clue: "And students get two dollars off today.",
      explanation:
        "장미 5송이 15달러, 튤립 3송이 6달러, 포장지 2달러를 더하면 23달러이고, 학생 할인 2달러를 빼면 21달러이다. 따라서 답은 ①이다.",
      translation: [
        "W: 꽃집에 오신 걸 환영합니다. 무엇을 드릴까요?",
        "M: 장미 다섯 송이랑 튤립 세 송이 주세요.",
        "W: 장미는 3달러, 튤립은 2달러입니다.",
        "M: 알겠어요. 같이 포장해 주실 수 있나요?",
        "W: 물론이죠. 포장지는 2달러입니다.",
        "M: 괜찮아요. 예쁘게 포장해 주세요.",
        "W: 네. 그리고 오늘은 학생에게 2달러 할인이 됩니다.",
        "M: 그럼 여기 학생증이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taemin, you look worried about the English speech."],
        ["M", "I am. I have to speak in front of the whole grade."],
        ["W", "Have you written the whole thing already?"],
        ["M", "Yes, but I keep forgetting the middle part."],
        ["W", "How many times have you practiced out loud?"],
        ["M", "Only twice, and both times I read it from paper."],
        ["W", "That's the problem. Reading is not practicing."],
        ["M", "So what should I do instead of reading it?"],
        ["W", "Record yourself speaking and listen to it once."],
      ],
      choices: [
        "I'll try recording myself tonight.",
        "I'll write a new speech tomorrow.",
        "The speech is in December.",
        "I don't have to speak at all.",
        "Reading aloud is the best way.",
      ],
      answer: 1,
      clue: "Record yourself speaking and listen to it once.",
      explanation:
        "여자가 말하는 것을 녹음해서 들어 보라고 했으므로, 오늘 밤에 녹음해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 태민아, 영어 발표 때문에 걱정돼 보인다.",
        "M: 맞아. 학년 전체 앞에서 말해야 해.",
        "W: 원고는 다 썼어?",
        "M: 응, 그런데 중간 부분을 자꾸 잊어버려.",
        "W: 소리 내서 몇 번 연습했어?",
        "M: 두 번뿐이야. 그것도 종이 보고 읽었어.",
        "W: 그게 문제야. 읽는 건 연습이 아니야.",
        "M: 그럼 읽는 대신 뭘 해야 해?",
        "W: 말하는 걸 녹음해서 한 번 들어 봐.",
        "M: 오늘 밤에 녹음해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Seoyeon, did you decide on your free topic report?"],
        ["W", "Not yet. Everything I think of feels boring."],
        ["M", "What do you do when you have free time?"],
        ["W", "I usually bake bread with my mother on weekends."],
        ["M", "That's a great topic. Nobody else will choose it."],
        ["W", "Bread? Is that really a school report topic?"],
        ["M", "Sure. You can explain why the dough rises."],
        ["W", "Hmm, that does sound interesting."],
        ["M", "And you could bring a small loaf for the class."],
      ],
      choices: [
        "I don't know how to bake.",
        "That's a good idea. I'll write about bread.",
        "My report is already finished.",
        "Let's choose a topic next month.",
        "The class is too small for that.",
      ],
      answer: 2,
      clue: "And you could bring a small loaf for the class.",
      explanation:
        "남자가 빵을 주제로 삼고 작은 빵도 가져오라고 권했으므로, 좋은 생각이라며 빵에 대해 쓰겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 서연아, 자유 주제 보고서 정했어?",
        "W: 아직. 생각나는 게 다 지루해 보여.",
        "M: 시간 날 때 뭐 해?",
        "W: 주말마다 엄마랑 빵을 구워.",
        "M: 그거 좋은 주제다. 아무도 안 고를걸.",
        "W: 빵? 그게 학교 보고서 주제가 돼?",
        "M: 그럼. 반죽이 왜 부푸는지 설명하면 되지.",
        "W: 음, 그건 재미있겠다.",
        "M: 그리고 작은 빵 하나를 반에 가져와도 되고.",
        "W: 좋은 생각이야. 빵에 대해 쓸게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Taemin, have you seen my water bottle anywhere?"],
        ["M", "The blue one with the white cap?"],
        ["W", "Yes, that one. I've looked everywhere since lunch."],
        ["M", "Did you take it to the music room this morning?"],
        ["W", "I think so, but the room was locked when I went back."],
        ["M", "The music teacher opens it again at four."],
        ["W", "That's too late. My bus leaves at three forty."],
        ["M", "Then ask the office. They keep a spare key there."],
        ["W", "Do you think they will open it for a student?"],
        ["M", "Yes, if you explain it to Mr. Jung at the front desk."],
      ],
      choices: [
        "I'll go and talk to Mr. Jung now.",
        "The bottle was green, not blue.",
        "I'll wait until four o'clock then.",
        "Music class starts next week.",
        "I already found my bottle at home.",
      ],
      answer: 1,
      clue: "Yes, if you explain it to Mr. Jung at the front desk.",
      explanation:
        "남자가 안내 데스크의 정 선생님께 말씀드리면 열어 주실 거라고 했으므로, 지금 가서 말씀드리겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 태민아, 내 물병 어디서 못 봤어?",
        "M: 뚜껑이 흰 파란색?",
        "W: 응, 그거. 점심시간부터 다 찾아봤어.",
        "M: 오늘 아침에 음악실에 가져갔어?",
        "W: 그런 것 같은데, 다시 갔더니 문이 잠겨 있었어.",
        "M: 음악 선생님이 4시에 다시 여셔.",
        "W: 너무 늦어. 내 버스가 3시 40분에 떠나.",
        "M: 그럼 행정실에 물어봐. 거기 여분 열쇠가 있어.",
        "W: 학생한테도 열어 주실까?",
        "M: 응, 안내 데스크에 계신 정 선생님께 말씀드리면 돼.",
        "W: 지금 가서 정 선생님께 말씀드릴게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minji가 Woojin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Minji : ________________",
      lines: [
        [
          "W",
          "Minji and Woojin are classmates on the same cleaning team. " +
            "Today they have to empty the recycling bins after school. " +
            "Woojin is putting paper cups into the paper bin. " +
            "Minji knows that paper cups go into the plastic bin at their school. " +
            "She wants to tell him before the whole bin is mixed up. " +
            "In this situation, what would Minji most likely say to Woojin?",
        ],
      ],
      choices: [
        "Let's go home before it rains.",
        "The bins were emptied yesterday.",
        "I'll buy you a cup of coffee.",
        "We have no cleaning duty today.",
        "Paper cups go in the plastic bin.",
      ],
      answer: 5,
      clue: "Minji knows that paper cups go into the plastic bin at their school.",
      explanation:
        "우진이가 종이컵을 종이 수거함에 넣고 있는데 학교에서는 플라스틱 수거함에 넣어야 하므로, 그 사실을 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "W: 민지와 우진이는 같은 청소 조인 같은 반 친구입니다. 오늘 두 사람은 방과 후에 재활용 수거함을 비워야 합니다. 우진이는 종이컵을 종이 수거함에 넣고 있습니다. 민지는 우리 학교에서 종이컵은 플라스틱 수거함에 넣어야 한다는 것을 알고 있습니다. 민지는 수거함이 다 섞이기 전에 알려 주고 싶습니다. 이런 상황에서 민지가 우진이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
