/** 중1 듣기 36회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 36회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 액자를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a photo frame?"],
        ["W", "Yes. My photo is taller than it is wide."],
        ["M", "Then you need a tall frame, not a wide one."],
        ["W", "Right. And I want to put it on my desk."],
        ["M", "These frames have a stand on the back."],
        ["W", "A stand is perfect. I won't hang it on the wall."],
        ["M", "Do you like the ones with flowers on the edge?"],
        ["W", "No, a plain edge looks better with my photo."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Then you need a tall frame, not a wide one. / No, a plain edge looks better with my photo.",
      explanation:
        "여자는 세로로 긴 액자에 받침대가 있고 테두리에 무늬가 없는 것을 골랐다. 따라서 답은 ①이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five photo frames standing side by side as five choices, clean black line art on white. " +
          "① a TALL upright frame with a PLAIN edge and a small STAND leg behind it. " +
          "② a WIDE landscape frame with a PLAIN edge and a small STAND leg behind it. " +
          "③ a TALL upright frame with a PLAIN edge and NO stand, with a hanging hook on top. " +
          "④ a TALL upright frame with FLOWER shapes carved along the edge and a STAND leg behind it. " +
          "⑤ a WIDE landscape frame with FLOWER shapes along the edge and NO stand, with a hanging hook.",
      },
      translation: [
        "M: 안녕하세요. 액자 찾으세요?",
        "W: 네. 제 사진이 가로보다 세로가 길어요.",
        "M: 그러면 가로가 아니라 세로로 긴 액자가 필요하시겠네요.",
        "W: 맞아요. 그리고 책상 위에 세워 둘 거예요.",
        "M: 이 액자들은 뒤에 받침대가 있어요.",
        "W: 받침대 있으면 딱 좋아요. 벽에는 안 걸 거예요.",
        "M: 테두리에 꽃무늬 있는 건 어떠세요?",
        "W: 아니요, 제 사진에는 무늬 없는 게 더 어울려요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 뮤지컬 공연에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hyunsu, our school musical is almost ready."],
        ["M", "When will it be on stage?"],
        ["W", "On the last Saturday of this month."],
        ["M", "Where are you going to perform it?"],
        ["W", "In the large hall on the first floor."],
        ["M", "How long does the whole show run?"],
        ["W", "About an hour and a half without a break."],
        ["M", "How many students are in it?"],
        ["W", "Twenty-two, and eight of them also sing."],
      ],
      choices: [
        "공연하는 날",
        "표의 가격",
        "공연하는 장소",
        "공연에 걸리는 시간",
        "출연하는 학생 수",
      ],
      answer: 2,
      clue: "On the last Saturday of this month. / Twenty-two, and eight of them also sing.",
      explanation:
        "날짜, 장소, 공연 시간, 출연 인원은 말했지만 표 가격은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 현수야, 우리 학교 뮤지컬이 거의 다 준비됐어.",
        "M: 언제 무대에 올려?",
        "W: 이번 달 마지막 토요일에.",
        "M: 어디서 공연해?",
        "W: 1층 대강당에서.",
        "M: 공연은 얼마나 걸려?",
        "W: 쉬는 시간 없이 한 시간 반쯤.",
        "M: 몇 명이 나와?",
        "W: 스물두 명. 그중 여덟 명은 노래도 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Chaeyeon. This is Seokjin."],
        ["W", "Hi. Did you need something?"],
        ["M", "I still have the camera you lent me last week."],
        ["W", "Oh, I forgot all about it."],
        ["M", "I'm passing your house now. Can I drop it off?"],
        ["W", "Sure, I'm home. Ring the bell on the first floor."],
        ["M", "I'll be there in two minutes."],
      ],
      choices: [
        "빌린 물건을 돌려주려고",
        "숙제를 물어보려고",
        "약속을 잡으려고",
        "생일을 축하하려고",
        "길을 물어보려고",
      ],
      answer: 1,
      clue: "I still have the camera you lent me last week.",
      explanation:
        "남자는 지난주에 빌린 카메라를 돌려주려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 채연아. 석진이야.",
        "W: 안녕. 무슨 일 있어?",
        "M: 지난주에 네가 빌려준 카메라가 아직 나한테 있어.",
        "W: 아, 완전히 잊고 있었어.",
        "M: 지금 너희 집 지나가는데 갖다줘도 될까?",
        "W: 그럼, 집에 있어. 1층 벨 눌러.",
        "M: 2분 뒤에 도착할게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Eunji, what time does the pottery class open?"],
        ["W", "The morning class starts at eleven o'clock."],
        ["M", "Do we have to pay before we go in?"],
        ["W", "Yes, and there is usually a line at the desk."],
        ["M", "How long does the line take?"],
        ["W", "About twenty minutes on a weekend."],
        ["M", "Then let's meet forty minutes before it starts."],
        ["W", "So twenty past ten at the front door."],
        ["M", "Yes, ten twenty. Don't be late."],
      ],
      choices: ["10:00 a.m.", "10:10 a.m.", "10:15 a.m.", "10:30 a.m.", "10:20 a.m."],
      answer: 5,
      clue: "So twenty past ten at the front door.",
      explanation:
        "11시 수업 40분 전에 만나기로 했으므로 10시 20분이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 은지야, 도예 수업 몇 시에 열어?",
        "W: 오전반은 11시에 시작해.",
        "M: 들어가기 전에 돈을 내야 해?",
        "W: 응, 접수대에 보통 줄이 있어.",
        "M: 줄이 얼마나 걸려?",
        "W: 주말에는 20분쯤.",
        "M: 그럼 시작 40분 전에 만나자.",
        "W: 그럼 10시 20분에 정문에서.",
        "M: 응, 10시 20분. 늦지 마.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, did you find your wallet in the end?"],
        ["W", "A man from the bakery called me this morning."],
        ["M", "Did he really keep it for you?"],
        ["W", "He kept it in his drawer for three whole days."],
        ["M", "Was everything still inside?"],
        ["W", "My bus card, my photos, all of it."],
        ["M", "That was very kind of him."],
        ["W", "I'm going to bring him some cookies tomorrow."],
      ],
      choices: ["sad", "angry", "thankful", "bored", "nervous"],
      answer: 3,
      clue: "I'm going to bring him some cookies tomorrow.",
      explanation:
        "지갑을 사흘 동안 보관해 준 사람에게 과자를 드리려 하므로 고마워하는 심정이다. 따라서 답은 ③이다.",
      translation: [
        "M: 다혜야, 결국 지갑 찾았어?",
        "W: 오늘 아침에 빵집 아저씨가 전화하셨어.",
        "M: 정말 보관해 주셨어?",
        "W: 사흘 내내 서랍에 넣어 두셨대.",
        "M: 안에 있던 건 다 있었어?",
        "W: 버스 카드, 사진, 전부 다.",
        "M: 정말 친절한 분이시다.",
        "W: 내일 과자 좀 사다 드리려고.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "I'd like to send this box to Busan."],
        ["M", "Please put it on the scale first."],
        ["ANN", "Number two."],
        ["W", "How much is a stamp?"],
        ["M", "It's four hundred won."],
        ["ANN", "Number three."],
        ["W", "Where is the nearest bank?"],
        ["M", "Just across the street."],
        ["ANN", "Number four."],
        ["W", "Can I pay by card?"],
        ["M", "Yes, of course."],
        ["ANN", "Number five."],
        ["W", "Is the post office open tomorrow?"],
        ["M", "No, it's a holiday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "I'd like to send this box to Busan.",
      explanation:
        "그림은 우체국에서 여자가 상자를 내밀고 직원이 저울을 가리키는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a post office, clean black line art on a plain white background, no writing anywhere. " +
          "A woman stands at the counter holding out a medium cardboard box with both hands. " +
          "A male clerk behind the counter points with one hand at a flat weighing scale on the counter top. " +
          "Shelves with plain empty boxes and a blank notice board are drawn in the background.",
      },
      translation: [
        "① W: 이 상자를 부산으로 보내고 싶어요. / M: 먼저 저울에 올려 주세요.",
        "② W: 우표 얼마예요? / M: 400원이에요.",
        "③ W: 가장 가까운 은행이 어디예요? / M: 바로 길 건너에요.",
        "④ W: 카드로 내도 돼요? / M: 네, 물론이죠.",
        "⑤ W: 내일 우체국 문 열어요? / M: 아니요, 휴일이에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taejun, are you going to the cafeteria now?"],
        ["M", "Yes, I'm heading there with Minho."],
        ["W", "I have to finish this drawing for art class."],
        ["M", "How long will that take you?"],
        ["W", "About fifteen minutes, maybe a little more."],
        ["M", "The lunchroom gets full around that time."],
        ["W", "Could you save a seat for me at your table?"],
        ["M", "No problem. I'll put my bag on the chair."],
      ],
      choices: [
        "준비물을 빌려주기",
        "자리를 맡아 주기",
        "숙제를 도와주기",
        "물건을 옮겨 주기",
        "전화를 해 주기",
      ],
      answer: 2,
      clue: "Could you save a seat for me at your table?",
      explanation:
        "여자는 급식실에서 자기 자리를 맡아 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 태준아, 지금 급식실 가?",
        "M: 응, 민호랑 가는 길이야.",
        "W: 나는 미술 시간 그림을 끝내야 해.",
        "M: 얼마나 걸려?",
        "W: 15분쯤, 어쩌면 조금 더.",
        "M: 그때쯤이면 급식실이 꽉 차.",
        "W: 너희 자리에 내 자리 좀 맡아 줄래?",
        "M: 그럴게. 의자에 내 가방 올려 둘게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 박물관 견학에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Good morning, everyone. Here are the details of our museum trip. " +
            "We will go next Wednesday, so bring your permission slip tomorrow. " +
            "Two school buses will leave the front gate at nine. " +
            "Bring your own lunch, because the museum has no cafeteria. " +
            "Stay with your group and never touch anything on display.",
        ],
      ],
      choices: [
        "가는 날",
        "이동하는 방법",
        "점심에 관한 안내",
        "내야 하는 입장료",
        "지켜야 할 주의 사항",
      ],
      answer: 4,
      clue: "We will go next Wednesday, so bring your permission slip tomorrow.",
      explanation:
        "날짜, 교통편, 점심, 주의 사항은 말했지만 입장료는 말하지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 여러분, 안녕하세요. 박물관 견학 안내를 드립니다. 다음 주 수요일에 가니 내일 동의서를 가져오세요. 학교 버스 두 대가 아홉 시에 정문에서 출발합니다. 박물관에 식당이 없으니 도시락을 가져오세요. 모둠에서 떨어지지 말고 전시물에는 절대 손대지 마세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This hangs on the wall or stands on a table. " +
            "Its surface is flat, smooth and very shiny. " +
            "When you stand in front of it, you see yourself. " +
            "People look at it before they go out in the morning. " +
            "Be careful, because it breaks into sharp pieces when it falls.",
        ],
      ],
      choices: ["침대", "의자", "거울", "창문", "시계"],
      answer: 3,
      clue: "When you stand in front of it, you see yourself.",
      explanation:
        "표면이 매끄럽고 앞에 서면 자신이 보이며 아침에 외출 전에 보는 것은 거울이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 벽에 걸거나 탁자 위에 세웁니다. 표면이 평평하고 매끄러우며 아주 반짝입니다. 그 앞에 서면 자기 모습이 보입니다. 사람들은 아침에 나가기 전에 이것을 봅니다. 떨어지면 날카로운 조각으로 깨지니 조심하세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What are you going to do this evening?"],
        ["W", "I'll read a book at home."],
        ["ANN", "Number two."],
        ["M", "Do you need any help?"],
        ["W", "No, thanks. I'm almost done."],
        ["ANN", "Number three."],
        ["M", "How was the food at the new place?"],
        ["W", "It was a bit salty."],
        ["ANN", "Number four."],
        ["M", "Why were you late this morning?"],
        ["W", "It is ten kilometers long."],
        ["ANN", "Number five."],
        ["M", "Could you close the door, please?"],
        ["W", "Sure, no problem."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why were you late this morning?",
      explanation:
        "늦은 이유를 묻는 말에 10킬로미터 길이라고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 오늘 저녁에 뭐 할 거야? / W: 집에서 책 읽을 거야.",
        "② M: 도움이 필요해? / W: 아니, 고마워. 거의 다 했어.",
        "③ M: 새로 생긴 집 음식 어땠어? / W: 조금 짰어.",
        "④ M: 오늘 아침에 왜 늦었어? / W: 10킬로미터 길이야.",
        "⑤ M: 문 좀 닫아 줄래? / W: 그럼, 알겠어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minwoo, why do you keep looking in your bag?"],
        ["M", "My gym key is gone. I had it after lunch."],
        ["W", "Did you use it in the afternoon?"],
        ["M", "I opened the locker before the fifth period."],
        ["W", "Maybe you left it in the lock."],
        ["M", "I checked, and the locker was already locked."],
        ["W", "Someone may have handed it to the lost and found."],
        ["M", "Then I'll go to the lost and found right now."],
      ],
      choices: [
        "교무실에 가기",
        "매점에 가기",
        "교실을 청소하기",
        "분실물 센터에 가기",
        "집으로 돌아가기",
      ],
      answer: 4,
      clue: "Then I'll go to the lost and found right now.",
      explanation:
        "남자는 지금 바로 분실물 센터에 가겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 민우야, 왜 계속 가방을 들여다봐?",
        "M: 체육관 열쇠가 없어졌어. 점심 먹고는 있었는데.",
        "W: 오후에 썼어?",
        "M: 5교시 전에 사물함을 열었어.",
        "W: 자물쇠에 그냥 꽂아 뒀나 봐.",
        "M: 확인했는데 사물함은 이미 잠겨 있었어.",
        "W: 누가 분실물 센터에 갖다 놨을지도 몰라.",
        "M: 그럼 지금 바로 분실물 센터에 가 볼게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 자전거 자물쇠를 고르시오.",
      lines: [
        ["W", "Hyeonu, which bike lock are you going to get?"],
        ["M", "Let's look at these five on the screen."],
        ["W", "Do you mind carrying a heavy one?"],
        ["M", "Yes, anything over five hundred grams is too heavy."],
        ["W", "Okay. What about the price?"],
        ["M", "I can spend up to twenty five thousand won."],
        ["W", "Do you want a number lock or a key lock?"],
        ["M", "A number lock. I always lose small keys."],
        ["W", "Then only one lock here matches all of that."],
        ["M", "Good. I'll order it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Yes, anything over five hundred grams is too heavy.",
      explanation:
        "500그램 이하이고, 2만 5천 원 이하이며, 번호 자물쇠인 것을 고른다. 세 조건을 모두 채우는 것은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Weight: 400 g / Price: 28,000 won / Type: Number" },
          { no: 2, label: "②", value: "Weight: 600 g / Price: 22,000 won / Type: Number" },
          { no: 3, label: "③", value: "Weight: 450 g / Price: 24,000 won / Type: Number" },
          { no: 4, label: "④", value: "Weight: 380 g / Price: 20,000 won / Type: Key" },
          { no: 5, label: "⑤", value: "Weight: 700 g / Price: 18,000 won / Type: Key" },
        ],
      },
      translation: [
        "W: 현우야, 자전거 자물쇠 어떤 걸 살 거야?",
        "M: 화면에 있는 다섯 개 보자.",
        "W: 무거운 거 들고 다녀도 괜찮아?",
        "M: 아니, 500그램 넘으면 너무 무거워.",
        "W: 알겠어. 가격은?",
        "M: 2만 5천 원까지 쓸 수 있어.",
        "W: 번호 자물쇠가 좋아, 열쇠 자물쇠가 좋아?",
        "M: 번호 자물쇠. 작은 열쇠는 늘 잃어버려.",
        "W: 그럼 여기서 다 맞는 건 하나뿐이네.",
        "M: 좋아. 오늘 밤에 주문할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진 전시회에 가기로 한 날짜를 고르시오.",
      lines: [
        ["W", "Junseo, the photo exhibition at the gallery ends this month."],
        ["M", "When exactly does the exhibition close its doors?"],
        ["W", "On the twenty-first, so we still have a few days left."],
        ["M", "How about the fourteenth, which is next Sunday?"],
        ["W", "The gallery is closed every Sunday, so that won't work."],
        ["M", "Then what about the sixteenth, on Tuesday afternoon?"],
        ["W", "I have a dance class every Tuesday evening from five."],
        ["M", "It opens in the morning too, at ten o'clock."],
        ["W", "Then let's go on the sixteenth in the morning."],
      ],
      choices: [
        "the 14th",
        "the 16th",
        "the 18th",
        "the 21st",
        "the 24th",
      ],
      answer: 2,
      clue: "Then let's go on the sixteenth in the morning.",
      explanation:
        "14일은 휴관이고 16일 저녁에는 수업이 있어서 16일 오전에 가기로 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 사진 전시회가 이번 달에 끝나.",
        "M: 정확히 언제 끝나?",
        "W: 21일에. 며칠 남았어.",
        "M: 다음 주 일요일 14일은 어때?",
        "W: 전시관은 일요일에 쉬어.",
        "M: 그럼 화요일 16일은?",
        "W: 화요일 저녁마다 무용 수업이 있어.",
        "M: 오전에도 열어. 10시부터.",
        "W: 그럼 16일 오전에 가자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyerim, your hands look a little rough today."],
        ["W", "We made winter kimchi at my house on Saturday."],
        ["M", "The whole family together?"],
        ["W", "My aunts came, and we washed cabbages all morning."],
        ["M", "How many did you make in the end?"],
        ["W", "Enough to fill four large plastic boxes."],
        ["M", "That sounds like a very long day."],
        ["W", "It was, but the dinner after that was great."],
      ],
      choices: [
        "도서관에서 공부하기",
        "병원에 다녀오기",
        "집에서 김장을 돕기",
        "여행을 다녀오기",
        "운동장에서 운동하기",
      ],
      answer: 3,
      clue: "We made winter kimchi at my house on Saturday.",
      explanation:
        "여자는 토요일에 집에서 가족들과 김장을 도왔다. 따라서 답은 ③이다.",
      translation: [
        "M: 혜림아, 오늘 손이 좀 거칠어 보여.",
        "W: 토요일에 우리 집에서 김장했어.",
        "M: 온 가족이 다 같이?",
        "W: 이모들도 오셔서 오전 내내 배추를 씻었어.",
        "M: 결국 얼마나 만들었어?",
        "W: 큰 플라스틱 통 네 개를 채울 만큼.",
        "M: 정말 긴 하루였겠다.",
        "W: 맞아. 그래도 끝나고 먹은 저녁이 최고였어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. This is an announcement from the student council. " +
            "Our used book fair starts right now in the first floor hall. " +
            "You can buy a used book for one thousand won or less. " +
            "Bring your own bag, because we do not hand out plastic bags. " +
            "The fair ends at four thirty this afternoon. " +
            "Come down and find a good book for the winter.",
        ],
      ],
      choices: [
        "행사가 시작됨을 알리려고",
        "잃어버린 물건을 알리려고",
        "안전 규칙을 안내하려고",
        "문 닫는 시간을 알리려고",
        "책을 반납하라고 알리려고",
      ],
      answer: 1,
      clue: "Our used book fair starts right now in the first floor hall.",
      explanation:
        "중고 책 장터가 지금 시작한다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학생회에서 알려 드립니다. 중고 책 장터가 지금 1층 강당에서 시작합니다. 중고 책을 천 원 이하로 살 수 있습니다. 비닐봉지를 드리지 않으니 각자 가방을 가져오세요. 장터는 오늘 오후 네 시 삼십 분에 끝납니다. 내려오셔서 겨울에 읽을 좋은 책을 찾아보세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Good afternoon. What would you like to order?"],
        ["M", "Three hot dogs, please. How much is one?"],
        ["W", "Each hot dog is five dollars today."],
        ["M", "I'd also like two bottles of water."],
        ["W", "Water is two dollars a bottle."],
        ["M", "Is there a discount for large orders?"],
        ["W", "No, sorry. We only have discounts on Mondays."],
        ["M", "That's all right. Here is my card."],
      ],
      choices: ["$15", "$16", "$17", "$18", "$19"],
      answer: 5,
      clue: "Each hot dog is five dollars today. / Water is two dollars a bottle.",
      explanation:
        "핫도그 5달러짜리 세 개는 15달러이고 물 2달러짜리 두 병은 4달러이므로 모두 19달러이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요. 무엇을 주문하시겠어요?",
        "M: 핫도그 세 개 주세요. 하나에 얼마예요?",
        "W: 오늘 핫도그는 하나에 5달러예요.",
        "M: 물도 두 병 주세요.",
        "W: 물은 한 병에 2달러예요.",
        "M: 많이 사면 할인이 있나요?",
        "W: 아니요, 죄송해요. 할인은 월요일에만 해요.",
        "M: 괜찮아요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Dongjin, you were coughing all through class."],
        ["M", "My throat has been dry since last week."],
        ["W", "Do you drink enough water during the day?"],
        ["M", "I only drink water at lunch time."],
        ["W", "That's far too little for a whole school day."],
        ["M", "I forget about it when I'm busy."],
        ["W", "Keep a bottle on your desk where you can see it."],
        ["M", "My bottle leaks, so I stopped bringing it."],
        ["W", "The shop by the gate sells bottles for five thousand won."],
      ],
      choices: [
        "I drink water all day.",
        "Then I'll buy one tomorrow.",
        "My throat feels fine now.",
        "I never go near the gate.",
        "The shop sells only snacks.",
      ],
      answer: 2,
      clue: "The shop by the gate sells bottles for five thousand won.",
      explanation:
        "정문 옆 가게에서 물병을 판다고 했으므로, 내일 하나 사겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 동진아, 수업 내내 기침하더라.",
        "M: 지난주부터 목이 계속 말라.",
        "W: 낮에 물은 충분히 마셔?",
        "M: 점심때만 마셔.",
        "W: 하루 종일 학교에 있는데 그건 너무 적어.",
        "M: 바쁘면 잊어버려.",
        "W: 눈에 보이게 책상에 물병을 둬.",
        "M: 내 물병이 새서 안 가져와.",
        "W: 정문 옆 가게에서 오천 원에 물병 팔아.",
        "M: 그럼 내일 하나 살게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Seoyeong, are you free during lunch tomorrow?"],
        ["W", "I think so. Why do you ask?"],
        ["M", "Our class is painting the back wall of the school."],
        ["W", "Is that the wall near the bicycle rack?"],
        ["M", "Yes, it has been gray and dirty for years."],
        ["W", "What are you going to paint on it?"],
        ["M", "A big tree, and each student paints one leaf."],
        ["W", "That sounds wonderful. Do you need more hands?"],
        ["M", "We do. Can you come at twelve thirty?"],
      ],
      choices: [
        "The wall is already painted.",
        "I can't paint anything at all.",
        "I don't like trees on walls.",
        "Sure, I'll be there on time.",
        "Lunch ends at eleven thirty.",
      ],
      answer: 4,
      clue: "We do. Can you come at twelve thirty?",
      explanation:
        "남자가 12시 30분에 올 수 있는지 물었으므로, 시간 맞춰 가겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 서영아, 내일 점심시간에 시간 돼?",
        "W: 될 것 같아. 왜?",
        "M: 우리 반이 학교 뒷벽에 그림을 그려.",
        "W: 자전거 보관대 옆 그 벽?",
        "M: 응, 몇 년째 잿빛이고 지저분해.",
        "W: 거기에 뭘 그릴 건데?",
        "M: 큰 나무 하나. 학생마다 잎 하나씩 그려.",
        "W: 멋지다. 손이 더 필요해?",
        "M: 필요해. 12시 30분에 올 수 있어?",
        "W: 그럼, 시간 맞춰 갈게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jinseok, did you decide on your free topic report?"],
        ["M", "Not yet. Nothing feels interesting enough."],
        ["W", "What do you do when you have free time?"],
        ["M", "I fold paper airplanes and test how far they fly."],
        ["W", "That could be a great report topic."],
        ["M", "Would the teacher accept something like that?"],
        ["W", "She said any topic works if you show real results."],
        ["M", "I have written down the distances for two months."],
        ["W", "Then you already have all the data you need."],
      ],
      choices: [
        "I have no data at all.",
        "I'll throw the papers away.",
        "The teacher chose my topic.",
        "I never fold paper airplanes.",
        "You're right. I'll write about that.",
      ],
      answer: 5,
      clue: "Then you already have all the data you need.",
      explanation:
        "이미 필요한 자료가 다 있다고 했으므로, 그것으로 쓰겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 진석아, 자유 주제 보고서 정했어?",
        "M: 아직. 흥미로운 게 없어.",
        "W: 시간 날 때 뭐 해?",
        "M: 종이비행기 접어서 얼마나 멀리 나는지 재 봐.",
        "W: 그거 좋은 보고서 주제가 되겠다.",
        "M: 선생님이 그런 걸 받아 주실까?",
        "W: 결과만 제대로 보여 주면 어떤 주제든 된다고 하셨어.",
        "M: 두 달 동안 거리를 다 적어 뒀어.",
        "W: 그럼 필요한 자료는 이미 다 있는 거네.",
        "M: 네 말이 맞아. 그걸로 쓸게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nayoung이 Hoyeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Nayoung : ________________",
      lines: [
        [
          "W",
          "Nayoung and Hoyeon are practicing for the class relay race. " +
            "Hoyeon runs very fast but his shoelaces have come undone. " +
            "Nayoung sees the long laces dragging on the track behind him. " +
            "The next round starts in less than a minute. " +
            "She wants to warn him before he starts running again. " +
            "In this situation, what would Nayoung most likely say to Hoyeon?",
        ],
      ],
      choices: [
        "You should run a little faster.",
        "Let's stop practicing today.",
        "Can I borrow your running shoes?",
        "The race was canceled this morning.",
        "Tie your shoelaces before you run.",
      ],
      answer: 5,
      clue: "She wants to warn him before he starts running again.",
      explanation:
        "신발 끈이 풀린 채 다시 달리려 하므로, 끈을 묶으라고 말하는 ⑤가 가장 적절하다.",
      translation: [
        "W: 나영이와 호연이는 반 계주 연습을 하고 있습니다. 호연이는 아주 빨리 달리지만 신발 끈이 풀렸습니다. 나영이는 긴 끈이 트랙 위로 끌리는 것을 봅니다. 다음 차례는 1분도 안 남았습니다. 나영이는 호연이가 다시 달리기 전에 알려 주고 싶습니다. 이런 상황에서 나영이가 호연이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
