/** 중1 듣기 44회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 44회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 책가방을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a school bag?"],
        ["W", "Yes, my old one tore last week."],
        ["M", "Do you want two straps or one?"],
        ["W", "Two straps. One strap hurts my shoulder."],
        ["M", "This one has a big pocket on the front."],
        ["W", "A front pocket is good for my bus card."],
        ["M", "Would you like wheels on the bottom?"],
        ["W", "No wheels. I climb stairs every day."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Two straps. One strap hurts my shoulder. / A front pocket is good for my bus card.",
      explanation:
        "여자는 어깨끈이 둘이고 앞주머니가 있으며 바퀴가 없는 가방을 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five school bags side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a backpack with TWO SHOULDER STRAPS and a completely plain front, no pocket. " +
          "② a backpack with TWO SHOULDER STRAPS and one large POCKET on the front, standing flat with no wheels. " +
          "③ a bag with ONE SINGLE STRAP across the body and a front POCKET. " +
          "④ a backpack with TWO STRAPS, a front POCKET and two small WHEELS at the bottom. " +
          "⑤ a bag with ONE SINGLE STRAP and two small WHEELS at the bottom.",
      },
      translation: [
        "M: 안녕하세요. 책가방 찾으세요?",
        "W: 네, 지난주에 예전 것이 찢어졌어요.",
        "M: 어깨끈이 두 개인 게 좋으세요, 하나인 게 좋으세요?",
        "W: 두 개요. 하나는 어깨가 아파요.",
        "M: 이건 앞에 큰 주머니가 있어요.",
        "W: 앞주머니는 버스 카드 넣기 좋아요.",
        "M: 바닥에 바퀴 달린 건 어떠세요?",
        "W: 바퀴는 없는 걸로요. 매일 계단을 올라가요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 운동회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Dohyun, when is the school sports day?"],
        ["M", "Next Thursday, if the weather is fine."],
        ["W", "Where do we gather in the morning?"],
        ["M", "On the playground, by our class flag."],
        ["W", "What time does it start?"],
        ["M", "Nine o'clock, right after the morning bell."],
        ["W", "Do we need to wear anything special?"],
        ["M", "Gym clothes and a class color headband."],
        ["W", "I'll get my headband ready tonight."],
      ],
      choices: [
        "운동회를 하는 날",
        "모이는 곳",
        "시작하는 시각",
        "입어야 할 옷",
        "하는 경기 종목",
      ],
      answer: 5,
      clue: "Next Thursday, if the weather is fine.",
      explanation:
        "날짜, 장소, 시각, 복장은 말했지만 경기 종목은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 학교 운동회 언제야?",
        "M: 날씨가 좋으면 다음 주 목요일에.",
        "W: 아침에 어디로 모여?",
        "M: 운동장에서, 우리 반 깃발 옆에.",
        "W: 몇 시에 시작해?",
        "M: 아홉 시. 조회 종 치고 바로.",
        "W: 특별히 입어야 할 게 있어?",
        "M: 체육복이랑 반 색깔 머리띠.",
        "W: 오늘 밤에 머리띠 챙겨 놔야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Chaeyeon. It's Sangho. Are you free?"],
        ["W", "Yes, I'm just reading. What is it?"],
        ["M", "Our class is cleaning the park on Saturday."],
        ["W", "The one behind the library?"],
        ["M", "That one. We start at nine in the morning."],
        ["W", "How many people are going?"],
        ["M", "Seven so far, but we need ten."],
        ["W", "So you need three more."],
        ["M", "Would you come and help us on Saturday?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "봉사에 함께 가자고 하려고",
        "물건을 빌리려고",
        "길을 물어보려고",
      ],
      answer: 3,
      clue: "Would you come and help us on Saturday?",
      explanation:
        "남자는 토요일 공원 청소에 함께 가자고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 채연아. 상호야. 시간 돼?",
        "W: 응, 책 읽는 중이야. 무슨 일이야?",
        "M: 우리 반이 토요일에 공원을 청소해.",
        "W: 도서관 뒤에 있는 그 공원?",
        "M: 거기. 아침 아홉 시에 시작해.",
        "W: 몇 명이나 가?",
        "M: 지금까지 일곱 명. 열 명이 필요해.",
        "W: 그럼 세 명이 더 있어야겠네.",
        "M: 토요일에 와서 도와줄래?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yerin, when does the science club start?"],
        ["W", "The teacher opens the lab at four thirty."],
        ["M", "Do we set up the tables first?"],
        ["W", "Yes, and that takes about fifteen minutes."],
        ["M", "Then we should be there by four fifteen."],
        ["W", "My art class ends at four o'clock."],
        ["M", "So four fifteen works for you."],
        ["W", "Let's meet at four fifteen at the lab door."],
        ["M", "Four fifteen. I'll bring the note sheets."],
      ],
      choices: ["4:00 p.m.", "4:30 p.m.", "4:45 p.m.", "3:45 p.m.", "4:15 p.m."],
      answer: 5,
      clue: "Let's meet at four fifteen at the lab door.",
      explanation:
        "탁자 놓는 시간을 생각해 4시 15분에 만나기로 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예린아, 과학 동아리 몇 시에 시작해?",
        "W: 선생님이 4시 30분에 실험실을 열어 주셔.",
        "M: 먼저 탁자를 놓아야 해?",
        "W: 응, 그게 15분쯤 걸려.",
        "M: 그럼 4시 15분까지 가 있어야겠다.",
        "W: 내 미술 수업이 네 시에 끝나.",
        "M: 그럼 4시 15분이 괜찮겠네.",
        "W: 4시 15분에 실험실 문 앞에서 만나자.",
        "M: 4시 15분. 기록지는 내가 가져올게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, you've been quiet since lunch."],
        ["W", "I broke my sister's glasses this morning."],
        ["M", "Did you sit on them by mistake?"],
        ["W", "They were on the chair and I didn't see them."],
        ["M", "Did she say anything to you?"],
        ["W", "She said it was fine, which made it worse."],
        ["M", "She needs them for school, doesn't she?"],
        ["W", "Every single day, and I can't fix them."],
      ],
      choices: ["sorry", "happy", "bored", "proud", "excited"],
      answer: 1,
      clue: "She said it was fine, which made it worse.",
      explanation:
        "언니의 안경을 망가뜨려 미안해하고 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 나리야, 점심때부터 계속 조용하네.",
        "W: 오늘 아침에 언니 안경을 망가뜨렸어.",
        "M: 실수로 깔고 앉았어?",
        "W: 의자에 있었는데 못 봤어.",
        "M: 언니가 뭐라고 했어?",
        "W: 괜찮다고 했는데 그래서 더 미안해.",
        "M: 학교에서 꼭 써야 하잖아.",
        "W: 매일. 내가 고칠 수도 없어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "May I take your order?"],
        ["M", "One bowl of noodles, please."],
        ["ANN", "Number two."],
        ["W", "Is this table free?"],
        ["M", "Yes, please sit down."],
        ["ANN", "Number three."],
        ["W", "Could I have some more water?"],
        ["M", "Of course, right away."],
        ["ANN", "Number four."],
        ["W", "I dropped my spoon."],
        ["M", "I'll bring you a clean one."],
        ["ANN", "Number five."],
        ["W", "How much is the soup?"],
        ["M", "Six thousand won."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I dropped my spoon.",
      explanation:
        "그림은 식당에서 여자가 바닥에 떨어진 숟가락을 가리키고 종업원이 새것을 가져오려는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small restaurant, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman seated at a table points down at a spoon lying on the floor beside her chair, looking apologetic. " +
          "A server standing beside the table nods and turns toward a counter holding clean spoons. " +
          "Bowls on the table and other tables are drawn simply in the background.",
      },
      translation: [
        "① W: 주문하시겠어요? / M: 국수 한 그릇 주세요.",
        "② W: 이 자리 비었나요? / M: 네, 앉으세요.",
        "③ W: 물 좀 더 주시겠어요? / M: 그럼요, 바로 드릴게요.",
        "④ W: 숟가락을 떨어뜨렸어요. / M: 깨끗한 걸로 가져다드릴게요.",
        "⑤ W: 국은 얼마예요? / M: 6천 원입니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kiyoung, are you going to the stationery shop today?"],
        ["M", "After school, to buy a new pen."],
        ["W", "Our group is making a poster tomorrow."],
        ["M", "Do you need paper for it?"],
        ["W", "We have the paper, but the glue is dry."],
        ["M", "How many do you need?"],
        ["W", "Two glue sticks would be enough."],
        ["M", "That's easy. I pass the shop anyway."],
        ["W", "Could you buy two glue sticks for us?"],
        ["M", "Sure, I'll bring them tomorrow morning."],
      ],
      choices: [
        "풀을 사다 주기",
        "종이를 가져다주기",
        "포스터를 그려 주기",
        "펜을 빌려주기",
        "모둠에 들어오기",
      ],
      answer: 1,
      clue: "Could you buy two glue sticks for us?",
      explanation:
        "여자는 딱풀 두 개를 사다 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 기영아, 오늘 문구점 가?",
        "M: 방과 후에. 새 펜 사러.",
        "W: 우리 모둠이 내일 포스터를 만들어.",
        "M: 종이가 필요해?",
        "W: 종이는 있는데 풀이 말랐어.",
        "M: 몇 개 필요해?",
        "W: 딱풀 두 개면 충분해.",
        "M: 어렵지 않아. 어차피 가게를 지나가.",
        "W: 딱풀 두 개만 사다 줄래?",
        "M: 그래, 내일 아침에 가져올게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 사진 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The school photo contest starts this week. " +
            "The theme this year is our school in autumn. " +
            "You may send up to two photographs each. " +
            "Send the files to the art room email by the twentieth. " +
            "Winning photos go up in the first floor hallway. " +
            "Ask your homeroom teacher if you have a question.",
        ],
      ],
      choices: [
        "대회의 주제",
        "낼 수 있는 작품 수",
        "작품을 내는 방법",
        "뽑힌 작품을 거는 곳",
        "심사하는 사람",
      ],
      answer: 5,
      clue: "The theme this year is our school in autumn.",
      explanation:
        "주제, 작품 수, 제출 방법, 전시 장소는 말했지만 심사하는 사람은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 이번 주에 학교 사진 대회를 시작합니다. 올해 주제는 가을의 우리 학교입니다. 한 사람이 두 점까지 낼 수 있습니다. 20일까지 미술실 전자우편으로 파일을 보내 주세요. 뽑힌 사진은 1층 복도에 겁니다. 궁금한 것은 담임 선생님께 여쭤보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You use this to find your way in a new place. " +
            "It is flat and shows roads, rivers and buildings from above. " +
            "North is usually at the top of it. " +
            "You fold it and put it in your pocket when you finish. " +
            "Many people now look at one on their phone instead.",
        ],
      ],
      choices: ["달력", "사전", "신문", "지도", "편지"],
      answer: 4,
      clue: "It is flat and shows roads, rivers and buildings from above.",
      explanation:
        "길과 강, 건물을 위에서 본 대로 그려 길을 찾는 데 쓰는 것은 지도이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이것은 낯선 곳에서 길을 찾을 때 씁니다. 납작하고 길과 강, 건물을 위에서 본 대로 보여 줍니다. 보통 위쪽이 북쪽입니다. 다 보고 나면 접어서 주머니에 넣습니다. 요즘은 휴대폰으로 보는 사람이 많습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How do you come to school?"],
        ["W", "By bus, every morning."],
        ["ANN", "Number two."],
        ["M", "What's your favorite season?"],
        ["W", "Spring, because of the flowers."],
        ["ANN", "Number three."],
        ["M", "Could you close the door?"],
        ["W", "Sure, no problem."],
        ["ANN", "Number four."],
        ["M", "When is your birthday?"],
        ["W", "I have two brothers."],
        ["ANN", "Number five."],
        ["M", "Did you finish the book?"],
        ["W", "Almost, ten pages left."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "When is your birthday?",
      explanation:
        "생일을 묻는 말에 형제 수를 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 학교에 어떻게 와? / W: 아침마다 버스로.",
        "② M: 어느 계절을 제일 좋아해? / W: 봄. 꽃 때문에.",
        "③ M: 문 좀 닫아 줄래? / W: 그럼, 문제없어.",
        "④ M: 생일이 언제야? / W: 나는 남동생이 둘 있어.",
        "⑤ M: 그 책 다 읽었어? / W: 거의. 열 쪽 남았어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyun, did you hand in the trip form yet?"],
        ["W", "My mother signed it at breakfast this morning."],
        ["M", "So you have it with you right now?"],
        ["W", "It's inside my math textbook, I think."],
        ["M", "The teacher is collecting them in the staff room."],
        ["W", "I thought she was collecting them tomorrow."],
        ["M", "She changed it because of the bus booking."],
        ["W", "Until when does she collect them today?"],
        ["M", "Until the end of this break."],
        ["W", "I'll take the form to her now."],
      ],
      choices: [
        "어머니께 전화하기",
        "선생님께 동의서를 내기",
        "교과서를 빌리기",
        "가방을 싸기",
        "교실을 청소하기",
      ],
      answer: 2,
      clue: "I'll take the form to her now.",
      explanation:
        "여자는 지금 선생님께 동의서를 내러 가겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 서윤아, 여행 동의서 벌써 냈어?",
        "W: 오늘 아침 먹을 때 엄마가 서명해 주셨어.",
        "M: 그럼 지금 가지고 있어?",
        "W: 수학 교과서 안에 있을 거야.",
        "M: 선생님이 교무실에서 걷고 계셔.",
        "W: 내일 걷으시는 줄 알았는데.",
        "M: 버스 예약 때문에 바꾸셨어.",
        "W: 오늘 언제까지 걷으셔?",
        "M: 이번 쉬는 시간 끝날 때까지.",
        "W: 지금 갖다 드릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 신청할 방과 후 수업을 고르시오.",
      lines: [
        ["W", "Junseo, which after-school class are you taking?"],
        ["M", "There are five of them on the notice board."],
        ["W", "I've been waiting for this list since March."],
        ["M", "Then let's decide today. Which days can you come?"],
        ["W", "Only Tuesday and Thursday, because of my piano."],
        ["M", "Two of them are on Monday, so those are out."],
        ["W", "And I want a small class, under fifteen students."],
        ["M", "One of the rest has twenty students in it."],
        ["W", "The fee should also be under thirty thousand won."],
        ["M", "Then only one class is left for you."],
        ["W", "I'll sign up tomorrow morning before class."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Only Tuesday and Thursday.",
      explanation:
        "화·목요일이고, 정원 15명 미만이며, 3만 원 미만인 수업을 고른다. 세 조건을 모두 채우는 것은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Monday / Students: 12 / Fee: 25,000 won" },
          { no: 2, label: "②", value: "Day: Monday / Students: 10 / Fee: 20,000 won" },
          { no: 3, label: "③", value: "Day: Tuesday / Students: 12 / Fee: 28,000 won" },
          { no: 4, label: "④", value: "Day: Thursday / Students: 20 / Fee: 22,000 won" },
          { no: 5, label: "⑤", value: "Day: Thursday / Students: 14 / Fee: 35,000 won" },
        ],
      },
      translation: [
        "W: 준서야, 어떤 방과 후 수업 들을 거야?",
        "M: 게시판에 다섯 개 있어.",
        "W: 3월부터 이 목록 기다렸어.",
        "M: 그럼 오늘 정하자. 무슨 요일에 올 수 있어?",
        "W: 피아노 때문에 화요일이랑 목요일만.",
        "M: 두 개는 월요일이라 빠지네.",
        "W: 그리고 열다섯 명 아래인 작은 반이 좋아.",
        "M: 나머지 중 하나는 스무 명이야.",
        "W: 수강료도 3만 원 아래여야 해.",
        "M: 그럼 너한테 남는 건 하나뿐이네.",
        "W: 내일 아침 수업 전에 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 공연을 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Hayoon, the school band plays three times this month."],
        ["W", "Which days did they announce?"],
        ["M", "The seventh, the fourteenth and the twenty-first."],
        ["W", "The seventh is our class photo day."],
        ["M", "We'd be in uniform until late that day."],
        ["W", "And the fourteenth is the day before the math test."],
        ["M", "You wouldn't enjoy the music that night."],
        ["W", "Not at all. So the twenty-first is best."],
        ["M", "It's a Saturday, so we have the whole evening."],
        ["W", "I'll book two seats for the twenty-first."],
      ],
      choices: ["the 7th", "the 14th", "the 21st", "the 28th", "the 3rd"],
      answer: 3,
      clue: "Not at all. So the twenty-first is best.",
      explanation:
        "7일은 사진 촬영, 14일은 시험 전날이어서 21일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 하윤아, 학교 밴드가 이번 달에 세 번 공연해.",
        "W: 어떤 날이라고 했어?",
        "M: 7일, 14일, 21일.",
        "W: 7일은 우리 반 사진 찍는 날이야.",
        "M: 그날은 늦게까지 교복을 입고 있어야 해.",
        "W: 그리고 14일은 수학 시험 전날이야.",
        "M: 그날 밤엔 음악이 귀에 안 들어오겠다.",
        "W: 전혀. 그럼 21일이 제일 좋아.",
        "M: 토요일이라 저녁이 통째로 비어.",
        "W: 21일로 두 자리 예약할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minho, did you rest well over the weekend?"],
        ["M", "I painted the fence with my father."],
        ["W", "The one in front of your house?"],
        ["M", "Yes, it had been gray for years."],
        ["W", "What color did you paint it?"],
        ["M", "Dark green, because my mother chose it."],
        ["W", "How long did the whole thing take?"],
        ["M", "Two days, and my arms still hurt."],
        ["W", "Did it turn out well?"],
        ["M", "The neighbors said it looks like a new house."],
      ],
      choices: [
        "친구와 놀러 가기",
        "도서관에서 공부하기",
        "아버지와 울타리를 칠하기",
        "집에서 쉬기",
        "병원에 가기",
      ],
      answer: 3,
      clue: "I painted the fence with my father.",
      explanation:
        "남자는 주말에 아버지와 울타리를 칠했다. 따라서 답은 ③이다.",
      translation: [
        "W: 민호야, 주말에 잘 쉬었어?",
        "M: 아버지랑 울타리를 칠했어.",
        "W: 너희 집 앞에 있는 그거?",
        "M: 응, 몇 년 동안 회색이었어.",
        "W: 무슨 색으로 칠했어?",
        "M: 짙은 초록. 엄마가 고르셨어.",
        "W: 전부 얼마나 걸렸어?",
        "M: 이틀. 아직도 팔이 아파.",
        "W: 잘 나왔어?",
        "M: 이웃들이 새집 같다고 하셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school health room. " +
            "Many students have caught colds this week. " +
            "More than thirty of you came here in three days. " +
            "Please wash your hands before you eat lunch. " +
            "Open the classroom windows for five minutes every hour. " +
            "If you have a fever, come to the health room at once. " +
            "Take good care of yourselves, everyone.",
        ],
      ],
      choices: [
        "건강 관리를 당부하려고",
        "행사를 알리려고",
        "분실물을 찾으려고",
        "청소를 부탁하려고",
        "시험을 안내하려고",
      ],
      answer: 1,
      clue: "Please wash your hands before you eat lunch.",
      explanation:
        "감기가 도니 손 씻기와 환기를 하라고 당부하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 보건실입니다. 이번 주에 감기에 걸린 학생이 많습니다. 사흘 동안 서른 명 넘게 다녀갔습니다. 점심 먹기 전에 손을 씻어 주세요. 한 시간마다 5분씩 교실 창문을 열어 주세요. 열이 나면 바로 보건실로 오세요. 모두 건강 잘 챙기세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome. Are you buying tickets for the museum?"],
        ["W", "Yes, three student tickets, please."],
        ["M", "A student ticket is five dollars each."],
        ["W", "Do we need to pay for the map?"],
        ["M", "The map is free at the entrance."],
        ["W", "What about the audio guide?"],
        ["M", "That's three dollars for each person."],
        ["W", "We'll take one audio guide for the three of us."],
        ["M", "That's fine. Anything else today?"],
        ["W", "No, that's all. Here is my card."],
      ],
      choices: ["$15", "$21", "$24", "$18", "$20"],
      answer: 4,
      clue: "A student ticket is five dollars each.",
      explanation:
        "학생 표 세 장 15달러에 음성 안내기 하나 3달러를 더하면 18달러이다. 따라서 답은 ④이다.",
      translation: [
        "M: 어서 오세요. 박물관 표 사시나요?",
        "W: 네, 학생 표 세 장 주세요.",
        "M: 학생 표는 한 장에 5달러입니다.",
        "W: 안내도는 돈을 내야 하나요?",
        "M: 안내도는 입구에서 무료로 드립니다.",
        "W: 음성 안내기는요?",
        "M: 한 사람당 3달러입니다.",
        "W: 셋이서 하나만 빌릴게요.",
        "M: 괜찮습니다. 더 필요한 건 없으세요?",
        "W: 그게 다예요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taeho, you never forget your gym clothes."],
        ["M", "I keep them in my locker all week."],
        ["W", "Don't they get dirty by Friday?"],
        ["M", "I take them home every Friday and wash them."],
        ["W", "I carry mine back and forth every day."],
        ["M", "And that's when you forget them."],
        ["W", "Twice this month, and I had to borrow."],
        ["M", "One trip a week beats five chances to forget."],
        ["W", "Could you show me where the lockers are?"],
      ],
      choices: [
        "I don't use a locker.",
        "You should carry them daily.",
        "Gym clothes are not needed.",
        "I forgot mine today.",
        "Sure, they're by the gym door.",
      ],
      answer: 5,
      clue: "Could you show me where the lockers are?",
      explanation:
        "사물함이 어디 있는지 보여 달라고 했으므로, 체육관 문 옆이라고 알려 주는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 태호야, 너는 체육복을 한 번도 안 잊더라.",
        "M: 한 주 내내 사물함에 넣어 둬.",
        "W: 금요일쯤 되면 더러워지지 않아?",
        "M: 금요일마다 집에 가져가서 빨아.",
        "W: 나는 매일 들고 왔다 갔다 해.",
        "M: 그러다 잊어버리는 거야.",
        "W: 이번 달에 두 번. 빌려 입었어.",
        "M: 일주일에 한 번이 잊을 기회 다섯 번보다 나아.",
        "W: 사물함이 어디 있는지 보여 줄래?",
        "M: 그럼, 체육관 문 옆에 있어.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, are you still helping at the community center?"],
        ["W", "Every Saturday morning, for two hours."],
        ["M", "What do you do there?"],
        ["W", "I read picture books to little children."],
        ["M", "Is it hard to keep them sitting still?"],
        ["W", "At first it was. Now I change my voice."],
        ["M", "Change your voice for each character?"],
        ["W", "Yes, and they listen to the very end."],
        ["M", "Could I come and watch one Saturday?"],
      ],
      choices: [
        "Sure, come this Saturday.",
        "I stopped going in May.",
        "The center is closed now.",
        "Children don't like books.",
        "I read only at home.",
      ],
      answer: 1,
      clue: "Could I come and watch one Saturday?",
      explanation:
        "남자가 토요일에 보러 가도 되는지 물었으므로, 이번 토요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 다인아, 아직 주민 센터에서 도와?",
        "W: 토요일 아침마다 두 시간씩.",
        "M: 거기서 뭘 해?",
        "W: 어린아이들에게 그림책을 읽어 줘.",
        "M: 가만히 앉혀 두기 힘들지 않아?",
        "W: 처음엔 그랬어. 지금은 목소리를 바꿔.",
        "M: 등장인물마다 목소리를 바꿔?",
        "W: 응, 그러면 끝까지 들어.",
        "M: 나도 토요일에 한 번 보러 가도 돼?",
        "W: 그럼, 이번 토요일에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sangwoo, how is your English reading going?"],
        ["M", "Slowly. I look up almost every word."],
        ["W", "Do you stop at each new word?"],
        ["M", "Yes, or I feel like I'm missing something."],
        ["W", "Then you never reach the end of the page."],
        ["M", "That's true. I usually stop halfway."],
        ["W", "Read one whole page without stopping first."],
        ["M", "Even if some parts don't make sense?"],
        ["W", "Yes, then look up only the words that matter."],
      ],
      choices: [
        "I already read that way.",
        "All right, I'll try it tonight.",
        "I understand every word.",
        "You should look up more words.",
        "I don't read in English.",
      ],
      answer: 2,
      clue: "Yes, then look up only the words that matter.",
      explanation:
        "한 쪽을 끝까지 읽고 중요한 낱말만 찾으라는 제안이므로, 오늘 밤 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 상우야, 영어 읽기는 어때?",
        "M: 더뎌. 거의 모든 단어를 찾아봐.",
        "W: 새 단어마다 멈춰?",
        "M: 응, 안 그러면 뭔가 놓치는 것 같아.",
        "W: 그러면 한 쪽 끝까지 못 가잖아.",
        "M: 맞아. 보통 절반에서 멈춰.",
        "W: 먼저 한 쪽을 멈추지 말고 끝까지 읽어 봐.",
        "M: 이해 안 되는 부분이 있어도?",
        "W: 응, 그다음에 중요한 단어만 찾아봐.",
        "M: 알겠어, 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Areum이 Junho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Areum : ________________",
      lines: [
        [
          "W",
          "Areum and Junho are getting ready for the class presentation. " +
            "Junho carries the laptop to the front desk and opens it. " +
            "Areum notices that the power cable is still plugged into the wall. " +
            "If he walks any further, the laptop will be pulled from his hands. " +
            "She wants to warn him before he takes another step. " +
            "In this situation, what would Areum most likely say to Junho?",
        ],
      ],
      choices: [
        "The presentation starts at two.",
        "Stop, the cable is still plugged in.",
        "Let's use my laptop instead.",
        "Can you turn off the lights?",
        "We need one more desk here.",
      ],
      answer: 2,
      clue: "She wants to warn him before he takes another step.",
      explanation:
        "전원선이 꽂힌 채여서 노트북이 끌려갈 수 있으므로 말리는 ②가 가장 적절하다.",
      translation: [
        "W: 아름이와 준호는 학급 발표를 준비하고 있습니다. 준호가 노트북을 앞 책상으로 옮겨 펼칩니다. 아름이는 전원선이 아직 벽에 꽂혀 있는 것을 봅니다. 한 걸음 더 가면 노트북이 손에서 끌려 나갈 것입니다. 아름이는 준호가 더 움직이기 전에 말리고 싶습니다. 이런 상황에서 아름이가 준호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
