/** 중1 듣기 23회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 23회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 머그컵을 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a mug for yourself?"],
        ["W", "Yes. I need one for my desk at home."],
        ["M", "We have mugs with handles and mugs without handles."],
        ["W", "I'd like one with a handle. It's easier to hold."],
        ["M", "All right. This one has small hearts on it."],
        ["W", "Hearts are pretty, but I want something simpler."],
        ["M", "Then how about this one with dots?"],
        ["W", "That looks nice. I'll take the mug with dots."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I'd like one with a handle. / I'll take the mug with dots.",
      explanation: "여자는 손잡이가 있는 머그컵을 원하고, 하트 무늬 대신 점무늬를 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five coffee mugs drawn side by side as five choices, clean black line art on white. " +
          "① a mug with NO handle, covered in HEARTS. " +
          "② a mug with NO handle, covered in DOTS. " +
          "③ a mug WITH a handle, covered in DOTS. " +
          "④ a mug WITH a handle, covered in HEARTS. " +
          "⑤ a mug WITH a handle and NO pattern at all.",
      },
      translation: [
        "M: 어서 오세요. 머그컵을 찾으세요?",
        "W: 네. 집 책상에 둘 걸 하나 사려고요.",
        "M: 손잡이가 있는 것도 있고 없는 것도 있어요.",
        "W: 손잡이가 있는 걸로 할게요. 잡기가 더 편해서요.",
        "M: 알겠습니다. 이건 작은 하트 무늬가 있어요.",
        "W: 하트도 예쁘지만 좀 더 단순한 게 좋아요.",
        "M: 그럼 이 점무늬는 어떠세요?",
        "W: 그게 좋네요. 점무늬 머그컵으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 독서 축제에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minjun, did you see the poster for the reading festival?"],
        ["M", "Yes. It's in the school library next Thursday."],
        ["W", "What time does it start? I have soccer practice that day."],
        ["M", "It starts at four and ends at six."],
        ["W", "Good. Who can join it? Only second graders?"],
        ["M", "Anyone in our school can join. Even teachers come."],
        ["W", "Nice. Do we need to bring anything?"],
        ["M", "Yes, bring one book you love and a pen."],
        ["W", "Okay. I'll bring my favorite comic book then."],
      ],
      choices: ["열리는 장소", "시작 시각", "참가할 수 있는 사람", "참가비", "가져갈 물건"],
      answer: 4,
      clue: "참가비는 대화에서 언급되지 않았다.",
      explanation:
        "장소(학교 도서관), 시작 시각(4시), 참가 대상(우리 학교 누구나), 가져갈 물건(책과 펜)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 민준아, 독서 축제 포스터 봤어?",
        "M: 응. 다음 주 목요일에 학교 도서관에서 해.",
        "W: 몇 시에 시작해? 그날 축구 연습이 있어서.",
        "M: 4시에 시작해서 6시에 끝나.",
        "W: 잘됐다. 누가 참가할 수 있어? 2학년만?",
        "M: 우리 학교 누구나 참가할 수 있어. 선생님들도 오셔.",
        "W: 좋네. 뭘 가져가야 해?",
        "M: 응, 네가 좋아하는 책 한 권이랑 펜을 가져와.",
        "W: 알겠어. 그럼 내가 제일 좋아하는 만화책을 가져갈게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hi, Junho. This is Sora from the science club."],
        ["M", "Hi, Sora. Is something wrong?"],
        ["W", "No, but our meeting place has changed for tomorrow."],
        ["M", "Really? I thought we were meeting in Room 201."],
        ["W", "The floor there is being painted this week."],
        ["M", "Then where should we go instead?"],
        ["W", "Come to the science lab on the third floor."],
        ["M", "Got it. I'll tell the other members, too."],
      ],
      choices: [
        "모임 시간을 늦추려고",
        "모임 장소가 바뀐 것을 알리려고",
        "실험 준비물을 부탁하려고",
        "동아리 가입을 권하려고",
        "숙제를 대신 내 달라고 하려고",
      ],
      answer: 2,
      clue: "But our meeting place has changed for tomorrow.",
      explanation:
        "여자는 교실 바닥 도색 때문에 내일 모임 장소가 3층 과학실로 바뀌었다고 알려 주려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕, 준호야. 나 과학 동아리 소라야.",
        "M: 안녕, 소라야. 무슨 일 있어?",
        "W: 아니, 그런데 내일 모임 장소가 바뀌었어.",
        "M: 정말? 201호에서 모이는 줄 알았는데.",
        "W: 거기 바닥을 이번 주에 칠하고 있어.",
        "M: 그럼 어디로 가야 해?",
        "W: 3층 과학실로 와.",
        "M: 알겠어. 다른 부원들한테도 알릴게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Dahye, are you free this Saturday afternoon?"],
        ["W", "Yes. Do you want to go to the science museum?"],
        ["M", "I do. The robot show starts at three o'clock."],
        ["W", "Then let's meet in front of the ticket office."],
        ["M", "Sure. Should we meet at three, right before the show?"],
        ["W", "That's too late. The line is always long there."],
        ["M", "You're right. How about thirty minutes earlier?"],
        ["W", "Perfect. Let's meet then and buy our tickets first."],
        ["M", "Okay. See you at the ticket office on Saturday."],
      ],
      choices: ["2:00 p.m.", "3:00 p.m.", "3:30 p.m.", "4:00 p.m.", "2:30 p.m."],
      answer: 5,
      clue: "How about thirty minutes earlier?",
      explanation:
        "로봇 쇼가 3시에 시작하는데 줄이 길어 30분 일찍 만나기로 했으므로 만나는 시각은 2시 30분이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다혜야, 이번 토요일 오후에 시간 있어?",
        "W: 응. 과학관에 가고 싶어?",
        "M: 응. 로봇 쇼가 3시에 시작해.",
        "W: 그럼 매표소 앞에서 만나자.",
        "M: 좋아. 쇼 직전인 3시에 만날까?",
        "W: 그건 너무 늦어. 거기 줄이 항상 길어.",
        "M: 맞네. 30분 일찍 만나는 건 어때?",
        "W: 딱 좋아. 그때 만나서 표부터 사자.",
        "M: 알겠어. 토요일에 매표소에서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, you look much happier than this morning."],
        ["M", "I found my puppy. He came home an hour ago."],
        ["W", "That's great news! I know you looked for him all night."],
        ["M", "I did. I put up posters around the whole neighborhood."],
        ["W", "Where was he hiding all that time?"],
        ["M", "He was sleeping under the neighbor's car."],
        ["W", "Oh, no wonder nobody could see him."],
        ["M", "I was so worried, but now I can finally breathe."],
      ],
      choices: ["bored", "angry", "relieved", "nervous", "jealous"],
      answer: 3,
      clue: "I was so worried, but now I can finally breathe.",
      explanation:
        "밤새 찾던 강아지가 돌아왔고 이제야 마음이 놓인다고 했으므로 남자의 심정은 '안도한(relieved)'이다. 따라서 답은 ③이다.",
      translation: [
        "W: 지호야, 아침보다 훨씬 밝아 보인다.",
        "M: 강아지를 찾았어. 한 시간 전에 집에 왔어.",
        "W: 정말 잘됐다! 밤새 찾아다닌 거 알아.",
        "M: 맞아. 동네 곳곳에 전단도 붙였어.",
        "W: 그동안 어디 숨어 있었대?",
        "M: 옆집 차 밑에서 자고 있었어.",
        "W: 아, 그러니 아무도 못 봤지.",
        "M: 정말 걱정했는데, 이제야 숨이 쉬어져.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Where is the teachers' room?"],
        ["M", "It's on the second floor."],
        ["ANN", "Number two."],
        ["W", "Did you clean the stairs?"],
        ["M", "Yes, I did it yesterday."],
        ["ANN", "Number three."],
        ["W", "Shall I carry that box for you?"],
        ["M", "Yes, please. It's really heavy."],
        ["ANN", "Number four."],
        ["W", "What is inside the box?"],
        ["M", "Some old books and notebooks."],
        ["ANN", "Number five."],
        ["W", "Can I take the elevator?"],
        ["M", "Sure, it's over there."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Shall I carry that box for you?",
      explanation:
        "그림은 계단에서 무거운 상자를 든 남자 선생님에게 여학생이 손을 내밀며 들어 드리겠다고 하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "A school stairway, clean black line art on a plain white background, no writing anywhere. " +
          "A male teacher is walking down the stairs holding a large heavy cardboard box with both arms. " +
          "A schoolgirl standing a few steps below reaches out both hands toward the box to help him. " +
          "A handrail and a window are drawn simply in the background.",
      },
      translation: [
        "① W: 교무실이 어디예요? / M: 2층에 있어요.",
        "② W: 계단 청소했니? / M: 네, 어제 했어요.",
        "③ W: 그 상자 제가 들어 드릴까요? / M: 응, 부탁해. 정말 무겁구나.",
        "④ W: 상자 안에 뭐가 들어 있어요? / M: 오래된 책이랑 공책들이야.",
        "⑤ W: 엘리베이터를 타도 되나요? / M: 그럼, 저쪽에 있어.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, I'm going on a school trip for three days."],
        ["M", "That sounds fun. When do you leave?"],
        ["W", "Tomorrow morning. But I have a small problem."],
        ["M", "What is it? Maybe I can help you."],
        ["W", "I keep three flower pots on my classroom windowsill."],
        ["M", "Ah, the ones you grew from seeds in spring?"],
        ["W", "Yes. Could you water them while I'm away?"],
        ["M", "No problem. I'll give them water every morning."],
      ],
      choices: ["숙제 대신 내 주기", "교실 창문 닫기", "씨앗 사 오기", "화분에 물 주기", "사진 찍어 보내기"],
      answer: 4,
      clue: "Could you water them while I'm away?",
      explanation:
        "여자는 수학여행을 가 있는 동안 교실 창가의 화분에 물을 줘 달라고 부탁했다. 따라서 답은 ④이다.",
      translation: [
        "W: 준호야, 나 3일 동안 수학여행 가.",
        "M: 재밌겠다. 언제 떠나?",
        "W: 내일 아침에. 그런데 작은 문제가 하나 있어.",
        "M: 뭔데? 내가 도와줄 수 있을지도 몰라.",
        "W: 교실 창가에 화분을 세 개 두고 있거든.",
        "M: 아, 봄에 씨앗부터 키운 그거?",
        "W: 응. 나 없는 동안 물 좀 줄 수 있어?",
        "M: 그럼. 아침마다 물 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 벼룩시장에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Good afternoon, everyone. Our school flea market opens next Wednesday. " +
            "It will be held in the front playground from one to four. " +
            "You may bring books, toys, and clothes you no longer use. " +
            "Please put a price tag on every item before you come. " +
            "All the money we collect will go to the animal shelter near our school. " +
            "Come early and find something you like.",
        ],
      ],
      choices: ["열리는 날", "참가 신청 방법", "열리는 장소", "운영 시간", "모은 돈의 쓰임"],
      answer: 2,
      clue: "참가 신청 방법은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 수요일), 장소(앞 운동장), 운영 시간(1시~4시), 모은 돈의 쓰임(동물 보호소)은 언급되지만 참가 신청 방법은 언급되지 않았다. 따라서 답은 ②이다.",
      translation: [
        "M: 안녕하세요, 여러분. 우리 학교 벼룩시장이 다음 주 수요일에 열립니다. 앞 운동장에서 1시부터 4시까지 진행됩니다. 더 이상 쓰지 않는 책, 장난감, 옷을 가져오셔도 됩니다. 오기 전에 모든 물건에 가격표를 붙여 주세요. 모은 돈은 모두 학교 근처 동물 보호소에 전달됩니다. 일찍 와서 마음에 드는 물건을 찾아보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You can find one on a wall or on a desk. " +
            "It has twelve pages, and each page shows one month. " +
            "Each page has numbers in rows, and the numbers tell you the days of the week. " +
            "People mark birthdays and holidays on it with a pen. " +
            "At the end of December, you need a new one.",
        ],
      ],
      choices: ["시계", "지도", "일기장", "사전", "달력"],
      answer: 5,
      clue: "It has twelve pages, and each page shows one month.",
      explanation:
        "열두 장이 한 장씩 한 달을 보여 주고, 생일과 공휴일을 표시하며, 12월 말에 새것이 필요한 것은 달력이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 이것은 벽이나 책상에서 볼 수 있습니다. 열두 장으로 되어 있고, 한 장이 한 달을 보여 줍니다. 각 장에는 숫자가 줄지어 있고, 그 숫자가 요일을 알려 줍니다. 사람들은 여기에 펜으로 생일과 공휴일을 표시합니다. 12월 말이 되면 새것이 필요합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was your winter vacation?"],
        ["W", "It was great. I visited my grandmother."],
        ["ANN", "Number two."],
        ["M", "Can I borrow your eraser?"],
        ["W", "Sure, here you are."],
        ["ANN", "Number three."],
        ["M", "How long does it take to get there?"],
        ["W", "It costs five dollars."],
        ["ANN", "Number four."],
        ["M", "What do you want to be in the future?"],
        ["W", "I want to be a pilot."],
        ["ANN", "Number five."],
        ["M", "How often do you exercise?"],
        ["W", "I exercise three times a week."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How long does it take to get there?",
      explanation:
        "걸리는 시간을 묻는 말에 값이 5달러라고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 겨울 방학 어땠어? / W: 정말 좋았어. 할머니 댁에 다녀왔어.",
        "② M: 지우개 좀 빌려줄래? / W: 그럼, 여기 있어.",
        "③ M: 거기까지 얼마나 걸려? / W: 5달러야.",
        "④ M: 넌 나중에 뭐가 되고 싶어? / W: 나는 조종사가 되고 싶어.",
        "⑤ M: 운동을 얼마나 자주 해? / W: 일주일에 세 번 해.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, the class photo exhibition is tomorrow. Is everything ready?"],
        ["M", "Almost. I printed all twenty photos this morning."],
        ["W", "Great. Did you put them on the board in the hallway?"],
        ["M", "Not yet. I don't have enough pins for them."],
        ["W", "The art teacher keeps a box of pins in her office."],
        ["M", "Then I should go and borrow some right now."],
        ["W", "Good idea. I'll write the title cards while you're gone."],
        ["M", "Thanks. I'll be back in five minutes."],
      ],
      choices: ["미술 선생님께 핀 빌리기", "사진 인화하기", "제목 카드 쓰기", "게시판 청소하기", "사진 고르기"],
      answer: 1,
      clue: "Then I should go and borrow some right now.",
      explanation:
        "사진은 다 인화했지만 핀이 모자라서, 남자는 지금 바로 미술 선생님께 핀을 빌리러 가겠다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 준호야, 학급 사진 전시가 내일이야. 준비 다 됐어?",
        "M: 거의. 오늘 아침에 사진 스무 장 다 인화했어.",
        "W: 잘했다. 복도 게시판에 붙였어?",
        "M: 아직. 핀이 모자라.",
        "W: 미술 선생님 교무실에 핀 상자가 있어.",
        "M: 그럼 지금 바로 가서 빌려 와야겠다.",
        "W: 좋은 생각이야. 네가 간 사이에 내가 제목 카드를 쓸게.",
        "M: 고마워. 5분 안에 돌아올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 운동화를 고르시오.",
      lines: [
        ["M", "Sora, are you buying new running shoes today?"],
        ["W", "Yes. My old ones are too small for me now."],
        ["M", "Look at this list. Which size do you need?"],
        ["W", "I need size two hundred fifty. Anything smaller hurts my feet."],
        ["M", "Okay. And how much can you spend on them?"],
        ["W", "I have fifty thousand won, so it must be under that."],
        ["M", "Got it. Do you care about the color?"],
        ["W", "I don't want white ones. They get dirty too fast."],
        ["M", "Then only one pair on this list is right for you."],
        ["W", "Great. Let's ask the clerk to bring that pair."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I need size two hundred fifty.",
      explanation:
        "250 사이즈이면서 5만 원 미만이고 흰색이 아닌 것을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Size: 245 / Price: 45,000 won / Color: Black" },
          { no: 2, label: "②", value: "Size: 250 / Price: 58,000 won / Color: Blue" },
          { no: 3, label: "③", value: "Size: 250 / Price: 42,000 won / Color: White" },
          { no: 4, label: "④", value: "Size: 250 / Price: 47,000 won / Color: Black" },
          { no: 5, label: "⑤", value: "Size: 245 / Price: 39,000 won / Color: Blue" },
        ],
      },
      translation: [
        "M: 소라야, 오늘 운동화 새로 사는 거야?",
        "W: 응. 신던 게 이제 너무 작아.",
        "M: 이 목록 봐. 어떤 사이즈가 필요해?",
        "W: 250이 필요해. 그보다 작으면 발이 아파.",
        "M: 알겠어. 얼마까지 쓸 수 있어?",
        "W: 5만 원이 있으니까 그보다 싸야 해.",
        "M: 그렇구나. 색깔은 상관있어?",
        "W: 흰색은 싫어. 너무 빨리 더러워져.",
        "M: 그럼 이 목록에서 딱 한 켤레만 맞네.",
        "W: 좋아. 점원에게 그걸 가져다 달라고 하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Minjun, when should we do our volunteer work at the shelter?"],
        ["M", "How about October 5th? That's next Monday."],
        ["W", "I can't. We have a math test that morning."],
        ["M", "Hmm. Then what about October 9th?"],
        ["W", "October 9th is a holiday, so the shelter is closed."],
        ["M", "You're right. October 12th is free for me."],
        ["W", "But my cousin's wedding is on the 12th."],
        ["M", "Then the only day left is October 7th."],
        ["W", "That works. I have nothing after school that day."],
        ["M", "Good. Let's meet at the school gate at two."],
      ],
      choices: ["10월 5일", "10월 7일", "10월 9일", "10월 12일", "10월 14일"],
      answer: 2,
      clue: "Then the only day left is October 7th.",
      explanation:
        "5일에는 수학 시험이, 9일에는 보호소 휴무가, 12일에는 사촌 결혼식이 있다. 두 사람은 10월 7일에 가기로 한다. 따라서 답은 ②이다.",
      translation: [
        "W: 민준아, 보호소 봉사 활동 언제 갈까?",
        "M: 10월 5일 어때? 다음 주 월요일이야.",
        "W: 안 돼. 그날 오전에 수학 시험이 있어.",
        "M: 음. 그럼 10월 9일은?",
        "W: 10월 9일은 공휴일이라 보호소가 문을 닫아.",
        "M: 맞네. 10월 12일은 내가 비어 있어.",
        "W: 그런데 12일에 사촌 언니 결혼식이 있어.",
        "M: 그럼 남는 날은 10월 7일뿐이네.",
        "W: 그날 괜찮아. 그날은 방과 후에 아무것도 없어.",
        "M: 좋아. 2시에 학교 정문에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sora, you look a little sunburned. Were you outside?"],
        ["W", "Yes, I spent all Saturday at the river with my family."],
        ["M", "Did you go fishing? Your dad loves fishing."],
        ["W", "He wanted to, but the water was too high after the rain."],
        ["M", "So what did you do there all day?"],
        ["W", "We picked up trash along the riverside with other families."],
        ["M", "Wow, that's a lot of work. Was it hard?"],
        ["W", "It was, but the river looked beautiful when we finished."],
      ],
      choices: ["낚시하기", "자전거 타기", "텐트 치기", "사진 찍기", "강가에서 쓰레기 줍기"],
      answer: 5,
      clue: "We picked up trash along the riverside with other families.",
      explanation:
        "비 때문에 낚시는 못 하고, 다른 가족들과 강가에서 쓰레기를 주웠다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 소라야, 좀 탄 것 같다. 밖에 있었어?",
        "W: 응, 토요일 내내 가족들이랑 강에 있었어.",
        "M: 낚시하러 갔어? 너희 아버지 낚시 좋아하시잖아.",
        "W: 하고 싶어 하셨는데, 비 온 뒤라 물이 너무 불었어.",
        "M: 그럼 거기서 하루 종일 뭐 했어?",
        "W: 다른 가족들이랑 강가에서 쓰레기를 주웠어.",
        "M: 우와, 일이 많았겠다. 힘들었어?",
        "W: 힘들었지만 끝내고 나니 강이 정말 예뻤어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is an announcement from the school office. " +
            "Tomorrow morning, workers will repair the water pipes under the first floor. " +
            "Because of this, the water will be turned off from nine until noon. " +
            "The bathrooms on the first and second floors will be closed during that time. " +
            "Please use the bathrooms on the third floor instead. " +
            "We are sorry for the trouble, and thank you for your understanding.",
        ],
      ],
      choices: [
        "화재 대피 훈련을 안내하려고",
        "급식 시간 변경을 안내하려고",
        "단수 사실을 안내하려고",
        "분실물을 찾아가라고 하려고",
        "체육대회 일정을 안내하려고",
      ],
      answer: 3,
      clue: "the water will be turned off from nine until noon",
      explanation:
        "1층 수도관 공사로 내일 오전 9시부터 정오까지 물이 끊긴다는 사실을 알리는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실에서 알려 드립니다. 내일 오전에 작업자들이 1층 아래 수도관을 수리합니다. 이 때문에 9시부터 정오까지 물이 나오지 않습니다. 그 시간 동안 1층과 2층 화장실은 사용할 수 없습니다. 대신 3층 화장실을 이용해 주십시오. 불편을 드려 죄송하며, 양해해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Welcome to the school supply shop."],
        ["W", "Hi. How much is this notebook?"],
        ["M", "One notebook is four dollars, and a pen is three dollars."],
        ["W", "Then I'll take three notebooks and two pens."],
        ["M", "That will be eighteen dollars in total."],
        ["W", "Oh, I have a member card. Does it help?"],
        ["M", "Yes, members get two dollars off any order over ten dollars."],
        ["W", "Great. Here is my card and the money."],
      ],
      choices: ["$16", "$12", "$14", "$15", "$18"],
      answer: 1,
      clue: "members get two dollars off any order over ten dollars",
      explanation:
        "공책 3권 12달러와 펜 2자루 6달러를 더하면 18달러이고, 회원 할인 2달러를 빼면 16달러이다. 따라서 답은 ①이다.",
      translation: [
        "M: 안녕하세요. 학용품 가게에 오신 걸 환영합니다.",
        "W: 안녕하세요. 이 공책은 얼마예요?",
        "M: 공책 한 권은 4달러, 펜은 3달러입니다.",
        "W: 그럼 공책 세 권과 펜 두 자루 주세요.",
        "M: 모두 18달러입니다.",
        "W: 아, 회원 카드가 있어요. 할인되나요?",
        "M: 네, 회원은 10달러가 넘는 주문에서 2달러를 빼 드립니다.",
        "W: 잘됐네요. 여기 카드랑 돈이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, are you joining the school band this year?"],
        ["M", "I want to, but I'm not sure I'm good enough."],
        ["W", "You've played the drums since elementary school."],
        ["M", "Only at home. I've never played with other people."],
        ["W", "The band practices every Tuesday and Thursday after school."],
        ["M", "That's a lot. I also have English class on Thursday."],
        ["W", "You can come on Tuesday only. Many members do that."],
        ["M", "Really? I didn't know the practice was that flexible."],
        ["W", "Why don't you come and watch our practice first?"],
      ],
      choices: [
        "I sold my drums last month.",
        "The band plays only in winter.",
        "You should practice the piano more.",
        "That's a good idea. I'll come this Tuesday.",
        "English class is on Monday this week.",
      ],
      answer: 4,
      clue: "Why don't you come and watch our practice first?",
      explanation:
        "여자가 먼저 연습을 보러 오라고 권했으므로, 좋은 생각이라며 화요일에 가 보겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 준호야, 올해 학교 밴드에 들어갈 거야?",
        "M: 그러고 싶은데, 내가 잘하는지 모르겠어.",
        "W: 너 초등학교 때부터 드럼 쳤잖아.",
        "M: 집에서만. 다른 사람들이랑은 한 번도 안 쳐 봤어.",
        "W: 밴드는 방과 후에 화요일이랑 목요일마다 연습해.",
        "M: 많다. 나 목요일엔 영어 수업도 있어.",
        "W: 화요일만 와도 돼. 그렇게 하는 부원도 많아.",
        "M: 정말? 연습이 그렇게 자유로운 줄 몰랐어.",
        "W: 먼저 우리 연습을 보러 오는 건 어때?",
        "M: 좋은 생각이야. 이번 화요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sora, did you finish the book report for Korean class?"],
        ["W", "Not yet. I chose a book, but I can't start writing."],
        ["M", "Which book did you pick? Maybe I've read it."],
        ["W", "It's a long novel about a family on an island."],
        ["M", "That's a hard one. Did you take any notes while reading?"],
        ["W", "No, I just read it from the first page to the last."],
        ["M", "That's why it's hard. Try writing down three scenes you remember."],
        ["W", "Only three? Is that really enough to start?"],
        ["M", "Yes. Once you write those down, the rest comes easily."],
      ],
      choices: [
        "I'll return the book today.",
        "Okay. I'll try that tonight.",
        "Korean class was cancelled.",
        "You should read the novel again.",
        "I wrote ten pages already.",
      ],
      answer: 2,
      clue: "Once you write those down, the rest comes easily.",
      explanation:
        "남자가 기억나는 장면 세 개를 적어 보라고 권했으므로, 알겠다며 오늘 밤에 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 소라야, 국어 시간 독서 감상문 다 썼어?",
        "W: 아직. 책은 골랐는데 쓰기 시작을 못 하겠어.",
        "M: 어떤 책 골랐어? 나도 읽었을지 몰라.",
        "W: 섬에 사는 한 가족 이야기인 긴 소설이야.",
        "M: 그거 어렵지. 읽으면서 메모는 했어?",
        "W: 아니, 그냥 첫 장부터 끝까지 읽기만 했어.",
        "M: 그래서 어려운 거야. 기억나는 장면 세 개를 적어 봐.",
        "W: 세 개만? 그걸로 시작이 돼?",
        "M: 응. 그것만 적어 두면 나머지는 쉽게 나와.",
        "W: 알겠어. 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Minjun, our class is making a video for the school festival."],
        ["M", "I heard about it. Who is filming it?"],
        ["W", "I am, but my phone runs out of battery too fast."],
        ["M", "How long do you need to film tomorrow?"],
        ["W", "About two hours, from one to three in the afternoon."],
        ["M", "My brother has a camera he doesn't use anymore."],
        ["W", "Really? Would he let me borrow it for one day?"],
        ["M", "I think so. He lent it to my cousin last month."],
        ["W", "That would help a lot. When can I ask him?"],
        ["M", "He comes home from work around six every evening."],
      ],
      choices: [
        "I'll buy a new phone tomorrow.",
        "The festival was two hours long.",
        "Your brother should film the video.",
        "I already returned the camera.",
        "Then I'll call him after six tonight.",
      ],
      answer: 5,
      clue: "He comes home from work around six every evening.",
      explanation:
        "남자가 형이 저녁 6시쯤 퇴근해 집에 온다고 했으므로, 오늘 저녁 6시 이후에 전화하겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 민준아, 우리 반이 학교 축제용 영상을 만들어.",
        "M: 들었어. 누가 찍어?",
        "W: 내가 찍는데, 내 휴대폰 배터리가 너무 빨리 닳아.",
        "M: 내일 얼마나 오래 찍어야 해?",
        "W: 오후 1시부터 3시까지 두 시간쯤.",
        "M: 우리 형한테 이제 안 쓰는 카메라가 있어.",
        "W: 정말? 하루만 빌려주실까?",
        "M: 그럴 거야. 지난달에 내 사촌한테도 빌려줬어.",
        "W: 그럼 정말 큰 도움이 될 텐데. 언제 여쭤보면 돼?",
        "M: 형은 매일 저녁 6시쯤 퇴근해서 집에 와.",
        "W: 그럼 오늘 저녁 6시 넘어서 전화할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sumin이 Taeho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Sumin : ________________",
      lines: [
        [
          "W",
          "Sumin and Taeho are on the same badminton team. " +
            "They are practicing hard for the school tournament next week. " +
            "During practice, Sumin notices that Taeho's shoelaces are untied. " +
            "Taeho is about to run to the other side of the court. " +
            "Sumin is worried that Taeho will trip and get hurt. " +
            "In this situation, what would Sumin most likely say to Taeho?",
        ],
      ],
      choices: [
        "Let's change the net before we start.",
        "The tournament is next month.",
        "Wait, your shoelaces are untied.",
        "You should buy a new racket.",
        "I'll bring water bottles tomorrow.",
      ],
      answer: 3,
      clue: "Sumin is worried that Taeho will trip and get hurt.",
      explanation:
        "수민이는 태호의 신발 끈이 풀린 것을 보고 넘어져 다칠까 봐 걱정하고 있으므로, 신발 끈이 풀렸다고 알려 주는 ③이 가장 적절하다.",
      translation: [
        "W: 수민이와 태호는 같은 배드민턴 팀입니다. 두 사람은 다음 주 교내 대회를 위해 열심히 연습하고 있습니다. 연습 중에 수민이는 태호의 신발 끈이 풀린 것을 발견합니다. 태호는 막 코트 반대편으로 뛰어가려 합니다. 수민이는 태호가 걸려 넘어져 다칠까 봐 걱정합니다. 이런 상황에서 수민이가 태호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
