/** 중1 듣기 22회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 22회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 필통을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a pencil case?"],
        ["W", "Yes. Mine broke this morning."],
        ["M", "We have round ones and flat ones."],
        ["W", "A flat one, please. It fits in my book."],
        ["M", "This flat one has stars on it."],
        ["W", "Stars are a little childish for me."],
        ["M", "Then here is a flat one with stripes."],
        ["W", "I like that. I'll take the striped one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A flat one, please. / I'll take the striped one.",
      explanation: "여자는 납작한 필통을 원하고, 별무늬는 유치하다며 줄무늬를 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five pencil cases drawn side by side as five choices, clean black line art on white. " +
          "① a ROUND pencil case covered in STARS. " +
          "② a ROUND pencil case covered in STRIPES. " +
          "③ a FLAT pencil case covered in STARS. " +
          "④ a FLAT pencil case covered in STRIPES. " +
          "⑤ a FLAT pencil case with NO pattern at all.",
      },
      translation: [
        "M: 안녕하세요. 필통을 찾으세요?",
        "W: 네. 오늘 아침에 제 것이 망가졌어요.",
        "M: 둥근 것도 있고 납작한 것도 있어요.",
        "W: 납작한 걸로요. 책 사이에 들어가거든요.",
        "M: 이 납작한 건 별무늬가 있어요.",
        "W: 별무늬는 저한테 좀 유치해요.",
        "M: 그럼 여기 줄무늬 납작한 것이 있어요.",
        "W: 마음에 들어요. 줄무늬로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 사진 전시회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Did you see the poster for the photo show?"],
        ["M", "Yes. Where will it be held?"],
        ["W", "In the first-floor hallway, next to the library."],
        ["M", "Nice. When does it open?"],
        ["W", "It opens next Wednesday and runs for three days."],
        ["M", "Who can put up photos?"],
        ["W", "Any student in our school can join."],
        ["M", "What should we bring?"],
        ["W", "Bring one printed photo and a short title card."],
      ],
      choices: ["장소", "관람 시간", "기간", "참가 대상", "준비물"],
      answer: 2,
      clue: "Bring one printed photo and a short title card.",
      explanation:
        "장소(1층 복도), 기간(다음 주 수요일부터 사흘), 참가 대상(우리 학교 학생), 준비물(인화한 사진과 제목표)은 언급되지만 관람 시간은 언급되지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 사진 전시회 포스터 봤어?",
        "M: 응. 어디서 열려?",
        "W: 1층 복도, 도서관 옆에서.",
        "M: 좋네. 언제 열어?",
        "W: 다음 주 수요일에 열어서 사흘 동안 해.",
        "M: 누가 사진을 걸 수 있어?",
        "W: 우리 학교 학생이면 누구나 참여할 수 있어.",
        "M: 뭘 가져가야 해?",
        "W: 인화한 사진 한 장이랑 짧은 제목표를 가져와.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hi, Jiho. It's Soyeon."],
        ["M", "Hi, Soyeon. What's up?"],
        ["W", "I'm at the art room now."],
        ["M", "Are you painting the class banner?"],
        ["W", "Yes, but we ran out of blue paint."],
        ["M", "Oh, do you need some?"],
        ["W", "Yes. Can you bring two blue tubes tomorrow?"],
        ["M", "Sure. I'll put them in my bag tonight."],
      ],
      choices: [
        "배너 무늬를 정하려고",
        "미술실 위치를 물어보려고",
        "그림 그리는 법을 배우려고",
        "작업 시간을 바꾸려고",
        "파란 물감을 가져와 달라고 부탁하려고",
      ],
      answer: 5,
      clue: "Can you bring two blue tubes tomorrow?",
      explanation: "여자는 파란 물감이 떨어졌다며 내일 두 개를 가져다 달라고 부탁한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕, 지호야. 나 소연이야.",
        "M: 안녕, 소연아. 무슨 일이야?",
        "W: 나 지금 미술실에 있어.",
        "M: 학급 현수막 칠하고 있어?",
        "W: 응, 그런데 파란 물감이 다 떨어졌어.",
        "M: 아, 좀 필요해?",
        "W: 응. 내일 파란 물감 두 개 가져다줄 수 있어?",
        "M: 그럼. 오늘 밤에 가방에 넣어 둘게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Suji, what time does the school play start?"],
        ["W", "At 7:00 p.m. The doors open thirty minutes before."],
        ["M", "Then let's meet when the doors open."],
        ["W", "That's 6:30. But I want to save our seats first."],
        ["M", "Good idea. The front rows fill up fast."],
        ["W", "Then let's meet fifteen minutes earlier than that."],
        ["M", "Fifteen minutes earlier? All right."],
        ["W", "I'll wait by the poster near the door."],
        ["M", "See you then."],
      ],
      choices: ["6:00 p.m.", "6:30 p.m.", "6:15 p.m.", "6:45 p.m.", "7:00 p.m."],
      answer: 3,
      clue: "That's 6:30. / let's meet fifteen minutes earlier than that",
      explanation:
        "공연이 7시에 시작하고 문은 30분 전인 6시 30분에 연다. 자리를 맡으려고 그보다 15분 더 일찍 만나기로 했으므로 6시 15분이다. 따라서 답은 ③이다.",
      translation: [
        "M: 수지야, 학교 연극 몇 시에 시작해?",
        "W: 저녁 7시에. 문은 30분 전에 열어.",
        "M: 그럼 문 열 때 만나자.",
        "W: 6시 30분이네. 그런데 자리를 먼저 맡고 싶어.",
        "M: 좋은 생각이야. 앞줄은 금방 차거든.",
        "W: 그럼 그보다 15분 더 일찍 만나자.",
        "M: 15분 더 일찍? 알겠어.",
        "W: 문 옆 포스터 앞에서 기다릴게.",
        "M: 그때 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjun, why are you holding that empty box?"],
        ["M", "My class pet hamster is gone. The door was open."],
        ["W", "Oh no. Did you look under the desks?"],
        ["M", "Yes, twice. I even checked the hallway."],
        ["W", "Don't give up. We can look together."],
        ["M", "Thanks. I keep thinking it's my fault."],
        ["W", "It isn't. Let's check the back closet first."],
      ],
      choices: ["worried", "excited", "proud", "bored", "satisfied"],
      answer: 1,
      clue: "I keep thinking it's my fault.",
      explanation:
        "남자는 햄스터가 사라져 두 번이나 찾아보고도 못 찾았고 자기 잘못 같다고 말한다. 걱정하는 마음이므로 답은 ①이다.",
      translation: [
        "W: 민준아, 왜 빈 상자를 들고 있어?",
        "M: 우리 반 햄스터가 없어졌어. 문이 열려 있었어.",
        "W: 어떡해. 책상 밑은 봤어?",
        "M: 응, 두 번이나. 복도도 확인했어.",
        "W: 포기하지 마. 같이 찾아보자.",
        "M: 고마워. 자꾸 내 잘못인 것 같아.",
        "W: 아니야. 뒤쪽 사물함부터 보자.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is this seat free?"],
        ["M", "Yes, please sit down."],
        ["ANN", "Number two."],
        ["W", "Excuse me, I dropped my card."],
        ["M", "Here it is. I picked it up for you."],
        ["ANN", "Number three."],
        ["W", "Which bus goes to the museum?"],
        ["M", "Take the number nine bus."],
        ["ANN", "Number four."],
        ["W", "Did you ride the bus yesterday?"],
        ["M", "Yes, it was very crowded."],
        ["ANN", "Number five."],
        ["W", "Shall we get off here?"],
        ["M", "No, one more stop."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, I dropped my card. / Here it is. I picked it up for you.",
      explanation:
        "그림은 버스 안에서 남학생이 바닥에 떨어진 카드를 주워 여학생에게 건네주는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a city bus, clean black line art on a plain white background, no writing anywhere. " +
          "A boy is bending down and holding out a small card to a girl who stands beside him with her bag open. " +
          "Other passengers sit on the seats behind them. The bus windows and handrails are drawn simply.",
      },
      translation: [
        "① W: 이 자리 비었나요? / M: 네, 앉으세요.",
        "② W: 저기요, 카드를 떨어뜨렸어요. / M: 여기 있어요. 제가 주웠어요.",
        "③ W: 박물관에 가는 버스가 어느 것인가요? / M: 9번 버스를 타세요.",
        "④ W: 어제 버스 탔어? / M: 응, 아주 붐볐어.",
        "⑤ W: 여기서 내릴까? / M: 아니, 한 정거장 더 가.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suji, the class garden day starts at four in the afternoon."],
        ["W", "Right. I already filled all the watering cans this morning."],
        ["M", "Great. Then I'll hand out the gloves to everyone."],
        ["W", "Good. Did you sweep the path beside the flower bed?"],
        ["M", "Yes, I finished that during lunch break today."],
        ["W", "Thanks. Then almost everything is ready for the class."],
        ["M", "Is there anything else you want me to do?"],
        ["W", "Could you bring the seed packets from the science room? My hands are full of watering cans right now."],
        ["M", "Sure. I'll get them right away and meet you outside."],
      ],
      choices: ["물뿌리개 채우기", "씨앗 봉지 가져오기", "장갑 나눠 주기", "화단 옆 길 쓸기", "시작 시간 알리기"],
      answer: 2,
      clue: "Could you bring the seed packets from the science room?",
      explanation:
        "물뿌리개는 여자가 이미 채웠고, 장갑 나눠 주기와 길 쓸기는 남자가 하는 일이다. 여자는 과학실에서 씨앗 봉지를 가져다 달라고 부탁한다. 따라서 답은 ②이다.",
      translation: [
        "M: 수지야, 학급 텃밭의 날은 오후 네 시에 시작해.",
        "W: 맞아. 물뿌리개는 오늘 아침에 내가 다 채워 놨어.",
        "M: 잘했다. 그럼 장갑은 내가 모두에게 나눠 줄게.",
        "W: 좋아. 화단 옆 길은 쓸었어?",
        "M: 응, 오늘 점심시간에 다 했어.",
        "W: 고마워. 그럼 수업 준비는 거의 다 됐네.",
        "M: 내가 더 할 일이 있을까?",
        "W: 과학실에서 씨앗 봉지를 가져다줄 수 있어? 지금 두 손에 물뿌리개가 가득해.",
        "M: 그럼. 바로 가져와서 밖에서 만나자.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 남자가 독서 동아리 모집에 대해 언급하지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, everyone. Our reading club is looking for new members. " +
            "We meet every Thursday after school in the library. " +
            "This term we will read three short novels together. " +
            "Please bring a notebook and a pen to each meeting. " +
            "Come and enjoy reading with us.",
        ],
      ],
      choices: ["모임 요일", "모임 장소", "읽을 책 수", "준비물", "모집 인원"],
      answer: 5,
      clue: "Please bring a notebook and a pen to each meeting.",
      explanation:
        "모임 요일(목요일), 모임 장소(도서관), 읽을 책 수(짧은 소설 세 권), 준비물(공책과 펜)은 언급되지만 몇 명을 뽑는지는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안녕하세요, 여러분. 우리 독서 동아리에서 새 회원을 찾고 있습니다. 우리는 목요일마다 방과 후에 도서관에서 만납니다. 이번 학기에는 짧은 소설 세 권을 함께 읽을 거예요. 모임마다 공책과 펜을 가져와 주세요. 와서 우리와 함께 즐겁게 읽어요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "This is a small thing you wear on your wrist."],
        ["W", "It has two hands that move around a circle."],
        ["W", "Some kinds show numbers instead of hands."],
        ["W", "You look at it when you are late for class."],
        ["W", "It tells you the time wherever you go."],
      ],
      choices: ["거울", "지갑", "시계", "반지", "나침반"],
      answer: 3,
      clue: "It tells you the time wherever you go.",
      explanation: "손목에 차고 바늘이 원을 도는 작은 물건으로 시간을 알려 주므로 시계다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 손목에 차는 작은 물건입니다.",
        "W: 원을 도는 바늘 두 개가 있습니다.",
        "W: 바늘 대신 숫자를 보여 주는 것도 있습니다.",
        "W: 수업에 늦었을 때 이것을 봅니다.",
        "W: 어디에 가든 시간을 알려 줍니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How many pages should we read?"],
        ["W", "It is on the second shelf."],
        ["ANN", "Number two."],
        ["M", "How was your weekend?"],
        ["W", "It was great. I went hiking."],
        ["ANN", "Number three."],
        ["W", "Can I borrow your eraser?"],
        ["M", "Sure. Here you are."],
        ["ANN", "Number four."],
        ["W", "Where is the nurse's office?"],
        ["M", "Go down this hall and turn right."],
        ["ANN", "Number five."],
        ["M", "Do you want to join our team?"],
        ["W", "Yes, that sounds fun."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "How many pages should we read? / It is on the second shelf.",
      explanation:
        "①에서 남자는 몇 쪽을 읽어야 하는지 물었는데 여자는 둘째 칸에 있다고 자리를 답한다. 묻는 것과 답이 어긋나므로 답은 ①이다.",
      translation: [
        "① M: 몇 쪽을 읽어야 해? / W: 그건 둘째 칸에 있어.",
        "② M: 주말 어땠어? / W: 좋았어. 등산 갔어.",
        "③ W: 지우개 좀 빌려줄래? / M: 그럼. 여기 있어.",
        "④ W: 보건실이 어디예요? / M: 이 복도로 가서 오른쪽으로 도세요.",
        "⑤ M: 우리 팀에 들어올래? / W: 응, 재미있겠다.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiwon, the science fair opens tomorrow morning."],
        ["W", "I know. I finished our poster late last night."],
        ["M", "It looks really clear. Did you print the data sheet?"],
        ["W", "Not yet. The printer in the computer room was busy."],
        ["M", "We should also practice the presentation once more."],
        ["W", "Let's do that after we bring everything to the gym."],
        ["M", "Fine. I'll carry the model to the gym myself."],
        ["W", "Thanks. Then I'll go print the data sheet now."],
        ["M", "Good. I'll meet you by the stage in ten minutes."],
      ],
      choices: ["포스터 만들기", "모형 옮기기", "발표 연습하기", "자료 인쇄하기", "체육관 청소하기"],
      answer: 4,
      clue: "Then I'll go print the data sheet now.",
      explanation:
        "포스터는 어젯밤에 끝냈고, 모형 옮기기는 남자가 하며, 발표 연습은 나중에 할 일이다. 여자는 지금 자료를 인쇄하러 가겠다고 한다. 따라서 답은 ④이다.",
      translation: [
        "M: 지원아, 과학전람회가 내일 아침에 열려.",
        "W: 알아. 어젯밤 늦게 포스터를 끝냈어.",
        "M: 아주 보기 좋더라. 자료 표는 인쇄했어?",
        "W: 아직. 컴퓨터실 프린터가 바빴어.",
        "M: 발표 연습도 한 번 더 해야 해.",
        "W: 짐을 체육관에 다 옮기고 나서 하자.",
        "M: 좋아. 모형은 내가 체육관으로 옮길게.",
        "W: 고마워. 그럼 나는 지금 자료를 인쇄하러 갈게.",
        "M: 좋아. 10분 뒤에 무대 옆에서 만나자.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 방과후 수업을 고르시오.",
      lines: [
        ["M", "Hyerin, have you chosen an after-school class yet?"],
        ["W", "Not yet. I have piano lessons on Monday and Wednesday."],
        ["M", "Then you need a class on another day of the week."],
        ["W", "Right. I'd like one that meets on Friday afternoon."],
        ["M", "Okay. What about the fee? Some classes are expensive."],
        ["W", "It has to be under twenty thousand won for the term."],
        ["M", "Good. And which subject are you interested in?"],
        ["W", "I want a cooking class. Sports classes are too tiring for me."],
        ["M", "Then only one class fits all three of your conditions."],
        ["W", "Great. I'll sign up for it at the office today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "I'd like one that meets on Friday afternoon.",
      explanation:
        "금요일이고, 2만 원 미만이며, 요리 수업인 것을 고른다. 이 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Friday / Fee: 25,000 won / Subject: Cooking" },
          { no: 2, label: "②", value: "Day: Friday / Fee: 18,000 won / Subject: Cooking" },
          { no: 3, label: "③", value: "Day: Monday / Fee: 18,000 won / Subject: Cooking" },
          { no: 4, label: "④", value: "Day: Friday / Fee: 15,000 won / Subject: Sports" },
          { no: 5, label: "⑤", value: "Day: Thursday / Fee: 12,000 won / Subject: Sports" },
        ],
      },
      translation: [
        "M: 혜린아, 방과후 수업 골랐어?",
        "W: 아직. 월요일이랑 수요일에는 피아노 수업이 있어.",
        "M: 그럼 다른 요일에 하는 수업이 필요하겠네.",
        "W: 맞아. 금요일 오후에 하는 걸로 하고 싶어.",
        "M: 좋아. 수강료는? 비싼 수업도 있어.",
        "W: 한 학기에 2만 원 미만이어야 해.",
        "M: 좋아. 어떤 과목에 관심이 있어?",
        "W: 요리 수업이 좋아. 운동 수업은 나한테 너무 힘들어.",
        "M: 그럼 세 조건을 다 채우는 건 하나뿐이네.",
        "W: 좋아. 오늘 행정실에서 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 벽화를 그릴 날짜를 고르시오.",
      lines: [
        ["M", "Dain, let's paint the class mural sometime next week."],
        ["W", "Sure. The art teacher said we can use the art room."],
        ["M", "Great. How about September 8th, right after school?"],
        ["W", "I can't. I have a dentist appointment that afternoon."],
        ["M", "Then can we do it on the 10th instead?"],
        ["W", "Wait, the art room is closed on the 10th for cleaning."],
        ["M", "Hmm. What about September 12th? My schedule is empty."],
        ["W", "The 12th is our class field trip day, remember?"],
        ["M", "Oh, right. Then September 14th should work for both of us."],
        ["W", "Perfect. Let's start right after lunch that day."],
      ],
      choices: ["9월 8일", "9월 10일", "9월 12일", "9월 16일", "9월 14일"],
      answer: 5,
      clue: "Then September 14th should work for both of us.",
      explanation:
        "8일에는 치과 예약이, 10일에는 미술실 청소가, 12일에는 현장 학습이 있다. 두 사람은 9월 14일에 하기로 한다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 다음 주 언젠가 학급 벽화를 그리자.",
        "W: 좋아. 미술 선생님이 미술실 써도 된다고 하셨어.",
        "M: 잘됐다. 9월 8일 방과 후는 어때?",
        "W: 안 돼. 그날 오후에 치과 예약이 있어.",
        "M: 그럼 10일에 할까?",
        "W: 잠깐, 10일에는 미술실이 청소 때문에 닫아.",
        "M: 음. 9월 12일은 어때? 내 일정은 비어 있어.",
        "W: 12일은 우리 반 현장 학습 날이잖아.",
        "M: 아, 맞다. 그럼 9월 14일이면 둘 다 괜찮겠다.",
        "W: 좋아. 그날 점심 먹고 바로 시작하자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, did you go to the swimming pool last weekend?"],
        ["W", "No, I couldn't. The pool was closed for cleaning."],
        ["M", "Oh, that's too bad. You were looking forward to it."],
        ["W", "I know. So I stayed home with my grandmother instead."],
        ["M", "Did you watch movies together all afternoon?"],
        ["W", "No, we baked cookies. She taught me her own recipe."],
        ["M", "That sounds fun. I played badminton with my brother."],
        ["W", "Nice. I'll go swimming next weekend if the pool opens."],
      ],
      choices: ["수영하러 가기", "배드민턴 치기", "쿠키 굽기", "수영장 청소하기", "할머니 댁 가기"],
      answer: 3,
      clue: "No, we baked cookies. She taught me her own recipe.",
      explanation: "수영장이 닫아서 여자는 할머니와 쿠키를 구웠다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "M: 서연아, 지난 주말에 수영장 갔어?",
        "W: 아니, 못 갔어. 수영장이 청소 때문에 닫았어.",
        "M: 아쉽다. 기대했었잖아.",
        "W: 그러게. 그래서 대신 할머니랑 집에 있었어.",
        "M: 오후 내내 같이 영화 봤어?",
        "W: 아니, 쿠키를 구웠어. 할머니가 비법을 알려 주셨어.",
        "M: 재미있었겠다. 나는 동생이랑 배드민턴 쳤어.",
        "W: 좋네. 수영장이 열면 다음 주말에 수영하러 갈 거야.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Attention, students. This is an announcement from the school office."],
        ["W", "The front gate will be repaired this afternoon from one o'clock."],
        ["W", "Workers will be moving heavy metal parts near the entrance."],
        ["W", "For your safety, please do not walk past the front gate today."],
        ["W", "Instead, use the side gate next to the gym building."],
        ["W", "The repair work will be finished before five o'clock."],
        ["W", "Thank you for taking the longer way and walking safely."],
      ],
      choices: [
        "정문 공사로 옆문을 이용하라고 알리려고",
        "하교 시간 변경을 알리려고",
        "체육관 이용 규칙을 설명하려고",
        "안전 교육 참가를 권하려고",
        "자전거 보관 장소를 안내하려고",
      ],
      answer: 1,
      clue: "The front gate will be repaired this afternoon. / Please use the side gate near the gym.",
      explanation: "정문을 고치는 동안 체육관 옆 옆문을 쓰라고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알립니다. 학교 행정실에서 알려 드립니다.",
        "W: 오늘 오후 한 시부터 정문을 고칠 예정입니다.",
        "W: 작업자들이 출입구 근처에서 무거운 쇠붙이를 옮깁니다.",
        "W: 안전을 위해 오늘은 정문 쪽으로 다니지 마세요.",
        "W: 대신 체육관 건물 옆 옆문을 이용해 주세요.",
        "W: 공사는 다섯 시 전에 끝납니다.",
        "W: 돌아서 안전하게 다녀 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Good afternoon. What can I get for you today?"],
        ["W", "I need some notebooks for my science class, please."],
        ["M", "These lined notebooks are two dollars each today."],
        ["W", "Then I'll take three notebooks, please."],
        ["M", "Sure. Do you need anything else for your class?"],
        ["W", "Yes, I also want one glue stick for my project."],
        ["M", "The glue stick is three dollars. Do you have a coupon?"],
        ["W", "Yes, I have a two-dollar coupon from last week."],
        ["M", "Great. I'll take that off your total for you."],
      ],
      choices: ["$5", "$9", "$11", "$7", "$13"],
      answer: 4,
      clue: "Then I'll take three notebooks, please.",
      explanation:
        "공책 세 권은 2달러씩이라 6달러이고 풀은 3달러여서 모두 9달러다. 여기서 쿠폰 2달러를 빼면 7달러이므로 답은 ④이다.",
      translation: [
        "M: 안녕하세요. 오늘 무엇을 드릴까요?",
        "W: 과학 시간에 쓸 공책이 필요해요.",
        "M: 이 줄공책은 오늘 한 권에 2달러입니다.",
        "W: 그럼 세 권 주세요.",
        "M: 네. 수업에 더 필요한 게 있나요?",
        "W: 네, 과제에 쓸 풀도 하나 주세요.",
        "M: 풀은 3달러입니다. 쿠폰 있으세요?",
        "W: 네, 지난주에 받은 2달러짜리 쿠폰이 있어요.",
        "M: 좋습니다. 합계에서 빼 드릴게요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Our school festival booth is in the gym this year."],
        ["W", "Okay. I've never been to the gym building before."],
        ["M", "It's the tall building next to the music room."],
        ["W", "So I walk past the stairs on the first floor, right?"],
        ["M", "Yes, and keep going until you see the water fountain."],
        ["W", "And then which way do I turn there?"],
        ["M", "Turn left at the water fountain and go straight."],
        ["W", "After that, where should I wait for you?"],
        ["M", "Wait by the blue table near the gym door."]
      ],
      choices: [
        "No, I don't like music.",
        "Got it. I'll wait there.",
        "The festival was last week.",
        "Let's buy a new table.",
        "I lost my water bottle.",
      ],
      answer: 2,
      clue: "Wait by the blue table near the gym door.",
      explanation: "남자가 문 옆 파란 탁자에서 기다리라고 알려 주었으므로, 알겠다며 거기서 기다리겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 올해 우리 학교 축제 부스는 체육관에 있어.",
        "W: 알겠어. 나 체육관 건물에 가 본 적이 없어.",
        "M: 음악실 옆에 있는 높은 건물이야.",
        "W: 그럼 1층 계단을 지나가는 거지?",
        "M: 응, 정수기가 보일 때까지 계속 가.",
        "W: 거기서 어느 쪽으로 돌아?",
        "M: 정수기에서 왼쪽으로 돌아서 곧장 가.",
        "W: 그다음엔 어디서 기다릴까?",
        "M: 체육관 문 옆 파란 탁자에서 기다려.",
        "W: 알겠어. 거기서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Hyerin, I can't find my gym clothes anywhere."],
        ["W", "Did you check your locker in the hallway?"],
        ["M", "Yes, and I looked in my school bag twice."],
        ["W", "Maybe you left them in the classroom after lunch."],
        ["M", "I looked under every desk there too."],
        ["W", "What about the bench outside the gym?"],
        ["M", "I checked. Class starts in ten minutes."],
        ["W", "Then try the lost and found box by the office."],
      ],
      choices: [
        "Let's skip gym class today.",
        "I found them in your bag.",
        "The office closed last week.",
        "Please wash my gym clothes.",
        "Thanks. I'll check it right now.",
      ],
      answer: 5,
      clue: "Then try the lost and found box by the office.",
      explanation: "여자가 행정실 옆 분실물 상자를 알려 주었으므로, 고맙다며 지금 가 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "M: 혜린아, 체육복을 아무 데서도 못 찾겠어.",
        "W: 복도 사물함은 확인했어?",
        "M: 응, 학교 가방도 두 번 봤어.",
        "W: 점심 먹고 교실에 두고 온 거 아니야?",
        "M: 거기 책상 밑도 다 봤어.",
        "W: 체육관 앞 벤치는?",
        "M: 확인했어. 수업이 10분 뒤에 시작해.",
        "W: 그럼 행정실 옆 분실물 상자를 가 봐.",
        "M: 고마워. 지금 바로 가 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, you look really tired today. Are you okay?"],
        ["M", "I couldn't sleep well. I was nervous about the speech."],
        ["W", "Is the speech contest today? You practiced a lot."],
        ["M", "Yes, it's right after lunch, but my hands still shake."],
        ["W", "That happens to everyone. Try holding your card with both hands."],
        ["M", "Does that really help when you stand on the stage?"],
        ["W", "It helped me a lot at the contest last year."],
        ["M", "Then I'll try it. I hope I don't forget my lines."],
        ["W", "You won't. Shall I listen to you practice once?"]
      ],
      choices: [
        "No, the speech was yesterday.",
        "I forgot to write my card.",
        "Yes, please. That would help me a lot.",
        "You should sleep more tonight.",
        "Let's go to the library instead.",
      ],
      answer: 3,
      clue: "You won't. Shall I listen to you practice once?",
      explanation: "여자가 한 번 들어 줄까 하고 물었으므로, 그래 달라며 도움이 되겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 오늘 많이 피곤해 보인다. 괜찮아?",
        "M: 잠을 잘 못 잤어. 발표 때문에 긴장돼서.",
        "W: 말하기 대회가 오늘이야? 연습 많이 했잖아.",
        "M: 응, 점심 바로 뒤야. 그래도 손이 아직 떨려.",
        "W: 다들 그래. 카드를 두 손으로 잡아 봐.",
        "M: 무대에 서면 그게 정말 도움이 돼?",
        "W: 작년 대회 때 나한테 큰 도움이 됐어.",
        "M: 그럼 해 볼게. 대사를 잊지 않으면 좋겠다.",
        "W: 안 잊을 거야. 내가 연습 한 번 들어 줄까?",
        "M: 응, 그래 줘. 큰 도움이 될 거야.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yuna가 Doyun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yuna : ________________",
      lines: [
        [
          "W",
          "Yuna and Doyun are cleaning the classroom after school. " +
            "Yuna is wiping the windows, and Doyun is sweeping the floor. " +
            "Yuna finds that the window is too high for her to reach. " +
            "Doyun is taller than Yuna and has finished sweeping. " +
            "Yuna wants Doyun to wipe the top part of the window. " +
            "In this situation, what would Yuna most likely say to Doyun?",
        ],
      ],
      choices: [
        "Can you wipe the top of the window?",
        "Let's go home before the bell rings.",
        "I already swept the whole floor.",
        "Please close the classroom door.",
        "Your broom is much cleaner than mine.",
      ],
      answer: 1,
      clue: "Yuna wants Doyun to wipe the top part of the window.",
      explanation:
        "유나는 창문 윗부분에 손이 닿지 않고 도윤이는 키가 크고 비질을 끝냈으므로, 창문 위를 닦아 달라고 부탁하는 ①이 가장 적절하다.",
      translation: [
        "W: 유나와 도윤이는 방과 후에 교실을 청소하고 있습니다. 유나는 창문을 닦고 도윤이는 바닥을 쓸고 있습니다. 유나는 창문이 너무 높아 손이 닿지 않는다는 것을 알게 됩니다. 도윤이는 유나보다 키가 크고 비질을 다 끝냈습니다. 유나는 도윤이가 창문 윗부분을 닦아 주기를 바랍니다. 이런 상황에서 유나가 도윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
