/** 중1 듣기 16회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 16회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 시계를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for an alarm clock?"],
        ["M", "Yes, one for my desk. My phone alarm doesn't wake me."],
        ["W", "We have round ones and square ones."],
        ["M", "A square one, please. It won't roll off my desk."],
        ["W", "All right. Do you want two bells on the top?"],
        ["M", "Yes, the bells. They're much louder."],
        ["W", "Then two are left. One has stars on it and one has no pattern."],
        ["M", "I'll take the one with stars. My room is a bit plain."],
        ["W", "Good choice. This one glows in the dark too."],
        ["M", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'll take the one with stars. My room is a bit plain.",
      explanation:
        "남자는 네모난 모양에 종이 두 개 달리고 별무늬가 있는 시계를 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five alarm clocks shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no numbers or writing anywhere on the faces. " +
          "First: a ROUND alarm clock with NO bells on top, plain case with no pattern. " +
          "Second: a ROUND alarm clock with TWO BELLS on top, covered in small star shapes. " +
          "Third: a SQUARE alarm clock with NO bells on top, covered in small star shapes. " +
          "Fourth: a SQUARE alarm clock with TWO BELLS on top, covered in small star shapes. " +
          "Fifth: a SQUARE alarm clock with TWO BELLS on top, plain case with no pattern at all.",
      },
      translation: [
        "W: 안녕하세요. 알람 시계 찾으세요?",
        "M: 네, 책상에 놓을 거예요. 휴대전화 알람으로는 안 깨서요.",
        "W: 둥근 것과 네모난 것이 있어요.",
        "M: 네모난 걸로요. 책상에서 굴러떨어지지 않게요.",
        "W: 알겠습니다. 위에 종이 두 개 달린 걸로 하시겠어요?",
        "M: 네, 종이요. 훨씬 크게 울려요.",
        "W: 그럼 두 개 남았네요. 하나는 별무늬가 있고 하나는 무늬가 없습니다.",
        "M: 별무늬로 할게요. 제 방이 좀 밋밋해서요.",
        "W: 좋은 선택이세요. 이건 어두운 데서 빛나기도 합니다.",
        "M: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 텃밭 활동에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Sumin, are you joining the school garden club?"],
        ["W", "I want to, but I don't know much yet."],
        ["M", "They meet every Wednesday after lunch."],
        ["W", "Where is the garden?"],
        ["M", "Behind the gym, next to the parking area."],
        ["W", "What do they grow there?"],
        ["M", "Tomatoes, lettuce, and some flowers."],
        ["W", "Do we need anything?"],
        ["M", "Just gloves. The school gives you the tools."],
        ["W", "Then I'll bring mine tomorrow."],
      ],
      choices: ["모이는 요일", "장소", "기르는 것", "준비물", "회원 수"],
      answer: 5,
      clue: "Just gloves. The school gives you the tools.",
      explanation:
        "모이는 요일(수요일), 장소(체육관 뒤), 기르는 것(토마토·상추·꽃), 준비물(장갑)은 언급되지만 회원 수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 수민아, 학교 텃밭 동아리 들어올 거야?",
        "W: 들어가고 싶은데 아직 잘 몰라.",
        "M: 수요일마다 점심 먹고 모여.",
        "W: 텃밭이 어디 있는데?",
        "M: 체육관 뒤, 주차장 옆에.",
        "W: 거기서 뭘 길러?",
        "M: 토마토, 상추, 그리고 꽃도 조금.",
        "W: 뭐 필요한 거 있어?",
        "M: 장갑만. 도구는 학교에서 줘.",
        "W: 그럼 내일 내 장갑 가져올게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sora. It's Junho. Are you busy?"],
        ["W", "Not really. What's up?"],
        ["M", "We're meeting at the park at two tomorrow, right?"],
        ["W", "That's what we said."],
        ["M", "My cousin is coming at two, so can we make it three?"],
        ["W", "Three is fine for me."],
        ["M", "Thank you. I'll see you at three, then."],
        ["W", "All right. See you tomorrow."],
      ],
      choices: [
        "만나는 시간을 미루려고",
        "숙제를 물어보려고",
        "생일에 초대하려고",
        "길을 물어보려고",
        "책을 빌리려고",
      ],
      answer: 1,
      clue: "My cousin is coming at two, so can we make it three?",
      explanation:
        "남자는 사촌이 2시에 와서 약속을 3시로 미루려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 소라야. 준호야. 바빠?",
        "W: 아니. 무슨 일이야?",
        "M: 내일 2시에 공원에서 만나기로 했지?",
        "W: 그렇게 말했지.",
        "M: 사촌이 2시에 오는데 3시로 할 수 있을까?",
        "W: 3시도 괜찮아.",
        "M: 고마워. 그럼 3시에 보자.",
        "W: 그래. 내일 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yerin, what time should we meet at the bookstore?"],
        ["W", "It closes at eight, doesn't it?"],
        ["M", "Yes, and we need at least an hour there."],
        ["W", "How about five o'clock?"],
        ["M", "I have soccer practice until five thirty."],
        ["W", "Oh, I forgot. How long does it take you to get there?"],
        ["M", "Fifteen minutes by bus."],
        ["W", "Then let's meet at six o'clock."],
        ["M", "Six is fine. See you in front of the door."],
      ],
      choices: ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
      answer: 3,
      clue: "Then let's meet at six o'clock.",
      explanation:
        "남자의 축구 연습이 5시 30분에 끝나고 버스로 15분이 걸리므로 두 사람은 6시에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 예린아, 서점에서 몇 시에 만날까?",
        "W: 8시에 닫지?",
        "M: 응, 그리고 적어도 한 시간은 있어야 해.",
        "W: 5시는 어때?",
        "M: 5시 30분까지 축구 연습이 있어.",
        "W: 아, 깜빡했다. 거기까지 얼마나 걸려?",
        "M: 버스로 15분.",
        "W: 그럼 6시에 만나자.",
        "M: 6시 좋아. 문 앞에서 보자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, you keep looking out of the window."],
        ["W", "My dad is coming home from Busan tonight."],
        ["M", "How long has he been away?"],
        ["W", "Three months. He works there during the week."],
        ["M", "Three months is a long time."],
        ["W", "He's bringing my favorite bread from the bakery there."],
        ["M", "You must be counting the hours."],
        ["W", "I made a welcome card this morning before school."],
      ],
      choices: ["excited", "sad", "angry", "bored", "worried"],
      answer: 1,
      clue: "I made a welcome card this morning before school.",
      explanation:
        "석 달 만에 아버지가 돌아오는 날이라 아침에 환영 카드까지 만들었으므로 여자는 들떠 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 나리야, 계속 창밖을 보네.",
        "W: 오늘 밤에 아빠가 부산에서 오셔.",
        "M: 얼마나 안 계셨는데?",
        "W: 석 달. 주중에는 거기서 일하셔.",
        "M: 석 달이면 길다.",
        "W: 거기 빵집에서 내가 제일 좋아하는 빵을 사 오신대.",
        "M: 시간을 세고 있겠다.",
        "W: 오늘 아침에 학교 오기 전에 환영 카드를 만들었어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, is the library open today?"],
        ["M", "Yes, until six o'clock."],
        ["W", "May I take your order?"],
        ["M", "Yes, one orange juice, please."],
        ["W", "Do you need help crossing the street?"],
        ["M", "Yes, thank you very much."],
        ["W", "How much is this notebook?"],
        ["M", "It's three dollars."],
        ["W", "Where is the bus stop?"],
        ["M", "Just around the corner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Do you need help crossing the street?",
      explanation:
        "그림은 횡단보도 앞에서 학생이 지팡이를 짚은 할아버지에게 팔을 내밀어 건너는 것을 돕는 장면이므로 ③이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "At a crosswalk on a city street. An elderly man with a walking stick is standing at the edge of the pavement, looking across the road. A student beside him is holding out an arm to help him cross. Both are drawn clearly. A traffic light and the white stripes of the crossing are in the background.",
      },
      translation: [
        "① W: 실례지만 오늘 도서관 문 열었나요? / M: 네, 6시까지요.",
        "② W: 주문하시겠어요? / M: 네, 오렌지 주스 하나 주세요.",
        "③ W: 길 건너는 것 도와드릴까요? / M: 네, 정말 고맙습니다.",
        "④ W: 이 공책 얼마예요? / M: 3달러입니다.",
        "⑤ W: 버스 정류장이 어디예요? / M: 모퉁이 돌면 바로예요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dayeon, are you going to the music room after school?"],
        ["W", "Yes, our club practices there on Thursdays."],
        ["M", "That's good. I left my recorder there yesterday."],
        ["W", "Where did you leave it?"],
        ["M", "In the second drawer of the teacher's desk."],
        ["W", "I can look there."],
        ["M", "Could you bring it to my classroom after practice?"],
        ["W", "Sure. I'll drop it off on my way home."],
        ["M", "Thank you so much."],
      ],
      choices: ["숙제 도와주기", "리코더 가져다주기", "음악실 청소하기", "우산 빌려주기", "자리 맡아 주기"],
      answer: 2,
      clue: "Could you bring it to my classroom after practice?",
      explanation:
        "남자는 음악실에 두고 온 리코더를 교실로 가져다 달라고 부탁한다. 따라서 답은 ②이다.",
      translation: [
        "M: 다연아, 방과 후에 음악실 가?",
        "W: 응, 우리 동아리가 목요일마다 거기서 연습해.",
        "M: 잘됐다. 어제 거기에 리코더를 두고 왔어.",
        "W: 어디에 뒀는데?",
        "M: 교탁 두 번째 서랍에.",
        "W: 거기 볼 수 있어.",
        "M: 연습 끝나고 우리 교실로 가져다줄 수 있어?",
        "W: 그래. 집에 가는 길에 갖다 놓을게.",
        "M: 정말 고마워.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Reading Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Let me tell you about Reading Day."],
        ["W", "It will be held next Wednesday, all afternoon."],
        ["W", "We will read in the library instead of our classrooms."],
        ["W", "Bring one book you want to read from home."],
        ["W", "At the end, each class will choose one favorite book."],
        ["W", "We hope you find a book you love."],
      ],
      choices: ["열리는 날", "장소", "준비물", "마지막에 하는 일", "참가 학년"],
      answer: 5,
      clue: "At the end, each class will choose one favorite book.",
      explanation:
        "날짜(다음 주 수요일), 장소(도서관), 준비물(읽을 책 한 권), 마지막에 하는 일(반마다 좋아하는 책 한 권 고르기)은 언급되지만 참가 학년은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. Reading Day를 안내합니다.",
        "W: 다음 주 수요일 오후 내내 열립니다.",
        "W: 교실이 아니라 도서관에서 읽습니다.",
        "W: 집에서 읽고 싶은 책 한 권을 가져오세요.",
        "W: 끝날 때 반마다 가장 좋았던 책 한 권을 고릅니다.",
        "W: 마음에 드는 책을 찾기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You use this almost every day at school."],
        ["M", "It is long and thin, and one end is sharp."],
        ["M", "You hold it in your hand to write or draw."],
        ["M", "When the end becomes dull, you have to sharpen it."],
        ["M", "Some of them have a small eraser on the other end."],
      ],
      choices: ["연필", "자", "가위", "붓", "칼"],
      answer: 1,
      clue: "When the end becomes dull, you have to sharpen it.",
      explanation:
        "길고 가늘며 한쪽 끝이 뾰족하고 무뎌지면 깎아야 하고 반대쪽에 지우개가 달린 것도 있다고 했으므로 연필이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 학교에서 거의 매일 씁니다.",
        "M: 길고 가늘며 한쪽 끝이 뾰족합니다.",
        "M: 손에 쥐고 쓰거나 그립니다.",
        "M: 끝이 무뎌지면 깎아야 합니다.",
        "M: 반대쪽 끝에 작은 지우개가 달린 것도 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "What's your favorite season?"],
        ["M", "I like autumn the best."],
        ["W", "Can you close the window?"],
        ["M", "Sure, it's cold today."],
        ["W", "How many brothers do you have?"],
        ["M", "I usually go there by bike."],
        ["W", "Did you enjoy the concert?"],
        ["M", "Yes, it was wonderful."],
        ["W", "Are you free this Saturday?"],
        ["M", "Yes, I have no plans."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How many brothers do you have?",
      explanation:
        "형제가 몇 명인지 묻는 말에 자전거로 간다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① W: 제일 좋아하는 계절이 뭐야? / M: 가을이 제일 좋아.",
        "② W: 창문 좀 닫아 줄래? / M: 그래, 오늘 춥네.",
        "③ W: 형제가 몇 명이야? / M: 나는 보통 자전거로 거기 가.",
        "④ W: 그 공연 재미있었어? / M: 응, 정말 좋았어.",
        "⑤ W: 이번 토요일에 시간 있어? / M: 응, 계획 없어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjae, the class party starts in ten minutes."],
        ["M", "Is everything ready? What should I do?"],
        ["W", "I've moved the desks and put up the balloons."],
        ["M", "Should I bring the juice from the office?"],
        ["W", "Seoyul is carrying it up right now."],
        ["M", "Then what is left?"],
        ["W", "Nobody has brought the paper cups from our locker."],
        ["M", "I'll go and get them now."],
        ["W", "Thanks. I'll write the names on the board."],
      ],
      choices: ["책상 옮기기", "풍선 달기", "주스 가져오기", "종이컵 가져오기", "칠판에 이름 쓰기"],
      answer: 4,
      clue: "I'll go and get them now.",
      explanation:
        "책상과 풍선, 주스는 이미 해결되었으므로 남자는 사물함에서 종이컵을 가져온다. 따라서 답은 ④이다.",
      translation: [
        "W: 민재야, 학급 파티가 10분 뒤에 시작해.",
        "M: 다 준비됐어? 내가 뭘 할까?",
        "W: 책상은 옮겼고 풍선도 달았어.",
        "M: 행정실에서 주스를 가져올까?",
        "W: 서율이가 지금 들고 올라오고 있어.",
        "M: 그럼 뭐가 남았어?",
        "W: 사물함에 있는 종이컵을 아무도 안 가져왔어.",
        "M: 내가 지금 가서 가져올게.",
        "W: 고마워. 나는 칠판에 이름을 쓸게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 물통을 고르시오.",
      lines: [
        ["M", "Hayun, are these the water bottles you were looking at?"],
        ["W", "Yes, these five. I need one for the school trip."],
        ["M", "How much can you spend?"],
        ["W", "Fifteen dollars at the most."],
        ["M", "All right, that takes out one of them."],
        ["W", "And it has to hold at least eight hundred milliliters."],
        ["M", "Then one more is gone. Three are left."],
        ["W", "I want a shoulder strap. My hands will be full."],
        ["M", "One has no strap, so not that one."],
        ["W", "Two left. Are they both light?"],
        ["M", "One is four hundred grams, the other is three hundred."],
        ["W", "Then the lighter one, please."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Then the lighter one, please.",
      explanation:
        "18달러인 ②, 600밀리리터인 ①, 끈이 없는 ③을 뺀다. 남은 ④와 ⑤ 중 더 가벼운 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "600ml / $10 / 끈 있음 / 300g" },
          { no: 2, label: "②", value: "1,000ml / $18 / 끈 있음 / 350g" },
          { no: 3, label: "③", value: "800ml / $12 / 끈 없음 / 300g" },
          { no: 4, label: "④", value: "800ml / $14 / 끈 있음 / 400g" },
          { no: 5, label: "⑤", value: "900ml / $15 / 끈 있음 / 300g" },
        ],
      },
      translation: [
        "M: 하윤아, 네가 보던 물통이 이거야?",
        "W: 응, 이 다섯 개. 수학여행에 쓸 게 필요해.",
        "M: 얼마까지 쓸 수 있어?",
        "W: 많아야 15달러.",
        "M: 그럼 하나가 빠지네.",
        "W: 그리고 적어도 800밀리리터는 돼야 해.",
        "M: 그럼 하나 더 빠진다. 세 개 남았어.",
        "W: 어깨끈이 있으면 좋겠어. 손이 꽉 찰 거라서.",
        "M: 하나는 끈이 없으니 그건 빼고.",
        "W: 둘 남았다. 둘 다 가벼워?",
        "M: 하나는 400그램, 다른 하나는 300그램이야.",
        "W: 그럼 가벼운 걸로 할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 동물원에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Suji, when should we go to the zoo?"],
        ["W", "Students get in free on the twelfth, thirteenth, and fourteenth."],
        ["M", "Only those three days? Then we should decide now."],
        ["W", "I want to see the new baby elephant before it gets cold."],
        ["M", "Me too. But I have a family dinner on the twelfth."],
        ["W", "Then it's the thirteenth or the fourteenth."],
        ["M", "Wait. Isn't the fourteenth the day of the math test?"],
        ["W", "You're right, I forgot. We'd be too tired after that."],
        ["M", "So only the thirteenth is left."],
        ["W", "Then let's go on the thirteenth, right after school."],
      ],
      choices: ["11일", "12일", "13일", "14일", "15일"],
      answer: 3,
      clue: "So only the thirteenth is left.",
      explanation:
        "12일은 가족 저녁 식사, 14일은 수학 시험이어서 13일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 수지야, 동물원에 언제 갈까?",
        "W: 12일, 13일, 14일에 학생은 무료로 들어갈 수 있대.",
        "M: 사흘뿐이야? 그럼 지금 정하자.",
        "W: 추워지기 전에 새로 태어난 아기 코끼리를 보고 싶어.",
        "M: 나도. 그런데 12일에 가족 저녁 식사가 있어.",
        "W: 그럼 13일이나 14일이네.",
        "M: 잠깐. 14일은 수학 시험 날 아니야?",
        "W: 맞다, 잊었네. 그러고 나면 너무 피곤하겠다.",
        "M: 그럼 13일만 남네.",
        "W: 그럼 13일에 가자, 학교 끝나고 바로.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyeon, did you go to the beach last weekend?"],
        ["W", "No, I painted my room with my mom on Sunday."],
        ["M", "You painted it yourself? What color?"],
        ["W", "Light green. It took us almost five hours."],
        ["M", "Five hours! Were your arms sore?"],
        ["W", "Very. But the room looks completely new."],
        ["M", "I'd like to see it sometime."],
        ["W", "Come over next week. The smell will be gone by then."],
      ],
      choices: ["바다에 가기", "방 페인트칠하기", "영화 보기", "자전거 타기", "책 읽기"],
      answer: 2,
      clue: "No, I painted my room with my mom on Sunday.",
      explanation:
        "여자는 지난 일요일에 어머니와 방을 페인트칠했다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "M: 채연아, 지난 주말에 바다 갔어?",
        "W: 아니, 일요일에 엄마랑 내 방을 페인트칠했어.",
        "M: 직접 칠했어? 무슨 색으로?",
        "W: 연한 초록색. 거의 다섯 시간 걸렸어.",
        "M: 다섯 시간이나! 팔 아팠겠다.",
        "W: 엄청. 그래도 방이 완전히 새것 같아.",
        "M: 나중에 보고 싶다.",
        "W: 다음 주에 와. 그때면 냄새도 다 빠질 거야.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "We have one notice for you this morning."],
        ["M", "The school bus will leave ten minutes earlier tomorrow."],
        ["M", "There is road work in front of the market."],
        ["M", "So the bus needs more time to reach the school."],
        ["M", "Please be at your bus stop by seven thirty tomorrow."],
        ["M", "This is only for tomorrow. Thank you."],
      ],
      choices: [
        "도로 공사 봉사자를 모집하려고",
        "버스 요금이 오른 것을 알리려고",
        "등교 시간이 바뀐 것을 알리려고",
        "통학 버스가 일찍 출발한다고 알리려고",
        "버스 이용 예절을 당부하려고",
      ],
      answer: 4,
      clue: "The school bus will leave ten minutes earlier tomorrow.",
      explanation:
        "도로 공사 때문에 내일 통학 버스가 10분 일찍 떠난다고 알리는 방송이다. 따라서 방송의 목적은 ④이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 오늘 아침에 알려 드릴 것이 하나 있습니다.",
        "M: 내일은 통학 버스가 10분 일찍 출발합니다.",
        "M: 시장 앞에 도로 공사가 있습니다.",
        "M: 그래서 버스가 학교까지 오는 데 시간이 더 걸립니다.",
        "M: 내일은 7시 30분까지 정류장에 나와 주세요.",
        "M: 내일 하루만 그렇습니다. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What can I get for you?"],
        ["M", "Two hamburgers and one milk, please."],
        ["W", "Hamburgers are six dollars each."],
        ["M", "And the milk?"],
        ["W", "Milk is two dollars."],
        ["M", "So twelve dollars and two dollars."],
        ["W", "That's right. Do you have a student card?"],
        ["M", "Yes, here it is."],
        ["W", "Then I can take two dollars off."],
        ["M", "Great. Here's my card."],
      ],
      choices: ["$10", "$12", "$14", "$16", "$18"],
      answer: 2,
      clue: "Then I can take two dollars off.",
      explanation:
        "햄버거 6달러짜리 두 개는 12달러, 우유 2달러를 더하면 14달러이다. 학생 할인 2달러를 빼면 12달러이므로 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 뭘 드릴까요?",
        "M: 햄버거 두 개랑 우유 하나 주세요.",
        "W: 햄버거는 하나에 6달러입니다.",
        "M: 우유는요?",
        "W: 우유는 2달러입니다.",
        "M: 그럼 12달러랑 2달러네요.",
        "W: 맞습니다. 학생증 있으세요?",
        "M: 네, 여기요.",
        "W: 그럼 2달러 빼 드릴게요.",
        "M: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Seoyeon, your English writing is getting better."],
        ["W", "Thanks, but the teacher says my sentences are too long."],
        ["M", "How long are they?"],
        ["W", "Some of them are four lines with three 'and's."],
        ["M", "Why do you write them that way?"],
        ["W", "I'm afraid short sentences look too simple."],
        ["M", "Short sentences are easier to read, though."],
        ["W", "Do you really think so?"],
        ["M", "Try cutting each long one into two short ones."],
      ],
      choices: [
        "My essay is about my summer.",
        "I write two pages every week.",
        "English grammar is hard for me.",
        "Then I'll try that in tonight's homework.",
        "You should write longer sentences.",
      ],
      answer: 4,
      clue: "Try cutting each long one into two short ones.",
      explanation:
        "긴 문장을 두 개의 짧은 문장으로 나눠 보라는 조언을 들었으므로, 오늘 숙제에 해 보겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 서연아, 영어 글쓰기가 점점 좋아지네.",
        "W: 고마워, 그런데 선생님이 문장이 너무 길대.",
        "M: 얼마나 긴데?",
        "W: 어떤 건 'and'가 세 번 들어간 네 줄짜리야.",
        "M: 왜 그렇게 써?",
        "W: 짧은 문장은 너무 단순해 보일까 봐.",
        "M: 그래도 짧은 문장이 읽기 쉬워.",
        "W: 정말 그렇게 생각해?",
        "M: 긴 문장을 두 개의 짧은 문장으로 잘라 봐.",
        "W: 그럼 오늘 숙제에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Taemin, you're late for class again."],
        ["M", "I know. I always run from the bus stop."],
        ["W", "How many times has it been this week?"],
        ["M", "Three, and it's only Thursday."],
        ["W", "What time does your bus arrive?"],
        ["M", "Eight twenty-five, and class starts at eight thirty."],
        ["W", "That's only five minutes to get inside."],
        ["M", "And my classroom is on the fourth floor."],
        ["W", "The stairs alone take three minutes. Is there an earlier bus?"],
        ["M", "There's one at eight ten, but I'd have to leave home earlier."],
        ["W", "Fifteen minutes would be much easier than five."],
      ],
      choices: [
        "My bus stop is near my house.",
        "The class ends at nine twenty.",
        "I run quite fast, actually.",
        "You should move to the first floor.",
        "Then I'll take the eight-ten bus tomorrow.",
      ],
      answer: 5,
      clue: "Fifteen minutes would be much easier than five.",
      explanation:
        "15분이 훨씬 낫다는 말을 들었으므로, 내일은 8시 10분 버스를 타겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 태민아, 또 수업에 늦었네.",
        "M: 알아. 늘 정류장에서 뛰어와.",
        "W: 이번 주에 몇 번째야?",
        "M: 세 번, 아직 목요일인데.",
        "W: 버스가 몇 시에 도착하는데?",
        "M: 8시 25분, 수업은 8시 30분에 시작하고.",
        "W: 들어오는 데 5분밖에 없잖아.",
        "M: 게다가 우리 교실은 4층이야.",
        "W: 계단만 3분이겠다. 더 이른 버스는 없어?",
        "M: 8시 10분 버스가 있는데 집에서 더 일찍 나와야 해.",
        "W: 5분보다는 15분이 훨씬 수월하지.",
        "M: 그럼 내일은 8시 10분 버스를 탈게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Jiwon, you look tired after every gym class."],
        ["W", "I know. I can't keep running for ten minutes."],
        ["M", "How do you start the run?"],
        ["W", "I go as fast as I can from the first whistle."],
        ["M", "All the way from the start?"],
        ["W", "Yes, and after two minutes I have to walk."],
        ["M", "That's why you can't finish."],
        ["W", "So what should I do?"],
        ["M", "Start slowly and keep the same speed to the end."],
      ],
      choices: [
        "Then I'll start slowly next time.",
        "Gym class is on Tuesdays.",
        "I run about one kilometer.",
        "I don't like running at all.",
        "You should run with me.",
      ],
      answer: 1,
      clue: "Start slowly and keep the same speed to the end.",
      explanation:
        "천천히 출발해서 같은 속도로 끝까지 가라는 조언을 들었으므로, 다음에 그렇게 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 지원아, 체육 시간 끝나면 늘 피곤해 보여.",
        "W: 그러게. 10분을 계속 뛰지를 못해.",
        "M: 처음에 어떻게 시작하는데?",
        "W: 첫 호루라기부터 최대한 빨리 뛰어.",
        "M: 처음부터 그렇게?",
        "W: 응, 그러고 2분 지나면 걸어야 해.",
        "M: 그래서 끝까지 못 가는 거야.",
        "W: 그럼 어떻게 해야 해?",
        "M: 천천히 출발해서 끝까지 같은 속도로 가 봐.",
        "W: 그럼 다음에는 천천히 시작할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Junseo가 Hayeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Junseo : ________________",
      lines: [
        ["W", "Junseo and Hayeon are in the same class."],
        ["W", "They are making a poster about their school trip together."],
        ["W", "Hayeon has chosen very nice photos for it."],
        ["W", "But she has put all of them on the left side."],
        ["W", "The right side of the poster is completely empty."],
        ["W", "It will be put on the wall next to the door."],
        ["W", "Junseo does not want to say that her photos are bad."],
        ["W", "He wants to ask her to move some photos to the right side."],
        ["W", "In this situation, what would Junseo most likely say to Hayeon?"],
      ],
      choices: [
        "Let's use different photos instead.",
        "Could you move a few photos to the right side?",
        "I'll finish the poster by myself.",
        "We should write more about the trip.",
        "Your photos are too small to see.",
      ],
      answer: 2,
      clue: "He wants to ask her to move some photos to the right side.",
      explanation:
        "준서는 하연이의 사진 선택을 깎아내리지 않으면서, 사진 몇 장을 오른쪽으로 옮겨 달라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 준서와 하연은 같은 반입니다.",
        "W: 두 사람은 수학여행에 관한 포스터를 함께 만들고 있습니다.",
        "W: 하연이 아주 좋은 사진들을 골랐습니다.",
        "W: 그런데 사진을 전부 왼쪽에만 붙였습니다.",
        "W: 포스터 오른쪽은 완전히 비어 있습니다.",
        "W: 이 포스터는 문 옆 벽에 붙을 것입니다.",
        "W: 준서는 하연의 사진이 나쁘다고 말하고 싶지는 않습니다.",
        "W: 다만 사진 몇 장을 오른쪽으로 옮겨 달라고 부탁하고 싶습니다.",
        "W: 이런 상황에서 준서가 하연에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
