/** 중1 듣기 51회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 51회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 만들 초대 카드를 고르시오.",
      lines: [
        ["M", "Sora, are you making the invitation cards now?"],
        ["W", "Yes, I'm deciding on the shape first."],
        ["M", "A heart shape would look sweet for a party."],
        ["W", "I chose a plain rectangle. It's easier to write on."],
        ["M", "Will you draw balloons along the edge?"],
        ["W", "No balloons. I'm drawing a big star in the middle."],
        ["M", "Are you adding a ribbon at the corner too?"],
        ["W", "Yes, one small ribbon on the top corner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I chose a plain rectangle. It's easier to write on. / Yes, one small ribbon on the top corner.",
      explanation:
        "여자는 직사각형 카드에 가운데 큰 별과 모서리 리본 하나를 넣기로 했다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five invitation cards side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a HEART-shaped card with a big STAR drawn in the middle. " +
          "② a RECTANGULAR card with BALLOONS drawn along the edge. " +
          "③ a HEART-shaped card with a small RIBBON at the top corner. " +
          "④ a RECTANGULAR card with a big STAR in the middle and BALLOONS along the edge. " +
          "⑤ a RECTANGULAR card with a big STAR in the middle and one small RIBBON at the top corner, no balloons.",
      },
      translation: [
        "M: 소라야, 지금 초대 카드 만들어?",
        "W: 응, 먼저 모양을 정하는 중이야.",
        "M: 파티니까 하트 모양이 예쁘겠다.",
        "W: 나는 그냥 직사각형으로 골랐어. 글씨 쓰기 편해서.",
        "M: 가장자리에 풍선도 그릴 거야?",
        "W: 풍선은 안 그려. 가운데에 큰 별을 그릴 거야.",
        "M: 모서리에 리본도 붙여?",
        "W: 응, 위쪽 모서리에 작은 리본 하나.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 여름 방학 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Suyeon, are you going to the summer camp?"],
        ["W", "I want to. Where is it this year?"],
        ["M", "At a forest center near Gangneung."],
        ["W", "How long does the camp last?"],
        ["M", "Three days and two nights in early August."],
        ["W", "What do they do all day?"],
        ["M", "Hiking, cooking and star watching at night."],
        ["W", "How much does it cost?"],
        ["M", "Eighty thousand won, meals included."],
      ],
      choices: ["장소", "기간", "활동", "비용", "인솔 교사"],
      answer: 5,
      clue: "At a forest center near Gangneung.",
      explanation:
        "장소, 기간, 활동, 비용은 말했지만 인솔 교사는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 수연아, 여름 캠프 갈 거야?",
        "W: 가고 싶어. 올해는 어디서 해?",
        "M: 강릉 근처 숲 체험 센터에서.",
        "W: 며칠 동안 해?",
        "M: 8월 초에 2박 3일.",
        "W: 하루 종일 뭘 해?",
        "M: 등산, 요리, 그리고 밤에는 별 보기.",
        "W: 비용은 얼마야?",
        "M: 8만 원이고 식사 포함이야.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Come in. You're from class three, right?"],
        ["W", "Yes, I'm Jiwoo. Do you have a minute?"],
        ["M", "Of course. Is it about the art room?"],
        ["W", "It's about the drawing supplies in the cabinet."],
        ["M", "We keep the brushes and paints in there."],
        ["W", "Our club wants to use them on Wednesday."],
        ["M", "The cabinet is locked after school, though."],
        ["W", "That's why I came to see you."],
        ["M", "So you need the key for Wednesday."],
        ["W", "I came to ask you to lend us the key."],
      ],
      choices: [
        "숙제를 물어보려고",
        "열쇠를 빌리려고",
        "결석을 알리려고",
        "상담을 신청하려고",
        "물건을 돌려주려고",
      ],
      answer: 2,
      clue: "I came to ask you to lend us the key.",
      explanation:
        "여자는 미술 재료함 열쇠를 빌리러 왔다. 따라서 답은 ②이다.",
      translation: [
        "M: 들어와. 3반 학생이지?",
        "W: 네, 지우예요. 잠깐 시간 되세요?",
        "M: 그럼. 미술실 일이니?",
        "W: 보관함에 있는 그림 재료 때문에요.",
        "M: 거기에 붓이랑 물감을 둬.",
        "W: 저희 동아리가 수요일에 쓰고 싶어요.",
        "M: 그런데 방과 후에는 보관함을 잠가 둬.",
        "W: 그래서 선생님을 찾아왔어요.",
        "M: 수요일에 쓸 열쇠가 필요하구나.",
        "W: 열쇠를 빌려주십사 부탁드리러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["W", "Dohyun, what time does the movie start today?"],
        ["M", "The show begins at four o'clock this afternoon."],
        ["W", "Should we just meet right at four then?"],
        ["M", "We need time to pick up the tickets first."],
        ["W", "Can't we print them from the machine quickly?"],
        ["M", "The line at that machine is long on weekends."],
        ["W", "How long does picking up the tickets usually take?"],
        ["M", "About thirty minutes on a busy Saturday afternoon."],
        ["W", "Then let's meet at three thirty in front of the theater."],
        ["M", "Three thirty works for me without any problem."],
        ["W", "I'll be there a little before you arrive."],
        ["M", "Call me if your bus is late again."],
      ],
      choices: ["2:30 p.m.", "3:00 p.m.", "3:15 p.m.", "3:30 p.m.", "4:00 p.m."],
      answer: 4,
      clue: "Then let's meet at three thirty in front of the theater.",
      explanation:
        "4시 영화를 위해 표 찾는 30분을 감안해 3시 30분에 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 도현아, 오늘 영화 몇 시에 시작해?",
        "M: 상영은 오늘 오후 4시에 시작해.",
        "W: 그럼 그냥 4시에 만날까?",
        "M: 표 찾을 시간이 먼저 필요해.",
        "W: 기계에서 빨리 뽑으면 안 돼?",
        "M: 주말에는 그 기계 줄이 길어.",
        "W: 표 찾는 데 보통 얼마나 걸려?",
        "M: 바쁜 토요일 오후에는 30분쯤.",
        "W: 그럼 3시 30분에 극장 앞에서 만나자.",
        "M: 3시 30분이면 나도 전혀 문제없어.",
        "W: 네가 오기 조금 전에 가 있을게.",
        "M: 버스가 또 늦으면 전화해.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sihyun, why do you keep checking your bag again?"],
        ["M", "I can't find my grandmother's silver watch anywhere."],
        ["W", "The one you always wear on your left wrist?"],
        ["M", "She gave it to me on my birthday last year."],
        ["W", "When did you last see it on your wrist?"],
        ["M", "Before gym class, I think, in the locker room."],
        ["W", "Did you put it in your shoe or your pocket?"],
        ["M", "I usually leave it on the bench while I change."],
        ["W", "Let's go and look in the locker room together now."],
        ["M", "I hope nobody has taken it away."],
      ],
      choices: ["excited", "worried", "bored", "proud", "angry"],
      answer: 2,
      clue: "I hope nobody has taken it away.",
      explanation:
        "할머니께 받은 시계를 잃어버려 걱정하고 있다. 따라서 답은 ②이다.",
      translation: [
        "W: 시현아, 왜 자꾸 가방을 또 뒤져?",
        "M: 할머니 은색 시계를 어디서도 못 찾겠어.",
        "W: 네가 늘 왼쪽 손목에 차던 그거?",
        "M: 작년 생일에 주신 거야.",
        "W: 손목에 있던 걸 마지막으로 본 게 언제야?",
        "M: 체육 시간 전, 탈의실에서인 것 같아.",
        "W: 신발이나 주머니에 넣어 둔 건 아니야?",
        "M: 옷 갈아입을 때는 보통 의자에 올려 둬.",
        "W: 지금 같이 탈의실에 가 보자.",
        "M: 누가 가져가지 않았으면 좋겠어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you have this in a smaller size?"],
        ["M", "Let me check the back room."],
        ["ANN", "Number two."],
        ["W", "How much is the bus fare?"],
        ["M", "One thousand two hundred won."],
        ["ANN", "Number three."],
        ["W", "Excuse me, you dropped your glove."],
        ["M", "Oh, thank you so much."],
        ["ANN", "Number four."],
        ["W", "Is this seat taken?"],
        ["M", "No, please sit down."],
        ["ANN", "Number five."],
        ["W", "When does the library close?"],
        ["M", "At six on weekdays."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, you dropped your glove.",
      explanation:
        "그림은 앞서 걷던 사람이 떨어뜨린 장갑을 주워 건네는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "On a city sidewalk in winter, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A girl bends slightly and holds out a single fallen GLOVE toward a boy who has stopped and turned back to face her. " +
          "The boy reaches out one hand to take it and wears a thick coat and scarf. " +
          "A bare street tree and a low fence are drawn simply behind them.",
      },
      translation: [
        "① W: 이거 더 작은 치수 있나요? / M: 창고에 확인해 볼게요.",
        "② W: 버스 요금이 얼마예요? / M: 1,200원입니다.",
        "③ W: 저기요, 장갑 떨어뜨리셨어요. / M: 아, 정말 감사합니다.",
        "④ W: 이 자리 주인 있나요? / M: 아니요, 앉으세요.",
        "⑤ W: 도서관 몇 시에 닫아요? / M: 평일에는 여섯 시요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, do you still have your camera?"],
        ["W", "I mean the one you used at the festival."],
        ["M", "Yes, it's in my locker right now."],
        ["W", "Our class is making a short video."],
        ["M", "That sounds like a big project."],
        ["W", "We film during lunch break tomorrow."],
        ["M", "My phone camera isn't as clear as that."],
        ["W", "Could you lend me your camera for a day?"],
        ["M", "Sure, but bring it back by Friday."],
      ],
      choices: [
        "사진을 찍어 주기",
        "카메라를 빌려주기",
        "영상을 편집해 주기",
        "대본을 써 주기",
        "함께 출연해 주기",
      ],
      answer: 2,
      clue: "Could you lend me your camera for a day?",
      explanation:
        "여자는 하루만 카메라를 빌려 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 카메라 아직 있어?",
        "W: 축제 때 쓰던 그거 말이야.",
        "M: 응, 지금 사물함에 있어.",
        "W: 우리 반이 짧은 영상을 만들거든.",
        "M: 큰 작업이겠다.",
        "W: 내일 점심시간에 찍어.",
        "M: 내 휴대폰 카메라는 그만큼 선명하지 않아.",
        "W: 카메라 하루만 빌려줄 수 있어?",
        "M: 그래, 대신 금요일까지 돌려줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 도서관 이용 안내에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Here is the library guide for this term. " +
            "The library opens at nine and closes at six. " +
            "You may borrow three books at one time. " +
            "Each book can be kept for two weeks. " +
            "Food and drinks are not allowed inside the reading room. " +
            "Please keep your voice low for others.",
        ],
      ],
      choices: [
        "여는 시간과 닫는 시간",
        "한 번에 빌릴 수 있는 권수",
        "책을 빌릴 수 있는 기간",
        "열람실에서 금지된 것",
        "책을 잃어버렸을 때",
      ],
      answer: 5,
      clue: "The library opens at nine and closes at six.",
      explanation:
        "시간, 권수, 기간, 금지 사항은 말했지만 책을 잃어버렸을 때는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 이번 학기 도서관 이용 안내입니다. 도서관은 아홉 시에 열고 여섯 시에 닫습니다. 한 번에 세 권까지 빌릴 수 있습니다. 한 권당 2주 동안 볼 수 있습니다. 열람실 안에서는 음식과 음료를 드실 수 없습니다. 다른 사람을 위해 목소리를 낮춰 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This animal lives in water but breathes with lungs. " +
            "It is very large and gray, and it swims in the sea. " +
            "It blows water high into the air from its back. " +
            "People often watch it from boats in the ocean. " +
            "It is the biggest animal on the earth.",
        ],
      ],
      choices: ["상어", "거북", "펭귄", "고래", "물개"],
      answer: 4,
      clue: "It is the biggest animal on the earth.",
      explanation:
        "바다에 살며 물을 뿜고 지구에서 가장 큰 동물은 고래이다. 따라서 답은 ④이다.",
      translation: [
        "M: 이 동물은 물에 살지만 폐로 숨을 쉽니다. 매우 크고 회색이며 바다에서 헤엄칩니다. 등에서 물을 공중으로 높이 뿜습니다. 사람들은 바다에서 배를 타고 이 동물을 자주 봅니다. 지구에서 가장 큰 동물입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Where did you buy that cap?"],
        ["W", "At the shop near the station."],
        ["ANN", "Number two."],
        ["M", "Can I borrow your eraser?"],
        ["W", "Here you are."],
        ["ANN", "Number three."],
        ["M", "How was the test today?"],
        ["W", "My favorite color is blue."],
        ["ANN", "Number four."],
        ["M", "Are you free this Saturday?"],
        ["W", "Sorry, I have a piano lesson."],
        ["ANN", "Number five."],
        ["M", "What's wrong with your arm?"],
        ["W", "I hurt it playing basketball."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How was the test today?",
      explanation:
        "시험이 어땠는지 묻는 말에 좋아하는 색을 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 그 모자 어디서 샀어? / W: 역 근처 가게에서.",
        "② M: 지우개 좀 빌려줄래? / W: 여기 있어.",
        "③ M: 오늘 시험 어땠어? / W: 내가 좋아하는 색은 파랑이야.",
        "④ M: 이번 토요일에 시간 돼? / W: 미안, 피아노 수업 있어.",
        "⑤ M: 팔이 왜 그래? / W: 농구 하다가 다쳤어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunwoo, the science fair starts in twenty minutes."],
        ["M", "Our poster is already on the board."],
        ["W", "Did you bring the model of the water cycle?"],
        ["M", "It's still on the desk in our classroom."],
        ["W", "The judges look at the models first."],
        ["M", "Then I have to move quickly."],
        ["W", "I'll stay here and save our table."],
        ["M", "I'll run and get the model now."],
      ],
      choices: [
        "포스터를 붙이기",
        "교실에서 모형을 가져오기",
        "심사위원을 만나기",
        "자리를 맡아 두기",
        "발표 연습을 하기",
      ],
      answer: 2,
      clue: "I'll run and get the model now.",
      explanation:
        "남자는 교실에 있는 모형을 가지러 가겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 현우야, 과학 전시회가 20분 뒤에 시작해.",
        "M: 포스터는 이미 게시판에 붙였어.",
        "W: 물의 순환 모형은 가져왔어?",
        "M: 아직 교실 책상 위에 있어.",
        "W: 심사위원들이 모형부터 봐.",
        "M: 그럼 빨리 움직여야겠다.",
        "W: 나는 여기서 우리 자리 맡고 있을게.",
        "M: 지금 뛰어가서 모형 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 방과 후 수업을 고르시오.",
      lines: [
        ["M", "Chaeyeon, which after-school class will you take?"],
        ["W", "Five classes are open this term."],
        ["M", "Do you have a day you can't come?"],
        ["W", "I go to the dentist every Monday."],
        ["M", "So Monday classes are out for you."],
        ["W", "And I want a class with fewer than fifteen students."],
        ["M", "Two of them are quite large."],
        ["W", "The fee has to be under thirty thousand won too."],
        ["M", "Then only one class is left."],
        ["W", "I'll sign up for it tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I go to the dentist every Monday.",
      explanation:
        "월요일이 아니고 정원 15명 미만이며 수강료 3만 원 미만인 수업은 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Monday / Students: 12 / Fee: 25,000 won" },
          { no: 2, label: "②", value: "Day: Tuesday / Students: 20 / Fee: 22,000 won" },
          { no: 3, label: "③", value: "Day: Wednesday / Students: 18 / Fee: 28,000 won" },
          { no: 4, label: "④", value: "Day: Thursday / Students: 10 / Fee: 26,000 won" },
          { no: 5, label: "⑤", value: "Day: Friday / Students: 14 / Fee: 35,000 won" },
        ],
      },
      translation: [
        "M: 채연아, 방과 후 수업 뭐 들을 거야?",
        "W: 이번 학기에 다섯 개가 열렸어.",
        "M: 못 오는 요일이 있어?",
        "W: 월요일마다 치과에 가.",
        "M: 그럼 월요일 수업은 안 되겠네.",
        "W: 그리고 인원이 15명 미만인 수업이면 좋겠어.",
        "M: 두 개는 꽤 많네.",
        "W: 수강료도 3만 원 미만이어야 해.",
        "M: 그럼 하나만 남는다.",
        "W: 내일 아침에 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Jaemin, when are we going to the animal shelter?"],
        ["M", "The teacher wrote three dates on the notice board."],
        ["W", "Which dates did she actually write down for us?"],
        ["M", "The eighth, the fifteenth and the twenty-second."],
        ["W", "The eighth is the day of the school concert."],
        ["M", "Right, almost everyone will be busy that afternoon."],
        ["W", "And the fifteenth is right in the middle of exam week."],
        ["M", "So the twenty-second is the only day left for us."],
        ["W", "Then let's put our names down for the twenty-second."],
        ["M", "I'll write both names on the board tomorrow morning."],
      ],
      choices: ["the 8th", "the 15th", "the 22nd", "the 5th", "the 18th"],
      answer: 3,
      clue: "So the twenty-second is the only day left for us.",
      explanation:
        "8일은 음악회 날이고 15일은 시험 주간이어서 22일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "W: 재민아, 우리 동물 보호소 언제 가?",
        "M: 선생님이 게시판에 날짜 세 개를 적으셨어.",
        "W: 정확히 어떤 날짜를 적으셨는데?",
        "M: 8일, 15일, 22일.",
        "W: 8일은 학교 음악회 날이야.",
        "M: 맞아, 그날 오후에는 거의 다 바빠.",
        "W: 그리고 15일은 시험 주간 한가운데야.",
        "M: 그럼 우리한테 남는 날은 22일뿐이네.",
        "W: 그럼 22일로 이름 적어 두자.",
        "M: 내일 아침에 둘 이름 다 적어 놓을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minu, how was your weekend?"],
        ["M", "I helped my father at the flower shop."],
        ["W", "Is that the shop near the market?"],
        ["M", "Yes, Saturday is their busiest day."],
        ["W", "What did you actually do there?"],
        ["M", "I carried pots and tied ribbons all morning."],
        ["W", "Did you get paid for it?"],
        ["M", "He bought me lunch and a new notebook."],
        ["W", "Will you go again next weekend?"],
        ["M", "Only if he needs me again."],
      ],
      choices: [
        "꽃집에서 아버지를 도왔다",
        "친척 집에 갔다",
        "도서관에서 공부했다",
        "축구를 했다",
        "집에서 쉬었다",
      ],
      answer: 1,
      clue: "I helped my father at the flower shop.",
      explanation:
        "남자는 주말에 꽃집에서 아버지를 도왔다. 따라서 답은 ①이다.",
      translation: [
        "W: 민우야, 주말 어땠어?",
        "M: 꽃집에서 아버지를 도와드렸어.",
        "W: 시장 근처에 있는 그 가게?",
        "M: 응, 토요일이 제일 바빠.",
        "W: 거기서 뭘 했는데?",
        "M: 오전 내내 화분 나르고 리본 묶었어.",
        "W: 돈은 받았어?",
        "M: 점심이랑 새 공책을 사 주셨어.",
        "W: 다음 주말에도 갈 거야?",
        "M: 또 필요하시면.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Good afternoon, everyone. This is the student council. " +
            "We are collecting old books for the village children's center. " +
            "Bring books you have already read and no longer need. " +
            "Put them in the boxes beside the front door. " +
            "We will collect them until Friday this week. " +
            "Thank you for sharing your books with others.",
        ],
      ],
      choices: [
        "도서관 공사를 알리려고",
        "행사 시간을 바꾸려고",
        "분실물을 찾으려고",
        "헌책 모으기를 알리려고",
        "안전 규칙을 알리려고",
      ],
      answer: 4,
      clue: "We are collecting old books for the village children's center.",
      explanation:
        "아동 센터에 보낼 헌책 모으기를 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 여러분, 안녕하세요. 학생회입니다. 저희는 마을 아동 센터에 보낼 헌책을 모으고 있습니다. 이미 읽어서 더 필요하지 않은 책을 가져와 주세요. 정문 옆에 있는 상자에 넣어 주시면 됩니다. 이번 주 금요일까지 모읍니다. 책을 나눠 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the flower shop. How can I help you?"],
        ["W", "I'd like four roses and three tulips, please."],
        ["M", "Roses are two dollars each today."],
        ["W", "And how much is one tulip?"],
        ["M", "Tulips are one dollar each this week."],
        ["W", "Could you wrap them together in paper?"],
        ["M", "Wrapping is free for orders over ten dollars."],
        ["W", "Then I don't pay extra for that."],
        ["M", "That's right, nothing extra at all."],
        ["W", "Here's my card."],
      ],
      choices: ["$9", "$10", "$11", "$12", "$13"],
      answer: 3,
      clue: "Roses are two dollars each today.",
      explanation:
        "장미 네 송이 8달러와 튤립 세 송이 3달러를 더하면 11달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 꽃집에 오신 걸 환영합니다. 뭘 도와드릴까요?",
        "W: 장미 네 송이랑 튤립 세 송이 주세요.",
        "M: 오늘 장미는 한 송이에 2달러입니다.",
        "W: 튤립은 한 송이에 얼마예요?",
        "M: 이번 주에 튤립은 한 송이에 1달러입니다.",
        "W: 같이 종이로 싸 주실 수 있나요?",
        "M: 10달러 넘게 사시면 포장은 무료입니다.",
        "W: 그럼 추가로 낼 건 없네요.",
        "M: 맞습니다. 전혀 없습니다.",
        "W: 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, your handwriting got much neater this year."],
        ["W", "I practiced for ten minutes every evening."],
        ["M", "Did you use a special notebook for that?"],
        ["W", "Just lined paper and one thin pen."],
        ["M", "Ten minutes doesn't sound like much."],
        ["W", "It adds up to an hour every week."],
        ["M", "My notes are hard to read even for me."],
        ["W", "Slowing down helps more than trying hard."],
        ["M", "Where should I start if I try tonight?"],
      ],
      choices: [
        "Write only in pencil forever.",
        "Start with your own name.",
        "You can't improve at all.",
        "Stop taking notes in class.",
        "Buy an expensive pen first.",
      ],
      answer: 2,
      clue: "Where should I start if I try tonight?",
      explanation:
        "어디서부터 시작할지 물었으므로, 자기 이름부터 써 보라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 예린아, 올해 네 글씨가 훨씬 단정해졌어.",
        "W: 매일 저녁 10분씩 연습했어.",
        "M: 특별한 공책을 썼어?",
        "W: 줄 공책이랑 가는 펜 하나뿐이야.",
        "M: 10분은 별로 많지 않은 것 같은데.",
        "W: 모으면 일주일에 한 시간이야.",
        "M: 내 필기는 나도 알아보기 힘들어.",
        "W: 애쓰는 것보다 천천히 쓰는 게 더 도움이 돼.",
        "M: 오늘 밤에 해 보려면 뭐부터 시작할까?",
        "W: 네 이름부터 써 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seongmin, did you take care of a puppy last month?"],
        ["M", "My aunt left him with us for three weeks."],
        ["W", "Was it hard to look after him every day?"],
        ["M", "He woke me up at five every single morning."],
        ["W", "Did you have to walk him before school?"],
        ["M", "Twice a day, morning and evening."],
        ["W", "That's a lot of work for one student."],
        ["M", "My little brother helped with the evening walk."],
        ["W", "Do you miss the puppy now that he's gone?"],
        ["M", "The house feels very quiet without him."],
        ["W", "Would you take care of him again?"],
      ],
      choices: [
        "Yes, anytime she asks.",
        "I have never seen a dog.",
        "Puppies don't need walks.",
        "I gave him away myself.",
        "My aunt lives with us.",
      ],
      answer: 1,
      clue: "Would you take care of him again?",
      explanation:
        "다시 돌볼 것인지 물었으므로, 언제든 부탁하면 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 성민아, 지난달에 강아지 돌봤어?",
        "M: 이모가 3주 동안 우리 집에 맡기셨어.",
        "W: 매일 돌보는 게 힘들었어?",
        "M: 매일 아침 다섯 시에 나를 깨웠어.",
        "W: 학교 가기 전에 산책도 시켜야 했어?",
        "M: 하루에 두 번, 아침저녁으로.",
        "W: 학생 혼자 하기엔 일이 많네.",
        "M: 저녁 산책은 동생이 도와줬어.",
        "W: 이제 없으니까 보고 싶어?",
        "M: 강아지가 없으니까 집이 아주 조용해.",
        "W: 또 돌봐 줄 거야?",
        "M: 응, 이모가 부탁하시면 언제든.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, you've been carrying that thick book all week."],
        ["W", "It's a novel my cousin lent me."],
        ["M", "How many pages have you read so far?"],
        ["W", "Only about sixty out of four hundred."],
        ["M", "Is the story boring at the beginning?"],
        ["W", "There are too many names to remember."],
        ["M", "I usually give up when that happens."],
        ["W", "I don't want to return it unfinished."],
        ["M", "Why don't you write the names down?"],
      ],
      choices: [
        "I'll try that tonight.",
        "I already finished the book.",
        "The book has no names.",
        "I don't like reading at all.",
        "My cousin wrote the novel.",
      ],
      answer: 1,
      clue: "Why don't you write the names down?",
      explanation:
        "이름을 적어 보라는 제안이므로, 오늘 밤에 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 다인아, 일주일 내내 그 두꺼운 책을 들고 다니네.",
        "W: 사촌이 빌려준 소설이야.",
        "M: 지금까지 몇 쪽 읽었어?",
        "W: 400쪽 중에 60쪽쯤.",
        "M: 처음이 지루해?",
        "W: 외워야 할 이름이 너무 많아.",
        "M: 나는 그러면 보통 포기해.",
        "W: 다 못 읽고 돌려주기는 싫어.",
        "M: 이름을 적어 보는 건 어때?",
        "W: 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Woobin이 Sera에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woobin : ________________",
      lines: [
        [
          "M",
          "Woobin and Sera are cleaning the classroom after school. " +
            "Sera is trying to carry two heavy boxes of books at once. " +
            "Woobin sees that the top box is sliding to one side. " +
            "The stairs are just a few steps ahead of her. " +
            "He wants to take one box so she does not drop them. " +
            "In this situation, what would Woobin most likely say to Sera?",
        ],
      ],
      choices: [
        "Let me take one box for you.",
        "The classroom is already clean.",
        "You should go home now.",
        "I lost the key to the door.",
        "Put the books on the floor forever.",
      ],
      answer: 1,
      clue: "He wants to take one box so she does not drop them.",
      explanation:
        "상자가 기울고 계단이 코앞이므로, 하나를 들어 주겠다는 ①이 가장 적절하다.",
      translation: [
        "M: 우빈이와 세라는 방과 후에 교실을 청소하고 있습니다. 세라는 무거운 책 상자 두 개를 한꺼번에 들려고 합니다. 우빈이는 맨 위 상자가 한쪽으로 미끄러지는 것을 봅니다. 계단은 그녀 바로 몇 걸음 앞에 있습니다. 우빈이는 세라가 상자를 떨어뜨리지 않도록 하나를 들어 주고 싶습니다. 이런 상황에서 우빈이가 세라에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
