/** 중1 듣기 15회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 15회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 컵을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a cup?"],
        ["W", "Yes, one for my desk at home."],
        ["M", "We have cups with a handle and cups without one."],
        ["W", "With a handle, please. The hot ones are hard to hold."],
        ["M", "All right. Do you want a lid on it?"],
        ["W", "Yes, a lid. My cat likes to look inside my cup."],
        ["M", "Then we have two left. One has hearts on it and one has no pattern."],
        ["W", "I'll take the plain one. It goes with my desk."],
        ["M", "Good choice. That one keeps drinks warm for two hours."],
        ["W", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'll take the plain one. It goes with my desk.",
      explanation:
        "여자는 손잡이가 있고 뚜껑이 있으며 무늬가 없는 컵을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five drinking cups shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a cup with NO HANDLE and no lid, completely plain. " +
          "Second: a cup with NO HANDLE and a LID on top, covered in small heart shapes. " +
          "Third: a cup with a HANDLE on its side and no lid, covered in small heart shapes. " +
          "Fourth: a cup with a HANDLE on its side and a LID on top, covered in small heart shapes. " +
          "Fifth: a cup with a HANDLE on its side and a LID on top, completely plain with no pattern.",
      },
      translation: [
        "M: 안녕하세요. 컵 찾으세요?",
        "W: 네, 집 책상에 놓을 거예요.",
        "M: 손잡이가 있는 것과 없는 것이 있어요.",
        "W: 손잡이 있는 걸로요. 뜨거우면 잡기 힘들어서요.",
        "M: 알겠습니다. 뚜껑도 있는 걸로 하시겠어요?",
        "W: 네, 뚜껑도요. 우리 고양이가 컵 안을 들여다봐요.",
        "M: 그럼 두 개 남았네요. 하나는 하트 무늬가 있고 하나는 무늬가 없습니다.",
        "W: 무늬 없는 걸로 할게요. 제 책상이랑 어울려서요.",
        "M: 좋은 선택이세요. 그건 두 시간 동안 따뜻하게 유지됩니다.",
        "W: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 음악회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jiho, are you going to the school concert?"],
        ["M", "I want to, but I don't know much about it."],
        ["W", "It's next Tuesday, right after school."],
        ["M", "Where is it?"],
        ["W", "In the big hall on the first floor."],
        ["M", "Who is playing?"],
        ["W", "The school band and three students from our class."],
        ["M", "Do we need a ticket?"],
        ["W", "No, anyone can come in. It's free."],
        ["M", "Then I'll go with my sister."],
      ],
      choices: ["열리는 날", "장소", "출연자", "준비물", "입장 방법"],
      answer: 4,
      clue: "No, anyone can come in. It's free.",
      explanation:
        "날짜(다음 주 화요일), 장소(1층 대강당), 출연자(학교 밴드와 반 학생 세 명), 입장 방법(표 없이 누구나)은 언급되지만 준비물은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 지호야, 학교 음악회 갈 거야?",
        "M: 가고 싶은데 잘 몰라.",
        "W: 다음 주 화요일, 학교 끝나고 바로.",
        "M: 어디서 해?",
        "W: 1층 대강당에서.",
        "M: 누가 연주하는데?",
        "W: 학교 밴드랑 우리 반 학생 세 명.",
        "M: 표가 필요해?",
        "W: 아니, 누구나 들어올 수 있어. 무료야.",
        "M: 그럼 동생이랑 가야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Seojun. It's Yuna from class three."],
        ["M", "Hi, Yuna. What's up?"],
        ["W", "I'm calling about my birthday on Saturday."],
        ["M", "Oh, is it this Saturday?"],
        ["W", "Yes. We're having lunch at my house at twelve."],
        ["M", "That sounds fun. Can I come?"],
        ["W", "Of course. That's why I called."],
        ["M", "Thank you. I'll be there at twelve."],
        ["W", "Great. Don't bring anything, just come."],
      ],
      choices: [
        "숙제를 물어보려고",
        "생일에 초대하려고",
        "약속을 미루려고",
        "책을 빌리려고",
        "길을 물어보려고",
      ],
      answer: 2,
      clue: "Yes. We're having lunch at my house at twelve.",
      explanation:
        "여자는 토요일 생일 점심에 남자를 초대하려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 서준아. 3반 유나야.",
        "M: 안녕, 유나야. 무슨 일이야?",
        "W: 토요일 내 생일 때문에 전화했어.",
        "M: 아, 이번 주 토요일이야?",
        "W: 응. 12시에 우리 집에서 점심 먹어.",
        "M: 재미있겠다. 가도 돼?",
        "W: 그럼. 그래서 전화한 거야.",
        "M: 고마워. 12시에 갈게.",
        "W: 좋아. 아무것도 가져오지 말고 그냥 와.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minho, what time should we meet at the pool?"],
        ["M", "The swimming class starts at five."],
        ["W", "Then we need time to change first."],
        ["M", "How about four o'clock?"],
        ["W", "That's too early. I have art club until four."],
        ["M", "Oh, right. How long does it take you to get there?"],
        ["W", "Fifteen minutes by bike."],
        ["M", "Then let's meet at four thirty."],
        ["W", "Four thirty is good. See you at the front door."],
      ],
      choices: ["3:30 p.m.", "4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "5:30 p.m."],
      answer: 3,
      clue: "Then let's meet at four thirty.",
      explanation:
        "여자의 미술 동아리가 4시에 끝나고 자전거로 15분이 걸리므로 두 사람은 4시 30분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 민호야, 수영장에서 몇 시에 만날까?",
        "M: 수영 수업이 5시에 시작해.",
        "W: 그럼 갈아입을 시간이 필요하겠다.",
        "M: 4시는 어때?",
        "W: 너무 일러. 4시까지 미술 동아리가 있어.",
        "M: 아, 맞다. 거기까지 얼마나 걸려?",
        "W: 자전거로 15분.",
        "M: 그럼 4시 30분에 만나자.",
        "W: 4시 30분 좋아. 정문에서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you're smiling at your phone again."],
        ["M", "My cousin is coming to stay with us this weekend."],
        ["W", "The one who lives in Jeju?"],
        ["M", "Yes. I haven't seen him for two years."],
        ["W", "Two years! What are you going to do together?"],
        ["M", "We're going to the science museum and the baseball game."],
        ["W", "That sounds like a busy weekend."],
        ["M", "I've been counting the days since last month."],
      ],
      choices: ["excited", "worried", "angry", "bored", "sad"],
      answer: 1,
      clue: "I've been counting the days since last month.",
      explanation:
        "2년 만에 사촌을 만나는 주말을 지난달부터 손꼽아 기다렸다고 했으므로 남자는 들떠 있다. 따라서 답은 ①이다.",
      translation: [
        "W: 준호야, 또 휴대전화를 보면서 웃고 있네.",
        "M: 이번 주말에 사촌이 우리 집에 와.",
        "W: 제주에 사는 그 사촌?",
        "M: 응. 2년 동안 못 봤어.",
        "W: 2년이나! 같이 뭐 할 거야?",
        "M: 과학관이랑 야구 경기 보러 갈 거야.",
        "W: 바쁜 주말이겠다.",
        "M: 지난달부터 날짜를 세고 있었어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Can I sit here?"],
        ["M", "Yes, the seat is free."],
        ["W", "Excuse me, how do I get to the museum?"],
        ["M", "Take the number five bus."],
        ["W", "What's wrong? You look sad."],
        ["M", "I lost my dog this morning."],
        ["W", "Would you like a bag for these?"],
        ["M", "Yes, please. A big one."],
        ["W", "How much are these apples?"],
        ["M", "Four dollars for a bag."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Would you like a bag for these?",
      explanation:
        "그림은 가게 계산대에서 점원이 손님에게 봉투를 들어 보이며 필요한지 묻는 장면이므로 ④가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "At the checkout counter of a small grocery shop. A shop assistant behind the counter is holding up an open paper bag with one hand and looking at the customer. On the counter in front of her lie some fruit and vegetables. The customer is standing opposite her with a purse in her hand. Both are drawn clearly. Shelves of goods are in the background.",
      },
      translation: [
        "① W: 여기 앉아도 될까요? / M: 네, 빈자리예요.",
        "② W: 실례지만 박물관에 어떻게 가나요? / M: 5번 버스를 타세요.",
        "③ W: 무슨 일이야? 슬퍼 보여. / M: 오늘 아침에 강아지를 잃어버렸어.",
        "④ W: 이거 담을 봉투 필요하세요? / M: 네, 큰 걸로 주세요.",
        "⑤ W: 이 사과 얼마예요? / M: 한 봉지에 4달러입니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taehoon, do you go past the post office on your way home?"],
        ["M", "Yes, it's right next to my bus stop."],
        ["W", "That's lucky. I have a letter to send today."],
        ["M", "Can't you send it tomorrow?"],
        ["W", "It's my grandmother's birthday card. It has to go today."],
        ["M", "And you can't go yourself?"],
        ["W", "I have to stay for cleaning duty until six."],
        ["M", "So you want me to post it for you?"],
        ["W", "Yes, please. Here it is, with the stamp on."],
        ["M", "No problem. I'll post it on my way."],
      ],
      choices: ["편지 부쳐 주기", "우표 사다 주기", "카드 써 주기", "청소 도와주기", "자리 맡아 주기"],
      answer: 1,
      clue: "Yes, please. Here it is, with the stamp on.",
      explanation:
        "여자는 청소 당번 때문에 우체국에 갈 수 없어 남자에게 편지를 부쳐 달라고 부탁한다. 따라서 답은 ①이다.",
      translation: [
        "W: 태훈아, 집에 가는 길에 우체국 지나가?",
        "M: 응, 우리 버스 정류장 바로 옆이야.",
        "W: 잘됐다. 오늘 보내야 할 편지가 있어.",
        "M: 내일 보내면 안 돼?",
        "W: 할머니 생신 카드야. 오늘 가야 해.",
        "M: 네가 직접 못 가?",
        "W: 6시까지 청소 당번이야.",
        "M: 그럼 내가 대신 부쳐 달라는 거지?",
        "W: 응, 부탁해. 여기 있어, 우표도 붙였어.",
        "M: 그래. 가는 길에 부칠게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Green Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about Green Day."],
        ["M", "It will be held on the first Friday of next month."],
        ["M", "We will all work on the school garden behind the gym."],
        ["M", "Each class will plant flowers in one bed."],
        ["M", "Please wear old clothes and bring your own gloves."],
        ["M", "Let's make our school greener together."],
      ],
      choices: ["열리는 날", "장소", "하는 일", "준비물", "참가 학년"],
      answer: 5,
      clue: "Please wear old clothes and bring your own gloves.",
      explanation:
        "날짜(다음 달 첫째 금요일), 장소(체육관 뒤 학교 텃밭), 하는 일(반마다 화단에 꽃 심기), 준비물(헌 옷과 장갑)은 언급되지만 참가 학년은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Green Day를 안내합니다.",
        "M: 다음 달 첫째 금요일에 열립니다.",
        "M: 모두 체육관 뒤 학교 텃밭에서 일합니다.",
        "M: 반마다 화단 하나에 꽃을 심습니다.",
        "M: 헌 옷을 입고 장갑을 가져오세요.",
        "M: 우리 학교를 함께 더 푸르게 만듭시다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You use this when you want to know a word."],
        ["W", "It is a thick book with very thin pages."],
        ["W", "The words inside are in order from A to Z."],
        ["W", "Next to each word there is its meaning."],
        ["W", "These days many people use it on their phone."],
      ],
      choices: ["사전", "공책", "달력", "지도", "잡지"],
      answer: 1,
      clue: "The words inside are in order from A to Z.",
      explanation:
        "낱말을 알고 싶을 때 쓰고, 낱말이 알파벳 순서로 있고 옆에 뜻이 있다고 했으므로 사전이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 낱말을 알고 싶을 때 씁니다.",
        "W: 아주 얇은 종이로 된 두꺼운 책입니다.",
        "W: 안에 있는 낱말은 A부터 Z까지 순서대로 있습니다.",
        "W: 낱말 옆에는 그 뜻이 적혀 있습니다.",
        "W: 요즘은 휴대전화로 쓰는 사람도 많습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "What time do you get up on weekends?"],
        ["W", "Around nine o'clock."],
        ["M", "Can you help me with this question?"],
        ["W", "Sure, let me see it."],
        ["M", "How was your weekend?"],
        ["W", "It was quiet but nice."],
        ["M", "Do you want to play badminton?"],
        ["W", "Yes, let's go outside."],
        ["M", "Where did you buy that hat?"],
        ["W", "It rains a lot in July."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Where did you buy that hat?",
      explanation:
        "모자를 어디서 샀는지 묻는 말에 7월에 비가 많이 온다는 대답은 어울리지 않는다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 주말에 몇 시에 일어나? / W: 9시쯤에.",
        "② M: 이 문제 좀 도와줄래? / W: 그럼, 어디 보자.",
        "③ M: 주말 어땠어? / W: 조용했지만 좋았어.",
        "④ M: 배드민턴 칠래? / W: 응, 밖에 나가자.",
        "⑤ M: 그 모자 어디서 샀어? / W: 7월에는 비가 많이 와.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suji, the movie starts in fifteen minutes."],
        ["W", "Is everything ready? What should I do?"],
        ["M", "I already bought the tickets and found our seats."],
        ["W", "Should I get some popcorn?"],
        ["M", "Dad is getting it right now."],
        ["W", "Then what is left?"],
        ["M", "Grandma is waiting outside and doesn't know where we are."],
        ["W", "I'll go and bring her in."],
        ["M", "Thanks. I'll save the seats."],
      ],
      choices: ["표 사기", "팝콘 사 오기", "자리 맡기", "할머니 모시고 오기", "화장실 다녀오기"],
      answer: 4,
      clue: "I'll go and bring her in.",
      explanation:
        "표와 자리, 팝콘은 이미 해결되었으므로 여자는 밖에서 기다리는 할머니를 모시러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 수지야, 영화가 15분 뒤에 시작해.",
        "W: 다 준비됐어? 내가 뭘 할까?",
        "M: 표는 벌써 샀고 자리도 찾아 놨어.",
        "W: 팝콘을 사 올까?",
        "M: 아빠가 지금 사고 계셔.",
        "W: 그럼 뭐가 남았어?",
        "M: 할머니가 밖에서 기다리시는데 우리가 어디 있는지 모르셔.",
        "W: 내가 가서 모시고 올게.",
        "M: 고마워. 나는 자리를 맡고 있을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 공책을 고르시오.",
      lines: [
        ["W", "Dongha, are these the notebooks you were looking at?"],
        ["M", "Yes, these five. I need one for science class."],
        ["W", "How much can you spend?"],
        ["M", "Six dollars at the most."],
        ["W", "All right, that takes out one of them."],
        ["M", "And I need at least a hundred pages."],
        ["W", "Then one more is gone. Three are left."],
        ["M", "I want lined pages, not blank ones."],
        ["W", "One of them is blank, so not that one."],
        ["M", "Two left. Do they both have a hard cover?"],
        ["W", "Only one does. The other has a soft cover."],
        ["M", "Then I'll take the hard one. It lasts longer in my bag."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Then I'll take the hard one. It lasts longer in my bag.",
      explanation:
        "8달러인 ⑤, 80쪽인 ①, 무지인 ②를 뺀다. 남은 ③과 ④ 중 표지가 두꺼운 것은 ③이므로 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "$4 / 80쪽 / 줄 있음 / 두꺼운 표지" },
          { no: 2, label: "②", value: "$5 / 120쪽 / 무지 / 두꺼운 표지" },
          { no: 3, label: "③", value: "$6 / 120쪽 / 줄 있음 / 두꺼운 표지" },
          { no: 4, label: "④", value: "$5 / 100쪽 / 줄 있음 / 얇은 표지" },
          { no: 5, label: "⑤", value: "$8 / 150쪽 / 줄 있음 / 두꺼운 표지" },
        ],
      },
      translation: [
        "W: 동하야, 네가 보던 공책이 이거야?",
        "M: 응, 이 다섯 개. 과학 시간에 쓸 게 필요해.",
        "W: 얼마까지 쓸 수 있어?",
        "M: 많아야 6달러.",
        "W: 그럼 하나가 빠지네.",
        "M: 그리고 적어도 100쪽은 돼야 해.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 무지 말고 줄이 있는 게 좋아.",
        "W: 하나가 무지니까 그건 빼고.",
        "M: 둘 남았다. 둘 다 표지가 두꺼워?",
        "W: 하나만. 다른 하나는 표지가 얇아.",
        "M: 그럼 두꺼운 걸로 할게. 가방에서 더 오래 버텨.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 수영장에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Junseo, when should we go to the swimming pool?"],
        ["M", "It's only open to students on the ninth, tenth, and eleventh."],
        ["W", "I have a dentist appointment on the ninth."],
        ["M", "Then the tenth or the eleventh."],
        ["W", "Isn't the eleventh the day of the class photo?"],
        ["M", "You're right. We'd have to stay in uniform all day."],
        ["W", "So only the tenth is left."],
        ["M", "Then let's go on the tenth, right after lunch."],
      ],
      choices: ["8일", "9일", "10일", "11일", "12일"],
      answer: 3,
      clue: "So only the tenth is left.",
      explanation:
        "9일은 치과 예약, 11일은 학급 사진 찍는 날이어서 10일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "W: 준서야, 수영장에 언제 갈까?",
        "M: 학생은 9일, 10일, 11일에만 들어갈 수 있대.",
        "W: 나 9일에 치과 예약이 있어.",
        "M: 그럼 10일이나 11일이네.",
        "W: 11일은 학급 사진 찍는 날 아니야?",
        "M: 맞다. 하루 종일 교복을 입고 있어야 해.",
        "W: 그럼 10일만 남네.",
        "M: 그럼 10일에 가자, 점심 먹고 바로.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunwoo, did you go camping last weekend?"],
        ["M", "No, I went to the library with my sister on Sunday."],
        ["W", "The new one near the station?"],
        ["M", "Yes. It has a room just for comic books."],
        ["W", "How long did you stay there?"],
        ["M", "About three hours. We read five books each."],
        ["W", "Five books! That's a lot."],
        ["M", "They were short ones. We're going again next Sunday."],
      ],
      choices: ["캠핑 가기", "영화 보기", "운동하기", "친척 집 가기", "도서관 가기"],
      answer: 5,
      clue: "No, I went to the library with my sister on Sunday.",
      explanation:
        "남자는 지난 일요일에 누나와 도서관에 갔다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 현우야, 지난 주말에 캠핑 갔어?",
        "M: 아니, 일요일에 누나랑 도서관에 갔어.",
        "W: 역 근처에 새로 생긴 데?",
        "M: 응. 만화책만 있는 방이 있어.",
        "W: 거기 얼마나 있었어?",
        "M: 세 시간쯤. 각자 다섯 권씩 읽었어.",
        "W: 다섯 권이나! 많다.",
        "M: 짧은 책들이었어. 다음 주 일요일에 또 갈 거야.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "We have one short notice this morning."],
        ["W", "The playground will be closed all day today."],
        ["W", "Workers are painting the lines on the ground."],
        ["W", "The paint needs a whole day to dry."],
        ["W", "Please use the gym during lunch time instead."],
        ["W", "The playground will open again tomorrow morning."],
      ],
      choices: [
        "체육대회 일정을 알리려고",
        "급식 시간을 안내하려고",
        "체육복을 가져오라고 하려고",
        "운동장을 쓸 수 없다고 알리려고",
        "교실 청소를 당부하려고",
      ],
      answer: 4,
      clue: "The playground will be closed all day today.",
      explanation:
        "선 긋는 페인트칠 때문에 오늘 하루 운동장을 쓸 수 없다고 알리는 방송이다. 따라서 방송의 목적은 ④이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 오늘 아침에 짧게 알려 드릴 것이 있습니다.",
        "W: 오늘 하루 운동장을 닫습니다.",
        "W: 바닥에 선을 긋는 페인트칠을 합니다.",
        "W: 페인트가 마르는 데 하루가 걸립니다.",
        "W: 점심시간에는 대신 체육관을 이용해 주세요.",
        "W: 운동장은 내일 아침에 다시 엽니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What can I get you?"],
        ["W", "Three hot chocolates, please."],
        ["M", "They're four dollars each."],
        ["W", "And do you have cookies?"],
        ["M", "We do. A cookie is two dollars."],
        ["W", "Then one cookie too."],
        ["M", "So twelve dollars and two dollars."],
        ["W", "Do you give a student discount?"],
        ["M", "We do. I can take two dollars off."],
        ["W", "Great. Here's my card."],
      ],
      choices: ["$10", "$12", "$14", "$16", "$18"],
      answer: 2,
      clue: "We do. I can take two dollars off.",
      explanation:
        "핫초코 4달러짜리 세 잔은 12달러, 쿠키 2달러를 더하면 14달러이다. 학생 할인 2달러를 빼면 12달러이므로 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 무엇을 드릴까요?",
        "W: 핫초코 세 잔 주세요.",
        "M: 한 잔에 4달러입니다.",
        "W: 쿠키도 있나요?",
        "M: 있습니다. 쿠키는 2달러입니다.",
        "W: 그럼 쿠키도 하나요.",
        "M: 그럼 12달러랑 2달러네요.",
        "W: 학생 할인이 있나요?",
        "M: 있습니다. 2달러 빼 드릴게요.",
        "W: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Dayeon, you look tired in the mornings lately."],
        ["W", "I know. I can't fall asleep until midnight."],
        ["M", "What do you do before bed?"],
        ["W", "I drink a cup of tea in my room."],
        ["M", "What kind of tea?"],
        ["W", "Black tea. My mom always makes it for me."],
        ["M", "Black tea has caffeine, you know."],
        ["W", "Really? I didn't know that."],
        ["M", "Try warm milk instead for a few nights."],
      ],
      choices: [
        "I go to bed at ten every night.",
        "My mom makes very good tea.",
        "Then I'll try warm milk tonight.",
        "I don't like milk at all.",
        "You should drink more water.",
      ],
      answer: 3,
      clue: "Try warm milk instead for a few nights.",
      explanation:
        "며칠은 따뜻한 우유를 마셔 보라는 말을 들었으므로, 오늘 밤에 그렇게 해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 다연아, 요즘 아침마다 피곤해 보여.",
        "W: 그러게. 자정까지 잠이 안 와.",
        "M: 자기 전에 뭐 해?",
        "W: 방에서 차를 한 잔 마셔.",
        "M: 무슨 차?",
        "W: 홍차. 엄마가 늘 끓여 주셔.",
        "M: 홍차에는 카페인이 있잖아.",
        "W: 정말? 몰랐어.",
        "M: 며칠만 대신 따뜻한 우유를 마셔 봐.",
        "W: 그럼 오늘 밤에 따뜻한 우유를 마셔 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Sungho, you brought the wrong textbook again."],
        ["M", "The third time this month. They look the same."],
        ["W", "Do they have different colors?"],
        ["M", "Both covers are blue. That's the problem."],
        ["W", "How do you pack your bag?"],
        ["M", "At night, and my room is dark by then."],
        ["W", "Then you can't see the titles properly."],
        ["M", "I just grab the top one."],
        ["W", "Put a big sticker on each cover."],
      ],
      choices: [
        "My bag is too small for both books.",
        "Then I'll put stickers on them tonight.",
        "I have science class on Mondays.",
        "The textbooks cost ten dollars each.",
        "You should pack your bag in the morning.",
      ],
      answer: 2,
      clue: "Put a big sticker on each cover.",
      explanation:
        "표지마다 큰 스티커를 붙이라는 조언을 들었으므로, 오늘 밤에 붙이겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 성호야, 또 교과서를 잘못 가져왔네.",
        "M: 이번 달에 세 번째야. 둘이 똑같이 생겼어.",
        "W: 색이 다르지 않아?",
        "M: 둘 다 표지가 파란색이야. 그게 문제야.",
        "W: 가방은 언제 싸?",
        "M: 밤에, 그때는 방이 어두워.",
        "W: 그럼 제목이 제대로 안 보이겠네.",
        "M: 그냥 맨 위에 있는 걸 집어.",
        "W: 표지마다 큰 스티커를 붙여 봐.",
        "M: 그럼 오늘 밤에 스티커를 붙일게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Nari, you didn't finish your lunch again today."],
        ["W", "I wasn't hungry. I ate a lot at breakfast."],
        ["M", "But you looked sleepy in the afternoon class."],
        ["W", "I always feel like that after lunch time."],
        ["M", "Do you go outside at all?"],
        ["W", "No, I stay at my desk and read."],
        ["M", "My brother walks for ten minutes after lunch."],
        ["W", "Does that really help?"],
        ["M", "He says he doesn't get sleepy anymore."],
      ],
      choices: [
        "Then I'll walk outside tomorrow after lunch.",
        "I read two books last week.",
        "My brother is in the first grade.",
        "Lunch time is only thirty minutes.",
        "I don't like walking in the cold.",
      ],
      answer: 1,
      clue: "He says he doesn't get sleepy anymore.",
      explanation:
        "점심 후에 10분 걸으면 졸리지 않는다는 말을 들었으므로, 내일 점심 후에 걸어 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 나리야, 오늘도 점심을 다 안 먹었네.",
        "W: 배가 안 고팠어. 아침을 많이 먹었거든.",
        "M: 그런데 오후 수업 때 졸려 보였어.",
        "W: 점심시간 지나면 늘 그래.",
        "M: 밖에는 안 나가?",
        "W: 응, 자리에 앉아서 책 읽어.",
        "M: 우리 형은 점심 먹고 10분씩 걸어.",
        "W: 그게 정말 도움이 돼?",
        "M: 이제 졸리지 않는대.",
        "W: 그럼 내일 점심 먹고 밖에 걸어 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minji가 Taehyun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Minji : ________________",
      lines: [
        ["M", "Minji and Taehyun are in the same class."],
        ["M", "They are making a model of the solar system together."],
        ["M", "Taehyun has painted all the planets very carefully."],
        ["M", "But he made all of them the same size."],
        ["M", "Their teacher said the sizes should be different."],
        ["M", "The model will be shown to the whole grade next week."],
        ["M", "Minji does not want to say that his painting is bad."],
        ["M", "She wants to ask him to make some planets smaller."],
        ["M", "In this situation, what would Minji most likely say to Taehyun?"],
      ],
      choices: [
        "Let's paint them all blue instead.",
        "Could you make the small planets smaller?",
        "I'll finish the model by myself.",
        "We should choose a different subject.",
        "Your painting is too colorful.",
      ],
      answer: 2,
      clue: "She wants to ask him to make some planets smaller.",
      explanation:
        "민지는 태현이의 색칠을 깎아내리지 않으면서, 작은 행성은 더 작게 만들어 달라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 민지와 태현은 같은 반입니다.",
        "M: 두 사람은 태양계 모형을 함께 만들고 있습니다.",
        "M: 태현이 행성을 모두 아주 꼼꼼하게 칠했습니다.",
        "M: 그런데 행성을 전부 같은 크기로 만들었습니다.",
        "M: 선생님은 크기가 서로 달라야 한다고 하셨습니다.",
        "M: 이 모형은 다음 주에 학년 전체에 전시됩니다.",
        "M: 민지는 태현의 색칠이 나쁘다고 말하고 싶지는 않습니다.",
        "M: 다만 작은 행성은 더 작게 만들어 달라고 부탁하고 싶습니다.",
        "M: 이런 상황에서 민지가 태현에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
