/** 중1 듣기 37회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 37회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 책상 스탠드를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a desk lamp?"],
        ["W", "Yes, but my desk is very small and crowded."],
        ["M", "Then a clip lamp saves space on the desk."],
        ["W", "A clip is a good idea. I'll go with that."],
        ["M", "Do you want a straight neck or a bending one?"],
        ["W", "A bending neck, so I can aim the light at my book."],
        ["M", "Some lamps also have a small clock in the base."],
        ["W", "I don't need a clock. Just the lamp, please."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "A clip is a good idea. I'll go with that. / A bending neck, so I can aim the light at my book.",
      explanation:
        "여자는 집게로 고정하는 형태에 목이 구부러지고, 시계는 없는 스탠드를 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five desk lamps standing side by side as five choices, clean black line art on white. " +
          "① a lamp with a STRAIGHT neck standing on a ROUND flat base. " +
          "② a lamp with a BENDING curved neck standing on a ROUND flat base. " +
          "③ a lamp with a BENDING curved neck held by a CLIP clamp instead of a base. " +
          "④ a lamp with a STRAIGHT neck held by a CLIP clamp instead of a base. " +
          "⑤ a lamp with a BENDING curved neck on a ROUND base that has a small round CLOCK face on it.",
      },
      translation: [
        "M: 안녕하세요. 책상 스탠드 찾으세요?",
        "W: 네, 그런데 책상이 아주 작고 복잡해요.",
        "M: 그러면 집게형이 책상 자리를 아껴 줘요.",
        "W: 집게 좋네요. 그걸로 할게요.",
        "M: 목은 곧은 게 좋으세요, 구부러지는 게 좋으세요?",
        "W: 구부러지는 걸로요. 책 쪽으로 빛을 맞추게요.",
        "M: 받침에 작은 시계가 있는 것도 있어요.",
        "W: 시계는 필요 없어요. 스탠드만 주세요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 요리 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Sangmin, are you entering the cooking contest?"],
        ["M", "I might. When is it going to be held?"],
        ["W", "On the third Saturday of next month."],
        ["M", "Where does the contest take place?"],
        ["W", "In the cooking room on the second floor."],
        ["M", "Can everyone take part in it?"],
        ["W", "Only twenty students, so you should hurry."],
        ["M", "How much time do we get for cooking?"],
        ["W", "Forty minutes from start to finish."],
      ],
      choices: [
        "대회가 열리는 날",
        "대회가 열리는 곳",
        "참가할 수 있는 인원",
        "우승자가 받는 상품",
        "요리하는 데 주는 시간",
      ],
      answer: 4,
      clue: "Only twenty students, so you should hurry. / Forty minutes from start to finish.",
      explanation:
        "날짜, 장소, 인원, 요리 시간은 말했지만 우승 상품은 말하지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 상민아, 요리 대회 나갈 거야?",
        "M: 나갈지도. 언제 열려?",
        "W: 다음 달 셋째 주 토요일에.",
        "M: 어디서 해?",
        "W: 2층 조리실에서.",
        "M: 아무나 참가할 수 있어?",
        "W: 스무 명만. 그러니 서둘러야 해.",
        "M: 요리 시간은 얼마나 줘?",
        "W: 시작부터 끝까지 40분.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Gunwoo. It's Suhyeon. Are you home?"],
        ["M", "Yes, I just got back. What's going on?"],
        ["W", "My bike chain came off in front of your street."],
        ["M", "Oh no. Can you push it home like that?"],
        ["W", "It's too heavy for me. Could you come and help?"],
        ["M", "Of course. Wait there and I'll bring gloves."],
        ["W", "Thank you. I'm by the blue mailbox."],
      ],
      choices: [
        "약속을 미루려고",
        "도움을 요청하려고",
        "숙제를 물어보려고",
        "물건을 빌리려고",
        "생일을 축하하려고",
      ],
      answer: 2,
      clue: "It's too heavy for me. Could you come and help?",
      explanation:
        "여자는 자전거 체인이 빠져서 도와 달라고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 건우야. 수현이야. 집이야?",
        "M: 응, 방금 들어왔어. 무슨 일이야?",
        "W: 너희 동네 앞에서 자전거 체인이 빠졌어.",
        "M: 이런. 그 상태로 끌고 갈 수 있어?",
        "W: 나한테는 너무 무거워. 와서 도와줄 수 있어?",
        "M: 그럼. 거기서 기다려. 장갑 가져갈게.",
        "W: 고마워. 파란 우체통 옆이야.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taemin, what time is the science club meeting?"],
        ["M", "It begins at four in the science room."],
        ["W", "Do we need to set up the tables first?"],
        ["M", "Yes, and that takes about thirty minutes."],
        ["W", "Then we should meet at three thirty."],
        ["M", "My last class ends at three forty on Thursdays."],
        ["W", "Then let's meet at three forty-five instead."],
        ["M", "Three forty-five is fine. We can still finish."],
        ["W", "See you at the science room door."],
      ],
      choices: ["3:30 p.m.", "3:40 p.m.", "3:45 p.m.", "4:00 p.m.", "4:15 p.m."],
      answer: 3,
      clue: "Then let's meet at three forty-five instead.",
      explanation:
        "남자의 수업이 3시 40분에 끝나서 3시 45분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 과학 동아리 모임 몇 시야?",
        "M: 과학실에서 4시에 시작해.",
        "W: 먼저 책상을 정리해야 해?",
        "M: 응, 그게 30분쯤 걸려.",
        "W: 그럼 3시 30분에 만나야겠다.",
        "M: 목요일에는 마지막 수업이 3시 40분에 끝나.",
        "W: 그럼 3시 45분에 만나자.",
        "M: 3시 45분이면 괜찮아. 그래도 끝낼 수 있어.",
        "W: 과학실 문 앞에서 보자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hanul, why are you holding that paper so carefully?"],
        ["M", "My poem was chosen for the school magazine."],
        ["W", "The one you wrote about your grandfather?"],
        ["M", "Yes. The teacher read it aloud in front of everyone."],
        ["W", "That must have felt amazing."],
        ["M", "I rewrote that poem nine times last month."],
        ["W", "And now the whole school will read it."],
        ["M", "I'm going to show this page to my parents tonight."],
      ],
      choices: ["sorry", "angry", "bored", "scared", "proud"],
      answer: 5,
      clue: "I'm going to show this page to my parents tonight.",
      explanation:
        "아홉 번이나 고쳐 쓴 시가 교지에 실려 부모님께 보여 드리려 하므로 뿌듯한 심정이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 하늘아, 그 종이 왜 그렇게 조심스럽게 들고 있어?",
        "M: 내 시가 교지에 실리게 됐어.",
        "W: 할아버지에 대해 쓴 그 시?",
        "M: 응. 선생님이 모두 앞에서 읽어 주셨어.",
        "W: 기분 정말 좋았겠다.",
        "M: 지난달에 그 시를 아홉 번이나 고쳐 썼어.",
        "W: 이제 전교생이 읽게 되겠네.",
        "M: 오늘 밤에 이 쪽을 부모님께 보여 드릴 거야.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Where should I put this box?"],
        ["M", "On the shelf over there."],
        ["ANN", "Number two."],
        ["W", "Is the water cold enough?"],
        ["M", "Yes, it just came out."],
        ["ANN", "Number three."],
        ["W", "Did you finish your homework?"],
        ["M", "Almost. One more page."],
        ["ANN", "Number four."],
        ["W", "Paper goes in the other bin."],
        ["M", "Oh, thank you for telling me."],
        ["ANN", "Number five."],
        ["W", "What time do we leave?"],
        ["M", "In about ten minutes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Paper goes in the other bin.",
      explanation:
        "그림은 분리수거장에서 남학생이 종이를 잘못된 통에 넣으려 하자 여학생이 다른 통을 가리키는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "A recycling corner beside a school building, clean black line art on a plain white background, no writing anywhere. " +
          "Three large separate bins stand in a row, each with a different shaped opening and no labels. " +
          "A schoolboy is about to drop a flat sheet of paper into the first bin. " +
          "A schoolgirl beside him points firmly at the third bin with her finger. " +
          "A broom and a simple wall are drawn in the background.",
      },
      translation: [
        "① W: 이 상자 어디에 둘까요? / M: 저기 선반 위에요.",
        "② W: 물이 충분히 차가워요? / M: 네, 방금 나왔어요.",
        "③ W: 숙제 다 했어? / M: 거의. 한 쪽 남았어.",
        "④ W: 종이는 다른 통에 넣어야 해. / M: 아, 알려 줘서 고마워.",
        "⑤ W: 우리 몇 시에 출발해? / M: 10분쯤 뒤에.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeji, are you coming to school early tomorrow?"],
        ["W", "Yes, I have morning practice at seven thirty."],
        ["M", "I have a presentation in the first period."],
        ["W", "Did you finish making your slides?"],
        ["M", "I did, but I left my notes on my desk at school."],
        ["W", "Do you want me to check your desk?"],
        ["M", "Please bring the blue notebook to the front gate."],
        ["W", "All right. I'll look for it when I arrive."],
      ],
      choices: [
        "청소를 도와주기",
        "숙제를 알려 주기",
        "두고 온 물건을 가져다주기",
        "자리를 바꿔 주기",
        "전화를 해 주기",
      ],
      answer: 3,
      clue: "Please bring the blue notebook to the front gate.",
      explanation:
        "남자는 학교 책상에 두고 온 파란 공책을 정문으로 가져다 달라고 부탁했다. 따라서 답은 ③이다.",
      translation: [
        "M: 예지야, 내일 학교에 일찍 와?",
        "W: 응, 7시 30분에 아침 연습이 있어.",
        "M: 나는 1교시에 발표가 있어.",
        "W: 발표 자료는 다 만들었어?",
        "M: 만들었는데 학교 책상에 메모를 두고 왔어.",
        "W: 내가 네 책상 확인해 줄까?",
        "M: 파란 공책을 정문으로 가져다줘.",
        "W: 알겠어. 도착하면 찾아볼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 합창단 모집에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Our school choir is looking for new members. " +
            "We practice every Monday and Thursday after the last class. " +
            "Practice is held in the music room on the fourth floor. " +
            "If you want to join, write your name on the paper by the door. " +
            "Our first concert will be at the winter festival in December.",
        ],
      ],
      choices: [
        "연습하는 요일",
        "지도하시는 선생님",
        "연습하는 장소",
        "지원하는 방법",
        "첫 공연 시기",
      ],
      answer: 2,
      clue: "We practice every Monday and Thursday after the last class.",
      explanation:
        "연습 요일, 장소, 지원 방법, 첫 공연 시기는 말했지만 지도 선생님은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 우리 학교 합창단에서 새 단원을 찾습니다. 연습은 매주 월요일과 목요일 마지막 수업이 끝난 뒤에 합니다. 연습은 4층 음악실에서 합니다. 들어오고 싶은 학생은 문 옆 종이에 이름을 적어 주세요. 첫 공연은 12월 겨울 축제에서 합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a tall box that stands in the kitchen. " +
            "It keeps the air inside much colder than the room. " +
            "You put milk, eggs and vegetables on its shelves. " +
            "Food stays fresh in it for many more days. " +
            "Close its door quickly so that the cold air does not escape.",
        ],
      ],
      choices: ["냉장고", "세탁기", "전자레인지", "청소기", "에어컨"],
      answer: 1,
      clue: "You put milk, eggs and vegetables on its shelves.",
      explanation:
        "부엌에 서 있는 큰 상자로 안을 차게 유지해 음식을 오래 보관하는 것은 냉장고이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 부엌에 서 있는 키 큰 상자입니다. 안의 공기를 방보다 훨씬 차갑게 유지합니다. 선반에 우유, 달걀, 채소를 넣습니다. 음식이 이 안에서 훨씬 오래 신선하게 유지됩니다. 찬 공기가 빠져나가지 않도록 문을 빨리 닫으세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Would you like some more soup?"],
        ["M", "Yes, please. It's delicious."],
        ["ANN", "Number two."],
        ["W", "How long have you played the guitar?"],
        ["M", "For about two years."],
        ["ANN", "Number three."],
        ["W", "Can you speak Chinese?"],
        ["M", "Only a little."],
        ["ANN", "Number four."],
        ["W", "I'm going to the library."],
        ["M", "Have a good time."],
        ["ANN", "Number five."],
        ["W", "Where is my umbrella?"],
        ["M", "It costs ten thousand won."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Where is my umbrella?",
      explanation:
        "우산이 어디 있는지 묻는 말에 만 원이라고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① W: 국 더 드릴까요? / M: 네, 주세요. 맛있어요.",
        "② W: 기타 친 지 얼마나 됐어? / M: 2년쯤.",
        "③ W: 중국어 할 줄 알아? / M: 조금만.",
        "④ W: 나 도서관에 가. / M: 잘 다녀와.",
        "⑤ W: 내 우산 어디 있어? / M: 만 원이야.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaerin, is that library book still in your bag?"],
        ["W", "Yes, I finished it on the bus this morning."],
        ["M", "When is it due back at the library?"],
        ["W", "Today. I have to return it before five."],
        ["M", "It's already four thirty right now."],
        ["W", "Oh no, I completely lost track of time."],
        ["M", "The library is only three minutes away."],
        ["W", "I'll run over and return it right now."],
      ],
      choices: [
        "숙제를 하기",
        "교실을 청소하기",
        "도서관에 책을 반납하기",
        "저녁을 먹으러 가기",
        "운동장에서 운동하기",
      ],
      answer: 3,
      clue: "I'll run over and return it right now.",
      explanation:
        "여자는 지금 바로 도서관에 가서 책을 반납하겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 채린아, 그 도서관 책 아직 가방에 있어?",
        "W: 응, 오늘 아침 버스에서 다 읽었어.",
        "M: 반납 기한이 언제야?",
        "W: 오늘. 5시 전에 반납해야 해.",
        "M: 지금 벌써 4시 30분이야.",
        "W: 어떡해, 시간 가는 걸 완전히 잊었어.",
        "M: 도서관은 3분 거리밖에 안 돼.",
        "W: 지금 뛰어가서 반납하고 올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 여름 캠프를 고르시오.",
      lines: [
        ["M", "Sein, which summer camp are you going to choose?"],
        ["W", "Let's go through these five on the list."],
        ["M", "How many nights can you stay away from home?"],
        ["W", "Two nights at the most. Three is too long for me."],
        ["M", "All right. What about the cost?"],
        ["W", "My parents said one hundred thousand won or less."],
        ["M", "Do you want a camp by the sea or in the mountains?"],
        ["W", "The mountains, please. I get sunburned so easily."],
        ["M", "Then only one camp here fits everything."],
        ["W", "Great. I'll fill in the form this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Two nights at the most. Three is too long for me.",
      explanation:
        "2박 이하이고, 10만 원 이하이며, 산에서 하는 캠프를 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Nights: 3 / Fee: 90,000 won / Place: Mountain" },
          { no: 2, label: "②", value: "Nights: 2 / Fee: 120,000 won / Place: Mountain" },
          { no: 3, label: "③", value: "Nights: 2 / Fee: 95,000 won / Place: Sea" },
          { no: 4, label: "④", value: "Nights: 2 / Fee: 88,000 won / Place: Mountain" },
          { no: 5, label: "⑤", value: "Nights: 1 / Fee: 70,000 won / Place: Sea" },
        ],
      },
      translation: [
        "M: 세인아, 어떤 여름 캠프 고를 거야?",
        "W: 목록에 있는 다섯 개 같이 보자.",
        "M: 집 떠나서 며칠 밤까지 잘 수 있어?",
        "W: 최대 2박. 3박은 나한테 너무 길어.",
        "M: 알겠어. 비용은?",
        "W: 부모님이 10만 원 이하라고 하셨어.",
        "M: 바다 캠프가 좋아, 산 캠프가 좋아?",
        "W: 산으로. 나는 햇볕에 금방 타.",
        "M: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "W: 좋아. 오늘 저녁에 신청서 쓸게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 이사를 돕기로 한 날짜를 고르시오.",
      lines: [
        ["W", "Jiwon, my family is moving to a new apartment."],
        ["M", "Really? When is the moving day?"],
        ["W", "The truck comes on the eleventh, next Thursday."],
        ["M", "I have an exam on the eleventh, all morning."],
        ["W", "We also need help packing before that day."],
        ["M", "I could come on the ninth or the tenth."],
        ["W", "The ninth is my grandmother's birthday."],
        ["M", "Then I'll come on the tenth after school."],
        ["W", "Thank you. There are so many books to pack."],
      ],
      choices: [
        "the 8th",
        "the 9th",
        "the 11th",
        "the 10th",
        "the 12th",
      ],
      answer: 4,
      clue: "Then I'll come on the tenth after school.",
      explanation:
        "11일은 시험, 9일은 할머니 생신이어서 10일에 돕기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 지원아, 우리 가족이 새 아파트로 이사 가.",
        "M: 정말? 이사하는 날이 언제야?",
        "W: 다음 주 목요일 11일에 트럭이 와.",
        "M: 11일에는 오전 내내 시험이 있어.",
        "W: 그 전에 짐 싸는 것도 도움이 필요해.",
        "M: 9일이나 10일에는 갈 수 있어.",
        "W: 9일은 할머니 생신이야.",
        "M: 그럼 10일에 방과 후에 갈게.",
        "W: 고마워. 쌀 책이 정말 많아.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Daehyun, did you go anywhere on Saturday?"],
        ["M", "No, I stayed home and looked after my little sister."],
        ["W", "Were your parents out all day?"],
        ["M", "They went to a wedding in Daegu until evening."],
        ["W", "How old is your sister again?"],
        ["M", "She is five, and she never sits still for a minute."],
        ["W", "What did the two of you do together?"],
        ["M", "We drew pictures and built a house with blocks."],
      ],
      choices: [
        "동생을 돌보기",
        "영화를 보러 가기",
        "운동장에서 운동하기",
        "가족과 여행을 가기",
        "도서관에서 공부하기",
      ],
      answer: 1,
      clue: "No, I stayed home and looked after my little sister.",
      explanation:
        "남자는 토요일에 집에서 다섯 살 동생을 돌봤다. 따라서 답은 ①이다.",
      translation: [
        "W: 대현아, 토요일에 어디 갔었어?",
        "M: 아니, 집에서 여동생을 돌봤어.",
        "W: 부모님이 하루 종일 나가셨어?",
        "M: 저녁까지 대구에 결혼식 가셨어.",
        "W: 동생이 몇 살이라고 했지?",
        "M: 다섯 살. 1분도 가만히 있질 않아.",
        "W: 둘이서 뭐 했어?",
        "M: 그림 그리고 블록으로 집 만들었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, please. This is the front desk of the sports center. " +
            "Our new lockers on the second floor are ready to use today. " +
            "Press the red button and choose any four numbers you like. " +
            "Remember those four numbers, because we cannot open the door for you. " +
            "Please take all your things out before nine in the evening. " +
            "Thank you for using our sports center.",
        ],
      ],
      choices: [
        "행사 시작을 알리려고",
        "이용 방법을 안내하려고",
        "할인 행사를 알리려고",
        "분실물을 찾아가라고",
        "문 닫는 시간을 알리려고",
      ],
      answer: 2,
      clue: "Press the red button and choose any four numbers you like.",
      explanation:
        "새 사물함을 쓰는 방법을 알려 주는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안내 말씀 드립니다. 스포츠 센터 안내 데스크입니다. 2층에 새로 놓은 사물함을 오늘부터 쓰실 수 있습니다. 빨간 단추를 누르고 원하시는 네 자리 번호를 정하세요. 저희가 문을 열어 드릴 수 없으니 그 네 자리 번호를 꼭 기억하세요. 저녁 아홉 시 전에 물건을 모두 빼 주세요. 저희 스포츠 센터를 이용해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you buying tickets for the show?"],
        ["W", "Yes, three student tickets, please."],
        ["M", "A student ticket is eight dollars each."],
        ["W", "Do we need to pay for the program book?"],
        ["M", "The program book is three dollars."],
        ["W", "We'll take just one program book for us."],
        ["M", "All right, that will be everything."],
        ["W", "Here you are. Thank you very much."],
      ],
      choices: ["$27", "$24", "$30", "$33", "$21"],
      answer: 1,
      clue: "A student ticket is eight dollars each. / The program book is three dollars.",
      explanation:
        "학생 표 8달러짜리 세 장은 24달러이고 프로그램 책 3달러를 더하면 27달러이다. 따라서 답은 ①이다.",
      translation: [
        "M: 안녕하세요. 공연 표 사시나요?",
        "W: 네, 학생 표 세 장 주세요.",
        "M: 학생 표는 한 장에 8달러입니다.",
        "W: 안내 책자도 돈을 내야 하나요?",
        "M: 안내 책자는 3달러입니다.",
        "W: 저희는 한 권만 살게요.",
        "M: 알겠습니다. 이걸로 다 되셨습니다.",
        "W: 여기 있습니다. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Areum, you brought a lunch box to the field trip."],
        ["W", "My mother made rice balls for me this morning."],
        ["M", "They look much better than the store sandwiches."],
        ["W", "She wakes up early whenever we have a trip."],
        ["M", "Does she pack something different every time?"],
        ["W", "Yes, and she puts a small note inside the box."],
        ["M", "A note? What does she usually write?"],
        ["W", "Just short things, like have a good day."],
        ["M", "You should show her how much you like it."],
      ],
      choices: [
        "I don't read the notes.",
        "She never makes lunch.",
        "The store sandwich is better.",
        "I'll write her a note back.",
        "My mother is at work now.",
      ],
      answer: 4,
      clue: "You should show her how much you like it.",
      explanation:
        "남자가 어머니께 마음을 표현하라고 했으므로, 답장을 써 드리겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 아름아, 현장 학습에 도시락을 싸 왔네.",
        "W: 오늘 아침에 엄마가 주먹밥을 만들어 주셨어.",
        "M: 가게에서 파는 샌드위치보다 훨씬 좋아 보여.",
        "W: 소풍 있을 때마다 일찍 일어나셔.",
        "M: 매번 다른 걸 싸 주셔?",
        "W: 응, 그리고 도시락 안에 작은 쪽지를 넣어 주셔.",
        "M: 쪽지? 보통 뭐라고 쓰셔?",
        "W: 좋은 하루 보내라 같은 짧은 말들.",
        "M: 네가 얼마나 좋아하는지 보여 드려야겠다.",
        "W: 나도 답장 쪽지를 써 드려야겠어.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seungmin, your English speaking has improved a lot."],
        ["M", "Do you really think so? I still make mistakes."],
        ["W", "You spoke for three minutes without stopping."],
        ["M", "I was so nervous that my voice shook."],
        ["W", "Nobody noticed that at all."],
        ["M", "I have been reading aloud every night."],
        ["W", "For how long have you been doing that?"],
        ["M", "Since the summer break, about ten minutes a day."],
        ["W", "You should tell the class about your method."],
      ],
      choices: [
        "All right, I'll share it tomorrow.",
        "I never read aloud at home.",
        "My English has not changed.",
        "The class already knows it.",
        "I stopped reading last month.",
      ],
      answer: 1,
      clue: "You should tell the class about your method.",
      explanation:
        "반 친구들에게 공부 방법을 알려 주라고 했으므로, 내일 알려 주겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 승민아, 네 영어 말하기가 많이 늘었어.",
        "M: 정말? 아직 실수도 많이 해.",
        "W: 3분 동안 멈추지 않고 말했잖아.",
        "M: 너무 긴장해서 목소리가 떨렸어.",
        "W: 아무도 눈치 못 챘어.",
        "M: 매일 밤 소리 내어 읽고 있어.",
        "W: 얼마나 오래 했어?",
        "M: 여름방학부터, 하루 10분쯤.",
        "W: 반 애들한테 그 방법을 알려 줘.",
        "M: 알겠어, 내일 얘기할게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Bomi, your drawing club had an exhibition, right?"],
        ["W", "Yes, we hung our work in the hallway last week."],
        ["M", "I saw the one with the old bicycle."],
        ["W", "That one took me almost a month."],
        ["M", "Where did you learn to draw like that?"],
        ["W", "I taught myself by copying photos."],
        ["M", "I'd like to start drawing too, but I can't begin."],
        ["W", "Start with something simple, like your own hand."],
        ["M", "Could you look at my first drawing next week?"],
      ],
      choices: [
        "I can't draw at all.",
        "Of course, bring it on Monday.",
        "The exhibition is over now.",
        "You already draw very well.",
        "I don't have a pencil.",
      ],
      answer: 2,
      clue: "Could you look at my first drawing next week?",
      explanation:
        "남자가 다음 주에 첫 그림을 봐 달라고 했으므로, 월요일에 가져오라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 보미야, 너희 그림 동아리 전시했지?",
        "W: 응, 지난주에 복도에 작품을 걸었어.",
        "M: 낡은 자전거 그린 그림 봤어.",
        "W: 그건 거의 한 달 걸렸어.",
        "M: 그렇게 그리는 걸 어디서 배웠어?",
        "W: 사진을 따라 그리면서 혼자 익혔어.",
        "M: 나도 그리고 싶은데 시작을 못 하겠어.",
        "W: 네 손처럼 쉬운 것부터 시작해 봐.",
        "M: 다음 주에 내 첫 그림 좀 봐 줄래?",
        "W: 그럼, 월요일에 가져와.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Dain이 Yunho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Dain : ________________",
      lines: [
        [
          "M",
          "Dain and Yunho are eating lunch together in the school cafeteria. " +
            "Yunho finishes his meal and stands up with his tray in his hands. " +
            "Dain notices that his milk carton is still on the table. " +
            "The carton is open and standing very close to the edge. " +
            "She wants to tell him before he walks away and someone knocks it over. " +
            "In this situation, what would Dain most likely say to Yunho?",
        ],
      ],
      choices: [
        "Can I have your dessert?",
        "The cafeteria closes at one.",
        "Let's sit at another table.",
        "You forgot to bring a tray.",
        "Take your milk carton with you.",
      ],
      answer: 5,
      clue: "She wants to tell him before he walks away and someone knocks it over.",
      explanation:
        "열린 우유갑이 식탁 끝에 놓인 채 남아 있으므로, 가져가라고 말하는 ⑤가 가장 적절하다.",
      translation: [
        "M: 다인이와 윤호는 학교 급식실에서 함께 점심을 먹고 있습니다. 윤호가 식사를 마치고 식판을 들고 일어섭니다. 다인이는 윤호의 우유갑이 아직 식탁에 있는 것을 봅니다. 우유갑은 열린 채로 식탁 끝 가까이에 놓여 있습니다. 다인이는 윤호가 그냥 가서 누군가 쏟기 전에 알려 주고 싶습니다. 이런 상황에서 다인이가 윤호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
