/** 중1 듣기 19회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 19회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 우산을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for an umbrella?"],
        ["W", "Yes, one I can put in my school bag."],
        ["M", "We have long ones and folding ones."],
        ["W", "A folding one, please. The long ones don't fit in my bag."],
        ["M", "All right. Do you want a curved handle or a round one?"],
        ["W", "A curved handle. Then I can hang it on my arm."],
        ["M", "Then two are left. One has stars on it and one has no pattern."],
        ["W", "The one with stars, please. My last umbrella was plain and someone took it."],
        ["M", "Good choice. This one opens with one button."],
        ["W", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "The one with stars, please. My last umbrella was plain and someone took it.",
      explanation:
        "여자는 접는 우산을, 손잡이가 굽은 것으로, 별무늬가 있는 것을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five closed umbrellas shown standing in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing or letters anywhere. " +
          "Umbrella 1: a LONG umbrella, tall and thin, with a J-shaped CURVED HOOK HANDLE at the bottom, covered in small STAR shapes. " +
          "Umbrella 2: a SHORT FOLDING umbrella, half the height of the long ones, with a straight ROUND KNOB handle, covered in small STAR shapes. " +
          "Umbrella 3: a LONG umbrella, tall and thin, with a straight ROUND KNOB handle, completely blank with no pattern. " +
          "Umbrella 4: a SHORT FOLDING umbrella, half the height of the long ones, with a J-shaped CURVED HOOK HANDLE, covered in small STAR shapes. " +
          "Umbrella 5: a SHORT FOLDING umbrella, half the height of the long ones, with a J-shaped CURVED HOOK HANDLE, completely blank with no pattern.",
      },
      translation: [
        "M: 안녕하세요. 우산 찾으세요?",
        "W: 네, 책가방에 넣을 수 있는 걸로요.",
        "M: 긴 우산과 접는 우산이 있습니다.",
        "W: 접는 걸로요. 긴 건 가방에 안 들어가요.",
        "M: 알겠습니다. 손잡이는 굽은 게 좋으세요, 둥근 게 좋으세요?",
        "W: 굽은 손잡이요. 그래야 팔에 걸 수 있어요.",
        "M: 그럼 두 개 남았네요. 하나는 별무늬가 있고 하나는 무늬가 없습니다.",
        "W: 별무늬로요. 지난번 우산은 무늬가 없어서 누가 가져갔어요.",
        "M: 좋은 선택이세요. 이건 단추 하나로 펴집니다.",
        "W: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 축구 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minho, is your class playing in the football tournament?"],
        ["M", "We are, but I don't know much about it yet."],
        ["W", "It starts next Monday and runs for three days."],
        ["M", "Where do we play?"],
        ["W", "On the big playground, behind the gym."],
        ["M", "How long is one game?"],
        ["W", "Twenty minutes, ten each half."],
        ["M", "Do we need anything special?"],
        ["W", "Just your class T-shirt and trainers."],
        ["M", "Then I'll tell our team tomorrow."],
      ],
      choices: ["열리는 날", "장소", "경기 시간", "준비물", "참가 팀 수"],
      answer: 5,
      clue: "Just your class T-shirt and trainers.",
      explanation:
        "날짜(다음 주 월요일부터 사흘), 장소(체육관 뒤 큰 운동장), 경기 시간(20분), 준비물(반 티셔츠와 운동화)은 언급되지만 참가 팀 수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민호야, 너희 반도 축구 대회 나가?",
        "M: 나가는데 아직 잘 몰라.",
        "W: 다음 주 월요일에 시작해서 사흘 동안 해.",
        "M: 어디서 하는데?",
        "W: 체육관 뒤 큰 운동장에서.",
        "M: 한 경기가 얼마나 걸려?",
        "W: 20분, 전후반 10분씩.",
        "M: 뭐 따로 준비할 거 있어?",
        "W: 반 티셔츠랑 운동화만.",
        "M: 그럼 내일 우리 팀한테 말할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sujin. It's Dohyun from your class."],
        ["W", "Hi, Dohyun. Is something wrong?"],
        ["M", "Nothing's wrong, but tomorrow's club meeting has moved."],
        ["W", "Moved? To another day?"],
        ["M", "Same day, but two o'clock instead of one."],
        ["W", "Why an hour later than usual?"],
        ["M", "The room is being cleaned until half past one."],
        ["W", "I see. Is it still the same room?"],
        ["M", "Yes, room two-oh-four. Only the time is different."],
        ["W", "Then I'll have lunch first and go up at two."],
        ["M", "That's what I'm doing. Could you tell Nari as well?"],
        ["W", "Sure, I'll message her now. Thanks for telling me."],
      ],
      choices: [
        "모임 시간이 바뀐 것을 알리려고",
        "모임이 취소되었다고 알리려고",
        "청소를 도와 달라고 하려고",
        "숙제를 물어보려고",
        "동아리에 들어오라고 하려고",
      ],
      answer: 1,
      clue: "Same day, but two o'clock instead of one.",
      explanation:
        "남자는 청소 때문에 동아리 모임이 1시에서 2시로 바뀌었다고 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 수진아. 같은 반 도현이야.",
        "W: 안녕, 도현아. 무슨 일 있어?",
        "M: 별일은 아니고, 내일 동아리 모임 시간이 바뀌었어.",
        "W: 바뀌었다고? 다른 날로?",
        "M: 날은 그대로인데, 1시가 아니라 2시에 해.",
        "W: 왜 평소보다 한 시간 늦어졌어?",
        "M: 1시 30분까지 교실 청소를 한대.",
        "W: 그렇구나. 교실은 그대로야?",
        "M: 응, 204호. 시간만 달라.",
        "W: 그럼 점심 먼저 먹고 2시에 올라갈게.",
        "M: 나도 그럴 생각이야. 나리한테도 말해 줄래?",
        "W: 그래, 지금 문자 보낼게. 알려 줘서 고마워.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yerin, what time should we meet at the park tomorrow?"],
        ["W", "The bike lesson starts at eleven."],
        ["M", "And we have to rent the bikes first."],
        ["W", "How about ten forty-five?"],
        ["M", "There's a queue at the rental shop on Sundays. Let's go earlier."],
        ["W", "How long does it take you to get there?"],
        ["M", "Twenty minutes by bus."],
        ["W", "Then let's meet at ten o'clock."],
        ["M", "Ten o'clock is good. I'll wait by the fountain."],
      ],
      choices: ["10:00 a.m.", "10:15 a.m.", "10:30 a.m.", "10:45 a.m.", "11:00 a.m."],
      answer: 1,
      clue: "Then let's meet at ten o'clock.",
      explanation:
        "수업이 11시에 시작하고 대여점에 줄이 서서 두 사람은 10시에 만나기로 한다. 따라서 답은 ①이다.",
      translation: [
        "M: 예린아, 내일 공원에서 몇 시에 만날까?",
        "W: 자전거 수업이 11시에 시작해.",
        "M: 그리고 자전거도 먼저 빌려야 하잖아.",
        "W: 10시 45분은 어때?",
        "M: 일요일에는 대여점에 줄이 서. 더 일찍 가자.",
        "W: 거기까지 얼마나 걸려?",
        "M: 버스로 20분.",
        "W: 그럼 10시에 만나자.",
        "M: 10시 좋아. 분수대 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you've been smiling at your phone for five minutes."],
        ["M", "My cousin sent me a photo. My dog had puppies last night."],
        ["W", "Puppies? How many?"],
        ["M", "Four. Three brown and one white."],
        ["W", "That's wonderful! Have you seen them?"],
        ["M", "Not yet. I'm going to my grandmother's house on Saturday."],
        ["W", "You must be counting the days."],
        ["M", "I've looked at the photo about thirty times already."],
      ],
      choices: ["bored", "worried", "angry", "delighted", "disappointed"],
      answer: 4,
      clue: "I've looked at the photo about thirty times already.",
      explanation:
        "강아지가 태어난 사진을 서른 번이나 봤다고 했으므로 남자는 기뻐하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 준호야, 5분째 휴대전화를 보며 웃고 있네.",
        "M: 사촌이 사진을 보냈어. 우리 개가 어젯밤에 새끼를 낳았대.",
        "W: 강아지? 몇 마리?",
        "M: 네 마리. 갈색 세 마리에 흰색 한 마리.",
        "W: 잘됐다! 봤어?",
        "M: 아직. 토요일에 할머니 댁에 가.",
        "W: 날짜 세고 있겠다.",
        "M: 사진을 벌써 서른 번쯤 봤어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Are you all right? Let me help you up."],
        ["M", "Thank you. I slipped on the ice."],
        ["W", "How much is this cap?"],
        ["M", "Nine dollars."],
        ["W", "What time does the class start?"],
        ["M", "At two thirty."],
        ["W", "Where is the science room?"],
        ["M", "On the third floor."],
        ["W", "Can I borrow your ruler?"],
        ["M", "Sure, here you are."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Are you all right? Let me help you up.",
      explanation:
        "그림은 얼어붙은 길에서 넘어진 사람에게 다른 사람이 손을 내밀어 일으켜 주려는 장면이므로 ①이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On an icy winter pavement, clean black line art on a plain white background, no writing or letters anywhere. A BOY has fallen and is sitting on the ground with one hand behind him, looking up. A GIRL standing beside him is bending forward and reaching out one hand toward him to pull him up. Both people are drawn clearly. Bare trees and a low wall are in the background.",
      },
      translation: [
        "① W: 괜찮아? 일어나게 도와줄게. / M: 고마워. 얼음에 미끄러졌어.",
        "② W: 이 모자 얼마예요? / M: 9달러입니다.",
        "③ W: 수업 몇 시에 시작해? / M: 2시 30분에.",
        "④ W: 과학실이 어디예요? / M: 3층에 있어요.",
        "⑤ W: 자 좀 빌려줄래? / M: 그럼, 여기 있어.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, are you going to the library after school?"],
        ["W", "Yes, I have to return two books."],
        ["M", "Could you do one thing for me while you're there?"],
        ["W", "Sure. What is it?"],
        ["M", "I left my pencil case on the table by the window."],
        ["W", "Do you want me to bring it to you tomorrow?"],
        ["M", "No, please give it to the librarian. I'll pick it up on Friday."],
        ["W", "What does it look like?"],
        ["M", "Blue, with a small bear on the zip."],
        ["W", "Got it. I'll do it before I leave."],
      ],
      choices: ["책을 빌려 주기", "필통을 사서 관리자에게 맡기기", "필통을 가져다주기", "필통을 사서 주기", "책을 반납해 주기"],
      answer: 2,
      clue: "No, please give it to the librarian. I'll pick it up on Friday.",
      explanation:
        "남자는 도서관에 두고 온 필통을 사서 선생님께 맡겨 달라고 부탁한다. 가져다 달라는 것이 아니다. 따라서 답은 ②이다.",
      translation: [
        "M: 나리야, 방과 후에 도서관 가?",
        "W: 응, 책 두 권 반납해야 해.",
        "M: 거기 있는 동안 하나만 부탁할게.",
        "W: 그래. 뭔데?",
        "M: 창가 탁자에 필통을 두고 왔어.",
        "W: 내일 가져다줄까?",
        "M: 아니, 사서 선생님께 맡겨 줘. 금요일에 찾아갈게.",
        "W: 어떻게 생겼어?",
        "M: 파란색이고 지퍼에 작은 곰이 달려 있어.",
        "W: 알겠어. 나오기 전에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, School Photo Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Here is news about School Photo Day."],
        ["W", "It will be held next Wednesday, in the morning."],
        ["W", "Each class comes to the gym in order, starting with the first years."],
        ["W", "Wear your full school uniform, with the tie."],
        ["W", "The photos will be sent home at the end of the month."],
        ["W", "Please be on time; the whole day runs on one schedule."],
      ],
      choices: ["열리는 날", "장소", "복장", "사진 받는 때", "촬영 순서 기준"],
      answer: 5,
      clue: "Wear your full school uniform, with the tie.",
      explanation:
        "날짜(다음 주 수요일 오전), 장소(체육관), 복장(교복과 넥타이), 사진 받는 때(이달 말)는 언급되지만 촬영 순서를 어떤 기준으로 정하는지는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. School Photo Day 소식입니다.",
        "W: 다음 주 수요일 오전에 있습니다.",
        "W: 1학년부터 차례로 반마다 체육관으로 옵니다.",
        "W: 교복을 다 갖춰 입고 넥타이도 매세요.",
        "W: 사진은 이달 말에 집으로 보내 드립니다.",
        "W: 시간을 지켜 주세요. 하루가 하나의 일정으로 돌아갑니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You see this in every classroom, usually at the front."],
        ["M", "It is a wide flat board on the wall."],
        ["M", "Teachers write on it with a pen that wipes off."],
        ["M", "There is a small tray under it for the pens and the eraser."],
        ["M", "At the end of class someone always has to wipe it clean."],
      ],
      choices: ["게시판", "사물함", "창문", "책상", "칠판"],
      answer: 5,
      clue: "Teachers write on it with a pen that wipes off.",
      explanation:
        "교실 앞 벽에 있는 넓고 평평한 판으로 지워지는 펜으로 쓰고 아래에 펜 놓는 받침이 있다고 했으므로 칠판이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 이것은 교실마다, 보통 앞쪽에 있습니다.",
        "M: 벽에 붙은 넓고 평평한 판입니다.",
        "M: 선생님은 지워지는 펜으로 거기에 씁니다.",
        "M: 그 아래에는 펜과 지우개를 놓는 작은 받침이 있습니다.",
        "M: 수업이 끝나면 늘 누군가 닦아야 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How was the test?"],
        ["M", "Harder than I expected."],
        ["W", "Could you help me carry this?"],
        ["M", "Of course."],
        ["W", "What's your favourite season?"],
        ["M", "Autumn, because of the weather."],
        ["W", "Who is your homeroom teacher?"],
        ["M", "I had toast for breakfast."],
        ["W", "Shall we meet at six?"],
        ["M", "Six is fine with me."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is your homeroom teacher?",
      explanation:
        "담임 선생님이 누구냐는 물음에 아침에 토스트를 먹었다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① W: 시험 어땠어? / M: 생각보다 어려웠어.",
        "② W: 이거 같이 들어 줄래? / M: 그럼.",
        "③ W: 어느 계절을 제일 좋아해? / M: 가을, 날씨 때문에.",
        "④ W: 담임 선생님이 누구야? / M: 나 아침에 토스트 먹었어.",
        "⑤ W: 6시에 만날까? / M: 6시 좋아.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, the class play starts in fifteen minutes."],
        ["W", "Is the stage ready? What should I do?"],
        ["M", "I've set up the chairs and tested the lights."],
        ["W", "Should I hand out the programmes?"],
        ["M", "Junho is doing that at the door."],
        ["W", "Then what's left?"],
        ["M", "The hats for the second scene are still in the classroom."],
        ["W", "I'll run and get them now."],
        ["M", "Thanks. I'll close the curtains while you're gone."],
      ],
      choices: ["의자 놓기", "조명 확인하기", "안내지 나눠 주기", "모자 가져오기", "막 내리기"],
      answer: 4,
      clue: "I'll run and get them now.",
      explanation:
        "의자와 조명, 안내지는 이미 해결되었으므로 여자는 교실에 있는 모자를 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 다인아, 학급 연극이 15분 뒤에 시작해.",
        "W: 무대는 준비됐어? 내가 뭘 할까?",
        "M: 의자는 놨고 조명도 확인했어.",
        "W: 안내지를 나눠 줄까?",
        "M: 준호가 문 앞에서 나눠 주고 있어.",
        "W: 그럼 뭐가 남았어?",
        "M: 두 번째 장면에 쓸 모자가 아직 교실에 있어.",
        "W: 내가 지금 가서 가져올게.",
        "M: 고마워. 네가 간 사이에 막을 내려 둘게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 동아리를 고르시오.",
      lines: [
        ["W", "Junseo, these are the five clubs still taking new members."],
        ["M", "Let's see. I can't do Wednesdays because of my piano lesson."],
        ["W", "Then one is out. What else?"],
        ["M", "It has to be indoors. I don't want to be outside in winter."],
        ["W", "One is outdoors, so that's gone too."],
        ["M", "Three left. How many people are in each one?"],
        ["W", "You said you wanted a small one, under fifteen."],
        ["M", "Then one more drops out. Two are left."],
        ["W", "Do they both meet once a week?"],
        ["M", "Only one does. The other meets twice, and that's too much."],
        ["W", "Then that settles it. Sign up tomorrow."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Then that settles it. Sign up tomorrow.",
      explanation:
        "수요일인 ①, 야외인 ②, 스무 명인 ③을 뺀다. 남은 ④와 ⑤ 중 주 1회 모이는 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "수요일 / 실내 / 12명 / 주 1회" },
          { no: 2, label: "②", value: "금요일 / 야외 / 12명 / 주 1회" },
          { no: 3, label: "③", value: "금요일 / 실내 / 20명 / 주 1회" },
          { no: 4, label: "④", value: "금요일 / 실내 / 10명 / 주 2회" },
          { no: 5, label: "⑤", value: "금요일 / 실내 / 14명 / 주 1회" },
        ],
      },
      translation: [
        "W: 준서야, 아직 부원을 받는 동아리가 이 다섯 개야.",
        "M: 보자. 피아노 수업 때문에 수요일은 안 돼.",
        "W: 그럼 하나 빠지네. 또 뭐가 있어?",
        "M: 실내여야 해. 겨울에 밖에 있고 싶지 않아.",
        "W: 하나는 야외니까 그것도 빠져.",
        "M: 셋 남았다. 각각 몇 명이야?",
        "W: 열다섯 명 안 되는 작은 데가 좋다고 했잖아.",
        "M: 그럼 하나 더 빠지고 둘 남았다.",
        "W: 둘 다 주 1회 모여?",
        "M: 한 곳만. 다른 하나는 주 2회라 너무 많아.",
        "W: 그럼 정해졌네. 내일 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 박물관에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Chaewon, when should we go to the museum?"],
        ["W", "The dinosaur exhibition runs on the fifteenth, sixteenth, and seventeenth."],
        ["M", "What can we see there?"],
        ["W", "A whole skeleton, and you can touch a real bone."],
        ["M", "Sounds great. But I have swimming class on the fifteenth."],
        ["W", "Then the sixteenth or the seventeenth."],
        ["M", "Isn't the seventeenth the day of the school picnic?"],
        ["W", "You're right, I forgot. We'd be out all day."],
        ["M", "So only the sixteenth is left."],
        ["W", "Then let's go on the sixteenth. I'll ask my mother tonight."],
      ],
      choices: ["14일", "15일", "16일", "17일", "18일"],
      answer: 3,
      clue: "So only the sixteenth is left.",
      explanation:
        "15일은 수영 수업, 17일은 소풍이어서 16일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 채원아, 박물관에 언제 갈까?",
        "W: 공룡 전시가 15일, 16일, 17일에 열려.",
        "M: 거기서 뭘 볼 수 있는데?",
        "W: 뼈대 전체, 그리고 진짜 뼈를 만져 볼 수도 있어.",
        "M: 좋겠다. 그런데 나 15일에 수영 수업이 있어.",
        "W: 그럼 16일이나 17일이네.",
        "M: 17일은 소풍 가는 날 아니야?",
        "W: 맞다, 잊었네. 하루 종일 밖에 있잖아.",
        "M: 그럼 16일만 남네.",
        "W: 그럼 16일에 가자. 오늘 밤에 엄마한테 여쭤볼게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayoon, did you go to the concert on Saturday?"],
        ["W", "No, I stayed at home and painted my bookshelf."],
        ["M", "Painted it? What colour?"],
        ["W", "White. It was brown before and the room looked dark."],
        ["M", "Did you do it by yourself?"],
        ["W", "My father helped me take the books out first."],
        ["M", "How many books were there?"],
        ["W", "About ninety. Putting them back took longer than the painting."],
        ["M", "So the whole day went on one bookshelf."],
        ["W", "The whole day. But the room looks twice as bright now."],
      ],
      choices: ["음악회 가기", "책 읽기", "책장 칠하기", "책 사러 가기", "방 청소하기"],
      answer: 3,
      clue: "No, I stayed at home and painted my bookshelf.",
      explanation:
        "여자는 지난 토요일에 집에서 책장을 흰색으로 칠했다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "M: 하윤아, 토요일에 음악회 갔어?",
        "W: 아니, 집에서 책장 칠했어.",
        "M: 칠했다고? 무슨 색으로?",
        "W: 흰색. 원래 갈색이라 방이 어두워 보였거든.",
        "M: 혼자 했어?",
        "W: 아빠가 책 빼는 걸 도와주셨어.",
        "M: 책이 몇 권이나 있었는데?",
        "W: 아흔 권쯤. 다시 꽂는 게 칠하는 것보다 오래 걸렸어.",
        "M: 그럼 하루를 통째로 책장 하나에 쓴 거네.",
        "W: 하루 종일. 그래도 방이 두 배로 밝아 보여.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "The lift in the main building will be stopped all day tomorrow."],
        ["M", "Engineers are checking it, as they do every year."],
        ["M", "Please use the stairs, and leave a few minutes earlier."],
        ["M", "Students who cannot use the stairs should tell their homeroom teacher today."],
        ["M", "Thank you for your understanding."],
      ],
      choices: [
        "계단을 뛰지 말라고 하려고",
        "승강기가 멈춘다고 알리려고",
        "등교 시간을 바꾸려고",
        "담임 선생님을 찾아가라고 하려고",
        "건물 청소를 부탁하려고",
      ],
      answer: 2,
      clue: "The lift in the main building will be stopped all day tomorrow.",
      explanation:
        "내일 하루 승강기가 멈춘다는 것과 그에 따른 안내를 하는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 내일 하루 본관 승강기가 멈춥니다.",
        "M: 해마다 하는 점검을 기사님들이 합니다.",
        "M: 계단을 이용하고 몇 분 일찍 나오세요.",
        "M: 계단을 쓰기 어려운 학생은 오늘 담임 선생님께 말씀드리세요.",
        "M: 이해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the ice cream shop. What would you like?"],
        ["W", "Three cones, please."],
        ["M", "Cones are three dollars each."],
        ["W", "So nine dollars."],
        ["M", "That's right. Would you like a bottle of water too?"],
        ["W", "How much is it?"],
        ["M", "Two dollars."],
        ["W", "Then one bottle, please."],
        ["M", "All right. And we take two dollars off if you buy three or more cones."],
        ["W", "Great. Here you are."],
      ],
      choices: ["$8", "$9", "$10", "$11", "$12"],
      answer: 2,
      clue: "All right. And we take two dollars off if you buy three or more cones.",
      explanation:
        "콘 3달러씩 세 개는 9달러, 물 2달러를 더하면 11달러이다. 세 개 이상 할인 2달러를 빼면 9달러이므로 답은 ②이다.",
      translation: [
        "M: 아이스크림 가게입니다. 무엇을 드릴까요?",
        "W: 콘 세 개 주세요.",
        "M: 콘은 하나에 3달러입니다.",
        "W: 그럼 9달러네요.",
        "M: 맞습니다. 물도 한 병 하시겠어요?",
        "W: 얼마예요?",
        "M: 2달러입니다.",
        "W: 그럼 한 병 주세요.",
        "M: 알겠습니다. 그리고 콘을 세 개 이상 사시면 2달러 빼 드립니다.",
        "W: 좋네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sumin, you've lost your umbrella twice this month."],
        ["W", "I know. My mother is not happy about it."],
        ["M", "Where do you lose them, though?"],
        ["W", "Always at school, and always when the rain stops."],
        ["M", "So you walk out without it."],
        ["W", "I forget I even brought one."],
        ["M", "Where do you put it when you come inside?"],
        ["W", "By the door, in the stand, with all the others."],
        ["M", "And they all look the same, I suppose."],
        ["W", "Exactly. Twenty black umbrellas and I can't tell which one is mine."],
        ["M", "Then even when you remember, you can't find it."],
        ["W", "Last time I took someone else's by mistake."],
        ["M", "Tie something bright on the handle."],
      ],
      choices: [
        "My umbrella is blue.",
        "It rained all day yesterday.",
        "Then I'll tie a ribbon on it today.",
        "I have two umbrellas at home.",
        "You should buy a new one.",
      ],
      answer: 3,
      clue: "Tie something bright on the handle.",
      explanation:
        "손잡이에 눈에 띄는 것을 묶어 두라는 조언을 들었으므로, 오늘 리본을 묶겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 수민아, 이번 달에 우산을 두 번이나 잃어버렸네.",
        "W: 알아. 엄마가 좋아하지 않으셔.",
        "M: 그런데 어디서 잃어버리는데?",
        "W: 늘 학교에서, 그리고 늘 비가 그쳤을 때.",
        "M: 그럼 그냥 두고 나오는 거네.",
        "W: 가져온 것도 잊어버려.",
        "M: 안에 들어오면 우산을 어디에 둬?",
        "W: 문 옆 꽂이에, 다른 것들이랑 같이.",
        "M: 그리고 다 똑같이 생겼겠지.",
        "W: 그래. 검은 우산 스무 개 중에 어느 게 내 건지 알 수가 없어.",
        "M: 그럼 기억이 나도 못 찾겠네.",
        "W: 지난번엔 남의 걸 잘못 가져갔어.",
        "M: 손잡이에 눈에 띄는 걸 묶어 둬.",
        "W: 그럼 오늘 리본을 묶을게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Taemin, you looked tired in class all week."],
        ["M", "I've been falling asleep in the fourth period."],
        ["W", "What time do you go to bed?"],
        ["M", "Eleven, the same as always. That's what I don't understand."],
        ["W", "Eleven is early enough. Do you fall asleep then?"],
        ["M", "No. I lie there for ages."],
        ["W", "What do you do in bed before you turn the light off?"],
        ["M", "I watch videos until my eyes hurt."],
        ["W", "For how long?"],
        ["M", "An hour, maybe more. I don't really count."],
        ["W", "And then the light goes off and nothing happens."],
        ["M", "Nothing happens for another hour, yes."],
        ["W", "Put the phone down half an hour before you lie down."],
      ],
      choices: [
        "My room is very quiet.",
        "Then I'll stop watching at ten thirty.",
        "I usually watch cooking videos.",
        "The bed is next to the window.",
        "You should sleep earlier too.",
      ],
      answer: 2,
      clue: "Put the phone down half an hour before you lie down.",
      explanation:
        "눕기 30분 전에 휴대전화를 내려놓으라는 조언을 들었으므로, 10시 30분에 그만 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 태민아, 일주일 내내 수업 때 피곤해 보였어.",
        "M: 4교시마다 졸고 있어.",
        "W: 몇 시에 자는데?",
        "M: 11시, 늘 그랬어. 그래서 이해가 안 돼.",
        "W: 11시면 이른데. 그때 바로 잠들어?",
        "M: 아니. 한참 누워 있어.",
        "W: 불 끄기 전에 침대에서 뭐 해?",
        "M: 눈이 아플 때까지 영상을 봐.",
        "W: 얼마나?",
        "M: 한 시간, 아마 더. 세어 본 적은 없어.",
        "W: 그러고 불을 끄면 아무 일도 안 일어나고.",
        "M: 또 한 시간 아무 일도 안 일어나지.",
        "W: 눕기 30분 전에는 휴대전화를 내려놔.",
        "M: 그럼 10시 30분에 그만 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Jiwoo, how is the class plant corner going?"],
        ["W", "Not well. Two of the four plants have died."],
        ["M", "Which two?"],
        ["W", "The small ones by the window. The leaves went brown."],
        ["M", "Brown leaves usually mean too little water."],
        ["W", "Or too much. That's the part nobody can tell."],
        ["M", "Well, who waters them?"],
        ["W", "Whoever is on cleaning duty that day."],
        ["M", "So a different person every single day."],
        ["W", "And nobody knows what the person before them did."],
        ["M", "So some days they get water twice and some days none."],
        ["W", "That's exactly what I think happened."],
        ["M", "Put a small card beside them and write the date each time."],
      ],
      choices: [
        "The plants are by the window.",
        "We started the corner in May.",
        "Then I'll make a card tomorrow.",
        "I water them on Mondays.",
        "You should take one home.",
      ],
      answer: 3,
      clue: "Put a small card beside them and write the date each time.",
      explanation:
        "옆에 작은 카드를 두고 물 준 날짜를 적으라는 조언을 들었으므로, 내일 카드를 만들겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 지우야, 학급 화분 코너는 잘돼 가?",
        "W: 잘 안돼. 네 개 중 두 개가 죽었어.",
        "M: 어느 거?",
        "W: 창가에 있던 작은 것들. 잎이 갈색이 됐어.",
        "M: 잎이 갈색이면 보통 물이 모자란 거야.",
        "W: 아니면 너무 많거나. 그걸 아무도 모르겠다는 게 문제야.",
        "M: 그럼 누가 물을 주는데?",
        "W: 그날 청소 당번이.",
        "M: 그럼 날마다 사람이 다르네.",
        "W: 그리고 앞사람이 뭘 했는지 아무도 몰라.",
        "M: 어떤 날은 두 번 주고 어떤 날은 아예 안 주겠네.",
        "W: 딱 그렇게 됐을 거라고 생각해.",
        "M: 옆에 작은 카드를 두고 줄 때마다 날짜를 적어.",
        "W: 그럼 내일 카드를 만들게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yerin이 Dohun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Yerin : ________________",
      lines: [
        ["W", "Yerin and Dohun are making a poster for the school library."],
        ["W", "Dohun has drawn the pictures and coloured them carefully."],
        ["W", "The pictures take up almost the whole poster."],
        ["W", "There is only a small space left at the bottom for the words."],
        ["W", "The poster has to say when the library opens and closes."],
        ["W", "Yerin does not want to say that his pictures are too big."],
        ["W", "She wants to suggest moving one picture to leave room for the words."],
        ["W", "In this situation, what would Yerin most likely say to Dohun?"],
      ],
      choices: [
        "Let's draw the pictures again in black and white.",
        "You should write the words yourself.",
        "Could we move one picture to make room for the words?",
        "I'll make a different poster on my own.",
        "The library opens at nine.",
      ],
      answer: 3,
      clue: "She wants to suggest moving one picture to leave room for the words.",
      explanation:
        "예린이는 도훈이의 그림을 깎아내리지 않으면서, 그림 하나를 옮겨 글자 자리를 만들자고 말하려 한다. 따라서 ③이 가장 적절하다.",
      translation: [
        "W: 예린이와 도훈이는 학교 도서관 포스터를 만들고 있습니다.",
        "W: 도훈이가 그림을 그리고 색도 꼼꼼히 칠했습니다.",
        "W: 그림이 포스터를 거의 다 차지합니다.",
        "W: 글자를 넣을 자리는 아래쪽에 조금밖에 남지 않았습니다.",
        "W: 포스터에는 도서관이 몇 시에 열고 닫는지 적어야 합니다.",
        "W: 예린이는 도훈이의 그림이 너무 크다고 말하고 싶지는 않습니다.",
        "W: 다만 그림 하나를 옮겨 글자 자리를 만들자고 제안하고 싶습니다.",
        "W: 이런 상황에서 예린이가 도훈이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
