/** 중1 듣기 49회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 49회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 두 사람이 만들 학급 안내판을 고르시오.",
      lines: [
        ["W", "Hyunsu, how should we design the class sign?"],
        ["M", "Let's start with the shape of the board."],
        ["W", "A long rectangle holds more words than a circle."],
        ["M", "A rectangle, then. What goes on the left side?"],
        ["W", "A drawing of an open book would suit us."],
        ["M", "Should we add an arrow under the book?"],
        ["W", "No arrow. It makes the board look crowded."],
        ["M", "Then a plain border around the whole thing."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "A rectangle, then. What goes on the left side? / No arrow. It makes the board look crowded.",
      explanation:
        "두 사람은 직사각형 판 왼쪽에 펼친 책 그림이 있고 화살표는 없으며 테두리가 둘린 안내판을 만들기로 했다. 따라서 답은 ①이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five blank sign boards side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a wide RECTANGULAR board with a plain BORDER line, an OPEN BOOK drawn on the LEFT side, no arrow. " +
          "② a wide RECTANGULAR board with an OPEN BOOK on the left and a big ARROW under the book. " +
          "③ a ROUND board with an OPEN BOOK drawn in the middle. " +
          "④ a wide RECTANGULAR board with a MUSIC NOTE on the left instead of a book. " +
          "⑤ a ROUND board with an OPEN BOOK and an ARROW under it.",
      },
      translation: [
        "W: 현수야, 학급 안내판을 어떻게 만들까?",
        "M: 판 모양부터 정하자.",
        "W: 긴 직사각형이 동그라미보다 글자가 더 들어가.",
        "M: 그럼 직사각형으로. 왼쪽에는 뭘 넣지?",
        "W: 펼친 책 그림이 우리한테 어울릴 것 같아.",
        "M: 책 아래에 화살표도 넣을까?",
        "W: 화살표는 빼자. 판이 복잡해 보여.",
        "M: 그럼 전체에 단순한 테두리만 두르자.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 여름 봉사 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Nahee, are you applying for the summer volunteer camp?"],
        ["W", "I want to. How many days does it last?"],
        ["M", "Three days and two nights in August."],
        ["W", "Where do the students stay at night?"],
        ["M", "In the dormitory of a country middle school."],
        ["W", "What kind of work do we actually do?"],
        ["M", "We paint walls and clean up a village library."],
        ["W", "How many students can join?"],
        ["M", "Only twenty, so apply early."],
      ],
      choices: [
        "캠프 기간",
        "묵는 곳",
        "하는 일",
        "참가 인원",
        "지도하는 선생님",
      ],
      answer: 5,
      clue: "Three days and two nights in August.",
      explanation:
        "기간, 숙소, 하는 일, 인원은 말했지만 지도 교사는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 나희야, 여름 봉사 캠프 신청할 거야?",
        "W: 하고 싶어. 며칠 동안 해?",
        "M: 8월에 2박 3일.",
        "W: 밤에는 어디서 자?",
        "M: 시골 중학교 기숙사에서.",
        "W: 실제로 무슨 일을 해?",
        "M: 벽을 칠하고 마을 도서관을 정리해.",
        "W: 몇 명이나 갈 수 있어?",
        "M: 스무 명뿐이라 일찍 신청해야 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Minseok. This is Jieun from class three."],
        ["M", "Hi, Jieun. Is something up?"],
        ["W", "You lent me your history notes last Friday."],
        ["M", "Right, I almost forgot about those."],
        ["W", "I finished copying them last night."],
        ["M", "No hurry. I'm not using them yet."],
        ["W", "Still, I don't want to keep them too long."],
        ["M", "That's kind of you."],
        ["W", "I'd like to give them back tomorrow morning."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "도움을 요청하려고",
        "감사를 전하려고",
        "빌린 것을 돌려주려고",
      ],
      answer: 5,
      clue: "I'd like to give them back tomorrow morning.",
      explanation:
        "여자는 빌린 필기를 내일 아침에 돌려주려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 민석아. 3반 지은이야.",
        "M: 안녕, 지은아. 무슨 일이야?",
        "W: 지난 금요일에 네 역사 필기 빌렸잖아.",
        "M: 맞다, 그거 거의 잊고 있었어.",
        "W: 어젯밤에 다 베껴 썼어.",
        "M: 급하지 않아. 아직 안 써.",
        "W: 그래도 너무 오래 갖고 있기 싫어.",
        "M: 고맙네.",
        "W: 내일 아침에 돌려주고 싶어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 영화를 볼 시각을 고르시오.",
      lines: [
        ["W", "Dohun, what time is the movie you wanted to see?"],
        ["M", "There are showings at six, seven and eight."],
        ["W", "My last class finishes at six fifteen."],
        ["M", "Then the six o'clock showing is out."],
        ["W", "How long does it take to get to the theater?"],
        ["M", "Twenty minutes if we walk fast."],
        ["W", "The seven o'clock one is a little tight."],
        ["M", "We can make it if we leave right away."],
        ["W", "All right, let's take the seven o'clock showing."],
      ],
      choices: ["6:00 p.m.", "6:15 p.m.", "7:00 p.m.", "8:00 p.m.", "7:30 p.m."],
      answer: 3,
      clue: "All right, let's take the seven o'clock showing.",
      explanation:
        "6시 상영은 수업 때문에 못 보고 7시 상영을 보기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 도훈아, 네가 보고 싶다던 영화 몇 시야?",
        "M: 6시, 7시, 8시 상영이 있어.",
        "W: 내 마지막 수업이 6시 15분에 끝나.",
        "M: 그럼 6시 상영은 안 되겠다.",
        "W: 극장까지 얼마나 걸려?",
        "M: 빨리 걸으면 20분.",
        "W: 7시 상영은 좀 빠듯한데.",
        "M: 바로 출발하면 갈 수 있어.",
        "W: 알겠어, 7시 상영으로 하자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junhyeok, why do you keep looking at the door?"],
        ["M", "My little brother should have come home an hour ago."],
        ["W", "Did you call his phone?"],
        ["M", "It rings and rings, and nobody picks up."],
        ["W", "Maybe he stayed at a friend's house."],
        ["M", "He always tells me before he does that."],
        ["W", "Have you told your parents yet?"],
        ["M", "I can't stop imagining bad things right now."],
      ],
      choices: ["happy", "bored", "proud", "worried", "jealous"],
      answer: 4,
      clue: "I can't stop imagining bad things right now.",
      explanation:
        "동생이 늦게까지 연락이 되지 않아 걱정하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 준혁아, 왜 자꾸 문만 봐?",
        "M: 동생이 한 시간 전에 집에 왔어야 해.",
        "W: 전화해 봤어?",
        "M: 계속 울리는데 아무도 안 받아.",
        "W: 친구 집에 있는 거 아닐까?",
        "M: 그럴 때는 항상 나한테 말해.",
        "W: 부모님께는 말씀드렸어?",
        "M: 자꾸 나쁜 생각만 들어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is this the line for tickets?"],
        ["M", "No, that line is over there."],
        ["ANN", "Number two."],
        ["W", "My train leaves in five minutes."],
        ["M", "Then you should hurry to platform two."],
        ["ANN", "Number three."],
        ["W", "Where can I leave my suitcase?"],
        ["M", "There are lockers downstairs."],
        ["ANN", "Number four."],
        ["W", "Does this train stop at Daejeon?"],
        ["M", "Yes, it's the third stop."],
        ["ANN", "Number five."],
        ["W", "I think I dropped my ticket."],
        ["M", "It's right there by your foot."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I think I dropped my ticket.",
      explanation:
        "그림은 기차역에서 여자가 표를 찾고 남자가 발밑의 표를 가리키는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a train station hall, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman with a shoulder bag searches through her empty hands with a worried face. " +
          "A man beside her bends slightly and points down at a small rectangular paper ticket lying on the floor near her shoe. " +
          "A ticket gate and waiting benches are drawn simply in the background.",
      },
      translation: [
        "① W: 여기가 표 사는 줄인가요? / M: 아니요, 그 줄은 저쪽입니다.",
        "② W: 제 기차가 5분 뒤에 떠나요. / M: 그럼 2번 승강장으로 서두르세요.",
        "③ W: 여행 가방은 어디에 둘 수 있나요? / M: 아래층에 보관함이 있어요.",
        "④ W: 이 기차 대전에 서나요? / M: 네, 세 번째 정거장이에요.",
        "⑤ W: 표를 떨어뜨린 것 같아요. / M: 발밑에 바로 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kyungmin, do you still have the class camera?"],
        ["M", "It's in my locker until Friday."],
        ["W", "Our group finishes its project tomorrow."],
        ["M", "Do you need photos of the finished work?"],
        ["W", "The teacher asked for pictures of every step."],
        ["M", "When are you putting it together?"],
        ["W", "Tomorrow, during the fifth and sixth periods."],
        ["M", "I have a free period then."],
        ["W", "Could you take photos during our work tomorrow?"],
        ["M", "Sure, I'll bring the camera at lunch."],
      ],
      choices: [
        "사진을 찍어 주기",
        "사물함을 빌려주기",
        "과제를 도와주기",
        "선생님께 여쭤보기",
        "자료를 보내 주기",
      ],
      answer: 1,
      clue: "Could you take photos during our work tomorrow?",
      explanation:
        "여자는 내일 작업하는 동안 사진을 찍어 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 경민아, 학급 사진기 아직 가지고 있어?",
        "M: 금요일까지 내 사물함에 있어.",
        "W: 우리 조가 내일 과제를 끝내.",
        "M: 완성된 작품 사진이 필요해?",
        "W: 선생님이 단계마다 사진을 찍어 오라고 하셨어.",
        "M: 언제 만들어?",
        "W: 내일 5교시랑 6교시에.",
        "M: 그때 나는 공강이야.",
        "W: 내일 작업하는 동안 사진 좀 찍어 줄래?",
        "M: 그래, 점심때 사진기 가져올게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 겨울 방학 특강에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Let me explain the winter special classes. " +
            "They run for two weeks in the first half of January. " +
            "Classes are held in the morning, from nine to twelve. " +
            "We offer English, mathematics and coding this winter. " +
            "Sign up on the paper outside the teachers' room. " +
            "The list closes when forty students have written their names.",
        ],
      ],
      choices: [
        "특강 기간",
        "수업 시간",
        "열리는 과목",
        "신청하는 방법",
        "수업을 맡는 선생님",
      ],
      answer: 5,
      clue: "They run for two weeks in the first half of January.",
      explanation:
        "기간, 시간, 과목, 신청 방법은 말했지만 담당 교사는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 겨울 특강에 대해 알려 드립니다. 1월 전반부에 2주 동안 진행합니다. 수업은 오전 아홉 시부터 열두 시까지입니다. 이번 겨울에는 영어, 수학, 코딩을 엽니다. 교무실 앞 종이에 신청해 주세요. 마흔 명이 이름을 적으면 마감합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a place where you go when you are sick. " +
            "A doctor checks you and decides what is wrong. " +
            "Nurses take your temperature before you go in. " +
            "You may wait a long time on a busy morning. " +
            "You usually get a paper for medicine when you leave.",
        ],
      ],
      choices: ["약국", "은행", "우체국", "병원", "도서관"],
      answer: 4,
      clue: "A doctor checks you and decides what is wrong.",
      explanation:
        "의사가 진찰하고 간호사가 체온을 재며 처방전을 받는 곳은 병원이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이곳은 아플 때 가는 곳입니다. 의사가 진찰하고 어디가 아픈지 판단합니다. 들어가기 전에 간호사가 체온을 잽니다. 붐비는 아침에는 오래 기다릴 수도 있습니다. 나올 때는 보통 약을 받을 종이를 받습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How do you get to school?"],
        ["W", "I usually ride my bike."],
        ["ANN", "Number two."],
        ["M", "Could I borrow your eraser?"],
        ["W", "Here, keep it if you want."],
        ["ANN", "Number three."],
        ["M", "When did you move here?"],
        ["W", "I have two younger brothers."],
        ["ANN", "Number four."],
        ["M", "Are you free this Saturday?"],
        ["W", "In the afternoon, yes."],
        ["ANN", "Number five."],
        ["M", "What should we bring to the picnic?"],
        ["W", "Just something to drink."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "When did you move here?",
      explanation:
        "언제 이사 왔는지 묻는 말에 동생 수를 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 학교에 어떻게 와? / W: 보통 자전거 타고 와.",
        "② M: 지우개 좀 빌려줄래? / W: 여기, 필요하면 가져.",
        "③ M: 여기 언제 이사 왔어? / W: 나는 남동생이 둘 있어.",
        "④ M: 이번 토요일에 시간 있어? / W: 오후에는 있어.",
        "⑤ M: 소풍에 뭘 가져갈까? / W: 마실 것만 가져와.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junyoung, the rain is getting heavier outside."],
        ["M", "I left my bike by the front gate this morning."],
        ["W", "Is the seat covered with anything?"],
        ["M", "No, and the cover is inside my locker."],
        ["W", "A wet seat takes two days to dry."],
        ["M", "I can't ride it home like that."],
        ["W", "You still have ten minutes before class."],
        ["M", "I'll go put the cover on it now."],
      ],
      choices: [
        "자전거를 타고 집에 가기",
        "우산을 빌리기",
        "자전거에 덮개를 씌우러 가기",
        "교실에서 기다리기",
        "선생님께 말씀드리기",
      ],
      answer: 3,
      clue: "I'll go put the cover on it now.",
      explanation:
        "남자는 지금 자전거에 덮개를 씌우러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 준영아, 밖에 비가 점점 세져.",
        "M: 아침에 정문 옆에 자전거 세워 뒀어.",
        "W: 안장은 뭘로 덮어 놨어?",
        "M: 아니, 덮개는 사물함 안에 있어.",
        "W: 안장이 젖으면 이틀은 말려야 해.",
        "M: 그렇게 해서는 집에 못 타고 가.",
        "W: 수업까지 아직 10분 남았어.",
        "M: 지금 가서 덮개 씌우고 올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 예약할 숙소를 고르시오.",
      lines: [
        ["M", "Chaerin, let's pick a place for the club trip."],
        ["W", "Five rooms are still open on this page."],
        ["M", "We need a room for eight people."],
        ["W", "Two of them hold only six."],
        ["M", "And breakfast should be included."],
        ["W", "Not every place serves breakfast."],
        ["M", "Our budget is one hundred thousand won a night."],
        ["W", "One of them costs a lot more than that."],
        ["M", "Then only one place works for us."],
        ["W", "I'll reserve it right after this class."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "We need a room for eight people.",
      explanation:
        "8인실, 조식 포함, 10만 원 이하인 곳을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Capacity: 6 / Breakfast: Yes / Price: 90,000 won" },
          { no: 2, label: "②", value: "Capacity: 8 / Breakfast: No / Price: 85,000 won" },
          { no: 3, label: "③", value: "Capacity: 6 / Breakfast: No / Price: 70,000 won" },
          { no: 4, label: "④", value: "Capacity: 8 / Breakfast: Yes / Price: 130,000 won" },
          { no: 5, label: "⑤", value: "Capacity: 8 / Breakfast: Yes / Price: 98,000 won" },
        ],
      },
      translation: [
        "M: 채린아, 동아리 여행 숙소 정하자.",
        "W: 이 쪽에 다섯 곳이 아직 열려 있어.",
        "M: 우리는 여덟 명이 들어갈 방이 필요해.",
        "W: 두 곳은 여섯 명까지야.",
        "M: 그리고 아침 식사가 포함돼야 해.",
        "W: 다 주는 건 아니야.",
        "M: 예산은 하룻밤에 10만 원이야.",
        "W: 한 곳은 그보다 훨씬 비싸.",
        "M: 그럼 되는 곳은 하나뿐이네.",
        "W: 이 수업 끝나고 바로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 체육 대회를 준비할 날짜를 고르시오.",
      lines: [
        ["W", "Sungho, when should our class practice for sports day?"],
        ["M", "The playground is free on three afternoons."],
        ["W", "Which days are those exactly?"],
        ["M", "The eighth, the eleventh and the fifteenth."],
        ["W", "The eighth is too close to the English test."],
        ["M", "And the eleventh is the school health checkup."],
        ["W", "Nobody could run after all those tests."],
        ["M", "So the fifteenth is the only day left."],
        ["W", "I'll write the fifteenth on the class calendar."],
      ],
      choices: ["the 8th", "the 11th", "the 15th", "the 18th", "the 22nd"],
      answer: 3,
      clue: "So the fifteenth is the only day left.",
      explanation:
        "8일은 시험이 가깝고 11일은 건강 검진이어서 15일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "W: 성호야, 우리 반 체육 대회 연습 언제 할까?",
        "M: 운동장이 세 번 오후에 비어.",
        "W: 정확히 어떤 날들이야?",
        "M: 8일, 11일, 15일.",
        "W: 8일은 영어 시험이랑 너무 가까워.",
        "M: 그리고 11일은 학교 건강 검진이야.",
        "W: 그런 검사 다 받고 나서 아무도 못 뛰어.",
        "M: 그럼 남는 건 15일뿐이야.",
        "W: 학급 달력에 15일이라고 적을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 일요일에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minwoo, you look sunburned today."],
        ["M", "I climbed a mountain with my father on Sunday."],
        ["W", "Which mountain did you two go to?"],
        ["M", "The one about an hour north of the city."],
        ["W", "How long did the whole climb take?"],
        ["M", "Five hours up and down, with one long break."],
        ["W", "Wasn't it too hot for that?"],
        ["M", "We started at six, before the sun got strong."],
        ["W", "Would you go again next month?"],
        ["M", "Only if we start that early again."],
      ],
      choices: [
        "바다에 놀러 가기",
        "집에서 쉬기",
        "도서관에서 공부하기",
        "아버지와 등산을 하기",
        "친척 집을 방문하기",
      ],
      answer: 4,
      clue: "I climbed a mountain with my father on Sunday.",
      explanation:
        "남자는 일요일에 아버지와 산에 올랐다. 따라서 답은 ④이다.",
      translation: [
        "W: 민우야, 오늘 햇볕에 탄 것 같아.",
        "M: 일요일에 아버지랑 등산했어.",
        "W: 어느 산에 갔어?",
        "M: 도시에서 북쪽으로 한 시간쯤 되는 산.",
        "W: 전체 산행이 얼마나 걸렸어?",
        "M: 오르내리는 데 다섯 시간. 한 번 길게 쉬고.",
        "W: 너무 덥지 않았어?",
        "M: 해가 세지기 전인 여섯 시에 출발했어.",
        "W: 다음 달에 또 갈 거야?",
        "M: 그때도 그렇게 일찍 출발한다면.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school library. " +
            "Our reading room will be repainted this coming week. " +
            "The walls have not been painted for almost ten years. " +
            "The room stays closed from Monday until Thursday. " +
            "You may still borrow books at the front desk. " +
            "Return boxes are placed near the main entrance instead. " +
            "The reading room opens again on Friday morning.",
        ],
      ],
      choices: [
        "책을 기부해 달라고 하려고",
        "독서 대회를 알리려고",
        "열람실이 닫힌다고 알리려고",
        "연체된 책을 돌려 달라고 하려고",
        "새 책을 소개하려고",
      ],
      answer: 3,
      clue: "The room stays closed from Monday until Thursday.",
      explanation:
        "도색 작업으로 열람실이 며칠 닫힌다고 알리는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 학교 도서관입니다. 다음 주에 열람실을 새로 칠합니다. 벽을 칠한 지 거의 십 년이 되었습니다. 월요일부터 목요일까지 열람실은 닫습니다. 책은 접수대에서 계속 빌릴 수 있습니다. 대신 반납함을 정문 근처에 놓아 두었습니다. 열람실은 금요일 아침에 다시 엽니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you renting skates today?"],
        ["W", "Yes, two pairs for two hours, please."],
        ["M", "One pair for two hours is eight dollars."],
        ["W", "Do we need to rent gloves as well?"],
        ["M", "Gloves are required, and they're two dollars a pair."],
        ["W", "We brought our own gloves from home."],
        ["M", "Then you only pay for the skates."],
        ["W", "Is there a locker fee too?"],
        ["M", "One locker costs one dollar for the day."],
        ["W", "We'll take one locker. Here's my card."],
      ],
      choices: ["$16", "$17", "$18", "$20", "$21"],
      answer: 2,
      clue: "One pair for two hours is eight dollars.",
      explanation:
        "스케이트 두 켤레 16달러에 보관함 1달러를 더하면 17달러이다. 따라서 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 오늘 스케이트 빌리시나요?",
        "W: 네, 두 켤레 두 시간이요.",
        "M: 한 켤레 두 시간에 8달러입니다.",
        "W: 장갑도 빌려야 하나요?",
        "M: 장갑은 반드시 껴야 하고 한 켤레에 2달러입니다.",
        "W: 저희는 집에서 장갑을 가져왔어요.",
        "M: 그러면 스케이트 값만 내시면 됩니다.",
        "W: 보관함 요금도 있나요?",
        "M: 보관함 하나에 하루 1달러입니다.",
        "W: 하나만 쓸게요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dahye, how did you get better at math so fast?"],
        ["W", "I stopped looking at the answers too early."],
        ["M", "What do you do when you're really stuck?"],
        ["W", "I wait five more minutes before I check."],
        ["M", "Five minutes feels like a long time."],
        ["W", "It is, but that's when I actually learn."],
        ["M", "I usually give up after thirty seconds."],
        ["W", "Then the answer teaches you nothing."],
        ["M", "Could you sit with me during study time?"],
      ],
      choices: [
        "I don't study math.",
        "Okay, let's use the back table.",
        "You should check answers first.",
        "Math is impossible for you.",
        "I already finished the test.",
      ],
      answer: 2,
      clue: "Could you sit with me during study time?",
      explanation:
        "남자가 함께 앉아 달라고 했으므로, 뒤쪽 자리에서 하자는 ②가 가장 자연스럽다.",
      translation: [
        "M: 다혜야, 수학이 어떻게 그렇게 빨리 늘었어?",
        "W: 답을 너무 일찍 보는 걸 그만뒀어.",
        "M: 정말 막히면 어떻게 해?",
        "W: 확인하기 전에 5분을 더 기다려.",
        "M: 5분이면 길게 느껴지는데.",
        "W: 길지. 근데 그때 진짜로 배워.",
        "M: 나는 보통 30초면 포기해.",
        "W: 그러면 답이 아무것도 안 가르쳐 줘.",
        "M: 자습 시간에 나랑 같이 앉아 줄래?",
        "W: 좋아, 뒤쪽 자리에서 하자.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Wonjae, you've been writing in that notebook every day."],
        ["M", "I write three lines about my day before bed."],
        ["W", "Only three lines? That's short."],
        ["M", "Short enough that I never skip a night."],
        ["W", "Do you ever read the old pages again?"],
        ["M", "Every month, and I always find something surprising."],
        ["W", "Like what kind of thing?"],
        ["M", "Problems I worried about turned out to be small."],
        ["W", "Could I try writing like that too?"],
      ],
      choices: [
        "Of course, start with tonight.",
        "I stopped writing last year.",
        "You need a very thick notebook.",
        "Writing is a waste of time.",
        "I never read my notebook.",
      ],
      answer: 1,
      clue: "Could I try writing like that too?",
      explanation:
        "여자가 자기도 그렇게 써 보고 싶다고 했으므로, 오늘 밤부터 시작하라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 원재야, 그 공책에 매일 뭔가 쓰더라.",
        "M: 자기 전에 하루에 대해 세 줄씩 써.",
        "W: 세 줄만? 짧다.",
        "M: 짧으니까 하루도 안 빠뜨려.",
        "W: 예전 쪽을 다시 읽어 보기도 해?",
        "M: 한 달에 한 번. 늘 놀라운 게 있어.",
        "W: 어떤 게?",
        "M: 걱정했던 일이 사실은 작은 일이었다는 거.",
        "W: 나도 그렇게 써 봐도 될까?",
        "M: 그럼, 오늘 밤부터 시작해.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sujeong, are you still going to the swimming pool?"],
        ["W", "Twice a week, but I've been skipping lately."],
        ["M", "Is something making it hard to go?"],
        ["W", "The pool is thirty minutes away by bus."],
        ["M", "That's an hour of travel for one class."],
        ["W", "Exactly, and I get home after nine."],
        ["M", "There's a smaller pool near your apartment."],
        ["W", "Is the water there warm enough in winter?"],
        ["M", "My cousin swims there all year round."],
      ],
      choices: [
        "I'll visit that pool this week.",
        "I don't know how to swim.",
        "The bus is very comfortable.",
        "I quit swimming for good.",
        "There is no pool near me.",
      ],
      answer: 1,
      clue: "My cousin swims there all year round.",
      explanation:
        "가까운 수영장이 겨울에도 괜찮다고 했으므로, 이번 주에 가 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 수정아, 아직 수영장 다녀?",
        "W: 일주일에 두 번. 근데 요즘 자꾸 빠져.",
        "M: 가기 어려운 이유가 있어?",
        "W: 수영장이 버스로 30분 거리야.",
        "M: 수업 하나에 왕복 한 시간이네.",
        "W: 맞아, 집에 9시 넘어 와.",
        "M: 너희 아파트 근처에 작은 수영장이 있어.",
        "W: 거기 겨울에 물이 충분히 따뜻해?",
        "M: 내 사촌은 일 년 내내 거기서 수영해.",
        "W: 이번 주에 그 수영장에 가 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sieun이 Taeyang에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Sieun : ________________",
      lines: [
        [
          "W",
          "Sieun and Taeyang are on the same relay team for sports day. " +
            "Taeyang drops the baton during practice and looks very upset. " +
            "He tells Sieun that he will ruin the race for everyone. " +
            "Sieun knows there are still two weeks left to practice. " +
            "She wants to tell him that one mistake now does not matter. " +
            "In this situation, what would Sieun most likely say to Taeyang?",
        ],
      ],
      choices: [
        "You should leave the team today.",
        "We have two weeks to practice this.",
        "The race already finished.",
        "I will run instead of you.",
        "Let's stop practicing forever.",
      ],
      answer: 2,
      clue: "She wants to tell him that one mistake now does not matter.",
      explanation:
        "아직 2주가 남았으니 지금의 실수는 문제가 아니라는 뜻이므로 ②가 가장 적절하다.",
      translation: [
        "W: 시은이와 태양이는 체육 대회 계주에서 같은 팀입니다. 태양이가 연습 중에 배턴을 떨어뜨리고 몹시 속상해합니다. 태양이는 자기 때문에 경기를 망칠 거라고 시은이에게 말합니다. 시은이는 아직 연습할 시간이 2주 남았다는 것을 압니다. 시은이는 지금의 실수 하나는 문제가 아니라고 말해 주고 싶습니다. 이런 상황에서 시은이가 태양이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
