/** 중1 듣기 20회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 20회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 필통을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a pencil case?"],
        ["W", "Yes, one for my school bag."],
        ["M", "We have round ones and flat ones."],
        ["W", "A flat one, please. The round ones roll off my desk."],
        ["M", "All right. Do you want a small handle on it?"],
        ["W", "Yes, so I can hang it on my bag."],
        ["M", "Then two are left. One has hearts on it and one has no pattern."],
        ["W", "The one with hearts, please. My last one was plain and I lost it."],
        ["M", "Good choice. This one is also waterproof."],
        ["W", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "The one with hearts, please. My last one was plain and I lost it.",
      explanation:
        "여자는 납작한 필통을, 손잡이가 달린 것으로, 하트무늬가 있는 것을 고른다. 따라서 답은 ②이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five pencil cases shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing or letters anywhere. " +
          "Case 1: a FLAT wide pouch lying down, with a small loop HANDLE on top, completely blank with no pattern. " +
          "Case 2: a FLAT wide pouch lying down, with a small loop HANDLE on top, covered all over in small HEART shapes. " +
          "Case 3: a FLAT wide pouch lying down, the top edge bare with NO handle, covered all over in small HEART shapes. " +
          "Case 4: a ROUND TUBE-SHAPED case like a cylinder, with a small loop HANDLE on top, covered all over in small HEART shapes. " +
          "Case 5: a ROUND TUBE-SHAPED case like a cylinder, the top bare with NO handle, completely blank with no pattern.",
      },
      translation: [
        "M: 안녕하세요. 필통 찾으세요?",
        "W: 네, 책가방에 넣을 거예요.",
        "M: 둥근 것과 납작한 것이 있습니다.",
        "W: 납작한 걸로요. 둥근 건 책상에서 굴러떨어져요.",
        "M: 알겠습니다. 작은 손잡이가 있는 걸로 하시겠어요?",
        "W: 네, 가방에 걸 수 있게요.",
        "M: 그럼 두 개 남았네요. 하나는 하트무늬가 있고 하나는 무늬가 없습니다.",
        "W: 하트무늬로요. 지난번 건 무늬가 없어서 잃어버렸어요.",
        "M: 좋은 선택이세요. 이건 방수도 됩니다.",
        "W: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 동아리 발표회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, is your club performing at the club show?"],
        ["M", "We are, but I don't know the details yet."],
        ["W", "It's next Thursday, in the afternoon."],
        ["M", "Where do we perform?"],
        ["W", "On the stage in the big hall."],
        ["M", "How long does each club get?"],
        ["W", "Ten minutes, and they stop you at ten."],
        ["M", "Do we need to bring anything?"],
        ["W", "Just what you use in the performance."],
        ["M", "Then I'll tell my club tomorrow."],
      ],
      choices: ["열리는 날", "장소", "공연 시간", "준비물", "순서를 정하는 방법"],
      answer: 5,
      clue: "Just what you use in the performance.",
      explanation:
        "날짜(다음 주 목요일 오후), 장소(대강당 무대), 공연 시간(10분), 준비물(공연에 쓰는 것)은 언급되지만 순서를 정하는 방법은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 너희 동아리도 발표회 나가?",
        "M: 나가는데 자세한 건 아직 몰라.",
        "W: 다음 주 목요일 오후에 해.",
        "M: 어디서 공연하는데?",
        "W: 대강당 무대에서.",
        "M: 동아리마다 몇 분씩이야?",
        "W: 10분, 10분 되면 멈추게 해.",
        "M: 뭐 가져가야 해?",
        "W: 공연에 쓰는 것만.",
        "M: 그럼 내일 우리 동아리에 말할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Taemin. It's Nari from your class."],
        ["M", "Hi, Nari. Is something wrong?"],
        ["W", "No, but tomorrow we don't need the science book."],
        ["M", "We don't? It's on the timetable."],
        ["W", "The teacher changed it today. We're doing an experiment instead."],
        ["M", "So what do I bring?"],
        ["W", "Just a pencil. Everything else is in the lab."],
        ["M", "That's lighter. Thanks for telling me."],
        ["W", "No problem. See you tomorrow."],
      ],
      choices: [
        "준비물이 바뀐 것을 알리려고",
        "수업이 취소되었다고 알리려고",
        "책을 빌려 달라고 하려고",
        "숙제를 물어보려고",
        "시간표를 물어보려고",
      ],
      answer: 1,
      clue: "No, but tomorrow we don't need the science book.",
      explanation:
        "여자는 내일 실험을 해서 과학책 대신 연필만 가져오면 된다고 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 태민아. 같은 반 나리야.",
        "M: 안녕, 나리야. 무슨 일 있어?",
        "W: 아니, 내일 과학책 안 가져와도 돼.",
        "M: 안 가져와도 돼? 시간표에 있는데.",
        "W: 선생님이 오늘 바꾸셨어. 대신 실험해.",
        "M: 그럼 뭘 가져가?",
        "W: 연필만. 나머지는 실험실에 다 있어.",
        "M: 가볍겠다. 알려 줘서 고마워.",
        "W: 별말을. 내일 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minho, what time should we meet at the cinema?"],
        ["M", "The film starts at three."],
        ["W", "And we have to pick up the tickets."],
        ["M", "How about two forty-five?"],
        ["W", "The queue is long on Saturdays. Let's go earlier."],
        ["M", "How long does it take you to get there?"],
        ["W", "Ten minutes by bike."],
        ["M", "Then let's meet at two o'clock."],
        ["W", "Two o'clock is good. I'll wait by the door."],
      ],
      choices: ["2:00 p.m.", "2:15 p.m.", "2:30 p.m.", "2:45 p.m.", "3:00 p.m."],
      answer: 1,
      clue: "Then let's meet at two o'clock.",
      explanation:
        "영화가 3시에 시작하고 줄이 길어서 두 사람은 2시에 만나기로 한다. 따라서 답은 ①이다.",
      translation: [
        "W: 민호야, 영화관에서 몇 시에 만날까?",
        "M: 영화가 3시에 시작해.",
        "W: 그리고 표도 찾아야 하잖아.",
        "M: 2시 45분은 어때?",
        "W: 토요일에는 줄이 길어. 더 일찍 가자.",
        "M: 거기까지 얼마나 걸려?",
        "W: 자전거로 10분.",
        "M: 그럼 2시에 만나자.",
        "W: 2시 좋아. 문 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayoon, you've been reading that letter over and over."],
        ["W", "It's from the school art contest. I sent in my drawing last month."],
        ["M", "And? What does it say?"],
        ["W", "They picked six out of ninety, and mine is one of them."],
        ["M", "That's great! You drew it three times."],
        ["W", "Four times. I almost threw the last one away."],
        ["M", "Aren't you glad you didn't?"],
        ["W", "I keep checking that my name is really there."],
      ],
      choices: ["bored", "worried", "delighted", "angry", "disappointed"],
      answer: 3,
      clue: "I keep checking that my name is really there.",
      explanation:
        "90명 중 6명에 뽑혀 자기 이름을 거듭 확인한다고 했으므로 여자는 기뻐하고 있다. 따라서 답은 ③이다.",
      translation: [
        "M: 하윤아, 그 편지를 계속 읽고 있네.",
        "W: 학교 미술 대회에서 온 거야. 지난달에 그림을 냈거든.",
        "M: 그래서? 뭐래?",
        "W: 90명 중에 여섯 명을 뽑았는데 내가 그중 하나야.",
        "M: 잘됐다! 세 번이나 그렸잖아.",
        "W: 네 번. 마지막 건 버릴 뻔했어.",
        "M: 안 버리길 잘했지?",
        "W: 내 이름이 진짜 있는지 계속 확인하고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "How much is this ball?"],
        ["W", "Ten dollars."],
        ["M", "Excuse me, is this your ball?"],
        ["W", "Oh, yes. Thank you."],
        ["M", "Could you open the window?"],
        ["W", "Sure, no problem."],
        ["M", "What time does the game start?"],
        ["W", "At four o'clock."],
        ["M", "Where is the bus stop?"],
        ["W", "Just around the corner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, is this your ball?",
      explanation:
        "그림은 담장 너머로 굴러온 공을 주운 사람이 공을 들고 주인에게 확인하는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a park path beside a low fence, clean black line art on a plain white background, no writing or letters anywhere. A BOY is holding up a football in both hands and showing it to a GIRL who has come running up to the fence from the other side, looking at the ball. Both people are drawn clearly. Trees and a bench are in the background.",
      },
      translation: [
        "① M: 이 공 얼마예요? / W: 10달러입니다.",
        "② M: 실례합니다, 이거 당신 공인가요? / W: 아, 네. 고맙습니다.",
        "③ M: 창문 좀 열어 줄래? / W: 그래, 열게.",
        "④ M: 경기 몇 시에 시작해? / W: 4시에.",
        "⑤ M: 버스 정류장이 어디예요? / W: 모퉁이 돌면 바로예요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, are you going to the music room after class?"],
        ["M", "Yes, our club practises there on Wednesdays."],
        ["W", "Could you do one thing for me while you're there?"],
        ["M", "Sure. What is it?"],
        ["W", "I left my music book on the piano."],
        ["M", "Do you want me to bring it to you?"],
        ["W", "No, please put it in the cupboard by the door."],
        ["M", "The one with the other books?"],
        ["W", "That one. Someone almost took mine last week."],
        ["M", "Got it. I'll do it before we start."],
      ],
      choices: ["책을 빌려 주기", "책을 장에 넣어 주기", "책을 가져다주기", "피아노를 치기", "연습을 도와주기"],
      answer: 2,
      clue: "No, please put it in the cupboard by the door.",
      explanation:
        "여자는 피아노 위에 둔 악보집을 문 옆 장에 넣어 달라고 부탁한다. 가져다 달라는 것이 아니다. 따라서 답은 ②이다.",
      translation: [
        "W: 도현아, 수업 끝나고 음악실 가?",
        "M: 응, 우리 동아리가 수요일마다 거기서 연습해.",
        "W: 거기 있는 동안 하나만 부탁할게.",
        "M: 그래. 뭔데?",
        "W: 피아노 위에 악보집을 두고 왔어.",
        "M: 가져다줄까?",
        "W: 아니, 문 옆 장에 넣어 줘.",
        "M: 다른 책들 있는 그 장?",
        "W: 거기. 지난주에 누가 내 걸 가져갈 뻔했어.",
        "M: 알겠어. 시작 전에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Spring Sports Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Here is news about Spring Sports Day."],
        ["M", "It will be held on the first Friday of next month, all morning."],
        ["M", "Everything takes place on the big playground."],
        ["M", "There will be three games: relay, dodgeball, and tug of war."],
        ["M", "Wear your class T-shirt and bring a water bottle."],
        ["M", "Let's make it a good morning for everyone."],
      ],
      choices: ["열리는 날", "장소", "경기 종목", "준비물", "우승 상품"],
      answer: 5,
      clue: "Wear your class T-shirt and bring a water bottle.",
      explanation:
        "날짜(다음 달 첫째 금요일 오전), 장소(큰 운동장), 경기 종목(이어달리기·피구·줄다리기), 준비물(반 티셔츠와 물병)은 언급되지만 우승 상품은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Spring Sports Day 소식입니다.",
        "M: 다음 달 첫째 금요일 오전 내내 열립니다.",
        "M: 모든 경기는 큰 운동장에서 합니다.",
        "M: 경기는 세 가지입니다. 이어달리기, 피구, 줄다리기.",
        "M: 반 티셔츠를 입고 물병을 가져오세요.",
        "M: 모두에게 좋은 오전이 되게 만들어 봅시다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You use this every day at school."],
        ["W", "It is long and thin, and it has numbers along one side."],
        ["W", "You put it on the paper to draw a straight line."],
        ["W", "It also tells you how long something is."],
        ["W", "Most of them are thirty centimetres long."],
      ],
      choices: ["자", "지우개", "연필", "가위", "풀"],
      answer: 1,
      clue: "You put it on the paper to draw a straight line.",
      explanation:
        "길고 가늘며 한쪽에 숫자가 있고 곧은 선을 긋거나 길이를 잰다고 했으므로 자이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 학교에서 날마다 씁니다.",
        "W: 길고 가늘며 한쪽에 숫자가 죽 적혀 있습니다.",
        "W: 종이에 대고 곧은 선을 긋습니다.",
        "W: 무언가의 길이도 알려 줍니다.",
        "W: 대부분 30센티미터입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How was your weekend?"],
        ["W", "Busy, but good."],
        ["M", "Can I borrow your pencil?"],
        ["W", "Sure, here you are."],
        ["M", "What time do you get up?"],
        ["W", "At seven."],
        ["M", "Where did you buy that bag?"],
        ["W", "I have three brothers."],
        ["M", "Do you want to play after school?"],
        ["W", "Yes, that sounds fun."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Where did you buy that bag?",
      explanation:
        "가방을 어디서 샀느냐는 물음에 형이 셋이라는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 주말 어땠어? / W: 바빴지만 좋았어.",
        "② M: 연필 좀 빌려줄래? / W: 그럼, 여기 있어.",
        "③ M: 몇 시에 일어나? / W: 7시에.",
        "④ M: 그 가방 어디서 샀어? / W: 나는 형이 셋이야.",
        "⑤ M: 방과 후에 놀래? / W: 응, 재밌겠다.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, the class quiz starts in ten minutes."],
        ["W", "Is the room ready? What should I do?"],
        ["M", "I've moved the desks and written the rules on the board."],
        ["W", "Should I hand out the answer sheets?"],
        ["M", "Junho is doing that at the door."],
        ["W", "Then what's left?"],
        ["M", "The bell is still in the teachers' room and we need it."],
        ["W", "I'll run and get it now."],
        ["M", "Thanks. I'll put the prizes on the front desk."],
      ],
      choices: ["책상 옮기기", "칠판에 규칙 쓰기", "답안지 나눠 주기", "종 가져오기", "상품 놓기"],
      answer: 4,
      clue: "I'll run and get it now.",
      explanation:
        "책상과 칠판, 답안지는 이미 해결되었으므로 여자는 교무실에 있는 종을 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 수민아, 학급 퀴즈가 10분 뒤에 시작해.",
        "W: 교실은 준비됐어? 내가 뭘 할까?",
        "M: 책상은 옮겼고 칠판에 규칙도 썼어.",
        "W: 답안지를 나눠 줄까?",
        "M: 준호가 문 앞에서 나눠 주고 있어.",
        "W: 그럼 뭐가 남았어?",
        "M: 종이 아직 교무실에 있는데 그게 필요해.",
        "W: 내가 지금 가서 가져올게.",
        "M: 고마워. 나는 상품을 앞 책상에 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 방과 후 수업을 고르시오.",
      lines: [
        ["W", "Junho, these are the five after-school classes still open."],
        ["M", "Let's see. I can't do Tuesdays because of my art lesson."],
        ["W", "Then one is out. What else?"],
        ["M", "It has to be indoors. I don't like playing outside in winter."],
        ["W", "One is outdoors, so that's gone too."],
        ["M", "Three left. How long is each class?"],
        ["W", "You said sixty minutes at the most."],
        ["M", "Then one more drops out. Two are left."],
        ["W", "Do they both give you the materials?"],
        ["M", "Only one does. I'd have to buy my own for the other."],
        ["W", "Then that settles it. Sign up today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Then that settles it. Sign up today.",
      explanation:
        "화요일인 ①, 야외인 ②, 90분인 ③을 뺀다. 남은 ④와 ⑤ 중 재료를 주는 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "화요일 / 실내 / 60분 / 재료 제공" },
          { no: 2, label: "②", value: "목요일 / 야외 / 60분 / 재료 제공" },
          { no: 3, label: "③", value: "목요일 / 실내 / 90분 / 재료 제공" },
          { no: 4, label: "④", value: "목요일 / 실내 / 60분 / 재료 직접 준비" },
          { no: 5, label: "⑤", value: "금요일 / 실내 / 60분 / 재료 제공" },
        ],
      },
      translation: [
        "W: 준호야, 아직 열려 있는 방과 후 수업이 이 다섯 개야.",
        "M: 보자. 미술 수업 때문에 화요일은 안 돼.",
        "W: 그럼 하나 빠지네. 또 뭐가 있어?",
        "M: 실내여야 해. 겨울에 밖에서 하는 건 싫어.",
        "W: 하나는 야외니까 그것도 빠져.",
        "M: 셋 남았다. 한 번에 몇 분이야?",
        "W: 길어야 60분이라고 했잖아.",
        "M: 그럼 하나 더 빠지고 둘 남았다.",
        "W: 둘 다 재료를 줘?",
        "M: 한 곳만. 다른 하나는 내가 사야 해.",
        "W: 그럼 정해졌네. 오늘 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 동물원에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taemin, when should we go to the zoo?"],
        ["M", "The baby panda is out on the twenty-third, twenty-fourth, and twenty-fifth."],
        ["W", "Only those three days?"],
        ["M", "After that it goes back inside for the winter."],
        ["W", "Then let's go soon. But I have a piano lesson on the twenty-third."],
        ["M", "Then the twenty-fourth or the twenty-fifth."],
        ["W", "Isn't the twenty-fifth the day of the school concert?"],
        ["M", "You're right, I forgot. We'd be there all afternoon."],
        ["W", "So only the twenty-fourth is left."],
        ["M", "Then let's go on the twenty-fourth. I'll ask my father to take us."],
      ],
      choices: ["22일", "23일", "24일", "25일", "26일"],
      answer: 3,
      clue: "So only the twenty-fourth is left.",
      explanation:
        "23일은 피아노 수업, 25일은 학교 음악회여서 24일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 동물원에 언제 갈까?",
        "M: 아기 판다가 23일, 24일, 25일에만 나와 있대.",
        "W: 사흘만?",
        "M: 그 뒤로는 겨울이라 안으로 들어간대.",
        "W: 그럼 빨리 가자. 그런데 나 23일에 피아노 수업이 있어.",
        "M: 그럼 24일이나 25일이네.",
        "W: 25일은 학교 음악회 날 아니야?",
        "M: 맞다, 잊었네. 오후 내내 거기 있잖아.",
        "W: 그럼 24일만 남네.",
        "M: 그럼 24일에 가자. 아빠한테 데려다 달라고 할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, did you go to the park yesterday?"],
        ["M", "No, I stayed at home. I helped my mother in the garden."],
        ["W", "The garden? I didn't know you had one."],
        ["M", "It's small, but there's a long fence along one side."],
        ["W", "What did you do there?"],
        ["M", "We planted twenty small trees all the way along that fence."],
        ["W", "Twenty? That's a lot of digging."],
        ["M", "My mother dug and I carried the trees and the water."],
        ["W", "Still, your arms must be tired."],
        ["M", "They still hurt today. I couldn't lift my bag this morning."],
        ["W", "Did it take all day?"],
        ["M", "From after lunch until it got dark. But the fence looks green now."],
      ],
      choices: ["공원 가기", "나무 심기", "자전거 타기", "청소하기", "장보기"],
      answer: 2,
      clue: "We planted twenty small trees all the way along that fence.",
      explanation:
        "남자는 어제 어머니와 울타리를 따라 작은 나무 스무 그루를 심었다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "W: 도현아, 어제 공원 갔어?",
        "M: 아니, 집에 있었어. 엄마 도와서 마당 일 했어.",
        "W: 마당? 너희 집에 마당 있는 줄 몰랐네.",
        "M: 작아. 그런데 한쪽에 긴 울타리가 있어.",
        "W: 거기서 뭘 했는데?",
        "M: 그 울타리를 따라 작은 나무 스무 그루를 심었어.",
        "W: 스무 그루? 많이 팠겠다.",
        "M: 엄마가 파고 나는 나무랑 물을 날랐어.",
        "W: 그래도 팔이 아프겠다.",
        "M: 오늘도 아파. 아침에 가방도 못 들겠더라.",
        "W: 하루 종일 걸렸어?",
        "M: 점심 먹고부터 어두워질 때까지. 그래도 울타리가 초록초록해졌어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "We have one short notice about tomorrow morning."],
        ["W", "The playground will be closed from eight until lunchtime."],
        ["W", "Workers are painting the white lines we use on Sports Day."],
        ["W", "The paint needs about three hours to dry, so please do not step on it."],
        ["W", "Please use the gym for your morning break instead."],
        ["W", "Classes that have P.E. in the morning will use the gym as well."],
        ["W", "The playground opens again in the afternoon, as usual."],
        ["W", "Thank you for your understanding."],
      ],
      choices: [
        "체육대회 신청을 받으려고",
        "운동장이 닫힌다고 알리려고",
        "체육관 청소를 부탁하려고",
        "등교 시간을 바꾸려고",
        "선을 밟지 말라고 하려고",
      ],
      answer: 2,
      clue: "The playground will be closed from eight until lunchtime.",
      explanation:
        "선 긋는 작업 때문에 내일 오전에 운동장이 닫힌다는 것을 알리는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 내일 오전에 대해 짧게 알려 드립니다.",
        "W: 운동장이 8시부터 점심시간까지 닫힙니다.",
        "W: 체육대회 때 쓰는 흰 선을 칠하는 작업을 합니다.",
        "W: 페인트가 마르는 데 세 시간쯤 걸리니 밟지 마세요.",
        "W: 오전 쉬는 시간에는 대신 체육관을 이용해 주세요.",
        "W: 오전에 체육 수업이 있는 반도 체육관을 씁니다.",
        "W: 운동장은 오후에 평소처럼 다시 엽니다.",
        "W: 이해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the sandwich shop. What would you like?"],
        ["W", "Two sandwiches, please."],
        ["M", "Sandwiches are five dollars each."],
        ["W", "So ten dollars."],
        ["M", "That's right. Would you like a drink too?"],
        ["W", "How much is it?"],
        ["M", "Four dollars each."],
        ["W", "Then two drinks, please."],
        ["M", "All right. The two-sandwich discount ended last week, I'm afraid."],
        ["W", "Great. Here you are."],
      ],
      choices: ["$12", "$14", "$15", "$16", "$18"],
      answer: 5,
      clue: "All right. The two-sandwich discount ended last week, I'm afraid.",
      explanation:
        "샌드위치 5달러씩 두 개는 10달러, 음료 4달러씩 두 개는 8달러여서 18달러이다. 두 개 할인은 지난주에 끝났으므로 답은 ⑤이다.",
      translation: [
        "M: 샌드위치 가게입니다. 무엇을 드릴까요?",
        "W: 샌드위치 두 개 주세요.",
        "M: 샌드위치는 하나에 5달러입니다.",
        "W: 그럼 10달러네요.",
        "M: 맞습니다. 음료도 하시겠어요?",
        "W: 얼마예요?",
        "M: 하나에 4달러입니다.",
        "W: 그럼 두 개 주세요.",
        "M: 알겠습니다. 샌드위치 두 개 할인은 아쉽게도 지난주에 끝났습니다.",
        "W: 좋네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minho, you've been late to first period three times this week."],
        ["M", "I get to school on time. It's after that."],
        ["W", "What do you do when you arrive?"],
        ["M", "I go to my locker and then to the playground to see my friends."],
        ["W", "And the playground is at the other end."],
        ["M", "Right. Then I run back and I'm late."],
        ["W", "See them in the classroom instead."],
      ],
      choices: [
        "My locker is number nine.",
        "I arrive at eight o'clock.",
        "The playground is very big.",
        "Then I'll go straight to class tomorrow.",
        "You should come earlier too.",
      ],
      answer: 4,
      clue: "See them in the classroom instead.",
      explanation:
        "운동장 대신 교실에서 친구를 만나라는 조언을 들었으므로, 내일은 바로 교실로 가겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 민호야, 이번 주에 1교시에 세 번이나 늦었어.",
        "M: 학교엔 제시간에 와. 그다음이 문제야.",
        "W: 도착하면 뭐 해?",
        "M: 사물함 갔다가 운동장에 친구들 보러 가.",
        "W: 운동장은 반대편 끝이잖아.",
        "M: 맞아. 그러고 뛰어오면 늦어.",
        "W: 대신 교실에서 만나.",
        "M: 그럼 내일은 바로 교실로 갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Nari, your drawings always stop halfway."],
        ["W", "I know. I start a new one whenever I don't like it."],
        ["M", "How many have you started this month?"],
        ["W", "Eleven. I finished none of them."],
        ["M", "Eleven in three weeks. That's a lot of paper."],
        ["W", "My sketchbook is nearly gone and there's nothing in it."],
        ["M", "What happens at the halfway point?"],
        ["W", "It looks worse than it did at the start. Every time."],
        ["M", "And so you stop right there."],
        ["W", "I stop and turn the page."],
        ["M", "Everything looks worse halfway. Finish one and then judge it."],
      ],
      choices: [
        "I draw with a soft pencil.",
        "My sketchbook is almost full.",
        "Then I'll finish one tonight.",
        "I started in September.",
        "You should draw one too.",
      ],
      answer: 3,
      clue: "Everything looks worse halfway. Finish one and then judge it.",
      explanation:
        "하나를 끝내고 나서 판단하라는 조언을 들었으므로, 오늘 밤에 하나를 끝내겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 나리야, 네 그림은 늘 반쯤에서 멈춰.",
        "W: 알아. 마음에 안 들면 새로 시작해.",
        "M: 이번 달에 몇 장 시작했어?",
        "W: 열한 장. 하나도 안 끝냈어.",
        "M: 3주에 열한 장이면 종이도 많이 썼겠다.",
        "W: 스케치북이 거의 다 됐는데 남은 건 하나도 없어.",
        "M: 반쯤 오면 무슨 일이 생기는데?",
        "W: 처음보다 더 못나 보여. 매번.",
        "M: 그래서 딱 거기서 멈추고.",
        "W: 멈추고 장을 넘겨.",
        "M: 반쯤에서는 다 못나 보여. 하나를 끝내고 나서 판단해.",
        "W: 그럼 오늘 밤에 하나 끝낼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junseo, how is the class library going?"],
        ["M", "Badly. Six books have gone missing."],
        ["W", "Six out of how many?"],
        ["M", "Fifty. And they're the six everyone wanted."],
        ["W", "So the good ones went first."],
        ["M", "They went in the first week and never came back."],
        ["W", "Who writes down who takes them?"],
        ["M", "Nobody. We just have a shelf by the window."],
        ["W", "So nobody knows who has what."],
        ["M", "And nobody feels like they have to bring it back."],
        ["W", "Put a notebook on the shelf and write your name when you take one."],
      ],
      choices: [
        "We have about fifty books.",
        "The shelf is at the back.",
        "Then I'll put one there tomorrow.",
        "I read two books last month.",
        "You should borrow one.",
      ],
      answer: 3,
      clue: "Put a notebook on the shelf and write your name when you take one.",
      explanation:
        "선반에 공책을 두고 가져갈 때 이름을 적게 하라는 조언을 들었으므로, 내일 공책을 두겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 준서야, 학급 문고는 잘돼 가?",
        "M: 잘 안돼. 책 여섯 권이 없어졌어.",
        "W: 몇 권 중에 여섯 권?",
        "M: 쉰 권 중에. 그것도 다들 보고 싶어 하던 여섯 권.",
        "W: 좋은 게 먼저 나갔네.",
        "M: 첫 주에 나가서 돌아오지 않았어.",
        "W: 누가 가져갔는지 누가 적어?",
        "M: 아무도. 창가에 선반만 있어.",
        "W: 그럼 누가 뭘 가져갔는지 아무도 모르지.",
        "M: 그리고 아무도 돌려줘야 한다고 느끼지 않아.",
        "W: 선반에 공책을 두고 가져갈 때 이름을 적게 해.",
        "M: 그럼 내일 하나 갖다 놓을게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sohee가 Junho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Sohee : ________________",
      lines: [
        ["W", "Sohee and Junho are cleaning the classroom together."],
        ["W", "Junho has swept the whole floor very carefully."],
        ["W", "He has made one big pile of dust in the middle of the room."],
        ["W", "However, he has not picked it up, and people keep walking through it."],
        ["W", "The pile is getting spread around again."],
        ["W", "Sohee does not want to say that his sweeping was useless."],
        ["W", "She wants to ask him to put the pile in the bin now."],
        ["W", "In this situation, what would Sohee most likely say to Junho?"],
      ],
      choices: [
        "Let's sweep the floor again tomorrow.",
        "You should sweep more slowly.",
        "I'll clean the whole room myself.",
        "Could you put that pile in the bin now?",
        "The classroom is too big for two people.",
      ],
      answer: 4,
      clue: "She wants to ask him to put the pile in the bin now.",
      explanation:
        "소희는 준호가 쓴 일을 깎아내리지 않으면서, 모아 둔 먼지를 지금 쓰레기통에 넣자고 말하려 한다. 따라서 ④가 가장 적절하다.",
      translation: [
        "W: 소희와 준호는 함께 교실을 청소하고 있습니다.",
        "W: 준호가 바닥을 아주 꼼꼼히 쓸었습니다.",
        "W: 교실 가운데에 먼지를 큰 무더기로 모아 놓았습니다.",
        "W: 그런데 아직 치우지 않아서 사람들이 자꾸 밟고 지나갑니다.",
        "W: 무더기가 다시 흩어지고 있습니다.",
        "W: 소희는 준호가 쓴 일이 헛수고라고 말하고 싶지는 않습니다.",
        "W: 다만 지금 그 무더기를 쓰레기통에 넣자고 부탁하고 싶습니다.",
        "W: 이런 상황에서 소희가 준호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
