/** 중1 듣기 21회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 21회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 모자를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a hat?"],
        ["W", "Yes, for my little brother."],
        ["M", "We have caps with a brim and round hats with no brim."],
        ["W", "A cap, please. He wears one every day."],
        ["M", "All right. Do you want one with a pocket on the front?"],
        ["W", "No, plain at the front. He puts sweets in the pocket."],
        ["M", "Then these two. One has stars on it and one has stripes."],
        ["W", "The stars, please. Stripes are all he owns."],
        ["M", "Good choice. It comes in one size and the back adjusts."],
        ["W", "Then it will fit. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "The stars, please. Stripes are all he owns.",
      explanation:
        "여자는 챙이 있는 모자를, 앞주머니가 없는 것으로, 그중 별무늬를 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five hats in one row across the middle of the picture, all five fully inside the frame with a wide empty margin on the left and right so nothing is cut off, each the same size, drawn from the side, clean black line art on a plain white background, no writing or letters anywhere. " +
          "Hat 1: a ROUND soft hat with NO BRIM at all (like a beanie), covered in STARS. " +
          "Hat 2: a baseball CAP with a curved BRIM, a small square POCKET stitched on the front panel, covered in STRIPES. " +
          "Hat 3: a baseball CAP with a curved BRIM, a small square POCKET stitched on the front panel, covered in STARS. " +
          "Hat 4: a baseball CAP with a curved BRIM, NO pocket, the front panel plain, covered in STARS. " +
          "Hat 5: a baseball CAP with a curved BRIM, NO pocket, the front panel plain, covered in STRIPES.",
      },
      translation: [
        "M: 안녕하세요. 모자 찾으세요?",
        "W: 네, 남동생 줄 거예요.",
        "M: 챙이 있는 캡도 있고 챙 없는 둥근 모자도 있습니다.",
        "W: 캡으로요. 매일 쓰거든요.",
        "M: 알겠습니다. 앞에 주머니 달린 걸로 하시겠어요?",
        "W: 아니요, 앞은 그냥 밋밋한 걸로요. 주머니에 사탕을 넣어 둬서요.",
        "M: 그럼 이 두 개네요. 하나는 별무늬, 하나는 줄무늬입니다.",
        "W: 별무늬로요. 가진 게 전부 줄무늬예요.",
        "M: 좋은 선택이세요. 한 치수인데 뒤가 조절됩니다.",
        "W: 그럼 맞겠네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 텃밭에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jiho, are you joining the school garden?"],
        ["M", "I want to. Where is it?"],
        ["W", "Behind the gym, next to the bicycle rack."],
        ["M", "When do people work there?"],
        ["W", "Every Wednesday after lunch, for half an hour."],
        ["M", "What are we growing?"],
        ["W", "Lettuce and cherry tomatoes this term."],
        ["M", "Do we need to bring anything?"],
        ["W", "Just gloves. The school lends the rest."],
        ["M", "Then I'll put gloves in my bag tonight."],
      ],
      choices: ["있는 곳", "하는 때", "기르는 것", "가져올 것", "참여 인원"],
      answer: 5,
      clue: "Just gloves. The school lends the rest.",
      explanation:
        "장소(체육관 뒤), 시간(수요일 점심 후 30분), 기르는 것(상추와 방울토마토), 가져올 것(장갑)은 언급되지만 참여 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 지호야, 학교 텃밭 들어갈 거야?",
        "M: 하고 싶은데, 어디 있어?",
        "W: 체육관 뒤, 자전거 세우는 데 옆에.",
        "M: 언제 해?",
        "W: 수요일마다 점심 먹고 30분씩.",
        "M: 뭘 길러?",
        "W: 이번 학기엔 상추랑 방울토마토.",
        "M: 뭐 가져가야 해?",
        "W: 장갑만. 나머지는 학교에서 빌려줘.",
        "M: 그럼 오늘 밤에 장갑 가방에 넣어 둘게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junho. It's Somi."],
        ["M", "Hi, Somi. What's up?"],
        ["W", "You left your water bottle in the music room."],
        ["M", "Oh no. Is it still there?"],
        ["W", "I picked it up. It's in my bag."],
        ["M", "Thank you. Can you bring it tomorrow?"],
        ["W", "Sure. I'll give it to you before first period."],
      ],
      choices: [
        "물병을 주웠다고 알리려고",
        "음악실 열쇠를 빌리려고",
        "숙제를 물어보려고",
        "같이 가자고 하려고",
        "물병을 사 달라고 하려고",
      ],
      answer: 1,
      clue: "You left your water bottle in the music room.",
      explanation:
        "여자는 남자가 음악실에 두고 간 물병을 주웠다고 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준호야. 소미야.",
        "M: 안녕, 소미야. 무슨 일이야?",
        "W: 너 음악실에 물병 두고 갔어.",
        "M: 이런. 아직 거기 있어?",
        "W: 내가 챙겼어. 내 가방에 있어.",
        "M: 고마워. 내일 가져다줄 수 있어?",
        "W: 그래. 1교시 전에 줄게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minho, what time is the movie on Saturday?"],
        ["M", "It starts at four o'clock."],
        ["W", "Should we meet right before it?"],
        ["M", "We have to pick up the tickets at the counter."],
        ["W", "How long does that take?"],
        ["M", "About fifteen minutes on a Saturday."],
        ["W", "And I want to buy popcorn too."],
        ["M", "Then let's meet at three thirty."],
        ["W", "Three thirty is good. I'll wait by the door."],
      ],
      choices: ["3:00 p.m.", "3:15 p.m.", "3:30 p.m.", "3:45 p.m.", "4:00 p.m."],
      answer: 3,
      clue: "Then let's meet at three thirty.",
      explanation:
        "영화가 4시에 시작하고 표를 찾는 데 15분, 팝콘도 사야 해서 두 사람은 3시 30분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 민호야, 토요일에 영화 몇 시야?",
        "M: 4시에 시작해.",
        "W: 바로 전에 만날까?",
        "M: 표를 창구에서 찾아야 해.",
        "W: 그건 얼마나 걸려?",
        "M: 토요일엔 15분쯤.",
        "W: 나 팝콘도 사고 싶은데.",
        "M: 그럼 3시 30분에 만나자.",
        "W: 3시 30분 좋아. 문 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuna, you've been smiling at your phone all morning."],
        ["W", "My cousin sent me a photo of her new puppy."],
        ["M", "Can I see?"],
        ["W", "Here. His ears are bigger than his head."],
        ["M", "He really is small."],
        ["W", "And I'm going to meet him this weekend."],
        ["M", "That's why you keep looking at the clock, then."],
        ["W", "I've been counting the days since Monday."],
      ],
      choices: ["excited", "bored", "angry", "sorry", "nervous"],
      answer: 1,
      clue: "I've been counting the days since Monday.",
      explanation:
        "여자는 주말에 강아지를 보러 갈 날을 월요일부터 세고 있다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "M: 유나야, 아침 내내 휴대전화 보면서 웃고 있네.",
        "W: 사촌이 새로 키우는 강아지 사진을 보냈어.",
        "M: 나도 봐도 돼?",
        "W: 여기. 귀가 머리보다 더 커.",
        "M: 진짜 작다.",
        "W: 그리고 이번 주말에 보러 가.",
        "M: 그래서 자꾸 시계를 보는구나.",
        "W: 월요일부터 며칠 남았나 세고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "How much are these apples?"],
        ["M", "Two dollars each."],
        ["W", "Excuse me, you dropped your glove."],
        ["M", "Oh, thank you very much."],
        ["W", "What time does the class start?"],
        ["M", "At nine o'clock."],
        ["W", "Can I borrow your pencil?"],
        ["M", "Sure, here you are."],
        ["W", "Where is the library?"],
        ["M", "On the second floor."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, you dropped your glove.",
      explanation:
        "그림은 한 사람이 앞서 걸어가는 사람에게 떨어뜨린 장갑을 주워 내미는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "One single scene on a winter pavement, clean black line art on a plain white background, no writing or letters anywhere, all signboards blank. A GIRL has stopped and bent down to pick up a single GLOVE from the ground; she is holding it up in one hand and calling out to a BOY who is a few steps ahead of her and turning back to look at her over his shoulder. The boy has one bare hand and one gloved hand. Both people are drawn fully inside the frame, with bare winter trees and a bench behind them.",
      },
      translation: [
        "① W: 이 사과 얼마예요? / M: 하나에 2달러입니다.",
        "② W: 저기요, 장갑 떨어뜨리셨어요. / M: 아, 정말 고맙습니다.",
        "③ W: 수업 몇 시에 시작해? / M: 9시에.",
        "④ W: 연필 좀 빌려줄래? / M: 그럼, 여기 있어.",
        "⑤ W: 도서관이 어디예요? / M: 2층에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Somi, are you going to the art room later?"],
        ["W", "Yes, I have to finish my poster."],
        ["M", "Could you do something for me there?"],
        ["W", "What is it?"],
        ["M", "My brushes are drying on the window sill."],
        ["W", "Do you want me to wash them?"],
        ["M", "No, just put them in my box under the table."],
        ["W", "All right. Which box is yours?"],
        ["M", "The blue one with my name on it. Thanks."],
      ],
      choices: ["붓을 씻어 주기", "포스터를 그려 주기", "상자를 사 주기", "창문을 닫아 주기", "붓을 상자에 넣어 주기"],
      answer: 5,
      clue: "No, just put them in my box under the table.",
      explanation:
        "남자는 창틀에 말리고 있는 붓을 상자에 넣어 달라고 부탁한다. 씻는 것이 아니다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 소미야, 이따 미술실 가?",
        "W: 응, 포스터 마저 해야 해.",
        "M: 거기서 하나만 부탁할게.",
        "W: 뭔데?",
        "M: 내 붓이 창틀에서 마르고 있어.",
        "W: 씻어 줄까?",
        "M: 아니, 탁자 밑 내 상자에 넣어만 줘.",
        "W: 알겠어. 어느 상자가 네 거야?",
        "M: 이름 적힌 파란 거. 고마워.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 도서관 이용에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, everyone. This is about using the school library."],
        ["W", "It opens at eight in the morning and closes at six."],
        ["W", "You may borrow three books at a time."],
        ["W", "Keep them for two weeks and bring them back on time."],
        ["W", "Eating is not allowed inside, but water is fine."],
        ["W", "Come and find something you like."],
      ],
      choices: ["여는 시간", "빌릴 수 있는 권수", "빌리는 기간", "먹는 것", "도서관 위치"],
      answer: 5,
      clue: "Eating is not allowed inside, but water is fine.",
      explanation:
        "여는 시간(8시~6시), 권수(세 권), 기간(2주), 먹는 것(음식 금지, 물은 가능)은 언급되지만 도서관 위치는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여러분, 안녕하세요. 학교 도서관 이용 안내입니다.",
        "W: 아침 8시에 열고 6시에 닫습니다.",
        "W: 한 번에 세 권까지 빌릴 수 있습니다.",
        "W: 2주 동안 보고 제때 가져다주세요.",
        "W: 안에서 먹는 것은 안 되지만 물은 괜찮습니다.",
        "W: 와서 마음에 드는 책을 찾아보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You hold this in one hand and press it with your thumb."],
        ["M", "When it opens, it makes a roof over your head."],
        ["M", "You only take it out on some days."],
        ["M", "On the other days you leave it by the door and forget it."],
        ["M", "People lose this more often than anything else they own."],
      ],
      choices: ["가방", "우산", "모자", "부채", "지갑"],
      answer: 2,
      clue: "When it opens, it makes a roof over your head.",
      explanation:
        "한 손에 들고 엄지로 눌러 펴면 머리 위에 지붕이 생긴다고 했으므로 우산이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 한 손에 들고 엄지로 누릅니다.",
        "M: 펴지면 머리 위에 지붕이 생깁니다.",
        "M: 어떤 날에만 꺼내 듭니다.",
        "M: 다른 날에는 문 옆에 두고 잊어버립니다.",
        "M: 사람들이 가진 물건 중에 이것을 가장 자주 잃어버립니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How old is your sister?"],
        ["M", "She's nine."],
        ["W", "Can you close the window?"],
        ["M", "Sure, no problem."],
        ["W", "What color is your bag?"],
        ["M", "I walk to school."],
        ["W", "Where do you live?"],
        ["M", "Near the park."],
        ["W", "Do you like swimming?"],
        ["M", "Yes, very much."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "What color is your bag?",
      explanation:
        "가방이 무슨 색이냐는 물음에 걸어서 학교에 간다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① W: 네 동생 몇 살이야? / M: 아홉 살이야.",
        "② W: 창문 좀 닫아 줄래? / M: 그래, 그럴게.",
        "③ W: 네 가방 무슨 색이야? / M: 나는 걸어서 학교에 가.",
        "④ W: 어디 살아? / M: 공원 근처에.",
        "⑤ W: 수영 좋아해? / M: 응, 아주 좋아해.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuna, the class party starts in ten minutes."],
        ["W", "Is everything ready? What should I do?"],
        ["M", "The desks are moved and the balloons are up."],
        ["W", "What about the drinks?"],
        ["M", "Jiho brought them and they're on the back table."],
        ["W", "Then what's left?"],
        ["M", "Nobody has put out the paper cups yet."],
        ["W", "I'll get them from the cupboard now."],
        ["M", "Thanks. I'll turn on the music."],
      ],
      choices: ["책상 옮기기", "풍선 달기", "음료 가져오기", "종이컵 놓기", "음악 틀기"],
      answer: 4,
      clue: "I'll get them from the cupboard now.",
      explanation:
        "책상·풍선·음료는 이미 끝났고 남은 것은 종이컵이라 여자는 종이컵을 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 유나야, 학급 파티가 10분 뒤에 시작해.",
        "W: 다 준비됐어? 내가 뭘 할까?",
        "M: 책상은 옮겼고 풍선도 달았어.",
        "W: 음료는?",
        "M: 지호가 가져와서 뒤 탁자에 뒀어.",
        "W: 그럼 뭐가 남았어?",
        "M: 아직 아무도 종이컵을 안 놨어.",
        "W: 내가 지금 찬장에서 가져올게.",
        "M: 고마워. 나는 음악 틀게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 필통을 고르시오.",
      lines: [
        ["W", "Junho, these are the five pencil cases left."],
        ["M", "Let me see. I don't want a cloth one — it gets dirty."],
        ["W", "Then one is out. Two of them are cloth, actually."],
        ["M", "So three left. How much are they?"],
        ["W", "You said under eight dollars."],
        ["M", "Then one more drops out."],
        ["W", "Two left. Do you want one pocket or two?"],
        ["M", "Two. I keep my ruler separate."],
        ["W", "Then it's decided."],
        ["M", "Good. I'll buy it on the way home."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Two. I keep my ruler separate.",
      explanation:
        "천으로 된 ①·②를 빼고, 9달러인 ③을 빼면 ④와 ⑤가 남는다. 주머니가 두 개인 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "천 / 6달러 / 주머니 1개" },
          { no: 2, label: "②", value: "천 / 7달러 / 주머니 2개" },
          { no: 3, label: "③", value: "가죽 / 9달러 / 주머니 2개" },
          { no: 4, label: "④", value: "가죽 / 7달러 / 주머니 2개" },
          { no: 5, label: "⑤", value: "가죽 / 6달러 / 주머니 1개" },
        ],
      },
      translation: [
        "W: 준호야, 남은 필통이 이 다섯 개야.",
        "M: 어디 보자. 천으로 된 건 싫어. 금방 더러워져.",
        "W: 그럼 하나 빠지네. 사실 두 개가 천이야.",
        "M: 그럼 셋 남네. 얼마야?",
        "W: 8달러 아래라고 했잖아.",
        "M: 그럼 하나 더 빠지고.",
        "W: 둘 남았다. 주머니는 하나가 좋아, 둘이 좋아?",
        "M: 둘. 자는 따로 넣거든.",
        "W: 그럼 정해졌네.",
        "M: 좋아. 집에 가는 길에 살게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 수영장에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Minho, when should we go to the pool?"],
        ["M", "It's open from the fourth to the eighth."],
        ["W", "How long can we stay?"],
        ["M", "Two hours each time."],
        ["W", "I have a piano lesson on the fifth."],
        ["M", "Then the sixth, the seventh or the eighth."],
        ["W", "The seventh and the eighth are the school trip."],
        ["M", "That's right. We'd be away both days."],
        ["W", "So only one day is left."],
        ["M", "Then let's go on the sixth. I'll bring my goggles."],
      ],
      choices: ["4일", "5일", "6일", "7일", "8일"],
      answer: 3,
      clue: "Then let's go on the sixth. I'll bring my goggles.",
      explanation:
        "5일은 피아노 수업, 7일과 8일은 수학여행이어서 6일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "W: 민호야, 수영장 언제 갈까?",
        "M: 4일부터 8일까지 열어.",
        "W: 얼마나 있을 수 있어?",
        "M: 한 번에 두 시간.",
        "W: 나 5일에 피아노 수업 있어.",
        "M: 그럼 6일, 7일, 8일이네.",
        "W: 7일이랑 8일은 수학여행이잖아.",
        "M: 맞다. 이틀 다 밖에 있겠네.",
        "W: 그럼 하루만 남네.",
        "M: 그럼 6일에 가자. 물안경 가져갈게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, did you go to the park on Sunday?"],
        ["M", "No, I made cookies with my grandmother."],
        ["W", "Cookies? How many did you make?"],
        ["M", "Forty. We used three trays."],
        ["W", "That's a lot. Did you eat them all?"],
        ["M", "No, we gave half to the neighbours."],
        ["W", "What kind were they?"],
        ["M", "Chocolate. My grandmother only makes one kind."],
        ["W", "I would like to try one."],
        ["M", "There are six left. I'll bring you one tomorrow."],
      ],
      choices: ["쿠키 만들기", "공원에 가기", "쿠키 사러 가기", "이웃 만나기", "할머니 댁 청소하기"],
      answer: 1,
      clue: "No, I made cookies with my grandmother.",
      explanation:
        "남자는 지난 일요일에 할머니와 쿠키를 만들었다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "W: 지호야, 일요일에 공원 갔어?",
        "M: 아니, 할머니랑 쿠키 만들었어.",
        "W: 쿠키? 몇 개나 만들었는데?",
        "M: 마흔 개. 판 세 개 썼어.",
        "W: 많다. 다 먹었어?",
        "M: 아니, 반은 이웃에게 드렸어.",
        "W: 무슨 맛이었는데?",
        "M: 초콜릿. 할머니는 한 가지만 만드셔.",
        "W: 나도 하나 먹어 보고 싶다.",
        "M: 여섯 개 남았어. 내일 하나 가져다줄게.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "We have one thing to tell you about tomorrow."],
        ["M", "The water will be turned off from eight in the morning."],
        ["M", "Workers are fixing an old pipe under the first floor."],
        ["M", "That means the taps and the water fountains will not work."],
        ["M", "So please bring your own water bottle to school tomorrow."],
        ["M", "A big one is better than a small one."],
        ["M", "The water will come back on right after lunch."],
        ["M", "The toilets on the second floor will stay open all day."],
        ["M", "Thank you for understanding."],
      ],
      choices: [
        "물병을 가져오라고 하려고",
        "수업이 없다고 알리려고",
        "1층에 가지 말라고 하려고",
        "공사 비용을 안내하려고",
        "점심시간을 바꾼다고 알리려고",
      ],
      answer: 1,
      clue: "Please bring your own water bottle to school.",
      explanation:
        "내일 아침 물이 끊기니 물병을 가져오라는 방송이다. 따라서 방송의 목적은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 내일 일로 알려 드릴 것이 하나 있습니다.",
        "M: 아침 8시부터 물이 끊깁니다.",
        "M: 기사님들이 1층 아래 낡은 수도관을 고칩니다.",
        "M: 그래서 수도꼭지와 음수대를 쓸 수 없습니다.",
        "M: 내일은 물병을 각자 가져와 주세요.",
        "M: 큰 것이 작은 것보다 낫습니다.",
        "M: 물은 점심 먹고 바로 다시 나옵니다.",
        "M: 2층 화장실은 하루 종일 씁니다.",
        "M: 이해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the stationery shop. What would you like?"],
        ["W", "I need some notebooks for my new class."],
        ["M", "These lined ones are our most popular."],
        ["W", "Two of those, please."],
        ["M", "Notebooks are three dollars each."],
        ["W", "So six dollars for two."],
        ["M", "That's right. Anything else for you today?"],
        ["W", "One pen, please. The black one. How much is it?"],
        ["M", "That pen is two dollars."],
        ["W", "Then eight dollars in total."],
        ["M", "And students get one dollar off. Do you have your card?"],
        ["W", "Yes, here it is. Thank you."],
      ],
      choices: ["$6", "$7", "$8", "$9", "$10"],
      answer: 2,
      clue: "And students get one dollar off. Do you have your card?",
      explanation:
        "공책 3달러씩 두 권은 6달러, 펜 2달러를 더하면 8달러이다. 학생 할인 1달러를 빼면 7달러이므로 답은 ②이다.",
      translation: [
        "M: 문구점입니다. 무엇을 드릴까요?",
        "W: 새 수업에 쓸 공책이 필요해요.",
        "M: 이 줄 있는 공책이 제일 잘 나갑니다.",
        "W: 그걸로 두 권 주세요.",
        "M: 공책은 한 권에 3달러입니다.",
        "W: 그럼 두 권에 6달러네요.",
        "M: 맞습니다. 오늘 더 필요하신 건요?",
        "W: 펜 하나요. 검은색으로요. 얼마예요?",
        "M: 그 펜은 2달러입니다.",
        "W: 그럼 모두 8달러네요.",
        "M: 그리고 학생은 1달러 빼 드립니다. 카드 있으세요?",
        "W: 네, 여기 있습니다. 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Somi, you've read that same page five times."],
        ["W", "I know. Nothing stays in my head today."],
        ["M", "How long have you been sitting at that desk?"],
        ["W", "Since four o'clock. It's almost seven now."],
        ["M", "Three hours without standing up once?"],
        ["W", "I didn't want to waste any time."],
        ["M", "Have you even had a glass of water?"],
        ["W", "No. I was going to, and then I forgot."],
        ["M", "Your head stopped working about an hour ago."],
        ["W", "That's probably true. I keep reading the same line."],
        ["M", "Go outside for ten minutes and come back."],
      ],
      choices: [
        "My book has two hundred pages.",
        "All right, I'll take a short walk.",
        "I read for three hours every day.",
        "The test is on Friday morning.",
        "You should read this page too.",
      ],
      answer: 2,
      clue: "Go outside for ten minutes and come back.",
      explanation:
        "10분만 밖에 나갔다 오라는 말을 들었으므로, 잠깐 걷고 오겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 소미야, 같은 쪽을 다섯 번째 읽고 있어.",
        "W: 알아. 오늘은 머리에 하나도 안 들어와.",
        "M: 그 책상에 앉은 지 얼마나 됐어?",
        "W: 4시부터. 이제 거의 7시야.",
        "M: 세 시간 동안 한 번도 안 일어났다고?",
        "W: 시간을 조금도 버리고 싶지 않았어.",
        "M: 물은 한 잔이라도 마셨어?",
        "W: 아니. 마시려다가 잊어버렸어.",
        "M: 네 머리는 한 시간쯤 전에 멈췄어.",
        "W: 그 말이 맞을 거야. 같은 줄만 계속 읽고 있어.",
        "M: 10분만 밖에 나갔다 와.",
        "W: 알겠어, 잠깐 걷고 올게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junho, you've lost your umbrella three times this term."],
        ["M", "Four, actually. I found one of them again."],
        ["W", "Where do you put it when you get to school?"],
        ["M", "I lean it against the wall by the front door."],
        ["W", "And in the afternoon, do you go out the front door?"],
        ["M", "No, I use the side door. It's closer to the bus stop."],
        ["W", "So you never walk past your umbrella again."],
        ["M", "I never thought about that."],
        ["W", "Put it in your locker instead. You open that every day."],
      ],
      choices: [
        "My umbrella is blue.",
        "It rains a lot in June.",
        "Then I'll put it in my locker tomorrow.",
        "The side door is faster.",
        "You should buy a new umbrella.",
      ],
      answer: 3,
      clue: "Put it in your locker instead. You open that every day.",
      explanation:
        "사물함에 넣어 두라는 조언을 들었으므로, 내일부터 사물함에 넣겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 이번 학기에 우산을 세 번이나 잃어버렸네.",
        "M: 사실 네 번. 하나는 다시 찾았어.",
        "W: 학교 오면 우산을 어디에 둬?",
        "M: 앞문 옆 벽에 세워 둬.",
        "W: 그럼 오후에 앞문으로 나가?",
        "M: 아니, 옆문으로 나가. 버스 정류장이 더 가까워.",
        "W: 그럼 우산 옆을 다시 지나갈 일이 없네.",
        "M: 그건 생각 못 했어.",
        "W: 대신 사물함에 넣어 둬. 그건 매일 열잖아.",
        "M: 그럼 내일부터 사물함에 넣을게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Yuna, how is your English notebook going?"],
        ["W", "Not well. I write every new word down but I forget them."],
        ["M", "Where do you write them?"],
        ["W", "At the back of the notebook, one after another."],
        ["M", "So they're all mixed together in one long list?"],
        ["W", "Yes. It's four pages now."],
        ["M", "And when do you read that list?"],
        ["W", "Almost never. It's at the back."],
        ["M", "Write each day's words on that day's page instead."],
      ],
      choices: [
        "My notebook is almost full.",
        "I learn ten words a day.",
        "English is my favorite subject.",
        "Then I'll start doing that tonight.",
        "You should buy a new notebook.",
      ],
      answer: 4,
      clue: "Write each day's words on that day's page instead.",
      explanation:
        "그날 배운 낱말을 그날 쪽에 적으라는 조언을 들었으므로, 오늘 밤부터 그렇게 하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 유나야, 영어 공책은 잘돼 가?",
        "W: 잘 안돼. 새 낱말을 다 적는데 잊어버려.",
        "M: 어디에 적는데?",
        "W: 공책 맨 뒤에, 차례차례.",
        "M: 그럼 전부 긴 목록 하나에 섞여 있는 거야?",
        "W: 응. 이제 네 쪽이야.",
        "M: 그 목록을 언제 읽어?",
        "W: 거의 안 읽어. 맨 뒤에 있잖아.",
        "M: 대신 그날 낱말을 그날 쪽에 적어.",
        "W: 그럼 오늘 밤부터 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiho가 Somi에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Jiho : ________________",
      lines: [
        ["W", "Jiho and Somi are making a poster for the class together."],
        ["W", "Somi has drawn every picture on the poster by herself."],
        ["W", "The pictures are neat and she worked on them all week."],
        ["W", "However, she has drawn them all in one small corner."],
        ["W", "More than half of the poster is empty white paper."],
        ["W", "From the back of the room nobody can see the pictures."],
        ["W", "Jiho does not want to say that her work was wasted."],
        ["W", "He wants to suggest spreading the pictures across the whole poster."],
        ["W", "In this situation, what would Jiho most likely say to Somi?"],
      ],
      choices: [
        "Let's draw fewer pictures.",
        "Could we spread them out over the whole poster?",
        "You should draw them again tomorrow.",
        "I'll make my own poster instead.",
        "Let's use a smaller piece of paper.",
      ],
      answer: 2,
      clue: "He wants to suggest spreading the pictures across the whole poster.",
      explanation:
        "지호는 소미가 한 일을 깎아내리지 않으면서, 그림을 포스터 전체에 펼치자고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 지호와 소미는 학급 포스터를 함께 만들고 있습니다.",
        "W: 소미가 포스터의 그림을 혼자 다 그렸습니다.",
        "W: 그림은 깔끔하고, 소미는 일주일 내내 그렸습니다.",
        "W: 그런데 그림을 전부 한쪽 작은 구석에만 그렸습니다.",
        "W: 포스터의 반 넘게가 빈 종이입니다.",
        "W: 교실 뒤에서는 아무도 그림을 볼 수 없습니다.",
        "W: 지호는 소미가 한 일이 헛수고라고 말하고 싶지는 않습니다.",
        "W: 다만 그림을 포스터 전체에 펼치자고 제안하고 싶습니다.",
        "W: 이런 상황에서 지호가 소미에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
