/** 중1 듣기 30회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 30회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 티셔츠를 고르시오.",
      lines: [
        ["W", "Welcome. Are you looking for a T-shirt?"],
        ["M", "Yes, something to wear on our field trip."],
        ["W", "We have long-sleeve ones and short-sleeve ones."],
        ["M", "Short sleeves, please. It will be hot that day."],
        ["W", "All right. This short-sleeve shirt has a big star."],
        ["M", "A big picture on the front feels too loud for me."],
        ["W", "Then here is a short-sleeve one with a small pocket."],
        ["M", "That's perfect. I'll take the one with the pocket."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Short sleeves, please. / I'll take the one with the pocket.",
      explanation:
        "남자는 반팔 티셔츠를 원하고, 큰 별 그림 대신 작은 주머니가 달린 것을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five plain T-shirts drawn side by side as five choices, clean black line art on white. " +
          "① a LONG-SLEEVE shirt with a BIG STAR on the chest. " +
          "② a LONG-SLEEVE shirt with a SMALL POCKET on the chest. " +
          "③ a SHORT-SLEEVE shirt with a BIG STAR on the chest. " +
          "④ a SHORT-SLEEVE shirt with nothing on it at all. " +
          "⑤ a SHORT-SLEEVE shirt with a SMALL POCKET on the chest.",
      },
      translation: [
        "W: 어서 오세요. 티셔츠 찾으세요?",
        "M: 네, 현장 학습 때 입을 거예요.",
        "W: 긴팔도 있고 반팔도 있어요.",
        "M: 반팔로 주세요. 그날 더울 거예요.",
        "W: 알겠습니다. 이 반팔은 큰 별이 그려져 있어요.",
        "M: 앞에 큰 그림은 너무 튀어 보여요.",
        "W: 그럼 작은 주머니가 달린 반팔이 여기 있어요.",
        "M: 딱 좋네요. 주머니 있는 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 농구 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hana, is your class playing in the basketball tournament?"],
        ["W", "Yes, we are. When does it start?"],
        ["M", "Next Monday, right after lunch."],
        ["W", "How many players are on one team?"],
        ["M", "Five on the court and two more on the bench."],
        ["W", "Where do we play? The gym or outside?"],
        ["M", "In the gym, because rain is coming that week."],
        ["W", "Good. How long is one game?"],
        ["M", "Two halves of ten minutes each."],
      ],
      choices: ["시작하는 날", "한 팀의 인원", "경기 장소", "한 경기 시간", "심판"],
      answer: 5,
      clue: "심판은 대화에서 언급되지 않았다.",
      explanation:
        "시작하는 날(다음 주 월요일), 한 팀 인원(코트 5명, 벤치 2명), 장소(체육관), 경기 시간(10분씩 두 번)은 언급되지만 심판은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 하나야, 너희 반 농구 대회 나가?",
        "W: 응, 나가. 언제 시작해?",
        "M: 다음 주 월요일, 점심 먹고 바로.",
        "W: 한 팀에 몇 명이야?",
        "M: 코트에 다섯 명, 벤치에 두 명 더.",
        "W: 어디서 해? 체육관이야, 밖이야?",
        "M: 체육관에서. 그 주에 비가 온대.",
        "W: 잘됐다. 한 경기는 얼마나 해?",
        "M: 10분씩 두 번.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this Hana's mother?"],
        ["W", "Yes, speaking. Who is this, please?"],
        ["M", "This is Taeho, Hana's classmate from school."],
        ["W", "Oh, hello, Taeho. Hana is in the shower now."],
        ["M", "I see. Our class trip has been moved to Thursday."],
        ["W", "Thursday? I thought it was on Wednesday."],
        ["M", "It changed this afternoon, and Hana's phone is off."],
        ["W", "Thank you for calling. I'll tell her right away."],
      ],
      choices: [
        "숙제를 물어보려고",
        "현장 학습 날짜가 바뀐 것을 알리려고",
        "함께 공부하자고 하려고",
        "빌린 물건을 돌려주려고",
        "생일에 초대하려고",
      ],
      answer: 2,
      clue: "I see. Our class trip has been moved to Thursday.",
      explanation:
        "남자는 현장 학습이 목요일로 바뀐 것을 알리려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요, 하나 어머님이신가요?",
        "W: 네, 맞습니다. 누구세요?",
        "M: 저는 하나 반 친구 태호예요.",
        "W: 아, 안녕 태호야. 하나는 지금 씻고 있어.",
        "M: 그렇군요. 저희 현장 학습이 목요일로 바뀌었어요.",
        "W: 목요일? 수요일인 줄 알았는데.",
        "M: 오늘 오후에 바뀌었는데 하나 휴대폰이 꺼져 있어요.",
        "W: 전화해 줘서 고마워. 바로 전해 줄게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taeho, what time does the baking class begin?"],
        ["M", "It starts at eleven on Saturday morning."],
        ["W", "Do we have to do anything before it starts?"],
        ["M", "Yes, we wash our hands and put on aprons."],
        ["W", "How much time does that take?"],
        ["M", "About fifteen minutes for everyone."],
        ["W", "Then let's meet fifteen minutes before eleven."],
        ["M", "Good. I'll wait in front of the kitchen door."],
        ["W", "See you there on Saturday morning."],
      ],
      choices: ["10:15 a.m.", "10:30 a.m.", "10:45 a.m.", "11:00 a.m.", "11:15 a.m."],
      answer: 3,
      clue: "Then let's meet fifteen minutes before eleven.",
      explanation:
        "수업이 11시에 시작하고 15분 전에 만나기로 했으므로 만나는 시각은 10시 45분이다. 따라서 답은 ③이다.",
      translation: [
        "W: 태호야, 제빵 수업 몇 시에 시작해?",
        "M: 토요일 오전 11시에 시작해.",
        "W: 시작 전에 뭘 해야 해?",
        "M: 응, 손 씻고 앞치마 입어야 해.",
        "W: 그건 얼마나 걸려?",
        "M: 다 같이 하면 15분쯤.",
        "W: 그럼 11시 15분 전에 만나자.",
        "M: 좋아. 나는 조리실 문 앞에서 기다릴게.",
        "W: 토요일 아침에 거기서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hana, what are you reading so closely?"],
        ["W", "A letter from my old friend in Jeonju."],
        ["M", "Isn't that the friend who moved in third grade?"],
        ["W", "Yes, and we haven't talked for four years."],
        ["M", "How did she find your address?"],
        ["W", "She asked my old teacher, and the teacher remembered me."],
        ["M", "That's a lovely story."],
        ["W", "I want to write back to both of them tonight."],
      ],
      choices: ["bored", "angry", "nervous", "thankful", "jealous"],
      answer: 4,
      clue: "I want to write back to both of them tonight.",
      explanation:
        "4년 만에 편지를 보내 준 친구와 주소를 알려 준 선생님께 답장을 쓰고 싶다고 했으므로 여자의 심정은 '고마운(thankful)'이다. 따라서 답은 ④이다.",
      translation: [
        "M: 하나야, 뭘 그렇게 열심히 읽어?",
        "W: 전주에 사는 옛 친구가 보낸 편지야.",
        "M: 3학년 때 이사 간 그 친구?",
        "W: 응, 4년 동안 연락을 못 했어.",
        "M: 네 주소는 어떻게 알았대?",
        "W: 옛 담임 선생님께 여쭤봤는데 선생님이 나를 기억하셨대.",
        "M: 참 좋은 이야기다.",
        "W: 오늘 밤에 두 분 다 답장을 쓰고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I sit in the front row?"],
        ["M", "Yes, those seats are empty."],
        ["ANN", "Number two."],
        ["W", "When does the train arrive?"],
        ["M", "In about ten minutes."],
        ["ANN", "Number three."],
        ["W", "Is this the right platform for Busan?"],
        ["M", "No, Busan trains leave from platform four."],
        ["ANN", "Number four."],
        ["W", "How much is a ticket to Daejeon?"],
        ["M", "It's twenty dollars."],
        ["ANN", "Number five."],
        ["W", "Do you have a map of the city?"],
        ["M", "Yes, take one from the desk."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Is this the right platform for Busan?",
      explanation:
        "그림은 기차역 승강장에서 여행 가방을 든 여자가 역무원에게 승강장이 맞는지 물어보고, 역무원이 다른 쪽을 가리키는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "On a train station platform, clean black line art on a plain white background, no writing anywhere. " +
          "A woman with a rolling suitcase is speaking to a station worker in a uniform cap. " +
          "The worker points with one arm toward the far side of the station. " +
          "An empty platform edge, a bench and a station roof are drawn simply in the background.",
      },
      translation: [
        "① W: 앞줄에 앉아도 되나요? / M: 네, 그 자리는 비었어요.",
        "② W: 기차가 언제 도착해요? / M: 10분쯤 뒤에요.",
        "③ W: 부산 가는 승강장이 여기 맞나요? / M: 아니요, 부산행은 4번 승강장에서 떠납니다.",
        "④ W: 대전까지 표가 얼마예요? / M: 20달러입니다.",
        "⑤ W: 시내 지도 있나요? / M: 네, 저기 책상에서 하나 가져가세요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeho, you live near the stationery shop, right?"],
        ["M", "Yes, it's two minutes from my apartment."],
        ["W", "Our class needs color paper for tomorrow's poster."],
        ["M", "Didn't we buy some last week?"],
        ["W", "We used it all on the science board."],
        ["M", "I see. Do you want me to go there today?"],
        ["W", "Yes, could you buy ten sheets on your way home?"],
        ["M", "Sure. I'll bring them first thing in the morning."],
      ],
      choices: ["색종이 사 오기", "포스터 그리기", "과학 게시판 만들기", "돈 빌려주기", "가게 위치 알려 주기"],
      answer: 1,
      clue: "Yes, could you buy ten sheets on your way home?",
      explanation:
        "여자는 집에 가는 길에 색종이 열 장을 사다 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 태호야, 너 문구점 근처 살지?",
        "M: 응, 우리 아파트에서 2분 거리야.",
        "W: 내일 포스터에 쓸 색종이가 필요해.",
        "M: 지난주에 사지 않았어?",
        "W: 과학 게시판에 다 썼어.",
        "M: 그렇구나. 오늘 내가 가 볼까?",
        "W: 응, 집에 가는 길에 열 장만 사 줄래?",
        "M: 그럼. 내일 아침에 제일 먼저 갖다줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 수확 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Our school garden harvest day is this Friday. " +
            "We will meet behind the science building right after fifth period. " +
            "This year we are picking tomatoes, peppers, and lettuce. " +
            "Wear clothes that can get dirty, and bring a pair of gloves. " +
            "Everything we pick will go to the school kitchen for next week's lunch. " +
            "We hope many of you can join us.",
        ],
      ],
      choices: ["행사 요일", "모이는 장소", "수확할 작물", "준비물", "참가 신청 방법"],
      answer: 5,
      clue: "참가 신청 방법은 방송에서 언급되지 않았다.",
      explanation:
        "요일(이번 주 금요일), 장소(과학관 뒤), 수확할 작물(토마토·고추·상추), 준비물(더러워져도 되는 옷과 장갑)은 언급되지만 참가 신청 방법은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 학교 텃밭 수확의 날이 이번 주 금요일입니다. 5교시가 끝난 직후 과학관 뒤에서 모입니다. 올해는 토마토, 고추, 상추를 땁니다. 더러워져도 되는 옷을 입고 장갑 한 켤레를 가져오세요. 딴 것은 모두 학교 조리실로 보내 다음 주 급식에 씁니다. 많이 함께해 주기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a place where you go when your tooth hurts. " +
            "You sit in a chair that leans back, and a bright light shines on your face. " +
            "The doctor wears a mask and looks inside your mouth with a small mirror. " +
            "You can hear a high buzzing sound from the next room. " +
            "Many people feel nervous before they go in.",
        ],
      ],
      choices: ["미용실", "치과", "안경점", "약국", "체육관"],
      answer: 2,
      clue: "The doctor wears a mask and looks inside your mouth with a small mirror.",
      explanation:
        "이가 아플 때 가서 눕는 의자에 앉고, 의사가 작은 거울로 입안을 보는 곳은 치과이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이곳은 이가 아플 때 가는 곳입니다. 뒤로 젖혀지는 의자에 앉으면 밝은 불빛이 얼굴을 비춥니다. 의사 선생님은 마스크를 쓰고 작은 거울로 입안을 들여다봅니다. 옆방에서 높은 윙 소리가 들립니다. 많은 사람이 들어가기 전에 긴장합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What did you have for breakfast?"],
        ["W", "I had toast and milk."],
        ["ANN", "Number two."],
        ["M", "How often does the bus come?"],
        ["W", "Every fifteen minutes."],
        ["ANN", "Number three."],
        ["M", "Could you help me with this box?"],
        ["W", "Of course, let me hold one side."],
        ["ANN", "Number four."],
        ["M", "What does your father do?"],
        ["W", "He works at a hospital."],
        ["ANN", "Number five."],
        ["M", "Where is the nearest post office?"],
        ["W", "I finished my homework already."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Where is the nearest post office?",
      explanation:
        "가장 가까운 우체국이 어디인지 묻는 말에 숙제를 다 했다고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 아침에 뭐 먹었어? / W: 토스트랑 우유 먹었어.",
        "② M: 버스가 얼마나 자주 와? / W: 15분마다 와.",
        "③ M: 이 상자 좀 도와줄래? / W: 그럼, 내가 한쪽 들게.",
        "④ M: 아버지는 무슨 일 하셔? / W: 병원에서 일하셔.",
        "⑤ M: 가장 가까운 우체국이 어디야? / W: 나는 숙제를 벌써 끝냈어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeho, the school concert starts in half an hour."],
        ["M", "I know. Are all the chairs in the hall ready?"],
        ["W", "Yes, I set out eighty chairs this morning."],
        ["M", "Great. Did you check the microphone on the stage?"],
        ["W", "I tried it, but there was no sound at all."],
        ["M", "Maybe the cable is loose behind the stage."],
        ["W", "I have to hand out the programs at the door."],
        ["M", "Then I'll go behind the stage and check the cable."],
      ],
      choices: ["의자 놓기", "프로그램 나눠 주기", "무대 뒤 선 확인하기", "표 팔기", "노래 연습하기"],
      answer: 3,
      clue: "Then I'll go behind the stage and check the cable.",
      explanation:
        "마이크에서 소리가 안 나는데 여자는 프로그램을 나눠 줘야 해서, 남자가 무대 뒤로 가 선을 확인하겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태호야, 학교 음악회가 30분 뒤에 시작해.",
        "M: 알아. 강당 의자는 다 준비됐어?",
        "W: 응, 오늘 아침에 여든 개 놨어.",
        "M: 잘했다. 무대 마이크는 확인했어?",
        "W: 해 봤는데 소리가 전혀 안 나.",
        "M: 무대 뒤에서 선이 빠졌을지도 몰라.",
        "W: 나는 문에서 프로그램을 나눠 줘야 해.",
        "M: 그럼 내가 무대 뒤로 가서 선을 확인할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 방과후 강좌를 고르시오.",
      lines: [
        ["M", "Hana, have you picked an after-school class yet?"],
        ["W", "Not yet. Let's look at the list together."],
        ["M", "Do you have any day you cannot come?"],
        ["W", "I go to the hospital every Tuesday afternoon."],
        ["M", "Okay, so no Tuesday classes."],
        ["W", "Right. And I don't want one that meets three days a week."],
        ["M", "Too much homework already?"],
        ["W", "Exactly. Two days a week is enough for me."],
        ["M", "Then only one class on this list is left."],
        ["W", "Good. I'll put my name down tomorrow."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I go to the hospital every Tuesday afternoon.",
      explanation:
        "화요일이 아니고 주 2회인 강좌를 고른다. 두 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Tuesday / Times: 2 a week / Class: Pottery" },
          { no: 2, label: "②", value: "Day: Monday / Times: 3 a week / Class: Guitar" },
          { no: 3, label: "③", value: "Day: Tuesday / Times: 3 a week / Class: Dance" },
          { no: 4, label: "④", value: "Day: Thursday / Times: 2 a week / Class: Pottery" },
          { no: 5, label: "⑤", value: "Day: Friday / Times: 3 a week / Class: Dance" },
        ],
      },
      translation: [
        "M: 하나야, 방과후 강좌 골랐어?",
        "W: 아직. 목록 같이 보자.",
        "M: 못 오는 요일 있어?",
        "W: 화요일 오후마다 병원에 가.",
        "M: 알겠어, 그럼 화요일 강좌는 안 되겠다.",
        "W: 맞아. 그리고 주 3회짜리는 싫어.",
        "M: 벌써 숙제가 많아서?",
        "W: 그래. 나는 주 2회면 충분해.",
        "M: 그럼 이 목록에서 남는 건 하나뿐이야.",
        "W: 좋아. 내일 이름 적을게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 동아리 발표를 할 날짜를 고르시오.",
      lines: [
        ["M", "Hana, when should our club give its presentation?"],
        ["W", "How about May 2nd? That's next Thursday."],
        ["M", "The projector room is booked all that day."],
        ["W", "Then what about May 4th?"],
        ["M", "May 4th is Saturday, and school is closed."],
        ["W", "Hmm. I'm free on May 9th."],
        ["M", "But the club report is due on the 7th."],
        ["W", "You're right. Then let's do it on May 6th."],
        ["M", "May 6th is good. The room is open that afternoon."],
        ["W", "Perfect. Let's practice the day before."],
      ],
      choices: ["5월 2일", "5월 4일", "5월 6일", "5월 7일", "5월 9일"],
      answer: 3,
      clue: "You're right. Then let's do it on May 6th.",
      explanation:
        "2일에는 영사실이 예약되어 있고, 4일은 토요일 휴교이며, 9일은 보고서 마감(7일) 이후다. 두 사람은 5월 6일에 하기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 하나야, 우리 동아리 발표 언제 할까?",
        "W: 5월 2일 어때? 다음 주 목요일이야.",
        "M: 그날은 영사실이 하루 종일 예약돼 있어.",
        "W: 그럼 5월 4일은?",
        "M: 5월 4일은 토요일이라 학교가 쉬어.",
        "W: 음. 나는 5월 9일이 비어.",
        "M: 그런데 동아리 보고서 마감이 7일이야.",
        "W: 맞네. 그럼 5월 6일에 하자.",
        "M: 5월 6일 좋아. 그날 오후엔 방이 비어 있어.",
        "W: 좋아. 전날에 연습하자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeho, why is your voice so quiet today?"],
        ["M", "I was at the animal shelter all day on Saturday."],
        ["W", "Did you go there to adopt a dog?"],
        ["M", "No, I washed the dogs there with two other students."],
        ["W", "That sounds like a lot of work. How many dogs?"],
        ["M", "Eleven, and one of them barked right into my ear."],
        ["W", "Ouch. Were they easy to hold in the water?"],
        ["M", "The small ones were, but two big ones kept running away."],
        ["W", "Will you go there again next month?"],
        ["M", "Yes, every second Saturday from now on."],
      ],
      choices: ["보호소에서 개 씻기기", "강아지 입양하기", "동물 병원 가기", "봉사 신청서 내기", "개 산책시키기"],
      answer: 1,
      clue: "No, I washed the dogs there with two other students.",
      explanation:
        "남자는 토요일에 동물 보호소에서 다른 학생 둘과 함께 개 열한 마리를 씻겼다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 태호야, 오늘 왜 목소리가 작아?",
        "M: 토요일 하루 종일 동물 보호소에 있었어.",
        "W: 강아지 입양하러 갔어?",
        "M: 아니, 다른 학생 두 명이랑 거기 개들을 씻겼어.",
        "W: 일이 많았겠다. 몇 마리나?",
        "M: 열한 마리. 그중 한 마리가 내 귀에다 대고 짖었어.",
        "W: 아팠겠다. 물속에서 잡고 있기 쉬웠어?",
        "M: 작은 애들은 괜찮았는데 큰 개 두 마리가 자꾸 도망갔어.",
        "W: 다음 달에도 또 갈 거야?",
        "M: 응, 이제부터 격주 토요일마다 가.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement from the library. " +
            "Starting this Monday, the library will open one hour earlier. " +
            "The new opening time is eight in the morning, not nine. " +
            "Many students asked for a quiet place to study before class. " +
            "The closing time stays the same at six in the evening. " +
            "We hope you make good use of the extra hour.",
        ],
      ],
      choices: [
        "도서관 공사를 알리려고",
        "도서 반납을 당부하려고",
        "독서 행사를 안내하려고",
        "도서관 여는 시각 변경을 알리려고",
        "도서관 이용 규칙을 알리려고",
      ],
      answer: 4,
      clue: "The new opening time is eight in the morning, not nine.",
      explanation:
        "이번 주 월요일부터 도서관이 한 시간 일찍, 아침 8시에 연다는 것을 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 도서관에서 알려 드립니다. 이번 주 월요일부터 도서관이 한 시간 일찍 문을 엽니다. 새 개관 시각은 9시가 아니라 아침 8시입니다. 수업 전에 조용히 공부할 곳을 원하는 학생이 많았기 때문입니다. 닫는 시각은 저녁 6시로 그대로입니다. 늘어난 한 시간을 잘 활용하기 바랍니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the boat ride?"],
        ["M", "Yes, three adult tickets, please."],
        ["W", "One adult ticket is nine dollars."],
        ["M", "So twenty-seven dollars for three?"],
        ["W", "That's right. Would you like a photo as well?"],
        ["M", "No, thank you. Just the tickets."],
        ["W", "All right. Groups of three or more get three dollars off."],
        ["M", "That's good news. Here is the money."],
      ],
      choices: ["$21", "$24", "$25", "$27", "$30"],
      answer: 2,
      clue: "Groups of three or more get three dollars off.",
      explanation:
        "어른 표 세 장은 27달러이고, 3인 이상 단체 할인 3달러를 빼면 24달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 유람선 표 사시나요?",
        "M: 네, 어른 세 장 주세요.",
        "W: 어른 표는 한 장에 9달러입니다.",
        "M: 그럼 세 장이면 27달러인가요?",
        "W: 맞습니다. 사진도 찍으시겠어요?",
        "M: 아니요, 괜찮아요. 표만 주세요.",
        "W: 알겠습니다. 3인 이상은 3달러 할인됩니다.",
        "M: 잘됐네요. 여기 돈이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Hana, you look tired every Monday morning."],
        ["W", "I always sleep in until noon on Sundays."],
        ["M", "Then you can't fall asleep on Sunday night, right?"],
        ["W", "Exactly. I lie awake until two in the morning."],
        ["M", "And then Monday is terrible all day."],
        ["W", "It is. But weekends are the only time I can rest."],
        ["M", "Resting is fine, but the time matters."],
        ["W", "So what should I change about my weekend?"],
        ["M", "Get up at the same hour, even on Sunday."],
      ],
      choices: [
        "I'll set my alarm this Sunday too.",
        "I never sleep on weekends.",
        "Monday is my favorite day.",
        "I'll sleep until three next time.",
        "My alarm clock is broken.",
      ],
      answer: 1,
      clue: "Get up at the same hour, even on Sunday.",
      explanation:
        "남자가 일요일에도 같은 시각에 일어나라고 했으므로, 이번 일요일에도 알람을 맞추겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 하나야, 월요일 아침마다 피곤해 보여.",
        "W: 일요일엔 늘 정오까지 자.",
        "M: 그럼 일요일 밤에 잠이 안 오지?",
        "W: 맞아. 새벽 2시까지 못 자고 누워 있어.",
        "M: 그러면 월요일은 하루 종일 힘들지.",
        "W: 그래. 그런데 주말밖에 쉴 시간이 없어.",
        "M: 쉬는 건 좋은데 시간이 중요해.",
        "W: 그럼 주말에 뭘 바꿔야 해?",
        "M: 일요일에도 같은 시각에 일어나.",
        "W: 이번 일요일에도 알람 맞출게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taeho, did you finish the drawing for the contest?"],
        ["M", "Almost, but the paper tore at the bottom corner."],
        ["W", "Oh no. How big is the tear?"],
        ["M", "About the size of my thumb, right under the tree."],
        ["W", "Can you start over before Friday?"],
        ["M", "There's no time. It took me three weeks."],
        ["W", "Then don't throw it away yet."],
        ["M", "Is there really a way to fix torn paper?"],
        ["W", "The art teacher has special tape for exactly that."],
      ],
      choices: [
        "I'll draw a new picture tonight.",
        "The contest was last month.",
        "My paper is not torn at all.",
        "I'll ask her for the tape tomorrow.",
        "Let's throw the drawing away.",
      ],
      answer: 4,
      clue: "The art teacher has special tape for exactly that.",
      explanation:
        "여자가 미술 선생님께 찢어진 종이용 특수 테이프가 있다고 했으므로, 내일 부탁드리겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 태호야, 대회에 낼 그림 다 그렸어?",
        "M: 거의. 그런데 아래쪽 모서리가 찢어졌어.",
        "W: 어떡해. 얼마나 찢어졌어?",
        "M: 엄지손가락만큼. 나무 바로 밑이야.",
        "W: 금요일 전에 다시 그릴 수 있어?",
        "M: 시간이 없어. 3주 걸렸거든.",
        "W: 그럼 아직 버리지 마.",
        "M: 찢어진 종이를 고치는 방법이 정말 있어?",
        "W: 미술 선생님께 딱 그런 용도의 특수 테이프가 있어.",
        "M: 내일 선생님께 그 테이프 부탁드릴게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Hana, our group needs one more member for the quiz."],
        ["W", "Didn't four people sign up last week?"],
        ["M", "Yes, but Jiwoo moved to another school."],
        ["W", "That's too bad. When is the quiz again?"],
        ["M", "Next Wednesday, and teams must have five."],
        ["W", "Have you asked anyone in our class?"],
        ["M", "I asked six people, and they all said no."],
        ["W", "Maybe try the class next door."],
        ["M", "I don't know anyone in that class, though."],
        ["W", "My cousin Seora is in there. I can introduce you."],
      ],
      choices: [
        "Thanks. Please introduce me tomorrow.",
        "Our team already has five members.",
        "The quiz was cancelled last week.",
        "I know everyone in that class.",
        "Let's not join the quiz at all.",
      ],
      answer: 1,
      clue: "My cousin Seora is in there. I can introduce you.",
      explanation:
        "여자가 옆 반에 있는 사촌을 소개해 주겠다고 했으므로, 고맙다며 내일 소개해 달라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 하나야, 우리 조에 퀴즈 대회 나갈 사람이 한 명 더 필요해.",
        "W: 지난주에 네 명 신청하지 않았어?",
        "M: 응, 그런데 지우가 다른 학교로 전학 갔어.",
        "W: 안됐다. 퀴즈가 언제였지?",
        "M: 다음 주 수요일, 한 팀에 다섯 명이어야 해.",
        "W: 우리 반 애들한테는 물어봤어?",
        "M: 여섯 명한테 물어봤는데 다 안 한대.",
        "W: 옆 반에 물어보는 건 어때?",
        "M: 그 반엔 아는 사람이 없어.",
        "W: 내 사촌 서라가 거기 있어. 소개해 줄게.",
        "M: 고마워. 내일 소개해 줘.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jinho가 Sena에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jinho : ________________",
      lines: [
        [
          "M",
          "Jinho and Sena are cleaning the classroom windows together. " +
            "Sena is standing on a chair to reach the top of the window. " +
            "Jinho notices that the chair has one leg shorter than the others. " +
            "The chair wobbles every time Sena moves her arm. " +
            "Jinho is afraid that Sena will fall and hurt herself. " +
            "In this situation, what would Jinho most likely say to Sena?",
        ],
      ],
      choices: [
        "Let's clean the floor instead.",
        "That chair is not safe. Come down.",
        "The windows are already clean.",
        "I'll buy you a new chair.",
        "Please close the window now.",
      ],
      answer: 2,
      clue: "Jinho is afraid that Sena will fall and hurt herself.",
      explanation:
        "세나가 다리 한쪽이 짧아 흔들리는 의자 위에 서 있어 떨어질까 봐 걱정되므로, 위험하니 내려오라고 말하는 ②가 가장 적절하다.",
      translation: [
        "M: 진호와 세나는 함께 교실 창문을 닦고 있습니다. 세나는 창문 위쪽에 닿으려고 의자 위에 서 있습니다. 진호는 그 의자의 다리 하나가 다른 것보다 짧다는 것을 알아챕니다. 세나가 팔을 움직일 때마다 의자가 흔들립니다. 진호는 세나가 떨어져 다칠까 봐 걱정합니다. 이런 상황에서 진호가 세나에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
