/** 중1 듣기 25회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 25회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 시계를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a wall clock?"],
        ["W", "Yes, one for my room. My old one stopped."],
        ["M", "We have round ones and square ones."],
        ["W", "A square one, please. It fits my shelf better."],
        ["M", "All right. This square clock has numbers on it."],
        ["W", "Hmm, numbers make it look like a school clock."],
        ["M", "Then how about this square one with only dots?"],
        ["W", "I love that. I'll take the one with dots."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A square one, please. / I'll take the one with dots.",
      explanation:
        "여자는 네모난 시계를 원하고, 숫자가 적힌 것 대신 점만 있는 것을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five wall clocks drawn side by side as five choices, clean black line art on white, each with two hands. " +
          "① a ROUND clock with NUMBER marks around the face. " +
          "② a ROUND clock with only DOT marks around the face. " +
          "③ a SQUARE clock with NUMBER marks around the face. " +
          "④ a SQUARE clock with only DOT marks around the face. " +
          "⑤ a SQUARE clock with a completely blank face and no marks.",
      },
      translation: [
        "M: 안녕하세요. 벽시계 찾으세요?",
        "W: 네, 제 방에 걸 거예요. 쓰던 게 멈췄어요.",
        "M: 동그란 것도 있고 네모난 것도 있어요.",
        "W: 네모난 걸로 주세요. 제 선반에 더 잘 맞아요.",
        "M: 알겠습니다. 이 네모 시계는 숫자가 있어요.",
        "W: 음, 숫자가 있으니 학교 시계 같아 보여요.",
        "M: 그럼 점만 있는 이 네모 시계는 어떠세요?",
        "W: 마음에 들어요. 점 있는 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 도자기 체험 교실에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Sehun, did you sign up for the pottery class?"],
        ["M", "Not yet. Where is it held?"],
        ["W", "In the art center next to the post office."],
        ["M", "Good, that's close. How long does one class take?"],
        ["W", "Two hours, from three to five."],
        ["M", "And how much do we pay for it?"],
        ["W", "It's eight thousand won for each person."],
        ["M", "Okay. Do I need to bring my own apron?"],
        ["W", "Yes, and the teacher gives us the clay."],
      ],
      choices: ["열리는 장소", "수업 시간", "가르치는 사람", "수업료", "준비물"],
      answer: 3,
      clue: "가르치는 사람은 대화에서 언급되지 않았다.",
      explanation:
        "장소(우체국 옆 예술 회관), 수업 시간(3시~5시, 두 시간), 수업료(1인 8천 원), 준비물(앞치마)은 언급되지만 가르치는 사람은 언급되지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 세훈아, 도자기 교실 신청했어?",
        "M: 아직. 어디서 해?",
        "W: 우체국 옆 예술 회관에서.",
        "M: 잘됐다, 가깝네. 한 번에 얼마나 걸려?",
        "W: 두 시간, 3시부터 5시까지.",
        "M: 수업료는 얼마야?",
        "W: 한 사람당 8천 원이야.",
        "M: 알겠어. 앞치마는 내가 가져가야 해?",
        "W: 응, 흙은 선생님이 주셔.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hi, Sehun. Are you at home right now?"],
        ["M", "Yes, I just got back. What's up?"],
        ["W", "I think I left my flute in your car."],
        ["M", "Let me check the back seat for you."],
        ["W", "It's in a long black case with a blue strap."],
        ["M", "Oh, here it is, under my little brother's bag."],
        ["W", "What a relief. I have a lesson tomorrow."],
        ["M", "Don't worry. I'll bring it to school in the morning."],
      ],
      choices: [
        "차에 두고 온 물건을 찾으려고",
        "수업 시간을 바꾸려고",
        "악기를 빌려 달라고 하려고",
        "함께 연습하자고 하려고",
        "길을 물어보려고",
      ],
      answer: 1,
      clue: "I think I left my flute in your car.",
      explanation:
        "여자는 남자의 차에 두고 내린 플루트를 찾으려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 안녕, 세훈아. 지금 집이야?",
        "M: 응, 방금 들어왔어. 무슨 일이야?",
        "W: 네 차에 플루트를 두고 내린 것 같아.",
        "M: 뒷좌석 한번 볼게.",
        "W: 파란 끈이 달린 길쭉한 검은 케이스야.",
        "M: 아, 여기 있다. 동생 가방 밑에 있었어.",
        "W: 다행이다. 내일 레슨이 있거든.",
        "M: 걱정 마. 아침에 학교로 가져갈게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Jiyu, what time is the school bus to the farm?"],
        ["W", "It leaves the main gate at nine sharp."],
        ["M", "Then we should be there before that."],
        ["W", "Right. The teacher wants to count us first."],
        ["M", "How early should we arrive for the counting?"],
        ["W", "Twenty minutes before the bus leaves."],
        ["M", "Okay, let's meet at the gate at that time."],
        ["W", "Good. Don't be late like last week."],
        ["M", "I won't. I'll set two alarms tonight."],
      ],
      choices: ["8:20 a.m.", "8:30 a.m.", "9:00 a.m.", "8:40 a.m.", "9:20 a.m."],
      answer: 4,
      clue: "Twenty minutes before the bus leaves.",
      explanation:
        "버스가 9시 정각에 떠나고 그보다 20분 일찍 모이기로 했으므로 만나는 시각은 8시 40분이다. 따라서 답은 ④이다.",
      translation: [
        "M: 지유야, 농장 가는 학교 버스는 몇 시야?",
        "W: 정문에서 9시 정각에 출발해.",
        "M: 그럼 그전에 가 있어야겠네.",
        "W: 맞아. 선생님이 먼저 인원을 세신대.",
        "M: 인원 세는 거 때문에 얼마나 일찍 가야 해?",
        "W: 버스 떠나기 20분 전에.",
        "M: 알겠어, 그 시간에 정문에서 만나자.",
        "W: 좋아. 지난주처럼 늦지 마.",
        "M: 안 늦어. 오늘 밤에 알람 두 개 맞출게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sehun, why are you smiling at your phone?"],
        ["M", "My cousin in Canada is coming next week."],
        ["W", "Really? How long has it been?"],
        ["M", "Five years. We were both in elementary school."],
        ["W", "That's a long time. Will he stay at your house?"],
        ["M", "Yes, for ten whole days. I can't wait."],
        ["W", "What are you going to do together?"],
        ["M", "I've already made a list of ten places."],
      ],
      choices: ["upset", "excited", "sorry", "sleepy", "worried"],
      answer: 2,
      clue: "Yes, for ten whole days. I can't wait.",
      explanation:
        "5년 만에 사촌이 오고 열흘이나 함께 지낸다며 기다릴 수 없다고 했으므로 남자의 심정은 '신난(excited)'이다. 따라서 답은 ②이다.",
      translation: [
        "W: 세훈아, 왜 휴대폰 보면서 웃고 있어?",
        "M: 캐나다에 있는 사촌이 다음 주에 와.",
        "W: 정말? 얼마 만이야?",
        "M: 5년. 둘 다 초등학생이었어.",
        "W: 오래됐다. 너희 집에서 지내?",
        "M: 응, 열흘 내내. 너무 기다려져.",
        "W: 같이 뭐 할 거야?",
        "M: 벌써 갈 곳 열 군데를 적어 놨어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you have this book in English?"],
        ["M", "Yes, it's on the next shelf."],
        ["ANN", "Number two."],
        ["W", "How many books can I borrow?"],
        ["M", "You can take three at a time."],
        ["ANN", "Number three."],
        ["W", "Could you reach that book for me?"],
        ["M", "Sure, I'll get it down for you."],
        ["ANN", "Number four."],
        ["W", "When is this book due?"],
        ["M", "Please return it next Monday."],
        ["ANN", "Number five."],
        ["W", "Is there a study room here?"],
        ["M", "Yes, it's on the second floor."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Could you reach that book for me?",
      explanation:
        "그림은 도서관에서 키가 작은 여학생이 높은 책장의 책에 손이 닿지 않아, 키가 큰 남학생에게 꺼내 달라고 부탁하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a library, clean black line art on a plain white background, no writing anywhere. " +
          "A tall bookshelf full of books stands against the wall. " +
          "A short schoolgirl stands on her toes and points up at a book on the top shelf. " +
          "A taller schoolboy beside her is reaching up with one hand toward that book. " +
          "A reading table and two chairs are drawn simply in the background.",
      },
      translation: [
        "① W: 이 책 영어로 된 것도 있나요? / M: 네, 옆 책장에 있어요.",
        "② W: 책을 몇 권 빌릴 수 있어요? / M: 한 번에 세 권 빌릴 수 있어요.",
        "③ W: 저 책 좀 꺼내 줄래? / M: 그럼, 내가 내려 줄게.",
        "④ W: 이 책 언제까지예요? / M: 다음 주 월요일에 반납해 주세요.",
        "⑤ W: 여기 열람실이 있나요? / M: 네, 2층에 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sehun, you're good at drawing, aren't you?"],
        ["M", "A little. Why do you ask?"],
        ["W", "Our class is making a poster for the singing contest."],
        ["M", "That sounds fun. Who is writing the words on it?"],
        ["W", "Jiyu is doing the writing, and I chose the colors."],
        ["M", "Then everything is ready, isn't it?"],
        ["W", "Not quite. Could you draw a microphone in the middle?"],
        ["M", "Sure. I'll draw it during lunch break."],
      ],
      choices: ["글씨 써 주기", "색깔 골라 주기", "포스터에 그림 그리기", "노래 연습 도와주기", "포스터 붙이기"],
      answer: 3,
      clue: "Could you draw a microphone in the middle?",
      explanation:
        "여자는 포스터 가운데에 마이크 그림을 그려 달라고 부탁했다. 따라서 답은 ③이다.",
      translation: [
        "W: 세훈아, 너 그림 잘 그리지?",
        "M: 조금. 왜 물어봐?",
        "W: 우리 반이 노래 대회 포스터를 만들고 있어.",
        "M: 재밌겠다. 글씨는 누가 써?",
        "W: 지유가 글씨 쓰고, 색은 내가 골랐어.",
        "M: 그럼 다 준비된 거 아니야?",
        "W: 아직. 가운데에 마이크 좀 그려 줄 수 있어?",
        "M: 그럼. 점심시간에 그려 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 별 관측 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The star watching night will be held this Friday. " +
            "We will gather on the school rooftop at eight in the evening. " +
            "Our science teacher will bring two large telescopes for us. " +
            "The event will end at ten, so please tell your parents. " +
            "Wear a jacket because the rooftop gets windy after dark. " +
            "We hope to see many of you there.",
        ],
      ],
      choices: ["신청 마감일", "행사 요일", "모이는 장소", "끝나는 시각", "옷차림"],
      answer: 1,
      clue: "신청 마감일은 방송에서 언급되지 않았다.",
      explanation:
        "행사 요일(이번 주 금요일), 장소(학교 옥상), 끝나는 시각(10시), 옷차림(겉옷)은 언급되지만 신청 마감일은 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 별 관측의 밤이 이번 주 금요일에 열립니다. 저녁 8시에 학교 옥상에 모입니다. 과학 선생님이 큰 망원경 두 대를 가져오십니다. 행사는 10시에 끝나니 부모님께 말씀드리세요. 해가 진 뒤 옥상은 바람이 부니 겉옷을 입고 오세요. 많이 오기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You use this almost every morning in the bathroom. " +
            "It is small and has a short handle and soft hairs at one end. " +
            "You put something white on the hairs before you use it. " +
            "You move it up and down for about three minutes. " +
            "Dentists say you should change it every three months.",
        ],
      ],
      choices: ["빗", "수건", "비누", "칫솔", "거울"],
      answer: 4,
      clue: "It is small and has a short handle and soft hairs at one end.",
      explanation:
        "짧은 손잡이와 부드러운 솔이 있고, 흰 것을 묻혀 3분간 위아래로 움직이며 석 달마다 바꾸는 것은 칫솔이다. 따라서 답은 ④이다.",
      translation: [
        "W: 여러분은 거의 매일 아침 욕실에서 이것을 씁니다. 작고 짧은 손잡이가 있으며 한쪽 끝에 부드러운 솔이 달려 있습니다. 쓰기 전에 솔에 흰 것을 묻힙니다. 3분쯤 위아래로 움직입니다. 치과 의사들은 석 달마다 바꾸라고 말합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What's your favorite season?"],
        ["W", "I like autumn the most."],
        ["ANN", "Number two."],
        ["M", "Where are you from?"],
        ["W", "I ate lunch at noon."],
        ["ANN", "Number three."],
        ["M", "Could you pass me the salt?"],
        ["W", "Here you are."],
        ["ANN", "Number four."],
        ["M", "How was the exam?"],
        ["W", "It was harder than I expected."],
        ["ANN", "Number five."],
        ["M", "Do you have any pets?"],
        ["W", "Yes, I have two cats."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Where are you from?",
      explanation:
        "어디 출신인지 묻는 말에 점심을 정오에 먹었다고 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① M: 어느 계절을 제일 좋아해? / W: 나는 가을이 제일 좋아.",
        "② M: 어디에서 왔어? / W: 나는 정오에 점심을 먹었어.",
        "③ M: 소금 좀 건네줄래? / W: 여기 있어.",
        "④ M: 시험 어땠어? / W: 생각보다 어려웠어.",
        "⑤ M: 기르는 동물 있어? / W: 응, 고양이 두 마리 있어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiyu, the science fair opens in half an hour."],
        ["W", "I know. Our model volcano is on the table already."],
        ["M", "Did you put the sign with our names on it?"],
        ["W", "Yes, I taped it to the front of the table."],
        ["M", "Good. But the floor around our table is wet."],
        ["W", "Oh no, the water bottle must have leaked."],
        ["M", "I have to bring the last box from the classroom."],
        ["W", "Then I'll get a mop and dry the floor first."],
      ],
      choices: ["상자 가져오기", "이름표 붙이기", "물병 사 오기", "화산 모형 만들기", "바닥 닦기"],
      answer: 5,
      clue: "Then I'll get a mop and dry the floor first.",
      explanation:
        "물이 새어 바닥이 젖었고, 여자는 대걸레를 가져와 바닥부터 닦겠다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 지유야, 과학 전시회가 30분 뒤에 열려.",
        "W: 알아. 우리 화산 모형은 이미 탁자에 올려놨어.",
        "M: 우리 이름 적은 표지판도 붙였어?",
        "W: 응, 탁자 앞쪽에 테이프로 붙였어.",
        "M: 잘했다. 그런데 우리 탁자 주변 바닥이 젖었어.",
        "W: 어떡해, 물병이 샜나 봐.",
        "M: 나는 교실에서 마지막 상자를 가져와야 해.",
        "W: 그럼 내가 대걸레 가져와서 바닥부터 닦을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 방을 고르시오.",
      lines: [
        ["W", "Sehun, which room should we book for the club camp?"],
        ["M", "Let's see. There are eight of us going."],
        ["W", "Then a room for six people is too small."],
        ["M", "Right, we need one that holds eight or more."],
        ["W", "Okay. How much can we spend for one night?"],
        ["M", "Under ninety thousand won. That's all we collected."],
        ["W", "Got it. Does the room need a kitchen?"],
        ["M", "Yes, we're going to cook our own dinner."],
        ["W", "Then only one room on this list works for us."],
        ["M", "Perfect. I'll call the center and book it now."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Right, we need one that holds eight or more.",
      explanation:
        "8명 이상이 묵을 수 있고, 하룻밤 9만 원 미만이며, 부엌이 있는 방을 고른다. 세 조건을 모두 채우는 것은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "People: 6 / Price: 70,000 won / Kitchen: Yes" },
          { no: 2, label: "②", value: "People: 8 / Price: 95,000 won / Kitchen: Yes" },
          { no: 3, label: "③", value: "People: 10 / Price: 85,000 won / Kitchen: Yes" },
          { no: 4, label: "④", value: "People: 10 / Price: 88,000 won / Kitchen: No" },
          { no: 5, label: "⑤", value: "People: 6 / Price: 60,000 won / Kitchen: No" },
        ],
      },
      translation: [
        "W: 세훈아, 동아리 캠프에 어느 방을 예약할까?",
        "M: 보자. 우리는 여덟 명이 가.",
        "W: 그럼 여섯 명짜리 방은 너무 작네.",
        "M: 맞아, 여덟 명 이상 들어가는 방이 필요해.",
        "W: 알겠어. 하룻밤에 얼마까지 쓸 수 있어?",
        "M: 9만 원 미만. 우리가 모은 돈이 그게 다야.",
        "W: 그렇구나. 방에 부엌이 있어야 해?",
        "M: 응, 저녁은 우리가 해 먹을 거야.",
        "W: 그럼 이 목록에서 되는 방은 하나뿐이네.",
        "M: 좋아. 지금 수련관에 전화해서 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 함께 등산할 날짜를 고르시오.",
      lines: [
        ["M", "Jiyu, when can we climb Namsan together?"],
        ["W", "How about April 4th? The flowers are best then."],
        ["M", "I can't. My grandfather's birthday is that day."],
        ["W", "Then what about April 6th?"],
        ["M", "The weather report says it will rain all day."],
        ["W", "Hmm. I'm free on April 11th."],
        ["M", "But our class has a swimming lesson on the 11th."],
        ["W", "Oh, right. Then let's go on April 8th."],
        ["M", "April 8th is perfect. Nothing is on my calendar."],
        ["W", "Great. Let's take the first bus that morning."],
      ],
      choices: ["4월 8일", "4월 4일", "4월 6일", "4월 11일", "4월 13일"],
      answer: 1,
      clue: "Oh, right. Then let's go on April 8th.",
      explanation:
        "4일에는 할아버지 생신이, 6일에는 비 예보가, 11일에는 수영 수업이 있다. 두 사람은 4월 8일에 가기로 한다. 따라서 답은 ①이다.",
      translation: [
        "M: 지유야, 남산에 언제 같이 올라갈까?",
        "W: 4월 4일 어때? 그때 꽃이 제일 예뻐.",
        "M: 안 돼. 그날이 할아버지 생신이야.",
        "W: 그럼 4월 6일은?",
        "M: 일기예보에서 하루 종일 비 온대.",
        "W: 음. 나는 4월 11일이 비어 있어.",
        "M: 그런데 11일엔 우리 반 수영 수업이 있어.",
        "W: 아, 맞다. 그럼 4월 8일에 가자.",
        "M: 4월 8일 딱 좋아. 달력에 아무것도 없어.",
        "W: 좋아. 그날 아침 첫차 타자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiyu, your voice sounds a little rough today."],
        ["W", "I shouted too much at the stadium on Saturday."],
        ["M", "Did you go to a baseball game?"],
        ["W", "No, it was a soccer match. My brother plays there."],
        ["M", "Oh, is he on the city youth team?"],
        ["W", "Yes, and he scored the first goal of the match."],
        ["M", "No wonder you shouted. Did they win?"],
        ["W", "They did, two to one. I lost my voice at the end."],
      ],
      choices: ["야구 경기 보기", "노래 연습하기", "운동장 달리기", "축구 경기 응원하기", "친구 생일 파티 가기"],
      answer: 4,
      clue: "No, it was a soccer match. My brother plays there.",
      explanation:
        "여자는 토요일에 경기장에서 오빠가 뛰는 축구 경기를 응원하다가 목이 쉬었다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 지유야, 오늘 목소리가 좀 갈라진다.",
        "W: 토요일에 경기장에서 너무 많이 소리쳤어.",
        "M: 야구 보러 갔어?",
        "W: 아니, 축구 경기였어. 우리 오빠가 거기서 뛰어.",
        "M: 아, 시 청소년 팀이야?",
        "W: 응, 그리고 그 경기 첫 골을 넣었어.",
        "M: 그러니 소리쳤겠다. 이겼어?",
        "W: 응, 2대 1로. 끝날 때쯤 목이 다 쉬었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school library. " +
            "Over three hundred books have not been returned this month. " +
            "Some of them have been out since the winter vacation. " +
            "Please bring them back to the return desk by this Friday. " +
            "If you return them this week, there will be no late fee at all. " +
            "Thank you, and happy reading.",
        ],
      ],
      choices: [
        "도서관 이용 시간을 알리려고",
        "빌린 책을 반납하도록 당부하려고",
        "새로 들어온 책을 소개하려고",
        "독서 대회 참가를 권하려고",
        "도서관 공사를 안내하려고",
      ],
      answer: 2,
      clue: "Please bring them back to the return desk by this Friday.",
      explanation:
        "이달에 반납되지 않은 책이 많으니 금요일까지 반납해 달라고 당부하는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안내 말씀 드립니다. 학교 도서관입니다. 이번 달에 반납되지 않은 책이 300권이 넘습니다. 그중에는 겨울 방학 때부터 나가 있는 책도 있습니다. 이번 주 금요일까지 반납대로 가져와 주세요. 이번 주에 반납하면 연체료는 전혀 없습니다. 감사합니다. 즐거운 독서 되세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What would you like to order today?"],
        ["W", "Two sandwiches and one orange juice, please."],
        ["M", "A sandwich is six dollars and the juice is four."],
        ["W", "All right. Can I also get a cookie?"],
        ["M", "Of course. Each cookie is two dollars."],
        ["W", "Then just one cookie, please."],
        ["M", "Sure. And today every drink is one dollar off."],
        ["W", "Nice. Here is my money."],
      ],
      choices: ["$14", "$15", "$16", "$18", "$17"],
      answer: 5,
      clue: "And today every drink is one dollar off.",
      explanation:
        "샌드위치 두 개 12달러, 주스 4달러, 쿠키 2달러를 더하면 18달러이고, 음료 1달러 할인을 빼면 17달러이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안녕하세요. 오늘은 무엇을 드릴까요?",
        "W: 샌드위치 두 개랑 오렌지 주스 하나 주세요.",
        "M: 샌드위치는 6달러, 주스는 4달러입니다.",
        "W: 알겠어요. 쿠키도 하나 될까요?",
        "M: 물론이죠. 쿠키는 하나에 2달러입니다.",
        "W: 그럼 쿠키는 하나만 주세요.",
        "M: 네. 그리고 오늘은 모든 음료가 1달러 할인됩니다.",
        "W: 좋네요. 여기 돈이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Jiyu, you've brought the same lunch box all week."],
        ["W", "I know. My mom is away, so I make it myself."],
        ["M", "Rice and one fried egg every single day?"],
        ["W", "That's the only thing I can cook well."],
        ["M", "You could try a rice ball. It takes five minutes."],
        ["W", "Really? I thought those were hard to make."],
        ["M", "Not at all. You just mix rice with anything you like."],
        ["W", "That sounds easy enough even for me."],
        ["M", "I'll send you my mother's recipe tonight."],
      ],
      choices: [
        "I already ate my lunch.",
        "My mom came back last week.",
        "Thank you. I'll try it tomorrow morning.",
        "Fried eggs take about an hour.",
        "I don't like rice at all.",
      ],
      answer: 3,
      clue: "I'll send you my mother's recipe tonight.",
      explanation:
        "남자가 오늘 밤에 어머니의 조리법을 보내 주겠다고 했으므로, 고맙다며 내일 아침에 해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 지유야, 너 일주일 내내 같은 도시락을 싸 왔네.",
        "W: 알아. 엄마가 안 계셔서 내가 싸.",
        "M: 매일 밥이랑 달걀부침 하나만?",
        "W: 그게 내가 잘 만들 수 있는 유일한 거야.",
        "M: 주먹밥을 해 봐. 5분이면 돼.",
        "W: 정말? 만들기 어려운 줄 알았어.",
        "M: 전혀. 밥에 좋아하는 걸 섞기만 하면 돼.",
        "W: 나도 할 수 있을 만큼 쉬워 보인다.",
        "M: 오늘 밤에 우리 엄마 조리법 보내 줄게.",
        "W: 고마워. 내일 아침에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sehun, are you still walking to school every morning?"],
        ["M", "Yes, but it takes me almost forty minutes now."],
        ["W", "Forty? It used to take you twenty-five."],
        ["M", "They closed the bridge, so I go the long way."],
        ["W", "Oh, that's why you looked so tired yesterday."],
        ["M", "I have to leave home before seven these days."],
        ["W", "Why don't you take the number six bus instead?"],
        ["M", "Does it stop anywhere near my apartment?"],
        ["W", "Yes, right in front of your building every ten minutes."],
      ],
      choices: [
        "Then I'll try that bus tomorrow morning.",
        "I'll walk across the bridge tomorrow.",
        "My apartment is next to the school.",
        "The bus leaves only twice a day.",
        "I usually get up at nine.",
      ],
      answer: 1,
      clue: "Yes, right in front of your building every ten minutes.",
      explanation:
        "여자가 6번 버스가 남자의 아파트 앞에 10분마다 선다고 했으므로, 내일 아침에 그 버스를 타 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 세훈아, 아직도 매일 아침 걸어서 학교 와?",
        "M: 응, 그런데 이제 거의 40분 걸려.",
        "W: 40분? 예전엔 25분이었잖아.",
        "M: 다리를 막아서 멀리 돌아가야 해.",
        "W: 아, 그래서 어제 그렇게 피곤해 보였구나.",
        "M: 요즘은 7시 전에 집에서 나와야 해.",
        "W: 대신 6번 버스를 타는 건 어때?",
        "M: 우리 아파트 근처에 서긴 해?",
        "W: 응, 너희 건물 바로 앞에 10분마다 서.",
        "M: 그럼 내일 아침에 그 버스 타 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Jiyu, our class pet fish looks strange today."],
        ["W", "Strange how? Is it swimming near the bottom?"],
        ["M", "Yes, and it hasn't eaten since yesterday morning."],
        ["W", "Did anyone change the water this week?"],
        ["M", "No, I don't think anybody did."],
        ["W", "That could be the problem. Old water makes fish sick."],
        ["M", "Should we change all of it right now?"],
        ["W", "No, change only half, or the fish gets a shock."],
        ["M", "Okay. What else should we check?"],
        ["W", "Ask the science teacher to look at it after class."],
      ],
      choices: [
        "Let's change all the water now.",
        "The fish ate a lot this morning.",
        "We don't have a class pet.",
        "I'll go to the science room after class.",
        "I'll buy a new fish tomorrow.",
      ],
      answer: 4,
      clue: "Ask the science teacher to look at it after class.",
      explanation:
        "여자가 수업 후에 과학 선생님께 봐 달라고 하라고 했으므로, 수업 끝나고 과학실에 가겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 지유야, 우리 반 물고기가 오늘 좀 이상해.",
        "W: 어떻게 이상한데? 바닥 쪽에서 헤엄쳐?",
        "M: 응, 그리고 어제 아침부터 아무것도 안 먹어.",
        "W: 이번 주에 누가 물 갈았어?",
        "M: 아니, 아무도 안 간 것 같아.",
        "W: 그게 문제일 수 있어. 오래된 물은 물고기를 병들게 해.",
        "M: 지금 물을 다 갈아야 할까?",
        "W: 아니, 절반만 갈아. 안 그러면 물고기가 놀라.",
        "M: 알겠어. 또 뭘 확인해야 해?",
        "W: 수업 끝나고 과학 선생님께 봐 달라고 해.",
        "M: 알겠어. 수업 끝나고 과학실에 갈게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nara가 Junseo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Nara : ________________",
      lines: [
        [
          "W",
          "Nara and Junseo are working together on a class poster. " +
            "They have to hand it in to their teacher by five o'clock. " +
            "It is already four thirty, and the last drawing is not finished. " +
            "Junseo is putting the color pencils back in the box one by one. " +
            "Nara thinks they should finish the drawing before they clean up. " +
            "In this situation, what would Nara most likely say to Junseo?",
        ],
      ],
      choices: [
        "Let's clean the desk first.",
        "Let's finish the drawing first.",
        "The poster is due next week.",
        "I'll buy new color pencils.",
        "The teacher left an hour ago.",
      ],
      answer: 2,
      clue: "Nara thinks they should finish the drawing before they clean up.",
      explanation:
        "제출 시간이 얼마 남지 않았는데 준서가 먼저 정리를 하고 있으므로, 그림부터 끝내자고 말하는 ②가 가장 적절하다.",
      translation: [
        "W: 나라와 준서는 학급 포스터를 함께 만들고 있습니다. 두 사람은 5시까지 선생님께 제출해야 합니다. 벌써 4시 30분인데 마지막 그림이 끝나지 않았습니다. 준서는 색연필을 하나씩 상자에 넣고 있습니다. 나라는 정리하기 전에 그림부터 끝내야 한다고 생각합니다. 이런 상황에서 나라가 준서에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
