/** 중1 듣기 48회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 48회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 화분을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a plant pot?"],
        ["W", "Yes, one for the windowsill in my room."],
        ["M", "We have tall pots and short wide ones."],
        ["W", "A short wide one. My window ledge is narrow."],
        ["M", "Would you like handles on the sides?"],
        ["W", "No handles. They take up too much space."],
        ["M", "This one has a small dish under it."],
        ["W", "Yes, a dish is useful when I water it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A short wide one. My window ledge is narrow. / Yes, a dish is useful when I water it.",
      explanation:
        "여자는 낮고 넓으며 손잡이가 없고 받침 접시가 있는 화분을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five empty plant pots side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a TALL narrow pot standing alone with no dish. " +
          "② a TALL narrow pot with two HANDLES on its sides. " +
          "③ a SHORT WIDE pot with two HANDLES on its sides and no dish. " +
          "④ a TALL narrow pot sitting on a flat round DISH. " +
          "⑤ a SHORT WIDE pot with no handles, sitting on a flat round DISH.",
      },
      translation: [
        "M: 안녕하세요. 화분 찾으세요?",
        "W: 네, 제 방 창턱에 놓을 거예요.",
        "M: 키가 큰 것도 있고 낮고 넓은 것도 있어요.",
        "W: 낮고 넓은 걸로요. 창턱이 좁아요.",
        "M: 옆에 손잡이가 있는 건 어떠세요?",
        "W: 손잡이는 빼 주세요. 자리를 많이 차지해요.",
        "M: 이건 아래에 작은 받침 접시가 있어요.",
        "W: 네, 물 줄 때 접시가 있으면 좋아요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 영어 말하기 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, are you entering the English speaking contest?"],
        ["M", "I signed up yesterday. When is it exactly?"],
        ["W", "Next Thursday, during the seventh period."],
        ["M", "How long should each speech be?"],
        ["W", "Three minutes, and they stop you after that."],
        ["M", "Can we choose our own topic?"],
        ["W", "You pick one of three topics from the notice."],
        ["M", "Where will the contest be held?"],
        ["W", "In the small hall on the third floor."],
      ],
      choices: [
        "대회가 열리는 날",
        "발표하는 시간의 길이",
        "주제를 고르는 방법",
        "대회가 열리는 장소",
        "심사 기준",
      ],
      answer: 5,
      clue: "Next Thursday, during the seventh period.",
      explanation:
        "날짜, 발표 길이, 주제, 장소는 말했지만 심사 기준은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 영어 말하기 대회 나가?",
        "M: 어제 신청했어. 정확히 언제야?",
        "W: 다음 주 목요일 7교시에.",
        "M: 발표는 얼마나 해야 해?",
        "W: 3분. 그 뒤엔 끊어.",
        "M: 주제는 우리가 정해?",
        "W: 안내문에 있는 세 주제 중에 하나 골라.",
        "M: 대회는 어디서 해?",
        "W: 3층 소강당에서.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sora. It's Gunwoo. Are you home now?"],
        ["W", "I just got back. Why?"],
        ["M", "I think I left my umbrella at your house."],
        ["W", "The black one by the shoe rack?"],
        ["M", "That's mine. It's supposed to rain tomorrow."],
        ["W", "It was still there this morning."],
        ["M", "Good. I was worried I lost it."],
        ["W", "Do you want me to bring it to school?"],
        ["M", "Yes, could you bring it in the morning?"],
      ],
      choices: [
        "약속을 미루려고",
        "숙제를 물어보려고",
        "두고 온 물건을 가져다 달라고 하려고",
        "생일을 축하하려고",
        "길을 물어보려고",
      ],
      answer: 3,
      clue: "Yes, could you bring it in the morning?",
      explanation:
        "남자는 두고 온 우산을 아침에 가져다 달라고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 소라야. 건우야. 지금 집이야?",
        "W: 방금 왔어. 왜?",
        "M: 너희 집에 우산을 두고 온 것 같아.",
        "W: 신발장 옆에 있던 검은 거?",
        "M: 그거 내 거야. 내일 비 온대.",
        "W: 오늘 아침까지 거기 있었어.",
        "M: 다행이다. 잃어버린 줄 알았어.",
        "W: 학교에 가져다줄까?",
        "M: 응, 아침에 가져다줄 수 있어?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Hayeon, what time does the museum tour begin?"],
        ["W", "The guide starts at eleven o'clock sharp."],
        ["M", "How long is the bus ride from here?"],
        ["W", "About forty minutes without traffic."],
        ["M", "Then a ten o'clock bus would be too tight."],
        ["W", "We also need ten minutes to buy tickets."],
        ["M", "So we should leave at nine forty."],
        ["W", "There's a bus at nine forty exactly."],
        ["M", "Let's take that one and relax."],
      ],
      choices: ["9:30 a.m.", "9:40 a.m.", "10:00 a.m.", "10:20 a.m.", "11:00 a.m."],
      answer: 2,
      clue: "There's a bus at nine forty exactly.",
      explanation:
        "이동 40분과 표 사는 10분을 생각해 9시 40분 버스를 타기로 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 하연아, 박물관 해설 몇 시에 시작해?",
        "W: 해설사가 11시 정각에 시작해.",
        "M: 여기서 버스로 얼마나 걸려?",
        "W: 막히지 않으면 40분쯤.",
        "M: 그럼 10시 버스는 너무 빠듯하겠다.",
        "W: 표 사는 데도 10분 필요해.",
        "M: 그럼 9시 40분에 출발해야겠네.",
        "W: 9시 40분에 정확히 버스가 있어.",
        "M: 그거 타고 여유 있게 가자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiseok, why are you staring at your shoes?"],
        ["M", "I promised to bring the ball for today's match."],
        ["W", "Don't tell me you left it at home."],
        ["M", "It's still sitting by my front door."],
        ["W", "Everyone is already waiting on the field."],
        ["M", "Twenty people came here because of me."],
        ["W", "We can borrow one from the gym teacher."],
        ["M", "I still feel terrible about wasting their time."],
      ],
      choices: ["excited", "relaxed", "curious", "sorry", "surprised"],
      answer: 4,
      clue: "I still feel terrible about wasting their time.",
      explanation:
        "공을 두고 와서 친구들의 시간을 뺏은 것을 미안해하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 지석아, 왜 신발만 쳐다보고 있어?",
        "M: 오늘 경기에 공 가져오겠다고 했거든.",
        "W: 설마 집에 두고 온 거야?",
        "M: 아직 우리 집 현관에 있어.",
        "W: 다들 벌써 운동장에서 기다려.",
        "M: 나 때문에 스무 명이 왔는데.",
        "W: 체육 선생님께 하나 빌리면 돼.",
        "M: 그래도 시간 뺏은 게 너무 미안해.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Where do I put the plastic bottles?"],
        ["W", "In the blue bin on the left."],
        ["ANN", "Number two."],
        ["M", "Is the elevator working today?"],
        ["W", "No, please use the stairs."],
        ["ANN", "Number three."],
        ["M", "Can I park my bike here?"],
        ["W", "Only in the marked area."],
        ["ANN", "Number four."],
        ["M", "What time is trash collected?"],
        ["W", "Every evening at eight."],
        ["ANN", "Number five."],
        ["M", "Do you need help with that box?"],
        ["W", "Yes, please. It's quite heavy."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Where do I put the plastic bottles?",
      explanation:
        "그림은 분리수거장에서 남자가 플라스틱 병이 든 봉투를 들고 어디에 넣을지 묻는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "An apartment recycling area outdoors, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A man holds a clear bag full of plastic bottles and looks at a row of three large bins with a puzzled face. " +
          "A woman standing beside the bins points at the leftmost bin with her hand. " +
          "A low wall and a tree are drawn simply behind them.",
      },
      translation: [
        "① M: 플라스틱 병은 어디에 넣어요? / W: 왼쪽 파란 통에요.",
        "② M: 오늘 엘리베이터 되나요? / W: 아니요, 계단을 이용하세요.",
        "③ M: 여기 자전거 세워도 되나요? / W: 표시된 곳에만요.",
        "④ M: 쓰레기는 몇 시에 수거해요? / W: 매일 저녁 여덟 시에요.",
        "⑤ M: 그 상자 도와드릴까요? / W: 네, 부탁해요. 꽤 무거워요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongha, you're good with the video editing program, right?"],
        ["M", "I've used it since last winter."],
        ["W", "Our club made a five minute clip for the festival."],
        ["M", "That sounds like a lot of work."],
        ["W", "The problem is the sound. The voices are too quiet."],
        ["M", "That usually takes a few minutes to fix."],
        ["W", "Really? We thought we had to record it again."],
        ["M", "No, you can raise just the voice track."],
        ["W", "Could you make the voices louder for us?"],
        ["M", "Send me the file and I'll do it tonight."],
      ],
      choices: [
        "영상의 소리를 키워 주기",
        "사진을 골라 주기",
        "대본을 써 주기",
        "장비를 빌려주기",
        "포스터를 그려 주기",
      ],
      answer: 1,
      clue: "Could you make the voices louder for us?",
      explanation:
        "여자는 영상 속 목소리를 크게 키워 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 동하야, 영상 편집 프로그램 잘 다루지?",
        "M: 지난겨울부터 써 왔어.",
        "W: 우리 동아리가 축제용으로 5분짜리 영상을 만들었어.",
        "M: 일이 많았겠다.",
        "W: 문제는 소리야. 목소리가 너무 작아.",
        "M: 그건 보통 몇 분이면 고쳐.",
        "W: 정말? 우리는 다시 찍어야 하는 줄 알았어.",
        "M: 아니, 목소리 부분만 키우면 돼.",
        "W: 우리 목소리 좀 키워 줄 수 있어?",
        "M: 파일 보내 줘. 오늘 밤에 해 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 가꾸기에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Let me tell you about our school garden. " +
            "The garden sits behind the science building. " +
            "We will plant lettuce and cherry tomatoes this spring. " +
            "Each class takes care of it for one week in turn. " +
            "Bring your own gloves on the day your class works. " +
            "The small shovels are kept in the shed beside it.",
        ],
      ],
      choices: [
        "텃밭이 있는 곳",
        "심을 작물",
        "관리하는 차례",
        "가져와야 할 물건",
        "수확물을 나누는 방법",
      ],
      answer: 5,
      clue: "The garden sits behind the science building.",
      explanation:
        "위치, 작물, 차례, 준비물은 말했지만 수확물을 나누는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학교 텃밭에 대해 알려 드립니다. 텃밭은 과학관 뒤에 있습니다. 올봄에는 상추와 방울토마토를 심습니다. 각 반이 한 주씩 돌아가며 돌봅니다. 우리 반이 일하는 날에는 장갑을 챙겨 오세요. 작은 삽은 옆 창고에 있습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You wear this on your back when you go to school. " +
            "It has two straps that go over your shoulders. " +
            "Books, a pencil case and a water bottle go inside it. " +
            "Some of them have a small pocket on the side. " +
            "If you fill it with too many books, your back hurts.",
        ],
      ],
      choices: ["책가방", "우산", "사물함", "신발주머니", "필통"],
      answer: 1,
      clue: "It has two straps that go over your shoulders.",
      explanation:
        "어깨끈 두 개로 등에 메고 책과 필통을 넣는 것은 책가방이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 학교에 갈 때 등에 멥니다. 어깨에 걸치는 끈이 두 개 있습니다. 책, 필통, 물병이 그 안에 들어갑니다. 어떤 것은 옆에 작은 주머니가 달려 있습니다. 책을 너무 많이 넣으면 등이 아픕니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What are you going to do this weekend?"],
        ["W", "Visit my cousins in Busan."],
        ["ANN", "Number two."],
        ["M", "How far is the post office?"],
        ["W", "About a ten minute walk."],
        ["ANN", "Number three."],
        ["M", "Could you hold the door for me?"],
        ["W", "Of course, take your time."],
        ["ANN", "Number four."],
        ["M", "Who is your homeroom teacher?"],
        ["W", "The library opens at nine."],
        ["ANN", "Number five."],
        ["M", "Did you enjoy the concert?"],
        ["W", "Every single song was great."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is your homeroom teacher?",
      explanation:
        "담임 선생님을 묻는 말에 도서관 여는 시간을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 이번 주말에 뭐 할 거야? / W: 부산에 사촌들 보러 가.",
        "② M: 우체국이 얼마나 멀어? / W: 걸어서 10분쯤.",
        "③ M: 문 좀 잡아 줄래? / W: 그럼, 천천히 와.",
        "④ M: 너희 담임 선생님이 누구야? / W: 도서관은 아홉 시에 열어.",
        "⑤ M: 공연 재미있었어? / W: 노래 하나하나가 다 좋았어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hoseok, the school bus leaves in twenty minutes."],
        ["M", "I know. My bag is already packed."],
        ["W", "Did you get your permission form signed?"],
        ["M", "My father signed it at breakfast."],
        ["W", "And you handed it to the teacher?"],
        ["M", "It's still inside my math textbook."],
        ["W", "She is collecting them in the classroom now."],
        ["M", "I'll take it to her before the bus leaves."],
      ],
      choices: [
        "가방을 다시 싸기",
        "선생님께 동의서를 내기",
        "아버지께 전화하기",
        "버스에 먼저 타기",
        "교과서를 빌리기",
      ],
      answer: 2,
      clue: "I'll take it to her before the bus leaves.",
      explanation:
        "남자는 버스가 떠나기 전에 선생님께 동의서를 내겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 호석아, 학교 버스가 20분 뒤에 떠나.",
        "M: 알아. 가방은 벌써 다 쌌어.",
        "W: 동의서는 서명받았어?",
        "M: 아침 먹을 때 아버지가 해 주셨어.",
        "W: 그럼 선생님께 드렸어?",
        "M: 아직 수학 교과서 안에 있어.",
        "W: 지금 교실에서 걷고 계셔.",
        "M: 버스 떠나기 전에 갖다 드릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 선택할 강좌를 고르시오.",
      lines: [
        ["M", "Jiyu, the community center has five weekend classes."],
        ["W", "I can only go on Sunday afternoons."],
        ["M", "Two of these meet on Saturday."],
        ["W", "What about the number of weeks?"],
        ["M", "They run for six, eight or ten weeks."],
        ["W", "Six weeks is enough for me this term."],
        ["M", "And the fee?"],
        ["W", "I can pay up to fifty thousand won."],
        ["M", "Then this one fits all three conditions."],
        ["W", "I'll sign up online tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I can only go on Sunday afternoons.",
      explanation:
        "일요일 오후, 6주, 5만 원 이하인 강좌를 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Saturday / Weeks: 6 / Fee: 45,000 won" },
          { no: 2, label: "②", value: "Day: Sunday / Weeks: 10 / Fee: 40,000 won" },
          { no: 3, label: "③", value: "Day: Saturday / Weeks: 8 / Fee: 30,000 won" },
          { no: 4, label: "④", value: "Day: Sunday / Weeks: 6 / Fee: 48,000 won" },
          { no: 5, label: "⑤", value: "Day: Sunday / Weeks: 6 / Fee: 60,000 won" },
        ],
      },
      translation: [
        "M: 지유야, 주민 센터에 주말 강좌가 다섯 개 있어.",
        "W: 나는 일요일 오후에만 갈 수 있어.",
        "M: 두 개는 토요일에 해.",
        "W: 기간은 어때?",
        "M: 6주, 8주, 10주짜리가 있어.",
        "W: 이번 학기엔 6주면 충분해.",
        "M: 수강료는?",
        "W: 5만 원까지는 낼 수 있어.",
        "M: 그럼 이게 세 조건에 다 맞아.",
        "W: 오늘 밤에 누리집에서 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진 전시를 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Dayoung, the photo exhibition downtown ends this month."],
        ["W", "When exactly does the last day fall?"],
        ["M", "On the twenty-fifth, so we still have some time."],
        ["W", "How about the eighteenth? That's a Saturday."],
        ["M", "I have a dentist appointment that whole morning."],
        ["W", "Would the afternoon of the same day work?"],
        ["M", "The tickets are sold out after two on weekends."],
        ["W", "Then what about the nineteenth, the day after?"],
        ["M", "The gallery is closed every Sunday for cleaning."],
        ["W", "So the twentieth, Monday, right after school."],
        ["M", "The twentieth works. Let's meet at the entrance."],
      ],
      choices: ["the 18th", "the 19th", "the 20th", "the 25th", "the 15th"],
      answer: 3,
      clue: "So the twentieth, Monday, right after school.",
      explanation:
        "18일은 치과, 19일은 휴관이어서 20일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 다영아, 시내 사진 전시가 이번 달에 끝나.",
        "W: 마지막 날이 정확히 언제야?",
        "M: 25일. 그러니까 아직 시간은 좀 있어.",
        "W: 18일은 어때? 토요일이야.",
        "M: 그날 아침 내내 치과 예약이 있어.",
        "W: 같은 날 오후는 안 돼?",
        "M: 주말에는 2시 넘으면 표가 다 팔려.",
        "W: 그럼 다음 날 19일은?",
        "M: 전시관이 일요일마다 청소로 문을 닫아.",
        "W: 그럼 20일 월요일 방과 후 바로.",
        "M: 20일 괜찮아. 입구에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Soyul, you weren't in the library yesterday."],
        ["W", "I spent the whole afternoon at the animal shelter."],
        ["M", "Is that the place near the river?"],
        ["W", "Yes, it takes twenty minutes by bike from here."],
        ["M", "What did you do there all afternoon?"],
        ["W", "I washed the food bowls and walked two dogs."],
        ["M", "Weren't the dogs hard to handle?"],
        ["W", "One pulled me the whole way down the path."],
        ["M", "Will you go again this weekend?"],
        ["W", "Every Saturday until the end of the term."],
      ],
      choices: [
        "도서관에서 공부하기",
        "동물 보호소에서 봉사하기",
        "가족과 외식하기",
        "병원에 가기",
        "친구 집에 놀러 가기",
      ],
      answer: 2,
      clue: "I spent the whole afternoon at the animal shelter.",
      explanation:
        "여자는 어제 오후 내내 동물 보호소에서 봉사했다. 따라서 답은 ②이다.",
      translation: [
        "M: 소율아, 어제 도서관에 없더라.",
        "W: 오후 내내 동물 보호소에 있었어.",
        "M: 강 근처에 있는 거기?",
        "W: 응, 여기서 자전거로 20분 걸려.",
        "M: 오후 내내 거기서 뭐 했어?",
        "W: 밥그릇 씻고 개 두 마리 산책시켰어.",
        "M: 개들 다루기 힘들지 않았어?",
        "W: 한 마리가 길 내내 나를 끌고 다녔어.",
        "M: 이번 주말에도 가?",
        "W: 학기 끝날 때까지 매주 토요일에.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the lost and found desk. " +
            "A brown wallet was left in the second floor restroom. " +
            "It holds a student card and a bus card inside. " +
            "The owner should come to the office before six today. " +
            "Please describe the wallet before you take it. " +
            "Thank you for listening carefully.",
        ],
      ],
      choices: [
        "행사를 알리려고",
        "분실물을 찾아가라고 하려고",
        "규칙을 안내하려고",
        "봉사자를 모으려고",
        "공사를 알리려고",
      ],
      answer: 2,
      clue: "A brown wallet was left in the second floor restroom.",
      explanation:
        "잃어버린 갈색 지갑의 주인을 찾는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 분실물 보관소입니다. 2층 화장실에 갈색 지갑이 놓여 있었습니다. 안에는 학생증과 버스 카드가 들어 있습니다. 주인은 오늘 여섯 시 전에 행정실로 와 주세요. 가져가기 전에 지갑의 생김새를 말해 주세요. 잘 들어 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the musical?"],
        ["M", "Yes, three student tickets, please."],
        ["W", "A student ticket is twelve dollars each."],
        ["M", "Do we have to pay for the program?"],
        ["W", "The program costs four dollars."],
        ["M", "We'll take one program for the three of us."],
        ["W", "There is no other charge today."],
        ["M", "All right. Here is my card."],
      ],
      choices: ["$36", "$44", "$48", "$38", "$40"],
      answer: 5,
      clue: "A student ticket is twelve dollars each. / The program costs four dollars.",
      explanation:
        "학생 표 세 장 36달러에 안내 책자 4달러를 더하면 40달러이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요. 뮤지컬 표 사시나요?",
        "M: 네, 학생 표 세 장 주세요.",
        "W: 학생 표는 한 장에 12달러입니다.",
        "M: 안내 책자도 돈을 내야 하나요?",
        "W: 안내 책자는 4달러입니다.",
        "M: 셋이서 한 권만 살게요.",
        "W: 오늘 다른 요금은 없습니다.",
        "M: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaeyeon, you finished all your applications early."],
        ["W", "I wrote down every deadline on one sheet."],
        ["M", "Just one sheet for everything?"],
        ["W", "Yes, and I keep it inside my pencil case."],
        ["M", "I have deadlines in three different apps."],
        ["W", "Then you have to open three apps to check."],
        ["M", "And I still forgot the science one last week."],
        ["W", "One place beats three places every time."],
        ["M", "Could you show me how you set yours up?"],
      ],
      choices: [
        "I don't use any sheet.",
        "You should use more apps.",
        "Sure, bring your case tomorrow.",
        "I missed every deadline.",
        "The applications are closed.",
      ],
      answer: 3,
      clue: "Could you show me how you set yours up?",
      explanation:
        "남자가 정리하는 법을 보여 달라고 했으므로, 내일 필통을 가져오라는 ③이 가장 자연스럽다.",
      translation: [
        "M: 채연아, 너는 신청서를 다 일찍 끝냈더라.",
        "W: 마감일을 종이 한 장에 다 적어 뒀어.",
        "M: 전부 한 장에?",
        "W: 응, 그리고 필통 안에 넣고 다녀.",
        "M: 나는 마감이 앱 세 개에 흩어져 있어.",
        "W: 그럼 확인하려면 앱을 세 개 열어야 하잖아.",
        "M: 그러고도 지난주에 과학 것을 잊었어.",
        "W: 한 군데가 세 군데보다 늘 나아.",
        "M: 어떻게 정리하는지 보여 줄래?",
        "W: 그럼, 내일 필통 가져와.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, are you still tutoring at the community center?"],
        ["M", "Every Saturday morning, for two hours."],
        ["W", "What subject do you teach there?"],
        ["M", "Basic English to fourth and fifth graders."],
        ["W", "Is it hard to explain things to younger children?"],
        ["M", "At first, yes. Now I draw pictures instead of talking."],
        ["W", "That sounds like a good way to teach."],
        ["M", "They remember the pictures much longer."],
        ["W", "Do you need one more helper next month?"],
      ],
      choices: [
        "Yes, please come with me.",
        "I stopped teaching last year.",
        "The center is closed now.",
        "I teach only on Sundays.",
        "Nobody comes to my class.",
      ],
      answer: 1,
      clue: "Do you need one more helper next month?",
      explanation:
        "여자가 다음 달에 도우미가 필요한지 물었으므로, 함께 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 아직 주민 센터에서 가르쳐?",
        "M: 매주 토요일 아침에 두 시간씩.",
        "W: 무슨 과목을 가르쳐?",
        "M: 4, 5학년에게 기초 영어.",
        "W: 어린 아이들에게 설명하는 게 어렵지 않아?",
        "M: 처음엔 어려웠어. 지금은 말 대신 그림을 그려.",
        "W: 좋은 방법 같다.",
        "M: 아이들이 그림을 훨씬 오래 기억해.",
        "W: 다음 달에 도우미 한 명 더 필요해?",
        "M: 응, 같이 가자.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yujin, are you still nervous about the interview?"],
        ["W", "It's tomorrow and I can't stop thinking about it."],
        ["M", "Have you practiced answering out loud?"],
        ["W", "Only in my head, on the way to school."],
        ["M", "Your voice sounds different when you say it aloud."],
        ["W", "I never thought about that before."],
        ["M", "Record yourself once and listen to it."],
        ["W", "Won't it be strange to hear my own voice?"],
        ["M", "Strange for a minute, then very useful."],
      ],
      choices: [
        "I already passed the interview.",
        "All right, I'll record it tonight.",
        "I don't have an interview.",
        "Speaking aloud is useless.",
        "You should stop practicing.",
      ],
      answer: 2,
      clue: "Record yourself once and listen to it.",
      explanation:
        "녹음해서 들어 보라는 조언이므로, 오늘 밤 녹음하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 유진아, 아직도 면접 때문에 긴장돼?",
        "W: 내일인데 계속 생각나.",
        "M: 소리 내어 대답해 보는 연습은 했어?",
        "W: 학교 오는 길에 머릿속으로만.",
        "M: 소리 내어 말하면 목소리가 다르게 들려.",
        "W: 그건 생각 못 했어.",
        "M: 한 번 녹음해서 들어 봐.",
        "W: 내 목소리 듣는 거 이상하지 않을까?",
        "M: 1분만 이상하고 그다음엔 아주 쓸모 있어.",
        "W: 알겠어, 오늘 밤에 녹음해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Haeun이 Junsu에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Haeun : ________________",
      lines: [
        [
          "W",
          "Haeun and Junsu are working at the school library together. " +
            "Junsu puts the returned books back on the shelves very quickly. " +
            "Haeun notices that he is placing them in the wrong sections. " +
            "If the books stay there, no one will be able to find them. " +
            "She wants to ask him to slow down and check the labels. " +
            "In this situation, what would Haeun most likely say to Junsu?",
        ],
      ],
      choices: [
        "The library closes at six today.",
        "Let's borrow these books together.",
        "Check the label before you shelve it.",
        "You can take a break now.",
        "We need more books here.",
      ],
      answer: 3,
      clue: "She wants to ask him to slow down and check the labels.",
      explanation:
        "책을 엉뚱한 칸에 꽂고 있으므로, 꽂기 전에 이름표를 확인하라는 ③이 가장 적절하다.",
      translation: [
        "W: 하은이와 준수는 학교 도서관에서 함께 일하고 있습니다. 준수는 반납된 책을 아주 빠르게 책장에 다시 꽂습니다. 하은이는 준수가 책을 엉뚱한 칸에 꽂고 있는 것을 봅니다. 그대로 두면 아무도 그 책을 찾지 못할 것입니다. 하은이는 천천히 하면서 이름표를 확인하라고 말하고 싶습니다. 이런 상황에서 하은이가 준수에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
