/** 중1 듣기 42회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 42회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 모자를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a hat?"],
        ["W", "Yes, one for the school field trip."],
        ["M", "Do you want a round cap or a wide one?"],
        ["W", "A wide one. The sun is strong in May."],
        ["M", "This wide hat has a ribbon around it."],
        ["W", "No ribbon, please. It looks too dressy."],
        ["M", "Would you like a small pocket on the side?"],
        ["W", "No pocket. Just a plain wide hat."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "A wide one. The sun is strong in May. / No ribbon, please. It looks too dressy.",
      explanation:
        "여자는 챙이 넓고 리본과 주머니가 없는 모자를 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five hats laid side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a ROUND CAP with a short peak and no ribbon. " +
          "② a WIDE-BRIMMED hat with a RIBBON band around the crown. " +
          "③ a plain WIDE-BRIMMED hat with no ribbon and no pocket. " +
          "④ a WIDE-BRIMMED hat with a small POCKET sewn on the side of the crown. " +
          "⑤ a ROUND CAP with a RIBBON band around it.",
      },
      translation: [
        "M: 안녕하세요. 모자 찾으세요?",
        "W: 네, 학교 체험 학습 때 쓸 거예요.",
        "M: 둥근 모자가 좋으세요, 챙 넓은 게 좋으세요?",
        "W: 챙 넓은 거요. 5월에는 햇볕이 세요.",
        "M: 이 챙 넓은 모자는 둘레에 리본이 있어요.",
        "W: 리본은 빼 주세요. 너무 차려입은 느낌이에요.",
        "M: 옆에 작은 주머니 달린 건 어떠세요?",
        "W: 주머니도 없이요. 그냥 챙 넓은 모자로요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 체험 학습에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minho, where are we going for the field trip this year?"],
        ["M", "To the folk village outside the city."],
        ["W", "How long does the bus take to get there?"],
        ["M", "About an hour and a half each way."],
        ["W", "When do we leave in the morning?"],
        ["M", "The bus leaves at eight thirty from the front gate."],
        ["W", "Do we need to bring our own lunch?"],
        ["M", "Yes, the teacher said to pack a lunch box."],
        ["W", "What should we wear that day?"],
        ["M", "Comfortable shoes, because we walk a lot there."],
      ],
      choices: [
        "가는 곳",
        "출발하는 시각",
        "점심 준비",
        "신어야 할 신발",
        "내야 하는 돈",
      ],
      answer: 5,
      clue: "To the folk village outside the city.",
      explanation:
        "장소, 출발 시각, 점심, 신발은 말했지만 비용은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민호야, 올해 체험 학습 어디로 가?",
        "M: 시 외곽 민속촌으로.",
        "W: 버스로 얼마나 걸려?",
        "M: 한쪽으로 한 시간 반쯤.",
        "W: 아침에 몇 시에 출발해?",
        "M: 정문에서 8시 30분에 떠나.",
        "W: 점심은 각자 가져가야 해?",
        "M: 응, 선생님이 도시락 싸 오라고 하셨어.",
        "W: 그날 뭘 입어야 해?",
        "M: 거기서 많이 걸으니까 편한 신발.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Yuna. It's Jaemin. Are you busy right now?"],
        ["W", "Not really. I just got home. What's up?"],
        ["M", "I can't find my English workbook anywhere."],
        ["W", "Did you leave it in the classroom?"],
        ["M", "Maybe on the desk by the window."],
        ["W", "The one you sat at during fifth period?"],
        ["M", "That one. I had it open before the bell."],
        ["W", "I'll be there early tomorrow morning."],
        ["M", "Could you look for it and bring it?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "책을 찾아 달라고 하려고",
        "약속을 미루려고",
        "생일을 축하하려고",
        "길을 물어보려고",
      ],
      answer: 2,
      clue: "Could you look for it and bring it?",
      explanation:
        "남자는 교실에 두고 온 책을 찾아 가져다 달라고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 유나야. 재민이야. 지금 바빠?",
        "W: 아니. 방금 집에 왔어. 무슨 일이야?",
        "M: 영어 익힘책을 어디서도 못 찾겠어.",
        "W: 교실에 두고 왔어?",
        "M: 창가 책상 위에 있을 거야.",
        "W: 5교시에 앉았던 그 자리?",
        "M: 거기. 종 치기 전에 펴 놓고 있었어.",
        "W: 내일 아침에 일찍 갈 거야.",
        "M: 찾아서 가져다줄 수 있어?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Sora, when does the art class start?"],
        ["W", "The teacher opens the room at four."],
        ["M", "Do we have to spread the newspaper first?"],
        ["W", "Yes, and that takes about ten minutes."],
        ["M", "Then we should be there by three fifty."],
        ["W", "My music class ends at three forty-five."],
        ["M", "So three fifty is fine for you."],
        ["W", "Let's meet at three fifty by the door."],
        ["M", "Three fifty. I'll bring the brushes."],
      ],
      choices: ["3:40 p.m.", "3:45 p.m.", "3:50 p.m.", "4:00 p.m.", "4:10 p.m."],
      answer: 3,
      clue: "Let's meet at three fifty by the door.",
      explanation:
        "신문지를 까는 시간을 생각해 3시 50분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 소라야, 미술 수업 몇 시에 시작해?",
        "W: 선생님이 네 시에 교실을 열어 주셔.",
        "M: 먼저 신문지를 깔아야 해?",
        "W: 응, 그게 10분쯤 걸려.",
        "M: 그럼 3시 50분까지는 가 있어야겠다.",
        "W: 내 음악 수업이 3시 45분에 끝나.",
        "M: 그럼 3시 50분이 괜찮겠네.",
        "W: 3시 50분에 문 앞에서 만나자.",
        "M: 3시 50분. 붓은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiyu, why do you keep looking at the door?"],
        ["W", "My puppy ran out of the gate this morning."],
        ["M", "Did you look around your house?"],
        ["W", "My mother and I looked for two whole hours."],
        ["M", "Did you go down to the park as well?"],
        ["W", "Twice, and we called his name at every corner."],
        ["M", "Maybe a neighbor found him and took him in."],
        ["W", "Nobody has called us yet."],
        ["M", "He knows the way home, doesn't he?"],
        ["W", "He is only three months old."],
      ],
      choices: ["worried", "happy", "bored", "proud", "angry"],
      answer: 1,
      clue: "He is only three months old.",
      explanation:
        "어린 강아지가 나가서 돌아오지 않아 걱정하고 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 지유야, 왜 자꾸 문만 보고 있어?",
        "W: 오늘 아침에 강아지가 대문 밖으로 나갔어.",
        "M: 집 둘레는 찾아봤어?",
        "W: 엄마랑 두 시간을 꼬박 찾았어.",
        "M: 공원까지도 내려가 봤어?",
        "W: 두 번. 모퉁이마다 이름을 불렀어.",
        "M: 이웃이 찾아서 데리고 있을지도 몰라.",
        "W: 아직 아무도 전화 안 왔어.",
        "M: 집으로 오는 길은 알잖아?",
        "W: 태어난 지 석 달밖에 안 됐어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Where can I find bread?"],
        ["M", "In the second aisle."],
        ["ANN", "Number two."],
        ["W", "Do you have a bigger cart?"],
        ["M", "They're by the entrance."],
        ["ANN", "Number three."],
        ["W", "How much are these apples?"],
        ["M", "Five thousand won for six."],
        ["ANN", "Number four."],
        ["W", "My bag is too heavy."],
        ["M", "Let me carry it for you."],
        ["ANN", "Number five."],
        ["W", "Can I pay here?"],
        ["M", "Yes, this counter is open."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "My bag is too heavy.",
      explanation:
        "그림은 가게 앞에서 남학생이 할머니의 무거운 가방을 받아 드는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Outside a small grocery shop, clean black line art on a plain white background, no writing or letters anywhere. " +
          "An elderly woman holds a bulging shopping bag with both hands and looks tired. " +
          "A boy student with a backpack reaches out with both hands to take the bag from her, smiling. " +
          "The shop door and boxes of vegetables are drawn simply behind them.",
      },
      translation: [
        "① W: 빵은 어디에 있나요? / M: 둘째 줄에 있어요.",
        "② W: 더 큰 수레 있나요? / M: 입구 옆에 있어요.",
        "③ W: 이 사과 얼마예요? / M: 여섯 개에 5천 원이요.",
        "④ W: 가방이 너무 무거워요. / M: 제가 들어 드릴게요.",
        "⑤ W: 여기서 계산해도 되나요? / M: 네, 이 계산대 열려 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, are you good at drawing?"],
        ["M", "I like it more than I'm actually good at it."],
        ["W", "Our class is making a welcome poster this week."],
        ["M", "For the new students who come next Monday?"],
        ["W", "Yes, and we finished the pictures yesterday."],
        ["M", "Then what is left to do on it?"],
        ["W", "Nobody in our class can draw the big letters."],
        ["M", "Big letters are easier than pictures, honestly."],
        ["W", "Could you draw the title on the poster?"],
        ["M", "Sure, I'll do it right after lunch."],
      ],
      choices: [
        "포스터에 제목을 그려 주기",
        "물감을 빌려주기",
        "신입생을 안내하기",
        "교실을 꾸미기",
        "사진을 찍어 주기",
      ],
      answer: 1,
      clue: "Could you draw the title on the poster?",
      explanation:
        "여자는 포스터에 제목 글씨를 그려 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 준호야, 그림 잘 그려?",
        "M: 잘 그리기보다 좋아하는 쪽이야.",
        "W: 우리 반이 이번 주에 환영 포스터를 만들어.",
        "M: 다음 주 월요일에 오는 신입생들 거?",
        "W: 응, 그림은 어제 다 끝냈어.",
        "M: 그럼 뭐가 남았는데?",
        "W: 우리 반에 큰 글씨를 그릴 사람이 없어.",
        "M: 솔직히 큰 글씨는 그림보다 쉬워.",
        "W: 포스터에 제목 좀 그려 줄래?",
        "M: 그래, 점심 먹고 바로 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 도서관 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The library has a book week next month. " +
            "It runs from Monday to Friday in the first week. " +
            "You may read in the library until five each day. " +
            "There is a drawing table for your favorite book cover. " +
            "Ask the librarian if you want to join.",
        ],
      ],
      choices: [
        "행사를 하는 기간",
        "머물 수 있는 시각",
        "할 수 있는 활동",
        "참여하는 방법",
        "받을 수 있는 선물",
      ],
      answer: 5,
      clue: "It runs from Monday to Friday in the first week.",
      explanation:
        "기간, 시각, 활동, 참여 방법은 말했지만 선물은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 다음 달에 도서관 독서 주간이 있습니다. 첫째 주 월요일부터 금요일까지 합니다. 매일 다섯 시까지 도서관에서 책을 읽을 수 있습니다. 좋아하는 책 표지를 그리는 탁자도 있습니다. 참여하고 싶으면 사서 선생님께 말씀하세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You wear this on your feet when it rains. " +
            "It is made of rubber and comes up to your calf. " +
            "Water cannot get inside if you close it well. " +
            "Children like to jump in puddles with it. " +
            "You take it off at the door so the floor stays dry.",
        ],
      ],
      choices: ["운동화", "장화", "슬리퍼", "양말", "우산"],
      answer: 2,
      clue: "It is made of rubber and comes up to your calf.",
      explanation:
        "비 올 때 신는 고무로 만든 긴 신발은 장화이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이것은 비가 올 때 발에 신습니다. 고무로 만들고 종아리까지 올라옵니다. 잘 여미면 물이 안으로 들어오지 않습니다. 아이들은 이것을 신고 물웅덩이에서 뛰는 걸 좋아합니다. 바닥이 젖지 않게 문 앞에서 벗습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What time is it now?"],
        ["W", "It's a quarter past two."],
        ["ANN", "Number two."],
        ["M", "Do you like winter or summer?"],
        ["W", "Winter, because I like snow."],
        ["ANN", "Number three."],
        ["M", "How many pencils do you have?"],
        ["W", "My house is near the park."],
        ["ANN", "Number four."],
        ["M", "Can I borrow your ruler?"],
        ["W", "Sure, here you are."],
        ["ANN", "Number five."],
        ["M", "Where is your classroom?"],
        ["W", "On the third floor."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How many pencils do you have?",
      explanation:
        "연필이 몇 자루인지 묻는 말에 집 위치를 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 지금 몇 시야? / W: 두 시 15분이야.",
        "② M: 겨울이 좋아, 여름이 좋아? / W: 겨울. 눈을 좋아해.",
        "③ M: 연필 몇 자루 있어? / W: 우리 집은 공원 근처야.",
        "④ M: 네 자 좀 빌려도 돼? / W: 그럼, 여기.",
        "⑤ M: 너희 교실 어디야? / W: 3층에.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, is that your water bottle on the shelf?"],
        ["W", "It looks like mine. Let me see."],
        ["M", "The class is going to the gym now."],
        ["W", "And the door gets locked, right?"],
        ["M", "Until the end of the fifth period."],
        ["W", "I need my bottle for gym class."],
        ["M", "We have about two minutes."],
        ["W", "I'll grab my bottle from the shelf."],
      ],
      choices: [
        "체육관에 먼저 가기",
        "선반에서 물병을 가져오기",
        "선생님께 여쭤보기",
        "교실을 잠그기",
        "집에 전화하기",
      ],
      answer: 2,
      clue: "I'll grab my bottle from the shelf.",
      explanation:
        "여자는 선반에서 물병을 가져오겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 나리야, 선반에 있는 게 네 물병이야?",
        "W: 내 것 같아. 볼게.",
        "M: 반이 지금 체육관에 가.",
        "W: 그럼 문 잠그지?",
        "M: 5교시 끝날 때까지.",
        "W: 체육 시간에 물병이 필요한데.",
        "M: 2분쯤 남았어.",
        "W: 선반에서 물병 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 필통을 고르시오.",
      lines: [
        ["W", "Dongho, which pencil case are you buying?"],
        ["M", "There are five on this page."],
        ["W", "How much can you spend?"],
        ["M", "Under eight thousand won."],
        ["W", "Two of them are more than that."],
        ["M", "And I want two pockets, not one."],
        ["W", "One of the cheaper ones has only one."],
        ["M", "I also want a zipper, not a button."],
        ["W", "Then only one is left for you."],
        ["M", "I'll buy it on the way home."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Under eight thousand won.",
      explanation:
        "8천 원 미만, 주머니 두 개, 지퍼인 것을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 9,000 won / Pockets: 2 / Closing: Zipper" },
          { no: 2, label: "②", value: "Price: 10,000 won / Pockets: 1 / Closing: Zipper" },
          { no: 3, label: "③", value: "Price: 6,000 won / Pockets: 1 / Closing: Zipper" },
          { no: 4, label: "④", value: "Price: 7,500 won / Pockets: 2 / Closing: Zipper" },
          { no: 5, label: "⑤", value: "Price: 7,000 won / Pockets: 2 / Closing: Button" },
        ],
      },
      translation: [
        "W: 동호야, 어떤 필통 살 거야?",
        "M: 이 쪽에 다섯 개 있어.",
        "W: 얼마까지 쓸 수 있어?",
        "M: 8천 원 아래로.",
        "W: 두 개는 그보다 비싸.",
        "M: 그리고 주머니가 하나 말고 두 개였으면 좋겠어.",
        "W: 싼 것 중 하나는 주머니가 하나야.",
        "M: 단추 말고 지퍼도 필요해.",
        "W: 그럼 하나만 남네.",
        "M: 집에 가는 길에 살게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 도서관에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Suyeon, when can we go to the city library?"],
        ["W", "It opens late on three days this week."],
        ["M", "Which days are they exactly?"],
        ["W", "The eighth, the tenth and the twelfth."],
        ["M", "The eighth is our math test day."],
        ["W", "We could go after the test, but we would be tired."],
        ["M", "Too tired to read anything, I think."],
        ["W", "And I have piano until six on the tenth."],
        ["M", "Then the twelfth is the only day left."],
        ["W", "It's a Friday, so we finish school early."],
        ["M", "Let's go on the twelfth right after school."],
      ],
      choices: ["the 8th", "the 10th", "the 12th", "the 14th", "the 6th"],
      answer: 3,
      clue: "Then the twelfth is the only day.",
      explanation:
        "8일은 시험, 10일은 피아노 수업이어서 12일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수연아, 시립 도서관 언제 갈 수 있어?",
        "W: 이번 주에 사흘 늦게까지 열어.",
        "M: 정확히 어떤 날이야?",
        "W: 8일, 10일, 12일.",
        "M: 8일은 수학 시험 날이야.",
        "W: 시험 끝나고 갈 수도 있는데 피곤하겠지.",
        "M: 아무것도 못 읽을 만큼 피곤할 거야.",
        "W: 그리고 10일에는 여섯 시까지 피아노가 있어.",
        "M: 그럼 남는 건 12일뿐이네.",
        "W: 금요일이라 학교가 일찍 끝나.",
        "M: 12일 방과 후에 바로 가자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sihoon, what did you do last Saturday?"],
        ["M", "I made cookies with my grandmother all afternoon."],
        ["W", "Did you make them from the very beginning?"],
        ["M", "We mixed the flour and the butter ourselves."],
        ["W", "That sounds harder than opening a box."],
        ["M", "My arm hurt after stirring for ten minutes."],
        ["W", "How many cookies did you make in the end?"],
        ["M", "About forty, and we gave half of them away."],
        ["W", "Were they any good?"],
        ["M", "The first ten were a little burned."],
      ],
      choices: [
        "할머니와 과자를 만들기",
        "친구와 축구를 하기",
        "집에서 쉬기",
        "도서관에 가기",
        "가족과 여행을 가기",
      ],
      answer: 1,
      clue: "I made cookies with my grandmother.",
      explanation:
        "남자는 토요일에 할머니와 과자를 만들었다. 따라서 답은 ①이다.",
      translation: [
        "W: 시훈아, 지난 토요일에 뭐 했어?",
        "M: 오후 내내 할머니랑 과자를 만들었어.",
        "W: 아주 처음부터 만들었어?",
        "M: 밀가루랑 버터를 직접 섞었어.",
        "W: 상자 뜯는 것보다 힘들었겠다.",
        "M: 10분 젓고 나니까 팔이 아팠어.",
        "W: 결국 몇 개나 만들었어?",
        "M: 마흔 개쯤. 그중 절반은 나눠 줬어.",
        "W: 맛은 좀 있었어?",
        "M: 처음 열 개는 좀 탔어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school office. " +
            "The water in the third floor restroom is not working. " +
            "It stopped during the second period this morning. " +
            "Workers are fixing the pipe this afternoon. " +
            "Please use the restroom on the second floor today. " +
            "The one beside the stairs is open all day. " +
            "It will be ready again tomorrow morning. " +
            "Thank you for your patience.",
        ],
      ],
      choices: [
        "화장실을 쓸 수 없다고 알리려고",
        "행사를 소개하려고",
        "분실물을 찾으려고",
        "청소를 부탁하려고",
        "시험을 안내하려고",
      ],
      answer: 1,
      clue: "The water in the third floor restroom is not working.",
      explanation:
        "3층 화장실을 쓸 수 없으니 2층을 쓰라고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 행정실입니다. 3층 화장실 물이 나오지 않습니다. 오늘 아침 2교시에 멈췄습니다. 오후에 작업하시는 분들이 배관을 고칩니다. 오늘은 2층 화장실을 이용해 주세요. 계단 옆 화장실은 하루 종일 열려 있습니다. 내일 아침에는 다시 쓸 수 있습니다. 기다려 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What would you like to buy today?"],
        ["W", "Three notebooks and one eraser, please."],
        ["M", "Would you like the lined ones or the plain ones?"],
        ["W", "The lined ones. They're for my English class."],
        ["M", "A notebook is two dollars each."],
        ["W", "And how much is the eraser?"],
        ["M", "One dollar, and it comes in white or pink."],
        ["W", "White, please. Do I need to pay for the bag?"],
        ["M", "The bag is free today."],
        ["W", "Good. Here you are."],
      ],
      choices: ["$6", "$7", "$8", "$5", "$9"],
      answer: 2,
      clue: "A notebook is two dollars each.",
      explanation:
        "공책 세 권 6달러에 지우개 1달러를 더하면 7달러이다. 따라서 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 오늘은 뭘 사시겠어요?",
        "W: 공책 세 권이랑 지우개 하나요.",
        "M: 줄이 있는 걸로 드릴까요, 없는 걸로 드릴까요?",
        "W: 줄 있는 걸로요. 영어 시간에 쓸 거예요.",
        "M: 공책은 한 권에 2달러입니다.",
        "W: 지우개는 얼마예요?",
        "M: 1달러이고 흰색과 분홍색이 있습니다.",
        "W: 흰색으로요. 봉투는 돈을 내야 하나요?",
        "M: 오늘은 봉투가 무료입니다.",
        "W: 좋아요. 여기요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taemin, your desk is always tidy."],
        ["M", "I put things back right after I use them."],
        ["W", "Doesn't that stop your work?"],
        ["M", "It takes about three seconds each time."],
        ["W", "Mine gets messy by second period."],
        ["M", "Then you clean it all at once later."],
        ["W", "And that takes twenty minutes."],
        ["M", "Three seconds now beats twenty minutes later."],
        ["W", "Could you help me tidy mine today?"],
      ],
      choices: [
        "Sure, let's start after lunch.",
        "My desk is messy too.",
        "You should buy a new desk.",
        "I never tidy anything.",
        "Twenty minutes is fine.",
      ],
      answer: 1,
      clue: "Could you help me tidy mine today?",
      explanation:
        "여자가 정리를 도와 달라고 했으므로, 점심 먹고 하자는 ①이 가장 자연스럽다.",
      translation: [
        "W: 태민아, 네 책상은 늘 깔끔해.",
        "M: 쓰고 나면 바로 제자리에 둬.",
        "W: 그러면 하던 일이 끊기지 않아?",
        "M: 매번 3초쯤 걸려.",
        "W: 내 책상은 2교시면 지저분해져.",
        "M: 그럼 나중에 한꺼번에 치우게 되지.",
        "W: 그게 20분 걸려.",
        "M: 지금 3초가 나중 20분보다 나아.",
        "W: 오늘 내 책상 치우는 것 좀 도와줄래?",
        "M: 그럼, 점심 먹고 시작하자.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Areum, do you still walk your neighbor's dog?"],
        ["W", "Every evening after dinner, since the summer."],
        ["M", "How long do you walk him for?"],
        ["W", "Twenty minutes around the block and back."],
        ["M", "Does he pull hard on the leash?"],
        ["W", "He did at first, but not anymore."],
        ["M", "How did you get him to stop that?"],
        ["W", "I stop walking whenever he pulls."],
        ["M", "And he learned it just from that?"],
        ["W", "It took two weeks, but yes."],
        ["M", "Could I come with you tonight?"],
      ],
      choices: [
        "Sure, we leave at seven.",
        "I don't have a dog.",
        "The dog is gone now.",
        "You can't walk at night.",
        "I stopped last month.",
      ],
      answer: 1,
      clue: "Could I come with you tonight?",
      explanation:
        "남자가 오늘 밤 같이 가도 되는지 물었으므로, 일곱 시에 나간다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 아름아, 아직 이웃집 개 산책시켜?",
        "W: 여름부터 저녁 먹고 매일 저녁에.",
        "M: 얼마나 걸어?",
        "W: 동네 한 바퀴 돌아오는 데 20분.",
        "M: 줄을 세게 당기지 않아?",
        "W: 처음엔 그랬는데 이제 안 그래.",
        "M: 어떻게 그만두게 했어?",
        "W: 당길 때마다 내가 멈춰 서.",
        "M: 그것만으로 배웠어?",
        "W: 두 주 걸렸지만 그래.",
        "M: 오늘 밤에 나도 같이 가도 돼?",
        "W: 그럼, 우리는 일곱 시에 나가.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunwoo, how are you learning the new words?"],
        ["M", "I write each one ten times in my notebook."],
        ["W", "Do you remember them the next day?"],
        ["M", "About half of them, maybe a little less."],
        ["W", "Ten times is a lot of writing for half."],
        ["M", "It takes me nearly an hour every night."],
        ["W", "An hour for twenty words is too much."],
        ["M", "I don't really know another way."],
        ["W", "Cover the meaning and try to say it out loud."],
        ["M", "Even if I can't remember it at all?"],
        ["W", "Especially then. That's when you learn it."],
      ],
      choices: [
        "I already know every word.",
        "All right, I'll try tonight.",
        "Writing is the only way.",
        "I don't learn words.",
        "You should write them for me.",
      ],
      answer: 2,
      clue: "Especially then. That's when you learn it.",
      explanation:
        "뜻을 가리고 말해 보라는 조언이므로, 오늘 밤에 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 현우야, 새 단어를 어떻게 외워?",
        "M: 공책에 하나씩 열 번 써.",
        "W: 다음 날 기억나?",
        "M: 절반쯤. 그보다 조금 적을 수도.",
        "W: 절반을 얻자고 열 번을 쓰는 거네.",
        "M: 밤마다 한 시간 가까이 걸려.",
        "W: 단어 스무 개에 한 시간은 너무 많아.",
        "M: 사실 다른 방법을 몰라.",
        "W: 뜻을 가리고 소리 내어 말해 봐.",
        "M: 아예 기억이 안 나도?",
        "W: 그때가 특히. 그때 외워지는 거야.",
        "M: 알겠어, 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Somin이 Jiho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Somin : ________________",
      lines: [
        [
          "W",
          "Somin and Jiho are walking to the school gate after class. " +
            "Jiho is carrying a paper cup of juice in one hand. " +
            "Somin sees that he is about to drop it into the paper bin. " +
            "The school has a separate bin for cups right beside it. " +
            "She wants to tell him before the cup goes in. " +
            "In this situation, what would Somin most likely say to Jiho?",
        ],
      ],
      choices: [
        "The gate closes at six today.",
        "Cups go in the other bin.",
        "Let's buy more juice.",
        "I'll carry your bag.",
        "The paper bin is full.",
      ],
      answer: 2,
      clue: "She wants to tell him before the cup goes in.",
      explanation:
        "컵은 종이통이 아니라 옆의 컵 전용 통에 넣어야 하므로 ②가 가장 적절하다.",
      translation: [
        "W: 소민이와 지호는 수업이 끝나고 교문으로 걸어가고 있습니다. 지호는 한 손에 종이컵에 든 주스를 들고 있습니다. 소민이는 지호가 그것을 종이 수거함에 버리려는 것을 봅니다. 바로 옆에 컵을 따로 모으는 통이 있습니다. 소민이는 컵이 들어가기 전에 말해 주고 싶습니다. 이런 상황에서 소민이가 지호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
