/** 중1 듣기 13회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 13회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 우산을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for an umbrella?"],
        ["W", "Yes. Mine broke on the way to school this morning."],
        ["M", "We have folding ones and long ones. Which do you want?"],
        ["W", "A long one, please. The folding ones break too easily."],
        ["M", "All right. Do you like a curved handle or a straight one?"],
        ["W", "A curved handle. I can hang it on my desk."],
        ["M", "Then we have two left. One has dots and one has no pattern."],
        ["W", "I'll take the one with no pattern. It looks cleaner."],
        ["M", "Good choice. It's also very light."],
        ["W", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'll take the one with no pattern. It looks cleaner.",
      explanation:
        "여자는 접이식이 아닌 긴 우산을, 손잡이가 굽은 것으로, 무늬 없는 것을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five umbrellas shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a small FOLDING umbrella, closed and short, with no pattern. " +
          "Second: a small FOLDING umbrella, closed and short, covered in round dots. " +
          "Third: a LONG umbrella with a CURVED hook handle, covered in round dots. " +
          "Fourth: a LONG umbrella with a CURVED hook handle and no pattern at all. " +
          "Fifth: a LONG umbrella with a STRAIGHT handle and no pattern at all.",
      },
      translation: [
        "M: 안녕하세요. 우산 찾으세요?",
        "W: 네. 오늘 아침 학교 가는 길에 제 우산이 부러졌어요.",
        "M: 접이식과 긴 우산이 있어요. 어느 것으로 하시겠어요?",
        "W: 긴 우산으로요. 접이식은 너무 잘 부러져요.",
        "M: 알겠습니다. 손잡이는 굽은 것과 곧은 것 중 어느 쪽이 좋으세요?",
        "W: 굽은 손잡이요. 책상에 걸 수 있거든요.",
        "M: 그럼 두 개 남았네요. 하나는 물방울무늬가 있고 하나는 무늬가 없습니다.",
        "W: 무늬 없는 걸로 할게요. 더 깔끔해 보여요.",
        "M: 좋은 선택이세요. 아주 가볍기도 합니다.",
        "W: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 벼룩시장에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jinu, are you going to the school flea market?"],
        ["M", "I want to, but I don't know much about it."],
        ["W", "It's next Friday, right after lunch."],
        ["M", "Where is it going to be?"],
        ["W", "On the playground, next to the basketball court."],
        ["M", "What can we sell there?"],
        ["W", "Books, clothes, and toys you don't use anymore."],
        ["M", "And what happens to the money?"],
        ["W", "It all goes to the children's hospital in our city."],
        ["M", "That's nice. I'll look for things at home tonight."],
      ],
      choices: ["열리는 날", "장소", "준비물", "파는 물건", "수익금 사용처"],
      answer: 3,
      clue: "It all goes to the children's hospital in our city.",
      explanation:
        "열리는 날(다음 주 금요일), 장소(운동장), 파는 물건(책·옷·장난감), 수익금 사용처(어린이 병원)는 언급되지만 준비물은 언급되지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 진우야, 학교 벼룩시장 갈 거야?",
        "M: 가고 싶은데 잘 몰라.",
        "W: 다음 주 금요일, 점심시간 바로 다음이야.",
        "M: 어디에서 하는데?",
        "W: 운동장에서, 농구 코트 옆에.",
        "M: 거기서 뭘 팔 수 있어?",
        "W: 이제 안 쓰는 책, 옷, 장난감.",
        "M: 돈은 어떻게 되는데?",
        "W: 전부 우리 시 어린이 병원에 가.",
        "M: 좋다. 오늘 밤에 집에서 물건을 찾아봐야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junsu. This is Minji from class two."],
        ["M", "Oh, hi, Minji. What's up?"],
        ["W", "You borrowed my science book last week."],
        ["M", "That's right. I still have it on my desk."],
        ["W", "We have a test on Thursday, so I need it back."],
        ["M", "No problem. I'll bring it to school tomorrow."],
        ["W", "Thank you. See you tomorrow morning."],
      ],
      choices: [
        "약속을 취소하려고",
        "생일 파티에 초대하려고",
        "길을 물어보려고",
        "숙제 범위를 알려 주려고",
        "빌려 간 책을 언제 돌려줄지 물어보려고",
      ],
      answer: 5,
      clue: "We have a test on Thursday, so I need it back.",
      explanation:
        "여자는 남자가 빌려 간 과학책을 목요일 시험 때문에 돌려받으려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준수야. 2반 민지야.",
        "M: 아, 안녕. 무슨 일이야?",
        "W: 지난주에 내 과학책 빌려 갔잖아.",
        "M: 맞아. 아직 책상에 있어.",
        "W: 목요일에 시험이 있어서 돌려받아야 해.",
        "M: 알았어. 내일 학교에 가져갈게.",
        "W: 고마워. 내일 아침에 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taeho, what time should we meet at the park?"],
        ["M", "The bike rental closes at four, doesn't it?"],
        ["W", "Yes, so we need at least an hour before that."],
        ["M", "How about two o'clock?"],
        ["W", "I have lunch with my grandmother until two."],
        ["M", "Then how long do you need after lunch?"],
        ["W", "About thirty minutes to get to the park."],
        ["M", "Then let's meet at two thirty."],
        ["W", "Two thirty is perfect. See you at the gate."],
      ],
      choices: ["2:00 p.m.", "2:30 p.m.", "3:00 p.m.", "3:30 p.m.", "4:00 p.m."],
      answer: 2,
      clue: "Then let's meet at two thirty.",
      explanation:
        "여자가 2시까지 점심을 먹고 공원까지 30분이 걸리므로 두 사람은 2시 30분에 만나기로 한다. 따라서 답은 ②이다.",
      translation: [
        "W: 태호야, 공원에서 몇 시에 만날까?",
        "M: 자전거 대여소가 4시에 닫지?",
        "W: 응, 그래서 적어도 한 시간은 있어야 해.",
        "M: 2시는 어때?",
        "W: 2시까지 할머니랑 점심을 먹어.",
        "M: 그럼 점심 먹고 얼마나 걸려?",
        "W: 공원까지 30분쯤.",
        "M: 그럼 2시 30분에 만나자.",
        "W: 2시 30분 좋아. 정문에서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sungmin, you're smiling all morning. What's going on?"],
        ["M", "My family is going to the amusement park this Saturday."],
        ["W", "Have you been there before?"],
        ["M", "No, never. It's my first time."],
        ["W", "Which ride do you want to try first?"],
        ["M", "The big roller coaster. I've watched videos of it all week."],
        ["W", "You really can't wait, can you?"],
        ["M", "I've already put my ticket in my bag."],
      ],
      choices: ["excited", "sad", "angry", "nervous", "bored"],
      answer: 1,
      clue: "I've already put my ticket in my bag.",
      explanation:
        "처음 가는 놀이공원을 기다리며 표까지 가방에 넣어 두었으므로 남자는 들떠 있다. 따라서 답은 ①이다.",
      translation: [
        "W: 성민아, 아침 내내 웃고 있네. 무슨 일이야?",
        "M: 이번 토요일에 가족이랑 놀이공원에 가.",
        "W: 거기 가 본 적 있어?",
        "M: 아니, 한 번도. 이번이 처음이야.",
        "W: 어떤 놀이기구를 제일 먼저 타고 싶어?",
        "M: 큰 롤러코스터. 일주일 내내 영상만 봤어.",
        "W: 정말 못 기다리겠구나.",
        "M: 표는 벌써 가방에 넣어 놨어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "How much is this notebook?"],
        ["M", "It's two dollars."],
        ["W", "Where is the nearest subway station?"],
        ["M", "Go straight for two blocks."],
        ["W", "Could you get that book for me?"],
        ["M", "Sure. Here you are."],
        ["W", "What time does the class start?"],
        ["M", "At nine thirty."],
        ["W", "May I borrow your pen?"],
        ["M", "Of course. Take this one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Could you get that book for me?",
      explanation:
        "그림은 도서관에서 키가 닿지 않는 학생을 위해 다른 학생이 높은 칸의 책을 꺼내 주는 장면이므로 ③이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "Inside a library. A short student is standing on tiptoe in front of a tall bookshelf and looking up at a book on the top shelf, unable to reach it. A taller student beside them is reaching up with one hand and taking that book down from the top shelf. Both are drawn clearly. Rows of books fill the shelves and a table with chairs stands behind them.",
      },
      translation: [
        "① W: 이 공책 얼마예요? / M: 2달러입니다.",
        "② W: 가장 가까운 지하철역이 어디예요? / M: 두 블록 곧장 가세요.",
        "③ W: 저 책 좀 꺼내 줄래? / M: 그럼. 여기 있어.",
        "④ W: 수업이 몇 시에 시작해? / M: 9시 30분에.",
        "⑤ W: 펜 좀 빌려줄래? / M: 그럼. 이거 써.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayeon, do you still ride your bike to school?"],
        ["W", "Not these days. I take the bus now."],
        ["M", "So your bike is at home all week?"],
        ["W", "Yes, it just sits in the garage. Why?"],
        ["M", "My cousin is visiting on Sunday and we want to ride by the river."],
        ["W", "And you only have one bike?"],
        ["M", "Right. Could I borrow yours for the day?"],
        ["W", "Sure. Come and get it on Saturday evening."],
        ["M", "Thank you. I'll bring it back on Sunday night."],
      ],
      choices: ["필통 빌려주기", "사진 찍어 주기", "자리 맡아 주기", "자전거 빌려주기", "숙제 도와주기"],
      answer: 4,
      clue: "Right. Could I borrow yours for the day?",
      explanation:
        "남자는 일요일에 사촌과 강가에서 타려고 여자에게 자전거를 빌려 달라고 부탁한다. 따라서 답은 ④이다.",
      translation: [
        "M: 하연아, 아직 자전거 타고 학교 와?",
        "W: 요즘은 안 타. 버스 타고 와.",
        "M: 그럼 자전거는 일주일 내내 집에 있는 거야?",
        "W: 응, 창고에 그냥 있어. 왜?",
        "M: 일요일에 사촌이 오는데 강가에서 자전거를 타고 싶어서.",
        "W: 그런데 자전거가 하나뿐이야?",
        "M: 응. 그날 하루만 네 것 좀 빌릴 수 있을까?",
        "W: 그래. 토요일 저녁에 가지러 와.",
        "M: 고마워. 일요일 밤에 돌려줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, School Music Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, everyone. Let me tell you about School Music Day."],
        ["M", "It will be held on the second Friday of next month."],
        ["M", "The stage will be in the gym, so we can use it even if it rains."],
        ["M", "Each team can play for five minutes."],
        ["M", "If you want to join, write your team's name on the list by the music room."],
        ["M", "Come and show us what you have been practicing."],
      ],
      choices: ["참가비", "날짜", "장소", "공연 시간", "신청 방법"],
      answer: 1,
      clue: "If you want to join, write your team's name on the list by the music room.",
      explanation:
        "날짜(다음 달 둘째 금요일), 장소(체육관), 공연 시간(팀당 5분), 신청 방법(음악실 옆 명단)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 여러분, 안녕하세요. School Music Day를 안내합니다.",
        "M: 다음 달 둘째 금요일에 열립니다.",
        "M: 무대는 체육관에 설치되니 비가 와도 할 수 있습니다.",
        "M: 팀마다 5분씩 연주할 수 있습니다.",
        "M: 참가하고 싶으면 음악실 옆 명단에 팀 이름을 적으세요.",
        "M: 오셔서 그동안 연습한 것을 보여 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You can see this at almost every street corner."],
        ["W", "It stands on a tall pole so that everyone can see it."],
        ["W", "It has three round lights in a line."],
        ["W", "Red means stop, and green means you can go."],
        ["W", "Cars and people both have to watch it."],
      ],
      choices: ["표지판", "신호등", "가로등", "횡단보도", "버스 정류장"],
      answer: 2,
      clue: "Red means stop, and green means you can go.",
      explanation:
        "길모퉁이 높은 기둥 위에 있고 둥근 불이 셋이며 빨강은 정지, 초록은 통행을 뜻한다고 했으므로 신호등이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이것은 거의 모든 길모퉁이에서 볼 수 있습니다.",
        "W: 모두가 볼 수 있도록 높은 기둥 위에 있습니다.",
        "W: 둥근 불이 세 개 한 줄로 있습니다.",
        "W: 빨간색은 멈추라는 뜻이고, 초록색은 가도 된다는 뜻입니다.",
        "W: 자동차도 사람도 이것을 봐야 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "What's your favorite subject?"],
        ["W", "I like history the most."],
        ["M", "Can you help me with this box?"],
        ["W", "Sure, it looks heavy."],
        ["M", "How was the movie last night?"],
        ["W", "It was really funny."],
        ["M", "When does the library close?"],
        ["W", "At six on weekdays."],
        ["M", "Whose jacket is this?"],
        ["W", "I walked there this morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Whose jacket is this?",
      explanation:
        "누구의 재킷인지 묻는 말에 아침에 걸어갔다는 대답은 어울리지 않는다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 제일 좋아하는 과목이 뭐야? / W: 역사가 제일 좋아.",
        "② M: 이 상자 좀 도와줄래? / W: 그럼, 무거워 보인다.",
        "③ M: 어젯밤 영화 어땠어? / W: 정말 웃겼어.",
        "④ M: 도서관은 언제 닫아? / W: 평일에는 6시에.",
        "⑤ M: 이건 누구 재킷이야? / W: 나는 오늘 아침에 거기까지 걸어갔어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuri, Grandma will be here in twenty minutes."],
        ["W", "Is everything ready? What can I do?"],
        ["M", "I already wiped the table and boiled the water."],
        ["W", "Should I buy some bread, then?"],
        ["M", "No, Dad bought some on his way home."],
        ["W", "Then what is left?"],
        ["M", "The vegetables for the salad are still in the basket."],
        ["W", "I'll wash them right now."],
        ["M", "Thanks. I'll carry the plates to the table."],
      ],
      choices: ["접시 나르기", "식탁 닦기", "채소 씻기", "빵 사 오기", "물 끓이기"],
      answer: 3,
      clue: "I'll wash them right now.",
      explanation:
        "식탁 닦기, 물 끓이기, 빵 사 오기는 이미 끝났고 여자는 샐러드에 쓸 채소를 씻겠다고 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 유리야, 할머니가 20분 뒤에 오셔.",
        "W: 다 준비됐어? 내가 뭘 할까?",
        "M: 식탁은 벌써 닦았고 물도 끓였어.",
        "W: 그럼 빵을 사 올까?",
        "M: 아니, 아빠가 오시는 길에 사 오셨어.",
        "W: 그럼 뭐가 남았어?",
        "M: 샐러드에 넣을 채소가 아직 바구니에 있어.",
        "W: 내가 지금 씻을게.",
        "M: 고마워. 나는 접시를 식탁으로 나를게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 물병을 고르시오.",
      lines: [
        ["M", "Sora, are these the water bottles you were looking at?"],
        ["W", "Yes, these five. I can't decide."],
        ["M", "How much water do you need for one day?"],
        ["W", "At least seven hundred milliliters. Five hundred is too small."],
        ["M", "All right, that takes out two of them."],
        ["W", "And I can't spend more than twelve dollars."],
        ["M", "Then one more is gone. Two are left."],
        ["W", "Both have a straw, so that doesn't help."],
        ["M", "One of them has a handle. You said your bag is always full."],
        ["W", "Right, I want to carry it in my hand. I'll take that one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Right, I want to carry it in my hand. I'll take that one.",
      explanation:
        "500밀리리터인 ①·③을 빼고, 14달러인 ⑤를 뺀다. 남은 ②와 ④ 중 손잡이가 있는 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "500ml / $8 / 빨대 없음 / 손잡이 있음" },
          { no: 2, label: "②", value: "700ml / $12 / 빨대 있음 / 손잡이 없음" },
          { no: 3, label: "③", value: "500ml / $10 / 빨대 있음 / 손잡이 있음" },
          { no: 4, label: "④", value: "700ml / $10 / 빨대 있음 / 손잡이 있음" },
          { no: 5, label: "⑤", value: "1,000ml / $14 / 빨대 있음 / 손잡이 있음" },
        ],
      },
      translation: [
        "M: 소라야, 네가 보던 물병이 이거야?",
        "W: 응, 이 다섯 개. 못 고르겠어.",
        "M: 하루에 물이 얼마나 필요한데?",
        "W: 적어도 700밀리리터. 500은 너무 작아.",
        "M: 그럼 두 개가 빠지네.",
        "W: 그리고 12달러가 넘으면 안 돼.",
        "M: 그럼 하나 더 빠진다. 둘 남았어.",
        "W: 둘 다 빨대가 있어서 그걸로는 못 고르겠어.",
        "M: 하나는 손잡이가 있어. 네 가방은 늘 꽉 찬다고 했잖아.",
        "W: 맞아, 손에 들고 다니고 싶어. 그걸로 할래.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 도서관에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Dongha, when should we go to the library together?"],
        ["M", "How about this week? The third, fourth, or fifth?"],
        ["W", "What do we need to finish there, again?"],
        ["M", "The history report. We have to find three old photos."],
        ["W", "Then we need at least two hours. I have a piano lesson on the fourth."],
        ["M", "All right, so it's the third or the fifth."],
        ["W", "Wait. Isn't the fifth the day of the school photo?"],
        ["M", "You're right, I forgot. We'll be busy all afternoon that day."],
        ["W", "So only the third is left."],
        ["M", "Then let's go on the third, right after school."],
      ],
      choices: ["3일", "4일", "5일", "10일", "11일"],
      answer: 1,
      clue: "So only the third is left.",
      explanation:
        "4일은 피아노 수업, 5일은 학교 사진 찍는 날이어서 3일만 남는다. 따라서 답은 ①이다.",
      translation: [
        "W: 동하야, 도서관에 언제 같이 갈까?",
        "M: 이번 주 어때? 3일, 4일, 5일 중에.",
        "W: 거기서 뭘 끝내야 한다고 했지?",
        "M: 역사 보고서. 옛날 사진 세 장을 찾아야 해.",
        "W: 그럼 적어도 두 시간은 있어야겠다. 나 4일에 피아노 수업이 있어.",
        "M: 알겠어, 그럼 3일이나 5일이네.",
        "W: 잠깐. 5일은 학교 사진 찍는 날 아니야?",
        "M: 맞다, 잊었네. 그날은 오후 내내 바쁘겠다.",
        "W: 그럼 3일만 남네.",
        "M: 그럼 3일에 가자, 학교 끝나고 바로.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, did you go swimming last weekend?"],
        ["W", "No, I went to the science museum with my brother."],
        ["M", "The big one near the river? Was it fun?"],
        ["W", "It was great. We saw a show about the stars in a dark round room."],
        ["M", "That sounds nice. How did you get there?"],
        ["W", "We took the bus. It only takes twenty minutes from my house."],
        ["M", "And how long did you stay?"],
        ["W", "About four hours, and we still didn't see everything."],
        ["M", "Then you should go again."],
        ["W", "We will. My brother wants to see the robot room next time."],
      ],
      choices: ["수영하기", "영화 보기", "자전거 타기", "쿠키 만들기", "박물관 가기"],
      answer: 5,
      clue: "No, I went to the science museum with my brother.",
      explanation:
        "여자는 지난 주말에 동생과 과학 박물관에 갔다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 나리야, 지난 주말에 수영하러 갔어?",
        "W: 아니, 동생이랑 과학 박물관에 갔어.",
        "M: 강 근처에 있는 큰 데? 재미있었어?",
        "W: 아주 좋았어. 깜깜한 둥근 방에서 별에 관한 공연도 봤어.",
        "M: 좋았겠다. 거기까지 어떻게 갔어?",
        "W: 버스 탔어. 우리 집에서 20분밖에 안 걸려.",
        "M: 그럼 얼마나 있었어?",
        "W: 네 시간쯤, 그런데도 다 못 봤어.",
        "M: 그럼 또 가야겠다.",
        "W: 갈 거야. 동생이 다음에는 로봇관을 보고 싶대.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good afternoon, students. This is the school office."],
        ["W", "We have many lost things in the box by the front door."],
        ["W", "There are nine umbrellas, three jackets, and two pencil cases."],
        ["W", "Please come and look in the box before Friday."],
        ["W", "After Friday we will give everything to the recycling center."],
        ["W", "Come during lunch time and check the box."],
      ],
      choices: [
        "도서관 이용 시간을 알리려고",
        "잃어버린 물건을 찾아가라고 하려고",
        "운동장 공사를 알리려고",
        "급식 시간을 안내하려고",
        "우산을 가져오라고 하려고",
      ],
      answer: 2,
      clue: "Please come and look in the box before Friday.",
      explanation:
        "정문 옆 상자에 있는 분실물을 금요일 전에 찾아가라고 알리는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 정문 옆 상자에 잃어버린 물건이 많이 있습니다.",
        "W: 우산 아홉 개, 재킷 세 벌, 필통 두 개가 있습니다.",
        "W: 금요일 전에 와서 상자를 살펴보세요.",
        "W: 금요일이 지나면 모두 재활용 센터로 보냅니다.",
        "W: 점심시간에 와서 상자를 확인해 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Did you find what you need?"],
        ["M", "Yes. I'd like these two notebooks and one set of colored pencils."],
        ["W", "The notebooks are three dollars each."],
        ["M", "And the colored pencils?"],
        ["W", "That set is twelve dollars."],
        ["M", "So six dollars and twelve dollars."],
        ["W", "That's right. Do you have our store card?"],
        ["M", "Yes, here it is."],
        ["W", "Then I can take two dollars off."],
        ["M", "Great. I'll pay in cash."],
      ],
      choices: ["$12", "$14", "$15", "$16", "$18"],
      answer: 4,
      clue: "Then I can take two dollars off.",
      explanation:
        "공책 3달러짜리 두 권은 6달러, 색연필 세트 12달러를 더하면 18달러이다. 카드 할인 2달러를 빼면 16달러이므로 답은 ④이다.",
      translation: [
        "W: 안녕하세요. 필요한 건 찾으셨어요?",
        "M: 네. 이 공책 두 권이랑 색연필 세트 하나 주세요.",
        "W: 공책은 한 권에 3달러입니다.",
        "M: 색연필은요?",
        "W: 그 세트는 12달러입니다.",
        "M: 그럼 6달러랑 12달러네요.",
        "W: 맞습니다. 저희 매장 카드 있으세요?",
        "M: 네, 여기 있습니다.",
        "W: 그럼 2달러 빼 드릴게요.",
        "M: 좋네요. 현금으로 낼게요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Jaemin, you brought your soccer ball again."],
        ["M", "Yes, but I can't play today. The field is wet."],
        ["W", "Did it rain last night?"],
        ["M", "All night long. The whole field is muddy now."],
        ["W", "That's too bad. Do you practice every day?"],
        ["M", "Almost every day. Our game is in two weeks."],
        ["W", "Two weeks isn't much time. Who are you playing against?"],
        ["M", "The team from the middle school next to the park."],
        ["W", "They're strong. Then you really can't miss a day."],
        ["M", "That's why I keep bringing the ball."],
        ["W", "The gym is empty after school on Wednesdays."],
      ],
      choices: [
        "I forgot my soccer ball at home.",
        "The game was last Saturday.",
        "Then we can practice there today.",
        "I don't like soccer very much.",
        "It rained all day yesterday.",
      ],
      answer: 3,
      clue: "The gym is empty after school on Wednesdays.",
      explanation:
        "수요일 방과 후에는 체육관이 빈다는 말을 들었으므로, 오늘 거기서 연습하면 되겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 재민아, 또 축구공 가져왔네.",
        "M: 응, 그런데 오늘은 못 해. 운동장이 젖었어.",
        "W: 어젯밤에 비 왔어?",
        "M: 밤새 왔어. 지금 운동장이 온통 진흙이야.",
        "W: 아쉽다. 매일 연습해?",
        "M: 거의 매일. 2주 뒤에 경기가 있어.",
        "W: 2주면 얼마 안 남았네. 누구랑 붙어?",
        "M: 공원 옆 중학교 팀이랑.",
        "W: 거기 세잖아. 그럼 하루도 빠지면 안 되겠다.",
        "M: 그래서 공을 계속 들고 다니는 거야.",
        "W: 수요일 방과 후에는 체육관이 비어 있어.",
        "M: 그럼 오늘 거기서 연습하면 되겠다.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sehee, are you still looking for your library card?"],
        ["W", "Yes. I've checked my bag three times this morning."],
        ["M", "When did you use it last?"],
        ["W", "Last Thursday, in the reading room on the second floor."],
        ["M", "Did you go anywhere else after that?"],
        ["W", "Only home. That's why I don't understand it."],
        ["M", "Did you borrow anything that day?"],
        ["W", "Yes, one book about the sea. It's still on my desk."],
        ["M", "Did you look inside that book?"],
        ["W", "No, I didn't even think of that."],
        ["M", "People often leave the card inside the book as a bookmark."],
      ],
      choices: [
        "Then I'll check my book right now.",
        "I returned the book on Monday.",
        "The library opens at nine.",
        "I don't have a library card.",
        "You should borrow that book too.",
      ],
      answer: 1,
      clue: "People often leave the card inside the book as a bookmark.",
      explanation:
        "사람들이 책 안에 책갈피처럼 끼워 둔다는 말을 들었으므로, 지금 바로 책을 확인해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 세희야, 아직 도서관 카드 찾고 있어?",
        "W: 응. 오늘 아침에만 가방을 세 번 봤어.",
        "M: 마지막으로 언제 썼어?",
        "W: 지난 목요일, 2층 열람실에서.",
        "M: 그다음에 다른 데 갔어?",
        "W: 집에만 갔어. 그래서 더 모르겠어.",
        "M: 그날 뭐 빌렸어?",
        "W: 응, 바다에 관한 책 한 권. 아직 책상에 있어.",
        "M: 그 책 안은 봤어?",
        "W: 아니, 그 생각은 아예 못 했어.",
        "M: 사람들이 책갈피처럼 책 안에 카드를 두는 경우가 많거든.",
        "W: 그럼 지금 바로 책을 확인해 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minwoo, you look tired every Monday morning."],
        ["M", "I know. I always stay up late on Sunday."],
        ["W", "What do you do so late?"],
        ["M", "I do my weekend homework. I leave it until Sunday night."],
        ["W", "All of it on one night?"],
        ["M", "Yes, and it takes about four hours."],
        ["W", "Why don't you do half of it on Saturday?"],
        ["M", "I always want to rest on Saturday."],
        ["W", "Even one hour on Saturday morning would help."],
      ],
      choices: [
        "I finished my homework last night.",
        "Saturday is my birthday this week.",
        "I sleep until noon every Sunday.",
        "My homework is due on Friday.",
        "All right, I'll try that this weekend.",
      ],
      answer: 5,
      clue: "Even one hour on Saturday morning would help.",
      explanation:
        "토요일 아침에 한 시간만 해도 도움이 된다는 말을 들었으므로, 이번 주말에 해 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 민우야, 월요일 아침마다 피곤해 보여.",
        "M: 맞아. 일요일에 늘 늦게까지 안 자.",
        "W: 그렇게 늦게까지 뭐 해?",
        "M: 주말 숙제를 해. 일요일 밤까지 미뤄 둬.",
        "W: 하룻밤에 다?",
        "M: 응, 네 시간쯤 걸려.",
        "W: 토요일에 절반만 해 보면 어때?",
        "M: 토요일에는 늘 쉬고 싶어서.",
        "W: 토요일 아침에 한 시간만 해도 도움이 될 거야.",
        "M: 알겠어, 이번 주말에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yena가 Hajun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Yena : ________________",
      lines: [
        ["W", "Yena and Hajun are in the same art class."],
        ["W", "They are making a poster about saving water together."],
        ["W", "Hajun draws very well, and his picture is almost finished."],
        ["W", "But he has written the title in very small letters at the bottom."],
        ["W", "The poster will be put on the wall of the hallway."],
        ["W", "People walking by will not be able to read such small letters."],
        ["W", "Yena does not want to say that his drawing is bad."],
        ["W", "She wants to ask him to write the title bigger."],
        ["W", "In this situation, what would Yena most likely say to Hajun?"],
      ],
      choices: [
        "Let's draw a different picture instead.",
        "Could you make the title much bigger?",
        "I'll put the poster on the wall myself.",
        "We should finish the poster tomorrow.",
        "Your drawing takes up too much space.",
      ],
      answer: 2,
      clue: "She wants to ask him to write the title bigger.",
      explanation:
        "예나는 하준이의 그림을 깎아내리지 않으면서, 복도에서도 읽히도록 제목을 크게 써 달라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 예나와 하준은 같은 미술 시간을 듣습니다.",
        "W: 두 사람은 물 아껴 쓰기 포스터를 함께 만들고 있습니다.",
        "W: 하준은 그림을 아주 잘 그리고, 그림은 거의 다 되었습니다.",
        "W: 그런데 제목을 아래쪽에 아주 작은 글씨로 썼습니다.",
        "W: 이 포스터는 복도 벽에 붙을 것입니다.",
        "W: 지나가는 사람들은 그렇게 작은 글씨를 읽을 수 없습니다.",
        "W: 예나는 하준의 그림이 좋지 않다고 말하고 싶지는 않습니다.",
        "W: 다만 제목을 더 크게 써 달라고 부탁하고 싶습니다.",
        "W: 이런 상황에서 예나가 하준에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
