/** 중1 듣기 47회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 47회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 필통을 고르시오.",
      lines: [
        ["W", "May I help you find something?"],
        ["M", "I need a new pencil case for school."],
        ["W", "Do you prefer a flat one or a round one?"],
        ["M", "Flat, so it fits inside my textbook pocket."],
        ["W", "This flat one closes with a button."],
        ["M", "A zipper is safer. Buttons come off."],
        ["W", "Would you like one with a small handle?"],
        ["M", "No handle, please. It catches on everything."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Flat, so it fits inside my textbook pocket. / A zipper is safer. Buttons come off.",
      explanation:
        "남자는 납작하고 지퍼로 닫히며 손잡이가 없는 필통을 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five pencil cases side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a FLAT rectangular case closed with a round BUTTON. " +
          "② a FLAT rectangular case closed with a ZIPPER, with no handle at all. " +
          "③ a FLAT rectangular case with a ZIPPER and a small loop HANDLE on the side. " +
          "④ a fat ROUND cylinder case with a ZIPPER. " +
          "⑤ a fat ROUND cylinder case with a BUTTON and a loop HANDLE.",
      },
      translation: [
        "W: 찾으시는 것 도와드릴까요?",
        "M: 학교에서 쓸 새 필통이 필요해요.",
        "W: 납작한 게 좋으세요, 둥근 게 좋으세요?",
        "M: 납작한 거요. 교과서 주머니에 들어가게요.",
        "W: 이 납작한 건 단추로 잠가요.",
        "M: 지퍼가 더 안전해요. 단추는 떨어져요.",
        "W: 작은 손잡이가 달린 것은 어떠세요?",
        "M: 손잡이는 없는 걸로요. 자꾸 걸려요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 요리 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jiho, did you sign up for the cooking contest?"],
        ["M", "I did. Do you know when it starts?"],
        ["W", "Next Wednesday, at two in the afternoon."],
        ["M", "How long do we have to cook?"],
        ["W", "One hour, and then the tasting begins."],
        ["M", "Do they give us the ingredients?"],
        ["W", "The school provides everything except spices."],
        ["M", "Where does the contest take place?"],
        ["W", "In the home economics room on the second floor."],
      ],
      choices: [
        "대회가 시작하는 시각",
        "요리하는 시간",
        "재료를 주는지 여부",
        "대회가 열리는 곳",
        "우승자에게 주는 상",
      ],
      answer: 5,
      clue: "Next Wednesday, at two in the afternoon.",
      explanation:
        "시작 시각, 요리 시간, 재료, 장소는 말했지만 상은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 지호야, 요리 대회 신청했어?",
        "M: 했어. 언제 시작하는지 알아?",
        "W: 다음 주 수요일 오후 두 시에.",
        "M: 요리 시간은 얼마나 돼?",
        "W: 한 시간. 그다음에 시식이 시작돼.",
        "M: 재료는 주나?",
        "W: 양념 빼고는 학교에서 다 줘.",
        "M: 대회는 어디서 해?",
        "W: 2층 가정실에서.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Kiyoung. It's Dain. Do you have a minute?"],
        ["M", "Sure. What's up?"],
        ["W", "You helped me with the poster last Saturday."],
        ["M", "It was only two hours of work."],
        ["W", "It won second place in the contest."],
        ["M", "That's wonderful news for you."],
        ["W", "The teacher said the colors were the best part."],
        ["M", "Those were all your idea, though."],
        ["W", "I really wanted to say thank you properly."],
      ],
      choices: [
        "고마움을 전하려고",
        "도움을 요청하려고",
        "약속을 미루려고",
        "숙제를 물어보려고",
        "물건을 빌리려고",
      ],
      answer: 1,
      clue: "I really wanted to say thank you properly.",
      explanation:
        "여자는 도와준 것에 제대로 고마움을 전하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 기영아. 다인이야. 잠깐 시간 돼?",
        "M: 응. 무슨 일이야?",
        "W: 지난 토요일에 포스터 도와줬잖아.",
        "M: 두 시간밖에 안 걸렸는데.",
        "W: 그게 대회에서 2등 했어.",
        "M: 너한테 정말 좋은 소식이다.",
        "W: 선생님이 색이 제일 좋다고 하셨어.",
        "M: 그건 다 네 생각이었잖아.",
        "W: 제대로 고맙다고 말하고 싶었어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Nari, what time does the volunteer work start?"],
        ["W", "The center wants us there by two o'clock."],
        ["M", "How long does it take from the subway station?"],
        ["W", "About fifteen minutes on foot."],
        ["M", "Then we should meet at the station at one forty-five."],
        ["W", "We also need to sign in at the front desk."],
        ["M", "That takes a few more minutes, doesn't it?"],
        ["W", "Let's make it one thirty to be safe."],
        ["M", "One thirty at the station, then."],
      ],
      choices: ["1:30 p.m.", "1:45 p.m.", "2:00 p.m.", "2:15 p.m.", "1:15 p.m."],
      answer: 1,
      clue: "Let's make it one thirty to be safe.",
      explanation:
        "걸어가는 시간과 접수 시간을 생각해 1시 30분에 만나기로 했다. 따라서 답은 ①이다.",
      translation: [
        "M: 나리야, 봉사 활동 몇 시에 시작해?",
        "W: 센터에서 두 시까지 오라고 했어.",
        "M: 지하철역에서 얼마나 걸려?",
        "W: 걸어서 15분쯤.",
        "M: 그럼 1시 45분에 역에서 만나야겠다.",
        "W: 접수대에서 이름도 적어야 해.",
        "M: 그것도 몇 분 더 걸리지?",
        "W: 안전하게 1시 30분으로 하자.",
        "M: 그럼 1시 30분에 역에서.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, did you find someone to fix your bike?"],
        ["M", "My neighbor repaired it for free last night."],
        ["W", "The one who works at the bike shop?"],
        ["M", "Yes, and he stayed out until nine for it."],
        ["W", "Did he ask you for anything at all?"],
        ["M", "He refused even the money my mother offered."],
        ["W", "That was really kind of him."],
        ["M", "I want to do something for him this weekend."],
      ],
      choices: ["grateful", "angry", "bored", "nervous", "jealous"],
      answer: 1,
      clue: "I want to do something for him this weekend.",
      explanation:
        "이웃이 무료로 자전거를 고쳐 주어 보답하고 싶다고 했으므로 고마워하는 심정이다. 따라서 답은 ①이다.",
      translation: [
        "W: 상우야, 자전거 고쳐 줄 사람 찾았어?",
        "M: 어젯밤에 이웃 아저씨가 무료로 고쳐 주셨어.",
        "W: 자전거 가게에서 일하시는 그분?",
        "M: 응, 그것 때문에 아홉 시까지 계셨어.",
        "W: 뭐 달라고 하신 것도 없어?",
        "M: 엄마가 드리려던 돈도 안 받으셨어.",
        "W: 정말 고마운 분이시네.",
        "M: 이번 주말에 뭐라도 해 드리고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I try these on?"],
        ["M", "The fitting room is over there."],
        ["ANN", "Number two."],
        ["W", "Do you have a bigger size?"],
        ["M", "I'll check the back for you."],
        ["ANN", "Number three."],
        ["W", "This shirt has a hole in it."],
        ["M", "I'm sorry. I'll change it for you."],
        ["ANN", "Number four."],
        ["W", "How much is this jacket?"],
        ["M", "Forty dollars, including tax."],
        ["ANN", "Number five."],
        ["W", "Do you close at nine?"],
        ["M", "Yes, every day of the week."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "This shirt has a hole in it.",
      explanation:
        "그림은 옷 가게에서 여자가 구멍 난 셔츠를 가리키고 점원이 사과하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a clothing shop, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman holds up a shirt and points with her finger at a clear round hole near its sleeve, frowning. " +
          "A shop clerk behind the counter bows slightly with an apologetic face and reaches for a folded shirt. " +
          "Racks of hanging clothes are drawn simply behind them.",
      },
      translation: [
        "① W: 이거 입어 봐도 되나요? / M: 탈의실은 저쪽입니다.",
        "② W: 더 큰 치수 있나요? / M: 창고에서 확인해 볼게요.",
        "③ W: 이 셔츠에 구멍이 났어요. / M: 죄송합니다. 바꿔 드릴게요.",
        "④ W: 이 재킷 얼마예요? / M: 세금 포함 40달러입니다.",
        "⑤ W: 아홉 시에 닫나요? / M: 네, 매일 그렇습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyeon, you take the number eight bus, right?"],
        ["W", "Every day, and it passes the library."],
        ["M", "That's exactly what I wanted to ask about."],
        ["W", "Do you need to return something?"],
        ["M", "Two books, but I have practice until six."],
        ["W", "And the library closes at five thirty."],
        ["M", "That's the problem."],
        ["W", "Are they ready to go?"],
        ["M", "Could you return these two books for me?"],
        ["W", "Sure, the return box is by my stop."],
      ],
      choices: [
        "함께 버스를 타 주기",
        "책을 반납해 주기",
        "도서관에 전화하기",
        "연습을 도와주기",
        "책을 빌려주기",
      ],
      answer: 2,
      clue: "Could you return these two books for me?",
      explanation:
        "남자는 책 두 권을 대신 반납해 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 채연아, 너 8번 버스 타지?",
        "W: 매일 타. 도서관을 지나가.",
        "M: 그게 딱 물어보고 싶었던 거야.",
        "W: 반납할 게 있어?",
        "M: 책 두 권인데 여섯 시까지 연습이 있어.",
        "W: 도서관은 5시 30분에 닫고.",
        "M: 그게 문제야.",
        "W: 다 준비된 거야?",
        "M: 이 책 두 권 대신 반납해 줄래?",
        "W: 그럼, 반납함이 우리 정류장 옆에 있어.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학생 자치 예산 설명회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The student council will hold a budget meeting. " +
            "It takes place next Wednesday during the lunch break. " +
            "We will gather in the first floor meeting room. " +
            "We will explain how this term's money was actually spent. " +
            "Class leaders from every grade should attend. " +
            "The papers will be handed out at the door.",
        ],
      ],
      choices: [
        "설명회가 열리는 날",
        "설명회가 열리는 장소",
        "설명회에서 다루는 내용",
        "참석해야 하는 사람",
        "의견을 내는 방법",
      ],
      answer: 5,
      clue: "It takes place next Wednesday during the lunch break.",
      explanation:
        "날짜, 장소, 내용, 참석 대상은 말했지만 의견을 내는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학생회에서 예산 설명회를 엽니다. 다음 주 수요일 점심시간에 진행합니다. 1층 회의실에 모입니다. 이번 학기 돈이 실제로 어떻게 쓰였는지 설명해 드립니다. 각 학년 반장들은 참석해 주시기 바랍니다. 자료는 문 앞에서 나눠 드립니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a small strip of thin paper you get in a shop. " +
            "It lists what you bought and how much each item cost. " +
            "The total amount is printed at the bottom of it. " +
            "Keep it if you may want to return the item later. " +
            "The ink on it fades if you leave it in the sun.",
        ],
      ],
      choices: ["지갑", "통장", "영수증", "명함", "우표"],
      answer: 3,
      clue: "It lists what you bought and how much each item cost.",
      explanation:
        "가게에서 받는 종이로 산 물건과 값이 적혀 있고 환불할 때 필요한 것은 영수증이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 가게에서 받는 얇고 긴 종이입니다. 무엇을 샀는지와 각 물건의 값이 적혀 있습니다. 맨 아래에는 전체 금액이 찍혀 있습니다. 나중에 물건을 반품할 수도 있다면 보관하세요. 햇빛에 두면 글씨가 흐려집니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How often do you go swimming?"],
        ["M", "Twice a week, usually."],
        ["ANN", "Number two."],
        ["W", "Could you turn down the music?"],
        ["M", "Sure, sorry about that."],
        ["ANN", "Number three."],
        ["W", "What's the weather like outside?"],
        ["M", "Cold and windy today."],
        ["ANN", "Number four."],
        ["W", "Why were you late this morning?"],
        ["M", "My favorite color is green."],
        ["ANN", "Number five."],
        ["W", "Have you ever been to Jeju?"],
        ["M", "Twice, both times in summer."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why were you late this morning?",
      explanation:
        "늦은 이유를 묻는 말에 좋아하는 색을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 수영 얼마나 자주 가? / M: 보통 일주일에 두 번.",
        "② W: 음악 좀 줄여 줄래? / M: 그래, 미안해.",
        "③ W: 밖에 날씨 어때? / M: 오늘은 춥고 바람 불어.",
        "④ W: 오늘 아침에 왜 늦었어? / M: 내가 좋아하는 색은 초록색이야.",
        "⑤ W: 제주도에 가 본 적 있어? / M: 두 번. 둘 다 여름에.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suyeon, the art contest entries go out today."],
        ["W", "I finished my painting last night."],
        ["M", "Did you write your name on the back?"],
        ["W", "I don't think I did, actually."],
        ["M", "They throw away works without a name."],
        ["W", "Where is my painting right now?"],
        ["M", "Still on the shelf in the art room."],
        ["W", "I'll go and write my name on it."],
      ],
      choices: [
        "그림을 다시 그리기",
        "미술실에 가서 이름을 쓰기",
        "선생님께 여쭤보기",
        "집에 가기",
        "친구를 도와주기",
      ],
      answer: 2,
      clue: "I'll go and write my name on it.",
      explanation:
        "여자는 미술실에 가서 그림에 이름을 쓰겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 수연아, 오늘 미술 대회 작품 나가.",
        "W: 어젯밤에 그림 다 그렸어.",
        "M: 뒤에 이름 썼어?",
        "W: 안 쓴 것 같아, 사실.",
        "M: 이름 없는 작품은 버려.",
        "W: 내 그림 지금 어디 있지?",
        "M: 아직 미술실 선반에 있어.",
        "W: 가서 이름 써 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 여름 특강을 고르시오.",
      lines: [
        ["W", "Hyunwoo, which summer course are you going to take?"],
        ["M", "Let's look at these five on the printout."],
        ["W", "How many weeks can you attend?"],
        ["M", "Four weeks at the most. We travel in August."],
        ["W", "All right. Morning or afternoon?"],
        ["M", "Morning, because I work at the library later."],
        ["W", "And what about the fee?"],
        ["M", "Under a hundred and fifty thousand won."],
        ["W", "Then only one course here fits everything."],
        ["M", "Good. I'll register before it closes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Four weeks at the most. We travel in August.",
      explanation:
        "4주 이하, 오전반, 15만 원 이하인 강좌를 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Weeks: 6 / Time: Morning / Fee: 140,000 won" },
          { no: 2, label: "②", value: "Weeks: 4 / Time: Morning / Fee: 135,000 won" },
          { no: 3, label: "③", value: "Weeks: 4 / Time: Afternoon / Fee: 120,000 won" },
          { no: 4, label: "④", value: "Weeks: 3 / Time: Morning / Fee: 180,000 won" },
          { no: 5, label: "⑤", value: "Weeks: 8 / Time: Afternoon / Fee: 100,000 won" },
        ],
      },
      translation: [
        "W: 현우야, 어떤 여름 특강 들을 거야?",
        "M: 유인물에 있는 다섯 개 보자.",
        "W: 몇 주나 다닐 수 있어?",
        "M: 최대 4주. 8월에 여행 가.",
        "W: 알겠어. 오전반이야, 오후반이야?",
        "M: 오전. 오후에는 도서관에서 일해.",
        "W: 수강료는?",
        "M: 15만 원 이하로.",
        "W: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "M: 좋아. 마감 전에 등록할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["M", "Chaewon, when can we visit the senior center?"],
        ["W", "They take students on three days this month."],
        ["M", "Which days did they tell you?"],
        ["W", "The ninth, the sixteenth and the twenty-third."],
        ["M", "The ninth is our class photo day."],
        ["W", "And I have a piano exam on the sixteenth."],
        ["M", "Then the twenty-third is what's left."],
        ["W", "It's a Saturday, so we have the whole morning."],
        ["M", "I'll call them and say the twenty-third."],
      ],
      choices: ["the 9th", "the 16th", "the 23rd", "the 30th", "the 2nd"],
      answer: 3,
      clue: "Then the twenty-third is what's left.",
      explanation:
        "9일은 사진 촬영, 16일은 피아노 시험이어서 23일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 채원아, 노인정에 언제 갈 수 있어?",
        "W: 이번 달에 사흘 학생을 받는대.",
        "M: 어떤 날이라고 했어?",
        "W: 9일, 16일, 23일.",
        "M: 9일은 우리 반 사진 찍는 날이야.",
        "W: 그리고 16일에는 피아노 시험이 있어.",
        "M: 그럼 23일이 남네.",
        "W: 토요일이라 오전이 통째로 비어.",
        "M: 전화해서 23일이라고 할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyun, you didn't come to the study room yesterday."],
        ["W", "I was teaching my little brother how to swim."],
        ["M", "Where did you two go?"],
        ["W", "The indoor pool near our apartment."],
        ["M", "How old is your brother now?"],
        ["W", "He turned eight last month."],
        ["M", "Was he afraid of the water at first?"],
        ["W", "He held my arm for the whole first hour."],
        ["M", "Did he swim by himself in the end?"],
        ["W", "Three meters, and he was very proud."],
      ],
      choices: [
        "동생에게 수영을 가르치기",
        "독서실에서 공부하기",
        "병원에 가기",
        "친구와 쇼핑하기",
        "집에서 쉬기",
      ],
      answer: 1,
      clue: "I was teaching my little brother how to swim.",
      explanation:
        "여자는 어제 동생에게 수영을 가르쳤다. 따라서 답은 ①이다.",
      translation: [
        "M: 서윤아, 어제 독서실에 안 왔더라.",
        "W: 동생한테 수영 가르치고 있었어.",
        "M: 둘이 어디 갔는데?",
        "W: 우리 아파트 근처 실내 수영장.",
        "M: 동생이 몇 살이야?",
        "W: 지난달에 여덟 살 됐어.",
        "M: 처음엔 물을 무서워했어?",
        "W: 첫 한 시간은 내 팔을 붙잡고 있었어.",
        "M: 결국 혼자 헤엄쳤어?",
        "W: 3미터. 아주 뿌듯해했어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school office speaking. " +
            "The water will be shut off tomorrow for pipe repairs. " +
            "It stops from nine in the morning until one. " +
            "Restrooms on the first floor will stay open with tanks. " +
            "Please bring your own water bottle to school tomorrow. " +
            "The water comes back on in the afternoon.",
        ],
      ],
      choices: [
        "행사를 안내하려고",
        "단수를 알리려고",
        "분실물을 찾으려고",
        "청소를 부탁하려고",
        "시험을 안내하려고",
      ],
      answer: 2,
      clue: "The water will be shut off tomorrow for pipe repairs.",
      explanation:
        "배관 공사로 물이 끊긴다고 알리는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 행정실입니다. 배관 공사 때문에 내일 물이 끊깁니다. 아침 아홉 시부터 한 시까지 멈춥니다. 1층 화장실은 물통을 두어 계속 쓸 수 있습니다. 내일은 물병을 꼭 챙겨 오세요. 물은 오후에 다시 나옵니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you here for the cooking class?"],
        ["W", "Yes, I'd like to sign up for two people."],
        ["M", "One class is fifteen dollars per person."],
        ["W", "Does that include the ingredients?"],
        ["M", "It does, but the apron costs three dollars extra."],
        ["W", "We brought our own aprons from home."],
        ["M", "Then you only pay the class fee."],
        ["W", "Is there a deposit for the tools?"],
        ["M", "No deposit at all in our classes."],
        ["W", "Good. Here is my card, then."],
      ],
      choices: ["$15", "$18", "$30", "$33", "$36"],
      answer: 3,
      clue: "One class is fifteen dollars per person.",
      explanation:
        "한 사람 15달러씩 두 사람이므로 30달러이고 앞치마 값은 내지 않는다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 요리 수업 때문에 오셨나요?",
        "W: 네, 두 사람 신청하려고요.",
        "M: 한 수업에 한 사람당 15달러입니다.",
        "W: 재료비도 포함인가요?",
        "M: 포함입니다. 다만 앞치마는 3달러 더 내셔야 합니다.",
        "W: 저희는 앞치마를 집에서 가져왔어요.",
        "M: 그러면 수업료만 내시면 됩니다.",
        "W: 도구 보증금도 있나요?",
        "M: 저희 수업에는 보증금이 없습니다.",
        "W: 좋네요. 그럼 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Woosung, you never seem to lose things."],
        ["M", "Everything in my bag has its own pocket."],
        ["W", "Even small things like your bus card?"],
        ["M", "That one always goes in the front pocket."],
        ["W", "I put mine wherever my hand happens to be."],
        ["M", "Then you have to search five places later."],
        ["W", "I lost my card twice this month already."],
        ["M", "One thing, one place. That's the whole rule."],
        ["W", "Could you help me sort my bag today?"],
      ],
      choices: [
        "I lose things every day.",
        "Sure, let's do it after class.",
        "Your bag is already tidy.",
        "You should buy a new card.",
        "I don't use a bag at all.",
      ],
      answer: 2,
      clue: "Could you help me sort my bag today?",
      explanation:
        "여자가 가방 정리를 도와 달라고 했으므로, 수업 후에 하자는 ②가 가장 자연스럽다.",
      translation: [
        "W: 우성아, 너는 물건을 잃어버리는 법이 없더라.",
        "M: 가방 속 물건마다 자리가 정해져 있어.",
        "W: 버스 카드 같은 작은 것도?",
        "M: 그건 늘 앞주머니에 넣어.",
        "W: 나는 손 가는 데 아무 데나 넣어.",
        "M: 그럼 나중에 다섯 군데를 뒤져야 하잖아.",
        "W: 이번 달에만 카드를 두 번 잃어버렸어.",
        "M: 물건 하나에 자리 하나. 규칙은 그게 다야.",
        "W: 오늘 내 가방 정리하는 것 좀 도와줄래?",
        "M: 그래, 수업 끝나고 하자.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, you've been running in the morning lately."],
        ["W", "Twenty minutes around the park before breakfast."],
        ["M", "Isn't it hard to get up that early?"],
        ["W", "The first week was terrible, honestly."],
        ["M", "What made you keep going after that?"],
        ["W", "I stopped falling asleep in afternoon classes."],
        ["M", "That alone sounds worth the effort."],
        ["W", "My legs feel lighter on the stairs too."],
        ["M", "Could I run with you tomorrow?"],
      ],
      choices: [
        "Of course, I start at six thirty.",
        "I stopped running last month.",
        "The park is closed now.",
        "You can't run in the morning.",
        "I only run on Sundays.",
      ],
      answer: 1,
      clue: "Could I run with you tomorrow?",
      explanation:
        "남자가 내일 같이 뛰어도 되는지 물었으므로, 6시 30분에 시작한다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 다인아, 요즘 아침에 달리더라.",
        "W: 아침 먹기 전에 공원 둘레를 20분씩.",
        "M: 그렇게 일찍 일어나기 힘들지 않아?",
        "W: 솔직히 첫 주는 끔찍했어.",
        "M: 그런데 왜 계속했어?",
        "W: 오후 수업에 조는 일이 없어졌어.",
        "M: 그것만으로도 할 만하겠다.",
        "W: 계단 오를 때 다리도 가벼워.",
        "M: 내일 같이 뛰어도 돼?",
        "W: 그럼, 나는 6시 30분에 시작해.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunbin, how is your part of the group project going?"],
        ["M", "I've read six articles but written nothing."],
        ["W", "Why haven't you started writing yet?"],
        ["M", "I keep thinking I need one more source."],
        ["W", "Six is already more than most groups use."],
        ["M", "I know, but I'm afraid of missing something."],
        ["W", "You'll miss the deadline instead."],
        ["M", "That would be much worse, wouldn't it?"],
        ["W", "Why don't you write one page tonight?"],
      ],
      choices: [
        "I'll read three more articles.",
        "There is no deadline.",
        "You're right, I'll start tonight.",
        "I finished the project already.",
        "Writing is not my part.",
      ],
      answer: 3,
      clue: "Why don't you write one page tonight?",
      explanation:
        "오늘 밤에 한 쪽이라도 쓰라는 제안이므로, 그러겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 현빈아, 조별 과제 네 부분은 어때?",
        "M: 자료를 여섯 개 읽었는데 아직 한 줄도 못 썼어.",
        "W: 왜 아직 안 썼어?",
        "M: 자료가 하나 더 필요할 것 같아서.",
        "W: 여섯 개면 다른 조보다 이미 많아.",
        "M: 알아, 근데 뭔가 놓칠까 봐 겁나.",
        "W: 그러다 마감을 놓치게 돼.",
        "M: 그게 훨씬 나쁘겠지.",
        "W: 오늘 밤에 한 쪽만 써 보는 건 어때?",
        "M: 네 말이 맞아, 오늘 밤에 시작할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yebin이 Sejun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yebin : ________________",
      lines: [
        [
          "W",
          "Yebin and Sejun are cleaning up after the class party. " +
            "Sejun is about to throw all the paper cups into one bag. " +
            "Yebin sees that the school separates paper and plastic. " +
            "If everything goes in one bag, the cleaner has to sort it again. " +
            "She wants to stop him before he ties the bag shut. " +
            "In this situation, what would Yebin most likely say to Sejun?",
        ],
      ],
      choices: [
        "The party was really fun today.",
        "Let's wash the cups instead.",
        "Wait, the paper goes in another bag.",
        "I'll buy more cups tomorrow.",
        "You can go home first.",
      ],
      answer: 3,
      clue: "She wants to stop him before he ties the bag shut.",
      explanation:
        "종이와 플라스틱을 나눠 버려야 하므로, 종이는 다른 봉투에 넣으라는 ③이 가장 적절하다.",
      translation: [
        "W: 예빈이와 세준이는 학급 파티를 마치고 정리하고 있습니다. 세준이는 종이컵을 전부 한 봉투에 넣으려 합니다. 예빈이는 학교에서 종이와 플라스틱을 나눠 버린다는 것을 압니다. 다 한 봉투에 넣으면 청소하시는 분이 다시 나눠야 합니다. 예빈이는 세준이가 봉투를 묶기 전에 말리고 싶습니다. 이런 상황에서 예빈이가 세준이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
