/** 중1 듣기 24회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 24회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 모자를 고르시오.",
      lines: [
        ["W", "Good morning. Do you need a hat for the summer?"],
        ["M", "Yes, my old one is too tight now."],
        ["W", "We have caps with a front pocket and plain ones."],
        ["M", "A plain one, please. Pockets look too busy to me."],
        ["W", "All right. This plain cap has a ribbon around it."],
        ["M", "A ribbon is a bit much for school."],
        ["W", "Then here is a plain cap with a small star on the side."],
        ["M", "That's perfect. I'll take the one with the star."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A plain one, please. / I'll take the one with the star.",
      explanation:
        "남자는 앞주머니가 없는 단순한 모자를 원하고, 리본 대신 작은 별이 달린 것을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five baseball caps drawn side by side as five choices, clean black line art on white. " +
          "① a cap with a POCKET on the front and a RIBBON around it. " +
          "② a cap with a POCKET on the front and a small STAR on the side. " +
          "③ a PLAIN cap with a RIBBON around it. " +
          "④ a PLAIN cap with nothing on it at all. " +
          "⑤ a PLAIN cap with a small STAR on the side.",
      },
      translation: [
        "W: 안녕하세요. 여름용 모자 찾으세요?",
        "M: 네, 쓰던 게 이제 너무 꽉 껴서요.",
        "W: 앞에 주머니가 달린 모자도 있고 단순한 것도 있어요.",
        "M: 단순한 걸로 주세요. 주머니는 너무 복잡해 보여요.",
        "W: 알겠습니다. 이 단순한 모자는 둘레에 리본이 있어요.",
        "M: 학교에 쓰기엔 리본은 좀 과해요.",
        "W: 그럼 옆에 작은 별이 달린 단순한 모자가 여기 있어요.",
        "M: 딱 좋네요. 별 달린 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학급 캠핑에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yuna, are you going to the class camping trip?"],
        ["W", "Of course. When do we leave school?"],
        ["M", "The bus leaves on Friday at two in the afternoon."],
        ["W", "Where are we staying that night?"],
        ["M", "At the youth center beside Green Lake."],
        ["W", "Sounds nice. What do we do in the evening?"],
        ["M", "We cook dinner together and then look at the stars."],
        ["W", "Great. Should I pack anything special?"],
        ["M", "Bring a warm jacket. The lake gets cold at night."],
      ],
      choices: ["출발 시각", "묵을 곳", "저녁에 할 일", "챙길 물건", "참가 학생 수"],
      answer: 5,
      clue: "참가 학생 수는 대화에서 언급되지 않았다.",
      explanation:
        "출발 시각(금요일 오후 2시), 묵을 곳(그린 호수 옆 청소년 수련관), 저녁에 할 일(요리와 별 보기), 챙길 물건(따뜻한 외투)은 언급되지만 참가 학생 수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 유나야, 학급 캠핑 갈 거야?",
        "W: 당연하지. 학교에서 언제 출발해?",
        "M: 버스가 금요일 오후 2시에 떠나.",
        "W: 그날 밤엔 어디서 자?",
        "M: 그린 호수 옆 청소년 수련관에서.",
        "W: 좋다. 저녁엔 뭐 해?",
        "M: 다 같이 저녁 해 먹고 별을 봐.",
        "W: 멋지다. 특별히 챙겨 갈 게 있어?",
        "M: 따뜻한 외투 가져와. 호수는 밤에 추워져.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, Ms. Park. This is Dohyun from class two."],
        ["W", "Hi, Dohyun. Is everything all right?"],
        ["M", "I'm calling about the art contest form."],
        ["W", "You handed it in yesterday, didn't you?"],
        ["M", "I did, but I wrote the wrong birth date on it."],
        ["W", "Oh, we should fix that before Friday."],
        ["M", "May I come to your office tomorrow morning?"],
        ["W", "Sure. Come before the first class starts."],
      ],
      choices: [
        "신청서의 잘못 쓴 내용을 고치려고",
        "대회 날짜를 물어보려고",
        "상을 받으러 가려고",
        "그림 재료를 빌리려고",
        "대회 참가를 취소하려고",
      ],
      answer: 1,
      clue: "I did, but I wrote the wrong birth date on it.",
      explanation:
        "남자는 어제 낸 대회 신청서에 생년월일을 잘못 썼다며 고치러 가도 되는지 물으려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요, 박 선생님. 2반 도현입니다.",
        "W: 안녕, 도현아. 무슨 일 있니?",
        "M: 미술 대회 신청서 때문에 전화드렸어요.",
        "W: 어제 냈잖니?",
        "M: 냈는데, 생년월일을 잘못 썼어요.",
        "W: 아, 금요일 전에 고쳐야겠구나.",
        "M: 내일 아침에 교무실로 가도 될까요?",
        "W: 그럼. 1교시 시작하기 전에 오렴.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Dohyun, are you coming to the library tomorrow?"],
        ["M", "Yes. What time does it open on Saturday?"],
        ["W", "It opens at ten, but the study room opens later."],
        ["M", "Really? When can we use the study room?"],
        ["W", "From eleven. Before that, the cleaners are in there."],
        ["M", "Then let's not wait outside for an hour."],
        ["W", "Right. Let's meet when the study room opens."],
        ["M", "Good. I'll bring my math workbook."],
        ["W", "See you at the front desk then."],
      ],
      choices: ["9:00 a.m.", "10:00 a.m.", "10:30 a.m.", "11:00 a.m.", "11:30 a.m."],
      answer: 4,
      clue: "Let's meet when the study room opens.",
      explanation:
        "도서관은 10시에 열지만 열람실은 11시부터 쓸 수 있고, 두 사람은 열람실이 열 때 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 도현아, 내일 도서관 올 거야?",
        "M: 응. 토요일엔 몇 시에 열어?",
        "W: 10시에 여는데, 열람실은 더 늦게 열어.",
        "M: 그래? 열람실은 언제부터 쓸 수 있어?",
        "W: 11시부터. 그전엔 청소하시는 분들이 계셔.",
        "M: 그럼 한 시간이나 밖에서 기다리지는 말자.",
        "W: 맞아. 열람실 여는 시간에 만나자.",
        "M: 좋아. 나는 수학 문제집 가져갈게.",
        "W: 그럼 안내 데스크에서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuna, why are you looking at the clock again?"],
        ["W", "My name is next on the audition list."],
        ["M", "You practiced that song for a whole month."],
        ["W", "I know, but my heart is beating so fast."],
        ["M", "Take a deep breath. You'll do fine."],
        ["W", "My hands are shaking and my mouth is dry."],
        ["M", "Everyone feels like that before the stage."],
        ["W", "I hope I can remember the words up there."],
      ],
      choices: ["nervous", "bored", "proud", "curious", "thankful"],
      answer: 1,
      clue: "My hands are shaking and my mouth is dry.",
      explanation:
        "오디션 차례를 앞두고 심장이 빨리 뛰고 손이 떨린다고 했으므로 여자의 심정은 '긴장한(nervous)'이다. 따라서 답은 ①이다.",
      translation: [
        "M: 유나야, 왜 또 시계를 봐?",
        "W: 오디션 명단에서 다음이 내 이름이야.",
        "M: 너 그 노래 한 달 내내 연습했잖아.",
        "W: 알아, 그런데 심장이 너무 빨리 뛰어.",
        "M: 숨을 깊게 쉬어. 잘할 거야.",
        "W: 손도 떨리고 입도 말라.",
        "M: 무대 앞에서는 다들 그래.",
        "W: 위에서 가사를 기억할 수 있으면 좋겠어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I sit next to the window?"],
        ["M", "Sure, that seat is empty."],
        ["ANN", "Number two."],
        ["W", "Excuse me, you dropped your scarf."],
        ["M", "Oh, thank you so much."],
        ["ANN", "Number three."],
        ["W", "How much is this scarf?"],
        ["M", "It's fifteen dollars."],
        ["ANN", "Number four."],
        ["W", "Is it cold outside today?"],
        ["M", "Yes, wear something warm."],
        ["ANN", "Number five."],
        ["W", "Where did you buy that bag?"],
        ["M", "I got it at the market."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, you dropped your scarf.",
      explanation:
        "그림은 길에서 여학생이 앞서 걷던 남자가 떨어뜨린 목도리를 주워 건네주는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "A city sidewalk in winter, clean black line art on a plain white background, no writing anywhere. " +
          "A man in a coat is walking away and turning his head back over his shoulder. " +
          "Behind him a schoolgirl holds up a long scarf with both hands and calls out to him. " +
          "A bare tree and a simple bench are drawn in the background.",
      },
      translation: [
        "① W: 창가 자리에 앉아도 될까요? / M: 그럼요, 그 자리 비었어요.",
        "② W: 저기요, 목도리를 떨어뜨리셨어요. / M: 아, 정말 고맙습니다.",
        "③ W: 이 목도리 얼마예요? / M: 15달러입니다.",
        "④ W: 오늘 밖이 추워요? / M: 네, 따뜻하게 입으세요.",
        "⑤ W: 그 가방 어디서 샀어요? / M: 시장에서 샀어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuna, do you still go to the school library every day?"],
        ["W", "Yes, I read there after lunch. Why do you ask?"],
        ["M", "I broke my leg, so I can't go up to the third floor."],
        ["W", "Oh no. Do you need a book from there?"],
        ["M", "Yes, the history book I reserved came in yesterday."],
        ["W", "I see. Should I tell the librarian to keep it longer?"],
        ["M", "Actually, could you bring it to my classroom instead?"],
        ["W", "Sure. I'll drop it off after lunch today."],
      ],
      choices: ["책을 교실로 가져다주기", "도서관 자리 맡아 주기", "책 반납 날짜 미루기", "숙제 도와주기", "역사 필기 빌려주기"],
      answer: 1,
      clue: "Actually, could you bring it to my classroom instead?",
      explanation:
        "남자는 다리를 다쳐 3층 도서관에 갈 수 없어서, 예약한 책을 교실로 가져다 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 유나야, 너 아직도 학교 도서관에 매일 가?",
        "W: 응, 점심 먹고 거기서 책 읽어. 왜?",
        "M: 내가 다리를 다쳐서 3층까지 못 올라가.",
        "W: 어떡해. 거기서 책이 필요해?",
        "M: 응, 예약해 둔 역사책이 어제 들어왔거든.",
        "W: 그렇구나. 사서 선생님께 더 맡아 달라고 할까?",
        "M: 그것보다, 내 교실로 가져다줄 수 있어?",
        "W: 그럼. 오늘 점심 먹고 갖다줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 동아리에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, everyone. The school garden club is looking for new members. " +
            "We meet every Wednesday right after the last class. " +
            "Our garden is behind the science building, next to the small greenhouse. " +
            "This year we will grow tomatoes, lettuce, and strawberries. " +
            "Gloves and tools are already in the storage room, so bring only yourself. " +
            "Ask any member if you want to join us.",
        ],
      ],
      choices: ["모이는 요일", "텃밭의 위치", "기르는 작물", "동아리 회원 수", "준비물"],
      answer: 4,
      clue: "동아리 회원 수는 방송에서 언급되지 않았다.",
      explanation:
        "모이는 요일(수요일), 위치(과학관 뒤), 기르는 작물(토마토·상추·딸기), 준비물(따로 없음)은 언급되지만 회원 수는 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요, 여러분. 학교 텃밭 동아리에서 새 회원을 찾습니다. 우리는 매주 수요일 마지막 수업이 끝난 직후에 모입니다. 텃밭은 과학관 뒤, 작은 온실 옆에 있습니다. 올해는 토마토, 상추, 딸기를 기를 예정입니다. 장갑과 도구는 이미 창고에 있으니 몸만 오시면 됩니다. 함께하고 싶으면 아무 회원에게나 물어보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is something you carry when you leave home on a rainy day. " +
            "It is usually closed and thin, but you open it over your head. " +
            "It has a long handle and many thin metal bars inside. " +
            "People often leave it on the bus or in a shop by mistake. " +
            "When the rain stops, you close it and shake off the water.",
        ],
      ],
      choices: ["장화", "가방", "모자", "수건", "우산"],
      answer: 5,
      clue: "It has a long handle and many thin metal bars inside.",
      explanation:
        "비 오는 날 들고 나가 머리 위로 펴고, 긴 손잡이와 얇은 살이 있으며, 버스에 자주 두고 내리는 것은 우산이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 이것은 비 오는 날 집을 나설 때 들고 가는 것입니다. 보통은 접혀서 가늘지만, 머리 위로 펼칩니다. 긴 손잡이가 있고 안쪽에 얇은 금속 살이 여러 개 있습니다. 사람들은 이것을 버스나 가게에 자주 두고 옵니다. 비가 그치면 접어서 물을 털어 냅니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "What's the date today?"],
        ["M", "It's May eleventh."],
        ["ANN", "Number two."],
        ["W", "How was the movie?"],
        ["M", "It was really funny."],
        ["ANN", "Number three."],
        ["W", "Whose umbrella is this?"],
        ["M", "It's ten o'clock."],
        ["ANN", "Number four."],
        ["W", "May I use your phone?"],
        ["M", "Of course, go ahead."],
        ["ANN", "Number five."],
        ["W", "How do you go to school?"],
        ["M", "I usually take the subway."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Whose umbrella is this?",
      explanation:
        "누구의 우산인지 묻는 말에 10시라고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① W: 오늘 며칠이야? / M: 5월 11일이야.",
        "② W: 영화 어땠어? / M: 정말 웃겼어.",
        "③ W: 이거 누구 우산이야? / M: 10시야.",
        "④ W: 네 휴대폰 써도 돼? / M: 그럼, 써.",
        "⑤ W: 학교에 어떻게 가? / M: 보통 지하철 타.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuna, the school bazaar starts in twenty minutes."],
        ["W", "I know. Our table is almost ready."],
        ["M", "Did you count the cookies we baked yesterday?"],
        ["W", "Yes, there are sixty of them in the boxes."],
        ["M", "Good. But we still have no price sign on the table."],
        ["W", "You're right. Nobody will know how much they cost."],
        ["M", "I have to carry the chairs, so I can't do it."],
        ["W", "Then I'll make the sign right now with this marker."],
      ],
      choices: ["쿠키 굽기", "의자 옮기기", "쿠키 개수 세기", "가격표 만들기", "돈 거슬러 주기"],
      answer: 4,
      clue: "Then I'll make the sign right now with this marker.",
      explanation:
        "가격표가 없다는 말에, 여자는 지금 바로 매직펜으로 가격표를 만들겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 유나야, 학교 바자회가 20분 뒤에 시작해.",
        "W: 알아. 우리 탁자는 거의 다 준비됐어.",
        "M: 어제 구운 쿠키 개수 세어 봤어?",
        "W: 응, 상자에 60개 들어 있어.",
        "M: 좋아. 그런데 탁자에 가격표가 아직 없어.",
        "W: 맞네. 아무도 얼마인지 모르겠다.",
        "M: 나는 의자를 옮겨야 해서 못 해.",
        "W: 그럼 내가 지금 이 매직펜으로 만들게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 신청할 여름 강좌를 고르시오.",
      lines: [
        ["W", "Dohyun, have you picked a summer class at the youth center?"],
        ["M", "Not yet. I work at my uncle's shop every morning."],
        ["W", "Then you need one that starts in the afternoon."],
        ["M", "Exactly. And it must be three days a week or fewer."],
        ["W", "Okay, that narrows it down a lot."],
        ["M", "One more thing. I really don't want a swimming class."],
        ["W", "Why not? Swimming is good in summer."],
        ["M", "I can't swim at all, and I'd rather learn something quiet."],
        ["W", "Then only one class on this list is left for you."],
        ["M", "Good. I'll sign up online tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Then you need one that starts in the afternoon.",
      explanation:
        "오후에 시작하고, 주 3회 이하이며, 수영이 아닌 것을 고른다. 세 조건을 모두 채우는 것은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Time: Morning / Days: 2 a week / Class: Guitar" },
          { no: 2, label: "②", value: "Time: Afternoon / Days: 5 a week / Class: Guitar" },
          { no: 3, label: "③", value: "Time: Afternoon / Days: 3 a week / Class: Drawing" },
          { no: 4, label: "④", value: "Time: Afternoon / Days: 2 a week / Class: Swimming" },
          { no: 5, label: "⑤", value: "Time: Morning / Days: 3 a week / Class: Drawing" },
        ],
      },
      translation: [
        "W: 도현아, 청소년 수련관 여름 강좌 골랐어?",
        "M: 아직. 아침마다 삼촌 가게에서 일해.",
        "W: 그럼 오후에 시작하는 게 필요하겠네.",
        "M: 맞아. 그리고 주 3회 이하여야 해.",
        "W: 그러면 많이 좁혀지겠다.",
        "M: 하나 더. 수영 강좌는 정말 싫어.",
        "W: 왜? 여름엔 수영이 좋잖아.",
        "M: 나 수영을 전혀 못 해. 조용한 걸 배우고 싶어.",
        "W: 그럼 이 목록에서 너한테 남는 건 하나뿐이야.",
        "M: 좋아. 오늘 밤에 인터넷으로 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 이사를 도울 날짜를 고르시오.",
      lines: [
        ["W", "Dohyun, when can we help Mr. Kim move his bookshop?"],
        ["M", "How about November 3rd? That's a Saturday."],
        ["W", "I have a piano recital that whole day."],
        ["M", "Then what about November 5th, after school?"],
        ["W", "The shop is closed on the 5th, so nobody will be there."],
        ["M", "Hmm. November 9th is free for me."],
        ["W", "But the truck is only available until the 7th."],
        ["M", "Oh, then November 6th is our last chance."],
        ["W", "That works. I finish class at four that day."],
        ["M", "Great. Let's meet in front of the shop at five."],
      ],
      choices: ["11월 3일", "11월 5일", "11월 6일", "11월 7일", "11월 9일"],
      answer: 3,
      clue: "Oh, then November 6th is our last chance.",
      explanation:
        "3일에는 피아노 연주회가, 5일에는 가게 휴무가 있고 트럭은 7일까지만 쓸 수 있다. 두 사람은 11월 6일에 돕기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 도현아, 김 선생님 서점 이사는 언제 도와드릴 수 있을까?",
        "M: 11월 3일 어때? 토요일이야.",
        "W: 그날은 하루 종일 피아노 연주회가 있어.",
        "M: 그럼 11월 5일 방과 후는?",
        "W: 5일엔 가게가 쉬어서 아무도 없어.",
        "M: 음. 11월 9일은 내가 비어 있어.",
        "W: 그런데 트럭은 7일까지만 쓸 수 있대.",
        "M: 아, 그럼 11월 6일이 마지막 기회네.",
        "W: 그날 괜찮아. 그날은 4시에 수업이 끝나.",
        "M: 좋아. 5시에 가게 앞에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, your fingers look sore. What happened?"],
        ["M", "I spent all Sunday in my grandmother's kitchen."],
        ["W", "Did you help her cook something special?"],
        ["M", "We made kimchi together for the whole winter."],
        ["W", "Wow, that's a big job. How many cabbages?"],
        ["M", "Twenty of them. My hands were red for hours."],
        ["W", "Did your grandmother teach you the recipe?"],
        ["M", "She did, and I wrote every step in my notebook."],
      ],
      choices: ["텃밭 가꾸기", "설거지하기", "빵 굽기", "요리 대회 나가기", "김치 담그기"],
      answer: 5,
      clue: "We made kimchi together for the whole winter.",
      explanation:
        "남자는 일요일 내내 할머니와 겨울에 먹을 김치를 담갔다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 손가락이 아파 보인다. 무슨 일이야?",
        "M: 일요일 내내 할머니 부엌에 있었어.",
        "W: 특별한 요리를 도와드렸어?",
        "M: 겨울 내내 먹을 김치를 같이 담갔어.",
        "W: 우와, 큰일이었겠다. 배추 몇 포기나?",
        "M: 스무 포기. 손이 몇 시간이나 빨갰어.",
        "W: 할머니가 만드는 법도 가르쳐 주셨어?",
        "M: 응, 나는 모든 순서를 공책에 적어 뒀어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the student council. " +
            "Many students leave their lunch trays on the tables these days. " +
            "The kitchen staff then have to clean every table by themselves. " +
            "Please carry your own tray to the return window after you eat. " +
            "It takes only ten seconds, but it helps everyone a lot. " +
            "Thank you for listening, and enjoy your lunch.",
        ],
      ],
      choices: [
        "급식 메뉴를 알리려고",
        "식판을 직접 반납하도록 당부하려고",
        "점심시간 연장을 알리려고",
        "학생회 선거를 안내하려고",
        "식당 공사를 알리려고",
      ],
      answer: 2,
      clue: "Please carry your own tray to the return window after you eat.",
      explanation:
        "식판을 탁자에 두고 가는 학생이 많으니 직접 반납구에 가져다 놓으라고 당부하는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 안내 말씀 드립니다. 학생회입니다. 요즘 식판을 탁자에 그대로 두고 가는 학생이 많습니다. 그러면 조리사 선생님들이 모든 탁자를 혼자 치우셔야 합니다. 식사 후에는 식판을 반납구까지 직접 가져다 놓아 주세요. 10초밖에 걸리지 않지만 모두에게 큰 도움이 됩니다. 들어 주셔서 감사하고, 맛있게 드세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the science show?"],
        ["M", "Yes, two adult tickets and one child ticket, please."],
        ["W", "An adult ticket is nine dollars and a child ticket is five."],
        ["M", "Okay. Here is my card."],
        ["W", "Wait, do you have a museum membership?"],
        ["M", "Yes, I joined last spring."],
        ["W", "Then you get three dollars off the whole order."],
        ["M", "That's great news. Thank you."],
      ],
      choices: ["$18", "$20", "$23", "$26", "$28"],
      answer: 2,
      clue: "Then you get three dollars off the whole order.",
      explanation:
        "어른 표 두 장 18달러와 어린이 표 한 장 5달러를 더하면 23달러이고, 회원 할인 3달러를 빼면 20달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 과학 쇼 표 사시나요?",
        "M: 네, 어른 두 장이랑 어린이 한 장 주세요.",
        "W: 어른 표는 9달러, 어린이 표는 5달러입니다.",
        "M: 알겠습니다. 여기 카드요.",
        "W: 잠깐만요, 박물관 회원이신가요?",
        "M: 네, 지난봄에 가입했어요.",
        "W: 그럼 전체 금액에서 3달러를 빼 드립니다.",
        "M: 잘됐네요. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yuna, you've been staring at that plant all week."],
        ["W", "It was green last month, but now the leaves are yellow."],
        ["M", "Do you water it every day?"],
        ["W", "Yes, I give it a full cup every morning."],
        ["M", "That might be the problem, not the answer."],
        ["W", "Really? I thought plants needed a lot of water."],
        ["M", "Too much water makes the roots rot."],
        ["W", "Then how often should I water this one?"],
        ["M", "Twice a week is enough for a plant that size."],
      ],
      choices: [
        "I'll buy a bigger cup tomorrow.",
        "The leaves were yellow last year.",
        "Okay, I'll water it only twice a week.",
        "Plants don't need any sunlight.",
        "I moved it to the kitchen yesterday.",
      ],
      answer: 3,
      clue: "Twice a week is enough for a plant that size.",
      explanation:
        "남자가 그 크기의 식물은 일주일에 두 번이면 충분하다고 했으므로, 그렇게 하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 유나야, 너 일주일 내내 그 화분만 보고 있네.",
        "W: 지난달엔 초록색이었는데 이제 잎이 노래졌어.",
        "M: 매일 물 줘?",
        "W: 응, 아침마다 한 컵 가득 줘.",
        "M: 그게 답이 아니라 문제일 수도 있어.",
        "W: 정말? 식물은 물이 많이 필요한 줄 알았어.",
        "M: 물이 너무 많으면 뿌리가 썩어.",
        "W: 그럼 이건 얼마나 자주 줘야 해?",
        "M: 그 크기 식물은 일주일에 두 번이면 충분해.",
        "W: 알겠어, 일주일에 두 번만 줄게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Dohyun, did you hear about the marathon next month?"],
        ["M", "Yes, but ten kilometers sounds impossible for me."],
        ["W", "There is a three-kilometer course, too."],
        ["M", "Three? That still feels long. I get tired so fast."],
        ["W", "Everybody does at first. I started with one kilometer."],
        ["M", "How long did it take you to reach three?"],
        ["W", "About six weeks of running twice a week."],
        ["M", "So I still have enough time before the race."],
        ["W", "Why don't you run with me this Saturday morning?"],
      ],
      choices: [
        "I already finished the marathon.",
        "Ten kilometers is too short for me.",
        "I don't like Saturday movies.",
        "Sounds good. Where should we meet?",
        "You should rest for six weeks.",
      ],
      answer: 4,
      clue: "Why don't you run with me this Saturday morning?",
      explanation:
        "여자가 토요일 아침에 같이 달리자고 제안했으므로, 좋다며 만날 곳을 묻는 ④가 가장 자연스럽다.",
      translation: [
        "W: 도현아, 다음 달 마라톤 얘기 들었어?",
        "M: 응, 그런데 10킬로미터는 나한텐 불가능해 보여.",
        "W: 3킬로미터 코스도 있어.",
        "M: 3킬로? 그것도 길게 느껴져. 나 금방 지쳐.",
        "W: 처음엔 다 그래. 나도 1킬로미터부터 시작했어.",
        "M: 3킬로까지 가는 데 얼마나 걸렸어?",
        "W: 일주일에 두 번씩 여섯 주쯤.",
        "M: 그럼 대회까지 시간은 충분하네.",
        "W: 이번 토요일 아침에 나랑 같이 달릴래?",
        "M: 좋아. 어디서 만날까?",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Yuna, our group has to present the report on Monday."],
        ["W", "I know. Who is making the slides this time?"],
        ["M", "Jisoo said she would, but she's sick at home."],
        ["W", "Oh no. Has anyone started the slides at all?"],
        ["M", "Not yet. We only have the written part finished."],
        ["W", "Then we need to work on them this weekend."],
        ["M", "I'm free on Sunday, but the school is closed."],
        ["W", "We can share one file online and work from home."],
        ["M", "That's a good idea. How do we start?"],
        ["W", "I'll open a new file and send you the link tonight."],
      ],
      choices: [
        "Thanks. I'll check my mail after dinner.",
        "Let's meet at school on Sunday then.",
        "Jisoo finished all the slides already.",
        "The report is due next month.",
        "I don't have a computer at home.",
      ],
      answer: 1,
      clue: "I'll open a new file and send you the link tonight.",
      explanation:
        "여자가 오늘 밤에 파일을 만들어 링크를 보내 주겠다고 했으므로, 고맙다며 저녁 후에 확인하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 유나야, 우리 조는 월요일에 보고서를 발표해야 해.",
        "W: 알아. 이번엔 누가 슬라이드 만들어?",
        "M: 지수가 한다고 했는데 아파서 집에 있어.",
        "W: 어떡해. 슬라이드는 누가 시작이라도 했어?",
        "M: 아직. 글로 쓴 부분만 끝났어.",
        "W: 그럼 이번 주말에 해야겠다.",
        "M: 나는 일요일에 시간 되는데, 학교가 문을 닫아.",
        "W: 온라인으로 파일 하나를 같이 쓰면서 집에서 하면 돼.",
        "M: 좋은 생각이야. 어떻게 시작해?",
        "W: 내가 오늘 밤에 새 파일 만들어서 링크 보낼게.",
        "M: 고마워. 저녁 먹고 메일 확인할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiwon이 Hanbyul에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jiwon : ________________",
      lines: [
        [
          "M",
          "Jiwon and Hanbyul are classmates who sit next to each other. " +
            "Today the class is taking a long test in the afternoon. " +
            "Jiwon sees that Hanbyul is looking through her pencil case again and again. " +
            "Hanbyul has only one pencil, and its point has just broken. " +
            "Jiwon has two sharp pencils in his own case. " +
            "In this situation, what would Jiwon most likely say to Hanbyul?",
        ],
      ],
      choices: [
        "Let's check the answers together.",
        "You can use one of my pencils.",
        "The test starts next Monday.",
        "I lost my pencil case yesterday.",
        "Please close your pencil case.",
      ],
      answer: 2,
      clue: "Jiwon has two sharp pencils in his own case.",
      explanation:
        "한별이의 하나뿐인 연필심이 부러졌고 지원이에게는 깎아 둔 연필이 두 자루 있으므로, 자기 연필을 쓰라고 하는 ②가 가장 적절하다.",
      translation: [
        "M: 지원이와 한별이는 옆자리에 앉는 같은 반 친구입니다. 오늘 오후에 반 전체가 긴 시험을 봅니다. 지원이는 한별이가 필통을 자꾸 뒤지는 것을 봅니다. 한별이에게는 연필이 한 자루뿐인데, 방금 그 심이 부러졌습니다. 지원이의 필통에는 잘 깎은 연필이 두 자루 있습니다. 이런 상황에서 지원이가 한별이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
