/** 중1 듣기 27회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 27회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 가방을 고르시오.",
      lines: [
        ["M", "Good afternoon. Are you looking for a school bag?"],
        ["W", "Yes, my old one has a hole in the bottom."],
        ["M", "We have backpacks and shoulder bags."],
        ["W", "A backpack, please. My shoulders hurt with the other kind."],
        ["M", "All right. This backpack has two side pockets."],
        ["W", "Side pockets always catch on the door for me."],
        ["M", "Then here is a backpack with one front pocket."],
        ["W", "That's better. I'll take the one with the front pocket."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "A backpack, please. / I'll take the one with the front pocket.",
      explanation:
        "여자는 등에 메는 가방을 원하고, 옆주머니 대신 앞주머니가 하나 있는 것을 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five school bags drawn side by side as five choices, clean black line art on white. " +
          "① a SHOULDER BAG with one strap and TWO SIDE POCKETS. " +
          "② a SHOULDER BAG with one strap and ONE FRONT POCKET. " +
          "③ a BACKPACK with two shoulder straps and ONE FRONT POCKET. " +
          "④ a BACKPACK with two shoulder straps and TWO SIDE POCKETS. " +
          "⑤ a BACKPACK with two shoulder straps and NO pockets at all.",
      },
      translation: [
        "M: 안녕하세요. 학교 가방 찾으세요?",
        "W: 네, 쓰던 게 바닥에 구멍이 났어요.",
        "M: 등에 메는 가방도 있고 어깨에 드는 가방도 있어요.",
        "W: 등에 메는 걸로 주세요. 다른 건 어깨가 아파서요.",
        "M: 알겠습니다. 이 가방은 옆주머니가 두 개예요.",
        "W: 옆주머니는 늘 문에 걸리더라고요.",
        "M: 그럼 앞주머니가 하나 있는 가방이 여기 있어요.",
        "W: 그게 낫네요. 앞주머니 있는 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 여름 영어 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jiho, are you going to the summer English camp?"],
        ["M", "Maybe. How many days does it last?"],
        ["W", "Four days, from Monday to Thursday."],
        ["M", "Where do we stay at night?"],
        ["W", "In the school dormitory near the sports field."],
        ["M", "What do we do all day there?"],
        ["W", "We act out plays and play word games in English."],
        ["M", "Sounds fun. Who can apply for it?"],
        ["W", "Any first or second grader can sign up."],
      ],
      choices: ["기간", "참가비", "묵는 곳", "하는 활동", "신청 자격"],
      answer: 2,
      clue: "참가비는 대화에서 언급되지 않았다.",
      explanation:
        "기간(월~목 4일), 묵는 곳(학교 기숙사), 활동(연극과 낱말 놀이), 신청 자격(1·2학년)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 지호야, 여름 영어 캠프 갈 거야?",
        "M: 아마도. 며칠 동안 해?",
        "W: 월요일부터 목요일까지 나흘.",
        "M: 밤에는 어디서 자?",
        "W: 운동장 근처 학교 기숙사에서.",
        "M: 거기서 하루 종일 뭐 해?",
        "W: 영어로 연극도 하고 낱말 놀이도 해.",
        "M: 재밌겠다. 누가 신청할 수 있어?",
        "W: 1학년이나 2학년이면 누구나 신청할 수 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, is this the Sunflower Animal Clinic?"],
        ["M", "Yes, speaking. How may I help you?"],
        ["W", "My cat has not eaten anything since last night."],
        ["M", "I see. Is she drinking water at least?"],
        ["W", "A little, but she just lies under the sofa."],
        ["M", "You should bring her in as soon as possible."],
        ["W", "Can I come at five this afternoon?"],
        ["M", "Yes, the doctor is free at five. I'll write your name down."],
      ],
      choices: [
        "고양이 사료를 주문하려고",
        "병원 위치를 물어보려고",
        "진료비를 물어보려고",
        "고양이를 맡기려고",
        "고양이 진료를 예약하려고",
      ],
      answer: 5,
      clue: "Can I come at five this afternoon?",
      explanation:
        "여자는 아픈 고양이를 오후 5시에 데려가도 되는지 물어 진료를 예약하려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여보세요, 해바라기 동물병원이죠?",
        "M: 네, 맞습니다. 무엇을 도와드릴까요?",
        "W: 우리 고양이가 어젯밤부터 아무것도 안 먹어요.",
        "M: 그렇군요. 물은 마시나요?",
        "W: 조금요. 그런데 소파 밑에 계속 누워만 있어요.",
        "M: 되도록 빨리 데려오시는 게 좋겠습니다.",
        "W: 오늘 오후 5시에 가도 될까요?",
        "M: 네, 5시에 선생님이 비어 있어요. 성함 적어 두겠습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Nayeon, what time does the movie start on Saturday?"],
        ["W", "At two thirty in the afternoon."],
        ["M", "Should we buy the tickets before that?"],
        ["W", "I already booked two seats online last night."],
        ["M", "Great. Then we only need to pick them up."],
        ["W", "Right, but I want some popcorn before we go in."],
        ["M", "Then let's meet half an hour before the movie."],
        ["W", "Perfect. I'll wait by the ticket machine."],
        ["M", "See you there on Saturday."],
      ],
      choices: ["1:30 p.m.", "2:30 p.m.", "2:00 p.m.", "3:00 p.m.", "3:30 p.m."],
      answer: 3,
      clue: "Then let's meet half an hour before the movie.",
      explanation:
        "영화가 2시 30분에 시작하고 30분 전에 만나기로 했으므로 만나는 시각은 2시이다. 따라서 답은 ③이다.",
      translation: [
        "M: 나연아, 토요일에 영화 몇 시에 시작해?",
        "W: 오후 2시 30분에.",
        "M: 그전에 표를 사야 해?",
        "W: 어젯밤에 인터넷으로 두 자리 예매했어.",
        "M: 잘했다. 그럼 표만 찾으면 되네.",
        "W: 맞아, 그런데 들어가기 전에 팝콘 사고 싶어.",
        "M: 그럼 영화 시작 30분 전에 만나자.",
        "W: 좋아. 나는 발권기 옆에서 기다릴게.",
        "M: 토요일에 거기서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, why are you sitting alone out here?"],
        ["M", "My team lost the basketball game this morning."],
        ["W", "I heard it was very close at the end."],
        ["M", "I missed the last shot, and the buzzer went off."],
        ["W", "That could happen to anyone, even to a pro."],
        ["M", "We practiced every morning for two months."],
        ["W", "And you played really well all through the game."],
        ["M", "Still, I let all of my teammates down."],
      ],
      choices: ["disappointed", "excited", "curious", "surprised", "thankful"],
      answer: 1,
      clue: "Still, I let all of my teammates down.",
      explanation:
        "마지막 슛을 놓쳐 경기에서 졌고 팀원들을 실망시켰다고 했으므로 남자의 심정은 '실망한(disappointed)'이다. 따라서 답은 ①이다.",
      translation: [
        "W: 지호야, 왜 여기 혼자 앉아 있어?",
        "M: 오늘 아침에 우리 팀이 농구 경기에서 졌어.",
        "W: 끝까지 아주 접전이었다고 들었어.",
        "M: 내가 마지막 슛을 놓쳤고 종료 버저가 울렸어.",
        "W: 그건 누구한테나 있는 일이야. 프로 선수도 그래.",
        "M: 두 달 동안 아침마다 연습했는데.",
        "W: 그리고 너는 경기 내내 정말 잘했어.",
        "M: 그래도 팀원들을 다 실망시켰어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is this your first time here?"],
        ["M", "Yes, I came with my brother."],
        ["ANN", "Number two."],
        ["W", "Excuse me, can you take a picture of us?"],
        ["M", "Sure, stand a little closer together."],
        ["ANN", "Number three."],
        ["W", "How much is the entrance fee?"],
        ["M", "It's free for students."],
        ["ANN", "Number four."],
        ["W", "Where is the nearest bus stop?"],
        ["M", "Go straight and turn left."],
        ["ANN", "Number five."],
        ["W", "Did you enjoy the show?"],
        ["M", "Yes, it was wonderful."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, can you take a picture of us?",
      explanation:
        "그림은 공원에서 두 여학생이 지나가던 남자에게 휴대폰을 건네며 사진을 찍어 달라고 부탁하는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "In a park in front of a big fountain, clean black line art on a plain white background, no writing anywhere. " +
          "Two schoolgirls stand side by side and one of them holds out a smartphone toward a man. " +
          "The man is taking the phone with one hand and smiling at them. " +
          "Trees and a bench are drawn simply in the background.",
      },
      translation: [
        "① W: 여기 처음 오셨어요? / M: 네, 형이랑 같이 왔어요.",
        "② W: 저기요, 저희 사진 좀 찍어 주실래요? / M: 그럼요, 조금 더 붙어 서세요.",
        "③ W: 입장료가 얼마예요? / M: 학생은 무료예요.",
        "④ W: 가장 가까운 버스 정류장이 어디예요? / M: 곧장 가서 왼쪽으로 도세요.",
        "⑤ W: 공연 재미있었어요? / M: 네, 정말 멋졌어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, do you still keep the class key after school?"],
        ["M", "Yes, I lock the door every day at five."],
        ["W", "I left my science report on my desk today."],
        ["M", "Do you need it before tomorrow morning?"],
        ["W", "Yes, I have to finish the last page tonight."],
        ["M", "But you already went home, didn't you?"],
        ["W", "I did. Could you take it out and keep it for me?"],
        ["M", "No problem. I'll bring it to you at the gate."],
      ],
      choices: ["교실 문 잠그기", "두고 온 보고서 챙겨 주기", "보고서 대신 써 주기", "책상 정리하기", "열쇠 빌려주기"],
      answer: 2,
      clue: "Could you take it out and keep it for me?",
      explanation:
        "여자는 교실 책상에 두고 온 과학 보고서를 대신 챙겨 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 지호야, 아직도 방과 후에 교실 열쇠 가지고 있어?",
        "M: 응, 매일 5시에 문 잠가.",
        "W: 오늘 과학 보고서를 책상에 두고 왔어.",
        "M: 내일 아침 전에 필요해?",
        "W: 응, 오늘 밤에 마지막 장을 끝내야 해.",
        "M: 그런데 너 벌써 집에 갔잖아?",
        "W: 맞아. 그거 꺼내서 좀 챙겨 줄 수 있어?",
        "M: 그럼. 정문에서 갖다줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 중고 교복 나눔에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, everyone. Our school uniform sharing day is coming soon. " +
            "It will be held next Monday in the first floor lobby. " +
            "Bring any uniform that is clean and still in good shape. " +
            "You may take one shirt and one pair of pants for free. " +
            "The lobby will be open from nine in the morning until four. " +
            "Please help your friends and save your family's money.",
        ],
      ],
      choices: ["열리는 날", "열리는 장소", "가져올 물건의 상태", "가져갈 수 있는 개수", "담당 선생님"],
      answer: 5,
      clue: "담당 선생님은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 월요일), 장소(1층 로비), 가져올 물건의 상태(깨끗하고 멀쩡한 것), 가져갈 수 있는 개수(셔츠 한 벌과 바지 한 벌)는 언급되지만 담당 선생님은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안녕하세요, 여러분. 곧 교복 나눔의 날이 열립니다. 다음 주 월요일 1층 로비에서 진행됩니다. 깨끗하고 아직 멀쩡한 교복이면 무엇이든 가져오세요. 셔츠 한 벌과 바지 한 벌을 무료로 가져갈 수 있습니다. 로비는 아침 9시부터 4시까지 열려 있습니다. 친구들을 돕고 가정의 지출도 줄여 보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a place you visit when you want to send something far away. " +
            "You bring a box or a letter and put a small sticker on it. " +
            "The worker weighs your box and tells you the price. " +
            "People also come here to pay bills or to save money. " +
            "The red color is often used for its sign in Korea.",
        ],
      ],
      choices: ["은행", "경찰서", "우체국", "도서관", "약국"],
      answer: 3,
      clue: "You bring a box or a letter and put a small sticker on it.",
      explanation:
        "상자나 편지에 우표를 붙여 멀리 보내고, 무게를 달아 요금을 알려 주는 곳은 우체국이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이곳은 무언가를 멀리 보내고 싶을 때 가는 곳입니다. 상자나 편지를 가져가서 작은 딱지를 붙입니다. 직원이 상자의 무게를 재고 요금을 알려 줍니다. 사람들은 요금을 내거나 돈을 맡기러 오기도 합니다. 한국에서는 간판에 빨간색을 자주 씁니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was your trip to Jeju?"],
        ["W", "I have three brothers."],
        ["ANN", "Number two."],
        ["M", "How do you spell your name?"],
        ["W", "It's N-A-Y-E-O-N."],
        ["ANN", "Number three."],
        ["M", "What's wrong with your arm?"],
        ["W", "I fell off my bike yesterday."],
        ["ANN", "Number four."],
        ["M", "Where does your uncle live?"],
        ["W", "He lives in Busan."],
        ["ANN", "Number five."],
        ["M", "Can I borrow your umbrella?"],
        ["W", "Sure, take this one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "How was your trip to Jeju?",
      explanation:
        "제주 여행이 어땠는지 묻는 말에 형제가 셋이라고 답했으므로 ①의 대화가 어색하다. 따라서 답은 ①이다.",
      translation: [
        "① M: 제주 여행 어땠어? / W: 나는 형이 셋이야.",
        "② M: 이름 철자가 어떻게 돼? / W: N-A-Y-E-O-N이야.",
        "③ M: 팔이 왜 그래? / W: 어제 자전거에서 넘어졌어.",
        "④ M: 너희 삼촌은 어디 사셔? / W: 부산에 사셔.",
        "⑤ M: 네 우산 빌려도 돼? / W: 그럼, 이거 가져가.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nayeon, are we ready for the class party tomorrow?"],
        ["W", "Almost. I bought the paper cups and plates today."],
        ["M", "Great. Did anyone order the fruit for the table?"],
        ["W", "Yes, Minsu is bringing it in the morning."],
        ["M", "Good. What about the music for the games?"],
        ["W", "Oh, nobody has made the song list yet."],
        ["M", "I can't do it. My phone battery just died."],
        ["W", "Then I'll make the list on my phone right now."],
      ],
      choices: ["종이컵 사기", "과일 주문하기", "교실 꾸미기", "노래 목록 만들기", "휴대폰 충전하기"],
      answer: 4,
      clue: "Then I'll make the list on my phone right now.",
      explanation:
        "노래 목록을 아직 아무도 만들지 않았고 남자는 휴대폰이 꺼져서, 여자가 지금 자기 휴대폰으로 만들겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 나연아, 내일 학급 파티 준비 다 됐어?",
        "W: 거의. 오늘 종이컵이랑 접시를 샀어.",
        "M: 잘했다. 탁자에 올릴 과일은 누가 주문했어?",
        "W: 응, 민수가 아침에 가져와.",
        "M: 좋아. 게임할 때 틀 음악은?",
        "W: 아, 아직 아무도 노래 목록을 안 만들었어.",
        "M: 나는 못 해. 방금 휴대폰 배터리가 나갔어.",
        "W: 그럼 내가 지금 내 휴대폰으로 만들게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 책상 스탠드를 고르시오.",
      lines: [
        ["W", "Jiho, which desk lamp are you going to buy?"],
        ["M", "Let me see the list first."],
        ["W", "Do you want one you can bend and move?"],
        ["M", "Yes, I need to move the light while I study."],
        ["W", "Okay. How much can you spend?"],
        ["M", "Thirty thousand won at most. That's my whole allowance."],
        ["W", "Right. Do you want one with a clock on it?"],
        ["M", "No, a clock would only make me watch the time."],
        ["W", "Then only one lamp on this list is left."],
        ["M", "Good. Let's order it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Yes, I need to move the light while I study.",
      explanation:
        "구부릴 수 있고, 3만 원 이하이며, 시계가 없는 것을 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Bendable: No / Price: 25,000 won / Clock: No" },
          { no: 2, label: "②", value: "Bendable: Yes / Price: 22,000 won / Clock: No" },
          { no: 3, label: "③", value: "Bendable: Yes / Price: 38,000 won / Clock: No" },
          { no: 4, label: "④", value: "Bendable: Yes / Price: 28,000 won / Clock: Yes" },
          { no: 5, label: "⑤", value: "Bendable: No / Price: 19,000 won / Clock: Yes" },
        ],
      },
      translation: [
        "W: 지호야, 어떤 책상 스탠드 살 거야?",
        "M: 목록 먼저 볼게.",
        "W: 구부려서 움직일 수 있는 걸 원해?",
        "M: 응, 공부하면서 빛을 옮겨야 해.",
        "W: 알겠어. 얼마까지 쓸 수 있어?",
        "M: 최대 3만 원. 그게 내 용돈 전부야.",
        "W: 그렇구나. 시계가 달린 게 좋아?",
        "M: 아니, 시계가 있으면 자꾸 시간만 보게 돼.",
        "W: 그럼 이 목록에서 남는 건 하나뿐이야.",
        "M: 좋아. 오늘 밤에 주문하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 김장을 도울 날짜를 고르시오.",
      lines: [
        ["W", "Jiho, when should we help at the kimchi sharing event?"],
        ["M", "How about December 1st? It's a Saturday."],
        ["W", "I have my cousin's wedding that afternoon."],
        ["M", "Then what about December 4th?"],
        ["W", "The community center is closed on the 4th."],
        ["M", "Hmm. December 8th is free for me."],
        ["W", "But all the cabbage will be gone by the 6th."],
        ["M", "You're right. Then December 5th is the only day."],
        ["W", "That's fine. I finish school at two on Wednesdays."],
        ["M", "Great. Let's wear old clothes that day."],
      ],
      choices: ["12월 1일", "12월 4일", "12월 6일", "12월 8일", "12월 5일"],
      answer: 5,
      clue: "You're right. Then December 5th is the only day.",
      explanation:
        "1일에는 결혼식이, 4일에는 휴관이 있고 6일이면 배추가 다 떨어진다. 두 사람은 12월 5일에 돕기로 한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 지호야, 김치 나눔 행사는 언제 도울까?",
        "M: 12월 1일 어때? 토요일이야.",
        "W: 그날 오후에 사촌 언니 결혼식이 있어.",
        "M: 그럼 12월 4일은?",
        "W: 4일엔 주민 센터가 문을 닫아.",
        "M: 음. 12월 8일은 내가 비어 있어.",
        "W: 그런데 6일이면 배추가 다 떨어져.",
        "M: 맞네. 그럼 12월 5일밖에 없다.",
        "W: 괜찮아. 수요일엔 2시에 학교가 끝나.",
        "M: 좋아. 그날은 헌 옷 입고 가자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nayeon, you look sunburned on your nose."],
        ["W", "I was on the school roof all Saturday afternoon."],
        ["M", "The roof? What were you doing up there?"],
        ["W", "Our club planted flowers in the empty boxes."],
        ["M", "I didn't know we could grow anything up there."],
        ["W", "We filled twelve boxes with soil and seeds."],
        ["M", "That must have been heavy work."],
        ["W", "It was, but the roof looks like a small garden now."],
      ],
      choices: ["교실 청소하기", "그림 그리기", "옥상에 꽃 심기", "운동회 준비하기", "동아리 발표하기"],
      answer: 3,
      clue: "Our club planted flowers in the empty boxes.",
      explanation:
        "여자는 토요일 오후에 동아리 친구들과 학교 옥상 화분에 꽃을 심었다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 나연아, 코가 탔네.",
        "W: 토요일 오후 내내 학교 옥상에 있었어.",
        "M: 옥상? 거기서 뭐 했어?",
        "W: 우리 동아리가 빈 상자에 꽃을 심었어.",
        "M: 거기서 뭘 기를 수 있는 줄 몰랐어.",
        "W: 상자 열두 개에 흙이랑 씨앗을 채웠어.",
        "M: 힘든 일이었겠다.",
        "W: 힘들었지만 이제 옥상이 작은 정원 같아.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school office. " +
            "Tomorrow the whole school will take the yearly class photos. " +
            "Please wear your full school uniform, including your jacket. " +
            "Photos will be taken in the gym from nine until eleven. " +
            "Each class should come down as soon as its turn is called. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "학급 사진 촬영을 안내하려고",
        "체육관 공사를 알리려고",
        "교복 판매를 안내하려고",
        "운동회 일정을 알리려고",
        "졸업식을 안내하려고",
      ],
      answer: 1,
      clue: "Tomorrow the whole school will take the yearly class photos.",
      explanation:
        "내일 체육관에서 학급 사진을 찍으니 교복을 갖춰 입고 차례가 되면 내려오라고 안내하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실입니다. 내일 전교생이 연례 학급 사진을 찍습니다. 재킷을 포함해 교복을 모두 갖춰 입어 주세요. 사진은 체육관에서 9시부터 11시까지 찍습니다. 각 반은 차례가 불리면 바로 내려와 주세요. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the bakery. What can I get you?"],
        ["W", "Four muffins and two milk breads, please."],
        ["M", "A muffin is three dollars and a milk bread is four."],
        ["W", "Then that's twenty dollars in total, right?"],
        ["M", "Yes, that's correct."],
        ["W", "I have this coupon from the school festival."],
        ["M", "Let me see. It gives you four dollars off."],
        ["W", "Wonderful. Here you are."],
      ],
      choices: ["$14", "$18", "$19", "$16", "$20"],
      answer: 4,
      clue: "Let me see. It gives you four dollars off.",
      explanation:
        "머핀 4개 12달러와 우유식빵 2개 8달러를 더하면 20달러이고, 쿠폰 할인 4달러를 빼면 16달러이다. 따라서 답은 ④이다.",
      translation: [
        "M: 빵집에 오신 걸 환영합니다. 무엇을 드릴까요?",
        "W: 머핀 네 개랑 우유식빵 두 개 주세요.",
        "M: 머핀은 3달러, 우유식빵은 4달러입니다.",
        "W: 그럼 모두 20달러죠?",
        "M: 네, 맞습니다.",
        "W: 학교 축제에서 받은 이 쿠폰이 있어요.",
        "M: 볼게요. 4달러 할인되네요.",
        "W: 잘됐네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayeon, you brought your violin to school again."],
        ["W", "Yes, but I can't find a place to practice."],
        ["M", "Isn't the music room open after school?"],
        ["W", "The band uses it every day until six."],
        ["M", "What about practicing at home instead?"],
        ["W", "Our apartment walls are thin, so the neighbors complain."],
        ["M", "Then you need a room you can book for an hour."],
        ["W", "Does our school have a room like that?"],
        ["M", "Yes, the small room next to the library."],
      ],
      choices: [
        "I don't play the violin anymore.",
        "I'll ask about that room tomorrow.",
        "The band practices on weekends.",
        "My neighbors love loud music.",
        "The library closes at four.",
      ],
      answer: 2,
      clue: "Yes, the small room next to the library.",
      explanation:
        "남자가 도서관 옆 작은 방을 알려 주었으므로, 내일 그 방에 대해 물어보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나연아, 오늘도 바이올린 가져왔네.",
        "W: 응, 그런데 연습할 데를 못 찾겠어.",
        "M: 방과 후에 음악실 안 열어?",
        "W: 밴드가 매일 6시까지 써.",
        "M: 집에서 연습하는 건 어때?",
        "W: 우리 아파트는 벽이 얇아서 이웃이 싫어해.",
        "M: 그럼 한 시간씩 예약할 수 있는 방이 필요하겠다.",
        "W: 우리 학교에 그런 방이 있어?",
        "M: 응, 도서관 옆 작은 방.",
        "W: 내일 그 방에 대해 물어볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jiho, why is your notebook so wet?"],
        ["M", "My water bottle opened inside my bag."],
        ["W", "Oh no. Is your homework still readable?"],
        ["M", "Half of it. The ink ran down the last two pages."],
        ["W", "Will the teacher let you hand it in late?"],
        ["M", "I'm not sure. I'm afraid to ask her."],
        ["W", "She's kind. Just explain what happened."],
        ["M", "Should I show her the wet pages, too?"],
        ["W", "Yes, then she'll know you really did the work."],
      ],
      choices: [
        "I'll throw the notebook away.",
        "She never reads our homework.",
        "My bottle was empty all day.",
        "I'll buy a new water bottle.",
        "Okay, I'll show her after class.",
      ],
      answer: 5,
      clue: "Yes, then she'll know you really did the work.",
      explanation:
        "여자가 젖은 쪽도 보여 드리라고 했으므로, 알겠다며 수업 후에 보여 드리겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 지호야, 공책이 왜 이렇게 젖었어?",
        "M: 가방 안에서 물병이 열렸어.",
        "W: 어떡해. 숙제는 아직 알아볼 수 있어?",
        "M: 절반만. 마지막 두 쪽은 잉크가 번졌어.",
        "W: 선생님이 늦게 내도 된다고 하실까?",
        "M: 모르겠어. 여쭤보기가 겁나.",
        "W: 좋은 분이셔. 무슨 일이 있었는지 말씀드려.",
        "M: 젖은 쪽도 보여 드려야 할까?",
        "W: 응, 그래야 네가 정말 했다는 걸 아시지.",
        "M: 알겠어, 수업 끝나고 보여 드릴게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Jiho, our team has to plant a tree for Earth Day."],
        ["M", "I know. Where are we going to plant it?"],
        ["W", "The teacher said we can use the corner by the gate."],
        ["M", "That spot gets sun all afternoon, doesn't it?"],
        ["W", "Yes, and the ground there is soft enough to dig."],
        ["M", "Good. Do we have a shovel for the four of us?"],
        ["W", "Only one, and it belongs to the science room."],
        ["M", "One shovel will take us all afternoon."],
        ["W", "Then where can we borrow two more?"],
        ["M", "The gardening club keeps some in their storage room."],
      ],
      choices: [
        "We don't need any shovels.",
        "Let's plant the tree next year.",
        "Then I'll ask the gardening club today.",
        "The corner has no sunlight at all.",
        "I'll return the shovel tomorrow.",
      ],
      answer: 3,
      clue: "The gardening club keeps some in their storage room.",
      explanation:
        "남자가 원예 동아리 창고에 삽이 있다고 했으므로, 오늘 그 동아리에 부탁해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 지호야, 우리 조는 지구의 날에 나무를 심어야 해.",
        "M: 알아. 어디에 심을 거야?",
        "W: 선생님이 정문 옆 모퉁이를 써도 된대.",
        "M: 거기는 오후 내내 해가 들지?",
        "W: 응, 그리고 땅도 파기 좋을 만큼 부드러워.",
        "M: 좋아. 우리 넷이 쓸 삽은 있어?",
        "W: 하나뿐이야. 그것도 과학실 거야.",
        "M: 삽 하나로는 오후 내내 걸리겠다.",
        "W: 그럼 두 개를 어디서 빌리지?",
        "M: 원예 동아리 창고에 몇 개 있어.",
        "W: 그럼 오늘 원예 동아리에 물어볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Haeun이 Sangmin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Haeun : ________________",
      lines: [
        [
          "M",
          "Haeun and Sangmin are waiting for the school bus together. " +
            "The bus will arrive in about two minutes at the stop. " +
            "Sangmin takes out his earphones and puts them in his ears. " +
            "Haeun then sees that Sangmin's wallet has fallen out of his pocket. " +
            "It is lying on the ground right behind him. " +
            "In this situation, what would Haeun most likely say to Sangmin?",
        ],
      ],
      choices: [
        "Your wallet is on the ground.",
        "The bus already left the stop.",
        "Can I listen to your music?",
        "I'll buy you a new wallet.",
        "Let's walk to school today.",
      ],
      answer: 1,
      clue: "Haeun then sees that Sangmin's wallet has fallen out of his pocket.",
      explanation:
        "상민이의 지갑이 주머니에서 떨어져 바닥에 있으므로, 그 사실을 알려 주는 ①이 가장 적절하다.",
      translation: [
        "M: 하은이와 상민이는 함께 학교 버스를 기다리고 있습니다. 버스는 2분쯤 뒤에 정류장에 도착합니다. 상민이는 이어폰을 꺼내 귀에 꽂습니다. 그때 하은이는 상민이의 지갑이 주머니에서 떨어진 것을 봅니다. 지갑은 상민이 바로 뒤 바닥에 놓여 있습니다. 이런 상황에서 하은이가 상민이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
