/** 중1 듣기 33회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 33회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 컵을 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a cup?"],
        ["W", "Yes, one I can put in my school bag."],
        ["M", "Then a handle may catch on your books."],
        ["W", "You're right. I'll skip the handle."],
        ["M", "Do you want a lid? Bags get wet easily."],
        ["W", "Yes, a lid is a must for me."],
        ["M", "This lid has a hole for a straw."],
        ["W", "No straw hole, please. I'll take the closed lid."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "You're right. I'll skip the handle. / No straw hole, please.",
      explanation:
        "여자는 손잡이가 없고 뚜껑은 있으며, 빨대 구멍은 없는 컵을 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five drinking cups standing side by side as five choices, clean black line art on white. " +
          "① a cup WITH a side handle and NO lid, open on top. " +
          "② a cup with NO handle and a CLOSED lid on top. " +
          "③ a cup WITH a side handle and a CLOSED lid on top. " +
          "④ a cup with NO handle and NO lid, open on top. " +
          "⑤ a cup WITH a side handle and a lid that has a round STRAW HOLE with a straw in it.",
      },
      translation: [
        "M: 어서 오세요. 컵 찾으세요?",
        "W: 네, 학교 가방에 넣을 수 있는 걸로요.",
        "M: 그러면 손잡이가 책에 걸릴 수 있어요.",
        "W: 그렇네요. 손잡이는 빼야겠어요.",
        "M: 뚜껑은 어떠세요? 가방이 잘 젖거든요.",
        "W: 네, 뚜껑은 꼭 있어야 해요.",
        "M: 이 뚜껑은 빨대 구멍이 있어요.",
        "W: 빨대 구멍은 없는 걸로요. 막힌 뚜껑으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 합창 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hyeri, our class is entering the singing contest."],
        ["W", "Great. When is it held?"],
        ["M", "On the last Friday of this month."],
        ["W", "Where do we perform?"],
        ["M", "In the school auditorium on the third floor."],
        ["W", "How does our class sign up?"],
        ["M", "The class president writes our class name on the form."],
        ["W", "How many songs do we sing?"],
        ["M", "Two songs, and one of them must be in English."],
      ],
      choices: [
        "대회가 열리는 날",
        "공연하는 장소",
        "참가 신청 방법",
        "부르는 곡의 수",
        "점수를 매기는 기준",
      ],
      answer: 5,
      clue: "On the last Friday of this month. / Two songs, and one of them must be in English.",
      explanation:
        "날짜, 장소, 신청 방법, 곡의 수는 말했지만 점수 기준은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 혜리야, 우리 반이 합창 대회에 나가.",
        "W: 좋다. 언제 열려?",
        "M: 이번 달 마지막 금요일에.",
        "W: 어디서 공연해?",
        "M: 3층 강당에서.",
        "W: 우리 반은 어떻게 신청해?",
        "M: 반장이 신청서에 반 이름을 적어.",
        "W: 몇 곡 불러?",
        "M: 두 곡. 그중 한 곡은 영어여야 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Jaemin. It's Sohee. Are we still meeting today?"],
        ["M", "Yes, at the café in front of the station, right?"],
        ["W", "That's why I'm calling. The café is closed today."],
        ["M", "Oh, really?"],
        ["W", "Let's meet at the library reading room instead."],
        ["M", "Got it. Same time, four o'clock?"],
        ["W", "Yes, same time. See you there."],
      ],
      choices: [
        "숙제를 빌리려고",
        "병문안을 가려고",
        "물건을 돌려주려고",
        "만날 장소를 바꾸려고",
        "생일 선물을 물어보려고",
      ],
      answer: 4,
      clue: "Let's meet at the library reading room instead.",
      explanation:
        "카페가 문을 닫아서 만날 장소를 도서관으로 바꾸려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 재민아. 소희야. 오늘 만나는 거 맞지?",
        "M: 응, 역 앞 카페에서 맞지?",
        "W: 그것 때문에 전화했어. 오늘 그 카페 문 닫았대.",
        "M: 아, 정말?",
        "W: 대신 도서관 열람실에서 만나자.",
        "M: 알겠어. 시간은 그대로 4시?",
        "W: 응, 시간은 그대로. 거기서 보자.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Hyunwoo, what time does the movie start?"],
        ["M", "The evening show begins at five."],
        ["W", "Should we buy the tickets before that?"],
        ["M", "Yes, the line gets long on Saturdays."],
        ["W", "How early should we get there?"],
        ["M", "One hour before the show is safe."],
        ["W", "So we meet at four in front of the theater."],
        ["M", "Right, four o'clock at the ticket window."],
        ["W", "Okay, I'll be there on time."],
      ],
      choices: ["4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "5:30 p.m.", "6:00 p.m."],
      answer: 1,
      clue: "So we meet at four in front of the theater.",
      explanation:
        "영화는 5시에 시작하고 한 시간 전에 만나기로 했으므로 4시이다. 따라서 답은 ①이다.",
      translation: [
        "W: 현우야, 영화 몇 시에 시작해?",
        "M: 저녁 상영은 5시에 시작해.",
        "W: 그 전에 표를 사야 할까?",
        "M: 응, 토요일에는 줄이 길어져.",
        "W: 얼마나 일찍 가야 해?",
        "M: 상영 한 시간 전이면 안전해.",
        "W: 그럼 4시에 극장 앞에서 만나는 거네.",
        "M: 맞아, 4시에 매표소에서.",
        "W: 알겠어, 시간 맞춰 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sunwoo, you keep looking at your phone during break time."],
        ["M", "My dog stopped eating his food two days ago."],
        ["W", "Did you take him to the animal hospital near your house?"],
        ["M", "My mom took him there early this morning."],
        ["W", "Have the doctors told you anything about him yet?"],
        ["M", "Not yet. They are still running some tests on him."],
        ["W", "He has always been healthy, so I'm sure he will be fine."],
        ["M", "I hope so, but I can't stop thinking about him."],
      ],
      choices: ["proud", "curious", "worried", "happy", "thankful"],
      answer: 3,
      clue: "I can't stop thinking about him.",
      explanation:
        "강아지가 아파 병원에 있고 결과를 기다리며 계속 생각난다고 했으므로 걱정하는 심정이다. 따라서 답은 ③이다.",
      translation: [
        "W: 선우야, 계속 휴대전화만 보고 있네.",
        "M: 우리 강아지가 이틀째 밥을 안 먹어.",
        "W: 동물병원에 데려갔어?",
        "M: 오늘 아침에 엄마가 데려가셨어.",
        "W: 아직 얘기 들은 거 있어?",
        "M: 아직. 검사하고 있대.",
        "W: 분명 괜찮을 거야.",
        "M: 계속 생각이 나서 어쩔 수가 없어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Where can I buy a ticket?"],
        ["M", "At the machine over there."],
        ["ANN", "Number two."],
        ["W", "Please take my seat."],
        ["M", "Thank you, young lady."],
        ["ANN", "Number three."],
        ["W", "Does this bus go to city hall?"],
        ["M", "Yes, three more stops."],
        ["ANN", "Number four."],
        ["W", "May I open the window?"],
        ["M", "Sure, go ahead."],
        ["ANN", "Number five."],
        ["W", "What is the next stop?"],
        ["M", "It's the market."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Please take my seat.",
      explanation:
        "그림은 버스 안에서 여학생이 일어나 할아버지께 자리를 양보하는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a city bus, clean black line art on a plain white background, no writing anywhere. " +
          "A schoolgirl with a backpack has stood up from her seat and gestures toward the empty seat with an open hand. " +
          "An old man holding a walking stick stands in front of her and smiles as he bows slightly. " +
          "Other passengers sit quietly and hand rails hang from the ceiling.",
      },
      translation: [
        "① W: 표는 어디서 사요? / M: 저기 기계에서요.",
        "② W: 여기 앉으세요. / M: 고마워요, 학생.",
        "③ W: 이 버스 시청 가요? / M: 네, 세 정거장 더 가요.",
        "④ W: 창문 열어도 될까요? / M: 그럼요, 여세요.",
        "⑤ W: 다음 정거장이 어디예요? / M: 시장이에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dayeon, are you going to the classroom now?"],
        ["W", "Yes, I left my water bottle there."],
        ["M", "I have to carry these books to the office."],
        ["W", "Do you need a hand?"],
        ["M", "No, but the board is still full from last class."],
        ["W", "Do you want me to clean it?"],
        ["M", "Yes, please wipe the board before the bell rings."],
        ["W", "No problem. I'll do it right away."],
      ],
      choices: [
        "칠판을 지워 주기",
        "창문을 닫아 주기",
        "책상을 옮겨 주기",
        "쓰레기를 버려 주기",
        "출석부를 가져다주기",
      ],
      answer: 1,
      clue: "Yes, please wipe the board before the bell rings.",
      explanation:
        "남자는 종이 치기 전에 칠판을 지워 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 다연아, 지금 교실 가?",
        "W: 응, 물병을 거기 두고 왔어.",
        "M: 나는 이 책들을 교무실에 갖다 놔야 해.",
        "W: 도와줄까?",
        "M: 아니, 그런데 칠판이 지난 시간 그대로야.",
        "W: 내가 지워 줄까?",
        "M: 응, 종 치기 전에 칠판 좀 지워 줘.",
        "W: 그럴게. 바로 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 텃밭 동아리에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, everyone. Let me tell you about our garden club. " +
            "We meet every Wednesday after the sixth period. " +
            "Our garden is behind the gym, next to the bicycle rack. " +
            "We water the plants, pull weeds and pick vegetables. " +
            "Please bring a pair of gloves and an old shirt.",
        ],
      ],
      choices: [
        "모이는 요일",
        "텃밭의 위치",
        "동아리에서 하는 일",
        "가져올 준비물",
        "동아리 회원 수",
      ],
      answer: 5,
      clue: "We meet every Wednesday after the sixth period.",
      explanation:
        "요일, 위치, 하는 일, 준비물은 말했지만 회원 수는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여러분, 안녕하세요. 텃밭 동아리를 소개하겠습니다. 우리는 매주 수요일 6교시가 끝난 뒤에 모입니다. 텃밭은 체육관 뒤, 자전거 보관대 옆에 있습니다. 우리는 물을 주고, 잡초를 뽑고, 채소를 땁니다. 장갑 한 켤레와 낡은 셔츠를 가져오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is small and round, and it fits in your hand. " +
            "Inside it there is a thin needle that can turn freely. " +
            "The needle always points to the north, wherever you stand. " +
            "Hikers take it with them when they walk in the mountains. " +
            "With it you can find your way even without a road sign.",
        ],
      ],
      choices: ["시계", "지도", "사전", "나침반", "달력"],
      answer: 4,
      clue: "The needle always points to the north, wherever you stand.",
      explanation:
        "손에 들어오는 작고 둥근 것으로, 바늘이 항상 북쪽을 가리켜 산에서 길을 찾게 해 주는 것은 나침반이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이것은 작고 둥글며 손안에 들어옵니다. 안에는 자유롭게 돌아가는 가느다란 바늘이 있습니다. 그 바늘은 어디에 서 있든 항상 북쪽을 가리킵니다. 등산하는 사람들은 산에 갈 때 이것을 가져갑니다. 이것이 있으면 표지판이 없어도 길을 찾을 수 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was your weekend?"],
        ["W", "It was quiet and nice."],
        ["ANN", "Number two."],
        ["M", "How much is this notebook?"],
        ["W", "I bought it last Friday."],
        ["ANN", "Number three."],
        ["M", "Can I borrow your eraser?"],
        ["W", "Sure, here it is."],
        ["ANN", "Number four."],
        ["M", "Where are you going now?"],
        ["W", "To the music room."],
        ["ANN", "Number five."],
        ["M", "Thank you for your help."],
        ["W", "You're welcome."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "How much is this notebook?",
      explanation:
        "공책 값을 묻는 말에 지난 금요일에 샀다고 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① M: 주말 어땠어? / W: 조용하고 좋았어.",
        "② M: 이 공책 얼마야? / W: 지난 금요일에 샀어.",
        "③ M: 지우개 빌려줄래? / W: 그럼, 여기 있어.",
        "④ M: 지금 어디 가? / W: 음악실에.",
        "⑤ M: 도와줘서 고마워. / W: 천만에.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeun, your face looks pale today."],
        ["W", "My stomach has hurt since this morning."],
        ["M", "Did you eat anything strange yesterday?"],
        ["W", "I had cold noodles late at night."],
        ["M", "You should not walk around like this."],
        ["W", "I have math class in ten minutes."],
        ["M", "Go to the nurse's office first. I'll tell the teacher."],
        ["W", "Thanks. I'll go there now."],
      ],
      choices: [
        "도서관에 가기",
        "점심을 먹기",
        "보건실에 가기",
        "체육관에 가기",
        "집으로 돌아가기",
      ],
      answer: 3,
      clue: "Go to the nurse's office first. I'll tell the teacher.",
      explanation:
        "남자가 먼저 보건실에 가라고 했고 여자는 지금 가겠다고 답했다. 따라서 답은 ③이다.",
      translation: [
        "M: 채은아, 오늘 얼굴이 창백해 보여.",
        "W: 아침부터 배가 아파.",
        "M: 어제 이상한 거 먹었어?",
        "W: 밤늦게 냉면을 먹었어.",
        "M: 이런 상태로 돌아다니면 안 돼.",
        "W: 10분 뒤에 수학 수업이야.",
        "M: 보건실부터 가. 선생님께는 내가 말씀드릴게.",
        "W: 고마워. 지금 갈게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 여행 가방을 고르시오.",
      lines: [
        ["W", "Taeho, which suitcase are you taking on the trip?"],
        ["M", "Let's look at the list on the screen."],
        ["W", "Do you want wheels or not?"],
        ["M", "Wheels, definitely. I walk a lot at the airport."],
        ["W", "All right. What is your budget?"],
        ["M", "Eighty thousand won at the most."],
        ["W", "Any color you want to avoid?"],
        ["M", "Gray ones all look the same on the belt."],
        ["W", "Then only one suitcase here is right for you."],
        ["M", "Good. I'll order it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Wheels, definitely. I walk a lot at the airport.",
      explanation:
        "바퀴가 있고, 8만 원 이하이며, 회색이 아닌 것을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Wheels: Yes / Price: 75,000 won / Color: Red" },
          { no: 2, label: "②", value: "Wheels: Yes / Price: 92,000 won / Color: Red" },
          { no: 3, label: "③", value: "Wheels: No / Price: 60,000 won / Color: Blue" },
          { no: 4, label: "④", value: "Wheels: Yes / Price: 78,000 won / Color: Gray" },
          { no: 5, label: "⑤", value: "Wheels: No / Price: 85,000 won / Color: Gray" },
        ],
      },
      translation: [
        "W: 태호야, 여행에 어떤 가방 가져갈 거야?",
        "M: 화면에 있는 목록 보자.",
        "W: 바퀴 있는 걸로 할래, 없는 걸로 할래?",
        "M: 당연히 바퀴. 공항에서 많이 걸어.",
        "W: 알겠어. 예산은 얼마야?",
        "M: 최대 8만 원.",
        "W: 피하고 싶은 색 있어?",
        "M: 회색은 수하물 벨트에서 다 똑같아 보여.",
        "W: 그럼 여기서 맞는 건 하나뿐이네.",
        "M: 좋아. 오늘 밤에 주문할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 발표를 하기로 한 날짜를 고르시오.",
      lines: [
        ["W", "Minho, when should we give our history presentation?"],
        ["M", "The teacher gave us three choices this month."],
        ["W", "Which days are they?"],
        ["M", "The eighth, the fifteenth and the twenty-second."],
        ["W", "The eighth is too soon. We haven't made the slides."],
        ["M", "And I have a dentist appointment on the fifteenth."],
        ["W", "Then the twenty-second is the only day left."],
        ["M", "That gives us three weeks to practice."],
        ["W", "Let's tell the teacher tomorrow morning."],
      ],
      choices: [
        "the 1st",
        "the 8th",
        "the 15th",
        "the 20th",
        "the 22nd",
      ],
      answer: 5,
      clue: "Then the twenty-second is the only day left.",
      explanation:
        "8일은 준비가 안 됐고 15일은 치과 예약이 있어서 22일로 정했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민호야, 역사 발표 언제 하는 게 좋을까?",
        "M: 선생님이 이번 달에 세 날짜를 주셨어.",
        "W: 어떤 날들이야?",
        "M: 8일, 15일, 22일.",
        "W: 8일은 너무 이르다. 자료도 못 만들었어.",
        "M: 그리고 15일에는 치과 예약이 있어.",
        "W: 그럼 남는 건 22일뿐이네.",
        "M: 연습할 시간이 3주 생기네.",
        "W: 내일 아침에 선생님께 말씀드리자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiwoo, did you get enough rest over the weekend?"],
        ["M", "Not really. I painted my whole room on Saturday."],
        ["W", "All by yourself? That sounds like a really big job."],
        ["M", "My brother helped me move the bed and the desk out."],
        ["W", "What color did you finally choose for the walls?"],
        ["M", "Light green. The room feels much wider and brighter now."],
        ["W", "How long did the painting take you in the end?"],
        ["M", "Almost six hours, and my arms still hurt this morning."],
      ],
      choices: [
        "영화를 보러 가기",
        "축구 경기를 하기",
        "친척 집을 방문하기",
        "방에 페인트를 칠하기",
        "도서관에서 책을 읽기",
      ],
      answer: 4,
      clue: "Not really. I painted my room on Saturday.",
      explanation:
        "남자는 토요일에 형과 함께 방에 페인트를 칠했다고 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 지우야, 주말에 잘 쉬었어?",
        "M: 그렇지도 않아. 토요일에 내 방에 페인트를 칠했어.",
        "W: 혼자서? 큰일이었겠다.",
        "M: 형이 침대랑 책상 옮기는 걸 도와줬어.",
        "W: 무슨 색으로 했어?",
        "M: 연두색. 방이 더 넓어 보여.",
        "W: 얼마나 걸렸어?",
        "M: 거의 여섯 시간. 아직도 팔이 아파.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, please. This is an announcement from the library front desk. " +
            "The library will close in twenty minutes today, earlier than usual. " +
            "Please bring the books you want to borrow to the front desk right now. " +
            "Return the books you have finished reading to the cart by the window. " +
            "Do not leave any books on the tables or on the floor. " +
            "The reading room will open again tomorrow morning at nine o'clock.",
        ],
      ],
      choices: [
        "행사 시작을 알리려고",
        "책 반납을 독촉하려고",
        "문 닫는 시간을 알리려고",
        "새로 온 책을 소개하려고",
        "조용히 해 달라고 부탁하려고",
      ],
      answer: 3,
      clue: "The library will close in twenty minutes today.",
      explanation:
        "20분 뒤에 도서관 문을 닫는다고 알리는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안내 말씀 드립니다. 도서관 안내 데스크입니다. 오늘 도서관은 20분 뒤에 문을 닫습니다. 빌릴 책은 지금 데스크로 가져와 주세요. 읽으신 책은 창가에 있는 수레에 놓아 주세요. 열람실은 내일 아홉 시에 다시 엽니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Good morning. What would you like to order today?"],
        ["W", "Two chicken sandwiches, please. How much are they?"],
        ["M", "Each sandwich is seven dollars this week."],
        ["W", "I'll also take one bottle of orange juice."],
        ["M", "The juice is four dollars a bottle."],
        ["W", "Do you have any discount going on today?"],
        ["M", "Yes, we take four dollars off any order over ten dollars."],
        ["W", "That's good news. Here is my card, then."],
      ],
      choices: ["$10", "$14", "$18", "$22", "$25"],
      answer: 2,
      clue: "Each sandwich is seven dollars. / we take four dollars off orders over ten dollars.",
      explanation:
        "샌드위치 두 개 14달러에 주스 4달러를 더하면 18달러이고, 4달러를 빼면 14달러이다. 따라서 답은 ②이다.",
      translation: [
        "M: 안녕하세요. 무엇을 드릴까요?",
        "W: 샌드위치 두 개 주세요. 얼마예요?",
        "M: 샌드위치는 하나에 7달러예요.",
        "W: 주스도 한 병 살게요.",
        "M: 주스는 4달러예요.",
        "W: 오늘 할인 있나요?",
        "M: 네, 10달러 넘게 사시면 4달러 빼 드려요.",
        "W: 잘됐네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, you brought your lunch again today."],
        ["W", "I started making it myself last month."],
        ["M", "Isn't that hard before school?"],
        ["W", "I get up twenty minutes earlier, that's all."],
        ["M", "What do you usually put in it?"],
        ["W", "Rice, eggs and whatever vegetables we have."],
        ["M", "I always buy bread at the store and I'm hungry by noon."],
        ["W", "Bread alone won't last until lunch."],
        ["M", "Could you show me how you make yours?"],
      ],
      choices: [
        "Sure, come over on Saturday.",
        "I don't make my own lunch.",
        "The store is closed today.",
        "I'm never hungry at noon.",
        "You should skip breakfast.",
      ],
      answer: 1,
      clue: "Could you show me how you make yours?",
      explanation:
        "남자가 도시락 만드는 법을 보여 달라고 했으므로, 토요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 예린아, 오늘도 도시락 싸 왔네.",
        "W: 지난달부터 내가 직접 싸기 시작했어.",
        "M: 학교 가기 전에 힘들지 않아?",
        "W: 20분 일찍 일어나면 돼, 그뿐이야.",
        "M: 보통 뭘 넣어?",
        "W: 밥, 달걀, 집에 있는 채소 아무거나.",
        "M: 나는 늘 가게에서 빵을 사는데 점심때쯤이면 배가 고파.",
        "W: 빵만으로는 점심까지 못 버텨.",
        "M: 네가 어떻게 싸는지 보여 줄 수 있어?",
        "W: 그럼, 토요일에 우리 집에 와.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hanbin, are you still collecting stamps?"],
        ["M", "Yes, I have about three hundred now."],
        ["W", "Three hundred? Where do you keep them?"],
        ["M", "In two thick albums under my desk."],
        ["W", "How do you find new ones?"],
        ["M", "My uncle sends me letters from other countries."],
        ["W", "That's a nice way to get them."],
        ["M", "The problem is that my albums are full."],
        ["W", "The stationery store near school sells empty albums."],
      ],
      choices: [
        "I stopped collecting stamps.",
        "My uncle lives next door.",
        "I have only three stamps.",
        "The store sells only pens.",
        "Then I'll go there after school.",
      ],
      answer: 5,
      clue: "The stationery store near school sells empty albums.",
      explanation:
        "여자가 학교 근처 문구점에서 빈 앨범을 판다고 했으므로, 방과 후에 가 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 한빈아, 아직도 우표 모아?",
        "M: 응, 지금 300장쯤 돼.",
        "W: 300장? 어디에 보관해?",
        "M: 책상 밑 두꺼운 앨범 두 권에.",
        "W: 새 우표는 어떻게 구해?",
        "M: 삼촌이 다른 나라에서 편지를 보내 주셔.",
        "W: 그렇게 모으는 것도 좋다.",
        "M: 문제는 앨범이 다 찼다는 거야.",
        "W: 학교 근처 문구점에서 빈 앨범을 팔아.",
        "M: 그럼 방과 후에 거기 가 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Seoyeon, did you finish the science poster?"],
        ["W", "Almost. I still need photos of plants."],
        ["M", "Did you look for them on the internet?"],
        ["W", "I did, but the teacher wants our own photos."],
        ["M", "Then take some in the school garden."],
        ["W", "My phone camera is broken."],
        ["M", "My sister has a small camera she never uses."],
        ["W", "Do you think she would lend it to me?"],
        ["M", "Ask her at the bus stop tomorrow morning."],
      ],
      choices: [
        "I already took the photos.",
        "My phone works well now.",
        "The poster is due next month.",
        "All right, I'll talk to her then.",
        "She should use the camera herself.",
      ],
      answer: 4,
      clue: "Ask her at the bus stop tomorrow morning.",
      explanation:
        "남자가 내일 아침 버스 정류장에서 누나에게 물어보라고 했으므로, 그때 말해 보겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 서연아, 과학 포스터 다 했어?",
        "W: 거의. 식물 사진이 아직 필요해.",
        "M: 인터넷에서 찾아봤어?",
        "W: 찾아봤는데 선생님이 직접 찍은 사진을 원하셔.",
        "M: 그럼 학교 화단에서 찍어.",
        "W: 내 휴대전화 카메라가 고장 났어.",
        "M: 우리 누나가 안 쓰는 작은 카메라가 있어.",
        "W: 누나가 빌려줄까?",
        "M: 내일 아침 버스 정류장에서 물어봐.",
        "W: 알겠어, 그때 말해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jina가 Sehun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jina : ________________",
      lines: [
        [
          "M",
          "Jina and Sehun are working on a group poster in the art room. " +
            "Sehun opens a bottle of glue and puts it down near the edge of the desk. " +
            "Jina sees that the open bottle is about to fall onto Sehun's bag. " +
            "If it spills, the glue will ruin his books inside the bag. " +
            "She wants to warn him before he moves his arm again. " +
            "In this situation, what would Jina most likely say to Sehun?",
        ],
      ],
      choices: [
        "Can I borrow your glue?",
        "Let's finish the poster tomorrow.",
        "Watch out, the glue is falling.",
        "Your bag is very heavy.",
        "I need more colored paper.",
      ],
      answer: 3,
      clue: "She wants to warn him before he moves his arm again.",
      explanation:
        "열린 풀이 가방 위로 떨어지려 하므로, 조심하라고 알려 주는 ③이 가장 적절하다.",
      translation: [
        "M: 지나와 세훈이는 미술실에서 모둠 포스터를 만들고 있습니다. 세훈이가 풀 뚜껑을 열고 책상 끝 가까이에 내려놓습니다. 지나는 열린 풀통이 세훈이의 가방 위로 떨어지려는 것을 봅니다. 쏟아지면 가방 안 책들이 못 쓰게 됩니다. 지나는 세훈이가 팔을 다시 움직이기 전에 알려 주고 싶습니다. 이런 상황에서 지나가 세훈이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
