/** 중1 듣기 45회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 45회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 시계를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a wall clock?"],
        ["M", "Yes, one for my study room."],
        ["W", "Do you want a round one or a square one?"],
        ["M", "A round one. It looks softer on the wall."],
        ["W", "This round clock has numbers on the face."],
        ["M", "Numbers, yes. Lines are hard to read at night."],
        ["W", "Would you like a small bell on top?"],
        ["M", "No bell. My sister sleeps in the next room."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "A round one. It looks softer on the wall. / Numbers, yes. Lines are hard to read at night.",
      explanation:
        "남자는 둥글고 숫자가 있으며 종이 없는 시계를 골랐다. 따라서 답은 ①이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five wall clocks side by side as five choices, clean black line art on white, no writing anywhere. " +
          "① a ROUND clock face with clear NUMBER marks around it and no bell. " +
          "② a ROUND clock face with only short LINE marks and no bell. " +
          "③ a ROUND clock face with NUMBER marks and a small BELL on top. " +
          "④ a SQUARE clock face with NUMBER marks and no bell. " +
          "⑤ a SQUARE clock face with LINE marks and a small BELL on top.",
      },
      translation: [
        "W: 안녕하세요. 벽시계 찾으세요?",
        "M: 네, 제 공부방에 걸 거예요.",
        "W: 둥근 게 좋으세요, 네모난 게 좋으세요?",
        "M: 둥근 걸로요. 벽에 걸면 더 부드러워 보여요.",
        "W: 이 둥근 시계는 문자판에 숫자가 있어요.",
        "M: 숫자요. 선만 있으면 밤에 읽기 어려워요.",
        "W: 위에 작은 종이 달린 건 어떠세요?",
        "M: 종은 빼 주세요. 옆방에서 동생이 자요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 독서 주간에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Taemin, when does the reading week start?"],
        ["M", "Next Monday, and it runs for five days."],
        ["W", "Where do we read during that week?"],
        ["M", "In the library, or in our own classroom."],
        ["W", "How much do we have to read each day?"],
        ["M", "Twenty pages, and you write the title down."],
        ["W", "Do we write anything else?"],
        ["M", "One sentence about what you liked."],
        ["W", "That's easier than a whole report."],
      ],
      choices: [
        "독서 주간이 시작하는 날",
        "책을 읽는 곳",
        "하루에 읽을 분량",
        "적어야 하는 것",
        "책을 빌리는 방법",
      ],
      answer: 5,
      clue: "Next Monday, and it runs for five days.",
      explanation:
        "시작일, 장소, 분량, 적을 것은 말했지만 책 빌리는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 태민아, 독서 주간 언제 시작해?",
        "M: 다음 주 월요일. 닷새 동안 해.",
        "W: 그 주에는 어디서 읽어?",
        "M: 도서관에서, 아니면 우리 교실에서.",
        "W: 하루에 얼마나 읽어야 해?",
        "M: 스무 쪽. 그리고 제목을 적어.",
        "W: 그 밖에 적을 것도 있어?",
        "M: 마음에 든 점을 한 문장으로.",
        "W: 독후감 쓰는 것보다 쉽네.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junho. It's Nari. Are you at home?"],
        ["M", "Yes, I just got back from the library."],
        ["W", "I heard you have the class camera this week."],
        ["M", "It's in my bag until Friday."],
        ["W", "Our group is making a poster tomorrow."],
        ["M", "Do you need photos of the steps?"],
        ["W", "The teacher asked for pictures of each one."],
        ["M", "So you need the camera in the morning."],
        ["W", "Could you bring the camera tomorrow?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "물건을 가져와 달라고 하려고",
        "약속을 미루려고",
        "생일을 축하하려고",
        "길을 물어보려고",
      ],
      answer: 2,
      clue: "Could you bring the camera tomorrow?",
      explanation:
        "여자는 내일 사진기를 가져와 달라고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준호야. 나리야. 집이야?",
        "M: 응, 방금 도서관에서 왔어.",
        "W: 이번 주에 네가 학급 사진기 가지고 있다며.",
        "M: 금요일까지 내 가방에 있어.",
        "W: 우리 모둠이 내일 포스터를 만들어.",
        "M: 단계마다 사진이 필요해?",
        "W: 선생님이 각 단계 사진을 찍어 오라고 하셨어.",
        "M: 그럼 아침에 사진기가 있어야겠네.",
        "W: 내일 사진기 좀 가져올래?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Chaewon, when does the swimming class start?"],
        ["W", "The pool opens at five o'clock."],
        ["M", "How long does it take to change?"],
        ["W", "About ten minutes, with the locker."],
        ["M", "Then we should be there by four fifty."],
        ["W", "My tutoring ends at four thirty."],
        ["M", "And the pool is fifteen minutes away."],
        ["W", "So four fifty is just right for me."],
        ["M", "Let's meet at four fifty at the front door."],
        ["W", "Four fifty. I'll bring the towels."],
      ],
      choices: ["4:30 p.m.", "4:40 p.m.", "4:50 p.m.", "5:00 p.m.", "5:10 p.m."],
      answer: 3,
      clue: "Let's meet at four fifty at the front door.",
      explanation:
        "옷 갈아입는 시간과 이동 시간을 생각해 4시 50분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 채원아, 수영 수업 몇 시에 시작해?",
        "W: 수영장이 다섯 시에 열어.",
        "M: 옷 갈아입는 데 얼마나 걸려?",
        "W: 사물함까지 하면 10분쯤.",
        "M: 그럼 4시 50분까지는 가 있어야겠다.",
        "W: 내 과외가 4시 30분에 끝나.",
        "M: 수영장은 15분 거리고.",
        "W: 그럼 4시 50분이 딱 맞아.",
        "M: 4시 50분에 정문에서 만나자.",
        "W: 4시 50분. 수건은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kiyoung, is that your name up on the board?"],
        ["M", "I read it three times to be sure."],
        ["W", "You won the school drawing contest this year."],
        ["M", "Eighty students sent in a picture."],
        ["W", "That is the most they have ever had."],
        ["M", "And half of them were in our grade."],
        ["W", "But yours was chosen first of all."],
        ["M", "I worked on it for three weekends."],
        ["W", "Are you going to tell your family?"],
        ["M", "I'm calling my mother right after this."],
      ],
      choices: ["delighted", "angry", "bored", "sorry", "scared"],
      answer: 1,
      clue: "I'm calling my mother right after this.",
      explanation:
        "그림 대회에서 1등을 해 무척 기뻐하고 있다. 따라서 답은 ①이다.",
      translation: [
        "W: 기영아, 게시판에 붙은 게 네 이름이야?",
        "M: 확실히 하려고 세 번 읽었어.",
        "W: 올해 학교 그림 대회에서 1등 했네.",
        "M: 여든 명이 그림을 냈어.",
        "W: 지금까지 중에 제일 많은 거야.",
        "M: 그중 절반이 우리 학년이었어.",
        "W: 그런데 네 것이 제일 먼저 뽑혔잖아.",
        "M: 주말 세 번을 꼬박 그렸어.",
        "W: 가족한테 알릴 거야?",
        "M: 이거 끝나고 바로 엄마한테 전화할 거야.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I borrow this book?"],
        ["M", "Yes, for two weeks."],
        ["ANN", "Number two."],
        ["W", "Where is the science section?"],
        ["M", "On the second floor."],
        ["ANN", "Number three."],
        ["W", "Do you have a pen I can use?"],
        ["M", "Here, take this one."],
        ["ANN", "Number four."],
        ["W", "This book is too high for me."],
        ["M", "I'll get it down for you."],
        ["ANN", "Number five."],
        ["W", "When does the library close?"],
        ["M", "At six on weekdays."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "This book is too high for me.",
      explanation:
        "그림은 도서관에서 높은 칸의 책을 남학생이 대신 꺼내 주는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a school library, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A short girl student stands in front of a tall bookshelf, stretching one arm up toward a book on the top shelf but not reaching it. " +
          "A taller boy student beside her reaches up easily and takes the book down with one hand. " +
          "Rows of shelves and a reading table are drawn simply behind them.",
      },
      translation: [
        "① W: 이 책 빌릴 수 있나요? / M: 네, 두 주 동안요.",
        "② W: 과학 책은 어디 있어요? / M: 2층에 있어요.",
        "③ W: 쓸 수 있는 펜 있어요? / M: 여기, 이거 쓰세요.",
        "④ W: 이 책이 너무 높아요. / M: 제가 꺼내 드릴게요.",
        "⑤ W: 도서관 몇 시에 닫아요? / M: 평일에는 여섯 시에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suyeon, do you go past the post office?"],
        ["W", "Every day, on my way home."],
        ["M", "I have a letter for my grandmother."],
        ["W", "Can't you send it yourself after school?"],
        ["M", "I have band practice until six today."],
        ["W", "And the post office closes at five."],
        ["M", "That's the problem, exactly."],
        ["W", "Is the stamp already on it?"],
        ["M", "Could you drop this letter in the post box?"],
        ["W", "Sure, the box is right by my stop."],
      ],
      choices: [
        "편지를 부쳐 주기",
        "우표를 사다 주기",
        "할머니께 전화하기",
        "연습을 도와주기",
        "함께 걸어가 주기",
      ],
      answer: 1,
      clue: "Could you drop this letter in the post box?",
      explanation:
        "남자는 편지를 우체통에 넣어 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 수연아, 우체국 지나가?",
        "W: 매일. 집에 가는 길에.",
        "M: 할머니께 보낼 편지가 있어.",
        "W: 방과 후에 직접 못 보내?",
        "M: 오늘 여섯 시까지 밴드 연습이 있어.",
        "W: 우체국은 다섯 시에 닫고.",
        "M: 그게 딱 문제야.",
        "W: 우표는 벌써 붙였어?",
        "M: 이 편지 우체통에 넣어 줄래?",
        "W: 그럼, 우리 정류장 바로 옆에 있어.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 벼룩시장에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, everyone. Our school flea market opens next month. " +
            "It runs on the first Saturday from ten to three. " +
            "We will set the tables up in the front yard. " +
            "Students may sell books, clothes and small toys. " +
            "All the money goes to the local children's center. " +
            "Bring your things to the gym on Friday afternoon.",
        ],
      ],
      choices: [
        "열리는 날과 시간",
        "장이 서는 곳",
        "팔 수 있는 물건",
        "모은 돈을 쓰는 곳",
        "물건에 값을 매기는 방법",
      ],
      answer: 5,
      clue: "It runs on the first Saturday from ten to three.",
      explanation:
        "날짜와 시간, 장소, 팔 물건, 수익 사용처는 말했지만 값을 매기는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여러분, 안녕하세요. 다음 달에 학교 벼룩시장이 열립니다. 첫째 주 토요일 열 시부터 세 시까지 합니다. 앞마당에 탁자를 놓습니다. 학생들은 책, 옷, 작은 장난감을 팔 수 있습니다. 모인 돈은 모두 지역 아동 센터로 보냅니다. 팔 물건은 금요일 오후에 체육관으로 가져오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You hold this in your hand when you write on the board. " +
            "It is white and soft, and it leaves dust on your fingers. " +
            "Teachers use it every day in the classroom. " +
            "It gets shorter and shorter as you write. " +
            "You wipe the board with an eraser afterwards.",
        ],
      ],
      choices: ["지우개", "연필", "자", "분필", "붓"],
      answer: 4,
      clue: "It is white and soft, and it leaves dust on your fingers.",
      explanation:
        "칠판에 쓸 때 손에 가루가 묻는 하얗고 무른 것은 분필이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이것은 칠판에 글씨를 쓸 때 손에 쥡니다. 하얗고 무르며 손가락에 가루가 묻습니다. 선생님들이 교실에서 매일 씁니다. 쓸수록 점점 짧아집니다. 다 쓰고 나면 지우개로 칠판을 지웁니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How old is your brother?"],
        ["M", "He turned ten last month."],
        ["ANN", "Number two."],
        ["W", "Do you want some juice?"],
        ["M", "Yes, please. I'm thirsty."],
        ["ANN", "Number three."],
        ["W", "Where did you buy that cap?"],
        ["M", "It takes twenty minutes."],
        ["ANN", "Number four."],
        ["W", "Can you help me move this?"],
        ["M", "Sure, take that side."],
        ["ANN", "Number five."],
        ["W", "What did you have for lunch?"],
        ["M", "Rice and soup, as usual."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Where did you buy that cap?",
      explanation:
        "모자를 어디서 샀는지 묻는 말에 걸리는 시간을 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① W: 동생이 몇 살이야? / M: 지난달에 열 살 됐어.",
        "② W: 주스 마실래? / M: 응, 좋아. 목말라.",
        "③ W: 그 모자 어디서 샀어? / M: 20분 걸려.",
        "④ W: 이거 옮기는 것 좀 도와줄래? / M: 그럼, 그쪽 잡아.",
        "⑤ W: 점심에 뭐 먹었어? / M: 늘 그렇듯 밥이랑 국.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayoon, the class photo is in ten minutes."],
        ["W", "I know. We line up by the stairs, right?"],
        ["M", "By the main stairs, in class order."],
        ["W", "Do we need anything special?"],
        ["M", "The teacher said to wear the jacket."],
        ["W", "My jacket is in my locker downstairs."],
        ["M", "You have just enough time to get it."],
        ["W", "I'll run down and get my jacket."],
      ],
      choices: [
        "계단 앞에 줄 서기",
        "사물함에서 재킷을 가져오기",
        "선생님께 여쭤보기",
        "교실을 청소하기",
        "사진기를 빌리기",
      ],
      answer: 2,
      clue: "I'll run down and get my jacket.",
      explanation:
        "여자는 사물함에서 재킷을 가져오겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 하윤아, 10분 뒤에 학급 사진 찍어.",
        "W: 알아. 계단 옆에 줄 서지?",
        "M: 중앙 계단 옆에, 반 순서대로.",
        "W: 따로 준비할 게 있어?",
        "M: 선생님이 재킷 입으라고 하셨어.",
        "W: 내 재킷은 아래층 사물함에 있어.",
        "M: 가져올 시간은 딱 돼.",
        "W: 뛰어가서 재킷 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 학급 티셔츠를 고르시오.",
      lines: [
        ["W", "Minjun, we need to pick the class T-shirt today."],
        ["M", "The shop sent us five choices."],
        ["W", "Our budget is eight thousand won each."],
        ["M", "Two of them cost more than that."],
        ["W", "And we agreed on a dark color."],
        ["M", "So the white one is out."],
        ["W", "The logo should be on the front, not the back."],
        ["M", "One of the rest prints only on the back."],
        ["W", "Then just one choice is left."],
        ["M", "I'll send the order form this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Our budget is eight thousand won each.",
      explanation:
        "8천 원 이하, 어두운 색, 앞면 인쇄인 것을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 10,000 won / Color: Navy / Print: Front" },
          { no: 2, label: "②", value: "Price: 9,000 won / Color: Black / Print: Front" },
          { no: 3, label: "③", value: "Price: 7,000 won / Color: White / Print: Front" },
          { no: 4, label: "④", value: "Price: 7,500 won / Color: Black / Print: Back" },
          { no: 5, label: "⑤", value: "Price: 8,000 won / Color: Navy / Print: Front" },
        ],
      },
      translation: [
        "W: 민준아, 오늘 학급 티셔츠를 정해야 해.",
        "M: 가게에서 다섯 가지를 보내 줬어.",
        "W: 우리 예산은 한 장에 8천 원이야.",
        "M: 두 개는 그보다 비싸.",
        "W: 그리고 어두운 색으로 하기로 했잖아.",
        "M: 그럼 흰색은 빠지네.",
        "W: 로고는 뒷면 말고 앞면에 찍혀야 해.",
        "M: 나머지 중 하나는 뒷면에만 찍어.",
        "W: 그럼 하나만 남네.",
        "M: 오늘 저녁에 주문서 보낼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 박물관에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Sihoon, when should we go to the museum?"],
        ["M", "The special show ends on the twentieth."],
        ["W", "So we have about two weeks."],
        ["M", "How about the eleventh, a Saturday?"],
        ["W", "I have a dentist appointment that morning."],
        ["M", "Then the twelfth, the day after?"],
        ["W", "The museum is closed on Sundays."],
        ["M", "So the thirteenth, Monday, after school."],
        ["W", "Monday works. We finish at three."],
        ["M", "Let's meet at the entrance on the thirteenth."],
      ],
      choices: ["the 11th", "the 12th", "the 13th", "the 20th", "the 9th"],
      answer: 3,
      clue: "So the thirteenth, Monday, after school.",
      explanation:
        "11일은 치과, 12일은 휴관이어서 13일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "W: 시훈아, 박물관 언제 갈까?",
        "M: 특별전이 20일에 끝나.",
        "W: 그럼 2주쯤 남았네.",
        "M: 11일 토요일은 어때?",
        "W: 그날 아침에 치과 예약이 있어.",
        "M: 그럼 다음 날 12일은?",
        "W: 박물관이 일요일에 문을 닫아.",
        "M: 그럼 13일 월요일 방과 후에.",
        "W: 월요일 괜찮아. 세 시에 끝나.",
        "M: 13일에 입구에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, what did you do on Sunday?"],
        ["W", "I went hiking with my father."],
        ["M", "Which mountain did you two climb?"],
        ["W", "The small one behind our neighborhood."],
        ["M", "How long did it take to the top?"],
        ["W", "Two hours up and one hour down."],
        ["M", "Was it crowded on a Sunday?"],
        ["W", "Very. We waited at two narrow spots."],
        ["M", "Would you go again next month?"],
        ["W", "Only if we start before seven."],
      ],
      choices: [
        "친구와 영화를 보기",
        "아버지와 등산을 하기",
        "집에서 쉬기",
        "도서관에서 공부하기",
        "친척 집에 가기",
      ],
      answer: 2,
      clue: "I went hiking with my father.",
      explanation:
        "여자는 일요일에 아버지와 등산을 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 서연아, 일요일에 뭐 했어?",
        "W: 아버지랑 등산 갔어.",
        "M: 어느 산에 올라갔어?",
        "W: 우리 동네 뒤에 있는 작은 산.",
        "M: 정상까지 얼마나 걸렸어?",
        "W: 올라가는 데 두 시간, 내려오는 데 한 시간.",
        "M: 일요일이라 붐볐어?",
        "W: 아주. 좁은 데 두 군데서 기다렸어.",
        "M: 다음 달에 또 갈 거야?",
        "W: 일곱 시 전에 출발한다면.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the student council. " +
            "We are collecting used books for the village center. " +
            "The center opened a small reading room last month. " +
            "Bring books you no longer read to the front hall. " +
            "Children's books and novels are especially welcome. " +
            "The collection box stays there until next Friday. " +
            "Please make sure the pages are not torn or wet.",
        ],
      ],
      choices: [
        "책 기부를 부탁하려고",
        "도서관 규칙을 알리려고",
        "행사를 취소하려고",
        "시험 범위를 알리려고",
        "청소 시간을 바꾸려고",
      ],
      answer: 1,
      clue: "We are collecting used books for the village center.",
      explanation:
        "마을 센터에 보낼 헌책을 모으니 가져다 달라고 부탁하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학생회입니다. 마을 센터에 보낼 헌책을 모으고 있습니다. 센터에서는 지난달에 작은 독서실을 열었습니다. 더 이상 읽지 않는 책을 현관 앞으로 가져와 주세요. 어린이책과 소설은 특히 환영합니다. 수거함은 다음 주 금요일까지 그곳에 있습니다. 쪽이 찢어지거나 젖지 않았는지 꼭 확인해 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you renting bicycles today?"],
        ["M", "Yes, two bicycles for two hours."],
        ["W", "One bicycle is six dollars for two hours."],
        ["M", "Do we have to rent helmets too?"],
        ["W", "Helmets are free with every bicycle."],
        ["M", "That's good news for us."],
        ["W", "But there is a two dollar cleaning fee in total."],
        ["M", "Is there anything else to pay?"],
        ["W", "No, that's everything for today."],
        ["M", "All right. Here is my card."],
      ],
      choices: ["$12", "$16", "$10", "$14", "$18"],
      answer: 4,
      clue: "One bicycle is six dollars for two hours.",
      explanation:
        "자전거 두 대 12달러에 청소비 2달러를 더하면 14달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요. 오늘 자전거 빌리시나요?",
        "M: 네, 두 시간 쓸 자전거 두 대요.",
        "W: 자전거 한 대는 두 시간에 6달러입니다.",
        "M: 헬멧도 빌려야 하나요?",
        "W: 헬멧은 자전거마다 무료입니다.",
        "M: 잘됐네요.",
        "W: 다만 청소비가 전체에 2달러 있습니다.",
        "M: 더 내야 하는 건 없나요?",
        "W: 아니요, 오늘은 그게 전부입니다.",
        "M: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, your notebook is always easy to read."],
        ["W", "I leave two empty lines between topics."],
        ["M", "Doesn't that use up a lot of pages?"],
        ["W", "A little, but I can find things fast."],
        ["M", "Mine is packed from edge to edge."],
        ["W", "Then everything looks the same on the page."],
        ["M", "And I can never find the important part."],
        ["W", "Two empty lines cost less than that."],
        ["M", "Could you show me one of your pages?"],
      ],
      choices: [
        "I don't use a notebook.",
        "Sure, open it right here.",
        "You should write smaller.",
        "Notebooks are not useful.",
        "I lost mine last week.",
      ],
      answer: 2,
      clue: "Could you show me one of your pages?",
      explanation:
        "남자가 공책을 보여 달라고 했으므로, 여기서 펴 보라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 다인아, 네 공책은 늘 읽기 쉬워.",
        "W: 주제마다 두 줄씩 비워 둬.",
        "M: 그러면 쪽수가 많이 들지 않아?",
        "W: 조금. 근데 찾기가 빨라.",
        "M: 내 건 끝에서 끝까지 꽉 차 있어.",
        "W: 그러면 쪽마다 다 똑같아 보여.",
        "M: 그래서 중요한 데를 못 찾아.",
        "W: 두 줄 비우는 값이 그보다 싸.",
        "M: 네 공책 한 쪽만 보여 줄래?",
        "W: 그럼, 여기서 펴 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sangho, you bring your lunch from home these days."],
        ["M", "Since April, and I make it myself."],
        ["W", "Isn't that hard on a school morning?"],
        ["M", "I prepare most of it the night before."],
        ["W", "What do you usually put in the box?"],
        ["M", "Rice, one egg dish and a vegetable."],
        ["W", "It looks better than what I buy."],
        ["M", "It's cheaper too, and I know what's in it."],
        ["W", "Could you teach me how to pack one?"],
      ],
      choices: [
        "Sure, come to my house Saturday.",
        "I buy my lunch every day.",
        "Cooking is impossible for students.",
        "I don't eat lunch at all.",
        "You should stop bringing lunch.",
      ],
      answer: 1,
      clue: "Could you teach me how to pack one?",
      explanation:
        "여자가 도시락 싸는 법을 가르쳐 달라고 했으므로, 토요일에 집에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 상호야, 요즘 집에서 점심 싸 오네.",
        "M: 4월부터. 직접 싸.",
        "W: 학교 가는 아침에 힘들지 않아?",
        "M: 대부분 전날 밤에 준비해.",
        "W: 보통 뭘 넣어?",
        "M: 밥이랑 달걀 요리 하나, 채소 하나.",
        "W: 내가 사 먹는 것보다 좋아 보인다.",
        "M: 더 싸기도 하고 뭐가 들었는지 알잖아.",
        "W: 나도 싸는 법 좀 가르쳐 줄래?",
        "M: 그럼, 토요일에 우리 집에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaeyeon, are you still nervous about the speech?"],
        ["W", "It's tomorrow and I keep thinking about it."],
        ["M", "Have you practiced saying it out loud?"],
        ["W", "Only in my head, on the bus."],
        ["M", "Your voice sounds different when you say it aloud."],
        ["W", "I never thought about that before."],
        ["M", "Record yourself once and listen to it."],
        ["W", "Won't it be strange to hear my own voice?"],
        ["M", "Strange for a minute, then very useful."],
      ],
      choices: [
        "I already gave the speech.",
        "All right, I'll record it tonight.",
        "I don't have a speech.",
        "Speaking aloud is useless.",
        "You should stop practicing.",
      ],
      answer: 2,
      clue: "Record yourself once and listen to it.",
      explanation:
        "녹음해서 들어 보라는 조언이므로, 오늘 밤 녹음하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 채연아, 아직 발표 때문에 긴장돼?",
        "W: 내일인데 계속 생각나.",
        "M: 소리 내어 말해 보는 연습은 했어?",
        "W: 버스에서 머릿속으로만.",
        "M: 소리 내어 말하면 목소리가 다르게 들려.",
        "W: 그건 생각 못 했어.",
        "M: 한 번 녹음해서 들어 봐.",
        "W: 내 목소리 듣는 거 이상하지 않을까?",
        "M: 1분만 이상하고 그다음엔 아주 쓸모 있어.",
        "W: 알겠어, 오늘 밤에 녹음해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Dohyun이 Nari에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Dohyun : ________________",
      lines: [
        [
          "M",
          "Dohyun and Nari are putting away books in the class library. " +
            "Nari stacks the books into one very tall pile on the desk. " +
            "Dohyun sees that the pile is leaning toward the edge. " +
            "If she adds one more book, the whole pile will fall. " +
            "He wants to stop her before she puts the next one on. " +
            "In this situation, what would Dohyun most likely say to Nari?",
        ],
      ],
      choices: [
        "The library closes at five today.",
        "Let's read these books together.",
        "Stop, that pile is about to fall.",
        "I'll bring more books here.",
        "You can go home first.",
      ],
      answer: 3,
      clue: "He wants to stop her before she puts the next one on.",
      explanation:
        "책 더미가 기울어 쏟아지려 하므로 말리는 ③이 가장 적절하다.",
      translation: [
        "M: 도현이와 나리는 학급 문고에 책을 정리하고 있습니다. 나리는 책상 위에 책을 아주 높게 한 더미로 쌓습니다. 도현이는 그 더미가 책상 가장자리 쪽으로 기울어 있는 것을 봅니다. 한 권만 더 얹으면 더미 전체가 무너질 것입니다. 도현이는 나리가 다음 책을 얹기 전에 말리고 싶습니다. 이런 상황에서 도현이가 나리에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
