/** 중1 듣기 14회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중1 14회",
  gradeLevel: "middle1",
  speechSpeed: 0.75,
  folder: "중1 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 모자를 고르시오.",
      lines: [
        ["W", "Hello. Can I help you?"],
        ["M", "Yes, I'm looking for a hat for the summer camp."],
        ["W", "We have caps and bucket hats. Which do you like?"],
        ["M", "A bucket hat, please. It covers my neck better."],
        ["W", "All right. Do you want one with a chin strap?"],
        ["M", "Yes, please. It gets windy at the camp."],
        ["W", "Then we have two left. One has stripes and one has no pattern."],
        ["M", "I'll take the striped one. It's easier to find in my bag."],
        ["W", "Good choice. This one folds up, too."],
        ["M", "Great. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I'll take the striped one. It's easier to find in my bag.",
      explanation:
        "남자는 야구 모자가 아닌 벙거지 모자를, 턱끈이 있는 것으로, 줄무늬가 있는 것을 고른다. 따라서 답은 ③이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five hats shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a baseball CAP with a stiff peak, no chin strap, completely plain. " +
          "Second: a baseball CAP with a stiff peak and a chin strap, covered in stripes. " +
          "Third: a soft round BUCKET HAT with a downward brim all around, with a chin strap, covered in stripes. " +
          "Fourth: a soft round BUCKET HAT with a downward brim all around, with a chin strap, completely plain with no pattern. " +
          "Fifth: a soft round BUCKET HAT with a downward brim all around, no chin strap, covered in stripes.",
      },
      translation: [
        "W: 안녕하세요. 도와드릴까요?",
        "M: 네, 여름 캠프에서 쓸 모자를 찾고 있어요.",
        "W: 야구 모자와 벙거지 모자가 있어요. 어느 쪽이 좋으세요?",
        "M: 벙거지 모자로요. 목까지 더 잘 가려 줘서요.",
        "W: 알겠습니다. 턱끈이 있는 걸로 하시겠어요?",
        "M: 네, 부탁해요. 캠프에서는 바람이 많이 불어요.",
        "W: 그럼 두 개 남았네요. 하나는 줄무늬가 있고 하나는 무늬가 없습니다.",
        "M: 줄무늬로 할게요. 가방에서 찾기가 더 쉬워요.",
        "W: 좋은 선택이세요. 이건 접을 수도 있습니다.",
        "M: 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 체육대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Suji, are you excited about the sports day?"],
        ["W", "Yes! But I still don't know much about it."],
        ["M", "It's next Thursday, all morning."],
        ["W", "Where do we do it? On the playground?"],
        ["M", "No, in the big gym this year. It might rain."],
        ["W", "What games are there?"],
        ["M", "Relay running, jump rope, and a ball game."],
        ["W", "Do we wear our school uniform?"],
        ["M", "No, everyone wears their class T-shirt."],
        ["W", "Then I'll look for mine tonight."],
      ],
      choices: ["열리는 날", "장소", "경기 종목", "준비물", "복장"],
      answer: 4,
      clue: "No, everyone wears their class T-shirt.",
      explanation:
        "날짜(다음 주 목요일), 장소(체육관), 경기 종목(이어달리기·줄넘기·공놀이), 복장(반 티셔츠)은 언급되지만 준비물은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 수지야, 체육대회 기대돼?",
        "W: 응! 그런데 아직 잘 몰라.",
        "M: 다음 주 목요일 오전 내내 해.",
        "W: 어디서 해? 운동장에서?",
        "M: 아니, 올해는 큰 체육관에서. 비가 올 수도 있대.",
        "W: 무슨 경기를 해?",
        "M: 이어달리기, 줄넘기, 그리고 공놀이.",
        "W: 교복 입어?",
        "M: 아니, 다들 반 티셔츠를 입어.",
        "W: 그럼 오늘 밤에 내 것 찾아봐야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Yuna. It's Minho from your class."],
        ["W", "Hi, Minho. Are you feeling better now?"],
        ["M", "A little. I had a fever all morning, so I was absent today."],
        ["W", "I saw your empty seat. Do you need something?"],
        ["M", "Yes. What's our math homework for tomorrow?"],
        ["W", "Page forty and forty-one in the workbook."],
        ["M", "Both pages? That's a lot. Do we have to show our work?"],
        ["W", "Yes, the teacher said she will check it."],
        ["M", "All right. Thank you for telling me."],
        ["W", "And don't forget the short quiz on Friday."],
        ["M", "Good to know. See you tomorrow."],
      ],
      choices: [
        "숙제가 무엇인지 물어보려고",
        "약속을 미루려고",
        "책을 빌려 달라고 하려고",
        "생일에 초대하려고",
        "길을 물어보려고",
      ],
      answer: 1,
      clue: "Yes. What's our math homework for tomorrow?",
      explanation:
        "남자는 오늘 결석해서 수학 숙제가 무엇인지 물어보려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 유나야. 같은 반 민호야.",
        "W: 안녕, 민호야. 이제 좀 괜찮아?",
        "M: 조금. 오전 내내 열이 나서 오늘 결석했어.",
        "W: 네 자리가 비어 있더라. 뭐 필요해?",
        "M: 응. 내일까지 수학 숙제가 뭐야?",
        "W: 문제집 40쪽이랑 41쪽.",
        "M: 두 쪽 다? 많다. 풀이도 써야 해?",
        "W: 응, 선생님이 확인하신대.",
        "M: 알겠어. 알려 줘서 고마워.",
        "W: 그리고 금요일 쪽지 시험도 잊지 마.",
        "M: 알려 줘서 고마워. 내일 보자.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Hayun, what time should we meet at the library?"],
        ["W", "It closes at six today, doesn't it?"],
        ["M", "Yes, so we need at least two hours."],
        ["W", "How about three o'clock?"],
        ["M", "I have a piano lesson until three thirty."],
        ["W", "Oh, I forgot. How long does it take you to walk there?"],
        ["M", "About ten minutes."],
        ["W", "Then let's meet at four o'clock."],
        ["M", "Four is fine. See you at the front door."],
      ],
      choices: ["3:00 p.m.", "3:30 p.m.", "4:00 p.m.", "4:30 p.m.", "5:00 p.m."],
      answer: 3,
      clue: "Then let's meet at four o'clock.",
      explanation:
        "남자의 피아노 수업이 3시 30분에 끝나고 걸어서 10분이 걸리므로 두 사람은 4시에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 하윤아, 도서관에서 몇 시에 만날까?",
        "W: 오늘 6시에 닫지?",
        "M: 응, 그래서 적어도 두 시간은 있어야 해.",
        "W: 3시는 어때?",
        "M: 3시 30분까지 피아노 수업이 있어.",
        "W: 아, 깜빡했다. 거기까지 걸어서 얼마나 걸려?",
        "M: 10분쯤.",
        "W: 그럼 4시에 만나자.",
        "M: 4시 좋아. 정문에서 보자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Mina, why do you look so down?"],
        ["W", "I lost my umbrella on the bus this morning."],
        ["M", "Was it an expensive one?"],
        ["W", "No, but my grandmother gave it to me."],
        ["M", "Did you call the bus company?"],
        ["W", "My mom did. They haven't found it yet."],
        ["M", "Maybe someone will bring it in."],
        ["W", "I hope so. She brought it from Jeju for me."],
      ],
      choices: ["excited", "sad", "proud", "surprised", "bored"],
      answer: 2,
      clue: "No, but my grandmother gave it to me.",
      explanation:
        "할머니가 제주에서 사다 주신 우산을 잃어버려서 여자는 속상해하고 있다. 따라서 답은 ②이다.",
      translation: [
        "M: 미나야, 왜 그렇게 기운이 없어?",
        "W: 오늘 아침에 버스에서 우산을 잃어버렸어.",
        "M: 비싼 거였어?",
        "W: 아니, 그런데 할머니가 주신 거야.",
        "M: 버스 회사에 전화해 봤어?",
        "W: 엄마가 했어. 아직 못 찾았대.",
        "M: 누가 가져다줄지도 몰라.",
        "W: 그랬으면 좋겠다. 할머니가 제주에서 사다 주신 거야.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "How much is this backpack?"],
        ["W", "It's twenty dollars."],
        ["M", "What time is the next train?"],
        ["W", "At ten fifteen."],
        ["M", "Are you ready to order?"],
        ["W", "Yes, I'll have the sandwich."],
        ["M", "Excuse me, can I take your order now?"],
        ["W", "One more minute, please."],
        ["M", "Do you need a bigger size?"],
        ["W", "Yes, this one is too small."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "How much is this backpack?",
      explanation:
        "그림은 가게에서 손님이 배낭을 들고 점원에게 값을 묻는 장면이므로 ①이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "Inside a small bag shop. A young man is holding up a backpack with one hand and looking at the shop assistant behind the counter, asking her something. The woman behind the counter is smiling and holding out five fingers. Shelves of bags stand along the wall behind them. Both people are drawn clearly.",
      },
      translation: [
        "① M: 이 배낭 얼마예요? / W: 20달러입니다.",
        "② M: 다음 기차가 몇 시예요? / W: 10시 15분이요.",
        "③ M: 주문하시겠어요? / W: 네, 샌드위치로 할게요.",
        "④ M: 실례합니다, 지금 주문받아도 될까요? / W: 1분만 더 주세요.",
        "⑤ M: 더 큰 치수가 필요하세요? / W: 네, 이건 너무 작아요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiho, are you going to the science room after lunch?"],
        ["M", "Yes, our club meets there every Tuesday."],
        ["W", "That's good. I left my water bottle there yesterday."],
        ["M", "Where did you leave it?"],
        ["W", "On the table by the window. It's a blue one."],
        ["M", "I think I saw it this morning."],
        ["W", "Could you bring it to me after your club?"],
        ["M", "Sure. I'll bring it to your classroom."],
        ["W", "Thank you so much."],
      ],
      choices: ["숙제 도와주기", "물병 가져다주기", "자리 맡아 주기", "우산 빌려주기", "사진 찍어 주기"],
      answer: 2,
      clue: "Could you bring it to me after your club?",
      explanation:
        "여자는 과학실에 두고 온 파란 물병을 가져다 달라고 부탁한다. 따라서 답은 ②이다.",
      translation: [
        "W: 지호야, 점심 먹고 과학실 가?",
        "M: 응, 우리 동아리가 화요일마다 거기서 모여.",
        "W: 잘됐다. 어제 거기에 물병을 두고 왔어.",
        "M: 어디에 뒀는데?",
        "W: 창가 탁자 위에. 파란 거야.",
        "M: 오늘 아침에 본 것 같아.",
        "W: 동아리 끝나고 가져다줄 수 있어?",
        "M: 그럼. 너희 교실로 가져갈게.",
        "W: 정말 고마워.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Art Club에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, everyone. Let me tell you about the Art Club."],
        ["W", "We meet every Wednesday after school."],
        ["W", "Our club room is on the second floor, next to the library."],
        ["W", "This year we will draw, paint, and make small clay animals."],
        ["W", "If you want to join, write your name on the paper by the door."],
        ["W", "We hope to see many new members."],
      ],
      choices: ["모이는 요일", "모이는 장소", "하는 활동", "가입 방법", "회원 수"],
      answer: 5,
      clue: "If you want to join, write your name on the paper by the door.",
      explanation:
        "모이는 요일(수요일), 장소(2층 동아리방), 활동(그리기·색칠·찰흙), 가입 방법(문 옆 종이에 이름 적기)은 언급되지만 회원 수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여러분, 안녕하세요. Art Club을 소개합니다.",
        "W: 우리는 수요일마다 방과 후에 모입니다.",
        "W: 동아리방은 2층, 도서관 옆에 있습니다.",
        "W: 올해는 그림을 그리고, 색칠하고, 작은 찰흙 동물을 만듭니다.",
        "W: 들어오고 싶으면 문 옆 종이에 이름을 적으세요.",
        "W: 새 회원을 많이 만나면 좋겠습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You put this on your feet before you go outside."],
        ["M", "It comes in two, and they look the same."],
        ["M", "Many of them have strings that you tie."],
        ["M", "You wear a different kind for running and for rain."],
        ["M", "You take them off when you come into a Korean house."],
      ],
      choices: ["신발", "모자", "장갑", "가방", "우산"],
      answer: 1,
      clue: "You take them off when you come into a Korean house.",
      explanation:
        "발에 신고, 두 짝이며, 끈을 묶고, 한국 집에 들어올 때 벗는다고 했으므로 신발이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 밖에 나가기 전에 발에 신습니다.",
        "M: 두 개가 한 벌이고, 둘은 똑같이 생겼습니다.",
        "M: 많은 것에는 묶는 끈이 달려 있습니다.",
        "M: 달릴 때와 비 올 때 쓰는 것이 다릅니다.",
        "M: 한국 집에 들어올 때는 벗습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How old is your brother?"],
        ["M", "He's eleven."],
        ["W", "Can I use your eraser?"],
        ["M", "Of course, here you are."],
        ["W", "What are you doing now?"],
        ["M", "I'm reading a comic book."],
        ["W", "Do you like winter?"],
        ["M", "Yes, I love the snow."],
        ["W", "Where are you from?"],
        ["M", "I have two dogs at home."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Where are you from?",
      explanation:
        "어디에서 왔는지 묻는 말에 집에 개가 두 마리 있다는 대답은 어울리지 않는다. 따라서 답은 ⑤이다.",
      translation: [
        "① W: 네 동생 몇 살이야? / M: 열한 살이야.",
        "② W: 지우개 좀 써도 돼? / M: 그럼, 여기 있어.",
        "③ W: 지금 뭐 해? / M: 만화책 읽고 있어.",
        "④ W: 겨울 좋아해? / M: 응, 눈이 정말 좋아.",
        "⑤ W: 어디에서 왔어? / M: 나는 집에 개가 두 마리 있어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaemin, our guests will be here in ten minutes."],
        ["M", "Is everything ready? What can I do?"],
        ["W", "I already set the table and made the salad."],
        ["M", "Should I buy some juice?"],
        ["W", "No, Dad brought some home last night."],
        ["M", "Then what is left?"],
        ["W", "The front door is still locked and Grandma will arrive first."],
        ["M", "I'll go and open it right now."],
        ["W", "Thanks. I'll put the soup on the table."],
      ],
      choices: ["식탁 차리기", "샐러드 만들기", "주스 사 오기", "현관문 열어 두기", "국 나르기"],
      answer: 4,
      clue: "I'll go and open it right now.",
      explanation:
        "식탁과 샐러드는 이미 끝났고 주스도 있으므로, 남자는 잠겨 있는 현관문을 열러 간다. 따라서 답은 ④이다.",
      translation: [
        "W: 재민아, 손님들이 10분 뒤에 오셔.",
        "M: 다 준비됐어? 내가 뭘 할까?",
        "W: 식탁은 이미 차렸고 샐러드도 만들었어.",
        "M: 주스를 사 올까?",
        "W: 아니, 어젯밤에 아빠가 사 오셨어.",
        "M: 그럼 뭐가 남았어?",
        "W: 현관문이 아직 잠겨 있는데 할머니가 먼저 오실 거야.",
        "M: 지금 가서 열어 놓을게.",
        "W: 고마워. 나는 국을 식탁에 올릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 필통을 고르시오.",
      lines: [
        ["W", "Dongjin, are these the pencil cases you were looking at?"],
        ["M", "Yes, these five. I need a new one for school."],
        ["W", "How much can you spend?"],
        ["M", "Ten dollars at the most."],
        ["W", "All right, that takes out one of them."],
        ["M", "And I want a zipper, not a button."],
        ["W", "Then one more is gone. Three are left."],
        ["M", "I'd like two pockets so I can keep my ruler apart."],
        ["W", "Two of them have one pocket only."],
        ["M", "Then there's just one left. I'll take that one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Then there's just one left. I'll take that one.",
      explanation:
        "12달러인 ③, 단추로 여는 ①을 빼고, 주머니가 하나뿐인 ②와 ④를 뺀다. 남은 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "$7 / 단추 / 주머니 2개" },
          { no: 2, label: "②", value: "$8 / 지퍼 / 주머니 1개" },
          { no: 3, label: "③", value: "$12 / 지퍼 / 주머니 2개" },
          { no: 4, label: "④", value: "$9 / 지퍼 / 주머니 1개" },
          { no: 5, label: "⑤", value: "$10 / 지퍼 / 주머니 2개" },
        ],
      },
      translation: [
        "W: 동진아, 네가 보던 필통이 이거야?",
        "M: 응, 이 다섯 개. 학교에서 쓸 새것이 필요해.",
        "W: 얼마까지 쓸 수 있어?",
        "M: 많아야 10달러.",
        "W: 그럼 하나가 빠지네.",
        "M: 그리고 단추 말고 지퍼가 좋아.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 자를 따로 넣게 주머니가 두 개였으면 좋겠어.",
        "W: 둘은 주머니가 하나뿐이야.",
        "M: 그럼 하나만 남네. 그걸로 할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 박물관에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Seoyeon, when should we go to the museum?"],
        ["W", "What are we going to see there, again?"],
        ["M", "The dinosaur room. It's only open this month."],
        ["W", "Then let's go soon. How about the fifth?"],
        ["M", "I have swimming class on the fifth."],
        ["W", "Then the sixth or the seventh."],
        ["M", "Isn't the seventh the school picnic day?"],
        ["W", "You're right. We'd be too tired after that."],
        ["M", "So only the sixth is left."],
        ["W", "Let's go on the sixth, right after lunch."],
      ],
      choices: ["4일", "5일", "6일", "7일", "8일"],
      answer: 3,
      clue: "So only the sixth is left.",
      explanation:
        "5일은 수영 수업, 7일은 학교 소풍이어서 6일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 서연아, 박물관 언제 갈까?",
        "W: 거기서 뭘 본다고 했지?",
        "M: 공룡관. 이번 달에만 열어.",
        "W: 그럼 빨리 가자. 5일은 어때?",
        "M: 5일에 수영 수업이 있어.",
        "W: 그럼 6일이나 7일이네.",
        "M: 7일은 학교 소풍 날 아니야?",
        "W: 맞다. 그러고 나면 너무 피곤하겠다.",
        "M: 그럼 6일만 남네.",
        "W: 6일에 가자, 점심 먹고 바로.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nayoung, did you go to the park last weekend?"],
        ["W", "No, I made cookies with my mom on Saturday."],
        ["M", "Cookies? What kind did you make?"],
        ["W", "Chocolate ones. My mom found the recipe in an old book."],
        ["M", "How long did it take you?"],
        ["W", "Almost three hours, and we made about fifty of them."],
        ["M", "Fifty! That's a lot of cookies for one family."],
        ["W", "Too many, so we gave some to the neighbors next door."],
        ["M", "That was nice of you. Were they happy?"],
        ["W", "Very. They gave us a box of apples, so we ate those too."],
      ],
      choices: ["공원 가기", "쿠키 만들기", "영화 보기", "수영하기", "책 읽기"],
      answer: 2,
      clue: "No, I made cookies with my mom on Saturday.",
      explanation:
        "여자는 지난 토요일에 엄마와 쿠키를 만들었다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "M: 나영아, 지난 주말에 공원 갔어?",
        "W: 아니, 토요일에 엄마랑 쿠키를 만들었어.",
        "M: 쿠키? 무슨 쿠키를 만들었어?",
        "W: 초콜릿 쿠키. 엄마가 오래된 책에서 조리법을 찾으셨어.",
        "M: 얼마나 걸렸어?",
        "W: 거의 세 시간, 쉰 개쯤 만들었어.",
        "M: 쉰 개! 한 집이 먹기엔 정말 많다.",
        "W: 너무 많아서 옆집 이웃한테도 좀 드렸어.",
        "M: 착하다. 좋아하셨어?",
        "W: 아주. 사과 한 상자를 주셔서 그것도 먹었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "We have one short notice for you this morning."],
        ["M", "The water in the third-floor fountain is not working today."],
        ["M", "It stopped last night, and workers will come to fix it this afternoon."],
        ["M", "Until then, please use the fountain on the second floor instead."],
        ["M", "It is right beside the stairs, so it is not far from your classroom."],
        ["M", "You can also bring your own water bottle from home tomorrow."],
        ["M", "We are sorry for the trouble, and thank you for your patience."],
      ],
      choices: [
        "물을 아껴 쓰라고 하려고",
        "급식 시간을 알리려고",
        "교실 청소를 당부하려고",
        "3층 정수기를 쓸 수 없다고 알리려고",
        "물병을 사 오라고 하려고",
      ],
      answer: 4,
      clue: "The water in the third-floor fountain is not working today.",
      explanation:
        "3층 음수대가 오늘 고장 났으니 2층을 쓰라고 알리는 방송이다. 따라서 방송의 목적은 ④이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 오늘 아침에 짧게 알려 드릴 것이 하나 있습니다.",
        "M: 오늘 3층 음수대에서 물이 나오지 않습니다.",
        "M: 어젯밤에 멈췄고, 오늘 오후에 기사님이 고치러 오십니다.",
        "M: 그때까지는 2층 음수대를 이용해 주세요.",
        "M: 계단 바로 옆에 있어서 교실에서 멀지 않습니다.",
        "M: 내일은 집에서 물병을 가져와도 좋습니다.",
        "M: 불편을 드려 죄송하고, 기다려 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What would you like?"],
        ["W", "Two sandwiches and one orange juice, please."],
        ["M", "The sandwiches are five dollars each."],
        ["W", "And the juice?"],
        ["M", "The juice is three dollars."],
        ["W", "So ten dollars and three dollars."],
        ["M", "That's right. Do you have a student card?"],
        ["W", "Yes, here it is."],
        ["M", "Then I can take one dollar off."],
        ["W", "Great. Here's my card."],
      ],
      choices: ["$10", "$11", "$12", "$13", "$14"],
      answer: 3,
      clue: "Then I can take one dollar off.",
      explanation:
        "샌드위치 5달러짜리 두 개는 10달러, 주스 3달러를 더하면 13달러이다. 학생 할인 1달러를 빼면 12달러이므로 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 뭘 드릴까요?",
        "W: 샌드위치 두 개랑 오렌지 주스 하나 주세요.",
        "M: 샌드위치는 하나에 5달러입니다.",
        "W: 주스는요?",
        "M: 주스는 3달러입니다.",
        "W: 그럼 10달러랑 3달러네요.",
        "M: 맞습니다. 학생증 있으세요?",
        "W: 네, 여기요.",
        "M: 그럼 1달러 빼 드릴게요.",
        "W: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junho, you look sleepy again today."],
        ["M", "I know. I went to bed after twelve last night."],
        ["W", "What were you doing so late?"],
        ["M", "I was watching videos on my phone."],
        ["W", "Every night?"],
        ["M", "Almost. I start at nine and then I can't stop."],
        ["W", "Do you keep your phone next to your bed?"],
        ["M", "Yes, right beside my pillow."],
        ["W", "Try leaving it on your desk tonight."],
      ],
      choices: [
        "I watched a movie last Sunday.",
        "My phone is almost two years old.",
        "I go to bed at nine every night.",
        "You should buy a new phone.",
        "All right, I'll put it on my desk.",
      ],
      answer: 5,
      clue: "Try leaving it on your desk tonight.",
      explanation:
        "휴대전화를 책상에 두고 자 보라는 말을 들었으므로, 그렇게 하겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 준호야, 오늘도 졸려 보여.",
        "M: 그러게. 어젯밤에 12시 넘어서 잤어.",
        "W: 그렇게 늦게까지 뭐 했어?",
        "M: 휴대전화로 영상 봤어.",
        "W: 매일 밤?",
        "M: 거의. 9시에 시작하면 멈출 수가 없어.",
        "W: 휴대전화를 침대 옆에 둬?",
        "M: 응, 베개 바로 옆에.",
        "W: 오늘 밤에는 책상에 두고 자 봐.",
        "M: 알겠어, 책상에 둘게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Dayeon, are you still looking for your gym shoes?"],
        ["W", "Yes. I've looked in my locker three times."],
        ["M", "When did you use them last?"],
        ["W", "On Friday, in the gym."],
        ["M", "Did you take them home that day?"],
        ["W", "I don't think so. I went straight to the bus."],
        ["M", "Then they might still be in the gym."],
        ["W", "But the gym was locked this morning."],
        ["M", "It opens at lunchtime. You can check then."],
      ],
      choices: [
        "Then I'll go and look at lunchtime.",
        "I bought those shoes last year.",
        "My locker is next to the door.",
        "The gym class is on Fridays.",
        "You should look for yours too.",
      ],
      answer: 1,
      clue: "It opens at lunchtime. You can check then.",
      explanation:
        "체육관이 점심시간에 연다는 말을 들었으므로, 그때 가서 찾아보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 다연아, 아직 체육복 신발 찾고 있어?",
        "W: 응. 사물함을 세 번이나 봤어.",
        "M: 마지막으로 언제 신었어?",
        "W: 금요일, 체육관에서.",
        "M: 그날 집에 가져갔어?",
        "W: 아닌 것 같아. 바로 버스 타러 갔거든.",
        "M: 그럼 아직 체육관에 있을 수도 있겠다.",
        "W: 그런데 오늘 아침에 체육관이 잠겨 있었어.",
        "M: 점심시간에 열어. 그때 가서 보면 돼.",
        "W: 그럼 점심시간에 가서 찾아볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Sungho, you didn't eat much at lunch today."],
        ["M", "I wasn't hungry. I had a big snack at ten."],
        ["W", "Again? You did that yesterday too."],
        ["M", "I know. I get hungry in the second class."],
        ["W", "Do you eat breakfast at home?"],
        ["M", "Not usually. I get up too late."],
        ["W", "That's why you're hungry at ten."],
        ["M", "But I don't have time in the morning."],
        ["W", "Even a banana on the way would help."],
      ],
      choices: [
        "I had rice and soup this morning.",
        "Lunch starts at twelve thirty.",
        "I don't like bananas at all.",
        "Then I'll take one with me tomorrow.",
        "You should eat more at lunch.",
      ],
      answer: 4,
      clue: "Even a banana on the way would help.",
      explanation:
        "가는 길에 바나나라도 먹으면 도움이 된다는 말을 들었으므로, 내일 하나 가져가겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 성호야, 오늘 점심을 많이 안 먹었네.",
        "M: 배가 안 고팠어. 10시에 간식을 많이 먹었거든.",
        "W: 또? 어제도 그랬잖아.",
        "M: 알아. 2교시에 배가 고파져.",
        "W: 집에서 아침 먹어?",
        "M: 보통은 안 먹어. 너무 늦게 일어나서.",
        "W: 그래서 10시에 배가 고픈 거야.",
        "M: 그런데 아침에 시간이 없어.",
        "W: 가는 길에 바나나 하나라도 먹으면 도움이 될 거야.",
        "M: 그럼 내일 하나 가져갈게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sumin이 Jiwon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Sumin : ________________",
      lines: [
        ["M", "Sumin and Jiwon sit next to each other in class."],
        ["M", "They are making a poster about recycling together."],
        ["M", "Jiwon has drawn the pictures and they look very good."],
        ["M", "But she used a pencil, so the lines are very light."],
        ["M", "The poster will go on the wall at the back of the classroom."],
        ["M", "From the front of the room, nobody will see the light lines."],
        ["M", "Sumin does not want to say that her drawing is bad."],
        ["M", "She wants to ask her to go over the lines with a black pen."],
        ["M", "In this situation, what would Sumin most likely say to Jiwon?"],
      ],
      choices: [
        "Let's draw the pictures again tomorrow.",
        "Could you go over the lines with a black pen?",
        "I'll put the poster on the wall myself.",
        "We should choose a different subject.",
        "Your pictures are too big for the paper.",
      ],
      answer: 2,
      clue: "She wants to ask her to go over the lines with a black pen.",
      explanation:
        "수민이는 지원이의 그림을 깎아내리지 않으면서, 연필 선을 검은 펜으로 덧그려 달라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 수민과 지원은 교실에서 옆자리에 앉습니다.",
        "M: 두 사람은 재활용에 관한 포스터를 함께 만들고 있습니다.",
        "M: 지원이 그림을 그렸는데 아주 잘 그렸습니다.",
        "M: 그런데 연필로 그려서 선이 아주 연합니다.",
        "M: 이 포스터는 교실 뒤쪽 벽에 붙을 것입니다.",
        "M: 교실 앞에서는 아무도 연한 선을 보지 못할 것입니다.",
        "M: 수민은 지원의 그림이 나쁘다고 말하고 싶지는 않습니다.",
        "M: 다만 검은 펜으로 선을 덧그려 달라고 부탁하고 싶습니다.",
        "M: 이런 상황에서 수민이 지원에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
