/** 중2 듣기 22회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 22회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 손목시계를 고르시오.",
      lines: [
        ["M", "Good afternoon. Are you looking for a watch?"],
        ["W", "Yes, something simple for everyday use."],
        ["M", "We have leather bands and metal bands."],
        ["W", "A leather band, please. Metal feels cold in winter."],
        ["M", "All right. This leather one has a square face."],
        ["W", "A square face looks too formal for school."],
        ["M", "Then here is a leather one with a round face."],
        ["W", "That's much better. I'll take the round one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "A leather band, please. / I'll take the round one.",
      explanation:
        "여자는 가죽 줄 시계를 원하고, 네모난 판 대신 둥근 판을 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five wristwatches drawn side by side as five choices, clean black line art on white. " +
          "① a watch with a METAL LINK band and a SQUARE face. " +
          "② a watch with a METAL LINK band and a ROUND face. " +
          "③ a watch with a plain LEATHER band and a ROUND face. " +
          "④ a watch with a plain LEATHER band and a SQUARE face. " +
          "⑤ a watch with a METAL LINK band and an OVAL face.",
      },
      translation: [
        "M: 안녕하세요. 시계 찾으세요?",
        "W: 네, 평소에 차기 좋은 단순한 걸로요.",
        "M: 가죽 줄도 있고 금속 줄도 있어요.",
        "W: 가죽 줄로 주세요. 금속은 겨울에 차가워요.",
        "M: 알겠습니다. 이 가죽 줄 시계는 판이 네모예요.",
        "W: 네모난 판은 학교에 차기엔 너무 격식 있어 보여요.",
        "M: 그럼 판이 둥근 가죽 줄 시계가 여기 있어요.",
        "W: 그게 훨씬 낫네요. 둥근 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 토론 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jaemin, are you joining the school debate contest?"],
        ["M", "I'd like to. When is it held?"],
        ["W", "Next Thursday, in the audiovisual room."],
        ["M", "How many students are on one team?"],
        ["W", "Two students argue for, and two argue against."],
        ["M", "What is the topic this year?"],
        ["W", "Whether students should use phones during lunch."],
        ["M", "Interesting. How long does each side get?"],
        ["W", "Six minutes to speak and three minutes to answer."],
      ],
      choices: ["열리는 날", "열리는 장소", "한 팀의 인원", "토론 주제", "심사 위원"],
      answer: 5,
      clue: "심사 위원은 대화에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 목요일), 장소(시청각실), 한 팀 인원(찬반 각 2명), 주제(점심시간 휴대폰 사용)는 언급되지만 심사 위원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 재민아, 교내 토론 대회 나갈 거야?",
        "M: 나가고 싶어. 언제 해?",
        "W: 다음 주 목요일, 시청각실에서.",
        "M: 한 팀에 몇 명이야?",
        "W: 찬성 두 명, 반대 두 명이야.",
        "M: 올해 주제가 뭐야?",
        "W: 학생이 점심시간에 휴대폰을 써도 되는가.",
        "M: 흥미롭다. 한쪽에 시간을 얼마나 줘?",
        "W: 발언 6분, 반론 3분.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Hanul Community Center?"],
        ["W", "Yes, it is. How may I help you?"],
        ["M", "I signed up for the Saturday guitar class."],
        ["W", "Yes, the beginner class at two o'clock."],
        ["M", "My family is moving to Ulsan next month."],
        ["W", "Oh, so you can't continue the class."],
        ["M", "That's right. I'd like to cancel from October."],
        ["W", "I understand. I'll take your name off the list."],
      ],
      choices: [
        "수업을 신청하려고",
        "수업 시간을 바꾸려고",
        "수강을 취소하려고",
        "기타를 빌리려고",
        "수업료를 물어보려고",
      ],
      answer: 3,
      clue: "That's right. I'd like to cancel from October.",
      explanation:
        "남자는 이사 때문에 10월부터 기타 수업을 취소하려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "M: 여보세요, 하늘 주민 센터죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 토요일 기타 수업을 신청했는데요.",
        "W: 네, 2시 초급반이요.",
        "M: 저희 가족이 다음 달에 울산으로 이사 가요.",
        "W: 아, 그럼 수업을 계속 못 들으시겠네요.",
        "M: 맞아요. 10월부터 취소하고 싶어요.",
        "W: 알겠습니다. 명단에서 성함을 빼겠습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Jaemin, what time does the volunteer work start?"],
        ["M", "We start sorting the books at ten o'clock."],
        ["W", "Do we need to do anything before that?"],
        ["M", "Yes, we sign in and get our name tags first."],
        ["W", "How long does the sign-in take?"],
        ["M", "About thirty minutes for all twenty of us."],
        ["W", "Then let's meet thirty minutes before ten."],
        ["M", "Good. I'll wait by the library entrance."],
        ["W", "See you there on Saturday morning."],
      ],
      choices: ["9:00 a.m.", "9:30 a.m.", "10:00 a.m.", "10:30 a.m.", "11:00 a.m."],
      answer: 2,
      clue: "Then let's meet thirty minutes before ten.",
      explanation:
        "책 정리가 10시에 시작하고 30분 전에 만나기로 했으므로 만나는 시각은 9시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "W: 재민아, 봉사 활동 몇 시에 시작해?",
        "M: 10시에 책 정리를 시작해.",
        "W: 그전에 뭐 해야 해?",
        "M: 응, 먼저 서명하고 이름표를 받아야 해.",
        "W: 서명하는 데 얼마나 걸려?",
        "M: 스무 명이면 30분쯤.",
        "W: 그럼 10시 30분 전에 만나자.",
        "M: 좋아. 나는 도서관 입구에서 기다릴게.",
        "W: 토요일 아침에 거기서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sojin, you've been quiet since the club meeting."],
        ["W", "They gave the solo part to someone else."],
        ["M", "But you've practiced that song since March."],
        ["W", "I know. I stayed after school almost every day."],
        ["M", "Did the teacher say why?"],
        ["W", "She said the other student's voice fits better."],
        ["M", "That must be hard to hear."],
        ["W", "I worked so hard, and now I sing in the back row."],
      ],
      choices: ["excited", "thankful", "curious", "disappointed", "surprised"],
      answer: 4,
      clue: "I worked so hard, and now I sing in the back row.",
      explanation:
        "3월부터 준비한 독창 부분을 다른 학생이 맡게 되어 뒷줄에서 부르게 되었으므로 여자의 심정은 '실망한(disappointed)'이다. 따라서 답은 ④이다.",
      translation: [
        "M: 소진아, 동아리 모임 끝나고부터 말이 없네.",
        "W: 독창 부분을 다른 사람한테 줬어.",
        "M: 그런데 너 3월부터 그 노래 연습했잖아.",
        "W: 알아. 거의 매일 방과 후에 남았어.",
        "M: 선생님이 이유를 말씀하셨어?",
        "W: 다른 학생 목소리가 더 어울린다고 하셨어.",
        "M: 듣기 힘들었겠다.",
        "W: 그렇게 열심히 했는데 이제 뒷줄에서 불러.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is this book on sale?"],
        ["M", "Yes, everything here is half price."],
        ["ANN", "Number two."],
        ["W", "Do you have this in a bigger size?"],
        ["M", "Let me check the back room."],
        ["ANN", "Number three."],
        ["W", "Excuse me, you left your change on the counter."],
        ["M", "Oh, thank you for noticing."],
        ["ANN", "Number four."],
        ["W", "Can I return this next week?"],
        ["M", "Yes, within seven days."],
        ["ANN", "Number five."],
        ["W", "Where is the fitting room?"],
        ["M", "It's behind the shelf over there."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, you left your change on the counter.",
      explanation:
        "그림은 가게 계산대에서 남자가 거스름돈을 두고 나가려 하고, 여자 점원이 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small shop at the checkout counter, clean black line art on a plain white background, no writing anywhere. " +
          "A man with a shopping bag is turning to walk away from the counter. " +
          "Several coins and a bill are still lying on the counter top. " +
          "A woman clerk behind the counter points at the money and calls out to him. " +
          "Shelves of goods and a cash register are drawn simply in the background.",
      },
      translation: [
        "① W: 이 책 할인하나요? / M: 네, 여기 있는 건 다 반값입니다.",
        "② W: 이거 더 큰 치수 있나요? / M: 뒤쪽 창고를 확인해 볼게요.",
        "③ W: 저기요, 계산대에 거스름돈을 두고 가셨어요. / M: 아, 알려 주셔서 감사합니다.",
        "④ W: 다음 주에 반품해도 되나요? / M: 네, 7일 이내면 됩니다.",
        "⑤ W: 탈의실이 어디예요? / M: 저쪽 선반 뒤에 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaemin, you go past the post office every morning, right?"],
        ["M", "Yes, it's on my way to school. Why?"],
        ["W", "I have a letter for my pen pal in Canada."],
        ["M", "Do you need a stamp for it?"],
        ["W", "No, I already put the international stamp on it."],
        ["M", "Then you just need to drop it in the box."],
        ["W", "Right. Could you put it in the mailbox for me tomorrow?"],
        ["M", "Sure. Give it to me before you go home."],
      ],
      choices: ["편지 우체통에 넣어 주기", "우표 사다 주기", "편지 대신 써 주기", "우체국 위치 알려 주기", "소포 부쳐 주기"],
      answer: 1,
      clue: "Right. Could you put it in the mailbox for me tomorrow?",
      explanation:
        "여자는 우표까지 붙인 편지를 내일 우체통에 넣어 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 재민아, 너 아침마다 우체국 앞을 지나가지?",
        "M: 응, 학교 가는 길에 있어. 왜?",
        "W: 캐나다 펜팔 친구한테 보낼 편지가 있어.",
        "M: 우표가 필요해?",
        "W: 아니, 국제 우표는 벌써 붙였어.",
        "M: 그럼 우체통에 넣기만 하면 되겠네.",
        "W: 맞아. 내일 우체통에 넣어 줄 수 있어?",
        "M: 그럼. 집에 가기 전에 나한테 줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 진로 체험의 날에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Our career experience day is next Tuesday. " +
            "All classes will gather in the gym at nine in the morning. " +
            "Eight guests will come, including a nurse, a chef, and a game designer. " +
            "Each student can choose two of the eight talks to attend. " +
            "Bring a notebook, because you will write a short report afterward. " +
            "We hope you find something interesting for your future.",
        ],
      ],
      choices: ["열리는 날", "모이는 시각", "초청되는 직업", "들을 수 있는 강연 수", "행사가 끝나는 시각"],
      answer: 5,
      clue: "행사가 끝나는 시각은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 화요일), 모이는 시각(아침 9시), 초청 직업(간호사·요리사·게임 디자이너 등), 들을 수 있는 강연 수(여덟 개 중 두 개)는 언급되지만 끝나는 시각은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 진로 체험의 날이 다음 주 화요일에 열립니다. 모든 반은 아침 9시에 체육관에 모입니다. 간호사, 요리사, 게임 디자이너를 포함해 여덟 분이 오십니다. 학생마다 여덟 강연 중 두 개를 골라 들을 수 있습니다. 나중에 짧은 보고서를 쓰니 공책을 가져오세요. 앞날에 도움이 될 것을 찾기 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a job that many people meet only in an emergency. " +
            "People with this job wear heavy coats and hard hats. " +
            "They ride in a bright red truck with a long ladder on top. " +
            "They spray water on burning buildings and carry people out. " +
            "They also visit schools to teach children about safety.",
        ],
      ],
      choices: ["경찰관", "소방관", "간호사", "우체부", "요리사"],
      answer: 2,
      clue: "They spray water on burning buildings and carry people out.",
      explanation:
        "두꺼운 옷과 안전모를 쓰고 사다리 달린 빨간 차를 타며 불타는 건물에 물을 뿌리는 사람은 소방관이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이 직업은 많은 사람이 급한 일이 생겼을 때만 만납니다. 이 일을 하는 사람들은 두꺼운 옷과 딱딱한 모자를 씁니다. 위에 긴 사다리가 달린 밝은 빨간색 차를 타고 다닙니다. 불타는 건물에 물을 뿌리고 사람들을 밖으로 데리고 나옵니다. 학교에 찾아와 아이들에게 안전을 가르치기도 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How long have you studied Chinese?"],
        ["W", "For about two years."],
        ["ANN", "Number two."],
        ["M", "Would you like to leave a message?"],
        ["W", "Yes, please tell him I called."],
        ["ANN", "Number three."],
        ["M", "What's the matter with you?"],
        ["W", "I have a terrible headache."],
        ["ANN", "Number four."],
        ["M", "Whose turn is it to speak?"],
        ["W", "The weather is nice today."],
        ["ANN", "Number five."],
        ["M", "Could you turn down the music?"],
        ["W", "Sorry, I'll lower it right away."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Whose turn is it to speak?",
      explanation:
        "누구 차례인지 묻는 말에 오늘 날씨가 좋다고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 중국어 공부한 지 얼마나 됐어? / W: 2년쯤 됐어.",
        "② M: 말씀 남기시겠어요? / W: 네, 제가 전화했다고 전해 주세요.",
        "③ M: 무슨 일 있어? / W: 머리가 몹시 아파.",
        "④ M: 이제 누가 말할 차례야? / W: 오늘 날씨가 좋네.",
        "⑤ M: 음악 소리 좀 줄여 줄래? / W: 미안, 바로 줄일게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaemin, the class debate starts in twenty minutes."],
        ["M", "I know. Are the desks in two rows facing each other?"],
        ["W", "Yes, I moved them during lunch."],
        ["M", "Great. Did you print the rules for the judges?"],
        ["W", "I printed them, but the timer is missing."],
        ["M", "Without a timer nobody can keep to six minutes."],
        ["W", "I have to greet the teacher at the door."],
        ["M", "Then I'll run to the science room and borrow one."],
      ],
      choices: ["책상 옮기기", "규칙 인쇄하기", "선생님 맞이하기", "심사표 나눠 주기", "타이머 빌려 오기"],
      answer: 5,
      clue: "Then I'll run to the science room and borrow one.",
      explanation:
        "타이머가 없어 시간을 잴 수 없는데 여자는 선생님을 맞아야 해서, 남자가 과학실에 가 타이머를 빌려 오겠다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 재민아, 학급 토론이 20분 뒤에 시작해.",
        "M: 알아. 책상은 마주 보게 두 줄로 놨어?",
        "W: 응, 점심시간에 옮겼어.",
        "M: 잘했다. 심사 위원용 규칙은 인쇄했어?",
        "W: 인쇄는 했는데 타이머가 없어.",
        "M: 타이머가 없으면 6분을 못 지켜.",
        "W: 나는 문에서 선생님을 맞아야 해.",
        "M: 그럼 내가 과학실에 가서 하나 빌려 올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 예약할 숙소를 고르시오.",
      lines: [
        ["M", "Sojin, which guesthouse are you booking for the trip?"],
        ["W", "Let me look at the list first."],
        ["M", "How many people are going with you?"],
        ["W", "Six of us, so a room for four is too small."],
        ["M", "Okay. What about the price for one night?"],
        ["W", "Under ninety thousand won, because we split it."],
        ["M", "Got it. Do you need breakfast included?"],
        ["W", "Yes, we leave early and won't have time to cook."],
        ["M", "Then only one guesthouse on this list works."],
        ["W", "Good. I'll book it online tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Six of us, so a room for four is too small.",
      explanation:
        "6명 이상이 묵을 수 있고, 하룻밤 9만 원 미만이며, 아침 식사가 포함된 것을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "People: 4 / Price: 70,000 won / Breakfast: Yes" },
          { no: 2, label: "②", value: "People: 6 / Price: 95,000 won / Breakfast: Yes" },
          { no: 3, label: "③", value: "People: 8 / Price: 85,000 won / Breakfast: No" },
          { no: 4, label: "④", value: "People: 6 / Price: 82,000 won / Breakfast: Yes" },
          { no: 5, label: "⑤", value: "People: 4 / Price: 60,000 won / Breakfast: No" },
        ],
      },
      translation: [
        "M: 소진아, 여행 숙소 어디로 예약할 거야?",
        "W: 목록부터 볼게.",
        "M: 몇 명이 가?",
        "W: 여섯 명이라 4인실은 너무 작아.",
        "M: 알겠어. 하룻밤 가격은?",
        "W: 나눠 내니까 9만 원 미만이어야 해.",
        "M: 그렇구나. 아침 식사가 포함돼야 해?",
        "W: 응, 일찍 나가서 해 먹을 시간이 없어.",
        "M: 그럼 이 목록에서 되는 건 하나뿐이네.",
        "W: 좋아. 오늘 밤에 인터넷으로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 연극을 보러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Jaemin, when can we watch the school play?"],
        ["M", "How about September 4th? That's opening night."],
        ["W", "I have a dentist appointment that evening."],
        ["M", "Then what about September 6th?"],
        ["W", "The theater is closed on the 6th for cleaning."],
        ["M", "Hmm. I'm free on September 11th."],
        ["W", "But the play finishes its run on the 9th."],
        ["M", "Oh, right. Then September 8th is our last chance."],
        ["W", "That works. I finish my club at five that day."],
        ["M", "Great. Let's meet at the theater at six."],
      ],
      choices: ["9월 4일", "9월 6일", "9월 8일", "9월 9일", "9월 11일"],
      answer: 3,
      clue: "Oh, right. Then September 8th is our last chance.",
      explanation:
        "4일에는 치과 예약이, 6일에는 극장 청소가 있고 공연은 9일에 끝난다. 두 사람은 9월 8일에 보기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 재민아, 학교 연극 언제 보러 갈까?",
        "M: 9월 4일 어때? 첫날 공연이야.",
        "W: 그날 저녁에 치과 예약이 있어.",
        "M: 그럼 9월 6일은?",
        "W: 6일엔 극장이 청소 때문에 닫아.",
        "M: 음. 나는 9월 11일이 비어.",
        "W: 그런데 공연이 9일에 끝나.",
        "M: 아, 맞다. 그럼 9월 8일이 마지막 기회네.",
        "W: 괜찮아. 그날은 동아리가 5시에 끝나.",
        "M: 좋아. 6시에 극장에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sojin, your fingers look a little swollen today."],
        ["W", "I spent all Saturday at my aunt's flower shop."],
        ["M", "Did you sell flowers to customers there?"],
        ["W", "No, I tied bouquets for a wedding the whole day."],
        ["M", "How many bouquets did you make?"],
        ["W", "Forty, and the stems were harder than I expected."],
        ["M", "That sounds like real work."],
        ["W", "It was, but the bride sent us a thank-you note."],
      ],
      choices: ["꽃 팔기", "꽃다발 만들기", "결혼식 가기", "꽃집 청소하기", "꽃 배달하기"],
      answer: 2,
      clue: "No, I tied bouquets for a wedding the whole day.",
      explanation:
        "여자는 토요일 내내 이모의 꽃집에서 결혼식용 꽃다발 마흔 개를 만들었다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 소진아, 오늘 손가락이 좀 부어 보인다.",
        "W: 토요일 내내 이모 꽃집에 있었어.",
        "M: 거기서 손님들한테 꽃 팔았어?",
        "W: 아니, 하루 종일 결혼식에 쓸 꽃다발을 묶었어.",
        "M: 몇 개나 만들었어?",
        "W: 마흔 개. 줄기가 생각보다 단단했어.",
        "M: 진짜 일이었겠다.",
        "W: 그랬는데, 신부가 감사 편지를 보내 주셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the physical education office. " +
            "The gym floor will be repainted from Monday to Wednesday next week. " +
            "During those three days, no class may use the gym at all. " +
            "All physical education classes will be held on the outdoor field instead. " +
            "Please bring a hat and sunscreen for those days. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "체육복 구입을 안내하려고",
        "운동장 공사를 알리려고",
        "체육관 사용이 불가함을 알리려고",
        "체육 수업 시간 변경을 알리려고",
      ],
      answer: 4,
      clue: "During those three days, no class may use the gym at all.",
      explanation:
        "다음 주 월~수요일에 체육관 바닥을 칠해 사흘 동안 체육관을 쓸 수 없음을 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 체육부입니다. 다음 주 월요일부터 수요일까지 체육관 바닥을 다시 칠합니다. 그 사흘 동안은 어떤 반도 체육관을 쓸 수 없습니다. 모든 체육 수업은 대신 운동장에서 진행합니다. 그날들에는 모자와 자외선 차단제를 가져오세요. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the museum?"],
        ["M", "Yes, two student tickets and one adult ticket."],
        ["W", "A student ticket is six dollars and an adult is ten."],
        ["M", "So twenty-two dollars for the three of us?"],
        ["W", "That's right. Would you like an audio guide?"],
        ["M", "No, thank you. Just the tickets."],
        ["W", "All right. Weekday visitors get four dollars off."],
        ["M", "Lucky us. Today is Wednesday."],
      ],
      choices: ["$16", "$18", "$20", "$22", "$24"],
      answer: 2,
      clue: "All right. Weekday visitors get four dollars off.",
      explanation:
        "학생 표 두 장 12달러와 어른 표 한 장 10달러를 더하면 22달러이고, 평일 할인 4달러를 빼면 18달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 박물관 표 사시나요?",
        "M: 네, 학생 두 장이랑 어른 한 장이요.",
        "W: 학생 표는 6달러, 어른 표는 10달러입니다.",
        "M: 그럼 셋이 22달러인가요?",
        "W: 맞습니다. 음성 안내기도 빌리시겠어요?",
        "M: 아니요, 괜찮아요. 표만 주세요.",
        "W: 알겠습니다. 평일 방문객은 4달러 할인됩니다.",
        "M: 운이 좋네요. 오늘 수요일이에요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jaemin, you've rewritten that essay three times now."],
        ["M", "I know, but the ending still feels weak."],
        ["W", "What exactly bothers you about it?"],
        ["M", "It just repeats what I already said in the middle."],
        ["W", "Then the ending isn't doing any new work."],
        ["M", "Right, but I don't know what else to put there."],
        ["W", "What did you learn while writing this essay?"],
        ["M", "That I care about this topic more than I thought."],
        ["W", "Put exactly that in your last paragraph."],
      ],
      choices: [
        "I'll try writing it that way tonight.",
        "I already handed in the essay.",
        "The middle part is missing.",
        "I don't care about the topic.",
        "Let's write a new essay instead.",
      ],
      answer: 1,
      clue: "Put exactly that in your last paragraph.",
      explanation:
        "여자가 글을 쓰며 깨달은 바로 그것을 마지막 문단에 넣으라고 했으므로, 오늘 밤에 그렇게 써 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 재민아, 그 글을 벌써 세 번째 고쳐 쓰네.",
        "M: 알아, 그런데 마무리가 아직 약해.",
        "W: 정확히 뭐가 마음에 걸려?",
        "M: 중간에 이미 한 말을 되풀이하기만 해.",
        "W: 그럼 마무리가 하는 일이 없는 거네.",
        "M: 맞아, 그런데 거기 뭘 더 넣어야 할지 모르겠어.",
        "W: 이 글을 쓰면서 뭘 알게 됐어?",
        "M: 내가 이 주제를 생각보다 더 아낀다는 거.",
        "W: 바로 그걸 마지막 문단에 넣어.",
        "M: 오늘 밤에 그렇게 써 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sojin, are you still walking your neighbor's dog?"],
        ["W", "Yes, but it pulls so hard that my arm hurts."],
        ["M", "How long is the leash you use?"],
        ["W", "About three meters. I thought longer was kinder."],
        ["M", "A long leash actually makes pulling worse."],
        ["W", "Really? I had no idea."],
        ["M", "With a short leash the dog stays beside you."],
        ["W", "But won't the dog feel trapped?"],
        ["M", "Not if you stop walking every time it pulls."],
      ],
      choices: [
        "I'll try a short leash tomorrow.",
        "The dog never pulls at all.",
        "I stopped walking the dog last week.",
        "Longer leashes are always better.",
        "My neighbor has three cats.",
      ],
      answer: 1,
      clue: "Not if you stop walking every time it pulls.",
      explanation:
        "남자가 짧은 목줄을 쓰고 당길 때마다 멈추라고 알려 주었으므로, 내일 짧은 목줄을 써 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 소진아, 아직 이웃집 개 산책시켜?",
        "W: 응, 그런데 너무 세게 당겨서 팔이 아파.",
        "M: 쓰는 목줄이 얼마나 길어?",
        "W: 3미터쯤. 길수록 개한테 좋은 줄 알았어.",
        "M: 긴 목줄은 오히려 당기는 버릇을 키워.",
        "W: 정말? 전혀 몰랐어.",
        "M: 짧은 목줄이면 개가 네 옆에 붙어 있어.",
        "W: 그런데 개가 답답해하지 않을까?",
        "M: 당길 때마다 멈춰 서면 괜찮아.",
        "W: 내일 짧은 목줄 써 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Sojin, our group has to record a radio drama."],
        ["W", "I heard. Have you written the script yet?"],
        ["M", "Yes, but every recording comes out noisy."],
        ["W", "Where are you recording it?"],
        ["M", "In the classroom, right after school."],
        ["W", "That's the problem. The hallway is loud then."],
        ["M", "We can't record at night, though."],
        ["W", "Have you tried the small room in the library?"],
        ["M", "Is it quiet enough in there?"],
        ["W", "Yes, and you can book it for one hour at a time."],
      ],
      choices: [
        "I'll book it for tomorrow afternoon.",
        "The classroom is always silent.",
        "We finished recording yesterday.",
        "The library closed last month.",
        "Let's record in the hallway.",
      ],
      answer: 1,
      clue: "Yes, and you can book it for one hour at a time.",
      explanation:
        "여자가 도서관 작은 방을 한 시간씩 예약할 수 있다고 했으므로, 내일 오후로 예약하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 소진아, 우리 조가 라디오 드라마를 녹음해야 해.",
        "W: 들었어. 대본은 다 썼어?",
        "M: 응, 그런데 녹음할 때마다 잡음이 들어가.",
        "W: 어디서 녹음해?",
        "M: 교실에서, 방과 후 바로.",
        "W: 그게 문제야. 그때 복도가 시끄러워.",
        "M: 그렇다고 밤에는 녹음을 못 해.",
        "W: 도서관 작은 방은 써 봤어?",
        "M: 거기 충분히 조용해?",
        "W: 응, 한 시간씩 예약할 수도 있어.",
        "M: 내일 오후로 예약할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yerim이 Taeyang에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yerim : ________________",
      lines: [
        [
          "W",
          "Yerim and Taeyang are working on a group poster after school. " +
            "Taeyang is about to glue the last photo onto the poster board. " +
            "Yerim notices that the photo is upside down in his hand. " +
            "Once the glue dries, the photo cannot be moved again. " +
            "She wants to stop him before he presses it down. " +
            "In this situation, what would Yerim most likely say to Taeyang?",
        ],
      ],
      choices: [
        "Let's use a different photo.",
        "The glue dried a long time ago.",
        "I'll print a new poster board.",
        "We finished the poster yesterday.",
        "Wait, the photo is upside down.",
      ],
      answer: 5,
      clue: "Yerim notices that the photo is upside down in his hand.",
      explanation:
        "태양이가 사진을 거꾸로 든 채 붙이려 하므로, 붙이기 전에 거꾸로 되었다고 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "W: 예림이와 태양이는 방과 후에 모둠 포스터를 만들고 있습니다. 태양이는 마지막 사진을 포스터 판에 붙이려 합니다. 예림이는 그 사진이 태양이 손에 거꾸로 들려 있는 것을 알아챕니다. 풀이 마르면 사진을 다시 옮길 수 없습니다. 예림이는 태양이가 사진을 누르기 전에 말리고 싶습니다. 이런 상황에서 예림이가 태양이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
