/** 중2 듣기 24회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 24회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 램프를 고르시오.",
      lines: [
        ["M", "Good evening. Are you looking for a lamp?"],
        ["W", "Yes, one for the table beside my bed."],
        ["M", "We have floor lamps and small table lamps."],
        ["W", "A table lamp, please. A floor lamp won't fit there."],
        ["M", "All right. This table lamp has a round shade."],
        ["W", "A round shade spreads the light too widely."],
        ["M", "Then here is a table lamp with a cone shade."],
        ["W", "That's better. I'll take the cone one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A table lamp, please. / I'll take the cone one.",
      explanation:
        "여자는 작은 탁상용 램프를 원하고, 둥근 갓 대신 원뿔 갓을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five lamps drawn side by side as five choices, clean black line art on white. " +
          "① a TALL FLOOR lamp with a ROUND BALL shade. " +
          "② a TALL FLOOR lamp with a CONE shade. " +
          "③ a SMALL TABLE lamp with a ROUND BALL shade. " +
          "④ a SMALL TABLE lamp with a CONE shade. " +
          "⑤ a SMALL TABLE lamp with a plain CYLINDER shade. " +
          "The floor lamps are clearly about twice as tall as the table lamps.",
      },
      translation: [
        "M: 안녕하세요. 램프 찾으세요?",
        "W: 네, 침대 옆 탁자에 둘 거예요.",
        "M: 세워 두는 큰 램프도 있고 작은 탁상용도 있어요.",
        "W: 탁상용으로 주세요. 큰 건 거기 안 들어가요.",
        "M: 알겠습니다. 이 탁상용 램프는 갓이 둥글어요.",
        "W: 둥근 갓은 빛이 너무 넓게 퍼져요.",
        "M: 그럼 원뿔 갓이 달린 탁상용이 여기 있어요.",
        "W: 그게 낫네요. 원뿔 갓으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 미술 전시회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junseo, is your painting in the school art show?"],
        ["M", "Yes, it is. Are you coming to see it?"],
        ["W", "Of course. When does the show open?"],
        ["M", "Next Monday, and it runs for two weeks."],
        ["W", "Where are the works displayed?"],
        ["M", "Along the hallway on the third floor."],
        ["W", "How many works are in the show?"],
        ["M", "About sixty, from all three grades."],
        ["W", "That's a lot. I'll come after school on Tuesday."],
      ],
      choices: ["관람료", "시작하는 날", "전시 기간", "전시 장소", "작품 수"],
      answer: 1,
      clue: "관람료는 대화에서 언급되지 않았다.",
      explanation:
        "시작하는 날(다음 주 월요일), 기간(2주), 장소(3층 복도), 작품 수(약 60점)는 언급되지만 관람료는 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "W: 준서야, 학교 미술 전시회에 네 그림 나와?",
        "M: 응, 나와. 보러 올 거야?",
        "W: 당연하지. 전시회 언제 시작해?",
        "M: 다음 주 월요일, 2주 동안 해.",
        "W: 작품은 어디에 걸려 있어?",
        "M: 3층 복도를 따라서.",
        "W: 작품이 몇 점이나 돼?",
        "M: 세 학년 합쳐서 예순 점쯤.",
        "W: 많네. 화요일 방과 후에 갈게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Sunlight Sports Center?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "I left my water bottle in the locker room yesterday."],
        ["W", "What does it look like?"],
        ["M", "It's dark green with my name on the bottom."],
        ["W", "Let me check the lost and found box."],
        ["M", "Thank you. I really need it for practice."],
        ["W", "Good news. A green bottle is here with a name on it."],
      ],
      choices: [
        "운동 수업을 신청하려고",
        "사물함을 빌리려고",
        "운영 시간을 물어보려고",
        "두고 온 물건을 찾으려고",
        "회원 가입을 하려고",
      ],
      answer: 4,
      clue: "I left my water bottle in the locker room yesterday.",
      explanation:
        "남자는 어제 탈의실에 두고 온 물병을 찾으려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요, 선라이트 스포츠 센터죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 어제 탈의실에 물병을 두고 왔어요.",
        "W: 어떻게 생겼나요?",
        "M: 진한 초록색이고 바닥에 제 이름이 있어요.",
        "W: 분실물 상자를 확인해 볼게요.",
        "M: 감사합니다. 연습할 때 꼭 필요해서요.",
        "W: 좋은 소식이에요. 이름이 적힌 초록 물병이 여기 있어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Junseo, what time does the last subway leave?"],
        ["M", "The last one leaves the station at eleven thirty."],
        ["W", "Then we should leave the concert before that."],
        ["M", "Right. The walk to the station takes fifteen minutes."],
        ["W", "And the concert hall gets crowded at the end."],
        ["M", "So let's leave one hour before the last subway."],
        ["W", "Good idea. Let's meet at the side exit then."],
        ["M", "I'll be standing near the poster board."],
        ["W", "Okay, I'll find you there."],
      ],
      choices: ["10:00 p.m.", "10:30 p.m.", "11:00 p.m.", "11:15 p.m.", "11:30 p.m."],
      answer: 2,
      clue: "So let's leave one hour before the last subway.",
      explanation:
        "막차가 11시 30분에 떠나고 그보다 한 시간 전에 나가기로 했으므로 만나는 시각은 10시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 지하철 막차가 몇 시에 떠나?",
        "M: 막차는 역에서 11시 30분에 떠나.",
        "W: 그럼 그전에 공연장에서 나와야겠다.",
        "M: 맞아. 역까지 걸어가면 15분 걸려.",
        "W: 그리고 끝날 때쯤엔 공연장이 붐벼.",
        "M: 그러니까 막차 한 시간 전에 나가자.",
        "W: 좋은 생각이야. 그때 옆문에서 만나자.",
        "M: 나는 포스터 게시판 근처에 서 있을게.",
        "W: 알겠어, 거기서 찾을게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyeri, you've been smiling at that letter all morning."],
        ["W", "The city library accepted my book review."],
        ["M", "The one you wrote for the summer contest?"],
        ["W", "Yes, and they will print it in the fall magazine."],
        ["M", "That's wonderful. How many were chosen?"],
        ["W", "Only ten out of three hundred reviews."],
        ["M", "You must be so happy right now."],
        ["W", "I've read the letter four times already."],
      ],
      choices: ["bored", "worried", "angry", "sleepy", "delighted"],
      answer: 5,
      clue: "I've read the letter four times already.",
      explanation:
        "300편 중 열 편에 뽑혀 잡지에 실리게 되었고 편지를 네 번이나 읽었다고 했으므로 여자의 심정은 '기쁜(delighted)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 혜리야, 아침 내내 그 편지 보면서 웃네.",
        "W: 시립 도서관에서 내 독후감을 뽑았대.",
        "M: 여름 대회에 낸 그거?",
        "W: 응, 가을 잡지에 실어 준대.",
        "M: 멋지다. 몇 편이 뽑혔어?",
        "W: 300편 중에 열 편만.",
        "M: 지금 정말 기쁘겠다.",
        "W: 벌써 편지를 네 번이나 읽었어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How many laps did you swim?"],
        ["M", "Twenty laps today."],
        ["ANN", "Number two."],
        ["W", "Is the water cold in there?"],
        ["M", "A little, but you get used to it."],
        ["ANN", "Number three."],
        ["W", "Where are the changing rooms?"],
        ["M", "Down the stairs on your left."],
        ["ANN", "Number four."],
        ["W", "Excuse me, you can't run by the pool."],
        ["M", "Sorry, I'll walk from now on."],
        ["ANN", "Number five."],
        ["W", "Do I need a swimming cap?"],
        ["M", "Yes, everyone must wear one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Excuse me, you can't run by the pool.",
      explanation:
        "그림은 수영장 옆 젖은 바닥에서 남학생이 뛰어가고, 안전 요원인 여자가 손을 들어 제지하는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Beside an indoor swimming pool, clean black line art on a plain white background, no writing anywhere. " +
          "A boy in swim trunks is running along the wet edge of the pool with both arms swinging. " +
          "A woman lifeguard sitting on a tall chair raises one hand toward him as if telling him to stop. " +
          "Lane ropes in the water and a row of lockers are drawn simply in the background.",
      },
      translation: [
        "① W: 몇 바퀴 헤엄쳤어요? / M: 오늘은 스무 바퀴요.",
        "② W: 거기 물이 차가워요? / M: 조금요, 그런데 곧 익숙해져요.",
        "③ W: 탈의실이 어디예요? / M: 계단 내려가서 왼쪽이요.",
        "④ W: 저기요, 수영장 옆에서 뛰면 안 돼요. / M: 죄송해요, 이제 걸어갈게요.",
        "⑤ W: 수영모가 필요한가요? / M: 네, 모두 써야 합니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, you're good with computers, aren't you?"],
        ["M", "A little. What's the problem?"],
        ["W", "My history presentation file won't open at all."],
        ["M", "Did you save it on a USB drive?"],
        ["W", "Yes, and I have to present it tomorrow morning."],
        ["M", "It might just be a broken file name."],
        ["W", "Could you try opening it on your laptop today?"],
        ["M", "Sure. Bring the drive to the club room at four."],
      ],
      choices: ["파일 열어 보기", "발표 대신 해 주기", "노트북 빌려주기", "USB 사 오기", "발표 자료 만들어 주기"],
      answer: 1,
      clue: "Could you try opening it on your laptop today?",
      explanation:
        "여자는 열리지 않는 발표 파일을 남자의 노트북에서 열어 봐 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 준서야, 너 컴퓨터 잘하지?",
        "M: 조금. 무슨 문제야?",
        "W: 역사 발표 파일이 아예 안 열려.",
        "M: USB에 저장했어?",
        "W: 응, 내일 아침에 발표해야 해.",
        "M: 파일 이름이 깨진 것일 수도 있어.",
        "W: 오늘 네 노트북에서 한번 열어 봐 줄 수 있어?",
        "M: 그럼. 4시에 동아리방으로 USB 가져와.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 야영 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Our school camping night is this Friday. " +
            "We will set up tents on the grass field behind the gym. " +
            "Each tent holds four students, so find three friends. " +
            "Bring a sleeping bag, a flashlight, and warm socks. " +
            "Dinner will be cooked together over the fire at seven. " +
            "Please sign the form and give it to your homeroom teacher.",
        ],
      ],
      choices: ["열리는 날", "천막 치는 곳", "한 천막의 인원", "행사가 끝나는 시각", "준비물"],
      answer: 4,
      clue: "행사가 끝나는 시각은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(이번 주 금요일), 천막 치는 곳(체육관 뒤 잔디밭), 한 천막 인원(4명), 준비물(침낭·손전등·두꺼운 양말)은 언급되지만 끝나는 시각은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 학교 야영의 밤이 이번 주 금요일에 열립니다. 체육관 뒤 잔디밭에 천막을 칩니다. 천막 하나에 네 명이 들어가니 친구 세 명을 찾으세요. 침낭, 손전등, 두꺼운 양말을 가져오세요. 저녁은 7시에 불에 다 같이 해 먹습니다. 신청서에 서명해서 담임 선생님께 내 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a small machine you hold in one hand at home. " +
            "You press the buttons on it to change what you are watching. " +
            "It works only when you point it at the screen. " +
            "It often disappears between the sofa cushions. " +
            "When it stops working, the first thing to check is the batteries.",
        ],
      ],
      choices: ["계산기", "리모컨", "손전등", "휴대폰", "마우스"],
      answer: 2,
      clue: "You press the buttons on it to change what you are watching.",
      explanation:
        "화면을 향해 눌러 보는 것을 바꾸고, 소파 쿠션 사이에서 자주 사라지며, 안 되면 건전지부터 확인하는 것은 리모컨이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이것은 집에서 한 손에 드는 작은 기계입니다. 여기 있는 단추를 눌러 보고 있는 것을 바꿉니다. 화면을 향해 겨눠야만 작동합니다. 소파 쿠션 사이에서 자주 사라집니다. 작동하지 않으면 가장 먼저 건전지를 확인합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How do you feel about the new schedule?"],
        ["W", "I think it's much better."],
        ["ANN", "Number two."],
        ["M", "Where should I put these boxes?"],
        ["W", "In the corner by the door."],
        ["ANN", "Number three."],
        ["M", "Can you lend me five thousand won?"],
        ["W", "Sure, I'll give it back tomorrow."],
        ["ANN", "Number four."],
        ["M", "Do you want to join us for dinner?"],
        ["W", "I'd love to, thank you."],
        ["ANN", "Number five."],
        ["M", "What time did the meeting finish?"],
        ["W", "My sister lives in Daegu."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "What time did the meeting finish?",
      explanation:
        "회의가 몇 시에 끝났는지 묻는 말에 언니가 대구에 산다고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 새 시간표 어때? / W: 훨씬 나은 것 같아.",
        "② M: 이 상자들 어디에 둘까? / W: 문 옆 구석에.",
        "③ M: 5천 원만 빌려줄래? / W: 그럼, 내일 갚을게.",
        "④ M: 우리랑 저녁 먹을래? / W: 좋아, 고마워.",
        "⑤ M: 회의 몇 시에 끝났어? / W: 우리 언니는 대구에 살아.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, the class cooking contest starts in ten minutes."],
        ["M", "I know. Did you wash all the vegetables?"],
        ["W", "Yes, they're in the bowl on the counter."],
        ["M", "Great. Is the pan hot enough yet?"],
        ["W", "It is, but we have no cooking oil at our station."],
        ["M", "Without oil the vegetables will stick to the pan."],
        ["W", "I can't leave. I'm watching the pan."],
        ["M", "Then I'll go to the front table and get a bottle."],
      ],
      choices: ["채소 씻기", "팬 달구기", "기름 가져오기", "심사 위원 맞이하기", "접시 닦기"],
      answer: 3,
      clue: "Then I'll go to the front table and get a bottle.",
      explanation:
        "기름이 없는데 여자는 팬을 지켜야 해서, 남자가 앞 탁자에서 기름을 가져오겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 준서야, 학급 요리 대회가 10분 뒤에 시작해.",
        "M: 알아. 채소는 다 씻었어?",
        "W: 응, 조리대 위 그릇에 있어.",
        "M: 잘했다. 팬은 충분히 달궈졌어?",
        "W: 응, 그런데 우리 자리에 식용유가 없어.",
        "M: 기름이 없으면 채소가 팬에 눌어붙어.",
        "W: 나는 못 가. 팬을 보고 있어야 해.",
        "M: 그럼 내가 앞 탁자에 가서 한 병 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 자전거 헬멧을 고르시오.",
      lines: [
        ["M", "Hyeri, which helmet are you going to buy?"],
        ["W", "Let me see the list first."],
        ["M", "Do you need a light on the back?"],
        ["W", "Yes, I ride home after sunset every day."],
        ["M", "Okay. And how much can you spend?"],
        ["W", "Under fifty thousand won. That's my whole budget."],
        ["M", "Got it. Does the size matter?"],
        ["W", "I need a large one. Medium hurts my forehead."],
        ["M", "Then only one helmet on this list works for you."],
        ["W", "Good. Let's order it right after school."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Yes, I ride home after sunset every day.",
      explanation:
        "뒷불이 있고, 5만 원 미만이며, 큰 치수인 것을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Light: Yes / Price: 48,000 won / Size: Large" },
          { no: 2, label: "②", value: "Light: Yes / Price: 55,000 won / Size: Large" },
          { no: 3, label: "③", value: "Light: No / Price: 40,000 won / Size: Large" },
          { no: 4, label: "④", value: "Light: Yes / Price: 45,000 won / Size: Medium" },
          { no: 5, label: "⑤", value: "Light: No / Price: 30,000 won / Size: Medium" },
        ],
      },
      translation: [
        "M: 혜리야, 어떤 헬멧 살 거야?",
        "W: 목록부터 볼게.",
        "M: 뒤에 불이 필요해?",
        "W: 응, 매일 해 진 뒤에 자전거로 집에 와.",
        "M: 알겠어. 얼마까지 쓸 수 있어?",
        "W: 5만 원 미만. 그게 내 예산 전부야.",
        "M: 그렇구나. 치수는 상관있어?",
        "W: 큰 게 필요해. 중간은 이마가 아파.",
        "M: 그럼 이 목록에서 되는 건 하나뿐이야.",
        "W: 좋아. 방과 후에 바로 주문하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 한복을 빌리러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Hyeri, when should we rent the hanbok for the festival?"],
        ["W", "How about February 5th? That's next Wednesday."],
        ["M", "The rental shop is closed every Wednesday."],
        ["W", "Then what about February 8th?"],
        ["M", "My cousin's wedding is on the 8th."],
        ["W", "Hmm. I'm free on February 14th."],
        ["M", "But the festival itself is on the 12th."],
        ["W", "Oh, right. Then let's go on February 10th."],
        ["M", "February 10th works. The shop opens at ten."],
        ["W", "Perfect. Let's go right after breakfast."],
      ],
      choices: ["2월 5일", "2월 8일", "2월 12일", "2월 10일", "2월 14일"],
      answer: 4,
      clue: "Oh, right. Then let's go on February 10th.",
      explanation:
        "5일은 수요일 휴무이고, 8일에는 결혼식이 있으며, 14일은 축제(12일) 이후다. 두 사람은 2월 10일에 가기로 한다. 따라서 답은 ④이다.",
      translation: [
        "M: 혜리야, 축제에 입을 한복 언제 빌리러 갈까?",
        "W: 2월 5일 어때? 다음 주 수요일이야.",
        "M: 대여점은 수요일마다 문을 닫아.",
        "W: 그럼 2월 8일은?",
        "M: 8일에 사촌 결혼식이 있어.",
        "W: 음. 나는 2월 14일이 비어.",
        "M: 그런데 축제가 12일이잖아.",
        "W: 아, 맞다. 그럼 2월 10일에 가자.",
        "M: 2월 10일 괜찮아. 가게는 10시에 열어.",
        "W: 좋아. 아침 먹고 바로 가자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, why do you have paint under your nails?"],
        ["M", "I was at the old playground all Saturday."],
        ["W", "The one behind the market? It looked so worn out."],
        ["M", "It did. Our club repainted the slide and the benches."],
        ["W", "How many of you went?"],
        ["M", "Nine of us, and we used six cans of paint."],
        ["W", "The children must be happy now."],
        ["M", "They came to watch while it was still drying."],
      ],
      choices: ["놀이터에서 놀기", "놀이터 페인트칠하기", "미끄럼틀 고치기", "벤치 만들기", "시장 청소하기"],
      answer: 2,
      clue: "It did. Our club repainted the slide and the benches.",
      explanation:
        "남자는 토요일에 동아리 친구들과 오래된 놀이터의 미끄럼틀과 벤치를 다시 칠했다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 손톱 밑에 왜 페인트가 묻었어?",
        "M: 토요일 내내 낡은 놀이터에 있었어.",
        "W: 시장 뒤에 있는 거? 정말 낡아 보였는데.",
        "M: 맞아. 우리 동아리가 미끄럼틀이랑 벤치를 다시 칠했어.",
        "W: 몇 명이나 갔어?",
        "M: 아홉 명. 페인트 여섯 통 썼어.",
        "W: 아이들이 좋아하겠다.",
        "M: 아직 마르는 중인데도 와서 구경했어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school office. " +
            "Many bicycles are parked in front of the main entrance these days. " +
            "They block the door when students come in and out. " +
            "Please park your bicycle in the rack beside the gym instead. " +
            "Bicycles left at the entrance will be moved by the staff. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "자전거 등록을 안내하려고",
        "자전거 도난을 알리려고",
        "정문 공사를 알리려고",
        "자전거 대여를 안내하려고",
        "자전거 주차 장소를 안내하려고",
      ],
      answer: 5,
      clue: "Please park your bicycle in the rack beside the gym instead.",
      explanation:
        "정문 앞에 세운 자전거가 통행을 막으니 체육관 옆 거치대에 세우라고 안내하는 방송이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실입니다. 요즘 정문 앞에 자전거가 많이 세워져 있습니다. 학생들이 드나들 때 문을 막습니다. 대신 체육관 옆 거치대에 자전거를 세워 주세요. 정문에 둔 자전거는 직원이 옮깁니다. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the sports shop. What can I help you with?"],
        ["M", "Two pairs of socks and one water bottle, please."],
        ["W", "Socks are five dollars a pair and the bottle is twelve."],
        ["M", "So twenty-two dollars for everything?"],
        ["W", "That's right. Do you need a bag as well?"],
        ["M", "No, thank you. I have my backpack."],
        ["W", "All right. Members get three dollars off today."],
        ["M", "I'm a member. Here is my card."],
      ],
      choices: ["$15", "$17", "$19", "$18", "$22"],
      answer: 3,
      clue: "All right. Members get three dollars off today.",
      explanation:
        "양말 두 켤레 10달러와 물병 12달러를 더하면 22달러이고, 회원 할인 3달러를 빼면 19달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 스포츠 용품점에 오신 걸 환영합니다. 무엇을 도와드릴까요?",
        "M: 양말 두 켤레랑 물병 하나 주세요.",
        "W: 양말은 한 켤레에 5달러, 물병은 12달러입니다.",
        "M: 그럼 전부 22달러인가요?",
        "W: 맞습니다. 봉투도 드릴까요?",
        "M: 아니요, 괜찮아요. 가방이 있어요.",
        "W: 알겠습니다. 오늘은 회원에게 3달러 할인됩니다.",
        "M: 저 회원이에요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Hyeri, you look tired after every group practice."],
        ["W", "I end up doing everyone's part by myself."],
        ["M", "Why don't you tell them how you feel?"],
        ["W", "I don't want to sound like I'm complaining."],
        ["M", "Asking for help isn't complaining."],
        ["W", "But they might think I can't handle it."],
        ["M", "They'll think you're being honest with them."],
        ["W", "So how should I start that conversation?"],
        ["M", "Say what you need, not what they did wrong."],
      ],
      choices: [
        "I'll try saying it that way.",
        "Nobody is in my group.",
        "I never practice with them.",
        "I already told them everything.",
        "Let's cancel the practice.",
      ],
      answer: 1,
      clue: "Say what you need, not what they did wrong.",
      explanation:
        "남자가 잘못을 탓하지 말고 필요한 것을 말하라고 했으므로, 그렇게 말해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 혜리야, 모둠 연습 끝나면 늘 피곤해 보여.",
        "W: 결국 다른 사람 몫까지 내가 다 하게 돼.",
        "M: 어떤 기분인지 얘기해 보는 건 어때?",
        "W: 불평하는 것처럼 들리기 싫어.",
        "M: 도움을 청하는 건 불평이 아니야.",
        "W: 그런데 내가 못 해낸다고 생각할까 봐.",
        "M: 솔직한 사람이라고 생각할 거야.",
        "W: 그럼 그 얘기를 어떻게 꺼내야 해?",
        "M: 걔들이 뭘 잘못했는지 말고, 네가 뭐가 필요한지 말해.",
        "W: 그렇게 말해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junseo, your eyes look red again today."],
        ["M", "I read on my phone in bed until late."],
        ["W", "In the dark, with the screen right in your face?"],
        ["M", "Yes, and my eyes start to sting after an hour."],
        ["W", "That's the screen being much brighter than the room."],
        ["M", "I thought a dark room was better for reading."],
        ["W", "Not with a bright screen. The difference tires your eyes."],
        ["M", "So should I turn on a lamp while I read?"],
        ["W", "Yes, a soft light behind you makes a big difference."],
      ],
      choices: [
        "My phone has no screen.",
        "I never read before bed.",
        "The room is always bright.",
        "I'll turn on my desk lamp tonight.",
        "I'll read in a darker room.",
      ],
      answer: 4,
      clue: "Yes, a soft light behind you makes a big difference.",
      explanation:
        "여자가 뒤에서 은은한 불을 켜라고 했으므로, 오늘 밤 책상 등을 켜겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 준서야, 오늘도 눈이 빨개.",
        "M: 침대에서 늦게까지 휴대폰으로 글을 읽었어.",
        "W: 어두운 데서 화면을 얼굴 바로 앞에 두고?",
        "M: 응, 한 시간쯤 지나면 눈이 따가워.",
        "W: 화면이 방보다 훨씬 밝아서 그래.",
        "M: 어두운 방이 읽기에 더 좋은 줄 알았어.",
        "W: 밝은 화면이면 아니야. 그 차이가 눈을 지치게 해.",
        "M: 그럼 읽을 때 등을 켜야 해?",
        "W: 응, 뒤에서 은은하게 비추면 훨씬 나아.",
        "M: 오늘 밤엔 책상 등을 켤게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Hyeri, our club has to make a poster for the food drive."],
        ["W", "I heard. Do you have a design yet?"],
        ["M", "We drew one, but nobody stops to read it."],
        ["W", "Where did you put it up?"],
        ["M", "On the wall beside the second floor stairs."],
        ["W", "People walk fast there. They won't stop."],
        ["M", "Then where should we put the poster?"],
        ["W", "Somewhere people already stand and wait."],
        ["M", "Like the line in front of the cafeteria?"],
        ["W", "Exactly. They wait there for ten minutes every day."],
      ],
      choices: [
        "Nobody eats at the cafeteria.",
        "Then I'll move it there tomorrow.",
        "We already took the poster down.",
        "The stairs are the busiest place.",
        "Let's not make a poster at all.",
      ],
      answer: 2,
      clue: "Exactly. They wait there for ten minutes every day.",
      explanation:
        "여자가 사람들이 매일 10분씩 줄 서 기다리는 급식실 앞이 좋다고 했으므로, 내일 그리로 옮기겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 혜리야, 우리 동아리가 식품 나눔 포스터를 만들어야 해.",
        "W: 들었어. 도안은 나왔어?",
        "M: 그렸는데 아무도 멈춰서 안 읽어.",
        "W: 어디에 붙였어?",
        "M: 2층 계단 옆 벽에.",
        "W: 거기선 사람들이 빨리 걸어. 안 멈춰.",
        "M: 그럼 포스터를 어디에 붙여야 해?",
        "W: 사람들이 이미 서서 기다리는 곳에.",
        "M: 급식실 앞 줄 같은 데?",
        "W: 맞아. 거기서 매일 10분씩 기다리잖아.",
        "M: 그럼 내일 거기로 옮길게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Chaeun이 Geonwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Chaeun : ________________",
      lines: [
        [
          "W",
          "Chaeun and Geonwoo are cleaning the science room after an experiment. " +
            "Geonwoo is carrying a tray of glass beakers toward the sink. " +
            "Chaeun notices that his shoelace has come undone. " +
            "The floor between him and the sink is still wet from the experiment. " +
            "She is afraid he will slip and drop the glass. " +
            "In this situation, what would Chaeun most likely say to Geonwoo?",
        ],
      ],
      choices: [
        "Let's wash the beakers tomorrow.",
        "The floor is completely dry.",
        "I'll buy you new shoes.",
        "Please turn off the water.",
        "Stop. Your shoelace is untied.",
      ],
      answer: 5,
      clue: "She is afraid he will slip and drop the glass.",
      explanation:
        "건우가 신발 끈이 풀린 채로 젖은 바닥에서 유리 비커를 들고 가므로, 멈추고 끈이 풀렸다고 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "W: 채은이와 건우는 실험이 끝난 뒤 과학실을 치우고 있습니다. 건우는 유리 비커가 담긴 쟁반을 들고 개수대로 가고 있습니다. 채은이는 건우의 신발 끈이 풀린 것을 봅니다. 건우와 개수대 사이 바닥은 실험 때문에 아직 젖어 있습니다. 채은이는 건우가 미끄러져 유리를 떨어뜨릴까 봐 걱정합니다. 이런 상황에서 채은이가 건우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
