/** 중2 듣기 12회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 12회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 화분을 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a flower pot?"],
        ["W", "Yes, one for my windowsill at home."],
        ["M", "Do you want a round pot or a square one?"],
        ["W", "A square one, please. Round ones roll when I move them."],
        ["M", "All right. Do you need a saucer under it?"],
        ["W", "Yes, definitely. The water always leaks onto the sill."],
        ["M", "Then we have two left — one plain and one with a stripe."],
        ["W", "I'll take the plain one. My curtains already have stripes."],
        ["M", "Good choice. It's also lighter than the others."],
        ["W", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'll take the plain one. My curtains already have stripes.",
      explanation:
        "여자는 네모난 모양에 받침이 있고 무늬가 없는 화분을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five flower pots shown in one row on a plain white background, each drawn separately and all the same size, clean black line art, no writing anywhere. " +
          "First: a ROUND pot with no saucer under it and no pattern. " +
          "Second: a ROUND pot standing on a flat saucer, with a horizontal stripe around it. " +
          "Third: a SQUARE pot with no saucer under it and a horizontal stripe around it. " +
          "Fourth: a SQUARE pot standing on a flat saucer, with a horizontal stripe around it. " +
          "Fifth: a SQUARE pot standing on a flat saucer, with no pattern at all.",
      },
      translation: [
        "M: 어서 오세요. 화분 찾으시나요?",
        "W: 네, 집 창턱에 둘 거예요.",
        "M: 둥근 것과 네모난 것 중 어느 쪽이 좋으세요?",
        "W: 네모난 걸로요. 둥근 건 옮길 때 굴러요.",
        "M: 알겠습니다. 밑에 받침도 필요하세요?",
        "W: 네, 꼭이요. 물이 늘 창턱으로 새요.",
        "M: 그럼 두 개 남았네요. 하나는 무늬 없는 것, 하나는 줄무늬가 있는 것입니다.",
        "W: 무늬 없는 걸로 할게요. 커튼에 이미 줄무늬가 있어서요.",
        "M: 좋은 선택이세요. 다른 것보다 가볍기도 합니다.",
        "W: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 요리 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junwoo, are you entering the school cooking contest?"],
        ["M", "I'm thinking about it. When is it?"],
        ["W", "Next Thursday, during the afternoon club time."],
        ["M", "Where do we cook?"],
        ["W", "In the home economics room on the third floor."],
        ["M", "Do we work alone or in pairs?"],
        ["W", "In pairs, so you need a partner."],
        ["M", "What do we have to make?"],
        ["W", "One simple dish using vegetables only."],
        ["M", "That sounds fun. I'll ask Minho to be my partner."],
        ["W", "Good idea. Sign up before Tuesday."],
      ],
      choices: ["열리는 날", "장소", "참가 방식", "만들 음식", "심사 기준"],
      answer: 5,
      clue: "One simple dish using vegetables only.",
      explanation:
        "날짜(다음 주 목요일), 장소(3층 가정실), 참가 방식(2인 1조), 만들 음식(채소만 쓴 요리)은 언급되지만 심사 기준은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준우야, 교내 요리 대회 나갈 거야?",
        "M: 생각 중이야. 언제야?",
        "W: 다음 주 목요일, 오후 동아리 시간에.",
        "M: 어디서 요리해?",
        "W: 3층 가정실에서.",
        "M: 혼자 해, 둘이 해?",
        "W: 둘이 한 조야. 짝이 필요해.",
        "M: 뭘 만들어야 해?",
        "W: 채소만 써서 간단한 요리 하나.",
        "M: 재미있겠다. 민호한테 같이 하자고 해야지.",
        "W: 좋은 생각이야. 화요일 전에 신청해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sumin. It's Dohyun. Are you at home?"],
        ["W", "Yes, I just got back. What's up?"],
        ["M", "Do you remember the badminton match tomorrow?"],
        ["W", "Of course. At the gym at four, right?"],
        ["M", "That's the thing. The gym floor is being repaired."],
        ["W", "So we can't play there?"],
        ["M", "No. We're moving to the outdoor court behind the library."],
        ["W", "Same time?"],
        ["M", "Same time, four o'clock. Bring a jacket, it's cold outside."],
        ["W", "Thanks for telling me. I'll let Jina know too."],
      ],
      choices: [
        "경기 시간을 바꾸려고",
        "경기에 못 간다고 말하려고",
        "라켓을 빌려달라고 하려고",
        "경기 장소가 바뀐 것을 알리려고",
        "체육관 예약을 부탁하려고",
      ],
      answer: 4,
      clue: "We're moving to the outdoor court behind the library.",
      explanation:
        "남자는 체육관 바닥 공사로 경기 장소가 도서관 뒤 야외 코트로 바뀐 것을 알리려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 수민아. 도현이야. 집이야?",
        "W: 응, 방금 들어왔어. 무슨 일이야?",
        "M: 내일 배드민턴 경기 기억하지?",
        "W: 그럼. 네 시에 체육관에서지?",
        "M: 그게 문제야. 체육관 바닥을 수리한대.",
        "W: 그럼 거기서 못 해?",
        "M: 못 해. 도서관 뒤 야외 코트로 옮겨.",
        "W: 시간은 그대로야?",
        "M: 그대로 네 시. 밖이라 추우니까 겉옷 가져와.",
        "W: 알려 줘서 고마워. 지나한테도 말할게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yeji, what time does the concert start on Saturday?"],
        ["W", "At 7:00 p.m. The doors open thirty minutes before."],
        ["M", "Then let's meet when the doors open."],
        ["W", "That's 6:30. But I want to buy a program book first."],
        ["M", "The shop in the lobby opens at six."],
        ["W", "Then let's meet twenty minutes earlier than we said."],
        ["M", "Twenty minutes earlier? All right."],
        ["W", "I'll wait by the main entrance."],
        ["M", "See you then."],
      ],
      choices: ["6:00 p.m.", "6:10 p.m.", "6:20 p.m.", "6:30 p.m.", "6:40 p.m."],
      answer: 2,
      clue: "Then let's meet twenty minutes earlier than we said.",
      explanation:
        "7시 공연의 30분 전인 6시 30분에서 안내 책자를 사려고 20분 더 일찍 만나기로 했으므로 6시 10분이다. 따라서 답은 ②이다.",
      translation: [
        "M: 예지야, 토요일 공연 몇 시에 시작해?",
        "W: 저녁 7시. 30분 전에 문을 열어.",
        "M: 그럼 문 열 때 만나자.",
        "W: 6시 30분이네. 그런데 안내 책자를 먼저 사고 싶어.",
        "M: 로비 가게는 여섯 시에 열어.",
        "W: 그럼 말한 것보다 20분 더 일찍 만나자.",
        "M: 20분 일찍? 알겠어.",
        "W: 정문 옆에서 기다릴게.",
        "M: 그때 보자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyoung, you're smiling all the way to school today."],
        ["W", "My grandmother is coming to visit this weekend."],
        ["M", "Haven't you seen her for a while?"],
        ["W", "Two years. She lives in Jeju and travels are hard for her."],
        ["M", "Two years is a long time."],
        ["W", "I've already cleaned my room three times."],
        ["M", "Three times? She'll be impressed."],
        ["W", "I hope so. I even drew her a welcome card."],
      ],
      choices: ["upset", "bored", "excited", "scared", "sorry"],
      answer: 3,
      clue: "My grandmother is coming to visit this weekend.",
      explanation:
        "여자는 2년 만에 오시는 할머니를 기다리며 방을 세 번이나 치우고 환영 카드까지 그렸다. 따라서 심정은 ③(신난)이다.",
      translation: [
        "M: 채영아, 오늘 학교 오는 내내 웃고 있네.",
        "W: 이번 주말에 할머니가 오셔.",
        "M: 오랜만에 뵙는 거야?",
        "W: 2년 만이야. 제주에 사시는데 오시기가 힘드셔.",
        "M: 2년이면 오래됐다.",
        "W: 벌써 내 방을 세 번이나 치웠어.",
        "M: 세 번이나? 할머니가 놀라시겠다.",
        "W: 그러면 좋겠어. 환영 카드도 그렸어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "How was your trip to Busan?"],
        ["M", "It was great. The sea was beautiful."],
        ["W", "Excuse me, you left your phone on the table."],
        ["M", "Oh, thank you! I didn't notice."],
        ["W", "What time do you usually get up?"],
        ["M", "Around seven in the morning."],
        ["W", "Can I open the window?"],
        ["M", "Sure, it's a bit hot in here."],
        ["W", "Do you want more rice?"],
        ["M", "No, thanks. I'm full."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, you left your phone on the table.",
      explanation:
        "그림은 한 사람이 탁자에 두고 가는 휴대폰을 가리키며 알려 주는 장면이므로, 휴대폰을 두고 갔다고 말해 주는 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "Inside a small cafe. A man is standing up and starting to walk away from a table, leaving his mobile phone lying on the table behind him. A woman sitting at the next table is holding out her hand and pointing at the phone to call him back. Both are drawn clearly. Simple background with a counter and a window.",
      },
      translation: [
        "① W: 부산 여행 어땠어? / M: 좋았어. 바다가 아름다웠어.",
        "② W: 실례합니다, 탁자에 휴대폰을 두고 가셨어요. / M: 아, 감사합니다! 몰랐네요.",
        "③ W: 보통 몇 시에 일어나? / M: 아침 일곱 시쯤.",
        "④ W: 창문 열어도 될까요? / M: 그럼요, 여기 좀 덥네요.",
        "⑤ W: 밥 더 줄까? / M: 아니, 괜찮아. 배불러.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangmin, are you going to the gym this afternoon?"],
        ["M", "Yes, I have basketball practice at four."],
        ["W", "Could you bring back my water bottle?"],
        ["M", "Sure. Where did you leave it?"],
        ["W", "On the bench near the door. It's blue with a white cap."],
        ["M", "I'll look for it. Anything else?"],
        ["W", "No, just the bottle. Thanks a lot."],
        ["M", "No problem. I'll give it to you tomorrow morning."],
      ],
      choices: ["농구 연습하기", "체육관 청소하기", "벤치 옮기기", "물병 가져다주기", "가방 챙기기"],
      answer: 4,
      clue: "Could you bring back my water bottle?",
      explanation:
        "여자는 체육관에 가는 남자에게 문 옆 벤치에 두고 온 물병을 가져다 달라고 부탁한다. 따라서 답은 ④이다.",
      translation: [
        "W: 상민아, 오늘 오후에 체육관 가?",
        "M: 응, 네 시에 농구 연습 있어.",
        "W: 내 물병 좀 가져다줄 수 있어?",
        "M: 그럼. 어디에 뒀어?",
        "W: 문 옆 벤치에. 파란색이고 뚜껑이 흰색이야.",
        "M: 찾아볼게. 또 있어?",
        "W: 아니, 물병만. 정말 고마워.",
        "M: 문제없어. 내일 아침에 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Family Sports Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about Family Sports Day."],
        ["M", "It will be held on the last Saturday of this month."],
        ["M", "All the games take place on the school playground."],
        ["M", "Each student may bring up to two family members."],
        ["M", "Lunch boxes will be given to everyone who takes part."],
        ["M", "We hope to see you and your family there."],
      ],
      choices: ["열리는 날", "장소", "동반 인원", "제공되는 것", "경기 종목"],
      answer: 5,
      clue: "Lunch boxes will be given to everyone who takes part.",
      explanation:
        "날짜(이달 마지막 토요일), 장소(운동장), 동반 인원(가족 두 명까지), 제공되는 것(도시락)은 언급되지만 경기 종목은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 가족 체육대회에 대해 알려 드리겠습니다.",
        "M: 이달 마지막 주 토요일에 열립니다.",
        "M: 모든 경기는 학교 운동장에서 진행됩니다.",
        "M: 학생마다 가족을 두 명까지 데려올 수 있습니다.",
        "M: 참가하는 모든 분께 도시락을 드립니다.",
        "M: 가족과 함께 오시기를 기다리겠습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "This is a place where you go to send something far away."],
        ["W", "You bring a box or an envelope with you."],
        ["W", "A worker weighs it and tells you the price."],
        ["W", "You can also buy stamps here."],
        ["W", "Many people come here at the end of the year."],
      ],
      choices: ["은행", "병원", "우체국", "도서관", "약국"],
      answer: 3,
      clue: "You can also buy stamps here.",
      explanation:
        "멀리 무언가를 보내러 가고, 무게를 달아 값을 알려 주며 우표를 살 수 있다고 했으므로 우체국이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이곳은 무언가를 멀리 보내려고 가는 곳입니다.",
        "W: 상자나 봉투를 가지고 갑니다.",
        "W: 직원이 무게를 달아 값을 알려 줍니다.",
        "W: 여기서 우표도 살 수 있습니다.",
        "W: 연말에 많은 사람이 이곳에 옵니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How do you spell your last name?"],
        ["W", "It's K-I-M, Kim."],
        ["M", "Would you like something to drink?"],
        ["W", "Yes, a glass of water, please."],
        ["M", "Where did you find my notebook?"],
        ["W", "I'll buy a new notebook tomorrow."],
        ["M", "How was the test this morning?"],
        ["W", "It was harder than I expected."],
        ["M", "Shall we take the subway?"],
        ["W", "Good idea. It's faster."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Where did you find my notebook?",
      explanation:
        "내 공책을 어디서 찾았는지 묻는 말에 내일 새 공책을 사겠다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① M: 성을 어떻게 쓰세요? / W: K-I-M, 김입니다.",
        "② M: 마실 것 드릴까요? / W: 네, 물 한 잔 주세요.",
        "③ M: 내 공책을 어디서 찾았어? / W: 나는 내일 새 공책을 살 거야.",
        "④ M: 오늘 아침 시험 어땠어? / W: 생각보다 어려웠어.",
        "⑤ M: 지하철 탈까? / W: 좋은 생각이야. 그게 더 빨라.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunjun, the class photo is tomorrow morning."],
        ["M", "I know. I'll wear my school uniform."],
        ["W", "Did you bring the name list to the photo studio?"],
        ["M", "Not yet. I was going to do it after dinner."],
        ["W", "The studio closes at six today."],
        ["M", "Six? Then I have to go right now."],
        ["W", "Yes, hurry. I'll tell our teacher you're on the way."],
        ["M", "Thanks. I'll run there and come back."],
      ],
      choices: ["교복 다리기", "사진관 예약하기", "선생님께 말씀드리기", "저녁 먹기", "명단 가져다주기"],
      answer: 5,
      clue: "Six? Then I have to go right now.",
      explanation:
        "사진관이 여섯 시에 닫으므로 남자는 지금 바로 명단을 가져다주러 가겠다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 현준아, 내일 아침이 학급 사진이야.",
        "M: 알아. 교복 입고 올게.",
        "W: 사진관에 명단 가져다줬어?",
        "M: 아직. 저녁 먹고 하려고 했어.",
        "W: 사진관 오늘 여섯 시에 닫아.",
        "M: 여섯 시? 그럼 지금 바로 가야겠다.",
        "W: 응, 서둘러. 네가 가고 있다고 선생님께 말씀드릴게.",
        "M: 고마워. 뛰어갔다 올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 방과 후 강좌를 고르시오.",
      lines: [
        ["M", "Suyeon, have you chosen an after-school class?"],
        ["W", "Not yet. Five are still open."],
        ["M", "Is there a day you can't come?"],
        ["W", "Friday. I go to my cousin's house every Friday."],
        ["M", "All right, one is gone. What about the time?"],
        ["W", "It has to start after four. My tutoring ends at three forty."],
        ["M", "Then another is out. Three are left."],
        ["W", "And I can't pay more than forty thousand won."],
        ["M", "One of them is over that."],
        ["W", "So two left. One of them is in the annex building."],
        ["M", "That's a ten-minute walk. Take the one in the main building."],
        ["W", "Agreed. I'll sign up today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "That's a ten-minute walk. Take the one in the main building.",
      explanation:
        "금요일인 ①을 빼고, 3시 30분 시작인 ②를 빼고, 4만 원을 넘는 ⑤를 뺀다. 남은 ③과 ④ 중 본관에 있는 것은 ③이므로 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "금요일 / 오후 4시 / 35,000원 / 본관" },
          { no: 2, label: "②", value: "화요일 / 오후 3시 30분 / 36,000원 / 본관" },
          { no: 3, label: "③", value: "수요일 / 오후 4시 / 38,000원 / 본관" },
          { no: 4, label: "④", value: "목요일 / 오후 5시 / 39,000원 / 별관" },
          { no: 5, label: "⑤", value: "수요일 / 오후 4시 30분 / 45,000원 / 본관" },
        ],
      },
      translation: [
        "M: 수연아, 방과 후 강좌 정했어?",
        "W: 아직. 다섯 개가 남아 있어.",
        "M: 못 오는 요일 있어?",
        "W: 금요일. 매주 금요일에 사촌 집에 가.",
        "M: 그럼 하나 빠지네. 시간은?",
        "W: 네 시 이후에 시작해야 해. 과외가 3시 40분에 끝나.",
        "M: 그럼 하나 더 빠진다. 세 개 남았어.",
        "W: 그리고 4만 원 넘게는 못 내.",
        "M: 하나가 그걸 넘네.",
        "W: 그럼 둘 남았다. 하나는 별관에 있네.",
        "M: 거긴 걸어서 10분이야. 본관에 있는 걸로 해.",
        "W: 좋아. 오늘 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 전시회에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Jiyeon, the photo exhibition runs from the fifteenth to the twentieth."],
        ["W", "That's six days. When can you go?"],
        ["M", "Not on weekdays. I have club activities every afternoon."],
        ["W", "Then the weekend. The nineteenth is Saturday."],
        ["M", "I have a family dinner on the nineteenth."],
        ["W", "Then Sunday, the twentieth?"],
        ["M", "That works. The exhibition closes at five that day."],
        ["W", "Let's go in the morning, then."],
        ["M", "Good. I'll meet you at the station."],
      ],
      choices: ["15일", "17일", "19일", "20일", "21일"],
      answer: 4,
      clue: "Then Sunday, the twentieth?",
      explanation:
        "평일은 동아리 활동이 있고 19일 토요일은 가족 식사여서 20일 일요일에 가기로 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 지연아, 사진전이 15일부터 20일까지 해.",
        "W: 엿새네. 언제 갈 수 있어?",
        "M: 평일은 안 돼. 오후마다 동아리 활동이 있어.",
        "W: 그럼 주말이네. 19일이 토요일이야.",
        "M: 19일엔 가족 식사가 있어.",
        "W: 그럼 일요일인 20일은?",
        "M: 괜찮아. 그날은 다섯 시에 닫아.",
        "W: 그럼 오전에 가자.",
        "M: 좋아. 역에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaehyun, did you go to the water park last weekend?"],
        ["W", "You were talking about it all week."],
        ["M", "I couldn't. My cousin came to stay with us."],
        ["W", "Oh, so you stayed home?"],
        ["M", "Not exactly. We went fishing at the river."],
        ["W", "Fishing? Did you catch anything?"],
        ["M", "Two small fish, and we put them back."],
        ["W", "That still sounds fun."],
        ["M", "It was. We were there from morning until sunset."],
      ],
      choices: ["워터파크 가기", "집에서 쉬기", "사촌 만나러 가기", "낚시하기", "자전거 타기"],
      answer: 4,
      clue: "Not exactly. We went fishing at the river.",
      explanation:
        "남자는 사촌이 와서 워터파크에 가지 못하고 대신 강에 가서 낚시를 했다고 말한다. 따라서 답은 ④이다.",
      translation: [
        "W: 재현아, 지난 주말에 워터파크 갔어?",
        "W: 일주일 내내 그 얘기 했잖아.",
        "M: 못 갔어. 사촌이 우리 집에 왔거든.",
        "W: 아, 그럼 집에 있었어?",
        "M: 꼭 그런 건 아니야. 강에 낚시하러 갔어.",
        "W: 낚시? 뭐 잡았어?",
        "M: 작은 물고기 두 마리. 다시 놓아 줬어.",
        "W: 그래도 재미있었겠다.",
        "M: 재미있었어. 아침부터 해 질 때까지 있었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good afternoon, students. This is the library."],
        ["W", "Some books borrowed in September have not come back."],
        ["W", "Please check your bag and your desk at home."],
        ["W", "You can return them at the desk or in the box outside."],
        ["W", "There is no late fee until the end of this week."],
        ["W", "After that, you cannot borrow new books."],
      ],
      choices: [
        "도서관 이용 시간을 알리려고",
        "연체된 책의 반납을 요청하려고",
        "새 책 목록을 소개하려고",
        "도서관 공사를 안내하려고",
        "독서 행사 참여를 권하려고",
      ],
      answer: 2,
      clue: "Some books borrowed in September have not come back.",
      explanation:
        "9월에 빌려 간 책이 돌아오지 않았다며 이번 주까지 반납해 달라고 요청하고 있다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 도서관입니다.",
        "W: 9월에 빌려 간 책 중 아직 돌아오지 않은 것이 있습니다.",
        "W: 가방과 집 책상을 확인해 주세요.",
        "W: 데스크나 밖에 있는 반납함에 넣으시면 됩니다.",
        "W: 이번 주말까지는 연체료가 없습니다.",
        "W: 그 뒤에는 새 책을 빌릴 수 없습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Welcome to the bakery."],
        ["M", "Hi. I'd like three loaves of bread, please."],
        ["W", "Bread is five dollars a loaf today."],
        ["M", "All right. And two small cookies."],
        ["W", "Cookies are two dollars each."],
        ["M", "So the total is nineteen dollars?"],
        ["W", "Yes, but there's a four-dollar discount if you spend over fifteen."],
        ["M", "That's lucky. Here you are."],
      ],
      choices: ["$13", "$15", "$17", "$19", "$21"],
      answer: 2,
      clue: "there's a four-dollar discount if you spend over fifteen",
      explanation:
        "빵 5달러씩 세 개면 15달러, 쿠키 2달러씩 두 개면 4달러로 합계 19달러이다. 15달러를 넘어 4달러 할인되므로 15달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 빵집입니다.",
        "M: 안녕하세요. 식빵 세 덩이 주세요.",
        "W: 오늘 빵은 한 덩이에 5달러입니다.",
        "M: 네. 그리고 작은 쿠키 두 개도요.",
        "W: 쿠키는 하나에 2달러입니다.",
        "M: 그럼 모두 19달러인가요?",
        "W: 네, 그런데 15달러 넘게 사시면 4달러 할인됩니다.",
        "M: 운이 좋네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minjae, did you get your bicycle fixed?"],
        ["M", "Not yet. The shop near my house was closed again."],
        ["W", "Was it closed for the holiday last week?"],
        ["M", "I'm not sure. There was no sign on the door at all."],
        ["W", "That's strange. How long has it been closed?"],
        ["M", "Almost two weeks now, and my back tyre is still flat."],
        ["W", "My brother goes to a shop right by the station."],
        ["M", "Is that one open on weekdays?"],
        ["W", "Yes, from ten in the morning until eight in the evening."],
      ],
      choices: [
        "Then I'll take my bicycle there tomorrow.",
        "My bicycle is almost new.",
        "The shop near my house is bigger.",
        "I don't ride my bicycle in winter.",
        "You should fix it yourself.",
      ],
      answer: 1,
      clue: "Yes, from ten in the morning until eight.",
      explanation:
        "역 옆 가게가 평일 열 시부터 여덟 시까지 연다는 말을 들었으므로, 내일 자전거를 가져가겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 민재야, 자전거 고쳤어?",
        "M: 아직. 집 근처 가게가 문을 닫았더라.",
        "W: 명절이라 닫은 거야?",
        "M: 잘 모르겠어. 문에 아무 안내도 없었어.",
        "W: 우리 오빠는 역 옆 가게에 가.",
        "M: 평일에 열어?",
        "W: 응, 아침 열 시부터 여덟 시까지.",
        "M: 그럼 내일 자전거 가져가야겠다.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sohee, are you coming to the movie club tomorrow?"],
        ["W", "I'd like to, but I haven't watched this month's film yet."],
        ["M", "How much of it have you seen so far?"],
        ["W", "Only the first half. I fell asleep watching it last night."],
        ["M", "What is the film about, anyway?"],
        ["W", "A family that moves to an island and opens a small shop."],
        ["M", "That sounds slow. Do you have time to finish it tonight?"],
        ["W", "I have two assignments due tomorrow, so probably not."],
        ["M", "Don't worry. Tomorrow we only discuss the beginning."],
      ],
      choices: [
        "Then I'll come after all.",
        "I watched the whole film twice.",
        "The club meets in room 201.",
        "I don't like watching movies.",
        "You should join the club too.",
      ],
      answer: 1,
      clue: "Tomorrow we only discuss the beginning.",
      explanation:
        "내일은 앞부분만 이야기한다는 말을 들었으므로, 그럼 가겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 소희야, 내일 영화 동아리 올 거야?",
        "W: 가고 싶은데 이번 달 영화를 아직 못 봤어.",
        "M: 얼마나 봤어?",
        "W: 앞부분만. 어젯밤에 잠들었어.",
        "M: 오늘 밤에 마저 볼 시간 있어?",
        "W: 과제가 두 개라 아마 못 볼 거야.",
        "M: 걱정 마. 내일은 앞부분만 이야기해.",
        "W: 그럼 나도 갈게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Dongwoo, are you taking the bus to the museum on Saturday?"],
        ["M", "I was going to, but the bus takes almost an hour each way."],
        ["W", "An hour? That's long for that distance."],
        ["M", "It stops at every corner on the way downtown."],
        ["W", "How early would you have to leave, then?"],
        ["M", "Before eight, and the museum opens at ten."],
        ["W", "That's too early for a Saturday. Have you thought about the subway?"],
        ["M", "I didn't even know the subway goes there."],
        ["W", "It does. Line two stops right in front of the museum."],
      ],
      choices: [
        "Then I'll take the subway instead.",
        "The bus is cheaper than the subway.",
        "I've been to that museum twice.",
        "The museum opens at ten o'clock.",
        "You should walk there with me.",
      ],
      answer: 1,
      clue: "It does. Line two stops right in front of the museum.",
      explanation:
        "2호선이 박물관 바로 앞에 선다는 말을 들었으므로, 지하철을 타겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 동우야, 토요일에 박물관 갈 때 버스 타?",
        "M: 그러려고 했는데 버스로 거의 한 시간 걸려.",
        "W: 한 시간? 그 거리에 오래 걸리네.",
        "M: 가는 길에 모든 모퉁이마다 서.",
        "W: 지하철은 생각해 봤어?",
        "M: 지하철이 거기 가는 줄 몰랐어.",
        "W: 가. 2호선이 박물관 바로 앞에 서.",
        "M: 그럼 지하철을 타야겠다.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nara가 Junsu에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Nara : ________________",
      lines: [
        ["M", "Nara and Junsu are on the same school relay team."],
        ["M", "Today they are practising on the school track."],
        ["M", "Junsu runs very fast but often drops the baton at the handover."],
        ["M", "He has dropped it three times this week."],
        ["M", "Nara has watched him and noticed that he looks back while running."],
        ["M", "She thinks he would keep the baton if he looked forward instead."],
        ["M", "In this situation, what would Nara most likely say to Junsu?"],
      ],
      choices: [
        "Let's practise again tomorrow morning.",
        "Try looking forward when you take the baton.",
        "You should run a little more slowly.",
        "I'll take your place in the race.",
        "The baton is too heavy for you.",
      ],
      answer: 2,
      clue: "She thinks he would keep the baton if he looked forward instead.",
      explanation:
        "나라는 준수가 달리면서 뒤를 돌아보는 것이 문제라고 보고, 바통을 받을 때 앞을 보라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 나라와 준수는 같은 학교 이어달리기 팀입니다.",
        "M: 오늘 두 사람은 학교 운동장 트랙에서 연습하고 있습니다.",
        "M: 준수는 아주 빠르지만 바통을 주고받을 때 자주 떨어뜨립니다.",
        "M: 이번 주에만 세 번 떨어뜨렸습니다.",
        "M: 나라는 준수가 달리면서 뒤를 돌아본다는 것을 알아챘습니다.",
        "M: 앞을 보면 바통을 놓치지 않을 것이라고 생각합니다.",
        "M: 이런 상황에서 나라가 준수에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
