/** 중2 듣기 19회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 19회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 시계를 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a watch?"],
        ["M", "Yes, one I can wear to school every day."],
        ["W", "We have watches with a leather band and watches with a metal band."],
        ["M", "A leather one, please. The metal ones are heavy on my wrist."],
        ["W", "All right. Do you want a round face or a square one?"],
        ["M", "A square face. It's easier to read at a glance."],
        ["W", "Then two are left. One has numbers on the face and one has only lines."],
        ["M", "The one with numbers, please. I still count the lines by mistake."],
        ["W", "Good choice. This one is also water-resistant."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "The one with numbers, please. I still count the lines by mistake.",
      explanation:
        "남자는 가죽 줄 시계를, 사각형 판으로, 숫자가 적힌 것을 고른다. 따라서 답은 ③이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five wristwatches shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere except the numbers described. " +
          "Watch 1: a plain LEATHER STRAP with a buckle, a ROUND face, twelve NUMBERS printed around the face. " +
          "Watch 2: a plain LEATHER STRAP with a buckle, a SQUARE face, only short LINES around the face and no numbers. " +
          "Watch 3: a plain LEATHER STRAP with a buckle, a SQUARE face, twelve NUMBERS printed around the face. " +
          "Watch 4: a METAL LINK BRACELET made of small chain links, a SQUARE face, twelve NUMBERS printed around the face. " +
          "Watch 5: a METAL LINK BRACELET made of small chain links, a ROUND face, only short LINES around the face and no numbers.",
      },
      translation: [
        "W: 안녕하세요. 손목시계 찾으세요?",
        "M: 네, 날마다 학교에 차고 갈 거예요.",
        "W: 가죽 줄과 금속 줄이 있습니다.",
        "M: 가죽으로요. 금속은 손목에 무거워요.",
        "W: 알겠습니다. 판은 둥근 게 좋으세요, 네모난 게 좋으세요?",
        "M: 네모난 걸로요. 한눈에 보기 쉬워서요.",
        "W: 그럼 두 개 남았네요. 하나는 숫자가 있고 하나는 선만 있습니다.",
        "M: 숫자가 있는 걸로요. 아직도 선을 잘못 세거든요.",
        "W: 좋은 선택이세요. 이건 생활 방수도 됩니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 체육대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Sohee, do you know anything about the sports day?"],
        ["W", "A little. Why, are you on the team?"],
        ["M", "I might be, but the notice was gone when I got there."],
        ["W", "It's on the second Friday of next month, all day."],
        ["M", "All day? Where do we hold it?"],
        ["W", "On the main playground, and the gym if it rains."],
        ["M", "What events are there?"],
        ["W", "Relay, tug of war, and a class dance."],
        ["M", "A dance? That's new."],
        ["W", "It is, and every class has to enter one."],
        ["M", "Do we need anything?"],
        ["W", "Your class T-shirt and a water bottle."],
        ["M", "Then I'll tell our class tomorrow morning."],
      ],
      choices: ["열리는 날", "장소", "경기 종목", "준비물", "우승 상품"],
      answer: 5,
      clue: "Your class T-shirt and a water bottle.",
      explanation:
        "날짜(다음 달 둘째 금요일), 장소(운동장과 체육관), 종목(이어달리기·줄다리기·학급 춤), 준비물(반 티셔츠와 물병)은 언급되지만 우승 상품은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 소희야, 체육대회에 대해 뭐 아는 거 있어?",
        "W: 조금. 왜, 너 선수로 나가?",
        "M: 나갈지도 모르는데, 가 보니 공지가 없어졌더라.",
        "W: 다음 달 둘째 금요일, 하루 종일 해.",
        "M: 하루 종일? 어디서 하는데?",
        "W: 큰 운동장에서, 비 오면 체육관에서.",
        "M: 종목이 뭐야?",
        "W: 이어달리기, 줄다리기, 그리고 학급 춤.",
        "M: 춤? 그건 새롭네.",
        "W: 새로 생겼어. 반마다 하나씩 꼭 나가야 해.",
        "M: 뭐 준비할 거 있어?",
        "W: 반 티셔츠랑 물병.",
        "M: 그럼 내일 아침에 우리 반에 말할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junho. It's Yerin from the science club."],
        ["M", "Hi, Yerin. Is something wrong?"],
        ["W", "Not really, but Saturday's experiment needs one more thing."],
        ["M", "What thing?"],
        ["W", "An empty plastic bottle, one for each person."],
        ["M", "The teacher didn't mention that."],
        ["W", "She decided this afternoon, after she tried it herself."],
        ["M", "Then I'll bring two, in case somebody forgets."],
        ["W", "That would help. Thanks, and see you on Saturday."],
      ],
      choices: [
        "실험이 취소되었다고 알리려고",
        "실험 시간이 바뀐 것을 알리려고",
        "가져올 것이 늘었다고 알리려고",
        "동아리 가입을 권하려고",
        "실험실 청소를 부탁하려고",
      ],
      answer: 3,
      clue: "An empty plastic bottle, one for each person.",
      explanation:
        "여자는 토요일 실험에 빈 플라스틱 병을 하나씩 가져와야 한다고 알리려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준호야. 과학 동아리 예린이야.",
        "M: 안녕, 예린아. 무슨 일 있어?",
        "W: 별일은 아니고, 토요일 실험에 하나 더 필요한 게 생겼어.",
        "M: 뭐가 필요한데?",
        "W: 빈 플라스틱 병, 한 사람에 하나씩.",
        "M: 선생님이 그런 말씀은 없으셨는데.",
        "W: 오늘 오후에 직접 해 보시고 정하셨대.",
        "M: 그럼 나는 두 개 가져갈게. 누가 잊어버릴 수도 있으니까.",
        "W: 그러면 좋지. 고마워, 토요일에 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minjae, what time should we meet at the library tomorrow?"],
        ["M", "The study room opens at nine."],
        ["W", "And we have to get a seat card at the desk."],
        ["M", "How about nine o'clock, then?"],
        ["W", "On Saturdays the cards are gone by nine ten. Let's go earlier."],
        ["M", "How long does it take you to get there?"],
        ["W", "Fifteen minutes on foot."],
        ["M", "Then let's meet at eight forty-five."],
        ["W", "Eight forty-five is fine. I'll wait at the front steps."],
      ],
      choices: ["8:15 a.m.", "8:30 a.m.", "8:45 a.m.", "9:00 a.m.", "9:15 a.m."],
      answer: 3,
      clue: "Then let's meet at eight forty-five.",
      explanation:
        "열람실이 9시에 열고 자리표가 금방 나가서 두 사람은 8시 45분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 민재야, 내일 도서관에서 몇 시에 만날까?",
        "M: 열람실이 9시에 열어.",
        "W: 그리고 데스크에서 자리표도 받아야 하잖아.",
        "M: 그럼 9시는 어때?",
        "W: 토요일에는 9시 10분이면 자리표가 다 나가. 더 일찍 가자.",
        "M: 거기까지 얼마나 걸려?",
        "W: 걸어서 15분.",
        "M: 그럼 8시 45분에 만나자.",
        "W: 8시 45분 좋아. 정문 계단에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaerin, you've been quiet since lunch."],
        ["W", "I left my grandmother's ring in the changing room."],
        ["M", "The one you always wear on a chain?"],
        ["W", "She gave it to me last winter. It was the last thing she gave me."],
        ["M", "Did you go back and look?"],
        ["W", "Twice. The second time I moved every bench."],
        ["M", "Have you told the office?"],
        ["W", "Not yet. I keep hoping I'll find it myself."],
      ],
      choices: ["excited", "upset", "bored", "proud", "pleased"],
      answer: 2,
      clue: "She gave it to me last winter. It was the last thing she gave me.",
      explanation:
        "할머니가 주신 마지막 물건인 반지를 잃어버려 계속 찾고 있으므로 여자는 몹시 속상해하고 있다. 따라서 답은 ②이다.",
      translation: [
        "M: 채린아, 점심 먹고부터 조용하네.",
        "W: 탈의실에 할머니 반지를 두고 왔어.",
        "M: 늘 목걸이에 걸고 다니던 그거?",
        "W: 지난겨울에 주셨어. 할머니가 주신 마지막 물건이야.",
        "M: 다시 가서 찾아봤어?",
        "W: 두 번. 두 번째는 의자를 다 옮겨 봤어.",
        "M: 행정실에는 말했어?",
        "W: 아직. 자꾸 내가 찾을 것 같아서.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "Excuse me, could you take a photo of us?"],
        ["W", "Of course. Say cheese."],
        ["M", "How much is this scarf?"],
        ["W", "Fifteen dollars."],
        ["M", "What time does the shop close?"],
        ["W", "At eight on weekdays."],
        ["M", "Is this the right bus for the museum?"],
        ["W", "No, you need the number five."],
        ["M", "Can I use your phone?"],
        ["W", "Sure, go ahead."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Excuse me, could you take a photo of us?",
      explanation:
        "그림은 두 사람이 나란히 서서 지나가던 사람에게 휴대전화를 건네며 사진을 부탁하는 장면이므로 ①이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "In front of a large fountain in a park, clean black line art on a plain white background, no writing or letters anywhere. A MAN and a CHILD are standing side by side smiling, and the man is holding out a mobile phone toward a WOMAN who has stopped in front of them. The woman is reaching out to take the phone and is looking at the two of them. All three people are drawn clearly. Trees and a path are in the background.",
      },
      translation: [
        "① M: 실례지만 저희 사진 좀 찍어 주시겠어요? / W: 그럼요. 하나, 둘, 셋.",
        "② M: 이 목도리 얼마예요? / W: 15달러입니다.",
        "③ M: 가게 몇 시에 닫아요? / W: 평일에는 8시에요.",
        "④ M: 박물관 가는 버스 이거 맞나요? / W: 아니요, 5번을 타셔야 해요.",
        "⑤ M: 휴대전화 좀 써도 될까요? / W: 그럼요, 쓰세요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, you're going to the gym after school, aren't you?"],
        ["M", "Yes, the basketball club practises until six."],
        ["W", "Could you do one thing for me while you're there?"],
        ["M", "Sure. What is it?"],
        ["W", "The class banner is on the floor behind the stage."],
        ["M", "Do you want me to bring it back to the classroom?"],
        ["W", "No, please hang it on the rail so it doesn't get stepped on."],
        ["M", "Which rail?"],
        ["W", "The one along the side wall. It's long enough."],
        ["M", "Got it. I'll do it before practice starts."],
      ],
      choices: ["현수막을 가져다주기", "현수막을 난간에 걸어 주기", "현수막을 새로 만들기", "체육관 청소하기", "연습을 도와주기"],
      answer: 2,
      clue: "No, please hang it on the rail so it doesn't get stepped on.",
      explanation:
        "여자는 바닥에 있는 학급 현수막을 밟히지 않게 난간에 걸어 달라고 부탁한다. 가져다 달라는 것이 아니다. 따라서 답은 ②이다.",
      translation: [
        "W: 도현아, 방과 후에 체육관 가지?",
        "M: 응, 농구부가 6시까지 연습해.",
        "W: 거기 있는 동안 하나만 부탁할게.",
        "M: 그래. 뭔데?",
        "W: 학급 현수막이 무대 뒤 바닥에 있어.",
        "M: 교실로 가져다줄까?",
        "W: 아니, 밟히지 않게 난간에 걸어 줘.",
        "M: 어느 난간?",
        "W: 옆벽을 따라 있는 거. 충분히 길어.",
        "M: 알겠어. 연습 시작 전에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Winter Book Concert에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Here is news about the Winter Book Concert."],
        ["W", "It will be held on the last Tuesday of this month, in the afternoon."],
        ["W", "We will use the library on the second floor, not the hall."],
        ["W", "Six students will read a short piece they chose themselves."],
        ["W", "Anyone may come and listen; you do not need to sign up."],
        ["W", "Come and hear what your friends have been reading."],
      ],
      choices: ["열리는 날", "장소", "진행 방식", "참가 방법", "읽는 책의 종류"],
      answer: 5,
      clue: "Anyone may come and listen; you do not need to sign up.",
      explanation:
        "날짜(이달 마지막 화요일), 장소(2층 도서관), 진행 방식(여섯 명이 고른 글을 읽음), 참가 방법(신청 없이 누구나)은 언급되지만 읽는 책의 종류는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. Winter Book Concert 소식입니다.",
        "W: 이달 마지막 화요일 오후에 열립니다.",
        "W: 강당이 아니라 2층 도서관에서 합니다.",
        "W: 학생 여섯 명이 각자 고른 짧은 글을 읽습니다.",
        "W: 누구나 와서 들을 수 있고 신청은 필요 없습니다.",
        "W: 친구들이 무엇을 읽고 있는지 들으러 오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You will find one of these in the corridor of every school."],
        ["M", "It is a tall machine with a button and a small round spout."],
        ["M", "You press the button and cold water comes out in an arch."],
        ["M", "In summer there is a queue in front of it after every class."],
        ["M", "Someone from the office checks the filter twice a year."],
      ],
      choices: ["소화기", "정수기", "사물함", "신발장", "게시판"],
      answer: 2,
      clue: "You press the button and cold water comes out in an arch.",
      explanation:
        "단추를 누르면 찬물이 나오고 여름에 줄을 서며 여과기를 점검한다고 했으므로 정수기이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 학교마다 복도에 하나씩 있습니다.",
        "M: 단추와 작고 둥근 주둥이가 달린 키 큰 기계입니다.",
        "M: 단추를 누르면 찬물이 활처럼 솟아 나옵니다.",
        "M: 여름에는 수업이 끝날 때마다 그 앞에 줄이 섭니다.",
        "M: 행정실에서 1년에 두 번 여과기를 확인합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How long does the film run?"],
        ["M", "About two hours."],
        ["W", "Could you lend me your charger?"],
        ["M", "Sure, here it is."],
        ["W", "Why did you change your seat?"],
        ["M", "I'll have the same as you."],
        ["W", "What are you reading these days?"],
        ["M", "A book about the sea."],
        ["W", "Shall we walk to the station?"],
        ["M", "Let's do that. It's a nice evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Why did you change your seat?",
      explanation:
        "왜 자리를 바꿨느냐는 물음에 너와 같은 걸로 하겠다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① W: 영화가 얼마나 길어? / M: 두 시간쯤.",
        "② W: 충전기 좀 빌려줄래? / M: 그럼, 여기 있어.",
        "③ W: 왜 자리를 바꿨어? / M: 나도 너랑 같은 걸로 할게.",
        "④ W: 요즘 무슨 책 읽어? / M: 바다에 관한 책.",
        "⑤ W: 역까지 걸어갈까? / M: 그러자. 저녁이 좋네.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seojun, the science fair opens in twenty minutes."],
        ["M", "Is our table ready? What should I do?"],
        ["W", "I've put out the models and taped down the wires."],
        ["M", "Should I print the name cards?"],
        ["W", "Chaerin printed them at lunchtime."],
        ["M", "Then what's left?"],
        ["W", "The lamp is still in the storeroom, and our table is dark."],
        ["M", "I'll go and get it right now."],
        ["W", "Thanks. I'll arrange the chairs for the visitors."],
      ],
      choices: ["모형 놓기", "전선 붙이기", "이름표 인쇄하기", "조명 가져오기", "의자 배치하기"],
      answer: 4,
      clue: "I'll go and get it right now.",
      explanation:
        "모형과 전선, 이름표는 이미 해결되었으므로 남자는 창고에 있는 조명을 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "W: 서준아, 과학 전시가 20분 뒤에 시작해.",
        "M: 우리 자리 준비됐어? 내가 뭘 할까?",
        "W: 모형은 놨고 전선도 테이프로 붙였어.",
        "M: 이름표를 인쇄할까?",
        "W: 채린이가 점심시간에 인쇄했어.",
        "M: 그럼 뭐가 남았어?",
        "W: 조명이 아직 창고에 있어. 우리 자리가 어두워.",
        "M: 내가 지금 가서 가져올게.",
        "W: 고마워. 나는 방문객 의자를 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 예약할 숙소를 고르시오.",
      lines: [
        ["M", "Hayoon, these are the five places left for the family trip."],
        ["W", "Let's look. It has to be within an hour of the beach."],
        ["M", "Then one is out. What else?"],
        ["W", "We need four beds. My cousins are coming too."],
        ["M", "One only has three, so that's gone."],
        ["W", "Three left. What about the price?"],
        ["M", "You said a hundred thousand won a night at the most."],
        ["W", "Then one more drops out. Two are left."],
        ["M", "Do they both have a kitchen?"],
        ["W", "Only one does. We'd have to eat out every meal at the other."],
        ["M", "Then that settles it. Book it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Then that settles it. Book it tonight.",
      explanation:
        "바다에서 2시간인 ①, 침대 세 개인 ②, 120,000원인 ⑤를 뺀다. 남은 ③과 ④ 중 부엌이 있는 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "바다에서 2시간 / 침대 4개 / 90,000원 / 부엌 있음" },
          { no: 2, label: "②", value: "바다에서 30분 / 침대 3개 / 90,000원 / 부엌 있음" },
          { no: 3, label: "③", value: "바다에서 40분 / 침대 4개 / 80,000원 / 부엌 없음" },
          { no: 4, label: "④", value: "바다에서 40분 / 침대 4개 / 100,000원 / 부엌 있음" },
          { no: 5, label: "⑤", value: "바다에서 20분 / 침대 4개 / 120,000원 / 부엌 있음" },
        ],
      },
      translation: [
        "M: 하윤아, 가족 여행에 남은 숙소가 이 다섯 개야.",
        "W: 보자. 바다에서 한 시간 안이어야 해.",
        "M: 그럼 하나 빠지네. 또 뭐가 있어?",
        "W: 침대가 네 개 필요해. 사촌들도 오거든.",
        "M: 하나는 세 개뿐이니까 빠지고.",
        "W: 셋 남았다. 값은 어때?",
        "M: 하룻밤에 많아야 10만 원이라고 했잖아.",
        "W: 그럼 하나 더 빠지고 둘 남았다.",
        "M: 둘 다 부엌이 있어?",
        "W: 한 곳만. 다른 데는 끼니마다 나가서 먹어야 해.",
        "M: 그럼 정해졌네. 오늘 밤에 예약해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 자원봉사를 갈 날짜를 고르시오.",
      lines: [
        ["M", "Nari, when should we go to the old people's centre?"],
        ["W", "They take volunteers on the third, fourth, and fifth."],
        ["M", "What do we do there?"],
        ["W", "We read the newspaper aloud and help with lunch."],
        ["M", "That sounds fine. But I have a dental check-up on the third."],
        ["W", "Then the fourth or the fifth."],
        ["M", "Isn't the fifth the day of the English speaking test?"],
        ["W", "You're right, I forgot. We'd be at school all morning."],
        ["M", "So only the fourth is left."],
        ["W", "Then let's go on the fourth. I'll call them tonight."],
      ],
      choices: ["2일", "3일", "4일", "5일", "6일"],
      answer: 3,
      clue: "So only the fourth is left.",
      explanation:
        "3일은 치과 검진, 5일은 영어 말하기 시험이어서 4일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 나리야, 노인정에 언제 갈까?",
        "W: 3일, 4일, 5일에 자원봉사자를 받아.",
        "M: 거기서 뭘 하는데?",
        "W: 신문을 소리 내어 읽어 드리고 점심을 도와.",
        "M: 괜찮네. 그런데 나 3일에 치과 검진이 있어.",
        "W: 그럼 4일이나 5일이네.",
        "M: 5일은 영어 말하기 시험 날 아니야?",
        "W: 맞다, 잊었네. 오전 내내 학교에 있어야 해.",
        "M: 그럼 4일만 남네.",
        "W: 그럼 4일에 가자. 오늘 밤에 전화할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, did you go to the water park on Sunday?"],
        ["M", "No, I helped my father wash the car."],
        ["W", "The whole day for one car?"],
        ["M", "We washed it, and then we cleaned everything inside."],
        ["W", "What was inside?"],
        ["M", "Three years of things. I found a toy I lost in second grade."],
        ["W", "That's funny. Did you finish?"],
        ["M", "Just before dinner. My father says we'll do it again in spring."],
        ["W", "I hope you find something else."],
        ["M", "I hope I don't. That would mean we missed it this time."],
      ],
      choices: ["물놀이 가기", "세차하기", "장보기", "자전거 타기", "청소하기"],
      answer: 2,
      clue: "No, I helped my father wash the car.",
      explanation:
        "남자는 지난 일요일에 아버지와 세차를 하고 차 안까지 정리했다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 일요일에 워터파크 갔어?",
        "M: 아니, 아빠랑 세차했어.",
        "W: 차 한 대에 하루 종일?",
        "M: 씻고 나서 안에 있는 것도 다 치웠어.",
        "W: 안에 뭐가 있었는데?",
        "M: 3년 치 물건. 2학년 때 잃어버린 장난감도 찾았어.",
        "W: 웃기다. 다 끝냈어?",
        "M: 저녁 먹기 직전에. 아빠가 봄에 또 하자셔.",
        "W: 그때도 뭔가 나오면 좋겠다.",
        "M: 안 나오면 좋겠어. 나오면 이번에 놓쳤다는 뜻이잖아.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the student council."],
        ["M", "The lost property box by the front door is full again."],
        ["M", "There are eleven jackets and about thirty pens in it."],
        ["M", "Come and look during lunch this week, before Friday."],
        ["M", "Anything left on Friday goes to a charity shop."],
        ["M", "Please take two minutes and check."],
      ],
      choices: [
        "분실물을 찾아가라고 하려고",
        "기부 행사를 안내하려고",
        "물건을 잃어버리지 말라고 하려고",
        "상자를 새로 놓는다고 알리려고",
        "학생회 임원을 뽑는다고 알리려고",
      ],
      answer: 1,
      clue: "Come and look during lunch this week, before Friday.",
      explanation:
        "분실물 상자가 가득 찼으니 금요일 전에 찾아가라고 부탁하는 방송이다. 따라서 방송의 목적은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학생회입니다.",
        "M: 정문 옆 분실물 상자가 또 가득 찼습니다.",
        "M: 외투가 열한 벌, 펜이 서른 자루쯤 들어 있습니다.",
        "M: 이번 주 점심시간에, 금요일 전에 와서 살펴보세요.",
        "M: 금요일까지 남은 것은 기부 가게로 보냅니다.",
        "M: 2분만 내서 확인해 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the flower shop. What would you like?"],
        ["M", "Four roses, please."],
        ["W", "Roses are four dollars each."],
        ["M", "So sixteen dollars."],
        ["W", "That's right. Would you like a card with them?"],
        ["M", "How much is that?"],
        ["W", "Three dollars."],
        ["M", "Then one card, please."],
        ["W", "All right. And we take four dollars off if you buy four or more flowers."],
        ["M", "Great. Here's my card."],
      ],
      choices: ["$15", "$16", "$17", "$19", "$20"],
      answer: 1,
      clue: "All right. And we take four dollars off if you buy four or more flowers.",
      explanation:
        "장미 4달러씩 네 송이는 16달러, 카드 3달러를 더하면 19달러이다. 네 송이 이상 할인 4달러를 빼면 15달러이므로 답은 ①이다.",
      translation: [
        "W: 꽃집입니다. 무엇을 드릴까요?",
        "M: 장미 네 송이 주세요.",
        "W: 장미는 한 송이에 4달러입니다.",
        "M: 그럼 16달러네요.",
        "W: 맞습니다. 카드도 같이 하시겠어요?",
        "M: 얼마예요?",
        "W: 3달러입니다.",
        "M: 그럼 카드 하나 주세요.",
        "W: 알겠습니다. 그리고 꽃을 네 송이 이상 사시면 4달러 빼 드립니다.",
        "M: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Hyunwoo, you've been redoing the same drawing for two weeks."],
        ["M", "The face never looks right and I start again."],
        ["W", "From the very beginning each time?"],
        ["M", "A clean sheet every time. The old one goes in the bin."],
        ["W", "So you've thrown away about ten faces."],
        ["M", "Twelve. I counted last night."],
        ["W", "And you can't compare any of them now."],
        ["M", "I hadn't thought of that. They're all gone."],
        ["W", "Keep the next three and put them side by side."],
      ],
      choices: [
        "My drawing is for the art contest.",
        "Then I'll keep the next three.",
        "I use a soft pencil for faces.",
        "The paper is quite thin.",
        "You should draw one too.",
      ],
      answer: 2,
      clue: "Keep the next three and put them side by side.",
      explanation:
        "다음 세 장은 버리지 말고 나란히 놓고 보라는 조언을 들었으므로, 다음 세 장을 남기겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 현우야, 2주째 같은 그림을 다시 그리네.",
        "M: 얼굴이 마음에 안 들어서 자꾸 처음부터 다시 그려.",
        "W: 매번 처음부터?",
        "M: 매번 새 종이에. 그리던 건 버려.",
        "W: 그럼 얼굴을 열 장쯤 버린 거네.",
        "M: 열두 장. 어젯밤에 세어 봤어.",
        "W: 그리고 이제 그중 어느 것도 비교할 수가 없고.",
        "M: 그 생각은 못 했어. 다 없어졌네.",
        "W: 다음 세 장은 남겨서 나란히 놓고 봐.",
        "M: 그럼 다음 세 장은 남길게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Dain, you've missed the school bus three times this month."],
        ["W", "I leave the house at the right time. It's the walk."],
        ["M", "How long is the walk to the stop?"],
        ["W", "Eight minutes if I go straight there."],
        ["M", "And do you go straight there?"],
        ["W", "I stop at the shop for something to drink."],
        ["M", "Every morning?"],
        ["W", "Every morning, and the queue is different every day."],
        ["M", "Put a drink in your bag the night before."],
      ],
      choices: [
        "The bus comes at seven fifty.",
        "The shop opens at seven.",
        "Then I'll pack one tonight.",
        "I usually buy juice.",
        "You should walk faster.",
      ],
      answer: 3,
      clue: "Put a drink in your bag the night before.",
      explanation:
        "전날 밤에 마실 것을 가방에 넣어 두라는 조언을 들었으므로, 오늘 밤에 챙기겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 다인아, 이번 달에 통학 버스를 세 번이나 놓쳤네.",
        "W: 집에서는 제시간에 나와. 걸어가는 게 문제야.",
        "M: 정류장까지 얼마나 걸려?",
        "W: 바로 가면 8분.",
        "M: 바로 가?",
        "W: 가게에 들러서 마실 걸 사.",
        "M: 아침마다?",
        "W: 아침마다, 그런데 줄이 날마다 달라.",
        "M: 전날 밤에 마실 걸 가방에 넣어 둬.",
        "W: 그럼 오늘 밤에 챙길게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minho, how is the class quiz show going?"],
        ["M", "Badly. Only four people joined in last time."],
        ["W", "Out of how many?"],
        ["M", "Twenty-eight. The same four every week."],
        ["W", "How do you ask the questions?"],
        ["M", "I say one out loud and wait for someone to put a hand up."],
        ["W", "So the fastest person always answers."],
        ["M", "And everyone else stops trying."],
        ["W", "Give everyone paper and let them all write the answer."],
      ],
      choices: [
        "The quiz is every Friday.",
        "I write the questions myself.",
        "Our class has twenty-eight students.",
        "Then I'll bring paper next week.",
        "I'd rather stop the quiz show.",
      ],
      answer: 4,
      clue: "Give everyone paper and let them all write the answer.",
      explanation:
        "모두에게 종이를 나눠 주고 답을 적게 하라는 조언을 들었으므로, 다음 주에 종이를 가져오겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 민호야, 학급 퀴즈는 잘돼 가?",
        "M: 잘 안돼. 지난번엔 네 명만 참여했어.",
        "W: 몇 명 중에?",
        "M: 스물여덟 명. 매주 같은 네 명이야.",
        "W: 문제를 어떻게 내는데?",
        "M: 소리 내어 하나 말하고 손드는 사람을 기다려.",
        "W: 그럼 제일 빠른 사람이 늘 답하겠네.",
        "M: 그리고 나머지는 아예 안 하게 돼.",
        "W: 모두에게 종이를 주고 다 같이 답을 적게 해.",
        "M: 그럼 다음 주에 종이를 가져올게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Taemin이 Sohee에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Taemin : ________________",
      lines: [
        ["M", "Taemin and Sohee run the class announcement board together."],
        ["M", "Sohee writes the notices and her handwriting is very neat."],
        ["M", "She puts every notice up as soon as it comes in."],
        ["M", "However, she never takes the old ones down."],
        ["M", "The board now has notices from three months ago on it."],
        ["M", "Nobody can find this week's notice among them."],
        ["M", "Taemin does not want to say that her work is untidy."],
        ["M", "He wants to suggest taking down anything older than two weeks."],
        ["M", "In this situation, what would Taemin most likely say to Sohee?"],
      ],
      choices: [
        "Let's use a bigger board next term.",
        "You should write the notices larger.",
        "I'll write all the notices myself.",
        "The board is in the wrong place.",
        "Could we take down anything older than two weeks?",
      ],
      answer: 5,
      clue: "He wants to suggest taking down anything older than two weeks.",
      explanation:
        "태민이는 소희가 한 일을 깎아내리지 않으면서, 2주가 지난 것은 떼어 내자고 말하려 한다. 따라서 ⑤가 가장 적절하다.",
      translation: [
        "M: 태민이와 소희는 학급 알림판을 함께 맡고 있습니다.",
        "M: 소희가 알림글을 쓰는데 글씨가 아주 반듯합니다.",
        "M: 새 알림이 오면 바로바로 붙입니다.",
        "M: 그런데 예전 것을 한 번도 떼지 않습니다.",
        "M: 지금 알림판에는 석 달 전 알림까지 붙어 있습니다.",
        "M: 그 틈에서 이번 주 알림을 아무도 찾지 못합니다.",
        "M: 태민이는 소희가 한 일이 지저분하다고 말하고 싶지는 않습니다.",
        "M: 다만 2주가 지난 것은 떼어 내자고 제안하고 싶습니다.",
        "M: 이런 상황에서 태민이가 소희에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
