/** 중2 듣기 20회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 20회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 의자를 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a chair?"],
        ["M", "Yes, one for my desk at home."],
        ["W", "We have chairs with a back and stools with no back."],
        ["M", "One with a back, please. I lean back when I read."],
        ["W", "All right. Do you want armrests on it?"],
        ["M", "No, without. My desk is low and the arms get in the way."],
        ["W", "Then two are left. One has a cushion on the seat and one is plain wood."],
        ["M", "The cushioned one, please. I sit there for two hours at a time."],
        ["W", "Good choice. The cover comes off and washes."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "The cushioned one, please. I sit there for two hours at a time.",
      explanation:
        "남자는 등받이가 있는 의자를, 팔걸이가 없는 것으로, 방석이 깔린 것을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five chairs arranged in one row across the middle of the picture, all five drawn completely inside the frame with a wide empty margin on the left and right so nothing is cut off, each the same size, clean black line art on a plain white background, no writing or letters anywhere. " +
          "Chair 1: NO backrest at all, just a seat on four legs, ARMRESTS are impossible so none, a flat plain WOODEN seat. " +
          "Chair 2: a tall BACKREST, ARMRESTS on both sides, a flat plain WOODEN seat. " +
          "Chair 3: a tall BACKREST, ARMRESTS on both sides, a thick soft CUSHION on the seat. " +
          "Chair 4: a tall BACKREST, NO armrests at all, a thick soft CUSHION on the seat. " +
          "Chair 5: a tall BACKREST, NO armrests at all, a flat plain WOODEN seat.",
      },
      translation: [
        "W: 안녕하세요. 의자 찾으세요?",
        "M: 네, 집 책상에 둘 거예요.",
        "W: 등받이가 있는 것과 등받이 없는 스툴이 있습니다.",
        "M: 등받이 있는 걸로요. 책 읽을 때 기대거든요.",
        "W: 알겠습니다. 팔걸이가 있는 걸로 하시겠어요?",
        "M: 아니요, 없는 걸로요. 책상이 낮아서 팔걸이가 걸려요.",
        "W: 그럼 두 개 남았네요. 하나는 방석이 깔렸고 하나는 나무 그대로입니다.",
        "M: 방석 있는 걸로요. 한 번에 두 시간씩 앉아 있어요.",
        "W: 좋은 선택이세요. 덮개는 벗겨서 빨 수 있습니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 사진 전시회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Chaerin, are you putting a photo in the exhibition?"],
        ["W", "I want to, but I don't know how it works."],
        ["M", "It opens on the second Monday of next month and runs for a week."],
        ["W", "Where is it held?"],
        ["M", "In the corridor outside the library, on both walls."],
        ["W", "How many photos can we put in?"],
        ["M", "One each, printed on A4."],
        ["W", "Do we write anything with it?"],
        ["M", "A title and one line about where you took it."],
        ["W", "Then I'll look through my photos tonight."],
      ],
      choices: ["열리는 날", "장소", "출품 수", "함께 적을 것", "관람 시간"],
      answer: 5,
      clue: "A title and one line about where you took it.",
      explanation:
        "날짜(다음 달 둘째 월요일부터 일주일), 장소(도서관 앞 복도), 출품 수(한 사람에 한 장), 함께 적을 것(제목과 찍은 곳 한 줄)은 언급되지만 관람 시간은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 채린아, 사진 전시회에 사진 낼 거야?",
        "W: 내고 싶은데 어떻게 하는 건지 몰라.",
        "M: 다음 달 둘째 월요일에 열어서 일주일 동안 해.",
        "W: 어디서 하는데?",
        "M: 도서관 앞 복도, 양쪽 벽에.",
        "W: 몇 장까지 낼 수 있어?",
        "M: 한 사람에 한 장, A4로 인쇄해서.",
        "W: 같이 적는 건 있어?",
        "M: 제목이랑 어디서 찍었는지 한 줄.",
        "W: 그럼 오늘 밤에 사진을 훑어봐야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Yerin. It's Dohyun from the badminton club."],
        ["W", "Hi. What's up?"],
        ["M", "About Saturday. We need one more racket."],
        ["W", "One more? Aren't there enough in the gym?"],
        ["M", "Two broke last week and they haven't been replaced."],
        ["W", "I have one at home I never use."],
        ["M", "That would help a lot. Could you bring it?"],
        ["W", "Sure. I'll put it by the door tonight so I don't forget."],
        ["M", "Thanks. See you on Saturday."],
      ],
      choices: [
        "연습이 취소되었다고 알리려고",
        "라켓을 빌려 달라고 하려고",
        "연습 시간을 바꾸자고 하려고",
        "동아리 가입을 권하려고",
        "체육관 청소를 부탁하려고",
      ],
      answer: 2,
      clue: "That would help a lot. Could you bring it?",
      explanation:
        "남자는 라켓이 모자라서 여자에게 집에 있는 라켓을 가져와 달라고 부탁하려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 예린아. 배드민턴부 도현이야.",
        "W: 안녕. 무슨 일이야?",
        "M: 토요일 말인데, 라켓이 하나 더 필요해.",
        "W: 하나 더? 체육관에 충분하지 않아?",
        "M: 지난주에 두 개가 부러졌는데 아직 안 채워졌어.",
        "W: 나 집에 안 쓰는 거 하나 있어.",
        "M: 그러면 큰 도움이 될 텐데. 가져올 수 있어?",
        "W: 그래. 잊지 않게 오늘 밤에 문 앞에 둘게.",
        "M: 고마워. 토요일에 봐.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Sohee, what time should we meet at the museum tomorrow?"],
        ["W", "The guided tour starts at two."],
        ["M", "And we have to leave our bags at the counter."],
        ["W", "How about one forty-five?"],
        ["M", "The counter has a queue on Sundays. Let's go earlier."],
        ["W", "How long does it take you to get there?"],
        ["M", "Half an hour by subway."],
        ["W", "Then let's meet at one thirty."],
        ["M", "One thirty is fine. I'll wait by the steps."],
      ],
      choices: ["1:00 p.m.", "1:15 p.m.", "1:30 p.m.", "1:45 p.m.", "2:00 p.m."],
      answer: 3,
      clue: "Then let's meet at one thirty.",
      explanation:
        "안내 관람이 2시에 시작하고 보관대에 줄이 서서 두 사람은 1시 30분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 소희야, 내일 박물관에서 몇 시에 만날까?",
        "W: 안내 관람이 2시에 시작해.",
        "M: 그리고 가방도 보관대에 맡겨야 하잖아.",
        "W: 1시 45분은 어때?",
        "M: 일요일에는 보관대에 줄이 서. 더 일찍 가자.",
        "W: 거기까지 얼마나 걸려?",
        "M: 지하철로 30분.",
        "W: 그럼 1시 30분에 만나자.",
        "M: 1시 30분 좋아. 계단 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, you've checked the door three times since we sat down."],
        ["M", "My little sister was supposed to meet me here an hour ago."],
        ["W", "Have you called her?"],
        ["M", "Four times. It goes straight to voicemail."],
        ["W", "Maybe her battery died."],
        ["M", "Maybe. But she's never been this late before."],
        ["W", "Shall we walk to the bus stop and look?"],
        ["M", "Yes, please. I can't sit here any longer."],
      ],
      choices: ["excited", "bored", "proud", "pleased", "worried"],
      answer: 5,
      clue: "Yes, please. I can't sit here any longer.",
      explanation:
        "동생이 한 시간이나 늦고 전화도 안 되어 남자는 걱정하고 있다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준서야, 앉은 뒤로 문 쪽을 세 번이나 봤어.",
        "M: 동생이 한 시간 전에 여기서 만나기로 했거든.",
        "W: 전화해 봤어?",
        "M: 네 번. 바로 음성사서함으로 넘어가.",
        "W: 배터리가 나갔을 수도 있잖아.",
        "M: 그럴 수도. 그런데 이렇게 늦은 적이 없어.",
        "W: 버스 정류장까지 걸어가 볼까?",
        "M: 응, 그러자. 더는 앉아 있을 수가 없어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "How much is this umbrella?"],
        ["M", "Thirteen dollars."],
        ["W", "Would you like to share my umbrella?"],
        ["M", "Thank you. I left mine at home."],
        ["W", "What time does the bus come?"],
        ["M", "Every fifteen minutes."],
        ["W", "Is this seat free?"],
        ["M", "Yes, please sit down."],
        ["W", "Where is the nearest station?"],
        ["M", "Two streets that way."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Would you like to share my umbrella?",
      explanation:
        "그림은 비 오는 날 우산을 쓴 사람이 우산 없이 비를 맞고 있는 사람 쪽으로 우산을 기울여 함께 쓰자고 하는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a rainy street, clean black line art on a plain white background, no writing or letters anywhere. Rain is falling in slanting lines. A GIRL is holding an open umbrella and tilting it sideways over a BOY standing next to her who has no umbrella and whose hair and shoulders are wet. She is looking at him and holding the umbrella out toward him. Both people are drawn clearly. Shop fronts and a puddle are in the background.",
      },
      translation: [
        "① W: 이 우산 얼마예요? / M: 13달러입니다.",
        "② W: 우산 같이 쓸래? / M: 고마워. 집에 두고 왔어.",
        "③ W: 버스 몇 시에 와요? / M: 15분마다 와요.",
        "④ W: 이 자리 비었나요? / M: 네, 앉으세요.",
        "⑤ W: 가장 가까운 역이 어디예요? / M: 저쪽으로 두 블록이요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, are you going to the computer room after school?"],
        ["M", "Yes, our club meets there on Fridays."],
        ["W", "Could you do one thing for me while you're there?"],
        ["M", "Sure. What is it?"],
        ["W", "My report is saved on the computer nearest the window."],
        ["M", "Do you want me to print it?"],
        ["W", "No, please send it to me. I can't get in today."],
        ["M", "What's the file called?"],
        ["W", "'City parks'. It's the only one on the desktop."],
        ["M", "Got it. I'll send it as soon as we start."],
      ],
      choices: ["보고서를 보내 주기", "보고서를 인쇄해 주기", "컴퓨터를 켜 주기", "자리를 맡아 주기", "보고서를 써 주기"],
      answer: 1,
      clue: "No, please send it to me. I can't get in today.",
      explanation:
        "여자는 컴퓨터에 저장된 보고서를 보내 달라고 부탁한다. 인쇄가 아니라 전송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 태민아, 방과 후에 컴퓨터실 가?",
        "M: 응, 우리 동아리가 금요일마다 거기서 모여.",
        "W: 거기 있는 동안 하나만 부탁할게.",
        "M: 그래. 뭔데?",
        "W: 내 보고서가 창가에서 제일 가까운 컴퓨터에 저장돼 있어.",
        "M: 인쇄해 줄까?",
        "W: 아니, 나한테 보내 줘. 오늘 내가 못 들어가거든.",
        "M: 파일 이름이 뭐야?",
        "W: '도시의 공원'. 바탕화면에 그거 하나뿐이야.",
        "M: 알겠어. 시작하자마자 보낼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Winter Music Night에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Here is news about Winter Music Night."],
        ["M", "It will be held on the last Friday of this month, in the evening."],
        ["M", "We will use the big hall, and the doors open at six."],
        ["M", "Six groups will play, and each one gets fifteen minutes."],
        ["M", "Bring a friend or your family; anyone may come and listen."],
        ["M", "Let's end the term with something worth staying for."],
      ],
      choices: ["열리는 날", "장소", "공연 팀 수", "관람 방법", "입장료"],
      answer: 5,
      clue: "Bring a friend or your family; anyone may come and listen.",
      explanation:
        "날짜(이달 마지막 금요일 저녁), 장소(대강당), 공연 팀 수(여섯 팀), 관람 방법(누구나 와서 들을 수 있음)은 언급되지만 입장료는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Winter Music Night 소식입니다.",
        "M: 이달 마지막 금요일 저녁에 열립니다.",
        "M: 대강당에서 하고, 문은 6시에 엽니다.",
        "M: 여섯 팀이 연주하고, 한 팀에 15분씩입니다.",
        "M: 친구나 가족과 함께 오세요. 누구나 와서 들을 수 있습니다.",
        "M: 남아 있을 만한 것으로 이번 학기를 마무리해 봅시다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You will find one of these beside the door of every classroom."],
        ["W", "It is a flat board with small cards slotted into it."],
        ["W", "Each card has the name of a student who is on duty that week."],
        ["W", "The cards are moved along by one every Monday morning."],
        ["W", "Nobody looks at it until somebody says it is their turn."],
      ],
      choices: ["당번표", "게시판", "사물함", "시간표", "출석부"],
      answer: 1,
      clue: "Each card has the name of a student who is on duty that week.",
      explanation:
        "그 주 당번 학생 이름이 적힌 카드를 월요일마다 한 칸씩 옮긴다고 했으므로 당번표이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 교실마다 문 옆에 하나씩 있습니다.",
        "W: 작은 카드가 끼워진 납작한 판입니다.",
        "W: 카드마다 그 주 당번인 학생 이름이 적혀 있습니다.",
        "W: 월요일 아침마다 카드를 한 칸씩 옮깁니다.",
        "W: 누가 자기 차례라고 말하기 전까지는 아무도 쳐다보지 않습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How long have you lived here?"],
        ["W", "About four years."],
        ["M", "Could you lend me your eraser?"],
        ["W", "Sure, here it is."],
        ["M", "When does the library close?"],
        ["W", "At six on weekdays."],
        ["M", "Shall we sit outside?"],
        ["W", "Let's do that. It's warm today."],
        ["M", "Why are you carrying two bags?"],
        ["W", "I like pizza better."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Why are you carrying two bags?",
      explanation:
        "왜 가방을 두 개 들고 있느냐는 물음에 피자가 더 좋다는 대답은 어울리지 않는다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 여기 산 지 얼마나 됐어? / W: 4년쯤.",
        "② M: 지우개 좀 빌려줄래? / W: 그럼, 여기 있어.",
        "③ M: 도서관 몇 시에 닫아? / W: 평일에는 6시에.",
        "④ M: 밖에 앉을까? / W: 그러자. 오늘 따뜻하네.",
        "⑤ M: 왜 가방을 두 개 들고 있어? / W: 나는 피자가 더 좋아.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minho, the club fair opens in fifteen minutes."],
        ["M", "Is our table ready? What should I do?"],
        ["W", "I've put out the leaflets and hung the sign."],
        ["M", "Should I bring the sign-up sheet?"],
        ["W", "Chaerin is carrying it over now."],
        ["M", "Then what's left?"],
        ["W", "The extension cord for the laptop is in the club room."],
        ["M", "I'll go and get it right now."],
        ["W", "Thanks. I'll arrange the chairs for visitors."],
      ],
      choices: ["안내지 놓기", "현수막 걸기", "신청서 가져오기", "연장선 가져오기", "의자 배치하기"],
      answer: 4,
      clue: "I'll go and get it right now.",
      explanation:
        "안내지와 현수막, 신청서는 이미 해결되었으므로 남자는 동아리방에 있는 연장선을 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "W: 민호야, 동아리 박람회가 15분 뒤에 시작해.",
        "M: 우리 자리 준비됐어? 내가 뭘 할까?",
        "W: 안내지는 놨고 현수막도 걸었어.",
        "M: 신청서를 가져올까?",
        "W: 채린이가 지금 들고 오고 있어.",
        "M: 그럼 뭐가 남았어?",
        "W: 노트북에 쓸 연장선이 동아리방에 있어.",
        "M: 내가 지금 가서 가져올게.",
        "W: 고마워. 나는 방문객 의자를 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 겨울 캠프를 고르시오.",
      lines: [
        ["M", "Hayoon, these are the five winter camps still open."],
        ["W", "Let's look. I can't go in January because of my grandmother's birthday."],
        ["M", "Then one is out. What else?"],
        ["W", "It has to be two nights. One night is too short."],
        ["M", "One of them is a single night, so that's gone."],
        ["W", "Three left. How much do they cost?"],
        ["M", "You said a hundred thousand won at the most."],
        ["W", "Then one more drops out. Two are left."],
        ["M", "Do they both provide the bus?"],
        ["W", "Only one does. For the other I'd have to get there myself."],
        ["M", "Then that settles it. Sign up tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Then that settles it. Sign up tonight.",
      explanation:
        "1월인 ①, 1박인 ②, 120,000원인 ⑤를 뺀다. 남은 ③과 ④ 중 버스를 제공하는 것은 ③이므로 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "1월 / 2박 / 90,000원 / 버스 제공" },
          { no: 2, label: "②", value: "2월 / 1박 / 60,000원 / 버스 제공" },
          { no: 3, label: "③", value: "2월 / 2박 / 100,000원 / 버스 제공" },
          { no: 4, label: "④", value: "2월 / 2박 / 90,000원 / 버스 없음" },
          { no: 5, label: "⑤", value: "2월 / 2박 / 120,000원 / 버스 제공" },
        ],
      },
      translation: [
        "M: 하윤아, 아직 열려 있는 겨울 캠프가 이 다섯 개야.",
        "W: 보자. 할머니 생신 때문에 1월엔 못 가.",
        "M: 그럼 하나 빠지네. 또 뭐가 있어?",
        "W: 2박이어야 해. 1박은 너무 짧아.",
        "M: 하나는 1박이니까 빠지고.",
        "W: 셋 남았다. 얼마야?",
        "M: 많아야 10만 원이라고 했잖아.",
        "W: 그럼 하나 더 빠지고 둘 남았다.",
        "M: 둘 다 버스를 줘?",
        "W: 한 곳만. 다른 데는 내가 알아서 가야 해.",
        "M: 그럼 정해졌네. 오늘 밤에 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 연극을 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Nari, when should we go and see the play?"],
        ["W", "It's on from the eighth to the tenth."],
        ["M", "What's it about?"],
        ["W", "A family that moves to a small island for one year."],
        ["M", "Sounds good. But I have a dentist appointment on the eighth."],
        ["W", "Then the ninth or the tenth."],
        ["M", "Isn't the tenth the day of the class outing?"],
        ["W", "You're right, I forgot. We'd be away until evening."],
        ["M", "So only the ninth is left."],
        ["W", "Then let's go on the ninth. I'll book two seats tonight."],
      ],
      choices: ["6일", "7일", "8일", "9일", "10일"],
      answer: 4,
      clue: "So only the ninth is left.",
      explanation:
        "8일은 치과 예약, 10일은 학급 나들이여서 9일만 남는다. 따라서 답은 ④이다.",
      translation: [
        "M: 나리야, 연극 언제 보러 갈까?",
        "W: 8일부터 10일까지 해.",
        "M: 무슨 내용인데?",
        "W: 한 가족이 작은 섬으로 1년 동안 이사 가는 이야기야.",
        "M: 좋네. 그런데 나 8일에 치과 예약이 있어.",
        "W: 그럼 9일이나 10일이네.",
        "M: 10일은 학급 나들이 날 아니야?",
        "W: 맞다, 잊었네. 저녁까지 밖에 있잖아.",
        "M: 그럼 9일만 남네.",
        "W: 그럼 9일에 가자. 오늘 밤에 두 자리 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, did you go to the football match on Saturday?"],
        ["M", "No, I spent the day cleaning out the shed with my father."],
        ["W", "The shed? How long had it been since the last time?"],
        ["M", "Six years, my father says. I believe him."],
        ["W", "What was in there?"],
        ["M", "Three bicycles, and only one of them still works."],
        ["W", "What did you do with the other two?"],
        ["M", "We took them to the repair shop down the road."],
        ["W", "So the whole day went on one shed."],
        ["M", "The whole day. But I can walk into it now."],
      ],
      choices: ["창고 정리하기", "축구 경기 보기", "자전거 타기", "자전거 사러 가기", "집 청소하기"],
      answer: 1,
      clue: "No, I spent the day cleaning out the shed with my father.",
      explanation:
        "남자는 지난 토요일에 아버지와 창고를 정리했다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "W: 도현아, 토요일에 축구 경기 봤어?",
        "M: 아니, 아빠랑 하루 종일 창고 정리했어.",
        "W: 창고? 마지막으로 정리한 게 언제였는데?",
        "M: 아빠 말로는 6년 전. 믿을 만해.",
        "W: 안에 뭐가 있었어?",
        "M: 자전거 세 대, 그중 굴러가는 건 한 대뿐.",
        "W: 나머지 둘은 어떻게 했어?",
        "M: 길 아래 수리점에 가져갔어.",
        "W: 그럼 하루를 통째로 창고 하나에 쓴 거네.",
        "M: 하루 종일. 그래도 이제 걸어 들어갈 수는 있어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "The heating in the third-floor classrooms will be off tomorrow."],
        ["W", "Engineers are replacing a pipe, and it takes most of the day."],
        ["W", "Third-floor classes will use the second-floor rooms instead."],
        ["W", "Your homeroom teacher will tell you which room."],
        ["W", "Thank you for your understanding."],
      ],
      choices: [
        "따뜻하게 입고 오라고 하려고",
        "3층에 올라가지 말라고 하려고",
        "교실이 바뀐다고 알리려고",
        "등교 시간을 늦추려고",
        "공사 비용을 안내하려고",
      ],
      answer: 3,
      clue: "Third-floor classes will use the second-floor rooms instead.",
      explanation:
        "난방 공사로 3층 수업이 2층 교실에서 열린다는 것을 알리는 방송이다. 따라서 방송의 목적은 ③이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 내일 3층 교실 난방이 꺼집니다.",
        "W: 기사님들이 수도관을 바꾸는데 거의 하루가 걸립니다.",
        "W: 3층 수업은 대신 2층 교실에서 합니다.",
        "W: 어느 교실인지는 담임 선생님이 알려 주십니다.",
        "W: 이해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the bakery. What would you like?"],
        ["W", "Three sandwiches, please."],
        ["M", "Sandwiches are six dollars each."],
        ["W", "So eighteen dollars."],
        ["M", "That's right. Would you like some milk too?"],
        ["W", "How much is it?"],
        ["M", "Two dollars a bottle."],
        ["W", "Then two bottles, please."],
        ["M", "All right. And we take four dollars off if you spend over twenty."],
        ["W", "Great. Here's my card."],
      ],
      choices: ["$18", "$20", "$22", "$24", "$26"],
      answer: 1,
      clue: "All right. And we take four dollars off if you spend over twenty.",
      explanation:
        "샌드위치 6달러씩 세 개는 18달러, 우유 2달러씩 두 병은 4달러여서 22달러이다. 20달러 넘게 사면 4달러를 빼 주므로 18달러이고 답은 ①이다.",
      translation: [
        "M: 빵집입니다. 무엇을 드릴까요?",
        "W: 샌드위치 세 개 주세요.",
        "M: 샌드위치는 하나에 6달러입니다.",
        "W: 그럼 18달러네요.",
        "M: 맞습니다. 우유도 하시겠어요?",
        "W: 얼마예요?",
        "M: 한 병에 2달러입니다.",
        "W: 그럼 두 병 주세요.",
        "M: 알겠습니다. 그리고 20달러 넘게 사시면 4달러 빼 드립니다.",
        "W: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Chaewon, you've been redoing the same maths page every night."],
        ["W", "The questions I got wrong on the last test. I do them again."],
        ["M", "And do you get them right now?"],
        ["W", "Every time. It takes about fifteen minutes."],
        ["M", "Then what are you learning in those fifteen minutes?"],
        ["W", "That I can do them, I suppose."],
        ["M", "You knew that after the third night."],
        ["W", "I hadn't thought of it that way."],
        ["M", "Find five new questions of the same type instead."],
      ],
      choices: [
        "My textbook has two hundred questions.",
        "Then I'll find five new ones tonight.",
        "I study maths for an hour a day.",
        "The next test is in two weeks.",
        "You should redo yours as well.",
      ],
      answer: 2,
      clue: "Find five new questions of the same type instead.",
      explanation:
        "같은 유형의 새 문제 다섯 개를 찾으라는 조언을 들었으므로, 오늘 밤에 다섯 개를 찾겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 채원아, 저녁마다 같은 수학 쪽을 다시 풀고 있네.",
        "W: 지난 시험에서 틀린 문제들이야. 다시 풀어.",
        "M: 지금은 맞혀?",
        "W: 매번. 15분쯤 걸려.",
        "M: 그럼 그 15분에서 뭘 배우는데?",
        "W: 내가 풀 수 있다는 것 정도겠지.",
        "M: 그건 셋째 날 밤에 이미 알았잖아.",
        "W: 그렇게는 생각 못 했어.",
        "M: 대신 같은 유형의 새 문제 다섯 개를 찾아.",
        "W: 그럼 오늘 밤에 다섯 개 찾을게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junho, you've forgotten your gym clothes twice this month."],
        ["M", "I know. I had to borrow a shirt from Minho both times."],
        ["W", "Do you forget to wash them?"],
        ["M", "No, I wash them every Sunday and hang them on the drying rack."],
        ["W", "Then the problem isn't washing. Where is the rack?"],
        ["M", "Out on the balcony, behind the long curtain."],
        ["W", "So you never see it when you leave the house in the morning."],
        ["M", "Never. I pick up my bag and walk straight past the curtain."],
        ["W", "And in the morning you're in a hurry, so you don't go looking."],
        ["M", "I have about four minutes from bed to the front door."],
        ["W", "Bring them in on Sunday night and put them in your bag then."],
      ],
      choices: [
        "My gym clothes are grey.",
        "We have P.E. on Tuesdays.",
        "Then I'll pack them this Sunday.",
        "The balcony is quite cold.",
        "You should wash yours too.",
      ],
      answer: 3,
      clue: "Bring them in on Sunday night and put them in your bag.",
      explanation:
        "일요일 밤에 걷어서 가방에 넣으라는 조언을 들었으므로, 이번 일요일에 챙기겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 이번 달에 체육복을 두 번이나 두고 왔네.",
        "M: 그러게. 두 번 다 민호한테 셔츠를 빌렸어.",
        "W: 빨래를 잊어버리는 거야?",
        "M: 아니, 일요일마다 빨아서 건조대에 널어.",
        "W: 그럼 빨래가 문제는 아니네. 건조대가 어디 있는데?",
        "M: 베란다에, 긴 커튼 뒤에.",
        "W: 그럼 아침에 집을 나설 때는 볼 일이 없네.",
        "M: 전혀. 가방 들고 커튼 앞을 그냥 지나가.",
        "W: 게다가 아침에는 바쁘니까 찾아보지도 않고.",
        "M: 침대에서 현관까지 4분쯤이야.",
        "W: 일요일 밤에 걷어서 그때 가방에 넣어 둬.",
        "M: 그럼 이번 일요일에 챙길게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sohee, how is the class notice board going?"],
        ["W", "Badly. Nobody reads anything I put up."],
        ["M", "Where is the board?"],
        ["W", "At the back of the room, behind the last desk."],
        ["M", "And when do people stand at the back?"],
        ["W", "Almost never. They come in the front door."],
        ["M", "Then the board is in the one place nobody passes."],
        ["W", "I never thought about where people actually walk."],
        ["M", "Ask to move it to the wall by the front door."],
      ],
      choices: [
        "The board is quite big.",
        "I put up three notices a week.",
        "Our class has twenty-six students.",
        "Then I'll ask the teacher tomorrow.",
        "I'd rather use the group chat.",
      ],
      answer: 4,
      clue: "Ask to move it to the wall by the front door.",
      explanation:
        "앞문 옆 벽으로 옮겨 달라고 하라는 조언을 들었으므로, 내일 선생님께 여쭤보겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 소희야, 학급 알림판은 잘돼 가?",
        "W: 잘 안돼. 내가 붙이는 걸 아무도 안 읽어.",
        "M: 알림판이 어디 있는데?",
        "W: 교실 뒤, 맨 뒷자리 뒤에.",
        "M: 사람들이 언제 뒤에 서 있어?",
        "W: 거의 없어. 다 앞문으로 들어와.",
        "M: 그럼 알림판이 아무도 지나가지 않는 딱 그 자리에 있네.",
        "W: 사람들이 실제로 어디를 걷는지는 생각 못 했어.",
        "M: 앞문 옆 벽으로 옮겨 달라고 해 봐.",
        "W: 그럼 내일 선생님께 여쭤볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minjae가 Yerin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Minjae : ________________",
      lines: [
        ["M", "Minjae and Yerin are making a class newsletter together."],
        ["M", "Yerin has collected articles from ten students."],
        ["M", "The articles are interesting and well written."],
        ["M", "However, she has put all ten on one page in very small type."],
        ["M", "Nobody in the class can read it without holding it close."],
        ["M", "Their teacher said the newsletter should be easy to read."],
        ["M", "Minjae does not want to say that her work was wasted."],
        ["M", "He wants to suggest using two pages so the type can be bigger."],
        ["M", "In this situation, what would Minjae most likely say to Yerin?"],
      ],
      choices: [
        "Let's take out five of the articles.",
        "Could we use two pages and make the type bigger?",
        "You should write the articles yourself.",
        "The newsletter should come out later.",
        "I'll print it on coloured paper.",
      ],
      answer: 2,
      clue: "He wants to suggest using two pages so the type can be bigger.",
      explanation:
        "민재는 예린이가 한 일을 깎아내리지 않으면서, 두 쪽으로 나눠 글씨를 키우자고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 민재와 예린이는 학급 소식지를 함께 만들고 있습니다.",
        "M: 예린이가 학생 열 명에게서 글을 모았습니다.",
        "M: 글은 재미있고 잘 쓰여 있습니다.",
        "M: 그런데 열 편을 한 쪽에 아주 작은 글씨로 넣었습니다.",
        "M: 반 아이들 누구도 가까이 대고 보지 않으면 읽을 수 없습니다.",
        "M: 선생님은 소식지가 읽기 쉬워야 한다고 했습니다.",
        "M: 민재는 예린이가 한 일이 헛수고라고 말하고 싶지는 않습니다.",
        "M: 다만 두 쪽으로 나눠 글씨를 키우자고 제안하고 싶습니다.",
        "M: 이런 상황에서 민재가 예린이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
