/** 중2 듣기 28회 — 사람이 직접 쓴 회차 (2026-09-24) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 28회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 모자를 고르시오.",
      lines: [
        ["M", "Good morning. Are you looking for a hat?"],
        ["W", "Yes, something for walking in the sun."],
        ["M", "We have caps with a short brim and hats with a wide brim."],
        ["W", "A wide brim, please. It covers my neck too."],
        ["M", "All right. This wide-brim hat has a ribbon band."],
        ["W", "A ribbon looks a bit dressy for hiking."],
        ["M", "Then here is a wide-brim hat with a chin strap."],
        ["W", "That's the one. I'll take the hat with the strap."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A wide brim, please. / I'll take the hat with the strap.",
      explanation:
        "여자는 챙이 넓은 모자를 원하고, 리본 띠 대신 턱끈이 달린 것을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five sun hats drawn side by side as five choices, clean black line art on white. " +
          "① a SHORT-BRIM cap with a RIBBON BAND around the crown. " +
          "② a SHORT-BRIM cap with a CHIN STRAP hanging down. " +
          "③ a WIDE-BRIM hat with a RIBBON BAND around the crown. " +
          "④ a WIDE-BRIM hat with nothing on it at all. " +
          "⑤ a WIDE-BRIM hat with a CHIN STRAP hanging down. " +
          "The wide-brim hats have a brim clearly about twice as wide as the short-brim caps.",
      },
      translation: [
        "M: 안녕하세요. 모자 찾으세요?",
        "W: 네, 햇볕에 걸을 때 쓸 거예요.",
        "M: 챙이 짧은 것도 있고 넓은 것도 있어요.",
        "W: 챙이 넓은 걸로 주세요. 목까지 가려 주거든요.",
        "M: 알겠습니다. 이 챙 넓은 모자는 리본 띠가 있어요.",
        "W: 리본은 등산하기엔 좀 차려입은 느낌이에요.",
        "M: 그럼 턱끈이 달린 챙 넓은 모자가 여기 있어요.",
        "W: 그거예요. 턱끈 있는 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 영어 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, are you going to the winter English camp?"],
        ["M", "I'd like to. How long does it last?"],
        ["W", "Five days, from Monday to Friday."],
        ["M", "Where do we stay at night?"],
        ["W", "In the school dormitory next to the sports hall."],
        ["M", "What do we do during the day?"],
        ["W", "We act out plays and write short stories in English."],
        ["M", "Who can apply for it?"],
        ["W", "Any second or third grader can sign up."],
      ],
      choices: ["기간", "묵는 곳", "낮에 하는 활동", "신청 자격", "참가비"],
      answer: 5,
      clue: "참가비는 대화에서 언급되지 않았다.",
      explanation:
        "기간(월~금 5일), 묵는 곳(체육관 옆 기숙사), 낮 활동(연극과 짧은 글쓰기), 신청 자격(2·3학년)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 겨울 영어 캠프 갈 거야?",
        "M: 가고 싶어. 며칠 동안 해?",
        "W: 월요일부터 금요일까지 닷새.",
        "M: 밤에는 어디서 자?",
        "W: 체육관 옆 학교 기숙사에서.",
        "M: 낮에는 뭐 해?",
        "W: 영어로 연극도 하고 짧은 글도 써.",
        "M: 누가 신청할 수 있어?",
        "W: 2학년이나 3학년이면 누구나 신청할 수 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Haneul Music Academy?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "My sister takes the piano class on Wednesdays."],
        ["W", "Yes, the four o'clock class. Is there a problem?"],
        ["M", "Her school schedule changed from next month."],
        ["W", "I see. Would a different day work better?"],
        ["M", "Could you move her to the Friday class instead?"],
        ["W", "Friday at four has one seat left. I've moved her."],
      ],
      choices: [
        "수업을 새로 신청하려고",
        "수업 요일을 바꾸려고",
        "수강을 취소하려고",
        "수업료를 물어보려고",
        "학원 위치를 물어보려고",
      ],
      answer: 2,
      clue: "Could you move her to the Friday class instead?",
      explanation:
        "남자는 동생의 학교 시간표가 바뀌어 피아노 수업을 금요일로 옮기려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요, 하늘 음악 학원이죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 제 동생이 수요일 피아노 수업을 들어요.",
        "W: 네, 4시 수업이요. 무슨 문제가 있나요?",
        "M: 다음 달부터 학교 시간표가 바뀌었어요.",
        "W: 그렇군요. 다른 요일이 나으실까요?",
        "M: 금요일 수업으로 옮겨 주실 수 있나요?",
        "W: 금요일 4시에 한 자리 남았네요. 옮겨 드렸습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Junho, what time does the school play begin?"],
        ["M", "The curtain goes up at seven in the evening."],
        ["W", "Do we need to pick up our seats early?"],
        ["M", "Yes, the seats aren't numbered this year."],
        ["W", "How early should we get there for good seats?"],
        ["M", "An hour and a half before the curtain, my brother said."],
        ["W", "Then let's meet at the hall entrance at that time."],
        ["M", "Good. I'll bring two cushions for the hard seats."],
        ["W", "And I'll bring something warm to drink."],
      ],
      choices: ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
      answer: 2,
      clue: "An hour and a half before the curtain, my brother said.",
      explanation:
        "막이 7시에 오르고 그보다 한 시간 반 전에 가기로 했으므로 만나는 시각은 5시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "W: 준호야, 학교 연극 몇 시에 시작해?",
        "M: 저녁 7시에 막이 올라.",
        "W: 자리를 일찍 잡아야 해?",
        "M: 응, 올해는 좌석에 번호가 없어.",
        "W: 좋은 자리 잡으려면 얼마나 일찍 가야 해?",
        "M: 형 말로는 막 오르기 한 시간 반 전에.",
        "W: 그럼 그 시간에 강당 입구에서 만나자.",
        "M: 좋아. 의자가 딱딱해서 방석 두 개 가져갈게.",
        "W: 나는 따뜻하게 마실 것 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you've been quiet since you came back inside."],
        ["M", "My bike chain broke halfway to school."],
        ["W", "Oh no. Did you have to walk the rest of the way?"],
        ["M", "I pushed it for two kilometers in the rain."],
        ["W", "And you still made it before the bell?"],
        ["M", "Barely, but my shoes are soaked through."],
        ["W", "That sounds like a rough morning."],
        ["M", "I just want to sit down and not move for an hour."],
      ],
      choices: ["excited", "proud", "exhausted", "curious", "thankful"],
      answer: 3,
      clue: "I just want to sit down and not move for an hour.",
      explanation:
        "빗속에서 자전거를 2킬로미터 끌고 왔고 한 시간 동안 움직이고 싶지 않다고 했으므로 남자의 심정은 '지친(exhausted)'이다. 따라서 답은 ③이다.",
      translation: [
        "W: 준호야, 들어온 뒤로 말이 없네.",
        "M: 학교 오는 길 절반쯤에서 자전거 체인이 끊어졌어.",
        "W: 어떡해. 남은 길은 걸어왔어?",
        "M: 빗속에서 2킬로미터를 끌고 왔어.",
        "W: 그런데도 종 치기 전에 왔어?",
        "M: 겨우. 그런데 신발이 다 젖었어.",
        "W: 아침부터 고생했겠다.",
        "M: 그냥 앉아서 한 시간쯤 아무것도 안 하고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much is one scoop of ice cream?"],
        ["M", "Three dollars each."],
        ["ANN", "Number two."],
        ["W", "Which flavor do you recommend?"],
        ["M", "The strawberry is very popular."],
        ["ANN", "Number three."],
        ["W", "Do you want a cup or a cone?"],
        ["M", "A cone, please."],
        ["ANN", "Number four."],
        ["W", "Careful, your ice cream is about to fall."],
        ["M", "Oh! Thanks for the warning."],
        ["ANN", "Number five."],
        ["W", "Are you open on Sundays?"],
        ["M", "Yes, from noon until eight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Careful, your ice cream is about to fall.",
      explanation:
        "그림은 아이스크림 가게 앞에서 남자아이가 든 콘 위의 아이스크림이 기울어 떨어지려 하고, 여자가 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "In front of an ice cream shop, clean black line art on a plain white background, no writing anywhere. " +
          "A boy holds a cone and the scoop of ice cream on top is tipping sideways, about to slide off. " +
          "A woman beside him points at the tipping scoop with a surprised face and calls out to him. " +
          "A shop window with an awning and a small table are drawn simply in the background.",
      },
      translation: [
        "① W: 아이스크림 한 스쿱에 얼마예요? / M: 하나에 3달러입니다.",
        "② W: 어떤 맛을 추천하세요? / M: 딸기가 아주 인기 많아요.",
        "③ W: 컵으로 드릴까요, 콘으로 드릴까요? / M: 콘으로 주세요.",
        "④ W: 조심해, 아이스크림 떨어지겠어. / M: 앗! 알려 줘서 고마워.",
        "⑤ W: 일요일에도 문 여나요? / M: 네, 정오부터 8시까지요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you sit right by the classroom window, don't you?"],
        ["M", "Yes, the third seat in the last row."],
        ["W", "Our class plants are on that windowsill."],
        ["M", "The three pots with the small green leaves?"],
        ["W", "Those. I usually water them every morning."],
        ["M", "Are you going somewhere this week?"],
        ["W", "Yes, could you water them while I'm at the contest?"],
        ["M", "No problem. I'll give them water before first period."],
      ],
      choices: ["화분에 물 주기", "자리 바꿔 주기", "대회에 같이 가기", "화분 옮기기", "창문 닫기"],
      answer: 1,
      clue: "Yes, could you water them while I'm at the contest?",
      explanation:
        "여자는 대회에 가 있는 동안 교실 창가의 화분에 물을 줘 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 준호야, 너 교실 창가에 앉지?",
        "M: 응, 맨 뒷줄 세 번째 자리.",
        "W: 우리 반 화분이 그 창가에 있어.",
        "M: 작은 초록 잎 달린 화분 세 개?",
        "W: 그거. 내가 보통 아침마다 물을 줘.",
        "M: 이번 주에 어디 가?",
        "W: 응, 내가 대회 가 있는 동안 물 좀 줄 수 있어?",
        "M: 그럼. 1교시 전에 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 별 관측의 밤에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Our star watching night is this Friday. " +
            "We will gather on the rooftop of the science building at eight. " +
            "Our science teacher will set up three telescopes for us. " +
            "The rooftop gets windy after dark, so bring a warm jacket. " +
            "We will look at the moon first and then at Jupiter. " +
            "See you on the rooftop this Friday evening.",
        ],
      ],
      choices: ["열리는 날", "모이는 장소", "망원경 대수", "옷차림", "끝나는 시각"],
      answer: 5,
      clue: "끝나는 시각은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(이번 주 금요일), 장소(과학관 옥상), 망원경 대수(세 대), 옷차림(따뜻한 겉옷)은 언급되지만 끝나는 시각은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 별 관측의 밤이 이번 주 금요일에 열립니다. 저녁 8시에 과학관 옥상에 모입니다. 과학 선생님이 망원경 세 대를 설치해 주십니다. 해가 진 뒤 옥상은 바람이 부니 따뜻한 겉옷을 가져오세요. 먼저 달을 보고 그다음에 목성을 봅니다. 이번 주 금요일 저녁에 옥상에서 만나요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a job that most people meet only when they are sick. " +
            "The person wears a white coat and keeps a stethoscope around the neck. " +
            "They listen to your chest and ask where it hurts. " +
            "Then they write a paper you take to the pharmacy. " +
            "They study for more than ten years before they can start working.",
        ],
      ],
      choices: ["약사", "간호사", "의사", "수의사", "치과 의사"],
      answer: 3,
      clue: "They listen to your chest and ask where it hurts.",
      explanation:
        "흰 가운과 청진기를 쓰고 가슴 소리를 들은 뒤 약국에 낼 종이를 써 주는 사람은 의사이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이 직업은 대부분의 사람이 아플 때만 만납니다. 이 일을 하는 사람은 흰 가운을 입고 목에 청진기를 걸고 있습니다. 여러분의 가슴 소리를 듣고 어디가 아픈지 묻습니다. 그다음 약국에 가져갈 종이를 써 줍니다. 일을 시작하기까지 10년 넘게 공부합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How often do you visit your grandparents?"],
        ["W", "About once a month."],
        ["ANN", "Number two."],
        ["M", "Where is the nearest pharmacy?"],
        ["W", "My favorite subject is history."],
        ["ANN", "Number three."],
        ["M", "Shall I close the window?"],
        ["W", "Yes, please. It's getting cold."],
        ["ANN", "Number four."],
        ["M", "What time should we leave?"],
        ["W", "Around seven would be fine."],
        ["ANN", "Number five."],
        ["M", "Did you enjoy the concert?"],
        ["W", "It was wonderful from start to finish."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Where is the nearest pharmacy?",
      explanation:
        "가장 가까운 약국이 어디인지 묻는 말에 좋아하는 과목이 역사라고 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① M: 할아버지 댁에 얼마나 자주 가? / W: 한 달에 한 번쯤.",
        "② M: 가장 가까운 약국이 어디야? / W: 내가 제일 좋아하는 과목은 역사야.",
        "③ M: 창문 닫을까? / W: 응, 닫아 줘. 추워지네.",
        "④ M: 몇 시에 출발할까? / W: 7시쯤이면 괜찮아.",
        "⑤ M: 공연 재미있었어? / W: 처음부터 끝까지 정말 좋았어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, the club bake sale opens in twenty minutes."],
        ["W", "I know. The cookies are all on the trays."],
        ["M", "Did you write the price on the little cards?"],
        ["W", "Yes, three cards, one for each kind."],
        ["M", "Good. But the table has no cover, and the wood is dusty."],
        ["W", "Oh, the cloth is still folded in the club room."],
        ["M", "I have to count the coins in the cash box."],
        ["W", "Then I'll run up and bring the table cloth."],
      ],
      choices: ["쿠키 담기", "가격표 쓰기", "동전 세기", "탁자보 가져오기", "손님 맞이하기"],
      answer: 4,
      clue: "Then I'll run up and bring the table cloth.",
      explanation:
        "탁자보가 동아리방에 있고 남자는 동전을 세야 해서, 여자가 올라가 탁자보를 가져오겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 채원아, 동아리 제과 판매가 20분 뒤에 열려.",
        "W: 알아. 쿠키는 다 쟁반에 올려놨어.",
        "M: 작은 카드에 가격은 썼어?",
        "W: 응, 종류마다 하나씩 세 장.",
        "M: 잘했다. 그런데 탁자에 보가 없어서 나무가 먼지투성이야.",
        "W: 아, 탁자보가 아직 동아리방에 개어져 있어.",
        "M: 나는 돈통에 든 동전을 세야 해.",
        "W: 그럼 내가 올라가서 탁자보 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 캠핑장을 고르시오.",
      lines: [
        ["W", "Junho, which campsite are you booking for the family trip?"],
        ["M", "Let me look at the list first."],
        ["W", "Do you need a place with showers?"],
        ["M", "Yes, my mother won't go without them."],
        ["W", "Okay. How far can you drive from home?"],
        ["M", "Under two hours, or my sister gets carsick."],
        ["W", "Got it. What about the price for one night?"],
        ["M", "Forty thousand won at most for the whole family."],
        ["W", "Then only one campsite on this list works."],
        ["M", "Good. I'll book it online tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Yes, my mother won't go without them.",
      explanation:
        "샤워장이 있고, 차로 두 시간 미만이며, 하룻밤 4만 원 이하인 곳을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Shower: Yes / Drive: 3 hours / Price: 35,000 won" },
          { no: 2, label: "②", value: "Shower: No / Drive: 1 hour / Price: 25,000 won" },
          { no: 3, label: "③", value: "Shower: Yes / Drive: 1 hour / Price: 50,000 won" },
          { no: 4, label: "④", value: "Shower: Yes / Drive: 1 hour 30 min / Price: 38,000 won" },
          { no: 5, label: "⑤", value: "Shower: No / Drive: 2 hours 30 min / Price: 30,000 won" },
        ],
      },
      translation: [
        "W: 준호야, 가족 여행 캠핑장 어디로 예약할 거야?",
        "M: 목록부터 볼게.",
        "W: 샤워장이 있는 곳이어야 해?",
        "M: 응, 엄마가 샤워장 없으면 안 가셔.",
        "W: 알겠어. 집에서 차로 얼마나 갈 수 있어?",
        "M: 두 시간 미만. 안 그러면 동생이 멀미해.",
        "W: 그렇구나. 하룻밤 가격은?",
        "M: 가족 전체에 최대 4만 원.",
        "W: 그럼 이 목록에서 되는 건 하나뿐이야.",
        "M: 좋아. 오늘 밤에 인터넷으로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 발표를 연습할 날짜를 고르시오.",
      lines: [
        ["W", "Junho, when can we practice the presentation together?"],
        ["M", "How about November 4th? That's next Tuesday."],
        ["W", "I have a dentist appointment that afternoon."],
        ["M", "Then what about November 6th?"],
        ["W", "The practice room is booked all day on the 6th."],
        ["M", "Hmm. I'm free on November 12th."],
        ["W", "But the presentation itself is on the 10th."],
        ["M", "Oh, right. Then let's practice on November 8th."],
        ["W", "November 8th works. It's a Saturday, so we have time."],
        ["M", "Great. Let's meet at the library at ten."],
      ],
      choices: ["11월 4일", "11월 6일", "11월 8일", "11월 10일", "11월 12일"],
      answer: 3,
      clue: "Oh, right. Then let's practice on November 8th.",
      explanation:
        "4일에는 치과 예약이, 6일에는 연습실 예약이 있고 12일은 발표(10일) 이후다. 두 사람은 11월 8일에 연습하기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 준호야, 발표 연습 언제 같이 할까?",
        "M: 11월 4일 어때? 다음 주 화요일이야.",
        "W: 그날 오후에 치과 예약이 있어.",
        "M: 그럼 11월 6일은?",
        "W: 6일엔 연습실이 하루 종일 예약돼 있어.",
        "M: 음. 나는 11월 12일이 비어.",
        "W: 그런데 발표가 10일이잖아.",
        "M: 아, 맞다. 그럼 11월 8일에 연습하자.",
        "W: 11월 8일 괜찮아. 토요일이라 시간 돼.",
        "M: 좋아. 10시에 도서관에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, why are your fingertips so red today?"],
        ["W", "I was at my grandmother's house all Sunday."],
        ["M", "Did you help her cook something?"],
        ["W", "No, we picked red peppers in her field."],
        ["M", "How many did you pick?"],
        ["W", "Six big baskets, and the sun was very strong."],
        ["M", "That sounds like hard work."],
        ["W", "It was, but she sent us home with a whole box."],
      ],
      choices: ["요리 돕기", "밭에서 고추 따기", "고추 말리기", "시장 가기", "할머니 댁 청소하기"],
      answer: 2,
      clue: "No, we picked red peppers in her field.",
      explanation:
        "여자는 일요일에 할머니 밭에서 고추를 여섯 바구니 땄다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 채원아, 오늘 손끝이 왜 이렇게 빨개?",
        "W: 일요일 내내 할머니 댁에 있었어.",
        "M: 요리 도와드렸어?",
        "W: 아니, 할머니 밭에서 고추를 땄어.",
        "M: 얼마나 땄어?",
        "W: 큰 바구니 여섯 개. 햇볕도 아주 셌어.",
        "M: 힘든 일이었겠다.",
        "W: 그랬는데, 한 상자 가득 싸 주셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement from the student council. " +
            "The water fountain on the second floor has been leaking since this morning. " +
            "Workers will repair it during the fourth and fifth periods today. " +
            "Until then, please use the fountains on the first or third floor. " +
            "Do not step on the wet floor near the second floor fountain. " +
            "Thank you for your understanding.",
        ],
      ],
      choices: [
        "정수기 사용 제한을 알리려고",
        "물 절약을 당부하려고",
        "학생회 회의를 알리려고",
        "청소 당번을 안내하려고",
        "시설 신고 방법을 알리려고",
      ],
      answer: 1,
      clue: "Until then, please use the fountains on the first or third floor.",
      explanation:
        "2층 정수기 수리로 4·5교시 동안 쓸 수 없으니 다른 층을 이용하라고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 안내 말씀 드립니다. 학생회입니다. 2층 정수기가 오늘 아침부터 물이 새고 있습니다. 오늘 4교시와 5교시 동안 작업자들이 수리합니다. 그때까지는 1층이나 3층 정수기를 이용해 주세요. 2층 정수기 근처 젖은 바닥은 밟지 마세요. 양해해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the aquarium?"],
        ["M", "Yes, two student tickets and two child tickets."],
        ["W", "A student ticket is eleven dollars and a child is six."],
        ["M", "So thirty-four dollars for the four of us?"],
        ["W", "That's right. Would you like a guide book?"],
        ["M", "No, thank you. Just the tickets."],
        ["W", "All right. Groups of four get six dollars off."],
        ["M", "That's good news. Here you are."],
      ],
      choices: ["$24", "$26", "$28", "$30", "$34"],
      answer: 3,
      clue: "All right. Groups of four get six dollars off.",
      explanation:
        "학생 표 두 장 22달러와 어린이 표 두 장 12달러를 더하면 34달러이고, 4인 단체 할인 6달러를 빼면 28달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 수족관 표 사시나요?",
        "M: 네, 학생 두 장이랑 어린이 두 장이요.",
        "W: 학생 표는 11달러, 어린이 표는 6달러입니다.",
        "M: 그럼 네 명이 34달러인가요?",
        "W: 맞습니다. 안내 책자도 드릴까요?",
        "M: 아니요, 괜찮아요. 표만 주세요.",
        "W: 알겠습니다. 4인 단체는 6달러 할인됩니다.",
        "M: 좋은 소식이네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, you've been rewriting that same page all week."],
        ["M", "The opening of my story still feels boring."],
        ["W", "What does the first line say right now?"],
        ["M", "It describes the weather and the town."],
        ["W", "That's where most boring openings start."],
        ["M", "But readers need to know where the story happens."],
        ["W", "They can learn that later, in the middle of an action."],
        ["M", "So what should the first line be instead?"],
        ["W", "Start with your character already doing something."],
      ],
      choices: [
        "I'll rewrite the opening tonight.",
        "My story has no characters.",
        "I already finished the story.",
        "The weather is the whole point.",
        "Let's write about the town.",
      ],
      answer: 1,
      clue: "Start with your character already doing something.",
      explanation:
        "여자가 인물이 무언가를 하고 있는 장면으로 시작하라고 했으므로, 오늘 밤 도입부를 다시 쓰겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 일주일 내내 그 한 쪽만 고쳐 쓰네.",
        "M: 이야기 도입부가 아직 지루해.",
        "W: 지금 첫 문장이 뭐라고 돼 있어?",
        "M: 날씨랑 마을을 설명해.",
        "W: 지루한 도입부는 대개 거기서 시작해.",
        "M: 그래도 어디서 일어나는지는 알려 줘야지.",
        "W: 그건 나중에 사건 한가운데서 알려 줘도 돼.",
        "M: 그럼 첫 문장은 뭐로 해야 해?",
        "W: 인물이 이미 뭔가를 하고 있는 장면으로 시작해.",
        "M: 오늘 밤에 도입부를 다시 쓸게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaewon, your water bottle smells a little strange."],
        ["W", "I noticed too, and I rinse it every night."],
        ["M", "Do you take the lid apart when you wash it?"],
        ["W", "No, I just run water through the whole thing."],
        ["M", "There's a rubber ring inside the lid that traps water."],
        ["W", "I didn't know the lid came apart at all."],
        ["M", "It does, and that ring is usually the smelly part."],
        ["W", "How do I get the ring out without breaking it?"],
        ["M", "Push it up from underneath with a toothpick."],
      ],
      choices: [
        "My bottle has no lid.",
        "I wash the ring every day.",
        "The smell comes from the water.",
        "I'll buy a new bottle tomorrow.",
        "I'll try that when I get home.",
      ],
      answer: 5,
      clue: "Push it up from underneath with a toothpick.",
      explanation:
        "남자가 이쑤시개로 고무 고리를 밀어 빼라고 알려 주었으므로, 집에 가서 해 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "M: 채원아, 네 물병에서 좀 이상한 냄새가 나.",
        "W: 나도 느꼈어. 매일 밤 헹구는데.",
        "M: 씻을 때 뚜껑을 분해해?",
        "W: 아니, 그냥 통째로 물만 흘려보내.",
        "M: 뚜껑 안에 물이 고이는 고무 고리가 있어.",
        "W: 뚜껑이 분해되는 줄도 몰랐어.",
        "M: 분해돼. 그리고 보통 그 고리에서 냄새가 나.",
        "W: 고리를 안 부러뜨리고 어떻게 빼?",
        "M: 이쑤시개로 아래에서 위로 밀어 올려.",
        "W: 집에 가서 해 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Chaewon, our class movie day was a complete mess."],
        ["W", "I heard the sound kept cutting out."],
        ["M", "Every five minutes, right in the middle of a line."],
        ["W", "Was the laptop plugged into the wall?"],
        ["M", "No, we ran it on the battery the whole time."],
        ["W", "A low battery makes the laptop slow everything down."],
        ["M", "I never thought the battery could do that."],
        ["W", "It does, especially with a big video file."],
        ["M", "So what should we do for next month's movie day?"],
        ["W", "Plug the laptop in before you start, every time."],
      ],
      choices: [
        "I'll plug it in next time.",
        "We have no laptop at all.",
        "The battery was full.",
        "Let's cancel movie day.",
        "The sound was perfect.",
      ],
      answer: 1,
      clue: "Plug the laptop in before you start, every time.",
      explanation:
        "여자가 시작 전에 노트북을 꼭 전원에 연결하라고 했으므로, 다음에는 연결하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 채원아, 우리 반 영화의 날은 완전히 엉망이었어.",
        "W: 소리가 자꾸 끊겼다고 들었어.",
        "M: 5분마다, 그것도 대사 한가운데서.",
        "W: 노트북을 콘센트에 꽂아 놨어?",
        "M: 아니, 내내 배터리로 돌렸어.",
        "W: 배터리가 부족하면 노트북이 전체를 느리게 해.",
        "M: 배터리가 그런 영향을 주는 줄 몰랐어.",
        "W: 그래, 특히 큰 영상 파일이면 더해.",
        "M: 그럼 다음 달 영화의 날엔 어떻게 해야 해?",
        "W: 시작하기 전에 매번 노트북을 꽂아 둬.",
        "M: 다음엔 꽂아 놓을게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sumin이 Jaeha에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Sumin : ________________",
      lines: [
        [
          "W",
          "Sumin and Jaeha are working together in the school kitchen. " +
            "They are making soup for the class cooking lesson. " +
            "Jaeha reaches for the pot handle with his bare hand. " +
            "Sumin knows the pot has been over the flame for ten minutes. " +
            "She wants to stop him before he burns his hand. " +
            "In this situation, what would Sumin most likely say to Jaeha?",
        ],
      ],
      choices: [
        "Let's add more salt to the soup.",
        "The flame is already off.",
        "I'll wash the pot later.",
        "Wait, use the oven mitt.",
        "We need a bigger pot.",
      ],
      answer: 4,
      clue: "She wants to stop him before he burns his hand.",
      explanation:
        "재하가 10분 동안 불 위에 있던 뜨거운 냄비 손잡이를 맨손으로 잡으려 하므로, 주방 장갑을 쓰라고 말리는 ④가 가장 적절하다.",
      translation: [
        "W: 수민이와 재하는 학교 조리실에서 함께 일하고 있습니다. 두 사람은 학급 요리 수업에 쓸 국을 끓이고 있습니다. 재하는 냄비 손잡이를 맨손으로 잡으려고 손을 뻗습니다. 수민이는 그 냄비가 10분 동안 불 위에 있었다는 것을 압니다. 수민이는 재하가 손을 데기 전에 말리고 싶습니다. 이런 상황에서 수민이가 재하에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
