/** 중2 듣기 43회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 43회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 고를 배낭을 고르시오.",
      lines: [
        ["M", "Hyewon, are you choosing a backpack for the trip?"],
        ["W", "Yes, but there are too many kinds here."],
        ["M", "This one has a big front pocket."],
        ["W", "I'd rather have two side pockets for bottles."],
        ["M", "Do you want one with wheels at the bottom?"],
        ["W", "No wheels. They make the bag too heavy."],
        ["M", "How about the pattern on the front?"],
        ["W", "I like the one with stripes across it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I'd rather have two side pockets for bottles. / I like the one with stripes across it.",
      explanation:
        "양옆 주머니가 있고 바퀴가 없으며 줄무늬가 있는 배낭이다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five backpacks side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a backpack with one big FRONT POCKET and plain surface, no wheels. " +
          "② a backpack with two SIDE POCKETS and plain surface, with small WHEELS at the bottom. " +
          "③ a backpack with two SIDE POCKETS and horizontal STRIPES across the front, no wheels. " +
          "④ a backpack with one big FRONT POCKET and horizontal STRIPES, with WHEELS at the bottom. " +
          "⑤ a backpack with two SIDE POCKETS and large DOTS on the front, no wheels.",
      },
      translation: [
        "M: 혜원아, 여행 갈 배낭 고르는 중이야?",
        "W: 응, 그런데 종류가 너무 많아.",
        "M: 이건 앞주머니가 크네.",
        "W: 나는 물병 넣을 옆주머니 두 개가 더 좋아.",
        "M: 아래에 바퀴 달린 걸로 할래?",
        "W: 바퀴는 안 돼. 가방이 너무 무거워져.",
        "M: 앞면 무늬는 어때?",
        "W: 가로 줄무늬 있는 게 마음에 들어.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 음악회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minseok, are you playing at the school concert?"],
        ["M", "I am. Do you know when it starts?"],
        ["W", "Next Thursday at four in the afternoon."],
        ["M", "Where are they holding it this year?"],
        ["W", "In the main hall on the first floor."],
        ["M", "How many teams are performing that day?"],
        ["W", "Eight teams, and each plays for ten minutes."],
        ["M", "Can families come and watch us play?"],
        ["W", "Parents are welcome, but seats are limited."],
      ],
      choices: ["시작 시각", "열리는 장소", "공연 팀 수", "가족 관람 여부", "입장료"],
      answer: 5,
      clue: "Next Thursday at four in the afternoon.",
      explanation:
        "시각, 장소, 팀 수, 가족 관람은 말했지만 입장료는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민석아, 학교 음악회에서 연주해?",
        "M: 응. 언제 시작하는지 알아?",
        "W: 다음 주 목요일 오후 네 시.",
        "M: 올해는 어디서 해?",
        "W: 1층 대강당에서.",
        "M: 그날 몇 팀이 공연해?",
        "W: 여덟 팀이고, 한 팀당 10분씩 연주해.",
        "M: 가족들도 와서 볼 수 있어?",
        "W: 부모님도 오실 수 있는데 자리가 한정돼 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Come in, Jaewon. You look worried today."],
        ["M", "Do you have a few minutes to talk?"],
        ["W", "Of course. Is it about your grades?"],
        ["M", "It's about the science club and the debate club."],
        ["W", "You joined both of them in March, didn't you?"],
        ["M", "They both meet on Wednesday afternoon now."],
        ["W", "So you can't go to both any more."],
        ["M", "I can't decide which one to leave."],
        ["W", "That's a hard choice for anyone."],
        ["M", "I came to ask for your advice about it."],
      ],
      choices: [
        "조언을 구하려고",
        "결석을 알리려고",
        "물건을 빌리려고",
        "숙제를 내려고",
        "감사를 전하려고",
      ],
      answer: 1,
      clue: "I came to ask for your advice about it.",
      explanation:
        "남자는 어느 동아리를 그만둘지 조언을 구하러 왔다. 따라서 답은 ①이다.",
      translation: [
        "W: 들어와, 재원아. 오늘 걱정이 있어 보이네.",
        "M: 잠깐 말씀드릴 시간 있으세요?",
        "W: 그럼. 성적 때문이니?",
        "M: 과학 동아리랑 토론 동아리 때문이에요.",
        "W: 3월에 둘 다 들어갔지?",
        "M: 이제 둘 다 수요일 오후에 모여요.",
        "W: 그럼 둘 다 갈 수는 없겠구나.",
        "M: 어느 쪽을 그만둘지 못 정하겠어요.",
        "W: 누구에게나 어려운 선택이지.",
        "M: 그 일로 조언을 구하러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 버스를 탈 시각을 고르시오.",
      lines: [
        ["M", "Seoyul, what time is the bus to the stadium?"],
        ["W", "There is one at eleven and another at noon."],
        ["M", "The game starts at one o'clock sharp."],
        ["W", "The ride takes about forty minutes."],
        ["M", "The noon bus would still get us there in time."],
        ["W", "But I want to buy food before the game."],
        ["M", "Then we should take the eleven o'clock bus."],
        ["W", "Eleven it is. Don't be late this time."],
        ["M", "I'll wait at the stop from ten fifty."],
      ],
      choices: ["10:50 a.m.", "11:00 a.m.", "11:40 a.m.", "12:00 p.m.", "1:00 p.m."],
      answer: 2,
      clue: "Then we should take the eleven o'clock bus.",
      explanation:
        "경기 전에 음식을 사려고 11시 버스를 타기로 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 서율아, 경기장 가는 버스가 몇 시야?",
        "W: 11시 차랑 12시 차가 있어.",
        "M: 경기는 1시 정각에 시작해.",
        "W: 타고 가는 데 40분쯤 걸려.",
        "M: 12시 차를 타도 늦지는 않겠네.",
        "W: 그런데 경기 전에 먹을 걸 사고 싶어.",
        "M: 그럼 11시 버스를 타야겠다.",
        "W: 11시로 하자. 이번엔 늦지 마.",
        "M: 10시 50분부터 정류장에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunji, your team won the relay race today."],
        ["W", "We passed the last team on the final corner."],
        ["M", "I saw you run the fourth part."],
        ["W", "My legs were shaking at the finish line."],
        ["M", "Everyone in our class was shouting for you."],
        ["W", "I could hear them the whole way."],
        ["M", "You must be happy about the medal."],
        ["W", "It was the best moment of the year."],
      ],
      choices: ["scared", "sorry", "bored", "worried", "delighted"],
      answer: 5,
      clue: "It was the best moment of the year.",
      explanation:
        "이어달리기에서 이겨 올해 최고의 순간이라고 하므로 매우 기뻐하고 있다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 은지야, 오늘 너희 팀이 이어달리기에서 이겼네.",
        "W: 마지막 모퉁이에서 앞 팀을 제쳤어.",
        "M: 네가 네 번째 주자로 뛰는 거 봤어.",
        "W: 결승선에서 다리가 후들거렸어.",
        "M: 우리 반 전체가 너를 응원했어.",
        "W: 뛰는 내내 그 소리가 들렸어.",
        "M: 메달 받아서 기분 좋겠다.",
        "W: 올해 가장 좋은 순간이었어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Do you have this book in stock?"],
        ["W", "Let me look it up."],
        ["ANN", "Number two."],
        ["M", "May I borrow your umbrella?"],
        ["W", "Sure, I have another one."],
        ["ANN", "Number three."],
        ["M", "Where should I put the trash?"],
        ["W", "In the blue bin over there."],
        ["ANN", "Number four."],
        ["M", "Can you help me carry this?"],
        ["W", "I'll take the other side."],
        ["ANN", "Number five."],
        ["M", "Is the elevator working?"],
        ["W", "No, please use the stairs."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Can you help me carry this?",
      explanation:
        "그림은 긴 책상을 혼자 들지 못해 한쪽을 함께 드는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "In a school hallway, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy struggles to lift one end of a long, heavy table by himself and looks toward a girl. " +
          "The girl steps forward and grips the other end of the table with both hands. " +
          "Classroom doors and a bulletin board are drawn simply along the wall behind them.",
      },
      translation: [
        "① M: 이 책 재고 있나요? / W: 찾아볼게요.",
        "② M: 우산 좀 빌려도 될까? / W: 그래, 하나 더 있어.",
        "③ M: 쓰레기는 어디에 버려? / W: 저기 파란 통에.",
        "④ M: 이것 좀 같이 들어 줄래? / W: 내가 반대쪽 들게.",
        "⑤ M: 승강기 되나요? / W: 아니요, 계단을 이용하세요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunbin, you drew the class calendar last term."],
        ["M", "The one with a different picture each month?"],
        ["W", "Yes, everyone still talks about it."],
        ["M", "It took me three weekends to finish."],
        ["W", "Our club is making a welcome sign for new members."],
        ["M", "Is it the big board by the club room door?"],
        ["W", "That's the one, and nobody can draw well."],
        ["M", "What do you need on the sign?"],
        ["W", "Could you draw the pictures for our sign?"],
        ["M", "All right, but I need a week."],
      ],
      choices: [
        "그림을 그려 주기",
        "글씨를 써 주기",
        "달력을 빌려주기",
        "새 회원을 모아 주기",
        "동아리방을 청소하기",
      ],
      answer: 1,
      clue: "Could you draw the pictures for our sign?",
      explanation:
        "여자는 환영 게시판에 들어갈 그림을 그려 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 현빈아, 지난 학기 학급 달력 네가 그렸잖아.",
        "M: 달마다 그림이 다른 그거?",
        "W: 응, 다들 아직도 그 얘기를 해.",
        "M: 다 그리는 데 주말 세 번 걸렸어.",
        "W: 우리 동아리가 새 회원 환영 게시판을 만들어.",
        "M: 동아리방 문 옆에 있는 큰 판?",
        "W: 그거야. 그런데 그림 잘 그리는 사람이 없어.",
        "M: 게시판에 뭐가 필요한데?",
        "W: 게시판에 들어갈 그림 좀 그려 줄 수 있어?",
        "M: 알겠어, 대신 일주일은 필요해.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학생 기자단 모집에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, everyone. The school broadcasting room needs student reporters. " +
            "We are looking for four students this semester. " +
            "You will record short news for the morning broadcast. " +
            "Training happens every Tuesday after the sixth period. " +
            "Anyone in the first or second grade may apply. " +
            "Come to the broadcasting room to sign your name.",
        ],
      ],
      choices: ["뽑는 인원", "맡게 되는 일", "교육하는 요일", "지원 가능한 학년", "활동 기간"],
      answer: 5,
      clue: "We are looking for four students this semester.",
      explanation:
        "인원, 하는 일, 교육 요일, 학년은 말했지만 활동 기간은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여러분, 안녕하세요. 학교 방송실에서 학생 기자를 뽑습니다. 이번 학기에 네 명을 찾고 있습니다. 아침 방송에 나갈 짧은 소식을 녹음하게 됩니다. 교육은 매주 화요일 6교시 후에 합니다. 1학년이나 2학년이면 누구나 지원할 수 있습니다. 방송실로 와서 이름을 적어 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You use this when you want to see something far away. " +
            "You hold it up and look through two small circles. " +
            "Bird watchers carry it into the forest every morning. " +
            "It makes a distant mountain look very close. " +
            "People also take it to baseball games and concerts.",
        ],
      ],
      choices: ["안경", "현미경", "쌍안경", "거울", "사진기"],
      answer: 3,
      clue: "You hold it up and look through two small circles.",
      explanation:
        "두 개의 렌즈로 먼 것을 가까이 보는 도구는 쌍안경이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 멀리 있는 것을 보고 싶을 때 씁니다. 들어 올려 작은 원 두 개로 들여다봅니다. 새를 관찰하는 사람들은 아침마다 이것을 숲에 가지고 갑니다. 먼 산을 아주 가깝게 보이게 합니다. 사람들은 야구 경기나 공연에도 이것을 가져갑니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How do you get to school?"],
        ["M", "I ride my bike."],
        ["ANN", "Number two."],
        ["W", "What time does the class end?"],
        ["M", "I like math best."],
        ["ANN", "Number three."],
        ["W", "Would you like some water?"],
        ["M", "Yes, please. I'm thirsty."],
        ["ANN", "Number four."],
        ["W", "Did you finish the drawing?"],
        ["M", "Not yet, maybe tomorrow."],
        ["ANN", "Number five."],
        ["W", "Can I sit next to you?"],
        ["M", "Sure, the seat is empty."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "What time does the class end?",
      explanation:
        "수업이 몇 시에 끝나는지 묻는 말에 좋아하는 과목을 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① W: 학교에 어떻게 와? / M: 자전거 타고 와.",
        "② W: 수업 몇 시에 끝나? / M: 나는 수학이 제일 좋아.",
        "③ W: 물 좀 마실래? / M: 응, 목말라.",
        "④ W: 그림 다 그렸어? / M: 아직. 내일쯤.",
        "⑤ W: 네 옆에 앉아도 돼? / M: 그럼, 자리 비었어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Wonjun, the class picture is in ten minutes."],
        ["M", "I know, everyone is lining up outside."],
        ["W", "Your name tag is missing from your shirt."],
        ["M", "I took it off during gym class."],
        ["W", "The teacher checks name tags in the photo."],
        ["M", "It's in my desk drawer upstairs."],
        ["W", "You have just enough time to run up."],
        ["M", "I'll go and get my name tag."],
      ],
      choices: [
        "사진을 찍기",
        "이름표를 가지러 가기",
        "줄을 서기",
        "체육복을 갈아입기",
        "선생님을 부르기",
      ],
      answer: 2,
      clue: "I'll go and get my name tag.",
      explanation:
        "남자는 교실에 있는 이름표를 가지러 가겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 원준아, 10분 뒤에 반 사진 찍어.",
        "M: 알아, 다들 밖에 줄 서고 있어.",
        "W: 네 셔츠에 이름표가 없어.",
        "M: 체육 시간에 떼어 놨어.",
        "W: 선생님이 사진에서 이름표를 확인하셔.",
        "M: 위층 책상 서랍에 있어.",
        "W: 뛰어갔다 올 시간은 딱 돼.",
        "M: 가서 이름표 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 예약할 숙소를 고르시오.",
      lines: [
        ["M", "Dahye, which place will your family stay at?"],
        ["W", "There are five places near the beach."],
        ["M", "How much can your family spend a night?"],
        ["W", "No more than a hundred thousand won."],
        ["M", "One of them is far above that."],
        ["W", "We also need a room for four people."],
        ["M", "Two of them take only three guests."],
        ["W", "And breakfast should be included in the price."],
        ["M", "Then one place matches everything you said."],
        ["W", "I'll book it before the weekend."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "No more than a hundred thousand won.",
      explanation:
        "10만 원 이하, 4인실, 조식 포함인 숙소는 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 130,000 won / Guests: 4 / Breakfast: Yes" },
          { no: 2, label: "②", value: "Price: 90,000 won / Guests: 3 / Breakfast: Yes" },
          { no: 3, label: "③", value: "Price: 85,000 won / Guests: 3 / Breakfast: No" },
          { no: 4, label: "④", value: "Price: 95,000 won / Guests: 4 / Breakfast: No" },
          { no: 5, label: "⑤", value: "Price: 98,000 won / Guests: 4 / Breakfast: Yes" },
        ],
      },
      translation: [
        "M: 다혜야, 너희 가족은 어디에 묵을 거야?",
        "W: 해변 근처에 다섯 군데가 있어.",
        "M: 하룻밤에 얼마까지 쓸 수 있어?",
        "W: 10만 원을 넘으면 안 돼.",
        "M: 하나는 그보다 훨씬 비싸네.",
        "W: 그리고 네 명이 묵을 방이어야 해.",
        "M: 두 곳은 세 명까지만 받아.",
        "W: 그리고 아침 식사가 값에 포함돼야 해.",
        "M: 그럼 네가 말한 조건에 다 맞는 곳은 하나야.",
        "W: 주말 전에 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 자원봉사를 갈 날짜를 고르시오.",
      lines: [
        ["W", "Jiseok, when should we go to the food bank?"],
        ["M", "They said the fourth, the eleventh or the eighteenth."],
        ["W", "The fourth is the day of the midterm exam."],
        ["M", "Nobody would want to go right after that."],
        ["W", "The eighteenth is my grandmother's birthday."],
        ["M", "Then the eleventh is the only day left."],
        ["W", "Do they need us in the morning or afternoon?"],
        ["M", "From ten to one, on the eleventh."],
        ["W", "I'll write both our names on the list."],
      ],
      choices: ["the 4th", "the 11th", "the 18th", "the 7th", "the 14th"],
      answer: 2,
      clue: "Then the eleventh is the only day left.",
      explanation:
        "4일은 시험 날, 18일은 할머니 생신이어서 11일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 지석아, 푸드뱅크에 언제 갈까?",
        "M: 4일, 11일, 18일 중에 오라고 했어.",
        "W: 4일은 중간고사 날이야.",
        "M: 시험 끝나고 바로 가고 싶은 사람은 없겠지.",
        "W: 18일은 할머니 생신이야.",
        "M: 그럼 남는 날은 11일뿐이네.",
        "W: 오전에 오래, 오후에 오래?",
        "M: 11일 10시부터 1시까지.",
        "W: 명단에 우리 둘 이름 적을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kyungmin, you look tired this morning."],
        ["M", "I cleaned the whole attic with my father."],
        ["W", "Why did you do that on a school night?"],
        ["M", "We are moving to a new house next month."],
        ["W", "What did you find up there?"],
        ["M", "Old photo albums and my father's school books."],
        ["W", "Did you throw everything away?"],
        ["M", "We kept the albums and gave the rest away."],
        ["W", "How long did the whole thing take?"],
        ["M", "From dinner until almost midnight."],
      ],
      choices: [
        "친구와 공부했다",
        "아버지와 다락을 치웠다",
        "새집을 보러 갔다",
        "사진을 찍었다",
        "일찍 잠을 잤다",
      ],
      answer: 2,
      clue: "I cleaned the whole attic with my father.",
      explanation:
        "남자는 어제 아버지와 다락을 치웠다. 따라서 답은 ②이다.",
      translation: [
        "W: 경민아, 오늘 아침에 피곤해 보이네.",
        "M: 아버지랑 다락을 다 치웠어.",
        "W: 학교 가는 날 밤에 왜 그걸 했어?",
        "M: 다음 달에 새집으로 이사 가거든.",
        "W: 거기서 뭘 찾았어?",
        "M: 오래된 사진첩이랑 아버지 학창 시절 책들.",
        "W: 다 버렸어?",
        "M: 사진첩은 남기고 나머지는 나눠 줬어.",
        "W: 다 하는 데 얼마나 걸렸어?",
        "M: 저녁 먹고부터 거의 자정까지.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Good morning, students. This is the health office speaking. " +
            "Many students in every grade have caught colds this week. " +
            "Please wash your hands with soap before you eat lunch. " +
            "Open the classroom windows for five minutes every hour. " +
            "Cover your mouth with your sleeve when you cough. " +
            "If you have a fever, come to the health office right away. " +
            "Do not share your water bottle with your friends. " +
            "Take good care of yourselves this week.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "도서 반납을 알리려고",
        "감기 예방을 당부하려고",
        "봉사자를 모으려고",
        "급식 시간을 바꾸려고",
      ],
      answer: 3,
      clue: "Many students in every grade have caught colds this week.",
      explanation:
        "손 씻기와 환기를 당부하며 감기 예방을 안내하는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 보건실입니다. 이번 주에 학년마다 감기에 걸린 학생이 많습니다. 점심 먹기 전에 비누로 손을 씻어 주세요. 매시간 교실 창문을 5분씩 열어 주세요. 기침할 때는 소매로 입을 가려 주세요. 열이 나면 바로 보건실로 오세요. 물병은 친구와 같이 쓰지 마세요. 이번 주 건강에 유의하기 바랍니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What would you like to order?"],
        ["W", "Two sandwiches and one bottle of juice, please."],
        ["M", "Sandwiches are four dollars each today."],
        ["W", "And how much is the juice?"],
        ["M", "Three dollars for a large bottle."],
        ["W", "Do I pay extra for eating here?"],
        ["M", "No, the price is the same either way."],
        ["W", "Is there a discount with a student card?"],
        ["M", "Sorry, not on sandwiches."],
        ["W", "All right, here is my money."],
      ],
      choices: ["$9", "$10", "$11", "$12", "$13"],
      answer: 3,
      clue: "Sandwiches are four dollars each today.",
      explanation:
        "샌드위치 두 개 8달러와 주스 3달러를 더하면 11달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 무엇을 주문하시겠어요?",
        "W: 샌드위치 두 개랑 주스 한 병 주세요.",
        "M: 오늘 샌드위치는 하나에 4달러입니다.",
        "W: 주스는 얼마예요?",
        "M: 큰 병은 3달러입니다.",
        "W: 여기서 먹으면 돈을 더 내나요?",
        "M: 아니요, 값은 똑같습니다.",
        "W: 학생증으로 할인되나요?",
        "M: 죄송하지만 샌드위치는 안 됩니다.",
        "W: 알겠습니다. 여기 돈이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Suhyun, you never seem to lose anything."],
        ["W", "Every item in my bag has its own place."],
        ["M", "Does that really take a lot of time?"],
        ["W", "About two minutes before I leave home."],
        ["M", "I spend ten minutes looking for my key."],
        ["W", "Put the key in the same pocket every time."],
        ["M", "Even when I'm in a hurry?"],
        ["W", "Especially when you are in a hurry."],
        ["M", "Where should I keep my bus card then?"],
      ],
      choices: [
        "Throw the card away.",
        "You don't need a bus card.",
        "Keep it in the front pocket.",
        "I lost my card yesterday.",
        "Buy a new bag today.",
      ],
      answer: 3,
      clue: "Where should I keep my bus card then?",
      explanation:
        "버스 카드를 어디에 둘지 물었으므로, 앞주머니에 두라는 ③이 가장 자연스럽다.",
      translation: [
        "M: 수현아, 너는 물건을 잃어버리는 법이 없네.",
        "W: 가방 속 물건마다 자리가 정해져 있어.",
        "M: 그렇게 하는 데 시간이 많이 들지 않아?",
        "W: 집에서 나가기 전에 2분쯤.",
        "M: 나는 열쇠 찾는 데 10분을 써.",
        "W: 열쇠는 늘 같은 주머니에 넣어.",
        "M: 급할 때도?",
        "W: 급할 때일수록 더.",
        "M: 그럼 버스 카드는 어디에 둘까?",
        "W: 앞주머니에 넣어 둬.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Yohan, I heard you joined the school baking class."],
        ["M", "My grandmother taught me to make bread last winter."],
        ["W", "How often does the class meet after school?"],
        ["M", "Every Monday and Thursday in the cooking room."],
        ["W", "What have you made there so far?"],
        ["M", "Butter rolls, cookies and one very flat cake."],
        ["W", "A flat cake doesn't sound like a success."],
        ["M", "I forgot to add the baking powder that day."],
        ["W", "Did you try making the cake again?"],
        ["M", "The second one rose perfectly last week."],
        ["W", "Could you teach me the recipe sometime?"],
      ],
      choices: [
        "Sure, come on Thursday.",
        "I can't bake at all.",
        "The class is closed now.",
        "You should buy a cake.",
        "I never make cookies.",
      ],
      answer: 1,
      clue: "Could you teach me the recipe sometime?",
      explanation:
        "조리법을 가르쳐 달라고 했으므로, 목요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 요한아, 학교 제빵 수업 들어갔다며.",
        "M: 지난겨울에 할머니가 빵 만드는 법을 가르쳐 주셨어.",
        "W: 방과 후에 얼마나 자주 모여?",
        "M: 매주 월요일이랑 목요일에 조리실에서.",
        "W: 지금까지 뭘 만들었어?",
        "M: 버터 롤, 쿠키, 그리고 아주 납작한 케이크 하나.",
        "W: 납작한 케이크는 성공은 아니었나 보네.",
        "M: 그날 베이킹파우더 넣는 걸 잊었어.",
        "W: 케이크 다시 만들어 봤어?",
        "M: 두 번째 건 지난주에 완벽하게 부풀었어.",
        "W: 나한테도 언제 조리법 좀 알려 줄래?",
        "M: 그럼, 목요일에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yoonseo, how is your English speaking practice going?"],
        ["M", "You said you wanted to speak more smoothly."],
        ["W", "I memorize new words but forget them in a week."],
        ["M", "How many words do you study at one time?"],
        ["W", "About fifty on Sunday evening."],
        ["M", "That's a lot to hold in your head at once."],
        ["W", "I know, but I don't have time on weekdays."],
        ["M", "Ten words a day take only five minutes."],
        ["W", "Five minutes I could find every day."],
        ["M", "Why don't you split the list across the week?"],
      ],
      choices: [
        "I'll start with ten tonight.",
        "I already know every word.",
        "I'll study a hundred words.",
        "English has no new words.",
        "I stopped studying English.",
      ],
      answer: 1,
      clue: "Why don't you split the list across the week?",
      explanation:
        "목록을 일주일에 나누라는 제안이므로, 오늘 밤 열 개부터 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 윤서야, 영어 말하기 연습은 잘돼 가?",
        "M: 더 매끄럽게 말하고 싶다고 했잖아.",
        "W: 새 단어를 외워도 일주일이면 잊어버려.",
        "M: 한 번에 몇 개씩 외워?",
        "W: 일요일 저녁에 쉰 개쯤.",
        "M: 한 번에 머리에 담기에는 많다.",
        "W: 알아, 그런데 평일에는 시간이 없어.",
        "M: 하루에 열 개면 5분밖에 안 걸려.",
        "W: 5분은 매일 낼 수 있겠다.",
        "M: 목록을 일주일에 나눠 보는 건 어때?",
        "W: 오늘 밤에 열 개부터 시작할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Doyun이 Miso에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Doyun : ________________",
      lines: [
        [
          "M",
          "Doyun and Miso are practicing for the school play together. " +
            "Miso keeps speaking too quietly during her long speech. " +
            "Doyun is sitting in the back row and cannot hear the words. " +
            "The hall is much larger than their classroom. " +
            "He wants her to speak louder so everyone can hear her. " +
            "In this situation, what would Doyun most likely say to Miso?",
        ],
      ],
      choices: [
        "Your speech is too long.",
        "Try speaking a little louder.",
        "Let's change the play.",
        "I'll read your part instead.",
        "The hall is very small.",
      ],
      answer: 2,
      clue: "He wants her to speak louder so everyone can hear her.",
      explanation:
        "목소리가 작아 뒷자리에서 안 들리므로, 조금 더 크게 말해 보라는 ②가 가장 적절하다.",
      translation: [
        "M: 도윤이와 미소는 학교 연극 연습을 함께 하고 있습니다. 미소는 긴 대사를 하는 동안 계속 너무 작게 말합니다. 도윤이는 뒷줄에 앉아 있는데 말이 들리지 않습니다. 강당은 교실보다 훨씬 큽니다. 그는 모두가 들을 수 있도록 미소가 더 크게 말하기를 바랍니다. 이런 상황에서 도윤이가 미소에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
