/** 중2 듣기 50회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 50회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 만들 연을 고르시오.",
      lines: [
        ["W", "Hyunsik, what kind of kite are you making?"],
        ["M", "A simple one with a diamond shape."],
        ["W", "Are you drawing a face on the front?"],
        ["M", "No face. I'm painting three wide stripes."],
        ["W", "Will the stripes go up and down?"],
        ["M", "Across, from one side to the other."],
        ["W", "How many tails are you attaching?"],
        ["M", "Just one long tail at the bottom."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Across, from one side to the other. / Just one long tail at the bottom.",
      explanation:
        "마름모 연에 가로 줄무늬 세 개와 아래에 긴 꼬리 하나가 달린 것이다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five paper kites side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a DIAMOND kite with three VERTICAL stripes and ONE long tail at the bottom. " +
          "② a DIAMOND kite with three HORIZONTAL stripes and ONE long tail at the bottom. " +
          "③ a DIAMOND kite with three HORIZONTAL stripes and TWO tails at the bottom. " +
          "④ a DIAMOND kite with a simple FACE drawn on it and one tail. " +
          "⑤ a BOX-shaped kite with three HORIZONTAL stripes and one tail.",
      },
      translation: [
        "W: 현식아, 어떤 연을 만들어?",
        "M: 마름모 모양으로 단순하게.",
        "W: 앞면에 얼굴을 그려?",
        "M: 얼굴은 안 그려. 넓은 줄무늬 세 개를 칠할 거야.",
        "W: 줄무늬는 위아래로 그려?",
        "M: 가로로, 한쪽에서 반대쪽까지.",
        "W: 꼬리는 몇 개 달아?",
        "M: 아래에 긴 꼬리 하나만.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 도서 교환 행사에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Suhyeon, what is the book exchange day about?"],
        ["W", "You bring a book and take another one home."],
        ["M", "When does it happen this term?"],
        ["W", "On the last Wednesday of this month."],
        ["M", "Where do we bring the books?"],
        ["W", "To the long tables in the library lobby."],
        ["M", "How many books can one student bring?"],
        ["W", "Up to three, and you take the same number."],
        ["M", "What kinds of books are allowed?"],
        ["W", "Any book except school textbooks."],
      ],
      choices: ["행사 날짜", "책을 가져갈 곳", "가져올 수 있는 권수", "가져올 수 없는 책", "남은 책의 처리"],
      answer: 5,
      clue: "On the last Wednesday of this month.",
      explanation:
        "날짜, 장소, 권수, 제외 도서는 말했지만 남은 책 처리는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 수현아, 책 바꾸는 날이 뭐야?",
        "W: 책을 한 권 가져오면 다른 책을 가져갈 수 있어.",
        "M: 이번 학기에는 언제 해?",
        "W: 이번 달 마지막 수요일에.",
        "M: 책은 어디로 가져가?",
        "W: 도서관 앞 긴 탁자로.",
        "M: 한 사람이 몇 권까지 가져올 수 있어?",
        "W: 세 권까지. 가져온 만큼 가져가.",
        "M: 어떤 책이 되는데?",
        "W: 학교 교과서만 빼고 다 돼.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, this is the community center."],
        ["M", "Hello. My name is Junsu Lee."],
        ["W", "How can I help you today?"],
        ["M", "I saw the poster about the painting class."],
        ["W", "The Tuesday evening one for teenagers?"],
        ["M", "Yes, that's the class I mean."],
        ["W", "It starts on the first week of next month."],
        ["M", "Are there any seats left in it?"],
        ["W", "Three seats are still open."],
        ["M", "I'm calling to sign up for that class."],
      ],
      choices: [
        "수업을 신청하려고",
        "수업을 취소하려고",
        "길을 물어보려고",
        "요금을 물어보려고",
        "물건을 찾으려고",
      ],
      answer: 1,
      clue: "I'm calling to sign up for that class.",
      explanation:
        "남자는 그림 수업을 신청하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요, 주민 센터입니다.",
        "M: 안녕하세요. 저는 이준수입니다.",
        "W: 무엇을 도와드릴까요?",
        "M: 그림 수업 안내문을 봤어요.",
        "W: 청소년 대상 화요일 저녁 수업 말씀이신가요?",
        "M: 네, 그 수업이요.",
        "W: 다음 달 첫째 주에 시작합니다.",
        "M: 자리가 남아 있나요?",
        "W: 세 자리가 비어 있습니다.",
        "M: 그 수업을 신청하려고 전화했어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 발표 연습을 시작할 시각을 고르시오.",
      lines: [
        ["M", "Yeeun, when can we practice the presentation?"],
        ["W", "The empty classroom opens at four o'clock."],
        ["M", "My cleaning duty ends at four fifteen."],
        ["W", "Then four o'clock is too early for you."],
        ["M", "Can we start at four thirty instead?"],
        ["W", "I need fifteen minutes to set up the laptop."],
        ["M", "So you'll be ready by four thirty anyway."],
        ["W", "Then let's begin at four thirty."],
        ["M", "I'll bring the printed script."],
      ],
      choices: ["4:00 p.m.", "4:15 p.m.", "4:30 p.m.", "4:45 p.m.", "5:00 p.m."],
      answer: 3,
      clue: "Then let's begin at four thirty.",
      explanation:
        "청소 당번이 4시 15분에 끝나 4시 30분에 연습을 시작하기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 예은아, 발표 연습 언제 할 수 있어?",
        "W: 빈 교실이 네 시에 열려.",
        "M: 내 청소 당번이 네 시 15분에 끝나.",
        "W: 그럼 네 시는 너한테 너무 이르네.",
        "M: 대신 네 시 반에 시작할까?",
        "W: 나는 노트북 준비에 15분이 필요해.",
        "M: 그럼 어차피 네 시 반이면 준비되겠다.",
        "W: 그럼 네 시 반에 시작하자.",
        "M: 출력한 대본은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seokhyun, how was the club trip yesterday?"],
        ["M", "The bus left ten minutes before I arrived."],
        ["W", "Did nobody call you from the bus?"],
        ["M", "My phone was in my bag on silent."],
        ["W", "So you missed the whole day."],
        ["M", "I waited at the gate for an hour."],
        ["W", "That's really unlucky."],
        ["M", "I wanted to go on that trip all month."],
      ],
      choices: ["excited", "proud", "bored", "disappointed", "surprised"],
      answer: 4,
      clue: "I wanted to go on that trip all month.",
      explanation:
        "한 달 내내 기다린 여행을 놓쳐 실망하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 석현아, 어제 동아리 여행 어땠어?",
        "M: 내가 도착하기 10분 전에 버스가 떠났어.",
        "W: 버스에서 아무도 전화 안 했어?",
        "M: 휴대폰이 가방 안에 무음으로 있었어.",
        "W: 그래서 하루를 통째로 놓쳤구나.",
        "M: 정문에서 한 시간을 기다렸어.",
        "W: 정말 운이 없었네.",
        "M: 한 달 내내 그 여행을 가고 싶었는데.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How long is the wait?"],
        ["M", "About twenty minutes."],
        ["ANN", "Number two."],
        ["W", "Do you have a table for four?"],
        ["M", "Please write your name here."],
        ["ANN", "Number three."],
        ["W", "Is the soup very spicy?"],
        ["M", "Only a little bit."],
        ["ANN", "Number four."],
        ["W", "Could we have some more water?"],
        ["M", "I'll bring it right away."],
        ["ANN", "Number five."],
        ["W", "Can we pay separately?"],
        ["M", "Yes, that's no problem."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Do you have a table for four?",
      explanation:
        "그림은 식당 입구에서 대기 명단에 이름을 적으라고 안내받는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "At the entrance of a busy restaurant, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman with three companions standing behind her speaks to a staff member at a small podium. " +
          "The staff member holds out a pen and points down at a blank clipboard sheet on the podium. " +
          "Full tables and a doorway are drawn simply in the background.",
      },
      translation: [
        "① W: 얼마나 기다려요? / M: 20분쯤요.",
        "② W: 네 명 자리 있나요? / M: 여기에 이름을 적어 주세요.",
        "③ W: 국이 많이 매워요? / M: 아주 조금만요.",
        "④ W: 물 좀 더 주시겠어요? / M: 바로 가져다드릴게요.",
        "⑤ W: 따로 계산해도 되나요? / M: 네, 괜찮습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongjin, you took the class photos last year."],
        ["M", "I still have my father's old camera."],
        ["W", "Our class is planting trees on Friday."],
        ["M", "Is that the school yard project?"],
        ["W", "Yes, and we want a record of it."],
        ["M", "Phone pictures might be enough."],
        ["W", "The teacher wants them for the yearbook."],
        ["M", "Then the camera would be better."],
        ["W", "Could you take photos of the planting?"],
        ["M", "I'll charge the battery tonight."],
      ],
      choices: [
        "나무를 심어 주기",
        "사진을 찍어 주기",
        "카메라를 빌려주기",
        "졸업 앨범을 만들기",
        "선생님께 여쭤보기",
      ],
      answer: 2,
      clue: "Could you take photos of the planting?",
      explanation:
        "여자는 나무 심는 모습을 사진으로 찍어 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 동진아, 작년에 반 사진 네가 찍었잖아.",
        "M: 아버지 옛날 사진기가 아직 있어.",
        "W: 우리 반이 금요일에 나무를 심어.",
        "M: 학교 마당 사업 말이야?",
        "W: 응, 그걸 기록으로 남기고 싶어.",
        "M: 휴대폰 사진으로도 될 것 같은데.",
        "W: 선생님이 졸업 앨범에 쓰신대.",
        "M: 그럼 사진기가 낫겠다.",
        "W: 나무 심는 거 사진 좀 찍어 줄 수 있어?",
        "M: 오늘 밤에 배터리 충전해 놓을게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 겨울 나눔 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The student council is holding a winter sharing drive. " +
            "We are collecting clean winter clothes and blankets. " +
            "Please bring them to the box in the front hall. " +
            "We collect items until the end of next week. " +
            "Everything goes to the shelter in our neighborhood. " +
            "Items with holes or stains cannot be accepted.",
        ],
      ],
      choices: ["모으는 물건", "가져올 곳", "모으는 기간", "전달되는 곳", "행사를 여는 이유"],
      answer: 5,
      clue: "We are collecting clean winter clothes and blankets.",
      explanation:
        "물건, 장소, 기간, 전달처는 말했지만 행사를 여는 이유는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학생회에서 겨울 나눔 행사를 엽니다. 깨끗한 겨울옷과 담요를 모으고 있습니다. 중앙 현관에 있는 상자에 넣어 주세요. 다음 주말까지 물건을 받습니다. 모인 물건은 우리 동네 쉼터로 전달됩니다. 구멍이 나거나 얼룩진 물건은 받을 수 없습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "You carry this on your back with two straps. " +
            "Books, a lunch box and a water bottle go inside it. " +
            "It gets very heavy on exam days. " +
            "Students hang it on the hook beside their desk. " +
            "A broken zipper makes it useless right away.",
        ],
      ],
      choices: ["우산", "필통", "모자", "책가방", "신발"],
      answer: 4,
      clue: "You carry this on your back with two straps.",
      explanation:
        "어깨끈 두 개로 등에 메고 책과 도시락을 넣는 것은 책가방이다. 따라서 답은 ④이다.",
      translation: [
        "M: 이것은 어깨끈 두 개로 등에 멥니다. 책, 도시락, 물병이 안에 들어갑니다. 시험 날에는 아주 무거워집니다. 학생들은 책상 옆 고리에 이것을 겁니다. 지퍼가 고장 나면 바로 쓸 수 없게 됩니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What time do you usually sleep?"],
        ["W", "Around eleven."],
        ["ANN", "Number two."],
        ["M", "Could you spell your name?"],
        ["W", "Sure, it's J-I-N-A."],
        ["ANN", "Number three."],
        ["M", "How much homework do we have?"],
        ["W", "My favorite season is spring."],
        ["ANN", "Number four."],
        ["M", "Shall I open the curtains?"],
        ["W", "Yes, it's dark in here."],
        ["ANN", "Number five."],
        ["M", "Have you met the new teacher?"],
        ["W", "Not yet, but I've heard about her."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How much homework do we have?",
      explanation:
        "숙제가 얼마나 있는지 묻는 말에 좋아하는 계절을 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 보통 몇 시에 자? / W: 열한 시쯤.",
        "② M: 이름 철자 좀 알려 줄래? / W: 그럼, J-I-N-A야.",
        "③ M: 숙제가 얼마나 있어? / W: 내가 좋아하는 계절은 봄이야.",
        "④ M: 커튼 열까? / W: 응, 여기 어둡다.",
        "⑤ M: 새 선생님 만나 봤어? / W: 아직. 얘기는 들었어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hanbyul, the club fair opens in twenty minutes."],
        ["W", "Our booth is ready with the posters up."],
        ["M", "Did anyone bring the sign-up sheets?"],
        ["W", "They're still printing in the computer room."],
        ["M", "New members can't join without them."],
        ["W", "The printer was slow this morning."],
        ["M", "I'll stay here and watch the booth."],
        ["W", "I'll go and get the sign-up sheets."],
      ],
      choices: [
        "포스터를 붙이기",
        "부스를 지키기",
        "신청서를 가져오기",
        "회원을 모으기",
        "컴퓨터를 고치기",
      ],
      answer: 3,
      clue: "I'll go and get the sign-up sheets.",
      explanation:
        "여자는 신청서를 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 한별아, 동아리 박람회가 20분 뒤에 열어.",
        "W: 우리 부스는 포스터까지 다 붙였어.",
        "M: 가입 신청서는 누가 가져왔어?",
        "W: 아직 컴퓨터실에서 출력 중이야.",
        "M: 그게 없으면 새 회원이 못 들어와.",
        "W: 오늘 아침에 인쇄기가 느렸어.",
        "M: 나는 여기서 부스를 지킬게.",
        "W: 내가 가서 신청서를 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 살 책상 스탠드를 고르시오.",
      lines: [
        ["M", "Jiwon, which desk lamp are you going to buy?"],
        ["W", "Five lamps are on this page."],
        ["M", "How much can you spend on it?"],
        ["W", "Under forty thousand won."],
        ["M", "One of them is well over that."],
        ["W", "It also has to be the clip type."],
        ["M", "Two of them stand on a base."],
        ["W", "And I want one I can change the brightness on."],
        ["M", "Then only one lamp is left."],
        ["W", "I'll order it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Under forty thousand won.",
      explanation:
        "4만 원 미만, 집게형, 밝기 조절이 되는 스탠드는 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 45,000 won / Type: Clip / Brightness: Adjustable" },
          { no: 2, label: "②", value: "Price: 32,000 won / Type: Base / Brightness: Adjustable" },
          { no: 3, label: "③", value: "Price: 28,000 won / Type: Base / Brightness: Fixed" },
          { no: 4, label: "④", value: "Price: 36,000 won / Type: Clip / Brightness: Adjustable" },
          { no: 5, label: "⑤", value: "Price: 30,000 won / Type: Clip / Brightness: Fixed" },
        ],
      },
      translation: [
        "M: 지원아, 어떤 책상 스탠드 살 거야?",
        "W: 이 쪽에 다섯 개가 있어.",
        "M: 얼마까지 쓸 수 있어?",
        "W: 4만 원 미만.",
        "M: 하나는 그보다 훨씬 비싸네.",
        "W: 그리고 집게형이어야 해.",
        "M: 두 개는 받침에 세우는 거야.",
        "W: 그리고 밝기를 조절할 수 있으면 좋겠어.",
        "M: 그럼 하나만 남는다.",
        "W: 오늘 밤에 주문할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 학예회를 열 날짜를 고르시오.",
      lines: [
        ["M", "Sujeong, when should our class hold the talent show?"],
        ["W", "The teacher gave us three possible dates this term."],
        ["M", "Which dates did she put on the board?"],
        ["W", "The second, the ninth and the sixteenth."],
        ["M", "The second is only five days from now."],
        ["W", "Half the acts haven't even started practicing."],
        ["M", "And the sixteenth is right after the exams."],
        ["W", "Everyone will be too tired that week."],
        ["M", "Then the ninth is the best date for us."],
        ["W", "I'll write the ninth on the class calendar."],
      ],
      choices: ["the 2nd", "the 9th", "the 16th", "the 5th", "the 12th"],
      answer: 2,
      clue: "Then the ninth is the best date for us.",
      explanation:
        "2일은 너무 이르고 16일은 시험 직후여서 9일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "M: 수정아, 우리 반 학예회 언제 열까?",
        "W: 선생님이 이번 학기에 가능한 날 세 개를 주셨어.",
        "M: 칠판에 어떤 날짜를 적으셨어?",
        "W: 2일, 9일, 16일.",
        "M: 2일은 닷새밖에 안 남았어.",
        "W: 절반은 연습도 시작 안 했어.",
        "M: 16일은 시험 바로 다음이고.",
        "W: 그 주에는 다들 너무 지쳐 있을 거야.",
        "M: 그럼 우리한테는 9일이 제일 좋네.",
        "W: 학급 달력에 9일이라고 적어 둘게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaerin, you weren't on the school bus yesterday."],
        ["W", "I walked to the market with my mother."],
        ["M", "Did you buy something special?"],
        ["W", "Vegetables for a soup she makes in autumn."],
        ["M", "Did you carry the bags home?"],
        ["W", "Two heavy bags for twenty minutes."],
        ["M", "Did you help her cook as well?"],
        ["W", "I washed and cut everything."],
        ["M", "How did the soup turn out?"],
        ["W", "We had two bowls each."],
      ],
      choices: [
        "학교 버스를 탔다",
        "친구를 만났다",
        "집에서 쉬었다",
        "어머니와 시장에 갔다",
        "도서관에 갔다",
      ],
      answer: 4,
      clue: "I walked to the market with my mother.",
      explanation:
        "여자는 어제 어머니와 시장에 다녀왔다. 따라서 답은 ④이다.",
      translation: [
        "M: 채린아, 어제 학교 버스에 없더라.",
        "W: 어머니랑 시장까지 걸어갔어.",
        "M: 특별한 걸 샀어?",
        "W: 가을에 끓이시는 국에 넣을 채소.",
        "M: 짐은 네가 들고 왔어?",
        "W: 무거운 봉투 두 개를 20분 동안.",
        "M: 요리도 도와드렸어?",
        "W: 내가 다 씻고 썰었어.",
        "M: 국은 어떻게 됐어?",
        "W: 각자 두 그릇씩 먹었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the physical education office. " +
            "The gym floor is being waxed this afternoon. " +
            "No one may enter the gym until tomorrow morning. " +
            "Today's basketball practice moves to the outdoor court. " +
            "Bring your outdoor shoes to the afternoon class. " +
            "Equipment stays in the storage room until Thursday. " +
            "Thank you for following these directions.",
        ],
      ],
      choices: [
        "체육관 사용 금지를 알리려고",
        "농구 대회를 안내하려고",
        "운동화를 나눠 주려고",
        "분실물을 찾으려고",
        "봉사자를 모으려고",
      ],
      answer: 1,
      clue: "The gym floor is being waxed this afternoon.",
      explanation:
        "바닥 작업 때문에 체육관에 들어갈 수 없다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 체육부입니다. 오늘 오후에 체육관 바닥에 왁스를 칠합니다. 내일 아침까지는 아무도 체육관에 들어갈 수 없습니다. 오늘 농구 연습은 야외 코트로 옮깁니다. 오후 수업에는 야외용 운동화를 가져오세요. 기구는 목요일까지 창고에 둡니다. 안내에 따라 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to our shop. What can I get for you today?"],
        ["M", "Two sandwiches and three bottles of water, please."],
        ["W", "Sandwiches are four dollars each this week."],
        ["M", "Are they made here in the morning?"],
        ["W", "We make them fresh before we open the door."],
        ["M", "And how much is the water?"],
        ["W", "One dollar for each bottle, cold or room temperature."],
        ["M", "Cold ones, please. Is there a charge for the bag?"],
        ["W", "The paper bag costs nothing here."],
        ["M", "Good, I'll take one bag then."],
        ["W", "Then that will be everything for today."],
        ["M", "Here is my card, thank you."],
      ],
      choices: ["$9", "$10", "$11", "$12", "$13"],
      answer: 3,
      clue: "Sandwiches are four dollars each this week.",
      explanation:
        "샌드위치 두 개 8달러와 물 세 병 3달러를 더하면 11달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 저희 가게에 오신 걸 환영합니다. 오늘은 뭘 드릴까요?",
        "M: 샌드위치 두 개랑 물 세 병 주세요.",
        "W: 이번 주 샌드위치는 하나에 4달러입니다.",
        "M: 여기서 아침에 만드나요?",
        "W: 문 열기 전에 갓 만들어 둡니다.",
        "M: 물은 얼마예요?",
        "W: 한 병에 1달러입니다. 찬 것도 있고 실온도 있습니다.",
        "M: 찬 걸로 주세요. 봉투는 돈을 받나요?",
        "W: 종이봉투는 무료입니다.",
        "M: 좋네요, 봉투 하나 주세요.",
        "W: 그럼 오늘은 다 되셨습니다.",
        "M: 여기 카드요, 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junhyuk, your room was spotless when I visited."],
        ["M", "I clean one small area every evening."],
        ["W", "Not the whole room at once?"],
        ["M", "One shelf or one drawer, never more."],
        ["W", "I clean everything on Sunday and hate it."],
        ["M", "A whole room takes three hours of your day."],
        ["W", "And by Wednesday it looks the same again."],
        ["M", "Small pieces never pile up that way."],
        ["W", "Which part should I start with?"],
      ],
      choices: [
        "Clean the entire house.",
        "The desk you use most.",
        "Never clean anything.",
        "Wait until next Sunday.",
        "Throw out all your things.",
      ],
      answer: 2,
      clue: "Which part should I start with?",
      explanation:
        "어디부터 시작할지 물었으므로, 가장 많이 쓰는 책상부터라는 ②가 가장 자연스럽다.",
      translation: [
        "W: 준혁아, 내가 갔을 때 네 방이 정말 깨끗하더라.",
        "M: 저녁마다 작은 데 한 군데씩 치워.",
        "W: 방 전체를 한꺼번에 하는 게 아니고?",
        "M: 선반 하나나 서랍 하나, 그 이상은 안 해.",
        "W: 나는 일요일에 다 하는데 그게 정말 싫어.",
        "M: 방 전체는 하루에 세 시간이 들어.",
        "W: 그러고도 수요일이면 또 똑같아져.",
        "M: 조금씩 하면 그렇게 쌓이지 않아.",
        "W: 어디부터 시작하면 좋을까?",
        "M: 네가 제일 많이 쓰는 책상부터.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Seoyeon, I heard you write a letter every month."],
        ["W", "I write to my grandfather in the countryside."],
        ["M", "Why not just call him on the phone?"],
        ["W", "He keeps every letter in a wooden box."],
        ["M", "How long does one letter take you?"],
        ["W", "About half an hour on a Sunday evening."],
        ["M", "What do you write about?"],
        ["W", "School, the weather and what I ate."],
        ["M", "Does he write back to you?"],
        ["W", "Every time, in very careful handwriting."],
        ["M", "Could you help me write one to my grandmother?"],
      ],
      choices: [
        "Sure, bring paper tomorrow.",
        "I never write letters.",
        "Letters don't reach anyone.",
        "You should call instead.",
        "I stopped writing last year.",
      ],
      answer: 1,
      clue: "Could you help me write one to my grandmother?",
      explanation:
        "편지 쓰는 것을 도와 달라고 했으므로, 내일 종이를 가져오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 서연아, 너 매달 편지를 쓴다며.",
        "W: 시골에 계신 할아버지께 써.",
        "M: 그냥 전화하면 안 돼?",
        "W: 할아버지가 편지를 다 나무 상자에 모아 두셔.",
        "M: 한 통 쓰는 데 얼마나 걸려?",
        "W: 일요일 저녁에 30분쯤.",
        "M: 뭐에 대해 써?",
        "W: 학교, 날씨, 뭘 먹었는지.",
        "M: 답장도 해 주셔?",
        "W: 매번, 아주 또박또박한 글씨로.",
        "M: 나도 할머니께 쓰는 거 도와줄래?",
        "W: 그럼, 내일 종이 가져와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sangwoo, how is the school band poster going?"],
        ["W", "You said it goes up in the hallway on Monday."],
        ["M", "Nobody stops to look at my drafts."],
        ["W", "How big is the writing on it?"],
        ["M", "The same size as my normal handwriting."],
        ["W", "People walk past a poster in two seconds."],
        ["M", "So they never get close enough to read it."],
        ["W", "The date and place should be readable from far away."],
        ["M", "I put those at the very bottom."],
        ["W", "Why don't you make the date much bigger?"],
      ],
      choices: [
        "I'll redraw it tonight.",
        "There is no date at all.",
        "Posters don't need writing.",
        "I'll make it smaller.",
        "Nobody reads posters.",
      ],
      answer: 1,
      clue: "Why don't you make the date much bigger?",
      explanation:
        "날짜를 크게 쓰라는 제안이므로, 오늘 밤에 다시 그리겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 상우야, 밴드 포스터는 잘돼 가?",
        "W: 월요일에 복도에 붙인다고 했잖아.",
        "M: 아무도 내 시안 앞에 서지를 않아.",
        "W: 글씨가 얼마나 커?",
        "M: 내 평소 글씨 크기랑 같아.",
        "W: 사람들은 포스터를 2초 만에 지나쳐.",
        "M: 그럼 읽을 만큼 가까이 오지도 않는구나.",
        "W: 날짜랑 장소는 멀리서도 읽혀야 해.",
        "M: 그건 맨 아래에 넣었어.",
        "W: 날짜를 훨씬 크게 하는 건 어때?",
        "M: 오늘 밤에 다시 그릴게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Eunbi가 Taeho에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Eunbi : ________________",
      lines: [
        [
          "W",
          "Eunbi and Taeho are getting ready for the science presentation. " +
            "Taeho is about to leave the classroom with the wrong folder. " +
            "Eunbi sees that the folder in his hand is the math one. " +
            "Their science slides are still on the desk behind him. " +
            "She wants him to take the right folder before he goes. " +
            "In this situation, what would Eunbi most likely say to Taeho?",
        ],
      ],
      choices: [
        "The presentation is cancelled.",
        "Let's leave the slides here.",
        "Math class starts now.",
        "You should print more copies.",
        "That's the math folder.",
      ],
      answer: 5,
      clue: "She wants him to take the right folder before he goes.",
      explanation:
        "들고 가는 것이 수학 서류철이므로, 그것이 수학 것이라고 알리는 ⑤가 가장 적절하다.",
      translation: [
        "W: 은비와 태호는 과학 발표를 준비하고 있습니다. 태호는 엉뚱한 서류철을 들고 교실을 나가려고 합니다. 은비는 그의 손에 있는 것이 수학 서류철이라는 것을 봅니다. 과학 발표 자료는 아직 그의 뒤 책상 위에 있습니다. 그녀는 그가 나가기 전에 맞는 서류철을 챙기기를 바랍니다. 이런 상황에서 은비가 태호에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
