/** 중2 듣기 42회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 42회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 만든 포스터를 고르시오.",
      lines: [
        ["W", "Jiho, is that the poster for the book fair?"],
        ["M", "Yes, I finished the drawing last night."],
        ["W", "Did you put a big open book in the center?"],
        ["M", "I moved the book down to the bottom instead."],
        ["W", "Then what is in the middle of the poster?"],
        ["M", "A large tree with books hanging from the branches."],
        ["W", "Is the title written across the top?"],
        ["M", "I put the title in a banner at the top."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "A large tree with books hanging from the branches. / I put the title in a banner at the top.",
      explanation:
        "가운데에 책이 매달린 큰 나무, 아래에 펼친 책, 위에 제목 띠가 있는 포스터이다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five poster designs side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a poster with a big OPEN BOOK in the center and a blank banner at the top. " +
          "② a poster with a large TREE in the center with small books hanging from its branches, an OPEN BOOK at the bottom, and a blank banner at the top. " +
          "③ a poster with a large TREE in the center and a blank banner at the BOTTOM, no open book. " +
          "④ a poster with a big OPEN BOOK at the bottom and a blank banner at the top, empty center. " +
          "⑤ a poster with a large TREE in the center with hanging books, and no banner at all.",
      },
      translation: [
        "W: 지호야, 그거 책 축제 포스터야?",
        "M: 응, 어젯밤에 그림을 다 그렸어.",
        "W: 가운데에 펼친 큰 책을 넣었어?",
        "M: 책은 아래쪽으로 내렸어.",
        "W: 그럼 포스터 가운데에는 뭐가 있어?",
        "M: 가지에 책이 매달린 큰 나무.",
        "W: 제목은 위쪽에 가로로 썼어?",
        "M: 제목은 맨 위 띠 안에 넣었어.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 벼룩시장에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yuna, are you joining the school flea market this year?"],
        ["W", "I'd like to. Where exactly do they hold it?"],
        ["M", "In the playground behind the gym, near the back gate."],
        ["W", "When does the market open and close?"],
        ["M", "Next Saturday morning, from ten until two in the afternoon."],
        ["W", "What kinds of things can students sell there?"],
        ["M", "Used books, clothes and small toys they no longer need."],
        ["W", "What happens to all the money we make?"],
        ["M", "Every won goes to the animal shelter in our town."],
        ["W", "Then I'll bring the books I read last year."],
      ],
      choices: ["열리는 장소", "열리는 시간", "팔 수 있는 물건", "수익금의 쓰임", "참가 신청 방법"],
      answer: 5,
      clue: "In the playground behind the gym, near the back gate.",
      explanation:
        "장소, 시간, 물건, 수익금은 말했지만 신청 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 유나야, 올해 학교 벼룩시장 참가할 거야?",
        "W: 하고 싶어. 정확히 어디서 해?",
        "M: 체육관 뒤 운동장, 후문 가까이에서.",
        "W: 몇 시에 열고 닫아?",
        "M: 다음 주 토요일 오전 10시부터 오후 2시까지.",
        "W: 학생들은 어떤 걸 팔 수 있어?",
        "M: 이제 필요 없는 헌책, 옷, 작은 장난감.",
        "W: 번 돈은 어떻게 돼?",
        "M: 한 푼도 빠짐없이 우리 동네 동물 보호소에 가.",
        "W: 그럼 작년에 읽은 책들을 가져와야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, this is Junho."],
        ["W", "Hi, Junho. It's Seoyeon from the class trip group."],
        ["M", "Hi. Did something change again?"],
        ["W", "The bus company moved our departure earlier."],
        ["M", "How early are we leaving now?"],
        ["W", "Seven thirty instead of eight o'clock."],
        ["M", "That's half an hour earlier than before."],
        ["W", "The road work on the highway is the reason."],
        ["M", "I'll have to catch an earlier subway."],
        ["W", "I'm calling to tell everyone about the new time."],
      ],
      choices: [
        "출발 시각이 바뀐 것을 알리려고",
        "준비물을 부탁하려고",
        "결석을 알리려고",
        "길을 물어보려고",
        "숙제를 확인하려고",
      ],
      answer: 1,
      clue: "I'm calling to tell everyone about the new time.",
      explanation:
        "여자는 출발 시각이 앞당겨진 것을 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요, 준호입니다.",
        "W: 안녕, 준호야. 수학여행 조 서연이야.",
        "M: 안녕. 또 뭐가 바뀌었어?",
        "W: 버스 회사가 출발을 앞당겼어.",
        "M: 이제 얼마나 일찍 떠나?",
        "W: 여덟 시 대신 일곱 시 반.",
        "M: 전보다 30분 이르네.",
        "W: 고속도로 공사 때문이래.",
        "M: 지하철을 더 일찍 타야겠다.",
        "W: 새 시각을 다들한테 알리려고 전화하는 거야.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 시작할 시각을 고르시오.",
      lines: [
        ["W", "Sangmin, what time do we start at the center?"],
        ["M", "The center opens its doors at nine o'clock."],
        ["W", "Do the volunteers go in right at nine?"],
        ["M", "We get a short training talk first."],
        ["W", "How long does the training talk last?"],
        ["M", "Thirty minutes, so the work starts after that."],
        ["W", "Then we begin working at nine thirty."],
        ["M", "Yes, nine thirty on the second floor."],
        ["W", "I'll get there ten minutes early."],
      ],
      choices: ["9:00 a.m.", "9:30 a.m.", "10:00 a.m.", "10:30 a.m.", "11:00 a.m."],
      answer: 2,
      clue: "Then we begin working at nine thirty.",
      explanation:
        "9시에 문을 열고 30분 교육을 받은 뒤 9시 30분에 일을 시작한다. 따라서 답은 ②이다.",
      translation: [
        "W: 상민아, 센터에서 몇 시에 시작해?",
        "M: 센터는 아홉 시에 문을 열어.",
        "W: 자원봉사자들은 아홉 시에 바로 들어가?",
        "M: 먼저 짧은 교육을 받아.",
        "W: 교육은 얼마나 걸려?",
        "M: 30분이라서 그다음에 일을 시작해.",
        "W: 그럼 아홉 시 반에 일을 시작하는구나.",
        "M: 응, 아홉 시 반에 2층에서.",
        "W: 나는 10분 일찍 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongju, why are you standing outside the door?"],
        ["M", "The interview for the student council is next."],
        ["W", "You've prepared for two whole weeks."],
        ["M", "My hands are cold and my voice shakes."],
        ["W", "How many teachers are inside the room?"],
        ["M", "Three, and they ask questions one by one."],
        ["W", "Just answer the way you practiced with me."],
        ["M", "I keep forgetting my first sentence."],
      ],
      choices: ["bored", "angry", "satisfied", "nervous", "sleepy"],
      answer: 4,
      clue: "My hands are cold and my voice shakes.",
      explanation:
        "면접을 앞두고 손이 차고 목소리가 떨린다고 하므로 긴장한 상태이다. 따라서 답은 ④이다.",
      translation: [
        "W: 동주야, 왜 문밖에 서 있어?",
        "M: 다음이 학생회 면접이야.",
        "W: 너 두 주나 준비했잖아.",
        "M: 손이 차고 목소리가 떨려.",
        "W: 방 안에 선생님이 몇 분 계셔?",
        "M: 세 분이고 한 분씩 질문하셔.",
        "W: 나랑 연습한 대로만 대답해.",
        "M: 첫 문장이 자꾸 생각이 안 나.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Could you move over a little?"],
        ["M", "Sure, no problem."],
        ["ANN", "Number two."],
        ["W", "Would you like to sit here?"],
        ["M", "Thank you, that's very kind."],
        ["ANN", "Number three."],
        ["W", "Does this bus go to the museum?"],
        ["M", "No, take the one across the street."],
        ["ANN", "Number four."],
        ["W", "How many stops are left?"],
        ["M", "About three more."],
        ["ANN", "Number five."],
        ["W", "Is the next stop the hospital?"],
        ["M", "Yes, it is."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Would you like to sit here?",
      explanation:
        "그림은 버스에서 학생이 일어나 노인에게 자리를 양보하는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a city bus, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A student with a backpack has stood up from a seat and gestures with an open palm toward the empty seat. " +
          "An elderly person holding a cane stands beside the student and smiles. " +
          "Handrails, a window and other seated passengers are drawn simply in the background.",
      },
      translation: [
        "① W: 조금만 옆으로 가 주시겠어요? / M: 네, 그럼요.",
        "② W: 여기 앉으시겠어요? / M: 고마워요, 정말 친절하네요.",
        "③ W: 이 버스 박물관에 가나요? / M: 아니요, 길 건너에서 타세요.",
        "④ W: 몇 정거장 남았어요? / M: 세 정거장쯤요.",
        "⑤ W: 다음이 병원 정류장인가요? / M: 네, 맞습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyerim, you speak in front of people really well."],
        ["W", "I just practice more than other people do."],
        ["M", "Our group presents the history project on Friday."],
        ["W", "Who is speaking for your group?"],
        ["M", "I am, and I've never done it before."],
        ["W", "The first time is always the hardest."],
        ["M", "I wrote the script but it sounds flat."],
        ["W", "Reading it aloud usually shows the problem."],
        ["M", "Could you listen to me practice after school?"],
        ["W", "Sure, let's meet in the empty music room."],
      ],
      choices: [
        "발표를 대신해 주기",
        "연습을 들어 주기",
        "자료를 찾아 주기",
        "대본을 써 주기",
        "사진을 찍어 주기",
      ],
      answer: 2,
      clue: "Could you listen to me practice after school?",
      explanation:
        "남자는 방과 후에 발표 연습을 들어 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 혜림아, 너는 사람들 앞에서 말을 정말 잘하더라.",
        "W: 남들보다 연습을 더 할 뿐이야.",
        "M: 우리 조가 금요일에 역사 과제를 발표해.",
        "W: 누가 발표해?",
        "M: 나야. 한 번도 해 본 적이 없어.",
        "W: 처음이 늘 제일 어려워.",
        "M: 대본은 썼는데 밋밋하게 들려.",
        "W: 소리 내어 읽어 보면 보통 뭐가 문제인지 보여.",
        "M: 방과 후에 내 연습 좀 들어 줄 수 있어?",
        "W: 그래, 비어 있는 음악실에서 만나자.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 사진 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The art club is holding a photo contest. " +
            "This year's subject is a quiet corner of our school. " +
            "Each student may send up to two photographs. " +
            "Send your files by the end of next week. " +
            "The winning photos will be printed in the hallway. " +
            "Please write your class and name in the file.",
        ],
      ],
      choices: ["대회의 주제", "낼 수 있는 장수", "제출 기한", "수상작을 거는 곳", "심사 기준"],
      answer: 5,
      clue: "This year's subject is a quiet corner of our school.",
      explanation:
        "주제, 장수, 기한, 전시 장소는 말했지만 심사 기준은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 미술 동아리에서 사진 대회를 엽니다. 올해 주제는 우리 학교의 조용한 한구석입니다. 학생 한 명이 사진 두 장까지 낼 수 있습니다. 다음 주말까지 파일을 보내 주세요. 수상작은 복도에 인화해서 겁니다. 파일에 학급과 이름을 적어 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "You find this in almost every classroom wall. " +
            "It has two hands that move in a circle. " +
            "The short hand moves much more slowly than the long one. " +
            "Students look up at it when a lesson feels long. " +
            "It tells everyone when the class is over.",
        ],
      ],
      choices: ["달력", "지도", "칠판", "창문", "시계"],
      answer: 5,
      clue: "It has two hands that move in a circle.",
      explanation:
        "바늘 두 개가 돌며 시간을 알려 주는 것은 시계이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 이것은 거의 모든 교실 벽에 있습니다. 원을 그리며 움직이는 바늘이 두 개 있습니다. 짧은 바늘은 긴 바늘보다 훨씬 천천히 움직입니다. 학생들은 수업이 길게 느껴질 때 이것을 올려다봅니다. 이것은 수업이 언제 끝나는지 모두에게 알려 줍니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How long have you played the violin?"],
        ["W", "Since I was seven."],
        ["ANN", "Number two."],
        ["M", "Could you close the window?"],
        ["W", "Of course, it's windy today."],
        ["ANN", "Number three."],
        ["M", "What are you doing this weekend?"],
        ["W", "I'm visiting my grandparents."],
        ["ANN", "Number four."],
        ["M", "Why were you late this morning?"],
        ["W", "My favorite subject is science."],
        ["ANN", "Number five."],
        ["M", "Do you want some more soup?"],
        ["W", "No, thanks. I'm full."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why were you late this morning?",
      explanation:
        "늦은 이유를 묻는 말에 좋아하는 과목을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 바이올린 얼마나 배웠어? / W: 일곱 살 때부터.",
        "② M: 창문 좀 닫아 줄래? / W: 그럼, 오늘 바람이 세네.",
        "③ M: 이번 주말에 뭐 해? / W: 조부모님 댁에 가.",
        "④ M: 오늘 아침에 왜 늦었어? / W: 내가 좋아하는 과목은 과학이야.",
        "⑤ M: 국 더 먹을래? / W: 아니, 괜찮아. 배불러.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, the club room looks ready for tomorrow."],
        ["W", "We moved all the desks into a circle."],
        ["M", "Did anyone check the speaker for the music?"],
        ["W", "I plugged it in but heard nothing."],
        ["M", "Maybe the cable is loose at the back."],
        ["W", "The music matters more than the desks."],
        ["M", "I have to lock the front gate now."],
        ["W", "I'll go and check the speaker cable."],
      ],
      choices: [
        "책상을 옮기기",
        "정문을 잠그기",
        "스피커 선을 확인하기",
        "음악을 고르기",
        "집으로 돌아가기",
      ],
      answer: 3,
      clue: "I'll go and check the speaker cable.",
      explanation:
        "여자는 스피커 선을 확인하러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 나리야, 동아리방은 내일 준비가 다 된 것 같네.",
        "W: 책상을 전부 둥글게 놓았어.",
        "M: 음악 나올 스피커는 누가 확인했어?",
        "W: 꽂아 봤는데 소리가 안 났어.",
        "M: 뒤쪽 선이 헐거울지도 몰라.",
        "W: 책상보다 음악이 더 중요해.",
        "M: 나는 지금 정문을 잠가야 해.",
        "W: 내가 가서 스피커 선을 확인할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 선택할 체험 활동을 고르시오.",
      lines: [
        ["W", "Taehoon, which hands-on program should our class choose?"],
        ["M", "There are five programs on the list."],
        ["W", "We only have three hours in the afternoon."],
        ["M", "So anything longer than three hours is out."],
        ["W", "The cost has to stay under fifteen thousand won."],
        ["M", "Two of them are more expensive than that."],
        ["W", "And it should be indoors because of the rain."],
        ["M", "Then only one program fits all three conditions."],
        ["W", "I'll tell our teacher this afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "We only have three hours in the afternoon.",
      explanation:
        "3시간 이내, 15,000원 미만, 실내인 활동은 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Time: 2 hours / Cost: 18,000 won / Place: Indoor" },
          { no: 2, label: "②", value: "Time: 4 hours / Cost: 12,000 won / Place: Indoor" },
          { no: 3, label: "③", value: "Time: 3 hours / Cost: 10,000 won / Place: Outdoor" },
          { no: 4, label: "④", value: "Time: 2 hours / Cost: 13,000 won / Place: Indoor" },
          { no: 5, label: "⑤", value: "Time: 3 hours / Cost: 16,000 won / Place: Indoor" },
        ],
      },
      translation: [
        "W: 태훈아, 우리 반은 어떤 체험 활동을 고를까?",
        "M: 목록에 다섯 개가 있어.",
        "W: 오후에 세 시간밖에 없어.",
        "M: 그럼 세 시간 넘는 건 빠지네.",
        "W: 비용은 15,000원 미만이어야 해.",
        "M: 두 개는 그보다 비싸.",
        "W: 그리고 비가 오니까 실내여야 해.",
        "M: 그럼 세 조건에 다 맞는 건 하나뿐이야.",
        "W: 오늘 오후에 선생님께 말씀드릴게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 공연을 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Sujin, when can we go to the dance performance?"],
        ["W", "It runs from the ninth to the twelfth."],
        ["M", "I have a family dinner on the ninth."],
        ["W", "The tenth is a school holiday, isn't it?"],
        ["M", "It is, but the tickets are sold out that day."],
        ["W", "Then the eleventh or the twelfth is left."],
        ["M", "I promised to help my mother on the twelfth."],
        ["W", "So the eleventh is the only day we can go."],
        ["M", "I'll book two seats for the eleventh tonight."],
      ],
      choices: ["the 9th", "the 10th", "the 11th", "the 12th", "the 13th"],
      answer: 3,
      clue: "So the eleventh is the only day we can go.",
      explanation:
        "9일은 가족 식사, 10일은 매진, 12일은 약속이 있어 11일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수진아, 무용 공연 언제 보러 갈까?",
        "W: 9일부터 12일까지 해.",
        "M: 9일에는 가족 식사가 있어.",
        "W: 10일은 학교 쉬는 날 아니야?",
        "M: 맞는데 그날은 표가 매진이야.",
        "W: 그럼 11일이나 12일이 남네.",
        "M: 12일에는 엄마를 돕기로 했어.",
        "W: 그럼 갈 수 있는 날은 11일뿐이야.",
        "M: 오늘 밤에 11일 자리 두 개 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Areum, did you go anywhere last weekend?"],
        ["W", "I stayed home and made a photo album."],
        ["M", "An album with printed pictures?"],
        ["W", "Yes, pictures from our trip last spring."],
        ["M", "How many photos did you put in?"],
        ["W", "Almost sixty, and I wrote a line under each."],
        ["M", "That must have taken the whole weekend."],
        ["W", "Two afternoons, actually."],
        ["M", "Can I see it at school tomorrow?"],
        ["W", "I'll bring it in my bag."],
      ],
      choices: [
        "사진첩을 만들었다",
        "여행을 다녀왔다",
        "친구를 만났다",
        "도서관에 갔다",
        "운동을 했다",
      ],
      answer: 1,
      clue: "I stayed home and made a photo album.",
      explanation:
        "여자는 지난 주말에 집에서 사진첩을 만들었다. 따라서 답은 ①이다.",
      translation: [
        "M: 아름아, 지난 주말에 어디 갔었어?",
        "W: 집에 있으면서 사진첩을 만들었어.",
        "M: 인화한 사진으로?",
        "W: 응, 지난봄 여행 사진들로.",
        "M: 사진 몇 장이나 넣었어?",
        "W: 거의 예순 장. 밑에 한 줄씩 썼어.",
        "M: 주말을 다 썼겠다.",
        "W: 사실 오후 이틀.",
        "M: 내일 학교에서 봐도 돼?",
        "W: 가방에 넣어 갈게.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the school office speaking. " +
            "The hot water in the gym showers is not working today. " +
            "Workers are repairing the pipes this afternoon. " +
            "Please do not use the shower room until tomorrow. " +
            "You may change your clothes in the locker room as usual. " +
            "We are sorry for the trouble.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "분실물을 찾으려고",
        "청소를 부탁하려고",
        "동아리를 모집하려고",
        "샤워실 사용 중단을 알리려고",
      ],
      answer: 5,
      clue: "The hot water in the gym showers is not working today.",
      explanation:
        "수리 때문에 샤워실을 쓰지 말라고 알리는 방송이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 알려 드립니다. 학교 행정실입니다. 오늘 체육관 샤워실 온수가 나오지 않습니다. 오늘 오후에 작업자들이 배관을 고칩니다. 내일까지 샤워실을 사용하지 마시기 바랍니다. 옷은 평소처럼 탈의실에서 갈아입으시면 됩니다. 불편을 드려 죄송합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the science museum?"],
        ["M", "Yes, two student tickets, please."],
        ["W", "Student tickets are five dollars each."],
        ["M", "Is there a charge for the special room?"],
        ["W", "The space show costs two dollars per person."],
        ["M", "We'd like to see that as well."],
        ["W", "So that's two tickets and two shows."],
        ["M", "Do students get any discount today?"],
        ["W", "Not on weekends, I'm afraid."],
        ["M", "That's fine. Here you are."],
      ],
      choices: ["$10", "$12", "$14", "$16", "$18"],
      answer: 3,
      clue: "Student tickets are five dollars each.",
      explanation:
        "입장권 두 장 10달러와 우주쇼 두 명 4달러를 더하면 14달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 과학관 표 사시나요?",
        "M: 네, 학생 표 두 장 주세요.",
        "W: 학생 표는 한 장에 5달러입니다.",
        "M: 특별관은 따로 돈을 내나요?",
        "W: 우주쇼는 한 명당 2달러입니다.",
        "M: 그것도 보고 싶어요.",
        "W: 그럼 표 두 장에 쇼 두 명이네요.",
        "M: 오늘 학생 할인은 없나요?",
        "W: 주말에는 없습니다.",
        "M: 괜찮아요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Kiwon, you finished the whole reading list already."],
        ["M", "I read twenty pages before breakfast every day."],
        ["W", "Isn't it hard to wake up that early?"],
        ["M", "I go to bed thirty minutes earlier now."],
        ["W", "I always plan to read but never start."],
        ["M", "Keep the book on the table, not on the shelf."],
        ["W", "That sounds almost too simple."],
        ["M", "Seeing it is half the work."],
        ["W", "Which book should I start with?"],
      ],
      choices: [
        "You don't need to read.",
        "Try the shortest one first.",
        "Reading is a waste of time.",
        "I never read any books.",
        "Buy twenty books today.",
      ],
      answer: 2,
      clue: "Which book should I start with?",
      explanation:
        "어떤 책부터 시작할지 물었으므로, 제일 짧은 것부터 해 보라는 ②가 가장 자연스럽다.",
      translation: [
        "W: 기원아, 너 독서 목록을 벌써 다 읽었네.",
        "M: 매일 아침 먹기 전에 스무 쪽씩 읽어.",
        "W: 그렇게 일찍 일어나는 게 힘들지 않아?",
        "M: 요즘은 30분 일찍 자.",
        "W: 나는 늘 읽겠다고 계획만 하고 시작을 못 해.",
        "M: 책을 책꽂이 말고 책상 위에 둬.",
        "W: 너무 간단한 것 같은데.",
        "M: 눈에 보이는 게 절반이야.",
        "W: 어떤 책부터 시작할까?",
        "M: 제일 짧은 것부터 해 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Bora, I heard you started learning sign language."],
        ["W", "My neighbor is deaf, so I wanted to talk with her."],
        ["M", "Where do you learn it these days?"],
        ["W", "At the community center on Saturday mornings."],
        ["M", "Is it difficult to remember all the hand shapes?"],
        ["W", "The shapes are fine, but the speed is hard."],
        ["M", "Can you have a real conversation yet?"],
        ["W", "We talk about the weather and food slowly."],
        ["M", "Does your neighbor help you practice?"],
        ["W", "She corrects me every time we meet."],
        ["M", "Could I go to the class with you sometime?"],
      ],
      choices: [
        "Sure, come this Saturday.",
        "The class ended last year.",
        "I stopped learning it.",
        "You already speak it well.",
        "There is no class here.",
      ],
      answer: 1,
      clue: "Could I go to the class with you sometime?",
      explanation:
        "수업에 같이 가도 되는지 물었으므로, 이번 토요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 보라야, 너 수화 배우기 시작했다며.",
        "W: 이웃분이 청각 장애가 있으셔서 대화하고 싶었어.",
        "M: 요즘 어디서 배워?",
        "W: 토요일 오전에 주민 센터에서.",
        "M: 손 모양을 다 외우는 게 어렵지 않아?",
        "W: 모양은 괜찮은데 속도가 어려워.",
        "M: 이제 실제로 대화도 해?",
        "W: 날씨랑 음식 이야기를 천천히 해.",
        "M: 이웃분이 연습을 도와주셔?",
        "W: 만날 때마다 고쳐 주셔.",
        "M: 나도 언제 그 수업에 같이 가도 돼?",
        "W: 그럼, 이번 토요일에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seokjin, how is your work in the school garden going?"],
        ["M", "The tomatoes I planted in April are slowly dying."],
        ["W", "Have you been watering them every single day?"],
        ["M", "Twice a day, once in the morning and once after school."],
        ["W", "That might actually be far too much water for them."],
        ["M", "I always thought more water was better for plants."],
        ["W", "The roots need air in the soil between waterings."],
        ["M", "Nobody told me anything about that before."],
        ["W", "Are the lower leaves turning yellow and soft?"],
        ["M", "Yes, and the soil never really dries out."],
        ["W", "Why don't you water them only in the morning?"],
      ],
      choices: [
        "I'll try that from tomorrow.",
        "The garden has no plants.",
        "I never water anything.",
        "Tomatoes don't need water.",
        "I'll water them five times.",
      ],
      answer: 1,
      clue: "Why don't you water them only in the morning?",
      explanation:
        "아침에만 물을 주라는 제안이므로, 내일부터 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 석진아, 학교 텃밭 일은 잘돼 가?",
        "M: 4월에 심은 토마토가 서서히 죽어 가.",
        "W: 하루도 빠짐없이 물을 줬어?",
        "M: 하루에 두 번, 아침에 한 번 방과 후에 한 번.",
        "W: 그게 오히려 물이 훨씬 많은 걸 수도 있어.",
        "M: 식물한테는 물이 많을수록 좋은 줄 알았어.",
        "W: 뿌리는 물 주는 사이에 흙 속 공기가 필요해.",
        "M: 아무도 그런 말을 해 준 적이 없어.",
        "W: 아래쪽 잎이 노랗고 물러지지 않았어?",
        "M: 맞아, 흙이 제대로 마르지를 않아.",
        "W: 아침에만 물을 주는 건 어때?",
        "M: 내일부터 그렇게 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Haneul이 Jinu에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Haneul : ________________",
      lines: [
        [
          "W",
          "Haneul and Jinu are working on a group report together. " +
            "Jinu has copied three long paragraphs from a website. " +
            "Haneul knows their teacher checks every source carefully. " +
            "She does not want their group to lose points for copying. " +
            "She wants Jinu to write the part in his own words. " +
            "In this situation, what would Haneul most likely say to Jinu?",
        ],
      ],
      choices: [
        "Let's write this part ourselves.",
        "The report is already finished.",
        "You should print it in color.",
        "We don't need any sources.",
        "I'll hand it in tomorrow.",
      ],
      answer: 1,
      clue: "She wants Jinu to write the part in his own words.",
      explanation:
        "베낀 부분을 직접 쓰기를 바라므로, 우리가 직접 쓰자는 ①이 가장 적절하다.",
      translation: [
        "W: 하늘이와 진우는 함께 조별 보고서를 쓰고 있습니다. 진우는 어떤 누리집에서 긴 문단 세 개를 그대로 옮겨 왔습니다. 하늘이는 선생님이 출처를 꼼꼼히 확인하신다는 것을 압니다. 그녀는 베꼈다는 이유로 조가 점수를 잃는 것을 원하지 않습니다. 하늘이는 진우가 그 부분을 자기 말로 쓰기를 바랍니다. 이런 상황에서 하늘이가 진우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
