/** 중2 듣기 39회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 39회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 여행용 베개를 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a travel pillow?"],
        ["W", "Yes, my head falls forward on long bus rides."],
        ["M", "Then a U-shaped one holds your neck better."],
        ["W", "A U shape it is. The square ones look flat."],
        ["M", "Some of them have a hood attached behind."],
        ["W", "No hood, please. My head gets too warm."],
        ["M", "This one closes with a snap button in front."],
        ["W", "I don't need the button either. Just the plain one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "A U shape it is. The square ones look flat. / No hood, please. My head gets too warm.",
      explanation:
        "여자는 U자 모양에 후드와 단추가 없는 베개를 골랐다. 따라서 답은 ①이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five travel neck pillows laid side by side as five choices, clean black line art on white. " +
          "① a U-SHAPED neck pillow with NO hood and NO button, plain and open at the front. " +
          "② a SQUARE flat pillow with NO hood and NO button. " +
          "③ a U-SHAPED neck pillow with a soft HOOD attached at the back. " +
          "④ a SQUARE flat pillow with a soft HOOD attached at the back. " +
          "⑤ a U-SHAPED neck pillow with NO hood but a round SNAP BUTTON joining the two front ends.",
      },
      translation: [
        "M: 안녕하세요. 여행용 베개 찾으세요?",
        "W: 네, 버스 오래 타면 고개가 앞으로 떨어져요.",
        "M: 그러면 U자 모양이 목을 더 잘 받쳐 줘요.",
        "W: U자로 할게요. 네모난 건 납작해 보여요.",
        "M: 뒤에 후드가 달린 것도 있어요.",
        "W: 후드는 없는 걸로요. 머리가 너무 더워요.",
        "M: 이건 앞을 똑딱단추로 잠가요.",
        "W: 단추도 필요 없어요. 그냥 기본으로 주세요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 사진 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Dohyun, are you entering the school photo contest?"],
        ["M", "Maybe. What is the theme this year?"],
        ["W", "Something you see every day but never notice."],
        ["M", "When do we have to hand it in?"],
        ["W", "By the twentieth of this month."],
        ["M", "Do we print it or send a file?"],
        ["W", "Send the file to the art teacher's school mail."],
        ["M", "Is there a size rule for the photo?"],
        ["W", "It must be larger than two megabytes."],
      ],
      choices: [
        "올해의 주제",
        "제출하는 기한",
        "제출하는 방법",
        "사진의 크기 조건",
        "결과를 알리는 날",
      ],
      answer: 5,
      clue: "Something you see every day but never notice. / It must be larger than two megabytes.",
      explanation:
        "주제, 기한, 제출 방법, 크기 조건은 말했지만 결과 발표일은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 학교 사진 대회 나갈 거야?",
        "M: 아마도. 올해 주제가 뭐야?",
        "W: 매일 보지만 눈여겨보지 않는 것.",
        "M: 언제까지 내야 해?",
        "W: 이번 달 20일까지.",
        "M: 인쇄해서 내? 파일로 보내?",
        "W: 미술 선생님 학교 메일로 파일을 보내.",
        "M: 사진 크기 조건도 있어?",
        "W: 2메가바이트보다 커야 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Seungho. It's Hayeon. Are you busy tonight?"],
        ["M", "Not really. I'm just looking at my science notes."],
        ["W", "The unit test is on Thursday, right?"],
        ["M", "Yes, and chapter four is really hard."],
        ["W", "Chapter four is the part I understand best."],
        ["M", "Then maybe we should go over it together."],
        ["W", "That's why I called. Library at four tomorrow?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "함께 공부하자고 하려고",
        "약속을 미루려고",
        "물건을 빌리려고",
        "길을 물어보려고",
      ],
      answer: 2,
      clue: "That's why I called. Library at four tomorrow?",
      explanation:
        "여자는 시험공부를 함께 하자고 하려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 승호야. 하연이야. 오늘 밤 바빠?",
        "M: 아니. 과학 필기 보고 있었어.",
        "W: 단원 평가가 목요일이지?",
        "M: 응, 4단원이 정말 어려워.",
        "W: 4단원은 내가 제일 잘 아는 부분이야.",
        "M: 그럼 같이 보면 되겠다.",
        "W: 그것 때문에 전화했어. 내일 4시에 도서관에서?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Chaewon, when does the art class open on Sunday?"],
        ["W", "The studio opens its doors at two o'clock."],
        ["M", "Do we have to choose our seats early?"],
        ["W", "Yes, the ones near the window fill up fast."],
        ["M", "How early should we be there?"],
        ["W", "About fifteen minutes before it opens."],
        ["M", "Then a quarter to two at the entrance."],
        ["W", "My bus gets in at one fifty, sadly."],
        ["M", "Then let's just meet at one fifty-five."],
      ],
      choices: ["1:45 p.m.", "1:50 p.m.", "2:00 p.m.", "2:15 p.m.", "1:55 p.m."],
      answer: 5,
      clue: "Then let's just meet at one fifty-five.",
      explanation:
        "여자의 버스가 1시 50분에 도착해서 1시 55분에 만나기로 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 채원아, 일요일에 미술 수업 몇 시에 열어?",
        "W: 작업실은 2시에 문을 열어.",
        "M: 자리를 일찍 잡아야 해?",
        "W: 응, 창가 자리는 금방 차.",
        "M: 얼마나 일찍 가야 해?",
        "W: 문 열기 15분쯤 전에.",
        "M: 그럼 1시 45분에 입구에서.",
        "W: 아쉽게도 내 버스가 1시 50분에 도착해.",
        "M: 그럼 그냥 1시 55분에 만나자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, you keep checking your phone during break."],
        ["W", "My little sister went on her first school trip today."],
        ["M", "Is this the first time she is away overnight?"],
        ["W", "Yes, and she has never slept without our parents."],
        ["M", "Did she call you after they arrived?"],
        ["W", "One short message, and nothing since lunch."],
        ["M", "The teachers are with them the whole time."],
        ["W", "I know, but I keep thinking about her."],
      ],
      choices: ["angry", "bored", "worried", "happy", "proud"],
      answer: 3,
      clue: "I know, but I keep thinking about her.",
      explanation:
        "처음 밖에서 자는 동생이 계속 마음에 걸린다고 했으므로 걱정하는 심정이다. 따라서 답은 ③이다.",
      translation: [
        "M: 예린아, 쉬는 시간마다 휴대전화를 보네.",
        "W: 동생이 오늘 첫 수학여행을 갔어.",
        "M: 밖에서 자는 게 처음이야?",
        "W: 응, 부모님 없이 자 본 적이 없어.",
        "M: 도착하고 전화는 했어?",
        "W: 짧은 문자 하나. 점심 이후로는 없어.",
        "M: 선생님들이 내내 같이 계시잖아.",
        "W: 알아. 그래도 계속 생각이 나.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How long do I have to wait?"],
        ["M", "About ten minutes."],
        ["ANN", "Number two."],
        ["W", "Is this shampoo for dry hair?"],
        ["M", "Yes, it is."],
        ["ANN", "Number three."],
        ["W", "Please cut it about this much."],
        ["M", "All right, just above the shoulders."],
        ["ANN", "Number four."],
        ["W", "Do you take cards here?"],
        ["M", "Yes, we do."],
        ["ANN", "Number five."],
        ["W", "What time do you close?"],
        ["M", "At eight in the evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Please cut it about this much.",
      explanation:
        "그림은 미용실에서 여자가 손으로 자를 길이를 보여 주고 미용사가 고개를 끄덕이는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a hair salon, clean black line art on a plain white background, no writing anywhere. " +
          "A woman sits in a salon chair facing a large mirror and holds her own hair with two fingers to show a length. " +
          "A male hairdresser stands behind her with scissors in one hand and nods. " +
          "A cape covers her shoulders, and a shelf with plain bottles is drawn in the background.",
      },
      translation: [
        "① W: 얼마나 기다려야 해요? / M: 10분쯤이요.",
        "② W: 이 샴푸 건성 머리용인가요? / M: 네, 맞습니다.",
        "③ W: 이만큼만 잘라 주세요. / M: 알겠습니다, 어깨 조금 위로요.",
        "④ W: 여기 카드 되나요? / M: 네, 됩니다.",
        "⑤ W: 몇 시에 닫아요? / M: 저녁 8시에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, were you in English class this afternoon?"],
        ["W", "Yes, we went over the whole review unit."],
        ["M", "I was at the counseling room the whole period."],
        ["W", "The teacher said something about the test."],
        ["M", "That's what I was afraid of missing."],
        ["W", "She changed which pages will be on it."],
        ["M", "Could you tell me exactly which pages they are?"],
        ["W", "Sure, I wrote them down in my planner."],
      ],
      choices: [
        "준비물을 빌려주기",
        "시험 범위를 알려 주기",
        "청소를 도와주기",
        "사진을 찍어 주기",
        "자리를 맡아 주기",
      ],
      answer: 2,
      clue: "Could you tell me exactly which pages they are?",
      explanation:
        "남자는 바뀐 시험 범위를 알려 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 수민아, 오늘 오후 영어 수업 들었어?",
        "W: 응, 복습 단원 전체를 봤어.",
        "M: 나는 그 시간 내내 상담실에 있었어.",
        "W: 선생님이 시험에 대해 말씀하셨어.",
        "M: 그게 제일 놓치기 싫었던 건데.",
        "W: 시험에 나올 쪽수를 바꾸셨어.",
        "M: 정확히 몇 쪽인지 알려 줄 수 있어?",
        "W: 그럼, 수첩에 적어 뒀어.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 진로 캠프에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Let me tell you about the career camp. " +
            "It will be held on the last Saturday of this month. " +
            "We will use the multimedia room and the two science labs. " +
            "You will meet four workers and try one hands-on activity. " +
            "Applications close this Friday at the office.",
        ],
      ],
      choices: [
        "캠프가 열리는 날",
        "사용하는 장소",
        "참가할 수 있는 인원",
        "캠프에서 하는 활동",
        "신청이 끝나는 날",
      ],
      answer: 3,
      clue: "It will be held on the last Saturday of this month.",
      explanation:
        "날짜, 장소, 활동, 신청 마감은 말했지만 참가 인원은 말하지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 진로 캠프를 안내합니다. 캠프는 이번 달 마지막 토요일에 열립니다. 멀티미디어실과 과학실 두 곳을 씁니다. 여러 직업인 네 분을 만나고 체험 활동을 하나 해 봅니다. 신청은 이번 주 금요일에 교무실에서 마감합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a round metal container with two side handles. " +
            "You put water, rice or soup inside it. " +
            "Then you set it on the stove and turn on the heat. " +
            "A lid on top keeps the steam from escaping. " +
            "Use a cloth to lift it, because the handles get hot.",
        ],
      ],
      choices: ["냄비", "접시", "컵", "숟가락", "주전자"],
      answer: 1,
      clue: "Then you set it on the stove and turn on the heat.",
      explanation:
        "손잡이가 둘 달린 둥근 그릇에 국이나 밥을 넣고 불에 올려 끓이는 것은 냄비이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 양옆에 손잡이가 달린 둥근 쇠 그릇입니다. 안에 물이나 밥, 국을 넣습니다. 그런 다음 가스레인지에 올리고 불을 켭니다. 위에 있는 뚜껑이 김이 빠져나가지 않게 합니다. 손잡이가 뜨거워지니 천으로 잡고 드세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Are you coming to the meeting?"],
        ["M", "Yes, I'll be there at five."],
        ["ANN", "Number two."],
        ["W", "Could you pass me the eraser?"],
        ["M", "Here, take mine."],
        ["ANN", "Number three."],
        ["W", "How do you feel today?"],
        ["M", "Much better than yesterday."],
        ["ANN", "Number four."],
        ["W", "Who is going to speak first?"],
        ["M", "It takes about ten minutes."],
        ["ANN", "Number five."],
        ["W", "Did you lock the door?"],
        ["M", "Yes, I checked it twice."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is going to speak first?",
      explanation:
        "누가 먼저 말할지 묻는 말에 10분쯤 걸린다고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 모임에 올 거야? / M: 응, 5시에 갈게.",
        "② W: 지우개 좀 건네줄래? / M: 여기, 내 거 써.",
        "③ W: 오늘 몸은 어때? / M: 어제보다 훨씬 나아.",
        "④ W: 누가 먼저 발표해? / M: 10분쯤 걸려.",
        "⑤ W: 문 잠갔어? / M: 응, 두 번 확인했어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, did you hand in the club application form?"],
        ["W", "Not yet. It's still inside my folder."],
        ["M", "The teacher said today is the last day."],
        ["W", "I thought the deadline was tomorrow."],
        ["M", "She moved it up because of the school trip."],
        ["W", "What time does the office close today?"],
        ["M", "At four thirty, and it's four ten now."],
        ["W", "Then I'll take it to the office right away."],
      ],
      choices: [
        "도서관에 가기",
        "교무실에 서류를 내러 가기",
        "교실을 청소하기",
        "점심을 먹으러 가기",
        "집으로 돌아가기",
      ],
      answer: 2,
      clue: "Then I'll take it to the office right away.",
      explanation:
        "여자는 지금 바로 교무실에 신청서를 내러 가겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 다인아, 동아리 신청서 냈어?",
        "W: 아직. 아직 내 파일에 있어.",
        "M: 선생님이 오늘이 마지막이라고 하셨어.",
        "W: 마감이 내일인 줄 알았는데.",
        "M: 수학여행 때문에 앞당기셨어.",
        "W: 오늘 교무실 몇 시에 닫아?",
        "M: 4시 30분. 지금 4시 10분이야.",
        "W: 그럼 지금 바로 교무실에 가져갈게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 등록할 미술 학원을 고르시오.",
      lines: [
        ["M", "Seoyun, which art school are you going to register at?"],
        ["W", "Let's look at these five in our neighborhood."],
        ["M", "How far can you go from home?"],
        ["W", "Within fifteen minutes on foot."],
        ["M", "All right. Which days can you attend?"],
        ["W", "Only Monday and Wednesday. I have piano on other days."],
        ["M", "And what about the monthly fee?"],
        ["W", "Under a hundred thousand won, please."],
        ["M", "Then only one school here matches everything."],
        ["W", "Good. I'll visit it tomorrow after school."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Only Monday and Wednesday. I have piano on other days.",
      explanation:
        "걸어서 15분 이내, 월·수 수업, 10만 원 이하인 곳을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Walk: 10 min / Days: Tue, Thu / Fee: 90,000 won" },
          { no: 2, label: "②", value: "Walk: 25 min / Days: Mon, Wed / Fee: 85,000 won" },
          { no: 3, label: "③", value: "Walk: 12 min / Days: Mon, Wed / Fee: 120,000 won" },
          { no: 4, label: "④", value: "Walk: 8 min / Days: Mon, Wed / Fee: 95,000 won" },
          { no: 5, label: "⑤", value: "Walk: 5 min / Days: Fri, Sat / Fee: 70,000 won" },
        ],
      },
      translation: [
        "M: 서윤아, 어느 미술 학원에 등록할 거야?",
        "W: 우리 동네 다섯 곳 보자.",
        "M: 집에서 얼마나 멀리 갈 수 있어?",
        "W: 걸어서 15분 안쪽으로.",
        "M: 알겠어. 무슨 요일에 다닐 수 있어?",
        "W: 월요일과 수요일만. 다른 날은 피아노가 있어.",
        "M: 한 달 학원비는?",
        "W: 10만 원 이하로.",
        "M: 그럼 여기서 다 맞는 곳은 하나뿐이야.",
        "W: 좋아. 내일 방과 후에 가 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 가기로 한 날짜를 고르시오.",
      lines: [
        ["M", "Bomi, when can we go to the recycling center?"],
        ["W", "They accept student helpers three times this month."],
        ["M", "Which days did they give us?"],
        ["W", "The seventh, the fourteenth and the twenty-first."],
        ["M", "The seventh is our club presentation day."],
        ["W", "And the fourteenth is my grandmother's birthday."],
        ["M", "So the twenty-first is the only one left."],
        ["W", "It's a Saturday, so we can stay all morning."],
        ["M", "Then let's write our names down for the twenty-first."],
      ],
      choices: [
        "the 7th",
        "the 10th",
        "the 14th",
        "the 17th",
        "the 21st",
      ],
      answer: 5,
      clue: "So the twenty-first is the only one left.",
      explanation:
        "7일은 발표, 14일은 할머니 생신이어서 21일로 정했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 보미야, 재활용 센터에 언제 갈 수 있어?",
        "W: 이번 달에 학생 도우미를 세 번 받아 줘.",
        "M: 어떤 날을 알려 줬어?",
        "W: 7일, 14일, 21일.",
        "M: 7일은 우리 동아리 발표일이야.",
        "W: 그리고 14일은 우리 할머니 생신이야.",
        "M: 그럼 남는 건 21일뿐이네.",
        "W: 토요일이라 오전 내내 있을 수 있어.",
        "M: 그럼 21일로 이름 적자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jaehyun, did you stay in all weekend?"],
        ["M", "No, I went to my little brother's sports day."],
        ["W", "Which school does he go to?"],
        ["M", "The elementary school behind our apartment."],
        ["W", "Did he run in any of the races?"],
        ["M", "The relay, and his team came in second."],
        ["W", "Were your parents there as well?"],
        ["M", "They were, and we ate kimbap on the grass together."],
      ],
      choices: [
        "영화를 보러 가기",
        "병원에 다녀오기",
        "친구와 등산을 가기",
        "동생의 운동회에 가기",
        "도서관에서 공부하기",
      ],
      answer: 4,
      clue: "No, I went to my little brother's sports day.",
      explanation:
        "남자는 주말에 동생의 운동회에 다녀왔다. 따라서 답은 ④이다.",
      translation: [
        "W: 재현아, 주말 내내 집에 있었어?",
        "M: 아니, 동생 운동회에 갔어.",
        "W: 동생이 어느 학교 다녀?",
        "M: 우리 아파트 뒤 초등학교.",
        "W: 동생이 경주에 나갔어?",
        "M: 계주에 나가서 팀이 2등 했어.",
        "W: 부모님도 가셨어?",
        "M: 가셨어. 잔디밭에서 같이 김밥 먹었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. The student council has good news today. " +
            "A new study room opened on the fourth floor this morning. " +
            "It has twenty desks and stays open until seven every evening. " +
            "You may bring water, but no other food or drinks. " +
            "Anyone may use it, and no reservation is needed. " +
            "Come and take a look after your classes today.",
        ],
      ],
      choices: [
        "새 시설을 알리려고",
        "분실물을 찾아가라고",
        "안전 규칙을 안내하려고",
        "청소를 부탁하려고",
        "행사 취소를 알리려고",
      ],
      answer: 1,
      clue: "A new study room opened on the fourth floor this morning.",
      explanation:
        "4층에 새로 생긴 자습실을 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 오늘 학생회에서 좋은 소식이 있습니다. 오늘 아침 4층에 새 자습실이 문을 열었습니다. 책상이 스무 개 있고 매일 저녁 일곱 시까지 엽니다. 물은 가져와도 되지만 다른 음식이나 음료는 안 됩니다. 누구나 쓸 수 있고 예약도 필요 없습니다. 오늘 수업이 끝나면 한번 와서 보세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What would you like to order?"],
        ["M", "Three bowls of noodles, please. How much is one?"],
        ["W", "A bowl of noodles is eight dollars."],
        ["M", "We'd also like two plates of dumplings."],
        ["W", "Dumplings are five dollars a plate."],
        ["M", "Is there a discount for eating in?"],
        ["W", "No, but takeout orders get two dollars off."],
        ["M", "We're eating here. Thank you."],
      ],
      choices: ["$30", "$32", "$36", "$38", "$34"],
      answer: 5,
      clue: "A bowl of noodles is eight dollars. / Dumplings are five dollars a plate.",
      explanation:
        "국수 세 그릇 24달러에 만두 두 접시 10달러를 더하면 34달러이고, 매장에서 먹으므로 할인은 없다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요. 무엇을 주문하시겠어요?",
        "M: 국수 세 그릇 주세요. 한 그릇에 얼마예요?",
        "W: 국수는 한 그릇에 8달러예요.",
        "M: 만두도 두 접시 주세요.",
        "W: 만두는 한 접시에 5달러예요.",
        "M: 매장에서 먹으면 할인이 있나요?",
        "W: 아니요, 포장하시면 2달러 빼 드려요.",
        "M: 여기서 먹을게요. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junhyuk, your posture at the desk looks much better."],
        ["M", "I raised my monitor with two thick books."],
        ["W", "Did that really change anything?"],
        ["M", "My neck stopped hurting after three days."],
        ["W", "I lean forward the whole time when I study."],
        ["M", "Your screen is probably too low."],
        ["W", "It sits right on the desk, actually."],
        ["M", "The top of the screen should meet your eyes."],
        ["W", "Could you help me set mine up tomorrow?"],
      ],
      choices: [
        "My monitor is broken.",
        "You should lean forward.",
        "Sure, I'll come after lunch.",
        "I don't use a monitor.",
        "The books are too thin.",
      ],
      answer: 3,
      clue: "Could you help me set mine up tomorrow?",
      explanation:
        "여자가 내일 화면 높이 맞추는 걸 도와 달라고 했으므로, 점심 후에 가겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 준혁아, 책상에 앉은 자세가 훨씬 좋아졌어.",
        "M: 두꺼운 책 두 권으로 화면을 올렸어.",
        "W: 그걸로 정말 달라져?",
        "M: 사흘 만에 목이 안 아프기 시작했어.",
        "W: 나는 공부할 때 내내 앞으로 기울여.",
        "M: 화면이 너무 낮은 것 같아.",
        "W: 사실 책상에 그냥 놓여 있어.",
        "M: 화면 위쪽이 눈높이에 와야 해.",
        "W: 내일 내 것도 맞추는 것 좀 도와줄래?",
        "M: 그럼, 점심 먹고 갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayoon, your class recycling box is always neat."],
        ["W", "We fold every paper box before putting it in."],
        ["M", "Does folding really make that much difference?"],
        ["W", "One folded box takes a third of the space."],
        ["M", "Ours fills up by Wednesday every week."],
        ["W", "Then someone has to carry it down twice."],
        ["M", "That's why nobody wants to be on duty."],
        ["W", "Folding takes ten seconds for each box."],
        ["M", "Could you show my class how you fold them?"],
      ],
      choices: [
        "We never fold anything.",
        "Sure, I'll drop by on Friday.",
        "Your box is already neat.",
        "I don't do recycling.",
        "Folding takes an hour.",
      ],
      answer: 2,
      clue: "Could you show my class how you fold them?",
      explanation:
        "남자가 접는 법을 보여 달라고 했으므로, 금요일에 들르겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나윤아, 너희 반 재활용 상자는 늘 깔끔하더라.",
        "W: 종이 상자를 다 접어서 넣어.",
        "M: 접는 게 그렇게 차이가 나?",
        "W: 접으면 부피가 3분의 1이 돼.",
        "M: 우리 반은 매주 수요일이면 가득 차.",
        "W: 그럼 누가 두 번 들고 내려가야 하네.",
        "M: 그래서 아무도 당번을 하기 싫어해.",
        "W: 상자 하나 접는 데 10초면 돼.",
        "M: 우리 반에 접는 법 좀 보여 줄래?",
        "W: 그럼, 금요일에 들를게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seokjin, did you finish the reading log this month?"],
        ["M", "I only wrote two entries out of eight."],
        ["W", "What makes it so hard to keep up?"],
        ["M", "I try to write a full page about each book."],
        ["W", "A full page for every book is a lot."],
        ["M", "The teacher only asked for three sentences."],
        ["W", "Then why are you writing so much?"],
        ["M", "I thought longer answers would look better."],
        ["W", "Short and finished beats long and missing."],
      ],
      choices: [
        "I'll write two pages next time.",
        "The log is not due yet.",
        "I never read any books.",
        "You're right. I'll keep it short.",
        "Three sentences is too long.",
      ],
      answer: 4,
      clue: "Short and finished beats long and missing.",
      explanation:
        "짧아도 끝내는 게 낫다고 했으므로, 짧게 쓰겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 석진아, 이번 달 독서 기록 다 했어?",
        "M: 여덟 개 중에 두 개만 썼어.",
        "W: 왜 그렇게 따라가기 어려워?",
        "M: 책마다 한 쪽을 다 채우려고 해.",
        "W: 책마다 한 쪽이면 정말 많다.",
        "M: 선생님은 세 문장만 쓰라고 하셨어.",
        "W: 그런데 왜 그렇게 많이 써?",
        "M: 길게 쓰면 더 좋아 보일 줄 알았어.",
        "W: 짧아도 끝낸 게 길다가 못 낸 것보다 나아.",
        "M: 네 말이 맞아. 짧게 쓸게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yerim이 Gunwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yerim : ________________",
      lines: [
        [
          "W",
          "Yerim and Gunwoo are getting ready for the school marathon. " +
            "Gunwoo ties his number tag onto the back of his shirt. " +
            "Yerim knows that the tag must be worn on the front. " +
            "The camera at the finish line reads only the front tags. " +
            "She wants to tell him before the race begins. " +
            "In this situation, what would Yerim most likely say to Gunwoo?",
        ],
      ],
      choices: [
        "Your number goes on the front.",
        "The race starts at nine o'clock.",
        "Can I borrow your water bottle?",
        "Let's run together at the back.",
        "You should wear running shoes.",
      ],
      answer: 1,
      clue: "She wants to tell him before the race begins.",
      explanation:
        "번호표를 등에 달았는데 앞에 달아야 하므로, 앞에 달라고 알려 주는 ①이 가장 적절하다.",
      translation: [
        "W: 예림이와 건우는 학교 마라톤을 준비하고 있습니다. 건우가 번호표를 셔츠 등에 매답니다. 예림이는 번호표를 앞에 달아야 한다는 것을 압니다. 결승선의 카메라는 앞에 달린 번호표만 읽습니다. 예림이는 경주가 시작되기 전에 알려 주고 싶습니다. 이런 상황에서 예림이가 건우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
