/** 중2 듣기 14회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 14회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 의자를 고르시오.",
      lines: [
        ["M", "Good afternoon. Are you looking for a desk chair?"],
        ["W", "Yes, for my room. The old one has no back support."],
        ["M", "We have chairs with wheels and chairs with four fixed legs."],
        ["W", "With wheels, please. I move around a lot when I study."],
        ["M", "All right. Do you want armrests on it?"],
        ["W", "No armrests. My desk is low and they get in the way."],
        ["M", "Then we have two left. One has a cushion on the seat and one doesn't."],
        ["W", "I'll take the one with a cushion. I sit there for hours."],
        ["M", "Good choice. The height can be adjusted as well."],
        ["W", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'll take the one with a cushion. I sit there for hours.",
      explanation:
        "여자는 바퀴가 달리고 팔걸이가 없으며 방석이 있는 의자를 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five desk chairs shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a chair with FOUR FIXED LEGS and no wheels, with ARMRESTS, a plain hard seat. " +
          "Second: a chair with FOUR FIXED LEGS and no wheels, no armrests, a plain hard seat. " +
          "Third: a chair on a wheeled base with FIVE CASTER WHEELS, with ARMRESTS, a plain hard seat. " +
          "Fourth: a chair on a wheeled base with FIVE CASTER WHEELS, no armrests, with a thick padded CUSHION on the seat. " +
          "Fifth: a chair on a wheeled base with FIVE CASTER WHEELS, no armrests, a plain hard seat with no cushion.",
      },
      translation: [
        "M: 안녕하세요. 책상 의자 찾으세요?",
        "W: 네, 제 방에 놓을 거예요. 쓰던 건 등받이가 없어서요.",
        "M: 바퀴 달린 것과 다리 네 개짜리가 있습니다.",
        "W: 바퀴 달린 걸로요. 공부할 때 많이 움직이거든요.",
        "M: 알겠습니다. 팔걸이는 있는 게 좋으세요?",
        "W: 팔걸이는 없는 걸로요. 책상이 낮아서 걸려요.",
        "M: 그럼 두 개 남았네요. 하나는 방석이 있고 하나는 없습니다.",
        "W: 방석 있는 걸로 할게요. 몇 시간씩 앉아 있거든요.",
        "M: 좋은 선택이세요. 높이도 조절됩니다.",
        "W: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 영어 말하기 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junseo, are you entering the English speaking contest?"],
        ["M", "I want to, but I don't know the details yet."],
        ["W", "It's on the last Wednesday of this month, in the afternoon."],
        ["M", "Where is it held?"],
        ["W", "In the language room on the third floor, not the main hall."],
        ["M", "How long do we have to speak?"],
        ["W", "Three minutes each. They stop you at three thirty."],
        ["M", "Is the topic given, or do we choose?"],
        ["W", "You choose your own, but it has to be about your school life."],
        ["M", "That's easier than last year. I'll start writing tonight."],
        ["W", "Good. Don't leave it until the week before."],
      ],
      choices: ["열리는 날", "장소", "발표 시간", "주제", "심사 기준"],
      answer: 5,
      clue: "You choose your own, but it has to be about your school life.",
      explanation:
        "날짜(이달 마지막 수요일), 장소(3층 어학실), 발표 시간(3분), 주제(학교생활에 관한 자유 주제)는 언급되지만 심사 기준은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준서야, 영어 말하기 대회 나갈 거야?",
        "M: 나가고 싶은데 아직 자세한 걸 몰라.",
        "W: 이달 마지막 수요일 오후에 해.",
        "M: 어디에서 열려?",
        "W: 대강당이 아니라 3층 어학실에서.",
        "M: 몇 분 동안 말해야 해?",
        "W: 한 사람당 3분. 3분 30초에서 끊어.",
        "M: 주제는 정해 줘, 아니면 우리가 골라?",
        "W: 직접 고르는데 학교생활에 관한 거여야 해.",
        "M: 작년보다 쉽네. 오늘 밤부터 써 볼게.",
        "W: 그래. 전주까지 미루지 마.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Jinwoo. It's Seoyeon from the science club."],
        ["M", "Hi. Is something wrong with tomorrow's experiment?"],
        ["W", "Not the experiment. It's the goggles."],
        ["M", "Aren't there enough in the lab?"],
        ["W", "Only eight, and there are twelve of us tomorrow."],
        ["M", "So we need four more."],
        ["W", "Could you borrow four from the second science room?"],
        ["M", "Sure, I'll ask the teacher in the morning."],
      ],
      choices: [
        "보호 안경을 빌려 달라고 부탁하려고",
        "실험 시간을 미루려고",
        "동아리 가입을 권하려고",
        "실험실 위치를 물어보려고",
        "보고서를 대신 내 달라고 하려고",
      ],
      answer: 1,
      clue: "Could you borrow four from the second science room?",
      explanation:
        "여자는 내일 실험에 보호 안경 네 개가 모자라서 제2과학실에서 빌려 달라고 부탁하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 진우야. 과학 동아리 서연이야.",
        "M: 안녕. 내일 실험에 무슨 문제 있어?",
        "W: 실험이 아니라 보호 안경 때문에.",
        "M: 실험실에 넉넉하지 않아?",
        "W: 여덟 개뿐인데 내일 우리가 열두 명이야.",
        "M: 그럼 네 개가 더 필요하네.",
        "W: 제2과학실에서 네 개만 빌려 올 수 있어?",
        "M: 그래, 아침에 선생님께 여쭤볼게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minho, what time should we meet at the bus stop?"],
        ["M", "The bus to the museum leaves at nine thirty."],
        ["W", "Then we should be there before it comes."],
        ["M", "How about nine o'clock?"],
        ["W", "That's half an hour of standing around."],
        ["M", "True. How long does it take you to walk there?"],
        ["W", "About twelve minutes from my house."],
        ["M", "Then let's meet at nine fifteen. That's enough time."],
        ["W", "Nine fifteen it is. I'll bring the tickets."],
      ],
      choices: ["8:45 a.m.", "9:00 a.m.", "9:15 a.m.", "9:30 a.m.", "9:45 a.m."],
      answer: 3,
      clue: "Then let's meet at nine fifteen. That's enough time.",
      explanation:
        "버스가 9시 30분에 떠나므로 두 사람은 9시 15분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 민호야, 버스 정류장에서 몇 시에 만날까?",
        "M: 박물관 가는 버스가 9시 30분에 떠나.",
        "W: 그럼 버스 오기 전에 가 있어야겠다.",
        "M: 9시는 어때?",
        "W: 30분이나 서서 기다리는 거잖아.",
        "M: 그러네. 너는 거기까지 걸어서 얼마나 걸려?",
        "W: 우리 집에서 12분쯤.",
        "M: 그럼 9시 15분에 만나자. 그 정도면 충분해.",
        "W: 9시 15분으로 하자. 표는 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seokjin, is something wrong? You keep looking at the door."],
        ["M", "My presentation is the first one after lunch."],
        ["W", "You practiced it all week, didn't you?"],
        ["M", "Twenty times at home, but never in front of people."],
        ["W", "Our class is only twenty-six people."],
        ["M", "Twenty-six pairs of eyes. My hands are cold already."],
        ["W", "Try taking three slow breaths before you start."],
        ["M", "I'll try, but I can hear my own heartbeat right now."],
      ],
      choices: ["excited", "bored", "proud", "angry", "nervous"],
      answer: 5,
      clue: "I'll try, but I can hear my own heartbeat right now.",
      explanation:
        "발표를 앞두고 손이 차가워지고 심장 소리가 들린다고 했으므로 남자는 긴장하고 있다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 석진아, 무슨 일 있어? 문만 계속 보네.",
        "M: 점심 먹고 첫 번째가 내 발표야.",
        "W: 일주일 내내 연습했잖아.",
        "M: 집에서 스무 번 했지, 사람들 앞에서는 한 번도 안 해 봤어.",
        "W: 우리 반은 스물여섯 명밖에 안 돼.",
        "M: 눈이 스물여섯 쌍이잖아. 벌써 손이 차가워.",
        "W: 시작하기 전에 천천히 세 번 숨 쉬어 봐.",
        "M: 해 볼게, 그런데 지금 내 심장 소리가 들려.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, is this seat free?"],
        ["M", "Yes, please sit down."],
        ["W", "Could you take a picture of us, please?"],
        ["M", "Of course. Say cheese."],
        ["W", "How do I get to the library from here?"],
        ["M", "Turn right at the next corner."],
        ["W", "Do you have this in a larger size?"],
        ["M", "Let me check in the back."],
        ["W", "What time does the museum close?"],
        ["M", "At six on weekdays."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Could you take a picture of us, please?",
      explanation:
        "그림은 두 학생이 한 사람에게 휴대전화를 건네며 사진을 찍어 달라고 부탁하는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "In front of a famous old gate in a park. Two students stand side by side, and one of them is holding out a mobile phone toward a passing man, asking him to take their photo. The man is reaching out to take the phone and smiling. Trees and the gate are in the background. All the people are drawn clearly.",
      },
      translation: [
        "① W: 실례합니다, 이 자리 비었나요? / M: 네, 앉으세요.",
        "② W: 저희 사진 좀 찍어 주시겠어요? / M: 그럼요. 치즈 하세요.",
        "③ W: 여기서 도서관에 어떻게 가나요? / M: 다음 모퉁이에서 오른쪽으로 도세요.",
        "④ W: 이거 더 큰 치수 있나요? / M: 안쪽에서 확인해 볼게요.",
        "⑤ W: 박물관이 몇 시에 닫나요? / M: 평일에는 6시에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, do you still go to the art room after school?"],
        ["W", "Every Monday and Thursday. Why?"],
        ["M", "I left my sketchbook there on Thursday."],
        ["W", "The big one with the grey cover?"],
        ["M", "That's the one. I have to hand in a drawing on Friday."],
        ["W", "And you can't go yourself?"],
        ["M", "I have to go straight home this week. My grandmother is staying with us."],
        ["W", "So you want me to bring it to you tomorrow?"],
        ["M", "Yes, please. Just leave it on my desk if I'm not there."],
        ["W", "No problem. I'll pick it up on Monday."],
      ],
      choices: ["스케치북 가져다주기", "그림 그려 주기", "미술실 청소하기", "자리 맡아 주기", "숙제 도와주기"],
      answer: 1,
      clue: "Yes, please. Just leave it on my desk if I'm not there.",
      explanation:
        "남자는 미술실에 두고 온 스케치북을 가져다 달라고 부탁한다. 따라서 답은 ①이다.",
      translation: [
        "M: 다혜야, 아직 방과 후에 미술실 가?",
        "W: 월요일이랑 목요일마다. 왜?",
        "M: 목요일에 거기에 스케치북을 두고 왔어.",
        "W: 회색 표지에 큰 거?",
        "M: 그거. 금요일에 그림을 내야 하거든.",
        "W: 네가 직접 못 가?",
        "M: 이번 주는 바로 집에 가야 해. 할머니가 와 계셔서.",
        "W: 그럼 내일 가져다 달라는 거지?",
        "M: 응, 부탁해. 내가 없으면 책상에 놔 줘.",
        "W: 그래. 월요일에 가져올게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, School Movie Night에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Here is news about School Movie Night."],
        ["M", "It will be held next Friday, from six to eight in the evening."],
        ["M", "We will use the big hall on the first floor."],
        ["M", "This year's film is about a young pianist in a small town."],
        ["M", "Popcorn and juice will be given to everyone at the door."],
        ["M", "Just come to the hall. No sign-up is needed."],
      ],
      choices: ["열리는 날", "장소", "상영 작품", "제공되는 간식", "관람 인원"],
      answer: 5,
      clue: "Just come to the hall. No sign-up is needed.",
      explanation:
        "날짜(다음 주 금요일), 장소(1층 대강당), 상영 작품(작은 마을의 젊은 피아니스트 이야기), 간식(팝콘과 주스)은 언급되지만 관람 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. School Movie Night 소식입니다.",
        "M: 다음 주 금요일 저녁 6시부터 8시까지 열립니다.",
        "M: 1층 대강당을 사용합니다.",
        "M: 올해 상영작은 작은 마을의 젊은 피아니스트 이야기입니다.",
        "M: 입구에서 팝콘과 주스를 모두에게 드립니다.",
        "M: 그냥 강당으로 오세요. 신청은 필요 없습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "This is a small machine you find in almost every kitchen."],
        ["W", "You put food inside and close the door."],
        ["W", "Then you press a few buttons and wait one or two minutes."],
        ["W", "It makes cold food hot without any fire."],
        ["W", "When the time is over, it makes a beeping sound."],
      ],
      choices: ["전자레인지", "냉장고", "세탁기", "청소기", "토스터"],
      answer: 1,
      clue: "It makes cold food hot without any fire.",
      explanation:
        "음식을 넣고 문을 닫은 뒤 버튼을 눌러 불 없이 데우고 끝나면 소리가 난다고 했으므로 전자레인지이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 거의 모든 부엌에 있는 작은 기계입니다.",
        "W: 음식을 안에 넣고 문을 닫습니다.",
        "W: 그러고 나서 버튼을 몇 개 누르고 1, 2분 기다립니다.",
        "W: 불 없이 차가운 음식을 뜨겁게 만듭니다.",
        "W: 시간이 다 되면 삐 소리가 납니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How was your first day at the new school?"],
        ["W", "Better than I expected."],
        ["M", "Could you turn down the music a little?"],
        ["W", "Sure, sorry about that."],
        ["M", "What do you usually do on Sundays?"],
        ["W", "I go to the swimming pool."],
        ["M", "Who is the tallest person in your class?"],
        ["W", "It starts at nine in the morning."],
        ["M", "Would you like some more rice?"],
        ["W", "No, thank you. I'm full."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is the tallest person in your class?",
      explanation:
        "반에서 누가 가장 키가 큰지 묻는 말에 아침 9시에 시작한다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 새 학교 첫날 어땠어? / W: 생각보다 좋았어.",
        "② M: 음악 소리 좀 줄여 줄래? / W: 그래, 미안.",
        "③ M: 일요일에는 보통 뭐 해? / W: 수영장에 가.",
        "④ M: 너희 반에서 누가 제일 키가 커? / W: 아침 9시에 시작해.",
        "⑤ M: 밥 좀 더 먹을래? / W: 아니, 괜찮아. 배불러.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, the club photo is in fifteen minutes."],
        ["W", "Is everyone ready? What still needs doing?"],
        ["M", "I've moved the bench and told all the members."],
        ["W", "Should I get the camera from the club room?"],
        ["M", "Suho already has it. He's setting it up outside."],
        ["W", "Then what's left?"],
        ["M", "Nobody has told the teacher, and she's in the photo too."],
        ["W", "I'll run to the staff room and let her know."],
        ["M", "Thanks. I'll wait with the others by the bench."],
      ],
      choices: ["벤치 옮기기", "부원들에게 알리기", "카메라 가져오기", "선생님께 알리러 가기", "사진 찍기"],
      answer: 4,
      clue: "I'll run to the staff room and let her know.",
      explanation:
        "벤치와 부원 연락, 카메라는 이미 해결되었으므로 여자는 교무실로 선생님께 알리러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 예린아, 동아리 사진 15분 뒤야.",
        "W: 다들 준비됐어? 뭐가 더 남았어?",
        "M: 벤치는 옮겼고 부원들한테도 다 말했어.",
        "W: 동아리방에서 카메라를 가져올까?",
        "M: 수호가 벌써 가져갔어. 밖에서 설치하고 있어.",
        "W: 그럼 뭐가 남았어?",
        "M: 선생님께 아무도 말씀을 안 드렸어. 선생님도 사진에 들어가시는데.",
        "W: 내가 교무실에 뛰어가서 말씀드릴게.",
        "M: 고마워. 나는 벤치 옆에서 애들이랑 기다릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 우산을 고르시오.",
      lines: [
        ["W", "Dongha, are these the umbrellas you were looking at?"],
        ["M", "Yes, these five. Mine broke last week."],
        ["W", "How much can you spend?"],
        ["M", "Twenty dollars at the most."],
        ["W", "All right, that takes out one of them."],
        ["M", "And I want a long one. The folding ones break too easily."],
        ["W", "Then one more is gone. Three are left."],
        ["M", "How heavy are they? My bag is already full."],
        ["W", "One is five hundred grams, the others are lighter."],
        ["M", "Then not that one. What about the handle?"],
        ["W", "Of the two left, only one has a curved handle."],
        ["M", "I'll take that one. I hang it on my desk."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'll take that one. I hang it on my desk.",
      explanation:
        "25달러인 ③, 접이식인 ①, 500그램인 ②를 뺀다. 남은 ④와 ⑤ 중 손잡이가 굽은 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "$12 / 접이식 / 300g / 곧은 손잡이" },
          { no: 2, label: "②", value: "$15 / 장우산 / 500g / 굽은 손잡이" },
          { no: 3, label: "③", value: "$25 / 장우산 / 350g / 굽은 손잡이" },
          { no: 4, label: "④", value: "$18 / 장우산 / 380g / 곧은 손잡이" },
          { no: 5, label: "⑤", value: "$20 / 장우산 / 400g / 굽은 손잡이" },
        ],
      },
      translation: [
        "W: 동하야, 네가 보던 우산이 이거야?",
        "M: 응, 이 다섯 개. 지난주에 내 우산이 부러졌어.",
        "W: 얼마까지 쓸 수 있어?",
        "M: 많아야 20달러.",
        "W: 그럼 하나가 빠지네.",
        "M: 그리고 장우산이 좋아. 접이식은 너무 잘 부러져.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 무게는 어때? 내 가방은 이미 꽉 찼어.",
        "W: 하나는 500그램이고 나머지는 더 가벼워.",
        "M: 그럼 그건 빼고. 손잡이는?",
        "W: 남은 둘 중 하나만 손잡이가 굽었어.",
        "M: 그걸로 할게. 책상에 걸어 두거든.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 공연을 보러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taemin, when should we go to the school concert?"],
        ["M", "They perform on the twentieth, twenty-first, and twenty-second."],
        ["W", "I have a family dinner on the twentieth."],
        ["M", "Then the twenty-first or the twenty-second."],
        ["W", "Isn't the twenty-second the day before the math test?"],
        ["M", "You're right. We should study that evening."],
        ["W", "So the twenty-first is the only one left."],
        ["M", "Let's go on the twenty-first. I'll get the tickets tomorrow."],
      ],
      choices: ["19일", "20일", "21일", "22일", "23일"],
      answer: 3,
      clue: "So the twenty-first is the only one left.",
      explanation:
        "20일은 가족 저녁 식사, 22일은 수학 시험 전날이어서 21일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 학교 공연 언제 보러 갈까?",
        "M: 20일, 21일, 22일에 공연해.",
        "W: 나 20일에 가족 저녁 식사가 있어.",
        "M: 그럼 21일이나 22일이네.",
        "W: 22일은 수학 시험 전날 아니야?",
        "M: 맞다. 그날 저녁엔 공부해야지.",
        "W: 그럼 21일만 남네.",
        "M: 21일에 가자. 내일 표 구할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyeon, did you go to the concert last weekend?"],
        ["W", "No, I went camping with my family on Saturday."],
        ["M", "Camping in this weather? Where did you go?"],
        ["W", "A campsite by a lake, about two hours from here."],
        ["M", "Wasn't it cold at night?"],
        ["W", "Very. We sat around the fire until eleven."],
        ["M", "Did you sleep in a tent?"],
        ["W", "Yes, and I woke up at six because of the birds."],
      ],
      choices: ["음악회 가기", "캠핑 가기", "영화 보기", "자전거 타기", "도서관 가기"],
      answer: 2,
      clue: "No, I went camping with my family on Saturday.",
      explanation:
        "여자는 지난 토요일에 가족과 호숫가로 캠핑을 갔다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "M: 채연아, 지난 주말에 음악회 갔어?",
        "W: 아니, 토요일에 가족이랑 캠핑 갔어.",
        "M: 이 날씨에 캠핑을? 어디로 갔는데?",
        "W: 여기서 두 시간쯤 걸리는 호숫가 야영장.",
        "M: 밤에 안 추웠어?",
        "W: 엄청. 11시까지 불 앞에 앉아 있었어.",
        "M: 텐트에서 잤어?",
        "W: 응, 새소리 때문에 6시에 깼어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good afternoon, students. This is the student council."],
        ["W", "The school bus route will change from next Monday."],
        ["W", "The road in front of the market is closed for repairs."],
        ["W", "So the bus will not stop at the market stop for three weeks."],
        ["W", "Students who use that stop should get off at the post office instead."],
        ["W", "It is a five-minute walk from there to the market."],
        ["W", "Please tell your classmates so nobody misses the bus."],
      ],
      choices: [
        "버스 요금이 오른 것을 알리려고",
        "통학 버스 노선이 바뀐 것을 알리려고",
        "도로 공사 봉사자를 모집하려고",
        "등교 시간을 앞당기려고",
        "버스 이용 예절을 당부하려고",
      ],
      answer: 2,
      clue: "So the bus will not stop at the market stop for three weeks.",
      explanation:
        "도로 공사로 통학 버스가 시장 정류장에 서지 않는다는 노선 변경을 알리는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학생회입니다.",
        "W: 다음 주 월요일부터 통학 버스 노선이 바뀝니다.",
        "W: 시장 앞 도로가 공사로 막힙니다.",
        "W: 그래서 3주 동안 버스가 시장 정류장에 서지 않습니다.",
        "W: 그 정류장을 이용하는 학생은 대신 우체국에서 내리세요.",
        "W: 거기서 시장까지는 걸어서 5분입니다.",
        "W: 버스를 놓치는 친구가 없도록 서로 알려 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the city ice rink. How can I help you?"],
        ["M", "Two tickets for this afternoon, please."],
        ["W", "Tickets are eleven dollars for adults and seven for students."],
        ["M", "Both of us are students. Here are our cards."],
        ["W", "Thank you. Do you need to rent skates?"],
        ["M", "Yes, two pairs. How much are they?"],
        ["W", "Skates are four dollars a pair."],
        ["M", "So twenty-two dollars in all."],
        ["W", "That's right. And today there's a three-dollar discount on rentals."],
        ["M", "Great. Here's my card."],
      ],
      choices: ["$14", "$17", "$19", "$22", "$25"],
      answer: 3,
      clue: "That's right. And today there's a three-dollar discount on rentals.",
      explanation:
        "학생 표 7달러씩 두 장이면 14달러, 스케이트 4달러씩 두 켤레면 8달러로 합계 22달러이다. 대여 할인 3달러를 빼면 19달러이므로 답은 ③이다.",
      translation: [
        "W: 시립 아이스링크입니다. 무엇을 도와드릴까요?",
        "M: 오늘 오후 표 두 장 주세요.",
        "W: 표는 성인 11달러, 학생 7달러입니다.",
        "M: 둘 다 학생이에요. 학생증 여기 있습니다.",
        "W: 감사합니다. 스케이트도 빌리시겠어요?",
        "M: 네, 두 켤레요. 얼마예요?",
        "W: 스케이트는 한 켤레에 4달러입니다.",
        "M: 그럼 다 해서 22달러네요.",
        "W: 맞습니다. 그리고 오늘은 대여품에 3달러 할인이 있습니다.",
        "M: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minjun, you've been rewriting that English diary every night."],
        ["M", "I have to hand in five entries by Friday."],
        ["W", "How many have you finished?"],
        ["M", "One. I keep starting over because of the spelling."],
        ["W", "You stop to check every word?"],
        ["M", "Almost every word. It takes me an hour for six lines."],
        ["W", "Then the checking is the problem, not the writing."],
        ["M", "Probably. But I don't want to hand in mistakes."],
        ["W", "Write the whole entry first, then check the spelling at the end."],
      ],
      choices: [
        "Then I'll write it all first tonight.",
        "My diary is about my summer holiday.",
        "I've already handed in three entries.",
        "English spelling is easy for me.",
        "You should write a diary too.",
      ],
      answer: 1,
      clue: "Write the whole entry first, then check the spelling at the end.",
      explanation:
        "먼저 다 쓰고 마지막에 철자를 확인하라는 조언을 들었으므로, 오늘 밤에 그렇게 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 민준아, 매일 밤 영어 일기를 다시 쓰고 있네.",
        "M: 금요일까지 다섯 편을 내야 해.",
        "W: 몇 편 썼어?",
        "M: 한 편. 철자 때문에 자꾸 처음부터 다시 써.",
        "W: 낱말마다 멈춰서 확인해?",
        "M: 거의 다. 여섯 줄 쓰는 데 한 시간 걸려.",
        "W: 그럼 문제는 쓰는 게 아니라 확인하는 거네.",
        "M: 아마도. 그래도 틀린 걸 내고 싶지 않아서.",
        "W: 먼저 한 편을 다 쓰고 마지막에 철자를 확인해 봐.",
        "M: 그럼 오늘 밤에는 다 쓰고 나서 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sora, you were late for the bus again this morning."],
        ["W", "I know. I always leave the house at eight."],
        ["M", "What time does the bus come?"],
        ["W", "Eight ten, and the stop is eight minutes away."],
        ["M", "That's only two minutes to spare."],
        ["W", "And I always have to look for my bus card first."],
        ["M", "Where do you keep it?"],
        ["W", "Somewhere in my bag. It's different every day."],
        ["M", "Put it in the same pocket every time you get home."],
      ],
      choices: [
        "The bus is often five minutes late.",
        "Then I'll keep it in the front pocket.",
        "I walk to school on Fridays.",
        "My bag has three pockets.",
        "You should leave home earlier too.",
      ],
      answer: 2,
      clue: "Put it in the same pocket every time you get home.",
      explanation:
        "집에 오면 늘 같은 주머니에 넣어 두라는 조언을 들었으므로, 앞주머니에 넣어 두겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 소라야, 오늘 아침에도 버스에 늦었네.",
        "W: 알아. 늘 8시에 집에서 나와.",
        "M: 버스가 몇 시에 오는데?",
        "W: 8시 10분, 정류장까지는 8분 걸려.",
        "M: 그럼 2분밖에 안 남잖아.",
        "W: 게다가 늘 버스 카드부터 찾아야 해.",
        "M: 어디에 두는데?",
        "W: 가방 어딘가에. 날마다 달라.",
        "M: 집에 오면 매번 같은 주머니에 넣어 둬.",
        "W: 그럼 앞주머니에 넣어 둘게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Hyunwoo, how is the class newspaper going?"],
        ["M", "Slowly. I'm still waiting for two articles."],
        ["W", "When did you ask for them?"],
        ["M", "Three weeks ago, at the first meeting."],
        ["W", "Did you give them a date?"],
        ["M", "I just said 'as soon as you can'."],
        ["W", "That's not a date. It could mean next month."],
        ["M", "I thought they would understand."],
        ["W", "Ask them again tonight and give them a real deadline."],
      ],
      choices: [
        "The newspaper comes out every month.",
        "I wrote three articles myself.",
        "Our class has thirty students.",
        "Then I'll message them with a date tonight.",
        "I'd rather do it all alone.",
      ],
      answer: 4,
      clue: "Ask them again tonight and give them a real deadline.",
      explanation:
        "오늘 밤에 다시 부탁하면서 정확한 마감일을 주라는 조언을 들었으므로, 날짜를 정해 연락하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 현우야, 학급 신문은 잘돼 가?",
        "M: 천천히. 기사 두 편을 아직 기다리고 있어.",
        "W: 언제 부탁했는데?",
        "M: 3주 전, 첫 모임 때.",
        "W: 날짜를 정해 줬어?",
        "M: 그냥 '될 수 있는 대로 빨리'라고만 했어.",
        "W: 그건 날짜가 아니잖아. 다음 달이 될 수도 있어.",
        "M: 알아들을 줄 알았어.",
        "W: 오늘 밤에 다시 부탁하면서 진짜 마감일을 줘.",
        "M: 그럼 오늘 밤에 날짜를 적어서 연락할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiwon이 Minseo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Jiwon : ________________",
      lines: [
        ["W", "Jiwon and Minseo are in the same cooking club."],
        ["W", "They are making soup together for the school festival."],
        ["W", "Minseo is very good at cutting vegetables quickly and neatly."],
        ["W", "However, she puts every vegetable into the pot at the same time."],
        ["W", "Because of that, the carrots are still hard when the leaves are already soft."],
        ["W", "Jiwon does not want to say that her cooking is bad."],
        ["W", "She wants to suggest putting the hard vegetables in first."],
        ["W", "In this situation, what would Jiwon most likely say to Minseo?"],
      ],
      choices: [
        "Let's make a different dish this time.",
        "You should cut the vegetables smaller.",
        "Let's put the carrots in first and the leaves later.",
        "I'll cook the soup by myself today.",
        "We don't need any vegetables in the soup.",
      ],
      answer: 3,
      clue: "She wants to suggest putting the hard vegetables in first.",
      explanation:
        "지원이는 민서의 요리를 깎아내리지 않으면서, 단단한 채소를 먼저 넣자고 말하려 한다. 따라서 ③이 가장 적절하다.",
      translation: [
        "W: 지원과 민서는 같은 요리 동아리입니다.",
        "W: 두 사람은 학교 축제에 낼 수프를 함께 만들고 있습니다.",
        "W: 민서는 채소를 빠르고 깔끔하게 아주 잘 썹니다.",
        "W: 그런데 모든 채소를 한꺼번에 냄비에 넣습니다.",
        "W: 그래서 잎채소가 다 물러질 때까지도 당근은 여전히 단단합니다.",
        "W: 지원은 민서의 요리가 나쁘다고 말하고 싶지는 않습니다.",
        "W: 다만 단단한 채소를 먼저 넣자고 제안하고 싶습니다.",
        "W: 이런 상황에서 지원이 민서에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
