/** 중2 듣기 45회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 45회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 고를 탁상시계를 고르시오.",
      lines: [
        ["W", "Woojin, are you buying a clock for your desk?"],
        ["M", "Yes, my old one stopped last week."],
        ["W", "This square one shows the numbers in light."],
        ["M", "I'd rather have a round face with hands."],
        ["W", "Do you want one with an alarm bell on top?"],
        ["M", "No bell. The sound wakes up my brother too."],
        ["W", "What about the little stand at the back?"],
        ["M", "Yes, a folding stand so it leans on the desk."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'd rather have a round face with hands. / Yes, a folding stand so it leans on the desk.",
      explanation:
        "바늘이 있는 둥근 시계에 종은 없고 뒤에 접이식 받침이 있는 것이다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five small desk clocks side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a SQUARE digital clock with a flat base, no bell. " +
          "② a ROUND clock with hands and a BELL on top, standing on small feet. " +
          "③ a SQUARE digital clock with a BELL on top. " +
          "④ a ROUND clock with hands, no bell, leaning back on a FOLDING STAND behind it. " +
          "⑤ a ROUND clock with hands and a BELL on top, leaning back on a FOLDING STAND.",
      },
      translation: [
        "W: 우진아, 책상에 놓을 시계 사는 거야?",
        "M: 응, 지난주에 쓰던 게 멈췄어.",
        "W: 이 네모난 건 숫자가 빛으로 나와.",
        "M: 나는 바늘 있는 둥근 게 더 좋아.",
        "W: 위에 알람 종이 달린 건 어때?",
        "M: 종은 안 돼. 그 소리에 동생까지 깨.",
        "W: 뒤에 있는 작은 받침은?",
        "M: 응, 책상에 기대 놓게 접이식 받침이 있는 걸로.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 텃밭 활동에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dain, what does the garden club do this term?"],
        ["W", "We take care of the beds behind the gym."],
        ["M", "How often do you meet there?"],
        ["W", "Twice a week, on Tuesday and Friday afternoons."],
        ["M", "What are you growing at the moment?"],
        ["W", "Lettuce, green onions and small pumpkins."],
        ["M", "Who teaches you how to plant them?"],
        ["W", "A farmer from the village comes every month."],
        ["M", "What happens to the vegetables in the end?"],
        ["W", "We share them with the school kitchen."],
      ],
      choices: ["활동하는 곳", "모이는 요일", "기르는 작물", "수확물의 쓰임", "동아리 회원 수"],
      answer: 5,
      clue: "We take care of the beds behind the gym.",
      explanation:
        "장소, 요일, 작물, 수확물 쓰임은 말했지만 회원 수는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 이번 학기에 텃밭 동아리는 뭘 해?",
        "W: 체육관 뒤 텃밭을 돌봐.",
        "M: 얼마나 자주 모여?",
        "W: 일주일에 두 번, 화요일이랑 금요일 오후에.",
        "M: 지금은 뭘 기르고 있어?",
        "W: 상추, 파, 작은 호박.",
        "M: 심는 법은 누가 가르쳐 줘?",
        "W: 마을 농부 한 분이 매달 오셔.",
        "M: 채소는 결국 어떻게 돼?",
        "W: 학교 급식실에 나눠 드려.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Yubin. This is Daehyun from next door."],
        ["W", "Hi. Is everything all right?"],
        ["M", "My family is away until Sunday evening."],
        ["W", "I saw your car leave this morning."],
        ["M", "We left in a hurry for my grandfather."],
        ["W", "I hope he gets better soon."],
        ["M", "Our cat is still inside the apartment."],
        ["W", "She must be waiting for her food."],
        ["M", "I'm calling to ask you to feed her."],
      ],
      choices: [
        "고양이를 돌봐 달라고 부탁하려고",
        "이사를 알리려고",
        "주차 자리를 부탁하려고",
        "감사를 전하려고",
        "약속을 미루려고",
      ],
      answer: 1,
      clue: "I'm calling to ask you to feed her.",
      explanation:
        "남자는 집에 있는 고양이 밥을 부탁하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕하세요, 유빈 씨. 옆집 대현입니다.",
        "W: 안녕하세요. 별일 없으세요?",
        "M: 저희 가족이 일요일 저녁까지 집을 비워요.",
        "W: 아침에 차 나가는 걸 봤어요.",
        "M: 할아버지 일로 급하게 떠났어요.",
        "W: 빨리 나으시면 좋겠네요.",
        "M: 고양이가 아직 집 안에 있어요.",
        "W: 밥을 기다리고 있겠네요.",
        "M: 고양이 밥 좀 부탁드리려고 전화했어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 출발할 시각을 고르시오.",
      lines: [
        ["W", "Hyunsu, what time does the concert begin?"],
        ["M", "The doors open at six thirty in the evening."],
        ["W", "How long does it take to get there?"],
        ["M", "Forty minutes by subway from our station."],
        ["W", "Then we should leave before six o'clock."],
        ["M", "I also want to buy a program book."],
        ["W", "That means we need extra time inside."],
        ["M", "Let's leave home at five thirty."],
        ["W", "Five thirty it is. I'll be ready."],
      ],
      choices: ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
      answer: 2,
      clue: "Let's leave home at five thirty.",
      explanation:
        "이동 시간과 책자 구입 시간을 감안해 5시 30분에 집을 나서기로 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 현수야, 공연 몇 시에 시작해?",
        "M: 저녁 6시 30분에 문을 열어.",
        "W: 거기까지 얼마나 걸려?",
        "M: 우리 역에서 지하철로 40분.",
        "W: 그럼 6시 전에는 나가야겠네.",
        "M: 나는 안내 책자도 사고 싶어.",
        "W: 그럼 안에서 시간이 더 필요하겠다.",
        "M: 5시 30분에 집에서 나가자.",
        "W: 5시 30분으로 하자. 준비해 둘게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sujeong, you've been quiet since lunch time."],
        ["W", "I lost my little brother's toy at the park."],
        ["M", "The wooden train he carries everywhere?"],
        ["W", "He gave it to me to hold for a minute."],
        ["M", "Did you look under the benches?"],
        ["W", "I searched the whole park twice."],
        ["M", "He will understand if you explain."],
        ["W", "I feel terrible about breaking his trust."],
      ],
      choices: ["sorry", "excited", "proud", "bored", "surprised"],
      answer: 1,
      clue: "I feel terrible about breaking his trust.",
      explanation:
        "동생의 장난감을 잃어버려 미안해하고 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 수정아, 점심시간부터 계속 조용하네.",
        "W: 공원에서 동생 장난감을 잃어버렸어.",
        "M: 걔가 늘 들고 다니는 나무 기차?",
        "W: 잠깐 들고 있으라고 나한테 준 거였어.",
        "M: 의자 밑은 봤어?",
        "W: 공원 전체를 두 번 뒤졌어.",
        "M: 설명하면 이해해 줄 거야.",
        "W: 동생 믿음을 저버린 것 같아서 너무 미안해.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Could you pass me the salt?"],
        ["W", "Here it is."],
        ["ANN", "Number two."],
        ["M", "How was your meal?"],
        ["W", "The soup was delicious."],
        ["ANN", "Number three."],
        ["M", "Are you ready to order?"],
        ["W", "Give us five more minutes."],
        ["ANN", "Number four."],
        ["M", "Can we sit by the window?"],
        ["W", "That table is free now."],
        ["ANN", "Number five."],
        ["M", "Is this your first time here?"],
        ["W", "No, I came last summer."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Are you ready to order?",
      explanation:
        "그림은 종업원이 주문을 받으러 왔지만 손님이 차림표를 보고 있는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small restaurant, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A waiter stands beside a table holding a notepad and a pen, looking at two seated customers. " +
          "The two customers are still holding open menus in front of their faces and one raises a hand with fingers spread. " +
          "Plates, glasses and a window are drawn simply in the background.",
      },
      translation: [
        "① M: 소금 좀 건네주시겠어요? / W: 여기 있습니다.",
        "② M: 식사는 어떠셨어요? / W: 국이 맛있었어요.",
        "③ M: 주문하시겠어요? / W: 5분만 더 주세요.",
        "④ M: 창가에 앉아도 되나요? / W: 저 자리 지금 비었습니다.",
        "⑤ M: 여기 처음이세요? / W: 아니요, 지난여름에 왔었어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kyuhyun, you fixed the club computer last month."],
        ["M", "It only needed a new cable at the back."],
        ["W", "Our classroom projector is acting strangely now."],
        ["M", "Does it turn on at all?"],
        ["W", "The light comes on but the screen stays blue."],
        ["M", "That usually means a loose connection."],
        ["W", "We have a presentation tomorrow morning."],
        ["M", "Tonight I'm free after seven."],
        ["W", "Could you look at the projector for us?"],
        ["M", "I'll come by right after dinner."],
      ],
      choices: [
        "발표를 대신해 주기",
        "컴퓨터를 빌려주기",
        "빔 프로젝터를 봐 주기",
        "자료를 출력해 주기",
        "교실을 청소해 주기",
      ],
      answer: 3,
      clue: "Could you look at the projector for us?",
      explanation:
        "여자는 교실 프로젝터를 봐 달라고 부탁했다. 따라서 답은 ③이다.",
      translation: [
        "W: 규현아, 지난달에 동아리 컴퓨터 고쳤잖아.",
        "M: 뒤에 선만 새로 끼우면 됐어.",
        "W: 이번엔 우리 교실 프로젝터가 이상해.",
        "M: 켜지기는 해?",
        "W: 불은 들어오는데 화면이 파랗기만 해.",
        "M: 보통 연결이 헐거울 때 그래.",
        "W: 내일 아침에 발표가 있어.",
        "M: 오늘 밤 일곱 시 이후에는 시간 돼.",
        "W: 프로젝터 좀 봐 줄 수 있어?",
        "M: 저녁 먹고 바로 들를게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 마라톤 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The school marathon takes place next month. " +
            "The race starts at the front gate at nine. " +
            "Everyone runs five kilometers around the river path. " +
            "Water will be handed out at two points along the way. " +
            "Wear comfortable running shoes and light clothes. " +
            "Write your name on the list by this Friday.",
        ],
      ],
      choices: ["출발 장소", "달리는 거리", "물을 주는 곳", "신청 기한", "우승자 상품"],
      answer: 5,
      clue: "The race starts at the front gate at nine.",
      explanation:
        "출발 장소, 거리, 급수 지점, 신청 기한은 말했지만 상품은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 다음 달에 교내 마라톤 대회가 열립니다. 아홉 시에 정문에서 출발합니다. 모두 강변 길을 따라 5킬로미터를 달립니다. 도중에 두 곳에서 물을 나눠 드립니다. 편한 운동화와 가벼운 옷을 입으세요. 이번 주 금요일까지 명단에 이름을 적어 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You wear this on your feet before you go outside. " +
            "It has laces that you tie into a bow. " +
            "Runners choose light ones with soft soles. " +
            "You take them off at the door of a Korean house. " +
            "A pair that is too small will hurt your toes.",
        ],
      ],
      choices: ["모자", "장갑", "신발", "목도리", "양말"],
      answer: 3,
      clue: "It has laces that you tie into a bow.",
      explanation:
        "끈을 묶어 발에 신고 현관에서 벗는 것은 신발이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 밖에 나가기 전에 발에 신습니다. 나비 모양으로 묶는 끈이 달려 있습니다. 달리기를 하는 사람들은 바닥이 푹신하고 가벼운 것을 고릅니다. 한국 집에서는 현관에서 이것을 벗습니다. 너무 작은 것은 발가락을 아프게 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "When is your birthday?"],
        ["M", "The fifth of June."],
        ["ANN", "Number two."],
        ["W", "May I open the window?"],
        ["M", "Go ahead, it's hot in here."],
        ["ANN", "Number three."],
        ["W", "Who is the tall boy over there?"],
        ["M", "He's my cousin."],
        ["ANN", "Number four."],
        ["W", "How was your weekend?"],
        ["M", "I have two dogs at home."],
        ["ANN", "Number five."],
        ["W", "Do you need any help?"],
        ["M", "Yes, this box is heavy."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "How was your weekend?",
      explanation:
        "주말이 어땠는지 묻는 말에 개가 두 마리 있다고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 생일이 언제야? / M: 6월 5일이야.",
        "② W: 창문 열어도 돼? / M: 열어, 여기 덥다.",
        "③ W: 저기 키 큰 남자애는 누구야? / M: 내 사촌이야.",
        "④ W: 주말 어땠어? / M: 나는 집에 개가 두 마리 있어.",
        "⑤ W: 도와줄까? / M: 응, 이 상자 무거워.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, the science experiment starts in five minutes."],
        ["M", "I brought the notebook and the worksheet."],
        ["W", "Did anyone take the safety glasses from the cabinet?"],
        ["M", "I forgot about those completely."],
        ["W", "The teacher won't let us start without them."],
        ["M", "The cabinet is at the back of the lab."],
        ["W", "I'll set the beakers on our table."],
        ["M", "I'll get the safety glasses right now."],
      ],
      choices: [
        "공책을 챙기기",
        "비커를 놓기",
        "보안경을 가져오기",
        "선생님을 부르기",
        "실험을 시작하기",
      ],
      answer: 3,
      clue: "I'll get the safety glasses right now.",
      explanation:
        "남자는 지금 바로 보안경을 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 상우야, 과학 실험이 5분 뒤에 시작해.",
        "M: 공책이랑 실험지는 가져왔어.",
        "W: 보관함에서 보안경은 누가 가져왔어?",
        "M: 그건 완전히 잊었어.",
        "W: 선생님이 보안경 없이는 시작 못 하게 하셔.",
        "M: 보관함은 실험실 뒤쪽에 있어.",
        "W: 나는 우리 탁자에 비커를 놓을게.",
        "M: 내가 지금 보안경 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 영화를 고르시오.",
      lines: [
        ["M", "Chaeun, which movie should we watch this evening?"],
        ["W", "Five films are showing at our theater."],
        ["M", "We have to be home by nine o'clock."],
        ["W", "So anything longer than two hours is out."],
        ["M", "I don't want to watch a horror film."],
        ["W", "One of them is a horror film, then."],
        ["M", "And the ticket should be under ten thousand won."],
        ["W", "Then only one movie fits everything."],
        ["M", "I'll book the seats on my phone."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "We have to be home by nine o'clock.",
      explanation:
        "2시간 이내, 공포물이 아니고 표값 1만 원 미만인 영화는 ②이다. 따라서 답은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Length: 145 min / Genre: Comedy / Ticket: 9,000 won" },
          { no: 2, label: "②", value: "Length: 105 min / Genre: Comedy / Ticket: 9,500 won" },
          { no: 3, label: "③", value: "Length: 110 min / Genre: Horror / Ticket: 8,000 won" },
          { no: 4, label: "④", value: "Length: 95 min / Genre: Animation / Ticket: 12,000 won" },
          { no: 5, label: "⑤", value: "Length: 130 min / Genre: Animation / Ticket: 9,000 won" },
        ],
      },
      translation: [
        "M: 채은아, 오늘 저녁에 무슨 영화 볼까?",
        "W: 우리 극장에서 다섯 편 하고 있어.",
        "M: 아홉 시까지는 집에 가야 해.",
        "W: 그럼 두 시간 넘는 건 빼야겠네.",
        "M: 공포 영화는 보고 싶지 않아.",
        "W: 그럼 그중 하나는 공포물이니까 빠져.",
        "M: 그리고 표는 1만 원 미만이어야 해.",
        "W: 그럼 다 맞는 건 한 편뿐이야.",
        "M: 내가 휴대폰으로 자리 예매할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 이사를 도울 날짜를 고르시오.",
      lines: [
        ["W", "Junyoung, when is Mr. Kim moving out?"],
        ["M", "He said sometime around the end of the month."],
        ["W", "Did he give us any exact dates?"],
        ["M", "The twenty-third, twenty-fifth or twenty-seventh."],
        ["W", "We have a school trip on the twenty-third."],
        ["M", "And the twenty-seventh is my mother's birthday."],
        ["W", "Then the twenty-fifth is the only day we can help."],
        ["M", "He wants us there from nine in the morning."],
        ["W", "I'll tell him we'll come on the twenty-fifth."],
      ],
      choices: ["the 23rd", "the 25th", "the 27th", "the 21st", "the 29th"],
      answer: 2,
      clue: "Then the twenty-fifth is the only day we can help.",
      explanation:
        "23일은 수학여행, 27일은 어머니 생신이어서 25일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 준영아, 김 선생님 언제 이사 가셔?",
        "M: 이번 달 말쯤이라고 하셨어.",
        "W: 정확한 날짜는 말씀하셨어?",
        "M: 23일, 25일, 27일 중에.",
        "W: 23일에는 수학여행이 있어.",
        "M: 27일은 우리 어머니 생신이고.",
        "W: 그럼 도울 수 있는 날은 25일뿐이네.",
        "M: 아침 아홉 시부터 와 달라고 하셨어.",
        "W: 25일에 간다고 말씀드릴게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, you weren't at the study room yesterday."],
        ["W", "I went to the hospital with my grandmother."],
        ["M", "Is she not feeling well these days?"],
        ["W", "She had her eyes checked for new glasses."],
        ["M", "Did you stay with her the whole time?"],
        ["W", "I read the forms and wrote the answers for her."],
        ["M", "That must have taken a few hours."],
        ["W", "From two until almost five."],
        ["M", "Did you get her new glasses that day?"],
        ["W", "They will be ready next Tuesday."],
      ],
      choices: [
        "할머니와 병원에 갔다",
        "안경을 샀다",
        "공부방에 갔다",
        "친구를 만났다",
        "집에서 쉬었다",
      ],
      answer: 1,
      clue: "I went to the hospital with my grandmother.",
      explanation:
        "여자는 어제 할머니와 병원에 갔다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 어제 공부방에 없었네.",
        "W: 할머니랑 병원에 갔어.",
        "M: 요즘 편찮으셔?",
        "W: 새 안경 맞추려고 눈 검사를 받으셨어.",
        "M: 내내 같이 있었어?",
        "W: 서류를 읽어 드리고 답을 대신 적어 드렸어.",
        "M: 몇 시간 걸렸겠다.",
        "W: 두 시부터 거의 다섯 시까지.",
        "M: 그날 새 안경도 받으셨어?",
        "W: 다음 주 화요일에 나온대.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, please. This is the school office speaking. " +
            "Strong winds are expected this afternoon in our whole area. " +
            "All outdoor club activities are cancelled for today. " +
            "Indoor clubs may meet in their usual rooms as planned. " +
            "Please close the classroom windows tightly before you leave. " +
            "Take your umbrellas and bags home with you today. " +
            "Go straight home as soon as your classes end. " +
            "Do not stay on the playground after school hours.",
        ],
      ],
      choices: [
        "동아리를 모집하려고",
        "야외 활동 취소를 알리려고",
        "분실물을 찾으려고",
        "청소 시간을 바꾸려고",
        "체육 대회를 안내하려고",
      ],
      answer: 2,
      clue: "All outdoor club activities are cancelled for today.",
      explanation:
        "강풍 때문에 야외 활동이 취소되었음을 알리는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 알려 드립니다. 학교 행정실입니다. 오늘 오후 우리 지역 전체에 강한 바람이 예상됩니다. 오늘 야외 동아리 활동은 모두 취소되었습니다. 실내 동아리는 예정대로 평소 교실에서 모여도 됩니다. 나가기 전에 교실 창문을 꼭 닫아 주세요. 우산과 가방은 오늘 집으로 가져가세요. 수업이 끝나면 바로 집으로 가세요. 방과 후에 운동장에 남아 있지 마세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What can I get for you today?"],
        ["W", "Three cups of hot chocolate, please."],
        ["M", "Each cup is three dollars."],
        ["W", "Do you have anything to eat as well?"],
        ["M", "Cookies are one dollar each today."],
        ["W", "I'll take two cookies then."],
        ["M", "Would you like them in a box?"],
        ["W", "A paper bag is fine, thank you."],
        ["M", "The bag costs nothing extra."],
        ["W", "Great. Here you are."],
      ],
      choices: ["$9", "$10", "$11", "$12", "$13"],
      answer: 3,
      clue: "Each cup is three dollars.",
      explanation:
        "핫초코 세 잔 9달러와 쿠키 두 개 2달러를 더하면 11달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 오늘은 뭘 드릴까요?",
        "W: 따뜻한 코코아 세 잔 주세요.",
        "M: 한 잔에 3달러입니다.",
        "W: 먹을 것도 있나요?",
        "M: 오늘 쿠키는 하나에 1달러입니다.",
        "W: 그럼 쿠키 두 개 주세요.",
        "M: 상자에 넣어 드릴까요?",
        "W: 종이봉투면 됩니다, 감사합니다.",
        "M: 봉투는 따로 돈을 받지 않습니다.",
        "W: 좋네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Haeun, you always finish your homework before dinner."],
        ["W", "I start the moment I get home."],
        ["M", "Don't you want to rest for a while first?"],
        ["W", "Resting after work feels much better."],
        ["M", "I usually lie down and then it's ten o'clock."],
        ["W", "The first ten minutes decide the whole evening."],
        ["M", "That sounds true but hard to do."],
        ["W", "Put your bag on the desk, not the floor."],
        ["M", "What should I do on days with no homework?"],
      ],
      choices: [
        "Sleep all evening long.",
        "Read something for yourself.",
        "Never go home at all.",
        "Do tomorrow's homework twice.",
        "Throw your bag away.",
      ],
      answer: 2,
      clue: "What should I do on days with no homework?",
      explanation:
        "숙제가 없는 날 무엇을 할지 물었으므로, 스스로 읽을 것을 읽으라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 하은아, 너는 늘 저녁 먹기 전에 숙제를 끝내더라.",
        "W: 집에 오자마자 시작해.",
        "M: 먼저 좀 쉬고 싶지 않아?",
        "W: 할 일 끝내고 쉬는 게 훨씬 좋아.",
        "M: 나는 보통 누웠다가 정신 차리면 열 시야.",
        "W: 처음 10분이 저녁 전체를 정해.",
        "M: 맞는 말인데 하기는 어렵네.",
        "W: 가방을 바닥 말고 책상에 올려 둬.",
        "M: 숙제 없는 날은 뭘 하면 좋을까?",
        "W: 네가 읽고 싶은 걸 읽어.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jiwon, I heard you started running in the morning."],
        ["M", "Since the first week of September, every weekday."],
        ["W", "How far do you run before school?"],
        ["M", "Three kilometers along the river path."],
        ["W", "Isn't it dark when you start out?"],
        ["M", "The sun comes up while I'm running."],
        ["W", "Do you run alone or with someone?"],
        ["M", "My father comes with me twice a week."],
        ["W", "Has it changed anything for you?"],
        ["M", "I fall asleep much faster at night."],
        ["W", "Could I join you tomorrow morning?"],
      ],
      choices: [
        "Sure, be ready at six.",
        "I stopped running last month.",
        "There is no river here.",
        "You can't run at all.",
        "I run only on weekends.",
      ],
      answer: 1,
      clue: "Could I join you tomorrow morning?",
      explanation:
        "내일 함께 뛰어도 되는지 물었으므로, 여섯 시에 준비하라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 지원아, 아침에 달리기 시작했다며.",
        "M: 9월 첫째 주부터 평일마다.",
        "W: 학교 가기 전에 얼마나 뛰어?",
        "M: 강변 길로 3킬로미터.",
        "W: 출발할 때 어둡지 않아?",
        "M: 뛰는 동안 해가 떠.",
        "W: 혼자 뛰어, 누구랑 같이 뛰어?",
        "M: 일주일에 두 번은 아버지가 같이 가셔.",
        "W: 뭔가 달라진 게 있어?",
        "M: 밤에 훨씬 빨리 잠들어.",
        "W: 내일 아침에 나도 같이 가도 돼?",
        "M: 그럼, 여섯 시에 준비해.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Areum, how is your art project going this week?"],
        ["M", "You said you were painting the school garden."],
        ["W", "The colors come out muddy every single time."],
        ["M", "How many colors do you mix together?"],
        ["W", "Sometimes four or five at once."],
        ["M", "That's probably why they turn gray."],
        ["W", "I want the green to look fresh and bright."],
        ["M", "Two colors usually make a cleaner green."],
        ["W", "Nobody explained that to me before."],
        ["M", "Why don't you try mixing only blue and yellow?"],
      ],
      choices: [
        "I'll try that tomorrow.",
        "I don't have any paint.",
        "Green is not a color.",
        "I'll mix eight colors.",
        "I finished the painting.",
      ],
      answer: 1,
      clue: "Why don't you try mixing only blue and yellow?",
      explanation:
        "파랑과 노랑만 섞어 보라는 제안이므로, 내일 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 아름아, 이번 주 미술 과제는 잘돼 가?",
        "M: 학교 화단을 그린다고 했잖아.",
        "W: 색이 매번 탁하게 나와.",
        "M: 몇 가지 색을 섞어?",
        "W: 어떤 때는 한꺼번에 네다섯 가지.",
        "M: 그래서 회색처럼 되는 걸 거야.",
        "W: 초록이 산뜻하고 밝게 나왔으면 좋겠어.",
        "M: 두 가지만 섞으면 보통 더 맑은 초록이 나와.",
        "W: 아무도 그걸 알려 준 적이 없어.",
        "M: 파랑이랑 노랑만 섞어 보는 건 어때?",
        "W: 내일 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nara가 Gunwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Nara : ________________",
      lines: [
        [
          "W",
          "Nara and Gunwoo are cleaning up after the club meeting. " +
            "Gunwoo is about to throw plastic bottles into the paper bin. " +
            "Nara knows their school separates paper and plastic strictly. " +
            "The cleaning teacher checks every bin before she locks the room. " +
            "She wants him to put the bottles in the right bin instead. " +
            "In this situation, what would Nara most likely say to Gunwoo?",
        ],
      ],
      choices: [
        "Those go in the plastic bin.",
        "We don't have to clean up.",
        "Throw everything away now.",
        "The meeting starts at five.",
        "Paper is heavier than plastic.",
      ],
      answer: 1,
      clue: "She wants him to put the bottles in the right bin instead.",
      explanation:
        "플라스틱 병을 종이통에 버리려 하므로, 플라스틱 통에 넣으라는 ①이 가장 적절하다.",
      translation: [
        "W: 나라와 건우는 동아리 모임이 끝난 뒤 정리를 하고 있습니다. 건우는 플라스틱 병을 종이 수거함에 버리려고 합니다. 나라는 학교가 종이와 플라스틱을 엄격히 나눈다는 것을 압니다. 청소 선생님은 방을 잠그기 전에 모든 수거함을 확인하십니다. 그녀는 건우가 병을 맞는 통에 넣기를 바랍니다. 이런 상황에서 나라가 건우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
