/** 중2 듣기 51회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 51회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 고를 벽시계를 고르시오.",
      lines: [
        ["M", "Nayoung, which clock are you putting in the club room?"],
        ["W", "Something plain that everyone can read fast."],
        ["M", "This square one has numbers only at twelve and six."],
        ["W", "I want all twelve numbers printed on it."],
        ["M", "Do you want a round face or a square one?"],
        ["W", "Round, like the one in our classroom."],
        ["M", "Should it have a second hand as well?"],
        ["W", "No second hand. The ticking bothers people."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I want all twelve numbers printed on it. / No second hand. The ticking bothers people.",
      explanation:
        "둥근 시계에 열두 숫자가 다 있고 초침은 없는 것이다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five wall clocks side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a SQUARE clock face with tick marks only at the top and bottom positions, two hands. " +
          "② a ROUND clock face with tick marks only at the top and bottom positions, two hands. " +
          "③ a SQUARE clock face with twelve evenly spaced tick marks and THREE hands including a thin long one. " +
          "④ a ROUND clock face with twelve evenly spaced tick marks and only TWO hands. " +
          "⑤ a ROUND clock face with twelve evenly spaced tick marks and THREE hands including a thin long one.",
      },
      translation: [
        "M: 나영아, 동아리방에 어떤 시계를 달 거야?",
        "W: 다들 빨리 읽을 수 있는 단순한 걸로.",
        "M: 이 네모난 건 12시랑 6시에만 숫자가 있어.",
        "W: 나는 열두 숫자가 다 찍힌 게 좋아.",
        "M: 둥근 판으로 할래, 네모난 판으로 할래?",
        "W: 둥근 걸로. 우리 교실에 있는 것처럼.",
        "M: 초침도 있어야 해?",
        "W: 초침은 안 돼. 째깍 소리가 거슬려.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 영화 상영회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, is the school movie night happening again?"],
        ["M", "Yes, on the last Friday of this month."],
        ["W", "Where do they show the film?"],
        ["M", "In the main hall, right after school."],
        ["W", "What film are they showing this time?"],
        ["M", "A documentary about sea animals."],
        ["W", "How long does the whole thing take?"],
        ["M", "About ninety minutes with the talk afterwards."],
        ["W", "Can we bring something to eat?"],
        ["M", "Only water is allowed in the hall."],
      ],
      choices: ["상영하는 날", "상영하는 곳", "상영하는 영화", "걸리는 시간", "관람료"],
      answer: 5,
      clue: "Yes, on the last Friday of this month.",
      explanation:
        "날짜, 장소, 영화, 시간은 말했지만 관람료는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 학교 영화의 밤 또 해?",
        "M: 응, 이번 달 마지막 금요일에.",
        "W: 어디서 상영해?",
        "M: 대강당에서, 수업 끝나고 바로.",
        "W: 이번에는 무슨 영화를 틀어?",
        "M: 바다 동물에 관한 기록 영화.",
        "W: 전부 얼마나 걸려?",
        "M: 끝나고 하는 이야기까지 90분쯤.",
        "W: 먹을 걸 가져가도 돼?",
        "M: 강당에는 물만 가져갈 수 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Come in, Ssangwoo. You're early today."],
        ["M", "I wanted to catch you before the bell."],
        ["W", "Is it about the science fair project?"],
        ["M", "It's about the field trip next Thursday."],
        ["W", "The one to the water treatment plant?"],
        ["M", "Yes, and I signed up two weeks ago."],
        ["W", "Has something come up since then?"],
        ["M", "My grandmother is having surgery that morning."],
        ["W", "I'm sorry to hear that."],
        ["M", "I came to tell you I can't go on the trip."],
      ],
      choices: [
        "현장 학습에 못 간다고 알리려고",
        "현장 학습을 신청하려고",
        "숙제를 내려고",
        "상담을 받으려고",
        "물건을 빌리려고",
      ],
      answer: 1,
      clue: "I came to tell you I can't go on the trip.",
      explanation:
        "남자는 현장 학습에 갈 수 없다고 알리러 왔다. 따라서 답은 ①이다.",
      translation: [
        "W: 들어와, 쌍우야. 오늘 일찍 왔네.",
        "M: 종 치기 전에 뵙고 싶었어요.",
        "W: 과학 전시회 과제 때문이니?",
        "M: 다음 주 목요일 현장 학습 때문이에요.",
        "W: 정수장에 가는 거 말이니?",
        "M: 네, 두 주 전에 신청했어요.",
        "W: 그 뒤로 무슨 일이 생겼구나.",
        "M: 그날 아침에 할머니가 수술을 받으세요.",
        "W: 저런, 안됐구나.",
        "M: 현장 학습에 못 간다고 말씀드리러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["M", "Jiwon, when does the exhibition close today?"],
        ["W", "The doors shut at six in the evening."],
        ["M", "How long do we need inside?"],
        ["W", "At least an hour to see every room."],
        ["M", "Then four thirty would be too late."],
        ["W", "My art class finishes at four fifteen."],
        ["M", "So four o'clock doesn't work for you."],
        ["W", "Let's meet at four thirty at the entrance."],
        ["M", "Four thirty. I'll buy the tickets first."],
      ],
      choices: ["4:00 p.m.", "4:15 p.m.", "4:30 p.m.", "5:00 p.m.", "6:00 p.m."],
      answer: 3,
      clue: "Let's meet at four thirty at the entrance.",
      explanation:
        "여자의 미술 수업이 4시 15분에 끝나 4시 30분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 지원아, 오늘 전시 몇 시에 닫아?",
        "W: 저녁 여섯 시에 문을 닫아.",
        "M: 안에서 얼마나 필요해?",
        "W: 방을 다 보려면 적어도 한 시간.",
        "M: 그럼 4시 30분은 너무 늦겠네.",
        "W: 내 미술 수업이 4시 15분에 끝나.",
        "M: 그럼 4시는 너한테 안 되겠다.",
        "W: 4시 30분에 입구에서 만나자.",
        "M: 4시 30분. 표는 내가 먼저 사 둘게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sohyun, you look like you didn't sleep."],
        ["W", "My little brother has a high fever."],
        ["M", "Did your parents take him to the hospital?"],
        ["W", "They left at five this morning."],
        ["M", "Have they called you since then?"],
        ["W", "Not once, and my phone is right here."],
        ["M", "No news often means nothing is wrong."],
        ["W", "I keep checking the screen every minute."],
      ],
      choices: ["proud", "bored", "excited", "worried", "satisfied"],
      answer: 4,
      clue: "I keep checking the screen every minute.",
      explanation:
        "아픈 동생 소식을 기다리며 화면만 보고 있으므로 걱정하고 있다. 따라서 답은 ④이다.",
      translation: [
        "M: 소현아, 잠을 못 잔 것 같네.",
        "W: 동생이 열이 많이 나.",
        "M: 부모님이 병원에 데려가셨어?",
        "W: 오늘 아침 다섯 시에 나가셨어.",
        "M: 그 뒤로 전화 오셨어?",
        "W: 한 번도. 휴대폰은 여기 있는데.",
        "M: 소식이 없다는 건 별일 없다는 뜻일 때가 많아.",
        "W: 1분마다 화면을 들여다보고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you know how to use this machine?"],
        ["M", "Put the card in this slot first."],
        ["ANN", "Number two."],
        ["W", "Is the copy machine free?"],
        ["M", "Someone is using it now."],
        ["ANN", "Number three."],
        ["W", "How many copies do you need?"],
        ["M", "Just two, please."],
        ["ANN", "Number four."],
        ["W", "The paper is stuck inside."],
        ["M", "Let me open the side door."],
        ["ANN", "Number five."],
        ["W", "Where do I put the paper?"],
        ["M", "In the bottom tray."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "The paper is stuck inside.",
      explanation:
        "그림은 복사기에 종이가 걸려 옆문을 열어 보는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "In a school copy room, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A girl stands in front of a large copy machine pointing at a crumpled sheet of paper caught in its opening. " +
          "A boy crouches at the side of the machine and pulls its side panel open with one hand. " +
          "A stack of paper and a small bin are drawn simply on the floor beside them.",
      },
      translation: [
        "① W: 이 기계 쓸 줄 알아? / M: 카드를 이 구멍에 먼저 넣어.",
        "② W: 복사기 비었어? / M: 지금 누가 쓰고 있어.",
        "③ W: 몇 장 필요해? / M: 두 장만 부탁해.",
        "④ W: 종이가 안에 걸렸어. / M: 옆문 열어 볼게.",
        "⑤ W: 종이는 어디에 넣어? / M: 아래 받침대에.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minseok, you live near the stationery store, right?"],
        ["M", "It's two buildings from my apartment."],
        ["W", "Our class needs colored paper for the wall."],
        ["M", "How much paper are we talking about?"],
        ["W", "Ten sheets, five red and five blue."],
        ["M", "That's easy enough to carry."],
        ["W", "I have to leave early for a lesson today."],
        ["M", "The store closes at eight, I think."],
        ["W", "Could you buy the colored paper on your way home?"],
        ["M", "Sure, I'll bring it tomorrow morning."],
      ],
      choices: [
        "색종이를 사다 주기",
        "벽을 꾸며 주기",
        "수업을 대신 들어 주기",
        "짐을 들어 주기",
        "가게를 알려 주기",
      ],
      answer: 1,
      clue: "Could you buy the colored paper on your way home?",
      explanation:
        "여자는 집에 가는 길에 색종이를 사 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 민석아, 너 문구점 근처 살지?",
        "M: 우리 아파트에서 두 건물 떨어져 있어.",
        "W: 우리 반이 벽에 붙일 색종이가 필요해.",
        "M: 얼마나 필요한데?",
        "W: 열 장, 빨강 다섯에 파랑 다섯.",
        "M: 그 정도는 들고 오기 쉽네.",
        "W: 나는 오늘 수업 때문에 일찍 가야 해.",
        "M: 가게가 여덟 시에 닫을 거야.",
        "W: 집에 가는 길에 색종이 좀 사다 줄 수 있어?",
        "M: 그래, 내일 아침에 가져올게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 교내 글쓰기 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The library is holding a writing contest. " +
            "This year's subject is a person who changed your mind. " +
            "Write between eight hundred and a thousand letters. " +
            "Hand in your writing at the library desk by next Friday. " +
            "Only one piece per student will be accepted. " +
            "Winning pieces will be printed in the school magazine.",
        ],
      ],
      choices: ["대회 주제", "글의 길이", "제출 기한", "제출할 수 있는 편수", "심사 위원"],
      answer: 5,
      clue: "This year's subject is a person who changed your mind.",
      explanation:
        "주제, 분량, 기한, 편수는 말했지만 심사 위원은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 도서관에서 글쓰기 대회를 엽니다. 올해 주제는 내 생각을 바꾼 사람입니다. 800자에서 1,000자 사이로 써 주세요. 다음 주 금요일까지 도서관 안내대에 내시면 됩니다. 한 사람당 한 편만 받습니다. 당선작은 학교 잡지에 실립니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This shows every street and river in one picture. " +
            "You unfold it when you don't know where you are. " +
            "Small pictures at the side tell you what the marks mean. " +
            "Travelers used to carry a paper one in the car. " +
            "Now most people keep one inside their phone.",
        ],
      ],
      choices: ["달력", "사진", "지도", "편지", "신문"],
      answer: 3,
      clue: "This shows every street and river in one picture.",
      explanation:
        "길과 강을 한 그림에 보여 주며 길을 찾을 때 펼치는 것은 지도이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 모든 길과 강을 한 그림에 보여 줍니다. 어디에 있는지 모를 때 이것을 펼칩니다. 옆에 있는 작은 그림들이 표시가 무슨 뜻인지 알려 줍니다. 여행하는 사람들은 예전에 종이로 된 것을 차에 두고 다녔습니다. 지금은 대부분 휴대폰 안에 넣고 다닙니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Where are you going after school?"],
        ["W", "To the piano academy."],
        ["ANN", "Number two."],
        ["M", "How was the science test?"],
        ["W", "Harder than I expected."],
        ["ANN", "Number three."],
        ["M", "Could you lend me your ruler?"],
        ["W", "Here, take mine."],
        ["ANN", "Number four."],
        ["M", "What color is your new bag?"],
        ["W", "I have three classes today."],
        ["ANN", "Number five."],
        ["M", "Shall we study together tonight?"],
        ["W", "Good idea, let's meet at seven."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "What color is your new bag?",
      explanation:
        "가방 색을 묻는 말에 수업 수를 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 방과 후에 어디 가? / W: 피아노 학원에.",
        "② M: 과학 시험 어땠어? / W: 생각보다 어려웠어.",
        "③ M: 자 좀 빌려줄래? / W: 여기, 내 거 써.",
        "④ M: 네 새 가방 무슨 색이야? / W: 나 오늘 수업이 세 개야.",
        "⑤ M: 오늘 밤에 같이 공부할까? / W: 좋아, 일곱 시에 만나자.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyeon, the parents' meeting starts in fifteen minutes."],
        ["W", "The chairs are all set up in the hall."],
        ["M", "Did anyone put out the name cards?"],
        ["W", "They're still in the box on my desk."],
        ["M", "Parents can't find their seats without them."],
        ["W", "Thirty cards will take five minutes."],
        ["M", "I'll finish testing the microphone here."],
        ["W", "I'll go and put out the name cards."],
      ],
      choices: [
        "의자를 놓기",
        "마이크를 점검하기",
        "이름표를 놓기",
        "학부모를 맞이하기",
        "상자를 치우기",
      ],
      answer: 3,
      clue: "I'll go and put out the name cards.",
      explanation:
        "여자는 이름표를 자리에 놓으러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 채연아, 학부모 모임이 15분 뒤에 시작해.",
        "W: 의자는 강당에 다 놓았어.",
        "M: 이름표는 누가 놓았어?",
        "W: 아직 내 책상 위 상자에 있어.",
        "M: 그게 없으면 학부모님들이 자리를 못 찾으셔.",
        "W: 서른 장이면 5분이면 돼.",
        "M: 나는 여기서 마이크 점검을 끝낼게.",
        "W: 내가 가서 이름표를 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 가방을 고르시오.",
      lines: [
        ["W", "Taeyang, which school bag are you going to buy?"],
        ["M", "Five bags are shown on this page."],
        ["W", "How much money can you spend on it?"],
        ["M", "Under sixty thousand won, my mother said."],
        ["W", "One of them costs much more than that."],
        ["M", "It also needs a laptop pocket on the inside."],
        ["W", "Two of these bags don't have one at all."],
        ["M", "My old bag had no pocket and the screen got scratched."],
        ["W", "Then that pocket really matters this time."],
        ["M", "And I want a light one, under one kilogram."],
        ["W", "Then only one bag is left for you."],
        ["M", "I'll order it tonight before the sale ends."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Under sixty thousand won, my mother said.",
      explanation:
        "6만 원 미만, 노트북 주머니 있음, 1kg 미만인 가방은 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 70,000 won / Laptop pocket: Yes / Weight: 0.9 kg" },
          { no: 2, label: "②", value: "Price: 55,000 won / Laptop pocket: No / Weight: 0.8 kg" },
          { no: 3, label: "③", value: "Price: 48,000 won / Laptop pocket: No / Weight: 1.1 kg" },
          { no: 4, label: "④", value: "Price: 52,000 won / Laptop pocket: Yes / Weight: 1.3 kg" },
          { no: 5, label: "⑤", value: "Price: 58,000 won / Laptop pocket: Yes / Weight: 0.9 kg" },
        ],
      },
      translation: [
        "W: 태양아, 어떤 책가방 살 거야?",
        "M: 이 쪽에 다섯 개가 나와 있어.",
        "W: 거기에 얼마까지 쓸 수 있어?",
        "M: 어머니가 6만 원 미만이라고 하셨어.",
        "W: 하나는 그보다 훨씬 비싸네.",
        "M: 안쪽에 노트북 주머니도 있어야 해.",
        "W: 이 중 두 개는 아예 없어.",
        "M: 전에 쓰던 가방은 주머니가 없어서 화면이 긁혔어.",
        "W: 그럼 이번엔 그 주머니가 정말 중요하겠다.",
        "M: 그리고 1킬로그램 미만으로 가벼웠으면 좋겠어.",
        "W: 그럼 너한테는 하나만 남아.",
        "M: 할인 끝나기 전에 오늘 밤에 주문할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 병문안을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Hyunbin, when should we visit Mr. Song in the hospital?"],
        ["M", "Visiting hours are only on certain days this month."],
        ["W", "Which days did the nurse tell you?"],
        ["M", "The third, the sixth and the eleventh."],
        ["W", "The third is the day of our class presentation."],
        ["M", "We can't leave school early that afternoon."],
        ["W", "And the eleventh is the school open day."],
        ["M", "Then the sixth is the only day we can go."],
        ["W", "We should bring him something to read."],
        ["M", "I'll pick up a magazine before the sixth."],
      ],
      choices: ["the 3rd", "the 6th", "the 11th", "the 8th", "the 13th"],
      answer: 2,
      clue: "Then the sixth is the only day we can go.",
      explanation:
        "3일은 발표, 11일은 학교 공개일이어서 6일에 가기로 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 현빈아, 송 선생님 병문안 언제 갈까?",
        "M: 이번 달에는 면회가 정해진 날에만 돼.",
        "W: 간호사분이 어떤 날이라고 하셨어?",
        "M: 3일, 6일, 11일.",
        "W: 3일은 우리 반 발표 날이야.",
        "M: 그날 오후에는 일찍 못 나가지.",
        "W: 11일은 학교 공개일이고.",
        "M: 그럼 갈 수 있는 날은 6일뿐이네.",
        "W: 읽으실 거리를 하나 사 가자.",
        "M: 6일 전에 잡지를 사 둘게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, you weren't at the study room yesterday."],
        ["M", "I taught my grandfather how to use a phone."],
        ["W", "Did he just get a new one?"],
        ["M", "My father bought it for his birthday."],
        ["W", "What did you teach him first?"],
        ["M", "How to answer a call and save a number."],
        ["W", "Did he learn it quickly?"],
        ["M", "We went over the same thing six times."],
        ["W", "Can he use it alone now?"],
        ["M", "He called me twice last night."],
      ],
      choices: [
        "공부방에 갔다",
        "생일잔치를 했다",
        "할아버지께 휴대폰을 가르쳐 드렸다",
        "휴대폰을 샀다",
        "집에서 쉬었다",
      ],
      answer: 3,
      clue: "I taught my grandfather how to use a phone.",
      explanation:
        "남자는 어제 할아버지께 휴대폰 쓰는 법을 가르쳐 드렸다. 따라서 답은 ③이다.",
      translation: [
        "W: 도현아, 어제 공부방에 안 왔더라.",
        "M: 할아버지께 휴대폰 쓰는 법을 가르쳐 드렸어.",
        "W: 새로 사셨어?",
        "M: 아버지가 생신 선물로 사 드렸어.",
        "W: 뭐부터 가르쳐 드렸어?",
        "M: 전화 받는 법이랑 번호 저장하는 법.",
        "W: 금방 배우셨어?",
        "M: 같은 걸 여섯 번 되풀이했어.",
        "W: 이제 혼자 쓰셔?",
        "M: 어젯밤에 나한테 두 번 전화하셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school office speaking. " +
            "The bus route to the east village changes from tomorrow. " +
            "The bus will stop at the city library instead of the post office. " +
            "Students in that area should get on five minutes earlier. " +
            "The morning bus now leaves at seven forty. " +
            "Please tell your family about this change. " +
            "The new route map is on the front gate wall.",
        ],
      ],
      choices: [
        "통학 버스 노선 변경을 알리려고",
        "체육 대회를 안내하려고",
        "분실물을 찾으려고",
        "봉사자를 모으려고",
        "청소를 부탁하려고",
      ],
      answer: 1,
      clue: "The bus route to the east village changes from tomorrow.",
      explanation:
        "내일부터 통학 버스 노선이 바뀐다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 학교 행정실입니다. 내일부터 동쪽 마을 통학 버스 노선이 바뀝니다. 버스는 우체국 대신 시립 도서관에 섭니다. 그 지역 학생은 5분 일찍 타야 합니다. 아침 버스는 이제 일곱 시 사십 분에 출발합니다. 가족에게도 이 변경을 알려 주세요. 새 노선도는 정문 벽에 붙어 있습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Good afternoon. What can I get you today?"],
        ["W", "Three notebooks and one pack of pens, please."],
        ["M", "Notebooks are two dollars each this week."],
        ["W", "Were they three dollars last month?"],
        ["M", "They were, before the new term sale."],
        ["W", "And how much is the pack of pens?"],
        ["M", "The pack of five costs four dollars."],
        ["W", "Do I pay extra for a bag?"],
        ["M", "No, the bag is free here."],
        ["W", "Good. Here is my card."],
      ],
      choices: ["$8", "$9", "$10", "$11", "$12"],
      answer: 3,
      clue: "Notebooks are two dollars each this week.",
      explanation:
        "공책 세 권 6달러와 펜 한 묶음 4달러를 더하면 10달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 오늘은 뭘 드릴까요?",
        "W: 공책 세 권이랑 펜 한 묶음 주세요.",
        "M: 이번 주에 공책은 한 권에 2달러입니다.",
        "W: 지난달에는 3달러였죠?",
        "M: 맞습니다, 새 학기 할인 전에는요.",
        "W: 펜 묶음은 얼마예요?",
        "M: 다섯 자루짜리는 4달러입니다.",
        "W: 봉투 값도 내야 하나요?",
        "M: 아니요, 여기는 봉투가 무료입니다.",
        "W: 좋네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jaeho, you never lose points on spelling."],
        ["M", "I write the hard words three times each."],
        ["W", "Only the hard ones, not the whole list?"],
        ["M", "The easy ones waste my time."],
        ["W", "How do you know which ones are hard?"],
        ["M", "I test myself once before I study."],
        ["W", "That sounds backwards but it makes sense."],
        ["M", "You only practice what you actually miss."],
        ["W", "How many words should I test at once?"],
      ],
      choices: [
        "Test a hundred at once.",
        "Never test yourself.",
        "About twenty is enough.",
        "Write every word ten times.",
        "Spelling doesn't matter.",
      ],
      answer: 3,
      clue: "How many words should I test at once?",
      explanation:
        "한 번에 몇 개를 확인할지 물었으므로, 스무 개쯤이면 된다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 재호야, 너는 철자에서 점수를 안 깎이더라.",
        "M: 어려운 단어만 세 번씩 써.",
        "W: 목록 전체가 아니라 어려운 것만?",
        "M: 쉬운 건 시간 낭비야.",
        "W: 어떤 게 어려운지 어떻게 알아?",
        "M: 공부하기 전에 나 혼자 한 번 시험을 봐.",
        "W: 거꾸로인 것 같은데 말이 되네.",
        "M: 실제로 틀리는 것만 연습하게 되잖아.",
        "W: 한 번에 몇 개씩 확인하면 좋을까?",
        "M: 스무 개쯤이면 충분해.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yeonseo, I heard you volunteer at the animal shelter."],
        ["W", "I go there every other Saturday morning."],
        ["M", "What do you actually do there?"],
        ["W", "I walk the dogs and wash their bowls."],
        ["M", "Is it sad to see them in cages?"],
        ["W", "It was at first, but many find homes."],
        ["M", "How many dogs live there now?"],
        ["W", "About fifteen, and three left last month."],
        ["M", "Do they let students work alone?"],
        ["W", "An adult stays with us the whole time."],
        ["M", "Could I go with you next Saturday?"],
      ],
      choices: [
        "Sure, meet me at nine.",
        "The shelter closed down.",
        "I never go there.",
        "Students can't enter.",
        "I stopped volunteering.",
      ],
      answer: 1,
      clue: "Could I go with you next Saturday?",
      explanation:
        "다음 토요일에 같이 가도 되는지 물었으므로, 아홉 시에 만나자는 ①이 가장 자연스럽다.",
      translation: [
        "M: 연서야, 동물 보호소에서 봉사한다며.",
        "W: 격주 토요일 아침마다 가.",
        "M: 거기서 실제로 뭘 해?",
        "W: 개들을 산책시키고 밥그릇을 씻어.",
        "M: 우리 안에 있는 걸 보면 슬프지 않아?",
        "W: 처음에는 그랬는데, 새 가족을 찾아가는 애들도 많아.",
        "M: 지금 몇 마리가 있어?",
        "W: 열다섯 마리쯤. 지난달에 세 마리가 갔어.",
        "M: 학생이 혼자 일해도 돼?",
        "W: 어른 한 분이 내내 같이 계셔.",
        "M: 다음 토요일에 같이 가도 돼?",
        "W: 그럼, 아홉 시에 만나.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seungmin, how is the class vegetable box doing?"],
        ["W", "You planted the seeds by the window in March."],
        ["M", "The leaves are turning pale and thin."],
        ["W", "How often do you give them water?"],
        ["M", "A little every single morning."],
        ["W", "Have you changed the soil since March?"],
        ["M", "It's the same soil from the first day."],
        ["W", "Plants use up everything in a small box."],
        ["M", "I never thought soil could run out."],
        ["W", "Why don't you add fresh soil this week?"],
      ],
      choices: [
        "I'll do that on Friday.",
        "The box has no soil.",
        "I'll stop watering them.",
        "Plants don't need soil.",
        "I threw the box away.",
      ],
      answer: 1,
      clue: "Why don't you add fresh soil this week?",
      explanation:
        "새 흙을 넣어 보라는 제안이므로, 금요일에 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 승민아, 학급 채소 상자는 어때?",
        "W: 3월에 창가에 씨를 심었잖아.",
        "M: 잎이 희끄무레하고 얇아지고 있어.",
        "W: 물은 얼마나 자주 줘?",
        "M: 매일 아침 조금씩.",
        "W: 3월 이후로 흙은 갈아 줬어?",
        "M: 첫날 그 흙 그대로야.",
        "W: 작은 상자에서는 식물이 흙 영양을 다 써 버려.",
        "M: 흙이 바닥날 수 있다는 생각은 못 했어.",
        "W: 이번 주에 새 흙을 넣어 보는 건 어때?",
        "M: 금요일에 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Hyejin이 Doyun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Hyejin : ________________",
      lines: [
        [
          "W",
          "Hyejin and Doyun are on duty in the science lab after class. " +
            "Doyun is pouring the leftover liquid straight into the sink. " +
            "Hyejin knows their teacher collects that liquid in a special bottle. " +
            "The bottle is standing on the shelf right behind him. " +
            "She wants him to stop and use the bottle instead. " +
            "In this situation, what would Hyejin most likely say to Doyun?",
        ],
      ],
      choices: [
        "The lab is closed today.",
        "Pour it into the bottle.",
        "Let's wash the sink now.",
        "We need more liquid.",
        "Turn on the water tap.",
      ],
      answer: 2,
      clue: "She wants him to stop and use the bottle instead.",
      explanation:
        "남은 액체를 개수대에 버리려 하므로, 전용 병에 담으라는 ②가 가장 적절하다.",
      translation: [
        "W: 혜진이와 도윤이는 수업이 끝난 뒤 과학실 당번을 하고 있습니다. 도윤이는 남은 액체를 그대로 개수대에 붓고 있습니다. 혜진이는 선생님이 그 액체를 따로 병에 모으신다는 것을 압니다. 그 병은 그의 바로 뒤 선반에 놓여 있습니다. 그녀는 그가 멈추고 그 병을 쓰기를 바랍니다. 이런 상황에서 혜진이가 도윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
