/** 중2 듣기 17회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 17회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 머그컵을 고르시오.",
      lines: [
        ["W", "Good morning. Are you looking for a mug?"],
        ["M", "Yes, one I can take to the school library."],
        ["W", "We have mugs with a handle and mugs without one."],
        ["M", "With a handle, please. The ones without get too hot to hold."],
        ["W", "All right. Do you want a lid on it?"],
        ["M", "Yes, I spill things when I walk."],
        ["W", "Then two are left. One has stripes and one has no pattern."],
        ["M", "The striped one, please. My old mug was plain and I kept picking up someone else's."],
        ["W", "Good choice. This one keeps a drink warm for three hours."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "The striped one, please. My old mug was plain and I kept picking up someone else's.",
      explanation:
        "남자는 손잡이가 있는 머그컵을, 뚜껑이 달린 것으로, 줄무늬가 있는 것을 고른다. 따라서 답은 ②이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five drinking mugs standing side by side in one row on a plain white background, each the same size, clean black line art, no writing or letters anywhere. " +
          "Mug 1: a big C-shaped HANDLE on the side, a flat LID on top, body completely blank with no pattern. " +
          "Mug 2: a big C-shaped HANDLE on the side, a flat LID on top, body wrapped in bold horizontal STRIPES. " +
          "Mug 3: a big C-shaped HANDLE on the side, NO lid, the mug is wide open at the top, body wrapped in bold horizontal STRIPES. " +
          "Mug 4: NO handle at all, a smooth plain cylinder, a flat LID on top, body wrapped in bold horizontal STRIPES. " +
          "Mug 5: NO handle at all, a smooth plain cylinder, NO lid, wide open at the top, body completely blank with no pattern.",
      },
      translation: [
        "W: 안녕하세요. 머그컵 찾으세요?",
        "M: 네, 학교 도서관에 가져갈 거예요.",
        "W: 손잡이가 있는 것과 없는 것이 있습니다.",
        "M: 손잡이 있는 걸로요. 없는 건 뜨거워서 못 들겠더라고요.",
        "W: 알겠습니다. 뚜껑이 있는 걸로 하시겠어요?",
        "M: 네, 걷다가 잘 흘려서요.",
        "W: 그럼 두 개 남았네요. 하나는 줄무늬가 있고 하나는 무늬가 없습니다.",
        "M: 줄무늬로 주세요. 예전 머그컵은 무늬가 없어서 자꾸 남의 걸 집었거든요.",
        "W: 좋은 선택이세요. 이건 세 시간 동안 따뜻합니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 독서 토론회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yerin, are you joining the reading discussion this month?"],
        ["W", "I want to, but I don't know how it works."],
        ["M", "It meets every Wednesday after school in the library."],
        ["W", "What book are you reading?"],
        ["M", "A short novel about a boy who moves to an island."],
        ["W", "How many people come?"],
        ["M", "About twelve, in two small circles."],
        ["W", "Do I need to prepare anything?"],
        ["M", "Just read two chapters and write one question."],
        ["W", "That sounds easy enough. I'll come on Wednesday."],
      ],
      choices: ["모이는 요일", "모이는 장소", "읽는 책", "참가 인원", "신청 방법"],
      answer: 5,
      clue: "Just read two chapters and write one question.",
      explanation:
        "요일(수요일), 장소(도서관), 읽는 책(섬으로 이사 간 소년 이야기), 참가 인원(열두 명)은 언급되지만 신청 방법은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예린아, 이번 달 독서 토론회 들어올 거야?",
        "W: 하고 싶은데 어떻게 하는 건지 몰라.",
        "M: 수요일마다 방과 후에 도서관에서 모여.",
        "W: 무슨 책 읽는데?",
        "M: 섬으로 이사 간 소년 이야기인 짧은 소설이야.",
        "W: 몇 명이나 와?",
        "M: 열두 명쯤, 작은 모임 두 개로 나눠서.",
        "W: 뭘 준비해야 해?",
        "M: 두 장 읽고 질문 하나 써 오면 돼.",
        "W: 그 정도면 할 만하네. 수요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Sumin. It's Jaewon from the badminton club."],
        ["W", "Hi. What's up?"],
        ["M", "About tomorrow's practice. The gym floor is being repainted."],
        ["W", "So we can't use it?"],
        ["M", "Not until Monday. We're moving practice to Saturday morning."],
        ["W", "Same time?"],
        ["M", "Ten o'clock, at the outdoor court behind the science building."],
        ["W", "Got it. Thanks for letting me know."],
      ],
      choices: [
        "동아리 가입을 권하려고",
        "빌린 라켓을 돌려 달라고 하려고",
        "연습 날짜가 바뀐 것을 알리려고",
        "경기 결과를 알려 주려고",
        "체육관 청소를 부탁하려고",
      ],
      answer: 3,
      clue: "Not until Monday. We're moving practice to Saturday morning.",
      explanation:
        "남자는 체육관 바닥 도색 때문에 연습이 토요일 오전으로 옮겨졌다고 알리려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 수민아. 배드민턴부 재원이야.",
        "W: 안녕. 무슨 일이야?",
        "M: 내일 연습 말인데, 체육관 바닥을 다시 칠한대.",
        "W: 그럼 못 써?",
        "M: 월요일까지는 못 써. 연습을 토요일 오전으로 옮길 거야.",
        "W: 시간은 같고?",
        "M: 10시, 과학관 뒤 야외 코트에서.",
        "W: 알겠어. 알려 줘서 고마워.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yeji, what time should we meet at the station tomorrow?"],
        ["W", "The train leaves at nine thirty."],
        ["M", "And we have to collect the tickets from the machine."],
        ["W", "How about nine o'clock?"],
        ["M", "The machines are busy on Saturday mornings. Let's go earlier."],
        ["W", "How long does it take you to get there?"],
        ["M", "Twenty minutes by bus."],
        ["W", "Then let's meet at eight thirty."],
        ["M", "Eight thirty it is. I'll wait by the clock."],
      ],
      choices: ["8:15 a.m.", "8:30 a.m.", "8:45 a.m.", "9:00 a.m.", "9:30 a.m."],
      answer: 2,
      clue: "Then let's meet at eight thirty.",
      explanation:
        "기차가 9시 30분에 떠나고 표 기계 앞이 붐벼서 두 사람은 8시 30분에 만나기로 한다. 따라서 답은 ②이다.",
      translation: [
        "M: 예지야, 내일 역에서 몇 시에 만날까?",
        "W: 기차가 9시 30분에 떠나.",
        "M: 그리고 기계에서 표도 찾아야 하잖아.",
        "W: 9시는 어때?",
        "M: 토요일 아침에는 기계 앞이 붐벼. 더 일찍 가자.",
        "W: 거기까지 얼마나 걸려?",
        "M: 버스로 20분.",
        "W: 그럼 8시 30분에 만나자.",
        "M: 8시 30분으로 하자. 시계 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyewon, you've been staring at that envelope for a while."],
        ["W", "It's from the science fair. I sent in my project last month."],
        ["M", "And? Have you opened it?"],
        ["W", "I did. They chose twelve projects out of two hundred, and mine is one."],
        ["M", "That's amazing! You rebuilt that model three times."],
        ["W", "I nearly gave up in August. My mother told me to finish it."],
        ["M", "Aren't you glad you listened?"],
        ["W", "I keep reading my own name to make sure it's really there."],
      ],
      choices: ["delighted", "nervous", "bored", "upset", "disappointed"],
      answer: 1,
      clue: "I keep reading my own name to make sure it's really there.",
      explanation:
        "200편 중 12편에 뽑혀 자기 이름을 거듭 확인한다고 했으므로 여자는 매우 기뻐하고 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 혜원아, 그 봉투를 한참 들여다보네.",
        "W: 과학 전람회에서 온 거야. 지난달에 작품을 냈거든.",
        "M: 그래서? 열어 봤어?",
        "W: 열어 봤지. 200편 중에 12편을 뽑았는데 내 것이 있어.",
        "M: 대단하다! 그 모형 세 번이나 다시 만들었잖아.",
        "W: 8월에 거의 포기할 뻔했어. 엄마가 끝까지 해 보라고 하셨어.",
        "M: 말 듣길 잘했지?",
        "W: 진짜 있는지 확인하려고 내 이름을 계속 읽고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Is this seat taken?"],
        ["M", "No, please sit down."],
        ["W", "Excuse me, your bag is open."],
        ["M", "Oh, thank you. I didn't notice."],
        ["W", "What time does the library close?"],
        ["M", "At six on weekdays."],
        ["W", "How much is this notebook?"],
        ["M", "Two dollars."],
        ["W", "Can I borrow your eraser?"],
        ["M", "Sure, here you are."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Excuse me, your bag is open.",
      explanation:
        "그림은 앞서 걸어가는 사람의 배낭 지퍼가 열려 있고 뒤에서 걸어오던 사람이 그것을 가리키며 알려 주는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a school hallway. A student is walking away and the ZIPPER of his backpack is wide OPEN, with a notebook about to slip out. Another student walking behind him has stopped and is pointing at the open backpack with one hand, calling out to him. Both are drawn clearly. Lockers and a window are in the background.",
      },
      translation: [
        "① W: 이 자리 임자 있나요? / M: 아니요, 앉으세요.",
        "② W: 실례합니다, 가방이 열렸어요. / M: 아, 고맙습니다. 몰랐네요.",
        "③ W: 도서관 몇 시에 닫아요? / M: 평일에는 6시에요.",
        "④ W: 이 공책 얼마예요? / M: 2달러입니다.",
        "⑤ W: 지우개 좀 빌려줄래? / M: 그럼, 여기 있어.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minwoo, are you going to the art room after lunch?"],
        ["M", "Yes, our club paints there every Tuesday."],
        ["W", "Good. Could you do something for me while you're there?"],
        ["M", "What is it?"],
        ["W", "I left my brushes soaking in the sink yesterday."],
        ["M", "Do you want me to bring them to you?"],
        ["W", "No, just wash them and stand them up to dry."],
        ["M", "Sure. Which ones are yours?"],
        ["W", "The three with blue tape on the handles."],
        ["M", "Got it. I'll do it as soon as I get there."],
      ],
      choices: ["붓을 사다 주기", "그림 대신 그려 주기", "붓을 씻어 말려 주기", "미술실 문 잠그기", "물감 빌려주기"],
      answer: 3,
      clue: "No, just wash them and stand them up to dry.",
      explanation:
        "여자는 개수대에 담가 둔 붓을 씻어서 세워 말려 달라고 부탁한다. 가져다 달라는 것이 아니다. 따라서 답은 ③이다.",
      translation: [
        "W: 민우야, 점심 먹고 미술실 가?",
        "M: 응, 우리 동아리가 화요일마다 거기서 그려.",
        "W: 잘됐다. 거기 있는 동안 하나만 부탁할게.",
        "M: 뭔데?",
        "W: 어제 개수대에 붓을 담가 놓고 왔어.",
        "M: 가져다줄까?",
        "W: 아니, 씻어서 세워 말려 주기만 하면 돼.",
        "M: 그래. 어떤 게 네 거야?",
        "W: 손잡이에 파란 테이프 붙은 세 개.",
        "M: 알겠어. 가자마자 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Spring Book Market에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Here is news about the Spring Book Market."],
        ["M", "It will be held next Wednesday, from one to four in the afternoon."],
        ["M", "Everything takes place in the front yard, beside the flower beds."],
        ["M", "Bring books you have finished, but no torn or written-in ones."],
        ["M", "Every book costs one thousand won, whatever it is."],
        ["M", "Come early; the good ones go in the first half hour."],
      ],
      choices: ["열리는 날", "열리는 시간", "장소", "책값", "판매 수익 사용처"],
      answer: 5,
      clue: "Every book costs one thousand won, whatever it is.",
      explanation:
        "날짜(다음 주 수요일), 시간(오후 1시~4시), 장소(앞뜰), 책값(권당 천 원)은 언급되지만 판매 수익을 어디에 쓰는지는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Spring Book Market 소식입니다.",
        "M: 다음 주 수요일 오후 1시부터 4시까지 열립니다.",
        "M: 모두 화단 옆 앞뜰에서 진행합니다.",
        "M: 다 읽은 책을 가져오되, 찢어졌거나 낙서가 있는 책은 안 됩니다.",
        "M: 어떤 책이든 한 권에 천 원입니다.",
        "M: 일찍 오세요. 좋은 책은 처음 30분에 다 나갑니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You will find one of these at the side of every road."],
        ["W", "It is a tall pole with three round lights on it."],
        ["W", "The lights are red, yellow, and green, from the top down."],
        ["W", "Drivers stop when the top one is on and go when the bottom one is on."],
        ["W", "Many of them now count down the seconds for people crossing."],
      ],
      choices: ["신호등", "가로등", "표지판", "소화전", "버스 정류장"],
      answer: 1,
      clue: "The lights are red, yellow, and green, from the top down.",
      explanation:
        "빨강·노랑·초록 세 개의 등이 위에서부터 달려 있고 운전자가 그에 따라 서고 간다고 했으므로 신호등이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 길가 어디에나 하나씩 있습니다.",
        "W: 둥근 등이 세 개 달린 높은 기둥입니다.",
        "W: 등은 위에서부터 빨강, 노랑, 초록입니다.",
        "W: 운전자는 맨 위 등이 켜지면 서고, 맨 아래 등이 켜지면 갑니다.",
        "W: 요즘은 길을 건너는 사람을 위해 초를 세어 주는 것도 많습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How long have you played the guitar?"],
        ["W", "About three years."],
        ["M", "Could you close the window?"],
        ["W", "Sure, no problem."],
        ["M", "Where did you buy that hat?"],
        ["W", "At the shop near the station."],
        ["M", "Why are you so late today?"],
        ["W", "I like winter better than summer."],
        ["M", "What are you going to do this evening?"],
        ["W", "I'll finish my book report."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why are you so late today?",
      explanation:
        "왜 늦었는지 묻는 말에 겨울이 여름보다 좋다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 기타 친 지 얼마나 됐어? / W: 3년쯤.",
        "② M: 창문 좀 닫아 줄래? / W: 그래, 그럴게.",
        "③ M: 그 모자 어디서 샀어? / W: 역 근처 가게에서.",
        "④ M: 오늘 왜 이렇게 늦었어? / W: 나는 여름보다 겨울이 좋아.",
        "⑤ M: 오늘 저녁에 뭐 할 거야? / W: 독후감 끝낼 거야.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseo, the class concert starts in twenty minutes."],
        ["M", "Is the hall ready? What should I do?"],
        ["W", "I've put out the chairs and taped the wires down."],
        ["M", "Should I hand out the programs?"],
        ["W", "Yerin is doing that at the entrance."],
        ["M", "Then what's left?"],
        ["W", "The microphone stand is still in the music room and we need it."],
        ["M", "I'll go and bring it right now."],
        ["W", "Thanks. I'll turn on the stage lights."],
      ],
      choices: ["의자 놓기", "전선 붙이기", "안내지 나눠 주기", "마이크 받침대 가져오기", "무대 조명 켜기"],
      answer: 4,
      clue: "I'll go and bring it right now.",
      explanation:
        "의자와 전선, 안내지는 이미 해결되었으므로 남자는 음악실에 있는 마이크 받침대를 가지러 간다. 따라서 답은 ④이다.",
      translation: [
        "W: 준서야, 학급 음악회가 20분 뒤에 시작해.",
        "M: 강당은 준비됐어? 내가 뭘 할까?",
        "W: 의자는 다 놨고 전선도 테이프로 붙였어.",
        "M: 안내지를 나눠 줄까?",
        "W: 예린이가 입구에서 나눠 주고 있어.",
        "M: 그럼 뭐가 남았어?",
        "W: 마이크 받침대가 아직 음악실에 있는데 그게 필요해.",
        "M: 내가 지금 가서 가져올게.",
        "W: 고마워. 나는 무대 조명을 켤게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 체험 활동을 고르시오.",
      lines: [
        ["M", "Dain, these are the five weekend programs still open."],
        ["W", "Let's see. I can't do Saturdays because of my violin lesson."],
        ["M", "Then one is out. What else?"],
        ["W", "It has to be indoors. I get sunburned so easily."],
        ["M", "One is outdoors, so that's gone too."],
        ["W", "Three left. What about the fee?"],
        ["M", "You said ten thousand won at the most."],
        ["W", "Then one more drops out. Two are left."],
        ["M", "Do they both run for two hours?"],
        ["W", "Only one does. The other takes four hours and I'd be too tired."],
        ["M", "Then that settles it. Sign up tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Then that settles it. Sign up tonight.",
      explanation:
        "토요일인 ①, 야외인 ②, 12,000원인 ⑤를 뺀다. 남은 ③과 ④ 중 2시간인 것은 ③이므로 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "토요일 / 실내 / 8,000원 / 2시간" },
          { no: 2, label: "②", value: "일요일 / 야외 / 8,000원 / 2시간" },
          { no: 3, label: "③", value: "일요일 / 실내 / 9,000원 / 2시간" },
          { no: 4, label: "④", value: "일요일 / 실내 / 10,000원 / 4시간" },
          { no: 5, label: "⑤", value: "일요일 / 실내 / 12,000원 / 2시간" },
        ],
      },
      translation: [
        "M: 다인아, 아직 열려 있는 주말 프로그램이 이 다섯 개야.",
        "W: 보자. 바이올린 수업 때문에 토요일은 안 돼.",
        "M: 그럼 하나 빠지네. 또 뭐가 있어?",
        "W: 실내여야 해. 나는 햇볕에 너무 잘 타.",
        "M: 하나는 야외니까 그것도 빠져.",
        "W: 셋 남았다. 참가비는 어때?",
        "M: 많아야 만 원이라고 했잖아.",
        "W: 그럼 하나 더 빠지고 둘 남았다.",
        "M: 둘 다 두 시간짜리야?",
        "W: 한 개만. 다른 하나는 네 시간이라 너무 힘들 거야.",
        "M: 그럼 정해졌네. 오늘 밤에 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진전에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Chaewon, when should we go to the photo exhibition?"],
        ["W", "It runs on the eighth, ninth, and tenth."],
        ["M", "What is it about?"],
        ["W", "Street photographs taken in our city fifty years ago."],
        ["M", "That sounds good. But I have a dental check-up on the ninth."],
        ["W", "Then the eighth or the tenth."],
        ["M", "Isn't the tenth the day of the class field trip?"],
        ["W", "You're right, I forgot. We'd be away all day."],
        ["M", "So only the eighth is left."],
        ["W", "Then let's go on the eighth. I'll book the tickets tonight."],
      ],
      choices: ["8일", "9일", "10일", "11일", "12일"],
      answer: 1,
      clue: "So only the eighth is left.",
      explanation:
        "9일은 치과 검진, 10일은 현장 학습이어서 8일만 남는다. 따라서 답은 ①이다.",
      translation: [
        "M: 채원아, 사진전에 언제 갈까?",
        "W: 8일, 9일, 10일에 열려.",
        "M: 무슨 사진전인데?",
        "W: 50년 전 우리 도시 거리를 찍은 사진들이야.",
        "M: 좋네. 그런데 나 9일에 치과 검진이 있어.",
        "W: 그럼 8일이나 10일이네.",
        "M: 10일은 현장 학습 날 아니야?",
        "W: 맞다, 잊었네. 하루 종일 밖에 있잖아.",
        "M: 그럼 8일만 남네.",
        "W: 그럼 8일에 가자. 오늘 밤에 표 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeyang, did you go to the baseball game last weekend?"],
        ["M", "No, I helped my aunt move on Sunday."],
        ["W", "Move? To where?"],
        ["M", "A flat two streets away from her old one."],
        ["W", "Was there a lot to carry?"],
        ["M", "Mostly books. She has more books than furniture."],
        ["W", "So you carried boxes all day?"],
        ["M", "All day. But she bought us dinner, so it was worth it."],
      ],
      choices: ["야구 경기 보기", "책 사러 가기", "친구 만나기", "집안 청소하기", "이사 돕기"],
      answer: 5,
      clue: "No, I helped my aunt move on Sunday.",
      explanation:
        "남자는 지난 일요일에 이모의 이사를 도왔다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 태양아, 지난 주말에 야구 경기 봤어?",
        "M: 아니, 일요일에 이모 이사를 도왔어.",
        "W: 이사? 어디로?",
        "M: 원래 집에서 두 블록 떨어진 집으로.",
        "W: 나를 게 많았어?",
        "M: 거의 책이었어. 가구보다 책이 더 많으셔.",
        "W: 그럼 하루 종일 상자를 날랐겠네?",
        "M: 하루 종일. 그래도 저녁을 사 주셔서 보람 있었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school health office."],
        ["W", "The yearly eye check-up takes place on Tuesday."],
        ["W", "Each class comes down during its own physical education lesson."],
        ["W", "If you wear glasses or lenses, bring them with you."],
        ["W", "The results will be sent home at the end of next week."],
        ["W", "Please do not stay up late on Monday night."],
      ],
      choices: [
        "안경을 새로 맞추라고 하려고",
        "체육 수업 시간을 바꾸려고",
        "보건실 위치를 알리려고",
        "시력 검사 안내를 하려고",
        "일찍 등교하라고 하려고",
      ],
      answer: 4,
      clue: "The yearly eye check-up takes place on Tuesday.",
      explanation:
        "화요일에 있을 시력 검사의 시간과 준비물, 결과 통지를 알리는 방송이다. 따라서 방송의 목적은 ④이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 보건실입니다.",
        "W: 해마다 하는 시력 검사가 화요일에 있습니다.",
        "W: 각 반은 자기 반 체육 시간에 내려오면 됩니다.",
        "W: 안경이나 렌즈를 쓰는 학생은 꼭 가져오세요.",
        "W: 결과는 다음 주 말에 가정으로 보내 드립니다.",
        "W: 월요일 밤에는 늦게까지 깨어 있지 마세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the science center. How many tickets?"],
        ["M", "Four student tickets, please."],
        ["W", "Student tickets are five dollars each."],
        ["M", "So twenty dollars."],
        ["W", "That's right. Would you like the planetarium show as well?"],
        ["M", "How much is that?"],
        ["W", "Three dollars per person on top of the ticket."],
        ["M", "Then just two of us."],
        ["W", "All right. And groups of four or more get four dollars off."],
        ["M", "Great. Here's my card."],
      ],
      choices: ["$20", "$22", "$23", "$26", "$30"],
      answer: 2,
      clue: "All right. And groups of four or more get four dollars off.",
      explanation:
        "학생 표 5달러씩 네 장은 20달러, 천문관 3달러씩 두 명은 6달러여서 26달러이다. 4인 이상 할인 4달러를 빼면 22달러이므로 답은 ②이다.",
      translation: [
        "W: 과학관입니다. 표 몇 장 드릴까요?",
        "M: 학생 표 네 장 주세요.",
        "W: 학생 표는 한 장에 5달러입니다.",
        "M: 그럼 20달러네요.",
        "W: 맞습니다. 천문관 공연도 보시겠어요?",
        "M: 그건 얼마예요?",
        "W: 표값에 더해 한 사람에 3달러입니다.",
        "M: 그럼 저희 둘만요.",
        "W: 알겠습니다. 그리고 4인 이상은 4달러 할인됩니다.",
        "M: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Jiwoo, you've been redrawing that poster all week."],
        ["W", "The contest closes on Friday and the middle still looks empty."],
        ["M", "Which part exactly?"],
        ["W", "The space under the title. Everything I put there looks wrong."],
        ["M", "How do you decide what goes there?"],
        ["W", "I draw something, look at it, and rub it out."],
        ["M", "So you never see two ideas side by side."],
        ["W", "That's true. There's only ever one on the paper."],
        ["M", "Draw three small versions on scrap paper and lay them out together."],
      ],
      choices: [
        "Then I'll sketch three small ones tonight.",
        "The contest is held every spring.",
        "My poster is about saving water.",
        "I've used up all my colored pencils.",
        "You should enter the contest too.",
      ],
      answer: 1,
      clue: "Draw three small versions on scrap paper and lay them out together.",
      explanation:
        "작게 세 가지를 그려서 나란히 놓고 보라는 조언을 들었으므로, 오늘 밤에 작게 세 개를 그려 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 지우야, 일주일 내내 그 포스터를 다시 그리네.",
        "W: 대회가 금요일에 마감인데 가운데가 아직 비어 보여.",
        "M: 정확히 어느 부분?",
        "W: 제목 아래 공간. 거기 뭘 넣어도 이상해.",
        "M: 거기 뭘 넣을지 어떻게 정하는데?",
        "W: 뭔가 그리고, 보고, 지워.",
        "M: 그럼 두 안을 나란히 놓고 볼 일이 없네.",
        "W: 맞아. 종이 위에는 늘 하나뿐이야.",
        "M: 이면지에 작게 세 개를 그려서 나란히 놓아 봐.",
        "W: 그럼 오늘 밤에 작게 세 개 그려 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Hyunjun, you've missed the school bus twice this week."],
        ["M", "I wake up on time. It's what comes after that."],
        ["W", "What do you do first when you get up?"],
        ["M", "I check my phone in bed for a while."],
        ["W", "And then you dress and eat in five minutes."],
        ["M", "Exactly. I always run out of time at the end."],
        ["W", "Where do you keep the phone at night?"],
        ["M", "Right beside my pillow."],
        ["W", "Charge it across the room and you'll have to get up to reach it."],
      ],
      choices: [
        "The bus comes at seven forty.",
        "My phone battery lasts two days.",
        "Then I'll move the charger tonight.",
        "I usually sleep around eleven.",
        "You should take the bus with me.",
      ],
      answer: 3,
      clue: "Charge it across the room and you'll have to get up to reach it.",
      explanation:
        "휴대전화를 방 반대편에서 충전하라는 조언을 들었으므로, 오늘 밤에 충전기를 옮기겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 현준아, 이번 주에 통학 버스를 두 번이나 놓쳤네.",
        "M: 제시간에 일어나긴 해. 그다음이 문제야.",
        "W: 일어나서 제일 먼저 뭘 하는데?",
        "M: 침대에서 한참 휴대전화를 봐.",
        "W: 그러고는 5분 만에 옷 입고 밥 먹고.",
        "M: 그래. 늘 마지막에 시간이 없어.",
        "W: 밤에는 휴대전화를 어디에 둬?",
        "M: 베개 바로 옆에.",
        "W: 방 반대편에서 충전해 봐. 가지러 일어나야 하잖아.",
        "M: 그럼 오늘 밤에 충전기를 옮길게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sohee, how is the club recruiting going?"],
        ["W", "Badly. Only two people have signed up in three weeks."],
        ["M", "How are you telling people about it?"],
        ["W", "I put one notice on the board by the office."],
        ["M", "Just one notice, on one board?"],
        ["W", "Yes, and it says 'Join our film club'."],
        ["M", "Most people walk past that board without stopping."],
        ["W", "I never thought about where they actually stand still."],
        ["M", "Put a notice where people wait: the lunch queue and the bus stop."],
      ],
      choices: [
        "Our club meets on Thursdays.",
        "The notice is printed in color.",
        "I made the film club last year.",
        "We watch one film every month.",
        "Then I'll put two up tomorrow morning.",
      ],
      answer: 5,
      clue: "Put a notice where people wait: the lunch queue and the bus stop.",
      explanation:
        "사람들이 서서 기다리는 곳에 안내를 붙이라는 조언을 들었으므로, 내일 아침에 두 장 더 붙이겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "M: 소희야, 동아리 모집은 잘돼 가?",
        "W: 잘 안돼. 3주 동안 두 명 신청했어.",
        "M: 어떻게 알리고 있는데?",
        "W: 행정실 옆 게시판에 안내문 한 장 붙였어.",
        "M: 한 장을, 게시판 하나에만?",
        "W: 응, '영화 동아리에 들어오세요'라고 써 있어.",
        "M: 그 게시판은 다들 그냥 지나쳐.",
        "W: 사람들이 어디서 가만히 서 있는지는 생각 못 했어.",
        "M: 기다리는 곳에 붙여. 급식 줄이랑 버스 정류장.",
        "W: 그럼 내일 아침에 두 장 붙일게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minji가 Sangwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Minji : ________________",
      lines: [
        ["W", "Minji and Sangwoo run the school library together at lunchtime."],
        ["W", "Sangwoo has made a new list of the books students return late."],
        ["W", "The list is neat and easy to read."],
        ["W", "However, he has put it on the wall beside the back door."],
        ["W", "Almost nobody uses that door during lunch."],
        ["W", "Minji does not want to say that his list is useless."],
        ["W", "She wants to suggest moving it to the front desk instead."],
        ["W", "In this situation, what would Minji most likely say to Sangwoo?"],
      ],
      choices: [
        "Let's stop making the list from now on.",
        "You should write the names bigger.",
        "I'll take the books back myself.",
        "Could we move the list to the front desk?",
        "The back door should stay locked.",
      ],
      answer: 4,
      clue: "She wants to suggest moving it to the front desk instead.",
      explanation:
        "민지는 상우의 목록을 깎아내리지 않으면서, 뒷문 옆이 아니라 앞쪽 안내 책상으로 옮기자고 말하려 한다. 따라서 ④가 가장 적절하다.",
      translation: [
        "W: 민지와 상우는 점심시간에 함께 학교 도서관을 맡고 있습니다.",
        "W: 상우가 책을 늦게 반납한 학생 목록을 새로 만들었습니다.",
        "W: 목록은 깔끔하고 읽기 쉽습니다.",
        "W: 그런데 그것을 뒷문 옆 벽에 붙였습니다.",
        "W: 점심시간에 그 문을 쓰는 사람은 거의 없습니다.",
        "W: 민지는 그 목록이 쓸모없다고 말하고 싶지는 않습니다.",
        "W: 다만 앞쪽 안내 책상으로 옮기자고 제안하고 싶습니다.",
        "W: 이런 상황에서 민지가 상우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
