/** 중2 듣기 29회 — 사람이 직접 쓴 회차 (2026-09-24) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 29회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 탁상시계를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a desk clock?"],
        ["M", "Yes, one that can wake me up in the morning."],
        ["W", "We have clocks with two bells on top and clocks with a flat top."],
        ["M", "A flat top, please. The bells look old-fashioned to me."],
        ["W", "All right. This flat-top clock has round feet."],
        ["M", "Round feet slide around on my desk."],
        ["W", "Then here is a flat-top clock with square feet."],
        ["M", "That's the one. I'll take the square-foot clock."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A flat top, please. / I'll take the square-foot clock.",
      explanation:
        "남자는 윗면이 평평한 시계를 원하고, 둥근 다리 대신 네모난 다리를 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five small desk alarm clocks drawn side by side as five choices, clean black line art on white. " +
          "① a clock with TWO BELLS on top and ROUND BALL FEET. " +
          "② a clock with TWO BELLS on top and SQUARE BLOCK FEET. " +
          "③ a clock with a FLAT TOP and ROUND BALL FEET. " +
          "④ a clock with a FLAT TOP and SQUARE BLOCK FEET. " +
          "⑤ a clock with a FLAT TOP and NO feet, sitting flat on the table.",
      },
      translation: [
        "W: 안녕하세요. 탁상시계 찾으세요?",
        "M: 네, 아침에 깨워 줄 것으로요.",
        "W: 위에 종이 두 개 달린 것도 있고 윗면이 평평한 것도 있어요.",
        "M: 평평한 걸로 주세요. 종은 구식으로 보여요.",
        "W: 알겠습니다. 이 평평한 시계는 다리가 둥글어요.",
        "M: 둥근 다리는 책상에서 미끄러져요.",
        "W: 그럼 다리가 네모난 평평한 시계가 여기 있어요.",
        "M: 그거예요. 네모 다리 시계로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 글쓰기 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yeseul, are you entering the school writing contest?"],
        ["W", "I want to. When is the deadline?"],
        ["M", "The last Friday of this month."],
        ["W", "How long does the piece have to be?"],
        ["M", "Between eight hundred and a thousand words."],
        ["W", "Is there a set topic this year?"],
        ["M", "Yes, the topic is a person who changed you."],
        ["W", "Where do we submit it?"],
        ["M", "By email to the Korean language office."],
      ],
      choices: ["심사 위원", "제출 기한", "글의 길이", "글의 주제", "제출 방법"],
      answer: 1,
      clue: "심사 위원은 대화에서 언급되지 않았다.",
      explanation:
        "제출 기한(이달 마지막 금요일), 글의 길이(800~1000단어), 주제(나를 바꾼 사람), 제출 방법(국어실로 이메일)은 언급되지만 심사 위원은 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 예슬아, 교내 글쓰기 대회 나갈 거야?",
        "W: 나가고 싶어. 마감이 언제야?",
        "M: 이달 마지막 금요일.",
        "W: 글은 얼마나 길어야 해?",
        "M: 800단어에서 1000단어 사이.",
        "W: 올해는 정해진 주제가 있어?",
        "M: 응, 주제는 '나를 바꾼 사람'이야.",
        "W: 어디에 내?",
        "M: 국어실로 이메일 보내면 돼.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, is this the Areum Flower Shop?"],
        ["M", "Yes, it is. How may I help you?"],
        ["W", "I ordered a bouquet for tomorrow afternoon."],
        ["M", "Let me check. Under the name Yeseul Kang?"],
        ["W", "That's right. Could you deliver it in the morning instead?"],
        ["M", "Our morning delivery goes out around ten."],
        ["W", "Ten would be perfect. My grandmother leaves at noon."],
        ["M", "All right. I've changed it to the morning route."],
      ],
      choices: [
        "꽃다발을 새로 주문하려고",
        "주문을 취소하려고",
        "꽃값을 물어보려고",
        "배달 시간을 바꾸려고",
        "꽃집 위치를 물어보려고",
      ],
      answer: 4,
      clue: "That's right. Could you deliver it in the morning instead?",
      explanation:
        "여자는 예약한 꽃다발을 오후 대신 오전에 배달해 달라고 부탁하려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "W: 여보세요, 아름 꽃집이죠?",
        "M: 네, 맞습니다. 무엇을 도와드릴까요?",
        "W: 내일 오후로 꽃다발을 주문했어요.",
        "M: 확인해 볼게요. 강예슬 님이시죠?",
        "W: 맞아요. 대신 오전에 배달해 주실 수 있나요?",
        "M: 저희 오전 배달은 10시쯤 나갑니다.",
        "W: 10시면 딱 좋아요. 할머니가 정오에 나가시거든요.",
        "M: 알겠습니다. 오전 배달로 바꿔 두었습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Yeseul, what time does the pottery class end?"],
        ["W", "The class runs until three in the afternoon."],
        ["M", "Do you leave right when it ends?"],
        ["W", "No, we clean the tables and wash the tools first."],
        ["M", "How long does the cleaning take?"],
        ["W", "About thirty minutes with the whole class."],
        ["M", "Then let's meet when you finish cleaning."],
        ["W", "Good. I'll come out through the back door."],
        ["M", "I'll wait for you at the bus stop."],
      ],
      choices: ["2:30 p.m.", "3:30 p.m.", "3:00 p.m.", "4:00 p.m.", "4:30 p.m."],
      answer: 2,
      clue: "Then let's meet when you finish cleaning.",
      explanation:
        "수업이 3시에 끝나고 정리에 30분이 걸리므로 만나는 시각은 3시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "M: 예슬아, 도자기 수업 몇 시에 끝나?",
        "W: 수업은 오후 3시까지야.",
        "M: 끝나자마자 나와?",
        "W: 아니, 탁자 닦고 도구 씻는 걸 먼저 해.",
        "M: 정리하는 데 얼마나 걸려?",
        "W: 다 같이 하면 30분쯤.",
        "M: 그럼 정리 끝날 때 만나자.",
        "W: 좋아. 나는 뒷문으로 나갈게.",
        "M: 나는 버스 정류장에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeseul, you keep looking at the classroom door."],
        ["W", "My best friend is moving to Jeju this Friday."],
        ["M", "The one who sat next to you since first grade?"],
        ["W", "Yes, we've eaten lunch together for three years."],
        ["M", "You can still call and message her."],
        ["W", "I know, but it won't be the same at all."],
        ["M", "Friday is still three days away."],
        ["W", "Every time I look at her empty seat I feel it already."],
      ],
      choices: ["excited", "angry", "curious", "proud", "sad"],
      answer: 5,
      clue: "Every time I look at her empty seat I feel it already.",
      explanation:
        "3년을 함께한 단짝이 제주로 이사 가고 빈자리를 볼 때마다 벌써 그렇게 느껴진다고 했으므로 여자의 심정은 '슬픈(sad)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예슬아, 교실 문만 계속 보네.",
        "W: 내 단짝이 이번 주 금요일에 제주로 이사 가.",
        "M: 1학년 때부터 네 옆에 앉던 그 친구?",
        "W: 응, 3년 동안 같이 점심 먹었어.",
        "M: 그래도 전화하고 문자할 수 있잖아.",
        "W: 알아, 그래도 똑같진 않을 거야.",
        "M: 금요일까지 아직 사흘 남았어.",
        "W: 그 애 빈자리를 볼 때마다 벌써 그런 기분이 들어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How many books can I check out?"],
        ["M", "Up to five at a time."],
        ["ANN", "Number two."],
        ["W", "Is there a quiet room upstairs?"],
        ["M", "Yes, on the third floor."],
        ["ANN", "Number three."],
        ["W", "Excuse me, your phone is ringing."],
        ["M", "Oh, sorry. I'll step outside."],
        ["ANN", "Number four."],
        ["W", "When is this book due back?"],
        ["M", "In two weeks from today."],
        ["ANN", "Number five."],
        ["W", "Do you have today's newspaper?"],
        ["M", "It's on the rack by the window."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, your phone is ringing.",
      explanation:
        "그림은 도서관 열람실에서 남자의 휴대폰이 울리자 옆자리 여자가 그것을 가리키며 말을 거는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a quiet library reading room, clean black line art on a plain white background, no writing anywhere. " +
          "A man sits at a long table with an open book, and his phone on the table is buzzing with small motion lines around it. " +
          "A woman at the next seat looks up from her book, points at the buzzing phone and speaks to him. " +
          "Tall bookshelves and a window are drawn simply in the background.",
      },
      translation: [
        "① W: 책을 몇 권까지 빌릴 수 있나요? / M: 한 번에 다섯 권까지요.",
        "② W: 위층에 조용한 방이 있나요? / M: 네, 3층에 있어요.",
        "③ W: 저기요, 휴대폰이 울려요. / M: 아, 죄송합니다. 밖으로 나갈게요.",
        "④ W: 이 책은 언제까지 반납해요? / M: 오늘부터 2주 뒤에요.",
        "⑤ W: 오늘 신문 있나요? / M: 창가 거치대에 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeseul, you have neat handwriting, don't you?"],
        ["W", "People say so. Why do you ask?"],
        ["M", "Our class is making a thank-you card for the nurse."],
        ["W", "The one who took care of us during the flu week?"],
        ["M", "That's her. Everyone wrote a line on rough paper."],
        ["W", "So the card itself is still empty?"],
        ["M", "Right. Could you copy all the lines onto the card?"],
        ["W", "Of course. I'll do it during lunch tomorrow."],
      ],
      choices: ["카드에 글씨 옮겨 쓰기", "카드 사 오기", "보건 선생님께 드리기", "그림 그리기", "문구 만들어 주기"],
      answer: 1,
      clue: "Right. Could you copy all the lines onto the card?",
      explanation:
        "남자는 친구들이 쓴 문장을 감사 카드에 옮겨 써 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 예슬아, 너 글씨 예쁘지?",
        "W: 다들 그렇게 말해. 왜 물어봐?",
        "M: 우리 반이 보건 선생님께 감사 카드를 만들어.",
        "W: 독감 돌 때 우리 돌봐 주신 그분?",
        "M: 맞아. 다들 연습지에 한 줄씩 썼어.",
        "W: 그럼 카드는 아직 비어 있는 거야?",
        "M: 응. 그 문장들을 카드에 옮겨 써 줄 수 있어?",
        "W: 그럼. 내일 점심시간에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 헌 옷 나눔에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Our used clothes sharing day is next Thursday. " +
            "It will be held in the first floor lobby all day. " +
            "Bring clothes that are clean and have no holes or stains. " +
            "You may take home up to three items for free. " +
            "Everything left over will go to a shelter in our neighborhood. " +
            "Please help your friends and your closet at the same time.",
        ],
      ],
      choices: ["열리는 날", "열리는 장소", "가져올 옷의 상태", "참가 학년", "가져갈 수 있는 개수"],
      answer: 4,
      clue: "참가 학년은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 목요일), 장소(1층 로비), 가져올 옷의 상태(깨끗하고 구멍·얼룩 없는 것), 가져갈 수 있는 개수(세 벌)는 언급되지만 참가 학년은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 헌 옷 나눔의 날이 다음 주 목요일에 열립니다. 1층 로비에서 하루 종일 진행됩니다. 깨끗하고 구멍이나 얼룩이 없는 옷을 가져오세요. 최대 세 벌까지 무료로 가져갈 수 있습니다. 남은 것은 모두 우리 동네 보호 시설로 보냅니다. 친구도 돕고 옷장도 정리해 보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a machine you see beside the road in almost every neighborhood. " +
            "You put coins or a card in the slot and press a number. " +
            "Then something falls down into a small opening near the bottom. " +
            "Most of them sell cold drinks, and some of them sell hot ones too. " +
            "They work day and night, even when every shop is closed.",
        ],
      ],
      choices: ["현금 인출기", "자동판매기", "세탁기", "신호등", "공중전화"],
      answer: 2,
      clue: "You put coins or a card in the slot and press a number.",
      explanation:
        "동전이나 카드를 넣고 번호를 누르면 아래 구멍으로 물건이 떨어지며 대개 찬 음료를 파는 것은 자동판매기이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이것은 거의 모든 동네의 길가에서 볼 수 있는 기계입니다. 투입구에 동전이나 카드를 넣고 번호를 누릅니다. 그러면 아래쪽 작은 구멍으로 무언가가 떨어집니다. 대부분 찬 음료를 팔고, 어떤 것은 따뜻한 것도 팝니다. 모든 가게가 문을 닫은 때에도 밤낮으로 작동합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was your weekend?"],
        ["W", "I stayed home and read a novel."],
        ["ANN", "Number two."],
        ["M", "Could you hold the door for me?"],
        ["W", "Sure, go ahead."],
        ["ANN", "Number three."],
        ["M", "What are you going to major in?"],
        ["W", "I'm thinking about biology."],
        ["ANN", "Number four."],
        ["M", "Do you need help with those bags?"],
        ["W", "Yes, please. They're heavy."],
        ["ANN", "Number five."],
        ["M", "How long does the bus ride take?"],
        ["W", "My brother is taller than me."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "How long does the bus ride take?",
      explanation:
        "버스로 얼마나 걸리는지 묻는 말에 오빠가 자기보다 크다고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 주말 어땠어? / W: 집에서 소설 읽었어.",
        "② M: 문 좀 잡아 줄래? / W: 그럼, 들어와.",
        "③ M: 뭘 전공할 거야? / W: 생물학을 생각하고 있어.",
        "④ M: 그 가방들 도와줄까? / W: 응, 부탁해. 무거워.",
        "⑤ M: 버스로 얼마나 걸려? / W: 우리 오빠가 나보다 커.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohun, the class art show opens in fifteen minutes."],
        ["M", "I know. Are all the paintings on the wall?"],
        ["W", "Yes, I hung the last one this morning."],
        ["M", "Great. Did anyone write the name cards?"],
        ["W", "I wrote them, but they're still in my desk drawer."],
        ["M", "Without the cards nobody knows whose work it is."],
        ["W", "I have to greet the parents at the door."],
        ["M", "Then I'll get the cards from your drawer and put them up."],
      ],
      choices: ["그림 걸기", "학부모 맞이하기", "이름표 가져와 붙이기", "그림 그리기", "책상 정리하기"],
      answer: 3,
      clue: "Then I'll get the cards from your drawer and put them up.",
      explanation:
        "이름표가 서랍에 있고 여자는 학부모를 맞아야 해서, 남자가 이름표를 가져와 붙이겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 도훈아, 학급 미술 전시가 15분 뒤에 열려.",
        "M: 알아. 그림은 다 벽에 걸었어?",
        "W: 응, 오늘 아침에 마지막 것까지 걸었어.",
        "M: 잘했다. 이름표는 누가 썼어?",
        "W: 내가 썼는데, 아직 내 책상 서랍에 있어.",
        "M: 이름표가 없으면 누구 작품인지 모르잖아.",
        "W: 나는 문에서 학부모님들을 맞아야 해.",
        "M: 그럼 내가 네 서랍에서 이름표 가져와서 붙일게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 책상을 고르시오.",
      lines: [
        ["M", "Yeseul, which desk are you going to buy?"],
        ["W", "Let me look at the five of them again."],
        ["M", "Do you need drawers under the top?"],
        ["W", "Yes, I keep all my notebooks in drawers."],
        ["M", "Okay. How wide can the desk be?"],
        ["W", "A hundred twenty centimeters at most. My room is small."],
        ["M", "Got it. And how much can you spend?"],
        ["W", "Under a hundred fifty thousand won."],
        ["M", "Then only one desk on this list fits you."],
        ["W", "Good. Let's order it after dinner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Yes, I keep all my notebooks in drawers.",
      explanation:
        "서랍이 있고, 너비 120cm 이하이며, 15만 원 미만인 것을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Drawers: Yes / Width: 110 cm / Price: 145,000 won" },
          { no: 2, label: "②", value: "Drawers: Yes / Width: 140 cm / Price: 130,000 won" },
          { no: 3, label: "③", value: "Drawers: No / Width: 110 cm / Price: 90,000 won" },
          { no: 4, label: "④", value: "Drawers: Yes / Width: 120 cm / Price: 175,000 won" },
          { no: 5, label: "⑤", value: "Drawers: No / Width: 120 cm / Price: 120,000 won" },
        ],
      },
      translation: [
        "M: 예슬아, 어떤 책상 살 거야?",
        "W: 다섯 개 다시 볼게.",
        "M: 상판 아래 서랍이 필요해?",
        "W: 응, 공책을 다 서랍에 넣어 둬.",
        "M: 알겠어. 책상 너비는 얼마까지 돼?",
        "W: 최대 120센티미터. 내 방이 좁아.",
        "M: 그렇구나. 얼마까지 쓸 수 있어?",
        "W: 15만 원 미만.",
        "M: 그럼 이 목록에서 맞는 건 하나뿐이야.",
        "W: 좋아. 저녁 먹고 주문하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 도서관에 봉사하러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Yeseul, when can we help at the city library?"],
        ["W", "How about June 3rd? That's next Wednesday."],
        ["M", "The library is closed every first Wednesday."],
        ["W", "Then what about June 6th?"],
        ["M", "My cousin's graduation is on the 6th."],
        ["W", "Hmm. I'm free on June 13th."],
        ["M", "But the volunteer program ends on the 10th."],
        ["W", "Oh, right. Then let's go on June 8th."],
        ["M", "June 8th works. It's a Monday, and school ends early."],
        ["W", "Perfect. Let's meet at the front gate at two."],
      ],
      choices: ["6월 3일", "6월 6일", "6월 10일", "6월 8일", "6월 13일"],
      answer: 4,
      clue: "Oh, right. Then let's go on June 8th.",
      explanation:
        "3일은 첫째 수요일 휴관이고, 6일에는 졸업식이 있으며, 13일은 프로그램이 끝난 뒤다. 두 사람은 6월 8일에 가기로 한다. 따라서 답은 ④이다.",
      translation: [
        "M: 예슬아, 시립 도서관 봉사 언제 갈까?",
        "W: 6월 3일 어때? 다음 주 수요일이야.",
        "M: 도서관은 첫째 수요일마다 문을 닫아.",
        "W: 그럼 6월 6일은?",
        "M: 6일에 사촌 졸업식이 있어.",
        "W: 음. 나는 6월 13일이 비어.",
        "M: 그런데 봉사 프로그램이 10일에 끝나.",
        "W: 아, 맞다. 그럼 6월 8일에 가자.",
        "M: 6월 8일 괜찮아. 월요일이라 학교가 일찍 끝나.",
        "W: 좋아. 2시에 정문에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohun, why are your shoulders so stiff today?"],
        ["M", "I was at the community center all Saturday."],
        ["W", "Did you take a class there?"],
        ["M", "No, we carried boxes of rice up to the fifth floor."],
        ["W", "Was the elevator broken?"],
        ["M", "Yes, so twelve of us used the stairs all afternoon."],
        ["W", "How many boxes did you move?"],
        ["M", "Sixty, and each one weighed ten kilograms."],
      ],
      choices: ["수업 듣기", "쌀 상자 옮기기", "엘리베이터 고치기", "계단 청소하기", "쌀 나눠 주기"],
      answer: 2,
      clue: "No, we carried boxes of rice up to the fifth floor.",
      explanation:
        "남자는 토요일에 주민 센터에서 쌀 상자 예순 개를 5층까지 계단으로 옮겼다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 도훈아, 오늘 어깨가 왜 이렇게 굳었어?",
        "M: 토요일 내내 주민 센터에 있었어.",
        "W: 거기서 수업 들었어?",
        "M: 아니, 쌀 상자를 5층까지 날랐어.",
        "W: 엘리베이터가 고장 났어?",
        "M: 응, 그래서 열두 명이 오후 내내 계단을 썼어.",
        "W: 상자를 몇 개나 옮겼어?",
        "M: 예순 개. 한 개에 10킬로그램이었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school office. " +
            "The photo club has lost a camera bag since yesterday afternoon. " +
            "It is black with a yellow strap and a small name tag. " +
            "If you have seen it anywhere, please come to the office. " +
            "There is a memory card inside with a whole year of club photos. " +
            "Thank you for your help.",
        ],
      ],
      choices: [
        "사진 동아리 가입을 권하려고",
        "사진 대회를 안내하려고",
        "카메라 대여를 안내하려고",
        "분실물 보관 장소를 알리려고",
        "잃어버린 물건을 찾으려고",
      ],
      answer: 5,
      clue: "If you have seen it anywhere, please come to the office.",
      explanation:
        "사진 동아리가 잃어버린 카메라 가방을 본 사람은 행정실로 와 달라고 하는 방송이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실입니다. 사진 동아리가 어제 오후부터 카메라 가방을 잃어버렸습니다. 검은색이고 노란 끈과 작은 이름표가 달려 있습니다. 어디서든 보신 분은 행정실로 와 주세요. 안에 1년치 동아리 사진이 든 메모리 카드가 들어 있습니다. 도와주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the bakery. What would you like today?"],
        ["W", "Two loaves of bread and four rolls, please."],
        ["M", "A loaf is eight dollars and a roll is two."],
        ["W", "So the total is twenty-four dollars."],
        ["M", "That's right. Do you need a paper bag?"],
        ["W", "No, thank you. I brought my own."],
        ["M", "All right. Bringing your own bag gets you two dollars off."],
        ["W", "That's a nice surprise. Here you are."],
      ],
      choices: ["$23", "$24", "$22", "$26", "$28"],
      answer: 3,
      clue: "All right. Bringing your own bag gets you two dollars off.",
      explanation:
        "식빵 2개 16달러와 롤빵 4개 8달러를 더하면 24달러이고, 개인 가방 할인 2달러를 빼면 22달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 빵집에 오신 걸 환영합니다. 오늘은 무엇을 드릴까요?",
        "W: 식빵 두 개랑 롤빵 네 개 주세요.",
        "M: 식빵은 8달러, 롤빵은 2달러입니다.",
        "W: 그럼 모두 24달러네요.",
        "M: 맞습니다. 종이 봉투 필요하세요?",
        "W: 아니요, 괜찮아요. 제 가방 가져왔어요.",
        "M: 알겠습니다. 개인 가방을 가져오시면 2달러 할인됩니다.",
        "W: 뜻밖의 좋은 소식이네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Dohun, you look worried about the math test again."],
        ["M", "I study three hours every night, but my score stays the same."],
        ["W", "What exactly do you do during those three hours?"],
        ["M", "I read the textbook and copy the example problems."],
        ["W", "Copying isn't the same as solving, though."],
        ["M", "But I understand every step while I copy it."],
        ["W", "Understanding while reading feels easy. Doing it alone is different."],
        ["M", "So what should I do instead of copying?"],
        ["W", "Cover the solution and solve the same problem yourself."],
      ],
      choices: [
        "I'll try that tonight.",
        "I never study math.",
        "My score went up already.",
        "Copying is the best way.",
        "Let's skip the test.",
      ],
      answer: 1,
      clue: "Cover the solution and solve the same problem yourself.",
      explanation:
        "여자가 풀이를 가리고 직접 풀어 보라고 했으므로, 오늘 밤에 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 도훈아, 또 수학 시험 때문에 걱정돼 보여.",
        "M: 매일 밤 세 시간씩 공부하는데 점수가 그대로야.",
        "W: 그 세 시간 동안 정확히 뭘 해?",
        "M: 교과서 읽고 예제를 베껴 써.",
        "W: 베껴 쓰는 건 푸는 것과 다르잖아.",
        "M: 그런데 베낄 때 모든 단계가 이해돼.",
        "W: 읽으면서 이해하는 건 쉽게 느껴져. 혼자 푸는 건 달라.",
        "M: 그럼 베끼는 대신 뭘 해야 해?",
        "W: 풀이를 가리고 같은 문제를 직접 풀어 봐.",
        "M: 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yeseul, your bicycle tires look a little flat again."],
        ["W", "I pumped them up only two weeks ago."],
        ["M", "Do you check the pressure before you ride?"],
        ["W", "No, I just squeeze them with my hand."],
        ["M", "Your hand can't tell the difference until it's very low."],
        ["W", "Then how do people check it properly?"],
        ["M", "With a small gauge that costs a few thousand won."],
        ["W", "Is it hard for a beginner to use?"],
        ["M", "Not at all. You press it on the valve and read the number."],
      ],
      choices: [
        "My bicycle has no tires.",
        "I check the pressure daily.",
        "The tires are completely full.",
        "I'll buy one this weekend.",
        "I'll stop riding my bike.",
      ],
      answer: 4,
      clue: "Not at all. You press it on the valve and read the number.",
      explanation:
        "남자가 몇천 원짜리 압력계를 쓰면 된다고 알려 주었으므로, 이번 주말에 하나 사겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 예슬아, 자전거 타이어가 또 좀 빠진 것 같아.",
        "W: 2주 전에 바람 넣었는데.",
        "M: 타기 전에 공기압 확인해?",
        "W: 아니, 그냥 손으로 눌러 봐.",
        "M: 손으로는 많이 빠지기 전까진 차이를 못 느껴.",
        "W: 그럼 다들 어떻게 제대로 확인해?",
        "M: 몇천 원짜리 작은 압력계로.",
        "W: 처음 쓰는 사람도 쉬워?",
        "M: 전혀 안 어려워. 밸브에 대고 눌러서 숫자만 읽으면 돼.",
        "W: 이번 주말에 하나 살게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Dohun, our class recycling project isn't working."],
        ["M", "I know. Half the cans still go in the trash bin."],
        ["W", "We explained the rules at the morning meeting."],
        ["M", "Once, at the start of the term."],
        ["W", "So most people have forgotten by now?"],
        ["M", "Probably, and new students joined in September."],
        ["W", "Then should we explain it again?"],
        ["M", "Explaining alone won't stick. People need a reminder at the bin."],
        ["W", "What kind of reminder do you mean?"],
        ["M", "A picture of a can taped right above the right bin."],
      ],
      choices: [
        "We have no recycling bins.",
        "I'll make the picture tonight.",
        "Everyone remembers the rules.",
        "Let's stop recycling.",
        "The bins were removed.",
      ],
      answer: 2,
      clue: "A picture of a can taped right above the right bin.",
      explanation:
        "남자가 알맞은 통 바로 위에 캔 그림을 붙이자고 했으므로, 오늘 밤에 그림을 만들겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 도훈아, 우리 반 재활용 계획이 잘 안 되고 있어.",
        "M: 맞아. 캔 절반이 아직 쓰레기통으로 가.",
        "W: 아침 조회 때 규칙을 설명했잖아.",
        "M: 학기 초에 한 번.",
        "W: 그럼 이제 대부분 잊어버렸겠네?",
        "M: 아마도. 그리고 9월에 새로 온 학생들도 있어.",
        "W: 그럼 다시 설명해야 할까?",
        "M: 설명만으론 안 남아. 통 앞에서 떠올릴 게 필요해.",
        "W: 어떤 걸 말하는 거야?",
        "M: 알맞은 통 바로 위에 캔 그림을 붙이는 거.",
        "W: 오늘 밤에 그림 만들게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Hajin이 Seowoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Hajin : ________________",
      lines: [
        [
          "M",
          "Hajin and Seowoo are walking out of the school library together. " +
            "Seowoo has three thick books stacked in her arms. " +
            "Hajin sees that the top book has not been stamped at the desk. " +
            "The alarm at the door goes off for any book that is not checked out. " +
            "He wants to tell her before she walks through the gate. " +
            "In this situation, what would Hajin most likely say to Seowoo?",
        ],
      ],
      choices: [
        "Let's read the book together.",
        "I'll carry the books for you.",
        "The library closed an hour ago.",
        "You should borrow fewer books.",
        "You forgot to check that book out.",
      ],
      answer: 5,
      clue: "Hajin sees that the top book has not been stamped at the desk.",
      explanation:
        "서우가 대출 처리를 안 한 책을 들고 문을 지나려 하므로, 대출을 안 했다고 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "M: 하진이와 서우는 함께 학교 도서관을 나서고 있습니다. 서우는 두꺼운 책 세 권을 팔에 쌓아 들고 있습니다. 하진이는 맨 위 책이 대출대에서 처리되지 않은 것을 봅니다. 대출하지 않은 책이 있으면 문에서 경보가 울립니다. 하진이는 서우가 문을 지나기 전에 알려 주고 싶습니다. 이런 상황에서 하진이가 서우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
