/** 중2 듣기 25회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 25회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 책가방을 고르시오.",
      lines: [
        ["W", "Welcome. Are you looking for a school bag?"],
        ["M", "Yes, mine tore along the bottom seam."],
        ["W", "We have bags that open from the top and from the front."],
        ["M", "From the front, please. I can reach my books faster."],
        ["W", "All right. This front-opening bag has a fabric handle."],
        ["M", "A fabric handle wears out too quickly for me."],
        ["W", "Then here is one with a hard plastic handle."],
        ["M", "That's the one. I'll take the plastic handle bag."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "From the front, please. / I'll take the plastic handle bag.",
      explanation:
        "남자는 앞으로 여는 가방을 원하고, 천 손잡이 대신 단단한 플라스틱 손잡이를 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five school backpacks drawn side by side as five choices, clean black line art on white. " +
          "① a backpack with a FRONT FLAP that opens forward and a soft FABRIC LOOP handle on top. " +
          "② a backpack with a FRONT FLAP that opens forward and a thick HARD PLASTIC BAR handle on top. " +
          "③ a backpack with a TOP ZIPPER that opens upward and a soft FABRIC LOOP handle on top. " +
          "④ a backpack with a TOP ZIPPER that opens upward and a thick HARD PLASTIC BAR handle on top. " +
          "⑤ a backpack with a FRONT FLAP that opens forward and NO handle on top at all.",
      },
      translation: [
        "W: 어서 오세요. 책가방 찾으세요?",
        "M: 네, 쓰던 게 바닥 박음질이 뜯어졌어요.",
        "W: 위로 여는 것도 있고 앞으로 여는 것도 있어요.",
        "M: 앞으로 여는 걸로 주세요. 책을 더 빨리 꺼낼 수 있어서요.",
        "W: 알겠습니다. 이 앞으로 여는 가방은 손잡이가 천이에요.",
        "M: 천 손잡이는 저한테 너무 빨리 닳아요.",
        "W: 그럼 단단한 플라스틱 손잡이가 달린 게 여기 있어요.",
        "M: 그거예요. 플라스틱 손잡이 가방으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 뮤지컬 공연에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dain, is your class putting on the musical this year?"],
        ["W", "Yes, we perform on the last Friday of this month."],
        ["M", "Where will it be held?"],
        ["W", "In the main auditorium on the fourth floor."],
        ["M", "How long does the whole show run?"],
        ["W", "About fifty minutes, with one short break."],
        ["M", "Do I need a ticket to come in?"],
        ["W", "Yes, you pick one up at the student council room."],
        ["M", "Then I'll get one tomorrow morning."],
      ],
      choices: ["공연 날짜", "공연 장소", "공연 시간", "입장 방법", "출연 인원"],
      answer: 5,
      clue: "출연 인원은 대화에서 언급되지 않았다.",
      explanation:
        "공연 날짜(이달 마지막 금요일), 장소(4층 대강당), 시간(약 50분), 입장 방법(학생회실에서 표 받기)은 언급되지만 출연 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 올해 너희 반이 뮤지컬 해?",
        "W: 응, 이달 마지막 금요일에 공연해.",
        "M: 어디서 해?",
        "W: 4층 대강당에서.",
        "M: 전체 공연은 얼마나 해?",
        "W: 짧은 휴식 한 번 넣어서 50분쯤.",
        "M: 들어가려면 표가 필요해?",
        "W: 응, 학생회실에서 받아 가면 돼.",
        "M: 그럼 내일 아침에 받을게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, is this the Hanbyul Bike Shop?"],
        ["M", "Yes, it is. What can I do for you?"],
        ["W", "I bought a helmet from you last Saturday."],
        ["M", "Is something wrong with it?"],
        ["W", "The strap is too short for my head."],
        ["M", "I see. Would you like a bigger size?"],
        ["W", "Yes, can I exchange it if I bring the receipt?"],
        ["M", "Of course. Come anytime before Friday."],
      ],
      choices: [
        "헬멧을 새로 사려고",
        "헬멧을 다른 치수로 바꾸려고",
        "자전거를 수리하려고",
        "가게 위치를 물어보려고",
        "영수증을 다시 받으려고",
      ],
      answer: 2,
      clue: "Yes, can I exchange it if I bring the receipt?",
      explanation:
        "여자는 끈이 짧은 헬멧을 더 큰 치수로 바꿀 수 있는지 물으려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "W: 여보세요, 한별 자전거 가게죠?",
        "M: 네, 맞습니다. 무엇을 도와드릴까요?",
        "W: 지난 토요일에 거기서 헬멧을 샀어요.",
        "M: 무슨 문제가 있나요?",
        "W: 끈이 제 머리에 너무 짧아요.",
        "M: 그렇군요. 더 큰 치수로 드릴까요?",
        "W: 네, 영수증 가져가면 바꿀 수 있나요?",
        "M: 물론이죠. 금요일 전에 아무 때나 오세요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Dain, what time does the market close on Sunday?"],
        ["W", "The stalls close at six in the evening."],
        ["M", "Then we shouldn't go too late."],
        ["W", "Right. The best bread is gone by five."],
        ["M", "How long do we need to look around?"],
        ["W", "Two hours at least. It's a very big market."],
        ["M", "Then let's meet two hours before the bread runs out."],
        ["W", "Good. I'll wait at the north gate."],
        ["M", "I'll bring a cloth bag for the fruit."],
      ],
      choices: ["2:00 p.m.", "3:00 p.m.", "4:00 p.m.", "5:00 p.m.", "6:00 p.m."],
      answer: 2,
      clue: "Then let's meet two hours before the bread runs out.",
      explanation:
        "좋은 빵이 5시면 다 떨어지는데 그보다 두 시간 전에 만나기로 했으므로 만나는 시각은 3시이다. 따라서 답은 ②이다.",
      translation: [
        "M: 다인아, 일요일에 시장 몇 시에 닫아?",
        "W: 가게들은 저녁 6시에 닫아.",
        "M: 그럼 너무 늦게 가면 안 되겠네.",
        "W: 맞아. 맛있는 빵은 5시면 다 나가.",
        "M: 둘러보는 데 얼마나 걸려?",
        "W: 적어도 두 시간. 시장이 아주 커.",
        "M: 그럼 빵 떨어지기 두 시간 전에 만나자.",
        "W: 좋아. 나는 북문에서 기다릴게.",
        "M: 나는 과일 담을 천 가방 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sihoon, you've been staring at the window all class."],
        ["M", "My dog had surgery at the animal hospital this morning."],
        ["W", "Oh no. Was it serious?"],
        ["M", "He swallowed a small toy last night."],
        ["W", "Did the doctor say anything yet?"],
        ["M", "They said they would call when it was over."],
        ["W", "And they haven't called?"],
        ["M", "Not for three hours. I keep checking my phone."],
      ],
      choices: ["proud", "bored", "thankful", "anxious", "excited"],
      answer: 4,
      clue: "Not for three hours. I keep checking my phone.",
      explanation:
        "수술 중인 강아지 소식을 세 시간째 못 듣고 계속 휴대폰을 확인한다고 했으므로 남자의 심정은 '불안한(anxious)'이다. 따라서 답은 ④이다.",
      translation: [
        "W: 시훈아, 수업 내내 창밖만 보네.",
        "M: 오늘 아침에 우리 강아지가 동물병원에서 수술했어.",
        "W: 어떡해. 많이 아팠어?",
        "M: 어젯밤에 작은 장난감을 삼켰어.",
        "W: 의사 선생님이 뭐라고 하셨어?",
        "M: 끝나면 전화 주신다고 하셨어.",
        "W: 그런데 아직 전화가 안 왔어?",
        "M: 세 시간째. 계속 휴대폰만 보고 있어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much is this plant?"],
        ["M", "Eight dollars for the small one."],
        ["ANN", "Number two."],
        ["W", "Does this flower need much water?"],
        ["M", "Only twice a week."],
        ["ANN", "Number three."],
        ["W", "Can I take a photo of the garden?"],
        ["M", "Yes, please go ahead."],
        ["ANN", "Number four."],
        ["W", "Where should I put this empty pot?"],
        ["M", "On the shelf by the door."],
        ["ANN", "Number five."],
        ["W", "Watch out, the branch is about to fall."],
        ["M", "Thanks, I'll step back."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Watch out, the branch is about to fall.",
      explanation:
        "그림은 정원에서 남자가 서 있는 머리 위로 큰 나뭇가지가 부러져 내려오려 하고, 여자가 그것을 가리키며 소리치는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "In a garden next to a large tree, clean black line art on a plain white background, no writing anywhere. " +
          "A thick branch high on the tree has cracked and is bending down toward a man standing below it. " +
          "A woman a few steps away points up at the cracked branch and shouts to warn him. " +
          "A watering can and a few flower pots are drawn simply on the ground.",
      },
      translation: [
        "① W: 이 화초 얼마예요? / M: 작은 건 8달러입니다.",
        "② W: 이 꽃은 물이 많이 필요한가요? / M: 일주일에 두 번이면 돼요.",
        "③ W: 정원 사진 찍어도 되나요? / M: 네, 찍으세요.",
        "④ W: 이 빈 화분은 어디에 둘까요? / M: 문 옆 선반에요.",
        "⑤ W: 조심하세요, 나뭇가지가 떨어지려고 해요. / M: 고마워요, 뒤로 물러날게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, are you going to the art room this afternoon?"],
        ["W", "Yes, I have club practice there until five."],
        ["M", "I left my sketchbook on the back table yesterday."],
        ["W", "Did you check the lost and found?"],
        ["M", "I did, but it wasn't there."],
        ["W", "It's probably still under the paint boxes."],
        ["M", "Could you look for it and bring it to me?"],
        ["W", "Sure. I'll text you as soon as I find it."],
      ],
      choices: ["그림 그려 주기", "분실물 신고하기", "물감 빌려주기", "동아리 대신 가기", "스케치북 찾아다 주기"],
      answer: 5,
      clue: "Could you look for it and bring it to me?",
      explanation:
        "남자는 미술실에 두고 온 스케치북을 찾아서 가져다 달라고 부탁했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 오늘 오후에 미술실 가?",
        "W: 응, 5시까지 동아리 연습 있어.",
        "M: 어제 뒤쪽 탁자에 스케치북을 두고 왔어.",
        "W: 분실물 보관함은 확인했어?",
        "M: 했는데 거기 없었어.",
        "W: 아마 물감 상자 밑에 있을 거야.",
        "M: 좀 찾아서 갖다줄 수 있어?",
        "W: 그럼. 찾자마자 문자할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 마라톤 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Our school marathon will be held next Thursday. " +
            "Everyone will start together at the front gate at nine. " +
            "The course runs five kilometers along the river path and back. " +
            "Water will be handed out at the halfway point near the bridge. " +
            "Wear running shoes and a hat, and leave your bag in the classroom. " +
            "Let's all finish the course together.",
        ],
      ],
      choices: ["열리는 날", "출발 장소", "달리는 거리", "준비물", "우승 상품"],
      answer: 5,
      clue: "우승 상품은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 목요일), 출발 장소(정문), 거리(5킬로미터), 준비물(운동화와 모자)은 언급되지만 우승 상품은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 학교 마라톤이 다음 주 목요일에 열립니다. 모두 9시에 정문에서 함께 출발합니다. 강변길을 따라 5킬로미터를 달렸다가 돌아옵니다. 다리 근처 중간 지점에서 물을 나눠 드립니다. 운동화와 모자를 착용하고 가방은 교실에 두세요. 다 함께 완주해 봅시다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is something almost every student keeps in a school bag. " +
            "It is flat and round and fits in the palm of your hand. " +
            "You open the lid and press it onto a red ink pad first. " +
            "Then you press it onto a paper to leave your name behind. " +
            "Adults use one instead of signing important documents in Korea.",
        ],
      ],
      choices: ["도장", "지우개", "자", "돋보기", "풀"],
      answer: 1,
      clue: "Then you press it onto a paper to leave your name behind.",
      explanation:
        "빨간 인주에 찍은 뒤 종이에 눌러 이름을 남기고, 어른들이 서명 대신 쓰는 것은 도장이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 거의 모든 학생이 가방에 하나씩 가지고 있는 것입니다. 납작하고 둥글며 손바닥 안에 들어옵니다. 뚜껑을 열고 먼저 빨간 인주에 눌러 찍습니다. 그다음 종이에 눌러 이름을 남깁니다. 한국에서는 어른들이 중요한 서류에 서명 대신 이것을 씁니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What do you usually do on Sundays?"],
        ["W", "I go hiking with my father."],
        ["ANN", "Number two."],
        ["M", "Which floor is the science room on?"],
        ["W", "It's on the third floor."],
        ["ANN", "Number three."],
        ["M", "Have you ever been to Japan?"],
        ["W", "The soup tastes a little salty."],
        ["ANN", "Number four."],
        ["M", "Could I borrow your calculator?"],
        ["W", "Sure, here you go."],
        ["ANN", "Number five."],
        ["M", "Why didn't you come yesterday?"],
        ["W", "I had a bad cold."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Have you ever been to Japan?",
      explanation:
        "일본에 가 본 적이 있는지 묻는 말에 국이 좀 짜다고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 일요일에는 보통 뭐 해? / W: 아버지랑 등산 가.",
        "② M: 과학실이 몇 층이야? / W: 3층에 있어.",
        "③ M: 일본에 가 본 적 있어? / W: 국이 좀 짜네.",
        "④ M: 네 계산기 빌려도 돼? / W: 그럼, 여기.",
        "⑤ M: 어제 왜 안 왔어? / W: 감기가 심했어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, the school broadcast starts in fifteen minutes."],
        ["W", "I know. The script is printed and on the desk."],
        ["M", "Good. Did you test the microphone in the booth?"],
        ["W", "Yes, and it sounds clear today."],
        ["M", "Great. But the studio light is still red."],
        ["W", "That means the door isn't shut all the way."],
        ["M", "I have to call the teacher about the notice."],
        ["W", "Then I'll go and close the studio door properly."],
      ],
      choices: ["대본 인쇄하기", "마이크 점검하기", "선생님께 전화하기", "스튜디오 문 닫기", "방송 원고 쓰기"],
      answer: 4,
      clue: "Then I'll go and close the studio door properly.",
      explanation:
        "문이 제대로 닫히지 않아 불이 빨간데 남자는 선생님께 전화해야 해서, 여자가 가서 스튜디오 문을 제대로 닫겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 다인아, 학교 방송이 15분 뒤에 시작해.",
        "W: 알아. 대본은 인쇄해서 책상에 뒀어.",
        "M: 잘했다. 부스 마이크는 점검했어?",
        "W: 응, 오늘은 소리가 깨끗해.",
        "M: 좋아. 그런데 스튜디오 불이 아직 빨간색이야.",
        "W: 문이 끝까지 안 닫혔다는 뜻이야.",
        "M: 나는 공지 때문에 선생님께 전화해야 해.",
        "W: 그럼 내가 가서 스튜디오 문을 제대로 닫을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 구입할 운동화를 고르시오.",
      lines: [
        ["W", "Sihoon, which running shoes are you buying?"],
        ["M", "Let me check the list again."],
        ["W", "Do you want laces or a strap?"],
        ["M", "Laces, please. Straps come loose when I run."],
        ["W", "Okay. What's your budget?"],
        ["M", "Under seventy thousand won, including the tax."],
        ["W", "Got it. Does the weight matter to you?"],
        ["M", "Yes, I want the light ones. Heavy shoes tire me out."],
        ["W", "Then only one pair on this list is right."],
        ["M", "Good. Let's order them tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Laces, please. Straps come loose when I run.",
      explanation:
        "끈이 있고, 7만 원 미만이며, 가벼운 것을 고른다. 세 조건을 모두 채우는 것은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Close: Laces / Price: 75,000 won / Weight: Light" },
          { no: 2, label: "②", value: "Close: Strap / Price: 60,000 won / Weight: Light" },
          { no: 3, label: "③", value: "Close: Laces / Price: 65,000 won / Weight: Light" },
          { no: 4, label: "④", value: "Close: Laces / Price: 55,000 won / Weight: Heavy" },
          { no: 5, label: "⑤", value: "Close: Strap / Price: 50,000 won / Weight: Heavy" },
        ],
      },
      translation: [
        "W: 시훈아, 어떤 운동화 살 거야?",
        "M: 목록 다시 볼게.",
        "W: 끈이 좋아, 벨크로가 좋아?",
        "M: 끈으로. 벨크로는 뛸 때 풀려.",
        "W: 알겠어. 예산은?",
        "M: 세금 포함해서 7만 원 미만.",
        "W: 그렇구나. 무게도 중요해?",
        "M: 응, 가벼운 게 좋아. 무거운 신발은 금방 지쳐.",
        "W: 그럼 이 목록에서 맞는 건 하나뿐이야.",
        "M: 좋아. 오늘 밤에 주문하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 책을 기증하러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Sihoon, when can we take the books to the library?"],
        ["M", "How about January 7th? That's next Tuesday."],
        ["W", "I have a piano exam that whole afternoon."],
        ["M", "Then what about January 9th?"],
        ["W", "The library is closed on the second Thursday."],
        ["M", "Hmm. I'm free on January 15th."],
        ["W", "But the donation drive ends on the 13th."],
        ["M", "You're right. Then January 11th is our last chance."],
        ["W", "That works. It's a Saturday, so we have all day."],
        ["M", "Great. Let's borrow my brother's cart for the boxes."],
      ],
      choices: ["1월 7일", "1월 9일", "1월 11일", "1월 13일", "1월 15일"],
      answer: 3,
      clue: "You're right. Then January 11th is our last chance.",
      explanation:
        "7일에는 피아노 시험이, 9일에는 휴관이 있고 기증 행사는 13일에 끝난다. 두 사람은 1월 11일에 가기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 시훈아, 책을 도서관에 언제 가져갈까?",
        "M: 1월 7일 어때? 다음 주 화요일이야.",
        "W: 그날 오후 내내 피아노 시험이 있어.",
        "M: 그럼 1월 9일은?",
        "W: 도서관은 둘째 목요일에 문을 닫아.",
        "M: 음. 나는 1월 15일이 비어.",
        "W: 그런데 기증 행사가 13일에 끝나.",
        "M: 맞네. 그럼 1월 11일이 마지막 기회야.",
        "W: 괜찮아. 토요일이라 하루 종일 시간 돼.",
        "M: 좋아. 상자 옮길 우리 형 수레 빌리자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, why is your voice so rough today?"],
        ["W", "I read aloud for six hours on Saturday."],
        ["M", "Six hours? Were you practicing for a contest?"],
        ["W", "No, I recorded audio books for blind students."],
        ["M", "I didn't know our school did that."],
        ["W", "A city center does it. Ten of us went together."],
        ["M", "How many books did you finish?"],
        ["W", "Two short ones, and my throat is still sore."],
      ],
      choices: ["웅변 연습하기", "책 읽어 녹음하기", "도서관 청소하기", "독서 대회 나가기", "책 정리하기"],
      answer: 2,
      clue: "No, I recorded audio books for blind students.",
      explanation:
        "여자는 토요일에 시각 장애 학생을 위한 오디오북을 여섯 시간 동안 녹음했다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 다인아, 오늘 목소리가 왜 이렇게 갈라져?",
        "W: 토요일에 여섯 시간 동안 소리 내서 읽었어.",
        "M: 여섯 시간? 대회 연습했어?",
        "W: 아니, 시각 장애 학생들을 위한 오디오북을 녹음했어.",
        "M: 우리 학교에서 그런 걸 하는 줄 몰랐어.",
        "W: 시에서 운영하는 센터에서 해. 열 명이 같이 갔어.",
        "M: 몇 권이나 끝냈어?",
        "W: 짧은 책 두 권. 아직 목이 아파.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement from the science department. " +
            "The weather forecast says heavy rain will start this afternoon. " +
            "Because of this, tomorrow's outdoor field trip has been cancelled. " +
            "We will hold a science quiz in the gym instead, at the same hour. " +
            "You do not need to bring a lunch box or an umbrella. " +
            "Thank you, and please tell your classmates.",
        ],
      ],
      choices: [
        "과학 퀴즈 참가를 권하려고",
        "우산을 챙기라고 당부하려고",
        "체육관 사용 규칙을 알리려고",
        "현장 학습 취소를 알리려고",
        "도시락 신청을 안내하려고",
      ],
      answer: 4,
      clue: "Because of this, tomorrow's outdoor field trip has been cancelled.",
      explanation:
        "폭우 예보로 내일 야외 현장 학습이 취소되고 대신 체육관에서 과학 퀴즈를 한다고 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 과학부에서 알려 드립니다. 일기예보에 따르면 오늘 오후부터 폭우가 시작됩니다. 이 때문에 내일 야외 현장 학습이 취소되었습니다. 대신 같은 시간에 체육관에서 과학 퀴즈를 진행합니다. 도시락이나 우산은 가져오지 않아도 됩니다. 감사합니다. 친구들에게도 알려 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you ordering for the whole group?"],
        ["W", "Yes, four sandwiches and two bottles of juice."],
        ["M", "A sandwich is seven dollars and a juice is three."],
        ["W", "So the total comes to thirty-four dollars."],
        ["M", "That's right. Are you eating here or taking it out?"],
        ["W", "Taking it out, please."],
        ["M", "All right. Takeout orders get four dollars off today."],
        ["W", "That's a nice surprise. Here you are."],
      ],
      choices: ["$30", "$31", "$32", "$33", "$34"],
      answer: 1,
      clue: "All right. Takeout orders get four dollars off today.",
      explanation:
        "샌드위치 4개 28달러와 주스 2병 6달러를 더하면 34달러이고, 포장 할인 4달러를 빼면 30달러이다. 따라서 답은 ①이다.",
      translation: [
        "M: 안녕하세요. 여러 명 것을 주문하시나요?",
        "W: 네, 샌드위치 네 개랑 주스 두 병이요.",
        "M: 샌드위치는 7달러, 주스는 3달러입니다.",
        "W: 그럼 모두 34달러네요.",
        "M: 맞습니다. 드시고 가세요, 포장하세요?",
        "W: 포장해 주세요.",
        "M: 알겠습니다. 오늘 포장 주문은 4달러 할인됩니다.",
        "W: 뜻밖의 좋은 소식이네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, you've stopped raising your hand in English class."],
        ["W", "I'm afraid of saying something wrong in front of everyone."],
        ["M", "Did something happen last month?"],
        ["W", "I mixed up two words and a few people laughed."],
        ["M", "I remember, but nobody talks about it now."],
        ["W", "It still plays in my head every class."],
        ["M", "The teacher asks easy warm-up questions first."],
        ["W", "So you think I should start with those?"],
        ["M", "Yes, answer one warm-up question each day."],
      ],
      choices: [
        "I'll try one tomorrow.",
        "I answer every question already.",
        "I don't take English class.",
        "The teacher never asks questions.",
        "Let's skip class tomorrow.",
      ],
      answer: 1,
      clue: "Yes, answer one warm-up question each day.",
      explanation:
        "남자가 하루에 준비 질문 하나씩 답해 보라고 했으므로, 내일 하나 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 다인아, 영어 시간에 손을 안 들더라.",
        "W: 다들 앞에서 틀린 말을 할까 봐 무서워.",
        "M: 지난달에 무슨 일 있었어?",
        "W: 단어 두 개를 헷갈렸는데 몇 명이 웃었어.",
        "M: 기억나는데, 지금은 아무도 그 얘기 안 해.",
        "W: 그래도 수업마다 계속 떠올라.",
        "M: 선생님이 처음엔 쉬운 준비 질문을 하시잖아.",
        "W: 그럼 그것부터 시작하라는 거야?",
        "M: 응, 하루에 준비 질문 하나씩만 답해 봐.",
        "W: 내일 하나 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sihoon, your bicycle chain keeps coming off."],
        ["M", "It happens twice a week now."],
        ["W", "When did you last oil the chain?"],
        ["M", "I've never oiled it since I bought the bike."],
        ["W", "A dry chain slips off much more easily."],
        ["M", "I thought the chain was just too old."],
        ["W", "It might be, but oil is worth trying first."],
        ["M", "Where do I get the right kind of oil?"],
        ["W", "Any bike shop sells a small bottle for a few thousand won."],
      ],
      choices: [
        "My bicycle has no chain.",
        "I oiled it this morning.",
        "I'll buy a bottle on the way home.",
        "The chain is brand new.",
        "Let's walk to school instead.",
      ],
      answer: 3,
      clue: "Any bike shop sells a small bottle for a few thousand won.",
      explanation:
        "여자가 자전거 가게에서 기름을 살 수 있다고 했으므로, 집에 가는 길에 한 병 사겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 시훈아, 자전거 체인이 자꾸 빠지네.",
        "M: 요즘 일주일에 두 번은 빠져.",
        "W: 체인에 기름은 마지막으로 언제 쳤어?",
        "M: 자전거 산 뒤로 한 번도 안 쳤어.",
        "W: 마른 체인은 훨씬 쉽게 빠져.",
        "M: 그냥 체인이 오래돼서 그런 줄 알았어.",
        "W: 그럴 수도 있지만 기름부터 쳐 볼 만해.",
        "M: 맞는 기름은 어디서 사?",
        "W: 자전거 가게 아무 데서나 몇천 원이면 작은 병 하나 살 수 있어.",
        "M: 집에 가는 길에 한 병 살게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Sihoon, our class recycling box is always a mess."],
        ["M", "I know. Paper and plastic end up together."],
        ["W", "We put a sign on it last month, though."],
        ["M", "The sign is small and taped inside the box."],
        ["W", "So nobody sees it until they've already dropped something in."],
        ["M", "Exactly. The sign needs to be where people look first."],
        ["W", "Then should we make a bigger one?"],
        ["M", "Bigger, and taped above the box at eye level."],
        ["W", "Do we have poster paper for that?"],
        ["M", "There are three sheets left in the back cupboard."],
      ],
      choices: [
        "I'll make the sign after lunch.",
        "Our class has no recycling box.",
        "The old sign is big enough.",
        "Let's throw the box away.",
        "We ran out of paper last week.",
      ],
      answer: 1,
      clue: "There are three sheets left in the back cupboard.",
      explanation:
        "남자가 뒤쪽 장에 포스터 종이가 세 장 남아 있다고 했으므로, 점심 먹고 표지판을 만들겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 시훈아, 우리 반 재활용 상자가 늘 엉망이야.",
        "M: 맞아. 종이랑 플라스틱이 섞여.",
        "W: 지난달에 안내문을 붙이긴 했잖아.",
        "M: 그 안내문은 작고 상자 안쪽에 붙어 있어.",
        "W: 그러니까 이미 넣고 나서야 보이지.",
        "M: 그래. 안내문은 사람들이 먼저 보는 자리에 있어야 해.",
        "W: 그럼 더 크게 만들까?",
        "M: 더 크게, 그리고 상자 위 눈높이에 붙이자.",
        "W: 그럴 포스터 종이가 있어?",
        "M: 뒤쪽 장에 세 장 남아 있어.",
        "W: 점심 먹고 내가 만들게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yoonseo가 Kyungmin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yoonseo : ________________",
      lines: [
        [
          "W",
          "Yoonseo and Kyungmin are eating lunch in the school cafeteria. " +
            "Kyungmin picks up a bowl of soup and starts walking to their table. " +
            "Yoonseo sees that a wet spot is spreading on the floor ahead of him. " +
            "Someone spilled a drink there only a minute ago. " +
            "She is afraid he will slip with the hot soup in his hands. " +
            "In this situation, what would Yoonseo most likely say to Kyungmin?",
        ],
      ],
      choices: [
        "The soup is too cold today.",
        "Let's sit at another table.",
        "I'll bring you a second bowl.",
        "Careful, the floor is wet there.",
        "Lunch is already finished.",
      ],
      answer: 4,
      clue: "She is afraid he will slip with the hot soup in his hands.",
      explanation:
        "경민이가 뜨거운 국을 든 채 젖은 바닥 쪽으로 걸어가고 있으므로, 바닥이 젖었으니 조심하라고 말하는 ④가 가장 적절하다.",
      translation: [
        "W: 윤서와 경민이는 학교 급식실에서 점심을 먹고 있습니다. 경민이는 국그릇을 들고 자리로 걸어갑니다. 윤서는 경민이 앞쪽 바닥에 물기가 번지고 있는 것을 봅니다. 1분 전에 누군가 거기에 음료를 쏟았습니다. 윤서는 경민이가 뜨거운 국을 든 채 미끄러질까 봐 걱정합니다. 이런 상황에서 윤서가 경민이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
