/** 중2 듣기 46회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 46회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 주문할 티셔츠를 고르시오.",
      lines: [
        ["M", "Yoonji, what design do you want on the class shirt?"],
        ["W", "Something simple that everyone can wear."],
        ["M", "How about a big number on the front?"],
        ["W", "I'd rather put a small picture on the pocket."],
        ["M", "What picture did you have in mind?"],
        ["W", "A little mountain, since we hiked together."],
        ["M", "Do you want writing on the back as well?"],
        ["W", "No writing anywhere. Just the pocket picture."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "A little mountain, since we hiked together. / No writing anywhere. Just the pocket picture.",
      explanation:
        "가슴 주머니에 작은 산 그림만 있고 글자는 없는 티셔츠이다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five plain T-shirts side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a T-shirt with a large blank NUMBER-SHAPED box printed big on the chest. " +
          "② a T-shirt with a small chest POCKET and a tiny SUN drawn on the pocket. " +
          "③ a T-shirt with a small chest POCKET and a tiny MOUNTAIN shape drawn on the pocket, nothing else. " +
          "④ a T-shirt with a tiny MOUNTAIN on the pocket and a blank rectangular LABEL across the back shown beside it. " +
          "⑤ a completely plain T-shirt with no pocket and no picture.",
      },
      translation: [
        "M: 윤지야, 반 티셔츠에 어떤 무늬를 넣을까?",
        "W: 다들 입을 수 있는 단순한 걸로.",
        "M: 앞에 큰 숫자를 넣는 건 어때?",
        "W: 나는 주머니에 작은 그림을 넣는 게 더 좋아.",
        "M: 어떤 그림을 생각했어?",
        "W: 같이 등산했으니까 작은 산.",
        "M: 뒤에도 글자를 넣을까?",
        "W: 글자는 아무 데도 안 넣어. 주머니 그림만.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 봉사 동아리 활동에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hyunwoo, what does your volunteer club actually do?"],
        ["M", "We visit an elderly care center every month."],
        ["W", "How many students go there each time?"],
        ["M", "Six of us, always in the same group."],
        ["W", "What do you do while you are there?"],
        ["M", "We read newspapers aloud and play board games."],
        ["W", "How long do you stay at the center?"],
        ["M", "About two hours on Saturday afternoon."],
        ["W", "Who takes you there from school?"],
        ["M", "Our club teacher drives the school van."],
      ],
      choices: ["가는 인원", "하는 활동", "머무는 시간", "데려다주는 사람", "동아리 가입 방법"],
      answer: 5,
      clue: "Six of us, always in the same group.",
      explanation:
        "인원, 활동, 시간, 이동은 말했지만 가입 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 현우야, 너희 봉사 동아리는 뭘 해?",
        "M: 매달 노인 요양원에 가.",
        "W: 갈 때마다 몇 명이 가?",
        "M: 여섯 명, 늘 같은 조로.",
        "W: 거기서 뭘 해?",
        "M: 신문을 소리 내어 읽어 드리고 판 놀이를 해.",
        "W: 얼마나 머물러?",
        "M: 토요일 오후에 두 시간쯤.",
        "W: 학교에서 거기까지는 누가 데려다줘?",
        "M: 동아리 선생님이 학교 승합차를 운전하셔.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Come in. You look like you're in a hurry."],
        ["W", "I ran all the way from the second floor."],
        ["M", "Take a breath first. What is it?"],
        ["W", "It's about the English speech contest."],
        ["M", "The one being held next Wednesday?"],
        ["W", "I put my name down two weeks ago."],
        ["M", "Yes, you're third on the list."],
        ["W", "My family has a wedding that afternoon."],
        ["M", "So you can't be here at that time."],
        ["W", "I came to ask if I can change my turn."],
      ],
      choices: [
        "대회에 등록하려고",
        "발표 순서를 바꾸려고",
        "상담을 받으려고",
        "자료를 빌리려고",
        "결과를 물어보려고",
      ],
      answer: 2,
      clue: "I came to ask if I can change my turn.",
      explanation:
        "여자는 발표 순서를 바꿀 수 있는지 물으러 왔다. 따라서 답은 ②이다.",
      translation: [
        "M: 들어와. 급해 보이는구나.",
        "W: 2층에서부터 뛰어왔어요.",
        "M: 숨부터 돌리렴. 무슨 일이니?",
        "W: 영어 말하기 대회 때문이에요.",
        "M: 다음 주 수요일에 하는 그거?",
        "W: 두 주 전에 이름을 적었어요.",
        "M: 그래, 명단에 세 번째구나.",
        "W: 그날 오후에 집안 결혼식이 있어요.",
        "M: 그럼 그 시간에 여기 있을 수 없겠구나.",
        "W: 제 순서를 바꿀 수 있는지 여쭈러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 모일 시각을 고르시오.",
      lines: [
        ["M", "Sian, when does the club room open tomorrow?"],
        ["W", "The caretaker unlocks it at one o'clock."],
        ["M", "Our poster work will take about two hours."],
        ["W", "The room has to be empty by four."],
        ["M", "Then starting at one is the safest."],
        ["W", "I have a dental appointment until one thirty."],
        ["M", "So one thirty is the earliest for you."],
        ["W", "Let's all meet at one thirty then."],
        ["M", "I'll bring the paper and the markers."],
      ],
      choices: ["1:00 p.m.", "1:30 p.m.", "2:00 p.m.", "3:00 p.m.", "4:00 p.m."],
      answer: 2,
      clue: "Let's all meet at one thirty then.",
      explanation:
        "여자의 치과 예약이 1시 30분에 끝나 그때 모이기로 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 시안아, 내일 동아리방 몇 시에 열어?",
        "W: 관리 선생님이 한 시에 열어 주셔.",
        "M: 포스터 작업은 두 시간쯤 걸릴 거야.",
        "W: 네 시까지는 방을 비워야 해.",
        "M: 그럼 한 시에 시작하는 게 제일 안전하지.",
        "W: 나는 한 시 반까지 치과 예약이 있어.",
        "M: 그럼 너한테는 한 시 반이 제일 이르네.",
        "W: 그럼 다 같이 한 시 반에 모이자.",
        "M: 종이랑 색연필은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kangmin, you keep looking at your phone."],
        ["M", "The audition results come out this afternoon."],
        ["W", "For the school musical, right?"],
        ["M", "I sang in front of four teachers last week."],
        ["W", "How do you think it went?"],
        ["M", "My voice cracked on the last note."],
        ["W", "One note doesn't decide everything."],
        ["M", "I can't sit still until I know the result."],
      ],
      choices: ["bored", "angry", "nervous", "satisfied", "sleepy"],
      answer: 3,
      clue: "I can't sit still until I know the result.",
      explanation:
        "결과를 기다리며 가만히 있지 못하고 있으므로 초조한 상태이다. 따라서 답은 ③이다.",
      translation: [
        "W: 강민아, 계속 휴대폰만 보네.",
        "M: 오늘 오후에 오디션 결과가 나와.",
        "W: 학교 뮤지컬 말이지?",
        "M: 지난주에 선생님 네 분 앞에서 노래했어.",
        "W: 어땠던 것 같아?",
        "M: 마지막 음에서 목소리가 갈라졌어.",
        "W: 음 하나로 다 정해지지는 않아.",
        "M: 결과를 알 때까지 가만히 못 있겠어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Excuse me, is this the right platform?"],
        ["M", "Yes, the train comes in five minutes."],
        ["ANN", "Number two."],
        ["W", "Could you watch my bag for a moment?"],
        ["M", "Of course, take your time."],
        ["ANN", "Number three."],
        ["W", "Where can I buy a ticket?"],
        ["M", "The machine is behind you."],
        ["ANN", "Number four."],
        ["W", "Does this train stop at the airport?"],
        ["M", "No, take the blue line."],
        ["ANN", "Number five."],
        ["W", "Is the next train delayed?"],
        ["M", "By about ten minutes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Where can I buy a ticket?",
      explanation:
        "그림은 역에서 표 사는 곳을 물으니 뒤쪽 발매기를 가리키는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a subway station hall, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman with a small bag asks a question to a station staff member, holding out one empty hand. " +
          "The staff member points backward over the woman's shoulder toward a tall ticket machine with a blank screen and buttons. " +
          "Turnstiles and a staircase are drawn simply in the background.",
      },
      translation: [
        "① W: 실례합니다, 여기가 맞는 승강장인가요? / M: 네, 5분 뒤에 열차가 옵니다.",
        "② W: 제 가방 잠깐 봐 주시겠어요? / M: 그럼요, 천천히 다녀오세요.",
        "③ W: 표는 어디서 살 수 있나요? / M: 발매기가 뒤에 있습니다.",
        "④ W: 이 열차가 공항에 서나요? / M: 아니요, 파란색 노선을 타세요.",
        "⑤ W: 다음 열차가 늦나요? / M: 10분쯤요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiyu, you take really careful notes in history."],
        ["W", "I write down everything the teacher says twice."],
        ["M", "I missed Monday and Tuesday last week."],
        ["W", "Were you sick those two days?"],
        ["M", "I had a bad cold and stayed home."],
        ["W", "We covered two whole chapters then."],
        ["M", "The test next week includes both of them."],
        ["W", "My notebook is in my locker right now."],
        ["M", "Could you lend me your history notes?"],
        ["W", "Take it home and return it tomorrow."],
      ],
      choices: [
        "필기 공책을 빌려주기",
        "함께 공부해 주기",
        "숙제를 대신 내 주기",
        "선생님께 여쭤봐 주기",
        "약을 사다 주기",
      ],
      answer: 1,
      clue: "Could you lend me your history notes?",
      explanation:
        "남자는 역사 필기 공책을 빌려 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 지유야, 너 역사 필기를 정말 꼼꼼히 하더라.",
        "W: 선생님 말씀을 두 번씩 적어.",
        "M: 나 지난주 월요일이랑 화요일에 못 왔어.",
        "W: 그 이틀 동안 아팠어?",
        "M: 감기가 심해서 집에 있었어.",
        "W: 그때 단원 두 개를 나갔어.",
        "M: 다음 주 시험에 둘 다 들어가.",
        "W: 내 공책은 지금 사물함에 있어.",
        "M: 역사 필기 공책 좀 빌려줄 수 있어?",
        "W: 집에 가져갔다가 내일 돌려줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 벼룩시장에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The school flea market opens next Saturday. " +
            "It runs from ten in the morning until two. " +
            "Each class gets one table in the playground. " +
            "You may sell books, clothes and small household items. " +
            "Food and drinks cannot be sold at any table. " +
            "All the money goes to the local children's center.",
        ],
      ],
      choices: ["열리는 시간", "각 반이 받는 것", "팔 수 있는 물건", "팔 수 없는 것", "준비물 대여"],
      answer: 5,
      clue: "It runs from ten in the morning until two.",
      explanation:
        "시간, 탁자, 팔 물건, 금지 품목은 말했지만 준비물 대여는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 다음 주 토요일에 학교 벼룩시장이 열립니다. 오전 열 시부터 두 시까지 진행됩니다. 각 반은 운동장에 탁자 하나씩 받습니다. 책, 옷, 작은 생활용품을 팔 수 있습니다. 어느 탁자에서도 음식과 음료는 팔 수 없습니다. 수익금은 모두 지역 아동 센터에 전달됩니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "You press its keys with both hands to make sound. " +
            "The white keys and the black keys sit side by side. " +
            "It is usually too heavy for one person to carry. " +
            "Beginners learn simple songs with one hand first. " +
            "Many schools keep one in the music room.",
        ],
      ],
      choices: ["기타", "북", "피아노", "바이올린", "플루트"],
      answer: 3,
      clue: "The white keys and the black keys sit side by side.",
      explanation:
        "흰 건반과 검은 건반을 눌러 소리를 내는 악기는 피아노이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 두 손으로 건반을 눌러 소리를 냅니다. 흰 건반과 검은 건반이 나란히 놓여 있습니다. 보통 한 사람이 들기에는 너무 무겁습니다. 처음 배우는 사람은 한 손으로 쉬운 곡부터 칩니다. 많은 학교가 음악실에 한 대를 둡니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What do you want for lunch?"],
        ["W", "Noodles sound good."],
        ["ANN", "Number two."],
        ["M", "How far is the station from here?"],
        ["W", "About ten minutes on foot."],
        ["ANN", "Number three."],
        ["M", "Could you turn down the music?"],
        ["W", "Sorry, I'll make it quieter."],
        ["ANN", "Number four."],
        ["M", "Whose jacket is this?"],
        ["W", "I'll see you next Monday."],
        ["ANN", "Number five."],
        ["M", "Are you coming to practice?"],
        ["W", "Yes, right after dinner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Whose jacket is this?",
      explanation:
        "누구 옷인지 묻는 말에 다음 주에 보자고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 점심 뭐 먹고 싶어? / W: 국수 좋겠다.",
        "② M: 여기서 역까지 얼마나 멀어? / W: 걸어서 10분쯤.",
        "③ M: 음악 소리 좀 줄여 줄래? / W: 미안, 작게 할게.",
        "④ M: 이거 누구 외투야? / W: 다음 주 월요일에 보자.",
        "⑤ M: 연습에 올 거야? / W: 응, 저녁 먹고 바로.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Bomi, the school van leaves in fifteen minutes."],
        ["W", "I've already put my bag by the door."],
        ["M", "Did you sign the permission form for the trip?"],
        ["W", "My mother signed it at breakfast."],
        ["M", "Is it in the teacher's box downstairs?"],
        ["W", "It's still inside my desk drawer."],
        ["M", "We can't get on the van without it."],
        ["W", "I'll run and put the form in the box."],
      ],
      choices: [
        "가방을 챙기기",
        "승합차를 타기",
        "동의서를 제출하기",
        "어머니께 전화하기",
        "선생님을 기다리기",
      ],
      answer: 3,
      clue: "I'll run and put the form in the box.",
      explanation:
        "여자는 동의서를 제출하러 뛰어가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 보미야, 학교 승합차가 15분 뒤에 출발해.",
        "W: 가방은 벌써 문 옆에 놔뒀어.",
        "M: 현장 학습 동의서에 서명받았어?",
        "W: 아침 먹을 때 엄마가 해 주셨어.",
        "M: 아래층 선생님 상자에 넣었어?",
        "W: 아직 내 책상 서랍 안에 있어.",
        "M: 그거 없으면 차를 못 타.",
        "W: 뛰어가서 동의서를 상자에 넣을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 운동화를 고르시오.",
      lines: [
        ["W", "Hoyeon, which running shoes will you buy?"],
        ["M", "Five pairs are on sale at this shop."],
        ["W", "How much do you want to spend?"],
        ["M", "Under seventy thousand won, if possible."],
        ["W", "One pair is far above that price."],
        ["M", "I also need size two hundred seventy."],
        ["W", "Two of them only come in smaller sizes."],
        ["M", "And I really want the white ones."],
        ["W", "Then just one pair is left for you."],
        ["M", "I'll try them on right now."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Under seventy thousand won, if possible.",
      explanation:
        "7만 원 미만, 270 크기, 흰색인 운동화는 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 85,000 won / Size: 270 / Color: White" },
          { no: 2, label: "②", value: "Price: 65,000 won / Size: 265 / Color: White" },
          { no: 3, label: "③", value: "Price: 58,000 won / Size: 260 / Color: Black" },
          { no: 4, label: "④", value: "Price: 62,000 won / Size: 270 / Color: Black" },
          { no: 5, label: "⑤", value: "Price: 68,000 won / Size: 270 / Color: White" },
        ],
      },
      translation: [
        "W: 호연아, 어떤 운동화 살 거야?",
        "M: 이 가게에 다섯 켤레가 할인 중이야.",
        "W: 얼마까지 쓸 생각이야?",
        "M: 가능하면 7만 원 미만.",
        "W: 한 켤레는 그보다 훨씬 비싸네.",
        "M: 그리고 270 크기가 필요해.",
        "W: 두 켤레는 더 작은 크기만 있어.",
        "M: 그리고 흰색이었으면 좋겠어.",
        "W: 그럼 너한테는 한 켤레만 남아.",
        "M: 지금 바로 신어 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 야구장에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taeyang, when is the next home game?"],
        ["M", "They play on the sixth, the ninth and the twelfth."],
        ["W", "The sixth is the day of our science test."],
        ["M", "Nobody would enjoy a game that evening."],
        ["W", "What about the ninth?"],
        ["M", "The forecast says heavy rain all that day."],
        ["W", "Then the twelfth is the day for us."],
        ["M", "The game starts at six thirty that evening."],
        ["W", "I'll ask my father to buy the tickets."],
      ],
      choices: ["the 6th", "the 9th", "the 12th", "the 4th", "the 15th"],
      answer: 3,
      clue: "Then the twelfth is the day for us.",
      explanation:
        "6일은 시험 날, 9일은 비 예보여서 12일에 가기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태양아, 다음 홈 경기가 언제야?",
        "M: 6일, 9일, 12일에 해.",
        "W: 6일은 과학 시험 날이야.",
        "M: 그날 저녁 경기는 아무도 즐기지 못하겠지.",
        "W: 9일은 어때?",
        "M: 그날은 하루 종일 비가 많이 온대.",
        "W: 그럼 우리한테는 12일이네.",
        "M: 그날 저녁 6시 30분에 경기가 시작해.",
        "W: 아버지께 표 사 달라고 부탁할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junseok, what did you do last weekend?"],
        ["M", "I painted my little sister's room with my mother."],
        ["W", "What color did she choose?"],
        ["M", "Light yellow, the color of a lemon."],
        ["W", "Was it hard to paint a whole room?"],
        ["M", "We moved all the furniture out first."],
        ["W", "How long did the painting take?"],
        ["M", "Two days, and one coat was not enough."],
        ["W", "Does she like the new color?"],
        ["M", "She said her room looks sunny now."],
      ],
      choices: [
        "가구를 샀다",
        "친척 집에 갔다",
        "영화를 봤다",
        "동생 방을 칠했다",
        "공부방에 갔다",
      ],
      answer: 4,
      clue: "I painted my little sister's room with my mother.",
      explanation:
        "남자는 지난 주말에 어머니와 동생 방을 칠했다. 따라서 답은 ④이다.",
      translation: [
        "W: 준석아, 지난 주말에 뭐 했어?",
        "M: 어머니랑 동생 방에 페인트를 칠했어.",
        "W: 동생이 무슨 색을 골랐어?",
        "M: 연노랑, 레몬 색깔.",
        "W: 방 전체를 칠하는 게 힘들었어?",
        "M: 먼저 가구를 다 밖으로 뺐어.",
        "W: 칠하는 데 얼마나 걸렸어?",
        "M: 이틀. 한 번 칠해서는 모자랐어.",
        "W: 동생은 새 색 마음에 들어 해?",
        "M: 방이 볕이 드는 것 같대.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Good morning, students. This is the school library. " +
            "Many books borrowed in September are still not back. " +
            "Please return them by this Friday afternoon. " +
            "Check your bag and your desk drawer at home. " +
            "Students with late books cannot borrow new ones. " +
            "The return box sits beside the library door. " +
            "Thank you for helping us keep the shelves full.",
        ],
      ],
      choices: [
        "책 반납을 당부하려고",
        "도서관 공사를 알리려고",
        "독서 행사를 안내하려고",
        "분실물을 찾으려고",
        "봉사자를 모으려고",
      ],
      answer: 1,
      clue: "Many books borrowed in September are still not back.",
      explanation:
        "빌려 간 책을 금요일까지 반납하라고 당부하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학교 도서관입니다. 9월에 빌려 간 책이 아직 많이 돌아오지 않았습니다. 이번 주 금요일 오후까지 반납해 주세요. 집에서 가방과 책상 서랍을 확인해 보세요. 연체된 학생은 새 책을 빌릴 수 없습니다. 반납함은 도서관 문 옆에 있습니다. 서가를 채우는 데 협조해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you here for the art supplies?"],
        ["M", "Yes, three sketchbooks and one set of pencils."],
        ["W", "Sketchbooks are two dollars each this month."],
        ["M", "And the pencil set?"],
        ["W", "The small set costs five dollars."],
        ["M", "I'll take the small one."],
        ["W", "Do you need an eraser as well?"],
        ["M", "No, I still have two at home."],
        ["W", "Then that is all for today."],
        ["M", "Here is ten dollars."],
      ],
      choices: ["$8", "$9", "$10", "$11", "$12"],
      answer: 4,
      clue: "Sketchbooks are two dollars each this month.",
      explanation:
        "스케치북 세 권 6달러와 연필 세트 5달러를 더하면 11달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요. 미술 재료 사러 오셨나요?",
        "M: 네, 스케치북 세 권이랑 연필 세트 하나요.",
        "W: 이번 달 스케치북은 한 권에 2달러입니다.",
        "M: 연필 세트는요?",
        "W: 작은 세트는 5달러입니다.",
        "M: 작은 걸로 할게요.",
        "W: 지우개도 필요하신가요?",
        "M: 아니요, 집에 두 개 있어요.",
        "W: 그럼 오늘은 이게 다네요.",
        "M: 여기 10달러요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sungho, your group finished the project first again."],
        ["M", "We decided who does what on the first day."],
        ["W", "Our group argues for a week about that."],
        ["M", "Write the tasks on paper before anyone chooses."],
        ["W", "Does everyone really agree with the list?"],
        ["M", "They agree because they can see the whole thing."],
        ["W", "We only talk about it in the group chat."],
        ["M", "Words in a chat disappear too quickly."],
        ["W", "What should we do at our meeting tomorrow?"],
      ],
      choices: [
        "Cancel the project now.",
        "List the tasks on one page.",
        "Let one person do everything.",
        "Talk in the chat only.",
        "Wait until next month.",
      ],
      answer: 2,
      clue: "What should we do at our meeting tomorrow?",
      explanation:
        "내일 모임에서 무엇을 할지 물었으므로, 할 일을 한 장에 적으라는 ②가 가장 자연스럽다.",
      translation: [
        "W: 성호야, 너희 조가 또 제일 먼저 과제를 끝냈네.",
        "M: 첫날에 누가 뭘 할지 정해.",
        "W: 우리 조는 그것 때문에 일주일을 다퉈.",
        "M: 고르기 전에 할 일을 종이에 적어 봐.",
        "W: 다들 그 목록에 정말 동의해?",
        "M: 전체가 보이니까 동의해.",
        "W: 우리는 단체 대화방에서만 이야기해.",
        "M: 대화방 말은 너무 빨리 사라져.",
        "W: 내일 모임에서 뭘 하면 좋을까?",
        "M: 할 일을 한 장에 적어 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaeyoung, I heard you learned to swim this summer."],
        ["W", "I was afraid of deep water until July."],
        ["M", "What made you decide to start?"],
        ["W", "My cousin fell into a pool and I couldn't help."],
        ["M", "Where did you take the lessons?"],
        ["W", "At the city pool, three mornings a week."],
        ["M", "How long did it take to swim one lap?"],
        ["W", "Almost six weeks, but I never missed a class."],
        ["M", "Are you still afraid of the deep end?"],
        ["W", "I can float there calmly now."],
        ["M", "Could you teach me the first steps?"],
      ],
      choices: [
        "Sure, come to the pool Saturday.",
        "I never learned to swim.",
        "The pool closed last year.",
        "You should not swim.",
        "I am still afraid of water.",
      ],
      answer: 1,
      clue: "Could you teach me the first steps?",
      explanation:
        "처음 단계를 가르쳐 달라고 했으므로, 토요일에 수영장으로 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 채영아, 이번 여름에 수영 배웠다며.",
        "W: 7월까지는 깊은 물이 무서웠어.",
        "M: 왜 시작하기로 했어?",
        "W: 사촌이 수영장에 빠졌는데 내가 도울 수가 없었어.",
        "M: 수업은 어디서 받았어?",
        "W: 시립 수영장에서 일주일에 세 번 아침에.",
        "M: 한 바퀴 도는 데 얼마나 걸렸어?",
        "W: 거의 6주. 대신 한 번도 안 빠졌어.",
        "M: 아직도 깊은 쪽이 무서워?",
        "W: 이제 거기서 편하게 떠 있을 수 있어.",
        "M: 나한테 처음 단계 좀 가르쳐 줄래?",
        "W: 그럼, 토요일에 수영장으로 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Minjun, how is your guitar practice going?"],
        ["W", "You wanted to play a whole song by October."],
        ["M", "My fingers hurt after only ten minutes."],
        ["W", "How long do you practice at one time?"],
        ["M", "An hour every Saturday afternoon."],
        ["W", "That's a long time for beginner fingers."],
        ["M", "I thought one long practice was enough."],
        ["W", "Short practice on many days works better."],
        ["M", "I never thought about it that way."],
        ["W", "Why don't you practice fifteen minutes a day?"],
      ],
      choices: [
        "I'll start tonight.",
        "I sold my guitar already.",
        "I practice every hour.",
        "Guitars don't need practice.",
        "My fingers never hurt.",
      ],
      answer: 1,
      clue: "Why don't you practice fifteen minutes a day?",
      explanation:
        "하루 15분씩 연습하라는 제안이므로, 오늘 밤부터 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 민준아, 기타 연습은 잘돼 가?",
        "W: 10월까지 한 곡을 다 치고 싶다고 했잖아.",
        "M: 10분만 해도 손가락이 아파.",
        "W: 한 번에 얼마나 연습해?",
        "M: 토요일 오후마다 한 시간씩.",
        "W: 처음 배우는 손가락에는 긴 시간이야.",
        "M: 한 번 길게 하면 되는 줄 알았어.",
        "W: 여러 날 짧게 하는 게 더 나아.",
        "M: 그렇게 생각해 본 적이 없어.",
        "W: 하루에 15분씩 연습해 보는 건 어때?",
        "M: 오늘 밤부터 시작할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yeonwoo가 Bomin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yeonwoo : ________________",
      lines: [
        [
          "M",
          "Yeonwoo and Bomin are waiting at the school bus stop. " +
            "Bomin is standing with his heels over the edge of the curb. " +
            "A large bus is turning toward them from the corner. " +
            "Yeonwoo can see that the bus will swing in close. " +
            "He wants Bomin to step back onto the sidewalk at once. " +
            "In this situation, what would Yeonwoo most likely say to Bomin?",
        ],
      ],
      choices: [
        "Step back from the curb.",
        "The bus is always late.",
        "Let's walk home today.",
        "I forgot my bus card.",
        "Sit down on the road.",
      ],
      answer: 1,
      clue: "He wants Bomin to step back onto the sidewalk at once.",
      explanation:
        "버스가 가까이 돌아 들어오므로, 인도 쪽으로 물러서라는 ①이 가장 적절하다.",
      translation: [
        "M: 연우와 보민이는 학교 버스 정류장에서 기다리고 있습니다. 보민이는 발뒤꿈치를 연석 밖으로 내민 채 서 있습니다. 큰 버스가 모퉁이에서 그들 쪽으로 돌아오고 있습니다. 연우는 버스가 바짝 붙어 들어올 것을 알아챕니다. 그는 보민이가 곧바로 인도 쪽으로 물러서기를 바랍니다. 이런 상황에서 연우가 보민이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
