/** 중2 듣기 36회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 36회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 보온병을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a thermos bottle?"],
        ["W", "Yes, one I can open while I'm walking."],
        ["M", "Then a push button lid is easier than a cup lid."],
        ["W", "A button lid it is. One hand is enough."],
        ["M", "Do you want a side handle on the body?"],
        ["W", "No handle. It has to slide into my bag."],
        ["M", "This one comes with a strap around the neck."],
        ["W", "No strap either. Just the plain button one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "A button lid it is. One hand is enough. / No handle. It has to slide into my bag.",
      explanation:
        "여자는 버튼형 뚜껑에 손잡이와 끈이 없는 보온병을 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five thermos bottles standing side by side as five choices, clean black line art on white. " +
          "① a bottle with a CUP-SHAPED lid on top and NO side handle. " +
          "② a bottle with a flat PUSH BUTTON lid on top and NO side handle. " +
          "③ a bottle with a CUP-SHAPED lid and a SIDE HANDLE on the body. " +
          "④ a bottle with a PUSH BUTTON lid and a SIDE HANDLE on the body. " +
          "⑤ a bottle with a PUSH BUTTON lid, no handle, and a long STRAP tied around its neck.",
      },
      translation: [
        "M: 안녕하세요. 보온병 찾으세요?",
        "W: 네, 걸으면서 열 수 있는 걸로요.",
        "M: 그러면 컵 뚜껑보다 누르는 뚜껑이 편해요.",
        "W: 버튼 뚜껑으로 할게요. 한 손이면 되겠네요.",
        "M: 몸통에 손잡이가 있는 게 좋으세요?",
        "W: 손잡이는 없어야 해요. 가방에 들어가야 하거든요.",
        "M: 이건 목에 거는 끈이 같이 있어요.",
        "W: 끈도 필요 없어요. 버튼만 있는 걸로 주세요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 봉사 동아리 활동에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junhyeok, what does your volunteer club actually do?"],
        ["M", "We go out every second Saturday of the month."],
        ["W", "Where do you usually go?"],
        ["M", "To the senior center behind the community hall."],
        ["W", "What kind of work do you do there?"],
        ["M", "We read newspapers aloud and help with phones."],
        ["W", "Should I bring anything if I join?"],
        ["M", "Just a name tag and comfortable shoes."],
        ["W", "That sounds like something I could do."],
      ],
      choices: [
        "활동하는 요일",
        "찾아가는 장소",
        "함께 가는 인원",
        "그곳에서 하는 일",
        "챙겨야 할 물건",
      ],
      answer: 3,
      clue: "We go out every second Saturday of the month. / Just a name tag and comfortable shoes.",
      explanation:
        "요일, 장소, 하는 일, 준비물은 말했지만 함께 가는 인원은 말하지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 준혁아, 너희 봉사 동아리는 실제로 뭘 해?",
        "M: 매달 둘째 주 토요일에 나가.",
        "W: 보통 어디로 가?",
        "M: 주민회관 뒤 노인복지관으로.",
        "W: 거기서 무슨 일을 해?",
        "M: 신문을 소리 내어 읽어 드리고 휴대전화를 도와드려.",
        "W: 내가 들어가면 뭘 챙겨야 해?",
        "M: 이름표랑 편한 신발이면 돼.",
        "W: 나도 할 수 있을 것 같다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Dahye. It's Seungmin. Do you have a second?"],
        ["W", "Sure. What's going on?"],
        ["M", "I've been thinking about what I said at practice."],
        ["W", "You mean about my part in the song?"],
        ["M", "Yes. I spoke too sharply in front of everyone."],
        ["W", "It did bother me a little, honestly."],
        ["M", "I'm really sorry. I should have said it quietly."],
      ],
      choices: [
        "사과하려고",
        "약속을 잡으려고",
        "숙제를 물어보려고",
        "물건을 빌리려고",
        "길을 물어보려고",
      ],
      answer: 1,
      clue: "I'm really sorry. I should have said it quietly.",
      explanation:
        "남자는 연습 때 심하게 말한 것을 사과하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 다혜야. 승민이야. 잠깐 괜찮아?",
        "W: 응. 무슨 일이야?",
        "M: 연습 때 내가 한 말을 계속 생각했어.",
        "W: 내 파트 얘기 말하는 거야?",
        "M: 응. 모두 앞에서 너무 날카롭게 말했어.",
        "W: 솔직히 좀 속상하긴 했어.",
        "M: 정말 미안해. 조용히 말했어야 했어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taehyun, when does the swimming pool open on Saturday?"],
        ["M", "The morning session starts at nine."],
        ["W", "Do we have to shower before we get in?"],
        ["M", "Yes, and the lockers take a while too."],
        ["W", "How much time should we leave for that?"],
        ["M", "Twenty minutes for both, I'd say."],
        ["W", "Then we should meet at eight forty."],
        ["M", "My bus only gets there at eight forty-five."],
        ["W", "Then eight fifty. We'll have to hurry a bit."],
      ],
      choices: ["8:30 a.m.", "8:40 a.m.", "8:45 a.m.", "8:50 a.m.", "9:00 a.m."],
      answer: 4,
      clue: "Then eight fifty. We'll have to hurry a bit.",
      explanation:
        "남자의 버스가 8시 45분에 도착해서 8시 50분에 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 태현아, 토요일에 수영장 몇 시에 열어?",
        "M: 오전반은 9시에 시작해.",
        "W: 들어가기 전에 샤워해야 해?",
        "M: 응, 사물함 쓰는 것도 시간이 걸려.",
        "W: 그거 하는 데 얼마나 잡아야 해?",
        "M: 둘 다 하면 20분쯤.",
        "W: 그럼 8시 40분에 만나야겠다.",
        "M: 내 버스가 8시 45분에나 도착해.",
        "W: 그럼 8시 50분. 좀 서둘러야겠다.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jinwoo, aren't you worried about the speech tomorrow?"],
        ["M", "Not really. I've practiced it more than thirty times."],
        ["W", "Thirty times? That's a lot."],
        ["M", "I recorded it and listened on the bus every morning."],
        ["W", "Do you still look at your paper while speaking?"],
        ["M", "I haven't needed the paper for a week now."],
        ["W", "Then you're more ready than anyone."],
        ["M", "I just want to stand up there and start."],
      ],
      choices: ["confident", "nervous", "sad", "angry", "bored"],
      answer: 1,
      clue: "I just want to stand up there and start.",
      explanation:
        "서른 번 넘게 연습해 종이 없이도 말할 수 있고 어서 시작하고 싶다고 했으므로 자신 있는 심정이다. 따라서 답은 ①이다.",
      translation: [
        "W: 진우야, 내일 연설 걱정되지 않아?",
        "M: 별로. 서른 번도 넘게 연습했어.",
        "W: 서른 번? 정말 많다.",
        "M: 녹음해서 아침마다 버스에서 들었어.",
        "W: 아직도 종이를 보면서 말해?",
        "M: 일주일째 종이 없이 해.",
        "W: 그럼 누구보다 준비된 거네.",
        "M: 그냥 빨리 올라가서 시작하고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you have a bag for this?"],
        ["M", "Yes, a paper one."],
        ["ANN", "Number two."],
        ["W", "What time do you close today?"],
        ["M", "At nine in the evening."],
        ["ANN", "Number three."],
        ["W", "Can I read this before buying?"],
        ["M", "Yes, please sit over there."],
        ["ANN", "Number four."],
        ["W", "I'm looking for this book."],
        ["M", "It's on the second shelf behind you."],
        ["ANN", "Number five."],
        ["W", "Do you sell used books?"],
        ["M", "No, only new ones."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'm looking for this book.",
      explanation:
        "그림은 서점에서 여자가 메모를 보여 주자 직원이 뒤쪽 선반을 가리키는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a bookstore, clean black line art on a plain white background, no writing anywhere. " +
          "A woman holds up a small blank note toward a male shop clerk. " +
          "The clerk points with his finger at the second shelf of a tall bookcase behind her. " +
          "The bookcase is filled with rows of plain books with blank spines. " +
          "A counter with a plain box and a stool are drawn in the background.",
      },
      translation: [
        "① W: 이거 담을 봉투 있어요? / M: 네, 종이봉투요.",
        "② W: 오늘 몇 시에 닫아요? / M: 저녁 9시에요.",
        "③ W: 사기 전에 읽어 봐도 돼요? / M: 네, 저쪽에 앉으세요.",
        "④ W: 이 책을 찾고 있어요. / M: 뒤쪽 둘째 칸에 있어요.",
        "⑤ W: 중고책도 팔아요? / M: 아니요, 새 책만 팔아요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, do you still have your old recorder?"],
        ["M", "The one from last year's music class? Yes, at home."],
        ["W", "Our group performs in music class on Thursday."],
        ["M", "Don't you have your own recorder?"],
        ["W", "Mine cracked when it fell off my desk."],
        ["M", "Can't you buy a new one before Thursday?"],
        ["W", "Could I borrow yours just for that one class?"],
        ["M", "Sure, I'll bring it tomorrow morning."],
      ],
      choices: [
        "준비물을 챙겨 오기",
        "악기를 빌려주기",
        "청소를 도와주기",
        "사진을 찍어 주기",
        "자리를 맡아 주기",
      ],
      answer: 2,
      clue: "Could I borrow yours just for that one class?",
      explanation:
        "여자는 음악 시간에 쓸 리코더를 빌려 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 도현아, 예전 리코더 아직 있어?",
        "M: 작년 음악 시간에 쓰던 거? 응, 집에 있어.",
        "W: 우리 모둠이 목요일 음악 시간에 발표해.",
        "M: 네 리코더는 없어?",
        "W: 책상에서 떨어져서 금이 갔어.",
        "M: 목요일 전에 새로 못 사?",
        "W: 그 수업 한 번만 네 걸 빌릴 수 있을까?",
        "M: 그럼, 내일 아침에 가져올게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 안전 대피 훈련에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. Here is information about our fire drill. " +
            "When you hear three short bells, leave your classroom at once. " +
            "Every class gathers on the playground near the flag pole. " +
            "Do not run, and do not go back for your belongings. " +
            "Mr. Kang in the office will answer any questions about the drill.",
        ],
      ],
      choices: [
        "훈련을 하는 날",
        "대피하는 장소",
        "대피를 알리는 신호",
        "지켜야 할 주의 사항",
        "물어볼 수 있는 선생님",
      ],
      answer: 1,
      clue: "When you hear three short bells, leave your classroom at once.",
      explanation:
        "신호, 대피 장소, 주의 사항, 담당 선생님은 말했지만 훈련 날짜는 말하지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 화재 대피 훈련 안내입니다. 짧은 종이 세 번 울리면 즉시 교실을 나가세요. 각 반은 운동장 국기 게양대 근처로 모입니다. 뛰지 말고, 물건을 가지러 돌아가지 마세요. 훈련에 대해 궁금한 점은 교무실 강 선생님께 물어보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a soft piece of cloth with two loops on its sides. " +
            "You hang the loops over your ears to keep it in place. " +
            "It covers your nose and mouth but not your eyes. " +
            "People wear one when the air is dusty or when they cough. " +
            "Throw the paper kind away after you use it once.",
        ],
      ],
      choices: ["우산", "장갑", "목도리", "마스크", "모자"],
      answer: 4,
      clue: "It covers your nose and mouth but not your eyes.",
      explanation:
        "귀에 걸어 코와 입을 덮고 먼지가 많거나 기침할 때 쓰는 것은 마스크이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이것은 양옆에 고리가 달린 부드러운 천입니다. 고리를 귀에 걸어 자리에 고정합니다. 코와 입은 덮지만 눈은 덮지 않습니다. 공기가 탁하거나 기침이 날 때 사람들이 이것을 씁니다. 종이로 된 것은 한 번 쓰고 버리세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Have you finished the survey?"],
        ["M", "Almost, three more questions."],
        ["ANN", "Number two."],
        ["W", "Would you like to sit here?"],
        ["M", "Thank you, that's kind."],
        ["ANN", "Number three."],
        ["W", "How was the food at the festival?"],
        ["M", "The soup was the best part."],
        ["ANN", "Number four."],
        ["W", "When is your presentation?"],
        ["M", "On Friday afternoon."],
        ["ANN", "Number five."],
        ["W", "Who wrote this message?"],
        ["M", "I wrote it with a blue pen."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Who wrote this message?",
      explanation:
        "누가 썼는지 묻는 말에 파란 펜으로 썼다고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① W: 설문 다 했어? / M: 거의, 세 문항 남았어.",
        "② W: 여기 앉으실래요? / M: 고맙습니다, 친절하시네요.",
        "③ W: 축제 음식 어땠어? / M: 국이 제일 좋았어.",
        "④ W: 네 발표 언제야? / M: 금요일 오후에.",
        "⑤ W: 이 쪽지 누가 썼어? / M: 파란 펜으로 썼어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seokjin, did you get the group project file from me?"],
        ["M", "You sent it to my school account, right?"],
        ["W", "Yes, but my phone says it hasn't been opened."],
        ["M", "I can't open school mail on my phone."],
        ["W", "The deadline for printing is four o'clock."],
        ["M", "It's three forty now."],
        ["W", "The computer room is still open next door."],
        ["M", "I'll go download it there right away."],
      ],
      choices: [
        "도서관에 가기",
        "매점에 가기",
        "교실을 청소하기",
        "점심을 먹으러 가기",
        "컴퓨터실에 가서 파일을 받기",
      ],
      answer: 5,
      clue: "I'll go download it there right away.",
      explanation:
        "남자는 컴퓨터실에 가서 파일을 내려받겠다고 했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 석진아, 내가 보낸 모둠 과제 파일 받았어?",
        "M: 학교 계정으로 보냈지?",
        "W: 응, 그런데 아직 안 열렸다고 떠.",
        "M: 휴대전화로는 학교 메일을 못 열어.",
        "W: 인쇄 마감이 4시야.",
        "M: 지금 3시 40분이네.",
        "W: 옆에 컴퓨터실이 아직 열려 있어.",
        "M: 지금 바로 가서 받을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 등록할 운동 센터를 고르시오.",
      lines: [
        ["W", "Hyunwoo, which fitness center are you going to join?"],
        ["M", "Let's look at these five near our neighborhood."],
        ["W", "How far can you walk from home?"],
        ["M", "Ten minutes at the most, or I won't keep going."],
        ["W", "All right. What about the monthly fee?"],
        ["M", "Under forty thousand won, if possible."],
        ["W", "Do you need a shower room there?"],
        ["M", "Yes, I go early and come straight to school."],
        ["W", "Then only one center here works for you."],
        ["M", "Good. I'll visit it after school today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Ten minutes at the most, or I won't keep going.",
      explanation:
        "걸어서 10분 이내, 4만 원 이하, 샤워실이 있는 곳을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Walk: 8 min / Fee: 38,000 won / Shower: Yes" },
          { no: 2, label: "②", value: "Walk: 15 min / Fee: 35,000 won / Shower: Yes" },
          { no: 3, label: "③", value: "Walk: 5 min / Fee: 45,000 won / Shower: Yes" },
          { no: 4, label: "④", value: "Walk: 9 min / Fee: 30,000 won / Shower: No" },
          { no: 5, label: "⑤", value: "Walk: 20 min / Fee: 28,000 won / Shower: No" },
        ],
      },
      translation: [
        "W: 현우야, 어느 운동 센터에 등록할 거야?",
        "M: 우리 동네 근처 다섯 곳 보자.",
        "W: 집에서 얼마나 걸어갈 수 있어?",
        "M: 최대 10분. 더 멀면 계속 못 다녀.",
        "W: 알겠어. 한 달 회비는?",
        "M: 되도록 4만 원 이하로.",
        "W: 샤워실이 필요해?",
        "M: 응, 일찍 가서 바로 학교로 와.",
        "W: 그럼 여기서 되는 곳은 하나뿐이야.",
        "M: 좋아. 오늘 방과 후에 가 볼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 설문 조사를 하기로 한 날짜를 고르시오.",
      lines: [
        ["M", "Chaewon, when should we do the school survey?"],
        ["W", "Our report is due on the twenty-eighth."],
        ["M", "So the survey has to be done well before that."],
        ["W", "How about the eighteenth, next Tuesday?"],
        ["M", "The whole school goes on a field trip that day."],
        ["W", "Then the nineteenth, on Wednesday?"],
        ["M", "Wednesday works. Classes end early, so students have time."],
        ["W", "Then the nineteenth it is."],
        ["M", "I'll print the sheets on the eighteenth evening."],
      ],
      choices: [
        "the 18th",
        "the 19th",
        "the 20th",
        "the 28th",
        "the 25th",
      ],
      answer: 2,
      clue: "Wednesday works. Classes end early, so students have time.",
      explanation:
        "18일은 현장 학습이어서 19일 수요일에 설문을 하기로 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 채원아, 학교 설문 조사 언제 할까?",
        "W: 보고서가 28일까지야.",
        "M: 그럼 설문은 그보다 훨씬 전에 끝내야겠다.",
        "W: 다음 주 화요일 18일은 어때?",
        "M: 그날 전교생이 현장 학습을 가.",
        "W: 그럼 수요일 19일은?",
        "M: 수요일 좋아. 수업이 일찍 끝나서 학생들이 시간이 있어.",
        "W: 그럼 19일로 하자.",
        "M: 18일 저녁에 설문지를 인쇄할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeeun, did you go out with your family on Saturday?"],
        ["W", "No, I helped at the town library all morning."],
        ["M", "What kind of help did they need?"],
        ["W", "We put returned books back on the right shelves."],
        ["M", "Was it hard to find the right places?"],
        ["W", "The numbers on the spines make it easier."],
        ["M", "How many books did you handle?"],
        ["W", "More than two hundred by lunch time."],
      ],
      choices: [
        "영화를 보러 가기",
        "병원에 다녀오기",
        "도서관에서 공부하기",
        "마을 도서관에서 봉사하기",
        "가족과 여행을 가기",
      ],
      answer: 4,
      clue: "No, I helped at the town library all morning.",
      explanation:
        "여자는 토요일 오전에 마을 도서관에서 책 정리 봉사를 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 예은아, 토요일에 가족이랑 나갔어?",
        "W: 아니, 오전 내내 마을 도서관에서 도왔어.",
        "M: 어떤 도움이 필요했는데?",
        "W: 반납된 책을 제자리 선반에 꽂았어.",
        "M: 제자리 찾기 어렵지 않았어?",
        "W: 책등에 있는 번호 덕분에 수월해.",
        "M: 몇 권이나 다뤘어?",
        "W: 점심때까지 200권 넘게.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. The student council has one announcement. " +
            "From next week there is a new rule for the front stairs. " +
            "Go up on the right side and come down on the left side. " +
            "Too many students bumped into each other last month. " +
            "Teachers will stand on each floor for the first three days. " +
            "Thank you for helping everyone move safely.",
        ],
      ],
      choices: [
        "행사 시작을 알리려고",
        "새로운 규칙을 안내하려고",
        "분실물을 찾아가라고",
        "청소를 부탁하려고",
        "문 닫는 시간을 알리려고",
      ],
      answer: 2,
      clue: "From next week there is a new rule for the front stairs.",
      explanation:
        "다음 주부터 계단 통행에 새 규칙이 생긴다고 안내하는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 학생회에서 안내 말씀 하나 드립니다. 다음 주부터 정문 계단에 새 규칙이 생깁니다. 올라갈 때는 오른쪽으로, 내려올 때는 왼쪽으로 다니세요. 지난달에 너무 많은 학생이 서로 부딪혔습니다. 처음 사흘 동안은 층마다 선생님이 서 계실 것입니다. 모두가 안전하게 다니도록 도와주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you renting bikes for the afternoon?"],
        ["W", "Yes, three bikes for two hours, please."],
        ["M", "One bike is five dollars per hour."],
        ["W", "Do we need to pay for helmets too?"],
        ["M", "Helmets come free with each bike."],
        ["W", "Is there a group rate for three bikes?"],
        ["M", "Yes, three or more bikes get five dollars off."],
        ["W", "Great. Here is my card."],
      ],
      choices: ["$20", "$30", "$25", "$35", "$15"],
      answer: 3,
      clue: "One bike is five dollars per hour. / Yes, three or more bikes get five dollars off.",
      explanation:
        "자전거 세 대를 두 시간 빌리면 30달러이고 단체 할인 5달러를 빼면 25달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 오후에 자전거 빌리시나요?",
        "W: 네, 자전거 세 대를 두 시간 빌릴게요.",
        "M: 한 대에 시간당 5달러입니다.",
        "W: 헬멧도 돈을 내야 하나요?",
        "M: 헬멧은 자전거마다 무료입니다.",
        "W: 세 대면 단체 요금이 있나요?",
        "M: 네, 세 대 이상이면 5달러 빼 드립니다.",
        "W: 좋네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sujin, your group always finishes the lab report first."],
        ["W", "We write down the numbers while the experiment runs."],
        ["M", "You don't wait until the end?"],
        ["W", "No, one person records and the others watch."],
        ["M", "Our group tries to remember everything afterward."],
        ["W", "Then you argue about what the number was."],
        ["M", "That happens to us almost every time."],
        ["W", "One person with a pen solves the whole problem."],
        ["M", "Could you show our group how you split the roles?"],
      ],
      choices: [
        "We never write anything down.",
        "Your group finished first.",
        "Sure, I'll come over on Wednesday.",
        "I don't do experiments.",
        "The report is not due yet.",
      ],
      answer: 3,
      clue: "Could you show our group how you split the roles?",
      explanation:
        "남자가 역할 나누는 법을 보여 달라고 했으므로, 수요일에 가겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 수진아, 너희 모둠은 늘 실험 보고서를 제일 먼저 끝내더라.",
        "W: 실험하는 동안 숫자를 바로 적어.",
        "M: 끝날 때까지 기다리지 않아?",
        "W: 응, 한 명이 적고 나머지가 봐.",
        "M: 우리 모둠은 끝나고 다 기억해 내려고 해.",
        "W: 그러다 숫자가 뭐였는지 다투게 되지.",
        "M: 거의 매번 그래.",
        "W: 펜 든 사람 한 명이면 그 문제가 다 풀려.",
        "M: 우리 모둠에 역할 나누는 법 좀 알려 줄래?",
        "W: 그럼, 수요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Minseok, do you still walk your neighbor's dog?"],
        ["M", "Every evening, for about thirty minutes."],
        ["W", "Doesn't that take time away from studying?"],
        ["M", "Actually I think better after the walk."],
        ["W", "Do you get anything for doing it?"],
        ["M", "They pay me a little, but I'd do it anyway."],
        ["W", "My family has been thinking about a dog too."],
        ["M", "Walking one every day is a real promise."],
        ["W", "Could I come along one evening and see?"],
      ],
      choices: [
        "I don't walk any dog.",
        "You should get a cat.",
        "The dog never goes out.",
        "I stopped walking last month.",
        "Sure, come with me on Friday.",
      ],
      answer: 5,
      clue: "Could I come along one evening and see?",
      explanation:
        "여자가 한번 따라가 보겠다고 했으므로, 금요일에 같이 가자는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 민석아, 아직 이웃집 강아지 산책시켜?",
        "M: 매일 저녁에, 30분쯤.",
        "W: 공부 시간이 줄지 않아?",
        "M: 오히려 산책하고 나면 머리가 잘 돌아가.",
        "W: 하고 나서 뭐 받는 거 있어?",
        "M: 조금 주시는데 안 주셔도 할 거야.",
        "W: 우리 가족도 강아지를 생각하고 있어.",
        "M: 매일 산책시키는 건 진짜 약속이야.",
        "W: 나도 저녁에 한 번 따라가 봐도 돼?",
        "M: 그럼, 금요일에 같이 가자.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nari, your handwriting on the class notice was so clear."],
        ["W", "I wrote it three times before I put it up."],
        ["M", "Three times for one notice?"],
        ["W", "The first two had words crowded at the end."],
        ["M", "How do you keep the spacing even?"],
        ["W", "I draw light pencil lines and erase them later."],
        ["M", "I never thought of drawing lines first."],
        ["W", "It takes two minutes and saves the whole page."],
        ["M", "Could you help me with next week's notice?"],
      ],
      choices: [
        "I can't write neatly.",
        "You should not use pencils.",
        "The notice is already up.",
        "I don't make notices.",
        "Of course, bring the paper Monday.",
      ],
      answer: 5,
      clue: "Could you help me with next week's notice?",
      explanation:
        "남자가 다음 주 안내문을 도와 달라고 했으므로, 월요일에 종이를 가져오라는 ⑤가 가장 자연스럽다.",
      translation: [
        "M: 나리야, 학급 안내문 글씨가 정말 또렷하더라.",
        "W: 붙이기 전에 세 번 썼어.",
        "M: 안내문 하나에 세 번이나?",
        "W: 처음 두 번은 끝에 글자가 몰렸어.",
        "M: 간격을 어떻게 고르게 해?",
        "W: 연필로 흐리게 선을 긋고 나중에 지워.",
        "M: 선을 먼저 긋는 건 생각도 못 했어.",
        "W: 2분이면 되고 한 장을 살려.",
        "M: 다음 주 안내문 좀 도와줄래?",
        "W: 그럼, 월요일에 종이 가져와.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jaemin이 Chaeyeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jaemin : ________________",
      lines: [
        [
          "M",
          "Jaemin and Chaeyeon are packing up after the science club meeting. " +
            "Chaeyeon closes her bag and picks up a small bottle of glue. " +
            "Jaemin sees that she is holding the club's shared bottle, not her own. " +
            "Her own glue is still lying open on the table behind her. " +
            "He wants to tell her before she leaves the room with it. " +
            "In this situation, what would Jaemin most likely say to Chaeyeon?",
        ],
      ],
      choices: [
        "Can I borrow some glue?",
        "The meeting ended early today.",
        "That glue belongs to the club.",
        "Let's clean the table first.",
        "You should close your bag.",
      ],
      answer: 3,
      clue: "He wants to tell her before she leaves the room with it.",
      explanation:
        "채연이가 자기 풀 대신 동아리 공용 풀을 들고 나가려 하므로, 동아리 것이라고 알려 주는 ③이 가장 적절하다.",
      translation: [
        "M: 재민이와 채연이는 과학 동아리 모임이 끝난 뒤 짐을 챙기고 있습니다. 채연이가 가방을 닫고 작은 풀통 하나를 집어 듭니다. 재민이는 그것이 채연이 것이 아니라 동아리 공용 풀이라는 것을 봅니다. 채연이의 풀은 뒤쪽 탁자에 뚜껑이 열린 채 놓여 있습니다. 재민이는 채연이가 그것을 들고 나가기 전에 알려 주고 싶습니다. 이런 상황에서 재민이가 채연이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
