/** 중2 듣기 15회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 15회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 책가방을 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a school bag?"],
        ["M", "Yes, mine tore last week."],
        ["W", "We have bags that open with a zip and bags that close with buckles."],
        ["M", "A zip, please. The buckles take too long in the morning."],
        ["W", "All right. Do you want a front pocket on it?"],
        ["M", "Yes, I keep my bus card there."],
        ["W", "Then two are left. One has a chest strap and one doesn't."],
        ["M", "I'll take the one without a chest strap. It gets in my way."],
        ["W", "Good choice. That one has a padded back as well."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'll take the one without a chest strap. It gets in my way.",
      explanation:
        "남자는 지퍼로 열리고 앞주머니가 있으며 가슴끈이 없는 가방을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five school backpacks shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a backpack closed with two BUCKLE STRAPS on the front flap, with no front pocket. " +
          "Second: a backpack closed with two BUCKLE STRAPS on the front flap, with a small FRONT POCKET. " +
          "Third: a backpack closed with a ZIP, with NO front pocket, and a CHEST STRAP joining the two shoulder straps. " +
          "Fourth: a backpack closed with a ZIP, with a small FRONT POCKET, and NO chest strap at all. " +
          "Fifth: a backpack closed with a ZIP, with a small FRONT POCKET, and a CHEST STRAP joining the two shoulder straps.",
      },
      translation: [
        "W: 안녕하세요. 책가방 찾으세요?",
        "M: 네, 쓰던 게 지난주에 찢어졌어요.",
        "W: 지퍼로 여는 것과 버클로 잠그는 것이 있어요.",
        "M: 지퍼로요. 버클은 아침에 시간이 너무 걸려요.",
        "W: 알겠습니다. 앞주머니가 있는 걸로 하시겠어요?",
        "M: 네, 거기에 버스 카드를 넣거든요.",
        "W: 그럼 두 개 남았네요. 하나는 가슴끈이 있고 하나는 없습니다.",
        "M: 가슴끈 없는 걸로 할게요. 걸리적거려서요.",
        "W: 좋은 선택이세요. 그건 등판에 쿠션도 있습니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 글쓰기 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyul, are you entering the school writing contest?"],
        ["W", "I'm thinking about it. Do you know the details?"],
        ["M", "It's on the second Friday of next month, in the morning."],
        ["W", "Where do we write? In our classroom?"],
        ["M", "No, everyone goes to the library on the third floor."],
        ["W", "How long do we get?"],
        ["M", "Ninety minutes, and you write it by hand there."],
        ["W", "Is there a topic, or do we choose?"],
        ["M", "They give you three topics and you pick one."],
        ["W", "Three is enough to choose from. I'll enter."],
        ["M", "Good. Sign your name on the list by Wednesday."],
      ],
      choices: ["열리는 날", "장소", "시험 시간", "주제", "시상 내용"],
      answer: 5,
      clue: "They give you three topics and you pick one.",
      explanation:
        "날짜(다음 달 둘째 금요일), 장소(3층 도서관), 시간(90분), 주제(세 개 중 선택)는 언급되지만 시상 내용은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 서율아, 교내 글쓰기 대회 나갈 거야?",
        "W: 생각 중이야. 자세한 거 알아?",
        "M: 다음 달 둘째 금요일 오전에 해.",
        "W: 어디서 써? 교실에서?",
        "M: 아니, 다 같이 3층 도서관으로 가.",
        "W: 시간은 얼마나 줘?",
        "M: 90분, 거기서 손으로 써.",
        "W: 주제는 정해져 있어, 아니면 우리가 골라?",
        "M: 주제 세 개를 주고 그중 하나를 고르는 거야.",
        "W: 세 개면 고를 만하네. 나갈래.",
        "M: 그래. 수요일까지 명단에 이름 적어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Chaeyeon. It's Minjun from the class council."],
        ["W", "Hi. Is the meeting still on Thursday?"],
        ["M", "It is, but we need one more thing before then."],
        ["W", "What is it?"],
        ["M", "Nobody has written down what we decided last time."],
        ["W", "I took notes on my phone that day."],
        ["M", "Could you type them up and send them to me?"],
        ["W", "Sure. I'll do it tonight."],
      ],
      choices: [
        "회의 날짜를 바꾸려고",
        "회의록을 정리해 달라고 부탁하려고",
        "회의 장소를 물어보려고",
        "회의에 못 온다고 알리려고",
        "학급 임원을 추천하려고",
      ],
      answer: 2,
      clue: "Could you type them up and send them to me?",
      explanation:
        "남자는 지난 회의에서 정한 내용을 정리해 보내 달라고 부탁하려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 채연아. 학급 회의 민준이야.",
        "W: 안녕. 회의 목요일 그대로지?",
        "M: 그대로야, 그런데 그 전에 하나 더 필요해.",
        "W: 뭔데?",
        "M: 지난번에 정한 걸 아무도 적어 두지 않았어.",
        "W: 그날 내가 휴대전화에 메모해 뒀어.",
        "M: 그걸 정리해서 나한테 보내 줄 수 있어?",
        "W: 그래. 오늘 밤에 할게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Naeun, what time should we meet at the station?"],
        ["W", "The train to Gyeongju leaves at ten thirty."],
        ["M", "Then we should be there before it comes."],
        ["W", "How about ten o'clock?"],
        ["M", "We have to pick up the tickets at the machine first."],
        ["W", "How long does that take?"],
        ["M", "Ten minutes, maybe more if there's a queue."],
        ["W", "Then let's meet at nine forty-five to be safe."],
        ["M", "Nine forty-five it is. I'll wait by the ticket machines."],
      ],
      choices: ["9:15 a.m.", "9:30 a.m.", "9:45 a.m.", "10:00 a.m.", "10:30 a.m."],
      answer: 3,
      clue: "Then let's meet at nine forty-five to be safe.",
      explanation:
        "기차가 10시 30분에 떠나고 표를 뽑는 데 시간이 걸리므로 두 사람은 9시 45분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 나은아, 역에서 몇 시에 만날까?",
        "W: 경주 가는 기차가 10시 30분에 떠나.",
        "M: 그럼 그 전에 가 있어야겠다.",
        "W: 10시는 어때?",
        "M: 기계에서 표부터 뽑아야 해.",
        "W: 그건 얼마나 걸려?",
        "M: 10분, 줄이 있으면 더 걸리고.",
        "W: 그럼 안전하게 9시 45분에 만나자.",
        "M: 9시 45분으로 하자. 발권기 옆에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, you've looked at the clock five times this period."],
        ["W", "My little brother had his first day at a new school today."],
        ["M", "Is he all right?"],
        ["W", "I don't know. He cried at the gate this morning."],
        ["M", "He'll probably make friends by lunch time."],
        ["W", "Maybe, but he doesn't know anyone there at all."],
        ["M", "Can you call him after school?"],
        ["W", "Not until five, and that feels very far away."],
      ],
      choices: ["excited", "proud", "bored", "worried", "angry"],
      answer: 4,
      clue: "Not until five, and that feels very far away.",
      explanation:
        "새 학교 첫날인 동생이 아침에 울었고 5시까지 연락도 할 수 없어 여자는 걱정하고 있다. 따라서 답은 ④이다.",
      translation: [
        "M: 다혜야, 이번 시간에 시계를 다섯 번이나 봤어.",
        "W: 오늘 동생이 새 학교에 처음 가는 날이야.",
        "M: 괜찮대?",
        "W: 모르겠어. 아침에 교문에서 울었어.",
        "M: 점심때쯤이면 친구를 사귀겠지.",
        "W: 그럴지도, 그런데 거기 아는 사람이 하나도 없어.",
        "M: 학교 끝나고 전화할 수 있어?",
        "W: 5시는 돼야 해. 그게 너무 멀게 느껴져.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, could you move your bag?"],
        ["M", "Oh, sorry. Here you go."],
        ["W", "Are you all right? Let me help you up."],
        ["M", "Thank you. I slipped on the ice."],
        ["W", "How much is the bus fare?"],
        ["M", "It's one thousand two hundred won."],
        ["W", "What time does the shop open?"],
        ["M", "At nine on weekdays."],
        ["W", "Can I borrow your umbrella?"],
        ["M", "Sure, I have another one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Are you all right? Let me help you up.",
      explanation:
        "그림은 눈길에서 넘어진 사람에게 다른 사람이 손을 내밀어 일으켜 주려는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a snowy pavement in winter. A man has slipped and is sitting on the ground with one hand behind him, his bag beside him. A woman is bending down and reaching out her hand to help him stand up. Both are drawn clearly and wear winter coats. Bare trees and a low wall are in the background.",
      },
      translation: [
        "① W: 실례지만 가방 좀 옮겨 주시겠어요? / M: 아, 죄송합니다. 여기요.",
        "② W: 괜찮으세요? 제가 일으켜 드릴게요. / M: 감사합니다. 빙판에 미끄러졌어요.",
        "③ W: 버스 요금이 얼마예요? / M: 1,200원입니다.",
        "④ W: 그 가게 몇 시에 열어요? / M: 평일에는 9시에요.",
        "⑤ W: 우산 좀 빌릴 수 있을까? / M: 그럼, 나 하나 더 있어.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, do you still go to the gym after school?"],
        ["M", "Every Tuesday and Thursday. Why?"],
        ["W", "Our class banner is still on the wall there."],
        ["M", "The one from the sports day?"],
        ["W", "That's it. The teacher asked us to take it down this week."],
        ["M", "And you can't go there yourself?"],
        ["W", "The gym is locked when I'm free. You have the key time."],
        ["M", "So you want me to bring it back to the classroom?"],
        ["W", "Yes, please. Just fold it and put it in the back cupboard."],
        ["M", "No problem. I'll do it on Tuesday."],
      ],
      choices: ["현수막 가져오기", "체육관 청소하기", "열쇠 빌려주기", "사진 찍어 주기", "선생님께 말씀드리기"],
      answer: 1,
      clue: "Yes, please. Just fold it and put it in the back cupboard.",
      explanation:
        "여자는 체육관에 걸린 학급 현수막을 걷어서 교실로 가져다 달라고 부탁한다. 따라서 답은 ①이다.",
      translation: [
        "W: 준호야, 방과 후에 아직 체육관 가?",
        "M: 화요일이랑 목요일마다. 왜?",
        "W: 우리 반 현수막이 아직 거기 벽에 걸려 있어.",
        "M: 체육대회 때 그거?",
        "W: 그거. 선생님이 이번 주에 걷으라고 하셨어.",
        "M: 네가 직접 못 가?",
        "W: 내가 시간 될 때는 체육관이 잠겨 있어. 너는 열리는 시간에 가잖아.",
        "M: 그럼 그걸 교실로 가져다 달라는 거지?",
        "W: 응, 부탁해. 접어서 뒤쪽 사물함에 넣어 주면 돼.",
        "M: 그래. 화요일에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Autumn Book Fair에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Here is news about the Autumn Book Fair."],
        ["W", "It will be held next Thursday and Friday, for two days."],
        ["W", "The tables will be set up in the hallway on the first floor."],
        ["W", "You can buy books at half the usual price."],
        ["W", "Bring cash, because the card machine will not be there."],
        ["W", "Come early if you want the picture books."],
      ],
      choices: ["열리는 날", "장소", "책값", "결제 방법", "판매 도서 수"],
      answer: 5,
      clue: "Bring cash, because the card machine will not be there.",
      explanation:
        "날짜(다음 주 목·금), 장소(1층 복도), 책값(평소의 절반), 결제 방법(현금)은 언급되지만 판매 도서 수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. Autumn Book Fair 소식입니다.",
        "W: 다음 주 목요일과 금요일 이틀 동안 열립니다.",
        "W: 1층 복도에 판매대를 놓습니다.",
        "W: 책은 평소의 절반 값으로 살 수 있습니다.",
        "W: 카드 단말기가 없으니 현금을 가져오세요.",
        "W: 그림책을 원하면 일찍 오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You carry this in your bag on rainy days."],
        ["M", "It is made of cloth stretched over thin metal ribs."],
        ["M", "You push it open and it becomes a wide round roof."],
        ["M", "When you come inside, you shake the water off it."],
        ["M", "People leave it behind on buses more than anything else."],
      ],
      choices: ["우산", "모자", "수건", "장갑", "가방"],
      answer: 1,
      clue: "You push it open and it becomes a wide round roof.",
      explanation:
        "비 오는 날 가지고 다니며 펴면 넓은 지붕이 되고 버스에 가장 많이 두고 내린다고 했으므로 우산이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 비 오는 날 가방에 넣어 다닙니다.",
        "M: 가는 금속 살에 천을 씌워 만듭니다.",
        "M: 밀어서 펴면 넓고 둥근 지붕이 됩니다.",
        "M: 안으로 들어오면 물을 털어 냅니다.",
        "M: 사람들이 버스에 가장 많이 두고 내리는 물건입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How do you go to school?"],
        ["M", "I take the subway."],
        ["W", "Could you speak a little louder?"],
        ["M", "Sorry, is this better?"],
        ["W", "What did you have for dinner?"],
        ["M", "I had rice and soup."],
        ["W", "Whose turn is it to clean the board?"],
        ["M", "It takes about ten minutes."],
        ["W", "Shall we study together on Saturday?"],
        ["M", "Good idea. Let's meet at the library."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Whose turn is it to clean the board?",
      explanation:
        "칠판 닦을 차례가 누구인지 묻는 말에 10분쯤 걸린다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① W: 학교에 어떻게 와? / M: 지하철 타고 와.",
        "② W: 조금만 더 크게 말해 줄래? / M: 미안, 이제 괜찮아?",
        "③ W: 저녁으로 뭐 먹었어? / M: 밥이랑 국 먹었어.",
        "④ W: 칠판 닦을 차례가 누구야? / M: 10분쯤 걸려.",
        "⑤ W: 토요일에 같이 공부할까? / M: 좋아. 도서관에서 만나자.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sora, the club presentation starts in ten minutes."],
        ["W", "Is the room ready? What can I do?"],
        ["M", "I've connected the laptop and the slides are open."],
        ["W", "Should I hand out the papers?"],
        ["M", "Hyeon is doing that at the door right now."],
        ["W", "Then what's left?"],
        ["M", "The curtains are open and nobody can see the screen."],
        ["W", "I'll close them right away."],
        ["M", "Thanks. I'll test the sound one more time."],
      ],
      choices: ["노트북 연결하기", "유인물 나눠 주기", "커튼 닫기", "소리 확인하기", "의자 놓기"],
      answer: 3,
      clue: "I'll close them right away.",
      explanation:
        "노트북과 유인물은 이미 해결되었으므로 여자는 화면이 보이도록 커튼을 닫는다. 따라서 답은 ③이다.",
      translation: [
        "M: 소라야, 동아리 발표가 10분 뒤에 시작해.",
        "W: 교실은 준비됐어? 내가 뭘 할까?",
        "M: 노트북은 연결했고 슬라이드도 띄웠어.",
        "W: 유인물을 나눠 줄까?",
        "M: 현이가 지금 문 앞에서 나눠 주고 있어.",
        "W: 그럼 뭐가 남았어?",
        "M: 커튼이 열려 있어서 화면이 안 보여.",
        "W: 내가 바로 닫을게.",
        "M: 고마워. 나는 소리를 한 번 더 확인할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 자전거 헬멧을 고르시오.",
      lines: [
        ["M", "Yerin, are these the helmets you saved?"],
        ["W", "Yes, these five. I ride to school every day now."],
        ["M", "How much can you spend?"],
        ["W", "Fifty dollars at the most."],
        ["M", "All right, that takes out one of them."],
        ["W", "And it has to have a light on the back. I ride home at six."],
        ["M", "Then one more is gone. Three are left."],
        ["W", "How heavy are they? My neck hurts with a heavy one."],
        ["M", "One is four hundred grams, the others are lighter."],
        ["W", "Not that one, then. What about the size?"],
        ["M", "Of the two left, only one comes in a small size."],
        ["W", "That's the one. My head is quite small."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "That's the one. My head is quite small.",
      explanation:
        "60달러인 ②, 뒷등이 없는 ①, 400그램인 ③을 뺀다. 남은 ④와 ⑤ 중 작은 치수가 있는 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "$35 / 뒷등 없음 / 320g / 중간·큰 치수" },
          { no: 2, label: "②", value: "$60 / 뒷등 있음 / 300g / 작은·중간 치수" },
          { no: 3, label: "③", value: "$40 / 뒷등 있음 / 400g / 작은·중간 치수" },
          { no: 4, label: "④", value: "$45 / 뒷등 있음 / 340g / 중간·큰 치수" },
          { no: 5, label: "⑤", value: "$50 / 뒷등 있음 / 330g / 작은·중간 치수" },
        ],
      },
      translation: [
        "M: 예린아, 네가 담아 둔 헬멧이 이거야?",
        "W: 응, 이 다섯 개. 요즘 매일 자전거로 학교 가거든.",
        "M: 얼마까지 쓸 수 있어?",
        "W: 많아야 50달러.",
        "M: 그럼 하나가 빠지네.",
        "W: 그리고 뒤에 등이 있어야 해. 6시에 집에 가거든.",
        "M: 그럼 하나 더 빠진다. 세 개 남았어.",
        "W: 무게는 어때? 무거우면 목이 아파.",
        "M: 하나는 400그램이고 나머지는 더 가벼워.",
        "W: 그건 빼고. 치수는?",
        "M: 남은 둘 중 하나만 작은 치수가 나와.",
        "W: 그걸로 할게. 내 머리가 작은 편이라.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 연극을 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Suhyeon, when should we go to the play?"],
        ["W", "They perform on the twenty-third, twenty-fourth, and twenty-fifth."],
        ["M", "I have my cousin's wedding on the twenty-third."],
        ["W", "Then the twenty-fourth or the twenty-fifth."],
        ["M", "Isn't the twenty-fifth the day the report is due?"],
        ["W", "You're right. We'd be writing all evening."],
        ["M", "So the twenty-fourth is the only one left."],
        ["W", "Let's go on the twenty-fourth. I'll book two seats tonight."],
      ],
      choices: ["22일", "23일", "24일", "25일", "26일"],
      answer: 3,
      clue: "So the twenty-fourth is the only one left.",
      explanation:
        "23일은 사촌 결혼식, 25일은 보고서 마감일이어서 24일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 수현아, 연극 언제 보러 갈까?",
        "W: 23일, 24일, 25일에 공연해.",
        "M: 나 23일에 사촌 결혼식이 있어.",
        "W: 그럼 24일이나 25일이네.",
        "M: 25일은 보고서 내는 날 아니야?",
        "W: 맞다. 저녁 내내 쓰고 있겠네.",
        "M: 그럼 24일만 남는다.",
        "W: 24일에 가자. 오늘 밤에 두 자리 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongha, did you go to the amusement park last weekend?"],
        ["M", "No, I helped at my uncle's bakery on Saturday."],
        ["W", "A bakery? What did you do there?"],
        ["M", "I put bread on the shelves and wrapped it for customers."],
        ["W", "How long were you there?"],
        ["M", "From eight in the morning until two."],
        ["W", "That's six hours. Were you tired?"],
        ["M", "Very, but he sent me home with a big box of bread."],
      ],
      choices: ["놀이공원 가기", "영화 보기", "자전거 타기", "친구 만나기", "빵집 일 돕기"],
      answer: 5,
      clue: "No, I helped at my uncle's bakery on Saturday.",
      explanation:
        "남자는 지난 토요일에 삼촌의 빵집 일을 도왔다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 동하야, 지난 주말에 놀이공원 갔어?",
        "M: 아니, 토요일에 삼촌 빵집 일을 도왔어.",
        "W: 빵집? 가서 뭐 했는데?",
        "M: 빵을 진열대에 놓고 손님들 것을 포장했어.",
        "W: 얼마나 있었어?",
        "M: 아침 8시부터 2시까지.",
        "W: 여섯 시간이나. 힘들었겠다.",
        "M: 엄청. 그래도 빵 한 상자를 싸 주셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good afternoon, students. This is the student council."],
        ["M", "The lost and found box by the front door is full again."],
        ["M", "There are twelve water bottles and six pencil cases in it."],
        ["M", "Some of them have been there since last month."],
        ["M", "Please come and look before Friday afternoon."],
        ["M", "After Friday, everything left will be given away."],
        ["M", "The box is open during every break time."],
      ],
      choices: [
        "분실물을 찾아가라고 하려고",
        "물병을 가져오라고 하려고",
        "교실 청소를 당부하려고",
        "학생회 임원을 모집하려고",
        "쉬는 시간 규칙을 알리려고",
      ],
      answer: 1,
      clue: "Please come and look before Friday afternoon.",
      explanation:
        "정문 옆 분실물 상자가 다시 가득 찼으니 금요일 전에 찾아가라고 알리는 방송이다. 따라서 방송의 목적은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학생회입니다.",
        "M: 정문 옆 분실물 상자가 또 가득 찼습니다.",
        "M: 물병 열두 개와 필통 여섯 개가 들어 있습니다.",
        "M: 그중에는 지난달부터 있던 것도 있습니다.",
        "M: 금요일 오후 전에 와서 살펴봐 주세요.",
        "M: 금요일이 지나면 남은 것은 모두 기부합니다.",
        "M: 상자는 쉬는 시간마다 열려 있습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the city library café. What would you like?"],
        ["M", "Two sandwiches and two orange juices, please."],
        ["W", "Sandwiches are six dollars each and juice is three."],
        ["M", "So twelve dollars and six dollars."],
        ["W", "That's right. Would you like a cookie as well?"],
        ["M", "No, thank you."],
        ["W", "Do you have a library card?"],
        ["M", "Yes, here it is."],
        ["W", "Then I can take three dollars off."],
        ["M", "Great. I'll pay by card."],
      ],
      choices: ["$12", "$15", "$18", "$21", "$24"],
      answer: 2,
      clue: "Then I can take three dollars off.",
      explanation:
        "샌드위치 6달러짜리 두 개는 12달러, 주스 3달러짜리 두 잔은 6달러로 합계 18달러이다. 도서관 카드 할인 3달러를 빼면 15달러이므로 답은 ②이다.",
      translation: [
        "W: 시립 도서관 카페입니다. 무엇을 드릴까요?",
        "M: 샌드위치 두 개랑 오렌지 주스 두 잔 주세요.",
        "W: 샌드위치는 하나에 6달러, 주스는 3달러입니다.",
        "M: 그럼 12달러랑 6달러네요.",
        "W: 맞습니다. 쿠키도 하시겠어요?",
        "M: 아니요, 괜찮습니다.",
        "W: 도서관 카드 있으세요?",
        "M: 네, 여기요.",
        "W: 그럼 3달러 빼 드릴게요.",
        "M: 좋네요. 카드로 결제할게요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Taemin, you've been rewriting that poster all week."],
        ["M", "I have to hand it in on Friday and it still looks empty."],
        ["W", "Empty how?"],
        ["M", "There's a big white space in the middle and I can't fill it."],
        ["W", "What have you put on it so far?"],
        ["M", "The title at the top and a drawing at the bottom."],
        ["W", "And the information? Where is that?"],
        ["M", "I was going to add it last, in the small space that's left."],
        ["W", "Put the information in the middle first, then move the drawing."],
      ],
      choices: [
        "My poster is about saving water.",
        "Then I'll start with the information tonight.",
        "I drew the picture with a pencil.",
        "The poster is due next month.",
        "You should make a poster too.",
      ],
      answer: 2,
      clue: "Put the information in the middle first, then move the drawing.",
      explanation:
        "가운데에 정보를 먼저 넣고 그림을 옮기라는 조언을 들었으므로, 오늘 밤에 정보부터 넣겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 태민아, 일주일 내내 그 포스터를 다시 만들고 있네.",
        "M: 금요일까지 내야 하는데 아직 허전해 보여.",
        "W: 어떻게 허전한데?",
        "M: 가운데에 흰 공간이 크게 남는데 채울 수가 없어.",
        "W: 지금까지 뭘 넣었는데?",
        "M: 맨 위에 제목, 아래에 그림.",
        "W: 그럼 정보는? 어디 있어?",
        "M: 남는 작은 자리에 마지막에 넣으려고 했어.",
        "W: 가운데에 정보를 먼저 넣고 그림을 옮겨 봐.",
        "M: 그럼 오늘 밤에는 정보부터 넣을게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Jiwon, you left your gym clothes at home again."],
        ["W", "The second time this week. I always remember on the bus."],
        ["M", "Where do you keep them at home?"],
        ["W", "In my drawer, with my other clothes."],
        ["M", "So you don't see them when you leave."],
        ["W", "No, and I pack my bag in a hurry."],
        ["M", "Do you have a hook by your door?"],
        ["W", "There is one. I hang my coat on it."],
        ["M", "Hang the gym bag there the night before."],
      ],
      choices: [
        "My gym clothes are blue.",
        "The bus comes at seven fifty.",
        "I have gym class twice a week.",
        "Then I'll hang it by the door tonight.",
        "You should bring an extra set.",
      ],
      answer: 4,
      clue: "Hang the gym bag there the night before.",
      explanation:
        "전날 밤에 체육복 가방을 문 옆 고리에 걸어 두라는 조언을 들었으므로, 오늘 밤에 그렇게 하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 지원아, 또 체육복을 집에 두고 왔네.",
        "W: 이번 주에 두 번째야. 늘 버스에서 생각나.",
        "M: 집에서는 어디에 둬?",
        "W: 서랍 안에, 다른 옷이랑 같이.",
        "M: 그럼 나올 때 안 보이겠네.",
        "W: 응, 게다가 가방도 급하게 싸.",
        "M: 문 옆에 고리 있어?",
        "W: 하나 있어. 거기에 외투를 걸어.",
        "M: 전날 밤에 체육복 가방을 거기 걸어 둬.",
        "W: 그럼 오늘 밤에 문 옆에 걸어 둘게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Seungmin, how is the badminton club going?"],
        ["M", "Not well. I lose every game against the second years."],
        ["W", "What part do you lose on?"],
        ["M", "They hit it to the back and I can never get there in time."],
        ["W", "Do you practise moving, or only hitting?"],
        ["M", "Only hitting. We stand still and hit the shuttle back."],
        ["W", "Then the problem isn't your hitting."],
        ["M", "I never thought of practising the moving part."],
        ["W", "Ask your partner to hit it far and just practise running to it."],
      ],
      choices: [
        "Our club meets three times a week.",
        "I bought a new racket last month.",
        "Then I'll practise running for it tomorrow.",
        "The second years are much taller.",
        "I'd rather play singles from now on.",
      ],
      answer: 3,
      clue: "Ask your partner to hit it far and just practise running to it.",
      explanation:
        "멀리 친 공까지 달려가는 연습을 하라는 조언을 들었으므로, 내일 그렇게 해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 승민아, 배드민턴 동아리는 잘돼 가?",
        "M: 잘 안돼. 2학년들한테 매번 져.",
        "W: 어디에서 지는데?",
        "M: 뒤쪽으로 보내는데 제때 못 가.",
        "W: 움직이는 연습은 해, 아니면 치는 연습만 해?",
        "M: 치는 것만. 서서 셔틀콕을 받아넘겨.",
        "W: 그럼 문제는 치는 게 아니네.",
        "M: 움직이는 연습을 한다는 생각은 못 해 봤어.",
        "W: 짝한테 멀리 쳐 달라고 하고 달려가는 연습만 해 봐.",
        "M: 그럼 내일 달려가는 연습을 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Hyeonu가 Sumin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Hyeonu : ________________",
      lines: [
        ["W", "Hyeonu and Sumin are in the same class."],
        ["W", "They are preparing a short play for the class festival."],
        ["W", "Sumin has learned every line and never forgets a word."],
        ["W", "However, she speaks toward the wall instead of the audience."],
        ["W", "The teacher said the people at the back must be able to hear."],
        ["W", "The stage is in the big hall, and it is quite wide."],
        ["W", "Hyeonu does not want to say that her acting is bad."],
        ["W", "He wants to ask her to turn toward the front when she speaks."],
        ["W", "In this situation, what would Hyeonu most likely say to Sumin?"],
      ],
      choices: [
        "Could you face the front when you speak?",
        "Let's give your lines to someone else.",
        "You should learn your lines again.",
        "I'll play your part instead.",
        "We don't need a play this year.",
      ],
      answer: 1,
      clue: "He wants to ask her to turn toward the front when she speaks.",
      explanation:
        "현우는 수민의 연기를 깎아내리지 않으면서, 말할 때 앞쪽을 보라고 말하려 한다. 따라서 ①이 가장 적절하다.",
      translation: [
        "W: 현우와 수민은 같은 반입니다.",
        "W: 두 사람은 학급 축제에 낼 짧은 연극을 준비하고 있습니다.",
        "W: 수민은 대사를 모두 외웠고 한 마디도 틀리지 않습니다.",
        "W: 그런데 관객이 아니라 벽 쪽을 보고 말합니다.",
        "W: 선생님은 뒤쪽 사람들도 들을 수 있어야 한다고 했습니다.",
        "W: 무대는 대강당에 있고 꽤 넓습니다.",
        "W: 현우는 수민의 연기가 나쁘다고 말하고 싶지는 않습니다.",
        "W: 다만 말할 때 앞쪽을 보라고 부탁하고 싶습니다.",
        "W: 이런 상황에서 현우가 수민에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
