/** 중2 듣기 48회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 48회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 고를 필통을 고르시오.",
      lines: [
        ["W", "Seongjae, are you buying a new pencil case?"],
        ["M", "My old one lost its zipper last week."],
        ["W", "This flat one closes with a button."],
        ["M", "I'd rather have one that stands up on the desk."],
        ["W", "Do you want a handle on the side?"],
        ["M", "No handle. It catches on my bag."],
        ["W", "How about the pocket on the front?"],
        ["M", "Yes, one small front pocket for erasers."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'd rather have one that stands up on the desk. / Yes, one small front pocket for erasers.",
      explanation:
        "세워 놓는 필통에 손잡이는 없고 앞주머니가 하나 있는 것이다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five pencil cases side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a FLAT pencil case lying down with a round BUTTON closure. " +
          "② a tall STANDING pencil case with a HANDLE on the side, no front pocket. " +
          "③ a FLAT pencil case with a small FRONT POCKET. " +
          "④ a tall STANDING pencil case with one small FRONT POCKET and no handle. " +
          "⑤ a tall STANDING pencil case with both a HANDLE on the side and a FRONT POCKET.",
      },
      translation: [
        "W: 성재야, 새 필통 사는 거야?",
        "M: 쓰던 게 지난주에 지퍼가 빠졌어.",
        "W: 이 납작한 건 단추로 닫혀.",
        "M: 나는 책상에 세워 놓는 게 더 좋아.",
        "W: 옆에 손잡이 있는 건 어때?",
        "M: 손잡이는 안 돼. 가방에 걸려.",
        "W: 앞주머니는?",
        "M: 응, 지우개 넣을 작은 앞주머니 하나.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 신문 동아리에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dahyun, what does the newspaper club do exactly?"],
        ["W", "We write and print the school paper together."],
        ["M", "How often does the paper come out?"],
        ["W", "Once a month, on the last Friday."],
        ["M", "Where do you write the articles?"],
        ["W", "In the small room next to the library."],
        ["M", "How many students are in the club?"],
        ["W", "Twelve this year, four from each grade."],
        ["M", "Who decides what goes on the front page?"],
        ["W", "The whole club votes at the Monday meeting."],
      ],
      choices: ["신문이 나오는 주기", "활동하는 방", "동아리 인원", "1면을 정하는 방법", "가입 시기"],
      answer: 5,
      clue: "Once a month, on the last Friday.",
      explanation:
        "주기, 방, 인원, 1면 결정은 말했지만 가입 시기는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다현아, 신문 동아리는 정확히 뭘 해?",
        "W: 학교 신문을 같이 쓰고 찍어 내.",
        "M: 신문은 얼마나 자주 나와?",
        "W: 한 달에 한 번, 마지막 금요일에.",
        "M: 기사는 어디서 써?",
        "W: 도서관 옆 작은 방에서.",
        "M: 동아리에 몇 명이 있어?",
        "W: 올해는 열두 명, 학년마다 네 명씩.",
        "M: 1면에 뭐가 들어갈지는 누가 정해?",
        "W: 월요일 모임에서 동아리 전체가 투표해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, Minho. Do you need something from the office?"],
        ["M", "I found this near the third floor stairs."],
        ["W", "A grey wallet? Let me see it."],
        ["M", "There is a student card inside it."],
        ["W", "Then we can find the owner quickly."],
        ["M", "I didn't touch anything else in it."],
        ["W", "That was the right thing to do."],
        ["M", "I thought the office keeps lost things."],
        ["W", "We do, in the cabinet behind me."],
        ["M", "I came to hand in the wallet I found."],
      ],
      choices: [
        "지갑을 맡기려고",
        "지갑을 찾으려고",
        "상담을 받으려고",
        "서류를 내려고",
        "열쇠를 빌리려고",
      ],
      answer: 1,
      clue: "I came to hand in the wallet I found.",
      explanation:
        "남자는 주운 지갑을 맡기러 왔다. 따라서 답은 ①이다.",
      translation: [
        "W: 안녕, 민호야. 사무실에 볼일 있니?",
        "M: 3층 계단 근처에서 이걸 주웠어요.",
        "W: 회색 지갑? 어디 보자.",
        "M: 안에 학생증이 있어요.",
        "W: 그럼 주인을 금방 찾겠구나.",
        "M: 다른 건 손대지 않았어요.",
        "W: 잘했다.",
        "M: 분실물은 사무실에서 보관한다고 들었어요.",
        "W: 맞아, 내 뒤 보관함에 둔단다.",
        "M: 주운 지갑을 맡기러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["W", "Hyunwoo, when does the volunteer work start?"],
        ["M", "The center wants us there by two o'clock."],
        ["W", "How long does it take to walk from school?"],
        ["M", "About twenty minutes if we don't stop."],
        ["W", "Then we should leave before one forty."],
        ["M", "I also have to pick up the gloves."],
        ["W", "That takes another ten minutes, I think."],
        ["M", "Let's meet at the front gate at one thirty."],
        ["W", "One thirty. I'll wait by the bench."],
      ],
      choices: ["1:00 p.m.", "1:30 p.m.", "1:40 p.m.", "2:00 p.m.", "2:30 p.m."],
      answer: 2,
      clue: "Let's meet at the front gate at one thirty.",
      explanation:
        "이동 시간과 장갑 챙기는 시간을 감안해 1시 30분에 만나기로 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 현우야, 봉사 활동 몇 시에 시작해?",
        "M: 센터에서 두 시까지 오라고 했어.",
        "W: 학교에서 걸어가면 얼마나 걸려?",
        "M: 쉬지 않고 가면 20분쯤.",
        "W: 그럼 1시 40분 전에는 나가야겠네.",
        "M: 나는 장갑도 챙겨야 해.",
        "W: 그건 10분쯤 더 걸리겠다.",
        "M: 정문에서 1시 30분에 만나자.",
        "W: 1시 30분. 의자 옆에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, what did the coach say after practice?"],
        ["M", "He put me on the starting team for Saturday."],
        ["W", "You've waited for that since March."],
        ["M", "I sat on the bench for eleven games."],
        ["W", "And you never missed a single practice."],
        ["M", "I ran extra laps after everyone went home."],
        ["W", "Now all that work has paid off."],
        ["M", "I can't wait for Saturday morning."],
      ],
      choices: ["bored", "sorry", "excited", "worried", "angry"],
      answer: 3,
      clue: "I can't wait for Saturday morning.",
      explanation:
        "주전으로 뽑혀 토요일을 몹시 기다리고 있으므로 들떠 있다. 따라서 답은 ③이다.",
      translation: [
        "W: 준호야, 연습 끝나고 감독님이 뭐라셔?",
        "M: 토요일 경기 선발로 넣어 주셨어.",
        "W: 3월부터 기다린 거잖아.",
        "M: 열한 경기를 벤치에서 앉아 있었어.",
        "W: 그러면서 연습은 한 번도 안 빠졌지.",
        "M: 다들 집에 간 뒤에도 더 뛰었어.",
        "W: 이제 그 노력이 결실을 맺었네.",
        "M: 토요일 아침이 너무 기다려져.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I pay by card?"],
        ["M", "Yes, please insert it here."],
        ["ANN", "Number two."],
        ["W", "Do you need a bag?"],
        ["M", "No, I brought my own."],
        ["ANN", "Number three."],
        ["W", "Where are the eggs?"],
        ["M", "In the last row on the right."],
        ["ANN", "Number four."],
        ["W", "Excuse me, you dropped an apple."],
        ["M", "Oh, I didn't notice. Thank you."],
        ["ANN", "Number five."],
        ["W", "Is this milk fresh?"],
        ["M", "It came in this morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Excuse me, you dropped an apple.",
      explanation:
        "그림은 장바구니에서 떨어진 사과를 주워 건네는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a grocery store aisle, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman bends down and picks up a single APPLE from the floor, holding it out toward a man. " +
          "The man pushes a shopping cart and turns back with a surprised look, one hand raised. " +
          "Shelves of boxes and fruit crates are drawn simply along both sides.",
      },
      translation: [
        "① W: 카드로 계산해도 되나요? / M: 네, 여기 꽂아 주세요.",
        "② W: 봉투 필요하세요? / M: 아니요, 제 걸 가져왔어요.",
        "③ W: 달걀은 어디 있어요? / M: 오른쪽 맨 끝 줄에요.",
        "④ W: 저기요, 사과 떨어뜨리셨어요. / M: 아, 몰랐네요. 고맙습니다.",
        "⑤ W: 이 우유 신선한가요? / M: 오늘 아침에 들어왔습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaerin, you go past the post office every day."],
        ["W", "It's right on my way to the bus stop."],
        ["M", "I have a package for my cousin in Daegu."],
        ["W", "Is it heavy to carry?"],
        ["M", "It's just a book and a birthday card."],
        ["W", "When does it need to arrive?"],
        ["M", "Before Friday, or the card is late."],
        ["W", "The office closes at six on weekdays."],
        ["M", "Could you mail this package for me?"],
        ["W", "Give it to me and I'll send it today."],
      ],
      choices: [
        "소포를 부쳐 주기",
        "선물을 사 주기",
        "카드를 써 주기",
        "버스를 같이 타 주기",
        "짐을 들어 주기",
      ],
      answer: 1,
      clue: "Could you mail this package for me?",
      explanation:
        "남자는 소포를 대신 부쳐 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 채린아, 너 매일 우체국 앞을 지나가지.",
        "W: 버스 정류장 가는 길에 바로 있어.",
        "M: 대구에 있는 사촌한테 보낼 소포가 있어.",
        "W: 들고 가기 무거워?",
        "M: 책 한 권이랑 생일 카드뿐이야.",
        "W: 언제까지 가야 해?",
        "M: 금요일 전에. 아니면 카드가 늦어.",
        "W: 우체국은 평일에 여섯 시에 닫아.",
        "M: 이 소포 좀 대신 부쳐 줄 수 있어?",
        "W: 줘, 오늘 보낼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 미술 전시회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The art exhibition opens next week. " +
            "Works will be shown in the first floor hallway. " +
            "The exhibition runs from Monday to Friday. " +
            "Paintings, photographs and small sculptures are all included. " +
            "Please do not touch any of the works. " +
            "Visitors may leave a short note in the comment book.",
        ],
      ],
      choices: ["전시하는 곳", "전시 기간", "전시되는 작품", "지켜야 할 것", "작품을 낸 학생 수"],
      answer: 5,
      clue: "Works will be shown in the first floor hallway.",
      explanation:
        "장소, 기간, 작품, 주의 사항은 말했지만 참여 학생 수는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 다음 주에 미술 전시회가 열립니다. 작품은 1층 복도에 전시됩니다. 전시는 월요일부터 금요일까지 이어집니다. 그림, 사진, 작은 조각이 모두 포함됩니다. 어떤 작품에도 손대지 말아 주세요. 관람하신 분은 방명록에 짧은 글을 남기셔도 됩니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This sits on your desk and holds many words. " +
            "You open it when you meet a word you don't know. " +
            "The words inside are in alphabetical order. " +
            "Each word comes with its meaning and an example. " +
            "Students keep a small one in their school bags.",
        ],
      ],
      choices: ["공책", "사전", "달력", "지도", "잡지"],
      answer: 2,
      clue: "The words inside are in alphabetical order.",
      explanation:
        "모르는 낱말의 뜻을 찾아보는 책은 사전이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 책상 위에 놓여 있고 많은 낱말을 담고 있습니다. 모르는 낱말을 만나면 이것을 펼칩니다. 안의 낱말들은 알파벳 순서로 실려 있습니다. 낱말마다 뜻과 예문이 함께 나옵니다. 학생들은 작은 것을 책가방에 넣고 다닙니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How often do you go swimming?"],
        ["W", "Twice a week."],
        ["ANN", "Number two."],
        ["M", "Could I borrow a pencil?"],
        ["W", "Take this one."],
        ["ANN", "Number three."],
        ["M", "What's your sister's name?"],
        ["W", "The bus leaves at eight."],
        ["ANN", "Number four."],
        ["M", "Do you want to join us?"],
        ["W", "I'd love to, thanks."],
        ["ANN", "Number five."],
        ["M", "Where did you buy that hat?"],
        ["W", "At the market last Sunday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "What's your sister's name?",
      explanation:
        "언니 이름을 묻는 말에 버스 시각을 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 수영하러 얼마나 자주 가? / W: 일주일에 두 번.",
        "② M: 연필 좀 빌려도 될까? / W: 이거 써.",
        "③ M: 네 언니 이름이 뭐야? / W: 버스는 여덟 시에 떠나.",
        "④ M: 우리랑 같이 할래? / W: 좋아, 고마워.",
        "⑤ M: 그 모자 어디서 샀어? / W: 지난 일요일에 시장에서.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sujin, the school band plays in half an hour."],
        ["W", "The chairs and stands are all in place."],
        ["M", "Did anyone bring the extra drum sticks?"],
        ["W", "They are still in the music room cupboard."],
        ["M", "Minsu broke one pair during practice."],
        ["W", "Then we need the spare pair for sure."],
        ["M", "I'll keep setting up the microphones."],
        ["W", "I'll run to the music room for the sticks."],
      ],
      choices: [
        "의자를 놓기",
        "마이크를 설치하기",
        "북채를 가져오기",
        "연주를 시작하기",
        "관객을 안내하기",
      ],
      answer: 3,
      clue: "I'll run to the music room for the sticks.",
      explanation:
        "여자는 음악실로 북채를 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수진아, 30분 뒤에 학교 밴드가 연주해.",
        "W: 의자랑 보면대는 다 놓았어.",
        "M: 여분 북채는 누가 가져왔어?",
        "W: 아직 음악실 장에 있어.",
        "M: 민수가 연습 때 한 쌍을 부러뜨렸어.",
        "W: 그럼 여분이 꼭 필요하겠다.",
        "M: 나는 계속 마이크를 설치할게.",
        "W: 내가 음악실로 북채 가지러 뛰어갈게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 신청할 방과 후 수업을 고르시오.",
      lines: [
        ["W", "Kiyoung, which after-school class should we take together?"],
        ["M", "Five classes are open this term."],
        ["W", "I can't come on Wednesday because of piano."],
        ["M", "Then one class is already out."],
        ["W", "The class should also be one hour long."],
        ["M", "Two of them run for two hours."],
        ["W", "And the fee has to be under forty thousand won."],
        ["M", "Then only one class works for both of us."],
        ["W", "Let's sign up together tomorrow morning."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I can't come on Wednesday because of piano.",
      explanation:
        "수요일이 아니고 한 시간이며 수강료 4만 원 미만인 수업은 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Wednesday / Length: 1 hour / Fee: 30,000 won" },
          { no: 2, label: "②", value: "Day: Monday / Length: 2 hours / Fee: 35,000 won" },
          { no: 3, label: "③", value: "Day: Tuesday / Length: 2 hours / Fee: 38,000 won" },
          { no: 4, label: "④", value: "Day: Thursday / Length: 1 hour / Fee: 45,000 won" },
          { no: 5, label: "⑤", value: "Day: Friday / Length: 1 hour / Fee: 36,000 won" },
        ],
      },
      translation: [
        "W: 기영아, 방과 후 수업 뭘 같이 들을까?",
        "M: 이번 학기에 다섯 개가 열렸어.",
        "W: 나는 피아노 때문에 수요일에 못 와.",
        "M: 그럼 하나는 벌써 빠지네.",
        "W: 수업은 한 시간짜리였으면 좋겠어.",
        "M: 두 개는 두 시간이야.",
        "W: 그리고 수강료는 4만 원 미만이어야 해.",
        "M: 그럼 우리 둘 다 되는 건 하나뿐이야.",
        "W: 내일 아침에 같이 신청하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진을 찍을 날짜를 고르시오.",
      lines: [
        ["M", "Yerim, when should we take the club photo?"],
        ["W", "The photographer offered three days this month."],
        ["M", "Which days did he write down?"],
        ["W", "The fourteenth, the sixteenth and the nineteenth."],
        ["M", "Half the club goes on a field trip on the fourteenth."],
        ["W", "And the nineteenth is during the exam week."],
        ["M", "Then the sixteenth is the only day left."],
        ["W", "He wants everyone there by three o'clock."],
        ["M", "I'll tell the members about the sixteenth."],
      ],
      choices: ["the 14th", "the 16th", "the 19th", "the 12th", "the 21st"],
      answer: 2,
      clue: "Then the sixteenth is the only day left.",
      explanation:
        "14일은 현장 학습, 19일은 시험 주간이어서 16일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "M: 예림아, 동아리 사진 언제 찍을까?",
        "W: 사진사분이 이번 달에 사흘을 제안하셨어.",
        "M: 어떤 날들을 적어 주셨어?",
        "W: 14일, 16일, 19일.",
        "M: 14일에는 동아리 절반이 현장 학습을 가.",
        "W: 19일은 시험 주간이고.",
        "M: 그럼 남는 날은 16일뿐이네.",
        "W: 세 시까지 다 모이라고 하셨어.",
        "M: 회원들한테 16일이라고 알릴게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난주에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyoju, where were you last Wednesday?"],
        ["W", "I helped at the city library all afternoon."],
        ["M", "What kind of work did they give you?"],
        ["W", "I put returned books back on the shelves."],
        ["M", "That sounds harder than it looks."],
        ["W", "The numbers on the spines are very small."],
        ["M", "Did you finish the whole cart?"],
        ["W", "Two carts, and my arms ached afterwards."],
        ["M", "Will you go again this week?"],
        ["W", "Every Wednesday until the end of the term."],
      ],
      choices: [
        "책을 빌렸다",
        "병원에 갔다",
        "도서관에서 일을 도왔다",
        "친구를 만났다",
        "집에서 쉬었다",
      ],
      answer: 3,
      clue: "I helped at the city library all afternoon.",
      explanation:
        "여자는 지난주에 시립 도서관에서 일을 도왔다. 따라서 답은 ③이다.",
      translation: [
        "M: 효주야, 지난 수요일에 어디 있었어?",
        "W: 오후 내내 시립 도서관에서 도왔어.",
        "M: 어떤 일을 맡았어?",
        "W: 반납된 책을 서가에 다시 꽂았어.",
        "M: 보기보다 힘들 것 같은데.",
        "W: 책등에 있는 번호가 아주 작아.",
        "M: 수레를 다 끝냈어?",
        "W: 두 대. 끝나고 팔이 아팠어.",
        "M: 이번 주에도 가?",
        "W: 학기 끝날 때까지 수요일마다.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the student council. " +
            "We are looking for volunteers for the school festival. " +
            "We need help at the gate and in the booths. " +
            "Each volunteer works for two hours only. " +
            "You may choose the morning or the afternoon. " +
            "Write your name on the sheet outside our room. " +
            "We close the list this Thursday evening.",
        ],
      ],
      choices: [
        "축제를 미루려고",
        "축제 자원봉사자를 모으려고",
        "분실물을 찾으려고",
        "청소를 부탁하려고",
        "동아리를 소개하려고",
      ],
      answer: 2,
      clue: "We are looking for volunteers for the school festival.",
      explanation:
        "축제에서 일할 자원봉사자를 모으는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 학생회입니다. 학교 축제에서 도와줄 자원봉사자를 찾고 있습니다. 정문과 부스에서 손이 필요합니다. 자원봉사자는 두 시간만 일합니다. 오전과 오후 중에 고르시면 됩니다. 학생회실 밖에 있는 종이에 이름을 적어 주세요. 명단은 이번 주 목요일 저녁에 마감합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the museum?"],
        ["M", "Yes, three student tickets, please."],
        ["W", "Student tickets are four dollars each."],
        ["M", "Is the special exhibition extra?"],
        ["W", "That room costs one dollar per person."],
        ["M", "We'd like to see it as well."],
        ["W", "So three tickets and three exhibition passes."],
        ["M", "Do you have a group discount?"],
        ["W", "Only for groups of ten or more."],
        ["M", "All right. Here you are."],
      ],
      choices: ["$12", "$13", "$14", "$15", "$16"],
      answer: 4,
      clue: "Student tickets are four dollars each.",
      explanation:
        "학생 표 세 장 12달러와 특별전 세 명 3달러를 더하면 15달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요. 박물관 표 사시나요?",
        "M: 네, 학생 표 세 장 주세요.",
        "W: 학생 표는 한 장에 4달러입니다.",
        "M: 특별 전시는 따로인가요?",
        "W: 그 전시실은 한 사람당 1달러입니다.",
        "M: 그것도 보고 싶어요.",
        "W: 그럼 표 세 장에 특별전 세 명이네요.",
        "M: 단체 할인은 있나요?",
        "W: 열 명 이상일 때만 됩니다.",
        "M: 알겠습니다. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Woosung, your science notes are always so clear."],
        ["M", "I rewrite them once on the same evening."],
        ["W", "Doesn't writing everything twice waste time?"],
        ["M", "The second time takes only eight minutes."],
        ["W", "I can't read my own writing by Friday."],
        ["M", "Leave a wide margin on the left side."],
        ["W", "What do I write in the margin?"],
        ["M", "One question you still can't answer."],
        ["W", "What if I have no questions that day?"],
      ],
      choices: [
        "Then leave the margin empty.",
        "Stop taking notes at all.",
        "Write the whole page again.",
        "Questions are never useful.",
        "Throw the notebook away.",
      ],
      answer: 1,
      clue: "What if I have no questions that day?",
      explanation:
        "질문이 없는 날에 대해 물었으므로, 여백을 비워 두라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 우성아, 네 과학 필기는 늘 깔끔해.",
        "M: 그날 저녁에 한 번 다시 써.",
        "W: 다 두 번 쓰면 시간이 아깝지 않아?",
        "M: 두 번째는 8분밖에 안 걸려.",
        "W: 나는 금요일쯤이면 내 글씨를 못 읽어.",
        "M: 왼쪽에 여백을 넓게 남겨 둬.",
        "W: 여백에는 뭘 써?",
        "M: 아직 답 못 하는 질문 하나.",
        "W: 그날 질문이 없으면 어떻게 해?",
        "M: 그럼 여백을 비워 둬.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Eunseo, I heard you take care of the school rabbits."],
        ["W", "Two of them live in the hutch behind the garden."],
        ["M", "Who looks after them on the weekend?"],
        ["W", "Three of us take turns every Saturday."],
        ["M", "What do you feed them?"],
        ["W", "Hay in the morning and vegetables in the evening."],
        ["M", "Is it hard to clean the hutch?"],
        ["W", "It takes twenty minutes with two people."],
        ["M", "Do they let you hold them?"],
        ["W", "Only the older one sits still."],
        ["M", "Could I come and see them this Saturday?"],
      ],
      choices: [
        "Sure, come at ten o'clock.",
        "The rabbits are gone.",
        "I don't feed them.",
        "We have no garden here.",
        "Nobody can see them.",
      ],
      answer: 1,
      clue: "Could I come and see them this Saturday?",
      explanation:
        "토요일에 보러 가도 되는지 물었으므로, 열 시에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 은서야, 네가 학교 토끼를 돌본다며.",
        "W: 화단 뒤 우리에 두 마리가 살아.",
        "M: 주말에는 누가 돌봐?",
        "W: 셋이서 토요일마다 돌아가며 해.",
        "M: 뭘 먹여?",
        "W: 아침에는 마른풀, 저녁에는 채소.",
        "M: 우리 청소는 힘들어?",
        "W: 둘이 하면 20분 걸려.",
        "M: 안아 보게 해 줘?",
        "W: 나이 많은 애만 가만히 있어.",
        "M: 이번 토요일에 보러 가도 돼?",
        "W: 그럼, 열 시에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jinho, how is the class garden doing this month?"],
        ["W", "You said the seeds went in three weeks ago."],
        ["M", "Only half of them have come up so far."],
        ["W", "Where exactly did you plant them?"],
        ["M", "Along the wall on the north side."],
        ["W", "That side gets shade for most of the day."],
        ["M", "I never thought about the sunlight."],
        ["W", "Seeds need several hours of direct sun."],
        ["M", "The south bed is empty right now."],
        ["W", "Why don't you plant the next batch there?"],
      ],
      choices: [
        "I'll try the south bed.",
        "Seeds don't need sun.",
        "We have no seeds left.",
        "The garden is closed.",
        "I'll plant them indoors.",
      ],
      answer: 1,
      clue: "Why don't you plant the next batch there?",
      explanation:
        "남쪽 화단에 심어 보라는 제안이므로, 그렇게 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 진호야, 이번 달 학급 텃밭은 어때?",
        "W: 3주 전에 씨를 심었다고 했잖아.",
        "M: 지금까지 절반만 올라왔어.",
        "W: 정확히 어디에 심었어?",
        "M: 북쪽 벽을 따라서.",
        "W: 그쪽은 하루 대부분이 그늘이야.",
        "M: 햇빛은 생각도 못 했어.",
        "W: 씨앗은 직사광선이 몇 시간은 필요해.",
        "M: 남쪽 화단은 지금 비어 있어.",
        "W: 다음 씨앗은 거기에 심어 보는 건 어때?",
        "M: 남쪽 화단에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minseo가 Hanbin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Minseo : ________________",
      lines: [
        [
          "W",
          "Minseo and Hanbin are setting up chairs for the school concert. " +
            "Hanbin has stacked eight chairs into one very tall pile. " +
            "Minseo sees the top of the pile leaning toward the window. " +
            "He is about to lift the whole stack by himself. " +
            "She wants him to carry fewer chairs at one time. " +
            "In this situation, what would Minseo most likely say to Hanbin?",
        ],
      ],
      choices: [
        "The concert is tomorrow.",
        "Put the chairs outside.",
        "We need twenty more chairs.",
        "Take only four at a time.",
        "Lift the whole pile alone.",
      ],
      answer: 4,
      clue: "She wants him to carry fewer chairs at one time.",
      explanation:
        "쌓은 의자가 기울어 위험하므로, 한 번에 네 개씩만 들라는 ④가 가장 적절하다.",
      translation: [
        "W: 민서와 한빈이는 학교 음악회에 쓸 의자를 놓고 있습니다. 한빈이는 의자 여덟 개를 아주 높이 쌓아 올렸습니다. 민서는 쌓은 더미의 위쪽이 창문 쪽으로 기우는 것을 봅니다. 그는 그 더미를 혼자 들어 올리려고 합니다. 그녀는 그가 한 번에 더 적게 들기를 바랍니다. 이런 상황에서 민서가 한빈이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
