/** 중2 듣기 26회 — 사람이 직접 쓴 회차 (2026-09-23) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 26회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 화병을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a flower vase?"],
        ["W", "Yes, one for the table in our living room."],
        ["M", "We have tall narrow vases and wide low ones."],
        ["W", "A wide low one, please. Tall vases fall over easily."],
        ["M", "All right. This wide vase has a handle on the side."],
        ["W", "A handle makes it look like a jug to me."],
        ["M", "Then here is a wide one with no handle at all."],
        ["W", "That's the one. I'll take the plain wide vase."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A wide low one, please. / I'll take the plain wide vase.",
      explanation:
        "여자는 넓고 낮은 화병을 원하고, 손잡이가 달린 것 대신 손잡이가 없는 것을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five empty flower vases drawn side by side as five choices, clean black line art on white. " +
          "① a TALL NARROW vase with a HANDLE on one side. " +
          "② a TALL NARROW vase with NO handle. " +
          "③ a WIDE LOW vase with a HANDLE on one side. " +
          "④ a TALL NARROW vase with TWO handles, one on each side. " +
          "⑤ a WIDE LOW vase with NO handle at all. " +
          "The tall vases are clearly about twice as tall as the wide low ones.",
      },
      translation: [
        "M: 안녕하세요. 화병 찾으세요?",
        "W: 네, 거실 탁자에 놓을 거예요.",
        "M: 길고 좁은 것도 있고 넓고 낮은 것도 있어요.",
        "W: 넓고 낮은 걸로 주세요. 긴 건 잘 넘어져요.",
        "M: 알겠습니다. 이 넓은 화병은 옆에 손잡이가 있어요.",
        "W: 손잡이가 있으면 주전자 같아 보여요.",
        "M: 그럼 손잡이가 전혀 없는 넓은 화병이 여기 있어요.",
        "W: 그거예요. 손잡이 없는 넓은 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 과학 탐구 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Taeyeon, are you entering the science research contest?"],
        ["M", "I want to. When do we have to submit our work?"],
        ["W", "By the last day of next month."],
        ["M", "How many people can be on one team?"],
        ["W", "Up to three students per team."],
        ["M", "What form does the report have to take?"],
        ["W", "Ten pages of writing plus one poster."],
        ["M", "That's a lot. Where do we hand it in?"],
        ["W", "At the science office on the second floor."],
      ],
      choices: ["제출 기한", "한 팀의 인원", "보고서 형식", "제출 장소", "시상 내용"],
      answer: 5,
      clue: "시상 내용은 대화에서 언급되지 않았다.",
      explanation:
        "제출 기한(다음 달 마지막 날), 한 팀 인원(최대 3명), 보고서 형식(10쪽과 포스터 한 장), 제출 장소(2층 과학실)는 언급되지만 시상 내용은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 태연아, 과학 탐구 대회 나갈 거야?",
        "M: 나가고 싶어. 언제까지 내야 해?",
        "W: 다음 달 마지막 날까지.",
        "M: 한 팀에 몇 명까지 돼?",
        "W: 한 팀에 최대 세 명.",
        "M: 보고서는 어떤 형식이어야 해?",
        "W: 글 10쪽에 포스터 한 장.",
        "M: 많다. 어디에 내?",
        "W: 2층 과학실에.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Miso Photo Studio?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "Our family took photos there two weeks ago."],
        ["W", "Are you calling about the printed album?"],
        ["M", "Yes, we ordered one but it hasn't arrived."],
        ["W", "Let me look it up. Under what name?"],
        ["M", "Jiwon Han. We ordered it on the ninth."],
        ["W", "I see it here. It will be ready this Friday."],
      ],
      choices: [
        "사진을 새로 찍으려고",
        "촬영 예약을 하려고",
        "주문한 앨범이 언제 되는지 물으려고",
        "사진관 위치를 물어보려고",
        "사진값을 물어보려고",
      ],
      answer: 3,
      clue: "Yes, we ordered one but it hasn't arrived.",
      explanation:
        "남자는 2주 전에 주문한 사진 앨범이 아직 오지 않아 언제 되는지 물으려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "M: 여보세요, 미소 사진관이죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 2주 전에 저희 가족이 거기서 사진을 찍었어요.",
        "W: 인화한 앨범 때문에 전화하셨나요?",
        "M: 네, 하나 주문했는데 아직 안 왔어요.",
        "W: 찾아볼게요. 성함이 어떻게 되시죠?",
        "M: 한지원이요. 9일에 주문했어요.",
        "W: 여기 있네요. 이번 주 금요일에 준비됩니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taeyeon, what time does the museum tour begin?"],
        ["M", "The guided tour starts at two in the afternoon."],
        ["W", "Do we have to pick up the tickets first?"],
        ["M", "Yes, and the ticket line can be long on Saturday."],
        ["W", "How much time should we leave for the line?"],
        ["M", "Forty-five minutes at least, my sister said."],
        ["W", "Then let's meet forty-five minutes before the tour."],
        ["M", "Good. I'll stand near the fountain outside."],
        ["W", "Okay, I'll look for you there."],
      ],
      choices: ["1:15 p.m.", "1:00 p.m.", "1:30 p.m.", "2:00 p.m.", "2:45 p.m."],
      answer: 1,
      clue: "Then let's meet forty-five minutes before the tour.",
      explanation:
        "해설 관람이 2시에 시작하고 45분 전에 만나기로 했으므로 만나는 시각은 1시 15분이다. 따라서 답은 ①이다.",
      translation: [
        "W: 태연아, 박물관 해설 관람이 몇 시에 시작해?",
        "M: 해설 관람은 오후 2시에 시작해.",
        "W: 표를 먼저 받아야 해?",
        "M: 응, 토요일엔 표 사는 줄이 길 수 있어.",
        "W: 줄 서는 시간을 얼마나 잡아야 해?",
        "M: 누나 말로는 적어도 45분.",
        "W: 그럼 관람 45분 전에 만나자.",
        "M: 좋아. 나는 밖에 분수 근처에 서 있을게.",
        "W: 알겠어, 거기서 찾을게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiwon, why are you sitting outside the classroom?"],
        ["W", "Someone took my drawing off the display board."],
        ["M", "The one you worked on for three weeks?"],
        ["W", "Yes, and they didn't even ask me first."],
        ["M", "Maybe the teacher moved it to another wall."],
        ["W", "No, I found it crumpled in the recycling bin."],
        ["M", "That's really not okay."],
        ["W", "I can't believe someone would just throw it away."],
      ],
      choices: ["shy", "sleepy", "curious", "upset", "thankful"],
      answer: 4,
      clue: "I can't believe someone would just throw it away.",
      explanation:
        "3주 동안 그린 그림이 구겨진 채 재활용통에 버려져 있었다고 했으므로 여자의 심정은 '속상한(upset)'이다. 따라서 답은 ④이다.",
      translation: [
        "M: 지원아, 왜 교실 밖에 앉아 있어?",
        "W: 누가 게시판에서 내 그림을 떼어 갔어.",
        "M: 3주 동안 그린 그거?",
        "W: 응, 나한테 물어보지도 않고.",
        "M: 선생님이 다른 벽으로 옮기셨을 수도 있잖아.",
        "W: 아니, 재활용통에서 구겨진 채로 찾았어.",
        "M: 그건 정말 아니다.",
        "W: 누가 그냥 버렸다는 게 믿기지 않아.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Excuse me, your bag is caught in the door."],
        ["M", "Oh no, thank you for telling me."],
        ["ANN", "Number two."],
        ["W", "Which line goes to City Hall?"],
        ["M", "Take line two from platform one."],
        ["ANN", "Number three."],
        ["W", "Is this train going downtown?"],
        ["M", "Yes, it is."],
        ["ANN", "Number four."],
        ["W", "How many stops until the museum?"],
        ["M", "Three more stops."],
        ["ANN", "Number five."],
        ["W", "Do you have a transit card?"],
        ["M", "Yes, I bought one yesterday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Excuse me, your bag is caught in the door.",
      explanation:
        "그림은 지하철 문에 남자의 가방끈이 끼인 것을 여자가 가리키며 알려 주는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a subway car, clean black line art on a plain white background, no writing anywhere. " +
          "A man stands near the closed sliding doors, and the long strap of his shoulder bag is pinched between the two doors. " +
          "A woman beside him points at the trapped strap and speaks to him. " +
          "Seats, a handrail and hanging straps are drawn simply in the background.",
      },
      translation: [
        "① W: 저기요, 가방이 문에 끼었어요. / M: 어머, 알려 주셔서 감사합니다.",
        "② W: 시청에 가려면 몇 호선이에요? / M: 1번 승강장에서 2호선 타세요.",
        "③ W: 이 열차가 시내로 가나요? / M: 네, 맞습니다.",
        "④ W: 박물관까지 몇 정거장이에요? / M: 세 정거장 더 가요.",
        "⑤ W: 교통 카드 있으세요? / M: 네, 어제 샀어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeyeon, you have a printer at home, don't you?"],
        ["M", "Yes, my father uses it for work."],
        ["W", "Our club needs forty copies of a one-page form."],
        ["M", "Can't you use the school copy machine?"],
        ["W", "It's broken, and the repair takes three days."],
        ["M", "And you need them before then?"],
        ["W", "Yes, could you print forty copies tonight?"],
        ["M", "Sure. I'll bring them to the club room tomorrow."],
      ],
      choices: ["복사기 고치기", "동아리 가입하기", "프린터 빌려주기", "서류 작성하기", "서류 인쇄해 오기"],
      answer: 5,
      clue: "Yes, could you print forty copies tonight?",
      explanation:
        "여자는 학교 복사기가 고장 나서 남자에게 서류 마흔 장을 집에서 인쇄해 와 달라고 부탁했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 태연아, 너희 집에 프린터 있지?",
        "M: 응, 아버지가 일할 때 쓰셔.",
        "W: 우리 동아리에 한 쪽짜리 서류 마흔 장이 필요해.",
        "M: 학교 복사기 쓰면 안 돼?",
        "W: 고장 났는데 수리에 사흘 걸린대.",
        "M: 그전에 필요한 거야?",
        "W: 응, 오늘 밤에 마흔 장만 인쇄해 줄 수 있어?",
        "M: 그럼. 내일 동아리방으로 가져갈게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 축구 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The class soccer tournament starts next Wednesday. " +
            "All the matches will be played on the outdoor field behind the gym. " +
            "Each team has eleven players and three substitutes. " +
            "A match lasts thirty minutes, split into two halves. " +
            "Please bring your own water bottle and wear your gym clothes. " +
            "Come and cheer for your class.",
        ],
      ],
      choices: ["시작하는 날", "경기 장소", "우승 상품", "한 팀의 인원", "한 경기 시간"],
      answer: 3,
      clue: "우승 상품은 방송에서 언급되지 않았다.",
      explanation:
        "시작하는 날(다음 주 수요일), 장소(체육관 뒤 운동장), 한 팀 인원(선수 11명과 교체 3명), 경기 시간(30분)은 언급되지만 우승 상품은 언급되지 않았다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 학급 축구 대회가 다음 주 수요일에 시작합니다. 모든 경기는 체육관 뒤 운동장에서 진행됩니다. 한 팀은 선수 열한 명과 교체 선수 세 명으로 이루어집니다. 한 경기는 전후반으로 나눠 30분간 진행됩니다. 물병은 각자 준비하고 체육복을 입고 오세요. 오셔서 반을 응원해 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a job that keeps a whole building safe at night. " +
            "The person walks around the halls and checks that every door is locked. " +
            "They watch many small screens in a small room near the entrance. " +
            "If they see something strange, they call the police right away. " +
            "Most of them work while the rest of us are sleeping.",
        ],
      ],
      choices: ["경비원", "요리사", "운전기사", "정원사", "교사"],
      answer: 1,
      clue: "The person walks around the halls and checks that every door is locked.",
      explanation:
        "밤에 건물을 돌며 문을 확인하고 작은 화면들을 지켜보는 사람은 경비원이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이 직업은 밤에 건물 전체를 안전하게 지킵니다. 이 일을 하는 사람은 복도를 돌아다니며 문이 다 잠겼는지 확인합니다. 입구 근처 작은 방에서 여러 개의 작은 화면을 지켜봅니다. 이상한 것이 보이면 바로 경찰에 연락합니다. 대부분 우리가 잠든 사이에 일합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What kind of movies do you like?"],
        ["W", "I enjoy comedies the most."],
        ["ANN", "Number two."],
        ["M", "Would you like some more rice?"],
        ["W", "No, thank you. I'm full."],
        ["ANN", "Number three."],
        ["M", "How was your first day at the new school?"],
        ["W", "Everyone was really friendly."],
        ["ANN", "Number four."],
        ["M", "Could you tell me the way to the bank?"],
        ["W", "I like winter better than summer."],
        ["ANN", "Number five."],
        ["M", "When does the club meeting start?"],
        ["W", "At four o'clock sharp."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Could you tell me the way to the bank?",
      explanation:
        "은행 가는 길을 묻는 말에 겨울이 여름보다 좋다고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 어떤 영화 좋아해? / W: 나는 코미디를 제일 좋아해.",
        "② M: 밥 더 줄까? / W: 아니, 괜찮아. 배불러.",
        "③ M: 새 학교 첫날 어땠어? / W: 다들 정말 친절했어.",
        "④ M: 은행 가는 길 좀 알려 줄래? / W: 나는 여름보다 겨울이 좋아.",
        "⑤ M: 동아리 모임 몇 시에 시작해? / W: 4시 정각에.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeyeon, the club photo shoot starts in ten minutes."],
        ["M", "I know. Are all the members in the courtyard?"],
        ["W", "Yes, everyone came except two people."],
        ["M", "Good. Did you bring the club banner?"],
        ["W", "I did, but the wooden pole is still in the storage room."],
        ["M", "Without the pole nobody can hold the banner up."],
        ["W", "I have to line everyone up by height."],
        ["M", "Then I'll run to the storage room and get the pole."],
      ],
      choices: ["현수막 가져오기", "장대 가져오기", "부원 줄 세우기", "사진 찍기", "창고 청소하기"],
      answer: 2,
      clue: "Then I'll run to the storage room and get the pole.",
      explanation:
        "현수막을 들 장대가 창고에 있고 여자는 부원들을 줄 세워야 해서, 남자가 창고로 달려가 장대를 가져오겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 태연아, 동아리 사진 촬영이 10분 뒤에 시작해.",
        "M: 알아. 부원들 다 안뜰에 있어?",
        "W: 응, 두 명 빼고 다 왔어.",
        "M: 잘됐다. 동아리 현수막은 가져왔어?",
        "W: 가져왔는데, 나무 장대가 아직 창고에 있어.",
        "M: 장대가 없으면 현수막을 들 수가 없어.",
        "W: 나는 부원들을 키 순서로 세워야 해.",
        "M: 그럼 내가 창고로 달려가서 장대를 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 체험 활동을 고르시오.",
      lines: [
        ["M", "Jiwon, which hands-on program are you choosing?"],
        ["W", "Let me look at the five options first."],
        ["M", "Do you have time on Saturday morning?"],
        ["W", "No, I take a math class every Saturday morning."],
        ["M", "So it has to be a weekday or Sunday."],
        ["W", "Right. And I don't want anything outdoors."],
        ["M", "Why not? The weather is nice this month."],
        ["W", "I get sunburned very easily, even in autumn."],
        ["M", "Then only one program on this list is left."],
        ["W", "Good. I'll hand in the form this afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "No, I take a math class every Saturday morning.",
      explanation:
        "토요일 오전이 아니고 실내에서 하는 것을 고른다. 두 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Saturday morning / Place: Indoors / Program: Pottery" },
          { no: 2, label: "②", value: "Day: Sunday / Place: Outdoors / Program: Farming" },
          { no: 3, label: "③", value: "Day: Saturday morning / Place: Outdoors / Program: Hiking" },
          { no: 4, label: "④", value: "Day: Friday / Place: Outdoors / Program: Fishing" },
          { no: 5, label: "⑤", value: "Day: Thursday / Place: Indoors / Program: Baking" },
        ],
      },
      translation: [
        "M: 지원아, 어떤 체험 활동 고를 거야?",
        "W: 다섯 가지부터 볼게.",
        "M: 토요일 오전에 시간 돼?",
        "W: 아니, 토요일 오전마다 수학 수업이 있어.",
        "M: 그럼 평일이나 일요일이어야겠네.",
        "W: 맞아. 그리고 야외에서 하는 건 싫어.",
        "M: 왜? 이달엔 날씨 좋은데.",
        "W: 가을에도 쉽게 햇볕에 타서.",
        "M: 그럼 이 목록에서 남는 건 하나뿐이야.",
        "W: 좋아. 오늘 오후에 신청서 낼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 연습 경기를 할 날짜를 고르시오.",
      lines: [
        ["M", "Jiwon, when can our team play the practice match?"],
        ["W", "How about March 6th? That's next Friday."],
        ["M", "The field is booked by the third graders that day."],
        ["W", "Then what about March 9th?"],
        ["M", "It's the school opening ceremony on the 9th."],
        ["W", "Hmm. I'm free on March 16th."],
        ["M", "But the real match is on the 14th."],
        ["W", "Oh, right. Then let's play on March 11th."],
        ["M", "March 11th works. The field is empty that afternoon."],
        ["W", "Perfect. Let's tell the team tomorrow."],
      ],
      choices: ["3월 6일", "3월 9일", "3월 11일", "3월 14일", "3월 16일"],
      answer: 3,
      clue: "Oh, right. Then let's play on March 11th.",
      explanation:
        "6일에는 3학년이 운동장을 쓰고, 9일에는 개학식이 있으며, 16일은 실제 경기(14일) 이후다. 두 사람은 3월 11일에 하기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 지원아, 우리 팀 연습 경기 언제 할까?",
        "W: 3월 6일 어때? 다음 주 금요일이야.",
        "M: 그날은 3학년이 운동장을 예약했어.",
        "W: 그럼 3월 9일은?",
        "M: 9일은 개학식이야.",
        "W: 음. 나는 3월 16일이 비어.",
        "M: 그런데 실제 경기가 14일이야.",
        "W: 아, 맞다. 그럼 3월 11일에 하자.",
        "M: 3월 11일 괜찮아. 그날 오후엔 운동장이 비어.",
        "W: 좋아. 내일 팀에 알리자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taeyeon, why are your arms covered in scratches?"],
        ["M", "I was up on the hill behind our town all Sunday."],
        ["W", "Did you go hiking with your family?"],
        ["M", "No, our class pulled out weeds along the walking path."],
        ["W", "How long is that path?"],
        ["M", "Almost two kilometers, and the weeds were taller than me."],
        ["W", "No wonder your arms look like that."],
        ["M", "It was worth it. People can walk there safely now."],
      ],
      choices: ["산책로 잡초 뽑기", "등산하기", "나무 심기", "길 만들기", "쓰레기 줍기"],
      answer: 1,
      clue: "No, our class pulled out weeds along the walking path.",
      explanation:
        "남자는 일요일에 반 친구들과 산책로의 잡초를 뽑았다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 태연아, 팔에 왜 이렇게 긁힌 자국이 많아?",
        "M: 일요일 내내 동네 뒷산에 있었어.",
        "W: 가족이랑 등산 갔어?",
        "M: 아니, 우리 반이 산책로를 따라 잡초를 뽑았어.",
        "W: 그 길이 얼마나 길어?",
        "M: 거의 2킬로미터. 잡초가 나보다 컸어.",
        "W: 그러니 팔이 그렇지.",
        "M: 그래도 보람 있었어. 이제 사람들이 안전하게 걸어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school library. " +
            "We have received two hundred new books this month. " +
            "They are on the shelves by the window on the first floor. " +
            "Most of them are novels and science books chosen by students. " +
            "You may borrow up to three of the new books at one time. " +
            "Come and have a look during your lunch break.",
        ],
      ],
      choices: [
        "도서관 공사를 알리려고",
        "연체된 책 반납을 당부하려고",
        "독서 대회를 안내하려고",
        "새로 들어온 책을 소개하려고",
        "도서관 여는 시간을 알리려고",
      ],
      answer: 4,
      clue: "We have received two hundred new books this month.",
      explanation:
        "이달에 들어온 새 책 200권이 어디에 있고 몇 권까지 빌릴 수 있는지 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "W: 안내 말씀 드립니다. 학교 도서관입니다. 이달에 새 책 200권이 들어왔습니다. 1층 창가 쪽 책장에 꽂혀 있습니다. 대부분 학생들이 고른 소설과 과학책입니다. 새 책은 한 번에 세 권까지 빌릴 수 있습니다. 점심시간에 와서 둘러보세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you renting skates for today?"],
        ["M", "Yes, three pairs for two hours, please."],
        ["W", "One pair is six dollars an hour."],
        ["M", "So that's thirty-six dollars for all three."],
        ["W", "That's right. Would you like gloves as well?"],
        ["M", "No, we brought our own."],
        ["W", "All right. Students get six dollars off the total."],
        ["M", "Great. Here are our student cards."],
      ],
      choices: ["$24", "$30", "$26", "$28", "$36"],
      answer: 2,
      clue: "All right. Students get six dollars off the total.",
      explanation:
        "스케이트 세 켤레를 두 시간 빌리면 36달러이고, 학생 할인 6달러를 빼면 30달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 오늘 스케이트 빌리시나요?",
        "M: 네, 두 시간 동안 세 켤레 주세요.",
        "W: 한 켤레에 한 시간 6달러입니다.",
        "M: 그럼 세 켤레면 36달러네요.",
        "W: 맞습니다. 장갑도 필요하세요?",
        "M: 아니요, 저희 것 가져왔어요.",
        "W: 알겠습니다. 학생은 전체에서 6달러 할인됩니다.",
        "M: 잘됐네요. 여기 학생증이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taeyeon, your handwriting is hard to read lately."],
        ["M", "I write as fast as I can during class."],
        ["W", "Then you can't read your own notes later, right?"],
        ["M", "That's true. I rewrite everything at home."],
        ["W", "So you're doing the same work twice."],
        ["M", "I never thought of it that way."],
        ["W", "Try writing only the key words in class."],
        ["M", "But what if I miss something important?"],
        ["W", "Leave a blank line and ask the teacher after class."],
      ],
      choices: [
        "I never take notes at all.",
        "My handwriting is very neat.",
        "The teacher writes for me.",
        "I'll rewrite everything twice.",
        "I'll try that in tomorrow's class.",
      ],
      answer: 5,
      clue: "Leave a blank line and ask the teacher after class.",
      explanation:
        "여자가 빈 줄을 남기고 수업 후에 선생님께 여쭤보라고 했으므로, 내일 수업에서 해 보겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 태연아, 요즘 네 글씨를 알아보기 힘들어.",
        "M: 수업 시간에 최대한 빨리 쓰거든.",
        "W: 그럼 나중에 네 필기를 네가 못 읽잖아?",
        "M: 맞아. 집에서 다 다시 써.",
        "W: 그럼 같은 일을 두 번 하는 거네.",
        "M: 그렇게는 생각 못 했어.",
        "W: 수업 때는 핵심 단어만 적어 봐.",
        "M: 그러다 중요한 걸 놓치면?",
        "W: 빈 줄 하나 남겨 두고 수업 끝나고 선생님께 여쭤봐.",
        "M: 내일 수업에서 그렇게 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Jiwon, your plant on the windowsill looks weak."],
        ["W", "I water it every single morning without fail."],
        ["M", "Is there a hole at the bottom of the pot?"],
        ["W", "I don't think so. It's a plain ceramic pot."],
        ["M", "Then the water has nowhere to go."],
        ["W", "So the roots are sitting in water all day?"],
        ["M", "Exactly, and that slowly kills most plants."],
        ["W", "What should I do about the pot, then?"],
        ["M", "Move the plant into a pot with a drain hole."],
      ],
      choices: [
        "I'll water it twice a day.",
        "My pot has three holes.",
        "I'll change the pot this weekend.",
        "The plant has no roots.",
        "Let's throw the plant away.",
      ],
      answer: 3,
      clue: "Move the plant into a pot with a drain hole.",
      explanation:
        "남자가 물 빠지는 구멍이 있는 화분으로 옮기라고 했으므로, 이번 주말에 화분을 바꾸겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 지원아, 창가에 있는 네 화분이 시들해 보여.",
        "W: 하루도 빠짐없이 아침마다 물 주는데.",
        "M: 화분 바닥에 구멍이 있어?",
        "W: 없는 것 같아. 그냥 도자기 화분이야.",
        "M: 그럼 물이 빠져나갈 데가 없네.",
        "W: 그럼 뿌리가 하루 종일 물에 잠겨 있는 거야?",
        "M: 그래, 그러면 대부분의 식물이 서서히 죽어.",
        "W: 그럼 화분을 어떻게 해야 해?",
        "M: 물 빠지는 구멍이 있는 화분으로 옮겨.",
        "W: 이번 주말에 화분 바꿀게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Jiwon, nobody signed up for our board game club."],
        ["W", "Did you put up a notice anywhere?"],
        ["M", "Yes, one sheet on the wall near the stairs."],
        ["W", "Only one? And what does it say?"],
        ["M", "Just the club name and the meeting time."],
        ["W", "That doesn't tell anyone what you actually do."],
        ["M", "So I should explain the games we play?"],
        ["W", "Yes, and let people try one game at lunch."],
        ["M", "Where would we even set that up?"],
        ["W", "The empty table by the cafeteria door is free every day."],
      ],
      choices: [
        "I'll set up a game there tomorrow.",
        "Our club has twenty members.",
        "There is no empty table.",
        "We don't play any games.",
        "I'll take the notice down.",
      ],
      answer: 1,
      clue: "The empty table by the cafeteria door is free every day.",
      explanation:
        "여자가 급식실 문 옆 빈 탁자가 매일 비어 있다고 알려 주었으므로, 내일 거기에 게임을 차려 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 지원아, 우리 보드게임 동아리에 아무도 신청을 안 했어.",
        "W: 어디에 안내문 붙이긴 했어?",
        "M: 응, 계단 근처 벽에 한 장.",
        "W: 한 장만? 뭐라고 써 놨는데?",
        "M: 동아리 이름이랑 모임 시간만.",
        "W: 그러면 실제로 뭘 하는지 아무도 모르잖아.",
        "M: 그럼 어떤 게임을 하는지 설명해야 해?",
        "W: 응, 그리고 점심시간에 한 판 해 보게 해 줘.",
        "M: 그걸 어디에 차려?",
        "W: 급식실 문 옆 빈 탁자가 매일 비어 있어.",
        "M: 내일 거기에 게임을 차려 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nayeong이 Hoyeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Nayeong : ________________",
      lines: [
        [
          "M",
          "Nayeong and Hoyeon are leaving the classroom after the last class. " +
            "Hoyeon has already put on her coat and picked up her bag. " +
            "Nayeong notices that Hoyeon's umbrella is still hanging on her chair. " +
            "It has been raining hard since the morning. " +
            "She wants to tell her before they reach the front door. " +
            "In this situation, what would Nayeong most likely say to Hoyeon?",
        ],
      ],
      choices: [
        "Let's stay in the classroom longer.",
        "The rain stopped an hour ago.",
        "I'll carry your bag for you.",
        "Your umbrella is on your chair.",
        "You should buy a new coat.",
      ],
      answer: 4,
      clue: "Nayeong notices that Hoyeon's umbrella is still hanging on her chair.",
      explanation:
        "비가 많이 오는데 호연이의 우산이 의자에 걸린 채 남아 있으므로, 그 사실을 알려 주는 ④가 가장 적절하다.",
      translation: [
        "M: 나영이와 호연이는 마지막 수업이 끝나고 교실을 나서고 있습니다. 호연이는 이미 외투를 입고 가방을 들었습니다. 나영이는 호연이의 우산이 아직 의자에 걸려 있는 것을 봅니다. 아침부터 비가 많이 오고 있습니다. 나영이는 정문에 닿기 전에 알려 주고 싶습니다. 이런 상황에서 나영이가 호연이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
