/** 중2 듣기 33회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 33회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 우산을 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for an umbrella?"],
        ["M", "Yes, one I can carry in my school bag."],
        ["W", "Then a folding umbrella suits you better than a long one."],
        ["M", "Right, a long one never fits in my bag."],
        ["W", "Do you want a straight handle or a curved one?"],
        ["M", "A curved handle, so I can hang it on my desk."],
        ["W", "This one has small dots all over it."],
        ["M", "I'd rather have no pattern at all."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Then a folding umbrella suits you better than a long one. / A curved handle, so I can hang it on my desk.",
      explanation:
        "남자는 접이식이면서 손잡이가 굽어 있고 무늬가 없는 우산을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five closed umbrellas standing side by side as five choices, clean black line art on white. " +
          "① a LONG full-size umbrella with a STRAIGHT handle and a PLAIN surface. " +
          "② a LONG full-size umbrella with a CURVED hook handle and a PLAIN surface. " +
          "③ a SHORT folding umbrella with a STRAIGHT handle and a PLAIN surface. " +
          "④ a SHORT folding umbrella with a CURVED hook handle and a PLAIN surface. " +
          "⑤ a SHORT folding umbrella with a CURVED hook handle and round DOTS printed all over it.",
      },
      translation: [
        "W: 안녕하세요. 우산 찾으세요?",
        "M: 네, 학교 가방에 넣고 다닐 거예요.",
        "W: 그러면 장우산보다 접이식이 더 맞겠네요.",
        "M: 맞아요, 장우산은 가방에 안 들어가요.",
        "W: 손잡이는 곧은 게 좋으세요, 굽은 게 좋으세요?",
        "M: 굽은 걸로요. 책상에 걸어 둘 수 있게요.",
        "W: 이건 작은 점무늬가 가득해요.",
        "M: 무늬는 아예 없는 게 좋아요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 진로 특강에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Yerim, are you going to the career talk this month?"],
        ["W", "I want to. When is it being held?"],
        ["M", "Next Thursday, during the sixth and seventh periods."],
        ["W", "Where does it take place?"],
        ["M", "In the multimedia room on the fourth floor."],
        ["W", "What is the talk about this time?"],
        ["M", "Jobs that did not exist twenty years ago."],
        ["W", "Do we have to sign up for it?"],
        ["M", "Yes, put your name on the list in the hallway."],
      ],
      choices: [
        "특강이 열리는 날",
        "강연하는 사람의 이름",
        "특강이 열리는 장소",
        "특강의 주제",
        "신청하는 방법",
      ],
      answer: 2,
      clue: "Next Thursday, during the sixth and seventh periods. / Jobs that did not exist twenty years ago.",
      explanation:
        "날짜, 장소, 주제, 신청 방법은 말했지만 강연자의 이름은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "M: 예림아, 이번 달 진로 특강 갈 거야?",
        "W: 가고 싶어. 언제 열려?",
        "M: 다음 주 목요일 6, 7교시에.",
        "W: 어디서 해?",
        "M: 4층 멀티미디어실에서.",
        "W: 이번 주제가 뭐야?",
        "M: 20년 전에는 없었던 직업들.",
        "W: 신청해야 해?",
        "M: 응, 복도에 있는 명단에 이름 적어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Jinwoo. It's Sujin. Sorry to call so early."],
        ["M", "That's all right. Is something wrong?"],
        ["W", "I had a high fever all night and I can't come today."],
        ["M", "Oh no. Did you go to the hospital?"],
        ["W", "My mother is taking me this morning."],
        ["M", "Do you want me to tell our homeroom teacher?"],
        ["W", "Yes, please. Tell her I'll bring a note tomorrow."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 잡으려고",
        "물건을 빌리려고",
        "길을 물어보려고",
        "결석한다고 알리려고",
      ],
      answer: 5,
      clue: "I had a high fever all night and I can't come today.",
      explanation:
        "여자는 열이 나서 학교에 못 간다고 알리려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 진우야. 수진이야. 이른 시간에 미안해.",
        "M: 괜찮아. 무슨 일 있어?",
        "W: 밤새 열이 나서 오늘 학교에 못 가.",
        "M: 이런. 병원에 갔어?",
        "W: 오늘 아침에 엄마가 데려가 주셔.",
        "M: 담임 선생님께 내가 말씀드릴까?",
        "W: 응, 부탁해. 내일 확인서 가져간다고 전해 줘.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Hyunbin, when does the science fair open on Saturday?"],
        ["M", "The doors open at eleven in the morning."],
        ["W", "Do we have to set up our board before that?"],
        ["M", "Yes, the teachers want the boards up by ten thirty."],
        ["W", "How long will it take the two of us?"],
        ["M", "Maybe thirty minutes with the poster and the models."],
        ["W", "Then let's meet at ten at the school gate."],
        ["M", "Ten is right. That leaves us enough time."],
        ["W", "I'll bring the tape and you bring the models."],
      ],
      choices: ["10:00 a.m.", "10:30 a.m.", "11:00 a.m.", "11:30 a.m.", "9:30 a.m."],
      answer: 1,
      clue: "Then let's meet at ten at the school gate.",
      explanation:
        "10시 30분까지 설치하려면 30분이 걸려서 10시에 만나기로 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 현빈아, 토요일 과학 전시회 몇 시에 열어?",
        "M: 오전 11시에 문을 열어.",
        "W: 그 전에 우리 판을 세워야 해?",
        "M: 응, 선생님들이 10시 30분까지 세워 두라고 하셨어.",
        "W: 우리 둘이서 얼마나 걸릴까?",
        "M: 포스터랑 모형까지 하면 30분쯤.",
        "W: 그럼 10시에 학교 정문에서 만나자.",
        "M: 10시 좋아. 시간이 넉넉해.",
        "W: 나는 테이프 가져갈게. 너는 모형 가져와.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Woojin, why do you keep looking at the door?"],
        ["M", "My interview for the student council is next."],
        ["W", "Did you write down what you want to say?"],
        ["M", "I did, but my mind goes blank when I read it."],
        ["W", "You've spoken in front of our class many times."],
        ["M", "This time three teachers are sitting there."],
        ["W", "Take a deep breath before you open the door."],
        ["M", "My hands are cold and I can hear my heart."],
      ],
      choices: ["proud", "bored", "nervous", "angry", "relieved"],
      answer: 3,
      clue: "My hands are cold and I can hear my heart.",
      explanation:
        "면접을 앞두고 손이 차갑고 심장 소리가 들린다고 했으므로 긴장한 심정이다. 따라서 답은 ③이다.",
      translation: [
        "W: 우진아, 왜 자꾸 문 쪽을 봐?",
        "M: 다음이 학생회 면접이야.",
        "W: 할 말은 적어 뒀어?",
        "M: 적었는데 읽으면 머리가 하얘져.",
        "W: 우리 반 앞에서는 여러 번 말했잖아.",
        "M: 이번에는 선생님 세 분이 앉아 계셔.",
        "W: 문 열기 전에 숨 크게 쉬어.",
        "M: 손이 차갑고 심장 뛰는 소리가 들려.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is there an elevator here?"],
        ["M", "It's on the other side."],
        ["ANN", "Number two."],
        ["W", "How many steps are there?"],
        ["M", "About thirty, I think."],
        ["ANN", "Number three."],
        ["W", "Which exit should I take?"],
        ["M", "Exit four is the closest."],
        ["ANN", "Number four."],
        ["W", "Does this train stop here?"],
        ["M", "Yes, every twelve minutes."],
        ["ANN", "Number five."],
        ["W", "Let me help you carry that up."],
        ["M", "Thank you. It's heavy with the baby inside."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Let me help you carry that up.",
      explanation:
        "그림은 지하철 계단에서 유모차를 함께 들어 올려 주는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "A subway station staircase, clean black line art on a plain white background, no writing anywhere. " +
          "A young father stands at the bottom of the stairs holding the front of a baby stroller with both hands. " +
          "A schoolgirl holds the back of the same stroller and lifts it together with him. " +
          "A handrail runs up the side of the steps and other passengers walk past in the background.",
      },
      translation: [
        "① W: 여기 승강기 있어요? / M: 반대쪽에 있어요.",
        "② W: 계단이 몇 개예요? / M: 서른 개쯤 되는 것 같아요.",
        "③ W: 어느 출구로 나가야 해요? / M: 4번 출구가 제일 가까워요.",
        "④ W: 이 열차가 여기 서요? / M: 네, 12분마다 와요.",
        "⑤ W: 제가 같이 들어 드릴게요. / M: 고마워요. 아기가 타서 무겁네요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, are you going to the office after class?"],
        ["W", "Yes, I have to hand in my club form today."],
        ["M", "Mine is filled in, but I have a dentist appointment."],
        ["W", "What time does your appointment start?"],
        ["M", "Three thirty, and the office closes at four."],
        ["W", "So you can't get back in time."],
        ["M", "Could you hand in my form with yours?"],
        ["W", "Sure. Give it to me before you leave."],
      ],
      choices: [
        "숙제를 알려 주기",
        "청소를 도와주기",
        "자리를 맡아 주기",
        "신청서를 대신 내 주기",
        "전화를 해 주기",
      ],
      answer: 4,
      clue: "Could you hand in my form with yours?",
      explanation:
        "남자는 동아리 신청서를 대신 제출해 달라고 부탁했다. 따라서 답은 ④이다.",
      translation: [
        "M: 채원아, 수업 끝나고 교무실 가?",
        "W: 응, 오늘 동아리 신청서를 내야 해.",
        "M: 내 것도 다 썼는데 치과 예약이 있어.",
        "W: 예약이 몇 시야?",
        "M: 3시 30분. 교무실은 4시에 닫아.",
        "W: 그럼 제때 못 돌아오겠네.",
        "M: 네 것 낼 때 내 것도 같이 내 줄 수 있어?",
        "W: 그럼. 가기 전에 나한테 줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 축제 체험 부스에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Here is news about the festival booths. " +
            "The booths will run for two days, Thursday and Friday. " +
            "All of them will be set up along the first floor hallway. " +
            "If your class wants a booth, submit the plan by next Monday. " +
            "Each class must bring its own table cloth and name card.",
        ],
      ],
      choices: [
        "부스를 운영하는 기간",
        "참가할 수 있는 학년",
        "부스가 설치되는 장소",
        "신청하는 방법",
        "각 반이 준비할 물건",
      ],
      answer: 2,
      clue: "The booths will run for two days, Thursday and Friday.",
      explanation:
        "기간, 장소, 신청 방법, 준비물은 말했지만 참가 학년은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 축제 체험 부스 소식입니다. 부스는 목요일과 금요일 이틀 동안 운영합니다. 모든 부스는 1층 복도를 따라 설치됩니다. 부스를 운영하고 싶은 반은 다음 주 월요일까지 계획서를 내세요. 각 반은 상보와 이름표를 직접 준비해야 합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a thin glass tube with numbers marked on its side. " +
            "A red or silver line inside it rises and falls. " +
            "You put it under your arm or hang it on a wall. " +
            "It tells you how hot or cold something is right now. " +
            "Doctors use one to check whether you have a fever.",
        ],
      ],
      choices: ["현미경", "망원경", "온도계", "저울", "자"],
      answer: 3,
      clue: "It tells you how hot or cold something is right now.",
      explanation:
        "눈금이 있는 가는 관 안의 선이 오르내리며 온도를 알려 주는 것은 온도계이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 옆면에 숫자가 새겨진 가느다란 유리관입니다. 안에 있는 빨간색이나 은색 선이 오르내립니다. 겨드랑이에 끼우거나 벽에 걸어 둡니다. 지금 무엇이 얼마나 뜨겁거나 차가운지 알려 줍니다. 의사 선생님은 열이 있는지 볼 때 이것을 씁니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How do you spell that word?"],
        ["M", "I finished it last night."],
        ["ANN", "Number two."],
        ["W", "Have you ever been to Japan?"],
        ["M", "Yes, twice with my family."],
        ["ANN", "Number three."],
        ["W", "Could I borrow your ruler?"],
        ["M", "Sure, take this one."],
        ["ANN", "Number four."],
        ["W", "What time did the movie end?"],
        ["M", "Around nine thirty."],
        ["ANN", "Number five."],
        ["W", "Do you want to join us?"],
        ["M", "I'd love to, thanks."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "How do you spell that word?",
      explanation:
        "단어 철자를 묻는 말에 어젯밤에 끝냈다고 답했으므로 ①의 대화가 어색하다. 따라서 답은 ①이다.",
      translation: [
        "① W: 그 단어 철자가 어떻게 돼? / M: 어젯밤에 끝냈어.",
        "② W: 일본에 가 본 적 있어? / M: 응, 가족이랑 두 번.",
        "③ W: 네 자 좀 빌려줄래? / M: 그럼, 이거 써.",
        "④ W: 영화 몇 시에 끝났어? / M: 9시 30분쯤에.",
        "⑤ W: 우리랑 같이 할래? / M: 좋지, 고마워.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, isn't your painting still in the art room?"],
        ["W", "Yes, I left it on the drying rack yesterday."],
        ["M", "The art teacher is cleaning that room today."],
        ["W", "Does she throw away what students leave behind?"],
        ["M", "She puts everything in a box and keeps it a week."],
        ["W", "My painting is for the contest on Monday."],
        ["M", "Then you should get it before she starts."],
        ["W", "I'll go up to the art room right now."],
      ],
      choices: [
        "도서관에 가기",
        "매점에 가기",
        "교실을 청소하기",
        "미술실에 작품을 가지러 가기",
        "집으로 돌아가기",
      ],
      answer: 4,
      clue: "I'll go up to the art room right now.",
      explanation:
        "여자는 지금 바로 미술실에 가서 그림을 가져오겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 다인아, 네 그림 아직 미술실에 있지 않아?",
        "W: 응, 어제 건조대에 올려 뒀어.",
        "M: 오늘 미술 선생님이 그 방을 정리하셔.",
        "W: 학생들이 두고 간 건 버리셔?",
        "M: 상자에 넣어서 일주일 보관하셔.",
        "W: 내 그림은 월요일 대회에 낼 거야.",
        "M: 그럼 시작하시기 전에 가져와야겠다.",
        "W: 지금 바로 미술실에 올라갈게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 체험 프로그램을 고르시오.",
      lines: [
        ["M", "Seoyeon, which weekend program will you choose?"],
        ["W", "Let's look at these five on the center's page."],
        ["M", "How long can you stay at the center?"],
        ["W", "Two hours at the most. I have piano after that."],
        ["M", "All right. How about the group size?"],
        ["W", "Small groups, ten people or fewer."],
        ["M", "And what about the fee?"],
        ["W", "Under twenty thousand won, please."],
        ["M", "Then only one program here matches everything."],
        ["W", "Good. I'll sign up before it fills."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Two hours at the most. I have piano after that.",
      explanation:
        "2시간 이하, 10명 이하, 2만 원 이하인 것을 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Time: 3 hours / Group: 8 / Fee: 15,000 won" },
          { no: 2, label: "②", value: "Time: 2 hours / Group: 8 / Fee: 18,000 won" },
          { no: 3, label: "③", value: "Time: 2 hours / Group: 15 / Fee: 12,000 won" },
          { no: 4, label: "④", value: "Time: 2 hours / Group: 6 / Fee: 25,000 won" },
          { no: 5, label: "⑤", value: "Time: 4 hours / Group: 20 / Fee: 10,000 won" },
        ],
      },
      translation: [
        "M: 서연아, 주말 프로그램 어떤 걸 고를 거야?",
        "W: 센터 쪽에 있는 다섯 개 보자.",
        "M: 센터에 얼마나 있을 수 있어?",
        "W: 최대 두 시간. 그다음에 피아노가 있어.",
        "M: 알겠어. 인원은?",
        "W: 작은 모둠으로, 열 명 이하.",
        "M: 참가비는?",
        "W: 2만 원 이하로.",
        "M: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "W: 좋아. 자리 차기 전에 신청할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 벽보를 붙이기로 한 날짜를 고르시오.",
      lines: [
        ["M", "Yerin, when should we put up the campaign posters?"],
        ["W", "The campaign begins on the twenty-fifth."],
        ["M", "So the posters should go up before that."],
        ["W", "How about the twentieth, this Friday?"],
        ["M", "The hallway gets repainted on the twentieth."],
        ["W", "Then the twenty-second, on Sunday?"],
        ["M", "The school building is closed on Sundays."],
        ["W", "Then the twenty-third is the last chance."],
        ["M", "The twenty-third it is. I'll bring the tape."],
      ],
      choices: [
        "the 20th",
        "the 22nd",
        "the 24th",
        "the 25th",
        "the 23rd",
      ],
      answer: 5,
      clue: "Then the twenty-third is the last chance.",
      explanation:
        "20일은 복도 페인트칠, 22일은 휴관이어서 23일에 붙이기로 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예린아, 캠페인 벽보 언제 붙일까?",
        "W: 캠페인이 25일에 시작해.",
        "M: 그럼 그 전에 붙여야겠네.",
        "W: 이번 금요일 20일은 어때?",
        "M: 20일에 복도에 페인트칠을 해.",
        "W: 그럼 일요일 22일은?",
        "M: 일요일에는 학교 건물이 닫혀.",
        "W: 그럼 23일이 마지막 기회네.",
        "M: 23일로 하자. 테이프는 내가 가져올게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiseok, your fingernails look a little dirty today."],
        ["M", "We worked in our rooftop garden all Saturday."],
        ["W", "You have a garden on the roof?"],
        ["M", "Just six boxes, but they need a lot of care."],
        ["W", "What did you do up there this time?"],
        ["M", "We pulled weeds and moved the tomato plants."],
        ["W", "Did anything grow well this season?"],
        ["M", "The lettuce did. We ate some for dinner."],
      ],
      choices: [
        "영화를 보러 가기",
        "병원에 다녀오기",
        "가족과 텃밭을 가꾸기",
        "친척 집을 방문하기",
        "도서관에서 공부하기",
      ],
      answer: 3,
      clue: "We worked in our rooftop garden all Saturday.",
      explanation:
        "남자는 토요일에 가족과 옥상 텃밭을 가꿨다. 따라서 답은 ③이다.",
      translation: [
        "W: 지석아, 오늘 손톱이 좀 지저분해 보여.",
        "M: 토요일 내내 옥상 텃밭에서 일했어.",
        "W: 옥상에 텃밭이 있어?",
        "M: 상자 여섯 개뿐인데 손이 많이 가.",
        "W: 이번에는 거기서 뭘 했어?",
        "M: 잡초 뽑고 토마토 모종을 옮겼어.",
        "W: 이번 철에 잘 자란 게 있어?",
        "M: 상추가 잘 됐어. 저녁에 좀 먹었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, everyone in the building. " +
            "The power will be turned off this Friday for safety checks. " +
            "It will be off from one o'clock until three in the afternoon. " +
            "Please save your work and turn off your computers before one. " +
            "The lights in the stairways will stay on during that time. " +
            "Thank you for your cooperation this week.",
        ],
      ],
      choices: [
        "정전 예정을 알리려고",
        "행사 시작을 알리려고",
        "분실물을 찾아가라고",
        "할인 행사를 알리려고",
        "문 닫는 시간을 알리려고",
      ],
      answer: 1,
      clue: "The power will be turned off this Friday for safety checks.",
      explanation:
        "금요일 오후에 안전 점검으로 전기가 끊긴다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 건물에 계신 여러분께 알려 드립니다. 이번 주 금요일에 안전 점검으로 전기를 끊습니다. 오후 한 시부터 세 시까지 전기가 들어오지 않습니다. 한 시 전에 작업을 저장하고 컴퓨터를 꺼 주십시오. 그 시간에도 계단 조명은 켜져 있습니다. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome. What can I get for you today?"],
        ["W", "Three notebooks, please. How much is one?"],
        ["M", "Each notebook is five dollars this month."],
        ["W", "I'd also like two packs of sticky notes."],
        ["M", "Sticky notes are three dollars a pack."],
        ["W", "Is there a discount for students?"],
        ["M", "Yes, students get three dollars off the total."],
        ["W", "Here is my student card and my money."],
      ],
      choices: ["$15", "$21", "$24", "$18", "$20"],
      answer: 4,
      clue: "Each notebook is five dollars this month. / Yes, students get three dollars off the total.",
      explanation:
        "공책 세 권 15달러에 붙임쪽지 두 묶음 6달러를 더하면 21달러이고, 3달러를 빼면 18달러이다. 따라서 답은 ④이다.",
      translation: [
        "M: 어서 오세요. 무엇을 드릴까요?",
        "W: 공책 세 권 주세요. 한 권에 얼마예요?",
        "M: 이번 달 공책은 한 권에 5달러예요.",
        "W: 붙임쪽지도 두 묶음 주세요.",
        "M: 붙임쪽지는 한 묶음에 3달러예요.",
        "W: 학생 할인이 있나요?",
        "M: 네, 학생은 전체에서 3달러 빼 드려요.",
        "W: 여기 학생증이랑 돈이요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayeon, your group finished the model bridge first."],
        ["W", "We planned the whole thing before touching the sticks."],
        ["M", "How long did the planning take?"],
        ["W", "One full period, which felt like a waste at first."],
        ["M", "Our group started building right away."],
        ["W", "And then you had to take it apart twice."],
        ["M", "Three times, actually. We kept changing our minds."],
        ["W", "A drawing on paper costs nothing to change."],
        ["M", "Could you show me how your group draws the plan?"],
      ],
      choices: [
        "Our group never plans.",
        "Sure, come by after lunch.",
        "You should build faster.",
        "The bridge already fell down.",
        "I can't draw anything.",
      ],
      answer: 2,
      clue: "Could you show me how your group draws the plan?",
      explanation:
        "남자가 계획 그리는 법을 보여 달라고 했으므로, 점심 후에 오라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나연아, 너희 모둠이 모형 다리를 제일 먼저 끝냈네.",
        "W: 막대를 만지기 전에 전체를 먼저 계획했어.",
        "M: 계획하는 데 얼마나 걸렸어?",
        "W: 한 교시 내내. 처음엔 시간 낭비 같았어.",
        "M: 우리 모둠은 바로 만들기 시작했어.",
        "W: 그러다 두 번이나 다시 뜯었잖아.",
        "M: 사실 세 번. 계속 생각이 바뀌었어.",
        "W: 종이에 그린 건 고쳐도 아무 값이 안 들어.",
        "M: 너희 모둠이 계획 그리는 걸 보여 줄 수 있어?",
        "W: 그럼, 점심 먹고 와.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sungmin, are you still writing your travel blog?"],
        ["M", "I am, but almost nobody reads it these days."],
        ["W", "How often do you post something new?"],
        ["M", "Whenever I go somewhere, so maybe once a month."],
        ["W", "Readers come back when posts appear on a fixed day."],
        ["M", "I never thought about picking a day."],
        ["W", "Even a short post every Friday would help."],
        ["M", "I could write about small places near my house."],
        ["W", "That's exactly the kind of post people save."],
      ],
      choices: [
        "Nobody lives near my house.",
        "I will close the blog today.",
        "I already post every Friday.",
        "My blog has no readers.",
        "All right, I'll start this Friday.",
      ],
      answer: 5,
      clue: "That's exactly the kind of post people save.",
      explanation:
        "금요일마다 짧게라도 올리라는 제안에 동의하는 흐름이므로, 이번 금요일부터 시작하겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 성민아, 아직 여행 블로그 써?",
        "M: 쓰는데 요즘은 읽는 사람이 거의 없어.",
        "W: 새 글은 얼마나 자주 올려?",
        "M: 어디 갈 때마다니까 한 달에 한 번쯤.",
        "W: 정해진 날에 글이 올라오면 사람들이 다시 와.",
        "M: 요일을 정한다는 생각은 못 해 봤어.",
        "W: 금요일마다 짧게라도 올리면 도움이 될 거야.",
        "M: 집 근처 작은 장소들에 대해 쓸 수도 있겠다.",
        "W: 그런 글이 바로 사람들이 저장하는 글이야.",
        "M: 알겠어, 이번 금요일부터 시작할게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Hayeon, did your class decide on the field trip place?"],
        ["W", "Not yet. Half want the museum and half want the park."],
        ["M", "How are you going to settle it?"],
        ["W", "We keep voting and it comes out almost even."],
        ["M", "Voting again will only give the same result."],
        ["W", "Then what else can we do about it?"],
        ["M", "Let each side explain why for two minutes first."],
        ["W", "Some people might change their minds after that."],
        ["M", "Why don't you try that at tomorrow's class meeting?"],
      ],
      choices: [
        "We never have class meetings.",
        "The trip was already canceled.",
        "That's worth trying. I'll suggest it.",
        "Everyone wants the museum.",
        "We should not vote at all.",
      ],
      answer: 3,
      clue: "Why don't you try that at tomorrow's class meeting?",
      explanation:
        "남자가 내일 학급 회의에서 해 보라고 했으므로, 해 볼 만하다며 제안하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 하연아, 너희 반 현장 학습 장소 정했어?",
        "W: 아직. 절반은 박물관, 절반은 공원을 원해.",
        "M: 어떻게 정할 거야?",
        "W: 계속 투표하는데 거의 반반으로 나와.",
        "M: 또 투표해도 결과는 같을 거야.",
        "W: 그럼 뭘 할 수 있을까?",
        "M: 양쪽이 이유를 2분씩 먼저 설명하게 해 봐.",
        "W: 그러고 나면 생각이 바뀌는 사람도 있겠다.",
        "M: 내일 학급 회의에서 해 보지 그래?",
        "W: 해 볼 만하다. 내가 제안할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Woobin이 Sera에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woobin : ________________",
      lines: [
        [
          "M",
          "Woobin and Sera are leaving the school library together in the evening. " +
            "Sera puts her laptop into her bag and zips it halfway. " +
            "Woobin sees that the open side of the bag is facing down. " +
            "The laptop could slide out the moment she lifts the bag. " +
            "He wants to tell her before she swings it onto her shoulder. " +
            "In this situation, what would Woobin most likely say to Sera?",
        ],
      ],
      choices: [
        "Your bag isn't closed all the way.",
        "The library closes at nine tonight.",
        "Can I borrow your laptop?",
        "Let's study here a little longer.",
        "You left your books on the table.",
      ],
      answer: 1,
      clue: "He wants to tell her before she swings it onto her shoulder.",
      explanation:
        "가방 지퍼가 반만 잠긴 채 열린 쪽이 아래를 향해 노트북이 쏟아질 수 있으므로, 가방이 덜 닫혔다고 알려 주는 ①이 가장 적절하다.",
      translation: [
        "M: 우빈이와 세라는 저녁에 학교 도서관을 함께 나서고 있습니다. 세라가 노트북을 가방에 넣고 지퍼를 반만 잠급니다. 우빈이는 가방의 열린 쪽이 아래를 향한 것을 봅니다. 가방을 드는 순간 노트북이 미끄러져 나올 수 있습니다. 우빈이는 세라가 가방을 어깨에 메기 전에 알려 주고 싶습니다. 이런 상황에서 우빈이가 세라에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
