/** 중2 듣기 38회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 38회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 자판을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a keyboard?"],
        ["W", "Yes, my desk is small and the cable gets in the way."],
        ["M", "Then a wireless keyboard would suit you better."],
        ["W", "Wireless, definitely. No cable across my desk."],
        ["M", "Do you need the number pad on the right side?"],
        ["W", "No, that part only makes it longer."],
        ["M", "Some models light up under the keys at night."],
        ["W", "I don't need the light. Just the short wireless one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Wireless, definitely. No cable across my desk. / No, that part only makes it longer.",
      explanation:
        "여자는 무선이면서 숫자판이 없고 조명도 없는 자판을 골랐다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five computer keyboards lying side by side as five choices, clean black line art on white. " +
          "① a WIDE keyboard with a CABLE going out of the top and a NUMBER PAD block on its right side. " +
          "② a NARROW keyboard with a CABLE going out of the top and NO number pad. " +
          "③ a NARROW keyboard with NO cable and NO number pad. " +
          "④ a WIDE keyboard with NO cable and a NUMBER PAD block on its right side. " +
          "⑤ a NARROW keyboard with NO cable, NO number pad, and small LIGHT RAYS drawn under the keys.",
      },
      translation: [
        "M: 안녕하세요. 자판 찾으세요?",
        "W: 네, 책상이 작아서 선이 자꾸 걸려요.",
        "M: 그러면 무선 자판이 더 맞으시겠네요.",
        "W: 무조건 무선이요. 책상에 선이 지나가는 건 싫어요.",
        "M: 오른쪽 숫자판이 필요하세요?",
        "W: 아니요, 그것 때문에 길어지기만 해요.",
        "M: 밤에 자판 아래가 빛나는 것도 있어요.",
        "W: 조명은 필요 없어요. 짧은 무선으로 주세요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 농장 체험 학습에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minhyuk, when is the farm trip for our grade?"],
        ["M", "Next Wednesday, the whole day."],
        ["W", "What are we going to do on the farm?"],
        ["M", "We pick sweet potatoes and feed the goats."],
        ["W", "Should I bring anything special?"],
        ["M", "Old clothes, work gloves and a hat."],
        ["W", "Do we have to pay for it?"],
        ["M", "Eight thousand won, including lunch there."],
        ["W", "That sounds fair for a whole day."],
      ],
      choices: [
        "가는 날",
        "타고 가는 방법",
        "농장에서 하는 활동",
        "챙겨야 할 물건",
        "내야 하는 비용",
      ],
      answer: 2,
      clue: "Next Wednesday, the whole day. / Eight thousand won, including lunch there.",
      explanation:
        "날짜, 활동, 준비물, 비용은 말했지만 교통편은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 민혁아, 우리 학년 농장 체험이 언제야?",
        "M: 다음 주 수요일, 하루 종일.",
        "W: 농장에서 뭘 해?",
        "M: 고구마를 캐고 염소에게 먹이를 줘.",
        "W: 특별히 챙길 게 있어?",
        "M: 낡은 옷, 장갑, 모자.",
        "W: 돈을 내야 해?",
        "M: 8천 원. 거기서 먹는 점심 포함이야.",
        "W: 하루 종일인데 괜찮은 값이네.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Jiwoo. It's Taeho. Are you still looking for it?"],
        ["W", "My water bottle? I gave up this morning."],
        ["M", "It was under the last seat on the school bus."],
        ["W", "Really? I looked there twice yesterday."],
        ["M", "The driver found it while cleaning after school."],
        ["W", "That's such a relief. Where is it now?"],
        ["M", "I have it here. I'll bring it tomorrow."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "물건을 빌리려고",
        "길을 물어보려고",
        "잃어버린 물건을 찾았다고 알리려고",
      ],
      answer: 5,
      clue: "It was under the last seat on the school bus.",
      explanation:
        "남자는 여자가 잃어버린 물병을 찾았다고 알리려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 지우야. 태호야. 아직 찾고 있어?",
        "W: 내 물병? 오늘 아침에 포기했어.",
        "M: 학교 버스 맨 뒷자리 밑에 있었어.",
        "W: 정말? 어제 거기 두 번이나 봤는데.",
        "M: 방과 후에 기사님이 청소하다가 찾으셨대.",
        "W: 정말 다행이다. 지금 어디 있어?",
        "M: 내가 가지고 있어. 내일 가져다줄게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Chaerin, when does the book talk start at the library?"],
        ["W", "The writer begins speaking at four o'clock."],
        ["M", "Do we need to get a seat number at the desk?"],
        ["W", "Yes, and they stop giving numbers at three forty."],
        ["M", "Then we have to arrive before three forty."],
        ["W", "The line for numbers is usually long too."],
        ["M", "Let's meet at three thirty to be safe."],
        ["W", "Three thirty works for me."],
        ["M", "I'll wait by the library entrance."],
      ],
      choices: ["3:30 p.m.", "3:40 p.m.", "3:50 p.m.", "4:00 p.m.", "3:20 p.m."],
      answer: 1,
      clue: "Let's meet at three thirty to be safe.",
      explanation:
        "번호표를 3시 40분에 마감해서 3시 30분에 만나기로 했다. 따라서 답은 ①이다.",
      translation: [
        "M: 채린아, 도서관 작가와의 만남 몇 시에 시작해?",
        "W: 작가님이 4시에 이야기를 시작해.",
        "M: 접수대에서 번호표를 받아야 해?",
        "W: 응, 3시 40분에 번호표 나눠 주는 걸 멈춰.",
        "M: 그럼 3시 40분 전에 도착해야겠네.",
        "W: 번호표 줄도 보통 길어.",
        "M: 안전하게 3시 30분에 만나자.",
        "W: 3시 30분 좋아.",
        "M: 도서관 입구에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seongjun, how did the class play go on Friday?"],
        ["M", "Better than I ever expected."],
        ["W", "Did you remember all of your lines?"],
        ["M", "Every one, and I didn't rush like in practice."],
        ["W", "I heard the audience laughed a lot."],
        ["M", "They laughed exactly where we hoped they would."],
        ["W", "All those late practices paid off."],
        ["M", "I'm really glad we kept working on it."],
      ],
      choices: ["bored", "angry", "nervous", "satisfied", "sad"],
      answer: 4,
      clue: "I'm really glad we kept working on it.",
      explanation:
        "연습한 대로 공연이 잘되어 계속 노력한 것이 기쁘다고 했으므로 만족한 심정이다. 따라서 답은 ④이다.",
      translation: [
        "W: 성준아, 금요일 학급 연극 어땠어?",
        "M: 생각보다 훨씬 잘됐어.",
        "W: 대사 다 기억났어?",
        "M: 하나도 안 빼먹었고 연습 때처럼 서두르지도 않았어.",
        "W: 관객들이 많이 웃었다고 들었어.",
        "M: 우리가 바라던 자리에서 딱 웃어 줬어.",
        "W: 늦게까지 연습한 보람이 있네.",
        "M: 끝까지 해낸 게 정말 기뻐.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Can I get a larger size?"],
        ["M", "Yes, it's one dollar more."],
        ["ANN", "Number two."],
        ["W", "Where do I put the used cup?"],
        ["M", "On the shelf over there, please."],
        ["ANN", "Number three."],
        ["W", "Is this table free?"],
        ["M", "Yes, nobody is using it."],
        ["ANN", "Number four."],
        ["W", "Could I have some more water?"],
        ["M", "Of course, one moment."],
        ["ANN", "Number five."],
        ["W", "Do you have any sandwiches left?"],
        ["M", "Only two, I'm afraid."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Where do I put the used cup?",
      explanation:
        "그림은 카페에서 여자가 다 쓴 컵을 들고 묻자 직원이 반납 선반을 가리키는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small café, clean black line art on a plain white background, no writing anywhere. " +
          "A woman stands holding an empty paper cup in one hand with a questioning look. " +
          "A male staff member behind the counter points toward a wooden shelf on the side wall. " +
          "A few used cups already sit on that shelf, and a trash bin stands beside it. " +
          "Plain tables and chairs are drawn in the background.",
      },
      translation: [
        "① W: 더 큰 걸로 주실 수 있어요? / M: 네, 1달러 더 내시면 됩니다.",
        "② W: 다 쓴 컵은 어디에 둘까요? / M: 저쪽 선반에 놓아 주세요.",
        "③ W: 이 자리 비었나요? / M: 네, 아무도 안 씁니다.",
        "④ W: 물 좀 더 주시겠어요? / M: 그럼요, 잠시만요.",
        "⑤ W: 샌드위치 남았나요? / M: 죄송하지만 두 개뿐이에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you sit by the window in science class, right?"],
        ["M", "Yes, the second row from the back."],
        ["W", "The afternoon sun shines straight onto my desk."],
        ["M", "Can't you close the curtain beside you?"],
        ["W", "The curtain there has been broken since last week."],
        ["M", "So the light hits your notebook the whole class."],
        ["W", "Could we trade seats just for that period?"],
        ["M", "Sure, I don't mind the sun at all."],
      ],
      choices: [
        "준비물을 빌려주기",
        "청소를 도와주기",
        "사진을 찍어 주기",
        "숙제를 알려 주기",
        "자리를 바꿔 주기",
      ],
      answer: 5,
      clue: "Could we trade seats just for that period?",
      explanation:
        "여자는 과학 시간에만 자리를 바꿔 달라고 부탁했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 과학 시간에 창가에 앉지?",
        "M: 응, 뒤에서 둘째 줄.",
        "W: 오후 햇빛이 내 책상에 그대로 들어와.",
        "M: 네 옆 커튼은 못 쳐?",
        "W: 그 커튼이 지난주부터 고장 났어.",
        "M: 그럼 수업 내내 공책에 빛이 비치겠네.",
        "W: 그 시간만 자리 바꿔 줄 수 있어?",
        "M: 그럼, 나는 햇빛 괜찮아.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 교내 축구 리그에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The school soccer league starts next month. " +
            "It will run for four weeks, until the end of the month. " +
            "All matches are played on Tuesday and Thursday after school. " +
            "Each class should hand in a team list to the gym office. " +
            "Remember that every player must wear shin guards.",
        ],
      ],
      choices: [
        "리그가 이어지는 기간",
        "경기가 있는 요일",
        "참가를 신청하는 방법",
        "심판을 보는 사람",
        "지켜야 할 규칙",
      ],
      answer: 4,
      clue: "It will run for four weeks, until the end of the month.",
      explanation:
        "기간, 요일, 신청 방법, 규칙은 말했지만 심판은 말하지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학교 축구 리그가 다음 달에 시작합니다. 그달 말까지 4주 동안 이어집니다. 모든 경기는 화요일과 목요일 방과 후에 합니다. 각 반은 체육 교무실에 선수 명단을 내세요. 모든 선수는 정강이 보호대를 꼭 착용해야 합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This tool has two rings for your fingers at one end. " +
            "At the other end there are two thin metal blades. " +
            "When you open and close the rings, the blades cross. " +
            "People use it to cut paper, string and thin cloth. " +
            "Always carry it with the sharp end pointing down.",
        ],
      ],
      choices: ["자", "지우개", "가위", "풀", "연필"],
      answer: 3,
      clue: "People use it to cut paper, string and thin cloth.",
      explanation:
        "손가락을 끼우는 고리와 두 개의 날이 있어 종이를 자르는 것은 가위이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이 도구는 한쪽 끝에 손가락을 끼우는 고리 두 개가 있습니다. 반대쪽 끝에는 얇은 쇠 날이 두 개 있습니다. 고리를 벌렸다 오므리면 날이 서로 엇갈립니다. 사람들은 종이, 끈, 얇은 천을 자를 때 이것을 씁니다. 들고 다닐 때는 날카로운 쪽을 늘 아래로 향하게 하세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Did you bring your umbrella?"],
        ["W", "Yes, it's in my bag."],
        ["ANN", "Number two."],
        ["M", "How was your summer vacation?"],
        ["W", "It is next to the bank."],
        ["ANN", "Number three."],
        ["M", "Could you repeat the question?"],
        ["W", "Of course, listen carefully."],
        ["ANN", "Number four."],
        ["M", "What are you looking for?"],
        ["W", "My history textbook."],
        ["ANN", "Number five."],
        ["M", "Shall I turn on the light?"],
        ["W", "Yes, please. It's dark."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "How was your summer vacation?",
      explanation:
        "여름 방학이 어땠는지 묻는 말에 은행 옆에 있다고 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① M: 우산 가져왔어? / W: 응, 가방에 있어.",
        "② M: 여름 방학 어땠어? / W: 은행 옆에 있어.",
        "③ M: 질문 다시 해 주시겠어요? / W: 그럼요, 잘 들어 보세요.",
        "④ M: 뭐 찾고 있어? / W: 내 역사 교과서.",
        "⑤ M: 불 켤까? / W: 응, 켜 줘. 어두워.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dongwoo, are those the gym balls in the corner?"],
        ["M", "Yes, we used them during lunch break."],
        ["W", "Didn't the P.E. teacher ask for them back?"],
        ["M", "He said to return them before the fifth period."],
        ["W", "The fifth period bell rings in five minutes."],
        ["M", "The storage room is right beside the gym."],
        ["W", "You should hurry if you want to make it."],
        ["M", "I'll take them to the gym right now."],
      ],
      choices: [
        "도서관에 가기",
        "매점에 가기",
        "교실을 청소하기",
        "체육관에 공을 갖다 놓기",
        "집으로 돌아가기",
      ],
      answer: 4,
      clue: "I'll take them to the gym right now.",
      explanation:
        "남자는 지금 바로 체육관 창고에 공을 갖다 놓겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 동우야, 구석에 있는 게 체육관 공이야?",
        "M: 응, 점심시간에 썼어.",
        "W: 체육 선생님이 돌려 달라고 하지 않으셨어?",
        "M: 5교시 전에 갖다 놓으라고 하셨어.",
        "W: 5교시 종이 5분 뒤에 울려.",
        "M: 창고가 체육관 바로 옆이야.",
        "W: 늦지 않으려면 서둘러야겠다.",
        "M: 지금 바로 체육관에 갖다 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 빌릴 캠핑 장비를 고르시오.",
      lines: [
        ["W", "Junseo, which camping set are you going to rent?"],
        ["M", "Let's look at these five on the rental page."],
        ["W", "How many days do you need it for?"],
        ["M", "Two days. We come back on Sunday evening."],
        ["W", "All right. What about the price?"],
        ["M", "Under fifty thousand won for the whole rental."],
        ["W", "Do you want it delivered to your house?"],
        ["M", "Yes, I can't carry it on the subway."],
        ["W", "Then only one set here fits everything."],
        ["M", "Good. I'll book it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Two days. We come back on Sunday evening.",
      explanation:
        "2일, 5만 원 이하, 배송이 되는 것을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Days: 3 / Price: 45,000 won / Delivery: Yes" },
          { no: 2, label: "②", value: "Days: 2 / Price: 62,000 won / Delivery: Yes" },
          { no: 3, label: "③", value: "Days: 2 / Price: 40,000 won / Delivery: No" },
          { no: 4, label: "④", value: "Days: 1 / Price: 30,000 won / Delivery: No" },
          { no: 5, label: "⑤", value: "Days: 2 / Price: 48,000 won / Delivery: Yes" },
        ],
      },
      translation: [
        "W: 준서야, 어떤 캠핑 세트 빌릴 거야?",
        "M: 대여 쪽에 있는 다섯 개 보자.",
        "W: 며칠 동안 필요해?",
        "M: 이틀. 일요일 저녁에 돌아와.",
        "W: 알겠어. 가격은?",
        "M: 전체 대여에 5만 원 이하로.",
        "W: 집으로 배송받을 거야?",
        "M: 응, 지하철로는 못 들고 가.",
        "W: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "M: 좋아. 오늘 밤에 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 학급 회의를 열기로 한 날짜를 고르시오.",
      lines: [
        ["M", "Seoyeon, when should we hold the class meeting?"],
        ["W", "We need to decide the trip plan before the twentieth."],
        ["M", "How about the ninth, this coming Monday?"],
        ["W", "Monday works. Everyone is in class that day."],
        ["M", "Wait, the ninth is the school photo day."],
        ["W", "Then the tenth, on Tuesday afternoon?"],
        ["M", "I have a dentist appointment on the tenth."],
        ["W", "Then let's go back to the ninth but after school."],
        ["M", "Good idea. The photos end at three."],
      ],
      choices: [
        "the 9th",
        "the 10th",
        "the 11th",
        "the 20th",
        "the 12th",
      ],
      answer: 1,
      clue: "Then let's go back to the ninth but after school.",
      explanation:
        "10일은 치과 예약이 있어 사진 촬영이 끝난 9일 방과 후에 회의를 열기로 했다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 학급 회의 언제 열까?",
        "W: 20일 전에 여행 계획을 정해야 해.",
        "M: 이번 주 월요일 9일은 어때?",
        "W: 월요일 좋아. 그날은 다 학교에 있어.",
        "M: 잠깐, 9일은 학교 사진 찍는 날이야.",
        "W: 그럼 화요일 오후 10일은?",
        "M: 10일에는 치과 예약이 있어.",
        "W: 그럼 다시 9일로 하되 방과 후에 하자.",
        "M: 좋은 생각이야. 사진 촬영은 3시에 끝나.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nari, did you rest at home this weekend?"],
        ["W", "No, I sold my old things at the flea market."],
        ["M", "What kind of things did you take there?"],
        ["W", "Books I finished and clothes that got too small."],
        ["M", "Did many people stop at your table?"],
        ["W", "About twenty, and I sold almost everything."],
        ["M", "What are you going to do with the money?"],
        ["W", "I put all of it into my travel savings."],
      ],
      choices: [
        "영화를 보러 가기",
        "병원에 다녀오기",
        "벼룩시장에서 물건을 팔기",
        "가족과 여행을 가기",
        "도서관에서 공부하기",
      ],
      answer: 3,
      clue: "No, I sold my old things at the flea market.",
      explanation:
        "여자는 주말에 벼룩시장에서 안 쓰는 물건을 팔았다. 따라서 답은 ③이다.",
      translation: [
        "M: 나리야, 이번 주말에 집에서 쉬었어?",
        "W: 아니, 벼룩시장에서 안 쓰는 물건을 팔았어.",
        "M: 뭘 가져갔는데?",
        "W: 다 읽은 책이랑 작아진 옷.",
        "M: 사람들이 많이 들렀어?",
        "W: 스무 명쯤. 거의 다 팔았어.",
        "M: 그 돈은 어떻게 할 거야?",
        "W: 전부 여행 저금에 넣었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, passengers on platform two. " +
            "Trains on this line have stopped because of a signal problem. " +
            "We do not know yet how long the repair will take. " +
            "Buses on route thirty run to the same stations from exit five. " +
            "Your subway card will work on those buses today. " +
            "We are very sorry for the sudden trouble.",
        ],
      ],
      choices: [
        "요금이 오름을 알리려고",
        "분실물을 찾아가라고",
        "열차 운행이 멈췄음을 알리려고",
        "안전 규칙을 안내하려고",
        "새 노선을 소개하려고",
      ],
      answer: 3,
      clue: "Trains on this line have stopped because of a signal problem.",
      explanation:
        "신호 고장으로 열차 운행이 멈췄다고 알리는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "M: 2번 승강장에 계신 승객 여러분께 알려 드립니다. 신호 고장으로 이 노선의 열차 운행이 멈췄습니다. 수리가 얼마나 걸릴지는 아직 알 수 없습니다. 5번 출구에서 30번 버스가 같은 역들로 갑니다. 오늘은 지하철 카드를 그 버스에서도 쓰실 수 있습니다. 갑작스러운 불편을 드려 대단히 죄송합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. Are you buying tickets for the science show?"],
        ["W", "Yes, four student tickets, please."],
        ["M", "Each student ticket is seven dollars."],
        ["W", "Do we need to pay for the seat cushions?"],
        ["M", "Cushions are one dollar each."],
        ["W", "We'll take two cushions for the younger ones."],
        ["M", "Then that is everything for you today."],
        ["W", "Here is my card. Thank you."],
      ],
      choices: ["$28", "$32", "$34", "$30", "$26"],
      answer: 4,
      clue: "Each student ticket is seven dollars. / Cushions are one dollar each.",
      explanation:
        "학생 표 네 장 28달러에 방석 두 개 2달러를 더하면 30달러이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안녕하세요. 과학 공연 표 사시나요?",
        "W: 네, 학생 표 네 장 주세요.",
        "M: 학생 표는 한 장에 7달러입니다.",
        "W: 방석도 돈을 내야 하나요?",
        "M: 방석은 개당 1달러입니다.",
        "W: 어린 아이들 몫으로 두 개 주세요.",
        "M: 그럼 오늘은 이걸로 다 되셨습니다.",
        "W: 여기 카드요. 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Hyemin, your class never loses things anymore."],
        ["W", "We put a lost and found box by the door."],
        ["M", "Just a box? That sounds too simple."],
        ["W", "Anyone who finds something drops it in there."],
        ["M", "And people actually check the box?"],
        ["W", "The class leader shows it every Friday morning."],
        ["M", "Our class keeps sending things to the office."],
        ["W", "Most things belong to someone in the same room."],
        ["M", "Could you help us set up a box like that?"],
      ],
      choices: [
        "Our box is always empty.",
        "Sure, I'll come on Monday.",
        "You should use the office.",
        "I never lose anything.",
        "The box was thrown away.",
      ],
      answer: 2,
      clue: "Could you help us set up a box like that?",
      explanation:
        "남자가 상자 만드는 걸 도와 달라고 했으므로, 월요일에 가겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 혜민아, 너희 반은 이제 물건을 안 잃어버리더라.",
        "W: 문 옆에 분실물 상자를 뒀어.",
        "M: 상자만? 너무 단순한데.",
        "W: 뭔가 주운 사람이 거기에 넣어.",
        "M: 그리고 사람들이 정말 상자를 봐?",
        "W: 반장이 금요일 아침마다 보여 줘.",
        "M: 우리 반은 자꾸 교무실로 보내.",
        "W: 대부분은 같은 교실 사람 물건이야.",
        "M: 우리도 그런 상자 만드는 것 좀 도와줄래?",
        "W: 그럼, 월요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taeyang, are you still saving for the new bicycle?"],
        ["M", "Yes, but it's going very slowly."],
        ["W", "How much do you put aside each week?"],
        ["M", "Whatever is left on Sunday night."],
        ["W", "Then some weeks you save nothing at all."],
        ["M", "That's exactly what keeps happening."],
        ["W", "Put the money aside on the day you get it."],
        ["M", "Before I spend any of it, you mean?"],
        ["W", "Yes, save first and spend what remains."],
      ],
      choices: [
        "That makes sense. I'll try it.",
        "I already bought the bicycle.",
        "I never get any money.",
        "Saving last works better.",
        "I don't want a bicycle.",
      ],
      answer: 1,
      clue: "Yes, save first and spend what remains.",
      explanation:
        "여자가 먼저 저축하고 남은 돈을 쓰라고 했으므로, 그 말이 맞다며 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 태양아, 아직 새 자전거 살 돈 모으고 있어?",
        "M: 응, 그런데 아주 더뎌.",
        "W: 일주일에 얼마씩 떼어 놔?",
        "M: 일요일 밤에 남은 만큼.",
        "W: 그럼 어떤 주는 하나도 못 모으겠네.",
        "M: 딱 그게 계속 반복돼.",
        "W: 돈이 생긴 날 바로 떼어 놔.",
        "M: 쓰기 전에 말이지?",
        "W: 응, 먼저 모으고 남은 걸 써.",
        "M: 그 말이 맞네. 해 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Suyeon, your English vocabulary has grown so fast."],
        ["W", "I write new words on small cards every day."],
        ["M", "How many cards do you make in a day?"],
        ["W", "Only five, but I review them for a whole week."],
        ["M", "I write twenty and forget them all."],
        ["W", "Twenty new words in one day is too many."],
        ["M", "So fewer words but more days?"],
        ["W", "Exactly. Five words seen seven times stay with you."],
        ["M", "Could you show me how you keep the cards?"],
      ],
      choices: [
        "Of course, come by after class.",
        "I don't use any cards.",
        "Twenty words is perfect.",
        "You should write more words.",
        "I threw all my cards away.",
      ],
      answer: 1,
      clue: "Could you show me how you keep the cards?",
      explanation:
        "남자가 카드 정리하는 법을 보여 달라고 했으므로, 수업 후에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 수연아, 네 영어 단어가 정말 빨리 늘었어.",
        "W: 매일 새 단어를 작은 카드에 적어.",
        "M: 하루에 몇 장이나 만들어?",
        "W: 다섯 장만. 대신 일주일 내내 복습해.",
        "M: 나는 스무 개 쓰고 다 잊어버려.",
        "W: 하루에 스무 개는 너무 많아.",
        "M: 그럼 단어는 적게, 날은 많이?",
        "W: 맞아. 다섯 개를 일곱 번 보면 남아.",
        "M: 카드 어떻게 모아 두는지 보여 줄래?",
        "W: 그럼, 수업 끝나고 와.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jihun이 Minseo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jihun : ________________",
      lines: [
        [
          "M",
          "Jihun and Minseo are setting up chairs for the school concert. " +
            "Minseo lifts a tall stack of six chairs at once to save time. " +
            "Jihun sees that the stack is leaning to one side as she walks. " +
            "The top chairs could slide off onto the students nearby. " +
            "He wants to stop her before the stack tips over. " +
            "In this situation, what would Jihun most likely say to Minseo?",
        ],
      ],
      choices: [
        "The concert begins at seven.",
        "Can you bring more chairs?",
        "Let's put the chairs in a circle.",
        "You should sit down and rest.",
        "Carry fewer chairs at a time.",
      ],
      answer: 5,
      clue: "He wants to stop her before the stack tips over.",
      explanation:
        "의자 여섯 개를 한꺼번에 들어 한쪽으로 기울고 있으므로, 조금씩 나눠 옮기라고 말하는 ⑤가 가장 적절하다.",
      translation: [
        "M: 지훈이와 민서는 학교 음악회에 쓸 의자를 놓고 있습니다. 민서가 시간을 아끼려고 의자 여섯 개를 한꺼번에 들어 올립니다. 지훈이는 민서가 걸을 때 의자 더미가 한쪽으로 기우는 것을 봅니다. 위에 있는 의자가 옆에 있는 학생들 쪽으로 미끄러질 수 있습니다. 지훈이는 더미가 넘어지기 전에 말리고 싶습니다. 이런 상황에서 지훈이가 민서에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
