/** 중2 듣기 37회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중2 37회",
  gradeLevel: "middle2",
  speechSpeed: 0.75,
  folder: "중2 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 독서대를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a book stand?"],
        ["M", "Yes, my neck hurts when I read on a flat desk."],
        ["W", "Then you want one whose angle can be changed."],
        ["M", "An adjustable angle is exactly what I need."],
        ["W", "Do you want clips to hold the pages open?"],
        ["M", "Yes, my book keeps closing by itself."],
        ["W", "This one also folds flat for carrying."],
        ["M", "Folding is perfect. I take it to the library."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "An adjustable angle is exactly what I need. / Folding is perfect. I take it to the library.",
      explanation:
        "남자는 각도를 바꿀 수 있고 집게가 있으며 접히는 독서대를 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five book stands standing side by side as five choices, clean black line art on white. " +
          "① a book stand with a FIXED slanted board and NO page clips. " +
          "② a book stand with an ADJUSTABLE hinged board and NO page clips. " +
          "③ a book stand with a FIXED slanted board and two small PAGE CLIPS on the sides. " +
          "④ a book stand with an ADJUSTABLE hinged board and two PAGE CLIPS. " +
          "⑤ a book stand with an ADJUSTABLE hinged board, two PAGE CLIPS, and a FOLDING joint in the middle shown half folded.",
      },
      translation: [
        "W: 안녕하세요. 독서대 찾으세요?",
        "M: 네, 평평한 책상에서 읽으면 목이 아파요.",
        "W: 그러면 각도를 바꿀 수 있는 것이 좋겠네요.",
        "M: 각도 조절이 딱 제가 원하는 거예요.",
        "W: 책장을 잡아 주는 집게도 필요하세요?",
        "M: 네, 책이 자꾸 저절로 덮여요.",
        "W: 이건 접어서 납작하게 가지고 다닐 수도 있어요.",
        "M: 접히는 게 좋네요. 도서관에 들고 가거든요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 연극 동아리 오디션에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, are you trying out for the drama club?"],
        ["W", "I want to. Where is the audition held?"],
        ["M", "In the small theater next to the gym."],
        ["W", "What do I have to prepare?"],
        ["M", "A one minute scene of your own choice."],
        ["W", "How many students will they take?"],
        ["M", "Eight this time, four boys and four girls."],
        ["W", "When do we hear the result?"],
        ["M", "They post the names three days later."],
      ],
      choices: [
        "오디션을 보는 날",
        "오디션을 보는 곳",
        "준비해야 할 것",
        "뽑는 인원",
        "결과를 알리는 때",
      ],
      answer: 1,
      clue: "In the small theater next to the gym. / Eight this time, four boys and four girls.",
      explanation:
        "장소, 준비물, 인원, 결과 발표는 말했지만 오디션 날짜는 말하지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 연극 동아리 오디션 볼 거야?",
        "W: 보고 싶어. 오디션 어디서 해?",
        "M: 체육관 옆 소극장에서.",
        "W: 뭘 준비해야 해?",
        "M: 직접 고른 1분짜리 장면 하나.",
        "W: 몇 명이나 뽑아?",
        "M: 이번에 여덟 명. 남자 넷, 여자 넷.",
        "W: 결과는 언제 알 수 있어?",
        "M: 사흘 뒤에 이름을 붙여 줘.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Taemin. It's Chaewon. Are you at home?"],
        ["M", "Yes, I'm doing my homework. What's up?"],
        ["W", "The math test has been moved to Thursday."],
        ["M", "Thursday? I thought it was on Friday."],
        ["W", "The teacher announced it after you left today."],
        ["M", "Thanks for telling me. I would have missed that."],
        ["W", "I thought you should know as soon as possible."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "바뀐 소식을 알려 주려고",
        "물건을 빌리려고",
        "길을 물어보려고",
      ],
      answer: 3,
      clue: "The math test has been moved to Thursday.",
      explanation:
        "여자는 수학 시험 날짜가 바뀐 것을 알려 주려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 태민아. 채원이야. 집이야?",
        "M: 응, 숙제하고 있어. 무슨 일이야?",
        "W: 수학 시험이 목요일로 옮겨졌어.",
        "M: 목요일? 금요일인 줄 알았는데.",
        "W: 네가 오늘 간 뒤에 선생님이 말씀하셨어.",
        "M: 알려 줘서 고마워. 몰랐으면 큰일 날 뻔했어.",
        "W: 빨리 알아야 할 것 같았어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Jinho, when does the club room open on Saturday?"],
        ["M", "The caretaker unlocks it at one o'clock."],
        ["W", "Do we have to set up the chairs ourselves?"],
        ["M", "Yes, and that takes about twenty minutes."],
        ["W", "The meeting starts at one thirty, right?"],
        ["M", "Right, so we need to be inside by one ten."],
        ["W", "Then let's meet at one at the front door."],
        ["M", "One o'clock is when it opens. That's too tight."],
        ["W", "Then twelve fifty, ten minutes earlier."],
      ],
      choices: ["12:40 p.m.", "1:00 p.m.", "12:50 p.m.", "1:10 p.m.", "1:30 p.m."],
      answer: 3,
      clue: "Then twelve fifty, ten minutes earlier.",
      explanation:
        "1시는 빠듯해서 10분 이른 12시 50분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 진호야, 토요일에 동아리방 몇 시에 열어?",
        "M: 관리 선생님이 1시에 열어 주셔.",
        "W: 의자는 우리가 놓아야 해?",
        "M: 응, 그게 20분쯤 걸려.",
        "W: 모임은 1시 30분에 시작하지?",
        "M: 맞아, 그래서 1시 10분까지는 안에 들어가야 해.",
        "W: 그럼 1시에 현관에서 만나자.",
        "M: 1시는 문 여는 시간이야. 너무 빠듯해.",
        "W: 그럼 10분 이른 12시 50분에.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, how did the robot contest go on Saturday?"],
        ["M", "Our robot stopped moving in the second round."],
        ["W", "Did something break during the match?"],
        ["M", "One wheel came loose and we could not fix it in time."],
        ["W", "You worked on that robot for three months."],
        ["M", "We tested it twenty times and it never failed."],
        ["W", "That's really unlucky."],
        ["M", "I still can't stop thinking about that one wheel."],
      ],
      choices: ["proud", "disappointed", "excited", "calm", "curious"],
      answer: 2,
      clue: "I still can't stop thinking about that one wheel.",
      explanation:
        "석 달을 준비한 로봇이 바퀴 때문에 멈춰 계속 생각난다고 했으므로 실망한 심정이다. 따라서 답은 ②이다.",
      translation: [
        "W: 도현아, 토요일 로봇 대회 어땠어?",
        "M: 2라운드에서 로봇이 멈춰 버렸어.",
        "W: 경기 중에 뭐가 망가졌어?",
        "M: 바퀴 하나가 헐거워졌는데 제때 못 고쳤어.",
        "W: 그 로봇 석 달이나 만들었잖아.",
        "M: 스무 번 시험했는데 한 번도 안 그랬어.",
        "W: 정말 운이 없었다.",
        "M: 아직도 그 바퀴 하나 생각이 떠나지 않아.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much is it for a shirt?"],
        ["M", "Three thousand won each."],
        ["ANN", "Number two."],
        ["W", "Do you open on Sundays?"],
        ["M", "No, we are closed."],
        ["ANN", "Number three."],
        ["W", "Can you remove this stain?"],
        ["M", "I'll do my best."],
        ["ANN", "Number four."],
        ["W", "Where should I leave the hanger?"],
        ["M", "On that rack, please."],
        ["ANN", "Number five."],
        ["W", "I'd like to have this coat cleaned."],
        ["M", "It will be ready on Friday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'd like to have this coat cleaned.",
      explanation:
        "그림은 세탁소에서 여자가 외투를 건네고 주인이 표를 써 주는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a small dry cleaning shop, clean black line art on a plain white background, no writing anywhere. " +
          "A woman hands a folded long coat across the counter with both hands. " +
          "A male shop owner takes the coat with one hand and writes on a small blank slip with the other. " +
          "A long rail of hanging clothes covered in plain bags is drawn behind him.",
      },
      translation: [
        "① W: 셔츠 한 장에 얼마예요? / M: 한 장에 3천 원이요.",
        "② W: 일요일에도 여세요? / M: 아니요, 쉽니다.",
        "③ W: 이 얼룩 뺄 수 있어요? / M: 최선을 다해 볼게요.",
        "④ W: 옷걸이는 어디에 둘까요? / M: 저 걸이에 걸어 주세요.",
        "⑤ W: 이 외투 세탁 맡기고 싶어요. / M: 금요일에 찾으실 수 있습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nayeon, are you going to be in class tomorrow?"],
        ["W", "Yes, of course. Why do you ask?"],
        ["M", "I have to leave early for a hospital check-up."],
        ["W", "What time are you leaving?"],
        ["M", "Right after fourth period, around one o'clock."],
        ["W", "So you'll miss the homeroom notice."],
        ["M", "Could you take a photo of the board and send it?"],
        ["W", "Sure, I'll send it as soon as she writes it."],
      ],
      choices: [
        "준비물을 빌려주기",
        "청소를 도와주기",
        "자리를 맡아 주기",
        "알림 내용을 찍어 보내 주기",
        "전화를 해 주기",
      ],
      answer: 4,
      clue: "Could you take a photo of the board and send it?",
      explanation:
        "남자는 칠판의 알림 내용을 찍어 보내 달라고 부탁했다. 따라서 답은 ④이다.",
      translation: [
        "M: 나연아, 내일 수업에 오지?",
        "W: 응, 당연하지. 왜?",
        "M: 병원 검진 때문에 일찍 나가야 해.",
        "W: 몇 시에 나가?",
        "M: 4교시 끝나고 바로, 1시쯤.",
        "W: 그럼 종례 안내를 못 듣겠네.",
        "M: 칠판 사진 찍어서 보내 줄 수 있어?",
        "W: 그럼, 선생님이 쓰시자마자 보낼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 영어 말하기 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Here are the details of the English speaking contest. " +
            "It will take place on the second Friday of next month. " +
            "Each speaker has three minutes, and going over time is not allowed. " +
            "Submit your application form to the English office by next Monday. " +
            "This year's topic is a change you want to see in our town.",
        ],
      ],
      choices: [
        "대회가 열리는 날",
        "점수를 매기는 기준",
        "발표할 수 있는 시간",
        "신청하는 방법",
        "올해의 주제",
      ],
      answer: 2,
      clue: "It will take place on the second Friday of next month.",
      explanation:
        "날짜, 발표 시간, 신청 방법, 주제는 말했지만 채점 기준은 말하지 않았다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 영어 말하기 대회 안내입니다. 대회는 다음 달 둘째 주 금요일에 열립니다. 발표자마다 3분이 주어지며 시간을 넘길 수 없습니다. 신청서는 다음 주 월요일까지 영어 교무실에 내세요. 올해 주제는 우리 동네에서 바뀌었으면 하는 점입니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This flat machine sits on the floor or on a kitchen counter. " +
            "You place an object on its wide top surface. " +
            "A number then appears on the small screen in front. " +
            "Cooks use it to measure flour, and people use it for themselves. " +
            "Make sure it reads zero before you put anything on it.",
        ],
      ],
      choices: ["지도", "시계", "계산기", "사전", "저울"],
      answer: 5,
      clue: "Cooks use it to measure flour, and people use it for themselves.",
      explanation:
        "위에 물건을 올리면 숫자가 나타나 무게를 알려 주는 것은 저울이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 이 납작한 기계는 바닥이나 부엌 조리대 위에 놓입니다. 넓은 윗면에 물건을 올려놓습니다. 그러면 앞쪽 작은 화면에 숫자가 나타납니다. 요리사는 밀가루를 잴 때, 사람들은 자기 몸을 잴 때 씁니다. 무언가를 올리기 전에 숫자가 0인지 꼭 확인하세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Do you want to walk or take the bus?"],
        ["W", "Let's walk. It's a nice day."],
        ["ANN", "Number two."],
        ["M", "Have you decided on your topic?"],
        ["W", "Not yet, I need more time."],
        ["ANN", "Number three."],
        ["M", "How often does this bus come?"],
        ["W", "It is a very old bus."],
        ["ANN", "Number four."],
        ["M", "Could you hold this for a second?"],
        ["W", "Sure, give it to me."],
        ["ANN", "Number five."],
        ["M", "What did the doctor say?"],
        ["W", "She said I need more rest."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How often does this bus come?",
      explanation:
        "버스가 얼마나 자주 오는지 묻는 말에 아주 낡은 버스라고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 걸을까, 버스 탈까? / W: 걷자. 날씨 좋다.",
        "② M: 주제 정했어? / W: 아직, 시간이 더 필요해.",
        "③ M: 이 버스 얼마나 자주 와? / W: 아주 낡은 버스야.",
        "④ M: 이것 좀 잠깐 들어 줄래? / W: 그럼, 줘 봐.",
        "⑤ M: 의사 선생님이 뭐라셔? / W: 더 쉬어야 한대.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Bomi, are those the art room brushes in your bag?"],
        ["W", "Yes, I borrowed three for my poster last Friday."],
        ["M", "The art teacher was looking for them this morning."],
        ["W", "I completely forgot to bring them back."],
        ["M", "She said the first year class needs them today."],
        ["W", "Their class starts at two o'clock."],
        ["M", "It's one forty right now."],
        ["W", "I'll run to the art room and return them."],
      ],
      choices: [
        "미술실에 붓을 돌려주러 가기",
        "매점에 가기",
        "교실을 청소하기",
        "도서관에 가기",
        "집으로 돌아가기",
      ],
      answer: 1,
      clue: "I'll run to the art room and return them.",
      explanation:
        "여자는 미술실에 뛰어가서 붓을 돌려주겠다고 했다. 따라서 답은 ①이다.",
      translation: [
        "M: 보미야, 가방에 있는 거 미술실 붓이야?",
        "W: 응, 지난 금요일에 포스터 때문에 세 자루 빌렸어.",
        "M: 오늘 아침에 미술 선생님이 찾으셨어.",
        "W: 돌려드리는 걸 완전히 잊었어.",
        "M: 오늘 1학년 수업에 필요하대.",
        "W: 그 수업이 2시에 시작하지.",
        "M: 지금 1시 40분이야.",
        "W: 미술실로 뛰어가서 돌려드릴게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 결제할 학습 프로그램을 고르시오.",
      lines: [
        ["M", "Hyerin, which study program are you going to pay for?"],
        ["W", "Let's compare these five on the screen."],
        ["M", "How many months do you want to use it?"],
        ["W", "Six months at the most. A year feels too long."],
        ["M", "All right. What about the price?"],
        ["W", "Under sixty thousand won for the whole thing."],
        ["M", "Do you need to watch the videos offline?"],
        ["W", "Yes, there is no signal on my bus route."],
        ["M", "Then only one program here fits everything."],
        ["W", "Good. I'll pay for it this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Six months at the most. A year feels too long.",
      explanation:
        "6개월 이하, 6만 원 이하, 내려받기가 되는 것을 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Months: 12 / Price: 55,000 won / Offline: Yes" },
          { no: 2, label: "②", value: "Months: 6 / Price: 58,000 won / Offline: Yes" },
          { no: 3, label: "③", value: "Months: 6 / Price: 70,000 won / Offline: Yes" },
          { no: 4, label: "④", value: "Months: 3 / Price: 40,000 won / Offline: No" },
          { no: 5, label: "⑤", value: "Months: 12 / Price: 45,000 won / Offline: No" },
        ],
      },
      translation: [
        "M: 혜린아, 어떤 학습 프로그램 결제할 거야?",
        "W: 화면에 있는 다섯 개 비교해 보자.",
        "M: 몇 달 동안 쓸 거야?",
        "W: 최대 6개월. 1년은 너무 길게 느껴져.",
        "M: 알겠어. 가격은?",
        "W: 전체에 6만 원 이하로.",
        "M: 영상을 내려받아서 봐야 해?",
        "W: 응, 내가 타는 버스 길에는 신호가 안 잡혀.",
        "M: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "W: 좋아. 오늘 저녁에 결제할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 반 티셔츠를 주문하기로 한 날짜를 고르시오.",
      lines: [
        ["W", "Junseo, when should we order the class T-shirts?"],
        ["M", "The sports day is on the twenty-sixth."],
        ["W", "The shop said printing takes about ten days."],
        ["M", "Then we should order by the sixteenth at the latest."],
        ["W", "How about the fourteenth, this Friday?"],
        ["M", "We still don't have the sizes from four students."],
        ["W", "They promised to tell me by Monday, the fifteenth."],
        ["M", "Then let's order on the sixteenth, right after that."],
        ["W", "The sixteenth it is. I'll call the shop that morning."],
      ],
      choices: [
        "the 14th",
        "the 15th",
        "the 26th",
        "the 16th",
        "the 20th",
      ],
      answer: 4,
      clue: "Then let's order on the sixteenth, right after that.",
      explanation:
        "치수를 15일에 받으므로 그 다음 날인 16일에 주문하기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 준서야, 반 티셔츠 언제 주문할까?",
        "M: 체육대회가 26일이야.",
        "W: 가게에서 인쇄에 열흘쯤 걸린다고 했어.",
        "M: 그럼 늦어도 16일까지는 주문해야겠다.",
        "W: 이번 금요일 14일은 어때?",
        "M: 아직 네 명 치수를 못 받았어.",
        "W: 월요일 15일까지 알려 주기로 했어.",
        "M: 그럼 그다음 날인 16일에 주문하자.",
        "W: 16일로 하자. 그날 아침에 가게에 전화할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seungho, did you go out anywhere on Sunday?"],
        ["M", "No, I helped my little brother with his homework."],
        ["W", "What subject was he working on?"],
        ["M", "Math. He kept mixing up the times tables."],
        ["W", "How long did the two of you sit together?"],
        ["M", "Almost three hours, with a snack in the middle."],
        ["W", "Did he understand it in the end?"],
        ["M", "He got eight out of ten on the practice sheet."],
      ],
      choices: [
        "동생의 숙제를 도와주기",
        "영화를 보러 가기",
        "가족과 등산을 가기",
        "여행을 다녀오기",
        "도서관에서 공부하기",
      ],
      answer: 1,
      clue: "No, I helped my little brother with his homework.",
      explanation:
        "남자는 일요일에 동생의 수학 숙제를 도왔다. 따라서 답은 ①이다.",
      translation: [
        "W: 승호야, 일요일에 어디 나갔어?",
        "M: 아니, 동생 숙제를 도와줬어.",
        "W: 무슨 과목이었는데?",
        "M: 수학. 구구단을 계속 헷갈려 했어.",
        "W: 둘이 얼마나 앉아 있었어?",
        "M: 중간에 간식 먹고 거의 세 시간.",
        "W: 결국 이해했어?",
        "M: 연습지에서 열 개 중 여덟 개 맞혔어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is an announcement from the office. " +
            "The drinking fountains on the second floor cannot be used today. " +
            "A pipe under the floor is being repaired this afternoon. " +
            "Please use the fountains on the first or third floor instead. " +
            "They should work again from tomorrow morning. " +
            "Thank you for your patience today.",
        ],
      ],
      choices: [
        "행사 시작을 알리려고",
        "분실물을 찾아가라고",
        "안전 규칙을 안내하려고",
        "급수대를 쓸 수 없음을 알리려고",
        "청소를 부탁하려고",
      ],
      answer: 4,
      clue: "The drinking fountains on the second floor cannot be used today.",
      explanation:
        "배관 수리로 2층 급수대를 쓸 수 없다고 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 교무실에서 전하는 안내입니다. 오늘 2층 급수대를 쓰실 수 없습니다. 오늘 오후에 바닥 아래 배관을 고치고 있습니다. 대신 1층이나 3층 급수대를 이용해 주세요. 내일 아침부터는 다시 쓸 수 있습니다. 오늘 기다려 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What would you like to buy today?"],
        ["M", "Two boxes of colored pencils. How much is one box?"],
        ["W", "Each box is eleven dollars this week."],
        ["M", "I'd also like one sketchbook."],
        ["W", "The sketchbook is six dollars."],
        ["M", "Do you have a discount for students?"],
        ["W", "Yes, students get four dollars off the total."],
        ["M", "Here is my student card and my card."],
      ],
      choices: ["$28", "$24", "$22", "$32", "$26"],
      answer: 2,
      clue: "Each box is eleven dollars this week. / Yes, students get four dollars off the total.",
      explanation:
        "색연필 두 상자 22달러에 스케치북 6달러를 더하면 28달러이고, 4달러를 빼면 24달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 오늘 무엇을 사시겠어요?",
        "M: 색연필 두 상자요. 한 상자에 얼마예요?",
        "W: 이번 주에는 한 상자에 11달러예요.",
        "M: 스케치북도 한 권 주세요.",
        "W: 스케치북은 6달러예요.",
        "M: 학생 할인이 있나요?",
        "W: 네, 학생은 전체에서 4달러 빼 드려요.",
        "M: 여기 학생증이랑 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunjun, you finished the whole novel in one week."],
        ["M", "I read thirty pages every night before bed."],
        ["W", "Do you set a timer or count the pages?"],
        ["M", "Pages. Time makes me look at the clock."],
        ["W", "I always plan to read but never start."],
        ["M", "Put the book on your pillow in the morning."],
        ["W", "On my pillow? Why there?"],
        ["M", "Then you have to move it before you sleep."],
        ["W", "Could you lend me the one you just finished?"],
      ],
      choices: [
        "Sure, I'll bring it tomorrow.",
        "I don't read any novels.",
        "You should buy a timer.",
        "My pillow is too small.",
        "I never finish books.",
      ],
      answer: 1,
      clue: "Could you lend me the one you just finished?",
      explanation:
        "여자가 방금 다 읽은 책을 빌려 달라고 했으므로, 내일 가져오겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 현준아, 그 소설을 일주일 만에 다 읽었네.",
        "M: 자기 전에 매일 서른 쪽씩 읽었어.",
        "W: 시간을 재? 쪽수를 세?",
        "M: 쪽수. 시간을 재면 자꾸 시계를 봐.",
        "W: 나는 늘 읽겠다고 하고 시작을 못 해.",
        "M: 아침에 책을 베개 위에 올려 둬.",
        "W: 베개 위에? 왜 거기에?",
        "M: 그럼 자기 전에 치워야 하잖아.",
        "W: 방금 다 읽은 그 책 좀 빌려줄래?",
        "M: 그럼, 내일 가져올게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dayeon, your class raised the most money for the charity."],
        ["W", "We sold handmade bookmarks for two weeks."],
        ["M", "Did everyone in the class make them?"],
        ["W", "Yes, each person made ten before the sale."],
        ["M", "Our class only collected coins in a box."],
        ["W", "People give more when they get something back."],
        ["M", "That makes sense now that you say it."],
        ["W", "And making them together was the fun part."],
        ["M", "Could you teach our class how to make them?"],
      ],
      choices: [
        "We didn't make anything.",
        "Your class raised more money.",
        "I can't make bookmarks.",
        "Sure, I'll come next Tuesday.",
        "The sale ended last year.",
      ],
      answer: 4,
      clue: "Could you teach our class how to make them?",
      explanation:
        "남자가 만드는 법을 가르쳐 달라고 했으므로, 다음 주 화요일에 가겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 다연아, 너희 반이 기부금을 제일 많이 모았더라.",
        "W: 2주 동안 손으로 만든 책갈피를 팔았어.",
        "M: 반 전체가 만들었어?",
        "W: 응, 판매 전에 한 사람이 열 개씩 만들었어.",
        "M: 우리 반은 상자에 동전만 모았어.",
        "W: 사람들은 뭔가 받으면 더 내.",
        "M: 듣고 보니 맞는 말이네.",
        "W: 그리고 같이 만드는 게 재미있었어.",
        "M: 우리 반에 만드는 법 좀 가르쳐 줄래?",
        "W: 그럼, 다음 주 화요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Minjae, are you still having trouble sleeping?"],
        ["M", "Yes, I lie awake until almost one every night."],
        ["W", "What do you drink in the evening?"],
        ["M", "Usually a can of cola while I study."],
        ["W", "Cola has caffeine, just like coffee does."],
        ["M", "I always thought only coffee had it."],
        ["W", "It stays in your body for several hours."],
        ["M", "So I should stop drinking it at night?"],
        ["W", "Try water for a week and see what happens."],
      ],
      choices: [
        "I never drink cola.",
        "Water keeps me awake.",
        "All right, I'll try that this week.",
        "I sleep very well already.",
        "Coffee has no caffeine.",
      ],
      answer: 3,
      clue: "Try water for a week and see what happens.",
      explanation:
        "여자가 일주일 동안 물을 마셔 보라고 했으므로, 이번 주에 해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 민재야, 아직도 잠을 못 자?",
        "M: 응, 매일 밤 거의 1시까지 깨어 있어.",
        "W: 저녁에 뭘 마셔?",
        "M: 공부할 때 보통 콜라 한 캔.",
        "W: 콜라에도 커피처럼 카페인이 있어.",
        "M: 커피에만 있는 줄 알았어.",
        "W: 몸에 몇 시간이나 남아 있어.",
        "M: 그럼 밤에 그만 마셔야 하는 거야?",
        "W: 일주일만 물로 바꿔 보고 어떤지 봐.",
        "M: 알겠어, 이번 주에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yuna가 Doyun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yuna : ________________",
      lines: [
        [
          "W",
          "Yuna and Doyun are painting a backdrop for the school play. " +
            "Doyun finishes his part and stands up to stretch his arms. " +
            "Yuna sees that the wet paint brush is still in his back pocket. " +
            "If he sits down again, the paint will ruin his trousers. " +
            "She wants to tell him before he takes his seat. " +
            "In this situation, what would Yuna most likely say to Doyun?",
        ],
      ],
      choices: [
        "The play starts next Friday.",
        "Can I use your paint?",
        "Let's paint the sky first.",
        "Your part looks really good.",
        "There's a wet brush in your pocket.",
      ],
      answer: 5,
      clue: "She wants to tell him before he takes his seat.",
      explanation:
        "물감이 묻은 붓이 뒷주머니에 꽂혀 있어 앉으면 바지를 버리므로, 붓이 있다고 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "W: 유나와 도윤이는 학교 연극에 쓸 배경을 칠하고 있습니다. 도윤이가 자기 몫을 끝내고 일어나 팔을 폅니다. 유나는 물감이 묻은 붓이 아직 도윤이 뒷주머니에 꽂혀 있는 것을 봅니다. 다시 앉으면 물감이 바지를 버리게 됩니다. 유나는 도윤이가 앉기 전에 알려 주고 싶습니다. 이런 상황에서 유나가 도윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
