/** 중3 듣기 17회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 17회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 주문할 탁상시계를 고르시오.",
      lines: [
        ["M", "Good afternoon. Are you looking for a desk clock?"],
        ["W", "Yes, one for my study table."],
        ["M", "We have clocks with hands and clocks with number displays."],
        ["W", "One with hands, please. The bright numbers keep me awake."],
        ["M", "All right. Do you want an alarm bell on top?"],
        ["W", "Yes, a real bell. I sleep through the quiet ones."],
        ["M", "Then two are left. One has a square case and one has a round case."],
        ["W", "The square one, please. It won't roll off when I knock the table."],
        ["M", "Good choice. This one runs on a single battery for a year."],
        ["W", "Perfect. I'll order it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "The square one, please. It won't roll off when I knock the table.",
      explanation:
        "여자는 바늘이 있는 시계를, 위에 종이 달린 것으로, 몸체가 네모난 것을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five desk clocks shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a clock with a DIGITAL NUMBER PANEL instead of hands, no bell, in a square case. " +
          "Second: a clock with a DIGITAL NUMBER PANEL instead of hands, with TWO ROUND ALARM BELLS on top, in a round case. " +
          "Third: a clock with HANDS on a dial, NO bell on top, in a round case. " +
          "Fourth: a clock with HANDS on a dial, with TWO ROUND ALARM BELLS on top, in a ROUND case. " +
          "Fifth: a clock with HANDS on a dial, with TWO ROUND ALARM BELLS on top, in a SQUARE case with flat sides.",
      },
      translation: [
        "M: 안녕하세요. 탁상시계 찾으세요?",
        "W: 네, 공부 책상에 둘 거예요.",
        "M: 바늘이 있는 것과 숫자가 뜨는 것이 있습니다.",
        "W: 바늘이 있는 걸로요. 밝은 숫자는 잠을 깨워서요.",
        "M: 알겠습니다. 위에 알람 종이 달린 걸로 하시겠어요?",
        "W: 네, 진짜 종이요. 조용한 건 자느라 못 들어요.",
        "M: 그럼 두 개 남았네요. 하나는 몸체가 네모나고 하나는 둥급니다.",
        "W: 네모난 걸로요. 책상을 쳐도 굴러떨어지지 않으니까요.",
        "M: 좋은 선택이세요. 이건 건전지 하나로 1년 갑니다.",
        "W: 딱 좋네요. 그걸로 주문할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 진로 특강에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Dowon, are you going to the career talk this week?"],
        ["M", "I'd like to, but I don't know the details."],
        ["W", "It's on Thursday, during the sixth and seventh periods."],
        ["M", "Who is coming to speak?"],
        ["W", "A vet who works at the animal hospital near the market."],
        ["M", "Where is it being held?"],
        ["W", "In the multimedia room on the third floor."],
        ["M", "Do we have to sign up?"],
        ["W", "Yes, write your name on the sheet outside the office by Wednesday."],
        ["M", "Then I'll put my name down at lunchtime."],
      ],
      choices: ["열리는 날", "강사", "장소", "정원", "신청 방법"],
      answer: 4,
      clue: "Yes, write your name on the sheet outside the office by Wednesday.",
      explanation:
        "날짜(목요일 6·7교시), 강사(수의사), 장소(3층 멀티미디어실), 신청 방법(행정실 앞 명단에 이름 쓰기)은 언급되지만 정원은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 도원아, 이번 주 진로 특강 갈 거야?",
        "M: 가고 싶은데 자세한 걸 몰라.",
        "W: 목요일 6, 7교시에 해.",
        "M: 누가 오는데?",
        "W: 시장 근처 동물병원에서 일하는 수의사 선생님.",
        "M: 어디서 하는데?",
        "W: 3층 멀티미디어실에서.",
        "M: 신청해야 해?",
        "W: 응, 수요일까지 행정실 앞 명단에 이름 써.",
        "M: 그럼 점심시간에 이름 적을게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Seokjin. It's Nari from the science club."],
        ["M", "Hi, Nari. Is everything all right?"],
        ["W", "Yes, but I need to tell you about Saturday's experiment."],
        ["M", "Has it been cancelled?"],
        ["W", "No, the time has changed. We start at one instead of three."],
        ["M", "Why so early?"],
        ["W", "The lab has to be free by four for the teachers' meeting."],
        ["M", "Thanks for calling. I'll be there at one."],
      ],
      choices: [
        "실험 시간이 바뀐 것을 알리려고",
        "실험이 취소되었다고 알리려고",
        "실험 도구를 빌려 달라고 하려고",
        "동아리 가입을 권하려고",
        "회의 장소를 물어보려고",
      ],
      answer: 1,
      clue: "No, the time has changed. We start at one instead of three.",
      explanation:
        "여자는 토요일 실험이 3시에서 1시로 앞당겨졌다고 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 석진아. 과학 동아리 나리야.",
        "M: 안녕. 무슨 일 있어?",
        "W: 아니, 토요일 실험 얘기 하려고.",
        "M: 취소됐어?",
        "W: 아니, 시간이 바뀌었어. 3시가 아니라 1시에 시작해.",
        "M: 왜 그렇게 일찍?",
        "W: 4시까지 실험실을 비워야 해. 선생님들 회의가 있어서.",
        "M: 알려 줘서 고마워. 1시에 갈게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Hyunbin, what time should we meet at the gallery?"],
        ["M", "The guided tour starts at four o'clock."],
        ["W", "And we still have to leave our bags at the counter."],
        ["M", "How about three forty-five?"],
        ["W", "The counter has a queue on Sundays. Let's go earlier."],
        ["M", "How long does it take you to get there?"],
        ["W", "About twenty-five minutes on foot."],
        ["M", "Then let's meet at three thirty."],
        ["W", "Three thirty is fine. I'll wait by the fountain."],
      ],
      choices: ["3:15 p.m.", "3:30 p.m.", "3:45 p.m.", "4:00 p.m.", "4:15 p.m."],
      answer: 2,
      clue: "Then let's meet at three thirty.",
      explanation:
        "안내 관람이 4시에 시작하고 짐 맡기는 줄이 길어서 두 사람은 3시 30분에 만나기로 한다. 따라서 답은 ②이다.",
      translation: [
        "W: 현빈아, 미술관에서 몇 시에 만날까?",
        "M: 안내 관람이 4시에 시작해.",
        "W: 그리고 짐도 보관대에 맡겨야 하잖아.",
        "M: 3시 45분은 어때?",
        "W: 일요일에는 보관대에 줄이 서. 더 일찍 가자.",
        "M: 거기까지 얼마나 걸려?",
        "W: 걸어서 25분쯤.",
        "M: 그럼 3시 30분에 만나자.",
        "W: 3시 30분 좋아. 분수대 앞에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Woojin, you've checked your bag four times since we sat down."],
        ["M", "My speech is in there. I go on stage in twenty minutes."],
        ["W", "You've practised it every day for a month."],
        ["M", "I know, but there will be three hundred people watching."],
        ["W", "You'll be fine. You know the whole thing by heart."],
        ["M", "My hands are cold and I keep forgetting the first line."],
        ["W", "Take a slow breath. The first line is 'Good evening, everyone'."],
        ["M", "Right. Ask me again in five minutes, in case I lose it."],
      ],
      choices: ["excited", "bored", "nervous", "angry", "satisfied"],
      answer: 3,
      clue: "My hands are cold and I keep forgetting the first line.",
      explanation:
        "무대에 오르기 직전에 손이 차가워지고 첫 문장을 자꾸 잊는다고 했으므로 남자는 몹시 긴장하고 있다. 따라서 답은 ③이다.",
      translation: [
        "W: 우진아, 앉은 뒤로 가방을 네 번이나 확인했어.",
        "M: 원고가 거기 있어. 20분 뒤에 무대에 올라가.",
        "W: 한 달 동안 매일 연습했잖아.",
        "M: 알아. 그런데 300명이 보고 있을 거잖아.",
        "W: 괜찮을 거야. 다 외웠잖아.",
        "M: 손이 차가워지고 첫 문장이 자꾸 생각이 안 나.",
        "W: 천천히 숨 쉬어. 첫 문장은 '여러분, 안녕하세요'야.",
        "M: 맞다. 혹시 또 잊을지 모르니 5분 뒤에 다시 물어봐 줘.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "How often does this bus come?"],
        ["W", "Every ten minutes."],
        ["M", "Could you take a picture of us?"],
        ["W", "Of course. Say cheese."],
        ["M", "Do you know where the post office is?"],
        ["W", "It's behind that grey building."],
        ["M", "How much does this cost?"],
        ["W", "Three dollars each."],
        ["M", "Do you need a hand with that?"],
        ["W", "Yes, please. I can't reach the top shelf."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Do you need a hand with that?",
      explanation:
        "그림은 서점에서 높은 책장 맨 위 칸에 손이 닿지 않아 애쓰는 사람에게 키 큰 사람이 다가와 도와주려는 장면이므로 ⑤가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "Inside a bookshop. A short woman is standing on her toes with one arm stretched up, trying to reach a book on the TOP shelf of a tall bookcase, and she cannot reach it. A taller man beside her is stepping forward and raising his hand toward the same top shelf to help her. Both are drawn clearly. Rows of books fill the shelves and no writing appears anywhere.",
      },
      translation: [
        "① M: 이 버스 얼마나 자주 와요? / W: 10분마다요.",
        "② M: 저희 사진 좀 찍어 주시겠어요? / W: 그럼요. 하나, 둘, 셋.",
        "③ M: 우체국이 어디 있는지 아세요? / W: 저 회색 건물 뒤에 있어요.",
        "④ M: 이거 얼마예요? / W: 하나에 3달러입니다.",
        "⑤ M: 도와드릴까요? / W: 네, 부탁해요. 맨 위 칸에 손이 안 닿아서요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunbi, you're going to the teachers' office after class, right?"],
        ["W", "Yes, I have to return the class journal."],
        ["M", "Could you do one thing for me while you're there?"],
        ["W", "Sure. What is it?"],
        ["M", "I handed in my report form without a date on it."],
        ["W", "Do you want me to take it back out for you?"],
        ["M", "No, just write today's date at the top. It's in the blue tray."],
        ["W", "Got it. Which name should I look for?"],
        ["M", "Kang Minhyuk, class three."],
        ["W", "All right. I'll do it before I leave."],
      ],
      choices: ["날짜를 적어 주기", "보고서를 다시 가져다주기", "일지를 대신 반납하기", "새 양식을 받아 오기", "이름을 고쳐 주기"],
      answer: 1,
      clue: "No, just write today's date at the top. It's in the blue tray.",
      explanation:
        "남자는 제출한 보고서 맨 위에 오늘 날짜만 적어 달라고 부탁한다. 다시 가져다 달라는 것이 아니다. 따라서 답은 ①이다.",
      translation: [
        "M: 은비야, 수업 끝나고 교무실 가지?",
        "W: 응, 학급 일지 반납해야 해.",
        "M: 거기 있는 동안 하나만 부탁할게.",
        "W: 그래. 뭔데?",
        "M: 보고서 양식을 냈는데 날짜를 안 썼어.",
        "W: 도로 빼다 줄까?",
        "M: 아니, 맨 위에 오늘 날짜만 적어 줘. 파란 바구니에 있어.",
        "W: 알겠어. 이름이 뭐로 되어 있어?",
        "M: 3반 강민혁.",
        "W: 그래. 나오기 전에 해 놓을게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Green Market Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Here is news about Green Market Day."],
        ["W", "It will be held on the second Saturday of next month."],
        ["W", "The stalls will stand along the path between the gym and the library."],
        ["W", "You may sell clothes, books, and small items you no longer use."],
        ["W", "All the money raised goes to the city animal shelter."],
        ["W", "Come and clear out your room for a good cause."],
      ],
      choices: ["열리는 날", "장소", "팔 수 있는 물건", "수익금 사용처", "참가 신청 기간"],
      answer: 5,
      clue: "All the money raised goes to the city animal shelter.",
      explanation:
        "날짜(다음 달 둘째 토요일), 장소(체육관과 도서관 사이 길), 팔 수 있는 물건(옷·책·작은 물건), 수익금 사용처(시 동물보호소)는 언급되지만 참가 신청 기간은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. Green Market Day 소식입니다.",
        "W: 다음 달 둘째 토요일에 열립니다.",
        "W: 가판은 체육관과 도서관 사이 길을 따라 놓입니다.",
        "W: 더 이상 쓰지 않는 옷과 책, 작은 물건을 팔 수 있습니다.",
        "W: 모인 돈은 모두 시 동물보호소로 갑니다.",
        "W: 좋은 일도 하고 방도 정리해 보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You will find this in the corner of almost every classroom."],
        ["M", "It is a tall box with a door and a wide, flat top."],
        ["M", "Warm air comes out of it from late autumn to early spring."],
        ["M", "Teachers tell you not to dry wet gloves on top of it."],
        ["M", "In summer nobody notices that it is there at all."],
      ],
      choices: ["사물함", "난방기", "정수기", "청소함", "책장"],
      answer: 2,
      clue: "Warm air comes out of it from late autumn to early spring.",
      explanation:
        "늦가을부터 초봄까지 더운 바람이 나오고 여름에는 아무도 눈여겨보지 않는다고 했으므로 난방기이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 거의 모든 교실 구석에 있습니다.",
        "M: 문이 달리고 윗면이 넓고 평평한 키 큰 상자입니다.",
        "M: 늦가을부터 초봄까지 여기서 더운 바람이 나옵니다.",
        "M: 선생님들은 젖은 장갑을 그 위에 말리지 말라고 합니다.",
        "M: 여름에는 아무도 그게 거기 있는 줄 모릅니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How was the school trip?"],
        ["M", "Long, but I'm glad I went."],
        ["W", "Would you mind opening the door?"],
        ["M", "Not at all."],
        ["W", "Who is going to speak first?"],
        ["M", "I left it on the bus."],
        ["W", "When does the library open on Saturday?"],
        ["M", "At ten in the morning."],
        ["W", "Shall we walk or take the bus?"],
        ["M", "Let's walk. It's only ten minutes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Who is going to speak first?",
      explanation:
        "누가 먼저 발표하느냐는 물음에 버스에 두고 왔다는 대답은 어울리지 않는다. 따라서 답은 ③이다.",
      translation: [
        "① W: 수학여행 어땠어? / M: 길었지만 가길 잘했어.",
        "② W: 문 좀 열어 줄래? / M: 그럼, 열어 줄게.",
        "③ W: 누가 먼저 발표할 거야? / M: 버스에 두고 왔어.",
        "④ W: 토요일에 도서관 몇 시에 열어? / M: 아침 10시에.",
        "⑤ W: 걸어갈까, 버스 탈까? / M: 걷자. 10분밖에 안 걸려.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerim, the science exhibition opens in half an hour."],
        ["W", "Is the room ready? What should I take care of?"],
        ["M", "I've put the posters up and arranged the models on the tables."],
        ["W", "Should I print the name cards?"],
        ["M", "Dowon printed them this morning."],
        ["W", "Then what's still missing?"],
        ["M", "The extension cord for the lamps is in the storage room."],
        ["W", "I'll go and get it now."],
        ["M", "Thanks. I'll open the windows while you're gone."],
      ],
      choices: ["포스터 붙이기", "모형 배치하기", "이름표 인쇄하기", "창문 열기", "연장선 가져오기"],
      answer: 5,
      clue: "I'll go and get it now.",
      explanation:
        "포스터와 모형, 이름표는 이미 해결되었으므로 여자는 창고에 있는 연장선을 가지러 간다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 예림아, 과학 전시가 30분 뒤에 시작해.",
        "W: 교실은 준비됐어? 내가 뭘 맡을까?",
        "M: 포스터는 다 붙였고 모형도 책상에 배치했어.",
        "W: 이름표를 인쇄할까?",
        "M: 도원이가 아침에 인쇄했어.",
        "W: 그럼 뭐가 아직 없어?",
        "M: 조명에 쓸 연장선이 창고에 있어.",
        "W: 내가 지금 가서 가져올게.",
        "M: 고마워. 네가 간 사이에 창문을 열어 둘게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 캠프를 고르시오.",
      lines: [
        ["W", "Junyeong, these are the five summer camps still taking students."],
        ["M", "Let's look. I can't go in July because of my grandmother's birthday."],
        ["W", "Then one is out. What else matters?"],
        ["M", "It has to be two nights. One night is too short to learn anything."],
        ["W", "One of them is a single night, so that's gone too."],
        ["M", "Three left. How about the cost?"],
        ["W", "You said a hundred and fifty thousand won at the most."],
        ["M", "Then one more drops out. Two are left."],
        ["W", "Is there a difference between those two?"],
        ["M", "One is by the sea and the other is in the mountains. I want the sea."],
        ["W", "Then that settles it. Book it before Friday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Then that settles it. Book it before Friday.",
      explanation:
        "7월인 ③, 1박인 ④, 180,000원인 ⑤를 뺀다. 남은 ①과 ② 중 바다에 있는 것은 ①이므로 답은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "8월 / 2박 / 140,000원 / 바다" },
          { no: 2, label: "②", value: "8월 / 2박 / 150,000원 / 산" },
          { no: 3, label: "③", value: "7월 / 2박 / 140,000원 / 바다" },
          { no: 4, label: "④", value: "8월 / 1박 / 100,000원 / 바다" },
          { no: 5, label: "⑤", value: "8월 / 2박 / 180,000원 / 바다" },
        ],
      },
      translation: [
        "W: 준영아, 아직 신청을 받는 여름 캠프가 이 다섯 개야.",
        "M: 보자. 할머니 생신 때문에 7월에는 못 가.",
        "W: 그럼 하나 빠지네. 또 뭐가 중요해?",
        "M: 2박이어야 해. 1박은 뭘 배우기엔 너무 짧아.",
        "W: 하나는 1박이니까 그것도 빠져.",
        "M: 셋 남았다. 비용은 어때?",
        "W: 많아야 15만 원이라고 했잖아.",
        "M: 그럼 하나 더 빠지고 둘 남았다.",
        "W: 그 둘은 뭐가 달라?",
        "M: 하나는 바다에 있고 하나는 산에 있어. 나는 바다가 좋아.",
        "W: 그럼 정해졌네. 금요일 전에 예약해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 공연을 보러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taeho, when should we go and see the musical?"],
        ["M", "It's on from the twenty-first to the twenty-fourth."],
        ["W", "What's it about?"],
        ["M", "A group of students who start a radio station at school."],
        ["W", "That sounds fun. But I have a piano exam on the twenty-first."],
        ["M", "Then the twenty-second, third, or fourth."],
        ["W", "The twenty-fourth is Sunday and my cousins are visiting."],
        ["M", "And the twenty-third is the day we clean the classroom until late."],
        ["W", "So the twenty-second is the only day left."],
        ["M", "Then let's go on the twenty-second. I'll book two seats."],
      ],
      choices: ["21일", "22일", "23일", "24일", "25일"],
      answer: 2,
      clue: "So the twenty-second is the only day left.",
      explanation:
        "21일은 피아노 시험, 24일은 사촌 방문, 23일은 늦게까지 교실 청소여서 22일만 남는다. 따라서 답은 ②이다.",
      translation: [
        "W: 태호야, 뮤지컬 언제 보러 갈까?",
        "M: 21일부터 24일까지 해.",
        "W: 무슨 내용인데?",
        "M: 학교에 라디오 방송국을 만드는 학생들 이야기야.",
        "W: 재밌겠다. 그런데 나 21일에 피아노 시험이 있어.",
        "M: 그럼 22일, 23일, 24일이네.",
        "W: 24일은 일요일인데 사촌들이 와.",
        "M: 그리고 23일은 늦게까지 교실 청소하는 날이야.",
        "W: 그럼 22일만 남네.",
        "M: 그럼 22일에 가자. 두 자리 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sujin, did you finish that novel last weekend?"],
        ["W", "No, I spent Saturday painting my room."],
        ["M", "Painting? By yourself?"],
        ["W", "With my brother. We did one wall each."],
        ["M", "What colour did you choose?"],
        ["W", "A pale green. It took three coats to cover the old blue."],
        ["M", "So the whole day went on one room?"],
        ["W", "The whole day. My arms still hurt, but I like how it looks."],
      ],
      choices: ["소설 읽기", "친구 만나기", "방 페인트칠하기", "가구 옮기기", "그림 그리기"],
      answer: 3,
      clue: "No, I spent Saturday painting my room.",
      explanation:
        "여자는 지난 토요일에 남동생과 방에 페인트를 칠했다고 말한다. 따라서 답은 ③이다.",
      translation: [
        "M: 수진아, 지난 주말에 그 소설 다 읽었어?",
        "W: 아니, 토요일에 방 페인트칠했어.",
        "M: 페인트칠? 혼자?",
        "W: 동생이랑. 한 사람이 한 벽씩 했어.",
        "M: 무슨 색으로 했는데?",
        "W: 연한 초록. 원래 파란색을 덮느라 세 번 칠했어.",
        "M: 그럼 하루 종일 방 하나에 매달린 거야?",
        "W: 하루 종일. 팔이 아직 아프지만 마음에 들어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "From Monday the front gate will be closed for repairs."],
        ["M", "Please use the small side gate beside the bicycle racks."],
        ["M", "The work will take about two weeks."],
        ["M", "The side gate is narrower, so leave home five minutes earlier."],
        ["M", "Thank you for your patience."],
      ],
      choices: [
        "자전거를 세워 달라고 하려고",
        "등교 시간을 늦추려고",
        "공사 비용을 안내하려고",
        "정문 대신 옆문을 쓰라고 하려고",
        "교문 앞 청소를 부탁하려고",
      ],
      answer: 4,
      clue: "Please use the small side gate beside the bicycle racks.",
      explanation:
        "정문 보수 공사 동안 자전거 거치대 옆 옆문을 쓰라고 알리는 방송이다. 따라서 방송의 목적은 ④이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 월요일부터 정문이 보수 공사로 닫힙니다.",
        "M: 자전거 거치대 옆 작은 옆문을 이용해 주세요.",
        "M: 공사는 2주쯤 걸립니다.",
        "M: 옆문이 좁으니 집에서 5분 일찍 나오세요.",
        "M: 협조해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the city aquarium. How many tickets would you like?"],
        ["W", "Three student tickets, please."],
        ["M", "Student tickets are eight dollars each."],
        ["W", "So twenty-four dollars."],
        ["M", "That's right. Would you like to join the feeding tour as well?"],
        ["W", "How much is that?"],
        ["M", "Five dollars per person on top of the ticket."],
        ["W", "Then two of us, please."],
        ["M", "All right. And students get four dollars off the total on weekdays."],
        ["W", "Great, today is Tuesday. Here's my card."],
      ],
      choices: ["$24", "$26", "$28", "$30", "$34"],
      answer: 4,
      clue: "All right. And students get four dollars off the total on weekdays.",
      explanation:
        "학생 표 8달러씩 세 장은 24달러, 먹이 주기 5달러씩 두 명은 10달러여서 34달러이다. 평일 할인 4달러를 빼면 30달러이므로 답은 ④이다.",
      translation: [
        "M: 시립 수족관입니다. 표 몇 장 드릴까요?",
        "W: 학생 표 세 장 주세요.",
        "M: 학생 표는 한 장에 8달러입니다.",
        "W: 그럼 24달러네요.",
        "M: 맞습니다. 먹이 주기 체험도 하시겠어요?",
        "W: 그건 얼마예요?",
        "M: 표값에 더해 한 사람에 5달러입니다.",
        "W: 그럼 저희 둘만요.",
        "M: 알겠습니다. 그리고 평일에는 학생에게 전체 금액에서 4달러를 빼 드립니다.",
        "W: 잘됐네요, 오늘 화요일이에요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Seungmin, you've rewritten that essay four times this week."],
        ["M", "The deadline is Monday and the ending still falls flat."],
        ["W", "Which part exactly?"],
        ["M", "The last paragraph. It just repeats what I said at the start."],
        ["W", "How do you write the ending?"],
        ["M", "I write it straight after the body, when I'm already tired."],
        ["W", "So the ending always gets the worst hour of your day."],
        ["M", "I'd never looked at it that way."],
        ["W", "Write the body tonight and the ending tomorrow morning."],
      ],
      choices: [
        "My essay is about city libraries.",
        "Then I'll leave the ending until tomorrow.",
        "The deadline was moved to Tuesday.",
        "I usually write about eight hundred words.",
        "You should read my first draft.",
      ],
      answer: 2,
      clue: "Write the body tonight and the ending tomorrow morning.",
      explanation:
        "본문은 오늘 밤에 쓰고 결론은 내일 아침에 쓰라는 조언을 들었으므로, 결론을 내일로 미루겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 승민아, 이번 주에 그 글을 네 번이나 다시 썼네.",
        "M: 마감이 월요일인데 마무리가 아직 밋밋해.",
        "W: 정확히 어느 부분?",
        "M: 마지막 문단. 처음에 한 말을 되풀이하기만 해.",
        "W: 마무리는 어떻게 쓰는데?",
        "M: 본문 다 쓰고 바로 써. 이미 지쳐 있을 때.",
        "W: 그럼 마무리는 늘 하루 중 제일 안 좋은 시간을 받네.",
        "M: 그렇게는 생각 못 했어.",
        "W: 오늘 밤엔 본문을 쓰고 마무리는 내일 아침에 써.",
        "M: 그럼 마무리는 내일로 미룰게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Chaeyoung, your English listening score hasn't moved since March."],
        ["W", "I listen to English every day on the bus."],
        ["M", "What do you listen to?"],
        ["W", "Songs, mostly. Sometimes a drama with subtitles."],
        ["M", "And do you ever stop and check what you heard?"],
        ["W", "No, I just let it play until I get off."],
        ["M", "Then you're hearing English, not listening to it."],
        ["W", "That's fair. I've never written anything down."],
        ["M", "Take one short talk a day and write out what you hear."],
      ],
      choices: [
        "Then I'll start with one talk tonight.",
        "The bus ride takes forty minutes.",
        "I've been learning English since third grade.",
        "My headphones are broken.",
        "You should listen to that song too.",
      ],
      answer: 1,
      clue: "Take one short talk a day and write out what you hear.",
      explanation:
        "하루에 짧은 말 하나를 받아써 보라는 조언을 들었으므로, 오늘 밤부터 하나 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 채영아, 3월 이후로 영어 듣기 점수가 그대로네.",
        "W: 버스에서 매일 영어 들어요.",
        "M: 뭘 듣는데?",
        "W: 주로 노래요. 가끔 자막 있는 드라마도 보고요.",
        "M: 듣다가 멈춰서 뭘 들었는지 확인해 본 적 있어?",
        "W: 아니요, 내릴 때까지 그냥 틀어 둬요.",
        "M: 그건 영어를 듣는 게 아니라 흘려보내는 거야.",
        "W: 맞아요. 한 번도 받아써 본 적이 없어요.",
        "M: 하루에 짧은 말 하나씩 골라서 들리는 대로 적어 봐.",
        "W: 그럼 오늘 밤에 하나부터 시작할게요.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Hoseok, how is the class fundraising going?"],
        ["M", "Not well. We've collected less than a third of what we need."],
        ["W", "How are you asking for donations?"],
        ["M", "I put a box at the back of the classroom."],
        ["W", "Just a box, with nothing on it?"],
        ["M", "There's a sign that says 'Please help'."],
        ["W", "Nobody gives to a box when they don't know what it buys."],
        ["M", "I never thought about that."],
        ["W", "Write on the box what the money is for and how much is left to go."],
      ],
      choices: [
        "The box is behind the last desk.",
        "We started collecting two weeks ago.",
        "Then I'll write both on it tomorrow.",
        "Our class has thirty-one students.",
        "I'd rather ask the teacher for help.",
      ],
      answer: 3,
      clue: "Write on the box what the money is for and how much is left to go.",
      explanation:
        "상자에 돈의 쓰임과 남은 금액을 적으라는 조언을 들었으므로, 내일 둘 다 적겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 호석아, 학급 모금은 잘돼 가?",
        "M: 잘 안돼. 필요한 돈의 3분의 1도 못 모았어.",
        "W: 어떻게 모으고 있는데?",
        "M: 교실 뒤에 상자를 놔뒀어.",
        "W: 아무것도 안 써 붙인 상자만?",
        "M: '도와주세요'라고 쓴 종이는 있어.",
        "W: 그 돈으로 뭘 하는지 모르면 아무도 상자에 넣지 않아.",
        "M: 그 생각은 못 했어.",
        "W: 상자에 돈의 쓰임과 얼마가 남았는지 적어.",
        "M: 그럼 내일 둘 다 적을게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jaehyun이 Somi에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Jaehyun : ________________",
      lines: [
        ["M", "Jaehyun and Somi are preparing the class video for graduation."],
        ["M", "Somi has collected photographs from every student in the class."],
        ["M", "The photographs are clear and well chosen."],
        ["M", "However, she has set each one to stay on screen for one second."],
        ["M", "At that speed nobody can tell who is in the picture."],
        ["M", "Their teacher said the video should be easy to follow."],
        ["M", "Jaehyun does not want to say that her work was wasted."],
        ["M", "He wants to suggest holding each photograph for about three seconds."],
        ["M", "In this situation, what would Jaehyun most likely say to Somi?"],
      ],
      choices: [
        "Let's use fewer photographs next time.",
        "You should add more music to the video.",
        "I'll collect the photographs myself.",
        "Could we hold each photo for about three seconds?",
        "The photographs are too dark to use.",
      ],
      answer: 4,
      clue: "He wants to suggest holding each photograph for about three seconds.",
      explanation:
        "재현이는 소미가 한 일을 깎아내리지 않으면서, 사진 한 장을 3초쯤 띄워 두자고 말하려 한다. 따라서 ④가 가장 적절하다.",
      translation: [
        "M: 재현이와 소미는 졸업식에 쓸 학급 영상을 준비하고 있습니다.",
        "M: 소미가 반 학생 모두에게서 사진을 모았습니다.",
        "M: 사진은 또렷하고 잘 골랐습니다.",
        "M: 그런데 한 장이 화면에 1초만 머물도록 해 두었습니다.",
        "M: 그 속도로는 누가 찍혔는지 알아볼 수가 없습니다.",
        "M: 선생님은 영상이 따라가기 쉬워야 한다고 했습니다.",
        "M: 재현이는 소미가 한 일이 헛수고라고 말하고 싶지는 않습니다.",
        "M: 다만 사진 한 장을 3초쯤 띄워 두자고 제안하고 싶습니다.",
        "M: 이런 상황에서 재현이가 소미에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
