/** 중3 듣기 39회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 39회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 화분을 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a plant pot?"],
        ["M", "Yes, one for the windowsill in my room."],
        ["W", "We have tall pots and short wide ones."],
        ["M", "A short wide one. My window ledge is narrow."],
        ["W", "Would you like handles on the sides?"],
        ["M", "No handles. They take up too much space."],
        ["W", "This one has a small dish under it."],
        ["M", "Yes, a dish is useful when I water it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A short wide one. My window ledge is narrow. / Yes, a dish is useful when I water it.",
      explanation:
        "남자는 낮고 넓으며 손잡이가 없고 받침 접시가 있는 화분을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five empty plant pots side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a TALL narrow pot standing alone with no dish. " +
          "② a TALL narrow pot with two HANDLES on its sides. " +
          "③ a SHORT WIDE pot with two HANDLES on its sides and no dish. " +
          "④ a TALL narrow pot sitting on a flat round DISH. " +
          "⑤ a SHORT WIDE pot with no handles, sitting on a flat round DISH.",
      },
      translation: [
        "W: 안녕하세요. 화분 찾으세요?",
        "M: 네, 제 방 창턱에 놓을 거예요.",
        "W: 키가 큰 것도 있고 낮고 넓은 것도 있어요.",
        "M: 낮고 넓은 걸로요. 창턱이 좁아요.",
        "W: 옆에 손잡이가 있는 건 어떠세요?",
        "M: 손잡이는 빼 주세요. 자리를 많이 차지해요.",
        "W: 이건 아래에 작은 받침 접시가 있어요.",
        "M: 네, 물 줄 때 접시가 있으면 좋아요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 밴드 오디션에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, are you trying out for the school band?"],
        ["W", "I might. When is the audition?"],
        ["M", "Next Friday, right after the sixth period."],
        ["W", "How long does each person play?"],
        ["M", "Two minutes, and you choose the piece yourself."],
        ["W", "Do I have to bring my own instrument?"],
        ["M", "Yes, except for the drums and the piano."],
        ["W", "Where do we wait before our turn?"],
        ["M", "In the hallway outside the music room."],
      ],
      choices: [
        "오디션 날짜",
        "연주하는 시간",
        "악기 준비",
        "기다리는 장소",
        "뽑히는 인원",
      ],
      answer: 5,
      clue: "Next Friday, right after the sixth period.",
      explanation:
        "날짜, 연주 시간, 악기, 대기 장소는 말했지만 뽑는 인원은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 서연아, 학교 밴드 오디션 볼 거야?",
        "W: 볼까 해. 오디션 언제야?",
        "M: 다음 주 금요일, 6교시 바로 끝나고.",
        "W: 한 사람이 얼마나 연주해?",
        "M: 2분. 곡은 직접 고르는 거야.",
        "W: 악기는 내가 가져가야 해?",
        "M: 응, 드럼이랑 피아노만 빼고.",
        "W: 차례 전에 어디서 기다려?",
        "M: 음악실 밖 복도에서.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Jaeho. It's Minseo. Do you have a minute?"],
        ["M", "Sure. What's up?"],
        ["W", "You helped me with the poster last Saturday."],
        ["M", "It was only two hours of work."],
        ["W", "It won second place in the contest."],
        ["M", "That's wonderful news for you."],
        ["W", "I really wanted to say thank you properly."],
      ],
      choices: [
        "고마움을 전하려고",
        "도움을 요청하려고",
        "약속을 미루려고",
        "숙제를 물어보려고",
        "물건을 빌리려고",
      ],
      answer: 1,
      clue: "I really wanted to say thank you properly.",
      explanation:
        "여자는 도와준 것에 제대로 고마움을 전하려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 재호야. 민서야. 잠깐 시간 돼?",
        "M: 응. 무슨 일이야?",
        "W: 지난 토요일에 포스터 도와줬잖아.",
        "M: 두 시간밖에 안 걸렸는데.",
        "W: 그게 대회에서 2등 했어.",
        "M: 너한테 정말 좋은 소식이다.",
        "W: 제대로 고맙다고 말하고 싶었어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 도서관에서 만날 시각을 고르시오.",
      lines: [
        ["M", "Jiwon, when should we work on the report?"],
        ["W", "The library closes at eight tonight."],
        ["M", "We need at least two hours together."],
        ["W", "Then we have to start by six o'clock."],
        ["M", "My tutoring finishes at five forty."],
        ["W", "The library is fifteen minutes from there."],
        ["M", "So six would be too early for me."],
        ["W", "Let's meet at six fifteen instead."],
        ["M", "Six fifteen at the reading room door."],
      ],
      choices: ["5:40 p.m.", "6:00 p.m.", "6:15 p.m.", "6:30 p.m.", "8:00 p.m."],
      answer: 3,
      clue: "Let's meet at six fifteen instead.",
      explanation:
        "남자의 수업이 5시 40분에 끝나고 이동 시간이 있어 6시 15분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 지원아, 보고서 언제 할까?",
        "W: 오늘 도서관이 여덟 시에 닫아.",
        "M: 우리 둘이 적어도 두 시간은 있어야 해.",
        "W: 그럼 여섯 시까지는 시작해야겠다.",
        "M: 내 과외가 5시 40분에 끝나.",
        "W: 거기서 도서관까지 15분 걸려.",
        "M: 그럼 여섯 시는 나한테 너무 이르네.",
        "W: 대신 6시 15분에 만나자.",
        "M: 6시 15분에 열람실 문 앞에서.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, you've been standing by the window all break."],
        ["W", "My family is moving to another city next month."],
        ["M", "Does that mean you're changing schools?"],
        ["W", "I'll finish this term and then leave."],
        ["M", "We've been in the same class for three years."],
        ["W", "That's exactly what I keep thinking about."],
        ["M", "We can still call each other, you know."],
        ["W", "It won't be the same as sitting together."],
      ],
      choices: ["angry", "excited", "bored", "sad", "surprised"],
      answer: 4,
      clue: "It won't be the same as sitting together.",
      explanation:
        "전학으로 친구와 헤어지게 되어 서운해하고 있다. 따라서 답은 ④이다.",
      translation: [
        "M: 다혜야, 쉬는 시간 내내 창가에 서 있네.",
        "W: 다음 달에 우리 가족이 다른 도시로 이사 가.",
        "M: 그럼 전학 가는 거야?",
        "W: 이번 학기 마치고 떠나.",
        "M: 우리 3년을 같은 반이었는데.",
        "W: 나도 계속 그 생각만 해.",
        "M: 그래도 서로 전화할 수 있잖아.",
        "W: 같이 앉아 있는 거랑은 다르지.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you deliver to my house?"],
        ["M", "Yes, within three kilometers."],
        ["ANN", "Number two."],
        ["W", "Are these apples sweet?"],
        ["M", "Try a slice and see."],
        ["ANN", "Number three."],
        ["W", "How much for three of them?"],
        ["M", "Five thousand won for three."],
        ["ANN", "Number four."],
        ["W", "I think you gave me too much change."],
        ["M", "Oh, you're right. Thank you."],
        ["ANN", "Number five."],
        ["W", "Do you have a paper bag?"],
        ["M", "Here you are, no charge."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I think you gave me too much change.",
      explanation:
        "그림은 과일 가게에서 여자가 거스름돈을 다시 내밀고 주인이 놀라는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "A small fruit shop counter, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A woman holds out several coins on her open palm toward the shopkeeper with a polite expression. " +
          "The shopkeeper, standing behind a cash box, raises one hand to his cheek in surprise and reaches for the coins. " +
          "Boxes of apples and pears are drawn simply beside the counter.",
      },
      translation: [
        "① W: 우리 집까지 배달되나요? / M: 네, 3킬로미터 안이면요.",
        "② W: 이 사과 달아요? / M: 한 조각 드셔 보세요.",
        "③ W: 세 개에 얼마예요? / M: 세 개에 5천 원입니다.",
        "④ W: 거스름돈을 더 주신 것 같아요. / M: 아, 맞네요. 고맙습니다.",
        "⑤ W: 종이봉투 있나요? / M: 여기요, 그냥 드려요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, do you still live near the bus terminal?"],
        ["M", "Two streets away from it."],
        ["W", "My aunt arrives there tomorrow at seven."],
        ["M", "Will you be able to meet her?"],
        ["W", "I have an exam until seven thirty."],
        ["M", "So she'd be waiting alone for a while."],
        ["W", "Could you wait with her until I get there?"],
        ["M", "Of course. I'll be at the terminal by seven."],
      ],
      choices: [
        "짐을 들어 주기",
        "길을 알려 주기",
        "시험공부를 도와주기",
        "터미널에서 함께 기다려 주기",
        "표를 사다 주기",
      ],
      answer: 4,
      clue: "Could you wait with her until I get there?",
      explanation:
        "여자는 자기가 갈 때까지 이모와 함께 기다려 달라고 부탁했다. 따라서 답은 ④이다.",
      translation: [
        "W: 상우야, 아직 버스 터미널 근처에 살아?",
        "M: 거기서 두 블록 떨어진 데.",
        "W: 내일 일곱 시에 이모가 거기 도착해.",
        "M: 너는 마중 나갈 수 있어?",
        "W: 7시 30분까지 시험이 있어.",
        "M: 그럼 이모가 한동안 혼자 기다리시겠네.",
        "W: 내가 갈 때까지 같이 기다려 줄 수 있어?",
        "M: 물론이지. 일곱 시까지 터미널에 가 있을게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 벽화 그리기 활동에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. We will paint a mural on the back wall. " +
            "The work takes place on the last two Saturdays of May. " +
            "Twenty students can take part in the painting. " +
            "Wear clothes that you do not mind getting dirty. " +
            "Brushes and paint will be prepared by the art teacher.",
        ],
      ],
      choices: [
        "작업하는 날",
        "참여 인원",
        "입고 와야 할 옷",
        "준비되는 도구",
        "그릴 그림의 주제",
      ],
      answer: 5,
      clue: "The work takes place on the last two Saturdays of May.",
      explanation:
        "날짜, 인원, 복장, 도구는 말했지만 그림의 주제는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 뒤쪽 벽에 벽화를 그립니다. 5월 마지막 두 토요일에 작업합니다. 스무 명이 그리기에 참여할 수 있습니다. 더러워져도 괜찮은 옷을 입고 오세요. 붓과 물감은 미술 선생님이 준비해 주십니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a small card that lets you ride buses and subways. " +
            "You touch it on a reader when you get on. " +
            "The money inside it goes down after each ride. " +
            "You can add more money at a convenience store. " +
            "Losing it is worse than losing your student card.",
        ],
      ],
      choices: ["교통카드", "신분증", "영수증", "도서 대출증", "우표"],
      answer: 1,
      clue: "This is a small card that lets you ride buses and subways.",
      explanation:
        "버스와 지하철을 탈 때 대고 충전해 쓰는 것은 교통카드이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 버스와 지하철을 탈 수 있게 해 주는 작은 카드입니다. 탈 때 단말기에 대면 됩니다. 탈 때마다 안에 든 돈이 줄어듭니다. 편의점에서 돈을 더 넣을 수 있습니다. 이것을 잃어버리면 학생증을 잃어버린 것보다 곤란합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Is this your first time here?"],
        ["W", "No, I came last summer."],
        ["ANN", "Number two."],
        ["M", "Which team won the game?"],
        ["W", "My shoes are size two forty."],
        ["ANN", "Number three."],
        ["M", "Could you say that again?"],
        ["W", "I said the class is cancelled."],
        ["ANN", "Number four."],
        ["M", "What are you reading?"],
        ["W", "A novel about a long journey."],
        ["ANN", "Number five."],
        ["M", "Do you want some help?"],
        ["W", "Yes, please hold this end."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Which team won the game?",
      explanation:
        "어느 팀이 이겼는지 묻는 말에 신발 치수를 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① M: 여기 처음이에요? / W: 아니요, 지난여름에 왔어요.",
        "② M: 어느 팀이 이겼어? / W: 내 신발은 240이야.",
        "③ M: 다시 말해 줄래? / W: 수업이 취소됐다고 했어.",
        "④ M: 뭐 읽고 있어? / W: 긴 여행에 관한 소설.",
        "⑤ M: 도와줄까? / W: 응, 이쪽 끝 좀 잡아 줘.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kiyoung, whose water bottle is on the back shelf?"],
        ["M", "It looks like Sohee's green one."],
        ["W", "She went home after the fifth period."],
        ["M", "She has swimming lessons every Wednesday."],
        ["W", "She'll need that bottle at the pool."],
        ["M", "The pool is right beside my house."],
        ["W", "Then you could drop it off on your way."],
        ["M", "I'll pick it up and take it to her."],
      ],
      choices: [
        "수영장에서 운동하기",
        "교실을 청소하기",
        "집에 바로 가기",
        "물병을 가져다주기",
        "선생님께 맡기기",
      ],
      answer: 4,
      clue: "I'll pick it up and take it to her.",
      explanation:
        "남자는 물병을 가져다주겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 기영아, 뒤쪽 선반에 있는 물병 누구 거야?",
        "M: 소희 초록색 물병 같은데.",
        "W: 소희는 5교시 끝나고 집에 갔어.",
        "M: 수요일마다 수영 배우잖아.",
        "W: 수영장에서 그 물병 필요할 텐데.",
        "M: 수영장이 우리 집 바로 옆이야.",
        "W: 그럼 가는 길에 갖다주면 되겠다.",
        "M: 챙겨서 갖다줄게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 봉사 활동을 고르시오.",
      lines: [
        ["M", "Yuna, five volunteer programs are still open."],
        ["W", "I can only go on Saturday mornings."],
        ["M", "Two of them run on weekday evenings."],
        ["W", "How many hours does each one take?"],
        ["M", "They range from two to five hours."],
        ["W", "Three hours at most is right for me."],
        ["M", "And do you want to work with children?"],
        ["W", "Yes, that's why I applied last time."],
        ["M", "Then this one matches everything you said."],
        ["W", "I'll fill out the form this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "I can only go on Saturday mornings.",
      explanation:
        "토요일 오전, 3시간 이하, 아이들과 함께하는 활동을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Time: Saturday morning / Hours: 3 / With: Children" },
          { no: 2, label: "②", value: "Time: Saturday morning / Hours: 5 / With: Children" },
          { no: 3, label: "③", value: "Time: Saturday morning / Hours: 2 / With: Elderly" },
          { no: 4, label: "④", value: "Time: Tuesday evening / Hours: 2 / With: Children" },
          { no: 5, label: "⑤", value: "Time: Thursday evening / Hours: 3 / With: Elderly" },
        ],
      },
      translation: [
        "M: 유나야, 봉사 활동 다섯 개가 아직 열려 있어.",
        "W: 나는 토요일 오전에만 갈 수 있어.",
        "M: 두 개는 평일 저녁에 해.",
        "W: 각각 몇 시간씩이야?",
        "M: 두 시간에서 다섯 시간까지 있어.",
        "W: 나는 많아야 세 시간이 맞아.",
        "M: 아이들과 함께하는 게 좋아?",
        "W: 응, 지난번에도 그래서 신청했어.",
        "M: 그럼 이게 네가 말한 조건에 다 맞아.",
        "W: 오늘 저녁에 신청서 쓸게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 동아리 발표회를 열 날짜를 고르시오.",
      lines: [
        ["W", "Dongwoo, when should we hold the club showcase?"],
        ["M", "The hall is free on three days next month."],
        ["W", "Which days are open for us?"],
        ["M", "The sixth, the thirteenth and the twentieth."],
        ["W", "The sixth is only two weeks away."],
        ["M", "We couldn't finish rehearsing by then."],
        ["W", "And the twentieth is during the exam period."],
        ["M", "So the thirteenth is the only good day."],
        ["W", "I'll book the hall for the thirteenth."],
      ],
      choices: ["the 6th", "the 20th", "the 27th", "the 3rd", "the 13th"],
      answer: 5,
      clue: "So the thirteenth is the only good day.",
      explanation:
        "6일은 준비가 부족하고 20일은 시험 기간이어서 13일로 정했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 동우야, 동아리 발표회 언제 할까?",
        "M: 다음 달에 강당이 사흘 비어.",
        "W: 어떤 날들이 열려 있어?",
        "M: 6일, 13일, 20일.",
        "W: 6일은 2주밖에 안 남았어.",
        "M: 그때까지 연습을 못 끝내.",
        "W: 그리고 20일은 시험 기간이야.",
        "M: 그럼 13일밖에 없네.",
        "W: 13일로 강당을 예약할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunjin, did you rest well over the weekend?"],
        ["M", "Not really. I sold books at the market with my mother."],
        ["W", "Which market are you talking about?"],
        ["M", "The flea market they hold by the river."],
        ["W", "What kind of books did you bring?"],
        ["M", "Old novels and picture books from our shelves."],
        ["W", "Did many people stop at your table?"],
        ["M", "We sold almost forty books before noon."],
        ["W", "What will you do with the money?"],
        ["M", "We sent all of it to a children's center."],
      ],
      choices: [
        "집에서 쉬기",
        "친구와 자전거를 타기",
        "벼룩시장에서 책을 팔기",
        "도서관에서 공부하기",
        "가족과 여행을 가기",
      ],
      answer: 3,
      clue: "I sold books at the market with my mother.",
      explanation:
        "남자는 주말에 어머니와 벼룩시장에서 책을 팔았다. 따라서 답은 ③이다.",
      translation: [
        "W: 현진아, 주말에 잘 쉬었어?",
        "M: 별로. 엄마랑 시장에서 책 팔았어.",
        "W: 어느 시장 말하는 거야?",
        "M: 강가에서 여는 벼룩시장.",
        "W: 어떤 책을 가져갔어?",
        "M: 우리 책장에 있던 옛날 소설이랑 그림책.",
        "W: 사람들이 많이 들렀어?",
        "M: 점심 전에 마흔 권 가까이 팔았어.",
        "W: 그 돈은 어떻게 해?",
        "M: 전부 아동 센터에 보냈어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the school cafeteria staff. " +
            "Many trays are being left on the tables lately. " +
            "Please carry your tray to the return window yourself. " +
            "Separate the food waste into the gray bin first. " +
            "Spoons and chopsticks go into the basket beside it. " +
            "Thank you for helping us keep the room clean.",
        ],
      ],
      choices: [
        "식판 정리를 부탁하려고",
        "메뉴를 소개하려고",
        "급식 시간을 바꾸려고",
        "손 씻기를 당부하려고",
        "설문에 참여해 달라고 하려고",
      ],
      answer: 1,
      clue: "Please carry your tray to the return window yourself.",
      explanation:
        "식판을 직접 반납구에 가져다 놓아 달라고 부탁하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 알려 드립니다. 급식실입니다. 요즘 식탁에 식판이 많이 남아 있습니다. 식판은 직접 반납구로 가져다 주세요. 먼저 음식물은 회색 통에 따로 버려 주세요. 숟가락과 젓가락은 그 옆 바구니에 넣어 주세요. 깨끗하게 써 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome. Are you buying tickets for the aquarium?"],
        ["W", "Two student tickets, please."],
        ["M", "Student tickets are eleven dollars each."],
        ["W", "Is the dolphin show included in that price?"],
        ["M", "The show is included, but the feeding program is not."],
        ["W", "How much is the feeding program?"],
        ["M", "Four dollars for each person."],
        ["W", "We'll join the feeding program too."],
        ["M", "Then that's everything for today."],
        ["W", "Here is my card. Thank you."],
      ],
      choices: ["$22", "$26", "$30", "$28", "$34"],
      answer: 3,
      clue: "Student tickets are eleven dollars each.",
      explanation:
        "학생 표 두 장 22달러에 먹이 주기 두 사람분 8달러를 더하면 30달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 어서 오세요. 수족관 표 사시나요?",
        "W: 학생 표 두 장이요.",
        "M: 학생 표는 한 장에 11달러입니다.",
        "W: 돌고래 공연도 그 값에 포함인가요?",
        "M: 공연은 포함이지만 먹이 주기 체험은 아닙니다.",
        "W: 먹이 주기 체험은 얼마예요?",
        "M: 한 사람당 4달러입니다.",
        "W: 먹이 주기 체험도 같이 할게요.",
        "M: 그러면 오늘은 그게 전부입니다.",
        "W: 여기 카드요. 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaeyeon, your English listening score jumped this month."],
        ["W", "I started listening to one short news clip daily."],
        ["M", "Do you understand all of it?"],
        ["W", "Not at first. I listen three times in a row."],
        ["M", "What changes between the first and third time?"],
        ["W", "The third time I hear whole sentences, not words."],
        ["M", "I only listen once and then give up."],
        ["W", "One listen is never enough for anyone."],
        ["M", "Which clip should I start with?"],
      ],
      choices: [
        "I don't listen to anything.",
        "Try the two minute weather one.",
        "You should listen only once.",
        "English listening is hopeless.",
        "My score went down.",
      ],
      answer: 2,
      clue: "Which clip should I start with?",
      explanation:
        "어떤 것부터 들으면 좋을지 물었으므로, 2분짜리 날씨 방송을 권하는 ②가 가장 자연스럽다.",
      translation: [
        "M: 채연아, 이번 달 영어 듣기 점수가 확 올랐네.",
        "W: 매일 짧은 뉴스 하나씩 듣기 시작했어.",
        "M: 다 알아들어?",
        "W: 처음엔 아니야. 연달아 세 번 들어.",
        "M: 첫 번째랑 세 번째가 뭐가 달라?",
        "W: 세 번째에는 단어가 아니라 문장으로 들려.",
        "M: 나는 한 번 듣고 포기해.",
        "W: 한 번으로 되는 사람은 없어.",
        "M: 어떤 걸로 시작하면 좋을까?",
        "W: 2분짜리 날씨 방송으로 해 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seonho, you walk to school every morning, don't you?"],
        ["M", "Forty minutes each way, rain or shine."],
        ["W", "Isn't that exhausting before a whole school day?"],
        ["M", "It wakes me up better than any alarm."],
        ["W", "What do you do while you're walking?"],
        ["M", "I listen to an audiobook most of the way."],
        ["W", "How many books have you finished like that?"],
        ["M", "Eleven since the school year started."],
        ["W", "Could I walk with you tomorrow morning?"],
      ],
      choices: [
        "Sure, I pass your street at seven.",
        "I take the subway now.",
        "Walking is not allowed.",
        "I don't listen to books.",
        "Tomorrow there is no school.",
      ],
      answer: 1,
      clue: "Could I walk with you tomorrow morning?",
      explanation:
        "여자가 내일 함께 걸어도 되는지 물었으므로, 일곱 시에 그 길을 지난다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 선호야, 매일 아침 걸어서 학교 오지?",
        "M: 편도 40분. 비가 오나 해가 나나.",
        "W: 하루 종일 수업인데 힘들지 않아?",
        "M: 어떤 알람보다 잠이 잘 깨.",
        "W: 걸으면서 뭐 해?",
        "M: 거의 내내 오디오북을 들어.",
        "W: 그렇게 몇 권이나 끝냈어?",
        "M: 학기 시작하고 열한 권.",
        "W: 내일 아침에 같이 걸어도 돼?",
        "M: 그럼, 일곱 시에 너희 길을 지나가.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, you didn't say much during the group meeting."],
        ["W", "I had ideas, but the others talked so fast."],
        ["M", "Did you get a chance to speak at all?"],
        ["W", "Only once, near the very end."],
        ["M", "Your idea about the survey was the best one."],
        ["W", "Nobody seemed to hear it, though."],
        ["M", "You said it while three people were talking."],
        ["W", "So I should wait for a quiet moment."],
        ["M", "Or write it down and hand it to the leader."],
      ],
      choices: [
        "I never have ideas.",
        "That's a good plan, I'll do that.",
        "The meeting is cancelled.",
        "I already left the group.",
        "You should speak for me.",
      ],
      answer: 2,
      clue: "Or write it down and hand it to the leader.",
      explanation:
        "적어서 조장에게 건네라는 제안이므로, 그렇게 하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 예린아, 조별 회의에서 말을 별로 안 하더라.",
        "W: 생각은 있었는데 다들 너무 빨리 말했어.",
        "M: 말할 기회는 있었어?",
        "W: 거의 끝날 때 한 번만.",
        "M: 설문 얘기는 제일 좋은 생각이었어.",
        "W: 근데 아무도 못 들은 것 같아.",
        "M: 세 사람이 동시에 말할 때 얘기했잖아.",
        "W: 그럼 조용해질 때를 기다려야겠네.",
        "M: 아니면 적어서 조장한테 건네.",
        "W: 좋은 방법이다, 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Donghyun이 Jimin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Donghyun : ________________",
      lines: [
        [
          "M",
          "Donghyun and Jimin are working together at the school store. " +
            "Jimin writes down every sale in a notebook by hand. " +
            "Donghyun notices that she has counted the same box twice. " +
            "If the numbers stay wrong, this week's total will not match. " +
            "He wants to point out the mistake before she closes the book. " +
            "In this situation, what would Donghyun most likely say to Jimin?",
        ],
      ],
      choices: [
        "The store opens at nine tomorrow.",
        "You wrote that box down twice.",
        "Let's buy something to drink.",
        "I can't find the notebook.",
        "We sold nothing today.",
      ],
      answer: 2,
      clue: "He wants to point out the mistake before she closes the book.",
      explanation:
        "같은 상자를 두 번 적은 것을 알려 주려 하므로 ②가 가장 적절하다.",
      translation: [
        "M: 동현이와 지민이는 학교 매점에서 함께 일하고 있습니다. 지민이는 판매한 것을 하나하나 공책에 손으로 적습니다. 동현이는 지민이가 같은 상자를 두 번 센 것을 알아챕니다. 숫자가 틀린 채로 두면 이번 주 합계가 맞지 않습니다. 동현이는 지민이가 공책을 덮기 전에 잘못을 알려 주고 싶습니다. 이런 상황에서 동현이가 지민이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
