/** 중3 듣기 20회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 20회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 시계를 고르시오.",
      lines: [
        ["M", "Welcome. Are you looking for a wall clock?"],
        ["W", "Yes, for the kitchen. Something I can read from the table."],
        ["M", "We have round ones and square ones."],
        ["W", "Round, please. A square one looks like another picture frame."],
        ["M", "All right. Do you want numbers on the face, or just marks?"],
        ["W", "Numbers. My grandmother comes over and she can't read the marks."],
        ["M", "Then these two. One has a plain rim, and one has a wide wooden rim."],
        ["W", "The wooden one, please. The kitchen is all white and it needs some warmth."],
        ["M", "Good choice. It runs on one battery and it's very quiet."],
        ["W", "That matters. The old one ticked all night."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "The wooden one, please. The kitchen is all white and it needs some warmth.",
      explanation:
        "여자는 둥근 시계를, 숫자가 적힌 것으로, 그중 나무 테두리가 넓은 것을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five wall clocks arranged in one row across the middle of the picture, all five fully inside the frame with a wide empty margin on the left and right so nothing is cut off, each the same size, clean black line art on a plain white background. The only writing allowed anywhere in the picture is the hour numbers on the clock faces described below; no other letters, words or brand names. " +
          "Clock 1: SQUARE case, a thin plain rim, the face shows the hour NUMBERS 1 to 12. " +
          "Clock 2: SQUARE case, a thin plain rim, the face shows only short TICK MARKS and no numbers. " +
          "Clock 3: ROUND case, a thin plain rim, the face shows only short TICK MARKS and no numbers. " +
          "Clock 4: ROUND case, a thin plain rim, the face shows the hour NUMBERS 1 to 12. " +
          "Clock 5: ROUND case with a very WIDE THICK WOODEN RIM drawn with wood grain lines, the face shows the hour NUMBERS 1 to 12. " +
          "Every clock has two hands.",
      },
      translation: [
        "M: 어서 오세요. 벽시계 찾으세요?",
        "W: 네, 부엌에 둘 거예요. 식탁에서 보이는 걸로요.",
        "M: 둥근 것도 있고 네모난 것도 있습니다.",
        "W: 둥근 걸로요. 네모난 건 액자 하나 더 건 것 같아서요.",
        "M: 알겠습니다. 숫자가 적힌 걸로 하시겠어요, 눈금만 있는 걸로 하시겠어요?",
        "W: 숫자요. 할머니가 오시는데 눈금은 못 읽으세요.",
        "M: 그럼 이 두 개네요. 하나는 테두리가 얇고, 하나는 나무 테두리가 넓습니다.",
        "W: 나무로 된 걸로요. 부엌이 온통 하얘서 따뜻한 게 필요해요.",
        "M: 좋은 선택이세요. 건전지 하나로 가고 아주 조용합니다.",
        "W: 그게 중요해요. 전에 쓰던 건 밤새 똑딱거렸거든요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 두 사람이 참여할 독서 토론에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Jiwon, have you signed up for the reading discussion?"],
        ["M", "Not yet. When does it meet?"],
        ["W", "Every other Thursday, right after the sixth period."],
        ["M", "Where?"],
        ["W", "In the small room behind the library, the one with the round table."],
        ["M", "How many people are in it?"],
        ["W", "Eight, and two places are still open."],
        ["M", "What are we reading first?"],
        ["W", "A short novel about a lighthouse keeper. It's about a hundred pages."],
        ["M", "That I can manage. I'll sign up tomorrow morning."],
      ],
      choices: ["모이는 요일", "모이는 곳", "인원", "첫 책", "지도 선생님"],
      answer: 5,
      clue: "A short novel about a lighthouse keeper. It's about a hundred pages.",
      explanation:
        "요일(격주 목요일), 장소(도서관 뒤 작은 방), 인원(여덟 명), 첫 책(등대지기 이야기)은 언급되지만 지도 선생님은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 지원아, 독서 토론 신청했어?",
        "M: 아직. 언제 모이는데?",
        "W: 격주 목요일, 6교시 끝나고 바로.",
        "M: 어디서?",
        "W: 도서관 뒤 작은 방, 둥근 탁자 있는 데.",
        "M: 몇 명인데?",
        "W: 여덟 명인데 두 자리 남았어.",
        "M: 첫 책은 뭐 읽어?",
        "W: 등대지기 이야기인 짧은 소설. 백 쪽쯤 돼.",
        "M: 그 정도면 할 만하다. 내일 아침에 신청할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Minjun. It's Haeun from the science club."],
        ["M", "Hi. What's up?"],
        ["W", "It's about tomorrow's experiment. The lab is being painted."],
        ["M", "So it's cancelled?"],
        ["W", "No, we're moving to the classroom next to the office."],
        ["M", "Same time?"],
        ["W", "Same time. I'm calling everyone so nobody waits at the lab door."],
        ["M", "Thanks for letting me know. I'll be there."],
      ],
      choices: [
        "실험이 취소되었다고 알리려고",
        "준비물을 가져오라고 하려고",
        "시간을 바꾸자고 하려고",
        "장소가 바뀌었다고 알리려고",
        "동아리 가입을 권하려고",
      ],
      answer: 4,
      clue: "No, we're moving to the classroom next to the office.",
      explanation:
        "실험실에 칠을 해서 교무실 옆 교실로 장소가 바뀌었다는 것을 알리려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 민준아. 과학 동아리 하은이야.",
        "M: 안녕. 무슨 일이야?",
        "W: 내일 실험 말인데, 실험실에 칠을 하고 있어.",
        "M: 그럼 취소야?",
        "W: 아니, 교무실 옆 교실로 옮겨.",
        "M: 시간은 그대로고?",
        "W: 그대로야. 실험실 문 앞에서 기다리는 사람 없게 다 전화하는 중이야.",
        "M: 알려 줘서 고마워. 거기로 갈게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 출발할 시각을 고르시오.",
      lines: [
        ["M", "Haeun, what time does the volunteer work start on Saturday?"],
        ["W", "Ten o'clock at the community centre."],
        ["M", "How long does it take to get there?"],
        ["W", "Forty minutes on the bus, if the bus is on time."],
        ["M", "Then we should leave at twenty past nine."],
        ["W", "We also have to pick up the gloves from my house."],
        ["M", "How long is that?"],
        ["W", "Twenty minutes out of our way."],
        ["M", "Then let's leave at nine o'clock."],
        ["W", "Nine o'clock it is. I'll be at your gate."],
      ],
      choices: ["8:40 a.m.", "9:00 a.m.", "9:20 a.m.", "9:40 a.m.", "10:00 a.m."],
      answer: 2,
      clue: "Then let's leave at nine o'clock.",
      explanation:
        "10시 시작에 버스로 40분, 장갑을 가지러 20분이 더 들어서 두 사람은 9시에 출발하기로 한다. 따라서 답은 ②이다.",
      translation: [
        "M: 하은아, 토요일 봉사는 몇 시에 시작해?",
        "W: 주민센터에서 10시에.",
        "M: 거기까지 얼마나 걸려?",
        "W: 버스로 40분, 버스가 제때 오면.",
        "M: 그럼 9시 20분에 나가야겠네.",
        "W: 우리 집에서 장갑도 챙겨 가야 해.",
        "M: 그건 얼마나 걸리는데?",
        "W: 돌아가느라 20분.",
        "M: 그럼 9시에 나가자.",
        "W: 9시로 하자. 너희 집 앞으로 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, you've been staring at your phone for ten minutes."],
        ["W", "The results of the writing contest come out at four."],
        ["M", "It's five past four now."],
        ["W", "I know. The page hasn't loaded once."],
        ["M", "Everyone in the country is opening it at the same time."],
        ["W", "My hands are shaking and I haven't even seen anything yet."],
        ["M", "Do you want me to try on my phone?"],
        ["W", "Please. I can't look at it any more."],
      ],
      choices: ["nervous", "bored", "proud", "angry", "satisfied"],
      answer: 1,
      clue: "My hands are shaking and I haven't even seen anything yet.",
      explanation:
        "여자는 대회 결과를 기다리며 손이 떨린다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 10분째 휴대전화만 보고 있네.",
        "W: 글쓰기 대회 결과가 4시에 나와.",
        "M: 지금 4시 5분이야.",
        "W: 알아. 화면이 한 번도 안 열려.",
        "M: 전국에서 다 같이 열고 있으니까.",
        "W: 아직 아무것도 못 봤는데 손이 떨려.",
        "M: 내 휴대전화로 해 볼까?",
        "W: 그래 줘. 더는 못 보겠어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, could you take a photo of us?"],
        ["M", "Of course. Say cheese."],
        ["W", "How much is the entrance fee?"],
        ["M", "Five dollars for students."],
        ["W", "Do you have this in a larger size?"],
        ["M", "Let me check the back."],
        ["W", "Could you move your bag, please?"],
        ["M", "Sorry, I didn't notice."],
        ["W", "Which way is the exit?"],
        ["M", "Straight ahead and to the left."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Excuse me, could you take a photo of us?",
      explanation:
        "그림은 두 사람이 지나가는 사람에게 휴대전화를 내밀며 사진을 찍어 달라고 부탁하는 장면이므로 ①이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "One single scene in front of a large stone monument in a park, clean black line art on a plain white background, no writing or letters anywhere, all signboards blank. TWO teenage girls stand side by side; the nearer one holds a smartphone out at arm's length toward a MAN walking past, offering it to him, and both girls are smiling at him. The man has turned toward them and is reaching out to take the phone. The monument and trees are behind the two girls. Everyone is drawn fully inside the frame.",
      },
      translation: [
        "① W: 실례지만, 사진 좀 찍어 주시겠어요? / M: 그럼요. 자, 웃으세요.",
        "② W: 입장료가 얼마예요? / M: 학생은 5달러입니다.",
        "③ W: 이거 더 큰 치수 있나요? / M: 뒤에 가서 볼게요.",
        "④ W: 가방 좀 치워 주시겠어요? / M: 죄송해요, 못 봤네요.",
        "⑤ W: 출구가 어느 쪽이에요? / M: 곧장 가서 왼쪽이요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, are you going to the teachers' office this afternoon?"],
        ["W", "Yes, I have to hand in the club report."],
        ["M", "Could you do one thing for me while you're there?"],
        ["W", "What is it?"],
        ["M", "My gym shoes are under the bench in the corridor outside."],
        ["W", "Do you want me to bring them to you?"],
        ["M", "No, just put them in the lost-and-found box so they don't disappear."],
        ["W", "I can do that. Are they the grey ones?"],
        ["M", "Grey with a white sole. Thanks, I have a dentist appointment."],
        ["W", "No problem. I'll do it on my way in."],
      ],
      choices: [
        "신발을 가져다주기",
        "보고서를 대신 내 주기",
        "치과에 같이 가 주기",
        "신발을 분실물함에 넣어 주기",
        "신발을 빨아 주기",
      ],
      answer: 4,
      clue: "No, just put them in the lost-and-found box so they don't disappear.",
      explanation:
        "남자는 복도 의자 밑에 있는 운동화를 분실물함에 넣어 달라고 부탁한다. 따라서 답은 ④이다.",
      translation: [
        "M: 서연아, 오늘 오후에 교무실 가?",
        "W: 응, 동아리 보고서 내야 해.",
        "M: 가는 김에 하나만 부탁할게.",
        "W: 뭔데?",
        "M: 내 운동화가 복도 의자 밑에 있어.",
        "W: 가져다줄까?",
        "M: 아니, 없어지지 않게 분실물함에 넣어만 줘.",
        "W: 그건 할 수 있어. 회색 거야?",
        "M: 회색에 밑창이 하얀 거. 고마워, 나 치과 예약이 있어서.",
        "W: 그래. 들어가는 길에 넣어 둘게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Green Market Day에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Good morning, everyone. Here is news about Green Market Day."],
        ["W", "It will be held on the third Saturday of next month."],
        ["W", "The whole playground will be used, and the stalls open at ten."],
        ["W", "Bring books, clothes or toys you no longer use and sell them yourself."],
        ["W", "All the money we make will go to the animal shelter near the station."],
        ["W", "Come and see how much your old things are still worth."],
      ],
      choices: ["열리는 날", "장소", "가져올 물건", "모은 돈의 쓰임", "참가 신청 방법"],
      answer: 5,
      clue: "All the money we make will go to the animal shelter near the station.",
      explanation:
        "날짜(다음 달 셋째 토요일), 장소(운동장), 가져올 물건(책·옷·장난감), 모은 돈의 쓰임(동물 보호소)은 언급되지만 신청 방법은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여러분, 안녕하세요. Green Market Day 소식입니다.",
        "W: 다음 달 셋째 토요일에 열립니다.",
        "W: 운동장 전체를 쓰고, 가게는 10시에 엽니다.",
        "W: 이제 쓰지 않는 책, 옷, 장난감을 가져와 직접 파세요.",
        "W: 모은 돈은 모두 역 근처 동물 보호소에 보냅니다.",
        "W: 여러분의 낡은 물건이 아직 얼마나 값어치가 있는지 보러 오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "This is a thin band of paper or cloth with nothing written on it."],
        ["M", "You slide it between two pages and close the book on it."],
        ["M", "It does only one thing, and it does it for months at a time."],
        ["M", "Without it, people fold the corner of a page instead."],
        ["M", "You always have one until the moment you need it."],
      ],
      choices: ["책갈피", "지우개", "자", "포스트잇", "종이봉투"],
      answer: 1,
      clue: "You slide it between two pages and close the book on it.",
      explanation:
        "두 쪽 사이에 끼워 두고 책을 덮는 얇은 띠이며, 없으면 쪽 모서리를 접는다고 했으므로 책갈피이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이것은 아무것도 적혀 있지 않은 얇은 종이나 천 띠입니다.",
        "M: 두 쪽 사이에 끼워 넣고 그 위로 책을 덮습니다.",
        "M: 하는 일은 하나뿐인데, 그 일을 몇 달이고 합니다.",
        "M: 이것이 없으면 사람들은 대신 쪽 모서리를 접습니다.",
        "M: 필요한 바로 그 순간 전까지는 늘 하나쯤 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How was the concert last night?"],
        ["M", "Louder than I expected, but good."],
        ["W", "Could you turn the light on?"],
        ["M", "Sure, one second."],
        ["W", "Do you know when the results come out?"],
        ["M", "On Friday, I think."],
        ["W", "Why did you leave so early?"],
        ["M", "My bicycle is blue."],
        ["W", "Would you like some more soup?"],
        ["M", "Yes, please. It's very good."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why did you leave so early?",
      explanation:
        "왜 그렇게 일찍 갔느냐는 물음에 자전거가 파란색이라는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① W: 어젯밤 공연 어땠어? / M: 생각보다 시끄러웠는데 좋았어.",
        "② W: 불 좀 켜 줄래? / M: 그래, 잠깐만.",
        "③ W: 결과 언제 나오는지 알아? / M: 금요일일걸.",
        "④ W: 왜 그렇게 일찍 갔어? / M: 내 자전거는 파란색이야.",
        "⑤ W: 수프 더 줄까? / M: 응, 줘. 정말 맛있다.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, the school play starts in twenty minutes."],
        ["W", "Is everything ready backstage?"],
        ["M", "The costumes are laid out and the props are on the table."],
        ["W", "What about the lights? Did someone check them?"],
        ["M", "Junho tested them an hour ago. They're fine."],
        ["W", "Then the only thing left is the programme sheets."],
        ["M", "They're printed, but nobody has put them on the seats."],
        ["W", "I'll go and put them out now."],
        ["M", "Thanks. I'll get the actors lined up."],
      ],
      choices: ["의상 준비하기", "소품 챙기기", "조명 점검하기", "안내지 놓기", "배우 모으기"],
      answer: 4,
      clue: "I'll go and put them out now.",
      explanation:
        "의상·소품·조명은 이미 끝났고 남은 것은 좌석에 안내지를 놓는 일이므로 여자는 안내지를 놓으러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 예린아, 학교 연극이 20분 뒤에 시작해.",
        "W: 무대 뒤는 다 준비됐어?",
        "M: 의상은 꺼내 놨고 소품도 탁자에 있어.",
        "W: 조명은? 누가 확인했어?",
        "M: 준호가 한 시간 전에 다 켜 봤어. 괜찮아.",
        "W: 그럼 남은 건 안내지뿐이네.",
        "M: 인쇄는 됐는데 좌석에 놓은 사람이 없어.",
        "W: 내가 지금 가서 놓을게.",
        "M: 고마워. 나는 배우들 줄 세울게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 신청할 체험 활동을 고르시오.",
      lines: [
        ["W", "Minjun, here are the five weekend programmes."],
        ["M", "Let's look. I can't do anything that starts before nine."],
        ["W", "Then one is out — it begins at eight."],
        ["M", "What about the length? I have to be home by two."],
        ["W", "Two of them run until three, so those are gone as well."],
        ["M", "Two left. How much are they?"],
        ["W", "You said under twenty thousand won."],
        ["M", "Then one more drops out."],
        ["W", "So only one is left, and it's the pottery class."],
        ["M", "That suits me. Let's sign up together tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "So only one is left, and it's the pottery class.",
      explanation:
        "8시 시작인 ①, 3시까지인 ②와 ⑤, 25,000원인 ④를 빼면 ③만 남는다. 따라서 답은 ③이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "목공 / 8:00~12:00 / 15,000원" },
          { no: 2, label: "②", value: "제빵 / 10:00~15:00 / 18,000원" },
          { no: 3, label: "③", value: "도예 / 10:00~13:00 / 15,000원" },
          { no: 4, label: "④", value: "사진 / 9:30~13:00 / 25,000원" },
          { no: 5, label: "⑤", value: "텃밭 / 9:00~15:00 / 12,000원" },
        ],
      },
      translation: [
        "W: 민준아, 주말 프로그램이 이 다섯 개야.",
        "M: 보자. 9시 전에 시작하는 건 못 해.",
        "W: 그럼 하나 빠지네. 8시에 시작하는 거.",
        "M: 시간은? 나는 2시까지 집에 가야 해.",
        "W: 두 개가 3시까지라서 그것도 빠지고.",
        "M: 둘 남았네. 얼마야?",
        "W: 2만 원 아래라고 했잖아.",
        "M: 그럼 하나 더 빠지고.",
        "W: 그럼 하나만 남는데, 도예 수업이야.",
        "M: 나한테 딱 맞아. 오늘 밤에 같이 신청하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 전시회에 갈 날짜를 고르시오.",
      lines: [
        ["W", "Dohyun, when should we go to the photo exhibition?"],
        ["M", "It runs from the eleventh to the fifteenth."],
        ["M", "What kind of photos are they?"],
        ["W", "Street photos taken in the same town over thirty years."],
        ["M", "I'd like to see that. But I have a make-up class on the twelfth."],
        ["W", "Then the thirteenth, the fourteenth or the fifteenth."],
        ["M", "The thirteenth and the fourteenth are the school festival."],
        ["W", "You're right. We'd be there all day both days."],
        ["M", "So the last day is the only one left."],
        ["W", "Then let's go on the fifteenth. It opens at ten."],
      ],
      choices: ["11일", "12일", "13일", "14일", "15일"],
      answer: 5,
      clue: "Then let's go on the fifteenth. It opens at ten.",
      explanation:
        "12일은 보강, 13일과 14일은 학교 축제여서 15일만 남는다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 사진 전시회 언제 갈까?",
        "M: 11일부터 15일까지 해.",
        "M: 어떤 사진인데?",
        "W: 같은 동네를 30년 동안 찍은 거리 사진이래.",
        "M: 보고 싶다. 그런데 12일엔 보강 수업이 있어.",
        "W: 그럼 13일, 14일, 15일이네.",
        "M: 13일이랑 14일은 학교 축제잖아.",
        "W: 맞다. 이틀 다 하루 종일 거기 있겠네.",
        "M: 그럼 마지막 날만 남네.",
        "W: 그럼 15일에 가자. 10시에 문 열어.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, you look tired today."],
        ["W", "I spent yesterday moving my grandmother's books."],
        ["M", "Moving them where?"],
        ["W", "From the second floor down to the first. She can't use the stairs any more."],
        ["M", "How many books are we talking about?"],
        ["W", "Around four hundred. We carried them ten at a time."],
        ["M", "That's forty trips down a staircase."],
        ["W", "My father counted. It was forty-three."],
        ["M", "And did you finish?"],
        ["W", "Everything except the shelf itself. That comes down on Sunday."],
      ],
      choices: ["책 옮기기", "책 정리하기", "책 사러 가기", "계단 청소하기", "책장 만들기"],
      answer: 1,
      clue: "I spent yesterday moving my grandmother's books.",
      explanation:
        "여자는 어제 할머니 책을 2층에서 1층으로 옮겼다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 오늘 피곤해 보인다.",
        "W: 어제 할머니 책을 옮기느라 하루를 다 썼어.",
        "M: 어디로 옮겼는데?",
        "W: 2층에서 1층으로. 이제 계단을 못 쓰시거든.",
        "M: 책이 몇 권이나 되는데?",
        "W: 사백 권쯤. 열 권씩 들고 날랐어.",
        "M: 그럼 계단을 마흔 번 내려간 거네.",
        "W: 아빠가 셌어. 마흔세 번이었대.",
        "M: 그래서 다 끝냈어?",
        "W: 책장만 빼고 다. 그건 일요일에 내려.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good afternoon, students. This is the school library."],
        ["M", "Twenty-three books borrowed last term have still not come back."],
        ["M", "Several of them are the only copies we have."],
        ["M", "If you have one at home, bring it back this week."],
        ["M", "No late fee will be charged until Friday."],
        ["M", "After that, the usual fee starts again."],
      ],
      choices: [
        "새 책이 들어왔다고 알리려고",
        "빌린 책을 돌려 달라고 하려고",
        "도서관 이용 시간을 알리려고",
        "독서 행사를 안내하려고",
        "연체료를 올린다고 알리려고",
      ],
      answer: 2,
      clue: "If you have one at home, bring it back this week.",
      explanation:
        "지난 학기에 빌려 간 책이 아직 돌아오지 않았으니 이번 주에 반납하라는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 도서관입니다.",
        "M: 지난 학기에 빌려 간 책 스물세 권이 아직 돌아오지 않았습니다.",
        "M: 그중 몇 권은 우리 도서관에 한 권뿐인 책입니다.",
        "M: 집에 가지고 있다면 이번 주에 가져다주세요.",
        "M: 금요일까지는 연체료를 받지 않습니다.",
        "M: 그 뒤로는 다시 원래대로 받습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the flower shop. What can I get you?"],
        ["M", "Five roses, please."],
        ["W", "Roses are three dollars each."],
        ["M", "So fifteen dollars for five."],
        ["W", "That's right. Would you like them wrapped?"],
        ["M", "Yes, please. How much is the wrapping?"],
        ["W", "Five dollars for the paper and ribbon."],
        ["M", "Then twenty dollars in total."],
        ["W", "And members get ten percent off the flowers, not the wrapping."],
        ["M", "I'm a member. Here's my card."],
      ],
      choices: ["$15.50", "$17.00", "$18.50", "$20.00", "$21.50"],
      answer: 3,
      clue: "And members get ten percent off the flowers, not the wrapping.",
      explanation:
        "장미 5송이는 15달러이고 여기서 10%를 빼면 13.5달러, 포장 5달러를 더하면 18.5달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 꽃집입니다. 무엇을 드릴까요?",
        "M: 장미 다섯 송이 주세요.",
        "W: 장미는 한 송이에 3달러입니다.",
        "M: 그럼 다섯 송이에 15달러네요.",
        "W: 맞습니다. 포장해 드릴까요?",
        "M: 네. 포장은 얼마예요?",
        "W: 종이와 리본 해서 5달러입니다.",
        "M: 그럼 모두 20달러군요.",
        "W: 그리고 회원은 꽃값에서 10%를 빼 드립니다. 포장은 빼고요.",
        "M: 저 회원이에요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Jiwon, you've rewritten the opening of your essay four times."],
        ["M", "I can't get the first sentence right, so I keep going back."],
        ["W", "And how much of the rest have you written?"],
        ["M", "Nothing. I haven't got past the first paragraph."],
        ["W", "The essay is due on Thursday."],
        ["M", "I know. But a weak opening ruins the whole thing."],
        ["W", "A missing essay ruins it more."],
        ["M", "That's fair."],
        ["W", "Write the middle first and come back to the opening at the end."],
      ],
      choices: [
        "My essay is about city traffic.",
        "I'll leave the opening and start the middle tonight.",
        "The teacher gave us two weeks.",
        "I write better in the morning.",
        "You should rewrite yours too.",
      ],
      answer: 2,
      clue: "Write the middle first and come back to the opening at the end.",
      explanation:
        "가운데부터 쓰고 서두는 나중에 손보라는 조언을 들었으므로, 오늘 밤 가운데부터 쓰겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 지원아, 글 첫머리를 네 번이나 다시 썼네.",
        "M: 첫 문장이 마음에 안 들어서 자꾸 돌아가게 돼.",
        "W: 그럼 나머지는 얼마나 썼는데?",
        "M: 하나도. 첫 문단을 못 넘겼어.",
        "W: 과제는 목요일까지잖아.",
        "M: 알아. 그런데 첫머리가 약하면 글 전체가 망가져.",
        "W: 글이 아예 없는 게 더 망가지는 거지.",
        "M: 그건 맞네.",
        "W: 가운데부터 쓰고 서두는 마지막에 다시 와서 손봐.",
        "M: 첫머리는 놔두고 오늘 밤에 가운데부터 쓸게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Haeun, how is the English vocabulary going?"],
        ["W", "Not well. I learn thirty words a night and forget most of them."],
        ["M", "Thirty is a lot. How do you study them?"],
        ["W", "I read the list from the top to the bottom, three times."],
        ["M", "And the next day, which words do you remember?"],
        ["W", "The first five and the last two, usually."],
        ["M", "So you remember the ends of the list, not the words."],
        ["W", "I hadn't noticed that, but you're right."],
        ["M", "Split the thirty into three groups of ten and shuffle the order each time."],
      ],
      choices: [
        "My vocabulary book has two thousand words.",
        "I study English for an hour every night.",
        "Then I'll split tonight's list into three.",
        "The test is on the first Monday.",
        "You should try thirty words as well.",
      ],
      answer: 3,
      clue: "Split the thirty into three groups of ten and shuffle the order each time.",
      explanation:
        "서른 개를 열 개씩 세 묶음으로 나누고 순서를 섞으라는 조언을 들었으므로, 오늘 목록을 셋으로 나누겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 하은아, 영어 단어는 잘돼 가?",
        "W: 잘 안돼. 저녁마다 서른 개씩 외우는데 대부분 잊어버려.",
        "M: 서른 개는 많다. 어떻게 외우는데?",
        "W: 목록을 위에서 아래로 세 번 읽어.",
        "M: 그럼 다음 날 어떤 단어가 기억나?",
        "W: 보통 처음 다섯 개랑 마지막 두 개.",
        "M: 그럼 단어가 아니라 목록의 양 끝을 기억하는 거네.",
        "W: 생각 못 했는데 맞는 말이야.",
        "M: 서른 개를 열 개씩 세 묶음으로 나누고 순서도 매번 섞어 봐.",
        "W: 그럼 오늘 목록부터 셋으로 나눌게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minjun, how did the group project go?"],
        ["M", "Badly. I ended up doing almost all of it myself."],
        ["W", "Didn't you divide the work at the start?"],
        ["M", "We said we'd all 'help with the research'."],
        ["W", "That isn't dividing the work. That's four people watching each other."],
        ["M", "Everyone thought somebody else had started."],
        ["W", "And nobody had a part with their own name on it."],
        ["M", "No. We only had one big job and four names."],
        ["W", "Next time write down who does what by when."],
      ],
      choices: [
        "Our group had four people.",
        "The project was about recycling.",
        "I'll write out the parts before we start next time.",
        "We got a good grade in the end.",
        "You should join our group.",
      ],
      answer: 3,
      clue: "Next time write down who does what by when.",
      explanation:
        "누가 무엇을 언제까지 하는지 적어 두라는 조언을 들었으므로, 다음에는 시작 전에 맡을 부분을 적겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 민준아, 모둠 과제는 어떻게 됐어?",
        "M: 망했어. 거의 다 내가 혼자 했어.",
        "W: 처음에 일을 안 나눴어?",
        "M: 다 같이 '자료 조사를 돕자'고 했지.",
        "W: 그건 일을 나눈 게 아니야. 네 명이 서로 쳐다본 거지.",
        "M: 다들 누가 이미 시작했겠거니 했어.",
        "W: 그리고 자기 이름이 붙은 부분이 아무한테도 없었고.",
        "M: 응. 큰 일 하나에 이름만 넷이었어.",
        "W: 다음엔 누가 무엇을 언제까지 하는지 적어 둬.",
        "M: 다음엔 시작하기 전에 맡을 부분을 적어 놓을게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiwon이 Seoyeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Jiwon : ________________",
      lines: [
        ["W", "Jiwon and Seoyeon are preparing a science presentation together."],
        ["W", "Seoyeon has made twenty-eight slides full of careful information."],
        ["W", "Every slide is accurate and well organised."],
        ["W", "However, they are only allowed six minutes to present."],
        ["W", "At that speed they would have about twelve seconds a slide."],
        ["W", "Jiwon does not want to say that her work was wasted."],
        ["W", "He wants to suggest keeping the eight strongest slides."],
        ["W", "The rest could be printed as a handout for the class."],
        ["W", "In this situation, what would Jiwon most likely say to Seoyeon?"],
      ],
      choices: [
        "Let's ask for more time.",
        "Could we show eight slides and print the rest?",
        "You should make more slides.",
        "I'll present the whole thing myself.",
        "Let's do the presentation next week.",
      ],
      answer: 2,
      clue: "He wants to suggest keeping the eight strongest slides.",
      explanation:
        "지원이는 서연이가 한 일을 깎아내리지 않으면서, 여덟 장만 보여 주고 나머지는 유인물로 내자고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 지원이와 서연이는 과학 발표를 함께 준비하고 있습니다.",
        "W: 서연이는 꼼꼼한 내용으로 스물여덟 장을 만들었습니다.",
        "W: 모든 장이 정확하고 잘 정리되어 있습니다.",
        "W: 그런데 발표 시간은 6분뿐입니다.",
        "W: 그 속도라면 한 장에 12초쯤 됩니다.",
        "W: 지원이는 서연이가 한 일이 헛수고라고 말하고 싶지는 않습니다.",
        "W: 다만 가장 좋은 여덟 장만 남기자고 제안하고 싶습니다.",
        "W: 나머지는 반 아이들에게 유인물로 나눠 줄 수 있습니다.",
        "W: 이런 상황에서 지원이가 서연이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
