/** 중3 듣기 49회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 49회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 고를 독서대를 고르시오.",
      lines: [
        ["W", "Minseok, are you buying a book stand?"],
        ["M", "My neck hurts from looking down all evening."],
        ["W", "This one folds flat when you put it away."],
        ["M", "Folding is good, but I need the page clips."],
        ["W", "Two clips to hold the pages open?"],
        ["M", "Yes, one clip on each side."],
        ["W", "Do you want the little drawer underneath?"],
        ["M", "No drawer. It makes the stand too tall."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Yes, one clip on each side. / No drawer. It makes the stand too tall.",
      explanation:
        "접히는 독서대에 양쪽 집게가 있고 아래 서랍은 없는 것이다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five reading book stands side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a FOLDING stand with NO page clips and NO drawer. " +
          "② a FOLDING stand with TWO page CLIPS on both sides and a small DRAWER underneath. " +
          "③ a FOLDING stand with TWO page CLIPS on both sides and NO drawer. " +
          "④ a fixed SOLID stand with TWO page CLIPS and no drawer. " +
          "⑤ a FOLDING stand with only ONE page CLIP on the left side and a DRAWER underneath.",
      },
      translation: [
        "W: 민석아, 독서대 사는 거야?",
        "M: 저녁 내내 고개를 숙이니까 목이 아파.",
        "W: 이건 치울 때 납작하게 접혀.",
        "M: 접히는 건 좋은데 쪽을 잡아 주는 집게가 있어야 해.",
        "W: 쪽을 벌려 주는 집게 두 개?",
        "M: 응, 양쪽에 하나씩.",
        "W: 아래에 작은 서랍도 있는 걸로 할래?",
        "M: 서랍은 안 돼. 독서대가 너무 높아져.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 겨울 방학 영어 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junho, are you going to the winter English camp?"],
        ["M", "I signed up yesterday. Where is it held?"],
        ["W", "At the youth center near the city hall."],
        ["M", "How many days does it last?"],
        ["W", "Five days, from Monday to Friday."],
        ["M", "What do we do all day there?"],
        ["W", "Speaking games in the morning and drama in the afternoon."],
        ["M", "Do we need to bring anything?"],
        ["W", "A notebook, a pen and your lunch."],
      ],
      choices: ["열리는 곳", "진행 기간", "하는 활동", "가져갈 것", "참가 인원"],
      answer: 5,
      clue: "At the youth center near the city hall.",
      explanation:
        "장소, 기간, 활동, 준비물은 말했지만 참가 인원은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준호야, 겨울 영어 캠프 갈 거야?",
        "M: 어제 신청했어. 어디서 해?",
        "W: 시청 근처 청소년 센터에서.",
        "M: 며칠 동안 해?",
        "W: 월요일부터 금요일까지 닷새.",
        "M: 하루 종일 뭘 해?",
        "W: 오전에는 말하기 놀이, 오후에는 연극.",
        "M: 가져갈 게 있어?",
        "W: 공책, 펜, 그리고 점심.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Come in, Chaewon. Is everything all right?"],
        ["W", "I wanted to talk before the deadline."],
        ["M", "Is this about the volunteer certificate?"],
        ["W", "It's about the hours I did in October."],
        ["M", "You worked at the children's center, didn't you?"],
        ["W", "Every Saturday, four hours each time."],
        ["M", "And the record shows something different?"],
        ["W", "Only two Saturdays are written on my sheet."],
        ["M", "The center may not have sent everything."],
        ["W", "I came to ask you to check my volunteer hours."],
      ],
      choices: [
        "봉사 시간을 확인해 달라고 하려고",
        "봉사를 신청하려고",
        "결석을 알리려고",
        "상담을 받으려고",
        "증명서를 받으려고",
      ],
      answer: 1,
      clue: "I came to ask you to check my volunteer hours.",
      explanation:
        "여자는 봉사 시간이 맞는지 확인해 달라고 찾아왔다. 따라서 답은 ①이다.",
      translation: [
        "M: 들어와, 채원아. 별일 없니?",
        "W: 마감 전에 말씀드리고 싶었어요.",
        "M: 봉사 확인서 때문이니?",
        "W: 10월에 한 시간 때문이에요.",
        "M: 아동 센터에서 했지?",
        "W: 토요일마다 네 시간씩이요.",
        "M: 기록에는 다르게 돼 있니?",
        "W: 제 기록지에는 토요일 두 번만 적혀 있어요.",
        "M: 센터에서 다 보내지 않았을 수도 있겠구나.",
        "W: 제 봉사 시간을 확인해 주십사 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["M", "Yerin, when should we meet to make the poster?"],
        ["W", "The art room opens at three on Saturday."],
        ["M", "My piano lesson ends at three fifteen."],
        ["W", "Then three o'clock is too early for you."],
        ["M", "It takes me ten minutes to walk over."],
        ["W", "So you'd get there around three thirty."],
        ["M", "Let's just meet at three thirty."],
        ["W", "Three thirty in the art room."],
        ["M", "I'll bring the paper and the paint."],
      ],
      choices: ["2:30 p.m.", "3:00 p.m.", "3:15 p.m.", "3:30 p.m.", "4:00 p.m."],
      answer: 4,
      clue: "Let's just meet at three thirty.",
      explanation:
        "피아노 수업과 걷는 시간을 감안해 3시 30분에 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 예린아, 포스터 만들러 언제 만날까?",
        "W: 토요일에 미술실이 세 시에 열어.",
        "M: 내 피아노 수업이 세 시 15분에 끝나.",
        "W: 그럼 세 시는 너한테 이르네.",
        "M: 걸어가는 데 10분 걸려.",
        "W: 그럼 세 시 반쯤 도착하겠다.",
        "M: 그냥 세 시 반에 만나자.",
        "W: 세 시 반에 미술실에서.",
        "M: 종이랑 물감은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seongho, you've been quiet since the bell rang."],
        ["M", "I lost the notebook with all my exam notes."],
        ["W", "The thick one with the blue cover?"],
        ["M", "Six months of writing is in that notebook."],
        ["W", "Where did you have it last?"],
        ["M", "In the study room, before dinner yesterday."],
        ["W", "Did you ask at the front desk?"],
        ["M", "Nobody has turned it in since then."],
      ],
      choices: ["excited", "upset", "proud", "bored", "satisfied"],
      answer: 2,
      clue: "Nobody has turned it in since then.",
      explanation:
        "반년 치 필기가 든 공책을 잃어버려 속상해하고 있다. 따라서 답은 ②이다.",
      translation: [
        "W: 성호야, 종 친 뒤로 계속 조용하네.",
        "M: 시험 필기가 다 있는 공책을 잃어버렸어.",
        "W: 파란 표지에 두꺼운 그거?",
        "M: 반년 치 필기가 그 공책에 있어.",
        "W: 마지막으로 어디서 봤어?",
        "M: 어제 저녁 먹기 전에 열람실에서.",
        "W: 안내대에 물어봤어?",
        "M: 그 뒤로 아무도 갖다주지 않았대.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Is this the line for the exam room?"],
        ["W", "Yes, please wait here."],
        ["ANN", "Number two."],
        ["M", "May I borrow an eraser?"],
        ["W", "Here, use mine."],
        ["ANN", "Number three."],
        ["M", "I think you dropped your student card."],
        ["W", "Oh, thank you very much."],
        ["ANN", "Number four."],
        ["M", "How many pages is the test?"],
        ["W", "Eight in total."],
        ["ANN", "Number five."],
        ["M", "Where do I put my bag?"],
        ["W", "At the back of the room."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "I think you dropped your student card.",
      explanation:
        "그림은 바닥에 떨어진 학생증을 주워 건네는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "In a school hallway outside an exam room, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy bends down and picks up a small blank card from the floor, holding it out toward a girl. " +
          "The girl turns back with a surprised expression and reaches for the card with both hands. " +
          "A queue of waiting students and a closed door are drawn simply behind them.",
      },
      translation: [
        "① M: 시험장 줄이 여기예요? / W: 네, 여기서 기다리세요.",
        "② M: 지우개 좀 빌려도 돼? / W: 여기, 내 거 써.",
        "③ M: 학생증 떨어뜨리신 것 같아요. / W: 아, 정말 고맙습니다.",
        "④ M: 시험지가 몇 쪽이에요? / W: 모두 여덟 쪽이요.",
        "⑤ M: 가방은 어디에 둬요? / W: 교실 뒤쪽에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, you finished the graduation speech last week."],
        ["W", "The teacher chose mine out of eleven."],
        ["M", "I'm writing the one for the club farewell."],
        ["W", "How long does it have to be?"],
        ["M", "About three minutes, and I've written five."],
        ["W", "Cutting is harder than writing."],
        ["M", "Every part feels necessary to me."],
        ["W", "A second reader always sees what to drop."],
        ["M", "Could you read it and mark what to cut?"],
        ["W", "Send it tonight and I'll mark it by morning."],
      ],
      choices: [
        "원고를 읽고 줄일 곳을 표시해 주기",
        "원고를 써 주기",
        "대신 발표해 주기",
        "연습을 들어 주기",
        "자료를 찾아 주기",
      ],
      answer: 1,
      clue: "Could you read it and mark what to cut?",
      explanation:
        "남자는 원고를 읽고 줄일 곳을 표시해 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 다혜야, 지난주에 졸업 연설문 다 썼잖아.",
        "W: 열한 편 중에 선생님이 내 걸 고르셨어.",
        "M: 나는 동아리 송별 연설문을 쓰고 있어.",
        "W: 길이가 얼마나 돼야 해?",
        "M: 3분쯤인데 5분 분량을 썼어.",
        "W: 줄이는 게 쓰는 것보다 어려워.",
        "M: 나한테는 다 필요해 보여.",
        "W: 다른 사람이 읽으면 뺄 데가 늘 보여.",
        "M: 읽어 보고 줄일 데 좀 표시해 줄 수 있어?",
        "W: 오늘 밤에 보내 줘. 아침까지 표시해 놓을게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 악기 대여에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The music room lends instruments this term. " +
            "Guitars, flutes and small drums are available. " +
            "You may keep one instrument for four weeks. " +
            "Come to the music room during lunch to borrow one. " +
            "Return it in the same case you received. " +
            "Damaged instruments must be reported right away.",
        ],
      ],
      choices: ["빌릴 수 있는 악기", "빌리는 기간", "빌리러 가는 때", "반납할 때 지킬 것", "빌릴 수 있는 학년"],
      answer: 5,
      clue: "Guitars, flutes and small drums are available.",
      explanation:
        "악기, 기간, 시간, 반납 방법은 말했지만 학년은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 이번 학기에 음악실에서 악기를 빌려 드립니다. 기타, 플루트, 작은 북이 있습니다. 악기 하나를 4주 동안 쓸 수 있습니다. 빌리려면 점심시간에 음악실로 오세요. 받은 그 가방에 넣어 돌려주세요. 망가진 악기는 바로 알려 주셔야 합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This holds your money and your cards in one place. " +
            "It folds in half and fits in a back pocket. " +
            "Losing it means calling the bank right away. " +
            "Many people keep a photograph inside it. " +
            "A thin one is easier to carry than a thick one.",
        ],
      ],
      choices: ["가방", "지갑", "필통", "수첩", "상자"],
      answer: 2,
      clue: "This holds your money and your cards in one place.",
      explanation:
        "돈과 카드를 넣고 반으로 접어 주머니에 넣는 것은 지갑이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 돈과 카드를 한곳에 담습니다. 반으로 접혀 뒷주머니에 들어갑니다. 잃어버리면 바로 은행에 전화해야 합니다. 많은 사람이 안에 사진을 한 장 넣어 둡니다. 두꺼운 것보다 얇은 것이 들고 다니기 편합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Have you packed for the trip?"],
        ["M", "Almost, just my toothbrush left."],
        ["ANN", "Number two."],
        ["W", "Could you turn the fan on?"],
        ["M", "Sure, it's warm in here."],
        ["ANN", "Number three."],
        ["W", "Which bus goes to the station?"],
        ["M", "I finished my homework already."],
        ["ANN", "Number four."],
        ["W", "Do you want to share this umbrella?"],
        ["M", "Yes, thanks. It's pouring."],
        ["ANN", "Number five."],
        ["W", "What did you think of the film?"],
        ["M", "The ending surprised me."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Which bus goes to the station?",
      explanation:
        "어느 버스가 역에 가는지 묻는 말에 숙제 얘기를 했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① W: 여행 짐 쌌어? / M: 거의. 칫솔만 남았어.",
        "② W: 선풍기 좀 켜 줄래? / M: 그래, 여기 덥다.",
        "③ W: 어느 버스가 역에 가? / M: 나 숙제 벌써 다 했어.",
        "④ W: 이 우산 같이 쓸래? / M: 응, 고마워. 비가 쏟아지네.",
        "⑤ W: 그 영화 어땠어? / M: 끝이 놀라웠어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suyeon, the farewell party starts in fifteen minutes."],
        ["W", "The desks are pushed back and the floor is clear."],
        ["M", "Did anyone bring the paper cups?"],
        ["W", "They're still in the box in the club room."],
        ["M", "Twenty-five people can't share three cups."],
        ["W", "I'll be back in five minutes."],
        ["M", "I'll hang the letters on the board meanwhile."],
        ["W", "I'll go and get the paper cups."],
      ],
      choices: [
        "책상을 옮기기",
        "편지를 걸기",
        "종이컵을 가져오기",
        "손님을 맞이하기",
        "바닥을 쓸기",
      ],
      answer: 3,
      clue: "I'll go and get the paper cups.",
      explanation:
        "여자는 동아리방에 있는 종이컵을 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수연아, 송별회가 15분 뒤에 시작해.",
        "W: 책상은 뒤로 밀었고 바닥도 치웠어.",
        "M: 종이컵은 누가 가져왔어?",
        "W: 아직 동아리방 상자에 있어.",
        "M: 스물다섯 명이 컵 세 개로는 안 되지.",
        "W: 5분이면 다녀와.",
        "M: 그동안 나는 게시판에 편지를 걸게.",
        "W: 내가 가서 종이컵을 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 학습 프로그램을 고르시오.",
      lines: [
        ["W", "Taemin, which program should we take before high school?"],
        ["M", "Five programs are open at the center."],
        ["W", "We can only go on weekday evenings."],
        ["M", "So the weekend ones are out."],
        ["W", "It should also be eight weeks or shorter."],
        ["M", "One of them runs for twelve weeks."],
        ["W", "And the fee has to be under sixty thousand won."],
        ["M", "Then only one program fits everything."],
        ["W", "I'll sign us both up tomorrow."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "We can only go on weekday evenings.",
      explanation:
        "평일 저녁, 8주 이내, 6만 원 미만인 프로그램은 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Weekend / Weeks: 6 / Fee: 50,000 won" },
          { no: 2, label: "②", value: "Day: Weekday / Weeks: 12 / Fee: 45,000 won" },
          { no: 3, label: "③", value: "Day: Weekend / Weeks: 8 / Fee: 55,000 won" },
          { no: 4, label: "④", value: "Day: Weekday / Weeks: 8 / Fee: 58,000 won" },
          { no: 5, label: "⑤", value: "Day: Weekday / Weeks: 6 / Fee: 70,000 won" },
        ],
      },
      translation: [
        "W: 태민아, 고등학교 가기 전에 어떤 프로그램 들을까?",
        "M: 센터에 다섯 개가 열려 있어.",
        "W: 우리는 평일 저녁에만 갈 수 있어.",
        "M: 그럼 주말 것은 빠지네.",
        "W: 기간도 8주 이내여야 해.",
        "M: 하나는 12주짜리야.",
        "W: 그리고 수강료는 6만 원 미만이어야 해.",
        "M: 그럼 다 맞는 건 하나뿐이야.",
        "W: 내일 둘 다 신청해 둘게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 여행을 갈 날짜를 고르시오.",
      lines: [
        ["M", "Areum, when should we go to Gangneung?"],
        ["W", "The train has seats on three days this month."],
        ["M", "Which days are still open?"],
        ["W", "The fifth, the twelfth and the nineteenth."],
        ["M", "The fifth is the day of the graduation ceremony."],
        ["W", "We can't leave town that morning."],
        ["M", "And the nineteenth is my cousin's wedding."],
        ["W", "Then the twelfth is the only day left."],
        ["M", "The first train leaves at six thirty."],
        ["W", "I'll book two seats for the twelfth."],
      ],
      choices: ["the 5th", "the 12th", "the 19th", "the 9th", "the 22nd"],
      answer: 2,
      clue: "Then the twelfth is the only day left.",
      explanation:
        "5일은 졸업식, 19일은 결혼식이어서 12일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "M: 아름아, 강릉에 언제 갈까?",
        "W: 이번 달에 기차 자리가 사흘 남았어.",
        "M: 어떤 날이 남았어?",
        "W: 5일, 12일, 19일.",
        "M: 5일은 졸업식 날이야.",
        "W: 그날 아침에는 못 떠나지.",
        "M: 19일은 사촌 결혼식이고.",
        "W: 그럼 남는 날은 12일뿐이네.",
        "M: 첫 기차가 여섯 시 반에 떠나.",
        "W: 12일 자리 두 개 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Bora, you weren't in the study room yesterday."],
        ["W", "I was at the animal shelter with my sister."],
        ["M", "Did you go there to adopt a dog?"],
        ["W", "No, we went to help for the afternoon."],
        ["M", "What did they have you do?"],
        ["W", "We washed blankets and refilled the water bowls."],
        ["M", "How many animals are there now?"],
        ["W", "Twenty dogs and about ten cats."],
        ["M", "Will you go back again?"],
        ["W", "Every second Saturday from now on."],
      ],
      choices: [
        "강아지를 입양했다",
        "공부방에 갔다",
        "언니를 만났다",
        "동물 보호소에서 도왔다",
        "집에서 쉬었다",
      ],
      answer: 4,
      clue: "I was at the animal shelter with my sister.",
      explanation:
        "여자는 어제 언니와 동물 보호소에서 일을 도왔다. 따라서 답은 ④이다.",
      translation: [
        "M: 보라야, 어제 열람실에 없더라.",
        "W: 언니랑 동물 보호소에 있었어.",
        "M: 강아지 입양하러 갔어?",
        "W: 아니, 오후 동안 돕겠다고 갔어.",
        "M: 무슨 일을 시키셨어?",
        "W: 담요를 빨고 물그릇을 채웠어.",
        "M: 지금 동물이 몇 마리 있어?",
        "W: 개 스무 마리에 고양이 열 마리쯤.",
        "M: 또 갈 거야?",
        "W: 이제부터 격주 토요일마다.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the student council room. " +
            "We are collecting warm clothes for the shelter downtown. " +
            "Coats, scarves and gloves are all welcome. " +
            "Everything should be clean and without holes. " +
            "Bring your items to the box in the front hall. " +
            "We collect until Friday afternoon this week. " +
            "Thank you for sharing what you no longer need.",
        ],
      ],
      choices: [
        "겨울옷 모으기를 알리려고",
        "행사를 미루려고",
        "분실물을 찾으려고",
        "봉사자를 모으려고",
        "청소를 부탁하려고",
      ],
      answer: 1,
      clue: "We are collecting warm clothes for the shelter downtown.",
      explanation:
        "쉼터에 보낼 겨울옷을 모은다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 학생회실입니다. 시내 쉼터에 보낼 따뜻한 옷을 모으고 있습니다. 외투, 목도리, 장갑 모두 좋습니다. 깨끗하고 구멍이 없어야 합니다. 중앙 현관 상자에 넣어 주세요. 이번 주 금요일 오후까지 모읍니다. 더 필요하지 않은 것을 나눠 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What would you like to buy today?"],
        ["M", "Three T-shirts and two caps, please."],
        ["W", "T-shirts are eight dollars each this week."],
        ["M", "Were they more expensive before?"],
        ["W", "Ten dollars until last Friday."],
        ["M", "And how much are the caps?"],
        ["W", "Five dollars for each cap."],
        ["M", "Is there a charge for the bag?"],
        ["W", "No, the bag is included."],
        ["M", "All right. Here is my card."],
      ],
      choices: ["$30", "$32", "$34", "$36", "$38"],
      answer: 3,
      clue: "T-shirts are eight dollars each this week.",
      explanation:
        "티셔츠 세 장 24달러와 모자 두 개 10달러를 더하면 34달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 오늘은 뭘 사시겠어요?",
        "M: 티셔츠 세 장이랑 모자 두 개 주세요.",
        "W: 이번 주 티셔츠는 한 장에 8달러입니다.",
        "M: 전에는 더 비쌌나요?",
        "W: 지난 금요일까지는 10달러였습니다.",
        "M: 모자는 얼마예요?",
        "W: 하나에 5달러입니다.",
        "M: 봉투 값도 내야 하나요?",
        "W: 아니요, 봉투는 포함입니다.",
        "M: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Kiyoung, you never seem to forget an assignment."],
        ["M", "I write everything in one small notebook."],
        ["W", "Not in your phone?"],
        ["M", "The phone shows me ten other things first."],
        ["W", "That's true. I open it and lose twenty minutes."],
        ["M", "The notebook only shows what I wrote."],
        ["W", "Do you carry it everywhere?"],
        ["M", "It lives in the front pocket of my bag."],
        ["W", "What do I write in it first?"],
      ],
      choices: [
        "Write nothing at all.",
        "Copy your whole timetable.",
        "Every phone number you know.",
        "Today's date and one task.",
        "Wait until next term.",
      ],
      answer: 4,
      clue: "What do I write in it first?",
      explanation:
        "무엇부터 적을지 물었으므로, 오늘 날짜와 할 일 하나라는 ④가 가장 자연스럽다.",
      translation: [
        "W: 기영아, 너는 과제를 잊는 법이 없네.",
        "M: 작은 공책 하나에 다 적어.",
        "W: 휴대폰에 안 적고?",
        "M: 휴대폰은 다른 열 가지를 먼저 보여 줘.",
        "W: 맞아. 열었다가 20분을 날려.",
        "M: 공책은 내가 쓴 것만 보여 줘.",
        "W: 어디든 가지고 다녀?",
        "M: 가방 앞주머니에 늘 있어.",
        "W: 거기에 뭐부터 적어?",
        "M: 오늘 날짜랑 할 일 하나.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayeon, I heard you make your own bread at home."],
        ["W", "My grandmother taught me the summer before last."],
        ["M", "How long does one loaf take?"],
        ["W", "Almost four hours, but most of it is waiting."],
        ["M", "What is the hardest part?"],
        ["W", "Knowing when the dough has risen enough."],
        ["M", "How do you tell?"],
        ["W", "I press it with one finger and watch it come back."],
        ["M", "How often do you bake?"],
        ["W", "Every Sunday morning since March."],
        ["M", "Could you teach me how to start?"],
      ],
      choices: [
        "Sure, come over on Sunday.",
        "I never bake anything.",
        "You can't make bread.",
        "The oven is broken.",
        "I stopped baking last year.",
      ],
      answer: 1,
      clue: "Could you teach me how to start?",
      explanation:
        "어떻게 시작하는지 가르쳐 달라고 했으므로, 일요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 나연아, 집에서 빵을 직접 만든다며.",
        "W: 재작년 여름에 할머니가 가르쳐 주셨어.",
        "M: 한 덩이 만드는 데 얼마나 걸려?",
        "W: 거의 네 시간인데 대부분은 기다리는 시간이야.",
        "M: 제일 어려운 게 뭐야?",
        "W: 반죽이 충분히 부풀었는지 아는 거.",
        "M: 어떻게 알아?",
        "W: 손가락으로 눌러 보고 되돌아오는 걸 봐.",
        "M: 얼마나 자주 구워?",
        "W: 3월부터 일요일 아침마다.",
        "M: 나한테도 어떻게 시작하는지 가르쳐 줄래?",
        "W: 그럼, 일요일에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunbin, how is the club yearbook page coming along?"],
        ["W", "You said it goes to the printer on Friday."],
        ["M", "The photos are in, but the page looks crowded."],
        ["W", "How many photos did you put on it?"],
        ["M", "Twenty-two, one for every member."],
        ["W", "On a single page that's very small."],
        ["M", "I didn't want anyone to be left out."],
        ["W", "You can keep everyone and use two pages."],
        ["M", "The teacher did offer us a second page."],
        ["W", "Why don't you spread them over two pages?"],
      ],
      choices: [
        "I'll redo it tonight.",
        "There are no photos.",
        "I'll use half a page.",
        "Nobody will see it.",
        "I deleted the page.",
      ],
      answer: 1,
      clue: "Why don't you spread them over two pages?",
      explanation:
        "두 쪽에 나누어 배치하라는 제안이므로, 오늘 밤에 다시 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 현빈아, 동아리 앨범 쪽은 잘돼 가?",
        "W: 금요일에 인쇄소로 넘긴다고 했잖아.",
        "M: 사진은 다 넣었는데 쪽이 빽빽해 보여.",
        "W: 사진을 몇 장 넣었어?",
        "M: 스물두 장, 회원마다 한 장씩.",
        "W: 한 쪽에 넣기에는 너무 작겠다.",
        "M: 누구도 빠뜨리고 싶지 않았어.",
        "W: 다 넣으면서 두 쪽을 써도 돼.",
        "M: 선생님이 한 쪽 더 주신다고 하시긴 했어.",
        "W: 두 쪽에 나눠 넣는 건 어때?",
        "M: 오늘 밤에 다시 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Sangmin이 Jiwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Sangmin : ________________",
      lines: [
        [
          "M",
          "Sangmin and Jiwoo are leaving the classroom after the club meeting. " +
            "Jiwoo is about to walk out with the window still wide open. " +
            "Sangmin remembers that heavy rain is forecast for tonight. " +
            "Their club posters are pinned on the wall right beside it. " +
            "He wants her to close the window before they lock the door. " +
            "In this situation, what would Sangmin most likely say to Jiwoo?",
        ],
      ],
      choices: [
        "Let's open the other window.",
        "The meeting starts at five.",
        "Take the posters home.",
        "It never rains here.",
        "Close the window before we go.",
      ],
      answer: 5,
      clue: "He wants her to close the window before they lock the door.",
      explanation:
        "비가 예보돼 있고 창문이 열려 있으므로, 가기 전에 닫으라는 ⑤가 가장 적절하다.",
      translation: [
        "M: 상민이와 지우는 동아리 모임이 끝나고 교실을 나서고 있습니다. 지우는 창문을 활짝 열어 둔 채 나가려고 합니다. 상민이는 오늘 밤에 비가 많이 온다는 예보를 기억합니다. 동아리 알림 종이가 바로 그 옆 벽에 붙어 있습니다. 그는 문을 잠그기 전에 그녀가 창문을 닫기를 바랍니다. 이런 상황에서 상민이가 지우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
