/** 중3 듣기 36회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 36회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 두 사람이 만들 안내판을 고르시오.",
      lines: [
        ["W", "Hyunsu, how should we design the club sign?"],
        ["M", "Let's start with the shape of the board."],
        ["W", "A long rectangle holds more words than a circle."],
        ["M", "A rectangle, then. What goes on the left side?"],
        ["W", "A drawing of an open book would suit us."],
        ["M", "Should we add an arrow under the book?"],
        ["W", "No arrow. It makes the board look crowded."],
        ["M", "Then a plain border around the whole thing."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "A rectangle, then. What goes on the left side? / No arrow. It makes the board look crowded.",
      explanation:
        "두 사람은 직사각형 판 왼쪽에 펼친 책 그림이 있고 화살표는 없으며 테두리가 둘린 안내판을 만들기로 했다. 따라서 답은 ①이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five blank sign boards side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a wide RECTANGULAR board with a plain BORDER line, an OPEN BOOK drawn on the LEFT side, no arrow. " +
          "② a wide RECTANGULAR board with an OPEN BOOK on the left and a big ARROW under the book. " +
          "③ a ROUND board with an OPEN BOOK drawn in the middle. " +
          "④ a wide RECTANGULAR board with a MUSIC NOTE on the left instead of a book. " +
          "⑤ a ROUND board with an OPEN BOOK and an ARROW under it.",
      },
      translation: [
        "W: 현수야, 동아리 안내판을 어떻게 만들까?",
        "M: 판 모양부터 정하자.",
        "W: 긴 직사각형이 동그라미보다 글자가 더 들어가.",
        "M: 그럼 직사각형으로. 왼쪽에는 뭘 넣지?",
        "W: 펼친 책 그림이 우리한테 어울릴 것 같아.",
        "M: 책 아래에 화살표도 넣을까?",
        "W: 화살표는 빼자. 판이 복잡해 보여.",
        "M: 그럼 전체에 단순한 테두리만 두르자.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 여름 봉사 캠프에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Nahee, are you applying for the summer volunteer camp?"],
        ["W", "I want to. How many days does it last?"],
        ["M", "Three days and two nights in August."],
        ["W", "Where do the students stay at night?"],
        ["M", "In the dormitory of a country middle school."],
        ["W", "What kind of work do we actually do?"],
        ["M", "We paint walls and clean up a village library."],
        ["W", "How many students can join?"],
        ["M", "Only twenty, so apply early."],
      ],
      choices: [
        "캠프 기간",
        "묵는 곳",
        "하는 일",
        "참가 인원",
        "지도하는 선생님",
      ],
      answer: 5,
      clue: "Three days and two nights in August.",
      explanation:
        "기간, 숙소, 하는 일, 인원은 말했지만 지도 교사는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 나희야, 여름 봉사 캠프 신청할 거야?",
        "W: 하고 싶어. 며칠 동안 해?",
        "M: 8월에 2박 3일.",
        "W: 밤에는 어디서 자?",
        "M: 시골 중학교 기숙사에서.",
        "W: 실제로 무슨 일을 해?",
        "M: 벽을 칠하고 마을 도서관을 정리해.",
        "W: 몇 명이나 갈 수 있어?",
        "M: 스무 명뿐이라 일찍 신청해야 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Minseok. This is Jieun from class three."],
        ["M", "Hi, Jieun. Is something up?"],
        ["W", "You lent me your history notes last Friday."],
        ["M", "Right, I almost forgot about those."],
        ["W", "I finished copying them last night."],
        ["M", "No hurry. I'm not using them yet."],
        ["W", "I'd like to give them back tomorrow morning."],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "도움을 요청하려고",
        "감사를 전하려고",
        "빌린 것을 돌려주려고",
      ],
      answer: 5,
      clue: "I'd like to give them back tomorrow morning.",
      explanation:
        "여자는 빌린 필기를 내일 아침에 돌려주려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 민석아. 3반 지은이야.",
        "M: 안녕, 지은아. 무슨 일이야?",
        "W: 지난 금요일에 네 역사 필기 빌렸잖아.",
        "M: 맞다, 그거 거의 잊고 있었어.",
        "W: 어젯밤에 다 베껴 썼어.",
        "M: 급하지 않아. 아직 안 써.",
        "W: 내일 아침에 돌려주고 싶어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 영화를 볼 시각을 고르시오.",
      lines: [
        ["W", "Dohun, what time is the movie you wanted to see?"],
        ["M", "There are showings at six, seven and eight."],
        ["W", "My last class finishes at six fifteen."],
        ["M", "Then the six o'clock showing is out."],
        ["W", "How long does it take to get to the theater?"],
        ["M", "Twenty minutes if we walk fast."],
        ["W", "The seven o'clock one is a little tight."],
        ["M", "We can make it if we leave right away."],
        ["W", "All right, let's take the seven o'clock showing."],
      ],
      choices: ["6:00 p.m.", "6:15 p.m.", "7:00 p.m.", "8:00 p.m.", "7:30 p.m."],
      answer: 3,
      clue: "All right, let's take the seven o'clock showing.",
      explanation:
        "6시 상영은 수업 때문에 못 보고 7시 상영을 보기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 도훈아, 네가 보고 싶다던 영화 몇 시야?",
        "M: 6시, 7시, 8시 상영이 있어.",
        "W: 내 마지막 수업이 6시 15분에 끝나.",
        "M: 그럼 6시 상영은 안 되겠다.",
        "W: 극장까지 얼마나 걸려?",
        "M: 빨리 걸으면 20분.",
        "W: 7시 상영은 좀 빠듯한데.",
        "M: 바로 출발하면 갈 수 있어.",
        "W: 알겠어, 7시 상영으로 하자.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junhyeok, why do you keep looking at the door?"],
        ["M", "My little brother should have come home an hour ago."],
        ["W", "Did you call his phone?"],
        ["M", "It rings and rings, and nobody picks up."],
        ["W", "Maybe he stayed at a friend's house."],
        ["M", "He always tells me before he does that."],
        ["W", "Have you told your parents yet?"],
        ["M", "I can't stop imagining bad things right now."],
      ],
      choices: ["happy", "bored", "proud", "worried", "jealous"],
      answer: 4,
      clue: "I can't stop imagining bad things right now.",
      explanation:
        "동생이 늦게까지 연락이 되지 않아 걱정하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 준혁아, 왜 자꾸 문만 봐?",
        "M: 동생이 한 시간 전에 집에 왔어야 해.",
        "W: 전화해 봤어?",
        "M: 계속 울리는데 아무도 안 받아.",
        "W: 친구 집에 있는 거 아닐까?",
        "M: 그럴 때는 항상 나한테 말해.",
        "W: 부모님께는 말씀드렸어?",
        "M: 자꾸 나쁜 생각만 들어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Where do I put the plastic bottles?"],
        ["W", "In the blue bin on the left."],
        ["ANN", "Number two."],
        ["M", "Is the elevator working today?"],
        ["W", "No, please use the stairs."],
        ["ANN", "Number three."],
        ["M", "Can I park my bike here?"],
        ["W", "Only in the marked area."],
        ["ANN", "Number four."],
        ["M", "What time is trash collected?"],
        ["W", "Every evening at eight."],
        ["ANN", "Number five."],
        ["M", "Do you need help with that box?"],
        ["W", "Yes, please. It's quite heavy."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Where do I put the plastic bottles?",
      explanation:
        "그림은 분리수거장에서 남자가 플라스틱 병이 든 봉투를 들고 어디에 넣을지 묻는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "An apartment recycling area outdoors, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A man holds a clear bag full of plastic bottles and looks at a row of three large bins with a puzzled face. " +
          "A woman standing beside the bins points at the leftmost bin with her hand. " +
          "A low wall and a tree are drawn simply behind them.",
      },
      translation: [
        "① M: 플라스틱 병은 어디에 넣어요? / W: 왼쪽 파란 통에요.",
        "② M: 오늘 엘리베이터 되나요? / W: 아니요, 계단을 이용하세요.",
        "③ M: 여기 자전거 세워도 되나요? / W: 표시된 곳에만요.",
        "④ M: 쓰레기는 몇 시에 수거해요? / W: 매일 저녁 여덟 시에요.",
        "⑤ M: 그 상자 도와드릴까요? / W: 네, 부탁해요. 꽤 무거워요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yuri, you take the number eight bus, right?"],
        ["W", "Every day, and it passes the post office."],
        ["M", "That's exactly what I wanted to ask about."],
        ["W", "Do you need to send something?"],
        ["M", "A letter for my grandmother, but I have practice."],
        ["W", "Is it ready to go?"],
        ["M", "Could you drop this letter in the post box?"],
        ["W", "Sure, the box is right by my stop."],
      ],
      choices: [
        "함께 버스를 타 주기",
        "편지를 부쳐 주기",
        "할머니께 전화하기",
        "연습을 도와주기",
        "우표를 사다 주기",
      ],
      answer: 2,
      clue: "Could you drop this letter in the post box?",
      explanation:
        "남자는 편지를 우체통에 넣어 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 유리야, 너 8번 버스 타지?",
        "W: 매일 타. 우체국을 지나가.",
        "M: 그게 딱 물어보고 싶었던 거야.",
        "W: 뭐 보낼 게 있어?",
        "M: 할머니께 보낼 편지인데 나는 연습이 있어.",
        "W: 다 준비된 거야?",
        "M: 이 편지 우체통에 넣어 줄 수 있어?",
        "W: 그럼, 우리 정류장 바로 옆에 있어.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 교내 사진 대회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The school photo contest begins this week. " +
            "The theme this year is our school in four seasons. " +
            "You may send up to two photographs each. " +
            "Send your files to the art room email by the twentieth. " +
            "Winning photos will be shown in the first floor hallway.",
        ],
      ],
      choices: [
        "대회의 주제",
        "낼 수 있는 작품 수",
        "작품을 보내는 방법",
        "뽑힌 작품을 거는 곳",
        "심사하는 날짜",
      ],
      answer: 5,
      clue: "The theme this year is our school in four seasons.",
      explanation:
        "주제, 작품 수, 제출 방법, 전시 장소는 말했지만 심사 날짜는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 이번 주에 교내 사진 대회를 시작합니다. 올해 주제는 사계절 속 우리 학교입니다. 한 사람이 두 점까지 낼 수 있습니다. 20일까지 미술실 전자우편으로 파일을 보내 주세요. 뽑힌 사진은 1층 복도에 걸립니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a machine that keeps your food cold. " +
            "It stands in the kitchen and hums quietly all day. " +
            "The lower part is often used for frozen things. " +
            "If you leave the door open, the food goes bad. " +
            "Most families could not live without one.",
        ],
      ],
      choices: ["세탁기", "냉장고", "전자레인지", "선풍기", "청소기"],
      answer: 2,
      clue: "This is a machine that keeps your food cold.",
      explanation:
        "부엌에 서서 음식을 차갑게 보관하고 아래쪽에 언 것을 넣는 기계는 냉장고이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이것은 음식을 차갑게 보관하는 기계입니다. 부엌에 서 있고 하루 종일 조용히 소리를 냅니다. 아래쪽은 얼린 것을 넣는 데 자주 씁니다. 문을 열어 두면 음식이 상합니다. 대부분의 가정은 이것 없이 살기 어렵습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How was your weekend?"],
        ["M", "Quiet, but I liked it."],
        ["ANN", "Number two."],
        ["W", "Where did you buy that hat?"],
        ["M", "It takes about an hour."],
        ["ANN", "Number three."],
        ["W", "Can you help me carry this?"],
        ["M", "Sure, give me one side."],
        ["ANN", "Number four."],
        ["W", "What's your favorite subject?"],
        ["M", "History, without a doubt."],
        ["ANN", "Number five."],
        ["W", "Should we meet before or after lunch?"],
        ["M", "After lunch is better for me."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Where did you buy that hat?",
      explanation:
        "어디서 샀는지 묻는 말에 걸리는 시간을 답했으므로 ②의 대화가 어색하다. 따라서 답은 ②이다.",
      translation: [
        "① W: 주말 어땠어? / M: 조용했는데 좋았어.",
        "② W: 그 모자 어디서 샀어? / M: 한 시간쯤 걸려.",
        "③ W: 이거 옮기는 것 좀 도와줄래? / M: 그럼, 한쪽 줘.",
        "④ W: 제일 좋아하는 과목이 뭐야? / M: 두말할 것 없이 역사.",
        "⑤ W: 점심 전에 만날까, 후에 만날까? / M: 점심 후가 나아.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoha, did you hear the announcement about the gym?"],
        ["W", "I was in the restroom. What did they say?"],
        ["M", "Our club practice moved to the music room."],
        ["W", "Do the other members know about it?"],
        ["M", "I told everyone except Yerin."],
        ["W", "She's probably waiting at the gym already."],
        ["M", "Practice starts in five minutes."],
        ["W", "I'll run over and bring her here."],
      ],
      choices: [
        "음악실을 정리하기",
        "체육관에 가서 친구를 데려오기",
        "선생님께 여쭤보기",
        "연습을 시작하기",
        "집에 돌아가기",
      ],
      answer: 2,
      clue: "I'll run over and bring her here.",
      explanation:
        "여자는 체육관에 가서 기다리고 있을 친구를 데려오겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 서하야, 체육관 방송 들었어?",
        "W: 화장실에 있었어. 뭐라고 했어?",
        "M: 우리 동아리 연습이 음악실로 바뀌었대.",
        "W: 다른 부원들은 알아?",
        "M: 예린이만 빼고 다 말했어.",
        "W: 아마 벌써 체육관에서 기다리고 있을 거야.",
        "M: 연습이 5분 뒤에 시작해.",
        "W: 내가 뛰어가서 데려올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 단체 티셔츠를 고르시오.",
      lines: [
        ["W", "Jaehun, we need to choose the club T-shirts today."],
        ["M", "The shop sent us five options."],
        ["W", "Our budget is nine thousand won per shirt."],
        ["M", "Two of them are more expensive than that."],
        ["W", "We also agreed on a dark color."],
        ["M", "So white and yellow are out."],
        ["W", "And we need our logo printed on the front."],
        ["M", "Some of them only print on the back."],
        ["W", "Then just one option is left for us."],
        ["M", "I'll send the order form this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Our budget is nine thousand won per shirt.",
      explanation:
        "9천 원 이하, 어두운 색, 앞면 인쇄인 것을 고른다. 세 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 8,000 won / Color: White / Print: Front" },
          { no: 2, label: "②", value: "Price: 11,000 won / Color: Navy / Print: Front" },
          { no: 3, label: "③", value: "Price: 8,500 won / Color: Black / Print: Back" },
          { no: 4, label: "④", value: "Price: 9,000 won / Color: Navy / Print: Front" },
          { no: 5, label: "⑤", value: "Price: 12,000 won / Color: Yellow / Print: Back" },
        ],
      },
      translation: [
        "W: 재훈아, 오늘 동아리 티셔츠를 정해야 해.",
        "M: 가게에서 다섯 가지를 보내 줬어.",
        "W: 우리 예산은 한 장에 9천 원이야.",
        "M: 두 개는 그보다 비싸.",
        "W: 그리고 어두운 색으로 하기로 했잖아.",
        "M: 그럼 흰색이랑 노란색은 빠지네.",
        "W: 로고는 앞면에 찍혀야 해.",
        "M: 어떤 건 뒷면에만 찍어.",
        "W: 그럼 하나만 남네.",
        "M: 오늘 저녁에 주문서 보낼게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 공연을 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Areum, the school orchestra plays three times this month."],
        ["W", "Which dates did they announce?"],
        ["M", "The fifth, the twelfth and the nineteenth."],
        ["W", "I have a family dinner on the fifth."],
        ["M", "Then that one is out for you."],
        ["W", "The twelfth is the day before the science test."],
        ["M", "You wouldn't enjoy the music at all that night."],
        ["W", "So the nineteenth is the best choice for me."],
        ["M", "I'll reserve two seats for the nineteenth."],
      ],
      choices: ["the 5th", "the 12th", "the 19th", "the 26th", "the 2nd"],
      answer: 3,
      clue: "So the nineteenth is the best choice for me.",
      explanation:
        "5일은 가족 식사, 12일은 시험 전날이어서 19일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 아름아, 학교 관현악단이 이번 달에 세 번 연주해.",
        "W: 어떤 날짜라고 했어?",
        "M: 5일, 12일, 19일.",
        "W: 5일에는 가족 식사가 있어.",
        "M: 그럼 그건 빠지네.",
        "W: 12일은 과학 시험 전날이야.",
        "M: 그날 밤엔 음악이 귀에 안 들어오겠다.",
        "W: 그럼 나한테는 19일이 제일 좋아.",
        "M: 19일로 두 자리 예약할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 토요일에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, I didn't see you at the basketball game."],
        ["W", "I was at the city library all day on Saturday."],
        ["M", "Were you studying for something?"],
        ["W", "No, I was helping with the children's reading day."],
        ["M", "What did you have to do there?"],
        ["W", "I read picture books aloud to first graders."],
        ["M", "Did they sit still for the whole story?"],
        ["W", "Only if I changed my voice for each character."],
        ["M", "That sounds harder than it looks."],
        ["W", "My throat hurt by the end of the afternoon."],
      ],
      choices: [
        "농구 경기를 보기",
        "시험공부를 하기",
        "도서관에서 아이들에게 책을 읽어 주기",
        "가족과 등산을 가기",
        "동아리 연습을 하기",
      ],
      answer: 3,
      clue: "I was at the city library all day on Saturday.",
      explanation:
        "여자는 토요일에 시립 도서관에서 아이들에게 그림책을 읽어 주었다. 따라서 답은 ③이다.",
      translation: [
        "M: 다인아, 농구 경기에서 못 봤어.",
        "W: 토요일 하루 종일 시립 도서관에 있었어.",
        "M: 뭐 공부하러?",
        "W: 아니, 어린이 독서의 날을 도왔어.",
        "M: 거기서 뭘 했는데?",
        "W: 1학년들에게 그림책을 소리 내어 읽어 줬어.",
        "M: 이야기 내내 가만히 앉아 있었어?",
        "W: 등장인물마다 목소리를 바꿔야 그랬어.",
        "M: 보기보다 힘들겠다.",
        "W: 오후가 끝날 때쯤엔 목이 아팠어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Good morning, students. This is the student council. " +
            "We are collecting used books for the village center. " +
            "The center opened a small reading room last month. " +
            "Bring books you no longer read to the front hall. " +
            "Children's books and novels are especially welcome there. " +
            "The collection box stays there until next Friday. " +
            "Please make sure the pages are not torn or wet. " +
            "Thank you for helping your neighbors.",
        ],
      ],
      choices: [
        "책 기부를 부탁하려고",
        "도서관 규칙을 알리려고",
        "행사를 취소하려고",
        "시험 범위를 알리려고",
        "청소 시간을 바꾸려고",
      ],
      answer: 1,
      clue: "We are collecting used books for the village center.",
      explanation:
        "마을 센터에 보낼 헌책을 모으니 가져다 달라고 부탁하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 학생회입니다. 마을 센터에 보낼 헌책을 모으고 있습니다. 센터에서는 지난달에 작은 독서실을 열었습니다. 더 이상 읽지 않는 책을 현관 앞으로 가져와 주세요. 어린이책과 소설은 특히 환영합니다. 수거함은 다음 주 금요일까지 그곳에 있습니다. 쪽이 찢어지거나 젖지 않았는지 꼭 확인해 주세요. 이웃을 도와주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the science museum. How many tickets?"],
        ["M", "Two student tickets and one adult ticket, please."],
        ["W", "Student tickets are five dollars each today."],
        ["M", "And how much is the adult ticket?"],
        ["W", "The adult ticket is nine dollars."],
        ["M", "Is the planetarium show included in that?"],
        ["W", "No, that show costs three dollars more per person."],
        ["M", "We'll skip the show this time, then."],
        ["W", "No problem. That's everything for today."],
        ["M", "Here you go. Thank you very much."],
      ],
      choices: ["$14", "$17", "$19", "$21", "$23"],
      answer: 3,
      clue: "Student tickets are five dollars each today.",
      explanation:
        "학생 표 두 장 10달러와 어른 표 9달러를 더하면 19달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 과학관에 오신 걸 환영합니다. 표 몇 장 드릴까요?",
        "M: 학생 표 두 장이랑 어른 표 한 장이요.",
        "W: 오늘 학생 표는 한 장에 5달러입니다.",
        "M: 어른 표는 얼마예요?",
        "W: 어른 표는 9달러입니다.",
        "M: 천문관 공연도 포함인가요?",
        "W: 아니요, 그 공연은 한 사람당 3달러 더 내셔야 합니다.",
        "M: 이번에는 공연은 빼겠습니다.",
        "W: 알겠습니다. 오늘은 그게 전부입니다.",
        "M: 여기요. 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seungmin, your desk is always so tidy."],
        ["M", "I clear it for two minutes before I go home."],
        ["W", "Only two minutes? That seems too short."],
        ["M", "It's short because I do it every single day."],
        ["W", "Mine takes an hour whenever I finally clean it."],
        ["M", "That's because you wait until it's terrible."],
        ["W", "And then I don't want to start at all."],
        ["M", "Two minutes daily beats one hour monthly."],
        ["W", "Could you help me clear mine today?"],
      ],
      choices: [
        "Sure, let's start right now.",
        "Your desk is already clean.",
        "I never clean my desk.",
        "You should wait one more month.",
        "Cleaning takes too long.",
      ],
      answer: 1,
      clue: "Could you help me clear mine today?",
      explanation:
        "여자가 오늘 책상 정리를 도와 달라고 했으므로, 지금 시작하자는 ①이 가장 자연스럽다.",
      translation: [
        "W: 승민아, 네 책상은 늘 깔끔해.",
        "M: 집에 가기 전에 2분씩 치워.",
        "W: 2분만? 너무 짧은데.",
        "M: 매일 하니까 짧은 거야.",
        "W: 나는 큰맘 먹고 치우면 한 시간 걸려.",
        "M: 아주 엉망이 될 때까지 기다려서 그래.",
        "W: 그러면 시작하기도 싫어져.",
        "M: 매일 2분이 한 달에 한 시간보다 나아.",
        "W: 오늘 내 책상 치우는 것 좀 도와줄래?",
        "M: 그럼, 지금 바로 시작하자.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayeon, you speak English so comfortably in class."],
        ["W", "I talk with my cousin in Canada every Sunday."],
        ["M", "For how long do you usually talk?"],
        ["W", "About thirty minutes on a video call."],
        ["M", "Don't you run out of things to say?"],
        ["W", "We decide on a topic before the call starts."],
        ["M", "That's a clever way to keep it going."],
        ["W", "Last week we talked about school lunches."],
        ["M", "Could I join your call one day?"],
      ],
      choices: [
        "I don't have a cousin.",
        "Of course, next Sunday works.",
        "We stopped calling months ago.",
        "You shouldn't speak English.",
        "The call is only in Korean.",
      ],
      answer: 2,
      clue: "Could I join your call one day?",
      explanation:
        "남자가 통화에 끼어도 되는지 물었으므로, 다음 주 일요일이 좋다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나연아, 너는 수업 시간에 영어를 참 편하게 하더라.",
        "W: 일요일마다 캐나다에 있는 사촌이랑 이야기해.",
        "M: 보통 얼마나 이야기해?",
        "W: 영상 통화로 30분쯤.",
        "M: 할 말이 떨어지지 않아?",
        "W: 통화 전에 주제를 정해 놔.",
        "M: 이어 가기 좋은 방법이네.",
        "W: 지난주엔 학교 급식 이야기를 했어.",
        "M: 나도 언젠가 그 통화에 껴도 될까?",
        "W: 그럼, 다음 주 일요일 괜찮아.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyeonjun, did you decide about the class president election?"],
        ["M", "I keep changing my mind every hour."],
        ["W", "What worries you the most about it?"],
        ["M", "Speaking in front of three hundred students."],
        ["W", "You spoke well at the club meeting last week."],
        ["M", "That room had twenty people, not three hundred."],
        ["W", "The number changes, but your words don't."],
        ["M", "I never thought about it that way."],
        ["W", "Why don't you write your speech first and decide later?"],
      ],
      choices: [
        "I already lost the election.",
        "There is no election this year.",
        "That's a good idea, I'll write it.",
        "I don't want to speak at all.",
        "You should run instead of me.",
      ],
      answer: 3,
      clue: "Why don't you write your speech first and decide later?",
      explanation:
        "먼저 연설문을 써 보고 나중에 정하라는 제안이므로, 그러겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 현준아, 반장 선거 나갈지 정했어?",
        "M: 한 시간마다 마음이 바뀌어.",
        "W: 뭐가 제일 걱정돼?",
        "M: 300명 앞에서 말하는 거.",
        "W: 지난주 동아리 모임에서는 잘하던데.",
        "M: 거긴 스무 명이었지 300명이 아니잖아.",
        "W: 사람 수는 달라져도 네 말은 그대로야.",
        "M: 그렇게는 생각 못 했어.",
        "W: 연설문부터 써 보고 나중에 정하는 건 어때?",
        "M: 좋은 생각이야, 써 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Woohyuk이 Sohee에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woohyuk : ________________",
      lines: [
        [
          "M",
          "Woohyuk and Sohee are eating lunch in the school cafeteria. " +
            "Sohee tells him she left her wallet on the bus this morning. " +
            "She says she has no money for lunch or for the bus home. " +
            "Woohyuk has enough money in his pocket for both of them. " +
            "He wants to offer to pay for her without making her uncomfortable. " +
            "In this situation, what would Woohyuk most likely say to Sohee?",
        ],
      ],
      choices: [
        "You should look for your wallet.",
        "Lunch is cheap at this school.",
        "I lost my wallet last week too.",
        "Let me cover it, pay me back later.",
        "The bus stop is over there.",
      ],
      answer: 4,
      clue: "He wants to offer to pay for her without making her uncomfortable.",
      explanation:
        "부담 주지 않고 대신 내 주겠다는 뜻이므로, 나중에 갚으라는 ④가 가장 적절하다.",
      translation: [
        "M: 우혁이와 소희는 학교 식당에서 점심을 먹고 있습니다. 소희는 오늘 아침 버스에 지갑을 두고 내렸다고 말합니다. 점심값도 집에 갈 차비도 없다고 합니다. 우혁이는 주머니에 둘의 몫을 낼 만큼 돈이 있습니다. 우혁이는 소희가 부담스럽지 않게 대신 내 주고 싶습니다. 이런 상황에서 우혁이가 소희에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
