/** 중3 듣기 47회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 47회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 고를 책상 의자를 고르시오.",
      lines: [
        ["M", "Suhyeon, are you buying a chair for your desk?"],
        ["W", "My old one hurts my back after an hour."],
        ["M", "This one has arm rests on both sides."],
        ["W", "No arm rests. They bump into my desk."],
        ["M", "Do you want wheels on the legs?"],
        ["W", "Yes, wheels. I move around a lot."],
        ["M", "And the head rest at the top?"],
        ["W", "A head rest would help my neck."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "No arm rests. They bump into my desk. / A head rest would help my neck.",
      explanation:
        "팔걸이 없고 바퀴가 있으며 머리 받침이 있는 의자이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five desk chairs side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a chair with ARM RESTS on both sides, WHEELS on the legs and a HEAD REST on top. " +
          "② a chair with NO arm rests, FLAT feet instead of wheels, and a HEAD REST on top. " +
          "③ a chair with ARM RESTS, WHEELS, and NO head rest. " +
          "④ a chair with NO arm rests, WHEELS, and NO head rest. " +
          "⑤ a chair with NO arm rests, WHEELS on the legs and a HEAD REST on top.",
      },
      translation: [
        "M: 수현아, 책상 의자 사는 거야?",
        "W: 쓰던 게 한 시간만 앉아 있으면 허리가 아파.",
        "M: 이건 양쪽에 팔걸이가 있네.",
        "W: 팔걸이는 안 돼. 책상에 걸려.",
        "M: 다리에 바퀴는 달린 걸로 할래?",
        "W: 응, 바퀴. 나는 많이 움직여.",
        "M: 위에 머리 받침은?",
        "W: 머리 받침은 목에 도움이 되겠어.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학생회 선거에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Dohyun, when is the student council election?"],
        ["M", "Voting happens next Friday afternoon."],
        ["W", "Where do we cast our votes?"],
        ["M", "In our own classrooms, one class at a time."],
        ["W", "Who can run for president?"],
        ["M", "Any second grade student with ten signatures."],
        ["W", "Do the candidates give speeches?"],
        ["M", "They speak in the hall on Wednesday morning."],
        ["W", "How long is each speech?"],
        ["M", "Three minutes, and no one gets more."],
      ],
      choices: ["투표하는 날", "투표하는 곳", "출마할 수 있는 학년", "연설 시간", "당선자 발표일"],
      answer: 5,
      clue: "Voting happens next Friday afternoon.",
      explanation:
        "투표일, 장소, 출마 자격, 연설 시간은 말했지만 당선자 발표일은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 학생회 선거가 언제야?",
        "M: 다음 주 금요일 오후에 투표해.",
        "W: 어디서 투표해?",
        "M: 각자 교실에서, 반별로 차례대로.",
        "W: 회장은 누가 나갈 수 있어?",
        "M: 서명 열 개를 받은 2학년이면 누구나.",
        "W: 후보들이 연설도 해?",
        "M: 수요일 아침에 강당에서 해.",
        "W: 연설은 얼마나 해?",
        "M: 3분, 누구도 더 못 해.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, this is the city library information desk."],
        ["M", "Hello. My name is Junseok Han."],
        ["W", "How may I help you today?"],
        ["M", "I borrowed three books two weeks ago."],
        ["W", "Are they due back this week?"],
        ["M", "Tomorrow, but I'm not finished with one of them."],
        ["W", "Have you renewed anything before?"],
        ["M", "This would be the first time."],
        ["W", "Renewing is possible if nobody is waiting."],
        ["M", "I'm calling to extend the loan by one week."],
      ],
      choices: [
        "대출 기간을 늘리려고",
        "책을 예약하려고",
        "책을 반납하려고",
        "회원증을 만들려고",
        "이용 시간을 물어보려고",
      ],
      answer: 1,
      clue: "I'm calling to extend the loan by one week.",
      explanation:
        "남자는 대출 기간을 일주일 늘리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요, 시립 도서관 안내대입니다.",
        "M: 안녕하세요. 저는 한준석입니다.",
        "W: 무엇을 도와드릴까요?",
        "M: 두 주 전에 책 세 권을 빌렸어요.",
        "W: 이번 주가 반납일인가요?",
        "M: 내일이요. 그런데 한 권을 다 못 읽었어요.",
        "W: 전에 연장해 보신 적 있나요?",
        "M: 이번이 처음이에요.",
        "W: 기다리는 사람이 없으면 연장됩니다.",
        "M: 대출을 일주일 늘리려고 전화했어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 연습을 시작할 시각을 고르시오.",
      lines: [
        ["W", "Kiwon, when can we run through the speech today?"],
        ["M", "The small hall is free from three o'clock."],
        ["W", "My last class ends at three fifteen."],
        ["M", "Then three is too early for you."],
        ["W", "Can we start at three thirty instead?"],
        ["M", "I need fifteen minutes to set up the timer."],
        ["W", "So you'll be ready by three thirty anyway."],
        ["M", "Then let's begin at three thirty."],
        ["W", "I'll bring the printed script."],
      ],
      choices: ["3:00 p.m.", "3:15 p.m.", "3:30 p.m.", "3:45 p.m.", "4:00 p.m."],
      answer: 3,
      clue: "Then let's begin at three thirty.",
      explanation:
        "수업이 3시 15분에 끝나 3시 30분에 연습을 시작하기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 기원아, 오늘 연설 언제 맞춰 볼까?",
        "M: 소강당이 세 시부터 비어.",
        "W: 내 마지막 수업이 세 시 15분에 끝나.",
        "M: 그럼 세 시는 너한테 이르네.",
        "W: 대신 세 시 반에 시작할까?",
        "M: 나는 시계 맞추는 데 15분이 필요해.",
        "W: 그럼 어차피 세 시 반이면 준비되겠다.",
        "M: 그럼 세 시 반에 시작하자.",
        "W: 출력한 원고는 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, you've been grinning since lunch."],
        ["M", "My drawing was chosen for the city exhibition."],
        ["W", "The one of the market at night?"],
        ["M", "I worked on it for three whole months."],
        ["W", "How many works were submitted?"],
        ["M", "Over six hundred from middle school students."],
        ["W", "And yours made it in."],
        ["M", "My parents are coming to see it on Sunday."],
      ],
      choices: ["bored", "worried", "proud", "angry", "scared"],
      answer: 3,
      clue: "My parents are coming to see it on Sunday.",
      explanation:
        "석 달 걸린 그림이 전시에 뽑혀 뿌듯해하고 있다. 따라서 답은 ③이다.",
      translation: [
        "W: 상우야, 점심시간부터 계속 싱글벙글하네.",
        "M: 내 그림이 시 전시회에 뽑혔어.",
        "W: 밤 시장을 그린 그거?",
        "M: 꼬박 석 달을 매달렸어.",
        "W: 몇 작품이나 냈는데?",
        "M: 중학생 작품만 600점 넘게.",
        "W: 그중에 네 그림이 들어간 거네.",
        "M: 일요일에 부모님이 보러 오셔.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Could you show me where this street is?"],
        ["W", "It's two blocks that way."],
        ["ANN", "Number two."],
        ["M", "Is the museum open on Monday?"],
        ["W", "No, it's closed."],
        ["ANN", "Number three."],
        ["M", "May I take a photo here?"],
        ["W", "Please don't use a flash."],
        ["ANN", "Number four."],
        ["M", "Where can I throw this away?"],
        ["W", "The bin is around the corner."],
        ["ANN", "Number five."],
        ["M", "How far is the station?"],
        ["W", "About ten minutes on foot."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Could you show me where this street is?",
      explanation:
        "그림은 지도를 펼쳐 들고 길을 묻자 방향을 가리켜 주는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "On a city street corner, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy holds an open folded paper map with both hands and looks up at a woman beside him. " +
          "The woman points down the street with one arm fully extended. " +
          "Shop fronts, a street lamp and a crossing are drawn simply behind them.",
      },
      translation: [
        "① M: 이 길이 어디인지 알려 주시겠어요? / W: 저쪽으로 두 블록이요.",
        "② M: 박물관이 월요일에 여나요? / W: 아니요, 닫습니다.",
        "③ M: 여기서 사진 찍어도 되나요? / W: 플래시는 쓰지 말아 주세요.",
        "④ M: 이건 어디에 버려요? / W: 모퉁이 돌면 통이 있어요.",
        "⑤ M: 역까지 얼마나 멀어요? / W: 걸어서 10분쯤이요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeji, you're good at organizing files, aren't you?"],
        ["W", "I keep every school file in dated folders."],
        ["M", "Our club has three years of photos in one place."],
        ["W", "All mixed together in a single folder?"],
        ["M", "Nobody can find last year's festival pictures."],
        ["W", "That happens when nothing has a date."],
        ["M", "We need them for the graduation slideshow."],
        ["W", "How many photos are we talking about?"],
        ["M", "Could you sort the photos by year for us?"],
        ["W", "Send me the folder and I'll start tonight."],
      ],
      choices: [
        "사진을 찍어 주기",
        "영상을 만들어 주기",
        "사진첩을 사 주기",
        "사진을 연도별로 정리해 주기",
        "축제를 준비해 주기",
      ],
      answer: 4,
      clue: "Could you sort the photos by year for us?",
      explanation:
        "남자는 사진을 연도별로 정리해 달라고 부탁했다. 따라서 답은 ④이다.",
      translation: [
        "M: 예지야, 너 파일 정리 잘하지?",
        "W: 학교 파일은 날짜별 폴더에 다 넣어 둬.",
        "M: 우리 동아리는 3년 치 사진이 한군데에 있어.",
        "W: 폴더 하나에 전부 섞여 있어?",
        "M: 작년 축제 사진을 아무도 못 찾아.",
        "W: 날짜가 없으면 그렇게 돼.",
        "M: 졸업 영상에 그 사진이 필요해.",
        "W: 사진이 몇 장이나 되는데?",
        "M: 사진을 연도별로 좀 정리해 줄 수 있어?",
        "W: 폴더 보내 줘. 오늘 밤부터 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 졸업 앨범 신청에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, third grade students. Yearbook orders start this week. " +
            "The album costs twenty-five thousand won this year. " +
            "Write your name and class on the order sheet. " +
            "Hand the sheet to your homeroom teacher by Friday. " +
            "Albums are handed out on the graduation day. " +
            "Late orders cannot be accepted after Friday.",
        ],
      ],
      choices: ["앨범 값", "신청서에 적을 것", "신청서를 낼 사람", "앨범을 받는 날", "앨범의 쪽수"],
      answer: 5,
      clue: "The album costs twenty-five thousand won this year.",
      explanation:
        "값, 적을 내용, 제출처, 배부일은 말했지만 쪽수는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 3학년 학생 여러분, 안녕하세요. 이번 주부터 졸업 앨범을 신청받습니다. 올해 앨범 값은 25,000원입니다. 신청서에 이름과 반을 적어 주세요. 금요일까지 담임 선생님께 내시면 됩니다. 앨범은 졸업식 날 나눠 드립니다. 금요일이 지나면 늦은 신청은 받을 수 없습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This small card lets you into the school building. " +
            "Your photograph and your class are printed on it. " +
            "You show it to borrow a book from the library. " +
            "Losing it means paying for a new one at the office. " +
            "Keep it in your wallet, not loose in your pocket.",
        ],
      ],
      choices: ["교통 카드", "학생증", "도서 카드", "체육복", "명찰"],
      answer: 2,
      clue: "This small card lets you into the school building.",
      explanation:
        "사진과 반이 찍혀 있고 도서 대출에도 쓰는 것은 학생증이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이 작은 카드가 있으면 학교 건물에 들어갈 수 있습니다. 여기에는 사진과 반이 찍혀 있습니다. 도서관에서 책을 빌릴 때 이것을 보여 줍니다. 잃어버리면 사무실에서 돈을 내고 새로 만들어야 합니다. 주머니에 그냥 넣지 말고 지갑에 넣어 두세요.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Have you decided on a high school?"],
        ["M", "Almost, two are still on my list."],
        ["ANN", "Number two."],
        ["W", "Could you help me move this desk?"],
        ["M", "Take that side and lift on three."],
        ["ANN", "Number three."],
        ["W", "What time did you get home?"],
        ["M", "I like winter better than summer."],
        ["ANN", "Number four."],
        ["W", "Do you want to borrow my notes?"],
        ["M", "That would really help, thanks."],
        ["ANN", "Number five."],
        ["W", "Why is the gym locked?"],
        ["M", "They're waxing the floor."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "What time did you get home?",
      explanation:
        "집에 몇 시에 갔는지 묻는 말에 계절 이야기를 했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① W: 고등학교 정했어? / M: 거의. 두 곳이 아직 남았어.",
        "② W: 이 책상 옮기는 것 좀 도와줄래? / M: 그쪽 잡고 셋에 들어.",
        "③ W: 집에 몇 시에 갔어? / M: 나는 여름보다 겨울이 좋아.",
        "④ W: 내 필기 빌려줄까? / M: 정말 도움 되겠다, 고마워.",
        "⑤ W: 체육관이 왜 잠겼어? / M: 바닥에 왁스 칠하는 중이야.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Bora, the club exhibition opens in fifteen minutes."],
        ["W", "The works are all hung on the boards."],
        ["M", "Did anyone put up the name labels?"],
        ["W", "They're still in the envelope on the desk."],
        ["M", "Visitors won't know whose work is whose."],
        ["W", "Twenty labels will take a few minutes."],
        ["M", "I'll open the windows and turn on the lights."],
        ["W", "I'll go and put up the labels."],
      ],
      choices: [
        "작품을 걸기",
        "창문을 열기",
        "이름표를 붙이기",
        "손님을 맞이하기",
        "봉투를 치우기",
      ],
      answer: 3,
      clue: "I'll go and put up the labels.",
      explanation:
        "여자는 작품에 이름표를 붙이러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 보라야, 동아리 전시가 15분 뒤에 열어.",
        "W: 작품은 게시판에 다 걸었어.",
        "M: 이름표는 누가 붙였어?",
        "W: 아직 책상 위 봉투에 들어 있어.",
        "M: 그러면 누구 작품인지 아무도 몰라.",
        "W: 스무 장이면 몇 분이면 돼.",
        "M: 나는 창문 열고 불을 켤게.",
        "W: 내가 가서 이름표를 붙일게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 사진관을 고르시오.",
      lines: [
        ["W", "Junyoung, which studio will you book for the photos?"],
        ["M", "Five studios came up when I searched."],
        ["W", "How much can your family spend?"],
        ["M", "Under a hundred fifty thousand won."],
        ["W", "One of them is well over that."],
        ["M", "It also has to be open on Sunday."],
        ["W", "Two of these close on the weekend."],
        ["M", "And the photos should be ready within a week."],
        ["W", "Then only one studio fits everything."],
        ["M", "I'll call them after dinner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Under a hundred fifty thousand won.",
      explanation:
        "15만 원 미만, 일요일 영업, 일주일 이내 인화인 사진관은 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 180,000 won / Sunday: Open / Ready in: 5 days" },
          { no: 2, label: "②", value: "Price: 120,000 won / Sunday: Closed / Ready in: 4 days" },
          { no: 3, label: "③", value: "Price: 130,000 won / Sunday: Closed / Ready in: 6 days" },
          { no: 4, label: "④", value: "Price: 140,000 won / Sunday: Open / Ready in: 6 days" },
          { no: 5, label: "⑤", value: "Price: 135,000 won / Sunday: Open / Ready in: 10 days" },
        ],
      },
      translation: [
        "W: 준영아, 사진 찍을 사진관 어디로 예약할 거야?",
        "M: 찾아보니 다섯 곳이 나왔어.",
        "W: 너희 가족이 얼마까지 쓸 수 있어?",
        "M: 15만 원 미만.",
        "W: 한 곳은 그보다 훨씬 비싸네.",
        "M: 그리고 일요일에 문을 열어야 해.",
        "W: 이 중 두 곳은 주말에 쉬어.",
        "M: 그리고 사진이 일주일 안에 나와야 해.",
        "W: 그럼 다 맞는 곳은 하나뿐이야.",
        "M: 저녁 먹고 전화할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taeho, when should we go to the nursing home?"],
        ["M", "They gave us three Saturdays this month."],
        ["W", "Which dates did they write down?"],
        ["M", "The sixth, the thirteenth and the twentieth."],
        ["W", "The sixth is the day of the mock exam."],
        ["M", "We'd be too tired to be any help."],
        ["W", "And the twentieth is the graduation rehearsal."],
        ["M", "Then the thirteenth is the only day left."],
        ["W", "They want us there from two until four."],
        ["M", "I'll tell them we're coming on the thirteenth."],
      ],
      choices: ["the 6th", "the 13th", "the 20th", "the 3rd", "the 27th"],
      answer: 2,
      clue: "Then the thirteenth is the only day left.",
      explanation:
        "6일은 모의고사, 20일은 졸업식 예행연습이어서 13일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 태호야, 요양원에 언제 갈까?",
        "M: 이번 달에 토요일 세 번을 주셨어.",
        "W: 어떤 날짜를 적어 주셨어?",
        "M: 6일, 13일, 20일.",
        "W: 6일은 모의고사 날이야.",
        "M: 너무 지쳐서 도움이 안 되겠지.",
        "W: 20일은 졸업식 예행연습이고.",
        "M: 그럼 남는 날은 13일뿐이네.",
        "W: 두 시부터 네 시까지 와 달라고 하셨어.",
        "M: 13일에 간다고 말씀드릴게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minseok, you weren't at the study room yesterday."],
        ["M", "I helped my father repair the roof."],
        ["W", "Was something leaking?"],
        ["M", "Rain came through above the kitchen."],
        ["W", "Isn't that dangerous work?"],
        ["M", "I stayed on the ladder and passed him tools."],
        ["W", "How long did it take?"],
        ["M", "From two in the afternoon until dark."],
        ["W", "Is the leak fixed now?"],
        ["M", "It rained last night and nothing came in."],
      ],
      choices: [
        "공부방에 갔다",
        "지붕 고치는 것을 도왔다",
        "부엌을 청소했다",
        "친구를 만났다",
        "집에서 쉬었다",
      ],
      answer: 2,
      clue: "I helped my father repair the roof.",
      explanation:
        "남자는 어제 아버지의 지붕 수리를 도왔다. 따라서 답은 ②이다.",
      translation: [
        "W: 민석아, 어제 공부방에 없더라.",
        "M: 아버지 지붕 고치는 걸 도와드렸어.",
        "W: 어디 새고 있었어?",
        "M: 부엌 위로 비가 들어왔어.",
        "W: 위험한 일 아니야?",
        "M: 나는 사다리에 있으면서 연장을 건네 드렸어.",
        "W: 얼마나 걸렸어?",
        "M: 오후 두 시부터 어두워질 때까지.",
        "W: 이제 안 새?",
        "M: 어젯밤에 비가 왔는데 하나도 안 들어왔어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the physical education office. " +
            "The graduation rehearsal takes place tomorrow morning. " +
            "All third grade classes gather in the main hall at nine. " +
            "Line up in the order posted on your classroom door. " +
            "Wear your school uniform, not your gym clothes. " +
            "The rehearsal lasts about one hour. " +
            "Return to your classroom right afterwards.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "졸업식 예행연습을 안내하려고",
        "분실물을 찾으려고",
        "봉사자를 모으려고",
        "청소를 부탁하려고",
      ],
      answer: 2,
      clue: "The graduation rehearsal takes place tomorrow morning.",
      explanation:
        "내일 아침 졸업식 예행연습을 안내하는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 체육부입니다. 내일 아침에 졸업식 예행연습을 합니다. 3학년 전 학급은 아홉 시에 대강당으로 모입니다. 교실 문에 붙은 순서대로 줄을 서세요. 체육복 말고 교복을 입으세요. 예행연습은 한 시간쯤 걸립니다. 끝나면 바로 교실로 돌아가세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome. What can I do for you today?"],
        ["W", "Two photo frames and three albums, please."],
        ["M", "Frames are five dollars each this week."],
        ["W", "And how much are the albums?"],
        ["M", "Three dollars for a small album."],
        ["W", "Do you wrap them as gifts?"],
        ["M", "Wrapping is free for orders over ten dollars."],
        ["W", "Then I don't pay anything extra."],
        ["M", "That's right, nothing extra at all."],
        ["W", "Good. Here is my card."],
      ],
      choices: ["$16", "$17", "$18", "$19", "$20"],
      answer: 4,
      clue: "Frames are five dollars each this week.",
      explanation:
        "액자 두 개 10달러와 사진첩 세 권 9달러를 더하면 19달러이다. 따라서 답은 ④이다.",
      translation: [
        "M: 어서 오세요. 오늘은 뭘 도와드릴까요?",
        "W: 액자 두 개랑 사진첩 세 권 주세요.",
        "M: 이번 주 액자는 하나에 5달러입니다.",
        "W: 사진첩은 얼마예요?",
        "M: 작은 사진첩은 3달러입니다.",
        "W: 선물 포장도 해 주시나요?",
        "M: 10달러 넘게 사시면 포장은 무료입니다.",
        "W: 그럼 추가로 낼 건 없네요.",
        "M: 맞습니다. 전혀 없습니다.",
        "W: 좋네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Areum, your English writing improved a lot this year."],
        ["W", "I write three sentences in a diary every night."],
        ["M", "Only three? That seems too short to help."],
        ["W", "Three sentences I actually finish beat a page I never start."],
        ["M", "I always plan a whole page and give up."],
        ["W", "A small promise is easier to keep."],
        ["M", "Do you look up every word you don't know?"],
        ["W", "Only one word a night, never more."],
        ["M", "What should I write about tonight?"],
      ],
      choices: [
        "Write about today's dinner.",
        "Write ten pages at once.",
        "Don't write anything.",
        "Copy a whole textbook.",
        "Wait until next year.",
      ],
      answer: 1,
      clue: "What should I write about tonight?",
      explanation:
        "오늘 밤 무엇을 쓸지 물었으므로, 오늘 저녁밥 이야기를 쓰라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 아름아, 올해 네 영어 글쓰기가 많이 늘었네.",
        "W: 매일 밤 일기에 세 문장씩 써.",
        "M: 세 문장만? 도움이 되기엔 너무 짧은데.",
        "W: 끝까지 쓰는 세 문장이 시작도 못 하는 한 쪽보다 나아.",
        "M: 나는 늘 한 쪽을 계획하고 포기해.",
        "W: 작은 약속이 지키기 쉬워.",
        "M: 모르는 낱말은 다 찾아봐?",
        "W: 하룻밤에 한 개만, 그 이상은 안 해.",
        "M: 오늘 밤에는 뭘 쓰면 좋을까?",
        "W: 오늘 저녁밥에 대해 써 봐.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyunbin, I heard you make wooden spoons."],
        ["M", "My uncle showed me last winter in his workshop."],
        ["W", "How long does one spoon take?"],
        ["M", "About four hours if the wood is soft."],
        ["W", "What kind of wood do you use?"],
        ["M", "Cherry, because it doesn't split easily."],
        ["W", "Is it hard to make the bowl part?"],
        ["M", "That part takes half of the whole time."],
        ["W", "How many have you finished so far?"],
        ["M", "Nine, and I gave seven of them away."],
        ["W", "Could you show me how you start one?"],
      ],
      choices: [
        "Sure, come to the workshop Saturday.",
        "I never make spoons.",
        "The workshop burned down.",
        "You can't use tools.",
        "I stopped doing that.",
      ],
      answer: 1,
      clue: "Could you show me how you start one?",
      explanation:
        "어떻게 시작하는지 보여 달라고 했으므로, 토요일에 작업실로 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 현빈아, 나무 숟가락을 만든다며.",
        "M: 지난겨울에 삼촌이 작업실에서 가르쳐 주셨어.",
        "W: 하나 만드는 데 얼마나 걸려?",
        "M: 나무가 무르면 네 시간쯤.",
        "W: 어떤 나무를 써?",
        "M: 벚나무. 잘 안 쪼개져서.",
        "W: 움푹한 부분 만들기가 어려워?",
        "M: 그 부분이 전체 시간의 절반이야.",
        "W: 지금까지 몇 개나 만들었어?",
        "M: 아홉 개. 그중 일곱 개는 나눠 줬어.",
        "W: 어떻게 시작하는지 보여 줄래?",
        "M: 그럼, 토요일에 작업실로 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaewon, how is the class farewell letter going?"],
        ["M", "You said everyone writes a line for the teacher."],
        ["W", "Only eleven students have written anything."],
        ["W", "The paper has been on my desk for a week."],
        ["M", "Do people know where to find it?"],
        ["W", "I told them once at the morning meeting."],
        ["M", "One announcement gets forgotten by lunch time."],
        ["W", "I didn't want to keep nagging everyone."],
        ["M", "Why don't you pass the paper around the rows?"],
      ],
      choices: [
        "I'll do that tomorrow.",
        "There is no paper.",
        "Everyone already wrote.",
        "I'll throw it away.",
        "Nobody likes the teacher.",
      ],
      answer: 1,
      clue: "Why don't you pass the paper around the rows?",
      explanation:
        "종이를 줄마다 돌리라는 제안이므로, 내일 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 채원아, 학급 편지는 잘돼 가?",
        "M: 다들 선생님께 한 줄씩 쓰기로 했잖아.",
        "W: 지금까지 열한 명만 썼어.",
        "W: 종이가 일주일째 내 책상에 있어.",
        "M: 어디 있는지 다들 알아?",
        "W: 아침 모임에서 한 번 말했어.",
        "M: 한 번 알려서는 점심때면 다 잊어버려.",
        "W: 계속 잔소리하고 싶지 않았어.",
        "M: 종이를 줄마다 돌리는 건 어때?",
        "W: 내일 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yuna가 Dongju에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yuna : ________________",
      lines: [
        [
          "W",
          "Yuna and Dongju are setting up for the club exhibition. " +
            "Dongju is about to hang a heavy frame on a single small nail. " +
            "Yuna can see the nail bending under the weight already. " +
            "The frame holds glass and hangs right above the visitors' bench. " +
            "She wants him to use a stronger hook before letting go. " +
            "In this situation, what would Yuna most likely say to Dongju?",
        ],
      ],
      choices: [
        "Hang it higher on the wall.",
        "The exhibition ended already.",
        "That nail is too weak for it.",
        "We need another frame.",
        "Move the bench outside.",
      ],
      answer: 3,
      clue: "She wants him to use a stronger hook before letting go.",
      explanation:
        "못이 무게에 휘고 있으므로, 그 못으로는 약하다는 ③이 가장 적절하다.",
      translation: [
        "W: 유나와 동주는 동아리 전시를 준비하고 있습니다. 동주는 무거운 액자를 작은 못 하나에 걸려고 합니다. 유나는 벌써 못이 무게에 휘는 것을 봅니다. 그 액자에는 유리가 들어 있고 관람객 의자 바로 위에 걸립니다. 그녀는 그가 손을 놓기 전에 더 튼튼한 걸이를 쓰기를 바랍니다. 이런 상황에서 유나가 동주에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
