/** 중3 듣기 27회 — 사람이 직접 쓴 회차 (2026-09-25) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 27회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 시계를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a watch?"],
        ["M", "Yes, one I can wear while I swim."],
        ["W", "We have watches with hands and ones with a digital screen."],
        ["M", "A digital screen, please. I need to read the seconds."],
        ["W", "All right. This digital one has a metal band."],
        ["M", "Metal rusts in pool water after a while."],
        ["W", "Then here is a digital one with a rubber band."],
        ["M", "That's the one. I'll take the rubber band watch."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "A digital screen, please. / I'll take the rubber band watch.",
      explanation:
        "남자는 숫자가 나오는 시계를 원하고, 금속 줄 대신 고무줄을 골랐다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five wristwatches drawn side by side as five choices, clean black line art on white, each shown flat with the band open. " +
          "① an ANALOG watch with two hands and a METAL LINK band. " +
          "② an ANALOG watch with two hands and a thick RUBBER band. " +
          "③ a DIGITAL watch showing a rectangular number screen and a METAL LINK band. " +
          "④ an ANALOG watch with two hands and a woven FABRIC band. " +
          "⑤ a DIGITAL watch showing a rectangular number screen and a thick RUBBER band.",
      },
      translation: [
        "W: 안녕하세요. 시계 찾으세요?",
        "M: 네, 수영할 때 찰 수 있는 걸로요.",
        "W: 바늘이 있는 것도 있고 숫자가 나오는 것도 있어요.",
        "M: 숫자가 나오는 걸로 주세요. 초를 봐야 해서요.",
        "W: 알겠습니다. 이 숫자 시계는 금속 줄이에요.",
        "M: 금속은 수영장 물에서 시간이 지나면 녹슬어요.",
        "W: 그럼 고무줄이 달린 숫자 시계가 여기 있어요.",
        "M: 그거예요. 고무줄 시계로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 해외 자매결연 프로그램에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Doeun, are you applying for the exchange program?"],
        ["W", "I'd like to. Which country do we visit?"],
        ["M", "Japan, a middle school near Osaka."],
        ["W", "How long do the students stay there?"],
        ["M", "Ten days, over the winter vacation."],
        ["W", "Where do our students sleep?"],
        ["M", "With host families, two students per home."],
        ["W", "What do we do during the day?"],
        ["M", "We join regular classes and visit local museums."],
      ],
      choices: ["방문 국가", "선발 인원", "머무는 기간", "숙박 방법", "낮 활동"],
      answer: 2,
      clue: "선발 인원은 대화에서 언급되지 않았다.",
      explanation:
        "방문 국가(일본 오사카 근처), 기간(겨울 방학 중 10일), 숙박(가정마다 두 명씩 홈스테이), 낮 활동(정규 수업과 박물관 방문)은 언급되지만 선발 인원은 언급되지 않았다. 따라서 답은 ②이다.",
      translation: [
        "M: 도은아, 교환 프로그램 지원할 거야?",
        "W: 하고 싶어. 어느 나라에 가?",
        "M: 일본, 오사카 근처 중학교에.",
        "W: 학생들이 거기서 얼마나 머물러?",
        "M: 겨울 방학 동안 열흘.",
        "W: 우리 학생들은 어디서 자?",
        "M: 홈스테이로, 한 집에 두 명씩.",
        "W: 낮에는 뭐 해?",
        "M: 정규 수업에 들어가고 지역 박물관을 둘러봐.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, is this the Sejong Community Hall?"],
        ["M", "Yes, it is. How may I help you?"],
        ["W", "Our club booked the small hall for this Saturday."],
        ["M", "Let me check. Under the name Doeun Lim?"],
        ["W", "That's right. Our performance was moved to Sunday."],
        ["M", "So you need the room on a different day?"],
        ["W", "Yes, could you change it to Sunday at the same hour?"],
        ["M", "Sunday afternoon is open. I've moved your booking."],
      ],
      choices: [
        "대관을 처음 신청하려고",
        "대관을 취소하려고",
        "대관료를 물어보려고",
        "회관 위치를 물어보려고",
        "대관 날짜를 바꾸려고",
      ],
      answer: 5,
      clue: "Yes, could you change it to Sunday at the same hour?",
      explanation:
        "여자는 공연이 일요일로 옮겨져 대관 날짜를 바꾸려고 전화했다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 여보세요, 세종 문화회관이죠?",
        "M: 네, 맞습니다. 무엇을 도와드릴까요?",
        "W: 저희 동아리가 이번 주 토요일에 소강당을 예약했어요.",
        "M: 확인해 볼게요. 임도은 님이시죠?",
        "W: 맞아요. 저희 공연이 일요일로 옮겨졌어요.",
        "M: 그럼 다른 날에 방이 필요하시군요?",
        "W: 네, 같은 시간으로 일요일에 바꿔 주실 수 있나요?",
        "M: 일요일 오후가 비어 있네요. 옮겨 드렸습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Doeun, what time does the art gallery close?"],
        ["W", "The doors close at seven in the evening."],
        ["M", "And when is the last entry?"],
        ["W", "An hour before closing, so we can't go in after six."],
        ["M", "How long does the special exhibit take to see?"],
        ["W", "About an hour and a half, if we read the captions."],
        ["M", "Then let's go in ninety minutes before the last entry."],
        ["W", "Good. I'll wait by the ticket machine."],
        ["M", "I'll bring the student cards for the discount."],
      ],
      choices: ["3:30 p.m.", "4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "6:00 p.m."],
      answer: 3,
      clue: "Then let's go in ninety minutes before the last entry.",
      explanation:
        "마지막 입장이 6시인데 그보다 90분 전에 들어가기로 했으므로 만나는 시각은 4시 30분이다. 따라서 답은 ③이다.",
      translation: [
        "M: 도은아, 미술관 몇 시에 닫아?",
        "W: 저녁 7시에 문을 닫아.",
        "M: 마지막 입장은 언제야?",
        "W: 닫기 한 시간 전, 그러니까 6시 넘으면 못 들어가.",
        "M: 특별전 보는 데 얼마나 걸려?",
        "W: 설명까지 읽으면 한 시간 반쯤.",
        "M: 그럼 마지막 입장 90분 전에 들어가자.",
        "W: 좋아. 나는 발권기 옆에서 기다릴게.",
        "M: 나는 할인받게 학생증 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiwon, you've been smiling at that envelope all lunch."],
        ["M", "The city youth orchestra accepted my application."],
        ["W", "The one you recorded in the music room at midnight?"],
        ["M", "Yes, and they only take four cellists a year."],
        ["W", "Four out of how many who applied?"],
        ["M", "More than sixty, my teacher said."],
        ["W", "That's incredible. When is the first rehearsal?"],
        ["M", "Next Saturday. I've already packed my music twice."],
      ],
      choices: ["delighted", "bored", "worried", "angry", "sleepy"],
      answer: 1,
      clue: "Next Saturday. I've already packed my music twice.",
      explanation:
        "60명 넘는 지원자 중 네 명에 뽑혔고 악보를 벌써 두 번이나 챙겼다고 했으므로 남자의 심정은 '기쁜(delighted)'이다. 따라서 답은 ①이다.",
      translation: [
        "W: 지원아, 점심 내내 그 봉투 보면서 웃네.",
        "M: 시 청소년 관현악단에서 내 지원을 받아 줬어.",
        "W: 한밤중에 음악실에서 녹음한 그거?",
        "M: 응, 한 해에 첼로는 네 명만 뽑아.",
        "W: 몇 명이 지원했는데 네 명이야?",
        "M: 선생님 말로는 예순 명 넘게.",
        "W: 대단하다. 첫 연습이 언제야?",
        "M: 다음 주 토요일. 악보를 벌써 두 번이나 챙겼어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Which way is the exit?"],
        ["M", "Straight ahead and to the left."],
        ["ANN", "Number two."],
        ["W", "How much is a locker for one day?"],
        ["M", "Two dollars."],
        ["ANN", "Number three."],
        ["W", "Is the pool open in the morning?"],
        ["M", "Yes, from six o'clock."],
        ["ANN", "Number four."],
        ["W", "Do I need my own towel?"],
        ["M", "Yes, we don't lend them out."],
        ["ANN", "Number five."],
        ["W", "Careful, the floor is slippery there."],
        ["M", "Thanks, I'll walk around it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Careful, the floor is slippery there.",
      explanation:
        "그림은 수영장 옆 젖은 바닥 쪽으로 걸어가는 남자를 여자가 손을 들어 멈추게 하며 알려 주는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "Beside an indoor swimming pool, clean black line art on a plain white background, no writing anywhere. " +
          "A large puddle of water spreads across the tiled floor in front of a man who is about to step into it. " +
          "A woman beside him raises one hand toward him and points down at the wet floor with the other. " +
          "Lane ropes in the water and a row of lockers are drawn simply in the background.",
      },
      translation: [
        "① W: 출구가 어느 쪽이에요? / M: 곧장 가서 왼쪽이요.",
        "② W: 사물함 하루에 얼마예요? / M: 2달러입니다.",
        "③ W: 수영장 아침에도 열어요? / M: 네, 6시부터요.",
        "④ W: 수건을 가져와야 하나요? / M: 네, 저희는 빌려드리지 않습니다.",
        "⑤ W: 조심하세요, 거기 바닥이 미끄러워요. / M: 고마워요, 돌아서 갈게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiwon, you take the subway to school, don't you?"],
        ["M", "Yes, I change lines at City Hall every morning."],
        ["W", "My aunt runs a shop right by that station."],
        ["M", "The flower shop near exit four?"],
        ["W", "That's the one. I left my jacket there on Sunday."],
        ["M", "And you can't get there before school?"],
        ["W", "Right. Could you pick it up on your way tomorrow?"],
        ["M", "Sure. I'll bring it to your classroom in the morning."],
      ],
      choices: ["지하철 같이 타기", "외투 찾아다 주기", "가게 위치 알려 주기", "꽃 사 오기", "이모께 전해 주기"],
      answer: 2,
      clue: "Right. Could you pick it up on your way tomorrow?",
      explanation:
        "여자는 이모 가게에 두고 온 외투를 등굣길에 찾아다 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 지원아, 너 지하철 타고 학교 오지?",
        "M: 응, 매일 아침 시청에서 갈아타.",
        "W: 우리 이모가 그 역 바로 옆에서 가게를 하셔.",
        "M: 4번 출구 근처 꽃집?",
        "W: 그거야. 일요일에 거기 외투를 두고 왔어.",
        "M: 학교 오기 전에 못 가는 거야?",
        "W: 맞아. 내일 오는 길에 찾아다 줄 수 있어?",
        "M: 그럼. 아침에 너희 교실로 갖다줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 학생회 선거에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The student council election will be held next month. " +
            "Voting takes place on the first Friday, during the fourth period. " +
            "Each class votes in its own classroom using a paper ballot. " +
            "Candidates must hand in their forms by this Wednesday. " +
            "Speeches will be broadcast over the school radio on Thursday. " +
            "Please think carefully before you cast your vote.",
        ],
      ],
      choices: ["투표하는 날", "투표하는 곳", "후보 등록 마감일", "연설이 전해지는 방법", "후보 자격"],
      answer: 5,
      clue: "후보 자격은 방송에서 언급되지 않았다.",
      explanation:
        "투표하는 날(첫째 금요일 4교시), 투표 장소(각 교실), 후보 등록 마감(이번 주 수요일), 연설 방법(학교 방송)은 언급되지만 후보 자격은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 학생회 선거가 다음 달에 열립니다. 투표는 첫째 금요일 4교시에 진행됩니다. 각 반은 자기 교실에서 종이 투표용지로 투표합니다. 후보는 이번 주 수요일까지 서류를 내야 합니다. 연설은 목요일에 학교 방송으로 전합니다. 투표하기 전에 신중히 생각해 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a job that keeps a city moving every single day. " +
            "The person sits high up in front of a very wide window. " +
            "They open two doors at each stop and watch the mirror carefully. " +
            "Passengers tap a card as they step on board. " +
            "They memorize a long route and repeat it many times a day.",
        ],
      ],
      choices: ["경찰관", "우체부", "버스 기사", "기관사", "택배 기사"],
      answer: 3,
      clue: "Passengers tap a card as they step on board.",
      explanation:
        "넓은 창 앞에 높이 앉아 정류장마다 문을 열고, 승객이 카드를 찍으며 타고, 정해진 노선을 하루에 여러 번 도는 사람은 버스 기사이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이 직업은 매일 도시를 움직이게 합니다. 이 사람은 아주 넓은 창문 앞 높은 자리에 앉습니다. 정류장마다 문 두 개를 열고 거울을 잘 살핍니다. 승객들은 올라타면서 카드를 찍습니다. 긴 노선을 외워 하루에 여러 번 반복합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Where did you leave the key?"],
        ["W", "The exam is on Thursday."],
        ["ANN", "Number two."],
        ["M", "How long have you played the cello?"],
        ["W", "Since I was eight years old."],
        ["ANN", "Number three."],
        ["M", "Would you mind turning down the volume?"],
        ["W", "Not at all, sorry about that."],
        ["ANN", "Number four."],
        ["M", "What did you think of the speech?"],
        ["W", "It was shorter than I expected."],
        ["ANN", "Number five."],
        ["M", "Are you going to the concert tonight?"],
        ["W", "Yes, I bought my ticket last week."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Where did you leave the key?",
      explanation:
        "열쇠를 어디에 뒀는지 묻는 말에 시험이 목요일이라고 답했으므로 ①의 대화가 어색하다. 따라서 답은 ①이다.",
      translation: [
        "① M: 열쇠 어디에 뒀어? / W: 시험은 목요일이야.",
        "② M: 첼로를 얼마나 쳤어? / W: 여덟 살 때부터.",
        "③ M: 소리 좀 줄여 줄래? / W: 그럼, 미안해.",
        "④ M: 그 연설 어땠어? / W: 생각보다 짧았어.",
        "⑤ M: 오늘 밤 공연 갈 거야? / W: 응, 지난주에 표 샀어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Doeun, the club concert starts in twenty minutes."],
        ["W", "I know. All the chairs are out and in rows."],
        ["M", "Good. Did you put the programs on every seat?"],
        ["W", "Yes, eighty of them during lunch."],
        ["M", "Great. But the stage lights are still off."],
        ["W", "The switch panel is locked in the control room."],
        ["M", "I have to tune the piano before the first piece."],
        ["W", "Then I'll get the control room key and turn them on."],
      ],
      choices: ["의자 놓기", "프로그램 나눠 두기", "피아노 조율하기", "조명 켜기", "관객 맞이하기"],
      answer: 4,
      clue: "Then I'll get the control room key and turn them on.",
      explanation:
        "조명 스위치가 잠긴 조정실에 있고 남자는 피아노를 조율해야 해서, 여자가 열쇠를 받아 조명을 켜겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 도은아, 동아리 음악회가 20분 뒤에 시작해.",
        "W: 알아. 의자는 다 꺼내서 줄 맞춰 놨어.",
        "M: 잘했다. 좌석마다 프로그램은 놨어?",
        "W: 응, 점심시간에 여든 부.",
        "M: 좋아. 그런데 무대 조명이 아직 꺼져 있어.",
        "W: 스위치판이 조정실에 잠겨 있어.",
        "M: 나는 첫 곡 전에 피아노를 조율해야 해.",
        "W: 그럼 내가 조정실 열쇠 받아서 조명 켤게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 사진관을 고르시오.",
      lines: [
        ["W", "Jiwon, which studio are you booking for the club photo?"],
        ["M", "Let me look at the five of them again."],
        ["W", "How many people need to fit in one shot?"],
        ["M", "Fourteen, so a studio for ten is too small."],
        ["W", "Okay. What about the price for the whole group?"],
        ["M", "Under a hundred thousand won. That's what we collected."],
        ["W", "Got it. Do you need the files the same day?"],
        ["M", "Yes, the yearbook deadline is that evening."],
        ["W", "Then only one studio on this list works."],
        ["M", "Good. I'll call them right after school."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Fourteen, so a studio for ten is too small.",
      explanation:
        "14명 이상이 들어가고, 10만 원 미만이며, 당일에 파일을 주는 곳을 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Capacity: 10 / Price: 80,000 won / Same-day files: Yes" },
          { no: 2, label: "②", value: "Capacity: 20 / Price: 95,000 won / Same-day files: Yes" },
          { no: 3, label: "③", value: "Capacity: 20 / Price: 120,000 won / Same-day files: Yes" },
          { no: 4, label: "④", value: "Capacity: 16 / Price: 90,000 won / Same-day files: No" },
          { no: 5, label: "⑤", value: "Capacity: 10 / Price: 60,000 won / Same-day files: No" },
        ],
      },
      translation: [
        "W: 지원아, 동아리 사진은 어느 사진관에 예약할 거야?",
        "M: 다섯 개 다시 볼게.",
        "W: 한 장에 몇 명이 들어가야 해?",
        "M: 열네 명이라 10인용은 너무 작아.",
        "W: 알겠어. 전체 가격은?",
        "M: 10만 원 미만. 우리가 모은 게 그만큼이야.",
        "W: 그렇구나. 파일을 당일에 받아야 해?",
        "M: 응, 졸업 앨범 마감이 그날 저녁이야.",
        "W: 그럼 이 목록에서 되는 건 하나뿐이야.",
        "M: 좋아. 방과 후에 바로 전화할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 동아리 발표회를 열 날짜를 고르시오.",
      lines: [
        ["W", "Jiwon, when should our club hold the showcase?"],
        ["M", "How about November 4th? That's next Tuesday."],
        ["W", "The auditorium is booked for the parent meeting."],
        ["M", "Then what about November 6th?"],
        ["W", "Our third graders have the mock exam on the 6th."],
        ["M", "Hmm. I'm free on November 14th."],
        ["W", "But the school festival week starts on the 11th."],
        ["M", "Oh, right. Then let's do it on November 8th."],
        ["W", "November 8th works. It's a Saturday, so more parents can come."],
        ["M", "Great. Let's send out the notice tomorrow."],
      ],
      choices: ["11월 4일", "11월 6일", "11월 11일", "11월 14일", "11월 8일"],
      answer: 5,
      clue: "Oh, right. Then let's do it on November 8th.",
      explanation:
        "4일에는 학부모 회의가, 6일에는 모의고사가 있고 11일부터 축제 주간이다. 두 사람은 11월 8일에 열기로 한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 지원아, 우리 동아리 발표회 언제 열까?",
        "M: 11월 4일 어때? 다음 주 화요일이야.",
        "W: 그날은 강당이 학부모 회의로 예약돼 있어.",
        "M: 그럼 11월 6일은?",
        "W: 6일에 3학년 모의고사가 있어.",
        "M: 음. 나는 11월 14일이 비어.",
        "W: 그런데 11일부터 축제 주간이 시작해.",
        "M: 아, 맞다. 그럼 11월 8일에 하자.",
        "W: 11월 8일 괜찮아. 토요일이라 학부모님도 더 오실 수 있어.",
        "M: 좋아. 내일 공지 보내자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Doeun, why are your fingers covered in tape?"],
        ["W", "I spent all Saturday at the school music room."],
        ["M", "Were you practicing for the concert again?"],
        ["W", "No, we restrung eight old guitars for the new club members."],
        ["M", "Eight guitars in one day sounds like a lot."],
        ["W", "It was. The strings cut into my fingers after the third one."],
        ["M", "Why did the guitars need new strings?"],
        ["W", "Nobody had changed them in about three years."],
      ],
      choices: ["연주 연습하기", "음악실 청소하기", "기타 줄 갈기", "신입 회원 뽑기", "악기 사 오기"],
      answer: 3,
      clue: "No, we restrung eight old guitars for the new club members.",
      explanation:
        "여자는 토요일에 음악실에서 낡은 기타 여덟 대의 줄을 새로 갈았다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 도은아, 손가락에 왜 테이프를 감았어?",
        "W: 토요일 내내 학교 음악실에 있었어.",
        "M: 또 공연 연습했어?",
        "W: 아니, 신입 부원들 쓸 낡은 기타 여덟 대의 줄을 갈았어.",
        "M: 하루에 여덟 대면 많은데.",
        "W: 그랬어. 세 대째부터 줄이 손가락에 파고들었어.",
        "M: 기타에 왜 새 줄이 필요했어?",
        "W: 3년쯤 아무도 안 갈았대.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school office. " +
            "A heavy snow warning has been issued for tomorrow morning. " +
            "School will start two hours later than usual, at ten o'clock. " +
            "The morning study period is cancelled for all grades. " +
            "Please check the school website tonight for any further change. " +
            "Take care on the roads, and stay warm.",
        ],
      ],
      choices: [
        "등교 시간 변경을 알리려고",
        "눈 치우기를 부탁하려고",
        "휴교를 알리려고",
        "아침 자습 신청을 안내하려고",
        "교통 안전 교육을 알리려고",
      ],
      answer: 1,
      clue: "School will start two hours later than usual, at ten o'clock.",
      explanation:
        "폭설 경보로 내일 등교가 두 시간 늦춰져 10시에 시작한다고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실입니다. 내일 오전에 대설 경보가 발령되었습니다. 등교가 평소보다 두 시간 늦은 10시로 늦춰집니다. 모든 학년의 아침 자습은 취소됩니다. 오늘 밤 학교 누리집에서 추가 변경이 있는지 확인해 주세요. 길 조심하시고 따뜻하게 지내세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the music shop. What can I get you?"],
        ["M", "Two sets of guitar strings and one tuner, please."],
        ["W", "A string set is thirteen dollars and the tuner is sixteen."],
        ["M", "So the total is forty-two dollars."],
        ["W", "That's right. Do you need a case as well?"],
        ["M", "No, thank you. I already have one."],
        ["W", "All right. School clubs get eight dollars off."],
        ["M", "That helps our budget. Here you are."],
      ],
      choices: ["$32", "$36", "$38", "$34", "$42"],
      answer: 4,
      clue: "All right. School clubs get eight dollars off.",
      explanation:
        "기타 줄 2세트 26달러와 조율기 16달러를 더하면 42달러이고, 동아리 할인 8달러를 빼면 34달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 악기점에 오신 걸 환영합니다. 무엇을 드릴까요?",
        "M: 기타 줄 두 세트랑 조율기 하나 주세요.",
        "W: 줄 한 세트는 13달러, 조율기는 16달러입니다.",
        "M: 그럼 모두 42달러네요.",
        "W: 맞습니다. 케이스도 필요하세요?",
        "M: 아니요, 괜찮아요. 이미 있어요.",
        "W: 알겠습니다. 학교 동아리는 8달러 할인됩니다.",
        "M: 예산에 도움이 되네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Doeun, you look worn out after every group project."],
        ["W", "I end up doing the parts nobody finished."],
        ["M", "Do you tell them when someone misses a deadline?"],
        ["W", "No, I just fix it myself the night before."],
        ["M", "Then nobody ever learns that they missed anything."],
        ["W", "I don't want to sound like I'm blaming them."],
        ["M", "You can say it without blaming anyone."],
        ["W", "How would I even start that conversation?"],
        ["M", "Ask in the group chat who can finish part three by Friday."],
      ],
      choices: [
        "Nobody is in my group.",
        "I'll ask that tomorrow.",
        "I never do group projects.",
        "Everyone finished on time.",
        "Let's drop the project.",
      ],
      answer: 2,
      clue: "Ask in the group chat who can finish part three by Friday.",
      explanation:
        "남자가 단체 대화방에 누가 금요일까지 세 번째 부분을 끝낼 수 있는지 물어보라고 했으므로, 내일 물어보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 도은아, 모둠 과제 끝나면 늘 지쳐 보여.",
        "W: 아무도 안 끝낸 부분을 결국 내가 해.",
        "M: 누가 마감을 놓치면 말은 해?",
        "W: 아니, 그냥 전날 밤에 내가 고쳐.",
        "M: 그럼 아무도 자기가 놓쳤다는 걸 모르지.",
        "W: 탓하는 것처럼 들리기 싫어.",
        "M: 아무도 탓하지 않고 말할 수 있어.",
        "W: 그 얘기를 어떻게 꺼내?",
        "M: 단체 대화방에 누가 금요일까지 세 번째 부분을 끝낼 수 있는지 물어봐.",
        "W: 내일 물어볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Jiwon, your glasses are always smudged these days."],
        ["M", "I wipe them on my shirt every morning."],
        ["W", "Cloth from a shirt has tiny hard fibers in it."],
        ["M", "So that's why there are fine scratches on the lens?"],
        ["W", "Exactly, and scratches never come out."],
        ["M", "I thought any soft cloth would be fine."],
        ["W", "Only a proper lens cloth is soft enough."],
        ["M", "Where do I get one of those?"],
        ["W", "Any glasses shop gives you one for free."],
      ],
      choices: [
        "My glasses are brand new.",
        "I never wear glasses.",
        "My shirt is very soft.",
        "I'll use paper towels instead.",
        "I'll stop by a shop tomorrow.",
      ],
      answer: 5,
      clue: "Any glasses shop gives you one for free.",
      explanation:
        "여자가 안경점에서 렌즈 천을 무료로 준다고 알려 주었으므로, 내일 들르겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 지원아, 요즘 네 안경이 늘 뿌옇네.",
        "M: 아침마다 셔츠에 닦아.",
        "W: 셔츠 천에는 아주 단단한 섬유가 섞여 있어.",
        "M: 그래서 렌즈에 잔 흠집이 난 거야?",
        "W: 그래, 그리고 흠집은 절대 안 없어져.",
        "M: 부드러운 천이면 다 괜찮은 줄 알았어.",
        "W: 전용 렌즈 천만 충분히 부드러워.",
        "M: 그건 어디서 구해?",
        "W: 안경점 아무 데나 가면 무료로 줘.",
        "M: 내일 안경점에 들를게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Jiwon, our recycling bin is full of the wrong things again."],
        ["M", "I saw three milk cartons in the plastic bin this morning."],
        ["W", "We explained the rules at the start of the term."],
        ["M", "Once, in a five-minute talk."],
        ["W", "So people have simply forgotten by November."],
        ["M", "And nothing at the bin reminds them."],
        ["W", "Then should we explain the rules again?"],
        ["M", "Explaining alone won't hold. Put the reminder where they stand."],
        ["W", "What kind of reminder do you mean?"],
        ["M", "A photo of each item taped above the matching bin."],
      ],
      choices: [
        "We have no recycling bins.",
        "Everyone remembers the rules.",
        "I'll print the photos tonight.",
        "Let's remove the bins.",
        "The rules were never explained.",
      ],
      answer: 3,
      clue: "A photo of each item taped above the matching bin.",
      explanation:
        "남자가 알맞은 통 위에 물건 사진을 붙이자고 했으므로, 오늘 밤 사진을 인쇄하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 지원아, 우리 재활용 통에 또 엉뚱한 게 가득해.",
        "M: 오늘 아침엔 플라스틱 통에 우유갑이 세 개 있었어.",
        "W: 학기 초에 규칙을 설명했잖아.",
        "M: 5분짜리 설명 한 번.",
        "W: 그러니 11월이면 다들 잊어버리지.",
        "M: 그리고 통 앞에 떠올릴 게 아무것도 없어.",
        "W: 그럼 규칙을 다시 설명해야 할까?",
        "M: 설명만으론 안 남아. 사람들이 서는 자리에 붙여야지.",
        "W: 어떤 걸 붙이자는 거야?",
        "M: 알맞은 통 위에 물건 사진을 하나씩 붙이는 거.",
        "W: 오늘 밤에 사진 인쇄할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Chaewon이 Sihu에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Chaewon : ________________",
      lines: [
        [
          "W",
          "Chaewon and Sihu are leaving the science lab after an experiment. " +
            "Sihu has packed his bag and is already walking toward the door. " +
            "Chaewon sees that the gas valve on his bench is still open. " +
            "The teacher told everyone to close the valve before leaving. " +
            "She wants to stop him before they both walk out. " +
            "In this situation, what would Chaewon most likely say to Sihu?",
        ],
      ],
      choices: [
        "Your gas valve is still open.",
        "Let's do the experiment again.",
        "The lab closes at six today.",
        "I'll carry your bag for you.",
        "We should open the window.",
      ],
      answer: 1,
      clue: "Chaewon sees that the gas valve on his bench is still open.",
      explanation:
        "시후의 실험대 가스 밸브가 아직 열려 있으므로, 그 사실을 알려 주는 ①이 가장 적절하다.",
      translation: [
        "W: 채원이와 시후는 실험이 끝난 뒤 과학실을 나서고 있습니다. 시후는 가방을 챙겨 이미 문 쪽으로 걸어가고 있습니다. 채원이는 시후의 실험대 가스 밸브가 아직 열려 있는 것을 봅니다. 선생님은 나가기 전에 밸브를 잠그라고 모두에게 말씀하셨습니다. 채원이는 둘 다 나가기 전에 말리고 싶습니다. 이런 상황에서 채원이가 시후에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
