/** 중3 듣기 44회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 44회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 만들 상장을 고르시오.",
      lines: [
        ["M", "Hyejin, how should the club certificate look?"],
        ["W", "Something simple that we can print ourselves."],
        ["M", "Do you want a frame line around the paper?"],
        ["W", "Yes, a thin single line along the edge."],
        ["M", "Where should the club seal go?"],
        ["W", "In the bottom right corner, not the middle."],
        ["M", "Are you adding a ribbon at the top?"],
        ["W", "No ribbon. The printer can't handle it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Yes, a thin single line along the edge. / In the bottom right corner, not the middle.",
      explanation:
        "가는 테두리 한 줄에 도장이 오른쪽 아래에 있고 리본은 없는 상장이다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five blank certificates side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a certificate with a THIN SINGLE BORDER line and a round SEAL in the CENTER, no ribbon. " +
          "② a certificate with a THIN SINGLE BORDER line and a round SEAL in the BOTTOM RIGHT corner, no ribbon. " +
          "③ a certificate with a THIN SINGLE BORDER line, a round SEAL in the BOTTOM RIGHT corner and a RIBBON at the top. " +
          "④ a certificate with NO BORDER and a round SEAL in the BOTTOM RIGHT corner. " +
          "⑤ a certificate with a THICK DOUBLE BORDER and a round SEAL in the BOTTOM RIGHT corner.",
      },
      translation: [
        "M: 혜진아, 동아리 상장은 어떻게 만들까?",
        "W: 우리가 직접 뽑을 수 있게 단순한 걸로.",
        "M: 종이 둘레에 테두리 선을 넣을까?",
        "W: 응, 가장자리에 가는 선 한 줄.",
        "M: 동아리 도장은 어디에 찍어?",
        "W: 가운데 말고 오른쪽 아래 구석에.",
        "M: 위에 리본도 넣어?",
        "W: 리본은 안 돼. 인쇄기가 못 뽑아.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 고등학교 설명회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Dohyun, are you going to the high school briefing next week?"],
        ["M", "I have to go. When is it exactly?"],
        ["W", "Next Wednesday evening, starting at seven o'clock."],
        ["M", "Where in the school do they hold it?"],
        ["W", "In the gymnasium, because so many people come."],
        ["M", "Can our parents come along with us?"],
        ["W", "One parent per student is allowed to attend."],
        ["M", "My mother will want to hear it herself."],
        ["W", "Then she should come straight from work."],
        ["M", "What do the speakers actually talk about?"],
        ["W", "Admission dates and the subjects each school offers."],
      ],
      choices: ["열리는 날과 시각", "열리는 장소", "함께 갈 수 있는 사람", "다루는 내용", "신청 방법"],
      answer: 5,
      clue: "Next Wednesday evening, starting at seven o'clock.",
      explanation:
        "날짜, 장소, 동반자, 내용은 말했지만 신청 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 다음 주 고등학교 설명회 갈 거야?",
        "M: 가야지. 정확히 언제야?",
        "W: 다음 주 수요일 저녁 일곱 시부터.",
        "M: 학교 어디서 해?",
        "W: 사람이 워낙 많이 와서 체육관에서.",
        "M: 부모님도 같이 가도 돼?",
        "W: 학생 한 명당 보호자 한 분씩 오실 수 있어.",
        "M: 우리 어머니는 직접 들으려고 하실 거야.",
        "W: 그럼 퇴근하고 바로 오시면 되겠다.",
        "M: 강연에서 무슨 얘기를 해?",
        "W: 입학 일정이랑 학교마다 어떤 과목이 있는지.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, this is the youth center front desk."],
        ["M", "Hello. My name is Kiseok Yoon."],
        ["W", "How may I help you?"],
        ["M", "I left something in the study room yesterday."],
        ["W", "What did you leave behind?"],
        ["M", "A grey notebook with a blue sticker on it."],
        ["W", "Was it on a desk or on the floor?"],
        ["M", "On the desk by the window, I think."],
        ["W", "Let me check the lost and found box."],
        ["M", "I'm calling to ask if my notebook was found."],
      ],
      choices: [
        "잃어버린 물건을 찾으려고",
        "자리를 예약하려고",
        "수업을 신청하려고",
        "회원증을 만들려고",
        "이용 시간을 물어보려고",
      ],
      answer: 1,
      clue: "I'm calling to ask if my notebook was found.",
      explanation:
        "남자는 두고 온 공책을 찾으려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요, 청소년 센터 안내대입니다.",
        "M: 안녕하세요. 저는 윤기석입니다.",
        "W: 무엇을 도와드릴까요?",
        "M: 어제 열람실에 물건을 두고 왔어요.",
        "W: 무엇을 두고 가셨나요?",
        "M: 파란 스티커가 붙은 회색 공책이요.",
        "W: 책상 위였나요, 바닥이었나요?",
        "M: 창가 책상 위였던 것 같아요.",
        "W: 분실물 상자를 확인해 볼게요.",
        "M: 제 공책이 들어왔는지 여쭈려고 전화했어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 연습을 시작할 시각을 고르시오.",
      lines: [
        ["M", "Areum, when can we practice the duet today?"],
        ["W", "The music room is free from four o'clock."],
        ["M", "My tutoring ends at four fifteen."],
        ["W", "Then four is too early for you."],
        ["M", "Could we start at four thirty?"],
        ["W", "I need fifteen minutes to set up the stands."],
        ["M", "So you'll be ready by four thirty anyway."],
        ["W", "Then let's begin at four thirty."],
        ["M", "I'll bring the sheet music with me."],
      ],
      choices: ["4:00 p.m.", "4:15 p.m.", "4:30 p.m.", "4:45 p.m.", "5:00 p.m."],
      answer: 3,
      clue: "Then let's begin at four thirty.",
      explanation:
        "과외가 4시 15분에 끝나 4시 30분에 연습을 시작하기로 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 아름아, 오늘 이중창 언제 연습할까?",
        "W: 음악실이 네 시부터 비어.",
        "M: 내 과외가 네 시 15분에 끝나.",
        "W: 그럼 네 시는 너한테 이르네.",
        "M: 네 시 반에 시작할 수 있을까?",
        "W: 나는 보면대 놓는 데 15분이 필요해.",
        "M: 그럼 어차피 네 시 반이면 준비되겠다.",
        "W: 그럼 네 시 반에 시작하자.",
        "M: 악보는 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Wonbin, why are you sitting out here by yourself?"],
        ["M", "I forgot my whole part in front of the class."],
        ["W", "During the English presentation this morning?"],
        ["M", "I just stood there for almost a full minute."],
        ["W", "Did the teacher say anything to you?"],
        ["M", "She waited quietly and then moved on."],
        ["W", "Did anyone in the class laugh at you?"],
        ["M", "Nobody laughed, but I could feel them all watching."],
        ["W", "Everyone forgets a line at some point."],
        ["M", "I want to disappear for a whole week."],
      ],
      choices: ["excited", "proud", "embarrassed", "bored", "satisfied"],
      answer: 3,
      clue: "I want to disappear for a whole week.",
      explanation:
        "발표에서 대사를 잊어 창피해하고 있다. 따라서 답은 ③이다.",
      translation: [
        "W: 원빈아, 왜 여기 혼자 앉아 있어?",
        "M: 반 전체 앞에서 내 차례를 통째로 까먹었어.",
        "W: 오늘 아침 영어 발표 때?",
        "M: 꼬박 1분을 그냥 서 있었어.",
        "W: 선생님이 뭐라고 하셨어?",
        "M: 조용히 기다리시다가 그냥 넘어가셨어.",
        "W: 반에서 누가 웃었어?",
        "M: 웃는 사람은 없었는데, 다들 보는 게 느껴졌어.",
        "W: 누구나 언젠가는 대사를 잊어버려.",
        "M: 일주일쯤 통째로 사라지고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Is this the right line for the bus?"],
        ["M", "Yes, it goes downtown."],
        ["ANN", "Number two."],
        ["W", "Could you let me off at the next stop?"],
        ["M", "Press the button beside you."],
        ["ANN", "Number three."],
        ["W", "Excuse me, your bag is open."],
        ["M", "Oh, thank you for telling me."],
        ["ANN", "Number four."],
        ["W", "How much is the fare?"],
        ["M", "One thousand five hundred won."],
        ["ANN", "Number five."],
        ["W", "Do I need to transfer?"],
        ["M", "No, this bus goes all the way."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, your bag is open.",
      explanation:
        "그림은 열린 가방을 알려 주자 고마워하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "At a crowded bus stop, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A girl leans slightly forward and points at a boy's backpack, whose top flap hangs wide open with a book sticking out. " +
          "The boy twists around to look at his own bag and raises one hand in thanks. " +
          "A bus shelter bench and other waiting people are drawn simply behind them.",
      },
      translation: [
        "① W: 버스 줄이 여기 맞나요? / M: 네, 시내로 갑니다.",
        "② W: 다음 정류장에서 내려 주시겠어요? / M: 옆에 있는 단추를 누르세요.",
        "③ W: 저기요, 가방이 열렸어요. / M: 아, 알려 주셔서 고맙습니다.",
        "④ W: 요금이 얼마예요? / M: 1,500원입니다.",
        "⑤ W: 갈아타야 하나요? / M: 아니요, 이 버스가 끝까지 갑니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seongjun, you're good with the school computers."],
        ["M", "I spend most lunch times in that room."],
        ["W", "Our class is submitting a video contest entry."],
        ["M", "When is the deadline for it?"],
        ["W", "Tonight at midnight, through their website."],
        ["M", "Is the file ready to upload?"],
        ["W", "It's ready, but the site keeps rejecting the format."],
        ["M", "That usually means it needs a different file type."],
        ["W", "Could you change the file type for us?"],
        ["M", "Send it to me and I'll do it after class."],
      ],
      choices: [
        "영상을 찍어 주기",
        "파일 형식을 바꿔 주기",
        "컴퓨터를 빌려주기",
        "대회를 알아봐 주기",
        "자료를 출력해 주기",
      ],
      answer: 2,
      clue: "Could you change the file type for us?",
      explanation:
        "여자는 파일 형식을 바꿔 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "W: 성준아, 너 학교 컴퓨터 잘 다루잖아.",
        "M: 점심시간 대부분을 그 방에서 보내.",
        "W: 우리 반이 영상 대회에 작품을 내.",
        "M: 마감이 언제야?",
        "W: 오늘 밤 열두 시, 누리집으로.",
        "M: 파일은 올릴 준비가 됐어?",
        "W: 준비는 됐는데 형식이 안 맞는다고 계속 튕겨.",
        "M: 보통 그러면 다른 형식이어야 해.",
        "W: 파일 형식 좀 바꿔 줄 수 있어?",
        "M: 보내 줘. 수업 끝나고 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 겨울 방학 자율 학습실 운영에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The study room opens during the winter vacation. " +
            "It runs from the fifth of January to the thirtieth. " +
            "The room is open from nine in the morning until five. " +
            "Forty seats are available on a first come basis. " +
            "Bring your own study materials and a water bottle. " +
            "Eating meals inside the room is not allowed.",
        ],
      ],
      choices: ["운영 기간", "이용 시간", "자리 수", "가져올 것", "신청하는 곳"],
      answer: 5,
      clue: "It runs from the fifth of January to the thirtieth.",
      explanation:
        "기간, 시간, 자리 수, 준비물은 말했지만 신청하는 곳은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 겨울 방학 동안 자율 학습실을 엽니다. 1월 5일부터 30일까지 운영합니다. 오전 아홉 시부터 오후 다섯 시까지 열려 있습니다. 자리는 마흔 개이고 오는 순서대로 앉습니다. 공부할 자료와 물병은 각자 가져오세요. 학습실 안에서 식사는 할 수 없습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This machine washes the dishes after a meal. " +
            "You stack the plates inside and close the door. " +
            "It uses hot water and takes about an hour. " +
            "Families with many members save a lot of time with it. " +
            "You still have to rinse off the big pieces first.",
        ],
      ],
      choices: ["세탁기", "식기세척기", "냉장고", "전자레인지", "청소기"],
      answer: 2,
      clue: "This machine washes the dishes after a meal.",
      explanation:
        "그릇을 넣고 문을 닫으면 설거지를 해 주는 것은 식기세척기이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이 기계는 식사 뒤에 그릇을 씻어 줍니다. 접시를 안에 쌓아 넣고 문을 닫습니다. 뜨거운 물을 쓰고 한 시간쯤 걸립니다. 식구가 많은 집은 이것으로 시간을 많이 아낍니다. 큰 찌꺼기는 먼저 헹궈 내야 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How long have you lived here?"],
        ["W", "Since I was six."],
        ["ANN", "Number two."],
        ["M", "Do you need a hand with that box?"],
        ["W", "Yes, it's heavier than it looks."],
        ["ANN", "Number three."],
        ["M", "Where did you get that idea?"],
        ["W", "From a documentary last night."],
        ["ANN", "Number four."],
        ["M", "What time does the shop open?"],
        ["W", "My brother plays the drums."],
        ["ANN", "Number five."],
        ["M", "Shall we walk or take the subway?"],
        ["W", "The subway is faster today."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "What time does the shop open?",
      explanation:
        "가게 여는 시각을 묻는 말에 동생 이야기를 했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 여기 얼마나 오래 살았어? / W: 여섯 살 때부터.",
        "② M: 그 상자 들어 줄까? / W: 응, 보기보다 무거워.",
        "③ M: 그 생각 어디서 얻었어? / W: 어젯밤 기록 영화에서.",
        "④ M: 가게 몇 시에 열어? / W: 우리 동생은 드럼을 쳐.",
        "⑤ M: 걸어갈까, 지하철 탈까? / W: 오늘은 지하철이 빨라.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junyoung, the club fair opens in twenty minutes."],
        ["M", "The table and the banner are already up."],
        ["W", "Did anyone bring the sample projects?"],
        ["M", "They're in the science room cabinet."],
        ["W", "Visitors decide by looking at those."],
        ["M", "The cabinet is only two floors up."],
        ["W", "I'll stay and set out the chairs."],
        ["M", "I'll go and bring the sample projects."],
      ],
      choices: [
        "의자를 놓기",
        "현수막을 걸기",
        "작품을 가져오기",
        "방문객을 맞이하기",
        "탁자를 옮기기",
      ],
      answer: 3,
      clue: "I'll go and bring the sample projects.",
      explanation:
        "남자는 과학실에 있는 작품을 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 준영아, 동아리 박람회가 20분 뒤에 열어.",
        "M: 탁자랑 현수막은 벌써 다 했어.",
        "W: 견본 작품은 누가 가져왔어?",
        "M: 과학실 보관함에 있어.",
        "W: 방문객들은 그걸 보고 정해.",
        "M: 보관함은 두 층만 올라가면 돼.",
        "W: 나는 남아서 의자를 놓을게.",
        "M: 내가 가서 견본 작품을 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 고를 독서실 자리를 고르시오.",
      lines: [
        ["W", "Taeyang, which study room seat will you take?"],
        ["M", "Five seats are open for next month."],
        ["W", "How much can you pay each month?"],
        ["M", "Under a hundred thousand won for sure."],
        ["W", "One of them is well above that."],
        ["M", "I also want a seat by the window."],
        ["W", "Two of these are in the middle row."],
        ["M", "And it has to be on the first floor."],
        ["W", "I know you hate climbing stairs with that bag."],
        ["M", "Then only one seat is left for me."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Under a hundred thousand won for sure.",
      explanation:
        "10만 원 미만, 창가, 1층인 자리는 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Fee: 120,000 won / Spot: Window / Floor: 1st" },
          { no: 2, label: "②", value: "Fee: 90,000 won / Spot: Middle / Floor: 1st" },
          { no: 3, label: "③", value: "Fee: 85,000 won / Spot: Middle / Floor: 2nd" },
          { no: 4, label: "④", value: "Fee: 95,000 won / Spot: Window / Floor: 1st" },
          { no: 5, label: "⑤", value: "Fee: 80,000 won / Spot: Window / Floor: 2nd" },
        ],
      },
      translation: [
        "W: 태양아, 독서실 자리 어떤 걸로 할 거야?",
        "M: 다음 달에 다섯 자리가 나와.",
        "W: 한 달에 얼마까지 낼 수 있어?",
        "M: 무조건 10만 원 미만.",
        "W: 하나는 그보다 훨씬 비싸네.",
        "M: 그리고 창가 자리였으면 좋겠어.",
        "W: 이 중 두 개는 가운데 줄이야.",
        "M: 그리고 1층이어야 해.",
        "W: 그 가방 메고 계단 오르는 거 싫어하지.",
        "M: 그럼 나한테는 한 자리만 남네.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Minseo, when are we going to the children's center?"],
        ["M", "They offered us three Saturdays this month."],
        ["W", "Which dates did they give?"],
        ["M", "The seventh, the fourteenth and the twenty-first."],
        ["W", "The seventh is the high school briefing day."],
        ["M", "We can't miss that one."],
        ["W", "And the twenty-first is right before the exam."],
        ["M", "Then the fourteenth is the only day left."],
        ["W", "They want us there from two until four."],
        ["M", "I'll confirm the fourteenth tonight."],
      ],
      choices: ["the 7th", "the 14th", "the 21st", "the 4th", "the 28th"],
      answer: 2,
      clue: "Then the fourteenth is the only day left.",
      explanation:
        "7일은 설명회, 21일은 시험 직전이어서 14일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 민서야, 아동 센터에 언제 가?",
        "M: 이번 달에 토요일 세 번을 주셨어.",
        "W: 어떤 날짜야?",
        "M: 7일, 14일, 21일.",
        "W: 7일은 고등학교 설명회 날이야.",
        "M: 그건 빠질 수 없지.",
        "W: 21일은 시험 바로 전이고.",
        "M: 그럼 남는 날은 14일뿐이네.",
        "W: 두 시부터 네 시까지 와 달라고 하셨어.",
        "M: 오늘 밤에 14일로 확정할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, how did you spend the weekend?"],
        ["W", "I cleaned out my closet from top to bottom."],
        ["M", "That doesn't sound like much fun."],
        ["W", "I found clothes I hadn't worn in three years."],
        ["M", "What did you do with them?"],
        ["W", "I took two bags to the donation box."],
        ["M", "How long did the whole thing take?"],
        ["W", "Almost six hours over two days."],
        ["M", "Does the room feel different now?"],
        ["W", "I can finally close the closet door."],
      ],
      choices: [
        "옷장을 정리했다",
        "옷을 샀다",
        "친구를 만났다",
        "여행을 다녀왔다",
        "집에서 쉬었다",
      ],
      answer: 1,
      clue: "I cleaned out my closet from top to bottom.",
      explanation:
        "여자는 지난 주말에 옷장을 정리했다. 따라서 답은 ①이다.",
      translation: [
        "M: 예린아, 주말 어떻게 보냈어?",
        "W: 옷장을 위에서 아래까지 싹 정리했어.",
        "M: 별로 재미있을 것 같지 않은데.",
        "W: 3년 동안 안 입은 옷이 나왔어.",
        "M: 그건 어떻게 했어?",
        "W: 두 봉지를 기부함에 가져갔어.",
        "M: 전부 얼마나 걸렸어?",
        "W: 이틀에 걸쳐 거의 여섯 시간.",
        "M: 이제 방이 달라 보여?",
        "W: 드디어 옷장 문이 닫혀.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school library. " +
            "The reading room will be closed next Monday and Tuesday. " +
            "New shelves are being installed on both floors. " +
            "You may still return books at the outside box. " +
            "Borrowing starts again on Wednesday morning. " +
            "Please plan your study place for those two days. " +
            "Thank you for understanding.",
        ],
      ],
      choices: [
        "도서 반납을 당부하려고",
        "독서 행사를 안내하려고",
        "열람실 휴실을 알리려고",
        "봉사자를 모으려고",
        "새 책을 소개하려고",
      ],
      answer: 3,
      clue: "The reading room will be closed next Monday and Tuesday.",
      explanation:
        "서가 공사로 열람실이 이틀 문을 닫는다고 알리는 방송이다. 따라서 답은 ③이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 학교 도서관입니다. 다음 주 월요일과 화요일에 열람실 문을 닫습니다. 두 층 모두 새 서가를 설치합니다. 책 반납은 바깥 반납함에서 하실 수 있습니다. 대출은 수요일 아침부터 다시 됩니다. 그 이틀 동안 공부할 자리를 미리 정해 두세요. 양해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome. What would you like to buy?"],
        ["M", "Two workbooks and three pens, please."],
        ["W", "Workbooks are seven dollars each."],
        ["M", "Is that the price after the discount?"],
        ["W", "Yes, they were nine dollars last month."],
        ["M", "And how much are the pens?"],
        ["W", "One dollar each this week."],
        ["M", "Do I pay extra for a bag?"],
        ["W", "The bag is free with any purchase."],
        ["M", "Good. Here is my card."],
      ],
      choices: ["$15", "$16", "$17", "$18", "$19"],
      answer: 3,
      clue: "Workbooks are seven dollars each.",
      explanation:
        "문제집 두 권 14달러와 펜 세 자루 3달러를 더하면 17달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 어서 오세요. 무엇을 사시겠어요?",
        "M: 문제집 두 권이랑 펜 세 자루 주세요.",
        "W: 문제집은 한 권에 7달러입니다.",
        "M: 할인된 값인가요?",
        "W: 네, 지난달에는 9달러였습니다.",
        "M: 펜은 얼마예요?",
        "W: 이번 주에는 한 자루에 1달러입니다.",
        "M: 봉투 값도 내야 하나요?",
        "W: 무엇이든 사시면 봉투는 무료입니다.",
        "M: 좋네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sangmin, you never seem to fall behind in science."],
        ["M", "I read the next page before the class starts."],
        ["W", "Just one page, not the whole chapter?"],
        ["M", "One page tells me what the lesson is about."],
        ["W", "I always hear new words for the first time in class."],
        ["M", "That's why the first ten minutes feel hard."],
        ["W", "And by then I've already lost the thread."],
        ["M", "Knowing two or three words changes everything."],
        ["W", "When should I read that page?"],
      ],
      choices: [
        "During the test itself.",
        "The night before class.",
        "Never read anything early.",
        "After the semester ends.",
        "Read ten chapters tonight.",
      ],
      answer: 2,
      clue: "When should I read that page?",
      explanation:
        "언제 읽어야 하는지 물었으므로, 수업 전날 밤이라는 ②가 가장 자연스럽다.",
      translation: [
        "W: 상민아, 너는 과학에서 뒤처지는 법이 없네.",
        "M: 수업 시작 전에 다음 쪽을 읽어.",
        "W: 단원 전체가 아니라 한 쪽만?",
        "M: 한 쪽이면 오늘 수업이 뭔지 알 수 있어.",
        "W: 나는 새 낱말을 수업에서 처음 들어.",
        "M: 그래서 처음 10분이 어렵게 느껴지는 거야.",
        "W: 그때쯤이면 이미 흐름을 놓쳐.",
        "M: 낱말 두세 개만 알아도 완전히 달라져.",
        "W: 그 한 쪽을 언제 읽으면 좋을까?",
        "M: 수업 전날 밤에.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sohee, I heard you write a blog about old buildings."],
        ["W", "I started after a trip to Jeonju last year."],
        ["M", "How often do you put up a new post?"],
        ["W", "Once every two weeks, usually on Sunday."],
        ["M", "Where do you find the information?"],
        ["W", "City records and signs at the buildings themselves."],
        ["M", "Do many people read it?"],
        ["W", "About two hundred visits a month now."],
        ["M", "Do you take the photographs yourself?"],
        ["W", "Every single one, with my father's camera."],
        ["M", "Could you show me how you start a post?"],
      ],
      choices: [
        "Sure, come over on Sunday.",
        "I deleted the blog.",
        "I never take photos.",
        "You can't read it.",
        "I stopped writing it.",
      ],
      answer: 1,
      clue: "Could you show me how you start a post?",
      explanation:
        "글을 어떻게 시작하는지 보여 달라고 했으므로, 일요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 소희야, 옛 건물에 대한 블로그를 쓴다며.",
        "W: 작년에 전주에 다녀온 뒤로 시작했어.",
        "M: 새 글은 얼마나 자주 올려?",
        "W: 두 주에 한 번, 보통 일요일에.",
        "M: 자료는 어디서 찾아?",
        "W: 시 기록이랑 건물에 붙은 안내판에서.",
        "M: 읽는 사람이 많아?",
        "W: 요즘은 한 달에 200번쯤 들어와.",
        "M: 사진도 직접 찍어?",
        "W: 전부 다, 아버지 사진기로.",
        "M: 글을 어떻게 시작하는지 보여 줄래?",
        "W: 그럼, 일요일에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, how is your running club going this season?"],
        ["W", "You said you wanted to finish ten kilometers."],
        ["M", "My knees hurt after every long run."],
        ["W", "How far do you go each time?"],
        ["M", "Eight kilometers, three times a week."],
        ["W", "Did you jump straight to that distance?"],
        ["M", "I went from three to eight in one month."],
        ["W", "That's a big jump for your knees."],
        ["M", "I thought more distance meant faster progress."],
        ["W", "Why don't you add one kilometer a week instead?"],
      ],
      choices: [
        "I'll try that from Monday.",
        "I never run at all.",
        "I'll run twenty kilometers.",
        "My knees never hurt.",
        "I quit the club already.",
      ],
      answer: 1,
      clue: "Why don't you add one kilometer a week instead?",
      explanation:
        "일주일에 1킬로미터씩 늘리라는 제안이므로, 월요일부터 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 이번 철 달리기 동아리는 어때?",
        "W: 10킬로미터를 완주하고 싶다고 했잖아.",
        "M: 길게 뛸 때마다 무릎이 아파.",
        "W: 한 번에 얼마나 뛰어?",
        "M: 8킬로미터, 일주일에 세 번.",
        "W: 그 거리로 바로 올렸어?",
        "M: 한 달 만에 3킬로에서 8킬로로 갔어.",
        "W: 무릎한테는 너무 큰 걸음이야.",
        "M: 거리를 늘리면 빨리 는다고 생각했어.",
        "W: 대신 일주일에 1킬로미터씩 늘리는 건 어때?",
        "M: 월요일부터 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Nayun이 Kihoon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Nayun : ________________",
      lines: [
        [
          "W",
          "Nayun and Kihoon are finishing the group report in the computer room. " +
            "Kihoon is about to close the file without saving his last part. " +
            "Nayun sees that he typed two new pages in the past hour. " +
            "The computers in that room erase everything when they shut down. " +
            "She wants him to save the file before he closes it. " +
            "In this situation, what would Nayun most likely say to Kihoon?",
        ],
      ],
      choices: [
        "Save the file first.",
        "Let's write two more pages.",
        "The report is due next month.",
        "Turn off the computer now.",
        "You should delete that part.",
      ],
      answer: 1,
      clue: "She wants him to save the file before he closes it.",
      explanation:
        "저장하지 않고 파일을 닫으려 하므로, 먼저 저장하라는 ①이 가장 적절하다.",
      translation: [
        "W: 나윤이와 기훈이는 컴퓨터실에서 조별 보고서를 마무리하고 있습니다. 기훈이는 마지막 부분을 저장하지 않고 파일을 닫으려고 합니다. 나윤이는 그가 지난 한 시간 동안 두 쪽을 새로 썼다는 것을 압니다. 그 방 컴퓨터는 꺼지면 모든 것이 지워집니다. 그녀는 그가 닫기 전에 파일을 저장하기를 바랍니다. 이런 상황에서 나윤이가 기훈이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
