/** 중3 듣기 16회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 16회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 여행 가방을 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a suitcase?"],
        ["M", "Yes, for a school trip next month."],
        ["W", "We have ones with two wheels and ones with four."],
        ["M", "Four wheels, please. It's easier to push in a crowd."],
        ["W", "Of course. Do you want a hard shell or a soft one?"],
        ["M", "A hard shell. My last soft one tore at the corner."],
        ["W", "Then two are left. One has an outside pocket and one doesn't."],
        ["M", "I'll take the one without a pocket. It looks cleaner."],
        ["W", "Good choice. This one also has a lock built into the zip."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'll take the one without a pocket. It looks cleaner.",
      explanation:
        "남자는 바퀴가 네 개이고 겉이 단단하며 바깥 주머니가 없는 가방을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five suitcases shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a suitcase with TWO wheels at the bottom, a SOFT fabric body with visible seams, and no outside pocket. " +
          "Second: a suitcase with TWO wheels at the bottom, a HARD smooth shell with straight grooves, and a flat OUTSIDE POCKET on the front. " +
          "Third: a suitcase with FOUR small wheels, one at each corner, a SOFT fabric body, and a flat OUTSIDE POCKET on the front. " +
          "Fourth: a suitcase with FOUR small wheels, one at each corner, a HARD smooth shell with straight grooves, and a flat OUTSIDE POCKET on the front. " +
          "Fifth: a suitcase with FOUR small wheels, one at each corner, a HARD smooth shell with straight grooves, and NO outside pocket at all.",
      },
      translation: [
        "W: 안녕하세요. 여행 가방 찾으세요?",
        "M: 네, 다음 달 수학여행에 쓸 거예요.",
        "W: 바퀴가 두 개인 것과 네 개인 것이 있습니다.",
        "M: 네 개짜리로요. 사람 많은 데서 밀기 편해서요.",
        "W: 네. 겉이 단단한 것과 천으로 된 것 중 어느 쪽이 좋으세요?",
        "M: 단단한 걸로요. 전에 쓰던 천 가방은 모서리가 찢어졌어요.",
        "W: 그럼 두 개 남았네요. 하나는 바깥 주머니가 있고 하나는 없습니다.",
        "M: 주머니 없는 걸로 할게요. 더 깔끔해 보여요.",
        "W: 좋은 선택이세요. 이건 지퍼에 잠금장치도 달려 있습니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 과학 발표회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Chaewon, are you presenting at the science fair?"],
        ["W", "I want to, but I only saw the title on the board."],
        ["M", "It's on the second Thursday of next month, all afternoon."],
        ["W", "A whole afternoon. Where does it happen?"],
        ["M", "In the gym. They set up forty tables around the edge."],
        ["W", "How long does each team present?"],
        ["M", "Eight minutes, and then four minutes of questions."],
        ["W", "Do we apply as a team or alone?"],
        ["M", "Teams of two or three. You can't enter alone this year."],
        ["W", "Then I'll ask Sora and Minho today."],
        ["M", "Do it soon. The tables filled up in three days last year."],
      ],
      choices: ["열리는 날", "장소", "발표 시간", "참가 방식", "심사 기준"],
      answer: 5,
      clue: "Teams of two or three. You can't enter alone this year.",
      explanation:
        "날짜(다음 달 둘째 목요일), 장소(체육관), 발표 시간(8분과 질문 4분), 참가 방식(2~3인 팀)은 언급되지만 심사 기준은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 채원아, 과학 발표회에 나갈 거야?",
        "W: 나가고 싶은데 게시판에서 제목만 봤어.",
        "M: 다음 달 둘째 목요일, 오후 내내 해.",
        "W: 오후 내내구나. 어디서 하는데?",
        "M: 체육관에서. 가장자리에 탁자를 마흔 개 놓는대.",
        "W: 팀마다 몇 분씩 발표해?",
        "M: 8분, 그리고 질문 4분.",
        "W: 팀으로 신청해, 아니면 혼자?",
        "M: 2인이나 3인 팀. 올해는 혼자서는 못 나가.",
        "W: 그럼 오늘 소라랑 민호한테 물어봐야겠다.",
        "M: 빨리 해. 작년에는 사흘 만에 탁자가 다 찼어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello?"],
        ["M", "Hi, Yerin. It's Junho from the drama club."],
        ["W", "Hi. Is the rehearsal still at four?"],
        ["M", "That's why I'm calling. The hall is being cleaned tomorrow."],
        ["W", "So we can't use it at all?"],
        ["M", "Not in the afternoon. The teacher gave us the music room instead."],
        ["W", "Same time, though?"],
        ["M", "Same time, four o'clock. Could you tell the second-year members?"],
        ["W", "Sure. I'll message them tonight."],
      ],
      choices: [
        "연습 시간을 미루려고",
        "대본을 빌려 달라고 하려고",
        "연습 장소가 바뀐 것을 알리려고",
        "공연 표를 사 달라고 하려고",
        "동아리를 그만둔다고 알리려고",
      ],
      answer: 3,
      clue: "Not in the afternoon. The teacher gave us the music room instead.",
      explanation:
        "강당 청소 때문에 연습 장소가 음악실로 바뀐 것을 알리려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "W: 여보세요?",
        "M: 안녕, 예린아. 연극부 준호야.",
        "W: 안녕. 연습 4시 그대로지?",
        "M: 그것 때문에 전화했어. 내일 강당 청소를 한대.",
        "W: 그럼 아예 못 쓰는 거야?",
        "M: 오후에는 못 써. 선생님이 대신 음악실을 주셨어.",
        "W: 시간은 그대로고?",
        "M: 시간은 그대로 4시야. 2학년 부원들한테 좀 알려 줄래?",
        "W: 그래. 오늘 밤에 메시지 보낼게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Suhyeon, what time should we meet at the exhibition?"],
        ["W", "The last entry is at five, isn't it?"],
        ["M", "Yes, and we need at least an hour inside."],
        ["W", "Then how about four o'clock?"],
        ["M", "That's a bit tight for me. My class ends at three forty."],
        ["W", "Oh, I forgot. How long does it take you to get there?"],
        ["M", "Thirty-five minutes by bus."],
        ["W", "Then let's meet at four thirty. That still leaves us enough time."],
        ["M", "Four thirty works. I'll wait by the entrance."],
      ],
      choices: ["3:30 p.m.", "4:00 p.m.", "4:30 p.m.", "5:00 p.m.", "5:30 p.m."],
      answer: 3,
      clue: "Then let's meet at four thirty. That still leaves us enough time.",
      explanation:
        "남자의 수업이 3시 40분에 끝나고 35분이 걸리므로 두 사람은 4시 30분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 수현아, 전시회에서 몇 시에 만날까?",
        "W: 마지막 입장이 5시지?",
        "M: 응, 그리고 안에서 적어도 한 시간은 있어야 해.",
        "W: 그럼 4시는 어때?",
        "M: 나한테는 좀 빠듯해. 수업이 3시 40분에 끝나.",
        "W: 아, 깜빡했다. 거기까지 얼마나 걸려?",
        "M: 버스로 35분.",
        "W: 그럼 4시 30분에 만나자. 그래도 시간은 충분해.",
        "M: 4시 30분 좋아. 입구에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dain, you've been quiet since we left the classroom."],
        ["W", "I gave my presentation today and my hands shook the whole time."],
        ["M", "Did you finish it?"],
        ["W", "I did, but I skipped two slides without meaning to."],
        ["M", "Did anyone notice?"],
        ["W", "The teacher asked about one of them at the end."],
        ["M", "What did you say?"],
        ["W", "Nothing useful. I keep thinking about that moment."],
      ],
      choices: ["excited", "embarrassed", "proud", "bored", "relieved"],
      answer: 2,
      clue: "Nothing useful. I keep thinking about that moment.",
      explanation:
        "발표 중에 슬라이드를 빼먹고 질문에도 제대로 답하지 못해 그 순간을 계속 떠올리고 있으므로 여자는 부끄러워하고 있다. 따라서 답은 ②이다.",
      translation: [
        "M: 다인아, 교실 나오고부터 말이 없네.",
        "W: 오늘 발표했는데 내내 손이 떨렸어.",
        "M: 끝까지 했어?",
        "W: 하긴 했는데, 나도 모르게 슬라이드 두 장을 건너뛰었어.",
        "M: 누가 알아챘어?",
        "W: 선생님이 끝나고 그중 하나를 물어보셨어.",
        "M: 뭐라고 했는데?",
        "W: 제대로 답을 못 했어. 그 순간이 계속 생각나.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Shall I hold the door for you?"],
        ["M", "Yes, thank you. My hands are full."],
        ["W", "Excuse me, could you move up a little?"],
        ["M", "Of course, there's space here."],
        ["W", "How much is a ticket to the aquarium?"],
        ["M", "Nine dollars for students."],
        ["W", "Do you know when the library closes?"],
        ["M", "At six on weekdays."],
        ["W", "May I try this jacket on?"],
        ["M", "Certainly, the fitting room is over there."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Shall I hold the door for you?",
      explanation:
        "그림은 양손에 상자를 든 사람을 위해 다른 사람이 문을 잡아 주는 장면이므로 ①이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "At the entrance of a building. A man is carrying two large boxes with both arms and cannot reach the door handle. A woman is standing beside the open door, holding it wide open with one hand and looking at him. Both are drawn clearly. Steps and a glass door frame are in the background.",
      },
      translation: [
        "① W: 문 잡아 드릴까요? / M: 네, 감사합니다. 손이 꽉 차서요.",
        "② W: 실례지만 조금만 옆으로 가 주시겠어요? / M: 그럼요, 여기 자리 있어요.",
        "③ W: 수족관 표가 얼마예요? / M: 학생은 9달러입니다.",
        "④ W: 도서관이 언제 닫는지 아세요? / M: 평일에는 6시에요.",
        "⑤ W: 이 재킷 입어 봐도 될까요? / M: 그럼요, 탈의실은 저쪽입니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, are you going to the art room after school?"],
        ["W", "I mean today, not tomorrow."],
        ["M", "Yes, our club meets there on Tuesdays."],
        ["W", "Good. Our class banner is drying on the back table."],
        ["M", "The one you painted last week?"],
        ["W", "That's it. It should be dry by now."],
        ["M", "Do you want me to roll it up?"],
        ["W", "Yes, please, and bring it to our classroom."],
        ["M", "No problem. I'll put it behind the door."],
      ],
      choices: ["현수막 가져다주기", "그림 그려 주기", "미술실 청소하기", "물감 사다 주기", "자리 맡아 주기"],
      answer: 1,
      clue: "Yes, please, and bring it to our classroom.",
      explanation:
        "여자는 미술실에서 말리고 있는 학급 현수막을 말아서 교실로 가져다 달라고 부탁한다. 따라서 답은 ①이다.",
      translation: [
        "W: 태민아, 방과 후에 미술실 가?",
        "W: 내일 말고 오늘.",
        "M: 응, 우리 동아리가 화요일마다 거기서 모여.",
        "W: 잘됐다. 우리 반 현수막이 뒤쪽 탁자에서 마르고 있어.",
        "M: 지난주에 네가 칠한 거?",
        "W: 그거. 지금쯤이면 다 말랐을 거야.",
        "M: 말아 놓을까?",
        "W: 응, 부탁해. 그리고 우리 교실로 가져다줘.",
        "M: 그래. 문 뒤에 놔둘게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Winter Volunteer Week에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about Winter Volunteer Week."],
        ["M", "It runs from the twenty-second to the twenty-sixth of December."],
        ["M", "We will work at the community centre near the station."],
        ["M", "Each day you help for three hours in the afternoon."],
        ["M", "Sign your name on the sheet outside the counselling room."],
        ["M", "We hope many of you will join us."],
      ],
      choices: ["진행 기간", "장소", "하루 활동 시간", "신청 방법", "모집 인원"],
      answer: 5,
      clue: "Sign your name on the sheet outside the counselling room.",
      explanation:
        "기간(12월 22일~26일), 장소(역 근처 주민센터), 하루 활동 시간(오후 세 시간), 신청 방법(상담실 앞 명단)은 언급되지만 모집 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Winter Volunteer Week를 안내합니다.",
        "M: 12월 22일부터 26일까지 진행됩니다.",
        "M: 역 근처 주민센터에서 일합니다.",
        "M: 하루에 오후 세 시간씩 돕습니다.",
        "M: 상담실 앞 명단에 이름을 적으세요.",
        "M: 많은 학생이 함께하기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You will find this at the front of every classroom."],
        ["W", "It stands on the floor and has a slanted top."],
        ["W", "The teacher puts a book or a laptop on it while speaking."],
        ["W", "Some of them have a shelf underneath for chalk."],
        ["W", "Students stand behind it when they give a presentation."],
      ],
      choices: ["교탁", "책상", "사물함", "칠판", "게시판"],
      answer: 1,
      clue: "Students stand behind it when they give a presentation.",
      explanation:
        "교실 앞에 서 있고 위가 비스듬하며 발표할 때 그 뒤에 선다고 했으므로 교탁이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 모든 교실 앞쪽에 있습니다.",
        "W: 바닥에 서 있고 윗면이 비스듬합니다.",
        "W: 선생님은 말하면서 그 위에 책이나 노트북을 올려놓습니다.",
        "W: 아래에 분필을 넣는 선반이 있는 것도 있습니다.",
        "W: 학생들은 발표할 때 이것 뒤에 섭니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How long have you played the guitar?"],
        ["W", "Since I was ten."],
        ["M", "Could you turn the heater down?"],
        ["W", "Sure, it is warm in here."],
        ["M", "What did the doctor say?"],
        ["W", "I have to rest for a week."],
        ["M", "Which subject do you find hardest?"],
        ["W", "It takes about twenty minutes."],
        ["M", "Are you free after school?"],
        ["W", "Yes, until five."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Which subject do you find hardest?",
      explanation:
        "어떤 과목이 가장 어려운지 묻는 말에 20분쯤 걸린다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 기타 친 지 얼마나 됐어? / W: 열 살 때부터.",
        "② M: 난방 좀 줄여 줄래? / W: 그래, 여기 덥네.",
        "③ M: 의사 선생님이 뭐라셔? / W: 일주일 쉬어야 한대.",
        "④ M: 어떤 과목이 제일 어려워? / W: 20분쯤 걸려.",
        "⑤ M: 방과 후에 시간 있어? / W: 응, 5시까지는.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seungho, the club photo is in fifteen minutes."],
        ["M", "Is everyone coming? What still needs doing?"],
        ["W", "I've told all the members and moved the bench outside."],
        ["M", "Should I get the camera from the club room?"],
        ["W", "Hayeon already has it."],
        ["M", "Then what's left?"],
        ["W", "The club room door is still open and nobody will be inside."],
        ["M", "I'll go and lock it now."],
        ["W", "Thanks. I'll line everyone up by the bench."],
      ],
      choices: ["부원들에게 알리기", "벤치 옮기기", "카메라 가져오기", "동아리방 문 잠그기", "줄 세우기"],
      answer: 4,
      clue: "I'll go and lock it now.",
      explanation:
        "연락과 벤치, 카메라는 이미 해결되었으므로 남자는 열려 있는 동아리방 문을 잠그러 간다. 따라서 답은 ④이다.",
      translation: [
        "W: 승호야, 동아리 사진 15분 뒤야.",
        "M: 다들 와? 뭐가 더 남았어?",
        "W: 부원들한테는 다 말했고 벤치도 밖으로 옮겼어.",
        "M: 동아리방에서 카메라를 가져올까?",
        "W: 하연이가 벌써 가져갔어.",
        "M: 그럼 뭐가 남았어?",
        "W: 동아리방 문이 아직 열려 있는데 안에 아무도 없을 거야.",
        "M: 내가 가서 잠그고 올게.",
        "W: 고마워. 나는 벤치 옆에 줄 세울게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 예약할 체험 교실을 고르시오.",
      lines: [
        ["M", "Nayeon, these are the five weekend workshops still open."],
        ["W", "Let's look. I can't go on Sunday because of my grandmother."],
        ["M", "Then one is out. What next?"],
        ["W", "It has to be for beginners. I've never done any of these."],
        ["M", "One is for advanced students, so that's gone too."],
        ["W", "Three left. How much are they?"],
        ["M", "You said thirty thousand won at the most."],
        ["W", "Then one more is out. Two are left."],
        ["M", "Do they both let you take the piece home the same day?"],
        ["W", "Only one does. The other one fires it and posts it later."],
        ["M", "Then take the one you can carry home."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Only one does. The other one fires it and posts it later.",
      explanation:
        "일요일인 ⑤, 심화 과정인 ④, 35,000원인 ①을 뺀다. 남은 ②와 ③ 중 당일에 작품을 가져올 수 있는 것은 ②이므로 답은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "토요일 / 초급 / 35,000원 / 당일 수령" },
          { no: 2, label: "②", value: "토요일 / 초급 / 28,000원 / 당일 수령" },
          { no: 3, label: "③", value: "금요일 / 초급 / 25,000원 / 나중에 배송" },
          { no: 4, label: "④", value: "토요일 / 심화 / 30,000원 / 당일 수령" },
          { no: 5, label: "⑤", value: "일요일 / 초급 / 22,000원 / 당일 수령" },
        ],
      },
      translation: [
        "M: 나연아, 아직 열려 있는 주말 체험 교실이 이 다섯 개야.",
        "W: 보자. 할머니 때문에 일요일은 못 가.",
        "M: 그럼 하나 빠지네. 다음은?",
        "W: 초급이어야 해. 이런 걸 해 본 적이 없어서.",
        "M: 하나는 심화 과정이니까 그것도 빠져.",
        "W: 셋 남았다. 얼마야?",
        "M: 3만 원까지라고 했잖아.",
        "W: 그럼 하나 더 빠지고 둘 남았다.",
        "M: 둘 다 그날 작품을 가져올 수 있어?",
        "W: 한 곳만. 다른 곳은 구워서 나중에 보내 준대.",
        "M: 그럼 그날 들고 올 수 있는 걸로 해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진전에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Soyul, when should we go to the photo exhibition?"],
        ["W", "It's only open on the sixteenth, seventeenth, and eighteenth."],
        ["M", "Three days. What's it about, again?"],
        ["W", "Old streets of our city, taken fifty years ago."],
        ["M", "That sounds good. But I have a family dinner on the sixteenth."],
        ["W", "Then the seventeenth or the eighteenth."],
        ["M", "Wait. Isn't the eighteenth the day of the school health check?"],
        ["W", "You're right. We'd be in line all afternoon."],
        ["M", "So only the seventeenth is left."],
        ["W", "Then let's go on the seventeenth, right after school."],
      ],
      choices: ["15일", "16일", "17일", "18일", "19일"],
      answer: 3,
      clue: "So only the seventeenth is left.",
      explanation:
        "16일은 가족 저녁 식사, 18일은 학교 건강 검진이어서 17일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 소율아, 사진전 언제 갈까?",
        "W: 16일, 17일, 18일에만 열어.",
        "M: 사흘이구나. 무슨 사진전이라고 했지?",
        "W: 50년 전에 찍은 우리 도시의 옛 거리 사진.",
        "M: 좋겠다. 그런데 16일에 가족 저녁 식사가 있어.",
        "W: 그럼 17일이나 18일이네.",
        "M: 잠깐. 18일은 학교 건강 검진 날 아니야?",
        "W: 맞다. 오후 내내 줄 서 있겠네.",
        "M: 그럼 17일만 남네.",
        "W: 그럼 17일에 가자, 학교 끝나고 바로.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunjun, did you go to the game last weekend?"],
        ["M", "No, I helped my mother move her shop on Saturday."],
        ["W", "Move a whole shop? That sounds like hard work."],
        ["M", "It was. We carried boxes from eight until four."],
        ["W", "Eight hours! Were there many boxes?"],
        ["M", "Forty-two. I counted them while we loaded the truck."],
        ["W", "Is the new shop nice?"],
        ["M", "Much brighter, and it's closer to our house."],
      ],
      choices: ["가게 이사 돕기", "경기 보러 가기", "자전거 타기", "영화 보기", "친척 집 가기"],
      answer: 1,
      clue: "No, I helped my mother move her shop on Saturday.",
      explanation:
        "남자는 지난 토요일에 어머니의 가게 이사를 도왔다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "W: 현준아, 지난 주말에 경기 보러 갔어?",
        "M: 아니, 토요일에 엄마 가게 이사를 도왔어.",
        "W: 가게를 통째로? 힘들었겠다.",
        "M: 힘들었어. 8시부터 4시까지 상자를 날랐어.",
        "W: 여덟 시간이나! 상자가 많았어?",
        "M: 마흔두 개. 트럭에 실으면서 세어 봤어.",
        "W: 새 가게는 괜찮아?",
        "M: 훨씬 밝고 우리 집에서 더 가까워.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "The water will be turned off tomorrow between nine and one."],
        ["W", "Workers are replacing an old pipe under the first floor."],
        ["W", "The toilets on the second and third floors will still work."],
        ["W", "Please bring your own water bottle from home tomorrow."],
        ["W", "The water will come back before lunch time."],
        ["W", "We are sorry for the trouble."],
      ],
      choices: [
        "물을 아껴 쓰라고 하려고",
        "단수 안내를 하려고",
        "화장실 청소를 당부하려고",
        "급식 시간이 바뀐 것을 알리려고",
        "공사 봉사자를 모집하려고",
      ],
      answer: 2,
      clue: "The water will be turned off tomorrow between nine and one.",
      explanation:
        "낡은 배관 교체로 내일 9시부터 1시까지 물이 끊긴다는 것을 알리는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 내일 9시부터 1시까지 물이 끊깁니다.",
        "W: 1층 아래 낡은 배관을 교체하는 공사가 있습니다.",
        "W: 2층과 3층 화장실은 그대로 쓸 수 있습니다.",
        "W: 내일은 집에서 물병을 가져와 주세요.",
        "W: 물은 점심시간 전에 다시 나옵니다.",
        "W: 불편을 드려 죄송합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the stationery shop. What do you need?"],
        ["M", "Four notebooks and one file folder, please."],
        ["W", "The notebooks are five dollars each."],
        ["M", "And the folder?"],
        ["W", "The folder is seven dollars."],
        ["M", "So twenty dollars and seven dollars."],
        ["W", "That's right. Do you have our store card?"],
        ["M", "Yes, here it is."],
        ["W", "Then I can take four dollars off."],
        ["M", "Great. I'll pay by card."],
      ],
      choices: ["$20", "$23", "$25", "$27", "$31"],
      answer: 2,
      clue: "Then I can take four dollars off.",
      explanation:
        "공책 5달러짜리 네 권은 20달러, 서류철 7달러를 더하면 27달러이다. 매장 카드 할인 4달러를 빼면 23달러이므로 답은 ②이다.",
      translation: [
        "W: 문구점입니다. 무엇이 필요하세요?",
        "M: 공책 네 권이랑 서류철 하나 주세요.",
        "W: 공책은 한 권에 5달러입니다.",
        "M: 서류철은요?",
        "W: 서류철은 7달러입니다.",
        "M: 그럼 20달러랑 7달러네요.",
        "W: 맞습니다. 저희 매장 카드 있으세요?",
        "M: 네, 여기요.",
        "W: 그럼 4달러 빼 드릴게요.",
        "M: 좋네요. 카드로 결제할게요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Junseo, you've been staying late in the science room every day."],
        ["M", "I'm building a model bridge for the fair."],
        ["W", "How is it going?"],
        ["M", "Badly. It breaks at the same place whenever I add weight."],
        ["W", "Where exactly does it break?"],
        ["M", "Right in the middle, every single time."],
        ["W", "What do you do after it breaks?"],
        ["M", "I build the whole thing again from the start."],
        ["W", "Build only the middle part and test that piece by itself."],
      ],
      choices: [
        "The fair is in three weeks.",
        "My bridge is made of paper straws.",
        "I'd rather build something else.",
        "Then I'll test just the middle part tomorrow.",
        "You should enter the fair too.",
      ],
      answer: 4,
      clue: "Build only the middle part and test that piece by itself.",
      explanation:
        "가운데 부분만 만들어 따로 시험해 보라는 조언을 들었으므로, 내일 그렇게 하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 준서야, 매일 과학실에 늦게까지 남아 있네.",
        "M: 발표회에 낼 모형 다리를 만들고 있어.",
        "W: 잘돼 가?",
        "M: 아니. 무게를 올릴 때마다 같은 데서 부러져.",
        "W: 정확히 어디서 부러지는데?",
        "M: 매번 딱 가운데.",
        "W: 부러지면 어떻게 해?",
        "M: 처음부터 통째로 다시 만들어.",
        "W: 가운데 부분만 만들어서 그것만 따로 시험해 봐.",
        "M: 그럼 내일은 가운데 부분만 시험해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Chaeyeon, you look tired in the first period every day."],
        ["W", "I can't fall asleep until after midnight."],
        ["M", "What do you do in the hour before bed?"],
        ["W", "I finish my homework and then watch videos in bed."],
        ["M", "In bed with the light on?"],
        ["W", "Yes, and then I can't stop."],
        ["M", "My sister leaves her phone on the desk after ten."],
        ["W", "Does that really help her sleep?"],
        ["M", "She says she falls asleep in fifteen minutes now."],
      ],
      choices: [
        "My homework takes two hours.",
        "I go to bed around eleven.",
        "Then I'll leave my phone on the desk tonight.",
        "My sister is in the same class.",
        "You should watch fewer videos too.",
      ],
      answer: 3,
      clue: "She says she falls asleep in fifteen minutes now.",
      explanation:
        "10시 이후에는 휴대전화를 책상에 두면 금방 잠든다는 말을 들었으므로, 오늘 밤에 그렇게 하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 채연아, 매일 1교시에 피곤해 보여.",
        "W: 자정이 지나야 잠이 와.",
        "M: 자기 전 한 시간에는 뭐 해?",
        "W: 숙제를 끝내고 침대에서 영상을 봐.",
        "M: 불 켜고 침대에서?",
        "W: 응, 그러면 멈출 수가 없어.",
        "M: 우리 누나는 10시 넘으면 휴대전화를 책상에 둬.",
        "W: 그게 정말 잠드는 데 도움이 돼?",
        "M: 요즘은 15분이면 잠든대.",
        "W: 그럼 오늘 밤에 휴대전화를 책상에 둬야겠다.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Dohyun, how is the class reading corner going?"],
        ["M", "Not well. Only three people have borrowed a book this month."],
        ["W", "Where is the corner?"],
        ["M", "In the back corner, behind the cleaning cupboard."],
        ["W", "Behind the cupboard? Nobody goes there."],
        ["M", "It was the only empty space when we started."],
        ["W", "Is there anywhere people actually walk past?"],
        ["M", "There's a wall by the door, but it's narrow."],
        ["W", "A narrow shelf people see beats a big one they don't."],
      ],
      choices: [
        "We have about forty books.",
        "The corner opened in March.",
        "I read two books last month.",
        "I'd rather close the corner.",
        "Then I'll move the shelf by the door.",
      ],
      answer: 5,
      clue: "A narrow shelf people see beats a big one they don't.",
      explanation:
        "사람들이 지나다니는 문 옆으로 옮기는 편이 낫다는 조언을 들었으므로, 책꽂이를 문 옆으로 옮기겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 도현아, 학급 독서 코너는 잘돼 가?",
        "M: 잘 안돼. 이번 달에 세 명만 책을 빌려 갔어.",
        "W: 코너가 어디 있는데?",
        "M: 뒤쪽 구석, 청소함 뒤에.",
        "W: 청소함 뒤에? 거기는 아무도 안 가잖아.",
        "M: 시작할 때 빈 자리가 거기밖에 없었어.",
        "W: 사람들이 실제로 지나다니는 데는 없어?",
        "M: 문 옆에 벽이 있긴 한데 좁아.",
        "W: 아무도 안 보는 큰 자리보다 사람들이 보는 좁은 자리가 나아.",
        "M: 그럼 책꽂이를 문 옆으로 옮길게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minseo가 Hyunwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Minseo : ________________",
      lines: [
        ["W", "Minseo and Hyunwoo are on the same relay team."],
        ["W", "They will run in the school sports day next Friday."],
        ["W", "Hyunwoo is the fastest runner on the team."],
        ["W", "However, he starts running before he has the baton in his hand."],
        ["W", "Twice in practice the baton fell on the track."],
        ["W", "Their teacher said the hand must close before the feet move."],
        ["W", "Minseo does not want to say that his running is bad."],
        ["W", "She wants to ask him to wait until he feels the baton."],
        ["W", "In this situation, what would Minseo most likely say to Hyunwoo?"],
      ],
      choices: [
        "Let's change the running order.",
        "You should run a little slower.",
        "I'll run your part instead.",
        "Wait until you feel the baton before you go.",
        "We don't need to practise any more.",
      ],
      answer: 4,
      clue: "She wants to ask him to wait until he feels the baton.",
      explanation:
        "민서는 현우의 달리기를 깎아내리지 않으면서, 배턴이 손에 잡힌 뒤에 출발하라고 말하려 한다. 따라서 ④가 가장 적절하다.",
      translation: [
        "W: 민서와 현우는 같은 계주 팀입니다.",
        "W: 두 사람은 다음 주 금요일 체육대회에서 달립니다.",
        "W: 현우는 팀에서 가장 빠른 주자입니다.",
        "W: 그런데 배턴이 손에 들어오기 전에 출발합니다.",
        "W: 연습에서 두 번이나 배턴이 트랙에 떨어졌습니다.",
        "W: 선생님은 발이 움직이기 전에 손이 먼저 잡혀야 한다고 했습니다.",
        "W: 민서는 현우의 달리기가 나쁘다고 말하고 싶지는 않습니다.",
        "W: 다만 배턴이 손에 느껴질 때까지 기다리라고 부탁하고 싶습니다.",
        "W: 이런 상황에서 민서가 현우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
