/** 중3 듣기 26회 — 사람이 직접 쓴 회차 (2026-09-24) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 26회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 이어폰을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for earphones?"],
        ["W", "Yes, something for studying in a noisy room."],
        ["M", "We have over-ear headphones and small in-ear buds."],
        ["W", "Over-ear, please. Buds always fall out of my ears."],
        ["M", "All right. This over-ear pair connects with a cable."],
        ["W", "A cable gets caught on my chair every time."],
        ["M", "Then here is a wireless over-ear pair."],
        ["W", "That's the one. I'll take the wireless pair."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Over-ear, please. / I'll take the wireless pair.",
      explanation:
        "여자는 귀를 덮는 헤드폰을 원하고, 줄이 있는 것 대신 무선을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five sets of earphones drawn side by side as five choices, clean black line art on white. " +
          "① small IN-EAR BUDS joined by a CABLE with a plug at the end. " +
          "② small IN-EAR BUDS with NO cable at all, sitting beside a tiny charging case. " +
          "③ large OVER-EAR HEADPHONES with a CABLE and a plug at the end. " +
          "④ large OVER-EAR HEADPHONES with NO cable at all. " +
          "⑤ large OVER-EAR HEADPHONES with a CABLE and a small microphone arm in front.",
      },
      translation: [
        "M: 안녕하세요. 이어폰 찾으세요?",
        "W: 네, 시끄러운 방에서 공부할 때 쓸 거예요.",
        "M: 귀를 덮는 헤드폰도 있고 귀에 넣는 작은 것도 있어요.",
        "W: 귀를 덮는 걸로 주세요. 작은 건 자꾸 빠져요.",
        "M: 알겠습니다. 이 헤드폰은 줄로 연결해요.",
        "W: 줄은 매번 제 의자에 걸려요.",
        "M: 그럼 무선 헤드폰이 여기 있어요.",
        "W: 그거예요. 무선으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 수학 경시대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Seojun, are you taking the school math contest?"],
        ["M", "I think so. When exactly is it held?"],
        ["W", "Next Thursday, during the fifth and sixth periods."],
        ["M", "Where do we sit for the test?"],
        ["W", "In the third floor lecture room, by student number."],
        ["M", "How many questions are there?"],
        ["W", "Twenty, and you get eighty minutes."],
        ["M", "What can we bring inside?"],
        ["W", "Only a pen and your student card."],
      ],
      choices: ["열리는 날", "시험 장소", "문항 수", "반입 가능 물품", "시상 내용"],
      answer: 5,
      clue: "시상 내용은 대화에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 목요일), 장소(3층 강의실), 문항 수(20문항), 반입 물품(펜과 학생증)은 언급되지만 시상 내용은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 서준아, 교내 수학 경시대회 볼 거야?",
        "M: 그럴 것 같아. 정확히 언제 해?",
        "W: 다음 주 목요일, 5·6교시에.",
        "M: 시험은 어디서 봐?",
        "W: 3층 강의실에서, 학번 순으로 앉아.",
        "M: 문제는 몇 개야?",
        "W: 스무 개, 80분 줘.",
        "M: 안에 뭘 가지고 들어갈 수 있어?",
        "W: 펜이랑 학생증만.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Hanaro Sports Center?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "I registered for the Saturday swimming class."],
        ["W", "Let me check. Under the name Seojun Han?"],
        ["M", "That's right. I hurt my shoulder at practice."],
        ["W", "I'm sorry to hear that. How long will you need?"],
        ["M", "Could you pause my classes for three weeks?"],
        ["W", "Of course. I've put your spot on hold until then."],
      ],
      choices: [
        "수업을 새로 신청하려고",
        "수업을 취소하려고",
        "수업을 잠시 쉬겠다고 알리려고",
        "수강료를 물어보려고",
        "센터 위치를 물어보려고",
      ],
      answer: 3,
      clue: "Could you pause my classes for three weeks?",
      explanation:
        "남자는 어깨를 다쳐 3주 동안 수업을 쉬겠다고 알리려고 전화했다. 따라서 답은 ③이다.",
      translation: [
        "M: 여보세요, 하나로 스포츠 센터죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 토요일 수영 수업에 등록했는데요.",
        "W: 확인해 볼게요. 한서준 님이시죠?",
        "M: 맞아요. 연습하다 어깨를 다쳤어요.",
        "W: 안타깝네요. 얼마나 쉬셔야 하나요?",
        "M: 3주 동안 수업을 멈춰 주실 수 있나요?",
        "W: 물론이죠. 그때까지 자리를 잡아 두었습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Seojun, what time does the science lab close?"],
        ["M", "The teacher locks it at six in the evening."],
        ["W", "Then we have to finish the experiment before that."],
        ["M", "Right, and cleaning the tools takes a while."],
        ["W", "How long do we need for the cleaning?"],
        ["M", "A full hour, if we want to do it properly."],
        ["W", "And the experiment itself takes two hours."],
        ["M", "Then let's start three hours before the lab closes."],
        ["W", "Good. I'll meet you at the lab door then."],
      ],
      choices: ["3:00 p.m.", "2:00 p.m.", "4:00 p.m.", "5:00 p.m.", "6:00 p.m."],
      answer: 1,
      clue: "Then let's start three hours before the lab closes.",
      explanation:
        "과학실이 6시에 닫고 그보다 세 시간 전에 시작하기로 했으므로 만나는 시각은 3시이다. 따라서 답은 ①이다.",
      translation: [
        "W: 서준아, 과학실 몇 시에 닫아?",
        "M: 선생님이 저녁 6시에 잠그셔.",
        "W: 그럼 그전에 실험을 끝내야겠네.",
        "M: 맞아, 그리고 도구 씻는 데도 시간이 걸려.",
        "W: 씻는 데 얼마나 필요해?",
        "M: 제대로 하려면 꼬박 한 시간.",
        "W: 그리고 실험 자체가 두 시간 걸리고.",
        "M: 그럼 과학실 닫기 세 시간 전에 시작하자.",
        "W: 좋아. 그때 과학실 문 앞에서 만나.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayeon, you've been standing at that window all morning."],
        ["W", "My little brother has been missing since last night."],
        ["M", "Missing? Did your family call the police?"],
        ["W", "Yes, at midnight. They're searching the neighborhood."],
        ["M", "Has anyone seen him at all?"],
        ["W", "One neighbor saw him near the river at eight."],
        ["M", "The river? That's not far from your house."],
        ["W", "I can't sit down. Every phone call makes me jump."],
      ],
      choices: ["bored", "proud", "delighted", "anxious", "sleepy"],
      answer: 4,
      clue: "I can't sit down. Every phone call makes me jump.",
      explanation:
        "동생이 어젯밤부터 사라져 앉아 있지도 못하고 전화마다 놀란다고 했으므로 여자의 심정은 '불안한(anxious)'이다. 따라서 답은 ④이다.",
      translation: [
        "M: 하연아, 아침 내내 창가에 서 있네.",
        "W: 어젯밤부터 남동생이 안 보여.",
        "M: 안 보인다고? 경찰에 신고했어?",
        "W: 응, 자정에. 동네를 찾고 계셔.",
        "M: 본 사람은 있어?",
        "W: 이웃 한 분이 8시에 강가에서 봤대.",
        "M: 강가? 너희 집에서 멀지 않잖아.",
        "W: 앉아 있을 수가 없어. 전화만 오면 깜짝 놀라.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How long is the wait for a table?"],
        ["M", "About fifteen minutes."],
        ["ANN", "Number two."],
        ["W", "Could we have two more glasses?"],
        ["M", "Certainly, I'll bring them."],
        ["ANN", "Number three."],
        ["W", "Is this dish very spicy?"],
        ["M", "Only a little."],
        ["ANN", "Number four."],
        ["W", "Excuse me, your scarf is touching the candle."],
        ["M", "Oh! Thank you for warning me."],
        ["ANN", "Number five."],
        ["W", "Do you take reservations?"],
        ["M", "Yes, for groups of six or more."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Excuse me, your scarf is touching the candle.",
      explanation:
        "그림은 식당에서 남자의 긴 목도리 끝이 탁자 위 촛불에 닿으려 하고, 여자가 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a restaurant at a small table, clean black line art on a plain white background, no writing anywhere. " +
          "A man sits reading a menu, and the long end of his scarf hangs down very close to a lit candle on the table. " +
          "A woman at the next table points at the scarf and the candle with an alarmed face and calls out to him. " +
          "Other tables and a window are drawn simply in the background.",
      },
      translation: [
        "① W: 자리 기다리는 데 얼마나 걸려요? / M: 15분쯤이요.",
        "② W: 잔 두 개만 더 주시겠어요? / M: 네, 가져다드리겠습니다.",
        "③ W: 이 음식 많이 매워요? / M: 조금만 매워요.",
        "④ W: 저기요, 목도리가 촛불에 닿아요. / M: 앗! 알려 주셔서 감사합니다.",
        "⑤ W: 예약도 받나요? / M: 네, 여섯 분 이상이면 받습니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayeon, you write the club notices every month, right?"],
        ["W", "Yes, I post them on the board by the stairs."],
        ["M", "Our team needs one more player for the tournament."],
        ["W", "When is the tournament held?"],
        ["M", "In two weeks, and we only have four players."],
        ["W", "So you want more people to hear about it?"],
        ["M", "Could you put a notice on the board for us?"],
        ["W", "Sure. I'll write one and post it tomorrow morning."],
      ],
      choices: ["대회에 함께 나가기", "선수 추천해 주기", "게시판 만들기", "연습 도와주기", "모집 공고 붙여 주기"],
      answer: 5,
      clue: "Could you put a notice on the board for us?",
      explanation:
        "남자는 선수를 구한다는 공고를 게시판에 붙여 달라고 부탁했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 하연아, 매달 동아리 공고 네가 쓰지?",
        "W: 응, 계단 옆 게시판에 붙여.",
        "M: 우리 팀이 대회에 나갈 선수가 한 명 더 필요해.",
        "W: 대회가 언제야?",
        "M: 2주 뒤인데 선수가 네 명뿐이야.",
        "W: 그럼 더 많은 사람이 알았으면 좋겠다는 거지?",
        "M: 게시판에 공고 좀 붙여 줄 수 있어?",
        "W: 그럼. 내가 써서 내일 아침에 붙일게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 진학 설명회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, third graders. The high school information session is next week. " +
            "It will be held in the auditorium on Wednesday evening. " +
            "Teachers from four nearby high schools will come and speak. " +
            "Parents are welcome, and each family may bring two guests. " +
            "Written materials will be handed out at the door. " +
            "We hope the session helps you choose your next school.",
        ],
      ],
      choices: ["열리는 요일", "열리는 장소", "행사 소요 시간", "참석하는 학교 수", "동반 가능 인원"],
      answer: 3,
      clue: "행사 소요 시간은 방송에서 언급되지 않았다.",
      explanation:
        "요일(수요일 저녁), 장소(강당), 참석 학교 수(네 곳), 동반 인원(가정당 두 명)은 언급되지만 행사 소요 시간은 언급되지 않았다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요, 3학년 여러분. 다음 주에 고등학교 진학 설명회가 열립니다. 수요일 저녁 강당에서 진행됩니다. 인근 고등학교 네 곳의 선생님들이 오셔서 말씀해 주십니다. 학부모님도 오실 수 있고, 가정마다 두 분까지 함께 오실 수 있습니다. 자료집은 입구에서 나눠 드립니다. 이번 설명회가 다음 학교를 고르는 데 도움이 되기를 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a place students visit when they want a quiet hour alone. " +
            "You must whisper inside, and phones have to stay silent. " +
            "Rows of tall shelves divide the room into narrow aisles. " +
            "A worker at the counter stamps a date inside whatever you take home. " +
            "If you return it late, you may have to pay a small fee.",
        ],
      ],
      choices: ["도서관", "교무실", "매점", "보건실", "체육관"],
      answer: 1,
      clue: "A worker at the counter stamps a date inside whatever you take home.",
      explanation:
        "속삭여야 하고 키 큰 서가가 늘어서 있으며 빌려 가는 것에 날짜를 찍어 주는 곳은 도서관이다. 따라서 답은 ①이다.",
      translation: [
        "M: 이곳은 학생들이 혼자 조용한 시간을 보내고 싶을 때 가는 곳입니다. 안에서는 속삭여야 하고 휴대폰은 소리를 꺼야 합니다. 키 큰 서가가 줄지어 서서 방을 좁은 통로로 나눕니다. 창구 직원이 가져가는 것 안쪽에 날짜를 찍어 줍니다. 늦게 돌려주면 적은 금액을 내야 할 수도 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was the interview this morning?"],
        ["W", "Shorter than I expected."],
        ["ANN", "Number two."],
        ["M", "Where should I put my coat?"],
        ["W", "On the hook behind the door."],
        ["ANN", "Number three."],
        ["M", "Would you like another cup of tea?"],
        ["W", "Yes, please. It's delicious."],
        ["ANN", "Number four."],
        ["M", "Who is picking you up today?"],
        ["W", "The concert starts at seven."],
        ["ANN", "Number five."],
        ["M", "Have you decided what to study?"],
        ["W", "I'm leaning toward engineering."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is picking you up today?",
      explanation:
        "오늘 누가 데리러 오는지 묻는 말에 공연이 7시에 시작한다고 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 오늘 아침 면접 어땠어? / W: 생각보다 짧았어.",
        "② M: 외투는 어디에 둘까? / W: 문 뒤 고리에.",
        "③ M: 차 한 잔 더 드릴까요? / W: 네, 주세요. 맛있어요.",
        "④ M: 오늘은 누가 데리러 와? / W: 공연은 7시에 시작해.",
        "⑤ M: 뭘 공부할지 정했어? / W: 공학 쪽으로 기울고 있어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seojun, the school debate final starts in twenty minutes."],
        ["M", "I know. Are the two teams seated at the front?"],
        ["W", "Yes, both tables are ready with name cards."],
        ["M", "Good. Did you print the judging sheets?"],
        ["W", "I printed them, but the stapler ran out."],
        ["M", "Loose sheets will get mixed up during the rounds."],
        ["W", "I have to brief the timekeeper before we start."],
        ["M", "Then I'll get staples from the office and bind them."],
      ],
      choices: ["이름표 놓기", "심사표 묶기", "심사표 인쇄하기", "시간 담당에게 설명하기", "책상 옮기기"],
      answer: 2,
      clue: "Then I'll get staples from the office and bind them.",
      explanation:
        "심사표를 묶을 철심이 떨어졌고 여자는 시간 담당에게 설명해야 해서, 남자가 철심을 받아 심사표를 묶겠다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 서준아, 교내 토론 결승이 20분 뒤에 시작해.",
        "M: 알아. 두 팀은 앞자리에 앉았어?",
        "W: 응, 두 탁자 다 이름표까지 놨어.",
        "M: 잘했다. 심사표는 인쇄했어?",
        "W: 인쇄는 했는데 스테이플러 심이 떨어졌어.",
        "M: 낱장이면 진행 중에 섞여 버려.",
        "W: 나는 시작 전에 시간 담당한테 설명해야 해.",
        "M: 그럼 내가 행정실에서 심을 받아 와서 묶을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 구입할 노트북 가방을 고르시오.",
      lines: [
        ["M", "Hayeon, which laptop bag are you buying?"],
        ["W", "Let me look at the five of them again."],
        ["M", "Does it have to fit a fifteen-inch laptop?"],
        ["W", "Yes, mine is exactly fifteen inches."],
        ["M", "Okay. Do you want a shoulder strap?"],
        ["W", "Yes, I carry it across my body on the bus."],
        ["M", "Got it. And the price?"],
        ["W", "Under sixty thousand won, including tax."],
        ["M", "Then only one bag on this list fits you."],
        ["W", "Good. Let's order it after dinner."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Yes, mine is exactly fifteen inches.",
      explanation:
        "15인치가 들어가고, 어깨끈이 있으며, 6만 원 미만인 것을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Fits: 13 inch / Strap: Yes / Price: 45,000 won" },
          { no: 2, label: "②", value: "Fits: 15 inch / Strap: No / Price: 50,000 won" },
          { no: 3, label: "③", value: "Fits: 15 inch / Strap: Yes / Price: 75,000 won" },
          { no: 4, label: "④", value: "Fits: 13 inch / Strap: No / Price: 35,000 won" },
          { no: 5, label: "⑤", value: "Fits: 15 inch / Strap: Yes / Price: 55,000 won" },
        ],
      },
      translation: [
        "M: 하연아, 어떤 노트북 가방 살 거야?",
        "W: 다섯 개 다시 볼게.",
        "M: 15인치가 들어가야 해?",
        "W: 응, 내 노트북이 딱 15인치야.",
        "M: 알겠어. 어깨끈이 필요해?",
        "W: 응, 버스에서 몸에 가로질러 메.",
        "M: 그렇구나. 가격은?",
        "W: 세금 포함해서 6만 원 미만.",
        "M: 그럼 이 목록에서 맞는 건 하나뿐이야.",
        "W: 좋아. 저녁 먹고 주문하자.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 원서를 접수할 날짜를 고르시오.",
      lines: [
        ["M", "Hayeon, when should we hand in the application forms?"],
        ["W", "How about September 2nd? That's next Tuesday."],
        ["M", "The office only takes forms from Wednesday onward."],
        ["W", "Then what about September 4th?"],
        ["M", "We have the school photo day all day on the 4th."],
        ["W", "Hmm. I'm free on September 12th."],
        ["M", "But the deadline is the 10th."],
        ["W", "Oh, right. Then let's go on September 8th."],
        ["M", "September 8th works. School ends at one that day."],
        ["W", "Perfect. Let's meet at the office at two."],
      ],
      choices: ["9월 2일", "9월 4일", "9월 8일", "9월 10일", "9월 12일"],
      answer: 3,
      clue: "Oh, right. Then let's go on September 8th.",
      explanation:
        "2일은 접수를 받지 않고, 4일에는 사진 촬영일이 있으며, 12일은 마감(10일) 이후다. 두 사람은 9월 8일에 접수하기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 하연아, 원서 언제 낼까?",
        "W: 9월 2일 어때? 다음 주 화요일이야.",
        "M: 행정실은 수요일부터 접수해.",
        "W: 그럼 9월 4일은?",
        "M: 4일은 하루 종일 학교 사진 촬영이야.",
        "W: 음. 나는 9월 12일이 비어.",
        "M: 그런데 마감이 10일이야.",
        "W: 아, 맞다. 그럼 9월 8일에 가자.",
        "M: 9월 8일 괜찮아. 그날은 1시에 끝나.",
        "W: 좋아. 2시에 행정실에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seojun, why is your voice so quiet today?"],
        ["M", "I was at the children's center all day on Sunday."],
        ["W", "Did you go there to play games with the kids?"],
        ["M", "No, I read picture books aloud for four hours."],
        ["W", "Four whole hours of reading out loud?"],
        ["M", "Twelve books, and the children kept asking for more."],
        ["W", "No wonder your voice is completely gone today."],
        ["M", "The hardest part was doing a different voice for each animal."],
        ["W", "Are you going to do it again next weekend?"],
        ["M", "Yes, I'm going back next Sunday anyway."],
      ],
      choices: ["책 읽어 주기", "아이들과 놀기", "센터 청소하기", "책 정리하기", "수업 듣기"],
      answer: 1,
      clue: "No, I read picture books aloud for four hours.",
      explanation:
        "남자는 일요일에 아동 센터에서 그림책 열두 권을 네 시간 동안 읽어 주었다고 했다. 따라서 답은 ①이다.",
      translation: [
        "W: 서준아, 오늘 왜 목소리가 작아?",
        "M: 일요일 하루 종일 아동 센터에 있었어.",
        "W: 아이들이랑 놀아 주러 간 거야?",
        "M: 아니, 네 시간 동안 그림책을 소리 내서 읽어 줬어.",
        "W: 네 시간을 꼬박 소리 내서?",
        "M: 열두 권. 아이들이 계속 더 읽어 달라고 했어.",
        "W: 그러니 오늘 목이 완전히 쉬었지.",
        "M: 제일 힘든 건 동물마다 다른 목소리를 내는 거였어.",
        "W: 다음 주말에도 또 해?",
        "M: 응, 다음 일요일에 또 가.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the physical education office. " +
            "The outdoor field will be resurfaced from Monday to Friday next week. " +
            "No class may use the field during those five days. " +
            "All physical education classes will move to the gym instead. " +
            "Please bring indoor shoes for the whole week. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "실내화 구입을 안내하려고",
        "체육복 규정을 알리려고",
        "운동장 사용 제한을 알리려고",
        "체육관 공사를 알리려고",
      ],
      answer: 4,
      clue: "No class may use the field during those five days.",
      explanation:
        "다음 주 닷새 동안 운동장 바닥 공사로 운동장을 쓸 수 없고 체육관에서 수업한다고 알리는 방송이다. 따라서 답은 ④이다.",
      translation: [
        "M: 안내 말씀 드립니다. 체육부입니다. 다음 주 월요일부터 금요일까지 운동장 바닥을 새로 깝니다. 그 닷새 동안은 어떤 반도 운동장을 쓸 수 없습니다. 모든 체육 수업은 대신 체육관에서 합니다. 그 주 내내 실내화를 가져오세요. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the bookstore. What can I get you?"],
        ["W", "Three study guides and two pencil cases, please."],
        ["M", "A guide is eleven dollars and a case is four."],
        ["W", "So the total is forty-one dollars."],
        ["M", "That's right. Are you a member here?"],
        ["W", "Yes, I joined last year."],
        ["M", "Then I can take seven dollars off your total."],
        ["W", "Thank you very much."],
      ],
      choices: ["$30", "$34", "$32", "$36", "$41"],
      answer: 2,
      clue: "Then I can take seven dollars off your total.",
      explanation:
        "참고서 3권 33달러와 필통 2개 8달러를 더하면 41달러이고, 회원 할인 7달러를 빼면 34달러이다. 따라서 답은 ②이다.",
      translation: [
        "M: 서점에 오신 걸 환영합니다. 무엇을 드릴까요?",
        "W: 참고서 세 권이랑 필통 두 개 주세요.",
        "M: 참고서는 11달러, 필통은 4달러입니다.",
        "W: 그럼 모두 41달러네요.",
        "M: 맞습니다. 회원이신가요?",
        "W: 네, 작년에 가입했어요.",
        "M: 그럼 7달러를 빼 드릴게요.",
        "W: 정말 감사합니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seojun, you've solved that same problem set four times."],
        ["M", "I keep getting the answers right, but slowly."],
        ["W", "How long does one set take you?"],
        ["M", "About fifty minutes, and the exam gives thirty."],
        ["W", "Do you time yourself while you practice?"],
        ["M", "No, I just work until I finish."],
        ["W", "Then your body never learns what thirty minutes feels like."],
        ["M", "So should I put a clock on the desk?"],
        ["W", "Set a timer for thirty minutes and stop when it rings."],
      ],
      choices: [
        "I never solve problem sets.",
        "The exam gives me two hours.",
        "I finish in ten minutes.",
        "Let's skip the exam.",
        "I'll do that in tonight's practice.",
      ],
      answer: 5,
      clue: "Set a timer for thirty minutes and stop when it rings.",
      explanation:
        "여자가 30분 타이머를 맞추고 울리면 멈추라고 했으므로, 오늘 밤 연습에서 그렇게 하겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 서준아, 같은 문제집을 네 번째 풀고 있네.",
        "M: 답은 계속 맞는데 느려.",
        "W: 한 세트에 얼마나 걸려?",
        "M: 50분쯤. 시험은 30분 줘.",
        "W: 연습할 때 시간을 재?",
        "M: 아니, 끝날 때까지 그냥 풀어.",
        "W: 그럼 몸이 30분이 어떤 느낌인지 못 배우지.",
        "M: 그럼 책상에 시계를 올려놔야 해?",
        "W: 30분 타이머를 맞추고 울리면 멈춰.",
        "M: 오늘 밤 연습 때 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Hayeon, your laptop fan has been roaring all afternoon."],
        ["W", "It does that whenever I use it for more than an hour."],
        ["M", "Where do you put it while you work?"],
        ["W", "On my bed, usually on the blanket."],
        ["M", "The blanket blocks the air holes underneath."],
        ["W", "I didn't know there were holes on the bottom."],
        ["M", "There are, and the fan can't push heat out through cloth."],
        ["W", "Then where should I put it instead?"],
        ["M", "On any hard flat surface, like a desk or a tray."],
      ],
      choices: [
        "My laptop has no fan.",
        "The blanket keeps it cool.",
        "I'll use a tray from now on.",
        "I'll work on my bed tonight.",
        "I'll buy a new laptop.",
      ],
      answer: 3,
      clue: "On any hard flat surface, like a desk or a tray.",
      explanation:
        "남자가 책상이나 쟁반처럼 단단하고 평평한 곳에 두라고 했으므로, 이제부터 쟁반을 쓰겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 하연아, 네 노트북 팬이 오후 내내 요란해.",
        "W: 한 시간 넘게 쓰면 늘 그래.",
        "M: 쓸 때 어디에 올려 둬?",
        "W: 보통 침대 위, 이불 위에.",
        "M: 이불이 아래쪽 공기 구멍을 막아.",
        "W: 바닥에 구멍이 있는 줄 몰랐어.",
        "M: 있어. 천을 통해서는 열을 못 내보내.",
        "W: 그럼 어디에 둬야 해?",
        "M: 책상이나 쟁반처럼 단단하고 평평한 데면 돼.",
        "W: 이제부터 쟁반을 쓸게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Hayeon, our club's online notice gets almost no views."],
        ["W", "Where exactly do you post it?"],
        ["M", "On the school website, under the club section."],
        ["W", "Does anyone open that section on their own?"],
        ["M", "Probably not. I only go there when a teacher tells me to."],
        ["W", "So the notice sits where nobody looks."],
        ["M", "Then where should I put it instead?"],
        ["W", "In the class group chat, where people already read every day."],
        ["M", "Won't that annoy people during exam week?"],
        ["W", "Not if you post once and keep it to three lines."],
      ],
      choices: [
        "I'll post a short one tomorrow.",
        "Our club has no notices.",
        "Everyone reads the website.",
        "I'll write ten pages instead.",
        "Let's stop posting notices.",
      ],
      answer: 1,
      clue: "Not if you post once and keep it to three lines.",
      explanation:
        "여자가 한 번만, 세 줄로 올리면 괜찮다고 했으므로, 내일 짧게 올리겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 하연아, 우리 동아리 온라인 공지를 보는 사람이 거의 없어.",
        "W: 정확히 어디에 올려?",
        "M: 학교 누리집 동아리 게시판에.",
        "W: 누가 그 게시판을 스스로 들어가?",
        "M: 아마 없을걸. 나도 선생님이 시킬 때만 가.",
        "W: 그럼 아무도 안 보는 데 놓여 있는 거지.",
        "M: 그럼 어디에 올려야 해?",
        "W: 반 단체 대화방에. 다들 매일 읽잖아.",
        "M: 시험 주간에 귀찮아하지 않을까?",
        "W: 한 번만, 세 줄로 올리면 괜찮아.",
        "M: 내일 짧게 올릴게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jieun이 Hyunwoo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jieun : ________________",
      lines: [
        [
          "W",
          "Jieun and Hyunwoo are returning books at the library counter. " +
            "Hyunwoo has put his three books on the desk and turned to leave. " +
            "Jieun sees that one of his books still has a bus card tucked inside. " +
            "The librarian is already sliding the pile onto the return cart. " +
            "She wants to tell him before the books go back on the shelves. " +
            "In this situation, what would Jieun most likely say to Hyunwoo?",
        ],
      ],
      choices: [
        "Let's borrow three more books.",
        "The library closes at six.",
        "I'll pay your late fee.",
        "Your bus card is in that book.",
        "You should read this one first.",
      ],
      answer: 4,
      clue: "Jieun sees that one of his books still has a bus card tucked inside.",
      explanation:
        "현우가 반납한 책 안에 교통 카드가 끼어 있으므로, 그 사실을 알려 주는 ④가 가장 적절하다.",
      translation: [
        "W: 지은이와 현우는 도서관 창구에서 책을 반납하고 있습니다. 현우는 책 세 권을 창구에 올려놓고 돌아섰습니다. 지은이는 그중 한 권에 교통 카드가 끼어 있는 것을 봅니다. 사서 선생님은 이미 책 더미를 반납 수레로 밀고 있습니다. 지은이는 책이 서가로 돌아가기 전에 알려 주고 싶습니다. 이런 상황에서 지은이가 현우에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
