/** 중3 듣기 13회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 13회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 탁상 스탠드를 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a desk lamp?"],
        ["M", "Yes. The one in my room is too dim for reading."],
        ["W", "We have lamps with a straight neck and lamps with a bendable neck."],
        ["M", "A bendable one, please. I want to point the light at my book."],
        ["W", "Of course. Do you want a round base or a clip?"],
        ["M", "A round base. My desk is too thick for a clip."],
        ["W", "Then two are left. One has a small drawer in the base and one doesn't."],
        ["M", "I'll take the plain one. I never use those little drawers."],
        ["W", "Good choice. This one also has three brightness levels."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "I'll take the plain one. I never use those little drawers.",
      explanation:
        "남자는 목이 구부러지는 스탠드를, 둥근 받침이 있는 것으로, 서랍이 없는 것을 고른다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five desk lamps shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a lamp with a STRAIGHT rigid neck standing on a ROUND flat base, the base plain. " +
          "Second: a lamp with a STRAIGHT rigid neck fixed to a CLAMP CLIP instead of a base. " +
          "Third: a lamp with a BENDABLE curved flexible neck fixed to a CLAMP CLIP instead of a base. " +
          "Fourth: a lamp with a BENDABLE curved flexible neck standing on a ROUND base that has a small DRAWER in it with a knob. " +
          "Fifth: a lamp with a BENDABLE curved flexible neck standing on a ROUND flat base with no drawer at all.",
      },
      translation: [
        "W: 안녕하세요. 탁상 스탠드 찾으세요?",
        "M: 네. 제 방에 있는 건 책 읽기에 너무 어두워요.",
        "W: 목이 곧은 것과 구부러지는 것이 있어요.",
        "M: 구부러지는 걸로요. 빛을 책 쪽으로 향하게 하고 싶어요.",
        "W: 알겠습니다. 받침이 둥근 것이 좋으세요, 집게형이 좋으세요?",
        "M: 둥근 받침이요. 제 책상은 두꺼워서 집게가 안 물려요.",
        "W: 그럼 두 개 남았네요. 하나는 받침에 작은 서랍이 있고 하나는 없습니다.",
        "M: 서랍 없는 걸로 할게요. 그런 작은 서랍은 안 쓰거든요.",
        "W: 좋은 선택이세요. 이건 밝기도 세 단계로 조절됩니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 봉사 동아리 모집에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hyunsoo, are you going to apply to the volunteer club?"],
        ["M", "I'm thinking about it, but I don't know the details."],
        ["W", "They're taking new members until the end of this week."],
        ["M", "What do the members actually do?"],
        ["W", "They visit the nursing home near the school twice a month."],
        ["M", "Twice a month. Is there a meeting at school as well?"],
        ["W", "Yes, every Thursday after the sixth period, in room 203."],
        ["M", "How many people are they taking?"],
        ["W", "Fifteen this term. Last year twice that many applied."],
        ["M", "Then I'd better hand in my form tomorrow."],
        ["W", "You should. The forms are on the desk outside the staff room."],
      ],
      choices: ["모집 마감", "하는 일", "모임 요일", "모집 인원", "지도 교사"],
      answer: 5,
      clue: "Fifteen this term. Last year twice that many applied.",
      explanation:
        "모집 마감(이번 주말), 하는 일(요양원 방문), 모임 요일(목요일 6교시 후), 모집 인원(15명)은 언급되지만 지도 교사는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 현수야, 봉사 동아리 지원할 거야?",
        "M: 생각 중인데 자세한 건 몰라.",
        "W: 이번 주말까지 새 부원을 받아.",
        "M: 부원들은 실제로 뭘 하는데?",
        "W: 학교 근처 요양원에 한 달에 두 번 가.",
        "M: 한 달에 두 번. 학교에서 모임도 있어?",
        "W: 응, 목요일마다 6교시 끝나고 203호에서.",
        "M: 몇 명 뽑아?",
        "W: 이번 학기에 15명. 작년에는 그 두 배가 지원했대.",
        "M: 그럼 내일 신청서를 내야겠다.",
        "W: 그래. 신청서는 교무실 앞 책상에 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junho. It's Seoyeon from the drama club."],
        ["M", "Oh, hi. Is the rehearsal still at three tomorrow?"],
        ["W", "That's why I'm calling. The hall is being used for an exam."],
        ["M", "So we can't practice there at all?"],
        ["W", "Not tomorrow. We're moving to the music room on the third floor."],
        ["M", "Same time, though?"],
        ["W", "Same time, three o'clock. Could you tell the others in your class?"],
        ["M", "Sure. I'll send them a message tonight."],
      ],
      choices: [
        "연습 장소가 바뀐 것을 알리려고",
        "연습 시간을 미루려고",
        "대본을 빌려 달라고 하려고",
        "공연 표를 사 달라고 하려고",
        "동아리 가입을 권하려고",
      ],
      answer: 1,
      clue: "Not tomorrow. We're moving to the music room on the third floor.",
      explanation:
        "강당에서 시험이 있어 연습 장소가 3층 음악실로 바뀌었다는 것을 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준호야. 연극부 서연이야.",
        "M: 아, 안녕. 내일 연습 3시 맞지?",
        "W: 그것 때문에 전화했어. 강당을 시험 때문에 쓴대.",
        "M: 그럼 거기서 연습 못 하는 거야?",
        "W: 내일은 안 돼. 3층 음악실로 옮겨.",
        "M: 시간은 그대로고?",
        "W: 시간은 그대로 3시야. 너희 반 애들한테 좀 알려 줄래?",
        "M: 그래. 오늘 밤에 메시지 보낼게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Dohyun, what time should we meet at the stadium?"],
        ["M", "The game starts at seven, and the gates open an hour before."],
        ["W", "Then we should get there while the queue is short."],
        ["M", "How about five thirty?"],
        ["W", "That's before the gates open. We'd just be standing outside."],
        ["M", "True. How long does it take you to get there?"],
        ["W", "Forty minutes by subway from my house."],
        ["M", "Then let's meet at six, right when they open."],
        ["W", "Six it is. I'll wait at the east entrance."],
      ],
      choices: ["5:00 p.m.", "5:30 p.m.", "6:00 p.m.", "6:30 p.m.", "7:00 p.m."],
      answer: 3,
      clue: "Then let's meet at six, right when they open.",
      explanation:
        "경기가 7시에 시작하고 문은 한 시간 전에 열리므로 두 사람은 문이 열리는 6시에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 도현아, 경기장에서 몇 시에 만날까?",
        "M: 경기는 7시에 시작하고 문은 한 시간 전에 열려.",
        "W: 그럼 줄이 짧을 때 가는 게 좋겠다.",
        "M: 5시 30분은 어때?",
        "W: 그건 문 열기 전이잖아. 밖에 서 있기만 할걸.",
        "M: 그러네. 거기까지 얼마나 걸려?",
        "W: 우리 집에서 지하철로 40분.",
        "M: 그럼 문 여는 6시에 만나자.",
        "W: 6시로 하자. 동쪽 입구에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, you've checked your phone five times in ten minutes."],
        ["M", "The results of the writing contest come out this afternoon."],
        ["W", "The one you entered in September?"],
        ["M", "Yes. I rewrote that story four times before I sent it."],
        ["W", "Then you did everything you could."],
        ["M", "I know, but three hundred people entered."],
        ["W", "Try to think about something else until three o'clock."],
        ["M", "I can't. I've read the same page of this book twice."],
      ],
      choices: ["nervous", "proud", "bored", "angry", "relaxed"],
      answer: 1,
      clue: "I can't. I've read the same page of this book twice.",
      explanation:
        "글쓰기 대회 결과 발표를 앞두고 휴대전화를 계속 확인하고 책도 눈에 들어오지 않는다고 했으므로 남자는 긴장하고 있다. 따라서 답은 ①이다.",
      translation: [
        "W: 상우야, 10분 동안 휴대전화를 다섯 번이나 봤어.",
        "M: 오늘 오후에 글쓰기 대회 결과가 나와.",
        "W: 9월에 낸 그거?",
        "M: 응. 보내기 전에 그 이야기를 네 번이나 고쳐 썼어.",
        "W: 그럼 할 수 있는 건 다 한 거네.",
        "M: 알아, 그런데 300명이나 냈대.",
        "W: 3시까지는 다른 생각을 해 봐.",
        "M: 안 돼. 이 책 같은 쪽을 두 번이나 읽었어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "Excuse me, is this your umbrella?"],
        ["W", "Oh, yes it is. Thank you."],
        ["M", "How much are these apples?"],
        ["W", "Three dollars for six."],
        ["M", "Could you tell me where the hospital is?"],
        ["W", "It's right behind that tall building."],
        ["M", "Excuse me, you dropped your ticket."],
        ["W", "Did I? Thank you so much."],
        ["M", "Are you ready to order?"],
        ["W", "Yes, I'll have the noodles."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Could you tell me where the hospital is?",
      explanation:
        "그림은 한 사람이 지도를 들고 길을 물어보고, 다른 사람이 손으로 높은 건물 뒤쪽을 가리켜 주는 장면이므로 ③이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a city street corner. A young man holding an open paper map in both hands is asking a passer-by for directions, looking at her. The woman beside him is pointing with her arm straight out toward a tall building further down the street. Both are drawn clearly. Shops, a crossing and the tall building are in the background.",
      },
      translation: [
        "① M: 실례합니다, 이거 당신 우산인가요? / W: 아, 네 맞아요. 감사합니다.",
        "② M: 이 사과 얼마예요? / W: 여섯 개에 3달러입니다.",
        "③ M: 병원이 어디인지 알려 주시겠어요? / W: 저 높은 건물 바로 뒤에 있어요.",
        "④ M: 실례합니다, 표를 떨어뜨리셨어요. / W: 제가요? 정말 감사합니다.",
        "⑤ M: 주문하시겠어요? / W: 네, 국수로 할게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yujin, were you in the art room during sixth period?"],
        ["W", "I was. We were finishing the class banner."],
        ["M", "Did the teacher say anything about the materials?"],
        ["W", "She did, but I was cutting cloth and only half listened."],
        ["M", "I had a dentist appointment, so I missed the whole class."],
        ["W", "Ah, that's why you weren't there."],
        ["M", "Could you write down what we have to bring on Friday?"],
        ["W", "Sure. I'll ask Suyeon too, so I don't get it wrong."],
        ["M", "Thanks. Just send it to me tonight."],
      ],
      choices: ["미술실 청소하기", "천 사다 주기", "선생님께 말씀드리기", "준비물을 적어 보내 주기", "현수막 그려 주기"],
      answer: 4,
      clue: "Could you write down what we have to bring on Friday?",
      explanation:
        "남자는 치과 때문에 미술 수업을 빠져서 금요일 준비물을 적어 보내 달라고 부탁한다. 따라서 답은 ④이다.",
      translation: [
        "M: 유진아, 6교시에 미술실에 있었어?",
        "W: 있었어. 학급 현수막 마무리했어.",
        "M: 선생님이 준비물에 대해 뭐라고 하셨어?",
        "W: 하시긴 했는데 천 자르느라 반만 들었어.",
        "M: 나는 치과 예약이 있어서 수업을 통째로 빠졌어.",
        "W: 아, 그래서 안 보였구나.",
        "M: 금요일에 뭘 가져와야 하는지 적어 줄 수 있어?",
        "W: 그래. 틀리지 않게 수연이한테도 물어볼게.",
        "M: 고마워. 오늘 밤에 보내 주면 돼.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Winter Camp에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about this year's Winter Camp."],
        ["M", "It will run for three days, from the twenty-sixth to the twenty-eighth."],
        ["M", "We will stay at the youth center in Pyeongchang."],
        ["M", "Each day starts with a morning walk and ends with a group talk."],
        ["M", "Bring warm clothes, a towel, and your own water bottle."],
        ["M", "Come to the counselling room if you want to know more."],
      ],
      choices: ["진행 기간", "장소", "하루 일정", "준비물", "참가비"],
      answer: 5,
      clue: "Bring warm clothes, a towel, and your own water bottle.",
      explanation:
        "기간(26일~28일), 장소(평창 청소년수련관), 하루 일정(아침 산책과 저녁 모둠 이야기), 준비물(따뜻한 옷·수건·물병)은 언급되지만 참가비는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 올해 Winter Camp를 안내합니다.",
        "M: 26일부터 28일까지 사흘 동안 진행됩니다.",
        "M: 평창에 있는 청소년수련관에서 묵습니다.",
        "M: 하루는 아침 산책으로 시작해서 모둠 이야기로 끝납니다.",
        "M: 따뜻한 옷, 수건, 개인 물병을 가져오세요.",
        "M: 더 알고 싶으면 상담실로 오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You will find one in almost every classroom and office."],
        ["W", "It hangs on the wall, and it is usually green or white."],
        ["W", "Teachers write on it with chalk or a special pen."],
        ["W", "When it is full, someone wipes it clean with an eraser."],
        ["W", "Nothing written on it lasts until the next day."],
      ],
      choices: ["게시판", "칠판", "달력", "거울", "화면"],
      answer: 2,
      clue: "Teachers write on it with chalk or a special pen.",
      explanation:
        "교실 벽에 걸려 있고 분필이나 전용 펜으로 쓰며 다 차면 지우개로 지운다고 했으므로 칠판이다. 따라서 답은 ②이다.",
      translation: [
        "W: 거의 모든 교실과 사무실에 하나씩 있습니다.",
        "W: 벽에 걸려 있고 보통 초록색이거나 흰색입니다.",
        "W: 선생님들은 분필이나 전용 펜으로 여기에 씁니다.",
        "W: 가득 차면 누군가 지우개로 깨끗이 지웁니다.",
        "W: 여기 쓴 것은 다음 날까지 남아 있지 않습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How long have you lived in this town?"],
        ["M", "Since I was five."],
        ["W", "Could you close the window, please?"],
        ["M", "Sure, it's getting cold."],
        ["W", "What are you going to do after the exam?"],
        ["M", "I'm going to sleep all day."],
        ["W", "Why were you absent yesterday?"],
        ["M", "It's on the second floor."],
        ["W", "Do you want to join our team?"],
        ["M", "I'd love to, thank you."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why were you absent yesterday?",
      explanation:
        "어제 왜 결석했는지 묻는 말에 2층에 있다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① W: 이 동네에 산 지 얼마나 됐어? / M: 다섯 살 때부터.",
        "② W: 창문 좀 닫아 줄래? / M: 그래, 추워지네.",
        "③ W: 시험 끝나고 뭐 할 거야? / M: 하루 종일 잘 거야.",
        "④ W: 어제 왜 결석했어? / M: 그건 2층에 있어.",
        "⑤ W: 우리 팀에 들어올래? / M: 좋지, 고마워.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaeyeon, the parents' meeting starts in half an hour."],
        ["W", "Is the classroom ready? What should I do?"],
        ["M", "I've already arranged the chairs and wiped the desks."],
        ["W", "Should I make the name cards, then?"],
        ["M", "Minjae finished those during lunch."],
        ["W", "Then what's left?"],
        ["M", "The handouts are still in the copy room. Forty of them."],
        ["W", "I'll go and bring them up now."],
        ["M", "Thanks. I'll set up the screen while you're gone."],
      ],
      choices: ["인쇄물 가져오기", "의자 정리하기", "이름표 만들기", "책상 닦기", "화면 설치하기"],
      answer: 1,
      clue: "I'll go and bring them up now.",
      explanation:
        "의자·책상·이름표는 이미 끝났고 여자는 인쇄실에 있는 유인물 40장을 가져오기로 한다. 따라서 답은 ①이다.",
      translation: [
        "M: 채연아, 학부모 모임이 30분 뒤에 시작해.",
        "W: 교실은 준비됐어? 내가 뭘 할까?",
        "M: 의자는 이미 정리했고 책상도 닦았어.",
        "W: 그럼 이름표를 만들까?",
        "M: 민재가 점심시간에 다 만들었어.",
        "W: 그럼 뭐가 남았어?",
        "M: 유인물이 아직 인쇄실에 있어. 40장.",
        "W: 내가 지금 가서 가져올게.",
        "M: 고마워. 네가 간 동안 화면을 설치할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 신청할 체험 활동을 고르시오.",
      lines: [
        ["W", "Sanghyun, here are the five field activities that still have places."],
        ["M", "Let's look. I can't go on a Saturday because of my grandmother."],
        ["W", "All right, that takes out one. What next?"],
        ["M", "I'd rather do something outdoors. I sit inside all week."],
        ["W", "Then one more is gone. Three are left."],
        ["M", "How much are they? I have thirty thousand won."],
        ["W", "One of them is thirty-five, so that's out too."],
        ["M", "Two left. How long do they take?"],
        ["W", "One runs for five hours, the other for three."],
        ["M", "Five hours is too long. I'll take the three-hour one."],
        ["W", "Then I'll sign you up this evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Five hours is too long. I'll take the three-hour one.",
      explanation:
        "토요일인 ⑤, 실내인 ①, 35,000원인 ④를 뺀다. 남은 ②와 ③ 중 3시간짜리는 ②이므로 답은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "일요일 / 실내 / 25,000원 / 3시간" },
          { no: 2, label: "②", value: "일요일 / 야외 / 28,000원 / 3시간" },
          { no: 3, label: "③", value: "금요일 / 야외 / 30,000원 / 5시간" },
          { no: 4, label: "④", value: "일요일 / 야외 / 35,000원 / 3시간" },
          { no: 5, label: "⑤", value: "토요일 / 야외 / 22,000원 / 4시간" },
        ],
      },
      translation: [
        "W: 상현아, 아직 자리가 있는 체험 활동이 이 다섯 개야.",
        "M: 보자. 할머니 때문에 토요일은 못 가.",
        "W: 그럼 하나 빠지네. 다음은?",
        "M: 야외였으면 좋겠어. 일주일 내내 실내에만 앉아 있잖아.",
        "W: 그럼 하나 더 빠진다. 세 개 남았어.",
        "M: 얼마야? 나는 3만 원 있어.",
        "W: 하나는 3만 5천 원이라 그것도 빠지네.",
        "M: 둘 남았다. 시간은 얼마나 걸려?",
        "W: 하나는 다섯 시간, 다른 하나는 세 시간이야.",
        "M: 다섯 시간은 너무 길어. 세 시간짜리로 할게.",
        "W: 그럼 오늘 저녁에 신청해 줄게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진 전시회에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Naeun, when should we go to the photo exhibition?"],
        ["W", "It's only open on the eighth, ninth, and tenth."],
        ["M", "I have a family dinner on the eighth."],
        ["W", "Then the ninth or the tenth."],
        ["M", "Isn't the tenth the day of the school sports day?"],
        ["W", "You're right. We'd be too tired to look at anything."],
        ["M", "So the ninth is the only day that works."],
        ["W", "Let's go on the ninth, then. I'll book two tickets tonight."],
      ],
      choices: ["7일", "8일", "9일", "10일", "11일"],
      answer: 3,
      clue: "So the ninth is the only day that works.",
      explanation:
        "8일은 가족 저녁 식사, 10일은 학교 체육대회여서 9일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 나은아, 사진 전시회 언제 갈까?",
        "W: 8일, 9일, 10일에만 열어.",
        "M: 나 8일에 가족 저녁 식사가 있어.",
        "W: 그럼 9일이나 10일이네.",
        "M: 10일은 학교 체육대회 날 아니야?",
        "W: 맞다. 그날은 너무 지쳐서 아무것도 못 보겠다.",
        "M: 그럼 9일밖에 안 되겠네.",
        "W: 그럼 9일에 가자. 오늘 밤에 표 두 장 예매할게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayoung, did you go to the concert last weekend?"],
        ["W", "No, I helped at the animal shelter on Saturday."],
        ["M", "The one behind the market? What did you do there?"],
        ["W", "I washed the dog bowls and walked two of the dogs."],
        ["M", "That sounds like hard work."],
        ["W", "It was, but one of them fell asleep on my shoe."],
        ["M", "Are you going again?"],
        ["W", "Every other Saturday from now on."],
      ],
      choices: ["음악회 가기", "친척 집 방문하기", "자전거 타기", "요리하기", "봉사활동 하기"],
      answer: 5,
      clue: "No, I helped at the animal shelter on Saturday.",
      explanation:
        "여자는 지난 토요일에 동물 보호소에서 봉사활동을 했다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 하영아, 지난 주말에 음악회 갔어?",
        "W: 아니, 토요일에 동물 보호소에서 도왔어.",
        "M: 시장 뒤에 있는 거기? 가서 뭐 했어?",
        "W: 개 밥그릇을 씻고 두 마리를 산책시켰어.",
        "M: 힘들었겠다.",
        "W: 힘들었는데, 한 마리가 내 신발에 기대서 잠들었어.",
        "M: 또 갈 거야?",
        "W: 이제부터 격주 토요일마다.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the student council."],
        ["W", "The back gate will be closed for two weeks from Monday."],
        ["W", "Workers are repairing the wall beside it."],
        ["W", "Please use the front gate or the side gate near the gym."],
        ["W", "The side gate opens at seven forty, ten minutes later than the front one."],
        ["W", "Leave home a little earlier so that you are not late."],
      ],
      choices: [
        "지각하지 말라고 당부하려고",
        "후문이 닫히는 것을 알리려고",
        "등교 시간이 바뀐 것을 알리려고",
        "학생회 임원을 모집하려고",
        "교내 공사 봉사자를 구하려고",
      ],
      answer: 2,
      clue: "The back gate will be closed for two weeks from Monday.",
      explanation:
        "담장 공사로 월요일부터 2주 동안 후문이 닫힌다는 것을 알리는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학생회입니다.",
        "W: 월요일부터 2주 동안 후문이 닫힙니다.",
        "W: 후문 옆 담장을 고치는 공사가 있습니다.",
        "W: 정문이나 체육관 옆 쪽문을 이용해 주세요.",
        "W: 쪽문은 정문보다 10분 늦은 7시 40분에 엽니다.",
        "W: 늦지 않도록 집에서 조금 일찍 나와 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the city pottery studio. How can I help you?"],
        ["W", "I'd like to join the one-day class with my sister."],
        ["M", "The class is fifteen dollars per person."],
        ["W", "Two people, then. That's thirty dollars."],
        ["M", "That's right. Would you like the clay delivered after firing?"],
        ["W", "Yes, please. How much is the delivery?"],
        ["M", "Six dollars for the two pieces together."],
        ["W", "All right, let's do that."],
        ["M", "And students get four dollars off the class fee."],
        ["W", "We're both students. Here are our cards."],
      ],
      choices: ["$28", "$30", "$32", "$34", "$36"],
      answer: 3,
      clue: "And students get four dollars off the class fee.",
      explanation:
        "수업료 15달러씩 두 명이면 30달러, 배송비 6달러를 더하면 36달러이다. 학생 할인 4달러를 빼면 32달러이므로 답은 ③이다.",
      translation: [
        "M: 시립 도예 공방입니다. 무엇을 도와드릴까요?",
        "W: 동생이랑 일일 수업을 듣고 싶어요.",
        "M: 수업은 한 사람에 15달러입니다.",
        "W: 그럼 두 명이요. 30달러네요.",
        "M: 맞습니다. 구운 다음에 작품을 배송해 드릴까요?",
        "W: 네, 부탁해요. 배송비는 얼마예요?",
        "M: 두 점 합쳐서 6달러입니다.",
        "W: 그럼 그렇게 해 주세요.",
        "M: 그리고 학생은 수업료에서 4달러 할인됩니다.",
        "W: 저희 둘 다 학생이에요. 학생증 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Jiwon, you've been staying after school every day this week."],
        ["M", "I'm building a model bridge for the science fair."],
        ["W", "How is it going?"],
        ["M", "Badly. It keeps breaking in the middle when I add weight."],
        ["W", "Have you changed anything between the tries?"],
        ["M", "I change two or three things each time and test it again."],
        ["W", "Then you can't tell which change helped."],
        ["M", "I never thought about that."],
        ["W", "Change one thing at a time and write down what happens."],
      ],
      choices: [
        "Then I'll test one change at a time tomorrow.",
        "The science fair is next month.",
        "My bridge is made of wood.",
        "I'd rather build something else.",
        "You should enter the fair as well.",
      ],
      answer: 1,
      clue: "Change one thing at a time and write down what happens.",
      explanation:
        "한 번에 한 가지만 바꾸고 결과를 적으라는 조언을 들었으므로, 내일부터 그렇게 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 지원아, 이번 주 내내 학교에 남아 있네.",
        "M: 과학전에 낼 모형 다리를 만들고 있어.",
        "W: 잘돼 가?",
        "M: 아니. 무게를 올리면 가운데가 자꾸 부러져.",
        "W: 시도할 때마다 뭘 바꿨어?",
        "M: 매번 두세 가지를 바꾸고 다시 시험해.",
        "W: 그러면 뭐가 도움이 됐는지 알 수가 없잖아.",
        "M: 그 생각은 못 했어.",
        "W: 한 번에 한 가지만 바꾸고 결과를 적어 봐.",
        "M: 그럼 내일부터 한 가지씩 바꿔서 시험해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Sumin, are you still practicing for the speech contest?"],
        ["W", "Every night, but I always run over the time limit."],
        ["M", "How long are you supposed to speak?"],
        ["W", "Four minutes. Last night I finished at five and a half."],
        ["M", "Do you time yourself while you practice?"],
        ["W", "No, I just read it through and guess."],
        ["M", "Then you won't know where the extra time goes."],
        ["W", "That's true. It could be anywhere."],
        ["M", "Put a timer in front of you and mark where you pass three minutes."],
      ],
      choices: [
        "The contest is held in the main hall.",
        "I wrote the speech in one evening.",
        "My speech is about sea animals.",
        "Then I'll practice with a timer tonight.",
        "I've never entered a contest before.",
      ],
      answer: 4,
      clue: "Put a timer in front of you and mark where you pass three minutes.",
      explanation:
        "타이머를 앞에 두고 3분이 지나는 지점을 표시하라는 조언을 들었으므로, 오늘 밤에 타이머를 놓고 연습하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 수민아, 아직 말하기 대회 연습해?",
        "W: 매일 밤. 그런데 늘 시간을 넘겨.",
        "M: 몇 분 안에 해야 하는데?",
        "W: 4분. 어젯밤엔 5분 30초에 끝났어.",
        "M: 연습할 때 시간을 재?",
        "W: 아니, 그냥 쭉 읽고 짐작해.",
        "M: 그러면 어디서 시간이 늘어나는지 모르잖아.",
        "W: 그러네. 어디든 될 수 있겠다.",
        "M: 앞에 타이머를 놓고 3분이 지나는 지점을 표시해 봐.",
        "W: 그럼 오늘 밤에 타이머 놓고 연습할게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Minjun, you look tired again this morning."],
        ["M", "I couldn't sleep until two. I kept thinking about the test."],
        ["W", "Did you study right before you went to bed?"],
        ["M", "Yes, until half past one. Then I lay down."],
        ["W", "That's probably why. Your head is still running."],
        ["M", "But I can't finish everything earlier than that."],
        ["W", "My brother stops half an hour before bed and reads something easy."],
        ["M", "Does that really help him fall asleep?"],
        ["W", "He says he falls asleep in ten minutes now."],
      ],
      choices: [
        "The test is on Thursday morning.",
        "I usually get up at seven.",
        "I don't like reading before bed.",
        "Then I'll stop studying at one tonight.",
        "My brother goes to the same school.",
      ],
      answer: 4,
      clue: "He says he falls asleep in ten minutes now.",
      explanation:
        "자기 30분 전에 공부를 멈추면 금방 잠든다는 말을 들었으므로, 오늘 밤에는 1시에 공부를 그만두겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 민준아, 오늘 아침도 피곤해 보여.",
        "M: 2시까지 잠을 못 잤어. 시험 생각이 계속 나서.",
        "W: 자기 바로 전까지 공부했어?",
        "M: 응, 1시 30분까지. 그러고 누웠어.",
        "W: 아마 그래서일 거야. 머리가 계속 돌아가는 거지.",
        "M: 그런데 그보다 일찍은 다 못 끝내.",
        "W: 우리 오빠는 자기 30분 전에 멈추고 가벼운 걸 읽어.",
        "M: 그게 정말 잠드는 데 도움이 돼?",
        "W: 요즘은 10분이면 잠든대.",
        "M: 그럼 오늘 밤에는 1시에 공부를 그만둘게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Taeyeon이 Sejun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Taeyeon : ________________",
      lines: [
        ["W", "Taeyeon and Sejun are in the same school band."],
        ["W", "They will play together at the school festival next week."],
        ["W", "Sejun plays the drums very well and never misses a beat."],
        ["W", "However, he plays so loudly that nobody can hear the singer."],
        ["W", "The teacher told them that the singer must be heard at the back of the hall."],
        ["W", "Taeyeon does not want to say that his drumming is bad."],
        ["W", "She wants to ask him to play more softly during the singing parts."],
        ["W", "In this situation, what would Taeyeon most likely say to Sejun?"],
      ],
      choices: [
        "Let's change the song for the festival.",
        "Could you play more quietly when she sings?",
        "I think you should practice more this week.",
        "We don't need drums in this song.",
        "You should sing the song yourself.",
      ],
      answer: 2,
      clue: "She wants to ask him to play more softly during the singing parts.",
      explanation:
        "태연은 세준의 연주를 깎아내리지 않으면서, 노래하는 부분에서는 더 작게 쳐 달라고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "W: 태연과 세준은 같은 학교 밴드입니다.",
        "W: 두 사람은 다음 주 학교 축제에서 함께 연주합니다.",
        "W: 세준은 드럼을 아주 잘 치고 박자를 한 번도 놓치지 않습니다.",
        "W: 그런데 너무 크게 쳐서 노래하는 사람 목소리가 들리지 않습니다.",
        "W: 선생님은 강당 뒤쪽에서도 노래가 들려야 한다고 했습니다.",
        "W: 태연은 세준의 드럼 연주가 나쁘다고 말하고 싶지는 않습니다.",
        "W: 다만 노래하는 부분에서는 더 작게 쳐 달라고 부탁하고 싶습니다.",
        "W: 이런 상황에서 태연이 세준에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
