/** 중3 듣기 48회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 48회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 두 사람이 만들 학급 문패를 고르시오.",
      lines: [
        ["W", "Seongjun, how should the classroom nameplate look?"],
        ["M", "Let's make it a wide rectangle, not a circle."],
        ["W", "Do we add a picture beside the class number?"],
        ["M", "A small tree on the left side."],
        ["W", "Should the whole plate have a border?"],
        ["M", "A double border, so it stands out from the wall."],
        ["W", "And the hook for hanging it?"],
        ["M", "One hook in the middle of the top edge."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "A small tree on the left side. / A double border, so it stands out from the wall.",
      explanation:
        "가로 직사각형에 왼쪽 나무 그림, 이중 테두리, 위 가운데 고리가 있는 문패이다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five blank classroom nameplates side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a WIDE RECTANGLE with a small TREE on the LEFT, a SINGLE thin border and one HOOK at the top center. " +
          "② a WIDE RECTANGLE with a small TREE on the LEFT, a DOUBLE border and one HOOK at the top center. " +
          "③ a WIDE RECTANGLE with a small TREE on the RIGHT, a DOUBLE border and one HOOK at the top center. " +
          "④ a CIRCLE plate with a small TREE on the left and a DOUBLE border. " +
          "⑤ a WIDE RECTANGLE with a DOUBLE border, no tree, and TWO HOOKS at the top corners.",
      },
      translation: [
        "W: 성준아, 학급 문패를 어떻게 만들까?",
        "M: 동그라미 말고 가로로 긴 네모로 하자.",
        "W: 반 번호 옆에 그림도 넣어?",
        "M: 왼쪽에 작은 나무 하나.",
        "W: 판 전체에 테두리를 둘까?",
        "M: 이중 테두리로. 벽에서 눈에 띄게.",
        "W: 거는 고리는?",
        "M: 위쪽 가장자리 가운데에 고리 하나.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 과학 전시회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Dain, when is the science fair this year?"],
        ["W", "It runs for two days, next Monday and Tuesday."],
        ["M", "Where are the projects displayed?"],
        ["W", "In the science building, on the first floor."],
        ["M", "How many students are in one team?"],
        ["W", "Up to three, and each team gets one table."],
        ["M", "What do the judges look at?"],
        ["W", "The idea, the method and the poster."],
        ["M", "Can other grades come and see it?"],
        ["W", "Everyone can visit during lunch break."],
      ],
      choices: ["열리는 기간", "전시하는 곳", "한 팀의 인원", "심사 기준", "출품 신청 기한"],
      answer: 5,
      clue: "It runs for two days, next Monday and Tuesday.",
      explanation:
        "기간, 장소, 인원, 심사 기준은 말했지만 신청 기한은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 다인아, 올해 과학 전시회가 언제야?",
        "W: 다음 주 월요일이랑 화요일, 이틀 동안.",
        "M: 작품은 어디에 전시해?",
        "W: 과학관 1층에.",
        "M: 한 팀에 몇 명이야?",
        "W: 세 명까지. 팀마다 탁자 하나씩.",
        "M: 심사위원은 뭘 봐?",
        "W: 착상, 방법, 그리고 포스터.",
        "M: 다른 학년도 보러 올 수 있어?",
        "W: 점심시간에는 누구나 볼 수 있어.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junho. This is Sohee from the art club."],
        ["M", "Hi. Is the exhibition still on for Friday?"],
        ["W", "That's what I'm calling about."],
        ["M", "Did something change with the room?"],
        ["W", "The first floor hallway is being painted that day."],
        ["M", "So we can't hang anything on those walls."],
        ["W", "The teacher offered the library lobby instead."],
        ["M", "That space is smaller but brighter."],
        ["W", "I'm calling to move the exhibition to the library lobby."],
      ],
      choices: [
        "전시 장소를 바꾸려고",
        "전시를 취소하려고",
        "작품을 부탁하려고",
        "결석을 알리려고",
        "감사를 전하려고",
      ],
      answer: 1,
      clue: "I'm calling to move the exhibition to the library lobby.",
      explanation:
        "여자는 전시 장소를 도서관 앞으로 옮기려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준호야. 미술 동아리 소희야.",
        "M: 안녕. 전시 금요일에 그대로 해?",
        "W: 그것 때문에 전화한 거야.",
        "M: 장소에 무슨 일 있어?",
        "W: 그날 1층 복도에 페인트를 칠한대.",
        "M: 그럼 그 벽에는 아무것도 못 걸겠네.",
        "W: 선생님이 대신 도서관 앞을 쓰라고 하셨어.",
        "M: 거기가 좁긴 해도 더 밝아.",
        "W: 전시를 도서관 앞으로 옮기려고 전화했어.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 출발할 시각을 고르시오.",
      lines: [
        ["W", "Hyunwoo, what time does the exhibition close?"],
        ["M", "The last entry is at five o'clock."],
        ["W", "How long does it take to get there?"],
        ["M", "Forty minutes by bus from the school gate."],
        ["W", "Then we should leave before four twenty."],
        ["M", "I also want to pick up my ticket at the office."],
        ["W", "That takes another ten minutes, I'd say."],
        ["M", "Let's leave at four o'clock then."],
        ["W", "Four o'clock. I'll wait at the bus stop."],
      ],
      choices: ["3:30 p.m.", "4:00 p.m.", "4:20 p.m.", "4:40 p.m.", "5:00 p.m."],
      answer: 2,
      clue: "Let's leave at four o'clock then.",
      explanation:
        "이동 시간과 표 찾는 시간을 감안해 4시에 출발하기로 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 현우야, 전시 몇 시에 닫아?",
        "M: 마지막 입장이 다섯 시야.",
        "W: 거기까지 얼마나 걸려?",
        "M: 학교 정문에서 버스로 40분.",
        "W: 그럼 네 시 20분 전에는 나가야겠네.",
        "M: 나는 사무실에서 표도 찾아야 해.",
        "W: 그건 10분쯤 더 걸리겠다.",
        "M: 그럼 네 시에 출발하자.",
        "W: 네 시. 정류장에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Nayeon, you've been checking the clock all morning long."],
        ["W", "My interview at the high school is at two o'clock."],
        ["M", "Have you prepared your answers for it?"],
        ["W", "I practiced them with my sister every night this week."],
        ["M", "Then you should be perfectly fine."],
        ["W", "Three teachers sit there and ask questions at once."],
        ["M", "Do you know what they usually ask?"],
        ["W", "Why I chose the school, mostly."],
        ["M", "Just answer the way you practiced at home."],
        ["W", "My stomach has been tight since breakfast."],
      ],
      choices: ["bored", "proud", "angry", "nervous", "satisfied"],
      answer: 4,
      clue: "My stomach has been tight since breakfast.",
      explanation:
        "면접을 앞두고 아침부터 속이 조여 온다고 하므로 긴장하고 있다. 따라서 답은 ④이다.",
      translation: [
        "M: 나연아, 아침 내내 시계만 보고 있네.",
        "W: 두 시에 고등학교 면접이 있어.",
        "M: 답변은 준비했어?",
        "W: 이번 주 내내 밤마다 언니랑 연습했어.",
        "M: 그럼 아주 괜찮을 거야.",
        "W: 선생님 세 분이 앉아서 한꺼번에 질문하셔.",
        "M: 보통 뭘 물어보시는지는 알아?",
        "W: 대부분 왜 그 학교를 골랐는지.",
        "M: 집에서 연습한 대로만 대답해.",
        "W: 아침부터 속이 계속 조여.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Could you keep the noise down?"],
        ["M", "Sorry, we'll be quiet."],
        ["ANN", "Number two."],
        ["W", "Is this book available?"],
        ["M", "Someone borrowed it yesterday."],
        ["ANN", "Number three."],
        ["W", "Your shoelace is untied."],
        ["M", "Thanks, I didn't notice."],
        ["ANN", "Number four."],
        ["W", "Where do I sign up?"],
        ["M", "On the sheet by the door."],
        ["ANN", "Number five."],
        ["W", "Do you have a pen I can use?"],
        ["M", "Take this blue one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Your shoelace is untied.",
      explanation:
        "그림은 풀린 신발 끈을 알려 주자 고마워하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "In a school corridor, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A girl walking beside a boy points down at his shoe, whose lace trails loose on the floor. " +
          "The boy looks down at his own foot and raises one hand in thanks while holding books in the other arm. " +
          "Lockers and a window are drawn simply along the wall behind them.",
      },
      translation: [
        "① W: 소리 좀 줄여 주시겠어요? / M: 죄송해요, 조용히 할게요.",
        "② W: 이 책 빌릴 수 있나요? / M: 어제 누가 빌려 갔어요.",
        "③ W: 신발 끈 풀렸어. / M: 고마워, 몰랐어.",
        "④ W: 어디에 신청해요? / M: 문 옆 종이에요.",
        "⑤ W: 쓸 펜 있어? / M: 이 파란 거 써.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, you sit right next to the classroom speaker."],
        ["M", "I hear every announcement twice as loud."],
        ["W", "I'm going to the dentist tomorrow morning."],
        ["M", "Will you miss the whole first period?"],
        ["W", "Probably the first two, if the bus is slow."],
        ["M", "The teacher gives out the field trip details then."],
        ["W", "That's exactly what worries me."],
        ["M", "She only says it once over the speaker."],
        ["W", "Could you write down what she announces?"],
        ["M", "I'll text you everything at lunch."],
      ],
      choices: [
        "전달 사항을 적어 주기",
        "병원에 같이 가 주기",
        "숙제를 내 주기",
        "자리를 바꿔 주기",
        "선생님께 여쭤봐 주기",
      ],
      answer: 1,
      clue: "Could you write down what she announces?",
      explanation:
        "여자는 선생님의 전달 사항을 적어 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 태민아, 너 교실 스피커 바로 옆에 앉잖아.",
        "M: 방송이 두 배로 크게 들려.",
        "W: 나 내일 아침에 치과에 가.",
        "M: 1교시를 통째로 빠져?",
        "W: 버스가 느리면 2교시까지도.",
        "M: 그때 선생님이 현장 학습 안내를 하셔.",
        "W: 바로 그게 걱정이야.",
        "M: 스피커로 딱 한 번만 말씀하시지.",
        "W: 선생님이 알려 주시는 거 좀 적어 줄 수 있어?",
        "M: 점심때 다 문자로 보내 줄게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 마무리 행사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The garden club is holding a harvest day. " +
            "It takes place next Saturday morning behind the gym. " +
            "We pick the last vegetables of the year together. " +
            "Gloves and baskets are prepared for everyone. " +
            "Anyone from any grade may come and join. " +
            "The vegetables go to the school kitchen afterwards.",
        ],
      ],
      choices: ["열리는 날과 장소", "하는 일", "준비된 물건", "참여할 수 있는 사람", "신청 방법"],
      answer: 5,
      clue: "It takes place next Saturday morning behind the gym.",
      explanation:
        "날짜와 장소, 하는 일, 준비물, 참여 대상은 말했지만 신청 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 텃밭 동아리에서 수확하는 날을 엽니다. 다음 주 토요일 오전에 체육관 뒤에서 열립니다. 올해 마지막 채소를 함께 거둡니다. 장갑과 바구니는 모두에게 준비돼 있습니다. 학년에 상관없이 누구나 오셔도 됩니다. 거둔 채소는 학교 급식실로 보냅니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You open this when the sun is too strong. " +
            "It also keeps the rain off your head and shoulders. " +
            "A metal frame holds the cloth in a wide circle. " +
            "People leave it behind in cafés more than anything else. " +
            "A strong gust can turn it inside out in a second.",
        ],
      ],
      choices: ["모자", "외투", "장갑", "우산", "가방"],
      answer: 4,
      clue: "A metal frame holds the cloth in a wide circle.",
      explanation:
        "햇빛과 비를 가리며 살대가 천을 둥글게 펼치는 것은 우산이다. 따라서 답은 ④이다.",
      translation: [
        "W: 이것은 햇빛이 너무 셀 때 펼칩니다. 머리와 어깨에 비가 닿지 않게도 해 줍니다. 금속 살대가 천을 넓은 원으로 펼쳐 줍니다. 사람들이 찻집에 가장 많이 두고 가는 물건입니다. 센 바람이 불면 순식간에 뒤집히기도 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Did you get enough sleep?"],
        ["W", "About six hours."],
        ["ANN", "Number two."],
        ["M", "Where should we put the boxes?"],
        ["W", "Against the back wall."],
        ["ANN", "Number three."],
        ["M", "How many people signed up?"],
        ["W", "My sister is two years older."],
        ["ANN", "Number four."],
        ["M", "Can you come a little earlier?"],
        ["W", "I'll be there by eight."],
        ["ANN", "Number five."],
        ["M", "Is the printer working now?"],
        ["W", "Yes, someone fixed it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How many people signed up?",
      explanation:
        "몇 명이 신청했는지 묻는 말에 언니 얘기를 했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 잠은 충분히 잤어? / W: 여섯 시간쯤.",
        "② M: 상자는 어디에 놓을까? / W: 뒤쪽 벽에 붙여서.",
        "③ M: 몇 명이나 신청했어? / W: 우리 언니는 두 살 위야.",
        "④ M: 조금 일찍 올 수 있어? / W: 여덟 시까지 갈게.",
        "⑤ M: 인쇄기 이제 돼? / W: 응, 누가 고쳤어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Kiyoung, the science fair opens in fifteen minutes."],
        ["M", "Our poster is on the board and the model is out."],
        ["W", "Did anyone bring the extension cord?"],
        ["M", "It's still in the science room drawer."],
        ["W", "Our lamp won't reach the wall socket without it."],
        ["M", "The judges look at the lit model first."],
        ["W", "I'll arrange the handouts on the table."],
        ["M", "I'll run and get the extension cord."],
      ],
      choices: [
        "포스터를 붙이기",
        "유인물을 놓기",
        "연장선을 가져오기",
        "심사위원을 맞이하기",
        "모형을 옮기기",
      ],
      answer: 3,
      clue: "I'll run and get the extension cord.",
      explanation:
        "남자는 과학실에 있는 연장선을 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 기영아, 과학 전시회가 15분 뒤에 열어.",
        "M: 포스터는 붙였고 모형도 꺼내 놨어.",
        "W: 연장선은 누가 가져왔어?",
        "M: 아직 과학실 서랍에 있어.",
        "W: 그게 없으면 등이 벽 콘센트까지 안 닿아.",
        "M: 심사위원들은 불 켜진 모형부터 봐.",
        "W: 나는 탁자에 유인물을 놓을게.",
        "M: 내가 뛰어가서 연장선을 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 고를 졸업 선물을 고르시오.",
      lines: [
        ["M", "Chaerin, what are you buying for your teacher?"],
        ["W", "Five gifts are on the shop page."],
        ["M", "How much did the class collect?"],
        ["W", "We can spend up to forty thousand won."],
        ["M", "One of them is far above that."],
        ["W", "It should also arrive within three days."],
        ["M", "Two of these take a week to ship."],
        ["W", "And we want the gift wrapping included."],
        ["M", "Then only one gift fits everything."],
        ["W", "I'll order it tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "We can spend up to forty thousand won.",
      explanation:
        "4만 원 이하, 3일 안 도착, 포장 포함인 선물은 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Price: 50,000 won / Delivery: 2 days / Wrapping: Yes" },
          { no: 2, label: "②", value: "Price: 35,000 won / Delivery: 7 days / Wrapping: Yes" },
          { no: 3, label: "③", value: "Price: 30,000 won / Delivery: 7 days / Wrapping: No" },
          { no: 4, label: "④", value: "Price: 38,000 won / Delivery: 2 days / Wrapping: No" },
          { no: 5, label: "⑤", value: "Price: 39,000 won / Delivery: 3 days / Wrapping: Yes" },
        ],
      },
      translation: [
        "M: 채린아, 선생님 선물로 뭘 살 거야?",
        "W: 가게 쪽에 다섯 가지가 있어.",
        "M: 반에서 얼마나 모았어?",
        "W: 4만 원까지 쓸 수 있어.",
        "M: 하나는 그보다 훨씬 비싸네.",
        "W: 그리고 사흘 안에 와야 해.",
        "M: 이 중 두 개는 배송에 일주일 걸려.",
        "W: 그리고 선물 포장이 들어 있어야 해.",
        "M: 그럼 다 맞는 건 하나뿐이야.",
        "W: 오늘 밤에 주문할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 학급 문집을 낼 날짜를 고르시오.",
      lines: [
        ["W", "Junseo, when should we hand in the class book?"],
        ["M", "The printer offered three dates this month."],
        ["W", "Which dates did they give us?"],
        ["M", "The tenth, the seventeenth and the twenty-fourth."],
        ["W", "Five people haven't sent their writing yet."],
        ["M", "So the tenth is impossible for us."],
        ["W", "And the twenty-fourth is after graduation."],
        ["M", "Then the seventeenth is the only day left."],
        ["W", "I'll remind everyone before the seventeenth."],
        ["M", "I'll put the pages together that weekend."],
      ],
      choices: ["the 10th", "the 17th", "the 24th", "the 7th", "the 20th"],
      answer: 2,
      clue: "Then the seventeenth is the only day left.",
      explanation:
        "10일은 원고가 덜 모였고 24일은 졸업 뒤여서 17일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 준서야, 학급 문집 언제 넘길까?",
        "M: 인쇄소에서 이번 달에 사흘을 주셨어.",
        "W: 어떤 날짜를 주셨어?",
        "M: 10일, 17일, 24일.",
        "W: 다섯 명이 아직 글을 안 보냈어.",
        "M: 그럼 10일은 안 되겠네.",
        "W: 24일은 졸업식 뒤고.",
        "M: 그럼 남는 날은 17일뿐이야.",
        "W: 17일 전에 다들한테 다시 말할게.",
        "M: 그 주말에 내가 쪽을 맞춰 놓을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerin, how did your weekend go?"],
        ["W", "I taught my grandmother to send messages."],
        ["M", "Did she just get a new phone?"],
        ["W", "My uncle gave her his old one."],
        ["M", "What did you teach her first?"],
        ["W", "How to find my name and type one line."],
        ["M", "Did she pick it up quickly?"],
        ["W", "We practiced the same steps eight times."],
        ["M", "Has she sent you anything since then?"],
        ["W", "Four messages already this morning."],
      ],
      choices: [
        "휴대폰을 샀다",
        "삼촌 댁에 갔다",
        "할머니께 문자 보내는 법을 가르쳐 드렸다",
        "친구를 만났다",
        "집에서 쉬었다",
      ],
      answer: 3,
      clue: "I taught my grandmother to send messages.",
      explanation:
        "여자는 지난 주말에 할머니께 문자 보내는 법을 가르쳐 드렸다. 따라서 답은 ③이다.",
      translation: [
        "M: 예린아, 주말 어땠어?",
        "W: 할머니께 문자 보내는 법을 가르쳐 드렸어.",
        "M: 휴대폰을 새로 장만하셨어?",
        "W: 삼촌이 쓰시던 걸 드렸어.",
        "M: 뭐부터 가르쳐 드렸어?",
        "W: 내 이름 찾아서 한 줄 쓰는 법.",
        "M: 금방 익히셨어?",
        "W: 같은 걸 여덟 번 연습했어.",
        "M: 그 뒤로 문자 오셨어?",
        "W: 오늘 아침에만 벌써 네 통.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school library speaking. " +
            "All borrowed books must come back before graduation. " +
            "Third grade students return theirs by next Wednesday. " +
            "Check your desk drawer and your bag at home. " +
            "Students with unreturned books cannot receive their album. " +
            "The return box sits beside the library door. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "책 반납을 당부하려고",
        "독서 행사를 안내하려고",
        "도서관 공사를 알리려고",
        "봉사자를 모으려고",
        "새 책을 소개하려고",
      ],
      answer: 1,
      clue: "All borrowed books must come back before graduation.",
      explanation:
        "졸업 전에 빌린 책을 반납하라고 당부하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 학교 도서관입니다. 빌려 간 책은 졸업 전에 모두 돌아와야 합니다. 3학년은 다음 주 수요일까지 반납해 주세요. 집에서 책상 서랍과 가방을 확인해 보세요. 반납하지 않은 책이 있으면 앨범을 받을 수 없습니다. 반납함은 도서관 문 옆에 있습니다. 협조해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. What can I get for you today?"],
        ["M", "Four cups of hot chocolate and two cookies."],
        ["W", "Each cup is three dollars."],
        ["M", "And the cookies?"],
        ["W", "Two dollars for each cookie."],
        ["M", "Is there a charge for the tray?"],
        ["W", "No, the tray costs nothing."],
        ["M", "Do you have a student discount?"],
        ["W", "Not on drinks, I'm afraid."],
        ["M", "All right. Here is my card."],
      ],
      choices: ["$14", "$15", "$16", "$17", "$18"],
      answer: 3,
      clue: "Each cup is three dollars.",
      explanation:
        "핫초코 네 잔 12달러와 쿠키 두 개 4달러를 더하면 16달러이다. 따라서 답은 ③이다.",
      translation: [
        "W: 안녕하세요. 오늘은 뭘 드릴까요?",
        "M: 따뜻한 코코아 네 잔이랑 쿠키 두 개 주세요.",
        "W: 한 잔에 3달러입니다.",
        "M: 쿠키는요?",
        "W: 하나에 2달러입니다.",
        "M: 쟁반은 돈을 받나요?",
        "W: 아니요, 쟁반은 돈을 받지 않습니다.",
        "M: 학생 할인은 있나요?",
        "W: 음료는 안 됩니다.",
        "M: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Sangjun, you always hand in your work on time."],
        ["M", "I finish everything two days before it's due."],
        ["W", "Two whole days? That seems early."],
        ["M", "Something always goes wrong on the last day."],
        ["W", "My printer broke the night before last time."],
        ["M", "That's exactly what the two days are for."],
        ["W", "I always start the evening before."],
        ["M", "Then one small problem ruins everything."],
        ["W", "When should I start the next report?"],
      ],
      choices: [
        "The night before it's due.",
        "Never start it at all.",
        "After the deadline passes.",
        "The day you get it.",
        "Only on weekends.",
      ],
      answer: 4,
      clue: "When should I start the next report?",
      explanation:
        "언제 시작해야 하는지 물었으므로, 받은 날에 시작하라는 ④가 가장 자연스럽다.",
      translation: [
        "W: 상준아, 너는 늘 제때 과제를 내더라.",
        "M: 마감 이틀 전에 다 끝내.",
        "W: 꼬박 이틀이나? 너무 이른 것 같은데.",
        "M: 마지막 날에는 꼭 뭔가 잘못돼.",
        "W: 지난번에는 전날 밤에 인쇄기가 고장 났어.",
        "M: 그 이틀이 바로 그 때문이야.",
        "W: 나는 늘 전날 저녁에 시작해.",
        "M: 그러면 작은 문제 하나에 다 망가지지.",
        "W: 다음 보고서는 언제 시작하면 좋을까?",
        "M: 받은 날에 시작해.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Suyeon, I heard you grow herbs on your balcony."],
        ["W", "Basil, mint and rosemary in six pots."],
        ["M", "When did you start doing that?"],
        ["W", "Two springs ago, with one small basil plant."],
        ["M", "Do they survive the winter out there?"],
        ["W", "I bring them inside when it gets cold."],
        ["M", "Do you actually cook with them?"],
        ["W", "My mother uses the basil almost every week."],
        ["M", "Is it hard to keep them alive?"],
        ["W", "Only the rosemary gives me trouble."],
        ["M", "Could you show me how to start one?"],
      ],
      choices: [
        "Sure, come over this weekend.",
        "I don't grow anything.",
        "The pots are all empty.",
        "You can't grow herbs.",
        "I threw them all out.",
      ],
      answer: 1,
      clue: "Could you show me how to start one?",
      explanation:
        "어떻게 시작하는지 보여 달라고 했으므로, 이번 주말에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 수연아, 베란다에서 허브를 키운다며.",
        "W: 화분 여섯 개에 바질, 민트, 로즈메리.",
        "M: 언제부터 했어?",
        "W: 두 해 전 봄에 작은 바질 하나로 시작했어.",
        "M: 겨울에도 거기서 살아?",
        "W: 추워지면 안으로 들여놔.",
        "M: 요리에도 정말 써?",
        "W: 어머니가 바질을 거의 매주 쓰셔.",
        "M: 살리기가 어려워?",
        "W: 로즈메리만 나를 애먹여.",
        "M: 나한테도 어떻게 시작하는지 보여 줄래?",
        "W: 그럼, 이번 주말에 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Minjun, how is the farewell video going?"],
        ["W", "You said it plays at the class party next week."],
        ["M", "The pictures are in, but nobody can hear the words."],
        ["W", "Did you record the voices in the classroom?"],
        ["M", "During lunch, with everyone talking around us."],
        ["W", "That's why the background is so loud."],
        ["M", "I thought the phone would pick up only my voice."],
        ["W", "A phone hears everything in the room."],
        ["M", "The music room is empty after school."],
        ["W", "Why don't you record it again in there?"],
      ],
      choices: [
        "I'll do that tomorrow.",
        "There is no music room.",
        "I'll record it at lunch again.",
        "Nobody will watch it.",
        "I deleted the video.",
      ],
      answer: 1,
      clue: "Why don't you record it again in there?",
      explanation:
        "음악실에서 다시 녹음하라는 제안이므로, 내일 하겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 민준아, 송별 영상은 잘돼 가?",
        "W: 다음 주 학급 잔치에서 튼다고 했잖아.",
        "M: 사진은 다 넣었는데 말소리가 안 들려.",
        "W: 목소리를 교실에서 녹음했어?",
        "M: 점심시간에, 주변에서 다들 떠드는데.",
        "W: 그래서 배경 소리가 큰 거야.",
        "M: 휴대폰이 내 목소리만 담을 줄 알았어.",
        "W: 휴대폰은 방 안 소리를 다 담아.",
        "M: 음악실은 방과 후에 비어 있어.",
        "W: 거기서 다시 녹음하는 건 어때?",
        "M: 내일 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jieun이 Hoyeon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jieun : ________________",
      lines: [
        [
          "W",
          "Jieun and Hoyeon are cleaning the classroom on the last day. " +
            "Hoyeon is about to throw a box of old notebooks into the trash. " +
            "Jieun notices the class photo album sitting on top of the pile. " +
            "That album took the whole class three months to make. " +
            "She wants him to take the album out before he throws the rest. " +
            "In this situation, what would Jieun most likely say to Hoyeon?",
        ],
      ],
      choices: [
        "Throw the whole box away.",
        "Our album is in that box.",
        "Let's make a new album.",
        "The classroom is clean now.",
        "We need more notebooks.",
      ],
      answer: 2,
      clue: "She wants him to take the album out before he throws the rest.",
      explanation:
        "버리려는 상자 위에 학급 사진첩이 있으므로, 그것이 상자에 있다고 알리는 ②가 가장 적절하다.",
      translation: [
        "W: 지은이와 호연이는 마지막 날 교실을 청소하고 있습니다. 호연이는 낡은 공책이 든 상자를 쓰레기통에 버리려고 합니다. 지은이는 그 더미 위에 학급 사진첩이 놓인 것을 봅니다. 그 사진첩은 반 전체가 석 달에 걸쳐 만든 것입니다. 그녀는 그가 나머지를 버리기 전에 사진첩을 빼기를 바랍니다. 이런 상황에서 지은이가 호연이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
