/** 중3 듣기 18회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 18회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 의자를 고르시오.",
      lines: [
        ["W", "Good afternoon. Are you looking for a desk chair?"],
        ["M", "Yes, one for my room at home."],
        ["W", "We have chairs on wheels and chairs with four fixed legs."],
        ["M", "Four legs, please. The floor is wooden and wheels leave marks."],
        ["W", "All right. Do you want arms on it?"],
        ["M", "Yes, I lean on them when I read."],
        ["W", "Then two are left. One has a cushioned seat and one has a plain wooden seat."],
        ["M", "The cushioned one, please. I sit there for hours at a time."],
        ["W", "Good choice. The cover on this one comes off and washes."],
        ["M", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "The cushioned one, please. I sit there for hours at a time.",
      explanation:
        "남자는 바퀴가 없고 다리가 네 개인 의자를, 팔걸이가 있는 것으로, 방석이 깔린 것을 고른다. 따라서 답은 ②이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five desk chairs shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing or letters anywhere. " +
          "Chair 1: FOUR straight fixed LEGS with no wheels, ARMRESTS on both sides, a flat plain WOODEN seat with no padding. " +
          "Chair 2: FOUR straight fixed LEGS with no wheels, ARMRESTS on both sides, a thick soft CUSHION seat. " +
          "Chair 3: FOUR straight fixed LEGS with no wheels, NO armrests at all, a thick soft CUSHION seat. " +
          "Chair 4: a single centre post standing on a star base with five WHEELS, ARMRESTS on both sides, a thick soft CUSHION seat. " +
          "Chair 5: a single centre post standing on a star base with five WHEELS, NO armrests at all, a flat plain WOODEN seat.",
      },
      translation: [
        "W: 안녕하세요. 책상 의자 찾으세요?",
        "M: 네, 집 제 방에 둘 거예요.",
        "W: 바퀴가 달린 것과 다리가 네 개인 것이 있습니다.",
        "M: 다리 네 개로요. 바닥이 나무라서 바퀴 자국이 남아요.",
        "W: 알겠습니다. 팔걸이가 있는 걸로 하시겠어요?",
        "M: 네, 책 읽을 때 기대거든요.",
        "W: 그럼 두 개 남았네요. 하나는 방석이 깔렸고 하나는 나무 그대로입니다.",
        "M: 방석 있는 걸로요. 거기 몇 시간씩 앉아 있어요.",
        "W: 좋은 선택이세요. 이건 덮개를 벗겨서 빨 수 있습니다.",
        "M: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 영어 말하기 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, are you entering the English speech contest?"],
        ["W", "I'd like to, but I don't know how it works."],
        ["M", "It's on the first Wednesday of next month, in the auditorium."],
        ["W", "How long does each speech have to be?"],
        ["M", "Between three and four minutes. They stop you at four."],
        ["W", "Can we choose our own topic?"],
        ["M", "No, they give you three and you pick one."],
        ["W", "Who are the judges?"],
        ["M", "Two English teachers and a guest from the city library."],
        ["W", "Then I'll sign up before Friday."],
      ],
      choices: ["열리는 날", "발표 시간", "주제 선정 방식", "심사 위원", "시상 내용"],
      answer: 5,
      clue: "Two English teachers and a guest from the city library.",
      explanation:
        "날짜(다음 달 첫째 수요일), 발표 시간(3~4분), 주제 선정 방식(주어진 세 개 중 하나), 심사 위원(영어 교사 둘과 시립 도서관에서 온 손님)은 언급되지만 시상 내용은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 서연아, 영어 말하기 대회 나갈 거야?",
        "W: 나가고 싶은데 어떻게 하는 건지 몰라.",
        "M: 다음 달 첫째 수요일에 강당에서 해.",
        "W: 한 사람이 몇 분 동안 말해?",
        "M: 3분에서 4분. 4분이 되면 멈추게 해.",
        "W: 주제는 우리가 정해?",
        "M: 아니, 세 개를 주고 그중 하나를 고르는 거야.",
        "W: 심사는 누가 해?",
        "M: 영어 선생님 두 분이랑 시립 도서관에서 오시는 분.",
        "W: 그럼 금요일 전에 신청할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Taeyang. It's Hayoon from the volunteer group."],
        ["M", "Hi. Is something wrong?"],
        ["W", "No, but Saturday's visit has moved."],
        ["M", "Moved where?"],
        ["W", "Same place, but we meet at the back gate instead of the front."],
        ["M", "Why the back gate?"],
        ["W", "The front road is closed for a market until noon."],
        ["M", "Got it. Back gate at nine, then. Thanks for calling."],
      ],
      choices: [
        "만나는 장소가 바뀐 것을 알리려고",
        "봉사활동이 취소되었다고 알리려고",
        "새로운 봉사자를 모으려고",
        "준비물을 부탁하려고",
        "시간을 미루자고 하려고",
      ],
      answer: 1,
      clue: "Same place, but we meet at the back gate instead of the front.",
      explanation:
        "여자는 앞길이 막혀 모이는 곳이 정문에서 후문으로 바뀌었다고 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 태양아. 봉사 모임 하윤이야.",
        "M: 안녕. 무슨 일 있어?",
        "W: 아니, 토요일 방문 장소가 바뀌었어.",
        "M: 어디로 바뀌었는데?",
        "W: 장소는 같은데, 정문 말고 후문에서 모여.",
        "M: 왜 후문이야?",
        "W: 앞길이 정오까지 장터 때문에 막혀.",
        "M: 알겠어. 그럼 9시에 후문. 알려 줘서 고마워.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Chaewon, what time should we meet at the concert hall?"],
        ["W", "The performance begins at seven."],
        ["M", "And the doors close five minutes before that."],
        ["W", "How about six forty-five?"],
        ["M", "There's always a queue at the cloakroom. Let's go earlier."],
        ["W", "How long does it take you to get there?"],
        ["M", "About half an hour by subway."],
        ["W", "Then let's meet at six thirty."],
        ["M", "Six thirty is fine. I'll wait under the big poster."],
      ],
      choices: ["6:00 p.m.", "6:15 p.m.", "6:30 p.m.", "6:45 p.m.", "7:00 p.m."],
      answer: 3,
      clue: "Then let's meet at six thirty.",
      explanation:
        "공연이 7시에 시작하고 보관소에 줄이 서서 두 사람은 6시 30분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 채원아, 공연장에서 몇 시에 만날까?",
        "W: 공연이 7시에 시작해.",
        "M: 그리고 5분 전에 문을 닫잖아.",
        "W: 6시 45분은 어때?",
        "M: 보관소에는 늘 줄이 서. 더 일찍 가자.",
        "W: 거기까지 얼마나 걸려?",
        "M: 지하철로 30분쯤.",
        "W: 그럼 6시 30분에 만나자.",
        "M: 6시 30분 좋아. 큰 포스터 아래에서 기다릴게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Jiwoo, you've checked your phone six times since the bell."],
        ["W", "My grandmother went into hospital this morning."],
        ["M", "Is it serious?"],
        ["W", "They said it's a small operation, but she's eighty-one."],
        ["M", "Has anyone called you?"],
        ["W", "My mother said she'd call when it was over. That was two hours ago."],
        ["M", "Two hours isn't long for an operation."],
        ["W", "I know that. I still can't listen to a word the teacher says."],
      ],
      choices: ["worried", "excited", "bored", "proud", "delighted"],
      answer: 1,
      clue: "I know that. I still can't listen to a word the teacher says.",
      explanation:
        "할머니 수술 소식을 기다리며 수업도 귀에 들어오지 않는다고 했으므로 여자는 걱정하고 있다. 따라서 답은 ①이다.",
      translation: [
        "M: 지우야, 종 친 뒤로 휴대전화를 여섯 번이나 봤어.",
        "W: 할머니가 오늘 아침에 입원하셨어.",
        "M: 많이 편찮으셔?",
        "W: 작은 수술이라고는 하는데, 여든한 살이시잖아.",
        "M: 누가 연락 줬어?",
        "W: 엄마가 끝나면 전화한다고 하셨어. 두 시간 전에.",
        "M: 수술에 두 시간은 긴 것도 아니야.",
        "W: 그건 알아. 그래도 선생님 말씀이 하나도 안 들려.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "How long does it take to walk there?"],
        ["W", "About fifteen minutes."],
        ["M", "Is this seat free?"],
        ["W", "Yes, nobody is sitting there."],
        ["M", "How much are these apples?"],
        ["W", "Four dollars a bag."],
        ["M", "Would you like to sit down?"],
        ["W", "Thank you. My bags are heavy."],
        ["M", "What time does the bank close?"],
        ["W", "At four o'clock."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Would you like to sit down?",
      explanation:
        "그림은 장바구니를 든 할머니 앞에서 한 학생이 일어서며 자리를 권하는 장면이므로 ④가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "Inside a city bus, clean black line art on a plain white background, no writing or letters anywhere. An ELDERLY WOMAN is standing in the aisle holding two heavy shopping bags, one in each hand. A young MALE STUDENT with a backpack has risen from his seat beside her and is gesturing with an open hand toward the now empty seat, offering it to her. Both people are drawn clearly. Bus windows and a handrail are in the background.",
      },
      translation: [
        "① M: 거기까지 걸어서 얼마나 걸려요? / W: 15분쯤이요.",
        "② M: 이 자리 비었나요? / W: 네, 아무도 안 앉았어요.",
        "③ M: 이 사과 얼마예요? / W: 한 봉지에 4달러예요.",
        "④ M: 여기 앉으시겠어요? / W: 고마워요. 짐이 무거웠는데.",
        "⑤ M: 은행 몇 시에 닫아요? / W: 4시에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junwoo, you're going to the computer room after school, right?"],
        ["M", "Yes, I have to finish the club website."],
        ["W", "Could you do one thing for me while you're there?"],
        ["M", "Sure. What is it?"],
        ["W", "The class photo file is on the desktop of the third computer."],
        ["M", "Do you want me to print it?"],
        ["W", "No, please upload it to the class folder. I can't get in tomorrow."],
        ["M", "What's the file called?"],
        ["W", "'Sports day final'. It's the only one with a date on it."],
        ["M", "Got it. I'll upload it before I leave."],
      ],
      choices: ["사진을 인쇄해 주기", "컴퓨터를 고쳐 주기", "사진을 찍어 주기", "누리집을 만들어 주기", "파일을 학급 폴더에 올려 주기"],
      answer: 5,
      clue: "No, please upload it to the class folder. I can't get in tomorrow.",
      explanation:
        "여자는 컴퓨터에 있는 사진 파일을 학급 폴더에 올려 달라고 부탁한다. 인쇄가 아니라 올리는 것이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준우야, 방과 후에 컴퓨터실 가지?",
        "M: 응, 동아리 누리집을 마무리해야 해.",
        "W: 거기 있는 동안 하나만 부탁할게.",
        "M: 그래. 뭔데?",
        "W: 학급 사진 파일이 세 번째 컴퓨터 바탕화면에 있어.",
        "M: 인쇄해 줄까?",
        "W: 아니, 학급 폴더에 올려 줘. 내일 내가 못 들어가거든.",
        "M: 파일 이름이 뭐야?",
        "W: '체육대회 최종'. 날짜 붙은 건 그거 하나야.",
        "M: 알겠어. 가기 전에 올릴게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Winter Coding Camp에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hello, students. Here is news about Winter Coding Camp."],
        ["W", "It runs for three days, from the twenty-sixth to the twenty-eighth of December."],
        ["W", "All sessions take place in the second-floor computer room."],
        ["W", "You will build one small game and take the code home."],
        ["W", "Bring nothing but a notebook; the computers are all set up."],
        ["W", "Sign up on the sheet outside the office by the twentieth."],
      ],
      choices: ["열리는 날", "장소", "하는 일", "참가 인원", "준비물"],
      answer: 4,
      clue: "Bring nothing but a notebook; the computers are all set up.",
      explanation:
        "날짜(12월 26~28일), 장소(2층 컴퓨터실), 하는 일(작은 게임 만들기), 준비물(공책)은 언급되지만 참가 인원은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. Winter Coding Camp 소식입니다.",
        "W: 12월 26일부터 28일까지 사흘 동안 합니다.",
        "W: 모든 수업은 2층 컴퓨터실에서 합니다.",
        "W: 작은 게임을 하나 만들고 그 코드를 집으로 가져갑니다.",
        "W: 공책 말고는 아무것도 가져올 필요 없습니다. 컴퓨터는 다 준비돼 있습니다.",
        "W: 20일까지 행정실 앞 명단에 이름을 적으세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["M", "You pass one of these every time you walk into the school building."],
        ["M", "It is a tall frame full of small open squares."],
        ["M", "Each square has a number, and each student has one."],
        ["M", "You leave your outdoor shoes in it and put on your indoor ones."],
        ["M", "In June it is the place in the school that smells the worst."],
      ],
      choices: ["사물함", "우산꽂이", "신발장", "소화기함", "게시판"],
      answer: 3,
      clue: "You leave your outdoor shoes in it and put on your indoor ones.",
      explanation:
        "번호가 붙은 작은 칸이 있고 바깥 신발을 넣고 실내화로 갈아 신는다고 했으므로 신발장이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 학교 건물에 들어올 때마다 지나칩니다.",
        "M: 작은 빈칸이 가득한 키 큰 틀입니다.",
        "M: 칸마다 번호가 있고, 학생마다 하나씩 있습니다.",
        "M: 여기에 바깥 신발을 두고 실내화로 갈아 신습니다.",
        "M: 6월이면 학교에서 냄새가 가장 심한 곳입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["W", "How was the school trip?"],
        ["M", "Tiring, but worth it."],
        ["W", "What did you say to her?"],
        ["M", "I'll take the blue one."],
        ["W", "Could you move your bag?"],
        ["M", "Of course, sorry."],
        ["W", "When is the deadline?"],
        ["M", "Friday at five."],
        ["W", "Do you want to come with us?"],
        ["M", "Yes, I'd like that."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "What did you say to her?",
      explanation:
        "그 애에게 뭐라고 했느냐는 물음에 파란 것으로 하겠다는 대답은 어울리지 않는다. 따라서 답은 ②이다.",
      translation: [
        "① W: 수학여행 어땠어? / M: 힘들었지만 갈 만했어.",
        "② W: 걔한테 뭐라고 했어? / M: 파란 걸로 할게요.",
        "③ W: 가방 좀 치워 줄래? / M: 그럼, 미안.",
        "④ W: 마감이 언제야? / M: 금요일 5시.",
        "⑤ W: 우리랑 같이 갈래? / M: 응, 좋아.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minhyuk, the school debate starts in fifteen minutes."],
        ["M", "Is the room ready? What should I do?"],
        ["W", "I've arranged the tables and written the motion on the board."],
        ["M", "Should I hand out the ballot papers?"],
        ["W", "Chaerin is doing that at the door."],
        ["M", "Then what's left?"],
        ["W", "The bell we use for time is still in the staff room."],
        ["M", "I'll go and get it right now."],
        ["W", "Thanks. I'll set out the water for the speakers."],
      ],
      choices: ["종 가져오기", "책상 옮기기", "칠판에 주제 쓰기", "투표지 나눠 주기", "물 준비하기"],
      answer: 1,
      clue: "I'll go and get it right now.",
      explanation:
        "책상과 칠판, 투표지는 이미 해결되었으므로 남자는 교무실에 있는 종을 가지러 간다. 따라서 답은 ①이다.",
      translation: [
        "W: 민혁아, 학교 토론이 15분 뒤에 시작해.",
        "M: 교실은 준비됐어? 내가 뭘 할까?",
        "W: 책상은 배치했고 칠판에 주제도 썼어.",
        "M: 투표지를 나눠 줄까?",
        "W: 채린이가 문 앞에서 나눠 주고 있어.",
        "M: 그럼 뭐가 남았어?",
        "W: 시간 잴 때 쓰는 종이 아직 교무실에 있어.",
        "M: 내가 지금 가서 가져올게.",
        "W: 고마워. 나는 발언자들 물을 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 진로 체험을 고르시오.",
      lines: [
        ["M", "Dahye, these are the five career visits still open."],
        ["W", "Let's look. I can't go on the twelfth because of the school photo."],
        ["M", "Then one is out. What else?"],
        ["W", "It has to be in our city. I can't travel two hours each way."],
        ["M", "One is in another city, so that's gone too."],
        ["W", "Three left. How long do they run?"],
        ["M", "You said four hours at the most."],
        ["W", "Then one more drops out. Two are left."],
        ["M", "Do they both let you try the work yourself?"],
        ["W", "Only one does. The other is just a tour and a talk."],
        ["M", "Then that settles it. Sign up this afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Then that settles it. Sign up this afternoon.",
      explanation:
        "12일인 ①, 다른 도시인 ②, 6시간인 ③을 뺀다. 남은 ④와 ⑤ 중 직접 해 보는 것은 ④이므로 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "12일 / 우리 시 / 4시간 / 직접 해 봄" },
          { no: 2, label: "②", value: "14일 / 다른 시 / 4시간 / 직접 해 봄" },
          { no: 3, label: "③", value: "14일 / 우리 시 / 6시간 / 직접 해 봄" },
          { no: 4, label: "④", value: "15일 / 우리 시 / 3시간 / 직접 해 봄" },
          { no: 5, label: "⑤", value: "16일 / 우리 시 / 3시간 / 견학과 강의만" },
        ],
      },
      translation: [
        "M: 다혜야, 아직 열려 있는 진로 체험이 이 다섯 개야.",
        "W: 보자. 학교 사진 찍는 날이라 12일은 안 돼.",
        "M: 그럼 하나 빠지네. 또 뭐가 있어?",
        "W: 우리 시 안이어야 해. 편도 두 시간은 무리야.",
        "M: 하나는 다른 시니까 그것도 빠져.",
        "W: 셋 남았다. 몇 시간짜리야?",
        "M: 많아야 네 시간이라고 했잖아.",
        "W: 그럼 하나 더 빠지고 둘 남았다.",
        "M: 둘 다 직접 해 볼 수 있어?",
        "W: 한 곳만. 다른 하나는 견학하고 강의만 들어.",
        "M: 그럼 정해졌네. 오늘 오후에 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 등산을 갈 날짜를 고르시오.",
      lines: [
        ["M", "Sohee, when should we go up the mountain?"],
        ["W", "The weather is clear on the twenty-third, twenty-fourth, and twenty-fifth."],
        ["M", "How long does it take to the top?"],
        ["W", "About three hours, and three hours back."],
        ["M", "A whole day, then. I have a family dinner on the twenty-third."],
        ["W", "Then the twenty-fourth or the twenty-fifth."],
        ["M", "Isn't the twenty-fifth the day the club room has to be cleared?"],
        ["W", "You're right, I forgot. That takes the whole afternoon."],
        ["M", "So only the twenty-fourth is left."],
        ["W", "Then let's go on the twenty-fourth. I'll pack the water."],
      ],
      choices: ["22일", "23일", "24일", "25일", "26일"],
      answer: 3,
      clue: "So only the twenty-fourth is left.",
      explanation:
        "23일은 가족 저녁 약속, 25일은 동아리방 정리여서 24일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 소희야, 산에 언제 갈까?",
        "W: 23일, 24일, 25일에 날씨가 맑대.",
        "M: 정상까지 얼마나 걸려?",
        "W: 세 시간쯤, 내려오는 데 세 시간.",
        "M: 그럼 하루가 다 가네. 나 23일에 가족 저녁 약속이 있어.",
        "W: 그럼 24일이나 25일이네.",
        "M: 25일은 동아리방 비우는 날 아니야?",
        "W: 맞다, 잊었네. 그거 오후 내내 걸려.",
        "M: 그럼 24일만 남네.",
        "W: 그럼 24일에 가자. 물은 내가 챙길게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Dohyun, did you watch the game on Saturday?"],
        ["M", "No, I was at the animal shelter all day."],
        ["W", "The shelter? What did you do there?"],
        ["M", "Mostly washing bowls and walking the dogs."],
        ["W", "How many dogs are there?"],
        ["M", "Nineteen. I walked four of them, one at a time."],
        ["W", "That must have taken hours."],
        ["M", "Five hours. My legs hurt, but I'm going again next month."],
      ],
      choices: ["경기 보기", "강아지 입양하기", "산책하기", "친구 만나기", "동물보호소에서 봉사하기"],
      answer: 5,
      clue: "No, I was at the animal shelter all day.",
      explanation:
        "남자는 지난 토요일에 동물보호소에서 하루 종일 봉사했다고 말한다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 도현아, 토요일에 경기 봤어?",
        "M: 아니, 하루 종일 동물보호소에 있었어.",
        "W: 보호소? 거기서 뭐 했는데?",
        "M: 주로 밥그릇 씻고 강아지 산책시켰어.",
        "W: 강아지가 몇 마리야?",
        "M: 열아홉 마리. 그중 네 마리를 한 마리씩 데리고 나갔어.",
        "W: 몇 시간은 걸렸겠다.",
        "M: 다섯 시간. 다리는 아픈데 다음 달에 또 가려고.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Good morning, students. This is the school office."],
        ["M", "The fire drill will take place tomorrow during the third period."],
        ["M", "When the bell rings three times, leave everything and go outside."],
        ["M", "Use the nearest staircase, and walk; do not run."],
        ["M", "Each class lines up on the playground by year."],
        ["M", "It should take about ten minutes in all."],
      ],
      choices: [
        "체육대회 순서를 알리려고",
        "계단 공사를 안내하려고",
        "소방 훈련 방법을 안내하려고",
        "운동장 사용을 금지하려고",
        "수업 시간이 바뀐 것을 알리려고",
      ],
      answer: 3,
      clue: "When the bell rings three times, leave everything and go outside.",
      explanation:
        "내일 3교시에 있을 소방 훈련의 방법과 모이는 곳을 알리는 방송이다. 따라서 방송의 목적은 ③이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 행정실입니다.",
        "M: 내일 3교시에 소방 훈련을 합니다.",
        "M: 종이 세 번 울리면 모든 것을 두고 밖으로 나가세요.",
        "M: 가장 가까운 계단을 이용하고, 뛰지 말고 걸으세요.",
        "M: 각 반은 운동장에 학년별로 줄을 섭니다.",
        "M: 전체 10분쯤 걸릴 것입니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the city theatre. How many tickets?"],
        ["M", "Three student tickets, please."],
        ["W", "Student tickets are nine dollars each."],
        ["M", "So twenty-seven dollars."],
        ["W", "That's right. Would you like a programme as well?"],
        ["M", "How much is it?"],
        ["W", "Four dollars each."],
        ["M", "Then one, please."],
        ["W", "All right. And groups of three or more get five dollars off."],
        ["M", "Great. Here's my card."],
      ],
      choices: ["$26", "$27", "$28", "$31", "$35"],
      answer: 1,
      clue: "All right. And groups of three or more get five dollars off.",
      explanation:
        "학생 표 9달러씩 세 장은 27달러, 안내지 4달러를 더하면 31달러이다. 3인 이상 할인 5달러를 빼면 26달러이므로 답은 ①이다.",
      translation: [
        "W: 시립 극장입니다. 표 몇 장 드릴까요?",
        "M: 학생 표 세 장 주세요.",
        "W: 학생 표는 한 장에 9달러입니다.",
        "M: 그럼 27달러네요.",
        "W: 맞습니다. 안내지도 하시겠어요?",
        "M: 얼마예요?",
        "W: 한 부에 4달러입니다.",
        "M: 그럼 한 부 주세요.",
        "W: 알겠습니다. 그리고 3인 이상은 5달러 할인됩니다.",
        "M: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Nayeon, you've been rewriting the same page of notes all week."],
        ["W", "I copy the whole lesson out again neatly every evening."],
        ["M", "Does it help you remember it?"],
        ["W", "Not really. I've started to wonder about that."],
        ["M", "What do you think about while you copy?"],
        ["W", "Nothing, honestly. I just follow the lines with my eyes."],
        ["M", "Then your hand is working and your head is resting."],
        ["W", "That's exactly what it feels like."],
        ["M", "Close the notes and write down what you remember instead."],
      ],
      choices: [
        "My handwriting is quite neat.",
        "Then I'll try that tonight.",
        "The lesson was about volcanoes.",
        "I use three different pens.",
        "You should copy yours too.",
      ],
      answer: 2,
      clue: "Close the notes and write down what you remember instead.",
      explanation:
        "필기를 덮고 기억나는 것을 적어 보라는 조언을 들었으므로, 오늘 밤에 그렇게 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나연아, 일주일 내내 같은 쪽 필기를 다시 쓰고 있네.",
        "W: 저녁마다 수업 내용을 깔끔하게 다시 옮겨 적어.",
        "M: 그러면 기억이 잘 나?",
        "W: 딱히. 요즘 그게 좀 의심스러워.",
        "M: 옮겨 적는 동안 무슨 생각을 해?",
        "W: 솔직히 아무 생각도 안 해. 눈으로 줄만 따라가.",
        "M: 그럼 손은 일하고 머리는 쉬는 거네.",
        "W: 딱 그런 느낌이야.",
        "M: 필기를 덮고 기억나는 걸 적어 봐.",
        "W: 그럼 오늘 밤에 그렇게 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Seungho, you've been late for morning practice four times."],
        ["M", "I set three alarms and I still sleep through them."],
        ["W", "Where is the phone when the alarms go off?"],
        ["M", "Under my pillow, so it doesn't wake my brother."],
        ["W", "So you turn it off without waking up."],
        ["M", "I don't even remember doing it."],
        ["W", "One alarm, across the room, is better than three by your head."],
        ["M", "My brother will hear it, though."],
        ["W", "He'll hear it once instead of three times."],
      ],
      choices: [
        "Practice starts at six thirty.",
        "My brother sleeps very deeply.",
        "I go to bed around midnight.",
        "Then I'll move the phone tonight.",
        "You should set an alarm too.",
      ],
      answer: 4,
      clue: "He'll hear it once instead of three times.",
      explanation:
        "머리맡이 아니라 방 반대편에 알람 하나를 두라는 조언을 들었으므로, 오늘 밤에 휴대전화를 옮기겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 승호야, 아침 연습에 네 번이나 늦었어.",
        "M: 알람을 세 개 맞춰 놓는데도 그냥 자.",
        "W: 알람이 울릴 때 휴대전화가 어디 있는데?",
        "M: 베개 밑에. 동생을 깨우지 않으려고.",
        "W: 그럼 깨지도 않은 채로 꺼 버리는 거네.",
        "M: 껐다는 기억도 안 나.",
        "W: 머리맡에 세 개보다 방 반대편에 하나가 나아.",
        "M: 그러면 동생이 듣잖아.",
        "W: 세 번 대신 한 번 듣는 거지.",
        "M: 그럼 오늘 밤에 휴대전화를 옮길게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Yerin, how is the class newsletter going?"],
        ["W", "Slowly. I've been waiting for articles for two weeks."],
        ["M", "How did you ask for them?"],
        ["W", "I wrote 'please send me an article' in the class chat."],
        ["M", "An article about what?"],
        ["W", "Anything. I didn't want to limit people."],
        ["M", "'Anything' is the hardest thing to write about."],
        ["W", "I thought I was being generous."],
        ["M", "Give three people a title and a date each."],
      ],
      choices: [
        "The newsletter is two pages long.",
        "Then I'll message three people tonight.",
        "Our class has twenty-six students.",
        "I wrote the first article myself.",
        "I'd rather print it without articles.",
      ],
      answer: 2,
      clue: "Give three people a title and a date each.",
      explanation:
        "세 사람에게 제목과 날짜를 정해 주라는 조언을 들었으므로, 오늘 밤에 세 명에게 연락하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 예린아, 학급 소식지는 잘돼 가?",
        "W: 천천히. 2주째 글을 기다리고 있어.",
        "M: 어떻게 부탁했는데?",
        "W: 학급 대화방에 '글 하나 보내 줘'라고 썼어.",
        "M: 무엇에 대한 글?",
        "W: 아무거나. 사람들을 묶어 두기 싫어서.",
        "M: '아무거나'가 제일 쓰기 어려운 주제야.",
        "W: 나는 배려한다고 생각했는데.",
        "M: 세 사람한테 제목이랑 날짜를 하나씩 정해 줘.",
        "W: 그럼 오늘 밤에 세 명한테 연락할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Hayoon이 Junseo에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Hayoon : ________________",
      lines: [
        ["W", "Hayoon and Junseo are running the school radio at lunchtime."],
        ["W", "Junseo chooses the songs and he chooses them very well."],
        ["W", "Everyone says the music has been better since he took over."],
        ["W", "However, he plays each song all the way to the end."],
        ["W", "Lunch is only thirty minutes, so only five songs fit in."],
        ["W", "Many students send in requests that are never played."],
        ["W", "Hayoon does not want to say that his choices are wrong."],
        ["W", "She wants to suggest fading each song out after two minutes."],
        ["W", "In this situation, what would Hayoon most likely say to Junseo?"],
      ],
      choices: [
        "Let's stop taking requests from now on.",
        "You should choose faster songs.",
        "I'll pick the songs next week.",
        "The radio should be louder.",
        "Could we fade each song out after two minutes?",
      ],
      answer: 5,
      clue: "She wants to suggest fading each song out after two minutes.",
      explanation:
        "하윤이는 준서의 선곡을 깎아내리지 않으면서, 한 곡을 2분쯤에서 줄이자고 말하려 한다. 따라서 ⑤가 가장 적절하다.",
      translation: [
        "W: 하윤이와 준서는 점심시간에 학교 방송을 맡고 있습니다.",
        "W: 준서가 노래를 고르는데 아주 잘 고릅니다.",
        "W: 준서가 맡은 뒤로 음악이 좋아졌다고 다들 말합니다.",
        "W: 그런데 한 곡을 끝까지 다 틉니다.",
        "W: 점심시간은 30분뿐이라 다섯 곡밖에 들어가지 않습니다.",
        "W: 많은 학생이 신청한 곡이 한 번도 나오지 않습니다.",
        "W: 하윤이는 준서의 선곡이 잘못됐다고 말하고 싶지는 않습니다.",
        "W: 다만 한 곡을 2분쯤에서 줄이자고 제안하고 싶습니다.",
        "W: 이런 상황에서 하윤이가 준서에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
