/** 중3 듣기 50회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 50회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 만들 졸업 카드를 고르시오.",
      lines: [
        ["M", "Suyeon, what will the graduation card look like?"],
        ["W", "A tall card that opens from the side."],
        ["M", "Are you drawing the school building on it?"],
        ["W", "Not the building. A single tree instead."],
        ["M", "Where does the tree go on the cover?"],
        ["W", "Right in the middle, taking up most of it."],
        ["M", "Do you add a ribbon on the fold?"],
        ["W", "No ribbon. It won't fit in the envelope."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Not the building. A single tree instead. / No ribbon. It won't fit in the envelope.",
      explanation:
        "세로로 긴 카드 가운데에 나무 하나가 있고 리본은 없는 것이다. 따라서 답은 ③이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five greeting card covers side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a TALL card with a simple SCHOOL BUILDING drawn in the middle, no ribbon. " +
          "② a TALL card with a single TREE in the middle and a RIBBON tied at the folded edge. " +
          "③ a TALL card with a single large TREE in the middle, nothing else, no ribbon. " +
          "④ a WIDE card with a single TREE in the middle, no ribbon. " +
          "⑤ a TALL card with a TREE in the BOTTOM corner and a RIBBON at the fold.",
      },
      translation: [
        "M: 수연아, 졸업 카드는 어떻게 만들 거야?",
        "W: 옆으로 펼치는 세로로 긴 카드.",
        "M: 학교 건물을 그릴 거야?",
        "W: 건물은 안 그려. 대신 나무 한 그루.",
        "M: 표지 어디에 나무를 넣어?",
        "W: 한가운데에, 거의 다 차게.",
        "M: 접히는 쪽에 리본도 달아?",
        "W: 리본은 안 돼. 봉투에 안 들어가.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 진로 체험의 날에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junseo, what happens on career experience day?"],
        ["M", "We visit a workplace in small groups."],
        ["W", "When is it held this year?"],
        ["M", "On the third Thursday of next month."],
        ["W", "How many students go in one group?"],
        ["M", "Six, and each group has a different place."],
        ["W", "How do we get to the workplaces?"],
        ["M", "By school bus, leaving at nine in the morning."],
        ["W", "What do we have to do afterwards?"],
        ["M", "Write one page about what we saw."],
      ],
      choices: ["열리는 날", "한 모둠의 인원", "이동 방법", "다녀온 뒤 할 일", "방문할 직장의 종류"],
      answer: 5,
      clue: "On the third Thursday of next month.",
      explanation:
        "날짜, 인원, 이동, 사후 활동은 말했지만 직장의 종류는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준서야, 진로 체험의 날에 뭘 해?",
        "M: 작은 모둠으로 나눠서 직장을 방문해.",
        "W: 올해는 언제 해?",
        "M: 다음 달 셋째 주 목요일에.",
        "W: 한 모둠에 몇 명이야?",
        "M: 여섯 명. 모둠마다 가는 곳이 달라.",
        "W: 어떻게 가?",
        "M: 학교 버스로, 아침 아홉 시에 출발해.",
        "W: 다녀와서 뭘 해야 해?",
        "M: 본 것에 대해 한 쪽을 써.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, this is the print shop."],
        ["M", "Hello. My name is Dohyun Kim."],
        ["W", "How may I help you today?"],
        ["M", "Our class ordered fifty booklets last week."],
        ["W", "The class collection, right?"],
        ["M", "Yes, we sent the file on Monday."],
        ["W", "They are being printed right now."],
        ["M", "We found a mistake on the first page."],
        ["W", "Is it a big change?"],
        ["M", "I'm calling to ask you to stop the printing."],
      ],
      choices: [
        "인쇄를 멈춰 달라고 하려고",
        "새로 주문하려고",
        "값을 물어보려고",
        "배송을 부탁하려고",
        "감사를 전하려고",
      ],
      answer: 1,
      clue: "I'm calling to ask you to stop the printing.",
      explanation:
        "남자는 잘못을 발견해 인쇄를 멈춰 달라고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "W: 여보세요, 인쇄소입니다.",
        "M: 안녕하세요. 저는 김도현입니다.",
        "W: 무엇을 도와드릴까요?",
        "M: 저희 반이 지난주에 책자 쉰 부를 주문했어요.",
        "W: 학급 문집 말씀이시죠?",
        "M: 네, 월요일에 파일을 보냈어요.",
        "W: 지금 인쇄하고 있습니다.",
        "M: 첫 쪽에서 잘못된 곳을 찾았어요.",
        "W: 많이 고쳐야 하나요?",
        "M: 인쇄를 멈춰 주십사 전화했어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["W", "Taeyang, when should we go to the bookstore?"],
        ["M", "It stays open until eight in the evening."],
        ["W", "How long do we need to find the books?"],
        ["M", "Half an hour, maybe a bit more."],
        ["W", "My English class ends at six fifteen."],
        ["M", "Then six o'clock doesn't work for you."],
        ["W", "Let's meet at six thirty at the entrance."],
        ["M", "Six thirty. That leaves plenty of time."],
        ["W", "I'll bring the list of titles."],
      ],
      choices: ["6:00 p.m.", "6:15 p.m.", "6:30 p.m.", "7:00 p.m.", "8:00 p.m."],
      answer: 3,
      clue: "Let's meet at six thirty at the entrance.",
      explanation:
        "여자의 수업이 6시 15분에 끝나 6시 30분에 만나기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태양아, 서점에 언제 갈까?",
        "M: 저녁 여덟 시까지 열어.",
        "W: 책 찾는 데 얼마나 걸릴까?",
        "M: 30분, 조금 더 걸릴 수도.",
        "W: 내 영어 수업이 여섯 시 15분에 끝나.",
        "M: 그럼 여섯 시는 너한테 안 되겠네.",
        "W: 여섯 시 반에 입구에서 만나자.",
        "M: 여섯 시 반. 시간이 넉넉하겠다.",
        "W: 책 제목 목록은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjun, you've been smiling all through class."],
        ["M", "My short film was chosen for the youth festival."],
        ["W", "The one you shot at the river?"],
        ["M", "I filmed it every weekend for two months."],
        ["W", "How many films were entered?"],
        ["M", "Three hundred, and they picked twenty."],
        ["W", "So yours is one of the twenty."],
        ["M", "They're showing it on a real screen next month."],
      ],
      choices: ["bored", "worried", "thrilled", "angry", "sorry"],
      answer: 3,
      clue: "They're showing it on a real screen next month.",
      explanation:
        "두 달 걸린 단편이 뽑혀 몹시 신이 나 있다. 따라서 답은 ③이다.",
      translation: [
        "W: 민준아, 수업 내내 웃고 있네.",
        "M: 내 단편 영화가 청소년 축제에 뽑혔어.",
        "W: 강가에서 찍은 그거?",
        "M: 두 달 동안 주말마다 찍었어.",
        "W: 몇 편이나 냈는데?",
        "M: 300편인데 스무 편을 골랐어.",
        "W: 그중에 네 게 들어간 거네.",
        "M: 다음 달에 진짜 극장 화면으로 튼대.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you know when the next bus comes?"],
        ["M", "In about seven minutes."],
        ["ANN", "Number two."],
        ["W", "Could you help me with this bag?"],
        ["M", "I'll take the heavy one."],
        ["ANN", "Number three."],
        ["W", "Is this the right way to the hall?"],
        ["M", "Go straight and turn left."],
        ["ANN", "Number four."],
        ["W", "Are you waiting in line too?"],
        ["M", "Yes, the line starts back there."],
        ["ANN", "Number five."],
        ["W", "Would you like to go first?"],
        ["M", "Thank you, I'm in a hurry."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Could you help me with this bag?",
      explanation:
        "그림은 무거운 가방 하나를 대신 들어 주는 장면이다. 따라서 답은 ②이다.",
      figure: {
        kind: "scene",
        scene:
          "On a staircase inside a school building, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A girl stands holding two large bags and looks toward a boy with a strained expression. " +
          "The boy reaches down and takes the larger bag from her hand. " +
          "Stair railings and a landing window are drawn simply around them.",
      },
      translation: [
        "① W: 다음 버스 언제 오는지 아세요? / M: 7분쯤 뒤에요.",
        "② W: 이 가방 좀 도와줄래? / M: 무거운 걸 내가 들게.",
        "③ W: 강당 가는 길이 이쪽 맞나요? / M: 곧장 가서 왼쪽으로 도세요.",
        "④ W: 여기도 줄 서신 거예요? / M: 네, 줄은 저 뒤에서 시작해요.",
        "⑤ W: 먼저 하시겠어요? / M: 고맙습니다, 제가 급해서요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunwoo, you know the school piano well, don't you?"],
        ["M", "I practice on it every morning before class."],
        ["W", "Our class is singing at the farewell party."],
        ["M", "How many songs are you doing?"],
        ["W", "Two, and both need someone at the piano."],
        ["M", "Does anyone in your class play?"],
        ["W", "Only one person, and she is singing."],
        ["M", "So the piano seat is empty."],
        ["W", "Could you play the piano for our songs?"],
        ["M", "Send me the sheet music tonight."],
      ],
      choices: [
        "피아노를 쳐 주기",
        "노래를 불러 주기",
        "악보를 구해 주기",
        "연습실을 빌려주기",
        "무대를 꾸며 주기",
      ],
      answer: 1,
      clue: "Could you play the piano for our songs?",
      explanation:
        "여자는 반 노래에 피아노를 쳐 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 현우야, 너 학교 피아노 잘 알지?",
        "M: 수업 전에 매일 아침 거기서 연습해.",
        "W: 우리 반이 송별회에서 노래해.",
        "M: 몇 곡 해?",
        "W: 두 곡인데 둘 다 피아노 칠 사람이 필요해.",
        "M: 너희 반에 칠 줄 아는 사람 없어?",
        "W: 한 명뿐인데 걔가 노래를 해.",
        "M: 그럼 피아노 자리가 비네.",
        "W: 우리 노래에 피아노 좀 쳐 줄 수 있어?",
        "M: 오늘 밤에 악보 보내 줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 계단 공사에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The east staircase is being repaired. " +
            "Work starts this Thursday and lasts for five days. " +
            "Nobody may use that staircase during the work. " +
            "Please take the west staircase near the library. " +
            "Coming that way adds about three minutes. " +
            "Third grade classrooms are affected the most.",
        ],
      ],
      choices: ["공사 시작일", "공사 기간", "대신 쓸 곳", "더 걸리는 시간", "공사 비용"],
      answer: 5,
      clue: "Work starts this Thursday and lasts for five days.",
      explanation:
        "시작일, 기간, 대체 계단, 걸리는 시간은 말했지만 비용은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 동쪽 계단을 수리합니다. 이번 주 목요일에 시작해 닷새 동안 이어집니다. 공사 중에는 그 계단을 쓸 수 없습니다. 도서관 근처 서쪽 계단을 이용해 주세요. 그쪽으로 다니면 3분쯤 더 걸립니다. 3학년 교실이 가장 영향을 받습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You put this on your head before you ride. " +
            "A hard shell outside protects what is inside. " +
            "A strap under the chin keeps it from falling off. " +
            "Cyclists and construction workers both wear one. " +
            "Riding without it is dangerous even on a short trip.",
        ],
      ],
      choices: ["모자", "안전모", "장갑", "안경", "신발"],
      answer: 2,
      clue: "A strap under the chin keeps it from falling off.",
      explanation:
        "단단한 껍데기와 턱 끈으로 머리를 보호하는 것은 안전모이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이것은 타기 전에 머리에 씁니다. 바깥의 단단한 껍데기가 안쪽을 보호합니다. 턱 아래 끈이 있어 벗겨지지 않습니다. 자전거 타는 사람과 공사장에서 일하는 사람이 모두 씁니다. 짧은 거리라도 이것 없이 타면 위험합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Did you write down the due date?"],
        ["W", "It's in my notebook."],
        ["ANN", "Number two."],
        ["M", "Which way is the science room?"],
        ["W", "Second floor, at the end."],
        ["ANN", "Number three."],
        ["M", "Would you like some more rice?"],
        ["W", "Just a little, thanks."],
        ["ANN", "Number four."],
        ["M", "How was the interview yesterday?"],
        ["W", "This pencil is not mine."],
        ["ANN", "Number five."],
        ["M", "Shall we start the meeting?"],
        ["W", "Let's wait two more minutes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "How was the interview yesterday?",
      explanation:
        "면접이 어땠는지 묻는 말에 연필 얘기를 했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① M: 마감 날짜 적어 놨어? / W: 내 공책에 있어.",
        "② M: 과학실이 어느 쪽이야? / W: 2층 맨 끝에.",
        "③ M: 밥 더 줄까? / W: 조금만, 고마워.",
        "④ M: 어제 면접 어땠어? / W: 이 연필 내 게 아니야.",
        "⑤ M: 회의 시작할까? / W: 2분만 더 기다리자.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Sangwoo, the class presentation starts in ten minutes."],
        ["M", "The slides are open on the classroom screen."],
        ["W", "Did anyone bring the remote for the projector?"],
        ["M", "It's in the teachers' room, on the shelf."],
        ["W", "Someone has to stand at the computer without it."],
        ["M", "The presenter needs both hands for the model."],
        ["W", "I'll hand out the worksheets meanwhile."],
        ["M", "I'll go and get the remote."],
      ],
      choices: [
        "발표 자료를 띄우기",
        "학습지를 나눠 주기",
        "리모컨을 가져오기",
        "모형을 준비하기",
        "발표를 시작하기",
      ],
      answer: 3,
      clue: "I'll go and get the remote.",
      explanation:
        "남자는 교무실에 있는 리모컨을 가지러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 상우야, 학급 발표가 10분 뒤에 시작해.",
        "M: 발표 자료는 교실 화면에 띄워 놨어.",
        "W: 프로젝터 리모컨은 누가 가져왔어?",
        "M: 교무실 선반에 있어.",
        "W: 그게 없으면 누가 컴퓨터 앞에 서 있어야 해.",
        "M: 발표자는 모형 때문에 두 손이 다 필요해.",
        "W: 나는 그동안 학습지를 나눠 줄게.",
        "M: 내가 가서 리모컨을 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 예약할 연습실을 고르시오.",
      lines: [
        ["M", "Nayeon, which practice room will you book?"],
        ["W", "Five rooms are open at the center."],
        ["M", "How much can your club spend an hour?"],
        ["W", "Under twenty thousand won."],
        ["M", "One of them is far above that."],
        ["W", "It also has to hold six people."],
        ["M", "Two rooms only fit four."],
        ["W", "And we need a piano in the room."],
        ["M", "Then only one room fits everything."],
        ["W", "I'll book it for Saturday afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Under twenty thousand won.",
      explanation:
        "시간당 2만 원 미만, 6인 가능, 피아노 있음인 연습실은 ④이다. 따라서 답은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Fee: 25,000 won / People: 6 / Piano: Yes" },
          { no: 2, label: "②", value: "Fee: 15,000 won / People: 4 / Piano: Yes" },
          { no: 3, label: "③", value: "Fee: 17,000 won / People: 4 / Piano: No" },
          { no: 4, label: "④", value: "Fee: 18,000 won / People: 6 / Piano: Yes" },
          { no: 5, label: "⑤", value: "Fee: 16,000 won / People: 6 / Piano: No" },
        ],
      },
      translation: [
        "M: 나연아, 어떤 연습실 예약할 거야?",
        "W: 센터에 다섯 개가 비어 있어.",
        "M: 너희 동아리가 한 시간에 얼마까지 낼 수 있어?",
        "W: 2만 원 미만.",
        "M: 하나는 그보다 훨씬 비싸네.",
        "W: 그리고 여섯 명이 들어가야 해.",
        "M: 두 곳은 네 명까지만 돼.",
        "W: 그리고 방에 피아노가 있어야 해.",
        "M: 그럼 다 맞는 건 하나뿐이야.",
        "W: 토요일 오후로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 선생님을 찾아뵐 날짜를 고르시오.",
      lines: [
        ["W", "Kiyoung, when should we visit our old teacher?"],
        ["M", "She said three days work for her this month."],
        ["W", "Which days did she mention?"],
        ["M", "The eighth, the fifteenth and the twenty-second."],
        ["W", "The eighth is the graduation ceremony."],
        ["M", "Everyone is busy with family that day."],
        ["W", "And the twenty-second is when I move house."],
        ["M", "Then the fifteenth is the only day left."],
        ["W", "We should bring her something small."],
        ["M", "I'll pick up flowers before the fifteenth."],
      ],
      choices: ["the 8th", "the 15th", "the 22nd", "the 5th", "the 18th"],
      answer: 2,
      clue: "Then the fifteenth is the only day left.",
      explanation:
        "8일은 졸업식, 22일은 이사 날이어서 15일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "W: 기영아, 옛 선생님 언제 찾아뵐까?",
        "M: 이번 달에 사흘이 괜찮다고 하셨어.",
        "W: 어떤 날을 말씀하셨어?",
        "M: 8일, 15일, 22일.",
        "W: 8일은 졸업식이야.",
        "M: 그날은 다들 가족과 바쁘지.",
        "W: 22일은 내가 이사하는 날이고.",
        "M: 그럼 남는 날은 15일뿐이네.",
        "W: 작은 거라도 하나 사 가자.",
        "M: 15일 전에 꽃을 사 둘게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Junho, you weren't at the club room yesterday."],
        ["M", "I was moving furniture at my aunt's shop."],
        ["W", "Is she opening a new place?"],
        ["M", "She's changing the layout of the bookstore."],
        ["W", "What did you actually carry?"],
        ["M", "Six shelves and about thirty boxes of books."],
        ["W", "That sounds exhausting."],
        ["M", "My arms still ache this morning."],
        ["W", "Did she pay you for the work?"],
        ["M", "She gave me three books I wanted."],
      ],
      choices: [
        "동아리방에 갔다",
        "책을 샀다",
        "서점을 열었다",
        "이모 가게에서 가구를 옮겼다",
        "집에서 쉬었다",
      ],
      answer: 4,
      clue: "I was moving furniture at my aunt's shop.",
      explanation:
        "남자는 어제 이모 가게에서 가구를 옮겼다. 따라서 답은 ④이다.",
      translation: [
        "W: 준호야, 어제 동아리방에 없더라.",
        "M: 이모 가게에서 가구를 옮겼어.",
        "W: 새로 여시는 거야?",
        "M: 서점 배치를 바꾸고 계셔.",
        "W: 뭘 날랐는데?",
        "M: 책꽂이 여섯 개랑 책 상자 서른 개쯤.",
        "W: 힘들었겠다.",
        "M: 오늘 아침에도 팔이 아파.",
        "W: 돈은 받았어?",
        "M: 내가 갖고 싶던 책 세 권을 주셨어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school health office. " +
            "Free hearing checks are held next Monday and Tuesday. " +
            "Third grade students come on Monday afternoon. " +
            "First and second grade students come on Tuesday. " +
            "The check takes about five minutes for each person. " +
            "Tell us in advance if you already wear a hearing aid. " +
            "Results are sent home at the end of the week.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "청력 검사를 안내하려고",
        "감기 예방을 당부하려고",
        "봉사자를 모으려고",
        "청소를 부탁하려고",
      ],
      answer: 2,
      clue: "Free hearing checks are held next Monday and Tuesday.",
      explanation:
        "다음 주에 하는 청력 검사를 안내하는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 보건실입니다. 다음 주 월요일과 화요일에 무료 청력 검사를 합니다. 3학년은 월요일 오후에 오세요. 1학년과 2학년은 화요일에 오세요. 검사는 한 사람당 5분쯤 걸립니다. 보청기를 쓰는 학생은 미리 알려 주세요. 결과는 주말에 가정으로 보냅니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome. What can I get you today?"],
        ["W", "Four notebooks and two folders, please."],
        ["M", "Notebooks are three dollars each."],
        ["W", "Were they cheaper last month?"],
        ["M", "They were two dollars before the new term."],
        ["W", "And how much are the folders?"],
        ["M", "Two dollars for each folder."],
        ["W", "Do I pay extra for a bag?"],
        ["M", "No, the bag is free."],
        ["W", "Good. Here is my card."],
      ],
      choices: ["$14", "$15", "$16", "$17", "$18"],
      answer: 3,
      clue: "Notebooks are three dollars each.",
      explanation:
        "공책 네 권 12달러와 서류철 두 개 4달러를 더하면 16달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 어서 오세요. 오늘은 뭘 드릴까요?",
        "W: 공책 네 권이랑 서류철 두 개 주세요.",
        "M: 공책은 한 권에 3달러입니다.",
        "W: 지난달에는 더 쌌나요?",
        "M: 새 학기 전에는 2달러였습니다.",
        "W: 서류철은 얼마예요?",
        "M: 하나에 2달러입니다.",
        "W: 봉투 값도 내야 하나요?",
        "M: 아니요, 봉투는 무료입니다.",
        "W: 좋네요. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaewon, your presentations always sound relaxed."],
        ["W", "I say the first sentence out loud ten times."],
        ["M", "Only the first one?"],
        ["W", "If the first line goes well, the rest follows."],
        ["M", "My voice shakes on the very first word."],
        ["W", "That's when everyone is staring hardest."],
        ["M", "And then I rush through the whole thing."],
        ["W", "Slow down until the first sentence is over."],
        ["M", "What should my first sentence be?"],
      ],
      choices: [
        "Say nothing at the start.",
        "Something short and simple.",
        "Read the whole script aloud.",
        "Apologize to the class.",
        "Start with the conclusion.",
      ],
      answer: 2,
      clue: "What should my first sentence be?",
      explanation:
        "첫 문장을 무엇으로 할지 물었으므로, 짧고 단순한 것이라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 채원아, 네 발표는 늘 편안하게 들려.",
        "W: 첫 문장을 소리 내어 열 번 말해 봐.",
        "M: 첫 문장만?",
        "W: 첫 줄이 잘 나가면 나머지는 따라와.",
        "M: 나는 첫 낱말에서 목소리가 떨려.",
        "W: 그때가 다들 제일 뚫어져라 보는 때야.",
        "M: 그러고 나면 전체를 서둘러 버려.",
        "W: 첫 문장이 끝날 때까지는 천천히 해.",
        "M: 첫 문장은 뭐로 하면 좋을까?",
        "W: 짧고 단순한 걸로.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Seongjun, I heard you volunteer at the community kitchen."],
        ["M", "Every other Saturday since the spring."],
        ["W", "What do they have you do there?"],
        ["M", "I wash vegetables and carry trays."],
        ["W", "How many meals do they serve in a day?"],
        ["M", "About two hundred, mostly at lunch."],
        ["W", "Is it hard to keep up?"],
        ["M", "The first hour is the busiest by far."],
        ["W", "Do you work with other students?"],
        ["M", "Two from our school and several adults."],
        ["W", "Could I go with you next time?"],
      ],
      choices: [
        "Sure, wear closed shoes.",
        "I don't volunteer anywhere.",
        "The kitchen closed down.",
        "Students aren't allowed.",
        "I stopped going in March.",
      ],
      answer: 1,
      clue: "Could I go with you next time?",
      explanation:
        "다음에 같이 가도 되는지 물었으므로, 발을 덮는 신발을 신고 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 성준아, 지역 급식소에서 봉사한다며.",
        "M: 봄부터 격주 토요일마다.",
        "W: 거기서 뭘 시키셔?",
        "M: 채소를 씻고 쟁반을 날라.",
        "W: 하루에 몇 끼나 내?",
        "M: 200끼쯤, 대부분 점심에.",
        "W: 따라가기 힘들어?",
        "M: 첫 한 시간이 단연 제일 바빠.",
        "W: 다른 학생들과도 같이 해?",
        "M: 우리 학교에서 둘, 그리고 어른 몇 분.",
        "W: 다음에 나도 같이 가도 돼?",
        "M: 그럼, 발 덮는 신발 신고 와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yerin, how is the club recruiting poster going?"],
        ["M", "You said it goes up in the hallway on Monday."],
        ["W", "I drew it twice and it still looks empty."],
        ["W", "There's just a title and our club name."],
        ["M", "What does a new student actually want to know?"],
        ["W", "When we meet and what we do, I suppose."],
        ["M", "Neither of those is on the poster yet."],
        ["W", "I spent all my time on the drawing."],
        ["M", "Why don't you add the meeting day and place?"],
      ],
      choices: [
        "I'll add them tonight.",
        "We never meet anywhere.",
        "There is no club.",
        "I'll draw it again.",
        "Nobody reads posters.",
      ],
      answer: 1,
      clue: "Why don't you add the meeting day and place?",
      explanation:
        "모이는 날과 장소를 넣으라는 제안이므로, 오늘 밤에 넣겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 예린아, 동아리 모집 포스터는 잘돼 가?",
        "M: 월요일에 복도에 붙인다고 했잖아.",
        "W: 두 번이나 그렸는데 아직 휑해 보여.",
        "W: 제목이랑 동아리 이름뿐이야.",
        "M: 새로 들어오는 학생이 정말 궁금한 게 뭘까?",
        "W: 언제 모이고 뭘 하는지겠지.",
        "M: 둘 다 아직 포스터에 없잖아.",
        "W: 그림에만 시간을 다 썼어.",
        "M: 모이는 날이랑 장소를 넣는 건 어때?",
        "W: 오늘 밤에 넣을게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Dain이 Woojin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Dain : ________________",
      lines: [
        [
          "W",
          "Dain and Woojin are packing up after the science fair. " +
            "Woojin is about to unplug the lamp by pulling on the cord. " +
            "Dain can see the cord is already frayed near the plug. " +
            "Pulling it that way could tear the wire completely. " +
            "She wants him to hold the plug itself instead. " +
            "In this situation, what would Dain most likely say to Woojin?",
        ],
      ],
      choices: [
        "Pull the cord harder.",
        "Leave the lamp turned on.",
        "The fair starts tomorrow.",
        "We need a longer cord.",
        "Hold the plug, not the cord.",
      ],
      answer: 5,
      clue: "She wants him to hold the plug itself instead.",
      explanation:
        "선이 이미 해져 있으므로, 선 말고 플러그를 잡으라는 ⑤가 가장 적절하다.",
      translation: [
        "W: 다인이와 우진이는 과학 전시회가 끝난 뒤 정리를 하고 있습니다. 우진이는 전선을 잡아당겨 등을 뽑으려고 합니다. 다인이는 플러그 근처 전선이 이미 해진 것을 봅니다. 그렇게 당기면 선이 완전히 끊어질 수 있습니다. 그녀는 그가 대신 플러그를 잡기를 바랍니다. 이런 상황에서 다인이가 우진이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
