/** 중3 듣기 43회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 43회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 고를 여행 가방을 고르시오.",
      lines: [
        ["W", "Junho, are you picking a suitcase for the trip?"],
        ["M", "Yes, but I can't decide on the handle."],
        ["W", "This one has a handle on the top only."],
        ["M", "I'd rather have a pull-up handle for the airport."],
        ["W", "Do you want two wheels or four?"],
        ["M", "Four wheels. Two are hard to turn."],
        ["W", "And the strap across the front?"],
        ["M", "No strap. It catches on everything."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Four wheels. Two are hard to turn. / No strap. It catches on everything.",
      explanation:
        "긴 손잡이가 올라오고 바퀴가 넷이며 앞에 끈이 없는 가방이다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five suitcases side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a suitcase with only a small TOP HANDLE and TWO wheels, no strap. " +
          "② a suitcase with a tall PULL-UP HANDLE and TWO wheels, no strap. " +
          "③ a suitcase with a tall PULL-UP HANDLE, FOUR wheels and a STRAP across the front. " +
          "④ a suitcase with a tall PULL-UP HANDLE, FOUR wheels and no strap. " +
          "⑤ a suitcase with only a small TOP HANDLE, FOUR wheels and a STRAP across the front.",
      },
      translation: [
        "W: 준호야, 여행 가방 고르는 중이야?",
        "M: 응, 그런데 손잡이를 못 정하겠어.",
        "W: 이건 위에만 손잡이가 있네.",
        "M: 공항에서는 길게 뽑는 손잡이가 더 좋아.",
        "W: 바퀴는 두 개로 할래, 네 개로 할래?",
        "M: 네 개. 두 개는 돌리기 힘들어.",
        "W: 앞에 가로지르는 끈은?",
        "M: 끈은 안 돼. 여기저기 걸려.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 체험 학습에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minjun, where is our grade going next month?"],
        ["M", "To the old pottery village in Icheon."],
        ["W", "How do we get there from school?"],
        ["M", "By bus, and the ride takes an hour."],
        ["W", "What do we do once we arrive?"],
        ["M", "We shape a bowl and watch the kiln."],
        ["W", "Do we bring our own lunch?"],
        ["M", "Yes, a lunch box and a water bottle."],
        ["W", "When do we get back to school?"],
        ["M", "Around four in the afternoon."],
      ],
      choices: ["가는 곳", "가는 방법", "하는 활동", "가져갈 것", "드는 비용"],
      answer: 5,
      clue: "To the old pottery village in Icheon.",
      explanation:
        "장소, 방법, 활동, 준비물은 말했지만 비용은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민준아, 다음 달에 우리 학년 어디 가?",
        "M: 이천에 있는 옛 도자기 마을에.",
        "W: 학교에서 어떻게 가?",
        "M: 버스로, 한 시간 걸려.",
        "W: 도착하면 뭘 해?",
        "M: 그릇을 빚고 가마를 구경해.",
        "W: 점심은 각자 가져가?",
        "M: 응, 도시락이랑 물병.",
        "W: 학교에는 몇 시에 돌아와?",
        "M: 오후 네 시쯤.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Come in, Chaeyeon. You look determined today."],
        ["W", "I've been thinking about this for a week."],
        ["M", "Is it about your high school choice?"],
        ["W", "It's about the school band, actually."],
        ["M", "You've played the bass since first grade."],
        ["W", "Three members are graduating in February."],
        ["M", "So the band will be very small next year."],
        ["W", "Nobody wants to lead the practices."],
        ["M", "And you think you could do it."],
        ["W", "I came to ask if I can be the band leader."],
      ],
      choices: [
        "동아리를 그만두려고",
        "동아리 회장을 맡겠다고 말하려고",
        "악기를 빌리려고",
        "상담을 받으려고",
        "연습실을 예약하려고",
      ],
      answer: 2,
      clue: "I came to ask if I can be the band leader.",
      explanation:
        "여자는 밴드 대표를 맡을 수 있는지 물으러 왔다. 따라서 답은 ②이다.",
      translation: [
        "M: 들어와, 채연아. 오늘 단단히 마음먹은 얼굴이구나.",
        "W: 일주일 동안 생각했어요.",
        "M: 고등학교 선택 때문이니?",
        "W: 사실 학교 밴드 때문이에요.",
        "M: 1학년 때부터 베이스를 쳤지.",
        "W: 2월에 세 명이 졸업해요.",
        "M: 그럼 내년에는 밴드가 아주 작아지겠구나.",
        "W: 연습을 이끌겠다는 사람이 없어요.",
        "M: 네가 할 수 있겠다고 생각하는구나.",
        "W: 제가 밴드 대표를 맡아도 될지 여쭈러 왔어요.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만날 시각을 고르시오.",
      lines: [
        ["W", "Sangjin, when should we meet at the study café?"],
        ["M", "They open the second floor at two o'clock."],
        ["W", "My English class ends at two thirty."],
        ["M", "Then two o'clock doesn't work for you."],
        ["W", "It takes ten minutes to walk there."],
        ["M", "So you'd arrive around two forty."],
        ["W", "Let's just say three to be safe."],
        ["M", "Three o'clock on the second floor."],
        ["W", "I'll save two seats by the window."],
      ],
      choices: ["2:00 p.m.", "2:30 p.m.", "2:40 p.m.", "3:00 p.m.", "3:30 p.m."],
      answer: 4,
      clue: "Let's just say three to be safe.",
      explanation:
        "수업이 2시 30분에 끝나고 걷는 시간까지 감안해 3시에 만나기로 했다. 따라서 답은 ④이다.",
      translation: [
        "W: 상진아, 스터디 카페에서 몇 시에 만날까?",
        "M: 2층을 두 시에 열어.",
        "W: 내 영어 수업이 2시 30분에 끝나.",
        "M: 그럼 두 시는 너한테 안 되겠네.",
        "W: 거기까지 걸어서 10분 걸려.",
        "M: 그럼 2시 40분쯤 도착하겠다.",
        "W: 넉넉하게 세 시로 하자.",
        "M: 세 시에 2층에서.",
        "W: 창가 자리 두 개 맡아 둘게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yeji, you've been humming since we left school."],
        ["W", "My essay won first place in the city contest."],
        ["M", "The one about your grandmother's garden?"],
        ["W", "I rewrote the ending five times."],
        ["M", "How many students entered this year?"],
        ["W", "More than four hundred, from thirty schools."],
        ["M", "And yours came out on top."],
        ["W", "I still can't believe they called my name."],
      ],
      choices: ["scared", "bored", "delighted", "sorry", "worried"],
      answer: 3,
      clue: "I still can't believe they called my name.",
      explanation:
        "글이 1등으로 뽑혀 몹시 기뻐하고 있다. 따라서 답은 ③이다.",
      translation: [
        "M: 예지야, 학교 나온 뒤로 계속 콧노래를 부르네.",
        "W: 내 글이 시 대회에서 1등 했어.",
        "M: 할머니 텃밭에 대해 쓴 그거?",
        "W: 끝부분을 다섯 번이나 고쳐 썼어.",
        "M: 올해 몇 명이나 냈어?",
        "W: 서른 개 학교에서 400명 넘게.",
        "M: 그중에 네 글이 제일 위로 올라간 거네.",
        "W: 내 이름을 불렀다는 게 아직도 안 믿겨.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How much is this jacket?"],
        ["W", "Forty thousand won."],
        ["ANN", "Number two."],
        ["M", "Does it come in a larger size?"],
        ["W", "Let me check the back."],
        ["ANN", "Number three."],
        ["M", "The zipper is broken."],
        ["W", "I'll bring you another one."],
        ["ANN", "Number four."],
        ["M", "Can I pay in cash?"],
        ["W", "Yes, of course."],
        ["ANN", "Number five."],
        ["M", "Where is the fitting room?"],
        ["W", "Behind that blue curtain."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "The zipper is broken.",
      explanation:
        "그림은 손님이 고장 난 지퍼를 가리키자 점원이 다른 옷을 가지러 가는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a clothing shop, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy holds up a jacket and points with one finger at its zipper, which is split open halfway. " +
          "A shop assistant beside him turns toward a rack of identical jackets and reaches for one. " +
          "Hanging clothes and a mirror are drawn simply in the background.",
      },
      translation: [
        "① M: 이 외투 얼마예요? / W: 4만 원입니다.",
        "② M: 더 큰 치수 있나요? / W: 뒤쪽에 확인해 볼게요.",
        "③ M: 지퍼가 고장 났어요. / W: 다른 걸로 가져다드릴게요.",
        "④ M: 현금으로 내도 되나요? / W: 네, 그럼요.",
        "⑤ M: 탈의실이 어디예요? / W: 저 파란 커튼 뒤에요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dahye, you take the number seven bus, right?"],
        ["W", "Every morning and every evening."],
        ["M", "That bus stops in front of the library."],
        ["W", "It's the third stop from school."],
        ["M", "I borrowed two books that are due today."],
        ["W", "And you can't get there before it closes?"],
        ["M", "I have a dentist appointment at five."],
        ["W", "The library takes returns until seven."],
        ["M", "Could you return these books on your way?"],
        ["W", "Give them to me and I'll drop them off."],
      ],
      choices: [
        "책을 반납해 주기",
        "책을 빌려 주기",
        "병원에 같이 가 주기",
        "버스비를 빌려주기",
        "짐을 들어 주기",
      ],
      answer: 1,
      clue: "Could you return these books on your way?",
      explanation:
        "남자는 가는 길에 책을 반납해 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 다혜야, 너 7번 버스 타지?",
        "W: 아침저녁으로 매일.",
        "M: 그 버스가 도서관 앞에 서잖아.",
        "W: 학교에서 세 번째 정류장이야.",
        "M: 오늘까지인 책 두 권을 빌렸어.",
        "W: 닫기 전에 못 가?",
        "M: 다섯 시에 치과 예약이 있어.",
        "W: 도서관은 일곱 시까지 반납 받아.",
        "M: 가는 길에 이 책들 좀 반납해 줄 수 있어?",
        "W: 줘, 내가 넣고 갈게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 축제 무대 공연에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The festival stage is open for performances. " +
            "Each team may perform for up to seven minutes. " +
            "Singing, dancing and short plays are all welcome. " +
            "Apply at the student council room by this Friday. " +
            "The stage runs from one until four in the afternoon. " +
            "Bring your own instruments if you need them.",
        ],
      ],
      choices: ["공연 시간", "할 수 있는 공연", "신청하는 곳", "무대가 열리는 시간", "공연 순서"],
      answer: 5,
      clue: "Each team may perform for up to seven minutes.",
      explanation:
        "시간, 종류, 신청처, 무대 운영 시간은 말했지만 공연 순서는 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. 축제 무대에서 공연할 팀을 받습니다. 한 팀은 최대 7분까지 공연할 수 있습니다. 노래, 춤, 짧은 연극 모두 환영합니다. 이번 주 금요일까지 학생회실에서 신청하세요. 무대는 오후 한 시부터 네 시까지 이어집니다. 필요한 악기는 각자 가져오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "You put this over your ears to hear without disturbing others. " +
            "A cable or a small signal carries the sound to you. " +
            "Students wear it while studying on the subway. " +
            "Using it too loudly can hurt your hearing over time. " +
            "The pair usually comes in a small round case.",
        ],
      ],
      choices: ["안경", "모자", "이어폰", "목도리", "장갑"],
      answer: 3,
      clue: "You put this over your ears to hear without disturbing others.",
      explanation:
        "귀에 꽂고 혼자 소리를 듣는 것은 이어폰이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 남을 방해하지 않고 소리를 듣기 위해 귀에 꽂습니다. 선이나 작은 신호가 소리를 전해 줍니다. 학생들은 지하철에서 공부할 때 이것을 씁니다. 너무 크게 들으면 시간이 지나 청력이 상할 수 있습니다. 보통 작고 둥근 통에 한 쌍이 들어 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "What are you reading these days?"],
        ["M", "A novel about the sea."],
        ["ANN", "Number two."],
        ["W", "Could you turn off the light?"],
        ["M", "Sure, one second."],
        ["ANN", "Number three."],
        ["W", "How was your interview?"],
        ["M", "Better than I expected."],
        ["ANN", "Number four."],
        ["W", "Who is your homeroom teacher?"],
        ["M", "I ate lunch at twelve thirty."],
        ["ANN", "Number five."],
        ["W", "Are you coming to the festival?"],
        ["M", "I'll be there on Saturday."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Who is your homeroom teacher?",
      explanation:
        "담임 선생님을 묻는 말에 점심 시각을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 요즘 무슨 책 읽어? / M: 바다에 관한 소설.",
        "② W: 불 좀 꺼 줄래? / M: 그래, 잠깐만.",
        "③ W: 면접 어땠어? / M: 생각보다 나았어.",
        "④ W: 담임 선생님이 누구셔? / M: 나는 12시 30분에 점심 먹었어.",
        "⑤ W: 축제에 올 거야? / M: 토요일에 갈게.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Suyeon, the science presentation starts in fifteen minutes."],
        ["W", "The slides are loaded on the classroom computer."],
        ["M", "Did you print the handout for the judges?"],
        ["W", "The file is ready but not printed yet."],
        ["M", "Three judges need one copy each."],
        ["W", "The printer in the office is free now."],
        ["M", "I'll set up the model on the table."],
        ["W", "I'll go and print the handouts."],
      ],
      choices: [
        "발표 자료를 띄우기",
        "모형을 놓기",
        "유인물을 출력하기",
        "심사위원을 맞이하기",
        "교실을 정리하기",
      ],
      answer: 3,
      clue: "I'll go and print the handouts.",
      explanation:
        "여자는 유인물을 출력하러 가겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수연아, 과학 발표가 15분 뒤에 시작해.",
        "W: 발표 자료는 교실 컴퓨터에 띄워 놨어.",
        "M: 심사위원 드릴 유인물은 출력했어?",
        "W: 파일은 됐는데 아직 안 뽑았어.",
        "M: 심사위원 세 분께 한 부씩 필요해.",
        "W: 지금 사무실 인쇄기가 비어 있어.",
        "M: 나는 탁자에 모형을 놓을게.",
        "W: 내가 가서 유인물을 출력할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 고를 봉사 활동을 고르시오.",
      lines: [
        ["W", "Seungho, which volunteer program should we join this time?"],
        ["M", "Five programs are open at the center this winter."],
        ["W", "We only have Saturday afternoons free these days."],
        ["M", "So every weekday program is already out."],
        ["W", "It should also take three hours or less."],
        ["M", "One of them runs for five hours straight."],
        ["W", "We would never get home before dinner."],
        ["M", "And the last bus leaves the center at six."],
        ["W", "It also has to be indoors because of the cold."],
        ["M", "Then only one program fits everything you said."],
        ["W", "I'll write both our names down this afternoon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "We only have Saturday afternoons free these days.",
      explanation:
        "토요일, 3시간 이하, 실내인 봉사 활동은 ⑤이다. 따라서 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Wednesday / Hours: 2 / Place: Indoor" },
          { no: 2, label: "②", value: "Day: Saturday / Hours: 5 / Place: Indoor" },
          { no: 3, label: "③", value: "Day: Saturday / Hours: 3 / Place: Outdoor" },
          { no: 4, label: "④", value: "Day: Thursday / Hours: 3 / Place: Indoor" },
          { no: 5, label: "⑤", value: "Day: Saturday / Hours: 2 / Place: Indoor" },
        ],
      },
      translation: [
        "W: 승호야, 이번에는 어떤 봉사 활동에 참여할까?",
        "M: 이번 겨울에 센터에서 다섯 개를 열었어.",
        "W: 요즘 우리는 토요일 오후만 비어.",
        "M: 그럼 평일 것은 전부 빠지네.",
        "W: 시간도 세 시간 이하여야 해.",
        "M: 하나는 다섯 시간을 내리 해.",
        "W: 그러면 저녁 전에는 집에 못 가겠다.",
        "M: 센터에서 나오는 막차도 여섯 시야.",
        "W: 그리고 추우니까 실내여야 해.",
        "M: 그럼 네가 말한 조건에 다 맞는 건 하나뿐이야.",
        "W: 오늘 오후에 우리 둘 이름 적어 둘게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 송별회를 열 날짜를 고르시오.",
      lines: [
        ["M", "Jieun, when should we hold the farewell party?"],
        ["W", "Our teacher leaves at the end of this month."],
        ["M", "Which days work for the classroom?"],
        ["W", "The twentieth, the twenty-third and the twenty-sixth."],
        ["M", "The twentieth is the day before the exam."],
        ["W", "Nobody could enjoy a party that evening."],
        ["M", "And the twenty-sixth is after she leaves."],
        ["W", "Then the twenty-third is the day for us."],
        ["M", "We should prepare the letters by then."],
        ["W", "I'll collect them before the twenty-third."],
      ],
      choices: ["the 20th", "the 23rd", "the 26th", "the 18th", "the 28th"],
      answer: 2,
      clue: "Then the twenty-third is the day for us.",
      explanation:
        "20일은 시험 전날, 26일은 선생님이 떠난 뒤여서 23일로 정했다. 따라서 답은 ②이다.",
      translation: [
        "M: 지은아, 송별회 언제 열까?",
        "W: 선생님이 이번 달 말에 떠나셔.",
        "M: 교실을 쓸 수 있는 날이 언제야?",
        "W: 20일, 23일, 26일.",
        "M: 20일은 시험 전날이야.",
        "W: 그날 저녁에는 아무도 즐기지 못하겠지.",
        "M: 26일은 선생님이 떠나신 뒤고.",
        "W: 그럼 우리한테는 23일이네.",
        "M: 그때까지 편지를 준비해야겠다.",
        "W: 23일 전에 내가 걷을게.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hyunsu, you weren't at the library yesterday."],
        ["M", "I was at the gym teaching my cousin to swim."],
        ["W", "How old is your cousin?"],
        ["M", "Seven, and he was afraid of the water."],
        ["W", "Did he actually get in?"],
        ["M", "After twenty minutes on the steps."],
        ["W", "What did you teach him first?"],
        ["M", "How to put his face in and blow bubbles."],
        ["W", "Will you go again this week?"],
        ["M", "Every Wednesday until he can float."],
      ],
      choices: [
        "도서관에서 공부했다",
        "수영을 배웠다",
        "사촌에게 수영을 가르쳤다",
        "체육관을 청소했다",
        "집에서 쉬었다",
      ],
      answer: 3,
      clue: "I was at the gym teaching my cousin to swim.",
      explanation:
        "남자는 어제 사촌에게 수영을 가르쳤다. 따라서 답은 ③이다.",
      translation: [
        "W: 현수야, 어제 도서관에 없더라.",
        "M: 체육관에서 사촌한테 수영을 가르쳤어.",
        "W: 사촌이 몇 살이야?",
        "M: 일곱 살인데 물을 무서워했어.",
        "W: 결국 들어갔어?",
        "M: 계단에서 20분 있다가.",
        "W: 뭐부터 가르쳤어?",
        "M: 얼굴을 담그고 숨 내뱉는 것부터.",
        "W: 이번 주에도 가?",
        "M: 뜰 수 있을 때까지 수요일마다.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "Attention, students. This is the school health office. " +
            "The flu is spreading quickly in our neighborhood. " +
            "Wash your hands whenever you come in from outside. " +
            "Open the classroom windows between every class. " +
            "Stay home if your temperature is over thirty-eight degrees. " +
            "Tell your homeroom teacher before you leave. " +
            "Take care of yourselves this month.",
        ],
      ],
      choices: [
        "체육 대회를 안내하려고",
        "독감 예방을 당부하려고",
        "결석 처리를 알리려고",
        "봉사자를 모으려고",
        "청소를 부탁하려고",
      ],
      answer: 2,
      clue: "The flu is spreading quickly in our neighborhood.",
      explanation:
        "손 씻기와 환기를 당부하며 독감 예방을 알리는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "W: 학생 여러분께 알려 드립니다. 보건실입니다. 우리 동네에 독감이 빠르게 퍼지고 있습니다. 밖에서 들어올 때마다 손을 씻으세요. 수업 사이마다 교실 창문을 여세요. 체온이 38도가 넘으면 집에 있으세요. 나가기 전에 담임 선생님께 말씀드리세요. 이번 달 건강에 유의하기 바랍니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Hello. What can I get for you today?"],
        ["W", "Four sandwiches and two cups of coffee."],
        ["M", "Sandwiches are five dollars each."],
        ["W", "That's more than last week."],
        ["M", "The bread price went up this month."],
        ["W", "And the coffee?"],
        ["M", "Two dollars for a regular cup."],
        ["W", "Do I pay extra for the tray?"],
        ["M", "No, the tray costs nothing."],
        ["W", "All right. Here is my card."],
      ],
      choices: ["$20", "$22", "$24", "$26", "$28"],
      answer: 3,
      clue: "Sandwiches are five dollars each.",
      explanation:
        "샌드위치 네 개 20달러와 커피 두 잔 4달러를 더하면 24달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 안녕하세요. 오늘은 뭘 드릴까요?",
        "W: 샌드위치 네 개랑 커피 두 잔 주세요.",
        "M: 샌드위치는 하나에 5달러입니다.",
        "W: 지난주보다 올랐네요.",
        "M: 이번 달에 빵값이 올랐습니다.",
        "W: 커피는요?",
        "M: 보통 잔은 2달러입니다.",
        "W: 쟁반 값도 내야 하나요?",
        "M: 아니요, 쟁반은 돈을 받지 않습니다.",
        "W: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Bora, your English listening score went up fast."],
        ["W", "I listen to one short news clip every night."],
        ["M", "Do you understand all of it the first time?"],
        ["W", "Almost none of it on the first listen."],
        ["M", "Then how does it help at all?"],
        ["W", "I play the same clip three times in a row."],
        ["M", "And the third time is different?"],
        ["W", "The third time I hear the words I missed."],
        ["M", "How long is one clip?"],
      ],
      choices: [
        "About two minutes.",
        "Two hours every night.",
        "I don't listen to clips.",
        "Only on weekends.",
        "Clips are useless.",
      ],
      answer: 1,
      clue: "How long is one clip?",
      explanation:
        "한 편이 얼마나 긴지 물었으므로, 2분쯤이라는 ①이 가장 자연스럽다.",
      translation: [
        "M: 보라야, 네 영어 듣기 점수가 빨리 올랐네.",
        "W: 매일 밤 짧은 뉴스 한 편을 들어.",
        "M: 처음 들을 때 다 알아들어?",
        "W: 처음에는 거의 못 알아들어.",
        "M: 그럼 그게 무슨 도움이 돼?",
        "W: 같은 편을 세 번 이어서 틀어.",
        "M: 세 번째는 다르다는 거야?",
        "W: 세 번째에는 놓쳤던 낱말이 들려.",
        "M: 한 편이 얼마나 길어?",
        "W: 2분쯤이야.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Kiyoung, I heard you repair bicycles at the youth center."],
        ["M", "I learned from a mechanic who volunteers there."],
        ["W", "What kind of repairs do you do?"],
        ["M", "Mostly flat tires and loose chains."],
        ["W", "How long does one bicycle take?"],
        ["M", "About twenty minutes if nothing is bent."],
        ["W", "Do people pay for it?"],
        ["M", "It's free for anyone under nineteen."],
        ["W", "How many bicycles come in on a Saturday?"],
        ["M", "Six or seven, sometimes more."],
        ["W", "Could you look at my bicycle this Saturday?"],
      ],
      choices: [
        "Sure, bring it before noon.",
        "I don't fix bicycles.",
        "The center closed down.",
        "You should buy a new one.",
        "I stopped going there.",
      ],
      answer: 1,
      clue: "Could you look at my bicycle this Saturday?",
      explanation:
        "토요일에 자전거를 봐 달라고 했으므로, 정오 전에 가져오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 기영아, 청소년 센터에서 자전거를 고친다며.",
        "M: 거기서 봉사하시는 정비사분께 배웠어.",
        "W: 어떤 걸 고쳐?",
        "M: 대부분 바람 빠진 바퀴랑 헐거워진 체인.",
        "W: 한 대에 얼마나 걸려?",
        "M: 휜 데가 없으면 20분쯤.",
        "W: 돈을 받아?",
        "M: 열아홉 살 아래면 무료야.",
        "W: 토요일에 몇 대나 들어와?",
        "M: 예닐곱 대, 더 올 때도 있어.",
        "W: 이번 토요일에 내 자전거 좀 봐 줄래?",
        "M: 그럼, 정오 전에 가져와.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nari, how is the class newspaper going this term?"],
        ["M", "You said the winter issue comes out in December."],
        ["W", "We have plenty of articles but no readers."],
        ["W", "Copies sit on the table until someone throws them out."],
        ["M", "Where exactly do you leave them?"],
        ["W", "On the table beside the teachers' room."],
        ["M", "Hardly any student walks past that door."],
        ["W", "I never thought about where students actually go."],
        ["M", "Why don't you put them by the cafeteria line?"],
      ],
      choices: [
        "I'll move them tomorrow.",
        "We have no newspapers.",
        "Students can't read.",
        "The cafeteria is closed.",
        "I'll stop printing them.",
      ],
      answer: 1,
      clue: "Why don't you put them by the cafeteria line?",
      explanation:
        "급식 줄 옆에 두라는 제안이므로, 내일 옮기겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 나리야, 이번 학기 학급 신문은 잘돼 가?",
        "M: 겨울 호가 12월에 나온다고 했잖아.",
        "W: 기사는 많은데 읽는 사람이 없어.",
        "W: 누가 버릴 때까지 탁자에 그대로 쌓여 있어.",
        "M: 정확히 어디에 놓아 둬?",
        "W: 교무실 옆 탁자에.",
        "M: 그 문 앞으로는 학생이 거의 안 지나가.",
        "W: 학생들이 실제로 어디를 다니는지는 생각 못 했어.",
        "M: 급식 줄 옆에 두는 건 어때?",
        "W: 내일 옮길게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Taeho가 Yuna에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Taeho : ________________",
      lines: [
        [
          "M",
          "Taeho and Yuna are practicing for the school talent show. " +
            "Yuna is about to sing with the microphone right against her mouth. " +
            "Taeho hears a loud popping noise every time she starts a word. " +
            "The sound system cannot handle the microphone that close. " +
            "He wants her to hold it a little further from her face. " +
            "In this situation, what would Taeho most likely say to Yuna?",
        ],
      ],
      choices: [
        "Sing much more loudly.",
        "Hold the mic a bit further away.",
        "Let's cancel the show.",
        "The microphone is broken.",
        "You should not sing at all.",
      ],
      answer: 2,
      clue: "He wants her to hold it a little further from her face.",
      explanation:
        "마이크가 너무 가까워 소리가 튀므로, 조금 떼라는 ②가 가장 적절하다.",
      translation: [
        "M: 태호와 유나는 학예회 연습을 하고 있습니다. 유나는 마이크를 입에 바짝 붙인 채 노래하려고 합니다. 태호는 그녀가 말을 시작할 때마다 퍽퍽 튀는 소리를 듣습니다. 음향 장치가 그렇게 가까운 마이크를 감당하지 못합니다. 그는 그녀가 마이크를 얼굴에서 조금 떼기를 바랍니다. 이런 상황에서 태호가 유나에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
