/** 중3 듣기 15회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 15회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 필통을 고르시오.",
      lines: [
        ["M", "Good afternoon. Can I help you find something?"],
        ["W", "Yes, I need a new pencil case for school."],
        ["M", "We have flat ones and standing ones that open at the top."],
        ["W", "A standing one, please. I like to see everything at once."],
        ["M", "Of course. Do you want a strap on the side to hang it?"],
        ["W", "No strap, thank you. It catches on things in my bag."],
        ["M", "Then two are left. One has stripes and one has no pattern."],
        ["W", "I'll take the striped one. My last plain one got dirty fast."],
        ["M", "Good choice. This one can be wiped clean as well."],
        ["W", "Perfect. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "I'll take the striped one. My last plain one got dirty fast.",
      explanation:
        "여자는 세워 두는 필통을, 옆에 고리끈이 없는 것으로, 줄무늬가 있는 것을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five pencil cases shown in one row on a plain white background, each drawn separately and the same size, clean black line art, no writing anywhere. " +
          "First: a FLAT pouch lying down, with no strap, completely plain. " +
          "Second: a FLAT pouch lying down, with a short hanging STRAP on its side, covered in stripes. " +
          "Third: a TALL STANDING pencil case that opens at the top, with a short hanging STRAP on its side, covered in stripes. " +
          "Fourth: a TALL STANDING pencil case that opens at the top, with NO strap at all, covered in stripes. " +
          "Fifth: a TALL STANDING pencil case that opens at the top, with NO strap at all, completely plain with no pattern.",
      },
      translation: [
        "M: 안녕하세요. 찾으시는 것 도와드릴까요?",
        "W: 네, 학교에서 쓸 새 필통이 필요해요.",
        "M: 납작한 것과 위가 열리는 세워 두는 것이 있습니다.",
        "W: 세워 두는 걸로요. 한눈에 다 보이는 게 좋아서요.",
        "M: 네. 옆에 걸 수 있는 고리끈이 있는 걸로 하시겠어요?",
        "W: 끈은 없는 걸로요. 가방 안에서 자꾸 걸려요.",
        "M: 그럼 두 개 남았네요. 하나는 줄무늬가 있고 하나는 무늬가 없습니다.",
        "W: 줄무늬로 할게요. 지난번 무늬 없는 건 금방 더러워졌어요.",
        "M: 좋은 선택이세요. 이건 닦아 낼 수도 있습니다.",
        "W: 딱 좋네요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 진로 체험의 날에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Junseo, have you signed up for the career experience day?"],
        ["M", "Not yet. I only saw the poster in the hallway."],
        ["W", "It's on the last Tuesday of this month, all afternoon."],
        ["M", "Where does it happen?"],
        ["W", "At four places outside school. You take a bus to one of them."],
        ["M", "What kind of places?"],
        ["W", "A hospital, a radio station, a bakery, and a print shop."],
        ["M", "Do we choose, or do they decide for us?"],
        ["W", "You write your first and second choice on the form."],
        ["M", "Then I'll pick the radio station. Where do I get the form?"],
        ["W", "Outside the counselling room. It closes on Thursday."],
      ],
      choices: ["진행 날짜", "체험 장소", "선택 방법", "신청서 받는 곳", "인솔 교사"],
      answer: 5,
      clue: "Outside the counselling room. It closes on Thursday.",
      explanation:
        "날짜(이달 마지막 화요일), 체험 장소(병원·방송국·빵집·인쇄소), 선택 방법(1·2지망 적기), 신청서 받는 곳(상담실 앞)은 언급되지만 인솔 교사는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 준서야, 진로 체험의 날 신청했어?",
        "M: 아직. 복도에서 포스터만 봤어.",
        "W: 이달 마지막 화요일, 오후 내내 해.",
        "M: 어디서 하는데?",
        "W: 학교 밖 네 곳에서. 버스 타고 한 곳으로 가.",
        "M: 어떤 곳들인데?",
        "W: 병원, 방송국, 빵집, 인쇄소.",
        "M: 우리가 고르는 거야, 아니면 정해 주는 거야?",
        "W: 신청서에 1지망, 2지망을 적어.",
        "M: 그럼 방송국으로 해야지. 신청서는 어디서 받아?",
        "W: 상담실 앞에. 목요일에 마감이야.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Hyunwoo. It's Sora from the science club."],
        ["M", "Hi. Is something wrong with tomorrow's trip?"],
        ["W", "Not wrong, but the meeting place has changed."],
        ["M", "I thought we were meeting at the school gate."],
        ["W", "We were, but the bus can't stop there because of the road work."],
        ["M", "So where do we meet instead?"],
        ["W", "In front of the post office, at the same time."],
        ["M", "Got it. I'll be there at eight."],
        ["W", "Thanks. Could you tell the others in your class too?"],
      ],
      choices: [
        "모이는 장소가 바뀐 것을 알리려고",
        "출발 시간을 미루려고",
        "준비물을 부탁하려고",
        "견학이 취소되었다고 알리려고",
        "동아리 가입을 권하려고",
      ],
      answer: 1,
      clue: "In front of the post office, at the same time.",
      explanation:
        "도로 공사 때문에 모이는 장소가 교문 앞에서 우체국 앞으로 바뀐 것을 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 현우야. 과학 동아리 소라야.",
        "M: 안녕. 내일 견학에 무슨 문제 있어?",
        "W: 문제는 아니고, 모이는 장소가 바뀌었어.",
        "M: 교문 앞에서 모이는 줄 알았는데.",
        "W: 그랬는데 도로 공사 때문에 버스가 거기 못 서.",
        "M: 그럼 어디서 모여?",
        "W: 우체국 앞에서, 시간은 그대로.",
        "M: 알겠어. 8시에 갈게.",
        "W: 고마워. 너희 반 애들한테도 좀 알려 줄래?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taeho, what time should we meet at the sports centre?"],
        ["M", "Our badminton court is booked from three to five."],
        ["W", "Then we should get there a bit earlier to change."],
        ["M", "How about two thirty?"],
        ["W", "That's half an hour of sitting around."],
        ["M", "True. How long does it take you to get there?"],
        ["W", "Twenty minutes on foot from my house."],
        ["M", "Then let's meet at two forty-five. Fifteen minutes is enough."],
        ["W", "Two forty-five is fine. I'll bring the shuttlecocks."],
      ],
      choices: ["2:15 p.m.", "2:30 p.m.", "2:45 p.m.", "3:00 p.m.", "3:15 p.m."],
      answer: 3,
      clue: "Then let's meet at two forty-five. Fifteen minutes is enough.",
      explanation:
        "코트 예약이 3시부터이고 갈아입을 시간 15분이면 충분하므로 두 사람은 2시 45분에 만나기로 한다. 따라서 답은 ③이다.",
      translation: [
        "W: 태호야, 체육센터에서 몇 시에 만날까?",
        "M: 배드민턴 코트를 3시부터 5시까지 예약했어.",
        "W: 그럼 갈아입게 조금 일찍 가야겠다.",
        "M: 2시 30분은 어때?",
        "W: 30분이나 앉아 있는 거잖아.",
        "M: 그러네. 거기까지 얼마나 걸려?",
        "W: 우리 집에서 걸어서 20분.",
        "M: 그럼 2시 45분에 만나자. 15분이면 충분해.",
        "W: 2시 45분 좋아. 셔틀콕은 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjae, you've been quiet since the bell."],
        ["M", "I left my science project on the bus this morning."],
        ["W", "The model you worked on for three weeks?"],
        ["M", "That one. It's due at two o'clock."],
        ["W", "Did you call the bus company?"],
        ["M", "My teacher did. Nobody has handed anything in."],
        ["W", "There's still time. It might turn up."],
        ["M", "Three weeks of evenings, and I have nothing to show."],
      ],
      choices: ["excited", "upset", "proud", "bored", "relieved"],
      answer: 2,
      clue: "Three weeks of evenings, and I have nothing to show.",
      explanation:
        "3주 동안 저녁마다 만든 과제를 버스에 두고 내려 낼 것이 없다고 했으므로 남자는 속상해하고 있다. 따라서 답은 ②이다.",
      translation: [
        "W: 민재야, 종 친 뒤로 말이 없네.",
        "M: 오늘 아침에 과학 과제를 버스에 두고 내렸어.",
        "W: 3주 동안 만든 그 모형?",
        "M: 그거. 2시까지 내야 해.",
        "W: 버스 회사에 전화해 봤어?",
        "M: 선생님이 하셨어. 들어온 게 없대.",
        "W: 아직 시간 있어. 나올지도 몰라.",
        "M: 3주 동안 저녁을 다 썼는데 낼 게 하나도 없어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["M", "Excuse me, could you move up a little?"],
        ["W", "Of course, there's room here."],
        ["M", "Do you know when the next train comes?"],
        ["W", "In about five minutes."],
        ["M", "Excuse me, I think this is your glove."],
        ["W", "Oh, it must have fallen out of my pocket."],
        ["M", "How much is a ticket to the museum?"],
        ["W", "Eight dollars for students."],
        ["M", "Would you like me to carry that box?"],
        ["W", "Yes, thank you. It's heavier than it looks."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, I think this is your glove.",
      explanation:
        "그림은 길에서 한 사람이 떨어진 장갑을 주워 앞서 걷던 사람에게 건네려는 장면이므로 ③이 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "On a winter street. A woman is walking away with her hands in her coat pockets, and a single glove has fallen on the pavement behind her. A young man has picked the glove up and is holding it out toward her, calling to her. Both are drawn clearly. A shop front and a lamp post are in the background.",
      },
      translation: [
        "① M: 실례지만 조금만 옆으로 가 주시겠어요? / W: 그럼요, 여기 자리 있어요.",
        "② M: 다음 기차가 언제 오는지 아세요? / W: 5분쯤 뒤에요.",
        "③ M: 실례합니다, 이거 당신 장갑인 것 같아요. / W: 아, 주머니에서 떨어졌나 봐요.",
        "④ M: 박물관 표가 얼마예요? / W: 학생은 8달러입니다.",
        "⑤ M: 그 상자 제가 들어 드릴까요? / W: 네, 감사합니다. 보기보다 무겁네요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, do you still help in the library at lunch?"],
        ["W", "Every Monday and Wednesday. Why?"],
        ["M", "I need a book for my report and it's always out."],
        ["W", "Which one?"],
        ["M", "The one about Korean birds, the thick green one."],
        ["W", "I think it came back yesterday."],
        ["M", "Could you put it aside for me when you see it?"],
        ["W", "Sure. I'll keep it behind the desk with your name on it."],
        ["M", "Thank you. I'll come and borrow it on Wednesday."],
      ],
      choices: ["보고서 대신 써 주기", "책을 따로 빼 두기", "도서관 청소하기", "자료 찾아 주기", "자리 맡아 주기"],
      answer: 2,
      clue: "Could you put it aside for me when you see it?",
      explanation:
        "남자는 보고서에 필요한 책을 발견하면 따로 빼 두어 달라고 부탁한다. 따라서 답은 ②이다.",
      translation: [
        "M: 채원아, 점심시간에 아직 도서관 도우미 해?",
        "W: 월요일이랑 수요일마다. 왜?",
        "M: 보고서에 필요한 책이 있는데 늘 대출 중이야.",
        "W: 어떤 책인데?",
        "M: 한국의 새에 관한 책, 두꺼운 초록색 거.",
        "W: 어제 들어온 것 같은데.",
        "M: 보이면 나한테 따로 빼 줄 수 있어?",
        "W: 그래. 네 이름 적어서 데스크 뒤에 둘게.",
        "M: 고마워. 수요일에 가서 빌릴게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, School Photo Contest에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Let me tell you about the School Photo Contest."],
        ["M", "You may send in your photos until the twentieth of this month."],
        ["M", "This year's theme is one moment in our school day."],
        ["M", "Upload your files to the school website; you do not need to print them."],
        ["M", "Each student may send up to three photos."],
        ["M", "We look forward to seeing our school through your eyes."],
      ],
      choices: ["제출 마감일", "주제", "제출 방법", "제출 편수", "심사 기준"],
      answer: 5,
      clue: "Each student may send up to three photos.",
      explanation:
        "마감일(이달 20일), 주제(학교생활의 한 순간), 제출 방법(누리집 올리기), 제출 편수(세 장까지)는 언급되지만 심사 기준은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. School Photo Contest를 안내합니다.",
        "M: 이달 20일까지 사진을 낼 수 있습니다.",
        "M: 올해 주제는 우리 학교생활의 한 순간입니다.",
        "M: 학교 누리집에 파일을 올리면 됩니다. 인쇄할 필요는 없습니다.",
        "M: 학생마다 세 장까지 낼 수 있습니다.",
        "M: 여러분의 눈으로 본 우리 학교를 기다리겠습니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "You will find one of these in every classroom and office."],
        ["W", "It hangs on the wall and has a small door or a handle."],
        ["W", "Inside there is red powder or gas under pressure."],
        ["W", "You pull the pin and point the hose at the bottom of the flames."],
        ["W", "People check the date on it twice a year."],
      ],
      choices: ["소화기", "온풍기", "정수기", "청소기", "가습기"],
      answer: 1,
      clue: "You pull the pin and point the hose at the bottom of the flames.",
      explanation:
        "안전핀을 뽑고 호스를 불길 아래쪽에 겨눈다고 했으므로 소화기이다. 따라서 답은 ①이다.",
      translation: [
        "W: 이것은 모든 교실과 사무실에 하나씩 있습니다.",
        "W: 벽에 걸려 있고 작은 문이나 손잡이가 있습니다.",
        "W: 안에는 붉은 가루나 압축된 기체가 들어 있습니다.",
        "W: 안전핀을 뽑고 호스를 불길 아래쪽에 겨눕니다.",
        "W: 사람들은 1년에 두 번 날짜를 확인합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How long does the film run?"],
        ["W", "About two hours."],
        ["M", "Could you close the door, please?"],
        ["W", "Sure, it's noisy outside."],
        ["M", "Why are you carrying two bags today?"],
        ["W", "I have gym class this afternoon."],
        ["M", "What are you going to major in?"],
        ["W", "It's on the third floor."],
        ["M", "Have you finished the history project?"],
        ["W", "Almost. Just the last page left."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "What are you going to major in?",
      explanation:
        "무엇을 전공할 것인지 묻는 말에 3층에 있다는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 그 영화 몇 시간짜리야? / W: 두 시간쯤.",
        "② M: 문 좀 닫아 줄래? / W: 그래, 밖이 시끄럽네.",
        "③ M: 오늘은 왜 가방을 두 개 들었어? / W: 오후에 체육 수업이 있어.",
        "④ M: 너는 뭘 전공할 거야? / W: 그건 3층에 있어.",
        "⑤ M: 역사 과제 다 했어? / W: 거의. 마지막 쪽만 남았어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayeon, the parents are arriving in twenty minutes."],
        ["W", "Is the hall ready? What can I do?"],
        ["M", "I've put out the chairs and taped the signs to the doors."],
        ["W", "Should I make the name tags?"],
        ["M", "Jisu finished those during lunch."],
        ["W", "Then what's left?"],
        ["M", "The heater hasn't been turned on and the hall is freezing."],
        ["W", "I'll go and switch it on now."],
        ["M", "Thanks. I'll wait at the entrance to show people in."],
      ],
      choices: ["의자 놓기", "이름표 만들기", "안내문 붙이기", "난방 켜기", "손님 맞이하기"],
      answer: 4,
      clue: "I'll go and switch it on now.",
      explanation:
        "의자와 안내문, 이름표는 이미 끝났으므로 여자는 켜지지 않은 난방기를 켜러 간다. 따라서 답은 ④이다.",
      translation: [
        "M: 하연아, 학부모님들이 20분 뒤에 오셔.",
        "W: 강당은 준비됐어? 내가 뭘 할까?",
        "M: 의자는 놓았고 안내문도 문에 붙였어.",
        "W: 이름표를 만들까?",
        "M: 지수가 점심시간에 다 만들었어.",
        "W: 그럼 뭐가 남았어?",
        "M: 난방을 안 켜서 강당이 너무 추워.",
        "W: 내가 지금 가서 켤게.",
        "M: 고마워. 나는 입구에서 안내할게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 스터디룸을 고르시오.",
      lines: [
        ["W", "Jaeho, these are the five study rooms free on Saturday."],
        ["M", "Let's look. There are six of us in the group."],
        ["W", "Then the four-person room is out. That's one gone."],
        ["M", "Next, we need a whiteboard for the maths problems."],
        ["W", "One has no whiteboard, so that's out too."],
        ["M", "Three left. What do they cost an hour?"],
        ["W", "You said eight thousand won at the most."],
        ["M", "Then one more is gone. Two are left."],
        ["W", "Do they both open in the morning? We start at nine."],
        ["M", "Only one does. The other opens at one."],
        ["W", "Then that's the one. I'll book four hours."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Then that's the one. I'll book four hours.",
      explanation:
        "4인실인 ⑤, 화이트보드가 없는 ③, 시간당 10,000원인 ④를 뺀다. 남은 ①과 ② 중 오전에 여는 곳은 ②이므로 답은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "6인 / 화이트보드 있음 / 7,000원 / 오후 1시부터" },
          { no: 2, label: "②", value: "6인 / 화이트보드 있음 / 8,000원 / 오전 9시부터" },
          { no: 3, label: "③", value: "8인 / 화이트보드 없음 / 6,000원 / 오전 9시부터" },
          { no: 4, label: "④", value: "6인 / 화이트보드 있음 / 10,000원 / 오전 9시부터" },
          { no: 5, label: "⑤", value: "4인 / 화이트보드 있음 / 5,000원 / 오전 9시부터" },
        ],
      },
      translation: [
        "W: 재호야, 토요일에 비어 있는 스터디룸이 이 다섯 곳이야.",
        "M: 보자. 우리 모둠이 여섯 명이야.",
        "W: 그럼 4인실은 빠지네. 하나 빠졌어.",
        "M: 다음으로 수학 문제 풀 화이트보드가 있어야 해.",
        "W: 한 곳은 화이트보드가 없으니 그것도 빠져.",
        "M: 셋 남았다. 시간당 얼마야?",
        "W: 네가 8천 원까지라고 했잖아.",
        "M: 그럼 하나 더 빠진다. 둘 남았어.",
        "W: 둘 다 오전에 열어? 우리는 9시에 시작하잖아.",
        "M: 한 곳만. 다른 곳은 1시에 열어.",
        "W: 그럼 거기로 하자. 네 시간 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진을 찍으러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Seungho, when should we go and take the photos?"],
        ["M", "The garden is open to visitors on the fifth, sixth, and seventh."],
        ["W", "I have my cousin's graduation on the fifth."],
        ["M", "Then the sixth or the seventh."],
        ["W", "Isn't the seventh the day of the school health check?"],
        ["M", "You're right. We'd be in line all morning."],
        ["W", "So only the sixth is left."],
        ["M", "Let's go on the sixth, then. The light is best after four."],
      ],
      choices: ["4일", "5일", "6일", "7일", "8일"],
      answer: 3,
      clue: "So only the sixth is left.",
      explanation:
        "5일은 사촌 졸업식, 7일은 학교 건강 검진이어서 6일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "W: 승호야, 사진 찍으러 언제 갈까?",
        "M: 정원은 5일, 6일, 7일에 개방해.",
        "W: 나 5일에 사촌 졸업식이 있어.",
        "M: 그럼 6일이나 7일이네.",
        "W: 7일은 학교 건강 검진 날 아니야?",
        "M: 맞다. 오전 내내 줄 서 있겠다.",
        "W: 그럼 6일만 남네.",
        "M: 그럼 6일에 가자. 빛은 4시 넘어서가 제일 좋아.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Dayeon, did you go to the concert last weekend?"],
        ["W", "No, I took a cooking class with my mom on Sunday."],
        ["M", "A cooking class? What did you make?"],
        ["W", "Three kinds of pasta, all from scratch."],
        ["M", "From scratch? Even the noodles?"],
        ["W", "Even the noodles. My arms hurt from rolling them."],
        ["M", "Was it worth it?"],
        ["W", "Definitely. We made dinner with them that night."],
      ],
      choices: ["음악회 가기", "요리 수업 듣기", "자전거 타기", "등산하기", "영화 보기"],
      answer: 2,
      clue: "No, I took a cooking class with my mom on Sunday.",
      explanation:
        "여자는 지난 일요일에 어머니와 요리 수업을 들었다고 말한다. 따라서 답은 ②이다.",
      translation: [
        "M: 다연아, 지난 주말에 음악회 갔어?",
        "W: 아니, 일요일에 엄마랑 요리 수업 들었어.",
        "M: 요리 수업? 뭘 만들었는데?",
        "W: 파스타 세 가지, 전부 처음부터 만들었어.",
        "M: 처음부터? 면까지?",
        "W: 면까지. 밀느라 팔이 아팠어.",
        "M: 할 만했어?",
        "W: 당연하지. 그날 밤에 그걸로 저녁을 만들었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "The fire drill will take place during the fourth period today."],
        ["W", "When you hear the bell, leave the room in a line with your teacher."],
        ["W", "Do not go back for your bag or your phone."],
        ["W", "All classes gather on the playground by class number."],
        ["W", "The whole drill takes about fifteen minutes."],
        ["W", "Please take it seriously, even though it is only practice."],
      ],
      choices: [
        "체육대회 일정을 알리려고",
        "교실 청소를 당부하려고",
        "소방 훈련 방법을 안내하려고",
        "휴대전화 사용 규칙을 알리려고",
        "급식 시간을 안내하려고",
      ],
      answer: 3,
      clue: "The fire drill will take place during the fourth period today.",
      explanation:
        "오늘 4교시에 하는 소방 훈련의 절차를 안내하는 방송이다. 따라서 방송의 목적은 ③이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 오늘 4교시에 소방 훈련을 합니다.",
        "W: 종이 울리면 선생님과 함께 줄을 서서 교실을 나오세요.",
        "W: 가방이나 휴대전화를 가지러 돌아가지 마세요.",
        "W: 모든 반은 운동장에 반 번호대로 모입니다.",
        "W: 훈련 전체는 15분쯤 걸립니다.",
        "W: 연습이지만 진지하게 임해 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the art museum. How many tickets would you like?"],
        ["W", "Three student tickets, please."],
        ["M", "Student tickets are seven dollars each."],
        ["W", "So twenty-one dollars."],
        ["M", "That's right. Would you like the audio guide?"],
        ["W", "How much is it?"],
        ["M", "Three dollars per person."],
        ["W", "Then just one, for me."],
        ["M", "All right. And groups of three or more get four dollars off."],
        ["W", "Great. Here's my card."],
      ],
      choices: ["$18", "$20", "$21", "$24", "$27"],
      answer: 2,
      clue: "All right. And groups of three or more get four dollars off.",
      explanation:
        "학생 표 7달러씩 세 장은 21달러, 음성 안내 3달러를 더하면 24달러이다. 3인 이상 할인 4달러를 빼면 20달러이므로 답은 ②이다.",
      translation: [
        "M: 미술관입니다. 표 몇 장 드릴까요?",
        "W: 학생 표 세 장 주세요.",
        "M: 학생 표는 한 장에 7달러입니다.",
        "W: 그럼 21달러네요.",
        "M: 맞습니다. 음성 안내도 하시겠어요?",
        "W: 얼마예요?",
        "M: 한 사람에 3달러입니다.",
        "W: 그럼 저만 하나요.",
        "M: 알겠습니다. 그리고 3인 이상은 4달러 할인됩니다.",
        "W: 좋네요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Soyul, you've been staying after school every day this week."],
        ["W", "I'm learning the new dance for the festival."],
        ["M", "How is it going?"],
        ["W", "Badly. I always get lost in the middle part."],
        ["M", "How do you practise it?"],
        ["W", "I put the music on and dance the whole thing through."],
        ["M", "Then you only reach the middle when you're already tired."],
        ["W", "I never thought about that."],
        ["M", "Practise the middle eight counts alone, without the music."],
      ],
      choices: [
        "The festival is in three weeks.",
        "Then I'll work on the middle part alone tomorrow.",
        "I've been dancing since last year.",
        "The music is too fast for me.",
        "You should join the dance club too.",
      ],
      answer: 2,
      clue: "Practise the middle eight counts alone, without the music.",
      explanation:
        "가운데 여덟 박만 음악 없이 따로 연습하라는 조언을 들었으므로, 내일 그렇게 하겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 소율아, 이번 주 내내 방과 후에 남아 있네.",
        "W: 축제에서 출 새 춤을 배우고 있어.",
        "M: 잘돼 가?",
        "W: 아니. 가운데 부분에서 늘 놓쳐.",
        "M: 어떻게 연습하는데?",
        "W: 음악을 틀고 처음부터 끝까지 춰.",
        "M: 그럼 가운데에 닿을 때는 이미 지쳐 있겠네.",
        "W: 그 생각은 못 했어.",
        "M: 가운데 여덟 박만 음악 없이 따로 연습해 봐.",
        "W: 그럼 내일은 가운데 부분만 따로 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Dohyun, your English vocabulary test score dropped again."],
        ["M", "I study forty words every night. I don't know why."],
        ["W", "Forty in one sitting? How long does that take?"],
        ["M", "About twenty minutes. I read the list twice."],
        ["W", "Do you cover the meanings and test yourself?"],
        ["M", "No, I just read them over and over."],
        ["W", "Reading them is not the same as remembering them."],
        ["M", "So what should I do instead?"],
        ["W", "Cover the Korean side and say the meaning out loud."],
      ],
      choices: [
        "The test is every Friday morning.",
        "I have about four hundred words to learn.",
        "Then I'll cover the meanings tonight.",
        "My vocabulary book is quite thick.",
        "You should study with me sometime.",
      ],
      answer: 3,
      clue: "Cover the Korean side and say the meaning out loud.",
      explanation:
        "뜻을 가리고 소리 내어 말해 보라는 조언을 들었으므로, 오늘 밤에 그렇게 하겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 도현아, 영어 단어 시험 점수가 또 떨어졌네.",
        "M: 매일 밤 40개씩 외우는데 왜 그런지 모르겠어.",
        "W: 한 번에 40개를? 얼마나 걸려?",
        "M: 20분쯤. 목록을 두 번 읽어.",
        "W: 뜻을 가리고 스스로 시험해 봐?",
        "M: 아니, 그냥 계속 읽기만 해.",
        "W: 읽는 것과 외우는 건 달라.",
        "M: 그럼 어떻게 해야 해?",
        "W: 한국어 쪽을 가리고 뜻을 소리 내어 말해 봐.",
        "M: 그럼 오늘 밤에는 뜻을 가리고 해 볼게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Naeun, how is the class blog going?"],
        ["W", "Slowly. I posted twice this month."],
        ["M", "Only twice? You used to post every week."],
        ["W", "I know, but each post takes me three hours now."],
        ["M", "Three hours? What takes so long?"],
        ["W", "I rewrite it until every sentence sounds perfect."],
        ["M", "It's a class blog, not a newspaper."],
        ["W", "I suppose nobody reads it that closely."],
        ["M", "Set a timer for forty minutes and post whatever you have."],
      ],
      choices: [
        "The blog started in March.",
        "I write about our school trips.",
        "Then I'll try the timer this weekend.",
        "Nobody comments on my posts.",
        "You should write one instead.",
      ],
      answer: 3,
      clue: "Set a timer for forty minutes and post whatever you have.",
      explanation:
        "40분 타이머를 맞추고 그때까지 쓴 것을 올리라는 조언을 들었으므로, 이번 주말에 그렇게 해 보겠다는 ③이 가장 자연스럽다.",
      translation: [
        "M: 나은아, 학급 블로그는 잘돼 가?",
        "W: 천천히. 이번 달에 두 번 올렸어.",
        "M: 두 번밖에? 예전에는 매주 올렸잖아.",
        "W: 그러게, 그런데 이제 한 편에 세 시간이 걸려.",
        "M: 세 시간? 뭐가 그렇게 오래 걸려?",
        "W: 문장이 다 완벽해질 때까지 다시 써.",
        "M: 학급 블로그지 신문이 아니잖아.",
        "W: 아무도 그렇게 꼼꼼히 읽지는 않겠지.",
        "M: 40분 타이머를 맞추고 그때까지 쓴 걸 올려 봐.",
        "W: 그럼 이번 주말에 타이머를 써 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiwoo가 Sehun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Jiwoo : ________________",
      lines: [
        ["M", "Jiwoo and Sehun are in the same school band."],
        ["M", "They will play at the school festival next Friday."],
        ["M", "Sehun plays the keyboard very well and never misses a note."],
        ["M", "However, he looks down at his hands the whole time."],
        ["M", "Their teacher said the audience should be able to see their faces."],
        ["M", "The stage is high, so the audience looks up at them."],
        ["M", "Jiwoo does not want to say that his playing is bad."],
        ["M", "He wants to ask him to lift his head during the chorus."],
        ["M", "In this situation, what would Jiwoo most likely say to Sehun?"],
      ],
      choices: [
        "Let's choose an easier song for the festival.",
        "You should practise the keyboard more.",
        "I'll play the keyboard part instead.",
        "Try looking up during the chorus.",
        "We don't need a keyboard in this song.",
      ],
      answer: 4,
      clue: "He wants to ask him to lift his head during the chorus.",
      explanation:
        "지우는 세훈의 연주를 깎아내리지 않으면서, 후렴 부분에서는 고개를 들라고 말하려 한다. 따라서 ④가 가장 적절하다.",
      translation: [
        "M: 지우와 세훈은 같은 학교 밴드입니다.",
        "M: 두 사람은 다음 주 금요일 학교 축제에서 연주합니다.",
        "M: 세훈은 건반을 아주 잘 치고 음을 한 번도 놓치지 않습니다.",
        "M: 그런데 연주하는 내내 손만 내려다봅니다.",
        "M: 선생님은 관객이 얼굴을 볼 수 있어야 한다고 했습니다.",
        "M: 무대가 높아서 관객은 위를 올려다봅니다.",
        "M: 지우는 세훈의 연주가 나쁘다고 말하고 싶지는 않습니다.",
        "M: 다만 후렴 부분에서는 고개를 들어 달라고 부탁하고 싶습니다.",
        "M: 이런 상황에서 지우가 세훈에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
