/** 중3 듣기 32회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 32회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 안경테를 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for new glasses?"],
        ["M", "Yes, my old ones broke during basketball practice."],
        ["W", "Then a thick frame lasts much longer than a thin one."],
        ["M", "A thick frame it is. I can't keep breaking them."],
        ["W", "Do you prefer a round shape or a square one?"],
        ["M", "Round. Square frames look too serious on me."],
        ["W", "This round model has separate nose pads."],
        ["M", "No pads, please. They always leave marks."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "A thick frame it is. I can't keep breaking them. / Round. Square frames look too serious on me.",
      explanation:
        "남자는 둥근 모양에 테가 두껍고 코받침이 없는 안경을 골랐다. 따라서 답은 ②이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five pairs of eyeglass frames laid side by side as five choices, clean black line art on white. " +
          "① ROUND lenses with a THIN wire frame and no nose pads. " +
          "② ROUND lenses with a THICK heavy frame and no separate nose pads. " +
          "③ SQUARE lenses with a THIN wire frame. " +
          "④ SQUARE lenses with a THICK heavy frame. " +
          "⑤ ROUND lenses with a THICK frame and two small separate NOSE PADS on thin arms.",
      },
      translation: [
        "W: 안녕하세요. 새 안경 찾으세요?",
        "M: 네, 농구 연습하다가 예전 것이 부러졌어요.",
        "W: 그러면 얇은 테보다 두꺼운 테가 훨씬 오래가요.",
        "M: 두꺼운 테로 할게요. 계속 부러뜨릴 수는 없어요.",
        "W: 둥근 모양이 좋으세요, 네모난 모양이 좋으세요?",
        "M: 둥근 걸로요. 네모는 저한테 너무 딱딱해 보여요.",
        "W: 이 둥근 것은 코받침이 따로 달려 있어요.",
        "M: 코받침은 없는 걸로요. 자국이 남아요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 진로 박람회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hyerin, are you going to the career fair this month?"],
        ["W", "I want to. When is it being held?"],
        ["M", "On the third Saturday, from ten until four."],
        ["W", "Where does it take place?"],
        ["M", "At the city youth center near the station."],
        ["W", "How many booths will there be?"],
        ["M", "About thirty, one for each kind of job."],
        ["W", "Do we have to book a place in advance?"],
        ["M", "Yes, on the center's website by Thursday."],
      ],
      choices: [
        "박람회가 열리는 날",
        "박람회가 열리는 곳",
        "내야 하는 참가비",
        "설치되는 부스의 수",
        "미리 신청해야 하는지",
      ],
      answer: 3,
      clue: "On the third Saturday, from ten until four. / About thirty, one for each kind of job.",
      explanation:
        "날짜, 장소, 부스 수, 사전 신청은 말했지만 참가비는 말하지 않았다. 따라서 답은 ③이다.",
      translation: [
        "M: 혜린아, 이번 달 진로 박람회 갈 거야?",
        "W: 가고 싶어. 언제 열려?",
        "M: 셋째 주 토요일, 10시부터 4시까지.",
        "W: 어디서 해?",
        "M: 역 근처 시립 청소년 센터에서.",
        "W: 부스가 몇 개나 있어?",
        "M: 서른 개쯤. 직업마다 하나씩.",
        "W: 미리 신청해야 해?",
        "M: 응, 목요일까지 센터 누리집에서.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Junseo. It's Dahye. Are you at school tomorrow morning?"],
        ["M", "Yes, I always get there before eight."],
        ["W", "I have to leave my violin in the music room."],
        ["M", "Can't you take it home tonight?"],
        ["W", "It's too heavy for the bus with my other bags."],
        ["M", "So you want me to keep an eye on it?"],
        ["W", "Could you put it in the locked cabinet for me?"],
      ],
      choices: [
        "숙제를 물어보려고",
        "약속을 미루려고",
        "길을 물어보려고",
        "물건을 맡아 달라고 하려고",
        "생일을 축하하려고",
      ],
      answer: 4,
      clue: "Could you put it in the locked cabinet for me?",
      explanation:
        "여자는 바이올린을 잠금장이 있는 장에 넣어 맡아 달라고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 준서야. 다혜야. 내일 아침에 학교 있어?",
        "M: 응, 늘 8시 전에 도착해.",
        "W: 내 바이올린을 음악실에 두고 가야 해.",
        "M: 오늘 밤에 집에 못 가져가?",
        "W: 다른 가방까지 있어서 버스에 들고 타기엔 너무 무거워.",
        "M: 그럼 내가 봐 주면 되는 거야?",
        "W: 잠기는 장에 넣어 줄 수 있어?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Nayeon, when does the debate practice start?"],
        ["W", "The teacher opens the room at four o'clock."],
        ["M", "Do we need to move the desks into a circle first?"],
        ["W", "Yes, and that takes about fifteen minutes."],
        ["M", "Then we should be there by three forty-five."],
        ["W", "My science class ends at three forty."],
        ["M", "So three fifty would be safer for you."],
        ["W", "Let's say three fifty at the classroom door."],
        ["M", "Three fifty it is. I'll bring the question cards."],
      ],
      choices: ["3:40 p.m.", "3:45 p.m.", "4:00 p.m.", "4:15 p.m.", "3:50 p.m."],
      answer: 5,
      clue: "Let's say three fifty at the classroom door.",
      explanation:
        "여자의 수업이 3시 40분에 끝나 3시 50분에 만나기로 했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 나연아, 토론 연습 몇 시에 시작해?",
        "W: 선생님이 4시에 교실을 열어 주셔.",
        "M: 먼저 책상을 둥글게 놓아야 해?",
        "W: 응, 그게 15분쯤 걸려.",
        "M: 그럼 3시 45분까지는 가 있어야겠다.",
        "W: 내 과학 수업이 3시 40분에 끝나.",
        "M: 그럼 3시 50분이 너한테 더 안전하겠다.",
        "W: 3시 50분에 교실 문 앞에서 보자.",
        "M: 3시 50분으로 하자. 질문 카드는 내가 가져올게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Seongjin, did you find someone to fix your laptop?"],
        ["M", "My neighbor repaired it for free last night."],
        ["W", "The one who works at the computer shop?"],
        ["M", "Yes, and he stayed up until eleven for it."],
        ["W", "Did he ask you for anything at all?"],
        ["M", "He refused even the money my mother offered."],
        ["W", "That was really kind of him."],
        ["M", "I want to do something for him this weekend."],
      ],
      choices: ["grateful", "angry", "bored", "nervous", "jealous"],
      answer: 1,
      clue: "I want to do something for him this weekend.",
      explanation:
        "이웃이 무료로 노트북을 고쳐 주어 보답하고 싶다고 했으므로 고마워하는 심정이다. 따라서 답은 ①이다.",
      translation: [
        "W: 성진아, 노트북 고쳐 줄 사람 찾았어?",
        "M: 어젯밤에 이웃 아저씨가 무료로 고쳐 주셨어.",
        "W: 컴퓨터 가게에서 일하시는 그분?",
        "M: 응, 그것 때문에 11시까지 계셨어.",
        "W: 뭐 달라고 하신 것도 없어?",
        "M: 엄마가 드리려던 돈도 안 받으셨어.",
        "W: 정말 고마운 분이시네.",
        "M: 이번 주말에 뭐라도 해 드리고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Do you have a thermometer?"],
        ["M", "Yes, on the second shelf."],
        ["ANN", "Number two."],
        ["W", "What time do you close today?"],
        ["M", "At nine in the evening."],
        ["ANN", "Number three."],
        ["W", "Is this medicine for children?"],
        ["M", "No, this one is for adults."],
        ["ANN", "Number four."],
        ["W", "Here is my prescription."],
        ["M", "Please wait about five minutes."],
        ["ANN", "Number five."],
        ["W", "Can I pay with this card?"],
        ["M", "Yes, of course you can."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Here is my prescription.",
      explanation:
        "그림은 약국에서 여자가 처방전을 내밀고 약사가 받는 장면이다. 따라서 답은 ④이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a pharmacy, clean black line art on a plain white background, no writing anywhere. " +
          "A woman stands at the counter and holds out a folded blank slip of paper with one hand. " +
          "A pharmacist in a white coat takes the slip and gestures toward a row of chairs. " +
          "Shelves of plain unlabeled boxes and bottles are drawn behind the counter.",
      },
      translation: [
        "① W: 체온계 있나요? / M: 네, 둘째 칸에 있습니다.",
        "② W: 오늘 몇 시에 닫으세요? / M: 저녁 아홉 시에요.",
        "③ W: 이 약 어린이용인가요? / M: 아니요, 이건 어른용입니다.",
        "④ W: 여기 처방전이요. / M: 5분쯤 기다려 주세요.",
        "⑤ W: 이 카드로 계산해도 돼요? / M: 네, 물론입니다.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Chaewon, you won the speech contest last year, right?"],
        ["W", "I did, but that feels like a long time ago."],
        ["M", "I'm giving my speech in front of the grade on Friday."],
        ["W", "How far along is your script?"],
        ["M", "It's finished, but the middle part feels weak."],
        ["W", "The middle is where most people lose the audience."],
        ["M", "Could you read it through and tell me what to cut?"],
        ["W", "Sure, send it to me tonight."],
      ],
      choices: [
        "준비물을 빌려주기",
        "발표 원고를 봐 주기",
        "청소를 도와주기",
        "사진을 찍어 주기",
        "자리를 맡아 주기",
      ],
      answer: 2,
      clue: "Could you read it through and tell me what to cut?",
      explanation:
        "남자는 발표 원고를 읽고 무엇을 덜어 낼지 봐 달라고 부탁했다. 따라서 답은 ②이다.",
      translation: [
        "M: 채원아, 작년에 말하기 대회에서 1등 했지?",
        "W: 했는데 아주 오래전 일 같아.",
        "M: 금요일에 학년 앞에서 발표해야 해.",
        "W: 원고는 얼마나 됐어?",
        "M: 다 썼는데 중간 부분이 약한 것 같아.",
        "W: 중간에서 대부분 청중을 놓쳐.",
        "M: 한번 읽어 보고 뭘 덜어 낼지 말해 줄래?",
        "W: 그럼, 오늘 밤에 보내 줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학생 자치 예산 설명회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The student council will hold a budget meeting. " +
            "It takes place next Wednesday during the lunch break. " +
            "We will gather in the first floor meeting room. " +
            "We will explain how this term's money was actually spent. " +
            "Class leaders from every grade should attend.",
        ],
      ],
      choices: [
        "설명회가 열리는 날",
        "설명회가 열리는 장소",
        "설명회에서 다루는 내용",
        "참석해야 하는 사람",
        "의견을 내는 방법",
      ],
      answer: 5,
      clue: "It takes place next Wednesday during the lunch break.",
      explanation:
        "날짜, 장소, 내용, 참석 대상은 말했지만 의견을 내는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학생회에서 예산 설명회를 엽니다. 다음 주 수요일 점심시간에 진행합니다. 1층 회의실에 모입니다. 이번 학기 돈이 실제로 어떻게 쓰였는지 설명해 드립니다. 각 학년 반장들은 참석해 주시기 바랍니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a small strip of thin paper you get in a shop. " +
            "It lists what you bought and how much each item cost. " +
            "The total amount is printed at the bottom of it. " +
            "Keep it if you may want to return the item later. " +
            "The ink on it fades if you leave it in the sun.",
        ],
      ],
      choices: ["지갑", "통장", "영수증", "명함", "우표"],
      answer: 3,
      clue: "It lists what you bought and how much each item cost.",
      explanation:
        "가게에서 받는 종이로 산 물건과 값이 적혀 있고 환불할 때 필요한 것은 영수증이다. 따라서 답은 ③이다.",
      translation: [
        "M: 이것은 가게에서 받는 얇고 긴 종이입니다. 무엇을 샀는지와 각 물건의 값이 적혀 있습니다. 맨 아래에는 전체 금액이 찍혀 있습니다. 나중에 물건을 반품할 수도 있다면 보관하세요. 햇빛에 두면 글씨가 흐려집니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How long have you known him?"],
        ["M", "He lives on the fifth floor."],
        ["ANN", "Number two."],
        ["W", "Would you like to join our team?"],
        ["M", "I'd love to, thank you."],
        ["ANN", "Number three."],
        ["W", "What made you change your mind?"],
        ["M", "My sister's advice, actually."],
        ["ANN", "Number four."],
        ["W", "Could you speak a little louder?"],
        ["M", "Sorry, is this better?"],
        ["ANN", "Number five."],
        ["W", "When is the deadline?"],
        ["M", "Next Monday at noon."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "How long have you known him?",
      explanation:
        "얼마나 오래 알았는지 묻는 말에 5층에 산다고 답했으므로 ①의 대화가 어색하다. 따라서 답은 ①이다.",
      translation: [
        "① W: 그를 안 지 얼마나 됐어? / M: 5층에 살아.",
        "② W: 우리 팀에 들어올래? / M: 좋지, 고마워.",
        "③ W: 왜 마음을 바꿨어? / M: 사실 누나 조언 때문에.",
        "④ W: 조금 더 크게 말해 주시겠어요? / M: 죄송해요, 이제 괜찮나요?",
        "⑤ W: 마감이 언제야? / M: 다음 주 월요일 정오.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sujin, is that a lab coat in your locker?"],
        ["W", "Yes, I borrowed it for yesterday's experiment."],
        ["M", "The science teacher counted them this morning."],
        ["W", "Was one of them missing from the shelf?"],
        ["M", "Exactly one, and the next class needs it."],
        ["W", "Their lab starts right after lunch."],
        ["M", "You have about ten minutes left."],
        ["W", "I'll take it back to the science room now."],
      ],
      choices: [
        "도서관에 가기",
        "매점에 가기",
        "교실을 청소하기",
        "과학실에 실험복을 돌려주기",
        "집으로 돌아가기",
      ],
      answer: 4,
      clue: "I'll take it back to the science room now.",
      explanation:
        "여자는 지금 과학실에 실험복을 돌려주러 가겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 수진아, 네 사물함에 있는 게 실험복이야?",
        "W: 응, 어제 실험 때문에 빌렸어.",
        "M: 오늘 아침에 과학 선생님이 수를 세셨어.",
        "W: 선반에서 하나가 비었어?",
        "M: 딱 하나. 다음 수업에서 필요하대.",
        "W: 그 반 실험이 점심 끝나고 바로야.",
        "M: 10분쯤 남았어.",
        "W: 지금 과학실에 돌려주고 올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 신청할 여름 특강을 고르시오.",
      lines: [
        ["W", "Hyunwoo, which summer course are you going to take?"],
        ["M", "Let's look at these five on the printout."],
        ["W", "How many weeks can you attend?"],
        ["M", "Four weeks at the most. We travel in August."],
        ["W", "All right. Morning or afternoon?"],
        ["M", "Morning, because I work at the library later."],
        ["W", "And what about the fee?"],
        ["M", "Under a hundred and fifty thousand won."],
        ["W", "Then only one course here fits everything."],
        ["M", "Good. I'll register before it closes."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Four weeks at the most. We travel in August.",
      explanation:
        "4주 이하, 오전반, 15만 원 이하인 강좌를 고른다. 세 조건을 모두 채우는 것은 ②이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Weeks: 6 / Time: Morning / Fee: 140,000 won" },
          { no: 2, label: "②", value: "Weeks: 4 / Time: Morning / Fee: 135,000 won" },
          { no: 3, label: "③", value: "Weeks: 4 / Time: Afternoon / Fee: 120,000 won" },
          { no: 4, label: "④", value: "Weeks: 3 / Time: Morning / Fee: 180,000 won" },
          { no: 5, label: "⑤", value: "Weeks: 8 / Time: Afternoon / Fee: 100,000 won" },
        ],
      },
      translation: [
        "W: 현우야, 어떤 여름 특강 들을 거야?",
        "M: 유인물에 있는 다섯 개 보자.",
        "W: 몇 주나 다닐 수 있어?",
        "M: 최대 4주. 8월에 여행 가.",
        "W: 알겠어. 오전반이야, 오후반이야?",
        "M: 오전. 오후에는 도서관에서 일해.",
        "W: 수강료는?",
        "M: 15만 원 이하로.",
        "W: 그럼 여기서 다 맞는 건 하나뿐이야.",
        "M: 좋아. 마감 전에 등록할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 진로 상담을 받기로 한 날짜를 고르시오.",
      lines: [
        ["M", "Bomi, when can we see the career counselor?"],
        ["W", "She takes students on three days this month."],
        ["M", "Which days are open for us?"],
        ["W", "The sixth, the thirteenth and the twentieth."],
        ["M", "The sixth is our English speaking test."],
        ["W", "And I have a dental appointment on the thirteenth."],
        ["M", "Then the twentieth is the only day left."],
        ["W", "It's a Friday, so we finish class early."],
        ["M", "Let's book the twentieth this afternoon."],
      ],
      choices: [
        "the 6th",
        "the 10th",
        "the 13th",
        "the 16th",
        "the 20th",
      ],
      answer: 5,
      clue: "Then the twentieth is the only day left.",
      explanation:
        "6일은 시험, 13일은 치과 예약이어서 20일로 정했다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 보미야, 진로 상담 언제 받을 수 있어?",
        "W: 선생님이 이번 달에 사흘 학생을 받으셔.",
        "M: 어떤 날이 열려 있어?",
        "W: 6일, 13일, 20일.",
        "M: 6일은 영어 말하기 시험이야.",
        "W: 그리고 13일에는 치과 예약이 있어.",
        "M: 그럼 남는 건 20일뿐이네.",
        "W: 금요일이라 수업도 일찍 끝나.",
        "M: 오늘 오후에 20일로 예약하자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Yerim, did you go anywhere fun on Saturday?"],
        ["W", "I ran a booth at the neighborhood festival."],
        ["M", "What did your booth do?"],
        ["W", "We taught children how to fold paper animals."],
        ["M", "How many children came to your table?"],
        ["W", "More than sixty, and we ran out of paper."],
        ["M", "Did you do it alone?"],
        ["W", "Three of us from the art club took turns."],
      ],
      choices: [
        "영화를 보러 가기",
        "병원에 다녀오기",
        "동네 축제에서 부스를 운영하기",
        "가족과 여행을 가기",
        "도서관에서 공부하기",
      ],
      answer: 3,
      clue: "I ran a booth at the neighborhood festival.",
      explanation:
        "여자는 토요일에 동네 축제에서 종이접기 부스를 운영했다. 따라서 답은 ③이다.",
      translation: [
        "M: 예림아, 토요일에 재미있는 데 갔어?",
        "W: 동네 축제에서 부스를 맡았어.",
        "M: 무슨 부스였는데?",
        "W: 아이들에게 종이로 동물 접는 걸 가르쳤어.",
        "M: 몇 명이나 왔어?",
        "W: 예순 명 넘게. 종이가 다 떨어졌어.",
        "M: 혼자 했어?",
        "W: 미술 동아리에서 셋이 번갈아 했어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, third year students. This is the career room. " +
            "Personal counseling for this term opens from next Monday. " +
            "Each session lasts thirty minutes after the sixth period. " +
            "Write your name and your class on the sheet by our door. " +
            "Bring any questions about high schools or jobs with you. " +
            "We look forward to meeting each of you.",
        ],
      ],
      choices: [
        "진로 상담 신청을 안내하려고",
        "분실물을 찾아가라고",
        "안전 규칙을 안내하려고",
        "행사 취소를 알리려고",
        "청소를 부탁하려고",
      ],
      answer: 1,
      clue: "Personal counseling for this term opens from next Monday.",
      explanation:
        "다음 주부터 진로 상담 신청을 받는다고 안내하는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 3학년 학생 여러분께 알려 드립니다. 진로실입니다. 이번 학기 개인 상담을 다음 주 월요일부터 시작합니다. 한 번에 삼십 분씩, 6교시가 끝난 뒤에 진행합니다. 진로실 문 옆 종이에 이름과 반을 적어 주세요. 고등학교나 직업에 대한 질문을 가지고 오세요. 한 사람 한 사람 만나 뵙기를 기다리겠습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you buying tickets for the musical?"],
        ["M", "Yes, three student tickets, please."],
        ["W", "A student ticket is twelve dollars each."],
        ["M", "Do we have to pay for the program?"],
        ["W", "The program costs four dollars."],
        ["M", "We'll take one program for the three of us."],
        ["W", "There is no other charge today."],
        ["M", "All right. Here is my card."],
      ],
      choices: ["$36", "$44", "$48", "$38", "$40"],
      answer: 5,
      clue: "A student ticket is twelve dollars each. / The program costs four dollars.",
      explanation:
        "학생 표 세 장 36달러에 안내 책자 4달러를 더하면 40달러이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요. 뮤지컬 표 사시나요?",
        "M: 네, 학생 표 세 장 주세요.",
        "W: 학생 표는 한 장에 12달러입니다.",
        "M: 안내 책자도 돈을 내야 하나요?",
        "W: 안내 책자는 4달러입니다.",
        "M: 셋이서 한 권만 살게요.",
        "W: 오늘 다른 요금은 없습니다.",
        "M: 알겠습니다. 여기 카드요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Chaeyeon, you finished all your applications early."],
        ["W", "I wrote down every deadline on one sheet."],
        ["M", "Just one sheet for everything?"],
        ["W", "Yes, and I keep it inside my pencil case."],
        ["M", "I have deadlines in three different apps."],
        ["W", "Then you have to open three apps to check."],
        ["M", "And I still forgot the science one last week."],
        ["W", "One place beats three places every time."],
        ["M", "Could you show me how you set yours up?"],
      ],
      choices: [
        "I don't use any sheet.",
        "You should use more apps.",
        "Sure, bring your case tomorrow.",
        "I missed every deadline.",
        "The applications are closed.",
      ],
      answer: 3,
      clue: "Could you show me how you set yours up?",
      explanation:
        "남자가 정리하는 법을 보여 달라고 했으므로, 내일 필통을 가져오라는 ③이 가장 자연스럽다.",
      translation: [
        "M: 채연아, 너는 신청서를 다 일찍 끝냈더라.",
        "W: 마감일을 종이 한 장에 다 적어 뒀어.",
        "M: 전부 한 장에?",
        "W: 응, 그리고 필통 안에 넣고 다녀.",
        "M: 나는 마감이 앱 세 개에 흩어져 있어.",
        "W: 그럼 확인하려면 앱을 세 개 열어야 하잖아.",
        "M: 그러고도 지난주에 과학 것을 잊었어.",
        "W: 한 군데가 세 군데보다 늘 나아.",
        "M: 어떻게 정리하는지 보여 줄래?",
        "W: 그럼, 내일 필통 가져와.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Junho, are you still tutoring at the community center?"],
        ["M", "Every Saturday morning, for two hours."],
        ["W", "What subject do you teach there?"],
        ["M", "Basic English to fourth and fifth graders."],
        ["W", "Is it hard to explain things to younger children?"],
        ["M", "At first, yes. Now I draw pictures instead of talking."],
        ["W", "That sounds like a good way to teach."],
        ["M", "They remember the pictures much longer."],
        ["W", "Do you need one more helper next month?"],
      ],
      choices: [
        "Yes, please come with me.",
        "I stopped teaching last year.",
        "The center is closed now.",
        "I teach only on Sundays.",
        "Nobody comes to my class.",
      ],
      answer: 1,
      clue: "Do you need one more helper next month?",
      explanation:
        "여자가 다음 달에 도우미가 필요한지 물었으므로, 함께 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 준호야, 아직 주민 센터에서 가르쳐?",
        "M: 매주 토요일 아침에 두 시간씩.",
        "W: 무슨 과목을 가르쳐?",
        "M: 4, 5학년에게 기초 영어.",
        "W: 어린 아이들에게 설명하는 게 어렵지 않아?",
        "M: 처음엔 어려웠어. 지금은 말 대신 그림을 그려.",
        "W: 좋은 방법 같다.",
        "M: 아이들이 그림을 훨씬 오래 기억해.",
        "W: 다음 달에 도우미 한 명 더 필요해?",
        "M: 응, 같이 가자.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Dain, how is your English reading going these days?"],
        ["W", "Slowly. I look up almost every word."],
        ["M", "Do you stop at each unknown word?"],
        ["W", "Yes, otherwise I feel like I'm missing something."],
        ["M", "Then you never reach the end of the passage."],
        ["W", "That's true. I usually stop after one page."],
        ["M", "Try reading a whole page without stopping first."],
        ["W", "Even if I don't understand some parts?"],
        ["M", "Yes, then look up only the words that matter."],
      ],
      choices: [
        "I already read that way.",
        "All right, I'll try it tonight.",
        "I understand every word.",
        "You should look up more words.",
        "I don't read in English.",
      ],
      answer: 2,
      clue: "Yes, then look up only the words that matter.",
      explanation:
        "먼저 한 쪽을 끝까지 읽고 중요한 낱말만 찾으라는 제안이므로, 오늘 밤 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 다인아, 요즘 영어 읽기는 어때?",
        "W: 더뎌. 거의 모든 단어를 찾아봐.",
        "M: 모르는 단어마다 멈춰?",
        "W: 응, 안 그러면 뭔가 놓치는 것 같아.",
        "M: 그러면 지문 끝까지 못 가잖아.",
        "W: 맞아. 보통 한 쪽 읽고 멈춰.",
        "M: 먼저 한 쪽을 멈추지 말고 끝까지 읽어 봐.",
        "W: 이해 안 되는 부분이 있어도?",
        "M: 응, 그런 다음 중요한 단어만 찾아봐.",
        "W: 알겠어, 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Seungho가 Nari에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Seungho : ________________",
      lines: [
        [
          "M",
          "Seungho and Nari are preparing a presentation in the computer room. " +
            "Nari finishes the last slide and reaches for the power switch. " +
            "Seungho sees that the file has not been saved to the shared folder. " +
            "If the computer shuts down now, all their slides will disappear. " +
            "He wants to stop her before she presses the switch. " +
            "In this situation, what would Seungho most likely say to Nari?",
        ],
      ],
      choices: [
        "The presentation is next Friday.",
        "Can you print the slides for me?",
        "Let's add one more picture here.",
        "Wait, we haven't saved the file.",
        "You should turn off the monitor.",
      ],
      answer: 4,
      clue: "He wants to stop her before she presses the switch.",
      explanation:
        "저장하지 않은 채 컴퓨터를 끄려 하므로, 아직 저장하지 않았다고 말리는 ④가 가장 적절하다.",
      translation: [
        "M: 승호와 나리는 컴퓨터실에서 발표를 준비하고 있습니다. 나리가 마지막 장을 끝내고 전원 스위치로 손을 뻗습니다. 승호는 파일이 공유 폴더에 저장되지 않은 것을 봅니다. 지금 컴퓨터가 꺼지면 만든 장이 모두 사라집니다. 승호는 나리가 스위치를 누르기 전에 말리고 싶습니다. 이런 상황에서 승호가 나리에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
