/** 중3 듣기 24회 — 사람이 직접 쓴 회차 (2026-09-24) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 24회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 책상 정리함을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for a desk organizer?"],
        ["W", "Yes, something for my pens and small tools."],
        ["M", "We have organizers with open slots and ones with a lid."],
        ["W", "Open slots, please. A lid slows me down."],
        ["M", "All right. This open one is round and spins."],
        ["W", "A spinning one slides when I reach for a pen."],
        ["M", "Then here is a square open organizer that stays put."],
        ["W", "That's the one. I'll take the square open one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Open slots, please. / I'll take the square open one.",
      explanation:
        "여자는 뚜껑이 없는 정리함을 원하고, 돌아가는 둥근 것 대신 네모난 것을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five empty desk organizers drawn side by side as five choices, clean black line art on white. " +
          "① a ROUND organizer with a hinged LID closed on top. " +
          "② a SQUARE organizer with a hinged LID closed on top. " +
          "③ a ROUND organizer with OPEN SLOTS and no lid, sitting on a small round turning base. " +
          "④ a SQUARE organizer with OPEN SLOTS and no lid and a flat bottom. " +
          "⑤ a ROUND organizer with OPEN SLOTS and no lid and a small DRAWER underneath.",
      },
      translation: [
        "M: 안녕하세요. 책상 정리함 찾으세요?",
        "W: 네, 펜이랑 작은 도구 넣을 거예요.",
        "M: 칸이 열린 것도 있고 뚜껑이 있는 것도 있어요.",
        "W: 열린 걸로 주세요. 뚜껑이 있으면 느려져요.",
        "M: 알겠습니다. 이 열린 정리함은 둥글고 돌아가요.",
        "W: 돌아가는 건 펜을 집을 때 미끄러져요.",
        "M: 그럼 제자리에 있는 네모난 열린 정리함이 여기 있어요.",
        "W: 그거예요. 네모난 열린 걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 체육 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Eunbi, is our class ready for the sports day?"],
        ["W", "Almost. It's on the second Friday of next month."],
        ["M", "Where will the events be held?"],
        ["W", "On the main field, and in the gym if it rains."],
        ["M", "Which events does our class enter?"],
        ["W", "The relay, the tug of war, and the jump rope race."],
        ["M", "Do we need matching shirts?"],
        ["W", "Yes, each class wears its own color."],
        ["M", "Then I'll ask what color we got."],
      ],
      choices: ["우승 상품", "열리는 날", "열리는 장소", "참가 종목", "복장"],
      answer: 1,
      clue: "우승 상품은 대화에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 달 둘째 금요일), 장소(운동장과 체육관), 참가 종목(이어달리기·줄다리기·줄넘기), 복장(반별 색 티셔츠)은 언급되지만 우승 상품은 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "M: 은비야, 우리 반 체육 대회 준비 다 됐어?",
        "W: 거의. 다음 달 둘째 금요일이야.",
        "M: 종목은 어디서 해?",
        "W: 운동장에서, 비 오면 체육관에서.",
        "M: 우리 반은 어떤 종목에 나가?",
        "W: 이어달리기, 줄다리기, 줄넘기 경주.",
        "M: 맞춰 입는 옷이 있어?",
        "W: 응, 반마다 색이 달라.",
        "M: 그럼 우리 반 색이 뭔지 물어봐야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Miral Science Museum?"],
        ["W", "Yes, it is. How may I help you?"],
        ["M", "Our class booked a tour for next Wednesday."],
        ["W", "Let me check. Under Mirae Middle School?"],
        ["M", "That's right. We have five more students than planned."],
        ["W", "How many will be coming in total?"],
        ["M", "Thirty-five, including two teachers."],
        ["W", "No problem. I've updated the number for you."],
      ],
      choices: [
        "견학을 처음 예약하려고",
        "견학을 취소하려고",
        "입장료를 물어보려고",
        "견학 인원을 늘리려고",
        "박물관 위치를 물어보려고",
      ],
      answer: 4,
      clue: "That's right. We have five more students than planned.",
      explanation:
        "남자는 예정보다 다섯 명이 늘어 견학 인원을 고치려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "M: 여보세요, 미랄 과학관이죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 저희 반이 다음 주 수요일 견학을 예약했어요.",
        "W: 확인해 볼게요. 미래중학교죠?",
        "M: 맞아요. 학생이 예정보다 다섯 명 늘었어요.",
        "W: 모두 몇 분이 오시나요?",
        "M: 선생님 두 분 포함해서 서른다섯 명이요.",
        "W: 문제없습니다. 인원을 고쳐 두었습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Taemin, what time does the movie start on Saturday?"],
        ["M", "The screening begins at three in the afternoon."],
        ["W", "Do we have to collect the tickets at the counter?"],
        ["M", "Yes, and the counter line is long on weekends."],
        ["W", "How much time should we leave for it?"],
        ["M", "Half an hour, based on what happened last time."],
        ["W", "Then let's meet half an hour before the screening."],
        ["M", "Good. I'll stand by the poster wall."],
        ["W", "See you there on Saturday."],
      ],
      choices: ["2:00 p.m.", "2:30 p.m.", "3:00 p.m.", "3:30 p.m.", "4:00 p.m."],
      answer: 2,
      clue: "Then let's meet half an hour before the screening.",
      explanation:
        "상영이 3시에 시작하고 30분 전에 만나기로 했으므로 만나는 시각은 2시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "W: 태민아, 토요일에 영화 몇 시에 시작해?",
        "M: 상영이 오후 3시에 시작해.",
        "W: 표는 창구에서 받아야 해?",
        "M: 응, 주말엔 창구 줄이 길어.",
        "W: 그걸 위해 시간을 얼마나 잡아야 해?",
        "M: 지난번 봐서는 30분.",
        "W: 그럼 상영 30분 전에 만나자.",
        "M: 좋아. 나는 포스터 벽 앞에 서 있을게.",
        "W: 토요일에 거기서 봐.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunbi, you've been holding that phone for five minutes."],
        ["W", "The regional contest results came out just now."],
        ["M", "Your essay, the one about your grandmother?"],
        ["W", "Yes, and I got second place out of two hundred."],
        ["M", "Second place in the whole region? That's huge."],
        ["W", "I almost didn't enter because I thought it was too personal."],
        ["M", "Aren't you glad you sent it in?"],
        ["W", "I want to call my grandmother right this minute."],
      ],
      choices: ["bored", "angry", "worried", "sleepy", "delighted"],
      answer: 5,
      clue: "I want to call my grandmother right this minute.",
      explanation:
        "200편 중 2등을 했고 지금 당장 할머니께 전화하고 싶다고 했으므로 여자의 심정은 '기쁜(delighted)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 은비야, 그 휴대폰을 5분째 들고 있네.",
        "W: 지역 대회 결과가 방금 나왔어.",
        "M: 할머니에 대해 쓴 그 글?",
        "W: 응, 200편 중에 2등이래.",
        "M: 지역 전체에서 2등? 대단하다.",
        "W: 너무 개인적인 이야기 같아서 안 낼 뻔했어.",
        "M: 내길 잘했지?",
        "W: 지금 당장 할머니께 전화하고 싶어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much are these apples?"],
        ["M", "Four dollars for six."],
        ["ANN", "Number two."],
        ["W", "Do you have a smaller size?"],
        ["M", "Let me look in the back."],
        ["ANN", "Number three."],
        ["W", "Can I pay with this card?"],
        ["M", "Yes, we take all cards."],
        ["ANN", "Number four."],
        ["W", "What time do you close today?"],
        ["M", "At nine in the evening."],
        ["ANN", "Number five."],
        ["W", "Excuse me, your shopping bag has a hole."],
        ["M", "Oh, thank you. I'll get another one."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Excuse me, your shopping bag has a hole.",
      explanation:
        "그림은 가게 앞에서 남자가 든 장바구니 바닥의 구멍으로 과일이 떨어지고, 여자가 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ⑤이다.",
      figure: {
        kind: "scene",
        scene:
          "Outside a small grocery store, clean black line art on a plain white background, no writing anywhere. " +
          "A man is walking away holding a paper shopping bag, and two round fruits are falling through a torn hole in the bottom of the bag. " +
          "A woman behind him points at the torn bag with a surprised face and calls out to him. " +
          "A store window with crates of vegetables is drawn simply in the background.",
      },
      translation: [
        "① W: 이 사과 얼마예요? / M: 여섯 개에 4달러입니다.",
        "② W: 더 작은 치수 있나요? / M: 뒤쪽에서 찾아볼게요.",
        "③ W: 이 카드로 계산해도 되나요? / M: 네, 모든 카드 받습니다.",
        "④ W: 오늘 몇 시에 닫아요? / M: 저녁 9시에요.",
        "⑤ W: 저기요, 장바구니에 구멍이 났어요. / M: 아, 감사합니다. 다른 걸로 받을게요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunbi, you're in the broadcasting club, aren't you?"],
        ["W", "Yes, I run the sound board on Fridays."],
        ["M", "Our class made a short radio drama for the festival."],
        ["W", "Did you record it in the classroom?"],
        ["M", "We did, and there's a humming noise all the way through."],
        ["W", "That's usually the fan in the ceiling."],
        ["M", "Could you clean up the sound with your equipment?"],
        ["W", "Sure. Send me the file and I'll do it Friday."],
      ],
      choices: ["소리 다듬어 주기", "다시 녹음해 주기", "방송실 빌려주기", "대본 써 주기", "장비 사 오기"],
      answer: 1,
      clue: "Could you clean up the sound with your equipment?",
      explanation:
        "남자는 잡음이 섞인 녹음 파일의 소리를 장비로 다듬어 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 은비야, 너 방송 동아리지?",
        "W: 응, 금요일마다 음향 조절을 맡아.",
        "M: 우리 반이 축제에 낼 짧은 라디오 드라마를 만들었어.",
        "W: 교실에서 녹음했어?",
        "M: 응, 그런데 처음부터 끝까지 웅웅거리는 소리가 들어갔어.",
        "W: 그건 보통 천장 환풍기 소리야.",
        "M: 네 장비로 소리 좀 다듬어 줄 수 있어?",
        "W: 그럼. 파일 보내 주면 금요일에 할게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 독서 토론회에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. The reading discussion club starts next week. " +
            "We meet every Wednesday during the lunch break. " +
            "The meetings are held in the small room beside the library. " +
            "This term we will read three novels, one each month. " +
            "Bring your own copy, or borrow one from the library shelf. " +
            "Anyone in any grade is welcome to join us.",
        ],
      ],
      choices: ["모이는 요일", "모이는 장소", "읽을 책의 수", "회원 수 제한", "책을 구하는 방법"],
      answer: 4,
      clue: "회원 수 제한은 방송에서 언급되지 않았다.",
      explanation:
        "모이는 요일(수요일 점심시간), 장소(도서관 옆 작은 방), 읽을 책의 수(소설 세 권), 책을 구하는 방법(개인 책 또는 도서관)은 언급되지만 회원 수 제한은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 독서 토론 동아리가 다음 주에 시작합니다. 매주 수요일 점심시간에 모입니다. 모임은 도서관 옆 작은 방에서 열립니다. 이번 학기에는 한 달에 한 권씩 소설 세 권을 읽습니다. 자기 책을 가져오거나 도서관 서가에서 빌리면 됩니다. 학년에 관계없이 누구나 환영합니다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a job you meet at the front of every classroom. " +
            "The person writes on the board and asks the class questions. " +
            "They mark your papers at night and write comments in red. " +
            "At the end of the year they write a short note about each student. " +
            "Many of them say they learn as much as they teach.",
        ],
      ],
      choices: ["사서", "교사", "상담사", "기자", "작가"],
      answer: 2,
      clue: "They mark your papers at night and write comments in red.",
      explanation:
        "교실 앞에서 칠판에 쓰고 질문하며 밤에 시험지를 채점하고 학년 말에 학생 기록을 쓰는 사람은 교사이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이 직업은 모든 교실 앞에서 만납니다. 이 사람은 칠판에 쓰고 학생들에게 질문을 합니다. 밤에는 시험지를 채점하고 빨간 펜으로 의견을 적습니다. 학년이 끝날 때는 학생마다 짧은 기록을 씁니다. 많은 이들이 가르치는 만큼 배운다고 말합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How was the field trip yesterday?"],
        ["W", "The museum was better than I expected."],
        ["ANN", "Number two."],
        ["M", "Could you keep my seat for a minute?"],
        ["W", "Sure, take your time."],
        ["ANN", "Number three."],
        ["M", "Which team won the match?"],
        ["W", "Ours did, by one point."],
        ["ANN", "Number four."],
        ["M", "Are you free this weekend?"],
        ["W", "I have plans on Saturday only."],
        ["ANN", "Number five."],
        ["M", "How much does the ticket cost?"],
        ["W", "I moved here three years ago."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "How much does the ticket cost?",
      explanation:
        "표가 얼마인지 묻는 말에 3년 전에 이사 왔다고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 어제 현장 학습 어땠어? / W: 박물관이 생각보다 좋았어.",
        "② M: 내 자리 잠깐만 맡아 줄래? / W: 그럼, 천천히 다녀와.",
        "③ M: 어느 팀이 이겼어? / W: 우리가 1점 차로 이겼어.",
        "④ M: 이번 주말에 시간 있어? / W: 토요일만 약속이 있어.",
        "⑤ M: 표가 얼마야? / W: 나는 3년 전에 이사 왔어.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Taemin, the club exhibition opens in twenty minutes."],
        ["M", "I know. Are all the panels standing straight?"],
        ["W", "Yes, I checked every one of them this morning."],
        ["M", "Good. Did you put the visitor book on the table?"],
        ["W", "I did, but there's no pen next to it."],
        ["M", "Without a pen nobody can leave a comment."],
        ["W", "I have to guide the first group from the gate."],
        ["M", "Then I'll get a pen from the club room and put it there."],
      ],
      choices: ["패널 세우기", "방명록 놓기", "펜 가져다 놓기", "손님 안내하기", "탁자 옮기기"],
      answer: 3,
      clue: "Then I'll get a pen from the club room and put it there.",
      explanation:
        "방명록 옆에 펜이 없고 여자는 손님을 안내해야 해서, 남자가 동아리방에서 펜을 가져다 놓겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 동아리 전시가 20분 뒤에 열려.",
        "M: 알아. 패널은 다 똑바로 서 있어?",
        "W: 응, 오늘 아침에 하나하나 확인했어.",
        "M: 잘했다. 탁자에 방명록은 놨어?",
        "W: 놨는데, 옆에 펜이 없어.",
        "M: 펜이 없으면 아무도 글을 남길 수 없어.",
        "W: 나는 정문에서 첫 무리를 안내해야 해.",
        "M: 그럼 내가 동아리방에서 펜 가져다 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 스터디룸을 고르시오.",
      lines: [
        ["W", "Taemin, which study room are you booking for the group?"],
        ["M", "Let me look at the five of them again."],
        ["W", "How many people are studying together?"],
        ["M", "Seven, so a room for four is too small."],
        ["W", "Okay. Do you need a whiteboard in the room?"],
        ["M", "Yes, we solve math problems on the board."],
        ["W", "Got it. What about the hourly fee?"],
        ["M", "Under eight thousand won an hour, split seven ways."],
        ["W", "Then only one room on this list works."],
        ["M", "Good. I'll book it right after school."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Seven, so a room for four is too small.",
      explanation:
        "7명 이상이 들어가고, 화이트보드가 있으며, 시간당 8천 원 미만인 방을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Seats: 10 / Board: Yes / Fee: 7,500 won" },
          { no: 2, label: "②", value: "Seats: 4 / Board: Yes / Fee: 6,000 won" },
          { no: 3, label: "③", value: "Seats: 8 / Board: No / Fee: 5,000 won" },
          { no: 4, label: "④", value: "Seats: 8 / Board: Yes / Fee: 10,000 won" },
          { no: 5, label: "⑤", value: "Seats: 4 / Board: No / Fee: 4,000 won" },
        ],
      },
      translation: [
        "W: 태민아, 모임에 쓸 스터디룸 어디로 예약할 거야?",
        "M: 다섯 개 다시 볼게.",
        "W: 몇 명이 같이 공부해?",
        "M: 일곱 명이라 4인실은 너무 작아.",
        "W: 알겠어. 방에 화이트보드가 필요해?",
        "M: 응, 칠판에 수학 문제를 풀어.",
        "W: 그렇구나. 시간당 요금은?",
        "M: 일곱이 나누니까 시간당 8천 원 미만.",
        "W: 그럼 이 목록에서 되는 건 하나뿐이야.",
        "M: 좋아. 방과 후에 바로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진전을 보러 갈 날짜를 고르시오.",
      lines: [
        ["W", "Taemin, when can we see the photo exhibition?"],
        ["M", "How about July 4th? That's next Saturday."],
        ["W", "I have my English speaking test that morning."],
        ["M", "Then what about July 7th?"],
        ["W", "The gallery is closed every first Tuesday."],
        ["M", "Hmm. I'm free on July 15th."],
        ["W", "But the exhibition closes on the 12th."],
        ["M", "Oh, right. Then let's go on July 11th."],
        ["W", "July 11th works. It's a Saturday, and I'm free all day."],
        ["M", "Great. Let's meet at the subway exit at ten."],
      ],
      choices: ["7월 4일", "7월 7일", "7월 12일", "7월 11일", "7월 15일"],
      answer: 4,
      clue: "Oh, right. Then let's go on July 11th.",
      explanation:
        "4일에는 영어 말하기 시험이, 7일에는 휴관이 있고 전시는 12일에 끝난다. 두 사람은 7월 11일에 가기로 한다. 따라서 답은 ④이다.",
      translation: [
        "W: 태민아, 사진전 언제 보러 갈까?",
        "M: 7월 4일 어때? 다음 주 토요일이야.",
        "W: 그날 오전에 영어 말하기 시험이 있어.",
        "M: 그럼 7월 7일은?",
        "W: 갤러리는 첫째 화요일마다 문을 닫아.",
        "M: 음. 나는 7월 15일이 비어.",
        "W: 그런데 전시가 12일에 끝나.",
        "M: 아, 맞다. 그럼 7월 11일에 가자.",
        "W: 7월 11일 괜찮아. 토요일이라 하루 종일 비어.",
        "M: 좋아. 10시에 지하철 출구에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Eunbi, your hands look rough today."],
        ["W", "I was at the community garden all Sunday."],
        ["M", "Did you plant something there?"],
        ["W", "No, we built a wooden fence around the beds."],
        ["M", "A fence? How long did it take?"],
        ["W", "Six hours, and we used more than a hundred nails."],
        ["M", "Why did the garden need a fence?"],
        ["W", "To keep the stray cats off the young plants."],
      ],
      choices: ["꽃 심기", "울타리 만들기", "고양이 돌보기", "밭 갈기", "정원 청소하기"],
      answer: 2,
      clue: "No, we built a wooden fence around the beds.",
      explanation:
        "여자는 일요일에 마을 텃밭에 나무 울타리를 여섯 시간 동안 만들었다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 은비야, 오늘 손이 거칠어 보여.",
        "W: 일요일 내내 마을 텃밭에 있었어.",
        "M: 거기에 뭘 심었어?",
        "W: 아니, 밭 둘레에 나무 울타리를 만들었어.",
        "M: 울타리? 얼마나 걸렸어?",
        "W: 여섯 시간. 못을 백 개 넘게 썼어.",
        "M: 텃밭에 울타리가 왜 필요했어?",
        "W: 길고양이가 어린 식물에 못 오게 하려고.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is the school health office. " +
            "Flu cases have risen sharply in our school this week. " +
            "Please wash your hands with soap before and after every meal. " +
            "If you have a fever, go straight home and rest. " +
            "Do not share cups, towels, or water bottles with anyone. " +
            "Stay healthy, and take care of each other.",
        ],
      ],
      choices: [
        "예방 접종을 안내하려고",
        "보건실 이전을 알리려고",
        "결석 신고 방법을 알리려고",
        "건강 검진 일정을 알리려고",
        "감기 예방을 당부하려고",
      ],
      answer: 5,
      clue: "Please wash your hands with soap before and after every meal.",
      explanation:
        "독감이 늘고 있으니 손을 씻고 물건을 함께 쓰지 말라고 당부하는 방송이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 안내 말씀 드립니다. 보건실입니다. 이번 주 우리 학교에 독감 환자가 크게 늘었습니다. 식사 전후에는 비누로 손을 씻어 주세요. 열이 나면 바로 집에 가서 쉬세요. 컵, 수건, 물병을 누구와도 함께 쓰지 마세요. 건강하게 지내고 서로 챙겨 주세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the stationery shop. What do you need?"],
        ["W", "Two binders and four packs of paper, please."],
        ["M", "A binder is nine dollars and a pack is five."],
        ["W", "So the total is thirty-eight dollars."],
        ["M", "That's right. Do you need a bag?"],
        ["W", "No, thank you. I have my backpack."],
        ["M", "All right. Orders over thirty dollars get eight dollars off."],
        ["W", "That's great news. Here you are."],
      ],
      choices: ["$26", "$28", "$30", "$32", "$38"],
      answer: 3,
      clue: "All right. Orders over thirty dollars get eight dollars off.",
      explanation:
        "바인더 2개 18달러와 종이 4묶음 20달러를 더하면 38달러이고, 30달러 초과 할인 8달러를 빼면 30달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 문구점에 오신 걸 환영합니다. 무엇이 필요하세요?",
        "W: 바인더 두 개랑 종이 네 묶음 주세요.",
        "M: 바인더는 9달러, 종이는 한 묶음에 5달러입니다.",
        "W: 그럼 모두 38달러네요.",
        "M: 맞습니다. 봉투 필요하세요?",
        "W: 아니요, 괜찮아요. 가방이 있어요.",
        "M: 알겠습니다. 30달러가 넘는 주문은 8달러 할인됩니다.",
        "W: 좋은 소식이네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Taemin, you looked lost during the whole science class."],
        ["M", "I understood the first ten minutes and then nothing."],
        ["W", "Did you ask the teacher to repeat anything?"],
        ["M", "No, I didn't want to slow everyone down."],
        ["W", "So you sat there confused for forty more minutes."],
        ["M", "That's exactly what happened."],
        ["W", "Other people were probably lost at the same point."],
        ["M", "Then what should I do the next time it happens?"],
        ["W", "Raise your hand the moment you stop following."],
      ],
      choices: [
        "I'll try that in tomorrow's class.",
        "I understood everything today.",
        "I never take science class.",
        "The teacher speaks too slowly.",
        "Let's skip science tomorrow.",
      ],
      answer: 1,
      clue: "Raise your hand the moment you stop following.",
      explanation:
        "여자가 이해가 끊기는 순간 바로 손을 들라고 했으므로, 내일 수업에서 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 태민아, 과학 시간 내내 헤매는 것 같더라.",
        "M: 처음 10분은 알아듣고 그다음부터는 전혀 모르겠어.",
        "W: 선생님께 다시 설명해 달라고 했어?",
        "M: 아니, 다른 애들 진도를 늦추기 싫었어.",
        "W: 그래서 40분을 더 헷갈린 채로 앉아 있었구나.",
        "M: 딱 그랬어.",
        "W: 다른 애들도 같은 데서 놓쳤을 거야.",
        "M: 그럼 다음에 그러면 어떻게 해야 해?",
        "W: 따라가지 못하는 순간 바로 손을 들어.",
        "M: 내일 수업에서 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Eunbi, your backpack strap is fraying at the top."],
        ["W", "I noticed. It's been like that for two months."],
        ["M", "Do you carry it on one shoulder?"],
        ["W", "Yes, always on the right side."],
        ["M", "All the weight pulls on one strap, so it wears out."],
        ["W", "I thought one shoulder just looked better."],
        ["M", "It also makes your back hurt after a while."],
        ["W", "So should I use both straps from now on?"],
        ["M", "Yes, and tighten them so the bag sits high on your back."],
      ],
      choices: [
        "My backpack has one strap.",
        "My back never hurts at all.",
        "I'll buy a new backpack today.",
        "I'll wear it that way tomorrow.",
        "One shoulder is much better.",
      ],
      answer: 4,
      clue: "Yes, and tighten them so the bag sits high on your back.",
      explanation:
        "남자가 두 끈을 다 메고 등 위쪽에 오게 조이라고 했으므로, 내일부터 그렇게 메겠다는 ④가 가장 자연스럽다.",
      translation: [
        "M: 은비야, 가방끈 위쪽이 해지고 있어.",
        "W: 나도 봤어. 두 달째 그래.",
        "M: 한쪽 어깨에만 메?",
        "W: 응, 늘 오른쪽에.",
        "M: 무게가 한쪽 끈에만 실리니까 닳는 거야.",
        "W: 한쪽으로 메는 게 더 멋있어 보인다고 생각했어.",
        "M: 그리고 시간이 지나면 등도 아파.",
        "W: 그럼 이제부터 양쪽 끈을 다 메야 해?",
        "M: 응, 그리고 가방이 등 위쪽에 오게 조여.",
        "W: 내일부터 그렇게 멜게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["M", "Eunbi, our class newsletter has almost no photos."],
        ["W", "Didn't the photo club send you any?"],
        ["M", "They sent twelve, but they all came out too dark."],
        ["W", "Where were the pictures taken?"],
        ["M", "In the classroom, with the lights on and the curtains closed."],
        ["W", "Indoor light is much weaker than it looks to your eye."],
        ["M", "So the camera couldn't take in enough light?"],
        ["W", "Right. Open the curtains and shoot toward the window side."],
        ["M", "Is that enough by itself?"],
        ["W", "Almost. Just don't put people right in front of the window."],
      ],
      choices: [
        "Our class has no camera.",
        "I'll try that at the next shoot.",
        "The photos were very bright.",
        "Let's close all the curtains.",
        "I'll stop making the newsletter.",
      ],
      answer: 2,
      clue: "Almost. Just don't put people right in front of the window.",
      explanation:
        "여자가 커튼을 열고 창 쪽을 향해 찍되 사람을 창 바로 앞에 두지 말라고 했으므로, 다음 촬영 때 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 은비야, 우리 반 소식지에 사진이 거의 없어.",
        "W: 사진 동아리에서 안 보내 줬어?",
        "M: 열두 장 보내 줬는데 다 너무 어둡게 나왔어.",
        "W: 어디서 찍은 사진이야?",
        "M: 교실에서, 불 켜고 커튼 닫은 채로.",
        "W: 실내 조명은 눈에 보이는 것보다 훨씬 약해.",
        "M: 그럼 카메라가 빛을 충분히 못 받은 거야?",
        "W: 맞아. 커튼을 열고 창 쪽을 향해 찍어.",
        "M: 그것만으로 충분해?",
        "W: 거의. 다만 사람을 창 바로 앞에 세우지는 마.",
        "M: 다음 촬영 때 그렇게 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minseo가 Junhyung에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Minseo : ________________",
      lines: [
        [
          "W",
          "Minseo and Junhyung are packing up after the club meeting. " +
            "Junhyung has closed his laptop and slid it into his bag. " +
            "Minseo notices that his charger is still plugged into the wall. " +
            "The club room is locked for the whole weekend after today. " +
            "She wants to tell him before they turn off the lights. " +
            "In this situation, what would Minseo most likely say to Junhyung?",
        ],
      ],
      choices: [
        "Let's stay and work longer.",
        "The club room is open tomorrow.",
        "I'll lend you my laptop.",
        "Please turn on the lights.",
        "Your charger is still in the wall.",
      ],
      answer: 5,
      clue: "Minseo notices that his charger is still plugged into the wall.",
      explanation:
        "준형이의 충전기가 아직 벽에 꽂혀 있고 동아리방은 주말 내내 잠기므로, 그 사실을 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "W: 민서와 준형이는 동아리 모임이 끝나고 짐을 챙기고 있습니다. 준형이는 노트북을 덮어 가방에 넣었습니다. 민서는 준형이의 충전기가 아직 벽에 꽂혀 있는 것을 봅니다. 동아리방은 오늘 이후 주말 내내 잠깁니다. 민서는 불을 끄기 전에 알려 주고 싶습니다. 이런 상황에서 민서가 준형이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
