/** 중3 듣기 21회 — 사람이 직접 쓴 회차 (2026-09-21) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 21회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 스탠드를 고르시오.",
      lines: [
        ["M", "Good afternoon. Are you looking for a desk lamp?"],
        ["W", "Yes, for my daughter's study desk."],
        ["M", "We have ones that clip onto the desk and ones with a base."],
        ["W", "With a base, please. Her desk edge is too thick for a clip."],
        ["M", "All right. Do you want an arm that bends?"],
        ["W", "Yes, a bending arm. She moves it over her book."],
        ["M", "Then two are left. One has buttons on the base and one has a dial."],
        ["W", "The dial, please. She can turn it without looking."],
        ["M", "Good choice. The dial makes the light brighter as you turn it."],
        ["W", "That's exactly what she needs. I'll take it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "The dial, please. She can turn it without looking.",
      explanation:
        "여자는 받침이 있는 스탠드를, 구부러지는 팔이 달린 것으로, 그중 다이얼이 있는 것을 고른다. 따라서 답은 ④이다.",
      figure: {
        kind: "labeled",
        scene:
          "Five desk lamps in one row across the middle of the picture, all five fully inside the frame with a wide empty margin on the left and right, each the same size, drawn from the side, clean black line art on a plain white background, no writing or letters anywhere. " +
          "Lamp 1: a CLIP at the bottom that grips a desk edge (no base), with a straight rigid arm. " +
          "Lamp 2: a round flat BASE, a STRAIGHT rigid arm that does not bend, and three small round BUTTONS on the base. " +
          "Lamp 3: a round flat BASE, an arm with a clear BEND in the middle, and three small round BUTTONS on the base. " +
          "Lamp 4: a round flat BASE, an arm with a clear BEND in the middle, and one large round DIAL knob on the base. " +
          "Lamp 5: a round flat BASE, a STRAIGHT rigid arm that does not bend, and one large round DIAL knob on the base. " +
          "Every lamp has a cone-shaped shade at the top.",
      },
      translation: [
        "M: 안녕하세요. 책상 스탠드 찾으세요?",
        "W: 네, 딸아이 책상에 둘 거예요.",
        "M: 책상에 집게로 무는 것도 있고 받침이 있는 것도 있습니다.",
        "W: 받침 있는 걸로요. 책상 모서리가 두꺼워서 집게가 안 물려요.",
        "M: 알겠습니다. 구부러지는 팔로 하시겠어요?",
        "W: 네, 구부러지는 걸로요. 책 위로 옮겨 두거든요.",
        "M: 그럼 두 개 남았네요. 하나는 받침에 버튼이 있고 하나는 다이얼이 있습니다.",
        "W: 다이얼로요. 안 보고도 돌릴 수 있으니까요.",
        "M: 좋은 선택이세요. 다이얼을 돌리면 점점 밝아집니다.",
        "W: 딱 그게 필요했어요. 그걸로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 교내 토론 대회에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minjun, are you entering the debate contest?"],
        ["M", "I'd like to. When does it start?"],
        ["W", "The second Friday of next month, at four."],
        ["M", "Where is it held?"],
        ["W", "In the auditorium, on the stage."],
        ["M", "How long does each team speak?"],
        ["W", "Six minutes, and three minutes to answer questions."],
        ["M", "What are we arguing about?"],
        ["W", "Whether schools should have a uniform. They tell you your side on the day."],
        ["M", "Then I'll read both sides this week."],
      ],
      choices: ["열리는 날", "장소", "말하는 시간", "토론 주제", "심사 위원"],
      answer: 5,
      clue: "Whether schools should have a uniform. They tell you your side on the day.",
      explanation:
        "날짜(다음 달 둘째 금요일 4시), 장소(강당 무대), 시간(6분과 3분), 주제(교복)는 언급되지만 심사 위원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민준아, 토론 대회 나갈 거야?",
        "M: 나가고 싶어. 언제 시작해?",
        "W: 다음 달 둘째 금요일 4시에.",
        "M: 어디서 하는데?",
        "W: 강당 무대에서.",
        "M: 한 팀이 얼마나 말해?",
        "W: 6분, 그리고 질문에 답하는 시간 3분.",
        "M: 주제가 뭔데?",
        "W: 학교에 교복이 있어야 하는가. 어느 편인지는 당일에 알려 줘.",
        "M: 그럼 이번 주에 양쪽 다 읽어 봐야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello?"],
        ["W", "Hi, Dohyun. It's Seoyeon from the volunteer club."],
        ["M", "Hi. What's up?"],
        ["W", "About Saturday at the library."],
        ["M", "Is it cancelled?"],
        ["W", "No, but they want us an hour earlier."],
        ["M", "So nine instead of ten?"],
        ["W", "That's right. The books arrive at nine."],
        ["M", "Thanks for calling. I'll set my alarm earlier."],
      ],
      choices: [
        "시작 시간이 당겨졌다고 알리려고",
        "봉사가 취소되었다고 알리려고",
        "장소가 바뀌었다고 알리려고",
        "봉사 신청을 권하려고",
        "책을 빌려 달라고 하려고",
      ],
      answer: 1,
      clue: "No, but they want us an hour earlier.",
      explanation:
        "책이 9시에 와서 한 시간 일찍 오라는 것을 알리려고 전화했다. 따라서 답은 ①이다.",
      translation: [
        "M: 여보세요?",
        "W: 안녕, 도현아. 봉사 동아리 서연이야.",
        "M: 안녕. 무슨 일이야?",
        "W: 토요일 도서관 봉사 말인데.",
        "M: 취소됐어?",
        "W: 아니, 한 시간 일찍 와 달래.",
        "M: 10시 말고 9시?",
        "W: 맞아. 책이 9시에 들어온대.",
        "M: 전화해 줘서 고마워. 알람 일찍 맞춰 둘게.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 출발할 시각을 고르시오.",
      lines: [
        ["W", "Minjun, what time does the play start on Saturday?"],
        ["M", "Seven o'clock, and they close the doors at five to."],
        ["W", "How long does it take to get there?"],
        ["M", "Forty minutes by subway, if we don't miss the train."],
        ["W", "Then six fifteen would be enough."],
        ["M", "We have to pick up the tickets at the counter too."],
        ["W", "How long is that?"],
        ["M", "About fifteen minutes on a Saturday."],
        ["W", "Then let's leave at six."],
        ["M", "Six o'clock it is. I'll be at your gate."],
      ],
      choices: ["5:45 p.m.", "6:00 p.m.", "6:15 p.m.", "6:30 p.m.", "6:45 p.m."],
      answer: 2,
      clue: "Then let's leave at six.",
      explanation:
        "7시 공연에 지하철 40분, 표 찾는 데 15분이 더 들어서 두 사람은 6시에 출발하기로 한다. 따라서 답은 ②이다.",
      translation: [
        "W: 민준아, 토요일 연극 몇 시에 시작해?",
        "M: 7시. 5분 전에 문 닫아.",
        "W: 거기까지 얼마나 걸려?",
        "M: 지하철로 40분, 차를 놓치지 않으면.",
        "W: 그럼 6시 15분이면 되겠네.",
        "M: 표도 창구에서 찾아야 해.",
        "W: 그건 얼마나 걸려?",
        "M: 토요일엔 15분쯤.",
        "W: 그럼 6시에 나가자.",
        "M: 6시로 하자. 너희 집 앞으로 갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, you've refreshed that page five times."],
        ["W", "The exchange programme results come out at six."],
        ["M", "It's ten past six now."],
        ["W", "I know. The site keeps saying it's busy."],
        ["M", "Everyone in the country is opening it at once."],
        ["W", "I've wanted this for two years. My hands won't stay still."],
        ["M", "Shall I try on my phone?"],
        ["W", "Please. I can't press it again myself."],
      ],
      choices: ["nervous", "bored", "proud", "angry", "satisfied"],
      answer: 1,
      clue: "I've wanted this for two years. My hands won't stay still.",
      explanation:
        "여자는 2년 동안 바라던 결과를 기다리며 손이 떨린다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "M: 서연아, 그 화면을 다섯 번이나 새로 고쳤어.",
        "W: 교환 프로그램 결과가 6시에 나와.",
        "M: 지금 6시 10분이야.",
        "W: 알아. 사이트가 자꾸 붐빈다고만 떠.",
        "M: 전국에서 한꺼번에 열고 있으니까.",
        "W: 2년 동안 바라던 거야. 손이 가만히 안 있어.",
        "M: 내 휴대전화로 해 볼까?",
        "W: 그래 줘. 나는 못 누르겠어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["W", "Excuse me, is this seat taken?"],
        ["M", "No, please sit down."],
        ["W", "Would you like to take my seat?"],
        ["M", "Thank you. My leg is hurting today."],
        ["W", "How much is a single ticket?"],
        ["M", "Two dollars fifty."],
        ["W", "Does this bus go to the museum?"],
        ["M", "Yes, four stops from here."],
        ["W", "Could you press the bell for me?"],
        ["M", "Of course, I'm right next to it."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 2,
      clue: "Would you like to take my seat?",
      explanation:
        "그림은 버스 안에서 앉아 있던 학생이 일어나 목발을 짚은 사람에게 자리를 권하는 장면이므로 ②가 가장 적절하다.",
      figure: {
        kind: "plain",
        scene:
          "One single scene inside a city bus, clean black line art on a plain white background, no writing or letters anywhere, every sign blank. A teenage GIRL has just stood up from her seat and is turning toward an older MAN who is standing in the aisle leaning on a CRUTCH under one arm; she gestures with an open hand toward the empty seat she has left. The man looks at her with a grateful expression. Other passengers sit further back holding the overhead bar. Bus windows and handrails are drawn behind them, and everyone is fully inside the frame.",
      },
      translation: [
        "① W: 실례지만 이 자리 비었나요? / M: 네, 앉으세요.",
        "② W: 제 자리에 앉으시겠어요? / M: 고맙습니다. 오늘 다리가 아파서요.",
        "③ W: 표 한 장에 얼마예요? / M: 2달러 50센트입니다.",
        "④ W: 이 버스 박물관 가나요? / M: 네, 여기서 네 정거장이요.",
        "⑤ W: 벨 좀 눌러 주시겠어요? / M: 그럼요, 제가 바로 옆에 있어요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hayoon, are you going to the music room at lunch?"],
        ["W", "Yes, I practise the piano there every day."],
        ["M", "Could you do one thing for me while you're there?"],
        ["W", "Sure. What is it?"],
        ["M", "My guitar is leaning against the wall by the window."],
        ["W", "Do you want me to bring it to the classroom?"],
        ["M", "No, please put it back in its case. The sun fades the wood."],
        ["W", "All right. Where is the case?"],
        ["M", "Under the piano bench. Thanks, I have a meeting."],
      ],
      choices: [
        "기타를 가져다주기",
        "피아노를 쳐 주기",
        "창문을 닫아 주기",
        "기타를 고쳐 주기",
        "기타를 케이스에 넣어 주기",
      ],
      answer: 5,
      clue: "No, please put it back in its case. The sun fades the wood.",
      explanation:
        "남자는 창가에 세워 둔 기타를 케이스에 넣어 달라고 부탁한다. 가져다 달라는 것이 아니다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 하윤아, 점심시간에 음악실 가?",
        "W: 응, 매일 거기서 피아노 연습해.",
        "M: 거기 있는 동안 하나만 부탁할게.",
        "W: 그래. 뭔데?",
        "M: 내 기타가 창가 벽에 기대어 있어.",
        "W: 교실로 가져다줄까?",
        "M: 아니, 케이스에 다시 넣어 줘. 햇빛에 나무 색이 바래.",
        "W: 알겠어. 케이스는 어디 있어?",
        "M: 피아노 의자 밑에. 고마워, 나 회의가 있어서.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, Autumn Walk에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Hello, students. Here is news about the Autumn Walk."],
        ["M", "It will be held on the last Saturday of this month."],
        ["M", "We start at the school gate and walk to the river park."],
        ["M", "The whole way is about six kilometres, mostly flat."],
        ["M", "Wear comfortable shoes and bring a water bottle."],
        ["M", "Let's spend one morning outside together."],
      ],
      choices: ["열리는 날", "걷는 길", "거리", "준비물", "참가 인원"],
      answer: 5,
      clue: "Wear comfortable shoes and bring a water bottle.",
      explanation:
        "날짜(이달 마지막 토요일), 길(교문에서 강변공원), 거리(6km), 준비물(편한 신발과 물병)은 언급되지만 참가 인원은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 학생 여러분, 안녕하세요. Autumn Walk 소식입니다.",
        "M: 이달 마지막 토요일에 열립니다.",
        "M: 교문에서 출발해 강변공원까지 걷습니다.",
        "M: 전체 길이는 6킬로미터 남짓이고 거의 평지입니다.",
        "M: 편한 신발을 신고 물병을 가져오세요.",
        "M: 오전 한나절을 밖에서 함께 보내 봅시다.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        ["W", "This sits on a shelf in the corner of the classroom."],
        ["W", "It is a box with a slot cut in the top."],
        ["W", "Students drop folded notes into it without signing them."],
        ["W", "The class president opens it once a week."],
        ["W", "Things people would never say aloud end up inside."],
      ],
      choices: ["사물함", "쓰레기통", "건의함", "책 반납함", "분실물함"],
      answer: 3,
      clue: "Students drop folded notes into it without signing them.",
      explanation:
        "이름을 적지 않은 쪽지를 넣고 반장이 주마다 연다고 했으므로 건의함이다. 따라서 답은 ③이다.",
      translation: [
        "W: 이것은 교실 구석 선반에 놓여 있습니다.",
        "W: 위에 구멍이 뚫린 상자입니다.",
        "W: 학생들이 이름을 적지 않고 접은 쪽지를 넣습니다.",
        "W: 반장이 일주일에 한 번 엽니다.",
        "W: 소리 내어 말하지 못할 이야기가 그 안에 모입니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["M", "How long does the film run?"],
        ["W", "About two hours."],
        ["M", "Could you pass me the salt?"],
        ["W", "Here you are."],
        ["M", "Which subject do you find hardest?"],
        ["W", "Maths, without a doubt."],
        ["M", "Why are you carrying an umbrella?"],
        ["W", "I have two younger brothers."],
        ["M", "Shall we walk or take the bus?"],
        ["W", "Let's walk. It's a nice evening."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why are you carrying an umbrella?",
      explanation:
        "왜 우산을 들고 있느냐는 물음에 남동생이 둘이라는 대답은 어울리지 않는다. 따라서 답은 ④이다.",
      translation: [
        "① M: 그 영화 얼마나 길어? / W: 두 시간쯤.",
        "② M: 소금 좀 건네줄래? / W: 여기 있어.",
        "③ M: 어느 과목이 제일 어려워? / W: 두말할 것 없이 수학.",
        "④ M: 왜 우산을 들고 있어? / W: 나는 남동생이 둘이야.",
        "⑤ M: 걸을까, 버스 탈까? / W: 걷자. 저녁이 좋네.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, the club exhibition opens in twenty minutes."],
        ["W", "Is everything up? What should I do?"],
        ["M", "The posters are on the wall and the tables are in place."],
        ["W", "What about the name cards for each work?"],
        ["M", "Minjun put them out ten minutes ago."],
        ["W", "Then what's left?"],
        ["M", "The lights over the back wall are still off."],
        ["W", "I'll go and switch them on now."],
        ["M", "Thanks. I'll wait at the door for visitors."],
      ],
      choices: ["포스터 붙이기", "탁자 놓기", "이름표 놓기", "조명 켜기", "문에서 맞이하기"],
      answer: 4,
      clue: "I'll go and switch them on now.",
      explanation:
        "포스터·탁자·이름표는 이미 끝났고 남은 것은 뒷벽 조명을 켜는 일이다. 따라서 답은 ④이다.",
      translation: [
        "M: 서연아, 동아리 전시가 20분 뒤에 열려.",
        "W: 다 걸었어? 내가 뭘 할까?",
        "M: 포스터는 벽에 붙였고 탁자도 자리 잡았어.",
        "W: 작품마다 붙일 이름표는?",
        "M: 민준이가 10분 전에 놨어.",
        "W: 그럼 뭐가 남았어?",
        "M: 뒷벽 조명이 아직 꺼져 있어.",
        "W: 내가 지금 가서 켤게.",
        "M: 고마워. 나는 문에서 손님 맞을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 신청할 동아리를 고르시오.",
      lines: [
        ["W", "Dohyun, these are the five clubs still taking members."],
        ["M", "Let's look. I can't do anything on Wednesday — that's my academy day."],
        ["W", "Then one is out. What else?"],
        ["M", "It has to meet after school, not at lunch."],
        ["W", "One of them meets at lunch, so that's gone too."],
        ["M", "Three left. Is there a fee?"],
        ["W", "You said you'd rather not pay anything."],
        ["M", "Then one more drops out. Two are left."],
        ["W", "Do they both take beginners?"],
        ["M", "Only one does. The other wants a year of experience."],
        ["W", "Then that settles it. Sign up tomorrow."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Then that settles it. Sign up tomorrow.",
      explanation:
        "수요일인 ①, 점심에 모이는 ②, 회비가 있는 ③을 뺀다. 남은 ④와 ⑤ 중 초보자를 받는 것은 ⑤이므로 답은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "수요일 / 방과 후 / 회비 없음 / 초보 가능" },
          { no: 2, label: "②", value: "목요일 / 점심시간 / 회비 없음 / 초보 가능" },
          { no: 3, label: "③", value: "화요일 / 방과 후 / 회비 10,000원 / 초보 가능" },
          { no: 4, label: "④", value: "금요일 / 방과 후 / 회비 없음 / 경력 1년 필요" },
          { no: 5, label: "⑤", value: "월요일 / 방과 후 / 회비 없음 / 초보 가능" },
        ],
      },
      translation: [
        "W: 도현아, 아직 부원을 받는 동아리가 이 다섯 개야.",
        "M: 보자. 수요일은 안 돼. 학원 가는 날이야.",
        "W: 그럼 하나 빠지네. 또 뭐가 있어?",
        "M: 점심시간 말고 방과 후에 모여야 해.",
        "W: 하나는 점심에 모이니까 그것도 빠지고.",
        "M: 셋 남았다. 회비 있어?",
        "W: 돈은 안 내고 싶다고 했잖아.",
        "M: 그럼 하나 더 빠지고 둘 남았다.",
        "W: 둘 다 초보를 받아?",
        "M: 한 곳만. 다른 데는 경력 1년을 원해.",
        "W: 그럼 정해졌네. 내일 신청해.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 전시회에 갈 날짜를 고르시오.",
      lines: [
        ["M", "Hayoon, when should we go to the photo exhibition?"],
        ["W", "It's on from the eighteenth to the twenty-second."],
        ["M", "What kind of photos are they?"],
        ["W", "Night streets in five cities, all taken by one person."],
        ["M", "I'd like to see that. But I have a dentist appointment on the nineteenth."],
        ["W", "Then the twentieth, the twenty-first or the twenty-second."],
        ["M", "The twenty-first and the twenty-second are the school festival."],
        ["W", "You're right. We'd be there all day both days."],
        ["M", "So only one day is left."],
        ["W", "Then let's go on the twentieth. It opens at ten."],
      ],
      choices: ["18일", "19일", "20일", "21일", "22일"],
      answer: 3,
      clue: "Then let's go on the twentieth. It opens at ten.",
      explanation:
        "19일은 치과 예약, 21일과 22일은 학교 축제여서 20일만 남는다. 따라서 답은 ③이다.",
      translation: [
        "M: 하윤아, 사진 전시회 언제 갈까?",
        "W: 18일부터 22일까지 해.",
        "M: 어떤 사진인데?",
        "W: 다섯 도시의 밤거리를 한 사람이 다 찍은 거야.",
        "M: 보고 싶다. 그런데 19일에 치과 예약이 있어.",
        "W: 그럼 20일, 21일, 22일이네.",
        "M: 21일이랑 22일은 학교 축제잖아.",
        "W: 맞다. 이틀 다 하루 종일 거기 있겠네.",
        "M: 그럼 하루만 남네.",
        "W: 그럼 20일에 가자. 10시에 문 열어.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjun, did you go to the match on Sunday?"],
        ["M", "No, I spent the day fixing my grandfather's fence."],
        ["W", "The fence? How long had it been broken?"],
        ["M", "Since the storm in July. Three posts had come loose."],
        ["W", "Did you do it by yourself?"],
        ["M", "My uncle helped. He brought the tools."],
        ["W", "How long did it take?"],
        ["M", "Five hours, and we ran out of nails twice."],
        ["W", "Does it hold now?"],
        ["M", "My grandfather leaned on it and it didn't move. That was the test."],
      ],
      choices: ["울타리 고치기", "경기 보러 가기", "공구 사러 가기", "할아버지 댁 청소하기", "삼촌 돕기"],
      answer: 1,
      clue: "No, I spent the day fixing my grandfather's fence.",
      explanation:
        "남자는 지난 일요일에 할아버지 댁 울타리를 고쳤다고 말한다. 따라서 답은 ①이다.",
      translation: [
        "W: 민준아, 일요일에 경기 보러 갔어?",
        "M: 아니, 할아버지 댁 울타리 고치느라 하루를 다 썼어.",
        "W: 울타리? 언제부터 망가져 있었는데?",
        "M: 7월 태풍 때부터. 기둥 세 개가 헐거워졌어.",
        "W: 혼자 했어?",
        "M: 삼촌이 도와줬어. 공구를 가져오셨어.",
        "W: 얼마나 걸렸어?",
        "M: 다섯 시간. 못이 두 번이나 떨어졌어.",
        "W: 이제 튼튼해?",
        "M: 할아버지가 기대셨는데 안 흔들렸어. 그게 시험이었지.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Good morning, students. This is the school office."],
        ["W", "The lift in the main building will stop working tomorrow."],
        ["W", "Engineers are replacing the cables, and it takes all day."],
        ["W", "Students who cannot use the stairs should come to the office first."],
        ["W", "We will move your classes to the first floor for the day."],
        ["W", "Thank you for your understanding."],
      ],
      choices: [
        "계단을 이용하라고 하려고",
        "승강기가 멈춘다고 알리려고",
        "공사 비용을 안내하려고",
        "등교 시간을 바꾸려고",
        "1층에 가지 말라고 하려고",
      ],
      answer: 2,
      clue: "The lift in the main building will stop working tomorrow.",
      explanation:
        "본관 승강기가 하루 동안 멈춘다는 것과 그에 따른 안내를 전하는 방송이다. 따라서 방송의 목적은 ②이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 행정실입니다.",
        "W: 내일 본관 승강기가 멈춥니다.",
        "W: 기사님들이 줄을 바꾸는데 하루가 걸립니다.",
        "W: 계단을 쓰기 어려운 학생은 먼저 행정실로 오세요.",
        "W: 그날은 수업을 1층으로 옮겨 드립니다.",
        "W: 이해해 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the flower shop. What can I get you?"],
        ["W", "Four tulips, please."],
        ["M", "Tulips are four dollars each."],
        ["W", "So sixteen dollars for four."],
        ["M", "That's right. Would you like a card with them?"],
        ["W", "Yes, please. How much is that?"],
        ["M", "Six dollars."],
        ["W", "Then twenty-two dollars in total."],
        ["M", "And members get twenty-five percent off the flowers, not the card."],
        ["W", "I'm a member. Here's my card."],
      ],
      choices: ["$14", "$16", "$18", "$20", "$22"],
      answer: 3,
      clue: "And members get twenty-five percent off the flowers, not the card.",
      explanation:
        "튤립 네 송이는 16달러이고 여기서 25%를 빼면 12달러, 카드 6달러를 더하면 18달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 꽃집입니다. 무엇을 드릴까요?",
        "W: 튤립 네 송이 주세요.",
        "M: 튤립은 한 송이에 4달러입니다.",
        "W: 그럼 네 송이에 16달러네요.",
        "M: 맞습니다. 카드도 같이 하시겠어요?",
        "W: 네. 얼마예요?",
        "M: 6달러입니다.",
        "W: 그럼 모두 22달러군요.",
        "M: 그리고 회원은 꽃값에서 25%를 빼 드립니다. 카드는 빼고요.",
        "W: 저 회원이에요. 카드 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Hayoon, you've made flashcards for every word in the unit."],
        ["W", "All one hundred and twenty of them. It took two evenings."],
        ["M", "And how many do you get wrong when you test yourself?"],
        ["W", "About fifteen. The rest I knew already."],
        ["M", "So you're carrying a hundred and five cards you don't need."],
        ["W", "I never thought of it that way."],
        ["M", "Every time you go through the pile, those fifteen get one turn."],
        ["W", "And the ones I know get a turn too."],
        ["M", "Pull the fifteen out and carry only those."],
      ],
      choices: [
        "My flashcards are quite small.",
        "Then I'll pull those fifteen out tonight.",
        "I made them over two evenings.",
        "The test is next Wednesday.",
        "You should make flashcards too.",
      ],
      answer: 2,
      clue: "Pull the fifteen out and carry only those.",
      explanation:
        "틀리는 열다섯 장만 빼서 들고 다니라는 조언을 들었으므로, 오늘 밤에 그것들을 빼겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 하윤아, 단원에 나온 낱말을 전부 카드로 만들었네.",
        "W: 백스무 장 다. 저녁 이틀이 걸렸어.",
        "M: 그럼 혼자 시험 볼 때 몇 개나 틀려?",
        "W: 열다섯 개쯤. 나머지는 원래 알던 거야.",
        "M: 그럼 필요 없는 카드 백다섯 장을 들고 다니는 거네.",
        "W: 그렇게는 생각 못 했어.",
        "M: 더미를 한 바퀴 돌 때마다 그 열다섯 장은 한 번씩만 봐.",
        "W: 아는 것들도 한 번씩 돌아가고.",
        "M: 그 열다섯 장만 빼서 그것만 들고 다녀.",
        "W: 그럼 오늘 밤에 그 열다섯 장을 빼낼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Man : ________________",
      lines: [
        ["W", "Dohyun, you've missed the school bus three times this term."],
        ["M", "Four, if you count the day it left early."],
        ["W", "What time do you leave the house?"],
        ["M", "Seven fifty. The bus goes at seven fifty-five."],
        ["W", "And how long does it take you to walk to the stop?"],
        ["M", "Four minutes if nothing goes wrong."],
        ["W", "So you have one minute of room in the whole plan."],
        ["M", "When you say it out loud it sounds impossible."],
        ["W", "Leave at seven forty-five instead."],
      ],
      choices: [
        "My house is near the stop.",
        "The bus is often late anyway.",
        "Then I'll leave at seven forty-five tomorrow.",
        "I walk to school sometimes.",
        "You should catch an earlier bus.",
      ],
      answer: 3,
      clue: "Leave at seven forty-five instead.",
      explanation:
        "7시 45분에 나가라는 조언을 들었으므로, 내일부터 그 시각에 나가겠다는 ③이 가장 자연스럽다.",
      translation: [
        "W: 도현아, 이번 학기에 학교 버스를 세 번이나 놓쳤네.",
        "M: 일찍 떠난 날까지 세면 네 번.",
        "W: 집에서 몇 시에 나가는데?",
        "M: 7시 50분. 버스는 7시 55분에 가.",
        "W: 정류장까지 걸어가는 데 얼마나 걸려?",
        "M: 아무 일 없으면 4분.",
        "W: 그럼 계획 전체에 여유가 1분뿐이네.",
        "M: 소리 내어 들으니까 불가능하게 들린다.",
        "W: 대신 7시 45분에 나가.",
        "M: 그럼 내일부터 7시 45분에 나갈게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "Woman : ________________",
      lines: [
        ["M", "Seoyeon, how is the school newspaper going?"],
        ["W", "Slowly. I've been writing the same article for two weeks."],
        ["M", "What's holding you up?"],
        ["W", "I keep looking for more sources. I have thirty already."],
        ["M", "How many will fit in a six-hundred-word article?"],
        ["W", "Maybe four or five, honestly."],
        ["M", "So you've spent two weeks collecting twenty-five you can't use."],
        ["W", "I thought more reading would make it better."],
        ["M", "Pick your best four and start writing tonight."],
      ],
      choices: [
        "My article is about school lunches.",
        "I read three hours a day.",
        "The newspaper comes out monthly.",
        "Then I'll pick four and start tonight.",
        "You should find more sources too.",
      ],
      answer: 4,
      clue: "Pick your best four and start writing tonight.",
      explanation:
        "가장 좋은 자료 네 개를 골라 오늘 밤 쓰기 시작하라는 조언을 들었으므로 ④가 가장 자연스럽다.",
      translation: [
        "M: 서연아, 학교 신문은 잘돼 가?",
        "W: 더뎌. 같은 기사를 2주째 쓰고 있어.",
        "M: 뭐가 막고 있는데?",
        "W: 자료를 자꾸 더 찾게 돼. 벌써 서른 개야.",
        "M: 600낱말짜리 기사에 몇 개나 들어가는데?",
        "W: 솔직히 네다섯 개쯤.",
        "M: 그럼 쓰지도 못할 스물다섯 개를 모으느라 2주를 쓴 거네.",
        "W: 더 읽으면 더 좋아질 줄 알았어.",
        "M: 제일 좋은 네 개만 골라서 오늘 밤에 쓰기 시작해.",
        "W: 그럼 네 개 골라서 오늘 밤에 시작할게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minjun이 Hayoon에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "Minjun : ________________",
      lines: [
        ["M", "Minjun and Hayoon are preparing a class debate together."],
        ["M", "Hayoon has written a script for every possible question."],
        ["M", "The answers are careful and she worked on them all week."],
        ["M", "However, there are forty pages and she plans to read them aloud."],
        ["M", "A debate answer has to come back in thirty seconds."],
        ["M", "Turning pages would use up most of that time."],
        ["M", "Minjun does not want to say that her work was wasted."],
        ["M", "He wants to suggest turning each answer into one short line."],
        ["M", "In this situation, what would Minjun most likely say to Hayoon?"],
      ],
      choices: [
        "Let's write ten more answers.",
        "Could we turn each answer into one short line?",
        "You should read faster on the day.",
        "I'll do the debate by myself.",
        "Let's print it in a smaller font.",
      ],
      answer: 2,
      clue: "He wants to suggest turning each answer into one short line.",
      explanation:
        "민준이는 하윤이가 한 일을 깎아내리지 않으면서, 답마다 한 줄로 줄이자고 말하려 한다. 따라서 ②가 가장 적절하다.",
      translation: [
        "M: 민준이와 하윤이는 학급 토론을 함께 준비하고 있습니다.",
        "M: 하윤이는 나올 만한 질문마다 답을 글로 써 두었습니다.",
        "M: 답은 꼼꼼하고, 하윤이는 한 주 내내 매달렸습니다.",
        "M: 그런데 마흔 쪽이나 되고, 그것을 소리 내어 읽을 생각입니다.",
        "M: 토론에서는 30초 안에 답이 돌아와야 합니다.",
        "M: 쪽을 넘기는 데만 그 시간을 거의 다 쓰게 됩니다.",
        "M: 민준이는 하윤이가 한 일이 헛수고라고 말하고 싶지는 않습니다.",
        "M: 다만 답마다 짧은 한 줄로 줄이자고 제안하고 싶습니다.",
        "M: 이런 상황에서 민준이가 하윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
