/** 중3 듣기 29회 — 사람이 직접 쓴 회차 (2026-09-25) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 29회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 구입할 물통을 고르시오.",
      lines: [
        ["W", "Hello. Are you looking for a water bottle?"],
        ["M", "Yes, one I can take to soccer practice."],
        ["W", "We have wide-mouth bottles and narrow-mouth ones."],
        ["M", "A wide mouth, please. Ice cubes won't fit in a narrow one."],
        ["W", "All right. This wide-mouth bottle has a loop handle on the lid."],
        ["M", "A loop always hooks onto things inside my bag."],
        ["W", "Then here is a wide-mouth one with a plain lid."],
        ["M", "That's the one. I'll take the plain lid bottle."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A wide mouth, please. / I'll take the plain lid bottle.",
      explanation:
        "남자는 입구가 넓은 물통을 원하고, 뚜껑에 고리가 달린 것 대신 밋밋한 뚜껑을 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five closed water bottles standing upright side by side as five choices, clean black line art on white. " +
          "① a NARROW bottle with a small cap and ONE LOOP HANDLE sticking up from the lid. " +
          "② a NARROW bottle with a small cap and a PLAIN flat lid with nothing on it. " +
          "③ a WIDE bottle with a broad cap and ONE LOOP HANDLE sticking up from the lid. " +
          "④ a WIDE bottle with a broad cap and a PLAIN flat lid with nothing on it. " +
          "⑤ a WIDE bottle with a broad cap and TWO LOOP HANDLES, one on each side of the lid.",
      },
      translation: [
        "W: 안녕하세요. 물통 찾으세요?",
        "M: 네, 축구 연습에 들고 갈 거예요.",
        "W: 입구가 넓은 것도 있고 좁은 것도 있어요.",
        "M: 넓은 걸로 주세요. 좁으면 얼음이 안 들어가요.",
        "W: 알겠습니다. 이 넓은 물통은 뚜껑에 고리가 달려 있어요.",
        "M: 고리는 가방 안에서 자꾸 뭔가에 걸려요.",
        "W: 그럼 뚜껑이 밋밋한 넓은 물통이 여기 있어요.",
        "M: 그거예요. 밋밋한 뚜껑으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 축제 부스 운영에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Hanbyul, is our class running a booth at the festival?"],
        ["M", "Yes, we're doing a board game corner."],
        ["W", "Where will our booth be set up?"],
        ["M", "In the second floor hallway, near the stairs."],
        ["W", "How long does the booth stay open?"],
        ["M", "From ten in the morning until three."],
        ["W", "How many of us work at one time?"],
        ["M", "Four people per shift, two shifts in all."],
        ["W", "Then I'll take the morning shift."],
      ],
      choices: ["준비 예산", "부스 종류", "부스 위치", "운영 시간", "한 번에 일하는 인원"],
      answer: 1,
      clue: "준비 예산은 대화에서 언급되지 않았다.",
      explanation:
        "부스 종류(보드게임), 위치(2층 복도), 운영 시간(10시~3시), 한 번에 일하는 인원(4명)은 언급되지만 준비 예산은 언급되지 않았다. 따라서 답은 ①이다.",
      translation: [
        "W: 한별아, 우리 반도 축제에 부스 해?",
        "M: 응, 보드게임 코너를 해.",
        "W: 우리 부스는 어디에 차려?",
        "M: 2층 복도, 계단 근처에.",
        "W: 부스는 얼마나 열어 둬?",
        "M: 아침 10시부터 3시까지.",
        "W: 한 번에 몇 명이 일해?",
        "M: 한 조에 네 명씩, 모두 두 조.",
        "W: 그럼 나는 오전 조 할게.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hello, is this the Hanbit Dental Clinic?"],
        ["M", "Yes, it is. How may I help you?"],
        ["W", "I have an appointment next Tuesday at four."],
        ["M", "Let me check. Under the name Sumin Yang?"],
        ["W", "That's right. My school has an exam that afternoon."],
        ["M", "I see. Shall I find you another time?"],
        ["W", "Yes, could you move it to Thursday at the same hour?"],
        ["M", "Thursday at four is open. I've changed it."],
      ],
      choices: [
        "진료를 처음 예약하려고",
        "예약을 취소하려고",
        "진료비를 물어보려고",
        "예약 날짜를 바꾸려고",
        "병원 위치를 물어보려고",
      ],
      answer: 4,
      clue: "Yes, could you move it to Thursday at the same hour?",
      explanation:
        "여자는 시험 때문에 화요일 예약을 목요일로 옮기려고 전화했다. 따라서 답은 ④이다.",
      translation: [
        "W: 여보세요, 한빛 치과죠?",
        "M: 네, 맞습니다. 무엇을 도와드릴까요?",
        "W: 다음 주 화요일 4시에 예약이 있어요.",
        "M: 확인해 볼게요. 양수민 님이시죠?",
        "W: 맞아요. 그날 오후에 학교 시험이 있어요.",
        "M: 그렇군요. 다른 시간으로 잡아 드릴까요?",
        "W: 네, 목요일 같은 시간으로 옮겨 주실 수 있나요?",
        "M: 목요일 4시가 비어 있네요. 바꿔 드렸습니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["M", "Sumin, what time does the club room open on Saturday?"],
        ["W", "The caretaker unlocks it at ten in the morning."],
        ["M", "Can we start working right at ten?"],
        ["W", "No, we have to move the tables back first."],
        ["M", "How long does moving the tables take?"],
        ["W", "About thirty minutes with the two of us."],
        ["M", "Then let's meet when the room actually opens."],
        ["W", "Good. I'll wait in front of the door."],
        ["M", "I'll bring the paint and brushes."],
      ],
      choices: ["9:00 a.m.", "10:00 a.m.", "9:30 a.m.", "10:30 a.m.", "11:00 a.m."],
      answer: 2,
      clue: "Then let's meet when the room actually opens.",
      explanation:
        "관리인이 10시에 동아리방을 열어 주고 두 사람은 방이 열릴 때 만나기로 했으므로 만나는 시각은 10시이다. 따라서 답은 ②이다.",
      translation: [
        "M: 수민아, 토요일에 동아리방 몇 시에 열어?",
        "W: 관리인 아저씨가 아침 10시에 열어 주셔.",
        "M: 10시에 바로 작업 시작할 수 있어?",
        "W: 아니, 탁자부터 제자리로 옮겨야 해.",
        "M: 탁자 옮기는 데 얼마나 걸려?",
        "W: 둘이 하면 30분쯤.",
        "M: 그럼 방이 실제로 열리는 시간에 만나자.",
        "W: 좋아. 나는 문 앞에서 기다릴게.",
        "M: 나는 페인트랑 붓 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hanbyul, you've been standing by the notice board a while."],
        ["M", "The exchange student list went up ten minutes ago."],
        ["W", "And your name isn't on it?"],
        ["M", "No, it isn't. I studied for the test all summer."],
        ["W", "Did they say how many they picked?"],
        ["M", "Six out of forty. I missed it by two places."],
        ["W", "Two places is so close."],
        ["M", "I gave up every weekend for that test."],
      ],
      choices: ["delighted", "bored", "curious", "thankful", "disappointed"],
      answer: 5,
      clue: "I gave up every weekend for that test.",
      explanation:
        "여름 내내 준비한 교환 학생 시험에서 두 자리 차로 떨어졌다고 했으므로 남자의 심정은 '실망한(disappointed)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 한별아, 게시판 앞에 한참 서 있네.",
        "M: 10분 전에 교환 학생 명단이 올라왔어.",
        "W: 네 이름이 없어?",
        "M: 없어. 여름 내내 그 시험 준비했는데.",
        "W: 몇 명 뽑았대?",
        "M: 마흔 명 중 여섯. 두 자리 차로 떨어졌어.",
        "W: 두 자리면 정말 아깝다.",
        "M: 그 시험 때문에 주말을 다 포기했는데.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "Excuse me, your headlight is still on."],
        ["M", "Oh, thank you. I'll turn it off."],
        ["ANN", "Number two."],
        ["W", "How much is parking for one hour?"],
        ["M", "Two dollars an hour."],
        ["ANN", "Number three."],
        ["W", "Is this space free?"],
        ["M", "Yes, nobody has parked there."],
        ["ANN", "Number four."],
        ["W", "Where is the elevator to the mall?"],
        ["M", "Around that corner."],
        ["ANN", "Number five."],
        ["W", "Do I pay before I leave?"],
        ["M", "Yes, at the machine by the exit."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Excuse me, your headlight is still on.",
      explanation:
        "그림은 주차장에서 남자가 차에서 내려 걸어가는데 차의 전조등이 켜져 있고, 여자가 그것을 가리키며 알려 주는 장면이다. 따라서 답은 ①이다.",
      figure: {
        kind: "scene",
        scene:
          "In an underground parking area, clean black line art on a plain white background, no writing anywhere. " +
          "A man has just closed his car door and is walking away, while the car's headlights are still shining with bright rays drawn around them. " +
          "A woman a few steps behind him points at the glowing headlights and calls out to him. " +
          "Other parked cars and concrete pillars are drawn simply in the background.",
      },
      translation: [
        "① W: 저기요, 전조등이 아직 켜져 있어요. / M: 아, 감사합니다. 끌게요.",
        "② W: 주차 한 시간에 얼마예요? / M: 시간당 2달러입니다.",
        "③ W: 이 자리 비었나요? / M: 네, 아무도 안 댔어요.",
        "④ W: 상가로 가는 엘리베이터가 어디예요? / M: 저 모퉁이를 돌면 있어요.",
        "⑤ W: 나가기 전에 계산하나요? / M: 네, 출구 옆 기계에서요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 여자가 남자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hanbyul, you stay late for the coding club, don't you?"],
        ["M", "Yes, until six in the computer room."],
        ["W", "Our class survey file is on computer number three."],
        ["M", "Didn't you email it to yourself?"],
        ["W", "I meant to, but my bus came and I ran."],
        ["M", "So the file is still sitting on the school computer?"],
        ["W", "Right. Could you send it to my email tonight?"],
        ["M", "Sure. I'll do it as soon as I sit down."],
      ],
      choices: ["파일을 이메일로 보내 주기", "설문 정리해 주기", "컴퓨터 끄기", "동아리 대신 가기", "버스 같이 타기"],
      answer: 1,
      clue: "Right. Could you send it to my email tonight?",
      explanation:
        "여자는 학교 컴퓨터에 남아 있는 설문 파일을 자기 이메일로 보내 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "W: 한별아, 너 코딩 동아리 때문에 늦게까지 남지?",
        "M: 응, 컴퓨터실에서 6시까지.",
        "W: 우리 반 설문 파일이 3번 컴퓨터에 있어.",
        "M: 너한테 메일로 안 보내 놨어?",
        "W: 보내려다가 버스가 와서 뛰었어.",
        "M: 그럼 파일이 아직 학교 컴퓨터에 있는 거네?",
        "W: 맞아. 오늘 밤에 내 이메일로 보내 줄 수 있어?",
        "M: 그럼. 앉자마자 보낼게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 벼룩시장에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "M",
          "Hello, students. The autumn flea market opens next Saturday. " +
            "It will be held on the front playground from ten until three. " +
            "Each class gets one table, and tables are assigned by lottery. " +
            "You may sell books, clothes, and small household items. " +
            "All the earnings go to the local animal shelter. " +
            "Come and support your classmates.",
        ],
      ],
      choices: ["열리는 날", "운영 시간", "탁자 배정 방법", "참가 신청 마감일", "팔 수 있는 물건"],
      answer: 4,
      clue: "참가 신청 마감일은 방송에서 언급되지 않았다.",
      explanation:
        "열리는 날(다음 주 토요일), 운영 시간(10시~3시), 탁자 배정 방법(추첨), 팔 수 있는 물건(책·옷·작은 생활용품)은 언급되지만 신청 마감일은 언급되지 않았다. 따라서 답은 ④이다.",
      translation: [
        "M: 안녕하세요, 학생 여러분. 가을 벼룩시장이 다음 주 토요일에 열립니다. 앞 운동장에서 10시부터 3시까지 진행됩니다. 반마다 탁자 하나씩 받고, 자리는 추첨으로 정합니다. 책, 옷, 작은 생활용품을 팔 수 있습니다. 수익금은 모두 지역 동물 보호소에 전달합니다. 오셔서 친구들을 응원해 주세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "W",
          "This is a job most of us meet only after an accident or a fire. " +
            "The person rides in a white van with a loud siren on the roof. " +
            "They carry a folding bed and a heavy orange bag of equipment. " +
            "On the way they keep talking to the patient to stay awake. " +
            "Every second they save can change someone's whole life.",
        ],
      ],
      choices: ["소방관", "구급 대원", "경찰관", "의사", "간호사"],
      answer: 2,
      clue: "The person rides in a white van with a loud siren on the roof.",
      explanation:
        "사이렌을 단 흰 차를 타고 접이식 들것과 주황색 장비 가방을 들고 환자에게 계속 말을 거는 사람은 구급 대원이다. 따라서 답은 ②이다.",
      translation: [
        "W: 이 직업은 대부분의 사람이 사고나 화재 뒤에야 만납니다. 이 사람은 지붕에 요란한 사이렌이 달린 흰 차를 타고 다닙니다. 접이식 침대와 무거운 주황색 장비 가방을 들고 다닙니다. 가는 길에 환자가 깨어 있도록 계속 말을 겁니다. 이들이 아끼는 1초가 누군가의 인생 전체를 바꿀 수 있습니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "How often does this bus run?"],
        ["W", "Every twenty minutes."],
        ["ANN", "Number two."],
        ["M", "Could you spell your name for me?"],
        ["W", "It's S-U-M-I-N."],
        ["ANN", "Number three."],
        ["M", "What did the doctor tell you?"],
        ["W", "To rest for a week."],
        ["ANN", "Number four."],
        ["M", "Shall we share this umbrella?"],
        ["W", "Yes, thanks. It's pouring."],
        ["ANN", "Number five."],
        ["M", "Where did you put the scissors?"],
        ["W", "I have two older brothers."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "Where did you put the scissors?",
      explanation:
        "가위를 어디에 뒀는지 묻는 말에 오빠가 둘이라고 답했으므로 ⑤의 대화가 어색하다. 따라서 답은 ⑤이다.",
      translation: [
        "① M: 이 버스 얼마나 자주 와? / W: 20분마다.",
        "② M: 이름 철자를 알려 주시겠어요? / W: S-U-M-I-N이에요.",
        "③ M: 의사 선생님이 뭐라셔? / W: 일주일 쉬라고 하셨어.",
        "④ M: 이 우산 같이 쓸까? / W: 응, 고마워. 비가 쏟아지네.",
        "⑤ M: 가위 어디에 뒀어? / W: 나는 오빠가 둘이야.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, the club bazaar opens in fifteen minutes."],
        ["W", "I know. All the goods are laid out on the table."],
        ["M", "Good. Did you write the price tags?"],
        ["W", "Yes, one for every item, during lunch."],
        ["M", "Great. But we have no change in the cash box."],
        ["W", "Oh, the coin bag is still in the club room."],
        ["M", "I have to set up the sign at the entrance."],
        ["W", "Then I'll run up and get the coin bag now."],
      ],
      choices: ["물건 진열하기", "가격표 쓰기", "동전 가방 가져오기", "안내판 세우기", "손님 맞이하기"],
      answer: 3,
      clue: "Then I'll run up and get the coin bag now.",
      explanation:
        "거스름돈이 든 동전 가방이 동아리방에 있고 남자는 안내판을 세워야 해서, 여자가 동전 가방을 가져오겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "M: 수민아, 동아리 바자회가 15분 뒤에 열려.",
        "W: 알아. 물건은 다 탁자에 진열했어.",
        "M: 잘했다. 가격표는 썼어?",
        "W: 응, 점심시간에 물건마다 하나씩.",
        "M: 좋아. 그런데 돈통에 거스름돈이 없어.",
        "W: 아, 동전 가방이 아직 동아리방에 있어.",
        "M: 나는 입구에 안내판을 세워야 해.",
        "W: 그럼 내가 지금 올라가서 동전 가방 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 남자가 예약할 연습실을 고르시오.",
      lines: [
        ["W", "Hanbyul, which practice room are you booking for the band?"],
        ["M", "Let me look at the five of them again."],
        ["W", "How many of you play at once?"],
        ["M", "Six, so a room for four is too small."],
        ["W", "Okay. Do you need a drum set in the room?"],
        ["M", "Yes, carrying our own drums is impossible."],
        ["W", "Got it. What about the hourly fee?"],
        ["M", "Under fifteen thousand won an hour, split six ways."],
        ["W", "Then only one room on this list works."],
        ["M", "Good. I'll book it right after school."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 1,
      clue: "Six, so a room for four is too small.",
      explanation:
        "6명 이상이 들어가고, 드럼이 있으며, 시간당 1만 5천 원 미만인 방을 고른다. 세 조건을 모두 채우는 것은 ①이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Seats: 10 / Drums: Yes / Fee: 14,000 won" },
          { no: 2, label: "②", value: "Seats: 4 / Drums: Yes / Fee: 12,000 won" },
          { no: 3, label: "③", value: "Seats: 8 / Drums: No / Fee: 10,000 won" },
          { no: 4, label: "④", value: "Seats: 8 / Drums: Yes / Fee: 20,000 won" },
          { no: 5, label: "⑤", value: "Seats: 4 / Drums: No / Fee: 8,000 won" },
        ],
      },
      translation: [
        "W: 한별아, 밴드 연습실 어디로 예약할 거야?",
        "M: 다섯 개 다시 볼게.",
        "W: 한 번에 몇 명이 연주해?",
        "M: 여섯 명이라 4인실은 너무 작아.",
        "W: 알겠어. 방에 드럼이 있어야 해?",
        "M: 응, 우리 드럼을 들고 다니는 건 불가능해.",
        "W: 그렇구나. 시간당 요금은?",
        "M: 여섯이 나누니까 시간당 1만 5천 원 미만.",
        "W: 그럼 이 목록에서 되는 건 하나뿐이야.",
        "M: 좋아. 방과 후에 바로 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 봉사 활동을 갈 날짜를 고르시오.",
      lines: [
        ["W", "Hanbyul, when can we help at the food bank?"],
        ["M", "How about December 3rd? That's next Wednesday."],
        ["W", "The food bank only takes volunteers on weekends."],
        ["M", "Then what about December 6th?"],
        ["W", "My cousin's wedding is on the 6th."],
        ["M", "Hmm. I'm free on December 20th."],
        ["W", "But the winter program ends on the 15th."],
        ["M", "Oh, right. Then let's go on December 13th."],
        ["W", "December 13th works. It's a Saturday."],
        ["M", "Perfect. Let's take the nine o'clock bus."],
      ],
      choices: ["12월 3일", "12월 6일", "12월 15일", "12월 13일", "12월 20일"],
      answer: 4,
      clue: "Oh, right. Then let's go on December 13th.",
      explanation:
        "3일은 주중이라 받지 않고, 6일에는 결혼식이 있으며, 20일은 프로그램이 끝난 뒤다. 두 사람은 12월 13일에 가기로 한다. 따라서 답은 ④이다.",
      translation: [
        "W: 한별아, 푸드뱅크 봉사 언제 갈까?",
        "M: 12월 3일 어때? 다음 주 수요일이야.",
        "W: 푸드뱅크는 주말에만 자원봉사를 받아.",
        "M: 그럼 12월 6일은?",
        "W: 6일에 사촌 언니 결혼식이 있어.",
        "M: 음. 나는 12월 20일이 비어.",
        "W: 그런데 겨울 프로그램이 15일에 끝나.",
        "M: 아, 맞다. 그럼 12월 13일에 가자.",
        "W: 12월 13일 괜찮아. 토요일이야.",
        "M: 좋아. 9시 버스 타자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 남자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Hanbyul, why is your nose so sunburned today?"],
        ["M", "I was out on the riverbank all Sunday morning."],
        ["W", "Did you go fishing there with your father?"],
        ["M", "No, our club pulled trash out of the water."],
        ["W", "How much did the whole group collect?"],
        ["M", "Nine big bags, mostly cans and plastic bottles."],
        ["W", "That is a lot of trash for one morning."],
        ["M", "The hardest part was reaching the bottles under the bridge."],
        ["W", "Are you going back there again next month?"],
        ["M", "Yes, and the water already looked clearer afterward."],
      ],
      choices: ["낚시하기", "강에서 쓰레기 줍기", "물놀이하기", "강변 걷기", "사진 찍기"],
      answer: 2,
      clue: "No, our club pulled trash out of the water.",
      explanation:
        "남자는 일요일 오전에 동아리 친구들과 강에서 쓰레기를 아홉 자루 건져 냈다고 했다. 따라서 답은 ②이다.",
      translation: [
        "W: 한별아, 오늘 코가 왜 이렇게 탔어?",
        "M: 일요일 오전 내내 강변에 나가 있었어.",
        "W: 거기서 아버지랑 낚시했어?",
        "M: 아니, 우리 동아리가 물에서 쓰레기를 건졌어.",
        "W: 다 같이 얼마나 모았어?",
        "M: 큰 자루 아홉 개. 대부분 캔이랑 페트병이었어.",
        "W: 오전 한나절에 쓰레기가 정말 많았네.",
        "M: 제일 힘든 건 다리 밑에 있는 병을 건지는 거였어.",
        "W: 다음 달에도 또 가?",
        "M: 응, 그리고 끝나고 보니 물이 벌써 더 맑아 보였어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "W",
          "May I have your attention, please? This is the school office. " +
            "The main gate will be closed tomorrow for repair work. " +
            "Everyone should come in through the side gate by the gym. " +
            "The work will take one full day, from morning until evening. " +
            "Please leave home a few minutes earlier than usual. " +
            "Thank you for your cooperation.",
        ],
      ],
      choices: [
        "등교 시간 변경을 알리려고",
        "체육관 공사를 알리려고",
        "교통 안전 교육을 알리려고",
        "지각 방지를 당부하려고",
        "정문 폐쇄를 알리려고",
      ],
      answer: 5,
      clue: "The main gate will be closed tomorrow for repair work.",
      explanation:
        "내일 정문이 수리로 닫히니 체육관 옆 쪽문으로 들어오라고 알리는 방송이다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안내 말씀 드립니다. 행정실입니다. 내일 수리 공사로 정문이 닫힙니다. 모두 체육관 옆 쪽문으로 들어와 주세요. 공사는 아침부터 저녁까지 하루 종일 진행됩니다. 평소보다 몇 분 일찍 집에서 나와 주세요. 협조해 주셔서 감사합니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 여자가 지불할 금액을 고르시오.",
      lines: [
        ["M", "Welcome to the sports shop. What can I get you?"],
        ["W", "Four pairs of socks and two water bottles, please."],
        ["M", "Socks are five dollars a pair and a bottle is ten."],
        ["W", "So the total is forty dollars."],
        ["M", "That's right. Do you need a bag?"],
        ["W", "No, thank you. I brought my own."],
        ["M", "All right. Team orders get eight dollars off."],
        ["W", "That's good news. Here you are."],
      ],
      choices: ["$26", "$28", "$32", "$30", "$40"],
      answer: 3,
      clue: "All right. Team orders get eight dollars off.",
      explanation:
        "양말 4켤레 20달러와 물병 2개 20달러를 더하면 40달러이고, 팀 주문 할인 8달러를 빼면 32달러이다. 따라서 답은 ③이다.",
      translation: [
        "M: 스포츠 용품점에 오신 걸 환영합니다. 무엇을 드릴까요?",
        "W: 양말 네 켤레랑 물병 두 개 주세요.",
        "M: 양말은 한 켤레에 5달러, 물병은 10달러입니다.",
        "W: 그럼 모두 40달러네요.",
        "M: 맞습니다. 봉투 필요하세요?",
        "W: 아니요, 괜찮아요. 제 가방 가져왔어요.",
        "M: 알겠습니다. 팀 주문은 8달러 할인됩니다.",
        "W: 좋은 소식이네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sumin, you've been carrying that thick dictionary all week."],
        ["W", "I look up every word I don't know while I read."],
        ["M", "Every single one, right in the middle of a page?"],
        ["W", "Yes, otherwise I feel like I'm missing something."],
        ["M", "But then you stop reading every two lines."],
        ["W", "That's true. A short story takes me two hours."],
        ["M", "Try marking the word and reading to the end first."],
        ["W", "Won't I forget what the marks were for?"],
        ["M", "Look them all up together when you finish the page."],
      ],
      choices: [
        "I'll try that tonight.",
        "I never use a dictionary.",
        "I read very quickly already.",
        "I'll look up every word twice.",
        "Let's stop reading stories.",
      ],
      answer: 1,
      clue: "Look them all up together when you finish the page.",
      explanation:
        "남자가 표시해 두었다가 한 쪽을 다 읽고 한꺼번에 찾아보라고 했으므로, 오늘 밤에 해 보겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 수민아, 일주일 내내 그 두꺼운 사전을 들고 다니네.",
        "W: 읽으면서 모르는 낱말을 다 찾아봐.",
        "M: 한 낱말도 빠짐없이, 읽는 중간에?",
        "W: 응, 안 그러면 뭔가 놓치는 것 같아.",
        "M: 그런데 그러면 두 줄마다 읽기를 멈추잖아.",
        "W: 맞아. 짧은 이야기 하나에 두 시간 걸려.",
        "M: 낱말을 표시해 두고 끝까지 먼저 읽어 봐.",
        "W: 표시한 게 뭐였는지 잊어버리지 않을까?",
        "M: 한 쪽을 다 읽고 한꺼번에 찾아봐.",
        "W: 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hanbyul, your running shoes squeak on every step."],
        ["M", "They started doing that after the rainy week."],
        ["W", "Did you dry them somewhere warm?"],
        ["M", "Yes, right on top of the heater overnight."],
        ["W", "Fast heat hardens the sole and makes it squeak."],
        ["M", "I thought that was the quickest way to dry them."],
        ["W", "It is quick, but it ruins the rubber."],
        ["M", "Then how should I dry them next time?"],
        ["W", "Stuff them with newspaper and leave them in the shade."],
      ],
      choices: [
        "My shoes are never wet.",
        "The heater is the best way.",
        "I'll buy new shoes tonight.",
        "I'll do that next time.",
        "I don't own running shoes.",
      ],
      answer: 4,
      clue: "Stuff them with newspaper and leave them in the shade.",
      explanation:
        "여자가 신문지를 채워 그늘에 말리라고 알려 주었으므로, 다음에 그렇게 하겠다는 ④가 가장 자연스럽다.",
      translation: [
        "W: 한별아, 네 운동화가 걸음마다 삑삑거려.",
        "M: 비 오던 주 지나고부터 그래.",
        "W: 따뜻한 데서 말렸어?",
        "M: 응, 밤새 난로 위에 올려놨어.",
        "W: 빠른 열은 밑창을 굳혀서 소리 나게 해.",
        "M: 그게 제일 빨리 말리는 방법인 줄 알았어.",
        "W: 빠르긴 한데 고무를 망가뜨려.",
        "M: 그럼 다음엔 어떻게 말려야 해?",
        "W: 신문지를 채워서 그늘에 둬.",
        "M: 다음엔 그렇게 할게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Hanbyul, nobody signed up for our club's open class."],
        ["M", "Where did you announce it?"],
        ["W", "In the club newsletter we email once a month."],
        ["M", "Does anyone actually open that email?"],
        ["W", "Probably not. Most of them go unread."],
        ["M", "So the announcement never reached anyone."],
        ["W", "Then where should I announce it instead?"],
        ["M", "Somewhere people already gather and stand around."],
        ["W", "Like where, exactly?"],
        ["M", "The board beside the vending machines at lunch."],
      ],
      choices: [
        "Our club has no members.",
        "I'll put a notice there tomorrow.",
        "Everyone reads the newsletter.",
        "There are no vending machines.",
        "Let's cancel the open class.",
      ],
      answer: 2,
      clue: "The board beside the vending machines at lunch.",
      explanation:
        "남자가 점심시간에 자판기 옆 게시판에 알리라고 했으므로, 내일 거기에 안내문을 붙이겠다는 ②가 가장 자연스럽다.",
      translation: [
        "W: 한별아, 우리 동아리 공개 수업에 아무도 신청을 안 했어.",
        "M: 어디에 알렸는데?",
        "W: 한 달에 한 번 이메일로 보내는 동아리 소식지에.",
        "M: 그 이메일을 실제로 여는 사람이 있어?",
        "W: 아마 없을걸. 대부분 안 읽혀.",
        "M: 그럼 공지가 아무한테도 안 닿은 거네.",
        "W: 그럼 어디에 알려야 해?",
        "M: 사람들이 이미 모여서 서 있는 곳에.",
        "W: 예를 들면 어디?",
        "M: 점심시간에 자판기 옆 게시판.",
        "W: 내일 거기에 안내문 붙일게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Jiho가 Nayun에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Jiho : ________________",
      lines: [
        [
          "M",
          "Jiho and Nayun are packing up after the club meeting. " +
            "Nayun has zipped her bag and is heading for the stairs. " +
            "Jiho sees that her umbrella is still hooked on the back of her chair. " +
            "It has been raining hard since the morning. " +
            "He wants to tell her before she reaches the front door. " +
            "In this situation, what would Jiho most likely say to Nayun?",
        ],
      ],
      choices: [
        "Let's stay a little longer.",
        "The rain stopped an hour ago.",
        "I'll carry your bag downstairs.",
        "You should buy a new umbrella.",
        "Your umbrella is on your chair.",
      ],
      answer: 5,
      clue: "Jiho sees that her umbrella is still hooked on the back of her chair.",
      explanation:
        "비가 많이 오는데 나윤이의 우산이 의자에 걸린 채 남아 있으므로, 그 사실을 알려 주는 ⑤가 가장 적절하다.",
      translation: [
        "M: 지호와 나윤이는 동아리 모임이 끝나고 짐을 챙기고 있습니다. 나윤이는 가방을 잠그고 계단 쪽으로 가고 있습니다. 지호는 나윤이의 우산이 아직 의자 등받이에 걸려 있는 것을 봅니다. 아침부터 비가 많이 오고 있습니다. 지호는 나윤이가 정문에 닿기 전에 알려 주고 싶습니다. 이런 상황에서 지호가 나윤이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
