/** 중3 듣기 34회 — 사람이 직접 쓴 회차 (2026-09-29) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 34회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 남자가 주문할 케이크를 고르시오.",
      lines: [
        ["W", "Welcome. Are you ordering a cake for someone?"],
        ["M", "Yes, for my sister's graduation next week."],
        ["W", "Would you like a round cake or a square one?"],
        ["M", "Square, please. It's easier to cut for many people."],
        ["W", "Shall I put fresh strawberries on the top?"],
        ["M", "No fruit. She doesn't like it on cream."],
        ["W", "Then how about a chocolate plate with a message?"],
        ["M", "Yes, one chocolate plate right in the center."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Square, please. It's easier to cut for many people. / Yes, one chocolate plate right in the center.",
      explanation:
        "남자는 네모난 케이크에 과일 없이 가운데 초콜릿 판이 있는 것을 주문했다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five decorated cakes side by side as five choices, clean black line art on white, no writing or letters anywhere. " +
          "① a ROUND cake topped with several STRAWBERRIES. " +
          "② a ROUND cake with a blank rectangular CHOCOLATE PLATE standing in the center. " +
          "③ a SQUARE cake topped with several STRAWBERRIES. " +
          "④ a SQUARE cake with a blank rectangular CHOCOLATE PLATE standing in the center, no fruit at all. " +
          "⑤ a SQUARE cake with both STRAWBERRIES around the edge and a blank CHOCOLATE PLATE in the center.",
      },
      translation: [
        "W: 어서 오세요. 누구 드릴 케이크인가요?",
        "M: 네, 다음 주 동생 졸업식용이에요.",
        "W: 둥근 케이크로 하시겠어요, 네모난 것으로 하시겠어요?",
        "M: 네모로 주세요. 여러 명이 나눠 먹기 좋아요.",
        "W: 위에 생딸기를 올려 드릴까요?",
        "M: 과일은 빼 주세요. 크림 위에 얹은 걸 싫어해요.",
        "W: 그럼 글자 넣은 초콜릿 판은 어떠세요?",
        "M: 네, 초콜릿 판 하나를 가운데에 놓아 주세요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 체험 학습에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["M", "Seoyeon, where are we going for the field trip?"],
        ["W", "To the science park in the next city."],
        ["M", "How long does the bus take to get there?"],
        ["W", "About an hour and a half each way."],
        ["M", "Do we bring our own lunch?"],
        ["W", "Yes, the teacher said to pack sandwiches."],
        ["M", "What should we wear that day?"],
        ["W", "Our gym clothes, because we walk a lot."],
      ],
      choices: [
        "가는 장소",
        "걸리는 시간",
        "점심 준비 방법",
        "입어야 할 옷",
        "돌아오는 시각",
      ],
      answer: 5,
      clue: "To the science park in the next city.",
      explanation:
        "장소, 이동 시간, 점심, 복장은 말했지만 돌아오는 시각은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 서연아, 체험 학습 어디로 가?",
        "W: 옆 도시 과학 공원으로.",
        "M: 버스로 얼마나 걸려?",
        "W: 한 시간 반쯤, 한쪽으로.",
        "M: 점심은 각자 가져가?",
        "W: 응, 선생님이 샌드위치 싸 오라고 하셨어.",
        "M: 그날 뭘 입어야 해?",
        "W: 체육복. 많이 걸어야 하거든.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 여자가 남자를 찾아온 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hi, Chaeeun. Do you need something from the club room?"],
        ["W", "I heard you kept the old newspaper files here."],
        ["M", "We do, in the cabinet by the window."],
        ["W", "I'm writing about our school's history."],
        ["M", "Which year are you looking for?"],
        ["W", "The issues from five years ago, if you have them."],
        ["M", "They're in the bottom drawer."],
        ["W", "Could I borrow them for two days?"],
      ],
      choices: [
        "자료를 빌리려고",
        "동아리에 가입하려고",
        "약속을 정하려고",
        "물건을 돌려주려고",
        "선생님을 찾으려고",
      ],
      answer: 1,
      clue: "Could I borrow them for two days?",
      explanation:
        "여자는 예전 신문 자료를 이틀 빌리려고 찾아왔다. 따라서 답은 ①이다.",
      translation: [
        "M: 안녕, 채은아. 동아리방에서 뭐 필요해?",
        "W: 여기에 예전 신문 자료를 보관한다고 들었어.",
        "M: 맞아, 창문 옆 장에 있어.",
        "W: 우리 학교 역사에 대해 글을 쓰고 있어.",
        "M: 몇 년도 걸 찾는데?",
        "W: 5년 전 것들, 있으면.",
        "M: 맨 아래 서랍에 있어.",
        "W: 이틀만 빌려도 될까?",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 연습을 시작할 시각을 고르시오.",
      lines: [
        ["W", "Taemin, when can we practice the duet today?"],
        ["M", "The music room is free from five o'clock."],
        ["W", "My math class ends at five fifteen."],
        ["M", "Then five o'clock is too early for you."],
        ["W", "Can we start at five thirty instead?"],
        ["M", "I need ten minutes to tune the guitar first."],
        ["W", "So you'll be ready by five thirty anyway."],
        ["M", "Right. Let's begin at five thirty."],
        ["W", "I'll bring the sheet music with me."],
      ],
      choices: ["5:00 p.m.", "5:15 p.m.", "5:30 p.m.", "5:45 p.m.", "6:00 p.m."],
      answer: 3,
      clue: "Right. Let's begin at five thirty.",
      explanation:
        "여자의 수업이 5시 15분에 끝나 5시 30분에 연습을 시작하기로 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 태민아, 오늘 이중창 언제 연습할까?",
        "M: 음악실이 5시부터 비어.",
        "W: 내 수학 수업이 5시 15분에 끝나.",
        "M: 그럼 5시는 너한테 너무 이르네.",
        "W: 대신 5시 30분에 시작할까?",
        "M: 나는 먼저 기타 조율에 10분이 필요해.",
        "W: 그럼 어차피 5시 30분이면 준비되겠다.",
        "M: 맞아. 5시 30분에 시작하자.",
        "W: 악보는 내가 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 남자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Jiseok, why are you staring at your shoes?"],
        ["M", "I promised to bring the ball for today's match."],
        ["W", "Don't tell me you left it at home."],
        ["M", "It's still sitting by my front door."],
        ["W", "Everyone is already waiting on the field."],
        ["M", "Twenty people came here because of me."],
        ["W", "We can borrow one from the gym teacher."],
        ["M", "I still feel terrible about wasting their time."],
      ],
      choices: ["excited", "relaxed", "curious", "sorry", "surprised"],
      answer: 4,
      clue: "I still feel terrible about wasting their time.",
      explanation:
        "공을 두고 와서 친구들의 시간을 뺏은 것을 미안해하고 있다. 따라서 답은 ④이다.",
      translation: [
        "W: 지석아, 왜 신발만 쳐다보고 있어?",
        "M: 오늘 경기에 공 가져오겠다고 했거든.",
        "W: 설마 집에 두고 온 거야?",
        "M: 아직 우리 집 현관에 있어.",
        "W: 다들 벌써 운동장에서 기다려.",
        "M: 나 때문에 스무 명이 왔는데.",
        "W: 체육 선생님께 하나 빌리면 돼.",
        "M: 그래도 시간 뺏은 게 너무 미안해.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "Does this bus go downtown?"],
        ["W", "Yes, it stops at city hall."],
        ["ANN", "Number two."],
        ["M", "May I sit here?"],
        ["W", "Sorry, my friend is coming."],
        ["ANN", "Number three."],
        ["M", "Please take this seat."],
        ["W", "Thank you, young man."],
        ["ANN", "Number four."],
        ["M", "How much is the fare?"],
        ["W", "It's one thousand three hundred won."],
        ["ANN", "Number five."],
        ["M", "Is the next stop the market?"],
        ["W", "No, it's two stops away."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Please take this seat.",
      explanation:
        "그림은 버스 안에서 남학생이 일어나 할머니께 자리를 양보하는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a city bus, clean black line art on a plain white background, no writing or letters anywhere. " +
          "A boy student wearing a backpack has just stood up from his seat and gestures toward the empty seat with an open hand. " +
          "An elderly woman with a shopping bag stands beside him, holding a ceiling handle. " +
          "Other passengers and bus windows are drawn simply in the background.",
      },
      translation: [
        "① M: 이 버스 시내 가나요? / W: 네, 시청에 서요.",
        "② M: 여기 앉아도 될까요? / W: 죄송해요, 친구가 와요.",
        "③ M: 여기 앉으세요. / W: 고마워요, 학생.",
        "④ M: 요금이 얼마예요? / W: 1,300원입니다.",
        "⑤ M: 다음 정류장이 시장인가요? / W: 아니요, 두 정거장 더 가요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hyejin, are you going to the stationery shop after school?"],
        ["W", "Yes, I need new pens for the exam."],
        ["M", "Our class is making posters tomorrow morning."],
        ["W", "Do we have enough paper for that?"],
        ["M", "Paper is fine, but the glue sticks are all dry."],
        ["W", "How many do we need?"],
        ["M", "Could you buy five glue sticks on your way?"],
        ["W", "No problem. I'll keep the receipt."],
      ],
      choices: [
        "풀을 사다 주기",
        "포스터를 그려 주기",
        "종이를 나눠 주기",
        "청소를 도와주기",
        "자리를 바꿔 주기",
      ],
      answer: 1,
      clue: "Could you buy five glue sticks on your way?",
      explanation:
        "남자는 가는 길에 풀 다섯 개를 사다 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 혜진아, 방과 후에 문구점 가?",
        "W: 응, 시험 볼 새 펜이 필요해.",
        "M: 우리 반이 내일 아침에 포스터를 만들어.",
        "W: 종이는 충분해?",
        "M: 종이는 괜찮은데 딱풀이 다 말랐어.",
        "W: 몇 개 필요해?",
        "M: 가는 길에 딱풀 다섯 개만 사다 줄래?",
        "W: 그래. 영수증 챙겨 둘게.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 텃밭 가꾸기에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Let me tell you about our school garden. " +
            "The garden sits behind the science building. " +
            "We will plant lettuce and cherry tomatoes this spring. " +
            "Each class takes care of it for one week in turn. " +
            "Bring your own gloves on the day your class works.",
        ],
      ],
      choices: [
        "텃밭이 있는 곳",
        "심을 작물",
        "관리하는 차례",
        "가져와야 할 물건",
        "수확물을 나누는 방법",
      ],
      answer: 5,
      clue: "The garden sits behind the science building.",
      explanation:
        "위치, 작물, 차례, 준비물은 말했지만 수확물을 나누는 방법은 말하지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 학생 여러분, 안녕하세요. 학교 텃밭에 대해 알려 드립니다. 텃밭은 과학관 뒤에 있습니다. 올봄에는 상추와 방울토마토를 심습니다. 각 반이 한 주씩 돌아가며 돌봅니다. 우리 반이 일하는 날에는 장갑을 챙겨 오세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "You use this when you want to see something far away. " +
            "You hold it up and look through it with both eyes. " +
            "Bird watchers carry it into the mountains. " +
            "People also take it to a baseball stadium. " +
            "It makes distant things look much closer than they are.",
        ],
      ],
      choices: ["안경", "돋보기", "카메라", "손전등", "쌍안경"],
      answer: 5,
      clue: "You hold it up and look through it with both eyes.",
      explanation:
        "두 눈으로 들여다보며 먼 것을 가까이 보는 도구는 쌍안경이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 이것은 멀리 있는 것을 보고 싶을 때 씁니다. 들어 올려서 두 눈으로 들여다봅니다. 새를 관찰하는 사람들은 이것을 산으로 가져갑니다. 야구장에 가져가는 사람들도 있습니다. 먼 것을 실제보다 훨씬 가깝게 보이게 합니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How often do you go swimming?"],
        ["M", "Twice a week, usually."],
        ["ANN", "Number two."],
        ["W", "Could you turn down the music?"],
        ["M", "Sure, sorry about that."],
        ["ANN", "Number three."],
        ["W", "What's the weather like outside?"],
        ["M", "Cold and windy today."],
        ["ANN", "Number four."],
        ["W", "Why were you late this morning?"],
        ["M", "My favorite color is green."],
        ["ANN", "Number five."],
        ["W", "Have you ever been to Jeju?"],
        ["M", "Twice, both times in summer."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "Why were you late this morning?",
      explanation:
        "늦은 이유를 묻는 말에 좋아하는 색을 답했으므로 ④의 대화가 어색하다. 따라서 답은 ④이다.",
      translation: [
        "① W: 수영 얼마나 자주 가? / M: 보통 일주일에 두 번.",
        "② W: 음악 좀 줄여 줄래? / M: 그래, 미안해.",
        "③ W: 밖에 날씨 어때? / M: 오늘은 춥고 바람 불어.",
        "④ W: 오늘 아침에 왜 늦었어? / M: 내가 좋아하는 색은 초록색이야.",
        "⑤ W: 제주도에 가 본 적 있어? / M: 두 번. 둘 다 여름에.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 여자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Areum, the art contest entries go out today."],
        ["W", "I finished my painting last night."],
        ["M", "Did you write your name on the back?"],
        ["W", "I don't think I did, actually."],
        ["M", "They throw away works without a name."],
        ["W", "Where is my painting right now?"],
        ["M", "Still on the shelf in the art room."],
        ["W", "I'll go and write my name on it."],
      ],
      choices: [
        "그림을 다시 그리기",
        "선생님께 여쭤보기",
        "집에 가기",
        "미술실에 가서 이름을 쓰기",
        "친구를 도와주기",
      ],
      answer: 4,
      clue: "I'll go and write my name on it.",
      explanation:
        "여자는 미술실에 가서 그림에 이름을 쓰겠다고 했다. 따라서 답은 ④이다.",
      translation: [
        "M: 아름아, 오늘 미술 대회 작품 나가.",
        "W: 어젯밤에 그림 다 그렸어.",
        "M: 뒤에 이름 썼어?",
        "W: 안 쓴 것 같아, 사실.",
        "M: 이름 없는 작품은 버려.",
        "W: 내 그림 지금 어디 있지?",
        "M: 아직 미술실 선반에 있어.",
        "W: 가서 이름 써 놓을게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 두 사람이 예약할 방을 고르시오.",
      lines: [
        ["W", "Minhyuk, let's book a study room for our group."],
        ["M", "There are five rooms left on the screen."],
        ["W", "We are six people, so it must hold six."],
        ["M", "Two of them are only for four."],
        ["W", "We also need a whiteboard for the diagrams."],
        ["M", "Not every room has one."],
        ["W", "And can we keep it under ten thousand won?"],
        ["M", "One of them costs twelve thousand."],
        ["W", "Then there's only one room left for us."],
        ["M", "I'll book it before someone else does."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 5,
      clue: "We are six people, so it must hold six.",
      explanation:
        "6명 이상, 화이트보드 있음, 1만 원 이하인 방을 고른다. 세 조건을 모두 채우는 것은 ⑤이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Seats: 4 / Whiteboard: Yes / Price: 8,000 won" },
          { no: 2, label: "②", value: "Seats: 4 / Whiteboard: No / Price: 6,000 won" },
          { no: 3, label: "③", value: "Seats: 6 / Whiteboard: No / Price: 9,000 won" },
          { no: 4, label: "④", value: "Seats: 8 / Whiteboard: Yes / Price: 12,000 won" },
          { no: 5, label: "⑤", value: "Seats: 6 / Whiteboard: Yes / Price: 9,500 won" },
        ],
      },
      translation: [
        "W: 민혁아, 우리 조 스터디룸 예약하자.",
        "M: 화면에 방이 다섯 개 남았어.",
        "W: 우리 여섯 명이니까 여섯 명은 들어가야 해.",
        "M: 두 개는 네 명짜리야.",
        "W: 그림 그릴 화이트보드도 필요해.",
        "M: 모든 방에 있는 건 아니야.",
        "W: 그리고 1만 원 아래로 할 수 있을까?",
        "M: 하나는 1만 2천 원이야.",
        "W: 그럼 남는 건 한 개뿐이네.",
        "M: 다른 사람이 잡기 전에 예약할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 사진 전시를 보러 갈 날짜를 고르시오.",
      lines: [
        ["M", "Dayoung, the photo exhibition downtown ends this month."],
        ["W", "When exactly does the last day fall?"],
        ["M", "On the twenty-fifth, so we still have some time."],
        ["W", "How about the eighteenth? That's a Saturday."],
        ["M", "I have a dentist appointment that whole morning."],
        ["W", "Would the afternoon of the same day work?"],
        ["M", "The tickets are sold out after two on weekends."],
        ["W", "Then what about the nineteenth, the day after?"],
        ["M", "The gallery is closed every Sunday for cleaning."],
        ["W", "So the twentieth, Monday, right after school."],
        ["M", "The twentieth works. Let's meet at the entrance."],
      ],
      choices: ["the 18th", "the 19th", "the 20th", "the 25th", "the 15th"],
      answer: 3,
      clue: "So the twentieth, Monday, right after school.",
      explanation:
        "18일은 치과, 19일은 휴관이어서 20일로 정했다. 따라서 답은 ③이다.",
      translation: [
        "M: 다영아, 시내 사진 전시가 이번 달에 끝나.",
        "W: 마지막 날이 정확히 언제야?",
        "M: 25일. 그러니까 아직 시간은 좀 있어.",
        "W: 18일은 어때? 토요일이야.",
        "M: 그날 아침 내내 치과 예약이 있어.",
        "W: 같은 날 오후는 안 돼?",
        "M: 주말에는 2시 넘으면 표가 다 팔려.",
        "W: 그럼 다음 날 19일은?",
        "M: 전시관이 일요일마다 청소로 문을 닫아.",
        "W: 그럼 20일 월요일 방과 후 바로.",
        "M: 20일 괜찮아. 입구에서 만나자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 어제 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Soyul, you weren't in the library yesterday."],
        ["W", "I spent the whole afternoon at the animal shelter."],
        ["M", "Is that the place near the river?"],
        ["W", "Yes, it takes twenty minutes by bike from here."],
        ["M", "What did you do there all afternoon?"],
        ["W", "I washed the food bowls and walked two dogs."],
        ["M", "Weren't the dogs hard to handle?"],
        ["W", "One pulled me the whole way down the path."],
        ["M", "Will you go again this weekend?"],
        ["W", "Every Saturday until the end of the term."],
      ],
      choices: [
        "동물 보호소에서 봉사하기",
        "도서관에서 공부하기",
        "가족과 외식하기",
        "병원에 가기",
        "친구 집에 놀러 가기",
      ],
      answer: 1,
      clue: "I spent the whole afternoon at the animal shelter.",
      explanation:
        "여자는 어제 오후 내내 동물 보호소에서 봉사했다. 따라서 답은 ①이다.",
      translation: [
        "M: 소율아, 어제 도서관에 없더라.",
        "W: 오후 내내 동물 보호소에 있었어.",
        "M: 강 근처에 있는 거기?",
        "W: 응, 여기서 자전거로 20분 걸려.",
        "M: 오후 내내 거기서 뭐 했어?",
        "W: 밥그릇 씻고 개 두 마리 산책시켰어.",
        "M: 개들 다루기 힘들지 않았어?",
        "W: 한 마리가 길 내내 나를 끌고 다녔어.",
        "M: 이번 주말에도 가?",
        "W: 학기 끝날 때까지 매주 토요일에.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, students. This is the lost and found desk. " +
            "A brown wallet was left in the second floor restroom. " +
            "It holds a student card and a bus card inside. " +
            "The owner should come to the office before six today. " +
            "Please describe the wallet before you take it. " +
            "Thank you for listening carefully.",
        ],
      ],
      choices: [
        "행사를 알리려고",
        "분실물을 찾아가라고 하려고",
        "규칙을 안내하려고",
        "봉사자를 모으려고",
        "공사를 알리려고",
      ],
      answer: 2,
      clue: "A brown wallet was left in the second floor restroom.",
      explanation:
        "잃어버린 갈색 지갑의 주인을 찾는 방송이다. 따라서 답은 ②이다.",
      translation: [
        "M: 학생 여러분께 알려 드립니다. 분실물 보관소입니다. 2층 화장실에 갈색 지갑이 놓여 있었습니다. 안에는 학생증과 버스 카드가 들어 있습니다. 주인은 오늘 여섯 시 전에 행정실로 와 주세요. 가져가기 전에 지갑의 생김새를 말해 주세요. 잘 들어 주셔서 고맙습니다.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Hello. Are you here to rent bicycles?"],
        ["M", "Yes, two bicycles for the afternoon."],
        ["W", "One bicycle is seven dollars for three hours."],
        ["M", "Do we have to rent helmets as well?"],
        ["W", "Helmets are free with every bicycle."],
        ["M", "That's good news for us."],
        ["W", "But there is a two dollar cleaning fee in total."],
        ["M", "All right. Two bicycles, then."],
      ],
      choices: ["$14", "$16", "$18", "$12", "$20"],
      answer: 2,
      clue: "One bicycle is seven dollars for three hours.",
      explanation:
        "자전거 두 대 14달러에 청소비 2달러를 더하면 16달러이다. 따라서 답은 ②이다.",
      translation: [
        "W: 안녕하세요. 자전거 빌리러 오셨나요?",
        "M: 네, 오후에 쓸 자전거 두 대요.",
        "W: 자전거 한 대는 세 시간에 7달러입니다.",
        "M: 헬멧도 빌려야 하나요?",
        "W: 헬멧은 자전거마다 무료입니다.",
        "M: 잘됐네요.",
        "W: 다만 청소비가 전체에 2달러 있습니다.",
        "M: 알겠습니다. 그럼 두 대요.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Yeonsu, you always finish your homework on the bus."],
        ["W", "It's forty minutes I would waste otherwise."],
        ["M", "Doesn't the shaking make it hard to write?"],
        ["W", "I only read and mark things on the bus."],
        ["M", "So you save the writing for your desk."],
        ["W", "Exactly. Reading first makes the writing faster."],
        ["M", "I usually just listen to music the whole ride."],
        ["W", "You could read one page and still enjoy it."],
        ["M", "Which part should I start with tomorrow?"],
      ],
      choices: [
        "You should sleep on the bus.",
        "Start with the vocabulary list.",
        "I don't take the bus.",
        "Homework isn't important.",
        "The bus is always late.",
      ],
      answer: 2,
      clue: "Which part should I start with tomorrow?",
      explanation:
        "어디부터 시작하면 좋을지 물었으므로, 단어 목록부터 하라는 ②가 가장 자연스럽다.",
      translation: [
        "M: 연수야, 너는 늘 버스에서 숙제를 끝내더라.",
        "W: 안 그러면 버리는 40분이잖아.",
        "M: 흔들려서 쓰기 어렵지 않아?",
        "W: 버스에서는 읽고 표시만 해.",
        "M: 쓰는 건 책상에서 하는구나.",
        "W: 맞아. 먼저 읽으면 쓰는 게 빨라져.",
        "M: 나는 타는 내내 음악만 들어.",
        "W: 한 쪽만 읽어도 음악은 즐길 수 있어.",
        "M: 내일은 어디부터 시작하면 좋을까?",
        "W: 단어 목록부터 시작해.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 대한 남자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Hyeonu, did you plant those flowers by the gate?"],
        ["M", "My grandmother and I did it last spring."],
        ["W", "They look much taller than they were before."],
        ["M", "We water them every other evening."],
        ["W", "Who takes care of them when you're away?"],
        ["M", "My neighbor keeps an eye on them for us."],
        ["W", "That's a nice thing for a neighbor to do."],
        ["M", "She grows vegetables in her own yard too."],
        ["W", "Could I help you water them sometime?"],
      ],
      choices: [
        "Of course, come by on Friday.",
        "The flowers are gone.",
        "I never water them.",
        "My grandmother moved away.",
        "There is no yard here.",
      ],
      answer: 1,
      clue: "Could I help you water them sometime?",
      explanation:
        "여자가 물 주는 것을 돕겠다고 했으므로, 금요일에 오라는 ①이 가장 자연스럽다.",
      translation: [
        "W: 현우야, 대문 옆 저 꽃들 네가 심었어?",
        "M: 지난봄에 할머니랑 같이 심었어.",
        "W: 예전보다 훨씬 커 보인다.",
        "M: 이틀에 한 번 저녁에 물을 줘.",
        "W: 집 비울 때는 누가 돌봐?",
        "M: 이웃 아주머니가 봐 주셔.",
        "W: 이웃이 그렇게 해 주는 게 참 좋다.",
        "M: 그분도 마당에서 채소를 키우셔.",
        "W: 나도 언제 물 주는 거 도와도 돼?",
        "M: 그럼, 금요일에 들러.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 대한 여자의 응답으로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Nayoon, you look tired again this morning."],
        ["W", "I went to bed after one o'clock last night."],
        ["M", "Were you studying that late?"],
        ["W", "Not really. I kept watching short videos."],
        ["M", "That happens to me on my phone too."],
        ["W", "One video turns into thirty without me noticing."],
        ["M", "I started leaving my phone in the living room."],
        ["W", "Does that actually work for you?"],
        ["M", "I fall asleep almost an hour earlier now."],
      ],
      choices: [
        "I watch videos all night.",
        "Then I'll try that tonight.",
        "My phone is broken.",
        "I sleep at nine every day.",
        "You should watch more videos.",
      ],
      answer: 2,
      clue: "I fall asleep almost an hour earlier now.",
      explanation:
        "휴대폰을 거실에 두니 더 일찍 잔다고 했으므로, 오늘 밤 해 보겠다는 ②가 가장 자연스럽다.",
      translation: [
        "M: 나윤아, 오늘 아침에도 피곤해 보여.",
        "W: 어젯밤에 1시 넘어서 잤어.",
        "M: 그렇게 늦게까지 공부했어?",
        "W: 그건 아니고. 짧은 영상을 계속 봤어.",
        "M: 나도 휴대폰으로 그래.",
        "W: 하나 보다 보면 어느새 서른 개야.",
        "M: 나는 휴대폰을 거실에 두고 자기 시작했어.",
        "W: 그게 정말 효과 있어?",
        "M: 지금은 거의 한 시간 일찍 잠들어.",
        "W: 그럼 오늘 밤에 해 볼게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Minjun이 Serin에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Minjun : ________________",
      lines: [
        [
          "M",
          "Minjun and Serin are practicing for the school band concert. " +
            "Serin plays the same difficult part wrong for the fifth time. " +
            "She puts down her flute and says she wants to quit the band. " +
            "Minjun remembers that she could not play any song last March. " +
            "He wants to remind her how much she has improved since then. " +
            "In this situation, what would Minjun most likely say to Serin?",
        ],
      ],
      choices: [
        "You should choose another instrument.",
        "The concert was cancelled yesterday.",
        "Look how far you've come since March.",
        "I can't play this part either.",
        "Let's stop the practice for good.",
      ],
      answer: 3,
      clue: "He wants to remind her how much she has improved since then.",
      explanation:
        "그동안 얼마나 늘었는지 일깨워 주고 싶어 하므로, 3월 이후 많이 늘었다는 ③이 가장 적절하다.",
      translation: [
        "M: 민준이와 세린이는 학교 밴드 연주회를 연습하고 있습니다. 세린이는 어려운 부분을 다섯 번째로 틀리게 연주합니다. 세린이는 플루트를 내려놓고 밴드를 그만두고 싶다고 말합니다. 민준이는 세린이가 지난 3월에는 어떤 곡도 연주하지 못했던 것을 기억합니다. 민준이는 그때보다 얼마나 늘었는지 일깨워 주고 싶습니다. 이런 상황에서 민준이가 세린이에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
