/** 중3 듣기 28회 — 사람이 직접 쓴 회차 (2026-09-25) */
import type { SetSpec } from "../spec.ts";

export const spec: SetSpec = {
  title: "중3 28회",
  gradeLevel: "middle3",
  speechSpeed: 0.75,
  folder: "중3 듣기",
  questions: [
    {
      order: 1,
      type: "그림 고르기",
      instruction: "대화를 듣고, 여자가 구입할 우산을 고르시오.",
      lines: [
        ["M", "Hello. Are you looking for an umbrella?"],
        ["W", "Yes, one I can keep in my school bag."],
        ["M", "We have long ones and short folding ones."],
        ["W", "A folding one, please. Long ones won't fit in my bag."],
        ["M", "All right. This folding one has a curved hook handle."],
        ["W", "A hook handle takes up too much room when it's folded."],
        ["M", "Then here is a folding one with a straight handle."],
        ["W", "That's the one. I'll take the straight handle umbrella."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "A folding one, please. / I'll take the straight handle umbrella.",
      explanation:
        "여자는 접이식 우산을 원하고, 굽은 손잡이 대신 곧은 손잡이를 골랐다. 따라서 답은 ④이다.",
      figure: {
        kind: "grid5",
        scene:
          "Five closed umbrellas standing upright side by side as five choices, clean black line art on white. " +
          "① a LONG umbrella with a CURVED HOOK handle. " +
          "② a LONG umbrella with a STRAIGHT ROD handle. " +
          "③ a SHORT FOLDING umbrella with a CURVED HOOK handle. " +
          "④ a SHORT FOLDING umbrella with a STRAIGHT ROD handle. " +
          "⑤ a SHORT FOLDING umbrella with a ROUND BALL handle. " +
          "The long umbrellas are clearly about twice as tall as the short folding ones.",
      },
      translation: [
        "M: 안녕하세요. 우산 찾으세요?",
        "W: 네, 책가방에 넣고 다닐 거예요.",
        "M: 긴 우산도 있고 짧은 접이식도 있어요.",
        "W: 접이식으로 주세요. 긴 건 제 가방에 안 들어가요.",
        "M: 알겠습니다. 이 접이식은 손잡이가 굽어 있어요.",
        "W: 굽은 손잡이는 접었을 때 자리를 너무 차지해요.",
        "M: 그럼 손잡이가 곧은 접이식이 여기 있어요.",
        "W: 그거예요. 곧은 손잡이 우산으로 할게요.",
      ].join("\n"),
    },
    {
      order: 2,
      type: "언급하지 않은 것(대화)",
      instruction: "대화를 듣고, 학교 문집 제작에 관해 언급되지 않은 것을 고르시오.",
      lines: [
        ["W", "Minjae, is our class writing for the school anthology?"],
        ["M", "Yes, every student sends in one piece."],
        ["W", "When is the deadline for sending it?"],
        ["M", "The end of this month, by email."],
        ["W", "How long should each piece be?"],
        ["M", "Between two and four pages."],
        ["W", "Can we write in any form we like?"],
        ["M", "Poems, essays, or short stories are all fine."],
        ["W", "Then I'll write a short story about my grandfather."],
      ],
      choices: ["제출 기한", "제출 방법", "글의 길이", "글의 갈래", "인쇄 부수"],
      answer: 5,
      clue: "인쇄 부수는 대화에서 언급되지 않았다.",
      explanation:
        "제출 기한(이달 말), 제출 방법(이메일), 글의 길이(2~4쪽), 갈래(시·수필·단편)는 언급되지만 인쇄 부수는 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 민재야, 우리 반도 학교 문집에 글 써?",
        "M: 응, 학생마다 한 편씩 내.",
        "W: 언제까지 내야 해?",
        "M: 이달 말까지, 이메일로.",
        "W: 한 편에 얼마나 길어야 해?",
        "M: 두 쪽에서 네 쪽 사이.",
        "W: 형식은 마음대로 써도 돼?",
        "M: 시, 수필, 단편 다 괜찮아.",
        "W: 그럼 할아버지에 대한 단편을 써야겠다.",
      ].join("\n"),
    },
    {
      order: 3,
      type: "목적 파악(전화·방문)",
      instruction: "대화를 듣고, 남자가 여자에게 전화한 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Hello, is this the Nuri Bicycle Shop?"],
        ["W", "Yes, it is. How can I help you?"],
        ["M", "I left my bike there for a brake repair."],
        ["W", "Let me check. Under the name Minjae Go?"],
        ["M", "That's right. Is it ready to pick up?"],
        ["W", "Yes, we finished the brakes yesterday afternoon."],
        ["M", "Great. Can I come by after five today?"],
        ["W", "Of course. We're open until eight."],
      ],
      choices: [
        "자전거를 새로 사려고",
        "맡긴 자전거가 다 되었는지 물으려고",
        "수리를 맡기려고",
        "수리비를 물어보려고",
        "가게 위치를 물어보려고",
      ],
      answer: 2,
      clue: "That's right. Is it ready to pick up?",
      explanation:
        "남자는 브레이크 수리를 맡긴 자전거가 다 되었는지 물으려고 전화했다. 따라서 답은 ②이다.",
      translation: [
        "M: 여보세요, 누리 자전거 가게죠?",
        "W: 네, 맞습니다. 무엇을 도와드릴까요?",
        "M: 브레이크 수리 때문에 자전거를 맡겼는데요.",
        "W: 확인해 볼게요. 고민재 님이시죠?",
        "M: 맞아요. 찾아갈 수 있나요?",
        "W: 네, 어제 오후에 브레이크 작업을 끝냈습니다.",
        "M: 잘됐네요. 오늘 5시 넘어서 가도 될까요?",
        "W: 물론이죠. 8시까지 엽니다.",
      ].join("\n"),
    },
    {
      order: 4,
      type: "시각 파악",
      instruction: "대화를 듣고, 두 사람이 만나기로 한 시각을 고르시오.",
      lines: [
        ["W", "Minjae, what time does the library study room open?"],
        ["M", "The doors open at nine on Saturday morning."],
        ["W", "Do we get a seat right away?"],
        ["M", "No, they hand out seat numbers at the desk first."],
        ["W", "How long does that usually take?"],
        ["M", "About thirty minutes when it's busy."],
        ["W", "Then let's meet thirty minutes before the doors open."],
        ["M", "Good. I'll be waiting at the side entrance."],
        ["W", "I'll bring two cups of hot chocolate."],
      ],
      choices: ["8:00 a.m.", "8:30 a.m.", "9:00 a.m.", "9:30 a.m.", "10:00 a.m."],
      answer: 2,
      clue: "Then let's meet thirty minutes before the doors open.",
      explanation:
        "열람실이 9시에 열고 30분 전에 만나기로 했으므로 만나는 시각은 8시 30분이다. 따라서 답은 ②이다.",
      translation: [
        "W: 민재야, 도서관 열람실 몇 시에 열어?",
        "M: 토요일 아침 9시에 문을 열어.",
        "W: 바로 자리를 받을 수 있어?",
        "M: 아니, 먼저 데스크에서 좌석 번호를 나눠 줘.",
        "W: 그건 보통 얼마나 걸려?",
        "M: 붐빌 때는 30분쯤.",
        "W: 그럼 문 열기 30분 전에 만나자.",
        "M: 좋아. 나는 옆문에서 기다릴게.",
        "W: 나는 코코아 두 잔 가져갈게.",
      ].join("\n"),
    },
    {
      order: 5,
      type: "심정 파악",
      instruction: "대화를 듣고, 여자의 심정으로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, you've been quiet since you came back from the office."],
        ["W", "Someone entered my drawing in the contest without asking."],
        ["M", "Your drawing? The one you never finished?"],
        ["W", "Exactly. It was still a rough sketch."],
        ["M", "And now the judges have already seen it?"],
        ["W", "Yes, and they think that's my finished work."],
        ["M", "Who sent it in without telling you?"],
        ["W", "I worked on it for weeks, and now it's out there like that."],
      ],
      choices: ["delighted", "bored", "sleepy", "thankful", "upset"],
      answer: 5,
      clue: "I worked on it for weeks, and now it's out there like that.",
      explanation:
        "몇 주 동안 그린 미완성 그림이 허락 없이 대회에 제출되었다고 했으므로 여자의 심정은 '속상한(upset)'이다. 따라서 답은 ⑤이다.",
      translation: [
        "M: 수민아, 교무실에서 돌아온 뒤로 말이 없네.",
        "W: 누가 내 그림을 나한테 묻지도 않고 대회에 냈어.",
        "M: 네 그림? 아직 안 끝낸 그거?",
        "W: 그래. 아직 밑그림 상태였어.",
        "M: 그럼 심사 위원들이 벌써 봤다는 거야?",
        "W: 응, 그게 내 완성작인 줄 알아.",
        "M: 말도 없이 누가 냈대?",
        "W: 몇 주를 그렸는데 그런 상태로 나가 버렸어.",
      ].join("\n"),
    },
    {
      order: 6,
      type: "그림 상황에 맞는 대화",
      instruction: "다음 그림의 상황에 가장 적절한 대화를 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["W", "How much is a single ticket?"],
        ["M", "Twelve dollars."],
        ["ANN", "Number two."],
        ["W", "Does this seat have a good view?"],
        ["M", "Yes, it's right in the middle."],
        ["ANN", "Number three."],
        ["W", "Excuse me, you're in my seat."],
        ["M", "Oh, sorry. Let me check my ticket."],
        ["ANN", "Number four."],
        ["W", "When does the show start?"],
        ["M", "In about ten minutes."],
        ["ANN", "Number five."],
        ["W", "Is there an intermission?"],
        ["M", "Yes, after the first act."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "Excuse me, you're in my seat.",
      explanation:
        "그림은 공연장 객석에서 한 남자가 앉아 있고, 표를 든 여자가 그 자리를 가리키며 말을 거는 장면이다. 따라서 답은 ③이다.",
      figure: {
        kind: "scene",
        scene:
          "Inside a theater auditorium, clean black line art on a plain white background, no writing anywhere. " +
          "A man sits comfortably in a row of seats looking at the stage. " +
          "A woman stands in the aisle beside him holding up a ticket in one hand and pointing at his seat with the other. " +
          "Rows of empty seats and a stage curtain are drawn simply in the background.",
      },
      translation: [
        "① W: 한 장에 얼마예요? / M: 12달러입니다.",
        "② W: 이 자리는 잘 보이나요? / M: 네, 딱 가운데입니다.",
        "③ W: 저기요, 제 자리에 앉으셨어요. / M: 아, 죄송합니다. 표를 확인해 볼게요.",
        "④ W: 공연이 언제 시작해요? / M: 10분쯤 뒤에요.",
        "⑤ W: 중간 휴식이 있나요? / M: 네, 1막이 끝나고요.",
      ].join("\n"),
    },
    {
      order: 7,
      type: "부탁한 일 파악",
      instruction: "대화를 듣고, 남자가 여자에게 부탁한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, you're in the school band, aren't you?"],
        ["W", "Yes, I play the drums on Tuesdays and Fridays."],
        ["M", "Our class is putting on a short play next week."],
        ["W", "Is it for the school festival?"],
        ["M", "Yes, and we need a drum roll before the ending."],
        ["W", "Just one drum roll, or more than that?"],
        ["M", "Could you play a few beats behind the stage for us?"],
        ["W", "Sure. Tell me when the rehearsal is."],
      ],
      choices: ["무대 뒤에서 북 쳐 주기", "연극에 출연하기", "북 빌려주기", "밴드에 넣어 주기", "무대 준비하기"],
      answer: 1,
      clue: "Could you play a few beats behind the stage for us?",
      explanation:
        "남자는 연극의 마지막 장면 전에 무대 뒤에서 북을 쳐 달라고 부탁했다. 따라서 답은 ①이다.",
      translation: [
        "M: 수민아, 너 학교 밴드지?",
        "W: 응, 화요일이랑 금요일에 드럼 쳐.",
        "M: 우리 반이 다음 주에 짧은 연극을 해.",
        "W: 학교 축제용이야?",
        "M: 응, 그런데 마지막 장면 전에 북소리가 필요해.",
        "W: 한 번만? 아니면 더?",
        "M: 무대 뒤에서 몇 박자만 쳐 줄 수 있어?",
        "W: 그럼. 연습이 언제인지 알려 줘.",
      ].join("\n"),
    },
    {
      order: 8,
      type: "언급하지 않은 것",
      instruction: "다음을 듣고, 학교 체험 학습 신청에 대해 언급되지 않은 것을 고르시오.",
      lines: [
        [
          "W",
          "Hello, students. Applications for the field study open next Monday. " +
            "You may choose one of four places: a farm, a museum, a studio, or a factory. " +
            "Each place takes up to thirty students, first come first served. " +
            "Hand in the form to your homeroom teacher by Thursday. " +
            "Everyone will travel by school bus and return by four. " +
            "Ask your homeroom teacher if anything is unclear.",
        ],
      ],
      choices: ["신청 시작일", "고를 수 있는 곳", "장소별 정원", "제출처", "체험 비용"],
      answer: 5,
      clue: "체험 비용은 방송에서 언급되지 않았다.",
      explanation:
        "신청 시작일(다음 주 월요일), 고를 수 있는 곳(농장·박물관·공방·공장), 장소별 정원(30명), 제출처(담임 선생님)는 언급되지만 비용은 언급되지 않았다. 따라서 답은 ⑤이다.",
      translation: [
        "W: 안녕하세요, 학생 여러분. 체험 학습 신청이 다음 주 월요일에 시작됩니다. 농장, 박물관, 공방, 공장 네 곳 중 하나를 고를 수 있습니다. 각 장소는 선착순 서른 명까지 받습니다. 신청서는 목요일까지 담임 선생님께 내 주세요. 모두 학교 버스로 이동하고 4시까지 돌아옵니다. 궁금한 점은 담임 선생님께 여쭤보세요.",
      ].join("\n"),
    },
    {
      order: 9,
      type: "설명 대상 파악",
      instruction: "다음을 듣고, 무엇에 관한 설명인지 고르시오.",
      lines: [
        [
          "M",
          "This is a job that begins long before the rest of us wake up. " +
            "The person starts mixing flour and water around three in the morning. " +
            "They shape the dough by hand and slide it into a very hot oven. " +
            "By seven o'clock a warm smell fills the whole street. " +
            "Most of them go to bed while the sun is still up.",
        ],
      ],
      choices: ["요리사", "제빵사", "농부", "간호사", "기자"],
      answer: 2,
      clue: "The person starts mixing flour and water around three in the morning.",
      explanation:
        "새벽 3시에 밀가루와 물을 섞어 반죽을 빚어 뜨거운 오븐에 넣는 사람은 제빵사이다. 따라서 답은 ②이다.",
      translation: [
        "M: 이 직업은 우리 대부분이 깨어나기 훨씬 전에 시작합니다. 이 사람은 새벽 3시쯤 밀가루와 물을 섞기 시작합니다. 손으로 반죽을 빚어 아주 뜨거운 오븐에 넣습니다. 7시쯤이면 따뜻한 냄새가 거리를 가득 채웁니다. 대부분 해가 아직 떠 있을 때 잠자리에 듭니다.",
      ].join("\n"),
    },
    {
      order: 10,
      type: "어색한 대화 고르기",
      instruction: "다음을 듣고, 두 사람의 대화가 어색한 것을 고르시오.",
      lines: [
        ["ANN", "Number one."],
        ["M", "What time should we leave for the station?"],
        ["W", "Around half past six."],
        ["ANN", "Number two."],
        ["M", "Would you like me to carry that box?"],
        ["W", "Yes, thank you. It's heavy."],
        ["ANN", "Number three."],
        ["M", "How did you get to school today?"],
        ["W", "My favorite season is spring."],
        ["ANN", "Number four."],
        ["M", "Who is going to write the report?"],
        ["W", "Jiho volunteered yesterday."],
        ["ANN", "Number five."],
        ["M", "Have you eaten lunch yet?"],
        ["W", "Not yet. I'm heading there now."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 3,
      clue: "How did you get to school today?",
      explanation:
        "오늘 학교에 어떻게 왔는지 묻는 말에 좋아하는 계절이 봄이라고 답했으므로 ③의 대화가 어색하다. 따라서 답은 ③이다.",
      translation: [
        "① M: 역에 몇 시에 출발할까? / W: 6시 반쯤.",
        "② M: 그 상자 내가 들어 줄까? / W: 응, 고마워. 무거워.",
        "③ M: 오늘 학교에 어떻게 왔어? / W: 내가 제일 좋아하는 계절은 봄이야.",
        "④ M: 보고서는 누가 써? / W: 어제 지호가 하겠다고 했어.",
        "⑤ M: 점심 먹었어? / W: 아직. 지금 가는 길이야.",
      ].join("\n"),
    },
    {
      order: 11,
      type: "대화 직후 할 일 파악",
      instruction: "대화를 듣고, 남자가 대화 직후에 할 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["W", "Minjae, the class play starts in fifteen minutes."],
        ["M", "I know. Are all the actors in costume already?"],
        ["W", "Yes, and I helped two of them with their makeup."],
        ["M", "Good. Did anyone bring the paper crown for the king?"],
        ["W", "It's still on the art room shelf where we made it."],
        ["M", "The last scene doesn't work without that crown."],
        ["W", "I have to cue the music from the side of the stage."],
        ["M", "Then I'll run to the art room and bring the crown."],
      ],
      choices: ["분장 돕기", "음악 신호 주기", "왕관 가져오기", "의상 갈아입기", "무대 청소하기"],
      answer: 3,
      clue: "Then I'll run to the art room and bring the crown.",
      explanation:
        "종이 왕관이 미술실에 있고 여자는 음악 신호를 줘야 해서, 남자가 미술실로 달려가 왕관을 가져오겠다고 했다. 따라서 답은 ③이다.",
      translation: [
        "W: 민재야, 학급 연극이 15분 뒤에 시작해.",
        "M: 알아. 배우들 옷은 다 갈아입었어?",
        "W: 응, 두 명은 분장도 내가 도와줬어.",
        "M: 잘했다. 왕이 쓸 종이 왕관은 누가 가져왔어?",
        "W: 만들던 미술실 선반에 그대로 있어.",
        "M: 그 왕관이 없으면 마지막 장면이 안 돼.",
        "W: 나는 무대 옆에서 음악 신호를 줘야 해.",
        "M: 그럼 내가 미술실로 달려가서 왕관 가져올게.",
      ].join("\n"),
    },
    {
      order: 12,
      type: "표 보고 고르기",
      instruction: "다음 표를 보면서 대화를 듣고, 여자가 신청할 진로 특강을 고르시오.",
      lines: [
        ["M", "Sumin, which career talk are you signing up for?"],
        ["W", "Let me look at the five of them again."],
        ["M", "Can you attend on a weekday evening?"],
        ["W", "No, I have academy classes every weekday night."],
        ["M", "So it has to be on a Saturday."],
        ["W", "Right. And it should be held online."],
        ["M", "Why online? The rooms are close to school."],
        ["W", "My family moves to another city next month."],
        ["M", "Then only one talk on this list fits you."],
        ["W", "Good. I'll register before the deadline tonight."],
      ],
      choices: ["①", "②", "③", "④", "⑤"],
      answer: 4,
      clue: "No, I have academy classes every weekday night.",
      explanation:
        "토요일에 열리고 온라인으로 진행되는 것을 고른다. 두 조건을 모두 채우는 것은 ④이다.",
      table: {
        rows: [
          { no: 1, label: "①", value: "Day: Tuesday / Format: Online / Topic: Medicine" },
          { no: 2, label: "②", value: "Day: Saturday / Format: In person / Topic: Design" },
          { no: 3, label: "③", value: "Day: Thursday / Format: In person / Topic: Law" },
          { no: 4, label: "④", value: "Day: Saturday / Format: Online / Topic: Engineering" },
          { no: 5, label: "⑤", value: "Day: Wednesday / Format: Online / Topic: Design" },
        ],
      },
      translation: [
        "M: 수민아, 어떤 진로 특강 신청할 거야?",
        "W: 다섯 개 다시 볼게.",
        "M: 평일 저녁에 갈 수 있어?",
        "W: 아니, 평일 밤엔 매일 학원이 있어.",
        "M: 그럼 토요일이어야겠네.",
        "W: 맞아. 그리고 온라인으로 하는 거여야 해.",
        "M: 왜 온라인? 강의실이 학교에서 가까운데.",
        "W: 다음 달에 우리 가족이 다른 도시로 이사 가.",
        "M: 그럼 이 목록에서 맞는 건 하나뿐이야.",
        "W: 좋아. 오늘 밤 마감 전에 등록할게.",
      ].join("\n"),
    },
    {
      order: 13,
      type: "날짜 파악",
      instruction: "대화를 듣고, 두 사람이 문집 원고를 모을 날짜를 고르시오.",
      lines: [
        ["M", "Sumin, when should we collect the anthology drafts?"],
        ["W", "How about October 6th? That's next Monday."],
        ["M", "The third graders have their mock exam that day."],
        ["W", "Then what about October 9th?"],
        ["M", "October 9th is a national holiday."],
        ["W", "Hmm. I'm free on October 16th."],
        ["M", "But the printer needs everything by the 14th."],
        ["W", "Oh, right. Then let's collect them on October 13th."],
        ["M", "October 13th works. That gives the printer one day."],
        ["W", "Perfect. Let's tell everyone tomorrow morning."],
      ],
      choices: ["10월 6일", "10월 9일", "10월 13일", "10월 14일", "10월 16일"],
      answer: 3,
      clue: "Oh, right. Then let's collect them on October 13th.",
      explanation:
        "6일에는 모의고사가, 9일에는 공휴일이 있고 인쇄소는 14일까지 원고를 받아야 한다. 두 사람은 10월 13일에 모으기로 한다. 따라서 답은 ③이다.",
      translation: [
        "M: 수민아, 문집 원고 언제 모을까?",
        "W: 10월 6일 어때? 다음 주 월요일이야.",
        "M: 그날 3학년 모의고사가 있어.",
        "W: 그럼 10월 9일은?",
        "M: 10월 9일은 공휴일이야.",
        "W: 음. 나는 10월 16일이 비어.",
        "M: 그런데 인쇄소가 14일까지 다 받아야 해.",
        "W: 아, 맞다. 그럼 10월 13일에 모으자.",
        "M: 10월 13일 괜찮아. 인쇄소에 하루 여유가 생겨.",
        "W: 좋아. 내일 아침에 다들한테 알리자.",
      ].join("\n"),
    },
    {
      order: 14,
      type: "한 일 파악",
      instruction: "대화를 듣고, 여자가 지난 주말에 한 일로 가장 적절한 것을 고르시오.",
      lines: [
        ["M", "Sumin, why are your arms so sore today?"],
        ["W", "I spent all Sunday at the community center."],
        ["M", "Were you taking a class there?"],
        ["W", "No, we carried donated books up to the third floor."],
        ["M", "Was the elevator out of service again?"],
        ["W", "Yes, so eight of us used the stairs all afternoon."],
        ["M", "How many boxes did you move in total?"],
        ["W", "Forty, and each one held about twenty books."],
      ],
      choices: ["수업 듣기", "책 상자 옮기기", "책 정리하기", "엘리베이터 고치기", "책 기증하기"],
      answer: 2,
      clue: "No, we carried donated books up to the third floor.",
      explanation:
        "여자는 일요일에 주민 센터에서 기증받은 책 상자 마흔 개를 3층까지 계단으로 옮겼다고 했다. 따라서 답은 ②이다.",
      translation: [
        "M: 수민아, 오늘 팔이 왜 이렇게 아파?",
        "W: 일요일 내내 주민 센터에 있었어.",
        "M: 거기서 수업 들었어?",
        "W: 아니, 기증받은 책을 3층까지 날랐어.",
        "M: 엘리베이터가 또 고장 났어?",
        "W: 응, 그래서 여덟 명이 오후 내내 계단을 썼어.",
        "M: 상자를 모두 몇 개 옮겼어?",
        "W: 마흔 개. 한 상자에 책이 스무 권쯤 들었어.",
      ].join("\n"),
    },
    {
      order: 15,
      type: "방송 목적 파악",
      instruction: "다음을 듣고, 방송의 목적으로 가장 적절한 것을 고르시오.",
      lines: [
        [
          "M",
          "Attention, please. This is an announcement from the science department. " +
            "Fine dust levels will be very high tomorrow afternoon. " +
            "All outdoor classes will move indoors for the whole day. " +
            "Please keep the classroom windows closed until further notice. " +
            "Masks will be handed out at the health office in the morning. " +
            "Thank you, and take care of your health.",
        ],
      ],
      choices: [
        "미세먼지로 인한 조치를 알리려고",
        "마스크 구입을 안내하려고",
        "체육 대회를 알리려고",
        "창문 청소를 당부하려고",
        "보건실 이전을 알리려고",
      ],
      answer: 1,
      clue: "All outdoor classes will move indoors for the whole day.",
      explanation:
        "미세먼지가 심해 야외 수업을 실내로 옮기고 창문을 닫으라고 알리는 방송이다. 따라서 답은 ①이다.",
      translation: [
        "M: 안내 말씀 드립니다. 과학부에서 알려 드립니다. 내일 오후 미세먼지 농도가 매우 나쁨입니다. 모든 야외 수업은 하루 종일 실내로 옮깁니다. 다음 안내가 있을 때까지 교실 창문을 닫아 주세요. 마스크는 아침에 보건실에서 나눠 드립니다. 감사합니다. 건강 조심하세요.",
      ].join("\n"),
    },
    {
      order: 16,
      type: "금액 파악",
      instruction: "대화를 듣고, 남자가 지불할 금액을 고르시오.",
      lines: [
        ["W", "Welcome to the print shop. What do you need today?"],
        ["M", "Forty copies of this two-page form, please."],
        ["W", "Printing is fifty cents a page, so that's forty dollars."],
        ["M", "Do you also bind them?"],
        ["W", "Yes, binding is five dollars for the whole batch."],
        ["M", "Then please bind them too."],
        ["W", "All right. School orders get nine dollars off the total."],
        ["M", "That helps a lot. Here you are."],
      ],
      choices: ["$30", "$32", "$34", "$36", "$45"],
      answer: 4,
      clue: "All right. School orders get nine dollars off the total.",
      explanation:
        "두 쪽짜리 40부는 40달러이고 제본 5달러를 더하면 45달러이며, 학교 주문 할인 9달러를 빼면 36달러이다. 따라서 답은 ④이다.",
      translation: [
        "W: 인쇄소에 오신 걸 환영합니다. 오늘은 무엇이 필요하세요?",
        "M: 이 두 쪽짜리 서류를 40부 부탁드려요.",
        "W: 인쇄는 한 쪽에 50센트라서 40달러입니다.",
        "M: 제본도 해 주시나요?",
        "W: 네, 제본은 전체에 5달러입니다.",
        "M: 그럼 제본도 해 주세요.",
        "W: 알겠습니다. 학교 주문은 전체에서 9달러 할인됩니다.",
        "M: 큰 도움이 되네요. 여기 있습니다.",
      ].join("\n"),
    },
    {
      order: 17,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["M", "Sumin, you stopped going to the writing club."],
        ["W", "Everyone there writes so much better than I do."],
        ["M", "Did anyone actually say your writing was weak?"],
        ["W", "No, but I read theirs and mine feels plain."],
        ["M", "You're comparing your first draft to their final one."],
        ["W", "I never thought about it that way."],
        ["M", "They rewrite everything four or five times too."],
        ["W", "So what should I bring to the next meeting?"],
        ["M", "Bring a rough draft and ask them what to cut."],
      ],
      choices: [
        "I'll bring one next Friday.",
        "I never write anything.",
        "My writing is already perfect.",
        "Nobody rewrites their work.",
        "Let's close the writing club.",
      ],
      answer: 1,
      clue: "Bring a rough draft and ask them what to cut.",
      explanation:
        "남자가 초고를 가져가서 무엇을 덜어낼지 물어보라고 했으므로, 다음 금요일에 가져가겠다는 ①이 가장 자연스럽다.",
      translation: [
        "M: 수민아, 글쓰기 동아리 안 나가더라.",
        "W: 거기 사람들은 나보다 글을 훨씬 잘 써.",
        "M: 누가 네 글이 약하다고 말했어?",
        "W: 아니, 그런데 그 사람들 글을 읽으면 내 건 밋밋해.",
        "M: 네 초고를 남의 완성본과 견주는 거야.",
        "W: 그렇게는 생각 못 했어.",
        "M: 그 사람들도 네다섯 번씩 고쳐 써.",
        "W: 그럼 다음 모임에 뭘 가져가야 해?",
        "M: 초고를 가져가서 뭘 덜어내면 좋을지 물어봐.",
        "W: 다음 금요일에 하나 가져갈게.",
      ].join("\n"),
    },
    {
      order: 18,
      type: "응답 고르기",
      instruction: "대화를 듣고, 여자의 마지막 말에 이어질 남자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Man : ________________",
      lines: [
        ["W", "Minjae, your notebook pages are curling at the edges."],
        ["M", "They've looked like that since the rainy week."],
        ["W", "Do you keep the notebook in your bag all the time?"],
        ["M", "Yes, at the very bottom under my water bottle."],
        ["W", "Any drop from the bottle soaks straight into the paper."],
        ["M", "I thought the cap was tight enough."],
        ["W", "Even a little moisture makes paper curl like that."],
        ["M", "Then how should I carry them together?"],
        ["W", "Put the bottle in the side pocket, away from the paper."],
      ],
      choices: [
        "My notebook is brand new.",
        "I never carry a water bottle.",
        "The rain never touched my bag.",
        "I'll put the notebook at the bottom.",
        "I'll move my bottle tomorrow.",
      ],
      answer: 5,
      clue: "Put the bottle in the side pocket, away from the paper.",
      explanation:
        "여자가 물병을 옆주머니로 옮기라고 했으므로, 내일 물병을 옮기겠다는 ⑤가 가장 자연스럽다.",
      translation: [
        "W: 민재야, 네 공책 가장자리가 우글거려.",
        "M: 비 오던 주부터 그래.",
        "W: 공책을 늘 가방에 넣고 다녀?",
        "M: 응, 맨 아래 물병 밑에.",
        "W: 물병에서 한 방울만 새도 바로 종이에 스며들어.",
        "M: 뚜껑이 잘 잠긴 줄 알았어.",
        "W: 조금만 축축해도 종이는 그렇게 우글거려.",
        "M: 그럼 둘을 어떻게 같이 들고 다녀?",
        "W: 물병은 옆주머니에, 종이에서 떨어뜨려 놔.",
        "M: 내일 물병 옮길게.",
      ].join("\n"),
    },
    {
      order: 19,
      type: "응답 고르기",
      instruction: "대화를 듣고, 남자의 마지막 말에 이어질 여자의 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Woman : ________________",
      lines: [
        ["W", "Minjae, our class blood donation drive got only three sign-ups."],
        ["M", "How did you tell people about it?"],
        ["W", "I read the notice aloud in the morning meeting."],
        ["M", "Once, at eight in the morning?"],
        ["W", "Yes, when half the class is still half asleep."],
        ["M", "And nothing written stays behind for them to see."],
        ["W", "Then should I read it again tomorrow?"],
        ["M", "Reading again won't help. Leave something they can sign."],
        ["W", "What exactly do you mean?"],
        ["M", "A sign-up sheet taped to the classroom door all week."],
      ],
      choices: [
        "I'll put one up tomorrow.",
        "Our class has no door.",
        "Everyone already signed up.",
        "I'll read it three more times.",
        "Let's cancel the drive.",
      ],
      answer: 1,
      clue: "A sign-up sheet taped to the classroom door all week.",
      explanation:
        "남자가 교실 문에 신청서를 일주일 내내 붙여 두라고 했으므로, 내일 붙이겠다는 ①이 가장 자연스럽다.",
      translation: [
        "W: 민재야, 우리 반 헌혈 신청이 세 명밖에 안 됐어.",
        "M: 사람들한테 어떻게 알렸는데?",
        "W: 아침 조회 때 안내문을 소리 내서 읽었어.",
        "M: 아침 8시에 한 번?",
        "W: 응, 반 절반은 아직 비몽사몽일 때.",
        "M: 그리고 나중에 볼 수 있게 남는 게 없잖아.",
        "W: 그럼 내일 또 읽을까?",
        "M: 또 읽어도 소용없어. 서명할 수 있는 걸 남겨 둬.",
        "W: 그게 무슨 말이야?",
        "M: 교실 문에 신청서를 일주일 내내 붙여 두는 거.",
        "W: 내일 하나 붙일게.",
      ].join("\n"),
    },
    {
      order: 20,
      type: "상황에 맞는 말",
      instruction: "다음 상황 설명을 듣고, Yunseo가 Taehee에게 할 말로 가장 적절한 것을 고르시오.",
      questionText: "▶ Yunseo : ________________",
      lines: [
        [
          "W",
          "Yunseo and Taehee are leaving the exam room after the final test. " +
            "Taehee has put his pencil case away and is standing up to go. " +
            "Yunseo notices that the back page of his answer sheet is still blank. " +
            "The teacher has not collected the papers from their row yet. " +
            "She wants to tell him before he walks out the door. " +
            "In this situation, what would Yunseo most likely say to Taehee?",
        ],
      ],
      choices: [
        "Let's go to lunch together.",
        "The exam starts in ten minutes.",
        "I'll lend you my pencil.",
        "The back page is still empty.",
        "You should hand in your pencil case.",
      ],
      answer: 4,
      clue: "Yunseo notices that the back page of his answer sheet is still blank.",
      explanation:
        "태희의 답안지 뒷장이 비어 있는데 아직 답안지를 걷지 않았으므로, 그 사실을 알려 주는 ④가 가장 적절하다.",
      translation: [
        "W: 윤서와 태희는 마지막 시험이 끝나고 시험장을 나서고 있습니다. 태희는 필통을 넣고 일어서려 합니다. 윤서는 태희의 답안지 뒷장이 아직 비어 있는 것을 봅니다. 선생님은 아직 그 줄의 답안지를 걷지 않았습니다. 윤서는 태희가 문을 나서기 전에 알려 주고 싶습니다. 이런 상황에서 윤서가 태희에게 할 말로 가장 적절한 것은 무엇일까요?",
      ].join("\n"),
    },
  ],
};
