import type {
  GrammarChapter,
  GrammarPointCode,
  GrammarPointDefinition,
  GrammarPriority,
  GrammarTransformCode,
} from "@/lib/lesson-materials/grammar-choice-v2/types";

type Row = [
  GrammarPointCode,
  GrammarChapter,
  string,
  GrammarPriority,
  string,
  GrammarTransformCode,
  boolean,
];

function row(r: Row): GrammarPointDefinition {
  const [code, chapter, labelKo, priority, hint, transform, whole] = r;
  return {
    code,
    chapter,
    labelKo,
    priority,
    detectionHints: [hint],
    allowedTransforms: [transform],
    forbiddenTransforms: [],
    requiresWholeSentenceContext: whole,
    requiresPassageContext: false,
    maxPerPassage: priority === "BASIC" ? 2 : undefined,
    explanationTemplateId: code,
  };
}

const ROWS: Row[] = [
  ["SENTENCE_SV", "C01", "1형식 문장", "BASIC", "주어+동사만으로 성립", "FORM_SWAP", false],
  ["SENTENCE_SVC", "C01", "2형식 보어", "CORE", "연결동사 뒤 주격보어", "FORM_SWAP", true],
  ["SENTENCE_SVO", "C01", "3형식 목적어", "CORE", "타동사+필수 목적어", "FORM_SWAP", true],
  ["SENTENCE_SVOO", "C01", "4형식 간접·직접목적어", "CORE", "수여동사+두 목적어", "FORM_SWAP", true],
  ["SENTENCE_SVOC", "C01", "5형식 목적격보어", "CORE", "목적어+목적격보어", "FORM_SWAP", true],
  ["VERB_TRANSITIVE_INTRANSITIVE", "C01", "자동사·타동사", "CORE", "필수 목적어 유무", "FORM_SWAP", true],
  ["SUBJECT_COMPLEMENT", "C01", "주격보어", "CORE", "be/become/seem 뒤 보어 형태", "FORM_SWAP", true],
  ["OBJECT_COMPLEMENT_NOUN_ADJ", "C01", "목적격보어 명사·형용사", "CORE", "find/make O + adj/noun", "ADJ_ADV", true],
  ["OBJECT_COMPLEMENT_TO_V", "C01", "목적격보어 to부정사", "CORE", "allow/enable O to V", "NONFINITE_SWAP", true],
  ["OBJECT_COMPLEMENT_BARE_V", "C01", "원형부정사 보어", "CORE", "사역·지각 능동 원형", "NONFINITE_SWAP", true],
  ["OBJECT_COMPLEMENT_VING", "C01", "목적격보어 -ing", "CORE", "O를 능동으로 보충하는 -ing", "NONFINITE_SWAP", true],
  ["OBJECT_COMPLEMENT_PP", "C01", "목적격보어 과거분사", "CORE", "O와 수동 관계의 p.p.", "VOICE_SWAP", true],
  ["CAUSATIVE_ACTIVE", "C01", "사역동사 능동", "CORE", "make/let/have + O + 원형", "NONFINITE_SWAP", true],
  ["CAUSATIVE_PASSIVE", "C01", "사역동사 수동", "MANDATORY", "be made to V", "NONFINITE_SWAP", true],
  ["PERCEPTION_COMPLEMENT", "C01", "지각동사 보어", "CORE", "see/hear O V / V-ing / p.p.", "NONFINITE_SWAP", true],
  ["DUMMY_IT_SUBJECT", "C01", "가주어 it", "CORE", "It is ... that/to", "CLAUSE_MARKER", true],
  ["DUMMY_IT_OBJECT", "C01", "가목적어 it", "CORE", "make/find it adj to/that", "CLAUSE_MARKER", true],
  ["THERE_BE_STRUCTURE", "C01", "there+be", "CORE", "there be + 실제 주어", "NUMBER_SWAP", true],
  ["AGREEMENT_LONG_SUBJECT", "C02", "긴 주어 수일치", "MANDATORY", "주어-동사 사이 긴 수식", "NUMBER_SWAP", true],
  ["AGREEMENT_PREPOSITIONAL_MODIFIER", "C02", "전치사구 수식 수일치", "CORE", "전치사구 뒤 동사", "NUMBER_SWAP", true],
  ["AGREEMENT_RELATIVE_ANTECEDENT", "C02", "관계절 선행사 수일치", "MANDATORY", "관계사 뒤 동사의 수", "NUMBER_SWAP", true],
  ["AGREEMENT_CLAUSE_SUBJECT", "C02", "절 주어 수일치", "MANDATORY", "what/that절 주어", "NUMBER_SWAP", true],
  ["AGREEMENT_GERUND_SUBJECT", "C02", "동명사 주어 수일치", "CORE", "V-ing 주어+단수 동사", "NUMBER_SWAP", true],
  ["AGREEMENT_ONE_OF", "C02", "one of", "CORE", "one of + 복수명사", "NUMBER_SWAP", true],
  ["AGREEMENT_ONE_OF_RELATIVE", "C02", "one of + 관계절", "MANDATORY", "one of N who/that V", "NUMBER_SWAP", true],
  ["AGREEMENT_NUMBER_OF", "C02", "the number of", "CORE", "the number of vs a number of", "NUMBER_SWAP", true],
  ["AGREEMENT_PARTITIVE", "C02", "부분 표현", "CORE", "most/half/none of", "NUMBER_SWAP", true],
  ["AGREEMENT_EACH_EVERY", "C02", "each/every", "CORE", "each/every + 단수", "NUMBER_SWAP", true],
  ["AGREEMENT_CORRELATIVE", "C02", "상관접속사 수일치", "CORE", "not only A but also B", "NUMBER_SWAP", true],
  ["AGREEMENT_THERE_BE", "C02", "there be 수일치", "CORE", "후치 주어와 be", "NUMBER_SWAP", true],
  ["AGREEMENT_INVERSION", "C02", "도치 수일치", "MANDATORY", "도치 뒤 실제 주어", "NUMBER_SWAP", true],
  ["AGREEMENT_DISTANCE", "C02", "먼 주어 수일치", "MANDATORY", "가까운 명사와 실제 주어가 다름", "NUMBER_SWAP", true],
  ["TENSE_EXPLICIT_TIME_MARKER", "C03", "시간 부사 시제", "CORE", "yesterday/already/since 등", "TENSE_SWAP", true],
  ["TENSE_PRESENT_PAST", "C03", "현재·과거", "CORE", "명확한 과거 시점", "TENSE_SWAP", true],
  ["TENSE_PRESENT_PERFECT_PAST", "C03", "현재완료·과거", "CORE", "since/for/already가 제한", "TENSE_SWAP", true],
  ["TENSE_PAST_PERFECT", "C03", "과거완료", "CORE", "과거보다 앞선 사건", "TENSE_SWAP", true],
  ["TENSE_FUTURE_PERFECT", "C03", "미래완료", "CORE", "by next year 등", "TENSE_SWAP", true],
  ["TENSE_PROGRESSIVE", "C03", "진행상", "CORE", "진행 중인 사건", "TENSE_SWAP", true],
  ["TENSE_SEQUENCE", "C03", "시제 일치", "CORE", "주절·종속절 시제", "TENSE_SWAP", true],
  ["TENSE_REPORTED_SPEECH", "C03", "간접화법 시제", "CORE", "said that + 시제 후퇴", "TENSE_SWAP", true],
  ["TENSE_UNIVERSAL_TRUTH", "C03", "불변 진리", "CORE", "현재 사실 유지", "TENSE_SWAP", true],
  ["TENSE_TIME_CONDITION_CLAUSE", "C03", "시간·조건절 현재", "CORE", "when/if절 미래 대신 현재", "TENSE_SWAP", true],
  ["TENSE_SINCE_FOR", "C03", "since/for", "CORE", "since/for + 완료", "TENSE_SWAP", true],
  ["TENSE_BY_THE_TIME", "C03", "by the time", "CORE", "완료 기준 시점", "TENSE_SWAP", true],
  ["VOICE_ACTIVE_PASSIVE", "C04", "능동·수동", "CORE", "행위자/대상 의미역", "VOICE_SWAP", true],
  ["VOICE_PROGRESSIVE_PASSIVE", "C04", "진행 수동", "CORE", "are being p.p.", "VOICE_SWAP", true],
  ["VOICE_PERFECT_PASSIVE", "C04", "완료 수동", "CORE", "have been p.p.", "VOICE_SWAP", true],
  ["VOICE_MODAL_PASSIVE", "C04", "조동사 수동", "CORE", "must be p.p.", "VOICE_SWAP", true],
  ["VOICE_PHRASAL_VERB_PASSIVE", "C04", "구동사 수동", "CORE", "대명사·전치사 위치", "VOICE_SWAP", true],
  ["VOICE_SVOO_PASSIVE", "C04", "4형식 수동", "CORE", "간접/직접목적어 주어화", "VOICE_SWAP", true],
  ["VOICE_SVOC_PASSIVE", "C04", "5형식 수동", "CORE", "목적격보어 유지", "VOICE_SWAP", true],
  ["VOICE_NONFINITE_PASSIVE", "C04", "준동사 수동", "CORE", "to be p.p. / being p.p.", "VOICE_SWAP", true],
  ["VOICE_CAUSATIVE_HAVE_GET", "C04", "have/get 사역 수동", "CORE", "have/get O p.p.", "VOICE_SWAP", true],
  ["VOICE_BE_MADE_TO", "C04", "be made to V", "MANDATORY", "수동 사역 to부정사", "NONFINITE_SWAP", true],
  ["VOICE_BE_SEEN_TO", "C04", "be seen to V", "CORE", "지각동사 수동 to부정사", "NONFINITE_SWAP", true],
  ["MODAL_MEANING", "C05", "조동사 의미", "CORE", "추측·의무·허가 의미 대비", "FORM_SWAP", true],
  ["MODAL_HAVE_PP", "C05", "조동사+have p.p.", "CORE", "must/cannot/should have p.p.", "TENSE_SWAP", true],
  ["MODAL_PAST_INFERENCE", "C05", "과거 추측", "CORE", "must have p.p.", "TENSE_SWAP", true],
  ["MODAL_REGRET_CRITICISM", "C05", "후회·비난", "CORE", "should have p.p.", "TENSE_SWAP", true],
  ["SHOULD_SPECIAL_USE", "C05", "should 특수 용법", "CORE", "if S should / lest", "FORM_SWAP", true],
  ["MANDATIVE_SHOULD", "C05", "당위 should", "CORE", "요구·제안 that S (should) V", "FORM_SWAP", true],
  ["SUBSTITUTE_DO", "C05", "대동사 do", "MANDATORY", "비교·강조의 do", "FORM_SWAP", true],
  ["USED_TO", "C05", "used to", "CORE", "used to V vs be used to V-ing", "NONFINITE_SWAP", true],
  ["WOULD_PAST_HABIT", "C05", "would 과거 습관", "CORE", "would + 원형", "FORM_SWAP", true],
  ["HAD_BETTER", "C05", "had better", "CORE", "had better + 원형", "FORM_SWAP", true],
  ["WOULD_RATHER", "C05", "would rather", "CORE", "would rather V / than", "FORM_SWAP", true],
  ["WOULD_RATHER_SUBJUNCTIVE", "C06", "would rather 가정법", "MANDATORY", "would rather + 별도 주어 + 과거/과거완료", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_SECOND", "C06", "가정법 과거", "MANDATORY", "if+과거, would/could/might+원형", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_THIRD", "C06", "가정법 과거완료", "MANDATORY", "if+had p.p., would have p.p.", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_MIXED", "C06", "혼합 가정법", "MANDATORY", "과거 조건+현재 결과 또는 반대", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_IF_SHOULD", "C06", "if S should", "MANDATORY", "if S should V", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_IF_WERE_TO", "C06", "if S were to", "MANDATORY", "if S were to V", "CONDITIONAL_FORM", true],
  ["CONDITIONAL_INVERTED_WERE", "C06", "Were 도치 가정", "MANDATORY", "Were S ...", "WORD_ORDER", true],
  ["CONDITIONAL_INVERTED_HAD", "C06", "Had 도치 가정", "MANDATORY", "Had S p.p.", "WORD_ORDER", true],
  ["CONDITIONAL_INVERTED_SHOULD", "C06", "Should 도치 가정", "MANDATORY", "Should S V", "WORD_ORDER", true],
  ["WISH_PAST", "C06", "wish 가정법 과거", "MANDATORY", "wish + 과거", "CONDITIONAL_FORM", true],
  ["WISH_PAST_PERFECT", "C06", "wish 가정법 과거완료", "MANDATORY", "wish + had p.p.", "CONDITIONAL_FORM", true],
  ["WISH_WOULD", "C06", "wish 미래 가정", "MANDATORY", "wish + would + 원형", "CONDITIONAL_FORM", true],
  ["AS_IF_PAST", "C06", "as if 과거", "MANDATORY", "as if/though + 과거", "CONDITIONAL_FORM", true],
  ["AS_IF_PAST_PERFECT", "C06", "as if 과거완료", "MANDATORY", "as if + had p.p.", "CONDITIONAL_FORM", true],
  ["WITHOUT_IF_CONDITION", "C06", "if 없는 가정", "MANDATORY", "without/but for", "CONDITIONAL_FORM", true],
  ["IF_ONLY", "C06", "if only", "MANDATORY", "if only + 과거/과거완료", "CONDITIONAL_FORM", true],
  ["OTHERWISE_CONDITIONAL", "C06", "otherwise 가정", "MANDATORY", "otherwise + would/could/might", "CONDITIONAL_FORM", true],
  ["MANDATIVE_SUBJUNCTIVE", "C06", "당위 가정법", "MANDATORY", "insist/suggest that S V", "FORM_SWAP", true],
  ["IT_IS_TIME_SUBJUNCTIVE", "C06", "it is time", "MANDATORY", "it is time S 과거", "CONDITIONAL_FORM", true],
  ["INFINITIVE_NOUN_ROLE", "C07", "명사적 용법 to부정사", "CORE", "주어·목적어 to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_ADJECTIVE_ROLE", "C07", "형용사적 용법", "CORE", "명사 + to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_ADVERB_ROLE", "C07", "부사적 용법", "CORE", "목적·결과 to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_DUMMY_IT", "C07", "가주어+to부정사", "CORE", "It is adj to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_OBJECT_COMPLEMENT", "C07", "to부정사 목적격보어", "CORE", "O to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_LOGICAL_SUBJECT", "C07", "의미상 주어 for/of", "CORE", "for N to V", "NONFINITE_SWAP", true],
  ["INFINITIVE_PERFECT", "C07", "완료 to부정사", "CORE", "to have p.p.", "TENSE_SWAP", true],
  ["INFINITIVE_PASSIVE", "C07", "수동 to부정사", "CORE", "to be p.p.", "VOICE_SWAP", true],
  ["GERUND_SUBJECT", "C07", "동명사 주어", "CORE", "V-ing 주어", "NONFINITE_SWAP", true],
  ["GERUND_COMPLEMENT", "C07", "동명사 보어", "CORE", "보어 V-ing", "NONFINITE_SWAP", true],
  ["GERUND_VERB_OBJECT", "C07", "동사+동명사", "CORE", "enjoy/avoid V-ing", "NONFINITE_SWAP", true],
  ["GERUND_PREPOSITION_OBJECT", "C07", "전치사+동명사", "BASIC", "전치사 뒤 V-ing. to만 보고 고르지 말 것", "NONFINITE_SWAP", true],
  ["GERUND_LOGICAL_SUBJECT", "C07", "동명사 의미상 주어", "CORE", "소유격/목적격 + V-ing", "NONFINITE_SWAP", true],
  ["GERUND_PERFECT", "C07", "완료 동명사", "CORE", "having p.p.", "TENSE_SWAP", true],
  ["GERUND_PASSIVE", "C07", "수동 동명사", "CORE", "being p.p.", "VOICE_SWAP", true],
  ["VERB_COMPLEMENT_MEANING_CHANGE", "C07", "to V / V-ing 의미 변화", "CORE", "remember/stop/try + to/V-ing", "NONFINITE_SWAP", true],
  ["NONFINITE_MEMORY_COMPLEMENT", "C08", "remember/forget/regret 보충어", "MANDATORY", "문맥이 과거 경험과 앞으로의 의무를 잠글 때만", "NONFINITE_SWAP", true],
  ["NONFINITE_STOP_COMPLEMENT", "C08", "stop 보충어", "MANDATORY", "중단과 목적을 위한 멈춤이 잠길 때만", "NONFINITE_SWAP", true],
  ["NONFINITE_TRY_COMPLEMENT", "C08", "try 보충어", "MANDATORY", "노력과 시험이 잠길 때만", "NONFINITE_SWAP", true],
  ["NONFINITE_MEAN_COMPLEMENT", "C08", "mean 보충어", "MANDATORY", "의도와 수반이 잠길 때만", "NONFINITE_SWAP", true],
  ["NONFINITE_GO_ON_COMPLEMENT", "C08", "go on 보충어", "MANDATORY", "계속과 다음 단계가 잠길 때만", "NONFINITE_SWAP", true],
  ["GERUND_FIXED_CONSTRUCTION", "C07", "고정 동명사", "CORE", "spend time / look forward to / worth", "NONFINITE_SWAP", true],
  ["PARTICIPLE_NOUN_MODIFIER", "C08", "분사 명사 수식", "CORE", "명사 전후 분사", "VOICE_SWAP", true],
  ["PARTICIPLE_ACTIVE_PASSIVE", "C08", "분사 능동·수동", "CORE", "의미상 주어와 능동/수동", "VOICE_SWAP", true],
  ["PARTICIPLE_EMOTION", "C08", "감정분사", "CORE", "감정 원인 -ing / 느끼는 -ed", "VOICE_SWAP", true],
  ["PARTICIPLE_SUBJECT_COMPLEMENT", "C08", "주격보어 분사", "CORE", "seem/remain + 분사", "VOICE_SWAP", true],
  ["PARTICIPLE_OBJECT_COMPLEMENT", "C08", "목적격보어 분사", "CORE", "find/hear O + 분사", "VOICE_SWAP", true],
  ["PARTICIPLE_REDUCED_RELATIVE", "C08", "축약 관계절", "CORE", "관계사+be 생략 분사", "VOICE_SWAP", true],
  ["PARTICIPIAL_CLAUSE_ACTIVE", "C08", "능동 분사구문", "MANDATORY", "V-ing, 주절", "VOICE_SWAP", true],
  ["PARTICIPIAL_CLAUSE_PASSIVE", "C08", "수동 분사구문", "MANDATORY", "p.p., 주절", "VOICE_SWAP", true],
  ["PARTICIPIAL_CLAUSE_PERFECT", "C08", "완료 분사구문", "MANDATORY", "Having p.p.", "TENSE_SWAP", true],
  ["PARTICIPIAL_CLAUSE_NEGATIVE", "C08", "부정 분사구문", "MANDATORY", "Not V-ing", "FORM_SWAP", true],
  ["PARTICIPIAL_CLAUSE_WITH_CONJUNCTION", "C08", "접속사+분사구문", "MANDATORY", "when/while/if + 분사", "VOICE_SWAP", true],
  ["ABSOLUTE_PARTICIPLE", "C08", "독립분사구문", "MANDATORY", "명사+분사, 주절", "VOICE_SWAP", true],
  ["WITH_OBJECT_PARTICIPLE", "C08", "with+O+분사", "CORE", "with O V-ing/p.p.", "VOICE_SWAP", true],
  ["DANGLING_PARTICIPLE", "C08", "현수 분사", "CORE", "주어 불일치면 출제 금지", "VOICE_SWAP", true],
  ["NOUN_CLAUSE_THAT", "C09", "that 명사절", "CORE", "완전한 절을 이끄는 that", "CLAUSE_MARKER", true],
  ["NOUN_CLAUSE_WHETHER_IF", "C09", "whether/if 명사절", "CORE", "whether + 완전절", "CLAUSE_MARKER", true],
  ["NOUN_CLAUSE_WH_WORD", "C09", "의문사 명사절", "CORE", "what/how 완전절", "WORD_ORDER", true],
  ["NOUN_CLAUSE_DECLARATIVE_ORDER", "C09", "진술 명사절 어순", "CORE", "be동사 뒤 생략 that + 주어+동사", "WORD_ORDER", true],
  ["INDIRECT_QUESTION_ORDER", "C09", "간접의문문 어순", "MANDATORY", "의문사+주어+동사", "WORD_ORDER", true],
  ["APPOSITIVE_THAT", "C09", "동격 that", "CORE", "명사 + that절", "CLAUSE_MARKER", true],
  ["REPEATED_THAT", "C09", "반복 that", "CORE", "that A and that B", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_TIME", "C09", "시간 부사절", "CORE", "when/while/before", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_CONDITION", "C09", "조건 부사절", "CORE", "if/unless 중 구조가 다른 경우만", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_REASON", "C09", "이유 부사절", "CORE", "because + 절", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_CONCESSION", "C09", "양보 부사절", "CORE", "although + 절", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_PURPOSE", "C09", "목적 부사절", "CORE", "so that", "CLAUSE_MARKER", true],
  ["ADVERB_CLAUSE_RESULT", "C09", "결과 부사절", "CORE", "so ... that", "CLAUSE_MARKER", true],
  ["CONJUNCTION_PREPOSITION_CONTRAST", "C09", "접속사·전치사 대비", "CORE", "because/because of, although/despite", "CLAUSE_MARKER", true],
  ["CORRELATIVE_CONJUNCTION", "C09", "상관접속사", "CORE", "both A and B", "PARALLEL_FORM", true],
  ["RELATIVE_SUBJECT", "C10", "주격 관계대명사", "CORE", "관계절 주어 자리", "RELATIVE_CHOICE", true],
  ["RELATIVE_OBJECT", "C10", "목적격 관계대명사", "CORE", "관계절 목적어 자리", "RELATIVE_CHOICE", true],
  ["RELATIVE_POSSESSIVE", "C10", "소유격 관계대명사", "CORE", "whose", "RELATIVE_CHOICE", true],
  ["RELATIVE_WHO_WHOM", "C10", "who/whom", "CORE", "사람 선행사 격", "RELATIVE_CHOICE", true],
  ["RELATIVE_WHAT", "C10", "관계대명사 what", "CORE", "선행사 포함 what", "RELATIVE_CHOICE", true],
  ["RELATIVE_PREPOSITION_WHICH", "C10", "전치사+which", "CORE", "전치사 뒤 which", "RELATIVE_CHOICE", true],
  ["RELATIVE_PREPOSITION_WHOM", "C10", "전치사+whom", "CORE", "전치사 뒤 whom", "RELATIVE_CHOICE", true],
  ["RELATIVE_ADVERB_WHERE", "C10", "관계부사 where", "CORE", "장소 선행사", "RELATIVE_CHOICE", true],
  ["RELATIVE_ADVERB_WHEN", "C10", "관계부사 when", "CORE", "시간 선행사", "RELATIVE_CHOICE", true],
  ["RELATIVE_ADVERB_WHY", "C10", "관계부사 why", "CORE", "reason why", "RELATIVE_CHOICE", true],
  ["RELATIVE_ADVERB_HOW", "C10", "관계부사 how", "CORE", "방법 선행사 또는 선행사 없는 how", "RELATIVE_CHOICE", true],
  ["RELATIVE_RESTRICTIVE", "C10", "제한적 용법", "CORE", "콤마 없는 관계절. which/that 둘 다 가능하면 금지", "RELATIVE_CHOICE", true],
  ["RELATIVE_NONRESTRICTIVE", "C10", "계속적 용법", "MANDATORY", "콤마 뒤 which, that 불가", "RELATIVE_CHOICE", true],
  ["RELATIVE_OMISSION", "C10", "관계사 생략", "CORE", "목적격 생략 대비", "RELATIVE_CHOICE", true],
  ["RELATIVE_COMPOUND", "C10", "복합관계사", "MANDATORY", "whoever/whatever/no matter", "RELATIVE_CHOICE", true],
  ["RELATIVE_ANTECEDENT_DISTANCE", "C10", "먼 선행사", "MANDATORY", "선행사와 관계사 사이 수식", "RELATIVE_CHOICE", true],
  ["RELATIVE_AGREEMENT", "C10", "관계절 수일치", "MANDATORY", "관계사 동사와 선행사", "NUMBER_SWAP", true],
  ["PARALLEL_AND_OR_BUT", "C11", "등위 병렬", "CORE", "and/or/but 뒤 형태", "PARALLEL_FORM", true],
  ["PARALLEL_VERBS", "C11", "동사 병렬", "CORE", "떨어진 동사 형태", "PARALLEL_FORM", true],
  ["PARALLEL_NOUN_PHRASES", "C11", "명사구 병렬", "CORE", "and로 묶인 명사구", "PARALLEL_FORM", true],
  ["PARALLEL_ADJECTIVES", "C11", "형용사 병렬", "CORE", "형용사 and 형용사", "PARALLEL_FORM", true],
  ["PARALLEL_NONFINITE", "C11", "준동사 병렬", "CORE", "to/V-ing 병렬", "PARALLEL_FORM", true],
  ["PARALLEL_CLAUSES", "C11", "절 병렬", "MANDATORY", "that절 and that절", "PARALLEL_FORM", true],
  ["PARALLEL_SHARED_AUXILIARY", "C11", "조동사 공유 병렬", "MANDATORY", "will be and turn out", "PARALLEL_FORM", true],
  ["PARALLEL_SHARED_TO", "C11", "to 공유 병렬", "CORE", "to A and B", "PARALLEL_FORM", true],
  ["PARALLEL_REPEATED_THAT", "C11", "반복 that 병렬", "MANDATORY", "that A and that B", "CLAUSE_MARKER", true],
  ["CORRELATIVE_BOTH_AND", "C11", "both A and B", "CORE", "both와 and 짝", "PARALLEL_FORM", true],
  ["CORRELATIVE_EITHER_OR", "C11", "either A or B", "CORE", "either/or", "PARALLEL_FORM", true],
  ["CORRELATIVE_NEITHER_NOR", "C11", "neither A nor B", "CORE", "neither/nor", "PARALLEL_FORM", true],
  ["CORRELATIVE_NOT_ONLY_BUT_ALSO", "C11", "not only A but also B", "MANDATORY", "상관접속사 병렬", "PARALLEL_FORM", true],
  ["FROM_A_TO_B", "C11", "from A to B", "CORE", "from/to 병렬", "PARALLEL_FORM", true],
  ["COMPARISON_PARALLEL", "C11", "비교 병렬", "CORE", "비교 대상 형태", "PARALLEL_FORM", true],
  ["PRONOUN_SUBJECT_OBJECT_CASE", "C12", "대명사 격", "BASIC", "주격/목적격", "CASE_SWAP", true],
  ["PRONOUN_REFLEXIVE", "C12", "재귀대명사", "CORE", "주어와 일치하는 -self", "CASE_SWAP", true],
  ["PRONOUN_ANTECEDENT", "C12", "대명사 선행사", "CORE", "수·성 일치. 불명확하면 금지", "CASE_SWAP", true],
  ["DUMMY_REFERENTIAL_IT", "C12", "it 지시", "CORE", "가주어와 지시 it", "CASE_SWAP", true],
  ["ONE_ONES", "C12", "one/ones", "BASIC", "대명사 one", "NUMBER_SWAP", false],
  ["ANOTHER_OTHER_THE_OTHER", "C12", "another/other", "CORE", "another vs other", "FORM_SWAP", true],
  ["EACH_ALL_BOTH", "C12", "each/all/both", "BASIC", "수량 한정", "FORM_SWAP", true],
  ["EITHER_NEITHER", "C12", "either/neither", "CORE", "둘 중 하나", "FORM_SWAP", true],
  ["COUNTABLE_UNCOUNTABLE", "C12", "가산·불가산", "BASIC", "much/many", "NUMBER_SWAP", false],
  ["SINGULAR_PLURAL_NOUN", "C12", "명사 단복수", "BASIC", "many kinds. 같은 subtype 1회", "NUMBER_SWAP", false],
  ["ARTICLE", "C12", "관사", "BASIC", "a/an/the. 구조가 확정될 때만", "FORM_SWAP", false],
  ["PREPOSITION_COLLOCATION", "C12", "필수 전치사", "CORE", "동사·형용사가 요구하는 전치사", "FORM_SWAP", true],
  ["PREPOSITION_INSTEAD_OF", "C12", "instead of", "CORE", "명사 앞 복합전치사 instead of", "FORM_SWAP", true],
  ["POSSESSIVE", "C12", "소유격", "BASIC", "소유격 vs 목적격", "CASE_SWAP", false],
  ["ITS_IT_IS", "C12", "its/it's", "CORE", "소유격 its vs it is", "FORM_SWAP", false],
  ["QUANTIFIER", "C12", "수량사", "BASIC", "much/many/few/little", "NUMBER_SWAP", false],
  ["ADJECTIVE_NOUN_MODIFIER", "C13", "명사 수식 형용사", "BASIC", "형용사+명사", "ADJ_ADV", false],
  ["ADJECTIVE_SUBJECT_COMPLEMENT", "C13", "주격보어 형용사", "CORE", "be/become + 형용사", "ADJ_ADV", true],
  ["ADJECTIVE_OBJECT_COMPLEMENT", "C13", "목적격보어 형용사", "CORE", "keep/find O + 형용사", "ADJ_ADV", true],
  ["ADVERB_VERB_MODIFIER", "C13", "동사 수식 부사", "BASIC", "동사+부사", "ADJ_ADV", true],
  ["ADVERB_ADJECTIVE_MODIFIER", "C13", "형용사 수식 부사", "BASIC", "부사+형용사", "ADJ_ADV", true],
  ["ADVERB_SENTENCE_MODIFIER", "C13", "문장 부사", "CORE", "문장 전체 수식", "ADJ_ADV", true],
  ["LINKING_VERB_COMPLEMENT", "C13", "연결동사 보어", "CORE", "become/feel + 형용사", "ADJ_ADV", true],
  ["CONFUSABLE_ADVERB", "C13", "혼동 부사", "CORE", "hard/hardly", "ADJ_ADV", true],
  ["SO_SUCH", "C13", "so/such", "CORE", "so adj / such a", "ADJ_ADV", true],
  ["TOO_ENOUGH", "C13", "too/enough", "CORE", "too adj to / adj enough to", "FORM_SWAP", true],
  ["COMPARATIVE", "C13", "비교급", "CORE", "than 비교", "FORM_SWAP", true],
  ["SUPERLATIVE", "C13", "최상급", "CORE", "the + 최상급", "FORM_SWAP", true],
  ["AS_AS", "C13", "as ... as", "CORE", "원급 비교", "FORM_SWAP", true],
  ["THE_COMPARATIVE", "C13", "the 비교급", "CORE", "the + 비교급, the + 비교급", "FORM_SWAP", true],
  ["COMPARATIVE_AND_COMPARATIVE", "C13", "비교급 and 비교급", "CORE", "비교급 반복", "FORM_SWAP", true],
  ["MULTIPLICATIVE_COMPARISON", "C13", "배수 비교", "CORE", "times as ... as", "FORM_SWAP", true],
  ["ONE_OF_SUPERLATIVE", "C13", "one of 최상급", "CORE", "one of the + 최상급 + 복수", "FORM_SWAP", true],
  ["COMPARISON_TARGET", "C13", "비교 대상", "CORE", "비교 대상 불명확하면 금지", "FORM_SWAP", true],
  ["INVERSION_NEGATIVE", "C14", "부정어 도치", "MANDATORY", "Never/Not until + 조동사+주어", "WORD_ORDER", true],
  ["INVERSION_ONLY", "C14", "Only 도치", "MANDATORY", "Only then + 조동사+주어", "WORD_ORDER", true],
  ["INVERSION_PLACE_DIRECTION", "C14", "장소 도치", "MANDATORY", "장소 부사구 선행 도치", "WORD_ORDER", true],
  ["INVERSION_COMPLEMENT", "C14", "보어 도치", "MANDATORY", "보어 선행", "WORD_ORDER", true],
  ["INVERSION_SO_NEITHER", "C14", "so/neither 도치", "MANDATORY", "so/neither + 조동사+주어", "WORD_ORDER", true],
  ["CLEFT_IT_THAT", "C14", "강조구문", "MANDATORY", "It is/was ... that", "CLAUSE_MARKER", true],
  ["EMPHATIC_DO", "C14", "do 강조", "MANDATORY", "do/does/did + 원형", "FORM_SWAP", true],
  ["PSEUDO_CLEFT_ALL", "C14", "의사분열문 all", "CORE", "All (that) S have to do + be + 동사원형", "FORM_SWAP", true],
  ["ELLIPSIS_COMMON_ELEMENT", "C14", "공통 요소 생략", "MANDATORY", "반복 요소 생략", "FORM_SWAP", true],
  ["ELLIPSIS_SUBSTITUTION", "C14", "대동사 생략", "MANDATORY", "than S does", "FORM_SWAP", true],
  ["APPOSITION", "C14", "동격", "CORE", "명사, 명사", "CLAUSE_MARKER", true],
  ["INSERTION", "C14", "삽입", "CORE", "삽입절", "WORD_ORDER", true],
  ["NEGATION_SCOPE", "C14", "부정 범위", "CORE", "not ... all/every", "FORM_SWAP", true],
  ["PARTIAL_NEGATION", "C14", "부분 부정", "CORE", "not all / not every", "FORM_SWAP", true],
  ["DOUBLE_NEGATION", "C14", "이중 부정", "CORE", "부정+without/hardly", "FORM_SWAP", true],
  ["IT_TAKES_TO", "C14", "it takes to", "CORE", "It takes N to V", "NONFINITE_SWAP", true],
  ["TOO_TO", "C14", "too ... to", "CORE", "too adj to V", "FORM_SWAP", true],
  ["ENOUGH_TO", "C14", "enough to", "CORE", "adj enough to V", "FORM_SWAP", true],
  ["RESULT_RELATION_TOO_TO", "C11", "too ... to 결과 관계", "CORE", "too ... to ↔ so ... that ... cannot", "CLAUSE_MARKER", true],
  ["RESULT_RELATION_ENOUGH_TO", "C11", "enough to 결과 관계", "CORE", "enough to ↔ so ... that ... can", "CLAUSE_MARKER", true],
  ["NONFINITE_VERBAL_PROPERTY", "C08", "준동사 동사적 성질", "CORE", "준동사는 절의 시제를 맡지 않는다", "NONFINITE_SWAP", true],
  ["NONFINITE_LOGICAL_SUBJECT_ANALYSIS", "C08", "준동사 의미상 주어 분석", "CORE", "for/of 분석만", "NONFINITE_SWAP", true],
  ["OBJECT_COMPLEMENT_TO_V_ANALYSIS", "C08", "목적격보어 to V 분석", "CORE", "allow O to V 분석만", "NONFINITE_SWAP", true],
  ["OBJECT_COMPLEMENT_BARE_ANALYSIS", "C08", "사역·지각 원형 분석", "CORE", "help/let/make O V 분석만", "NONFINITE_SWAP", true],
  ["GERUND_SUBJECT_ANALYSIS", "C08", "동명사 주어 분석", "CORE", "동명사구 주어 분석만", "NONFINITE_SWAP", true],
  ["GERUND_PREP_OBJECT_ANALYSIS", "C08", "전치사+동명사 분석", "CORE", "전치사 목적어 분석만", "NONFINITE_SWAP", true],
  ["GERUND_SUBJECT_AGREEMENT_ANALYSIS", "C08", "동명사 주어 수일치 분석", "CORE", "동명사구 주어 수 분석만", "NUMBER_SWAP", true],
  ["PREP_MODIFIER_AGREEMENT_ANALYSIS", "C08", "전치사구 수식 수일치 분석", "CORE", "핵어 수일치 분석만", "NUMBER_SWAP", true],
  ["SO_AS_TO", "C14", "so as to", "CORE", "so as to V", "NONFINITE_SWAP", true],
];

const CH01_REFERENCE = new Set<GrammarPointCode>([
  "SENTENCE_SV",
  "SENTENCE_SVC",
  "SENTENCE_SVO",
  "SENTENCE_SVOO",
  "SENTENCE_SVOC",
  "VERB_TRANSITIVE_INTRANSITIVE",
  "SUBJECT_COMPLEMENT",
  "OBJECT_COMPLEMENT_NOUN_ADJ",
  "OBJECT_COMPLEMENT_TO_V",
  "OBJECT_COMPLEMENT_BARE_V",
  "OBJECT_COMPLEMENT_VING",
  "OBJECT_COMPLEMENT_PP",
  "CAUSATIVE_ACTIVE",
  "PERCEPTION_COMPLEMENT",
]);

const CH02_REFERENCE = new Set<GrammarPointCode>([
  "TENSE_EXPLICIT_TIME_MARKER",
  "TENSE_PRESENT_PAST",
  "TENSE_PRESENT_PERFECT_PAST",
  "TENSE_PAST_PERFECT",
  "TENSE_FUTURE_PERFECT",
  "TENSE_PROGRESSIVE",
  "TENSE_SEQUENCE",
  "TENSE_UNIVERSAL_TRUTH",
  "TENSE_SINCE_FOR",
  "TENSE_BY_THE_TIME",
]);

const CH04_REFERENCE = new Set<GrammarPointCode>([
  "MODAL_MEANING",
  "MODAL_HAVE_PP",
  "MODAL_PAST_INFERENCE",
  "MODAL_REGRET_CRITICISM",
  "MANDATIVE_SHOULD",
  "SUBSTITUTE_DO",
  "USED_TO",
  "WOULD_PAST_HABIT",
  "HAD_BETTER",
  "WOULD_RATHER",
]);

const CH05_REFERENCE = new Set<GrammarPointCode>([
  "CONDITIONAL_SECOND",
  "CONDITIONAL_THIRD",
  "CONDITIONAL_MIXED",
  "CONDITIONAL_IF_SHOULD",
  "CONDITIONAL_IF_WERE_TO",
  "CONDITIONAL_INVERTED_WERE",
  "CONDITIONAL_INVERTED_HAD",
  "CONDITIONAL_INVERTED_SHOULD",
  "WISH_PAST",
  "WISH_PAST_PERFECT",
  "WISH_WOULD",
  "AS_IF_PAST",
  "AS_IF_PAST_PERFECT",
  "WITHOUT_IF_CONDITION",
  "IF_ONLY",
  "OTHERWISE_CONDITIONAL",
  "IT_IS_TIME_SUBJUNCTIVE",
  "WOULD_RATHER_SUBJUNCTIVE",
]);

const CH09_REFERENCE = new Set<GrammarPointCode>([
  "INFINITIVE_OBJECT_COMPLEMENT",
  "INFINITIVE_PERFECT",
  "INFINITIVE_PASSIVE",
  "GERUND_PERFECT",
  "GERUND_PASSIVE",
  "NONFINITE_MEMORY_COMPLEMENT",
  "NONFINITE_STOP_COMPLEMENT",
  "NONFINITE_TRY_COMPLEMENT",
  "NONFINITE_MEAN_COMPLEMENT",
  "NONFINITE_GO_ON_COMPLEMENT",
  "NONFINITE_VERBAL_PROPERTY",
  "NONFINITE_LOGICAL_SUBJECT_ANALYSIS",
  "OBJECT_COMPLEMENT_TO_V_ANALYSIS",
  "OBJECT_COMPLEMENT_BARE_ANALYSIS",
  "GERUND_SUBJECT_ANALYSIS",
  "GERUND_PREP_OBJECT_ANALYSIS",
  "GERUND_SUBJECT_AGREEMENT_ANALYSIS",
  "PREP_MODIFIER_AGREEMENT_ANALYSIS",
]);

const CH12_REFERENCE = new Set<GrammarPointCode>([
  "COMPARATIVE",
  "SUPERLATIVE",
  "AS_AS",
  "THE_COMPARATIVE",
  "COMPARATIVE_AND_COMPARATIVE",
  "MULTIPLICATIVE_COMPARISON",
  "ONE_OF_SUPERLATIVE",
  "COMPARISON_TARGET",
]);

const CH13_REFERENCE = new Set<GrammarPointCode>([
  "COUNTABLE_UNCOUNTABLE",
  "SINGULAR_PLURAL_NOUN",
  "ARTICLE",
  "QUANTIFIER",
  "PREPOSITION_COLLOCATION",
  "PREPOSITION_INSTEAD_OF",
  "PRONOUN_SUBJECT_OBJECT_CASE",
  "PRONOUN_REFLEXIVE",
  "PRONOUN_ANTECEDENT",
  "DUMMY_REFERENTIAL_IT",
  "ONE_ONES",
  "ANOTHER_OTHER_THE_OTHER",
  "EACH_ALL_BOTH",
  "EITHER_NEITHER",
  "POSSESSIVE",
  "AGREEMENT_PREPOSITIONAL_MODIFIER",
  "AGREEMENT_ONE_OF",
  "AGREEMENT_NUMBER_OF",
  "AGREEMENT_PARTITIVE",
  "AGREEMENT_EACH_EVERY",
  "AGREEMENT_DISTANCE",
  "AGREEMENT_CORRELATIVE",
  "ADJECTIVE_NOUN_MODIFIER",
  "ADJECTIVE_SUBJECT_COMPLEMENT",
  "ADJECTIVE_OBJECT_COMPLEMENT",
  "ADVERB_VERB_MODIFIER",
  "ADVERB_ADJECTIVE_MODIFIER",
  "ADVERB_SENTENCE_MODIFIER",
  "LINKING_VERB_COMPLEMENT",
  "CONFUSABLE_ADVERB",
  "TOO_ENOUGH",
]);

const CH07_REFERENCE = new Set<GrammarPointCode>([
  "GERUND_SUBJECT",
  "GERUND_COMPLEMENT",
  "GERUND_VERB_OBJECT",
  "GERUND_PREPOSITION_OBJECT",
  "GERUND_LOGICAL_SUBJECT",
  "GERUND_FIXED_CONSTRUCTION",
  "AGREEMENT_GERUND_SUBJECT",
  "VERB_COMPLEMENT_MEANING_CHANGE",
]);

const CH06_REFERENCE = new Set<GrammarPointCode>([
  "INFINITIVE_NOUN_ROLE",
  "INFINITIVE_ADJECTIVE_ROLE",
  "INFINITIVE_ADVERB_ROLE",
  "INFINITIVE_DUMMY_IT",
  "INFINITIVE_LOGICAL_SUBJECT",
  "DUMMY_IT_OBJECT",
  "TOO_TO",
  "ENOUGH_TO",
  "SO_AS_TO",
]);

const CH08_REFERENCE = new Set<GrammarPointCode>([
  "PARTICIPLE_NOUN_MODIFIER",
  "PARTICIPLE_ACTIVE_PASSIVE",
  "PARTICIPLE_EMOTION",
  "PARTICIPLE_SUBJECT_COMPLEMENT",
  "PARTICIPLE_OBJECT_COMPLEMENT",
  "PARTICIPLE_REDUCED_RELATIVE",
  "PARTICIPIAL_CLAUSE_ACTIVE",
  "PARTICIPIAL_CLAUSE_PASSIVE",
  "PARTICIPIAL_CLAUSE_PERFECT",
  "PARTICIPIAL_CLAUSE_NEGATIVE",
  "PARTICIPIAL_CLAUSE_WITH_CONJUNCTION",
  "ABSOLUTE_PARTICIPLE",
  "WITH_OBJECT_PARTICIPLE",
  "DANGLING_PARTICIPLE",
]);

const CH10_REFERENCE = new Set<GrammarPointCode>([
  "PARALLEL_AND_OR_BUT",
  "CORRELATIVE_BOTH_AND",
  "CORRELATIVE_EITHER_OR",
  "CORRELATIVE_NEITHER_NOR",
  "CORRELATIVE_NOT_ONLY_BUT_ALSO",
  "CORRELATIVE_CONJUNCTION",
  "NOUN_CLAUSE_THAT",
  "NOUN_CLAUSE_WHETHER_IF",
  "NOUN_CLAUSE_WH_WORD",
  "NOUN_CLAUSE_DECLARATIVE_ORDER",
  "INDIRECT_QUESTION_ORDER",
  "TENSE_REPORTED_SPEECH",
  "ADVERB_CLAUSE_TIME",
  "ADVERB_CLAUSE_CONDITION",
  "TENSE_TIME_CONDITION_CLAUSE",
  "ADVERB_CLAUSE_REASON",
  "ADVERB_CLAUSE_CONCESSION",
  "CONJUNCTION_PREPOSITION_CONTRAST",
  "ADVERB_CLAUSE_PURPOSE",
  "ADVERB_CLAUSE_RESULT",
  "SO_SUCH",
  "RESULT_RELATION_TOO_TO",
  "RESULT_RELATION_ENOUGH_TO",
]);

const CH03_REFERENCE = new Set<GrammarPointCode>([
  "VOICE_ACTIVE_PASSIVE",
  "VOICE_PROGRESSIVE_PASSIVE",
  "VOICE_PERFECT_PASSIVE",
  "VOICE_MODAL_PASSIVE",
  "VOICE_PHRASAL_VERB_PASSIVE",
  "VOICE_SVOO_PASSIVE",
  "VOICE_SVOC_PASSIVE",
  "VOICE_NONFINITE_PASSIVE",
  "VOICE_CAUSATIVE_HAVE_GET",
  "VOICE_BE_MADE_TO",
  "VOICE_BE_SEEN_TO",
]);

const CH14_REFERENCE = new Set<GrammarPointCode>([
  "EMPHATIC_DO",
  "PSEUDO_CLEFT_ALL",
  "CLEFT_IT_THAT",
  "INVERSION_NEGATIVE",
  "INVERSION_ONLY",
  "INVERSION_PLACE_DIRECTION",
  "INVERSION_COMPLEMENT",
  "INVERSION_SO_NEITHER",
  "ELLIPSIS_COMMON_ELEMENT",
  "ELLIPSIS_SUBSTITUTION",
  "APPOSITION",
  "APPOSITIVE_THAT",
  "INSERTION",
  "NEGATION_SCOPE",
  "PARTIAL_NEGATION",
  "DOUBLE_NEGATION",
]);

const CH11_REFERENCE = new Set<GrammarPointCode>([
  "RELATIVE_SUBJECT",
  "RELATIVE_OBJECT",
  "RELATIVE_POSSESSIVE",
  "RELATIVE_WHO_WHOM",
  "RELATIVE_WHAT",
  "RELATIVE_PREPOSITION_WHICH",
  "RELATIVE_PREPOSITION_WHOM",
  "RELATIVE_ADVERB_WHERE",
  "RELATIVE_ADVERB_WHEN",
  "RELATIVE_ADVERB_WHY",
  "RELATIVE_ADVERB_HOW",
  "RELATIVE_RESTRICTIVE",
  "RELATIVE_NONRESTRICTIVE",
  "RELATIVE_OMISSION",
  "RELATIVE_COMPOUND",
  "RELATIVE_ANTECEDENT_DISTANCE",
  "RELATIVE_AGREEMENT",
]);

export const GRAMMAR_ONTOLOGY: GrammarPointDefinition[] = ROWS.map((item) => {
  const point = row(item);
  if (CH05_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH05" as const };
  if (CH04_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH04" as const };
  if (CH11_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH11" as const };
  if (CH10_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH10" as const };
  if (CH08_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH08" as const };
  if (CH07_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH07" as const };
  if (CH09_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH09" as const };
  if (CH14_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH14" as const };
  if (CH03_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH03" as const };
  if (CH01_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH01" as const };
  if (CH02_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH02" as const };
  if (CH06_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH06" as const };
  if (CH12_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH12" as const };
  if (CH13_REFERENCE.has(point.code)) return { ...point, referenceChapter: "CH13" as const };
  return point;
});

const BY_CODE = new Map(GRAMMAR_ONTOLOGY.map((p) => [p.code, p]));

export function ontologyPoint(code: string): GrammarPointDefinition | undefined {
  return BY_CODE.get(code as GrammarPointCode);
}

export function ontologyCounts() {
  const chapters = new Set(GRAMMAR_ONTOLOGY.map((p) => p.chapter));
  return {
    chapterCount: chapters.size,
    pointCount: GRAMMAR_ONTOLOGY.length,
    mandatoryCount: GRAMMAR_ONTOLOGY.filter((p) => p.priority === "MANDATORY")
      .length,
    coreCount: GRAMMAR_ONTOLOGY.filter((p) => p.priority === "CORE").length,
    basicCount: GRAMMAR_ONTOLOGY.filter((p) => p.priority === "BASIC").length,
  };
}

export function compactOntologyForPrompt() {
  return GRAMMAR_ONTOLOGY.map((p) => ({
    code: p.code,
    label: p.labelKo,
    priority: p.priority,
    detectionHint: p.detectionHints[0] ?? "",
    allowedTransforms: p.allowedTransforms,
  }));
}

export function isKnownPointCode(code: string): code is GrammarPointCode {
  return code === "UNMAPPED_HIGH_VALUE_POINT" || BY_CODE.has(code as GrammarPointCode);
}

export const FORBIDDEN_PATTERNS = [
  "mechanical to + V / V-ing",
  "modal + base-form inflection only",
  "short adjacent subject-verb agreement",
  "imperative Think/Thinks",
  "if/unless meaning preference",
  "which/that both grammatical in restrictive relatives",
  "all we have to do is think/to think",
];
